### ISSUE TITLE
No json data from any APIs

### ISSUE THREAD

**Issue by phanirithvij** [n8n-io/n8n#1]
I keep getting this `Entries exist but they do not contain any JSON data.` after every workflow execution.

e.g. starring my github repo like in the example youtube video.

But a Command Execution node works
e.g.
`node -e "console.log('success');"`
gives out a JSON
```json
[
{
"exitCode": 0,
"stderr": "",
"stdout": "success"
}
]
```

Am I doing something wrong with the access token generation on the github?
I gave all the permissions before generating the token and I still am not able to receive any JSON data.

**Comment by phanirithvij** [comment]
Working one

![image](https://user-images.githubusercontent.com/29627898/62423229-4ea4e300-b6dc-11e9-817d-6cc9ef24c754.png)

Github is not working

![image](https://user-images.githubusercontent.com/29627898/62423253-785e0a00-b6dc-11e9-92d8-f25e2e3e37db.png)

**Comment by phanirithvij** [comment]
And this is how my auth looks (I hid the access token)

![image](https://user-images.githubusercontent.com/29627898/62423282-b6f3c480-b6dc-11e9-8412-b9fc4eb4f78a.png)

**Comment by janober** [comment]
Hello!

I just tested and for me it seems to work fine. 

So are you running it locally? Because then you have an http://localhost URL and Github can not create a webhook to such a URL (as it would be their own localhost). You need a "proper" domain to create a webhook. n8n has a special tunnel service which makes that very easy. You simply have to start n8n like this: `n8n start --tunnel`

It will then create a unique URL on our tunnel-service for you and redirect that requests to your local server.

If that is not the problem I pasted full workflow at the end of the message. You can simply copy it, then click in the n8n-editor window and paste. It will then create the whole workflow. You then just have to change the credentials on the nodes and the Github repository.

Hope that helps. If not simply get back to me!


```
{
  "nodes": [
    {
      "parameters": {
        "owner": "n8n-io",
        "repository": "n8n",
        "events": [
          "star"
        ]
      },
      "name": "Github Trigger",
      "type": "n8n-nodes-base.githubTrigger",
      "typeVersion": 1,
      "position": [
        210,
        350
      ],
      "credentials": {
        "githubApi": "janober"
      }
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{$node[\"Github Trigger\"].data[\"body\"][\"action\"]}}",
              "value2": "created"
            }
          ]
        }
      },
      "name": "IF",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        400,
        350
      ]
    },
    {
      "parameters": {
        "channel": "#test",
        "attachments": [
          {
            "image_url": "={{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"avatar_url\"]}}",
            "title_link": "={{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"html_url\"]}}",
            "title": "=Got new star from: {{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"login\"]}}",
            "text": "=The project has now: {{$node[\"Github Trigger\"].data[\"body\"][\"repository\"][\"stargazers_count\"]}} Stars",
            "color": "#88FF00"
          }
        ],
        "otherOptions": {}
      },
      "name": "Slack - Add",
      "type": "n8n-nodes-base.slack",
      "typeVersion": 1,
      "position": [
        600,
        250
      ],
      "credentials": {
        "slackApi": "n8n"
      }
    },
    {
      "parameters": {
        "channel": "#test",
        "attachments": [
          {
            "image_url": "={{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"avatar_url\"]}}",
            "title_link": "={{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"html_url\"]}}",
            "title": "=Star got removed by: {{$node[\"Github Trigger\"].data[\"body\"][\"sender\"][\"login\"]}}",
            "text": "=The project has now: {{$node[\"Github Trigger\"].data[\"body\"][\"repository\"][\"stargazers_count\"]}} Stars",
            "color": "#ff0000"
          }
        ],
        "otherOptions": {}
      },
      "name": "Slack - Remove",
      "type": "n8n-nodes-base.slack",
      "typeVersion": 1,
      "position": [
        600,
        450
      ],
      "credentials": {
        "slackApi": "n8n"
      }
    }
  ],
  "connections": {
    "Github Trigger": {
      "main": [
        [
          {
            "node": "IF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF": {
      "main": [
        [
          {
            "node": "Slack - Add",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Slack - Remove",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by janober** [comment]
Hi!
Does it work now or do you still have issues?

**Comment by phanirithvij** [comment]
Oh sorry I forgot to let you know.
Starting a tunnel didn't work for me either.

The workflow is getting executed after some random time independent of
whether I star the target repo or not. And it says it's got no data.

I'll try to record or send a reproducible demo.

And I'm unable to connect anything to the start node.

**Comment by janober** [comment]
Hello!
Very strange. Did you check if it creates the webhook on Github. You can see it under this URL (you just have to replace it with the user and repository name you want to watch):
https://github.com/<user>/<repository>/settings/hooks

If you start it manually it should create a webhook there and after it got "stared" or "unstared" it should get removed again automatically.

Ah yes it has an automatic timeout build in to not wait "indefinitely". If the test-webhook does not get called within 120 seconds it will stop and resolve.

What do you mean you can not connect anything to the start node? You mean as an input? If so, that is OK as the start node does not have an input and so nothing can be connected to it. It has only an output (all trigger nodes currently have). If you want that a node can receive input data from two different nodes (for example the "Start-Node" and the "Webhook-Node") you would simply use both of them as the input of this node.

**Comment by phanirithvij** [comment]
Thanks for your immediate response. I'll be back just a bit later as
something came up. 😅.

**Comment by phanirithvij** [comment]
It is creating a webhook url but the response seems to be a 404. Here's a screenshot

![image](https://user-images.githubusercontent.com/29627898/62535926-467aae00-b86a-11e9-9e57-e939c598bab6.png)

**Comment by janober** [comment]
So what you do is?
 1. Press "Execute"
 2. Go directly to GitHub and star the repository.

And it does then not display any data?

**Comment by phanirithvij** [comment]
Yes, I execute the Github node. And star the repo like in the YouTube
video. Is that wrong?

**Comment by janober** [comment]
Hm no sounds all correct to me. How do you start n8n? Via npm or docker?

**Comment by janober** [comment]
Btw. did release a new version which fixed a bug that it took much longer than needed for the Editor-UI to get data. Do not think that causes your problem but who knows.

Do regular webhooks work for you? So if you for example create a new workflow with that node in it:
```
{
  "nodes": [
    {
      "parameters": {
        "path": "test"
      },
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        593,
        314
      ]
    }
  ],
  "connections": {}
}
``` 

You then press "Execute Workflow" and then visit directly this page with your browser (replace <WORKFLOW_ID> with the id your workflow got saved as):
```
http://localhost:5678/webhook-test/<WORKFLOW_ID>/webhook/test
``` 

Does it then resolve correctly and display you data on the webhook node?

**Comment by phanirithvij** [comment]
This one works.
> ```
> {
>   "nodes": [
>     {
>       "parameters": {
>         "path": "test"
>       },
>       "name": "Webhook",
>       "type": "n8n-nodes-base.webhook",
>       "typeVersion": 1,
>       "position": [
>         593,
>         314
>       ]
>     }
>   ],
>   "connections": {}
> }
> ```

The URL gave me a data

```json
{"message":"Workflow got started."}
```

> Does it then resolve correctly and display your data on the webhook node?
Then it resolved after some time and I received the data 

```json
{
  "host": "localhost:5678",
  "connection": "keep-alive",
  "upgrade-insecure-requests": "1",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "en-US,en;q=0.9",
  "cookie": "wcsid=ylUAvqLrAsS5HJ3W3m39N0JABkr36o7C; hblid=KbnytDPkeEmyDkPS3m39N0JAA6T6oBr3; _okdetect=%7B%22token%22%3A%2215610205567100%22%2C%22proto%22%3A%22http%3A%22%2C%22host%22%3A%22localhost%3A4040%22%7D; olfsk=olfsk3027408582743829; _okbk=cd4%3Dtrue%2Cvi5%3D0%2Cvi4%3D1561020556869%2Cvi3%3Dactive%2Cvi2%3Dfalse%2Cvi1%3Dfalse%2Ccd8%3Dchat%2Ccd6%3D0%2Ccd5%3Daway%2Ccd3%3Dfalse%2Ccd2%3D0%2Ccd1%3D0%2C; _ok=1700-237-10-3483; _oklv=1561021588077%2CylUAvqLrAsS5HJ3W3m39N0JABkr36o7C; username-localhost-8888=\"2|1:0|10:1565090142|23:username-localhost-8888|44:ZDMwMTI5NDFmMGVkNGQxZjlkYzQ2YTM4ZGUwMDJkZTc=|6a8bf9d70c674587a929cb5638019b436f990599172d1a7c42c2e927baa3998c\"; _xsrf=2|832e7633|8f4242fb9c6ee055293f9b5d2572f454|1565090142"
}

```

**Comment by phanirithvij** [comment]
When I tried `n8n start --tunnel`

And ran a simple github star workflow

I can see some webhooks in my project settings but they are all getting `404` from the ngnix server i.e. the tunnel I'm guessing.

![image](https://user-images.githubusercontent.com/29627898/62575310-1a861980-b8b8-11e9-8a9b-bf5b64c4eb0c.png)

**Comment by phanirithvij** [comment]
I start n8n from npm

**Comment by phanirithvij** [comment]
A post request is being sent to the `tunnel` server when I star or unstar the repo but the tunnel server is responding with 404.

**Comment by janober** [comment]
hm then it is even more confusing. When the webhook node works, the Github node should theoretically also work as they use to 100% the same code.

The nodes you did send look like totally right (even though they do not work for me as I can not set a hook on a repository I am not part of).

When you only click "Execute Workflow" and then go on the Github webhook page does it then display that webhook as OK with a green checkmark like this?
![Screenshot from 2019-08-06 22-55-58](https://user-images.githubusercontent.com/6249596/62576577-71322a00-b89d-11e9-8937-ca9e64366af6.png)

**Comment by phanirithvij** [comment]
No, it is a red warning icon.
I'm guessing the problem is with your cloud provider? Or it might be it's not available for me or my region specifically.

**Comment by janober** [comment]
Hm ok then it is really the inital request already. So probably really nothing at all gets through for some reason and it has really something to do with the tunnel.

Can you please start again with n8n with the tunnel, then make sure that you reload the browser with the Editor-UI. If you go then in the Webhook-Node and click on the orange "Webhook URLs" to display them you should see the Webhook-URLs. Then select "Test" and copy the URL by clicking on it (it should contain "webhook-test"). If you now start again the workflow and call the copied URL which goes now through the tunnel does it then also resolve and work like it does when you use the localhost URL?

**Comment by janober** [comment]
And just to be very sure that you have not have for some reason a very strict firewall in place. Can you please deactivate it and try then again the Github Trigger Node.

**Comment by phanirithvij** [comment]
It's not because of the firewall.
I just disabled it entirely and I still get no data.

**Comment by phanirithvij** [comment]
I re-enabled my firewall.

And now I get this

```
There was a problem running the workflow:
Github error response [422]: Validation Failed
```

**Comment by janober** [comment]
I am very sorry but I am not able to help you.

I now did extra set up everything totally new on a clean Windows (as I use Ubuntu) with new Github API token and hoped so to be able to reproduce your problem but "sadly" everything worked perfectly. Have not the slightest idea why it does not work for you. Hope you can figure out what is different for you.

For your (and the most people in general) it makes the most sense anyway to have it running on a server and not locally. So I advice you to get it up and running on a Linux-Server as the problem seems to be related to your computer somehow. I am sure there it will then work just fine.

**Comment by phanirithvij** [comment]
Cool, thanks for your quick responses. I will try it out on a Linux machine
and try to isolate the problem.

**Comment by janober** [comment]
Would be great, especially if it turns out to be a problem which maybe more people will have. Anyway the offer I did send you via email with the free hosted instance still stands.

**Comment by mockuser404** [comment]
I tried it on Linux but it's even weirder as it immediately gets executed.

So I've created a mock user on github.

@mockuser404
password: mockpassword404

And a test repository: https://github.com/mockuser404/test

I've generated an access token `31402d1eb32a1a397bc49406878468e5108be256`

Those are the credentials.

And this is the workflow JSON file.
[github.json.zip](https://github.com/n8n-io/n8n/files/3477090/github.json.zip)

Let me know whether it's working or not.

**Comment by mockuser404** [comment]
Btw I'm @phanirithvij

**Comment by mockuser404** [comment]
Leave it.
It's working on Linux.
I see you're connecting to some specific port but not simple http, https requests.

Like `hooks.n8n.cloud:37085`
I had my proxy settings configured to prevent torrents i.e it blocks all ports except the standard ones that is what caused the problem.

I reset my proxy settings and it works now.

It's a problem on my side.
Sorry for wasting your time.

**Comment by phanirithvij** [comment]
Great project btw.

**Comment by janober** [comment]
Ah just saw your messages now. Really great to hear that this mystery is now solved.

**Comment by phanirithvij** [comment]
And how can I change the n8n configuration settings?
Like e.g. You've disabled `Execute command` node on your hosted server.
Is it possible to do it locally?

**Comment by janober** [comment]
Everything that can be configured can be found here:
https://github.com/n8n-io/n8n/blob/master/packages/cli/config/index.ts

To not load some node types the "NODES_EXCLUDE" environment variable can be set.

I for example set this one:
```
export NODES_EXCLUDE="[\"n8n-nodes-base.executeCommand\", \"n8n-nodes-base.readBinaryFile\", \"n8n-nodes-base.readBinaryFiles\", \"n8n-nodes-base.writeBinaryFile\"]"
```

**Comment by iosifnicolae2** [comment]
If you want to find the URL where the Webhook is accessible, please toggle the "Webhook URL" section:
![image](https://user-images.githubusercontent.com/7108834/76745288-4e92b880-677e-11ea-9632-731ac894c5e8.png)

**Comment by Rudra-ravi** [comment]
Test comment from MCP tool.
