### ISSUE TITLE
[Question] ClickUp Time Tracking 2.0

### ISSUE THREAD

**Issue by evomation** [n8n-io/n8n#1000]
Hello,

I wonder If there are any plans for implementing ClickUp Time Tracking 2.0? If not, I would like to contribute and make n8n even better than it already is.

**Comment by RicardoE105** [comment]
Hello @evomation. 

There is no plan on our side of adding time tracking 2.0, but a contribution would be fantastic. Let me know if you have any questions. I'm happy to help. Glad you like n8n.

**Comment by evomation** [comment]
Hi @RicardoE105,

thanks for your answer. Good to know, I'm on it ;-)

**Comment by evomation** [comment]
HI @RicardoE105,

I implemented the the feature and created a pull request: #1007 
Let me know if I missed something and if there are improvements.

**Comment by RicardoE105** [comment]
@evomation added some improvements to what you did. We will let you know when is released. Thanks very much for your contributions.

**Comment by janober** [comment]
Got released with n8n@0.87.0
