### ISSUE TITLE
Contributing documentation is out of date

### ISSUE THREAD

**Issue by cgsmith** [n8n-io/n8n#10002]
### Bug Description

The contribution markdown contains the wrong version of Node referenced.

![image](https://github.com/n8n-io/n8n/assets/570018/691843bf-354c-49cc-adce-90f8823f788f)

### To Reproduce

1. Download n8n repo
2. Install Node 18.10
3. Receive error on `pnpm install` command

### Expected behavior

`pnpm install` should proceed correctly.

### Operating System

Pop!_OS 22.04 LTS

### n8n Version

1.50.0 (master)

### Node.js Version

18.10.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by cgsmith** [comment]
So my PR #10003 might not be right. When trying `pnpm start` after `pnpm build` on node 18.12 it fails saying n8n requires v18.17.0

I think the versions should be bumped to at least 18.17 as a requirement if that is the case.

**Comment by Joffcom** [comment]
Great spot, as our minimum is 18.17.0 we should probably use that in the docs.

Let me check with the team to confirm.

**Comment by cgsmith** [comment]
Updates?

**Comment by Joffcom** [comment]
Hey @cgsmith,

I will check on this, I am surprsied it is not done already.

**Comment by cgsmith** [comment]
Thanks @Joffcom 

`/gif waiting`

**Comment by janober** [comment]
Fix got released with [`n8n@1.66.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.66.0)
