### ISSUE TITLE
Notion one-way Relation property not found by n8n

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#10024]
### Bug Description

If a Notion Relation property is one-way, it is not found in Notion nodes (filters, add page, update page).
Once you add a backward relation, the property appears.

The bad news are that two-way relations are sometimes must be avoided as it may result in thousands of items slowing down DB.

Screenshots
This is the Notion part
![image](https://github.com/user-attachments/assets/a58858e1-260b-4daa-b86e-926e20d990ce)

This is the n8n part, using Notion filters. The Account property is visible ONLY if I enable the Show on toggle above.
![image](https://github.com/user-attachments/assets/1a26d9a7-e47f-4608-9cb5-2342362427ec)

Forum link: https://community.n8n.io/t/notion-one-way-relation-property-not-found-by-n8n/49856

### To Reproduce

1. Create 2 DBs with a 1-way relation property
2. Try to filter by/modify this property in n8n - there's nothing
3. Edit this property to the 2-way one
4. Go to n8n and make sure the property is available

### Expected behavior

The property must be available no matter it is 1-way or 2-way. It's not Notion limitation, this can be done via a separate HTTP-request

### Operating System

Ubuntu 22

### n8n Version

1.47.3

### Node.js Version

docker compose

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @artemdzyuba,

To save on duplication I am going to close this and we can pick this up from the forum post that you have created.
