### ISSUE TITLE
Google Drive - Bug in Search Operations when called by Execute Workflow

### ISSUE THREAD

**Issue by davidmoneil** [n8n-io/n8n#10041]
### Bug Description

Also, reference question here: https://community.n8n.io/t/google-drive-execute-workflow-trigger-test-shows-different-results-vs-triggered/49322

When I test the workflow from the editor, it returns the expected results, which are 47 documents and PDFs.

When I run this from another workflow, showing it here, I can see that it is returning JPEG, PNG, and JavaScript files. I have Return All enabled, and I only see 11 items.

What is the error message (if any)?
I’m not getting any error messages from Google Drive.

Please share your workflow.

💡 Double-click a node to see its settings, or paste this workflow's code into n8n to import it
Share the output returned by the last node.
The output is coming in the correct format; I’m just getting unexpected results.

**Information on your n8n setup**
n8n version: 1.47.1 -, and have upgraded to 1.49.0  Docker Image: latest
Database (default: SQLite): SQLite
n8n EXECUTIONS_PROCESS setting (default: own, main): Execution order: v1 - not sure on the Executions_process
Running n8n via (Docker, npm, n8n cloud, desktop app): Docker n8n single instance
Operating system:. Running on Synology NAS

### To Reproduce

1. Setup Trigger workflow to send : {"query": "some text"} to an Execute Workflow Trigger 
2. Create Workflow 2 to capture the Execute Workflow Trigger, and connect Google Drive Search, with Resource: File/Folder, Operation: Search, Search Method: Search File / Folder Name*. 
3. In workflow 2, open the Execute workflow trigger and pin { "query" :" some text" } for testing. 
4. Run workflow 1 and results 
5. Run workflow 2 manually when in edit mode 
6. Results are different - ensure that "some text" is the same in both locations. 

* Note that advanced Search returns an error when testing. 

### Expected behavior

I expect that the search results, when compared, would be 100% the same or close.  

The results I'm getting from workflow 1 are not even close to what I'm expecting. 

### Operating System

Docker 

### n8n Version

1.49.0

### Node.js Version

its docker latest on 1.49.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @davidmoneil,

As this is already opened as an issue on the forum we will pick this up there to save on duplicate posts. I will see you on the other side shortly.
