### ISSUE TITLE
HighLevel not populating contact custom fields

### ISSUE THREAD

**Issue by dsfdev** [n8n-io/n8n#10058]
### Bug Description

As title - custom fields dropdown does not populate custom fields anymore when it used to. 

Shows errors - "Error fetching options from HighLevel" as placeholder in field and warning triangle error of "Issues: There was a problem loading the parameter options from server: "The resource you are requesting could not be found"

![CleanShot 2024-07-15 at 12 30 57@2x](https://github.com/user-attachments/assets/ce45e295-60a1-4c7e-bd85-49a34021a41f)

Several reports in community 

- https://community.n8n.io/t/custom-fields-update-in-highlevel-using-highlevel-node-or-http-request-put-not-working/48904
- https://community.n8n.io/t/highlevel-custom-fields-not-working/49181
- https://community.n8n.io/t/highlevel-node/49182/

### To Reproduce

Use HighLevel node Update contact or Create/Update contact and try to get a custom field inside HighLevel node. 

### Expected behavior

Dropdown should show a list of custom fields available to the contact in that location

### Operating System

Ubuntu/Docker

### n8n Version

1.50.0

### Node.js Version

20.15.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dsfdev,

Thanks for reporting, As you have noticed though we are already aware of this and have an engineering ticket open to resolve this. To avoid having more duplicate tickets / issues opened I am going to close this one and we will pick it up on the community issues.
