### ISSUE TITLE
LiteLLM support

### ISSUE THREAD

**Issue by rcarmo** [n8n-io/n8n#10065]
### Bug Description

I would like to have the option to specify an OpenAI-compatible proxy (as discussed in #9862) but with sane [LiteLLM](https://litellm.vercel.app/docs) defaults, since it can proxy to multiple providers. This is not just about endpoints or filtering the model list, since the [Swagger schema](https://litellm-api.up.railway.app) is pretty comprehensive and supports chat, embeddings, etc.

### To Reproduce

Try to create a custom OpenAI model with a custom endpoint.

### Expected behavior

I should either be able to have easy access to the OpenAI endpoint and remove model filters, or have a separate LiteLLM option that could later be extended to use the rest of the API. 

### Operating System

Linux

### n8n Version

1.49.0

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @rcarmo 

This sounds like a duplicate of the bug you have already found, I am good to get this one marked as closed for now.

If this is a feature request for a specific litellm node the feature request category on the support forum would be the best place.

**Comment by CallumJHays** [comment]
This appears to be supported now (v1.113.3). Just use an OpenAI model, create new credential and in the OpenAI account settings you can set the LiteLLM baseURL and api key.

**Comment by zooneon** [comment]
+1
