### ISSUE TITLE
HelpScout Node - Create a new Thread

### ISSUE THREAD

**Issue by DavMoo** [n8n-io/n8n#10079]
### Bug Description

For the following HelpScout Node the "Type" field options seems to have an issue.

HelpScout Node:
* Resource: Thread
* Operation: Create
* Conversation ID: "Set correct ID"
* Type: Chat (other options: Customer, Note, Phone, Reply)

This will create a new "Chat" entry in HelpScout.

While changing the "Type" field in the n8n Node to e.g. "Note" it remains creating a "Chat" entry.
I expect a "Note" to be created when selecting "Note" in the Type field of the n8n Node.

### To Reproduce

HelpScout Node:
* Resource: Thread
* Operation: Create
* Conversation ID: "Set correct ID"
* Type: Note

-> This will create a new "Chat" entry in HelpScout not a "Note" entry.

### Expected behavior

I expect the type field to take effect while changing to different options than chat. Seems like its not correctly wired up.

### Operating System

MacOS 14.5

### n8n Version

1.49.0

### Node.js Version

not known

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @DavMoo,

Thanks for the report, I have put in a quick PR which should fix this. Once reviewed it will be merged and available in a future release.

**Comment by janober** [comment]
Fix got released with [`n8n@1.52.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.52.0)
