### ISSUE TITLE
Webhook gives me 504 Gateway Time-out

### ISSUE THREAD

**Issue by radu-bitspot** [n8n-io/n8n#10089]
### Bug Description

Hello,
I try to post to a webhook from an aplication that i have... but the flow in n8n it takes like 2 minutes to complete,
i tried increase this in the variables 

      - EXECUTIONS_TIMEOUT_MAX=7200
      - N8N_NODE_FUNCTION_TIMEOUT=1200000
      - WEBHOOK_TTL=600
It still gives me 504 gateway Time-out

i will give some screenshots of the config 

### To Reproduce

You need to post to a webhook with more than 2 minutes workflow..

![image](https://github.com/user-attachments/assets/512904ba-33dc-4b0e-a795-2ca5fcc3c0e9)
and the respond to webhook 
![image](https://github.com/user-attachments/assets/342f1a58-40b3-4fd4-b006-89ff371ee765)

![image](https://github.com/user-attachments/assets/3ee83278-b52e-4b11-81f9-c1a9108929b5)

### Expected behavior

To post and to get the response of the webhook in the aplication

### Operating System

Ubuntu 22.04

### n8n Version

1.50.1

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
> You need to post to a webhook with more than 2 minutes workflow..

This is the issue. Webhooks aren't usually used for such long wait times.

But if you need to do things this way, you need to change the timeouts in your reverse-proxy, because it's very likely that is where the 504 is coming from.

**Comment by radu-bitspot** [comment]
> > You need to post to a webhook with more than 2 minutes workflow..
> 
> This is the issue. Webhooks aren't usually used for such long wait times.
> 
> But if you need to do things this way, you need to change the timeouts in your reverse-proxy, because it's very likely that is where the 504 is coming from.

Thank you, Very good answer, my problem solved
