### ISSUE TITLE
Wrong output items count in workflow editor

### ISSUE THREAD

**Issue by mcnaveen** [n8n-io/n8n#10080]
### Bug Description

So, I have 2 two HTTP nodes here. Both request data from the same API endpoint. 

`https://jsonplaceholder.typicode.com/posts` which returns `100` items.

As you can see in the screenshot below, the output count shows `100` but if you look at the item count in the second node it shows `10000 items`

![CleanShot 2024-07-17 at 12 12 39@2x](https://github.com/user-attachments/assets/0f4453be-cc42-4f5c-9763-cad20ac3a05e)

This bug has been present for a while now. Because I took this screenshot in `v1.50.1`

I'm not sure this happening with other nodes. I tested with `Set` node and doesn't seem to be happening.

### To Reproduce

1. Add 2 HTTP Node
2. Request data from Same Endpoint
3. See the wrong items count.

or Use this Workflow

```
{
  "meta": {
    "instanceId": "2e9594c9753bc235ba5e080ba2cec19b79465d226d9c1e55f94dca71019c0e9e"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "c4e33faa-51e1-4d5b-a701-9b97b1b9b43e",
      "name": "When clicking ‘Test workflow’",
      "type": "n8n-nodes-base.manualTrigger",
      "position": [
        720,
        400
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "url": "https://jsonplaceholder.typicode.com/posts",
        "options": {}
      },
      "id": "4459b1a0-f223-4791-9edc-645487ebda12",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        900,
        400
      ]
    },
    {
      "parameters": {
        "url": "https://jsonplaceholder.typicode.com/posts",
        "options": {}
      },
      "id": "33e16644-ee86-4805-ba76-c2843e471d57",
      "name": "HTTP Request1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        1120,
        400
      ]
    }
  ],
  "connections": {
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "HTTP Request1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

### Expected behavior

It should return the correct item count

### Operating System

Currently tested in Mac, but happens in Ubuntu too

### n8n Version

1.50.1

### Node.js Version

Docker?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
@mcnaveen don't forget the nodes run once for each input item so that second node unless set to run once will be fetching 100 items for each of the 100 runs.

**Comment by mcnaveen** [comment]
Ah, expected behavior.
