### ISSUE TITLE
Salesforce Trigger – Opportunity Created/Updated Fails Test

### ISSUE THREAD

**Issue by trijste** [n8n-io/n8n#10091]
### Bug Description

It looks like the SOQL query used in the background to support this node, specifically where Opportunity is the trigger, includes a non-standard column, "type". 

Testing with fetch returns the following:

Bad request - please check your parameters
id,accountId,amount,probability,type FROM Opportunity LIMIT 1 ^ ERROR at Row:1:Column:40 No such column 'type' on entity 'Opportunity'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

### To Reproduce

Select an Opportunity Trigger, click Fetch Test Event.

### Expected behavior

I expect the test to fetch an event.

### Operating System

Cloud Instance

### n8n Version

1.49.0

### Node.js Version

Cloud Instance

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @trijste,

Thanks for reporting this, It looks like we use the `type` field in the standard node as well for `Account`, `Opportunity` and `Case`.

Looking at the Salesforce docs (going back to Spring 14) Opportunity does appear to have a default type field which is seen in the UI as `Opportunity Type` and is a pick list where you can select Existing Business or New Business. Is it possible that you have this field hidden in your view?

https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_opportunity.htm

**Comment by trijste** [comment]
Hey @Joffcom,

Thanks for looking into this. You are correct. This field is hidden in my org for some reason (with a custom field doing the exact same thing 🤷). I'm reluctant to unhide it for this purpose.

I've instead set up an HTTP callout to an n8n webhook node to avoid polling executions. It sure felt like a bug at the time :)
