### ISSUE TITLE
HTTP Request node fails

### ISSUE THREAD

**Issue by martireg** [n8n-io/n8n#10096]
### Bug Description

HTTP endpoint node fails with this error

TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' | property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle at JSON.stringify (<anonymous>) at toText (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:13:21) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1768:55) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:664:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1079:20

Tried returning a string and a json on the endpoint response but still same error. The http call is done though 

### To Reproduce

In my current configuration this node is executed after an aggregate node which reads from a google sheet and puts output field on data, then the http endpoint is configured to send body, body content rawm content type application/json and body is expression `{{ $json.data }}`

### Expected behavior

HTTP call is made sucessfully and the response is sent to the next node

### Operating System

Docker version 20.10.25 on Amazon Linux 2

### n8n Version

1.45.1

### Node.js Version

20.13.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @martireg,

Can you start by adding a new http request node to your workflow and see if you have the same issue? I would also recommend updating n8n to see if that helps.

**Comment by martireg** [comment]
@Joffcom creating a new node with same configuration and replacing it seems to have solved the problem

**Comment by martireg** [comment]
Thank you @Joffcom
