### ISSUE TITLE
Gmail Trigger is not working

### ISSUE THREAD

**Issue by islycodes** [n8n-io/n8n#10098]
### Bug Description

The Gmail Trigger has not been working since two updates ago. It only works in manual executions; its cron does not function

### To Reproduce

1. Go to nodes
2. Insert Gmail Trigger 

### Expected behavior

Cron should work

### Operating System

Windows 11

### n8n Version

1.51.1

### Node.js Version

dont know

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @islycodes,

Can you confirm the version you are using as `1.51.1` does not exist. I have just given this a test on `1.51.0` and the trigger appears to be working as expected.

Can you share how you are running n8n, Are you using docker, npm, Cloud? If you go to Help > About n8n there is a `Copy debug information` link, could you paste that here as well.

For now though I would try stopping your workflow and activating it again to see if that helps.

**Comment by islycodes** [comment]
sorry, its really 1.50.1

Here is debug information:

# Debug info

## core

- n8nVersion: 1.50.1
- platform: docker (self-hosted)
- nodeJsVersion: 20.15.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

Generated at: 2024-07-18T12:50:14.118Z

**Comment by Joffcom** [comment]
@islycodes perfect, Could you try upgrading to `1.51.0` as I know that is currently working, After upgrading I would deactivate the workflow then activate it again.

What sort of schedule are you using as well? I have mine set to every minute at the moment.

**Comment by islycodes** [comment]
it worked, thanks!
