### ISSUE TITLE
calling CREATE SCHEMA IF EXISTS causes error on postgres server

### ISSUE THREAD

**Issue by eyalfishler** [n8n-io/n8n#10150]
### Bug Description

Update to the Typeorm driver done on May 30th is causing an error in the Postgres DB
fixed an issue with
calling CREATE SCHEMA IF EXISTS causes error on postgres server

sql_error_code = 00000 time_ms = "2024-07-20 04:48:15.846 UTC" pid="303954" proc_start_time="2024-07-20 04:48:14 UTC" session_id="669b418e.4a352" vtid="2/271031" tid="0" log_line="14" database="XXXXX" connection_source="X.Y.Z.M(64744)" user="YYYYYYY" application_name="[unknown]" LOG:  statement: CREATE SCHEMA IF NOT EXISTS n8n

I created a PR on the submodule https://github.com/n8n-io/typeorm/pull/14

### To Reproduce

https://github.com/n8n-io/typeorm/pull/14

### Expected behavior

https://github.com/n8n-io/typeorm/pull/14

### Operating System

Ubuntu

### n8n Version

latest

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

queue

**Comment by netroy** [comment]
Thanks for catching this 🙏🏽 

> Update to the Typeorm driver done on May 30th

Are you referring to [this change](https://github.com/n8n-io/typeorm/pull/13)?

**Comment by Joffcom** [comment]
Hey @eyalfishler,

Thanks for the report, We are tracking this internally as `N8N-7529`

**Comment by netroy** [comment]
As pointed out [here](https://github.com/n8n-io/typeorm/pull/14#issuecomment-2255790063), this is not an error. Closing this.
