### ISSUE TITLE
When leaving a workflow n8n stopped asking if I want to save it

### ISSUE THREAD

**Issue by salomaoparkour** [n8n-io/n8n#10164]
### Bug Description

It was default behavior to ask if I wanted to save my changes to the current workflows, when:

- leaving the workflow
- closing the tab

Now it's not asking anymore and it caused me to lose my work.
It only warns me when closing the tab, but not when leaving the workflow.

### To Reproduce

1. Create a workflow
2. Add some nodes
3. Go to the home page

### Expected behavior

Pop-up asking if you want to save the workflow before leaving the page.

### Operating System

Ubuntu 22.04

### n8n Version

1.50.1

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
This was fixed [here](https://github.com/n8n-io/n8n/pull/10190), and released in `1.51.2`
