### ISSUE TITLE
Docker documentation: case for users with VPN

### ISSUE THREAD

**Issue by F041** [n8n-io/n8n#10176]
### Bug Description

as mentioned: https://docs.n8n.io/hosting/configuration/environment-variables/security/, as a VPN user (Tailscale) that installed the service on a VPS, so I can't access the URL via localhost, I had the problem
[your n8n server is configured to use a secure cookie, however you are visiting this via an insecure URL](https://community.n8n.io/t/please-document-n8n-secure-cookie/42972)
so I solved with a custom docker-compose.yml. Can you please add it in the documentation?
about the forcing the HTTPS, can you add another docker-compose.yml with something like Traefik?
Especially this part confuses me in the case of the URL that uses the IPv4 address of Tailscale 

```
[...]
 labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`yourdomain.com`)"
[...]
```

### To Reproduce

docker volume create n8n_data
docker run -it -d --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n

### Expected behavior

a setup running without issues

### Operating System

Ubuntu server 22.04

### n8n Version

latest

### Node.js Version

latest

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @F041,

Can you clarify what the bug is that you are reporting? It looks like what you are seeing is expected and you would likely not be using Traefik if you are running n8n on a VPS that needs a VPN to access it.

**Comment by Joffcom** [comment]
Hey @F041,

In that case as it is not a bug I am going to close this as we only use GitHub issues for bug tracking. If you can be a bit clearer on what you think we should document though I can look at opening a docs issue for that.

We do consider self hosting an advanced feature and we can't document every possible configuration option so we do tend to lean towards what is going to help the most users and for other things rely on the knowledge of the user configuring it. In this case I am still not sure why you would be using Traefik if you are using a VPN to access n8n but I think we do make it clear on the error page what needs to be done.
