### ISSUE TITLE
Google Sheets Credential Screen - No OAUTH Configuration

### ISSUE THREAD

**Issue by Fishwaldo** [n8n-io/n8n#10181]
### Bug Description

Trying to connect to google sheets. When I go to add a credential for the Google Sheets Node, I initially get a "OUATH/Service Account" radio button. When I click OAUTH, then I just get a "Sign in with Google" button, and no option to input any of the OAUTH parameters such as client id or secret as per the screenshot
<img width="985" alt="Screenshot 2024-07-25 at 1 16 55 PM" src="https://github.com/user-attachments/assets/b74ad80f-5935-4323-bb4d-f96ab39b8fdb">

If I try any of the other google nodes such as gmail, or drive, I get the OAUTH config options.

This is on 1.51.1 (and also was on 1.50.x) 

### To Reproduce

Add Google Sheets Node, Click Credentials, create, select OAUTH. 

### Expected behavior

It works :)

### Operating System

N8N Cloud

### n8n Version

1.51.1

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Fishwaldo 

When using n8n Cloud we handle this for you so all you need to do is click the sign in button.

This should be covered in the documentation just above the steps that need to be completed for self hosted users.

What I will do is add a notice to the credential as well.

**Comment by Fishwaldo** [comment]
Ok. When I do that, I get a "app is blocked" after signing in with my google account. 

![image](https://github.com/user-attachments/assets/850e2695-afa0-4811-9550-535c0c537e5e)

**Comment by Fishwaldo** [comment]
If I setup a drive or gmail node and put in my OAUTH client ID/Secret it works fine. So it seems a different authentication "flow" for sheets?

**Comment by Joffcom** [comment]
App is blocked is not good, I will need to look into that as we just went through the verification process with Google.

**Comment by Joffcom** [comment]
Thanks @Fishwaldo we have dug into this a bit more and it looks like the verification process may have one last step, We have reached out to Google to get this resolved as soon as possible.

**Comment by Fishwaldo** [comment]
Any update?

**Comment by Joffcom** [comment]
Hey @Fishwaldo,

We are still waiting on Google, We checked out verification yesterday and it was fine. Google have said they will prioritise this so we are hoping that it won't be too much longer.

**Comment by Joffcom** [comment]
Hey @Fishwaldo,

Good news Google completed the verification last night and this is now back up and running, Can you send in an email to help@n8n.io and include your Cloud username for me?

If you have any questions let me know.

**Comment by Fishwaldo** [comment]
Sent. We switched to a service account for the Google Sheets (and subsequently hit that Crowdstrike issue) but I’ll test a new workflow next week with oauth. 

Cheers
