### ISSUE TITLE
Pipedrive trigger creates multiple webhooks

### ISSUE THREAD

**Issue by Robarelli** [n8n-io/n8n#1018]
**Describe the bug**
I am noticing that, when a workflow that has a Pipedrive trigger is saved, it automatically adds the webhook to Pipedrive. However, it seems like it keeps adding new webhook entries even though one may already exist. For example, if I am working on a workflow and save it 3 times over the course of some time, I will see 3 identical webhook entries in Pipedrive and then my workflow gets hit 3 times by the same event until I manually go in and remove them.

**To Reproduce**
1. Create a workflow and add Pipedrive as the trigger
2. Test and Save the workflow and observe the webhook added to the Pipedrive account
3. Continue working on the workflow, then save again
4. Observe a second webhook entry in the Pipedrive account that's the same as the first

Note that I haven't observed this to be consistent. Sometimes I have to wait a bit before saving for the duplicate to get added.

**Expected behavior**
Saving the workflow should not add duplicate webhook entries

**Environment (please complete the following information):**
 - OS: Alpine Linux 3.11.6
 - n8n Version: 0.85.0
 - Node.js Version: v12.16.3

**Additional context**
Perhaps the user should manually add the webhook instead of it getting added automagically?

**Comment by RicardoE105** [comment]
@Robarelli thanks very much for letting us know. Just sent a PR fixing the issue. We will let you know when is released.

**Comment by janober** [comment]
Got merged. Will update once new version got released.

**Comment by janober** [comment]
Fix got released with n8n@0.87.0
