### ISSUE TITLE
Regression in versions >= 1.50.0: Failure to start n8n (Self-signed certificate in certificate chain)

### ISSUE THREAD

**Issue by ThomasRizzuto** [n8n-io/n8n#10197]
### Bug Description

Since version 1.50.0, a self hosted instance of n8n has been unable to start.
(Version 1.49.0 and downward are unaffected, and this particular instance boots correctly when downgraded)

During startup, the following error is shown in the container console, and the container exits:

```
Error: There was an error initializing DB
Error: self-signed certificate in certificate chain
```
![n8nLaunchError](https://github.com/user-attachments/assets/981db1e7-522e-41db-839a-b24bbe661992)

This instance of n8n is using "Azure Cosmos DB for PostgreSQL" as the underlying database.
The database settings are passed in to n8n via environment variables.
A secure connection to the database is required (SSL), so the "DB_POSTGRESDB_SSL_CA" environment variable is set and points to a valid certificate.
Despite this, the error above indicating a self-signed certificate persists.
I have tried launching this instance with "DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED" set to both "TRUE" and "FALSE" with the same result.

It appears that in 1.50.0 the backend config was refactored for #9325, possibly introducing a regression.

### To Reproduce

1. Create a containerized instance of n8n running version >= 1.50.0
2. Configure the instance to use a secure connection to a PostgresDB (Specify a CA cert via DB_POSTGRESDB_SSL_CA env. variable)
3. Launch the instance, and monitor the container console for errors.

### Expected behavior

n8n should launch and connect to the Postgres DB successfully, even when using a secure connection.
No errors should be shown in the container console window.

### Operating System

Azure Container Apps Managed Environment

### n8n Version

\>=1.50.0

### Node.js Version

20 (Specified by dockerfile)

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by kcyd** [comment]
same here, issue fixed by going back to 1.49.0

**Comment by netroy** [comment]
are you passing in only `DB_POSTGRESDB_SSL_CA`, or also the other `DB_POSTGRESDB_SSL_*` env variables as well?

**Comment by netroy** [comment]
Can you please try setting `DB_POSTGRESDB_SSL_CA_FILE` to point to the cert. `DB_POSTGRESDB_SSL_CA` seems to be incorrectly documented and is meant to be the literal certificate content.

**Comment by ThomasRizzuto** [comment]
@netroy Great suggestion, that has remedied the issue. Version 1.51.2 is now launching successfully.
