### ISSUE TITLE
Latin-1 encoding in CSV presents invalid characters

### ISSUE THREAD

**Issue by jalvesbsolus** [n8n-io/n8n#10194]
### Bug Description

When using the flag N8N_DEFAULT_BINARY_DATA_MODE=filesystem to read a 'csv' file with the 'raw data' option set to true and 'Read As String' set to false, characters such as accents appear invalid when use latin-1 encoding.

Attention: I specify the options used for a reason - when N8N_DEFAULT_BINARY_DATA_MODE=default works correctly, the issue arises with N8N_DEFAULT_BINARY_DATA_MODE=filesystem.

I have already tried with 'Read As String' set to true (which works for UTF-8) but it doesn't work either.

**This error already describe in [https://github.com/n8n-io/n8n/issues/9365](https://github.com/n8n-io/n8n/issues/9365)  .
However, at the time they resolved the issue, but it currently no longer works again. Remembering that the created option "encoding" does not appear in this version, so I don't know if they removed it or it is simply hidden**

### To Reproduce

1. Change N8N_DEFAULT_BINARY_DATA_MODE=filesystem
2. 'Read As String' set to false and 'raw data' option set to true (only Just because these options work for the flag N8N_DEFAULT_BINARY_DATA_MODE=default)
3. import csv with latin-1
4. See the accents

### Expected behavior

1. Use N8N_DEFAULT_BINARY_DATA_MODE=filesystem
2. import csv in latin-1
3. keep compatibility to utf-8 and utf-8 with bom
Finally, I use N8N_DEFAULT_BINARY_DATA_MODE=filesystem with CSV encoding latin-1, utf-8, and utf-8 with BOM (these last two already work).

### Operating System

centos

### n8n Version

1.51.1

### Node.js Version

v20.15.0

### Database

PostgreSQL

### Execution mode

own (deprecated)

**Comment by Joffcom** [comment]
Hey @jalvesbsolus,

When using Extract from CSV are you using the `Encoding` option to select `Latin-1`?

![image](https://github.com/user-attachments/assets/9d29f66b-75de-4f8e-98be-278b775e8786)

**Comment by jalvesbsolus** [comment]
@Joffcom  
![n8n](https://github.com/user-attachments/assets/4f606829-a781-43ca-bf4d-f734a6c747b1)
No option "enconding"   appear

**Comment by Joffcom** [comment]
Hey @jalvesbsolus,

That is interesting it appears on my version, Can you clear your browser cache and check again? Not upgrading to 1.43.0 won't matter as we don't do incremental updates like that.

**Comment by jalvesbsolus** [comment]
Thanks @Joffcom , that was it, I thought updates were applied and caches were cleared. Another question that I still haven't received an answer to was, do I need to detect whether the file is Latin or UTF-8 because I don't know beforehand. I used the strategy that was:
1.Read the file in utf-8
2.Check in python if there are invalid characters in the read data
3.If it doesn't exist, everything is ok, if it does, read again but in Latin-1

Is there any better solution?

**Comment by Joffcom** [comment]
@jalvesbsolus we don't have anything in n8n to determine the encoding at the moment so it would be a case of doing what you are doing for now.

It would make a great [feature request](https://community.n8n.io/c/feature-requests/5) if you wanted to open it on the support forum though. For now as there isn't a bug here I am going to mark this as closed, Thanks for taking the time to open it.
