### ISSUE TITLE
Encoding for some characters in IMAP trigger works incorrectly

### ISSUE THREAD

**Issue by workfloows** [n8n-io/n8n#10230]
### Bug Description

For IMAP trigger node in format "Simple" some characters are encoded incorrectly. For example, letter `ş` is converted to character `º`.

Below example for name "Eşref" being converted to "Eºref".

![Incoming email in mode "Simple"](https://github.com/user-attachments/assets/1a045e96-0a49-4ae9-aa2a-1341ad3b7f4c)

And the same email in web client

![encoding-source](https://github.com/user-attachments/assets/40334a5c-48ec-4db8-b81d-380a3f8fc151)

### To Reproduce

1. Set "Format" field to "Simple" in IMAP trigger.
2. Execute IMAP trigger for email message with character `ş`.
3. Observe fields `textHtml` and `textPlain` for wrongly encoded characters.  

### Expected behavior

Characters should be encoded correctly. 

### Operating System

Ubuntu 22.04.2 LTS

### n8n Version

1.49.0

### Node.js Version

20.14.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @workfloows,

Thanks for the report, I suspect this issue may be fixed with this PR: https://github.com/n8n-io/n8n/pull/10046 once reviewed and merged.

**Comment by mamezipl** [comment]
Same here, with polish characters!

Used node: Email Trigger (IMAP)

![Image](https://github.com/user-attachments/assets/e6928aa4-2f5c-41f8-aa63-f4c5d6463595)

**Comment by nicolashimmelmann** [comment]
An idea for a temporary fix (if anyone urgently needs this):

Put a code node after the IMAP node with this content:

```
function fixCommonEncodingErrors(text) {
    const encodingFixes = {
        "Ã¤": "ä",
        "Ã¶": "ö",
        "Ã¼": "ü",
        "Ã": "ß",
        "Ã„": "Ä",
        "Ã–": "Ö",
        "Ãœ": "Ü",
        "Ã¢": "â",
        "Ã©": "é",
        "Ã¨": "è",
        "Ãª": "ê",
        "Ã«": "ë",
        "Ã¯": "ï",
        "Ã®": "î",
        "Ã¥": "å",
        "Ã¦": "æ",
        "Ã¸": "ø",
        "Ã±": "ñ",
        "Ã§": "ç",
        "â€™": "'",
        "â€œ": '"',
        "â€": '"',
        "â€¢": "-",
        "â€“": "-",
        "â€”": "—",
        "â„¢": "™",
        "Ã‚": "Â",
        "Ã": "Ã",
        "Ã‡": "Ç",
        "Ãˆ": "È",
        "Ã‰": "É",
        "ÃŠ": "Ê",
        "Ã‹": "Ë",
        "Ã": "Ð",
        "Ã": "Í",
        "ÃŽ": "Î",
        "Ã": "Ï",
        "Ã": "Ñ",
        "Ã’": "Ò",
        "Ã“": "Ó",
        "Ã”": "Ô",
        "Ã•": "Õ",
        "Ã™": "Ù",
        "Ãš": "Ú",
        "Ã›": "Û",
        "Ã": "Ý",
        "Ãž": "Þ",
        "Ã¡": "á",
        "Ã ": "à",
        "Ã£": "ã",
        "Ã¥": "å",
        "Ã¦": "æ",
        "Ã§": "ç",
        "Ã¨": "è",
        "Ã©": "é",
        "Ãª": "ê",
        "Ã«": "ë",
        "Ã­": "í",
        "Ã¬": "ì",
        "Ã®": "î",
        "Ã¯": "ï",
        "Ã°": "ð",
        "Ã±": "ñ",
        "Ã³": "ó",
        "Ã²": "ò",
        "Ã´": "ô",
        "Ãµ": "õ",
        "Ã¹": "ù",
        "Ãº": "ú",
        "Ã»": "û",
        "Ã½": "ý",
        "Ã¿": "ÿ"
    };

    // Create a regular expression from the encodingFixes keys
    const regex = new RegExp(Object.keys(encodingFixes).join("|"), "g");

    // Replace each misencoded sequence in the text
    return text.replace(regex, match => encodingFixes[match]);
}

// Loop over input items and add a new field called 'myNewField' to the JSON of each one
for (const item of $input.all()) {
  item.json.textPlain = fixCommonEncodingErrors(item.json.textPlain);
}

return $input.all();
```

**Comment by Datenschmutz** [comment]
I'm facing the same issue.

@Joffcom , as the PR you linked seems to be stale, could you please reopen the issue?

**Comment by Bluejanis** [comment]
@ShireenMissi 2 years later this bug still exists. Why did you close it?
