### ISSUE TITLE
404 error for urls in docs 

### ISSUE THREAD

**Issue by jeanniesarah** [n8n-io/n8n#1030]
**Describe the bug**
404 error for urls in documentation
**To Reproduce**
1. Go to 'docs.n8n.io/getting-started/creating-your-first-workflow.html'
2. Scroll down to 'Prerequisites'
3.  Click on 'OpenWeatherMap account - You'll need to obtain an Access Token for the OpenWeatherMap API. You can find instructions on how to obtain that **_here._**'
5. Click on 'Twilio account - You'll need to obtain the Account SID and Auth Token for the Twilio API. You can find instructions on how to obtain that **_here.__**'
6. See error 

**Expected behavior**
Links to OpenWeatherMap api and Twilio docs open
https://home.openweathermap.org/
https://www.twilio.com/docs/api

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0]
 - Node.js Version [e.g. 10.16.0]

**Additional context**

**Comment by tanay1337** [comment]
Hi @jeanniesarah, thanks for filing this bug report. Unfortunately, I am unable to replicate the bug. Could you please check if the bug still persists? If it does, would you mind sharing your OS and browser information? 😄

**Comment by jeanniesarah** [comment]
Hi @tanay1337 on my local copy installed on Mac OS Catalina using Chrome browser however the urls on the live homepage work perfectly 👍

**Comment by tanay1337** [comment]
Great to hear @jeanniesarah, have fun! 🎉
