### ISSUE TITLE
AI Agent node's Conversational Agent can be configured with AWS Bedrock Chat Model only if it has been set to other type such as ReAct Agent and then changed back to Conversational Agent after setting the model to AWS Bedrock Chat Model

### ISSUE THREAD

**Issue by Gungz** [n8n-io/n8n#10316]
### Bug Description

AI Agent node's Conversational Agent can be configured with AWS Bedrock Chat Model only if it has been set to other type such as ReAct Agent and then changed back to Conversational Agent after setting the model to AWS Bedrock Chat Model.

### To Reproduce

1. Add AI Agent node
2. Set Agent to Conversational Agent
3. Try to set the Model as AWS Bedrock Chat Model, it will not be possible because the option doesn't allow it.

Workaround:
1. Set Agent to ReAct Agent
2. Set Model as AWS Bedrock Chat Model
3. Set Agent back to Conversational Agent

Now, Conversational Agent can use AWS Bedrock Chat Model and upon testing with some toy scenario, it works.

### Expected behavior

AI Agent Conversational Agent can directly use the AWS Bedrock Chat Model without workaround.

### Operating System

n8n cloud

### n8n Version

1.51.2

### Node.js Version

n8n cloud

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Gungz,

Thanks for the report, I have passed this on to our AI team to investigate. The internal reference is `AI-272`
