### ISSUE TITLE
Openai gpt-4-vision-preview is deprecated

### ISSUE THREAD

**Issue by kuon** [n8n-io/n8n#10375]
### Bug Description

Openai gpt-4-vision-preview is deprecated

### To Reproduce

Create an openai workflow with image->analyse image.

```
{ "error": { "message": "The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }
```

is returned

### Expected behavior

should work

### Operating System

archlinux

### n8n Version

1.53.2

### Node.js Version

22.6

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @kuon,

We have created an internal ticket to look into this which we will be tracking as "GHC-153"

**Comment by Joffcom** [comment]
Hey @kuon,

Have you tried selecting a different model to use? That message would suggest that OpenAI are removing support for the vision preview model. If you don't have the option to select the model can you try adding the node again and see if that gives the option to change it.

Looking at the OpenAI docs the model is only available to users who were already using it before June 17th.

**Comment by kuon** [comment]
> Hey @kuon,
> 
> Have you tried selecting a different model to use? That message would suggest that OpenAI are removing support for the vision preview model. If you don't have the option to select the model can you try adding the node again and see if that gives the option to change it.
> 

Yes it I didn't have the option to select the model, after deleting the node and adding again the list appeared. And it works with other model.

**Comment by Joffcom** [comment]
Perfect, That is to be expected as the original node only worked with vision.

I will mark this one as closed for now.
