### ISSUE TITLE
AI Agent not recognising attached tools [v1.54.1]

### ISSUE THREAD

**Issue by jimleuk** [n8n-io/n8n#10401]
### Bug Description

Discovered by [joachim_brindeau](https://community.n8n.io/u/joachim_brindeau): https://community.n8n.io/t/using-the-vector-store-tool/51805/5

An AI agent with attached tools complains with the following message:
`Please connect at least one tool. If you don't need any, try the conversational agent instead`

Tested using Docker image `docker.n8n.io/n8nio/n8n:next`

### To Reproduce

1. **Advanced AI** > **AI Agent** node
2. Attached all standard subnodes - LLM, Memory
3. Attach the calculator tool
4. Using chat trigger, ask any question
5. The error is returned instead of the LLM response.

### Expected behavior

Tools are attached to AI agent so error should not be thrown.
The LLM response should be returned instead.

### Operating System

MacOS Sonoma

### n8n Version

1.54.1

### Node.js Version

20

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jimleuk,

We have created an internal ticket to look into this which we will be tracking as "GHC-158"

**Comment by Joffcom** [comment]
Hey @jimleuk

Just looking at the post now, if a bug is found or raised on the forum there is no need to create a GitHub issue for it as it duplicates the issue.

I am going to close this issue and I will update the forum post with the internal ticket.

**Comment by Joffcom** [comment]
@jimleuk good news this has been fixed in `1.55.0` and `1.54.2` so an upgrade should resolve it .

**Comment by janober** [comment]
Fix got released with [`n8n@1.55.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.55.0)
