### ISSUE TITLE
Facebook Graph API needs to support api v.20

### ISSUE THREAD

**Issue by theRoundGreek** [n8n-io/n8n#10407]
### Bug Description

I have a few flows running that are getting ad perfomance data through the graph api. The past couple of days i wasn't getting any data. Just checked the flow and saw the following in the grap api responses:

[You are calling a deprecated version of the Ads API.](x-ad-api-version-warning:You are calling a deprecated version of the Ads API.)

www-authenticate:OAuth "Facebook Platform" "invalid_request" "(#2635) You are calling a deprecated version of the Ads API. Please upgrade to the latest version: v20.0."

### To Reproduce

if you have a facebook business manager account and run ads try to get the follwoing:

node: act_your_account_id
edge: insights

### Expected behavior

ad performace data.

### Operating System

ubuntu

### n8n Version

1.53.2

### Node.js Version

18.20.4

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @theRoundGreek,

We have created an internal ticket to look into this which we will be tracking as "GHC-160"

**Comment by Joffcom** [comment]
Hey @theRoundGreek,

Thanks for the report I have put in a quick fix for it that will be part of a future release most likely `1.56.0` next week, For now if you change the field to an expression for the version you should be able to input `v20.0` and it will work.

**Comment by janober** [comment]
Fix got released with [`n8n@1.56.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.56.0)
