### ISSUE TITLE
Workflows executed by workflows display as "Queued" in executions

### ISSUE THREAD

**Issue by Nick-PDS** [n8n-io/n8n#10444]
### Bug Description

I just upgraded from 1.52.2 to 1.55 and I started encountering a new issue with my workflows showing in the execution log as "Queued" only when they have been executed by another workflow.

At first, I thought this was affecting my actual executions and they were just getting stuck in queue (even though my EXECUTION_MODE is regular) but they actually did end up completing once I let it fully run it's course.

This isn't entirely a major issue but it did cause me to panic as to why my executions weren't running when actually they were.

![n8nExecutions](https://github.com/user-attachments/assets/a7a31e6e-dbfb-4298-8d4e-923fe0cf5c31)

### To Reproduce

1. Create 2 workflows
2. Execute the 2nd workflow in the first workflow (2nd workflow should have a long wait node so you can see it is "Queued" before completion
3. Go to execution logs to see "Queued"

### Expected behavior

Correctly show "Running for 0:00m" if it actually is running

### Operating System

Ubuntu Linux 22.02

### n8n Version

1.55.1

### Node.js Version

20.15.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Nick-PDS,

We have created an internal ticket to look into this which we will be tracking as "GHC-164"

**Comment by kent-1** [comment]
I also interrested by the resolution of this issue. I posted an a question on the forum : 

https://community.n8n.io/t/running-wf-are-taged-as-queued-instead-of-running/52853

**Comment by lfnt3** [comment]
I have the same issue.
