### ISSUE TITLE
I discovered a bug with Node S3 where n8n interprets the bucket name as a subdomain and throws an execution error. (minio)

### ISSUE THREAD

**Issue by Witroch4** [n8n-io/n8n#10467]
### Bug Description

I encountered a bug with the S3 Node in n8n where it interprets the bucket name as a subdomain, resulting in an execution error while using MinIO.

The node lists the buckets without issues, but when I attempt to create or locate files within a specific bucket, it triggers a domain error as indicated in the logs. The system tries to access a non-existent subdomain that shares the same name as the bucket.

Error Details

From S3
Error Code: ENOTFOUND
Full Message:
getaddrinfo ENOTFOUND pack-typebot.minioapi.meydomain.com.br

Other Information:

Node Type: n8n-nodes-base.s3
Node Version: 1 (Latest)
n8n Version: 1.54.4 (Self-Hosted)
Time: 18/08/2024, 16:59:58
Stack Trace:

NodeApiError: The connection cannot be established; this usually occurs due to an incorrect host (domain) value   
at Object.s3ApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/S3/GenericFunctions.js:67:15)   
at processTicksAndRejections (node:internal/process/task_queues:95:5)   
at Object.s3ApiRequestSOAP (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/S3/GenericFunctions.js:80:22)   
at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/S3/S3.node.js:412:40)   
at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:728:19)   
at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:673:51   
at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1104:20  
Problem in Node ‘S3’:
The connection cannot be established; this usually occurs due to an incorrect host (domain) value.

### To Reproduce

Access the self-hosted n8n and log in to your account.
Create a new workflow.
Add the S3 node to the workflow.
Configure the S3 node with the correct credentials and the name of the bucket you want to use in MinIO.
Attempt to list the buckets to confirm that the connection is working.
Try creating or finding a file within the specified bucket.
Note the execution error that occurs.
n8n latest

### Expected behavior

It was supposed to list the files in the bucket by accessing the correct endpoint.

### Operating System

ubuntu Linux 22.04

### n8n Version

n8n Version1.54.4

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @Witroch4,

We have created an internal ticket to look into this which we will be tracking as "GHC-172"

**Comment by Joffcom** [comment]
Hey @Witroch4 

Quick thought on this one, do you get the same issue if you try using the "force path style" option in the credential?

**Comment by Witroch4** [comment]
It really worked, I set the location in MinIO as us-east-1, but I believe that selecting this option must have made everything work. Thank you very much!!!

**Comment by Joffcom** [comment]
Hey @Witroch4, 

Perfect for now I will mark this as closed, The node is designed to work with different options and they all do things in a slightly different way so it is case of tweaking the options sometimes.

For now I will mark this as closed.
