### ISSUE TITLE
Allows to use await in subfunctions

### ISSUE THREAD

**Issue by felinto-dev** [n8n-io/n8n#10465]
### Bug Description

Hello,
I'm using puppeteer with n8n. I can't use await inside functions because it gives me a syntax error. I also can't return custom objects that don't have the "json" attribute inside them. 

### To Reproduce

Here's an sample code:

![image](https://github.com/user-attachments/assets/bab00597-db33-411a-9ac8-0f37cd8e7b7a)
![image](https://github.com/user-attachments/assets/6d92518e-b230-4413-8465-882bf94d42f6)

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch({ headless: true})
  const page = await browser.newPage()

  await page.evaluate(() => {
    const promise = new Promise();
    await promise; // Syntax error
  })

  await page.evaluate(() => {
    return []; // Code doesn't return an object. Array found instead. Please return an object representing the output item
  })

  await browser.close()
})()
```

### Expected behavior

There could be a setting in the "code" node saying something like: "I know what I'm doing. Please don't block code execution due to syntax errors."

### Operating System

Docker

### n8n Version

1.53.2

### Node.js Version

Docker official image

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @felinto-dev,

We have created an internal ticket to look into this which we will be tracking as "GHC-171"

**Comment by felinto-dev** [comment]
About page.evaluate puppeteer function: https://pptr.dev/api/puppeteer.page.evaluate

**Comment by Joffcom** [comment]
Hey @felinto-dev 

Just quickly looking at this now, the code node expects a json response as that is how we move data between nodes, most people doing what you are trying to do would just return something like `{ 'success': true }` so you know the task has completed.

The await is likely a limitation of the JavaScript sandbox that we currently use unless it is actually invalid code I would need to check that.

If you want to change how the code node outputs data I would recommend opening a feature request on our [support forum](https://community.n8n.io) as we only use GitHub for tracking bugs.

**Comment by Joffcom** [comment]
Based on that I think we can mark this as closed, Thanks for checking @netroy.
