### ISSUE TITLE
HTTP Request  Tools: Subsequent AI calls with different parameters return identical responses

### ISSUE THREAD

**Issue by FredMichel** [n8n-io/n8n#10541]
### Bug Description

When using the HTTP Request Tools, if the AI makes multiple calls to the tool with different parameters, only the first call responds correctly. Subsequent responses remain identical to the first call, even though the parameters are supposed to be modified.

### To Reproduce

1. Set up an HTTP request in n8n using the HTTP Tools.
2. Have the AI model make multiple calls to this HTTP request with different parameters for each call (ex. Give me the age of Anna and Henry) . First call is GET /age?name=Anna , second call is GET /age?name=Anna)
3. Notice that the first response is correct, but all subsequent response is identical to the first, regardless of the changed parameters.

### Expected behavior

Each HTTP request made with different parameters should return a distinct response based on those parameters, not repeat the first response.

### Operating System

Mac OS

### n8n Version

1.55.3

### Node.js Version

v20.10.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @FredMichel,

We have created an internal ticket to look into this which we will be tracking as "GHC-183"

**Comment by janober** [comment]
Fix got released with [`n8n@1.60.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.60.0)
