### ISSUE TITLE
HubSpot Trigger API key should not be required

### ISSUE THREAD

**Issue by wpchannel** [n8n-io/n8n#10544]
### Bug Description

When using HubSpot Trigger, API key is a required field. It should not because API keys no more exist. App token and OAuth 2 should be allowed.

### To Reproduce

1. Add HubSpot Trigger node
2. Click to add credentials to connect with
3. See that Developer API Key is a mandatory field

### Expected behavior

Developer API Key field should be removed

### Operating System

Docker

### n8n Version

1.54.4

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @wpchannel,

We have created an internal ticket to look into this which we will be tracking as "GHC-185"

**Comment by wpchannel** [comment]
@Joffcom sorry I'm wrong, the Developper API Key is still valid, the doc was confusing about it. I was looking for an app API key, but we need a developper account API key here...

**Comment by Joffcom** [comment]
Hey @wpchannel,

Perfect in that case I will mark this as closed as it sounds like everything is good.
