### ISSUE TITLE
Webflow -  Form Submissions 

### ISSUE THREAD

**Issue by oscarpedrero** [n8n-io/n8n#10549]
### Bug Description

I'm trying to configure Webflow so that every time a form is submitted, it's captured and sent to our CRM. I've set up the app in non-legacy mode, and it retrieves the pages perfectly. However, when I run the test, I get the following error:

``` Webflow Trigger: OAuthForbidden: You are missing the following scopes - 'forms:read' ```

![image](https://github.com/user-attachments/assets/b30b4250-0029-4fbf-b40c-c6a4930eeb93)

I've tested the other functionalities of the node, and it stays in listening mode perfectly, working without any issues.

### To Reproduce

1. Create a new scenario.
2. Select the initial Webflow module to capture form submissions.
3. Configure the connection using the OAuth app details you created in Webflow, uncheck the Legacy mode, and connect your Webflow account to N8N.
4. Press the "Test Step" button to receive a lead.

If you follow these steps, you'll encounter the error I mentioned above.

Attached is a screenshot of the app permissions in Webflow.
![image](https://github.com/user-attachments/assets/e5630548-3a5f-4a96-b24f-a38215325d60)

### Expected behavior

I expected the module to stay in listening mode to receive the form data submitted on the Webflow page, but it's giving an error.

### Operating System

Docker Image n8nio/n8n:latest

### n8n Version

1.55.3

### Node.js Version

v20.15.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @oscarpedrero,

We have created an internal ticket to look into this which we will be tracking as "GHC-186"

**Comment by oscarpedrero** [comment]
I submitted a pull request to fix it: https://github.com/n8n-io/n8n/pull/10554.

**Comment by Joffcom** [comment]
Looks good, I am going to close this as you made a PR

**Comment by Joffcom** [comment]
Fix got released with [`n8n@1.59.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.59.0)
