### ISSUE TITLE
Issue with autocomplete and external-secrets

### ISSUE THREAD

**Issue by eduardocalazansjr** [n8n-io/n8n#10576]
### Bug Description

When I try to use the autocomplete to match a path on a external-secret (w/ hashicorp vault), I got an `unexpected token` message.

I'm attaching the n8n screenshots and also my vault secret screenshot

 

### To Reproduce

1. Create a secret with a `/` in the mount-path in vault
2. Load the secret in n8n (works)
3. Go to the credentials page and try to create a new Basic Auth
4. Fill the password with the expression field as the screenshot

### Expected behavior

The autocomplete should works and I can use my external secret

### Operating System

MacOS X

### n8n Version

1.55.3

### Node.js Version

v18.19.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @eduardocalazansjr,

We have created an internal ticket to look into this which we will be tracking as "GHC-191"

**Comment by Joffcom** [comment]
Hey @eduardocalazansjr,

Officially we don't support a slash in secret names at the moment as mentioned in our documentation here: https://docs.n8n.io/external-secrets/#connect-n8n-to-your-secrets-store

I do expect this to be resolved in the future but it is a tricky one as we don't officially support it anyway is it a bug or is the bug that we support something we shouldn't.

For now I am going to mark this as "won't fix" but I do expect us in the future to pick this up when we officially add support for other options.

Oddly I think it was me that added in the partial support for a slash. Let me know if you have any questions on this.
