### ISSUE TITLE
No paste option on context menu

### ISSUE THREAD

**Issue by moabeonspot** [n8n-io/n8n#10571]
### Bug Description

When we click with the right button on the canvas we can't see the "paste" option as we can see in the image
![image](https://github.com/user-attachments/assets/af652961-0523-4193-9fda-a23e7efcc56d)

### To Reproduce

Open the canvas, click with the right button and try to find the "paste" option

### Expected behavior

It will be good to have this option

### Operating System

Debian

### n8n Version

1,55,3

### Node.js Version

I dont know

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @moabeonspot,

We have created an internal ticket to look into this which we will be tracking as "GHC-190"

**Comment by netroy** [comment]
From what I can tell, there has never been a paste option in this context menu. Which makes this a feature request.
Usually for stuff like this we recommend posting [here](https://community.n8n.io/c/feature-requests/5) instead.

**Comment by Joffcom** [comment]
Moving to closed as this is more of a feature request.
