### ISSUE TITLE
Send Template via Amazon SES Node

### ISSUE THREAD

**Issue by maxmarines** [n8n-io/n8n#1060]
**Describe the bug**
 "To Addresses:" field not worked in "Template Data" operation in Amazon SES Node. 

**To Reproduce**

1. Create Template [from officical documentation](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-personalized-email-api.html)`{
  "nodes": [
    {
      "parameters": {
        "resource": "template",
        "templateName": "MyTemplate",
        "subjectPart": "Greetings, {{name}}!",
        "htmlPart": "<h1>Hello {{name}},</h1><p>Your favorite animal is {{favoriteanimal}}.</p>",
        "additionalFields": {
          "textPart": "Dear {{name}},\\r\\nYour favorite animal is {{favoriteanimal}}."
        }
      },
      "name": "AWS Create",
      "type": "n8n-nodes-base.awsSes",
      "typeVersion": 1,
      "position": [
        170,
        660
      ],
      "credentials": {
        "aws": "AMAZON"
      }
    }
  ],
  "connections": {}
}`
2. Set Template Name in AWS SES node "MyTemplate".
3. Set "Template Data" field
![Безымянный](https://user-images.githubusercontent.com/62845038/96137937-ecfa1e80-0f05-11eb-86ca-395b4c35580b.png)
4. Set "To Addresses:" field
5. Execute Node.
6. I receive a notification about successful sending. 
![Безымянны555й](https://user-images.githubusercontent.com/62845038/96138469-7a3d7300-0f06-11eb-97bc-1517c45fcf98.png)

**but really the message does not appear in the mail.**

**Expected behavior**
If set Operation "Send" I receive a notification about successful sending and the letter appears in the mail in less than a second.

![Безымянны5566й](https://user-images.githubusercontent.com/62845038/96143876-39e0f380-0f0c-11eb-80d2-3d8f0ece157a.png)
**Environment (please complete the following information):**
 - OS: [Ubuntu 20 LTS]
 - n8n Version [0.87.0]
 - Node.js Version [from docker image]

**Comment by RicardoE105** [comment]
@maxmarines thanks for letting us know. I had not noticed the bug cuz AWS returned a `success` response. We will let you know when is released.

**Comment by janober** [comment]
Thanks a lot @RicardoE105! The PR just got merged. A new version with the fix will be released tomorrow.

**Comment by janober** [comment]
Fix got released with n8n@0.88.0
