### ISSUE TITLE
 OpenAI Assistant node new feat thread, vector store and file.

### ISSUE THREAD

**Issue by guilhermejansen** [n8n-io/n8n#10671]
This pull request introduces several key enhancements to the OpenAI Assistant node, significantly expanding its capabilities to manage threads, store vectors, and handle files. These enhancements aim to provide more comprehensive support for complex workflows involving OpenAI's API.

### Key Enhancements
1. **VectorStore Integration:**
   - Added the ability to associate a vector store with the OpenAI Assistant calls. This allows users to manage and retrieve vectors more efficiently within their workflows.

2. **Thread Management:**
   - Introduced functionality to manage thread IDs directly from the node. This enhancement facilitates better handling of conversations and interactions that require threading.

3. **File Handling:**
   - Implemented support for file IDs, enabling the node to handle files associated with specific threads or tasks. This addition enhances the node’s ability to manage documents and other file types.

4. **Role Specification:**
   - Users can now specify the role (`user` or `assistant`) when making calls, providing greater control over the interaction dynamics.

5. **Enhanced Input Options:**
   - Improved the 'Prompt' property with two selectable options: 'Take from previous node automatically' or 'Define below'. This enhancement provides users with greater flexibility in how they source and manage input data.

### Technical Implementation
- The `execute` function has been significantly modified to accommodate new properties such as `thread`, `vector`, `file`, and `role`.
- Handling of the assistant's capabilities has been refined to dynamically manage connected tools based on node inputs and execution context.

### Impact
These enhancements make the OpenAI Assistant node more robust and versatile for handling advanced workflows involving AI-driven interactions, data retrieval, and thread management. They cater to a broader range of use cases, promoting more dynamic and responsive automation strategies within n8n.

## How to Test
1. Configure the node with valid credentials and input data.
2. Set up scenarios to test each new property (`vector`, `thread`, `file`, `role`) in isolation and in combination.
3. Verify that the node behaves as expected, efficiently managing resources and maintaining consistent performance under various conditions.

## Screenshots 

![image](https://github.com/user-attachments/assets/7d802b4c-8524-4edf-84aa-ad40536d23b7)

![image](https://github.com/user-attachments/assets/b9387533-f977-4585-a143-6b6b54c0edd0)

![image](https://github.com/user-attachments/assets/f7f8e86c-218a-430c-afbb-28eafa763067)

![image](https://github.com/user-attachments/assets/fe5b3895-e28e-4e97-a555-09f6a24cfc55)

![image](https://github.com/user-attachments/assets/0a2a207e-6b25-4520-bf3e-b8cb447243e5)

_Originally posted by @guilhermejansen in https://github.com/n8n-io/n8n/issues/10631#issuecomment-2323755642_

**Comment by Joffcom** [comment]
Hey @guilhermejansen,

We have created an internal ticket to look into this which we will be tracking as "GHC-203"

**Comment by Joffcom** [comment]
Hey @guilhermejansen,

We don't need a ticket for the PR, Typically the approach would be to make an issue before a PR to talk about it first but in this case just the PR is ok. I am going to close this issue.
