### ISSUE TITLE
Problem in node ‘Qdrant Vector Store‘ 400 Bad Request: Wrong input: Not existing vector name error:

### ISSUE THREAD

**Issue by lwkask8** [n8n-io/n8n#10673]
finally

**Comment by Joffcom** [comment]
Hey @lwkask8,

We have created an internal ticket to look into this which we will be tracking as "GHC-204"

**Comment by Joffcom** [comment]
Hey @lwkask8, 

Can you complete the template we provide as you have not included any of the information from the form. For now I am going to close this one so we can make sure the data is there.
