### ISSUE TITLE
Failure to Load Multiple Custom Nodes

### ISSUE THREAD

**Issue by ybom77** [n8n-io/n8n#10699]
### Bug Description

When testing multiple custom nodes, I set the variable `N8N_CUSTOM_EXTENSIONS` to `/<path>/node-1/dist;/<path>/node-2/dist`. However, only the last custom node took effect. After reviewing the code, I found that using `;` to separate multiple paths is permitted. Nonetheless, during the node loading process, the `packageName` is consistently set to 'CUSTOM' (see image below), which causes the last node's name to overwrite the previous ones. Could this be a bug?

![image](https://github.com/user-attachments/assets/d59065e4-5882-4d78-bf0c-12270be2442e)

### To Reproduce

1.Create multiple n8n-nodes-starter instances.
2.Create nodes.
3.Package nodes.
4.Set N8N_CUSTOM_EXTENSIONS to multiple node paths.

### Expected behavior

The multiple node paths set by the variable N8N_CUSTOM_EXTENSIONS should be loaded correctly.

### Operating System

ubuntu 22.04

### n8n Version

1.55.0

### Node.js Version

20.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ybom77,

We have created an internal ticket to look into this which we will be tracking as "GHC-208"

**Comment by jarvisaoieong** [comment]
The problem still exists in version v1.114.3
