### ISSUE TITLE
On Safari on iOS 14, icons to modify each workflow step don’t work

### ISSUE THREAD

**Issue by asirota** [n8n-io/n8n#1070]
**Describe the bug**
Clicking on any of these UI items doesn't work on safari iOS. 

![image](https://user-images.githubusercontent.com/458134/96339413-8d655580-1062-11eb-8971-0583028a9fa0.jpeg)

**To Reproduce**
Open any workflow and try clicking on the UI items above each step. Nothing happens. 

Also executing workflow only works in landscape mode. Not portrait. 

**Expected behavior**
The expected behaviour for each UI item. 

**Environment (please complete the following information):**
 - OS: iOS 14, safari browser 
 - n8n Version 0.87
 - Node.js Version 12

**Additional context**
n8n is running on docker on a Synology NAS ds220+

**Comment by janober** [comment]
Thanks a lot for reporting this issue.

I also fixed many other issues like the most important one that the workflow could not be moved around. Experience is probably still not perfect (esp. as many icons are very small and hard to press) but worlds better than before.

I will update here once the new version got released.
