### ISSUE TITLE
Form templates are not using i18n translations

### ISSUE THREAD

**Issue by TaylorHo** [n8n-io/n8n#10716]
### Bug Description

The `handlebars` files located at `n8n/packages/cli/templates/` aren't using translations. Since it's something that appears in the UI, it would be great to have a way to translate this content, such in the `editor-ui`.

### To Reproduce

1. Access any file from `n8n/packages/cli/templates/`
2. See that the texts are hardcoded

### Expected behavior

Translations to be available also in forms.

### Operating System

Debian 12

### n8n Version

1.58

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @TaylorHo,

This sounds more like a feature request which would be better suited to our [forum](https://community.n8n.io/c/feature-requests/5) so we can track community requests. We do have plans in the future to support translations properly but at the moment if you are manually doing your translations this will also be a manual step.
