### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by suneetk92** [n8n-io/n8n#10728]
### Bug Description

Webhook + Respond to Webhook is resulting in [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) with the latest n8n version >=1.57.0

The same workflow is working fine till 1.56.2

### To Reproduce

```
{
  "meta": {
    "instanceId": "3bbb5eb527440d285b702982482fddd9fbd528aa6711cb410dfb9d10eb9f60cc"
  },
  "nodes": [
    {
      "parameters": {
        "respondWith": "json",
        "options": {
          "responseCode": 200
        }
      },
      "id": "28658438-e29c-499a-94af-f04e0403fefa",
      "name": "Respond to Webhook",
      "type": "n8n-nodes-base.respondToWebhook",
      "typeVersion": 1.1,
      "position": [
        820,
        860
      ]
    },
    {
      "parameters": {
        "path": "7b30ca2d-db12-43e5-88dd-1145363c148f",
        "responseMode": "responseNode",
        "options": {}
      },
      "id": "2395cdf7-6a62-4a0a-bd52-56cf3b2fb41f",
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 2,
      "position": [
        600,
        860
      ],
      "webhookId": "7b30ca2d-db12-43e5-88dd-1145363c148f"
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Respond to Webhook",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

### Expected behavior

Webhook + Respond to Webhook should work same as in 1.56.2

### Operating System

Alpine Linux v3.20.1 (docker)

### n8n Version

>=1.57.0

### Node.js Version

v20.15.0

### Database

PostgreSQL

### Execution mode

queue (1 master + 3 workers + 3 webhook nodes)

**Comment by Joffcom** [comment]
Hey @suneetk92,

We have created an internal ticket to look into this which we will be tracking as "GHC-212"

**Comment by luizeof** [comment]
Same here ... using Docker, n8n in queue mode ...

The nodes work, the webhook receives the data, the node responds to the webhook and executes but is not responded to by the request until it times out.

No error is generated, and the execution history shows that it was executed successfully.

**Comment by suneetk92** [comment]
> Same here ... using Docker, n8n in queue mode ...
> 
> The nodes work, the webhook receives the data, the node responds to the webhook and executes but is not responded to by the request until it times out.
> 
> No error is generated, and the execution history shows that it was executed successfully.

Exactly the same. I also have n8n in queue mode.
Just for testing, running the same version in normal mode is running fine.

**Comment by felipeslo** [comment]
![image](https://github.com/user-attachments/assets/ab18f60c-038b-45ca-a2b1-8a1776423344)

The webhook adds the task to the queue in Redis, the Worker picks up the task, executes it, and successfully saves it to the database. Meanwhile, the Webhook remains in an endless search for the response in the database.

**Comment by LeoPQDT** [comment]
I am facing the same issue too.
The workaround I found is set the Webhook to respond on Last Node Finishes and place an Aggregate node as a last node in order to wrap up the list content received for it in a single response attribute (Data for example).

**Comment by coroschina** [comment]
The same issue exists in version 1.58.1

**Comment by easydigi** [comment]
I also have the same problem.

**Comment by Joffcom** [comment]
The example workflow is working fine for me in `1.58.1`.

@coroschina @easydigi @LeoPQDT @luizeof can you all try the test workflow provided in `1.58.1` and see if you have the same issue.

My test was with Postgres DB and 4 workers.

**Comment by suneetk92** [comment]
It's the same issue with 1.58.1.

All versions after 1.57.0 are affected.

I also have postgresDB with 3 workers and 3 webhooks

**Comment by LeoPQDT** [comment]
> The example workflow is working fine for me in `1.58.1`.
> 
> @coroschina @easydigi @LeoPQDT @luizeof can you all try the test workflow provided in `1.58.1` and see if you have the same issue.
> 
> My test was with Postgres DB and 4 workers.

Hi Man, I'm running N8N in 1.58.1 and the same issue keep alive.

**Comment by easydigi** [comment]
> The example workflow is working fine for me in `1.58.1`.
> 
> @coroschina @easydigi @LeoPQDT @luizeof can you all try the test workflow provided in `1.58.1` and see if you have the same issue.
> 
> My test was with Postgres DB and 4 workers.

I am experiencing this problem under version 1.58.1.

**Comment by Joffcom** [comment]
Are you all using webhook workers?

**Comment by lucianodltec** [comment]
+1

**Comment by adrian-martinez-onestic** [comment]
+1

**Comment by felipeslo** [comment]
> Vocês todos estão usando webhook workers?

yes

**Comment by guibarbas** [comment]
I also have the same problem.

**Comment by bahoan** [comment]
I also have the same problem.

**Comment by ivov** [comment]
Can anyone with the issue please try this image to confirm the fix?

https://hub.docker.com/layers/n8nio/n8n/PR-10781-restore-queue-listeners-for-webhook-process/images/sha256-7afb760b0415b92abec7e20d318ff39f33b6701d7710bb5fdf6de8445c79f409

**Comment by adrian-martinez-onestic** [comment]
With my setup, I can replicate the issue for n8n versions >= 1.57.0, and using suggested image in the same setup fixes the issue.
