### ISSUE TITLE
Sendy node does not work for me

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#1072]
Hi, I try to test sendy node
But it responses nothing. Could you test it for this?
![sendy bug](https://user-images.githubusercontent.com/1112881/96358589-19df4900-1133-11eb-8925-299f291811da.png)

**Comment by janober** [comment]
Gets discussed in the forum so close it here:
https://community.n8n.io/t/i-can-not-add-subcribers-in-sendy-node/2727/2
