### ISSUE TITLE
Troubles when creating a new Header Auth Credential

### ISSUE THREAD

**Issue by qualvalordex** [n8n-io/n8n#10746]
### Bug Description

When I create a new Header Auth Credential
![image](https://github.com/user-attachments/assets/0ba91ed6-5372-4068-9aa8-ebc68ab3fa12)

I put "testKey" on Name and 1234 on Value as follows:
![image](https://github.com/user-attachments/assets/0fcb825f-9f93-47dc-a6d3-7647de41d054)

But when I save, the value is replaced by something weird:
![image](https://github.com/user-attachments/assets/a7ebc03c-954a-471a-a9a4-d8776a3522e1)

HELP

### To Reproduce

1. Go to Credentials
2. Click on "Add Credential"
3. Fill name with "testKey" and value with "1234"
4. Click on Save
5. Click to view the Credential
6. Click on "expression" and see the value replaced

### Expected behavior

The expected behavior is to save the correct value to BD.

### Operating System

Ubuntu 22.04

### n8n Version

1.57.0

### Node.js Version

20.15.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @qualvalordex,

We have created an internal ticket to look into this which we will be tracking as "GHC-217"

**Comment by Joffcom** [comment]
Hey @qualvalordex 

This is intentional the blank value we use is what we show to the front end so that the credentials can't be viewed.

Is this causing an issue when using the credential?

**Comment by Joffcom** [comment]
Moving to closed as working as expected
