### ISSUE TITLE
Facebook Lead Ads Trigger not working after update!

### ISSUE THREAD

**Issue by devsnit** [n8n-io/n8n#10793]
### Bug Description

Hi everyone,

After updating n8n to the latest version (1.58.1), the Facebook Lead Ads Trigger is no longer able to retrieve lead details. All of my workflows are now returning an error. The webhook is being triggered, but I receive the following error message:

Unsupported get request. Object with ID '1039213147374064' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api

This issue is affecting all of my workflows, which were functioning correctly before the update.
Has anyone else experienced this? Any advice or solutions would be greatly appreciated!

Thanks in advance!

### To Reproduce

Just create a new workflow add the Facebook Lead Ads Trigger and using the testing tool (https://developers.facebook.com/tools/lead-ads-testing/) try to trigger the workflow. 

### Expected behavior

It should receive the lead details

### Operating System

Ubuntu 22

### n8n Version

1.58.1

### Node.js Version

20.15

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @devsnit,

We have created an internal ticket to look into this which we will be tracking as "GHC-226"

**Comment by Joffcom** [comment]
Hey @devsnit,

Which version of n8n were you running before the update?

**Comment by devsnit** [comment]
1.49 or 1.50, didn't checked to be honest but it was 8 version or something behind

**Comment by Joffcom** [comment]
Hey @devsnit,

It looks like the node is working but the Facebook API is telling you that `1039213147374064` doesn't exist, Have you verified that it is there?

**Comment by devsnit** [comment]
Hi @Joffcom it seems the problem is from meta. https://developers.facebook.com/community/threads/539279861966705/ ... everyone is facing this issue

**Comment by devsnit** [comment]
Thanks
