### ISSUE TITLE
Response Format option for Azure OpenAI Chat Model node is missing.

### ISSUE THREAD

**Issue by nanbingxyz** [n8n-io/n8n#10816]
### Bug Description

Based on this [documentation](https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatazureopenai/), it appears Azure OpenAI Chat Model node does have Response Format option. However, when trying to find this option in the n8n UI (self-host), it appears to be missing.

### To Reproduce

1. Create a new workflow
2. Add a Basic LLM Chain.
3. Add an Azure OpenAI Chat Model node as a sub-node
4. Try to find Response Format option and see that it's missing

![CleanShot 2024-09-14 at 12 11 41@2x](https://github.com/user-attachments/assets/c70fe045-0bfc-42c0-b8c8-0c705ee9eb02)

### Expected behavior

1. Create a new workflow
2. Add a Basic LLM Chain.
3. Add an Azure OpenAI Chat Model node as a sub-node
4. Set Response Format to JSON

### Operating System

Ubuntu 22.04.4 LTS

### n8n Version

1.58.2

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nanbingxyz,

We have created an internal ticket to look into this which we will be tracking as "GHC-230"

**Comment by Joffcom** [comment]
Hey @nanbingxyz 

This is not really a bug with the n8n application and it is either a feature request which should be raised on our community support forum or an issue with the documentation which should be raised on our documentation GitHub repository.

I will have a chat with the AI team on Monday and see which option they would like to take unless they already have plans to add the option and the docs were just updated early.

**Comment by janober** [comment]
Fix got released with [`n8n@1.60.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.60.0)
