### ISSUE TITLE
Valid Notion page IDs are rejected

### ISSUE THREAD

**Issue by nihaals** [n8n-io/n8n#10831]
### Bug Description

Notion documents page IDs as being UUIDv4, however I have some page IDs that don’t have a 4 in the correct position. This means some Notion nodes reject the input even though the ID came directly from a Notion API response.

n8n’s regexes that neither the ID or the URL from the API response match:
https://github.com/n8n-io/n8n/blob/cef64329a9428bfa06b01deed050de02e6502433/packages/nodes-base/nodes/Notion/shared/descriptions/PageDescription.ts#L87-L128

### To Reproduce

1. Keep creating Notion pages until/find an existing page that doesn’t have a 4 in the expected position
2. Pass it into a page action node, for example archive page as an ID
3. Notice you get an error: “Page parameter's value is invalid. This is likely because the URL entered is incorrect [item 0]”

### Expected behavior

The page is archived.

### Operating System

Docker n8n:1.56.2

### n8n Version

1.56.2

### Node.js Version

Docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nihaals,

Can you share some URLs that show the errors? Notion page urls should be UUID 4 looking at their documentation.

**Comment by nihaals** [comment]
I think this might have changed within the past couple of weeks as the first page I just made wasn't a UUIDv4: https://www.notion.so/10336a9a827580b895e3f7ff1d3ea585 (the page is public).

**Comment by jshay21** [comment]
Yes, we are having the exact same issue here

**Comment by helbertparanhos** [comment]
same issue here
![2024-09-25 16_05_40-Window](https://github.com/user-attachments/assets/eafe88fe-0c6a-4925-9d29-de357529c093)

**Comment by Joffcom** [comment]
@jshay21 @helbertparanhos can you both upgrade to the newest release and see if you have the same issue, @helbertparanhos your issue looks to be different as Notion is returning a different error so it is likely that you have an issue in your workflow.

**Comment by jshay21** [comment]
Yes, the update fixed it. Thank you

**Comment by nihaals** [comment]
@Joffcom #10860 didn't fix this issue (see https://github.com/n8n-io/n8n/pull/10860#issuecomment-2356174554). Here's a simple workflow that reproduces the issue ("ERROR: Page parameter's value is invalid. This is likely because the URL entered is incorrect") on v1.60.1 using the ID from https://github.com/n8n-io/n8n/issues/10831#issuecomment-2352683065:
```json
{
  "nodes": [
    {
      "parameters": {},
      "id": "682aca11-cd31-4e04-a1a0-e82df830b2e2",
      "name": "Trigger",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        580,
        280
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "4f6cbbc6-562b-48a1-8d09-b0814671b5f6",
              "name": "id",
              "value": "10336a9a827580b895e3f7ff1d3ea585",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "785effe4-b5fb-40ca-af04-6b662b5c846c",
      "name": "Set ID",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        760,
        280
      ]
    },
    {
      "parameters": {
        "operation": "archive",
        "pageId": {
          "__rl": true,
          "value": "={{ $json.id }}",
          "mode": "id"
        }
      },
      "id": "baf6f8e3-69e2-4e62-a8e1-ffc7ac788319",
      "name": "Delete Notion page",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2.2,
      "position": [
        940,
        280
      ]
    }
  ],
  "connections": {
    "Trigger": {
      "main": [
        [
          {
            "node": "Set ID",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set ID": {
      "main": [
        [
          {
            "node": "Delete Notion page",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

**Comment by Joffcom** [comment]
@nihaals I was referring to this PR: https://github.com/n8n-io/n8n/pull/10938 which makes another change and is part of 1.61.0 which is the newest release.

**Comment by nihaals** [comment]
Ah, I thought you meant latest stable and didn't see that PR linking to this issue.
