### ISSUE TITLE
A scheduled workflow can't call an error workflow via settings

### ISSUE THREAD

**Issue by OlivierMary** [n8n-io/n8n#10835]
### Bug Description

Hi,

If a workflow start with an schedule trigger we can´t call an error workflow (workflow settings)

### To Reproduce

Setup an workflow which fail:
![image](https://github.com/user-attachments/assets/93ce9e45-97b8-443e-be04-4c7dd89e5464)

Setup a settings to this workflow to call another workflow on error:
![image](https://github.com/user-attachments/assets/75e558eb-37cf-418b-b2ec-f9294c7e4cea)

This error workflow will fail with this error:
![image](https://github.com/user-attachments/assets/29293e4c-33d9-449c-b109-d672ac59d6e5)

The error workflow:
![image](https://github.com/user-attachments/assets/078fd677-9ac1-422b-9bca-486c6c97271d)

And this line appear in n8n main logs:
`Error workflow execution blocked due to subworkflow settings`

### Expected behavior

No fail in error workflow

### Operating System

Docker

### n8n Version

1.22.6

### Node.js Version

the docker image ;)

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @OlivierMary,

We have created an internal ticket to look into this which we will be tracking as "GHC-238"

**Comment by OlivierMary** [comment]
I forgot 1 step:
- Enable the workflow :smile:

**Comment by Joffcom** [comment]
Hey @OlivierMary,

I have followed your steps but I am unable to reproduce this, Have you checked the settings for the workflow to make sure there are no settings blocking it?

I would also remove the Webhook from the error workflow as error workflows are not designed to be called with a webhook or active so that could be the issue as I didn't include the webhook in my error workflow.

**Comment by OlivierMary** [comment]
Hey @Joffcom same version ?

Which setting can block ?

All my possible settings with my version:
![image](https://github.com/user-attachments/assets/c56c74bc-9394-40db-8c1e-97d5e495fdff)

**Comment by Joffcom** [comment]
@OlivierMary they look ok, I take it you don't use workflow sharing?

Next step will be to upgrade your n8n to the latest release to see if the issue is there.

**Comment by OlivierMary** [comment]
@Joffcom ,

No, on-premise - Community Edition.

**Comment by Joffcom** [comment]
@OlivierMary in that case I would start by removing the webhook node and seeing if that helps, If it makes no difference update to the latest release which is what I have been testing this with.

**Comment by OlivierMary** [comment]
@Joffcom 

just test on `docker.n8n.io/n8nio/n8n:latest` on my local docker. with and withtout webhook there is no problem. will try on my server.

You can close for now, will reopen if pb happen on my server after upgrade (that can take a while)

Thanks !

**Comment by OlivierMary** [comment]
@Joffcom,

Just test with both 2 new workflow on my actual server and that work. 

So it's because another user than me created the 1 of the workflow ?

**Comment by Joffcom** [comment]
Hey @OlivierMary,

It could be if you have more than one user, If that is the case it would be expected as you don't have workflow sharing so you would need a different error workflow for each user.
