### ISSUE TITLE
Webhook node doesn't accept binary data

### ISSUE THREAD

**Issue by muslimanim** [n8n-io/n8n#10892]
### Bug Description

After upgrading to n8n 1.60.0 the file upload is not working in the Webhook node. It worked correctly when reverted back to version 1.59.3

### To Reproduce

1. Add a Webhook node
2. Change method to POST or PATCH
3. Set option "Field Name for Binary Data"
4. Test the workflow
5. Submit a multi-part form with any file to the workflow test URL

### Expected behavior

When the form is submitted, you should see in n8n execution the binary file you posted

### Operating System

Docker

### n8n Version

1.60.0

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @muslimanim,

We have created an internal ticket to look into this which we will be tracking as "GHC-243"

**Comment by janober** [comment]
Fix got released with [`n8n@1.61.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.61.0)
