### ISSUE TITLE
Asana Trigger Resource Error

### ISSUE THREAD

**Issue by jaitaiwan** [n8n-io/n8n#1090]
**Describe the bug**
The "Resource" field of the Asana Trigger node settings is not populated. Entering a resource manually like "Task" results in a 400 error from Asana's API as it expects the Resource type to be of type longint.

**To Reproduce**
1. Add Asana Trigger node
2. In the settings note that the list of workspaces appears correctly
3. Note that the "Resources" field is simply a text field and not a dropdown list

**Expected behavior**
The "Resources" field should be a dropdown list of possible resources or using the resource name such as "Task" will not create an API error.

**Environment (please complete the following information):**
 - OS: Docker Container n8nio/n8n:v0.88.1
 - n8n Version 0.88.1

**Comment by janober** [comment]
You can not type in anything like "Task" you have to type in the ID of the resource like "498346170860" like you wrote above.

Loading the resources automatically would in this case make no sense at there would, depending on the size of the organization, multiple thousand be loaded. That would not only be a huge problem performance-wise, it also means that it is harder to find the correct task in that small dropdown than simply copying the ID from the URL. 

And please do only post here if you are 100% sure it is a bug. Not without reason did we set up Github in that way that the only type that can be selected is "bug". Anything else, usage related questions, feature-requests (like this), .... always has to get posted in the forum https://community.n8n.io/ . Only if people follow that rule can we be sure that if other people face a similar issue they have one place, and only one, to look for a solution.

**Comment by jaitaiwan** [comment]
In that case @janober then you need to update your [workflow documentation](https://n8n.io/workflows/654) because this is the data you offer people copy:
```
{
  "id": "47",
  "name": "Receive updates when an event occurs in Asana",
  "nodes": [
    {
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "position": [
        250,
        300
      ],
      "parameters": {},
      "typeVersion": 1
    },
    {
      "name": "Asana-Trigger",
      "type": "n8n-nodes-base.asanaTrigger",
      "position": [
        1490,
        860
      ],
      "webhookId": "0de3b493-efb6-472c-9deb-80d28c89d28d",
      "parameters": {
        "resource": "Tweets",
        "workspace": "Engineering"
      },
      "credentials": {
        "asanaApi": "asana"
      },
      "typeVersion": 1
    }
  ],
  "active": false,
  "settings": {},
  "connections": {}
}
```

Notice how the resource is specified as `tweets` ? And now also note that an error comes back expecting a long. Either your documentation is wrong or it's a bug...
