### ISSUE TITLE
Redis doesn't have decrement operation

### ISSUE THREAD

**Issue by eduardonunesp** [n8n-io/n8n#10920]
### Bug Description

There's no DECR operation on Redis Node

### To Reproduce

Go to redis node look for decrement operation, isn't there 

### Expected behavior

To have the decrement https://redis.io/docs/latest/commands/decr/

### Operating System

Linux

### n8n Version

n8n@1.59.4

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @eduardonunesp,

We have created an internal ticket to look into this which we will be tracking as "GHC-248"

**Comment by Joffcom** [comment]
Hey @eduardonunesp,

I have just taken a quick look at this and it looks to be a feature request and not a bug, Would you be open to raise a feature request on the [community support forum ](https://community.n8n.io/c/feature-requests/5)?

We use GitHub to track bugs which we define as something that is there but not working, In this case the Decrement operation is something that would need to be added.

Let me know if you have any questions on this.
