### ISSUE TITLE
Can't active workflow with single RSS Feed Trigger node

### ISSUE THREAD

**Issue by NTLx** [n8n-io/n8n#10986]
### Bug Description

Workflow with single RSS Feed Trigger node, test run was OK, but can't Active, the Error message was: 
```
Workflow could not be activated:
There was a problem activating the workflow: "Invalid time value"
```

Screen Shot:
![image](https://github.com/user-attachments/assets/169277d5-dd83-4496-9a89-68fe4fd44bc2)

The RSS Feed URL:
https://rsshub.rssforever.com/google/scholar/"Confined+Placental+Mosaicism"+OR+"Uniparental+Disomy"+OR+"Imprintomics"

The Workflow JSON:
```json
{
  "meta": {
    "instanceId": "4a1946d731978808f812434e5f3ba9da873728265f5999342cbac96ba40552ce"
  },
  "nodes": [
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "hour": 10,
              "minute": 5
            }
          ]
        },
        "feedUrl": "https://rsshub.rssforever.com/google/scholar/\"Confined+Placental+Mosaicism\"+OR+\"Uniparental+Disomy\"+OR+\"Imprintomics\""
      },
      "id": "9685c1a8-ed4b-4d57-8250-64a2e24ee056",
      "name": "RSS Feed Trigger",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        760,
        460
      ]
    }
  ],
  "connections": {},
  "pinData": {}
}
```

### To Reproduce

1. Create an empty workflow.
2. Add a RSS Feed Trigger node.
3. Modify the `Feed URL` to: https://rsshub.rssforever.com/google/scholar/"Confined+Placental+Mosaicism"+OR+"Uniparental+Disomy"+OR+"Imprintomics"
4. Run `Test workflow`.
5. Active workflow.

### Expected behavior

If the test run is successful, it should also be able to activate normally.

### Operating System

Ubuntu Linux 20.04.6 LTS

### n8n Version

1.60.1

### Node.js Version

didn't know

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @NTLx,

We have created an internal ticket to look into this which we will be tracking as "GHC-260"

**Comment by Joffcom** [comment]
Hey @NTLx 

Can you share the env options you have set for TZ / Generic timezone?

**Comment by NTLx** [comment]
> Hey @NTLx
> 
> Can you share the env options you have set for TZ / Generic timezone?

Of course, I deployed n8n using docker-compose and added `TZ: "Asia/Shanghai"` to the environment variables.

**Comment by NTLx** [comment]
> Hey @NTLx
> 
> Can you share the env options you have set for TZ / Generic timezone?

The timezone setting in the workflow remains default, which is `Asia/Shanghai`.

**Comment by netroy** [comment]
Can you please try removing the quotes and try `TZ: Asia/Shanghai`?

**Comment by NTLx** [comment]
> Can you please try removing the quotes and try `TZ: Asia/Shanghai`?

I tried, but it still gives the same error.

**Comment by Joffcom** [comment]
Did you stop and start the container or restart it? Just incase you did a restart can you do a stop and start?

**Comment by netroy** [comment]
@NTLx Do you also have the env variable `GENERIC_TIMEZONE` set?

**Comment by netroy** [comment]
I found the issue. The RSS trigger node expects each item to contain an `isoDate` field, that is then used to incrementally load data. in the URL you shared, there are no timestamps in the items. There is only `lastBuildDate` on the response object, but we don't use that right now.

**Comment by NTLx** [comment]
> @NTLx Do you also have the env variable `GENERIC_TIMEZONE` set?

Yes, both `GENERIC_TIMEZONE` and `TZ` were set.

**Comment by NTLx** [comment]
> I found the issue. The RSS trigger node expects each item to contain an `isoDate` field, that is then used to incrementally load data. in the URL you shared, there are no timestamps in the items. There is only `lastBuildDate` on the response object, but we don't use that right now.

Well, I haven't tested other RSS URLs generated via RSSHub yet, so I'm not sure if this issue would also occur with other routes.

**Comment by netroy** [comment]
Just created a PR that reverts the assumption that we recently added that all RSS feeds have items with valid timestamps.
We'll try to get this backported as well.

**Comment by NTLx** [comment]
> Just created a PR that reverts the assumption that we recently added that all RSS feeds have items with valid timestamps. We'll try to get this backported as well.

Thank you very much, I look forward to trying it out after the updated version is released.

**Comment by netroy** [comment]
Just FYI: this node ignores all items without timestamps right now. So after the fix it out you'll be able to activate the workflow, but you won't see any data.

It might make sense to [open an issue with RSSHub](https://github.com/DIYgod/RSSHub/issues), to ask if the generated RSS on their end can include an `isoDate` or a `pubDate` timestamp on every item.

**Comment by NTLx** [comment]
> Just FYI: this node ignores all items without timestamps right now. So after the fix it out you'll be able to activate the workflow, but you won't see any data.
> 
> It might make sense to [open an issue with RSSHub](https://github.com/DIYgod/RSSHub/issues), to ask if the generated RSS on their end can include an `isoDate` or a `pubDate` timestamp on every item.

OK, thanks.
