### ISSUE TITLE
IF node type error with google calendar objects

### ISSUE THREAD

**Issue by JoshSchwarz** [n8n-io/n8n#1099]
**Describe the bug**
In my workflow if I have an IF node after google calendar string comparisons dont work as expected. Default behaviour results in a Type Error. 

When I select one of my google calendar nodes in the IF comparison I receive a Type Error ("Cannot read property 'toString' of undefined") when trying to do a string comparison.

However, if I then add another character in the expression I no longer receive a type error. 

I have not tested this issue with other nodes, but so far in normal use can only reproduce with google calendar.

**To Reproduce**
Make a workflow with google calendar getAll:events. 
Create an IF node following on from gCal. 
In the IF node select a string comparison and use an expression "{{$json["summary"]}}"
Compare to a random string (i.e. "test") and receive type error.

Change string comparison expression to "{{$json["summary"]}}_" and comparison now returns expected output.

**Expected behavior**
String comparison of google calendar objects to work in IF node with default expression.

**Environment (please complete the following information):**
 - OS: unRAID docker container
 - n8n Version 0.90.0
 - Node.js Version unsure

**Additional context**

[Test_1_typeerror.txt](https://github.com/n8n-io/n8n/files/5434834/Test_1_typeerror.txt)
[Test_1_working.txt](https://github.com/n8n-io/n8n/files/5434835/Test_1_working.txt)

**Comment by janober** [comment]
Thanks for reporting this.

I just tested the workflow that fails for you but it works totally fine for me. What you describe should only happen if the expression resolves to `undefined`. Sadly no idea why that happens in your case as "summary" should exist. 

Anyway for now, you can change the expression to:
```
{{$json["summary"] || ''}}
```

But I could reproduce the issue if I change the expression to for example "summary2" which does then also not exist for me. As it should not error in this case, rather treat is as an empty string by default, will we fix this issue.

**Comment by janober** [comment]
Got fixed and will be released with the next version. Will update here once it got released.

**Comment by janober** [comment]
Got released with n8n@0.91.0
