### ISSUE TITLE
No longer able to copy existing n8n public API Key from settings page

### ISSUE THREAD

**Issue by jimleuk** [n8n-io/n8n#11021]
### Bug Description

**User is unable to copy existing n8n public API key as no copy button exists and key is obfuscated in settings page.**
* I'm using docker self-hosted v1.61.0 version of n8n
* Not sure if my memory is failing me but I recall being able to copy this key at one point?
* It seems there is no way to retrieve the API key other than CLI or looking in the database.
* Please feel free to close this ticket if this is the intended behaviour.

---
**Screenshot**:
![image](https://github.com/user-attachments/assets/8f448068-af87-4c2b-b670-b8768f14740e)

### To Reproduce

1. Click into settings > n8n api
2. Create an API key if you haven't already
3. Navigate or refresh the page
4. Attempt to copy the existing API key

User is unable to copy the key. There doesn't seem to be a copy button and instructions are unclear as to how to reuse this API key.

### Expected behavior

I am able to copy and reuse this API key whether via a button or clicking on the key text.

### Operating System

Macos Sonoma

### n8n Version

1.61.0

### Node.js Version

20

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jimleuk,

We have created an internal ticket to look into this which we will be tracking as "GHC-266"

**Comment by Joffcom** [comment]
Hey @jimleuk,

This is intentional, we made a change to hide the API key once you first use it so you would need to make a note of it in a password manager or secrets manager.

If you need to copy the key again you would need to delete it and create a new one, If you want this to be changed I would recommend creating a feature request post on the forum.
