### ISSUE TITLE
workflows/1534-back-up-your-n8n-workflows-to-github/ not working and giving 404

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11034]
### Bug Description

Hi, your example workflow to backup does not work. I am using a fine grained permissions PAT from GitHub that has `contents` set to `read+write`. If that is not ok then the documentation should be clear about it, no?

### To Reproduce

1. Go to https://n8n.io/workflows/1534-back-up-your-n8n-workflows-to-github/
2. set credentials
3. run workflow

### Expected behavior

workflow to backup my stuff

### Operating System

Docker

### n8n Version

1.60.1

### Node.js Version

from docker.n8n.io/n8nio/n8n:latest

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

This doesn't appear to be a bug with n8n and is an issue with a specific workflow which would be better raised on the support forum.

Which node do you see the 404 error in and what is the exact error message from the node?

**Comment by Morriz** [comment]
Hi, thanks for the quick reply. It is ONLY in the last node that writes that the error is thrown: "Github Create".

**Comment by Joffcom** [comment]
@Morriz I have just followed your steps to reproduce and for me it appears to be working fine.

![image](https://github.com/user-attachments/assets/defc1777-4eb6-42b2-843b-f85b41a7bad0)

For my PAT I have it access to only the one repo and set Contents to Read & Write. Just to double check do you have the repo name and owner correct in the globals node? If I set the wrong Repository name I am able to get the same error message.

**Comment by Morriz** [comment]
I have the owner set to my own handle `Morriz` and the repo name I left to `n8n-backups`, which is an existing private repo.

But I now also notice that the "GitHub get file" node returns a "not found" error but it still continues? It seems this workflow is rather tacky and does not do any validation...who is responsible for the workflows you publish on your website?

<img width="878" alt="Screenshot 2024-10-01 at 12 19 15 PM" src="https://github.com/user-attachments/assets/9a31eae1-fcd7-4de1-9c20-e35ec9d3bbad">
