### ISSUE TITLE
MSSQL : result is not iterable (internal error)

### ISSUE THREAD

**Issue by SauerWorkflow** [n8n-io/n8n#11033]
### Bug Description

when we execute a query in the MSSQL node we get this error which has been recurring since version 1.56.1 to 1.60.1 :

n8n version

1.60.1 (Self Hosted)

Stack trace

TypeError: result is not iterable at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Sql/MicrosoftSql.node.js:218:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:670:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1100:20

### To Reproduce

on workflow :
add node MSSQL
when we execute a query insert in the MSSQL node we get this error that keeps coming back since version 1.56.1 to 1.60...
a simple insert with a single hard-coded field is enough to generate the problem
![Capture d’écran du 2024-10-01 11-27-43](https://github.com/user-attachments/assets/24830fd6-e20e-4435-80d7-fdbf9ff56eaf)

### Expected behavior

can you please correct this problem

### Operating System

docker

### n8n Version

1.60.1

### Node.js Version

20.15.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @SauerWorkflow,

We have created an internal ticket to look into this which we will be tracking as "GHC-271"

**Comment by janober** [comment]
Fix got released with [`n8n@1.65.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.65.0)
