### ISSUE TITLE
tool that returns binary borks AI Agent: add option to expect File type and make it return "OK" as text

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11069]
### Bug Description

An AI Agent using a tool that returns a binary throws an error about the size being too large (when the binary in question exceeds the max tokens of the llm in use).

Now, it should not be possible in the first place to make binary data end up in the agent thread IYAM, so that is a bug imo as no use case exists for it in that context.

The real use case to have a tool create a binary is obvious, but the current n8n platform won't allow it. However, it would be pretty trivial for the team to add an extra `File` option to the `Optimize Response > Expected Response Type` section, that just makes the tool respond with "OK" to the agent thread, but keeps the original buffer output available in subsequent nodes under `$('Create image').binary` (`Create image` being the name of the tool). I guess it also involves instructing the agent to accept "OK" as a successful finish.

That way we can all be happily implementing tools that return binaries.

### To Reproduce

1. Create a workflow with an AI Agent that calls an http tool that returns an binary of over 100k.
2. run it and observe the error

### Expected behavior

That the binary is not injected into the AI Agent thread.

### Operating System

Docker

### n8n Version

1.60.1

### Node.js Version

Docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-278"

**Comment by janober** [comment]
Fix got released with [`n8n@1.64.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.64.0)
