### ISSUE TITLE
Wrong Start Date with "Convert to ICS"

### ISSUE THREAD

**Issue by jpbaril** [n8n-io/n8n#11073]
### Bug Description

When converting items to ICal files (.ics) the event start date in the result is today's date instead of set start date item field.

![Capture d’écran du 2024-10-02 17-19-03](https://github.com/user-attachments/assets/1f6a621a-2eb3-4209-9fb1-408b936dceb5)
![Capture d’écran du 2024-10-02 17-19-30](https://github.com/user-attachments/assets/f0cfed87-72ef-43eb-8410-91278bd61e1c)

### To Reproduce

1. Use node "Convert to File".
2. Fill in fields.
3. Look at output file.

### Expected behavior

To have correct start date

### Operating System

docker (self-hosted)

### n8n Version

1.61.0

### Node.js Version

20.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jpbaril,

We have created an internal ticket to look into this which we will be tracking as "GHC-280"

**Comment by janober** [comment]
Fix got released with [`n8n@1.63.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.63.0)

**Comment by jpbaril** [comment]
"Start date" is now ok on 1.63.0.
I should maybe open a new ticket but now it's the "end date" for full day event that is wrong, it's one day later than what it should.
E.g. Christmas:
DTSTART;VALUE=DATE:20241225
DTEND;VALUE=DATE:20241227

**Comment by jpbaril** [comment]
https://github.com/n8n-io/n8n/issues/11192
