### ISSUE TITLE
Error when trying to load workflows for self hosted instance

### ISSUE THREAD

**Issue by renanpupin** [n8n-io/n8n#11084]
### Bug Description

I'm getting an error when trying to load the workflows page, all pages load except this one.
Initially this problem didn't happen, but after a few days it started happening even without making any changes to the architecture or deployment instance. It also seems to have an error on the rest endpoint related with users API.

`TypeError: Invalid URL "{ file: 'LoggerProxy.js', function: 'exports.error' }"`

N8N Version: 1.61.0
Deploy: self hosted docker instance

<img width="1040" alt="Captura de Tela 2024-10-03 às 19 27 51" src="https://github.com/user-attachments/assets/c84b4e08-78b6-40a4-b071-05553790570e">
<img width="775" alt="Captura de Tela 2024-10-03 às 19 28 08" src="https://github.com/user-attachments/assets/93f739e7-389a-4dee-a7af-7d1c2ccc4625">
<img width="1369" alt="Captura de Tela 2024-10-03 às 19 30 08" src="https://github.com/user-attachments/assets/9df3c810-6de4-4a19-8888-72e9aac9c90a">

### To Reproduce

1: Open n8n instance
2: Navigate to workflows
3: You can see the error

### Expected behavior

We expect to see the workflows list

### Operating System

Ubuntu linux 22

### n8n Version

1.61.0

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

main (default)

### Debug information

# Debug info

## core

- n8nVersion: 1.61.0
- platform: docker (self-hosted)
- nodeJsVersion: 20.17.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

Generated at: 2024-10-03T17:37:02.819Z

**Comment by Joffcom** [comment]
Hey @renanpupin,

We have created an internal ticket to look into this which we will be tracking as "GHC-282"

**Comment by Joffcom** [comment]
Hey @renanpupin 

I am not able to reproduce this using the instructions you have provided, I suspect this is going to be a configuration issue can you share the exact config you are using?

If you are using cloudflare can you make sure it is not caching.

**Comment by netroy** [comment]
Can you please share with us if you have set the `WEBHOOK_URL` or the `N8N_EDITOR_BASE_URL`, and if yes, can you please check if those are valid URLs.

**Comment by renanpupin** [comment]
@netroy I have the env variable WEBHOOK_URL setup, but not N8N_EDITOR_BASE_URL.
What is most weird is that these values haven't been changed since it was working before.
Only thing I did try yesterday, was upgrade n8n version and deploy again.

<img width="702" alt="Captura de Tela 2024-10-04 às 17 57 17" src="https://github.com/user-attachments/assets/91767736-fc18-46e0-a099-ad442f8c4f91">

**Comment by renanpupin** [comment]
> Hey @renanpupin
> 
> I am not able to reproduce this using the instructions you have provided, I suspect this is going to be a configuration issue can you share the exact config you are using?
> 
> If you are using cloudflare can you make sure it is not caching.

I am not using cloudflare, I have been using railway to deploy the docker container.

**Comment by renanpupin** [comment]
My url had not https:// at it's beginning, I tried to add it and then it worked. Most weird is that it was working before.
Thank you for the support!

**Comment by netroy** [comment]
> it was working before.

That sounds like we changed something recently that made the check for this stricter. let's keep the issue open to track what that change is, and to see if we can make the check backward compatible again.

**Comment by renanpupin** [comment]
Sure, count on me to help on the investigation. Maybe have a more explicit log message would help on this cases either.

**Comment by Joffcom** [comment]
Hey @renanpupin 

Just to check something you mentioned earlier, you had this issue on 1.61.0 and it was working ok but then without changing anything or upgrading n8n it started having issues?

**Comment by renanpupin** [comment]
@Joffcom previously I was using 1.49.0 version.
Related with the environment variable, it didn't change because my latest deploy was 3 months ago.
About the oauth credentials, I am using openAI, github and notion integrations.

**Comment by Joffcom** [comment]
@renanpupin perfect thanks, I think we need to update the config to mention the protocol is needed, In theory it should always have been the case as all of our documentation and examples include it so we should at least log a warning.

I will do some testing with older versions to see what happens.

**Comment by griseau** [comment]
Hey, 

I also just come across this issue when adding a new user, but the user doesn't accept the invitation yet (for you to be able to reproduce)
I had WEBHOOK_URL, and N8N_EDITOR_BASE_URL set, but without the protocol. 

The issue that it has created : 
- After adding a new user, the workflows page would never load and face the 500 error
- Users are not loading on the user page anymore (except the owner)
- When requesting a forget password link, nothing would get copied to the clipboard

I'm using 1.63.1

After setting the protocol, everything is working fine

**Comment by Joffcom** [comment]
@griseau yeah some kind of validation would be handy for the future, When you went through the env options available where did you find them? I am trying to work out where you spotted the list as that would be the first place to update as it would likely have solved the issue if you noticed it there.

For now as there isn't actually a bug here I am going to mark this as closed.

**Comment by griseau** [comment]
Sorry @Joffcom forgot to answer I was just looking at this [one](https://docs.n8n.io/hosting/configuration/environment-variables/endpoints/), without clicking on : see here for more details 😅
