### ISSUE TITLE
Crazy disk usage on database.sqlite - 18gb!

### ISSUE THREAD

**Issue by issmirnov** [n8n-io/n8n#1111]
**Describe the bug**
After running n8n with 3 lightweight RSS workflows, my disk space ran out on my VPS. Analysis shows the n8n docker instance taking up 22gb, with the `.n8n/database.sqlite` file using 18.8GB. 

**To Reproduce**
1. Run latest n8n using docker
2. Install the 3 sample workflows attached. Ultimately it's any RSS -> Webhook trigger
3. Let it run for 5 days.
4. Observe wild space usage

**Expected behavior**
My understanding is that n8n is a lambda/faas service, so I am deeply surprised why the database would blow up to 20+ GB in 5 days.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04.1, docker CE 19.03.13
 - n8n Version: 0.86.1-ubuntu
 - Node.js Version: N/A, whatever ships inside the docker container.

**Additional context**

![Screen Shot 2020-10-29 at 11 02 58 AM](https://user-images.githubusercontent.com/5771615/97622318-53d90680-19e1-11eb-8c16-9d03a788d013.png)
![Screen Shot 2020-10-29 at 11 18 24 AM](https://user-images.githubusercontent.com/5771615/97622323-54719d00-19e1-11eb-8096-e210eeb2d87d.png)

Sample workflow:

<details>
<summary>Deathworlders_RSS.json</summary>
{
  "name": "Deathworlders RSS",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "url": "https://www.reddit.com/search.rss?q=subreddit%3AHFY%20author%3AHambone3110%20Deathworlders&sort=new&restrict_sr=&t=all"
      },
      "name": "RSS Feed Read",
      "type": "n8n-nodes-base.rssFeedRead",
      "typeVersion": 1,
      "position": [
        450,
        400
      ]
    },
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        }
      },
      "name": "Cron",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        250,
        500
      ]
    },
    {
      "parameters": {
        "functionCode": "const staticData = this.getWorkflowStaticData('global');\n\nconst latestRead = staticData.latestRead;\n\nconst item = items[0];\n\nitem.json.latestRead = latestRead || '1970-01-01';\n\nreturn [item];\n\n"
      },
      "name": "Latest Read",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        650,
        400
      ]
    },
    {
      "parameters": {
        "functionCode": "const staticData = this.getWorkflowStaticData('global');\n\nif (items.length > 0) {\n  staticData.latestRead = items[0].json.isoDate || new Date().toISOString();\n}\n\n\nreturn items;"
      },
      "name": "Write Latest Read",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        1050,
        300
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{new Date($node[\"Latest Read\"].data[\"latestRead\"]).getTime()}}",
              "value2": "={{new Date($node[\"RSS Feed Read\"].data[\"isoDate\"]).getTime()}}"
            }
          ]
        }
      },
      "name": "IF",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        850,
        400
      ]
    },
    {
      "parameters": {
        "functionCode": "let messageText = '';\n\nfor (let item of items) {\n  messageText += `${item.json.title}\\n${item.json.link}`;\n}\n\nreturn [{json: {messageText}}];"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        1050,
        500
      ]
    },
    {
      "parameters": {
        "requestMethod": "POST",
        "url": "https://notify.smirnov.cloud/api/send",
        "options": {},
        "bodyParametersUi": {
          "parameter": [
            {
              "name": "message",
              "value": "={{$json[\"messageText\"]}}"
            },
            {
              "name": "apiKey",
              "value": "REDACTED"
            }
          ]
        }
      },
      "name": "Send to Telegram",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        1250,
        500
      ]
    }
  ],
  "connections": {
    "RSS Feed Read": {
      "main": [
        [
          {
            "node": "Latest Read",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Cron": {
      "main": [
        [
          {
            "node": "RSS Feed Read",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Latest Read": {
      "main": [
        [
          {
            "node": "IF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF": {
      "main": [
        [
          {
            "node": "Function",
            "type": "main",
            "index": 0
          },
          {
            "node": "Write Latest Read",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function": {
      "main": [
        [
          {
            "node": "Send to Telegram",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Start": {
      "main": [
        [
          {
            "node": "RSS Feed Read",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": "7"
}

</details>

**Comment by janober** [comment]
Actually sounds correct to me.

Lets take your "Deathworlders_RSS.json" workflow that pulls every minute 451 KB of data and then you save it. So if we calculate that is already:
5 days x 24h x 60 min x 0.451MB = 3.25 GB
Then there is also some other data from the other nodes lets round that up to 4 GB. You say you have 3 of those "lightweight" workflows running at the same time, then we are already at 12GB (3x4).

Again is a very rough calculation but 18GB for around 22k saved executions does not sound wrong to me.

The solution is to tell n8n to not save executions. You can do that either on a global level:
https://docs.n8n.io/reference/configuration.html#execution-data-error-success
or on a per workflow basis:
https://docs.n8n.io/reference/workflow.html#save-data-success-execution

If you really want to save each execution (successful or not) you can also configure n8n to automatically prune past executions after a while:
https://docs.n8n.io/reference/configuration.html#prune-data

In the future please post only here if you are 100% sure that it is a bug else post to the community forum here first:
https://community.n8n.io/
Only if we keep on doing that can we be sure that other people which have a similar problem in the future find the answer to their already previously asked question easily as then all of them are in a single location. Thanks!

**Comment by issmirnov** [comment]
Ah, interesting. I'll have to tune the parameters - thank you.

Re: forums. Understood, will keep in mind for the future - thank you for letting me know. Each project has a different priority for the forum vs github issues, so it's good to know that for n8n it's forum first, then github. Much appreciated!

**Comment by janober** [comment]
Glad to hear that it helped! Be however aware that even after changing these parameters and deleting the old executions the size of the database file will not shrink. That is sadly how SQLite works. Here a related ticket about that:
https://github.com/n8n-io/n8n/issues/819

But if you vacuum the database and change these parameters the file should never get that incredible large again.

Ah yes sorry. We probably still have to do some work to do about communicating that order.

Have fun with n8n!

**Comment by hazre** [comment]
Maybe this should be mentioned somewhere on the docs.. I came to find this today..
![image](https://user-images.githubusercontent.com/37149950/224506239-15be96e2-c0af-4665-9d41-1d72c4066c76.png)

**Comment by janober** [comment]
n8n is by default, configured in a way only to save failed executions. So by default, it should never get that large unless the default gets changed and all executions get saved.

Apart from does n8n offer configuration to vacuum automatically on startup:
https://docs.n8n.io/hosting/environment-variables/environment-variables/#sqlite
and pruning old execution data automatically:
https://docs.n8n.io/hosting/scaling/execution-data/#enable-data-pruning
