### ISSUE TITLE
Select all finished executions -> Delete -> off by 1

### ISSUE THREAD

**Issue by rthomas6charter** [n8n-io/n8n#11115]
### Bug Description

In n8n UI Executions view, when using the "select all ### finished executions" checkbox, and then clicking delete, all but 1 of the selected "finished executions" is deleted, but one remains (and has to be deleted separately).

### To Reproduce

1. Execute a workflow more than the number of times that would appear on a single page (~10).
2. Stop executing more workflows (so there is no ambiguity about how many finished executions exist).
3. Navigate to the `All Executions` page in the n8n UI
4. Verify that the `Load More` button appears at the bottom (to confirm the pagination threshold was exceeded).
5. Select all executions on current page using the checkbox at the top of the list (to the left of the `Name` column header).
6. Check the checkbox that appears above the list for `Select all 100 finished executions`
    * 100 is provided as an example.  The number could be anything over the number shown on one page.
7. Verify that the full count is represented in the `Delete / Clear selection` button box near the bottom of the page.
8. Click the `Delete` button
9. Click the `Yes, delete` button in the `Delete executions?` confirmation popup dialog.
10. Observe 99 of the 100 were deleted, but 1 wasn't.

### Expected behavior

All of the finished executions should get deleted without requiring an additional action of selecting the remaining one and deleting it too.

### Operating System

Official Docker Container - Base Image (Alpine?) linux/arm64

### n8n Version

1.61.0

### Node.js Version

18.19.1

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @rthomas6charter,

We have created an internal ticket to look into this which we will be tracking as "GHC-286"

**Comment by MarcL** [comment]
Now captured by internal issue PAY-2056.
