### ISSUE TITLE
Microsoft Outlook Send Message Bad API Use

### ISSUE THREAD

**Issue by advenimus** [n8n-io/n8n#11113]
### Bug Description

Appears that something is wrong with the use of the API in the node for send message. 

When using this node, emails are sent, hit M365 exchange and appear in sent folder (if selected to do so) but always return with an NDR stating: `Error: ‎550 5.7.708 Service unavailable. Access denied, traffic not accepted from this IP. For more information please go to http://go.microsoft.com/fwlink/?LinkId=526653 AS(7910)‎`

The NDR also shows: `Your message wasn't delivered because the recipient's email provider rejected it.`

After extensive testing and work with Microsoft, I can confirm it is something very specific to this node. Here's how I have come to that conclusion:
- When using an actual HTTP request with Oauth and sending emails that way, the issue occurs
- When using the Outlook node with Oauth and sending emails that way, issue occurs
- When using powershell from that same server to send using the same API request but the same body as the HTTP node body, it works fine!

![ScreenShot 2024-10-04 at 11 55 38@2x](https://github.com/user-attachments/assets/267f02fd-77f2-4673-b8cf-530fd7727c0f)
![ScreenShot 2024-10-04 at 11 56 31@2x](https://github.com/user-attachments/assets/4e25d2dd-21fe-4a72-a3d8-783958d57263)

### To Reproduce

1. Import my workflow and test both methods and test against M365 with a shared mailbox or user mailbox.
[Test_Outlook_Send.json](https://github.com/user-attachments/files/17261067/Test_Outlook_Send.json)

### Expected behavior

Expected email to be received, but not.

### Operating System

Ubuntu 24.04.1 LTS

### n8n Version

1.61.0

### Node.js Version

20.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @advenimus,

We have created an internal ticket to look into this which we will be tracking as "GHC-285"

**Comment by Joffcom** [comment]
Hey @advenimus 

That is very unusual, the error message from Microsoft looks very clear it is saying traffic is blocked from your n8n servers IP.

What I don't get though is why power shell works unless you are not sending the message using the same ip or for some reason poweshell is sending from a different public IP.

I have tried sending an email using the Outlook node from my n8n instance and it has worked as expected so I don't currently think this is a node issue.

Can you share the powershell commands you ran on your Ubuntu server so I can check them against what we do in the node?

**Comment by Joffcom** [comment]
Hey @advenimus 

Can you clarify on that? The node just uses the Microsoft API so wouldn't be doing any DKIM checks.

**Comment by advenimus** [comment]
Apologies, let me expand. 

So if your using a domain where you manage your own DNS with M365, then DKIM must be setup for use with Outlook REST API and Graph API, which is the underlying technology this node uses. It's not a requirement to add to docs I should say, but may be useful to throw in there in case anyone else has this issue.

**Comment by Joffcom** [comment]
Hey @advenimus 

Thanks for expanding, I will pass this to the docs team to consider. Maybe we can add it to a troubleshooting section, do you happen to have a link to the MS documentation that mentions this as I couldn't see anything
