### ISSUE TITLE
"Test Workflow" button starts Webhook node instead of Manual trigger when both are present

### ISSUE THREAD

**Issue by v-karbovnichy** [n8n-io/n8n#11121]
### Bug Description

"Test Workflow" button starts Webhook node instead of Manual trigger when both are present

Workflow:
![image](https://github.com/user-attachments/assets/dd9b2e03-e797-41ff-bbe2-f9e91da655b2)
Clicnking on "Test workflow" button:
![image](https://github.com/user-attachments/assets/a20fc5e1-da3c-427c-8365-7bb7affa8d72)

### To Reproduce

1. Create a new workflow
2. Add Manual Trigger node
3. Add Webhook node
4. Click on "Test Workflow" button
5. "Test Workflow" button changes caption to "Waiting for trigger event"

### Expected behavior

Manual Trigger node is executed. 
Webhook node is not executed.

### Operating System

Ubuntu 22.04

### n8n Version

1.59.3

### Node.js Version

idk, I use official docker image for n8n

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @v-karbovnichy,

We have created an internal ticket to look into this which we will be tracking as "GHC-290"

**Comment by Joffcom** [comment]
Hey @v-karbovnichy 

This is not really a bug as the workflow would need to start somehow and we can't guess which trigger you want to use.

We have a feature request open to allow you to select which trigger to use when manually launching a workflow which is what I think you are after. For now to set the trigger you want to use when testing you will need to disable the other trigger node.

I will link this issue up with the feature request but for now I am going to close this, let me know if you have any questions on this.

**Comment by v-karbovnichy** [comment]
There are multiple consistent mentions that clicking on "Test workflow" starts the workflow from Manual Trigger node only.

* when adding a new node:
![image](https://github.com/user-attachments/assets/aa2856fa-aafd-467b-8217-46025274c9ad)
* in the freshly created Manual Trigger node name:
![image](https://github.com/user-attachments/assets/01b1b28f-a4dc-472f-bb1a-d52cc82261f5)
* in node properties page (selected text):
![image](https://github.com/user-attachments/assets/ecde0a69-09da-4164-9bdc-27ec9e73e5c1)
* in the docs https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.manualworkflowtrigger/
(however, to be fair, there is a mention that things work this way when there's no other triggers)
![image](https://github.com/user-attachments/assets/7337053c-9f41-469f-9310-7fa19671e455)

So far you have 4 documented places that directly links "Test Workflow" button click and Manual Trigger node start. From the user perspective, it's "expected behavior". And system behaves differently.

>and we can't guess which trigger you want to use.

When there are multiple triggers (like several webhook nodes) you are right that you can't guess which one to start. To say more, "Test Workflow" button is the only way to fire listening on several webhooks: starting several Webhook nodes individually by a small node play button is not possible, only one would start listening, others will have play button disabled.
 
 Still, while n8n is starting all of the other trigger nodes, the Manual Trigger node is not triggered. 
 When you say "we can't guess", I understand that, and as a result of that thought all of the triggers fire. Except for the Manual Trigger one. Maybe we can rephrase the bug to "Manual Trigger node not starting while all other trigger nodes do that".
 
 What do you think?
