### ISSUE TITLE
I have wrong error notification from trello card comment

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#1113]
I use "bug node" to notify my bug in workflow
I received error of trello card comment node. When I check this, nothing 's wrong and comment created successfully
`ERROR: 400 - "invalid id"`

Could you check wrong notification for bug node?

**Comment by janober** [comment]
There was a bug in earlier versions of n8n that it reported errors on the wrong node in error-workflows. Please update to the latest n8n version. If that does not solve your problem please open the issue again.
