### ISSUE TITLE
OLLAMA embedding problem

### ISSUE THREAD

**Issue by lwkask8** [n8n-io/n8n#11144]
### Bug Description

After updating to the pre-release version 1.62.1 to make use of ollama's embbeding nodes, the error is showing:

Error in sub-node ‘Embeddings Ollama2’
input length exceeds maximum context length

There is not even an option to set the size in the ollama embedding node, remembering that the flows always worked normally only after updating that it stopped working

### To Reproduce

![ollama](https://github.com/user-attachments/assets/3cd63ad0-a7c6-49c7-b4ec-0fc2fa906d9e)

### Expected behavior

Other info
n8n version

1.62.1 (Self Hosted)

Time

07/10/2024, 14:35:32

Error cause

{ "error": "input length exceeds maximum context length", "status_code": 400, "name": "ResponseError", "attemptNumber": 7, "retriesLeft": 0 }

### Operating System

ubuntu 20.04

### n8n Version

1.62.1

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @lwkask8,

We have created an internal ticket to look into this which we will be tracking as "GHC-294"

**Comment by Joffcom** [comment]
Hey @lwkask8,

The team have taken a look and it looks like the error is coming back from Ollama to say you are exceeding the maximum content length this is likely to be down to the data being in a larger size than the model handle.

As this doesn't appear to be an issue with n8n itself I am going to move this to closed but if you have any questions on this let me know.

**Comment by AChaaChouh** [comment]
Hello, I am facing the same issue even when using nomic-embed-text embedding model which has a large context length, and my text does not come close to what the model should be able to handle.

**Comment by chipcrazy** [comment]
hi, 
I have the same problem using nomic-embed-text, has anyone solved this?
regards.

**Comment by RaafaRB** [comment]
Same boat usin mxbai-embed-large

**Comment by venetanji** [comment]
> Same boat using mxbai-embed-large.
> 
> EDIT: Maybe I'm just stupid, but 2 min after commenting here I switched the character splitter's (node attached to the vector store) chunk size from 3000 to 1000 and the workflow worked

The character splitter chunk size will affect the amount of **input tokens** you're tying to get the embedding of. mxbai-embed-large has max input token limit of 512, that's why it fails when you increase the chunk size. If you need to embed larger chunks you can try [nomic-embed-text](https://ollama.com/library/nomic-embed-text) (2k tokens) or https://ollama.com/library/bge-m3 (8k tokens)
