### ISSUE TITLE
HTTP Request Tool Node does not return response body on non-2xx response codes

### ISSUE THREAD

**Issue by a-d-r-i-a-n-d** [n8n-io/n8n#11172]
### Bug Description

When the HTTP Request Tool Node encounters non-2xx response codes, it returns the following generic message:
```json
{
  "response": "There was an error: \"Request failed with status code XXX\""
}
```

The node does not return the response body, which could contain critical information regarding the error. This is particularly problematic for AI Agents or other automated systems that rely on error messages to improve or fix subsequent requests.

For example, when calling Microsoft Graph Security REST API’s /v1.0/security/runHuntingQuery endpoint, the following response is received for a 400 Bad Request error:

```
{
  "error": {
    "code": "BadRequest",
    "message": "'where' operator: Failed to resolve table or column or scalar or graph expression named 'IPAddress'. Fix semantic errors in your query.",
    "innerError": {
      "date": "2024-10-08T22:59:29",
      "request-id": "b4d1eff2-14b8-xxxxx-8590-xxxxxx",
      "client-request-id": "b4d1eff2-xxxx-452f-8590-xxxxxx"
    }
  }
}
```

The message field contains valuable details on how to correct the request, but this is not returned by the node, only the status code.

### To Reproduce

	1.	Set up an HTTP Request Tool Node to call an API that returns a non-2xx status code
	2.	Ensure the request body contains a semantic error that triggers a 400 Bad Request response or similar.
	3.	Inspect the output of the node.

### Expected behavior

The HTTP Request Tool Node should return the entire response, including the response body, in order to provide detailed error information. This would allow the AI Agents to process and fix errors based on the response content. This might be a simple change that would make a huge difference from my point of view.

### Operating System

docker

### n8n Version

1.62.3

### Node.js Version

20.17.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @a-d-r-i-a-n-d,

We have created an internal ticket to look into this which we will be tracking as "GHC-296"

**Comment by a-d-r-i-a-n-d** [comment]
<img width="1719" alt="Screenshot 2024-10-12 at 22 31 19" src="https://github.com/user-attachments/assets/1244232e-e36a-4ae0-9ee3-131ea5ff7fb8">

Having the error message from the response body would have saved a significant amount of tokens in this example with plan and execute agent.
