### ISSUE TITLE
Meet on Node Google Calendar does not work

### ISSUE THREAD

**Issue by HermesMacedo** [n8n-io/n8n#11183]
### Bug Description

![image_error_meet](https://github.com/user-attachments/assets/16d0292d-dffa-4a52-89fb-11516950b6cd)

### To Reproduce

When selecting the conference data, creation and get do not work.

### Expected behavior

that displays conference data and creates a meet link.

### Operating System

Debian 12

### n8n Version

1.61.0

### Node.js Version

18

### Database

MySQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @HermesMacedo,

We have created an internal ticket to look into this which we will be tracking as "GHC-300"

**Comment by Joffcom** [comment]
This should be fixed in the next release

**Comment by janober** [comment]
Fix got released with [`n8n@1.64.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.64.0)
