### ISSUE TITLE
Wrong End Date output for all-day events with "Convert to ICS"

### ISSUE THREAD

**Issue by jpbaril** [n8n-io/n8n#11192]
### Bug Description

The Convert to File Node (Convert to ICS) output "end date" for all-day events is wrong, it's one day later than what it should.
E.g. Christmas:
DTSTART;VALUE=DATE:20241225
DTEND;VALUE=DATE:20241227

![Capture d’écran du 2024-10-09 14-42-39](https://github.com/user-attachments/assets/8f40d809-9aad-49fa-b75b-13d3a74fbb9c)

![Capture d’écran du 2024-10-09 14-43-27](https://github.com/user-attachments/assets/23cb4dd0-970e-45b9-a5e4-8015af82afc6)

### To Reproduce

1. Use node "Convert to File".
2. Fill in fields.
3. Look at output file.

### Expected behavior

To have correct end date, i.e. end date to be 1 day earlier.

### Operating System

docker (self-hosted)

### n8n Version

1.63.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jpbaril 

It looked ok when I tested it but I may have missed all day event.

What timezone and tz env option do you have set at the moment?

**Comment by jpbaril** [comment]
> Hey @jpbaril
> 
> It looked ok when I tested it but I may have missed all day event.
> 
> What timezone and tz env option do you have set at the moment?

      - GENERIC_TIMEZONE=America/Toronto
      - TZ=America/Toronto

**Comment by jpbaril** [comment]
> Are you using the ICS file in a calander or do you always manually parse them?

I'm not sure to understand (as English is not my main language).

**Comment by jpbaril** [comment]
[My_workflow.json](https://github.com/user-attachments/files/17355063/My_workflow.json)
[event.ics.txt](https://github.com/user-attachments/files/17355069/event.ics.txt)


# Debug info

## core

- n8nVersion: 1.63.0
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: 1f3e417e-92e0-4faf-9d1f-40d542cb15de

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

Generated at: 2024-10-13T09:23:19.921Z

**Comment by jpbaril** [comment]
BTW, if event is not an all-day event then resulting end date is ok.

**Comment by Joffcom** [comment]
@jpbaril how do you normally use the ICS files? When testing the current dates in a few different calendar applications they load as expected.

**Comment by jpbaril** [comment]
Right now until testing is conclusive I simply download the resulting ics file and open it in a text editor to validate date.
And as you can see in the provided workflow and resulting file above and screenshot below, I still get the issue by using the same bare bone 2-node workflow as you used. I also used nightly built docker images.
![Capture d’écran du 2024-10-15 13-20-40](https://github.com/user-attachments/assets/768f0e1f-2b7a-4a32-a14c-64e7457649b3)

But just to be sure I'm not wrongly assuming things, what is expected to be entered as value in n8n 'End' field, let say for all-day Christmas event?

**Comment by Joffcom** [comment]
Hey @jpbaril,

We have done testing internally with multiple cal options now and everything appears to be working as expected.

If you wanted to do all day Christmas you would have a start and an end of December 25th with All Day enabled, When using the file you will then see only one day in your cal.

If you select 25 and 26 like you have it will show as a 2 day even. Can you try and use the ICS file in whatever system you plan to use it in to see what that does as we don't think there is actually anything to fix here although it does look odd if you try to read it yourself.

Below is a screenshot of a cal event I have just exported for Christmas eve from Apple Cal, You will notice it does the same thing we do.

![image](https://github.com/user-attachments/assets/0c915898-6271-4d21-9e1c-9543469e1d73)

**Comment by jpbaril** [comment]
So, it seems it was just me wrongly assuming I would need to provide final "raw" dates to appear in the ics output file, but I understand now that is why the end date was "+1", your code already takes care of bringing the event end date to the next day as expected by ical standard for all-day events.
