### ISSUE TITLE
Redundant data being stored in database for nodes using collection and fixedCollection when parameter options are removed

### ISSUE THREAD

**Issue by Uro1** [n8n-io/n8n#1119]
**Describe the bug**
When nodes that employ parameters of the type 'collection' or 'fixedCollection' are used in a workflow and the collection options are attached with the workflow saved, the nodes in `workflow_entity` table in the database are stored as they should be.

For example, using the Zulip node with `Resource = Message` & `Operation = Update`, by adding all available `Update Fields` the node data is stored as:
```
[{"parameters":{},"name":"Start","type":"n8n-nodes-base.start","typeVersion":1,"position":[250,300]},{"parameters":{"operation":"update","updateFields":{"content":"","propagateMode":"changeOne","topic":""}},"name":"Zulip","type":"n8n-nodes-base.zulip","typeVersion":1,"position":[790,310]}]
```
With the `updateFields` object from the collection stored as:
```"updateFields":{"content":"","propagateMode":"changeOne","topic":""}```  

However, upon removing all of the collections' `Update Fields` from the node and saving thhe workflow again, the database entry for the `updateFields` object remains, resulting in an empty `updateFields` object stored in the database.

```
[{"parameters":{},"name":"Start","type":"n8n-nodes-base.start","typeVersion":1,"position":[250,300]},{"parameters":{"operation":"update","updateFields":{}},"name":"Zulip","type":"n8n-nodes-base.zulip","typeVersion":1,"position":[790,310]}]
```

This results in the `updateFields` stored in the database when it is not required:
```
"updateFields":{}
```

**To Reproduce**
1. In a new workflow add a Zulip node.
2. Change Resource parameter to Message.
3. Change Operation parameter to Update.
4. Add all available Update Fields.
5. Save the Workflow.
6. Check database entry for the workflow in `workflow_entity` database table.
7. Note the `updateFields` object.
7. In N8N, delete all `Update Fields` parameters.
8. Save the workflow again.
9. Refresh the database.
10. The workflow_entity row for the workflow will contain an empty `updateFields` object.

**Expected behavior**
Upon saving a node that uses collection or fixedCollection type parameters and after removing all available collection options, the collections' name object which is stored in the database should also be removed.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 2H20.
 - n8n Version [0.91.0]
 - Node.js Version [v12.16.1]

**Additional context**
This issue happens with nodes that use both `collection` & `fixedCollection` parameters, for anyone running a lot of workflows of these type the database is potentially storing redundant data.
To potentially save a little memory and database performance, by having n8n remove a collections' empty `name` object from the database will aid in both.  

In a custom node I am developing I use the IDataObject from a fixedCollection to populate a json array before pushing it into a body element in my payload.  
When the IDataObject returns an empty array in this way it makes an if check within my node return true instead of false which results in the passing of an array of empty objects into the body payload and on to the destination.  
At the destination (which I have no control over) the payload is being displayed incorrectly due to this array having empty objects rather than either containing objects with data or the array not being added to the payload at all.

This only happens after a user adds any of the nodes' collection options, saves the workflow and subsequently removes all of the collection options from the node. 

While it is a small issue, by altering the way n8n handles collection & fixedCollection object removal would be the ideal solution.

**Comment by krynble** [comment]
Hey @Uro1

Sorry about the long time it took to review this.

I was able to test and confirm that this is happening, but then I have 2 points to consider:

- Database space: this is really just a few bytes and should not be a big problem in general. 
- Having an empty `{}` actually is necessary as it's part of the expected behavior when we write nodes. I say this because the Zulip node, specifically, expects that the `updateFields` object exists. The keys are optional, but the object itself has to exist, empty if that's the case.

So the problem you are mentioning actually should be handled at node level, where you check if the properties you are expecting exist and are informed.

I tried making some changes in this regard but it would actually break more stuff than fix, so unfortunately it has to remain as is.

Please let me know if you can make these changes on node level on your side or if we can assist you in anything else.
