### ISSUE TITLE
Settings "On Error - Continue (using error output)" behavior incorrect, error output goes to 'Success Branch'

### ISSUE THREAD

**Issue by heroygt** [n8n-io/n8n#11202]
### Bug Description

When sub-workflow throw an error，the "Execute Workflow" node with settings "On Error - Stop Workflow" works fine.

But when change to "On Error - Continue (using error output)",  error output goes to 'Success Branch'
![image](https://github.com/user-attachments/assets/f43d75cb-12d9-4843-9a36-3ec7d1ebbb16)

### To Reproduce

1. set settings of "Execute Workflow" node into "On Error - Continue (using error output)" 
2. trigger "Stop and Error" node in sub workflow
3. main workflow goes to 'Success Branch'

### Expected behavior

main workflow goes to 'Error Branch'

### Operating System

Ubuntu

### n8n Version

1.62.3

### Node.js Version

18.16

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @heroygt,

We have created an internal ticket to look into this which we will be tracking as "GHC-303"

**Comment by Joffcom** [comment]
Hey @heroygt,

We were just trying to reproduce this and it looks like it is resolved, Are you able to upgrade and let me know if it is still an issue?
