### ISSUE TITLE
MySQL Node does not have an "success" output when using "insert"

### ISSUE THREAD

**Issue by avononit** [n8n-io/n8n#11220]
### Bug Description

When executing an MySQL Insert there should be the output "successful" when the insert was successful. Since the last Update (1.62.3) this is not the case anymore:

<img width="419" alt="image" src="https://github.com/user-attachments/assets/28c4b535-55a4-4b71-8246-258332f164b5">

### To Reproduce

1. Create MySQL Node
2. Use "insert"
3. Execute

### Expected behavior

Output should return "success" so the next Node will trigger

### Operating System

Ubuntu 24.04

### n8n Version

1.62.3

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @avononit,

We have created an internal ticket to look into this which we will be tracking as "GHC-305"

**Comment by ptn-aviation** [comment]
Update: The error seems to occur when using "On error - Continue (using error output"

**Comment by avononit** [comment]
Update: The problem only seems to occur when using "On error - Continue (using error output)"

When you use On error "Stop workflow" the output will return a "success"

**Comment by janober** [comment]
Fix got released with [`n8n@1.62.6`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.62.6)
