### ISSUE TITLE
OAuth Redirect URL has space in url

### ISSUE THREAD

**Issue by Toolfolks** [n8n-io/n8n#11239]
### Bug Description

Adding google OAuth Redirect URL it offers

OAuth Redirect URL = https://auto1-90sd.onrender.com
/rest/oauth2-credential/callback

It has a space in the url ( after .com )
Obviously I cant use this in the google settings.

Can’t see a way to change this BUG ???

### To Reproduce

I updated to 1.63.0.
Adding new credentials for Google Drive Auth.
Same Issue with callback pushbullet

### Expected behavior

No spaces in URL

### Operating System

Ubuntu

### n8n Version

1.63

### Node.js Version

??

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Toolfolks,

We have created an internal ticket to look into this which we will be tracking as "GHC-312"

**Comment by Joffcom** [comment]
Hey @Toolfolks 

Can you make sure that you don't have a space after the url in the env options, I have seen this happen a couple of times before where it just gets missed in the file.
