### ISSUE TITLE
[Node - Google Sheets V2]: Appending rows loads unnecessary data

### ISSUE THREAD

**Issue by soerenuhrbach** [n8n-io/n8n#11234]
### Bug Description

I'm using Google Sheets Node v2 to append rows to a single Google Sheet with more than 10.000 rows (and 35 columns) in that sheet. 

When running "update", "append" or "appendOrUpdate" operation leads to high memory when modifying sheets with a bigger amount of data. This results in performance and in worst case in out of memory exceptions. The n8n application crashes in my case.  

It seems that running all of these operations loads the whole spreadsheet before inserting. I understand, that it's necessary to load all rows for update operations. 

### To Reproduce

1. Create big set of data in google sheets with more than 10k rows and 35 columns.
2. Create a workflow to insert a single row in that google spreadsheet using "append" operation of Google Sheets v2 node
3. Run workflow 

### Expected behavior

My expectations for the "append" operations is ...

- appending rows doesn't require to load any other rows expect the key row to identify the columns
- the performance of the operation is not affected by the amount of data in the spreadsheet

### Operating System

Docker 

### n8n Version

1.63.1

### Node.js Version

20.10.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @soerenuhrbach,

We have created an internal ticket to look into this which we will be tracking as "GHC-310"

**Comment by soerenuhrbach** [comment]
I'll submit a pull request to fix that performance issues in a few days.

**Comment by Joffcom** [comment]
Hey @soerenuhrbach 

Does the operation have an option to make less api calls under the additional settings? This could help with the amount of data being loaded as we then change how we add the data.

If you are working with 10,000 rows and 35 columns I would recommend splitting the data into smaller chunks and using a sub workflow where possible which will help with the memory issues.

If you do decide to look into it and put in a pull request don't forget to update and include any new tests.

**Comment by soerenuhrbach** [comment]
@Joffcom I tried this option as well, but that didn't have any effect. I've already debugged the code. 

The operations always load all the data of a spreadsheet.

**Comment by soerenuhrbach** [comment]
-- 

The debugger shows pretty clear that the whole dataset (12.466 rows) is been loaded, even tough my workflows has only a single input item.

Debugger:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/2f4c6527-7688-45fa-a6f7-8b011281a6b2">

Workflow: 
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/12d1cd94-710c-4143-86ae-38956e81e4a0">

**Comment by michael-radency** [comment]
Hello @soerenuhrbach , thanks for your PR, you could also try to use "Minimise API Calls" option, as it could help with performance

**Comment by soerenuhrbach** [comment]
Hi @michael-radency, unfortunately it doesn't matter whether I active minimise api calls or not.. The linked line of code (see previous comments) show pretty well where the issue is.

**Comment by Joffcom** [comment]
Looks like the PR has been accepted and merged, I am going to mark this as closed. Thanks for the contribution 🙌🏻

**Comment by danberindei** [comment]
@Joffcom we have recently started using n8n and we the Google Sheets node to append rows to a table with 40k rows, and we see the append operation always takes more than 10 seconds (as opposed to make.com or Power Automate managing to insert the row in under 2 seconds most of the time). 

Is it because the PR was reverted with https://github.com/n8n-io/n8n/pull/11326, and n8n still reads 40k rows every time it append one row?
