### ISSUE TITLE
gitlab trigger Error

### ISSUE THREAD

**Issue by tengos** [n8n-io/n8n#1124]
**Describe the bug**
i run in docker mode in production server, i add a gitlab trigger, then copy the Webhook URLs, but anyway return the message:
422 - {"error":"Invalid url given"}

then i check the api, i found the Webhook URLs begins with "http://localhost......", i use the postman to test api and replace the host url with real ip address not begins with "localhost", it works !, so my question is how to change the Webhook URLs ? maybe something wrong with it

![image](https://user-images.githubusercontent.com/8084634/98085020-b20d5a00-1eb7-11eb-9cb6-c553cdeec908.png)

**Environment (please complete the following information):**
 - OS: [ Ubuntu Linux 18.04]
 - n8n Version [lastest]
 - Node.js Version [v12.14.1]

**Comment by tengos** [comment]
i need your help

**Comment by janober** [comment]
Please post your question to https://community.n8n.io/
GitHub issues is only for Bugs.
