### ISSUE TITLE
Error in function Node when retrieving from a in-memory vector store

### ISSUE THREAD

**Issue by marceltoma** [n8n-io/n8n#11256]
### Bug Description

I get an error in my function node when I try to use a in-memory vector store with a Vector Store Input

`const vectorStore = await this.getInputConnectionData('ai_vectorStore', 0);`

Error message in the node

NodeOperationError: Error in sub-node In-Memory Vector Store3 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1850:19 at processTicksAndRejections (node:internal/process/task_queues:95:5) at async Promise.all (index 0) at Proxy.getInputConnectionData (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:1857:19) at Proxy.getInputConnectionData (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2296:24)
Error in the in-memory vector store

context.getWorkflow is not a function
Error details
 Other info
    Item Index 0
    n8n version 1.62.4 (Self Hosted)
    Time 12/10/2024, 16:56:08
    Error cause {}

I posted the problem [here](https://community.n8n.io/t/error-in-function-node-when-retrieving-from-a-in-memory-vector-store/57457/1) but I guess I should have posted in here.

### To Reproduce

Create a function node and try to use use a vector store input using an in-memory vector store

### Expected behavior

SHould execute correctly

### Operating System

Windows 11 (docker)

### n8n Version

1.62.4

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @marceltoma,

We have created an internal ticket to look into this which we will be tracking as "GHC-316"

**Comment by Joffcom** [comment]
Hey @marceltoma 

As you have already raised this on the forum I am going to close this to prevent duplicate issues. This will also ensure that the team don't split the focus and we keep the attention in the one place. 

Let me know if you have any questions on this.
