### ISSUE TITLE
Failed to retrieve live execution rows in Postgres

### ISSUE THREAD

**Issue by maipal-c** [n8n-io/n8n#11255]
### Bug Description

Editor is now accessible via:
http://localhost:5678/
Failed to retrieve live execution rows in Postgres
Failed to retrieve live execution rows in Postgres

### To Reproduce
```
   N8N_AI_ENABLED: true
   N8N_AI_PROVIDER: openai
   # Database
   DB_TYPE: postgresdb
   DB_POSTGRESDB_HOST: postgresql-ha-pgpool.databases.svc.cluster.local
   DB_POSTGRESDB_DATABASE: n8n
   DB_POSTGRESDB_PORT: 5432
   DB_POSTGRESDB_POOL_SIZE: 2
   DB_POSTGRESDB_SCHEMA: n8n
   DB_POSTGRESDB_USER: n8n
   # Deployment
   N8N_VERSION_NOTIFICATIONS_ENABLED: false
   N8N_DIAGNOSTICS_ENABLED: false
   N8N_PUSH_BACKEND: websocket
   N8N_HIRING_BANNER_ENABLED: false
   N8N_PUBLIC_API_SWAGGERUI_DISABLED: false
   N8N_GRACEFUL_SHUTDOWN_TIMEOUT: 10
   N8N_REINSTALL_MISSING_PACKAGES: true
   # USER MANAGEMENT
   N8N_USER_MANAGEMENT_JWT_DURATION_HOURS: 24
   N8N_USER_MANAGEMENT_JWT_REFRESH_TIMEOUT_HOURS: -1
   # Endpoints
   N8N_PAYLOAD_SIZE_MAX: 16 # in MB
   N8N_ENDPOINT_REST: rest
   N8N_ENDPOINT_WEBHOOK: webhook
   N8N_ENDPOINT_WEBHOOK_TEST: webhook-test
   N8N_ENDPOINT_WEBHOOK_WAIT: webhook-wait
   # N8N_DISABLE_PRODUCTION_MAIN_PROCESS: true
   N8N_METRICS: true
   N8N_METRICS_PREFIX: n8n_
   N8N_METRICS_INCLUDE_CACHE_METRICS: true
   N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS: true
   N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL: true
   N8N_METRICS_INCLUDE_NODE_TYPE_LABEL: true
   N8N_METRICS_INCLUDE_API_ENDPOINTS: true
   N8N_METRICS_INCLUDE_API_PATH_LABEL: true
   N8N_METRICS_INCLUDE_API_METHOD_LABEL: true
   N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: true
   # Execution
   EXECUTIONS_DATA_PRUNE: true
   EXECUTIONS_DATA_MAX_AGE: 3760
   EXECUTIONS_DATA_PRUNE_MAX_COUNT: 10000
   # logs
   N8N_LOG_LEVEL: info
   CODE_ENABLE_STDOUT: true
   # queue mode
   QUEUE_BULL_PREFIX: n8n_core_queue_
   QUEUE_BULL_REDIS_CLUSTER_NODES: redis-cluster.cache.svc.cluster.local:6379
```
### Expected behavior

All Execxutions are executing normally. bt unable to see even single execution in UI (it shows only test executions)

### Operating System

amaon linux 2023 (arm64)

### n8n Version

1.62.1

### Node.js Version

dont know

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @maipal-c,

We have created an internal ticket to look into this which we will be tracking as "GHC-315"

**Comment by Joffcom** [comment]
Hey @maipal-c 

Do you have the option enabled to log workflow executions? Is that message what you are seeing when running n8n about not able to get live executions? 

As you are running in queue mode do the workers show any errors?

You don't need to set the `N8N_AI` variables as they don't do anything now.

**Comment by Joffcom** [comment]
Hey @maipal-c,

What do you have `TZ` and `GENERIC_TIMEZONE` set to, It sounds like maybe that is the issue although there was an old bug where the sorting wasn't handled correclty on the executions page but you are on a recent version so maybe just a browser refresh is needed.

As the executions are showing though it sounds like this is a different issue, Start by making sure your database and n8n have the correct timezone set, Check the workflow settings to make sure they are set to log the executions and clear your browser cache you should then be all good.

For now I think we can move this to closed, If there is still an issue after going over the above let me know.
