### ISSUE TITLE
Connections missing from workflows

### ISSUE THREAD

**Issue by tim-p1** [n8n-io/n8n#11273]
### Bug Description

When opening certain workflows, they have no connections and do not run correctly. Has happened so far to 2 different workflows

We've had to either redraw the connections or copy/paste from an earlier execution

![image](https://github.com/user-attachments/assets/2422317d-9f36-45d2-a4a9-62f89d3f4657)

### To Reproduce

1. Open workflow
2. See connections are missing

### Expected behavior

1. Open workflow
2. See connections are visible

### Operating System

Ubuntu 22.04 LTS

### n8n Version

v1.62.6

### Node.js Version

 docker

### Database

MySQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @tim-p1,

We have created an internal ticket to look into this which we will be tracking as "GHC-323"

**Comment by Joffcom** [comment]
Hey @tim-p1,

I have not been able to reproduce this, Did the workflows fail to run and which version did you upgrade from? If it happens on another workflow can you try and clear your browser cache and see if that changes anything.

**Comment by tim-p1** [comment]
Hi! They appeared to run as a schedule still without issue, but not via the front end, and of course if we changed anything and saved they would no longer run. I've already fixed that one so hard to retest, but I'll look for another example that is less important to do more testing

**Comment by npasslick** [comment]
Can confirm, the same bug occured to me just now. Not sure what caused it

**Comment by npasslick** [comment]
@Joffcom I did not update, it happened in a fresh installation. I edited and closed a workflow. When I opened the workflow again, all connections suddenly disappeared.

**Comment by ivov** [comment]
Closing here as not reproducible. Let us know if you can provide reproduction steps and we'll reopen.

**Comment by tanelaavistu** [comment]
Did anyone find a solution to this? We have this same issue on Ubuntu docker...

**Comment by tedraykov** [comment]
We have the same problem on a workflow running on the n8n cloud @ivov. The current running version of our instance is 1.67.1

**Comment by ivov** [comment]
1.67.1 is quite outdated, can you please upgrade to latest and see if it persists?
