### ISSUE TITLE
InvoiceNinja WebHooks do not work with version 5

### ISSUE THREAD

**Issue by m42e** [n8n-io/n8n#1128]
**Describe the bug**
Adding a Trigger for InvoiceNinja fails if the InvoiceNinja is Version 5

**To Reproduce**
1. Create a InvoiceNinja Trigger
2. Add an instance running  InvoiceNinja v5.
3. Execute the node.

**Expected behavior**
Register the webhook.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n 0.91.0
 - Invoiceninja 5.0.10

**Additional context**
The Issue seems related to an api change. InvoiceNinja previously had `/hooks` to register webhooks, now it is `/webhooks` (without changing the API version name).

**Question**
What would be the best solution, adding an additional Plugin for v5 (as there might be even more API changes) or do some version management inside the module?

**Comment by janober** [comment]
Thanks a lot for reporting!

No, a second node would not be added. If we would start doing that it would even become more messy and confusing. What we could do is to add a version selection on the node or maybe even better credentials.

**Comment by m42e** [comment]
Is there an example of how this could be done in another node? I want to give it a try :)

**Comment by krynble** [comment]
Hello @m42e sorry for the late response.

An example was created recently for Paddle where we had to switch between production or sandbox environment.

This was done here: https://github.com/n8n-io/n8n/pull/1777

**Comment by Joffcom** [comment]
Hey @m42e,

Bit of a delay here but we released support for Invoice Ninja v5 a couple of months ago with `n8n@0.200.0`. I am going to get this one marked as closed and if you get a chance to check it out and find any issues let me know.
