### ISSUE TITLE
Error When HTTP Request Node Gets Empty Response

### ISSUE THREAD

**Issue by sprankhub** [n8n-io/n8n#11283]
### Bug Description

In HTTP Request node version 4.2, I get the following error when the HTTP response is empty:

    TypeError: Cannot read properties of undefined (reading 'data') at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1842:33) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1141:20

My current workaround is to enable the "Include Response Headers and Status" option.

### To Reproduce

1. Add an HTTP Request node version 4.2.
2. Execute an HTTP request with an empty response.
3. Execute the node.
4. See above mentioned error.

### Expected behavior

No error should occur if the response is empty.

### Operating System

Cloud

### n8n Version

1.62.6

### Node.js Version

Cloud

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @sprankhub,

Do you have an example url that returns an empty response? I think the best option here would be if the request has no response throw an error and mention to use the include response headers / status option as our nodes rely on there being data to run.

**Comment by sprankhub** [comment]
In my case, this is https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-assignee-put. As you can see, it returns HTTP status code 204 No Content. I don't think there should be an error if the response is clearly empty. It is fine that subsequent nodes aren't executed if there is no output data. This can be fixed by using the "Always Output Data" option. However, sibling nodes should still be executed. But due to the current error, the whole execution of the workflow is stopped.

**Comment by Joffcom** [comment]
What if the response isn't meant to be empty though wouldn't you want to know which is where the error makes sense. If you are expecting no response then we have the options in place to work around that.

**Comment by Joffcom** [comment]
You are not wrong on a 204 response being valid as it is in the 200 range, I guess the tricky bit for us is we always expect data so we can link up the data. Maybe if it is a 204 we just output the input data 🤔 

I will pop a note on the internal ticket so we can think about the safest option, We should fix that error to make it clearer as a quick action.

**Comment by Joffcom** [comment]
Hey @sprankhub,

We have tried to reproduce this with https://httpbin.org/status/204 and https://httpstat.us/204 but they both appear to be working, In your environment do these 2 urls also fail?

**Comment by sprankhub** [comment]
@Joffcom, I tested this in a test workflow myself using https://httpstat.us/204. Unfortunately, I also cannot reproduce the issue then. I compared my failing node and the working node in my test workflow and cannot find any relevant changes. Do you have any better idea to reproduce it, looking at the call stack from my initial description?

**Comment by Joffcom** [comment]
Hey @sprankhub,

Oddly one of the other engineers took a look and was unable to reproduce it so we are not fully sure what happened.

**Comment by hmstein** [comment]
I'm running into this same issue. Vendor API gives us a 204 with no JSON in the body. n8n HTTP request node indicates an error, but the behavior is working as expected in the vendor's api. Additionally enabling the "Include Response Headers and Status" option is not working as a workaround. EDIT: Never Error is working

**Comment by b-buller** [comment]
- In the HTTP Request node 'Parameters' tab, scroll down to 'Options' and click 'Add option' and select 'Response'
- Turn on 'Include Response Headers and Status' and 'Never Error'.
