### ISSUE TITLE
Slack can not share channel with new ID

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#1130]
When I use slack node to invite user to a channel, I could share channel with "old ID". But it takes error when I share channel with "new ID"

- Slack Old ID channel: C2AA39T70
- Slack New ID channel: C01DR4H4B1V

Slack uses new ID for more channels in their system
Could you check this?

![n8n-⚠️-Contact-message-Receive-channel](https://user-images.githubusercontent.com/1112881/98344523-f3cc0b00-2045-11eb-9138-c22aeb2dbadb.png)

**Comment by RicardoE105** [comment]
This is quite weird as in the docs there is just one channel id. Maybe this is something related to permissions? 

https://api.slack.com/methods/admin.conversations.invite

**Comment by cmdntd** [comment]
I have the same user, same API, and public channel
The same error for "Close channel" with "new ID". But it is ok with "old ID"

**Comment by RicardoE105** [comment]
@cmdntd found the issue thanks to #1175. The node had a bug when inviting a user to a channel. It got fixed. We will let you know when is released.

**Comment by janober** [comment]
Fix got released with n8n@0.95.0
