### ISSUE TITLE
ssh node not closing file connections in temp folder

### ISSUE THREAD

**Issue by Surenthiran** [n8n-io/n8n#11303]
### Bug Description

![image](https://github.com/user-attachments/assets/28e3d86c-3980-45de-b4cd-d2cabac75b87)
am using ssh node to download the file from server and process it am not saving the downloaded file in anywhere in workflow. 
ssh node saves the file in temp folder and pass it to next node.
connection to file saved in temp folder created by ssh node is not closed properly those handles not closed until i restart n8n 
attached screen shows how many connections open 

when it comes around 8400 am getting following error from node

Error: EMFILE: too many open files,

### To Reproduce

try to download and process the file using ssh node. 

### Expected behavior

even after work flow completes connection to temp folder not closed properly. 

### Operating System

Winodws server 2019

### n8n Version

1.63.4

### Node.js Version

20.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Surenthiran,

We have created an internal ticket to look into this which we will be tracking as "GHC-329"
