### ISSUE TITLE
Invalid output when mapping to array

### ISSUE THREAD

**Issue by uiii** [n8n-io/n8n#11314]
### Bug Description

Not sure if I am doing anything wrong. I just tried to use n8n intuitively, I know JS so I started hacking straight away. But when I try to prepare a data for HTTP request node I struggle with mapping an array to values which contain array. The output array values are invalid as they are missing closing bracket. 

Here is just a simple example to demonstrate it:

![image](https://github.com/user-attachments/assets/51429f9c-111b-4c5f-8e72-fd8e6f4dc04f)

### To Reproduce

1. Go to any node
2. Edit any value
3. Put this expression in:
```
{
  "children":[{{[1,2,3].map(it => ([]))}}]
}
```
4. See the output
```
{
  "children":[[,[,[]
}
```

### Expected behavior

The output is valid JSON.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.63.4

### Node.js Version

22

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @uiii,

We have created an internal ticket to look into this which we will be tracking as "GHC-331"

**Comment by Joffcom** [comment]
Hey @uiii 

This should be fixed in 1.64.0 can you try updating and let me know if it resolves the problem.

**Comment by uiii** [comment]
Hi @Joffcom, thanks for the response. Is that version already released? I use docker.

**Comment by Joffcom** [comment]
Hey @uiii

Yeah that version was released last Wednesday: https://hub.docker.com/layers/n8nio/n8n/1.64.0/images/sha256-06ee93c4c11b98ab95aa0b93be9e0d4af2b8a2fd39d7442368eb046bb982b8b1?context=explore

**Comment by uiii** [comment]
Thanks, as it was prerelease I had to set the version specificaly. The issue is fixed thanks.
