### ISSUE TITLE
Specify a compatible Node engine version in package.json

### ISSUE THREAD

**Issue by VxJasonxV** [n8n-io/n8n#11313]
### Bug Description

The Node version in `engines {}` specifies any version greater than or equal to Node 20.15: https://github.com/n8n-io/n8n/blob/321d6deef18806d88d97afef2f2c6f29e739ccb4/package.json#L6

When n8n is deployed on a system where the version of Node used is dynamic (e.g. virtually every PaaS, managed app host, etc.), it always picks the latest stable release of Node, which as of this writing is Node 23.0.0. Later in n8n's own code, execution aborts because n8n doesn't support Node 23: https://github.com/n8n-io/n8n/blob/321d6deef18806d88d97afef2f2c6f29e739ccb4/packages/cli/bin/n8n#L27-L32

Please update the Node engine specification to match your in-application version logic's needs.

### To Reproduce

1. Deploy n8n onto your favorite application host.
2. Assuming a successful build, run the application, observe the output:
```	
==> Requesting Node.js version >=20.15
==> Using Node.js version 23.0.0 via package.json
==> Running 'pnpm run start'

> n8n-monorepo@1.63.0 start:default
> cd packages/cli/bin && ./n8n


	Your Node.js version 23.0.0 is currently not supported by n8n.
	Please use Node.js v18.17.0 (recommended), v20, or v22 instead!

 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

A successfully running deployment of n8n, using an appropriate version of Node, in environments where Node is dynamically installed based off `package.json` definition. 

### Operating System

Debian Bookworm 12

### n8n Version

1.64.0

### Node.js Version

23.0.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @VxJasonxV,

We have created an internal ticket to look into this which we will be tracking as "GHC-330"

**Comment by joepolask86** [comment]
How is this affecting my n8n on Render. 

ELIFECYCLE  Command failed with exit code 1.
==> Requesting Node.js version >=20.15
==> Using Node.js version 23.0.0 via /opt/render/project/src/package.json
==> Docs on specifying a Node.js version: https://render.com/docs/node-version
==> Running 'pnpm run start'
> n8n-monorepo@1.63.0 start /opt/render/project/src
> run-script-os
> n8n-monorepo@1.63.0 start:default
> cd packages/cli/bin && ./n8n
	Your Node.js version 23.0.0 is currently not supported by n8n.
	Please use Node.js v18.17.0 (recommended), v20, or v22 instead!
	
 ELIFECYCLE  Command failed with exit code 1.
 
 I can't build stuff on N8N
 
Bad Gateway
Request ID: 8d53cdbde42a1ba5-MAD

**Comment by VxJasonxV** [comment]
You can specify a specific version of Node to use with a higher precedence than the `package.json` definition.

I filed this because you shouldn't have to, but there are workarounds available.

**Comment by VxJasonxV** [comment]
https://github.com/n8n-io/n8n/blob/0e74dd0d9ec05d46ad6ebb609126867817dc81af/packages/cli/package.json#L45

<= 22 is interesting, because it will match 22.0.0, but not the probably much more desired current release in that series 22.10.0 as of this writing, nor any of the other updates in between. Wouldn't that be better expressed as `< 23`?

**Comment by netroy** [comment]
from the testing I did, `<= 22` matched all versions of 22.x

**Comment by VxJasonxV** [comment]
```
==> Using Node.js version 22.10.0 via environment variable NODE_VERSION
==> Docs on specifying a Node.js version: https://render.com/docs/node-version
==> Running 'pnpm run start'
> n8n-monorepo@1.64.0 start /opt/render/project/src
> run-script-os
> n8n-monorepo@1.64.0 start:default
> cd packages/cli/bin && ./n8n
No encryption key found - Auto-generated and saved to: /opt/render/.n8n/config
(node:138) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Initializing n8n process
n8n ready on 0.0.0.0, port 5678
Migrations in progress, please do NOT stop the process.
Starting migration InitialMigration1588102412422
Finished migration InitialMigration1588102412422
Starting migration WebhookModel1592445003908
Finished migration WebhookModel1592445003908
Starting migration CreateIndexStoppedAt1594825041918
Finished migration CreateIndexStoppedAt1594825041918
Starting migration MakeStoppedAtNullable1607431743769
Finished migration MakeStoppedAtNullable1607431743769
Starting migration AddWebhookId1611071044839
Finished migration AddWebhookId1611071044839
Starting migration CreateTagEntity1617213344594
Finished migration CreateTagEntity1617213344594
==> Your service is live 🎉
Starting migration UniqueWorkflowNames1620821879465
Finished migration UniqueWorkflowNames1620821879465
Starting migration AddWaitColumn1621707690587
Finished migration AddWaitColumn1621707690587
Starting migration UpdateWorkflowCredentials1630330987096
Finished migration UpdateWorkflowCredentials1630330987096
Starting migration AddExecutionEntityIndexes1644421939510
Finished migration AddExecutionEntityIndexes1644421939510
Starting migration CreateUserManagement1646992772331
Finished migration CreateUserManagement1646992772331
Starting migration LowerCaseUserEmail1648740597343
Finished migration LowerCaseUserEmail1648740597343
Starting migration CommunityNodes1652254514001
Finished migration CommunityNodes1652254514001
Starting migration AddUserSettings1652367743993
Finished migration AddUserSettings1652367743993
Starting migration AddAPIKeyColumn1652905585850
Finished migration AddAPIKeyColumn1652905585850
Starting migration IntroducePinData1654089251344
Finished migration IntroducePinData1654089251344
Starting migration AddNodeIds1658930531669
Finished migration AddNodeIds1658930531669
Starting migration AddJsonKeyPinData1659888469333
Finished migration AddJsonKeyPinData1659888469333
Starting migration CreateCredentialsUserRole1660062385367
Finished migration CreateCredentialsUserRole1660062385367
Starting migration CreateWorkflowsEditorRole1663755770892
Finished migration CreateWorkflowsEditorRole1663755770892
Starting migration WorkflowStatistics1664196174000
Finished migration WorkflowStatistics1664196174000
Starting migration CreateCredentialUsageTable1665484192211
Finished migration CreateCredentialUsageTable1665484192211
Starting migration RemoveCredentialUsageTable1665754637024
Finished migration RemoveCredentialUsageTable1665754637024
Starting migration AddWorkflowVersionIdColumn1669739707124
Finished migration AddWorkflowVersionIdColumn1669739707124
Starting migration AddTriggerCountColumn1669823906993
Finished migration AddTriggerCountColumn1669823906993
Starting migration MessageEventBusDestinations1671535397530
Finished migration MessageEventBusDestinations1671535397530
Starting migration RemoveWorkflowDataLoadedFlag1671726148419
Finished migration RemoveWorkflowDataLoadedFlag1671726148419
Starting migration DeleteExecutionsWithWorkflows1673268682475
Finished migration DeleteExecutionsWithWorkflows1673268682475
Starting migration AddStatusToExecutions1674138566000
Finished migration AddStatusToExecutions1674138566000
Starting migration CreateLdapEntities1674509946020
Finished migration CreateLdapEntities1674509946020
Starting migration PurgeInvalidWorkflowConnections1675940580449
Finished migration PurgeInvalidWorkflowConnections1675940580449
Starting migration MigrateExecutionStatus1676996103000
Finished migration MigrateExecutionStatus1676996103000
Starting migration UpdateRunningExecutionStatus1677237073720
Finished migration UpdateRunningExecutionStatus1677237073720
Starting migration CreateVariables1677501636752
Finished migration CreateVariables1677501636752
Starting migration CreateExecutionMetadataTable1679416281777
Finished migration CreateExecutionMetadataTable1679416281777
Starting migration AddUserActivatedProperty1681134145996
Finished migration AddUserActivatedProperty1681134145996
Starting migration RemoveSkipOwnerSetup1681134145997
Finished migration RemoveSkipOwnerSetup1681134145997
Starting migration MigrateIntegerKeysToString1690000000002
Finished migration MigrateIntegerKeysToString1690000000002
Starting migration SeparateExecutionData1690000000010
Finished migration SeparateExecutionData1690000000010
Starting migration FixMissingIndicesFromStringIdMigration1690000000020
Finished migration FixMissingIndicesFromStringIdMigration1690000000020
Starting migration RemoveResetPasswordColumns1690000000030
Finished migration RemoveResetPasswordColumns1690000000030
Starting migration AddMfaColumns1690000000030
Finished migration AddMfaColumns1690000000030
Starting migration CreateWorkflowNameIndex1691088862123
Finished migration CreateWorkflowNameIndex1691088862123
Starting migration CreateWorkflowHistoryTable1692967111175
Finished migration CreateWorkflowHistoryTable1692967111175
Starting migration ExecutionSoftDelete1693491613982
Finished migration ExecutionSoftDelete1693491613982
Starting migration DisallowOrphanExecutions1693554410387
Finished migration DisallowOrphanExecutions1693554410387
Starting migration AddWorkflowMetadata1695128658538
Finished migration AddWorkflowMetadata1695128658538
Starting migration ModifyWorkflowHistoryNodesAndConnections1695829275184
Finished migration ModifyWorkflowHistoryNodesAndConnections1695829275184
Starting migration AddGlobalAdminRole1700571993961
Finished migration AddGlobalAdminRole1700571993961
Starting migration DropRoleMapping1705429061930
Finished migration DropRoleMapping1705429061930
Starting migration RemoveFailedExecutionStatus1711018413374
Finished migration RemoveFailedExecutionStatus1711018413374
Starting migration MoveSshKeysToDatabase1711390882123
[MoveSshKeysToDatabase1711390882123] No SSH keys in filesystem, skipping
Finished migration MoveSshKeysToDatabase1711390882123
Starting migration RemoveNodesAccess1712044305787
Finished migration RemoveNodesAccess1712044305787
Starting migration CreateProject1714133768519
Finished migration CreateProject1714133768519
Starting migration MakeExecutionStatusNonNullable1714133768521
Finished migration MakeExecutionStatusNonNullable1714133768521
Starting migration AddActivatedAtUserSetting1717498465931
Finished migration AddActivatedAtUserSetting1717498465931
Starting migration AddConstraintToExecutionMetadata1720101653148
Finished migration AddConstraintToExecutionMetadata1720101653148
Starting migration CreateInvalidAuthTokenTable1723627610222
Finished migration CreateInvalidAuthTokenTable1723627610222
Starting migration RefactorExecutionIndices1723796243146
Finished migration RefactorExecutionIndices1723796243146
Starting migration CreateAnnotationTables1724753530828
Finished migration CreateAnnotationTables1724753530828
Starting migration AddApiKeysTable1724951148974
Finished migration AddApiKeysTable1724951148974
Starting migration CreateProcessedDataTable1726606152711
Finished migration CreateProcessedDataTable1726606152711
Starting migration SeparateExecutionCreationFromStart1727427440136
Finished migration SeparateExecutionCreationFromStart1727427440136
Starting migration AddMissingPrimaryKeyOnAnnotationTagMapping1728659839644
Finished migration AddMissingPrimaryKeyOnAnnotationTagMapping1728659839644
Version: 1.64.0
Editor is now accessible via:
http://localhost:5678/
```

```
==> Using Node.js version 23.0.0 via environment variable NODE_VERSION
==> Docs on specifying a Node.js version: https://render.com/docs/node-version
==> Running 'pnpm run start'
> n8n-monorepo@1.64.0 start /opt/render/project/src
> run-script-os
> n8n-monorepo@1.64.0 start:default
> cd packages/cli/bin && ./n8n
Your Node.js version 23.0.0 is currently not supported by n8n.
Please use a Node.js version that satisfies the following version range: >=18.17 <= 22
 ELIFECYCLE  Command failed with exit code 1.
```

Well, I can't argue with that even if that's not my understanding of semver. My understanding is that unspecified minor or patch versions are supposed to be expanded to `0`, and `<= 22.0.0` shouldn't match `22.10.0`. That said, for purposes of this issue I'm not going to argue it should be different, because it's clearly getting past the evaluation.

Thank you very much for this change.

**Comment by netroy** [comment]
We actually prefer to not define a max nodejs version at the root level because we are constantly working to make sure that n8n is ready for all future stable versions of node.
That way if any contributor wants to develop on node 23, we are likely to catch issues early on.

I don't know how your builds are setup, but if you are still using pnpm, I'd recommend using `pnpm deploy` [like we do for our custom images](https://github.com/n8n-io/n8n/blob/master/docker/images/n8n-custom/Dockerfile#L21).

**Comment by VxJasonxV** [comment]
Builds are dynamic based on a handful of factors, but for the Node version it is dependent on (in descending order of precedence):
1. An environment variable named `NODE_VERSION`
2. A file in the root directory named `.node-version`
3. A file in the root directory named `.nvmrc`, and absent all those;
4. The contents of the `engines: {node:}` section of the root directory's `package.json`

Using `pnpm`, `npm`, or any other build tool is irrelevant because the Node version selection will have already happened before the build command is even run. The runtime version/environment is selected first based off the aforementioned rules, and then the build/run execution takes place inside of that. The image you linked to explicitly specifies Node 20 as the very first step, which is the exact mitigation analogous the point I'm making here.

I don't agree with the statement that the current solution is ok and contributor friendly, because this project has logic that exits when used under Node 23 ( https://github.com/n8n-io/n8n/blob/fd3254d5874a03b57421246b77a519787536a93e/packages/cli/bin/n8n#L29-L33 ), any contributor has to undo/modify that anyway.

**Comment by netroy** [comment]
> the Node version selection will have already happened before the build command is even run.

That's a valid point. Let me get back to you tomorrow.

**Comment by VxJasonxV** [comment]
Because I don't want to force you into a Render-specific solution here, I did research on a handful of service hosts to see how they manage this and approach as vendor-agnostic a solution as possible.

I previously laid out how Render determines the Node Version to use ( https://github.com/n8n-io/n8n/issues/11313#issuecomment-2477618714, https://docs.render.com/node-version ), a descending order list but Nº1 is Render specific, Nºs 2 and 3 are not files that currently exist in this repository, so Nº4 (`package.json engines:{node:}`) is used when deploying this application assuming no end-user override. Render would default to the latest LTS if not specified.

Heroku exlusively uses the `engines` section of `package.json` ( https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version ) and that likely means that deploying n8n on Heroku has similar failures as we (Render) have been experiencing.

Vercel also consults the `engines` section which if specified will override what is selected in the web interface, but if I'm understanding their documentation correctly they cap at the latest 20.x series ( https://vercel.com/docs/functions/runtimes/node-js/node-js-versions ), so I think they will not be impacted because they won't run version 23 (nor even 22).

Fly.io uses Docker, and Railway uses Docker or nixpacks (but nixpacks appear to result in Docker enviroments so I don't think this has to be considered as a special case), so they are assuaged by either (1) using your provided images that will set a fixed version of Node, or (2) a general Docker+Node environment would also use a fixed version of Node, which they are in control of from the start (e.g. `FROM node:20`).

**Comment by VxJasonxV** [comment]
Should this issue be reopened if you're considering doing further work on it

**Comment by stephen-kruger** [comment]
Is there any resolution on this?
 Whilst I respect the n8n teams' decision to "we are moving to Docker" it does not mean we should ALL need to jump through hoops for local node development, where using Docker is an absolute pain.
For local dev, local is still easiest. How can we work around this versioning issue?

**Comment by netroy** [comment]
> Should this issue be reopened if you're considering doing further work on it?

This looks like miscommunication. Very few (if any) internal contributors are using containers for the development process.

> How can we work around this versioning issue?
You could either install node 20/22 (instead of node 23), use nvm to use node 22, or comment out [these lines](https://github.com/n8n-io/n8n/blob/master/packages/cli/bin/n8n#L21-L35) locally.

We are planning to add support for node 24 once it is out in about 6 weeks.
