### ISSUE TITLE
FTP node: No option to provide keyFile and passphrase

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#1131]
**Describe the bug**
Not sure if bug or feature request: FTP node should have options to support `keyFile` and `passphrase` as defined in https://www.npmjs.com/package/ssh2-sftp-client - which is a common use case for SFTP.

**To Reproduce**
1. Add a new FTP node
2. Click on 'Protocol: SFTP'
4. "error": no fields for passphrase and keyFile

**Expected behavior**
At least for SFTP, there should be an option to provide a keyFile and passphrase, either in the credentials or as additional options.

**Environment (please complete the following information):**
 - OS: all
 - n8n Version: all

**Comment by janober** [comment]
That would be a feature request as SFTP is working, just does not support this authentication method. So please post to https://community.n8n.io/ 
Thanks a lot!

**Comment by frane** [comment]
Done so in: https://community.n8n.io/t/ftp-node-no-option-to-provide-keyfile-and-passphrase/2954
