### ISSUE TITLE
google vertex ai anthropic

### ISSUE THREAD

**Issue by takefy-dev** [n8n-io/n8n#11332]
### Bug Description

I want to use anthropic with google vertex ai home-where it  says only gemini models are allowed...

### To Reproduce

Select google vertex ai node
put claude3.5-sonnet
and the error will be displayed

### Expected behavior

To support all vertex ai models

### Operating System

Linux

### n8n Version

All

### Node.js Version

20>=

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @takefy-dev,

We have created an internal ticket to look into this which we will be tracking as "GHC-335"

**Comment by Joffcom** [comment]
Hey @takefy-dev, 

Are you sure this is a bug and not a feature request? If this is a feature request can you open it on our community support forum?

**Comment by takefy-dev** [comment]
Yeah it's a bug since with vertex ai you must specify the model and it's not restricted only to gemini ... so it would be something related to n8n...

**Comment by Joffcom** [comment]
Hey @takefy-dev,

I have just taken a look and I have found where we return this, Looking at Googles docs here: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/models they only list Gemini models for Vertex and not Claude.

Can you share a link to the Google docs that shows Claude is supported on Vertex and I will pass it back to the team.

**Comment by takefy-dev** [comment]
https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude￼
Use Anthropic's Claude models  |  Generative AI on Vertex AI  |  Google Cloud
cloud.google.com

**Comment by Joffcom** [comment]
I suspect the issue here is we don't have support for "Partner Models" only Google models which may change this to a feature request instead of a bug as currently it is working as intended.

I was just looking at LangChain which we use under the hood and they also don't appear to support it from what I can see.

**Comment by takefy-dev** [comment]
ok thanks when it will be implemented i reckon it' 2 line of code to edit ? I need asap... Since token per day limit is contraignants with anthropic api.

**Comment by Joffcom** [comment]
Hey @takefy-dev,

It will go through prioritisation which could take a day or 2 then depending on priority it will be either updated or put into the backlog for the future. I did some more digging yesterday and we show that error if LangChain returns "Unable to verify model params" as the error which is based on the code here: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-google-common/src/utils/common.ts#L156 where Langchain only supports Gemini for this option.

However if you wanted to have a crack at adding this option in and raising the PR we will happily review.

**Comment by takefy-dev** [comment]
Ok I’ll have a look.In fact langchain has a Class called VertexAiModelGarden in python i did not found it in the js lib.Also I want to mention something langsmith tracking with environment variables do not seem to work at all.Sent from my iPhoneOn 22 Oct 2024, at 10:37, Jon ***@***.***> wrote:﻿
Hey @takefy-dev,
It will go through prioritisation which could take a day or 2 then depending on priority it will be either updated or put into the backlog for the future. I did some more digging yesterday and we show that error if LangChain returns "Unable to verify model params" as the error which is based on the code here: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-google-common/src/utils/common.ts#L156 where Langchain only supports Gemini for this option.
However if you wanted to have a crack at adding this option in and raising the PR we will happily review.
