### ISSUE TITLE
AI Agent output empty string

### ISSUE THREAD

**Issue by takefy-dev** [n8n-io/n8n#11375]
### Bug Description

It always happend on bedrock aws node using claude 3.5 sonnet and few time with anthropic node but each time an gent call a tool it return it to the llm but the llm never output something. I'm really frustrated here  and i'm tinking of writing my own langchain code instead of relying on n8n...

### To Reproduce

Create. an agent with bedrock node claude3.5 sonnet or anthropic node (it happens not all the time) put him a tool make him execute the tool then you will have an error :
 Error in sub-node ‘Redis Chat Memory2’
output values have 5 keys, you must specify an output key or pass only 1 key as output Open node

because the llm generation return empty this need to be fix it's just horrible and make tool not usable
LLM calling the tool
![image](https://github.com/user-attachments/assets/8aa56acd-c48f-436e-9653-d90895854442)
Tool response executed
![image](https://github.com/user-attachments/assets/92236950-8ea8-4593-993e-a8e650efbdea)
LLM called after tool:
![image](https://github.com/user-attachments/assets/db33d8d7-617b-46b7-a3d7-81bc982a14bb)
Redis node
![image](https://github.com/user-attachments/assets/646ac885-2e28-4dff-841c-4601f5d42873)

This is return because langchain avoid saving empty string to the memory store

### Expected behavior

To work

### Operating System

Linux

### n8n Version

1.64.1

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @takefy-dev,

We have created an internal ticket to look into this which we will be tracking as "GHC-340"

**Comment by burivuhster** [comment]
Hey @takefy-dev,

Thanks for taking time to report this. I believe this was recently addressed in #11300 and will be released in the coming days.

**Comment by takefy-dev** [comment]
No i've tested the pr it does not work please test it on ur own

**Comment by Joffcom** [comment]
@takefy-dev is this the same issue you raised before?

**Comment by takefy-dev** [comment]
> @takefy-dev is this the same issue you raised before? One of the things we did for this was to also contribute a fix to LangChain to resolve the issue there as well.
> 
> If the upcoming change doesn't fix it when released we can look again.
> 
> One thing you could do if you are confident with Typescript is raise a PR to fix the issue we can then review the change and merge it.

I've tested it with version 1.64.1 and it totally is not fix, what you have fix simply saving the output if it's an empty string which is not good because for instance with aws bedrock it will return an error saying we don't have ai, human 1:1 conversation type.
Also the main issue is the llm (i don't know if it's even triggered) for no reason not outputting after a tool call... Result in this error.
I really don't have the time at the moment to dive into the code. There is also another bug i've mentionned the langsmith tracing does not work even tho environment variable are set which is so frustrating to not be able to track spend

**Comment by Joffcom** [comment]
Hey @takefy-dev,

The fix mentioned for this is not in the 1.64.1 release unless you added the code change from the PR to the version you have. The fix for this issue and the other issue you have open which we believe is the same as this will be available in the release that is going out today.

For now as this appears to be exactly the same as the other issue I am going to mark this one as closed, Once released if it is still an issue we can look into opening it again.

**Comment by takefy-dev** [comment]
Ok nice!Sent from my iPhoneOn 24 Oct 2024, at 10:39, Jon ***@***.***> wrote:﻿
Hey @takefy-dev,
The fix mentioned for this is not in the 1.64.1 release unless you added the code change from the PR to the version you have. The fix for this issue and the other issue you have open which we believe is the same as this will be available in the release that is going out today.
For now as this appears to be exactly the same as the other issue I am going to mark this one as closed, Once released if it is still an issue we can look into opening it again.

**Comment by takefy-dev** [comment]
Which release tag it will be ?Sent from my iPhoneOn 24 Oct 2024, at 10:39, Jon ***@***.***> wrote:﻿
Hey @takefy-dev,
The fix mentioned for this is not in the 1.64.1 release unless you added the code change from the PR to the version you have. The fix for this issue and the other issue you have open which we believe is the same as this will be available in the release that is going out today.
For now as this appears to be exactly the same as the other issue I am going to mark this one as closed, Once released if it is still an issue we can look into opening it again.
