### ISSUE TITLE
Jira plugin will not display more than 50 projects

### ISSUE THREAD

**Issue by triangletodd** [n8n-io/n8n#1138]
## What

Jira plugin will not display all projects on Jira instances hosting more than 50 projects.

## Where

This code should be modified to paginate through all projects.

https://github.com/n8n-io/n8n/blob/96cffdfd1e0b6eb64fb94b6ac405c1a1d42d7cc7/packages/nodes-base/nodes/Jira/Jira.node.ts#L112-L133

#### API Documentation

https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-projects/#api-rest-api-3-project-search-get

**Comment by RicardoE105** [comment]
@triangletodd ahh yes, cuz we are not paginating the results there. Will fix it, thanks for letting us know. in the meantime, you can always set the project id manually using expressions.

**Comment by triangletodd** [comment]
![image](https://user-images.githubusercontent.com/578468/98453493-c3f53400-2127-11eb-834a-b3cdc4ecb314.png)

I'm pretty new to n8n. Can you elaborate a little on how to use an expression to set the project id?

**Comment by RicardoE105** [comment]
it's exactly what you did. Ignore the error message. The node should work like that. Check the video below where I set the project to 1234 manually.

https://www.loom.com/share/1018ae680c1849d8aeb0f4949de51fd5

**Comment by RicardoE105** [comment]
@triangletodd  Question. Are you using the Jira cloud or the self-hosted version?

**Comment by triangletodd** [comment]
> @triangletodd Question. Are you using the Jira cloud or the self-hosted version?

Jira Cloud

**Comment by janober** [comment]
Got released with n8n@0.93.0
