### ISSUE TITLE
use createMultiFormDataParser function not resolve

### ISSUE THREAD

**Issue by weiqingtao** [n8n-io/n8n#11405]
### Bug Description

when I upload file, I use  createMultiFormDataParser this function,but  promise not reslove.This issue seems to be a formidable bug.When I added this line of code to the body parse file, the problem was solved！
![image](https://github.com/user-attachments/assets/c98fc409-78f3-4bf3-a9b5-b210d720fa22)

### To Reproduce

![image](https://github.com/user-attachments/assets/dc4edbf5-1b98-4e5a-bb3d-0fd21f7ec19d)

### Expected behavior

reslove data

### Operating System

window

### n8n Version

1.64.0

### Node.js Version

v20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @weiqingtao,

We have created an internal ticket to look into this which we will be tracking as "GHC-348"

**Comment by Joffcom** [comment]
Hey @weiqingtao,

Can you clarify more on what you are actually doing? Are you uploading data with a webhook node or form node?

**Comment by weiqingtao** [comment]
> form node

I  use form node,I  add a new route, use createMultiFormDataParser  to upload file

**Comment by netroy** [comment]
Can you please share a workflow and/or a curl command to help us reproduce this quicker?

**Comment by Joffcom** [comment]
Moving to closed until we have a way to reproduce this.
