### ISSUE TITLE
facebook leads webook Error 

### ISSUE THREAD

**Issue by SamuelClickage** [n8n-io/n8n#11400]
### Bug Description

Cannot read properties of undefined (reading '0')

same lead 6 times with error
![image](https://github.com/user-attachments/assets/5c77a8ce-39d2-4c8c-8226-5a5aa16fe9e8)
![image](https://github.com/user-attachments/assets/699c56b0-b101-4e7f-b435-b45e990b2ed6)

### To Reproduce

1-Webhook get data

### Expected behavior

Get data from facecbook leads

### Operating System

Linux server

### n8n Version

1.64.2

### Node.js Version

1.64.2

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @SamuelClickage,

We have created an internal ticket to look into this which we will be tracking as "GHC-347"

**Comment by Joffcom** [comment]
Hey @SamuelClickage 

Can you share the full error output? There is a little copy icon next to the error details and that will give us the stack trace we can use to track down the issue

**Comment by SamuelClickage** [comment]
![image](https://github.com/user-attachments/assets/3cfe81b0-3ff8-4e10-acae-8251d574d7d6)

**Comment by Joffcom** [comment]
Thanks @SamuelClickage

**Comment by Joffcom** [comment]
Hey @SamuelClickage,

I am just trying to reproduce this but I have not been able to, Are you using optional fields in the form?
