### ISSUE TITLE
Errors installing n8n on my Mac

### ISSUE THREAD

**Issue by itscutarms** [n8n-io/n8n#11411]
### Bug Description

Hi, I tried to install n8n but I can't.

This is the whole message that I receive by the terminal:

npm install n8n -g
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/n8n
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/n8n'
npm error     at async mkdir (node:internal/fs/promises:858:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/n8n'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

Thank you in advance if someone can help me.

P.S. I already have installed node.js

### To Reproduce

How to fix this

### Expected behavior

I would like to receive help to install n8n

### Operating System

MacOS

### n8n Version

1.63.4

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @itscutarms,

We have created an internal ticket to look into this which we will be tracking as "GHC-349"
