### ISSUE TITLE
Slack Webhook not responding

### ISSUE THREAD

**Issue by ZanBlayde** [n8n-io/n8n#11424]
### Bug Description

Hi, here's my scenario:
- self hosted on Render Standard Plan
- slack bot works no problem for days then randomly stops responding
- in n8n executions for the workflow there are no new runs of the workflow no matter how many times I say hello to the bot in slack
- in slack the event subscription URL is validated but to troubleshoot I switch to the test webhook URL, listen, and verify and it works. Then I switch to the production URL (yes workflow is active) and it denies the validation in slack as it did not respond to challenge response.
- the way I fix this is to delete and recreate the incoming slack trigger which creates a new webhook URL, and slack validates it immediately
- bot responds again in slack when I ask it a question

![Screenshot 2024-10-25 at 10 59 24 AM](https://github.com/user-attachments/assets/9039342c-5875-4b34-bf1d-b838914f0877)

### To Reproduce

I am unable to reproduce it at will but when the bot stops responding, this is the workaround that has been successful.

### Expected behavior

The webhook should never become unresponsive. 

### Operating System

Render Web Service Node

### n8n Version

1.64.0

### Node.js Version

18.17.0

### Database

sqlite

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ZanBlayde,

We have created an internal ticket to look into this which we will be tracking as "GHC-352"

**Comment by ZanBlayde** [comment]
# Debug info

## core

- n8nVersion: 1.64.0
- platform: npm
- nodeJsVersion: 18.17.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

**Comment by Joffcom** [comment]
Hey @ZanBlayde 

With the Slack trigger we rely on Slack sending the webhook so this could be an issue on the Slack side.

One way to test this would be when it happens again see if you can manually send a request to the endpoint using something like Curl.

**Comment by Joffcom** [comment]
Hey @ZanBlayde,

Swapping between test and active could be part of the issue as Slack only allows one URL at a time so if you were using the test option you would need to update the URL in Slack, do your testing then activate the webhook workflow again and change the url in Slack.

The Google Sheets reconnection is likely to be unrelated as it isn't an incoming connection.

**Comment by ZanBlayde** [comment]
Good morning! Thanks for your insights. I am swapping back and forth between test and prod links because I'm setting up the bot and needing to test the payload from node to node. 

However, I had it running well yesterday and left it on the prod link without issue. This morning I tried saying hi and nothing happened. I immediately grabbed the active prod webhook link and tested it in postman and got this:

{
    "code": 404,
    "message": "The requested webhook \"GET <webhook ID>/webhook\" is not registered.",
    "hint": "The workflow must be active for a production URL to run successfully. You can activate the workflow using the toggle in the top-right of the editor. Note that unlike test URL calls, production URL calls aren't shown on the canvas (only in the executions list)"
}

Did my delete note, re-create, put new prod webhook URL in slack, if verified and the bot was working again.

**Comment by Joffcom** [comment]
Hey @ZanBlayde,

That is odd and would suggest the worklfow was not active or the url is incorrect. Does it just show `/webhook` or is there more to the path?

**Comment by ZanBlayde** [comment]
Hey @Joffcom , the webhook URL is https://<myinstance>.onrender.com/webhook/<webhookID>/webhook

**Comment by ZanBlayde** [comment]
Hey @Joffcom , the webhook URL is `https://<myinstance>.onrender.com/webhook/<webhookID>/webhook`
