### ISSUE TITLE
Usage page failing on license checks

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11459]
### Bug Description

Hi, I am self hosting and want to get the offered activation key from the "Usage" page, but get the following error (smtp settings DO work in another app):
```
n8n-app-1  | 2024-10-29T14:53:10.515Z | error | Failed to renew license: renewal failed because current cert is not initialized {"stack":"Error: renewal failed because current cert is not initialized\n    at p._renew (/usr/local/lib/node_modules/n8n/node_modules/@n8n_io/license-sdk/dist/LicenseManager.js:29:3102)\n    at p.renew (/usr/local/lib/node_modules/n8n/node_modules/@n8n_io/license-sdk/dist/LicenseManager.js:29:2982)\n    at License.renew (/usr/local/lib/node_modules/n8n/dist/license.js:185:28)\n    at LicenseService.renewLicense (/usr/local/lib/node_modules/n8n/dist/license/license.service.js:124:32)\n    at LicenseController.renewLicense (/usr/local/lib/node_modules/n8n/dist/license/license.controller.js:59:35)\n    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:53)\n    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:105:32\n    at newFn (/usr/local/lib/node_modules/n8n/node_modules/express-async-errors/index.js:16:20)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:149:13)","file":"license.service.js","function":"mapErrorMessage"}
```

### To Reproduce

1. self host, configure smtp settings and start
2. try to get activation license emailed

### Expected behavior

email to arrive

### Operating System

docker

### n8n Version

1.64.3

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-357"

**Comment by Joffcom** [comment]
Hey @Morriz 

The error you have shared seems unrelated to smtp. 

Is there an error in the UI at all?

**Comment by Morriz** [comment]
no UI error, but that line ONLY shows up immediately after I press "Send me a free activation key". I tried 3 times now...

**Comment by Morriz** [comment]
I also see that this error is not thrown in any of the typescript code, so I expect it to be an error from some external license server? In that case why does it check a license if it is in need of retrieving one? Maybe that code logic is incorrect?

**Comment by Joffcom** [comment]
Hey @Morriz,

I don't think this is related to SMTP in any way, The call will likely check our license server to generate the license key for you. Do you have any web filtering happening at all?

**Comment by Morriz** [comment]
no, everything is working fine, including hooks and inviting users...so all plumbing correct

**Comment by Morriz** [comment]
| The call will likely check our license server to generate the license key for you.

But the error is not from the `n8n-io/n8n` repo, unless I am wrong. Can you confirm?

Otherwise, is there some validation check on the licensing server in order to honor incoming requests? Do requests need to provide at least SOME license to make a call? Because we self-hosted peeps don't have one...

**Comment by Joffcom** [comment]
Hey @Morriz,

The error is coming from our license sdk which is not in a public repo, Sometimes when trying to load the usage page if the initial connection fails to initialize it can show this. Normally this is something I have seen when a proxy or webfilter is being used for outbound traffic.

As a test in your container can you run `n8n license:clear` then stop and start n8n and see if you have the same issue. This new feature you are using is only for self hosted peeps that have no existing license and it appears to be working for others so this does appear to be environmental at the moment.

**Comment by Joffcom** [comment]
We are closing this issue as there has been no response in 14 days, If this is still an issue let us know and provide any information requested and we can look at re-opening it.

**Comment by Morriz** [comment]
But I would just really like to get my hands on those features @Joffcom, how do I do that?

**Comment by Morriz** [comment]
can you reopen this @Joffcom? And please don't manually close tickets! (That is not good netiquette, I suggest adding a bot for that which first posts a "stale" warning

**Comment by EdgeNorthDev** [comment]
**UPDATE**: 
Despite the symptoms below and never finding the culprit and no clear understanding of WHY - I came back to this a couple days later, tried again, and it WORKED. Maybe something on the install system just needed time to percolate? Or...? Anyway, below is past tense and these issues are no longer occurring for me. Maybe others who run into them will have success later too? 

-----

I'm getting the same failure response when attempting to go to the activation screen and register. I get these errors in the console:
```
Failed to renew license: renewal failed because current cert is not initialized
400 Failed to renew license: renewal failed because current cert is not initialized
```

And these errors eventually pop up in the web UI on the Usage and Plan screen when I click the Send me a free license key button.
```
License request failed
Failed to register community edition: Request failed with status code 524
```

Any specific ideas on what I can try - this is on an Azure-hosted Windows server; npm install of version 1.95.3. I don't know if the server has anything setup for SMTP, but that wouldn't be the issue right? Potentially something with web proxy / traffic routing? Although everything else seems to work fine including things like a Power BI gateway we have running on the same server.

**Comment by SanAguirre2176** [comment]
I have the same issue. How can i fix this?

Failed to renew license: renewal failed because current cert is not initialized
400 Failed to renew license: renewal failed because current cert is not initialized
2025-06-10T16:29:57.528Z [Rudder] error: Response error code: ETIMEDOUT

Windows 11 - Node 22.16 - Powershell Admin execution
