### ISSUE TITLE
Hangs when pressing Ctrl and moving mouse

### ISSUE THREAD

**Issue by hibviny** [n8n-io/n8n#11468]
### Bug Description

On the new canvas, when I press CTRL and move the mouse to move the canvas, it hangs! In the previous flow, the hand appeared and moved the canvas normally. I managed to repeat this flow by crashing several times.
![on_press_ctrl](https://github.com/user-attachments/assets/1d706dab-392c-49bc-abdb-b9f8fb50de66)

# Debug info

## core

- n8nVersion: 1.65.2
- platform: npm
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/130.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2024-10-30T01:54:57.363Z

### To Reproduce

1 - Use new canvas
2 - click your flow
3 - Press Ctrl and move the mouse to move the flow.
4 - The window will lock.

### Expected behavior

that when pressing CTRL and moving the mouse, move the flow as it was previously.

### Operating System

Windows

### n8n Version

1.65.2

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @hibviny,

We have created an internal ticket to look into this which we will be tracking as "GHC-359"

**Comment by alexgrozav** [comment]
Hey @hibviny! Thank you for reporting the issue. It has been fixed in #11534. Will go out with the next release.
