### ISSUE TITLE
[New Canvas Editor] Browser crashes when I click these two buttons.

### ISSUE THREAD

**Issue by ARHAEEM** [n8n-io/n8n#11476]
### Bug Description

Usually, with the old editor, I use the scroll click and sometimes use CTRL with mouse movement. However, with the new editor, if I do this, the browser crashes with the error shown below:

![image](https://github.com/user-attachments/assets/79343f3c-c27d-43b2-8b03-cdfdadea36a4)
![image](https://github.com/user-attachments/assets/1d74ae53-579e-4719-94e6-f820fca21e4f)

### To Reproduce

Just click the scroll wheel of the mouse and press CTRL at the same time! The browser tab will freeze immediately.

-------------

# Debug info

## core

- n8nVersion: 1.65.2
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: postgres
- executionMode: regular
- concurrency: -1
- license: enterprise (production)
- consumerId: dc27dc16-38b9-460d-a9d3-07313e8835d5

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/130.0.0.0 safari/537.36 edg/130.0.0.0
- isTouchDevice: false

Generated at: 2024-10-30T13:30:45.138Z

### Expected behavior

After fixing the bug, I wish for both to work: CTRL and scroll click.

### Operating System

ubuntu linux 24

### n8n Version

docker:next (1.65.2)

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ARHAEEM,

We have created an internal ticket to look into this which we will be tracking as "GHC-365"

**Comment by alexgrozav** [comment]
Fixed in #11534
