### ISSUE TITLE
Back button in settings doesn't work correctly after upgrading to Enterprise

### ISSUE THREAD

**Issue by alonso-chainels** [n8n-io/n8n#11473]
### Bug Description

Hey team,

I discovered that if you navigate to the settings, click any of the options in the left bar and then refresh the page, if you would like to go back to the home page to see your projects and workflows, the back button doesn't work and instead opens the **any other option of the section**, but never goes back to the home page.

The only way to go back to the home page is by editing the URL and removing the settings part.

### To Reproduce

1. From the home screen, go to the bottom-left and click the three dots next to the user name.
2. Select **Settings**.
3. Within the settings page, select any option. For the sake of the test, select External Secrets.
4. Refresh the page
5. Click the back button to return to the home page.
6. The option/section **Personal** will open

### Expected behavior

1. From the home screen, go to the bottom-left and click the three dots next to the user name.
2. Select **Settings**.
3. Within the settings page, select any option. For the sake of the test, select External Secrets.
4. Refresh the page
5. Click the back button to return to the home page.
6. User is routed to the home page where you can see your workflows.

### Operating System

Mac OS 15.0.1

### n8n Version

1.62.5

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @alonso-chainels,

We have created an internal ticket to look into this which we will be tracking as "GHC-363"

**Comment by Joffcom** [comment]
Good news, This was fixed in todays `1.71.0` release.
