### ISSUE TITLE
Little bug in format message for AI 

### ISSUE THREAD

**Issue by afanjul** [n8n-io/n8n#11471]
### Bug Description

I think there is a little miss-typed bug in a message to format output in AI nodes, it says:

<img width="902" alt="image" src="https://github.com/user-attachments/assets/0051e203-95cd-49bf-a5b0-3677208f845e">

```
{
"action": "Final Answer",
"action_input": string // You should put what you want to return to use here and make sure to use valid json newline characters.
}
```

And I guess it should be:

"action_input": string // You should put what you want to return to **user** here and make sure to use valid json newline 

Pay attention to "use" vs "user".

### To Reproduce

1. Add an AI Agent node
2. Just review the formatting system prompt

### Expected behavior

Just correct the wrong word

### Operating System

Macos

### n8n Version

Sonoma

### Node.js Version

18.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @afanjul,

We have created an internal ticket to look into this which we will be tracking as "GHC-362"
