### ISSUE TITLE
Google sheet Append: header with \n can't Remove column or switch Expressions

### ISSUE THREAD

**Issue by sean6131** [n8n-io/n8n#11470]
### Bug Description

https://github.com/user-attachments/assets/c22136a1-c77a-4648-af34-25eee23979d2

If my Google Sheet column header contains a newline character( \n ), I can't remove the column or switch to expressions.
![image](https://github.com/user-attachments/assets/35757a53-392c-47e6-8ba2-d5a70f8daa08)

### To Reproduce

1. Create a new n8n workflow.
2. Create a new Google Sheet.
3. Choose any trigger (I use Trigger manually).
4. Add a Sheet node.
5. Choose "Append or Update Row in Sheet" or "Append Row in Sheet."
6. Write a column header with a newline character (CTRL+Enter) in Google Sheets.
7. Refresh the column list.
8. Try to switch expressions (Can't switch).
9. Try to remove the column (Can't remove).
10. Delete the newline character
11. Now you can switch expressions or remove the column

Full Reproduce video here:

https://github.com/user-attachments/assets/12ce1cd2-6c45-42ee-bfa0-52734687bae7

### Expected behavior

Even with newline character, it should can switch to expressions or remove the column.

### Operating System

Windows

### n8n Version

1.64.3

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @sean6131,

We have created an internal ticket to look into this which we will be tracking as "GHC-361"

**Comment by Joffcom** [comment]
Hey @sean6131,

I believe this issue is the pretty much the same thing as https://github.com/n8n-io/n8n/issues/9763 so for now I am going to mark this as closed. If you don't think this is the case let me know.
