### ISSUE TITLE
Exception thrown while using AMQP sender node

### ISSUE THREAD

**Issue by codenthusiast** [n8n-io/n8n#1148]
**Describe the bug**
After executing the workflow, I am sending a message to an Activemq queue using the AMQP sender node. The message delivers to the queue however, an exception is returned after execution with the following stack trace:

`
ERROR: container.close is not a function
TypeError: container.close is not a function
    at Object.executeSingle (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Amqp/Amqp.node.js:100:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:478:34)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:369:47
`

**To Reproduce**
1. 
```sh 
docker run -it --rm --name n8n --network demonet -p 5678:5678 -v ~/.n8n:/root/.n8n n8nio/n8n
docker run -p 61616:61616 --network demonet -p 8161:8161 rmohr/activemq
```

2. Goto http://localhost:5678/
3. Paste the following workflow JSON

```JSON
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        450,
        270
      ]
    },
    {
      "parameters": {
        "sink": "workflow-created",
        "options": {}
      },
      "name": "AMQP Sender",
      "type": "n8n-nodes-base.amqp",
      "position": [
        860,
        270
      ],
      "typeVersion": 1,
      "credentials": {
        "amqp": "Activemq"
      }
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "my_key",
              "value": "my_value"
            }
          ]
        },
        "options": {}
      },
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "position": [
        660,
        270
      ],
      "typeVersion": 1
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "AMQP Sender",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

4. Click execute workflow

**Expected behavior**
Message should be delivered to the queue without any exception

**Environment (please complete the following information):**
 - OS: Docker for windows
 - n8n Version 0.86.1
 - Node.js Version v12.16.3

**Additional context**
Both n8n's container and activemq are on the same network.

**Comment by janober** [comment]
Please update to the latest n8n version (currently 0.92.0). There it will work fine.
