### ISSUE TITLE
Deployment fail on latest fork version 

### ISSUE THREAD

**Issue by Webylon** [n8n-io/n8n#11493]
### Bug Description

I'm using Raleway as a cloud service and was recently unable to update from the latest version of my fork.

Issue: Deployment failed during network process - Healthcheck failure 
Deploy log: /bin/bash: line 1: n8n: command not found

### To Reproduce

Deployment using Railway using GitHub fork

### Expected behavior

Previous version has been deployed successfully

### Operating System

Mac OS Sonoma 14.5

### n8n Version

n8n-io#11485

### Node.js Version

1.65.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Webylon,

We have created an internal ticket to look into this which we will be tracking as "GHC-372"

**Comment by Joffcom** [comment]
Hey @Webylon 

This does not sound like an issue with n8n, can you share more information on how you deploy to Raleway? It sounds like for some reason it might be trying to run the container with a command that is invalid

**Comment by Webylon** [comment]
Sure @Joffcom 

I deployed using Raleway's built-in templates and my n8n fork as the source repo.

Please see the attached screenshot

<img width="1384" alt="Skärmavbild 2024-10-31 kl  22 30 43" src="https://github.com/user-attachments/assets/96009ee7-4bd8-4b05-864b-8fb8ee6d0d9f">
<img width="958" alt="Skärmavbild 2024-10-31 kl  22 31 04" src="https://github.com/user-attachments/assets/4c4cd3d8-7ba2-4a8a-8c88-0d3291d3940a">
<img width="991" alt="Skärmavbild 2024-10-31 kl  22 31 24" src="https://github.com/user-attachments/assets/30459e58-899a-4231-be47-b6d2d406027e">
<img width="964" alt="Skärmavbild 2024-10-31 kl  22 31 42" src="https://github.com/user-attachments/assets/6b18674d-427f-426f-9f33-ba080ee74d97">

**Comment by Webylon** [comment]
Everything was working fine until the recent version of n8n fork sync

**Comment by Webylon** [comment]
@Joffcom, Deployment is now successful.

It was the TRIAL limitation Railway had for maximum service usage.
It was kinda misleading because I still had $3.71 left on my trial and there was no notice regards to the limitation or any failed message.

Anyway I upgraded for their service and successfully deployed using their n8n integration template.

Thanks for your support!
