### ISSUE TITLE
node If is stuck in loop

### ISSUE THREAD

**Issue by nicolas-geysse** [n8n-io/n8n#11514]
### Bug Description

![Capture d'écran 2024-11-02 042832](https://github.com/user-attachments/assets/5639fdaf-c21b-43e8-af5d-f40ff412d2ee)
I've updated to the latest version, and it seems that the if node is now stuck / not reacting as expected.

### To Reproduce

1.set the node
2.add conditions like :
{{$json.data === "" || $json.data === "\n"}}
is eqaul to : true

OR
{{$json['File Size'] === '49 B'}}
is equal to : true

Convert types where required
Activated.

Then any files from any size goes to true, and goes in infinite loop.
I alos see that it keeps 2 files in the queue (like a loop of something)

### Expected behavior

To have a proper if statement that redirect to the good workflow, not looping, playing just once.

### Operating System

?

### n8n Version

1.65.2

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @nicolas-geysse,

We have created an internal ticket to look into this which we will be tracking as "GHC-378"

**Comment by Joffcom** [comment]
Hey @nicolas-geysse,

I have followed your steps and I am not able to reproduce this. Can you share a small workflow that reproduces the issue?

**Comment by nicolas-geysse** [comment]
My bad, I had some hard times playing with binaries files used by node code, that seems to be handled differently than the native n8n process.
I couldn't get the info (mime type, size) with my first attempts, it is now solved !
