### ISSUE TITLE
New Alpha Editor Zoom In and Pan/Drag Bug

### ISSUE THREAD

**Issue by vsnshanmuganathan** [n8n-io/n8n#11519]
### Bug Description

By pressing + button, the Editor **Zoom Out** which should **Zoom In** as the use case.
Second thing is by Pressing CMD and we use mouse it doesn't active the Pan/Drag feature.

### To Reproduce

1. Go to Workflow Editor.
2. Switch to New Canvas Editor.
3. Now try above shortcuts i mentioned in Bug Description. 

### Expected behavior

By pressing + button it should Zoom In.
By pressing CMD + mouse click, it should drag or move the canvas.

### Operating System

Docker

### n8n Version

1.65.2

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @vsnshanmuganathan,

We have created an internal ticket to look into this which we will be tracking as "GHC-383"

**Comment by nepomuc** [comment]
Also using the trackpad of my laptop to zoom in and zoom out doesn't work anymore. Do you want to include this in this ticket or should I open a new one?

**Comment by vsnshanmuganathan** [comment]
I have checked in latest version 1.66.0 and the bug still there in New Canvas mode,
Tried in Chrome and Safari too
