### ISSUE TITLE
Cancel renaming by keyboard

### ISSUE THREAD

**Issue by AlexanderHentzsch** [n8n-io/n8n#11528]
### Bug Description

If you want to rename a node and then switch to “Cancel” using the tab key and then press Enter, the change is not canceled but accepted.

### To Reproduce

1. Do it like in the description 😎 

### Expected behavior

Cancel the renaming like the ESC-button

### Operating System

docker (self hosted)

### n8n Version

1.65.2

### Node.js Version

docker

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @AlexanderHentzsch,

We have created an internal ticket to look into this which we will be tracking as "GHC-389"

**Comment by AlexanderHentzsch** [comment]
I have tested both 😉

**Comment by Joffcom** [comment]
@AlexanderHentzsch for me on the old canvas if I select a node, press F2 to rename, type in my name, press tab to go to cancel and press enter it doesn't rename the node.

On the new canvas if I select a node, Press F2 to rename, type in a name, Press tab and press enter it opens the node prompt.

This second option is a bug we should probably fix.

With a bit more playing... If a node is opened then you click on the rename node icon, type in a name, tab and enter that reproduces what you are reporting I take it this is what you are doing?

**Comment by AlexanderHentzsch** [comment]
Yes @Joffcom, I meen the renaming in the open node. I use the option via F2 for renaming to rare. Sorry I didn't mention that.

**Comment by Joffcom** [comment]
@AlexanderHentzsch it is all good, we reproduced it and the team are on the case.

**Comment by janober** [comment]
Fix got released with [`n8n@1.67.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.67.0)
