### ISSUE TITLE
"Save manual executions" switch automated to "Do not save"

### ISSUE THREAD

**Issue by AlexanderHentzsch** [n8n-io/n8n#11527]
### Bug Description

By default or if I set under Settings >> Save manual executions >> “Default - Do not save”, it changes to “Do not save” when I open it again. This saves an unnecessary setting in the database or makes it look as if you have manually set it to “Do not save”.

### To Reproduce

1. Go to settings
2. Set "Save manual executions" to "Default - Do not save"
3. Save
4. Reopen the settings

### Expected behavior

Due to the automatic change to a “manual” value, it always looks like a manual configuration. I wish that if default is selected, default is also displayed and then saved. Otherwise you have to adjust the “Save manual execution” for every other change (timeout, etc.).

### Operating System

docker (self hosted)

### n8n Version

1.65.2

### Node.js Version

docker

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @AlexanderHentzsch,

We have created an internal ticket to look into this which we will be tracking as "GHC-388"

**Comment by Joffcom** [comment]
Hey @AlexanderHentzsch,

I am not sure I understand the bug here, Can you provide more details?

**Comment by AlexanderHentzsch** [comment]
Hey @Joffcom 

this is the setting I would like to save:
![grafik](https://github.com/user-attachments/assets/3981c593-3882-4c43-8d5a-a7e9f49c9237)

but after saving and reopening it switch to:
![grafik](https://github.com/user-attachments/assets/aaa4b960-f260-4555-bbc9-53c3d1326878)

The automatic change (front-end) to a manual value under “Save manual executions” saves the setting in the database. It always looks as if you have switched to “Do not save” manually. I have not yet tested this: If you change the default value via the ENVs for manual execution, this would no longer be taken into account.

**Comment by Joffcom** [comment]
Ah ok that makes sense, So you would like the option to set a workflow to use the default value again if you selected something else. I will let the team work out if this is a bug or a feature request.

**Comment by despairblue** [comment]
This should be fixed by https://github.com/n8n-io/n8n/pull/11632 which will be in the next release.

Thanks for reporting this ❤️
