### ISSUE TITLE
Pagination Body not run

### ISSUE THREAD

**Issue by ip2cloud** [n8n-io/n8n#11540]
### Bug Description

I set $pagecount + 1 in the body page field, but n8n keeps page 1, does not change the page. n8n shows page 3 (for example), but the data is the same as page 1. 
When I make a connection via postman and select the page field, the data arrives updated. This is giving the error below, because the data is repeating itself.

{
  "errorMessage": "The returned response was identical 5x, so requests got stopped",
  "errorDescription": "Check if \"Pagination Completed When\" has been configured correctly.",
  "errorDetails": {
    "rawErrorMessage": [
      "The returned response was identical 5x, so requests got stopped"
    ]
  },
  "n8nDetails": {
    "nodeName": "HTTP Request4",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.2,
    "itemIndex": 0,
    "time": "04/11/2024, 10:58:58",
    "n8nVersion": "1.66.0 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The returned response was identical 5x, so requests got stopped",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:502:33)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:707:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1137:20"
    ]
  }
}

### To Reproduce

Configure pagination type body

### Expected behavior

The expectation is that the page data will be changed by changing the page field of the body with pagination.

### Operating System

Docker Self-Hosted

### n8n Version

1.66.0 (Self Hosted)

### Node.js Version

4.2 (Latest)

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ip2cloud,

We have created an internal ticket to look into this which we will be tracking as "GHC-390"

**Comment by Joffcom** [comment]
Hey @ip2cloud,

Do you have a simple workflow that we can use to try and reproduce this? Looking at the error it looks like the issue could be with knowing when pagination is complete.

**Comment by ip2cloud** [comment]
yes.. I will simulate and send the screens.

**Comment by ip2cloud** [comment]
acreito que é isso que esta acontecendo:

https://community.n8n.io/t/http-pagination-with-post-request-body-parameters-pagecount-not-incrementing/33633/6

**Comment by ip2cloud** [comment]
I Discovery!

I discovered...
I'm sending the pagination like this:

![image](https://github.com/user-attachments/assets/644f9a2d-963c-44d0-b58e-06c6f715056f)

but n8n send:

![Captura de Tela 2024-11-10 às 16 25 46](https://github.com/user-attachments/assets/e4e2fcf7-3bbf-4803-8fce-cba0773def90)

that is, with the "\" this is causing the request body to get in the way

**Comment by pedroaugustonyo** [comment]
> Resolved: expression {{ [{ pagina: $pageCount + 1, filtrar_apenas_titulos_em_aberto: "S" }] }} remove stringfy

i was already giving up and suddenly i found someone with the same problem as me, fetching the same api as me! too good to be real
