### ISSUE TITLE
docker custom build not working when docker start

### ISSUE THREAD

**Issue by aviam** [n8n-io/n8n#1155]
The error:

(node:7) UnhandledPromiseRejectionWarning: Error: There was an error: Cannot find module '/data/packages/cli/node_modules/n8n-nodes-base/dist/nodes/Affinity/Affinity.node.js'
Require stack:
- /data/packages/cli/dist/src/LoadNodesAndCredentials.js
- /data/packages/cli/dist/src/index.js
- /data/packages/cli/dist/commands/execute.js
- /data/node_modules/@oclif/config/lib/plugin.js
- /data/node_modules/@oclif/config/lib/config.js
- /data/node_modules/@oclif/config/lib/index.js
- /data/node_modules/@oclif/command/lib/command.js
- /data/node_modules/@oclif/command/lib/index.js
- /data/packages/cli/bin/n8n
    at Object.error (/data/node_modules/@oclif/errors/lib/index.js:26:15)
    at Start.error (/data/node_modules/@oclif/command/lib/command.js:60:23)
    at /data/packages/cli/commands/start.ts:231:10
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by janober** [comment]
Close issue as it does not follow the template we defined. Please open a new issue following it. Thanks!
