### ISSUE TITLE
Nodes development - Hot Reloading broken after chokidar upgrade

### ISSUE THREAD

**Issue by dziwoki** [n8n-io/n8n#11577]
### Bug Description

Chokidar v4 does not support glob-style paths input. As a result the changes in nodes are not hot-reloaded.

### To Reproduce

1. Create community node `n8n-nodes-nextthing` inside `/path/n8n-nodes-nextthing`
2. Start n8n project:
```
NODE_ENV=development N8N_DEV_RELOAD=true N8N_CUSTOM_EXTENSIONS="/path/n8n-nodes-nextthing" npm run dev
```
3. Start tsc-watch for `n8n-nodes-nextthing`
4. Make changes to `n8n-nodes-nextthing`
5. The `n8n-nodes-nextthing` node is not hot-reloaded in n8n

### Expected behavior

After making changes to the dependent node, the node should be hot reloaded

### Operating System

All

### n8n Version

1.66.0

### Node.js Version

All

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dziwoki,

We have created an internal ticket to look into this which we will be tracking as "GHC-397"

**Comment by Joffcom** [comment]
Get @dziwoki,

Did this ever work for custom nodes not being made in the n8n folder?
