### ISSUE TITLE
When removing a switch rule the outputs changes

### ISSUE THREAD

**Issue by woodsbox** [n8n-io/n8n#11587]
### Bug Description

Hi!

I deleted a switch rule and all the outputs are changed.

### To Reproduce

When you create a switch with say for example 3 outputs, pointing to different nodes say output 1 pointing to node 1 etc etc. When I remove for example the first rule leaving only rule 2 and 3 the output changes so output 1 is removed but output 2 is pointing then to node 1 and output 3 is pointing to node 2 and there is a new output created.

### Expected behavior

I would expect when I remove rule 1 the output 1 is removed and output 2 and 3 stay connected to node 2 and 3.

### Operating System

docker compose

### n8n Version

1.65.2

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @woodsbox,

We have created an internal ticket to look into this which we will be tracking as "GHC-398"

**Comment by janober** [comment]
Fix got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)
