### ISSUE TITLE
The screen/canvas freezes when I press CTRL + Click on the mouse wheel (to move around the canvas) with the new ALPHA version CANVAS

### ISSUE THREAD

**Issue by jbfleury** [n8n-io/n8n#11594]
### Bug Description

The screen/canvas freezes when I press CTRL + Click on the mouse wheel (to move around the canvas) with the new ALPHA version CANVAS

### To Reproduce

The screen/canvas freezes when I press CTRL + Click on the mouse wheel (to move around the canvas) with the new ALPHA version CANVAS

### Expected behavior

Freezing canvas

### Operating System

Windows

### n8n Version

1.66.0

### Node.js Version

???

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jbfleury,

We have created an internal ticket to look into this which we will be tracking as "GHC-399"

**Comment by Joffcom** [comment]
This has been fixed in a recent update, moving to closed.
