### ISSUE TITLE
responses are not streaming 

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11597]
### Bug Description

Hi, responses are not streaming, nor do I see the option to choose between streaming or aggregate response...am I missing something here? I think most of the AI world is used to tools that work with token streams.

### To Reproduce

1. Use any AI / LLM node to get output
2. Observe no streaming output

### Expected behavior

Streaming output to work

### Operating System

Docker

### n8n Version

1.64.3

### Node.js Version

Docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-401"

**Comment by Morriz** [comment]
And sorry for trying the bug entry if this is deemed a feature request, but you don't seem to listen to or monitor for user contributions in this regard one bit:
- https://community.n8n.io/t/support-for-stream-in-http-request-node-and-openai-node/23771
- https://community.n8n.io/t/stream-ai-responses-on-http-responses-llm-chains-and-ai-agents-nodes/52084/5
- https://community.n8n.io/t/request-for-http-streaming-support-in-respond-to-webhook-node/42944
- https://community.n8n.io/t/streaming-response-of-http-node-or-openai-node-via-respond-to-webhook-node/27772

So where is your stance on this matter?

**Comment by Joffcom** [comment]
Hey @Morriz,

This does look to be a feature request as you suggested which means this would be better suited to the forum where the other requests are and I will move this to closed for now, Don't forget to vote on one of the requests I will make sure they get merged tomorrow.

While it may not look like we monitor or listen we do keep an eye on them and do implement the features but we have to prioritise the features and some are easier than others to implement.

I believe this is something that is on the roadmap but it isn't a quick or easy change, Looking at the 3 requests you found it is easy to see how this has slipped we didn't ask the users to vote on one request so instead of 1 feature request having ~39 votes we have 4 with lower numbers so when looking at this view: https://community.n8n.io/c/feature-requests/5 it is not in the top 10.

**Comment by Morriz** [comment]
Thanks for the elaborate reply :)

**Comment by Joffcom** [comment]
No problem, I know that this is something Jan wanted to add for a while so it will happen at some point and with the recent hires it is more likely to happen sooner rather than later.

**Comment by BedroomDev** [comment]
I think we all need this asap with all the other plattforms having this out-the-box and n8n falling behind in that matter. 
We dont really want to switch, i think a lot dont want to, but steaming responses from AI is essential.

**Comment by MahraneAbid** [comment]
Are there any updates on this feature?

**Comment by Megant88** [comment]
any updates?

**Comment by DavideDelbianco** [comment]
This feature and a better self hosted "frontend ui" is the only thing that keeps me using Dify
I would gladly try n8n for its multiple entrypoints feature and lots of integrations... but I'm starting to think that it will be easier to see n8n features in other tools than this basic feature in n8n

**Comment by rgvcorley** [comment]
Please implement this feature! 💖

**Comment by Megant88** [comment]
yeah absolute needed, right now i just emulate streaming, but a native feature would be beautiful :0 +

**Comment by fbsfernando** [comment]
Up

**Comment by izmarel** [comment]
This feature is definitely a must-have!

**Comment by kairoswealth** [comment]
any update?

**Comment by jimiopex** [comment]
Any update?

**Comment by nskrable** [comment]
Commenting on this for attention. Streaming is a must-have for any AI text tools and it's unfortunate that n8n is behind the curve on this.

**Comment by kaonmir** [comment]
I hope this feature to be implemented soon 🙃 I wanna stream to Open WebUI

**Comment by tan-yong-sheng** [comment]
+1

**Comment by changezzz** [comment]
Up

**Comment by wuzhihaogithub** [comment]
Any update?

**Comment by mardev60** [comment]
Hi ! Any updates for streaming mode ?

**Comment by Jordy-A** [comment]
Any update?

**Comment by DVSR-dev** [comment]
Update?

**Comment by Raq-3773** [comment]
Yes! It is really needed!

**Comment by wauputr4** [comment]
Up, this important feature

**Comment by J7503303** [comment]
This is absolutely an essential feature! AI applications that don't support streaming responses would be very disappointing, and I'm considering whether to continue using them.

**Comment by tdwify** [comment]
yes!

**Comment by CrankGentleman** [comment]
Up, this important feature

**Comment by papajbeautiful** [comment]
Please!

**Comment by geiker** [comment]
+1

**Comment by pauloamgomes** [comment]
+1

**Comment by James4Ever0** [comment]
+1

**Comment by CrankGentleman** [comment]
I really hope this feature can be implemented as soon as possible, because I really need it.

**Comment by DavideDelbianco** [comment]
Will we ever see this feature? there are topics and issues dating back to almost 1year ago requesting this feature :(

**Comment by w32zhong** [comment]
+1

**Comment by imissapixel** [comment]
+1

**Comment by trojanbox** [comment]
+1

**Comment by isaachwt** [comment]
+1

**Comment by oscarho7** [comment]
+1

**Comment by Pierf22** [comment]
+1

**Comment by hungngodev** [comment]
+1

**Comment by jeannotdamoiseaux** [comment]
+1

**Comment by johnodoplatforms** [comment]
following this. Streaming is a great feature to have

**Comment by julian-hecker** [comment]
streaming would be fantastic

**Comment by maglat** [comment]
+1

**Comment by justin-kaese** [comment]
+1

**Comment by chsiny** [comment]
+1

**Comment by IgorFZ** [comment]
+1

**Comment by jadl456** [comment]
+1

**Comment by amithkk** [comment]
+1 - this is essential to consider n8n to be a usable AI agent building tool. This is all the more relevant with the recent add of agents as tools to agents capability.

**Comment by jeannotdamoiseaux** [comment]
The latest pre-release ([n8n@1.104.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.104.0)) introduces support for HTTP Streamable Transport in the MCP Client Tool node.

**Comment by yogasw** [comment]
+1

**Comment by maglat** [comment]
> The latest pre-release ([n8n@1.104.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.104.0)) introduces support for HTTP Streamable Transport in the MCP Client Tool node.

So how is this working?

**Comment by yogasw** [comment]
I tried it on version [n8n:1.104.2](https://github.com/n8n-io/n8n/compare/n8n@1.104.2) This problem did not occur, and I was able to use OpenAI with streaming mode set to false.
