### ISSUE TITLE
In Microsoft SQL Node can't copy query result preview

### ISSUE THREAD

**Issue by agilsantos** [n8n-io/n8n#11603]
### Bug Description

When i try to select and copy the result query for debug, the popup closes.

[bug_n8n.zip](https://github.com/user-attachments/files/17651050/bug_n8n.zip)

### To Reproduce

1. On a "Microsoft SQL" node with operation execute query
2. Type an expression on the query text box
3. Click on the query text box to show the result popup
4. With the mouse try to select the result and the popup will close

### Expected behavior

it should only close when you click outside of the popup not on the popup allowing you to select and copy it's contents

### Operating System

Docker Container on Ubuntu

### n8n Version

1.65.2

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

##### core

- n8nVersion: 1.65.2
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community
- consumerId: unknown

##### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

##### pruning

- enabled: true
- maxAge: 730 hours
- maxCount: 10000 executions

##### client

- userAgent: mozilla/5.0 (windows nt 10.0; win64; x64) applewebkit/537.36 (khtml, like gecko) chrome/130.0.0.0 safari/537.36 edg/130.0.0.0
- isTouchDevice: false

Generated at: 2024-11-06T17:44:32.114Z

**Comment by Joffcom** [comment]
Hey @agilsantos,

Thanks for the report, A fix has been put in once reviewed and merged it will be available in a future release.

**Comment by janober** [comment]
Fix got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)
