### ISSUE TITLE
No binary data returned in Read/Write Files from Disk

### ISSUE THREAD

**Issue by tautv** [n8n-io/n8n#11618]
### Bug Description

Read/Write Files from Disk node fails to return data if the filename (or directory/folder name) contains both "(" and ")".
Only affects Read part.
Write part works ok.

Read will work if only ) is present. 
Read will work if only ( is present.
Read will not work if both ( and ) are present, either in Filename or Directory Name.

### To Reproduce

1. Create two files locally - "test1.txt" ; "test(1).txt"
2. Create a Read/Write Files from Disk node (Operation: "Read File(s) From Disk")
3. test1.txt returns 'data'; test(1).txt doesn't:

Without ( and ):
<img width="773" alt="Screenshot 2024-11-07 at 10 12 52" src="https://github.com/user-attachments/assets/5fe371dc-a667-4cb8-87ee-58acc5d79573">

With ( and ) in filename:
<img width="800" alt="Screenshot 2024-11-07 at 10 12 58" src="https://github.com/user-attachments/assets/7dfa1def-7d97-40dd-a653-01a307792d89">

With ( and ) in foldername:
<img width="783" alt="Screenshot 2024-11-07 at 10 20 54" src="https://github.com/user-attachments/assets/df3717a3-f17c-4da6-9f32-fa874cbcdda9">

### Expected behavior

Read should work with files and folder containing ( and ).

### Operating System

MacOS - Sonoma 14.6.1

### n8n Version

1.66.0

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
This is now in Linear and is being tracked as `NODE-2010`

**Comment by tautv** [comment]
I did a quick/dirty fix on my side:
[packages/nodes-base/nodes/Files/ReadWriteFile/actions/read.operation.ts](https://github.com/n8n-io/n8n/compare/master...tautv:n8n:master#diff-52c3285b93a618f8ce4a92a14d74df635b57ce1be7eedd9afe6faf024e76b7fa)
`fileSelector = fileSelector.replace(/([()])/g, '\\$1');`

Was going to open PR, but can't get the `pnpm test` to run.

This solved my parentheses issue, but not sure if it breaks anything else.
