### ISSUE TITLE
[New Canva] Forced Authentication data on Webhook node.

### ISSUE THREAD

**Issue by 0nl1n1n** [n8n-io/n8n#11622]
### Bug Description

When you create a node with a generic type of authentication, in my example it's a "header auth", and I assign it to a node within a workflow, then the webhook that triggers this workflow gets assigned automatically the same "header auth" type of authentication on the webhook. So, even if you try to go back to the webhook and put authentication "none", it will still, once you save it, re-put the authentication "Header Auth".

### Steps to Reproduce the Issue

1. **Create a Workflow:**
   - Open **N8N** and start a new workflow or open an existing one.

2. **Add Webhook Node:**
   - Add a **Webhook** node to the workflow as your initial trigger.

3. **Set Webhook Authentication to None:**
   - Open the webhook node settings and set the **Authentication** option to **None**.
   - Save the workflow to confirm this setting.

4. **Add a New Node with Header Auth:**
   - Add a node that requires authentication (e.g., an **HTTP request** node or any custom node).
   - Set this new node's **Authentication** to **Header Auth** and configure the required details.
   - Save the settings and the workflow.

5. **Verify the Webhook Authentication:**
   - Go back to the **Webhook** node and check if the **Authentication** has switched to **Header Auth**.
   - If it has not, change it back to **None**, save, and then check if it reverts to **Header Auth** after a save or reload of the workflow.

### Expected behavior

Being able to remove the authentication on the trigger webhook node.

### Operating System

20.04

### n8n Version

1.65.2

### Node.js Version

Good Question

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Is this the same as #11610?

**Comment by 0nl1n1n** [comment]
Yes my bad!

**Comment by Joffcom** [comment]
In that case I will mark this as closed for now so we can focus on the one issue.
