### ISSUE TITLE
WhatsApp Trigger Node Fails with "Invalid Parameter" Error

### ISSUE THREAD

**Issue by hscalabrini** [n8n-io/n8n#11625]
### Bug Description

When creating a WhatsApp trigger node in a new or empty workflow, with credentials correctly set up and verified in WhatsApp, activating the workflow or running a test results in the following error message:

Problem running workflow
Bad request - please check your parameters
Show Details
WhatsApp Trigger: Invalid parameter.

The trigger is configured to activate on incoming messages, but it fails regardless of workflow configuration.

Additional Context:
This issue started after restarting Docker Compose to update the WEBHOOK_URL environment variable, following a change to the public domain. This change may have impacted the WhatsApp trigger node functionality. Additionally, a fresh installation of n8n was attempted, but the issue persists.

Docker Compose Configuration
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=######-######-######.ngrok-free.app
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

Debug Information
Core Details

n8nVersion: 1.66.0
Platform: Docker (self-hosted)
NodeJS Version: 20.18.0
Database: SQLite
Execution Mode: Regular
Concurrency: -1
License: Enterprise (production)
Consumer ID: 1df34cfb-4fdf-43cd-b86c-5fb0bf8f1a8d
Storage Settings

Success: All
Error: All
Progress: False
Manual: True
Binary Mode: Memory
Pruning Settings

Enabled: True
Max Age: 336 hours
Max Count: 10000 executions
Client Information

User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Is Touch Device: False
Timestamp: 2024-11-07T13:42:06.629Z

### To Reproduce

0. Restart Docker Compose after changing the WEBHOOK_URL environment variable due to an updated public domain.
1.Create a new workflow in n8n.
2.Add a WhatsApp trigger node configured to activate on incoming messages.
3.Set up and verify WhatsApp credentials (confirmed as correct).
4.Activate the workflow or run a test on the WhatsApp trigger node.

### Expected behavior

The workflow should activate or successfully test, listening for incoming messages as specified in the trigger configuration.

### Operating System

Ubuntu 20.04.6 LTS 

### n8n Version

1.66.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by hscalabrini** [comment]
The issue was caused by the webhook URL configuration in Docker Compose. WhatsApp requires that all webhook URLs use HTTPS for security reasons. When the webhook URL does not start with 'https://', WhatsApp rejects the registration with an error message indicating that the callback URL must be secure (HTTPS). To resolve this, the environment variable WEBHOOK_URL  in Docker Compose needs to include 'https://' at the beginning. This ensures that the webhook registration meets WhatsApp’s security requirements and prevents the 'Invalid parameter' error from occurring again.

**Comment by blerio-cyber** [comment]
hi, please how can i fix the the https issue in my docker compose
