### ISSUE TITLE
no conflict detection: multiple tabs with editor saves overwrite each other with stale data

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11638]
### Bug Description

No check is done on wether a save point has been created before "on save", overwriting the workflow with stale data...

### To Reproduce

1. open 2 editors with the same workflow
2. edit in one window and save
3. edit in another window and see previous save is overwritten

### Expected behavior

conflict detection

### Operating System

docker

### n8n Version

1.65.2

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-405"

**Comment by Joffcom** [comment]
Hey @Morriz 

This sadly is to be expected at the moment, we don't support multiple users editing the same workflow at the moment which means the last person to save gets their changes.

We have started work on implementing this, for now though it might be worth popping a vote on this request https://community.n8n.io/t/warn-if-the-workflow-changed-in-another-tab/44977

As this is not a bug I am going to move this to closed, let me know if you have any questions on this.
