### ISSUE TITLE
Requesting to save workflow even without changing anything

### ISSUE THREAD

**Issue by agldiasdigital** [n8n-io/n8n#11636]
### Bug Description

After I updated to the latest version (1.66.0) and activated the Community Edition license, every time I open a workflow, the save button is already activated, even without me changing anything. And when I try to leave the page, it asks if I want to save before exiting.

### To Reproduce

1. Open workflow
2. Go to any other page or close the tab
3. Modal asking to save, even without having edited the workflow

### Expected behavior

Exit the workflow without having to see the message to save, even though I haven't changed anything (which ends up generating doubt as to whether I changed something by accident or if I changed it and forgot to save it)

### Operating System

Ubuntu 24.04.1 LTS

### n8n Version

1.66.0

### Node.js Version

18.+19.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @agldiasdigital,

We have created an internal ticket to look into this which we will be tracking as "GHC-403"

**Comment by Joffcom** [comment]
Hey @agldiasdigital 

This looks to have been resolved in 1.67.0 which was released yesterday in this PR: #11579

If after upgrading you still this issue let me know and we can re-open this issue.

**Comment by agldiasdigital** [comment]
> Hey @agldiasdigital
> 
> This looks to have been resolved in 1.67.0 which was released yesterday in this PR: #11579
> 
> If after upgrading you still this issue let me know and we can re-open this issue.

Thanks for the feedback :)
