### ISSUE TITLE
body missing from gmail node when `simplify` chosen

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11637]
### Bug Description

There is a toggle called `simplify` that supposedly removes cruft from the response, like useless headers that take up way too much space. But it also removes the email text content which is not helpful!

Toggling it off says it will forward the raw emails as is, which makes n8n throw errors when I use `getMany` with `limit: 10`:
```
Display data?
The node contains 1.1 MB of data. Displaying it may slow down your browser temporarily.
```

Can we get some sane defaults so that we don't run into issues with this node? I guess including the body text would be nice, or you could just add some extra option to remove headers?

### To Reproduce

1. choose gmail node
2. turn on simplify
3. getMany emails (test)
4. observe no body to be found 

### Expected behavior

at the minimum the body to be included as text

### Operating System

docker

### n8n Version

1.65.2

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-404"

**Comment by Joffcom** [comment]
Hey @Morriz 

I was wondering if this was ever going to come up, waaaay back in the v1 node we did have a third option that included the body but in this case the idea was to keep the request light so you get the id and some basic info with the intention of using a get Message option with the ID if you wanted the body.

It could be that we need to revisit this but currently this is intended behaviour and not a bug. If you would be interested in seeing body being added I would pop open a feature request on the forum and we can see if others feel the same way.

I will also bring this up in our node team meeting next Wednesday as it feels like adding an option to simplify to include body would be a fairly quick win.

**Comment by Morriz** [comment]
Please do as removing the key property of the payload was a dumb thing to do

**Comment by Morriz** [comment]
I would reopen this as it is perceived as a bug by users imo
