### ISSUE TITLE
Outlook Tool / node missing "Attendee" in Create Event

### ISSUE THREAD

**Issue by jamesSFCG** [n8n-io/n8n#11640]
### Bug Description

I see that the Google Calendar tool has the ability to Create an event with attendees, but not the Outlook Tool / Node.  Is this a bug or an oversight.  I see "Hide Attendees" is an option.

### To Reproduce

Create new Tool or Node (outlook) 
Choose Event
Choose Create.

Observe optionis...

### Expected behavior

An "Attendee" field should be available, to be populated or not (as the case may be) with an email address

### Operating System

Docker Image

### n8n Version

1.66

### Node.js Version

20.18

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jamesSFCG,

We have created an internal ticket to look into this which we will be tracking as "GHC-406"

**Comment by Joffcom** [comment]
Hey @jamesSFCG 

Looks like it was never part of the plan, it would make a good feature request though if you wanted to raise it on the community support forum here: https://community.n8n.io/c/feature-requests/5

For now as this isn't a bug I am going to move this to closed, let me know if you have any questions on this.
