### ISSUE TITLE
html extraction concatenates without separator

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11648]
### Bug Description

the html node does extraction without providing a separator for its concatenation of text chunks, leading to words joined.

### To Reproduce

1. use html node and extract any html page
2. observe words joined

### Expected behavior

At the minimum a newline `\n` to be used for concatenation, at best a configurable separator offered so that we may choose our own.

### Operating System

docker

### n8n Version

1.65.2

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-409"

**Comment by Joffcom** [comment]
Hey @Morriz,

Can you provide an example workflow that shows this bug in action?

**Comment by Joffcom** [comment]
Have done a quick test if I want to extract the 4 title values here...

![image](https://github.com/user-attachments/assets/163a6e81-9bbc-43d8-bd99-b69451d5582c)

All 4 get extracted as I would expect if I use the array option otherwise I only get the first one.

![image](https://github.com/user-attachments/assets/c1971039-b5d1-4fdb-9625-66f56e78efa3)

**Comment by Morriz** [comment]
imo the "Return Array" option is not helpful as it needs another node to concatenate again. Again, it would be nice to be able to choose a separator for joining those chunks.

**Comment by Joffcom** [comment]
But are you expecting multiple options back or just one? If you can provide a workflow we can see if this is a bug or a feature request.

**Comment by Morriz** [comment]
you gave the example to return as array, but when turned off the app just concats blindly without separator. This should not be hard to understand...

**Comment by Joffcom** [comment]
@Morriz if I disable the option to return as an array I get one item back which is the first selected and there are no words joined as seen in the image below.

![image](https://github.com/user-attachments/assets/2ad58b45-d660-42f4-a458-6a723c8f6810)

This is why I have asked for a workflow that reproduces the issue you are reporting.

**Comment by Morriz** [comment]
I am not sure what happened, but I am now at 1.66 something and the html parts are now joined by a space...closing this as fixed
