### ISSUE TITLE
Question and Answer Chain does not allow to pass on the text to match

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11656]
### Bug Description

The QA chain passes on the prompt as-is to the vector store, which convolutes the input to match on. This makes the store return many irrelevant documents, which is a bug imo, as it should be matching against input and not a prompt. The chain's llm should get a separate prompt, while the vector store should get a configurable text selector.

### To Reproduce

1. create a QA chain
2. create a prompt instructing the LLM to format the results
3. observe the results to match the LLM instructions

### Expected behavior

The results to match some query input

### Operating System

docker

### n8n Version

1.65.2

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-413"

**Comment by Morriz** [comment]
I actually think this one is a big oversight. I understand you are building a lot of abstractions without actually implementing many of the real world use cases in user land, but this one def should be in your setup imo....

**Comment by OlegIvaniv** [comment]
@Morriz That doesn't sound right. Question and Answer Chain only passes the `Text` as the search to the vector store, the system message is only passed to the LLM with the retrieved context. You can very easily confirm this by looking at the AI logs:
![CleanShot 2024-11-08 at 16 04 27](https://github.com/user-attachments/assets/5896b1a6-d188-4148-9e7c-ffb5cb43eefe)
Here's a video with a quick explanation:

https://github.com/user-attachments/assets/051b1d8d-f94f-4185-acf5-10053ef5c2b1

If you're seeing a different behaviour, please open a new issue with some screenshots and ideally a workflow to reproduce it.

Oleg

**Comment by Morriz** [comment]
Wow @OlegIvaniv, you have a lot more fields than I have (I am at 1.65.2):
![kxW0Ufgz](https://github.com/user-attachments/assets/3c51e940-e752-4117-a21d-504daa15dbd5)

**Comment by Morriz** [comment]
I feel stupid as I overlooked that!
