### ISSUE TITLE
Tried to process a data mp3 to an api with simple curl request but not working

### ISSUE THREAD

**Issue by radu-bitspot** [n8n-io/n8n#11652]
### Bug Description

Try to send to an api mp3 file from the n8n request node but something is not right it don't take the input..

### To Reproduce

![image](https://github.com/user-attachments/assets/754c7497-1fa8-4987-a18d-b84b36d141d0)
if i try with simple curl bellow it works
curl -X POST -F "file=@a4ac24ba-6799-4312-a4ab-74b40c04c020.mp3" http://localhost:5001/transcribe
is there something that i missing or is just bug?

### Expected behavior

to be able to send the file to the api :(

### Operating System

Docker

### n8n Version

1.64.3

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @radu-bitspot,

We have created an internal ticket to look into this which we will be tracking as "GHC-410"

**Comment by Joffcom** [comment]
Hey @radu-bitspot,

The field is asking for the value rather than the data itself, Can you try just inputting `data` and let me know if that works.

**Comment by radu-bitspot** [comment]
> Hey @radu-bitspot,
> 
> The field is asking for the value rather than the data itself, Can you try just inputting `data` and let me know if that works.

it worked with changing the paramer type and data. Thank you. you can close this
![image](https://github.com/user-attachments/assets/f16662eb-c6b5-4551-9d49-91b29bbbb9d4)

**Comment by Joffcom** [comment]
Perfect thanks for letting me know @radu-bitspot
