### ISSUE TITLE
image file to base64 encoding not getting any  output

### ISSUE THREAD

**Issue by jithinagiboson** [n8n-io/n8n#11663]
### Bug Description

i wanted to use ollama vision model using n8n but ollama require image to be converted to base64 string.I try to use Extract from file but didnt work may be there is some easier way 
my setup 
![image](https://github.com/user-attachments/assets/5c3a809c-3c32-4fe1-bd79-19f373079640)

form submit->Extract from file ->http request
Extarct from file 
![image](https://github.com/user-attachments/assets/f526ee3f-fe4b-46ec-a4f5-d236ed505b9e)

what can i change to get the output

### To Reproduce

form submit->Extract from file ->http request
just try to convert file into base64 using Extarct from file 

### Expected behavior

output to be base64 string

### Operating System

windows

### n8n Version

1.66.0

### Node.js Version

v20.10.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by jithinagiboson** [comment]
i what able to do it using this setup instead .Seems more convenient and easier for my purpose .But still i wonder why image to base64 string did not work as expected
![image](https://github.com/user-attachments/assets/f2024029-5e8f-46a5-88ad-592297e50741)

**Comment by Joffcom** [comment]
Hey @jithinagiboson 

The conversion is after the field name not the data itself so if you would input `file` it will work. Did you want to give it a quick go to confirm it works?

**Comment by jithinagiboson** [comment]
> Hey @jithinagiboson
> 
> The conversion is after the field name not the data itself so if you would input `file` it will work. Did you want to give it a quick go to confirm it works?

are you talking about Extract from file? or ai agent .The ai agent setup works but the Extarct from file didnt

**Comment by Joffcom** [comment]
Hey @jithinagiboson 

In extract from file.

**Comment by jithinagiboson** [comment]
i understood the issue but its confusion when to drag and drop fields from previous node and when to just put name 
![image](https://github.com/user-attachments/assets/08032740-ce08-4265-b09b-c6698c097c0f)

**Comment by jithinagiboson** [comment]
IT WORKS

**Comment by Joffcom** [comment]
@jithinagiboson the drag and drop is a very good point on those fields
