### ISSUE TITLE
WooCommerce node does not pass previous input

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11664]
### Bug Description

Hi, when I use the WooCommerce node to get some info, it does not pass on the previous input.
Maybe I hit on some edge case, as I loop back, see json file:
[My_workflow_2.json](https://github.com/user-attachments/files/17689766/My_workflow_2.json)

### To Reproduce

1. create the workflow as given
2. run

### Expected behavior

The previous node input to be available for the next loop

### Operating System

docker

### n8n Version

1.66.0

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-418"

**Comment by Joffcom** [comment]
Hey @Morriz,

Looking at your workflow and the steps you have provided there appears to be some missing information.

What data are you sending to the workflow?
What does your Redis value look like for `heman/auth/{{ $('Execute Workflow Trigger').item.json.query.email }}`?
Do you have a screenshot showing the issue?
When you say it does not pass the previous input what do you mean? I would only expect it to pass the output of "Get All Customers" Assuming this is the node with the issue and not the tool attached to the Tools Agent.

**Comment by Joffcom** [comment]
Looking at the loop it could be ok, it is hard to say as we don't have anything we can run to test but the data should be available it may just need selecting using the run index.
