### ISSUE TITLE
Ctrl + mousewheel scrolls instead of zooming in/out

### ISSUE THREAD

**Issue by MKulys** [n8n-io/n8n#11667]
### Bug Description

In the Executions window, using Ctrl + Mousewheel scrolls the workflow up & down, instead of zooming in/out as it does in the Editor window.

### To Reproduce

1. (Optional) Open a workflow in the Editor window and use Ctrl + Mousewheel to check if it zooms in/out
2. Open the same workflow in the Execution window
3. Choose one of the executions
4. Use Ctrl + Mousewheel to zoom in/out
5. Step 4 instead scrolls up and down

### Expected behavior

In the Executions window, using Ctrl + Mousewheel should zoom in/out, same as it does in the Editor window.

### Operating System

Windows 11

### n8n Version

1.65.2

### Node.js Version

Unsure

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MKulys,

We have created an internal ticket to look into this which we will be tracking as "GHC-420"
