### ISSUE TITLE
Always have to "save" workflows while in New Canvas Mode

### ISSUE THREAD

**Issue by nicolas-geysse** [n8n-io/n8n#11670]
### Bug Description

While opening any workflow, the "Saved" buton is always red, and needs to be "save" (or you get a warning that you'll loose your last changes if not)
It occurs only while the "switch to new canvas" is activated.
No problem at all with the old canvas mode.

### To Reproduce

1.Activate the new canvas mode.
2.open any workflow
3see the buton "Save" highlighted directly after opening (even if no changes are made)

### Expected behavior

To have the save buton highlighted only if there are changes in the workflow.

### Operating System

?

### n8n Version

1.66

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @nicolas-geysse,

We have created an internal ticket to look into this which we will be tracking as "GHC-422"

**Comment by nicolas-geysse** [comment]
Hi @Joffcom,
Also tested in the cloud version , under 1.67.1 , and there's no issue here :)

**Comment by Joffcom** [comment]
Hey @nicolas-geysse 

You nailed it there, we have fixed  this already in 1.67 so you would just need to upgrade.

As this is resolved I am going to mark this as closed.
