### ISSUE TITLE
Basic LLM Chain Node with Item List Output Parser is always returning 3 items at maximum

### ISSUE THREAD

**Issue by eliasmainetti** [n8n-io/n8n#11686]
### Bug Description

Basic LLM Chain is always returning 3 items at the maximum even if I set Item List Output Parser to -1

<img width="280" alt="image" src="https://github.com/user-attachments/assets/f2815f1a-1ff7-4c7b-99f2-cfd49864530b">

<img width="317" alt="image" src="https://github.com/user-attachments/assets/ce569a5c-3ef7-43ed-8640-07148d92c8fa">

### To Reproduce

Create a Basic LLM Chain with Item List Output Parser and Set the Number of items -1 and the Separator (\n for example). N8N will always return 3 items at maximum

### Expected behavior

From the logs we can check that the LLM Node Model is returning the answer as expected, with ***** separator. But the Basic LLM Chain is returning always  3 itens at the maximum, while  the answer should have more than 20 itens. 

<img width="958" alt="image" src="https://github.com/user-attachments/assets/53df7fc4-1d01-4ed0-9724-fcb88eb4d025">

### Operating System

Docker Swarm Engine 24.0.7

### n8n Version

1.66.0

### Node.js Version

Docker 1.66.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @eliasmainetti,

We have created an internal ticket to look into this which we will be tracking as "GHC-425"
