### ISSUE TITLE
Workflow Executions Displaying the Same Timestamp

### ISSUE THREAD

**Issue by ArthurLVVilla** [n8n-io/n8n#11718]
### Bug Description

When running workflows in n8n, all execution entries are showing the same timestamp, making it difficult to identify at which specific time each execution ran and pinpoint which one encountered an error. This impacts the ability to monitor workflows effectively.

### To Reproduce

1. Go to the n8n interface and open any workflow.
2. Trigger the workflow multiple times to generate multiple executions.
3. Navigate to the "Executions" section to view the list of recorded runs.
4. Observe that all executions are displayed with the same timestamp.

Example screenshot illustrating the issue:
![image](https://github.com/user-attachments/assets/c342ef42-cb65-413b-a98e-052346505b63)

### Expected behavior

Each execution should display its unique and correct timestamp to accurately reflect when it occurred, allowing users to track and identify specific runs.

### Additional Context

- The issue seems to be related to workflows created prior to version 1.66.0. Newly created workflows do not exhibit this problem.
- This suggests that the timestamp behavior might be tied to an update or migration step affecting legacy workflows.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.66.0

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by despairblue** [comment]
Thanks for sharing this report 🙏🏾 

I have a couple of questions that should help us figure out what's going on.

1. Would it be possible to share the workflow? 
2. Are all affected workflows use the schedule trigger?
3. From which version did you upgrade from?
4. What's the output of `SELECT * from execution_entity WHERE workflowId = '[Affected Workflow ID]';`

> This suggests that the timestamp behavior might be tied to an update or migration step affecting legacy workflows.

Maybe related to the version of the trigger node, they are not updated which means old workflows will have an older version of the trigger node. 🤔

**Comment by MarcL** [comment]
Hey @ArthurLVVilla!

We haven’t heard back for a while so we’re going to close this for now.

If you’re still running into the issue, or have more details to share, feel free to reopen it or create a new one. 

Thanks!

Closes: PAY-2331
