### ISSUE TITLE
New canvas: Zoom in via "+" key zooms out

### ISSUE THREAD

**Issue by pfiadDi** [n8n-io/n8n#11713]
### Bug Description

When I press + on my keyboard (QWERTZ Layout, German layout) the canvas zooms out. Pressing "-" works as expected (zooms out)

### To Reproduce

1. Open a workflow using the new canvas
2. Press + 

# Debug info

## core

- n8nVersion: 1.66.0
- platform: docker (self-hosted)
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: -1
- license: community

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: memory

## pruning

- enabled: true
- maxAge: 336 hours
- maxCount: 10000 executions

## client

- userAgent: mozilla/5.0 (x11; linux x86_64) applewebkit/537.36 (khtml, like gecko) chrome/130.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2024-11-13T07:35:16.529Z

### Expected behavior

It should zoom in

### Operating System

Debian GNU/Linux 12 (bookworm) 

### n8n Version

1.66.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @pfiadDi,

We have created an internal ticket to look into this which we will be tracking as "GHC-431"

**Comment by pfiadDi** [comment]
Hi @Joffcom thanks for your reply - just updated to 1.67.1. and I have the same problem

**Comment by Joffcom** [comment]
Hey @pfiadDi,

Can you try 1.68 as well? I just gave it a go and it appears to be working fine.
