### ISSUE TITLE
Unable to update any community node

### ISSUE THREAD

**Issue by eyepokes** [n8n-io/n8n#11723]
### Bug Description

The error appears on Windows and Unix-like (Ubuntu) platforms. Out of the 7 most popular npm packages, 0 were updated.
![pv](https://github.com/user-attachments/assets/5125a633-d9ea-413d-a442-3f753903a483)
![errorUI](https://github.com/user-attachments/assets/e366a146-0f67-4e9c-96de-6dd9f6206c52)
![debug](https://github.com/user-attachments/assets/3d0d231a-f74b-4927-9d12-b117cd354815)

### To Reproduce

1. Install n8n `npm install n8n -g`
2. Start n8n `n8n start`
3. Go to `Settings` -> `Community nodes` then press `Install`, paste to `npm Package Name` input field any n8n-nodes-* package with any previous version, for example: `n8n-nodes-text-manipulation@1.3.0`
4. Press the `Update` -> `Update package` button

### Expected behavior

It is expected that the node will be updated.

### Operating System

Windows 11, Ubuntu 12.04

### n8n Version

1.66.0

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @eyepokes,

We have created an internal ticket to look into this which we will be tracking as "GHC-437"

**Comment by eyepokes** [comment]
> @eyepokes have you opened this same question on the forum as well?

nope

**Comment by Joffcom** [comment]
Perfect just checking as a the same node was used in an example on a forum post earlier.
