### ISSUE TITLE
n8n Form Node failure when Completion Message contains JSON

### ISSUE THREAD

**Issue by briansoegaard** [n8n-io/n8n#11729]
### Bug Description

If I enter a JSON expression in the Completion Message in an n8n Node with the Page Type 'Form Ending,' and it's referencing a Form Field in the n8n Form Trigger node, the form fails.

[Form_bug_report-2.json](https://github.com/user-attachments/files/17739761/Form_bug_report-2.json)

This:
<img width="499" alt="image" src="https://github.com/user-attachments/assets/aceebeec-2d1f-484e-be92-a0526737f990">
contains this simple form:
<img width="356" alt="image" src="https://github.com/user-attachments/assets/adcd74ca-dd4b-4ab4-9d53-e93fd924ab68">

When I, in the final node showing the Completion Screen, enter this in the Completion Message:
<img width="575" alt="image" src="https://github.com/user-attachments/assets/9be7d584-ce3e-4c12-9e66-15bd6f76b4e7">
the form works fine:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/5fb594f7-6e2a-4359-a1ff-4cdb10ba2bbb">

But when I use an expression, e.g., like this:
<img width="564" alt="image" src="https://github.com/user-attachments/assets/bc68065e-c1ad-4f28-a827-ba58128f4cda">
the form is showing this error message after submit:
<img width="472" alt="image" src="https://github.com/user-attachments/assets/88a2867b-d5d0-4829-abaa-348cba1e07bf">

### To Reproduce

1. Add a n8nm Form with a Trigger node and a Form Ending node to a canvas
2. Configure a simple form in the Trigger node
3. Reference a form field in the End node's Completion Message
4. Form fails at commit

I have reproduced it in various versions over the past couple of weeks.

### Expected behavior

The form is complete4d successfully, referencing the content of a form field in the Trigger node.

### Operating System

Ubuntu Linux 22.04.1

### n8n Version

1.68.0

### Node.js Version

18.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @briansoegaard,

We have created an internal ticket to look into this which we will be tracking as "GHC-439"

**Comment by soucosmo** [comment]
I am facing the same issue here, when fixed text is used it works fine but when using variables the flow does not go to the next node.
