### ISSUE TITLE
Webhook returning the auth header every time the workflow is opened - in the new version of canva

### ISSUE THREAD

**Issue by Daniel13df** [n8n-io/n8n#11722]
### Bug Description

I'm using the new version of Canva which is excellent, however, I noticed that every time I open any workflow and make changes, the webhook trigger changes by itself from the header that was none to auth and this crashes the applications. So, every time I enter a workflow, I first have to update the webhook header to be able to update the nodes.

### To Reproduce

1. Open a workflow
2. open the webhook node
3. change the header to none
4. save
5. exit the workflow
6. sign in again
7. open the webhook and the header will be enabled again

### Expected behavior

The correct thing is to not need to change the webhook every time I enter the workflow.

### Operating System

Ubuntu 22.04 with Easypanel

### n8n Version

1.65.2

### Node.js Version

20.10.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Daniel13df,

We have created an internal ticket to look into this which we will be tracking as "GHC-436"
