### ISSUE TITLE
(ReAct) agent does not allow tools with inline JSON schema defined in their description

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11721]
### Bug Description

The ReAct agent is currently suffering from a bug (omitting injection of too schema): #11720

So, I was hopeful to be able to work around that by just specifying the schema in the description of a tool, but that was not allowed by the agent as during run time an error was thrown:
```
Problem in node ‘AI Agent‘
Single '}' in template
```

### To Reproduce

1. create a ReAct agent
2. add a tool that specifies json schema in the description
3. trigger workflow
4. observe error

### Expected behavior

The description to be injected into the system message without errors

### Operating System

docker

### n8n Version

1.66.0

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-435"

**Comment by Morriz** [comment]
How robust is all of this, I ask myself, as I keep finding basic flaws in design and implementation of these AI Agent nodes? Worrisome ;(
