### ISSUE TITLE
Internal Server Error with Antropic nodes

### ISSUE THREAD

**Issue by mennovdmm** [n8n-io/n8n#11734]
### Bug Description

All my Antropic nodes are giving an Internal Server Error (not specified which one). Can this have something to do with the latest release where Anthropic Chat Model Node: Added Haiku 3.5 support (great by the way!) was updated? It worked fine yesterday. Stopt about the same time when the new version was released. The exact same credentials work fine in Make.com. 

### To Reproduce

1. Add an anthropic node
2. Enter credentials 

### Expected behavior

Connection tested successfully 

### Operating System

Cloud version 

### n8n Version

n/a

### Node.js Version

n/a

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mennovdmm,

We have created an internal ticket to look into this which we will be tracking as "GHC-442"

**Comment by Joffcom** [comment]
@mennovdmm the PR is in it just needs reviewing then it will be merged. We release weekly so hopefully this will be included in the release on Wednesday.
