### ISSUE TITLE
What's app throw "Problem saving workflow Invalid parameter" for trigger action

### ISSUE THREAD

**Issue by naormega1** [n8n-io/n8n#11745]
### Bug Description

after configure whatspp using the whatspp trigger node ( after getting good connection )
when try to save flow - getting 

Problem saving workflow
Invalid parameter

### To Reproduce

1. go to trigger
2. add whatatpp trigger ( get messages )
3. add client id and secret id + validate good connection
4. save flow

### Expected behavior

to allow trigger from whatapp

### Operating System

linux

### n8n Version

 1.66.0

### Node.js Version

latests

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @naormega1,

We have created an internal ticket to look into this which we will be tracking as "GHC-444"

**Comment by Joffcom** [comment]
Hey @naormega1,

Do you happen to have a screenshot of the workflow including the error? It sounds like an option is missing in the node or... the webhook url is still using localhost.

**Comment by naormega1** [comment]
Hey @Joffcom 
the webhook url are indeed using localhost - but there is no way to change it
![image](https://github.com/user-attachments/assets/b92d7ab2-824a-4bc1-bd7e-4edce7985352)

**Comment by Joffcom** [comment]
Hey @naormega1,

Perfect so this will be a configuration issue, When setting up n8n you need to set `WEBHOOK_URL` as an [environment option](https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/) if you are planning to have applications from outside your network connect in.

As there is no bug here I am going to mark this as closed.

**Comment by naormega1** [comment]
Thanks! 
this will work if I will run n8n in a container?

**Comment by Joffcom** [comment]
Yeah I don't see why not.

**Comment by lucioflaviodev** [comment]
set WEBHOOK_URL=https://<seu-dominio-ou-ngrok&& npx n8n
