### ISSUE TITLE
Jotform Trigger node Changes webhook

### ISSUE THREAD

**Issue by TouchstoneMediaSEO** [n8n-io/n8n#11760]
### Bug Description

I use the jotform trigger node to receive the data from jotform regularly and across multipule workflows. The problem has started when workflows were being triggered by the wrong trigger node. I seleceted the correct form in jotform but it keeps triggering the incorrect workflow. Part of the setup is to go into jotform and give the form the webhook from the trigger node you wish to fire. Every time the node fires it chnages the webhook though. which doesnt make any sense at all because the trigger node has a diffrent form selected and no correct webhook assigned to the jotform which means it shouldnt have any way of firing at all. 

### To Reproduce

1. Create a jotform
2. Assign a trigger node to that jotform completion
3. get the webhook from the trigger node
4. assign that webhook to the jotform under integrations, webhook
5. fire the form
6. look in your executions and see the webhook that was used
7. that webhook is diffrent than the webhook used to create the integration

### Expected behavior

The webhook shold remain consistant and thus maintain connections both to the jotform assigned as well as the trigger node you pulled it from

### Operating System

Could

### n8n Version

1.66.0

### Node.js Version

n/a

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @TouchstoneMediaSEO,

Can you try updating and let me know if you still see the same issue? Are you also using the new canvas or the old one?

**Comment by Joffcom** [comment]
Hey @TouchstoneMediaSEO,

Did you manage to update in the end?

**Comment by Joffcom** [comment]
We’re closing this issue for now since we haven’t heard back from you in a while. No worries, though—if you still need assistance or have more information to share, feel free to reopen it anytime. We’re always happy to help! 😊

Thanks for reaching out, and have a great day!
