### ISSUE TITLE
redis node does not pass on vars

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11765]
### Bug Description

When I use this workflow I see that the redis node blocks throughput of previous vars:

[Auth_status.json](https://github.com/user-attachments/files/17787486/Auth_status.json)

### To Reproduce

1. try snippet 
2. observe redis route not passing on stuff

### Expected behavior

The known vars to propagate

### Operating System

docker

### n8n Version

1.67.1

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Morriz** [comment]
nevermind, I saw wrong config used

**Comment by Morriz** [comment]
Oops, updated config....but still missing some vars from the input, like `customerEmail`

**Comment by Morriz** [comment]
@Joffcom I believe EVERY node should have that toggle "Include Other Input Fields" (turned on by default), so we can be certain that all our inputs get passed on.

I surely hope that the Redis node is not the only instance blocking inputs....this is a serious issue.

**Comment by Joffcom** [comment]
Hey @Morriz,

Can you clarify what is missing? For me as I don't have the key in my Redis instance it is returning null which I expect.

![image](https://github.com/user-attachments/assets/04999509-01e8-46c1-ac82-36b36569a125)

Doing a quick check the values from before the Redis node can still be used when accessed 🤔

Are you maybe expecting the Redis node to output all of the input items as well as the result from the Redis query? If that is the case n8n doesn't work like that with most of the nodes we will output the result of making that query or API request. To access the values you would do what you did in the Edit fields nodes and reference the previous node that had the data by name using `$('Input').item.json.customerEmail`.

**Comment by Morriz** [comment]
> If that is the case n8n doesn't work like that with most of the nodes we will output the result of making that query or API request.

Aha, any reason those nodes do not pass them on? It is hurtful as it breaks the paradigm and makes us do all that extra work

**Comment by Morriz** [comment]
That is a poor design decision imo for these reasons:

1. It breaks the rest of the chain when any of such nodes is put in between during building, when we rely on `$json.{prop}` style (which we should be able to depend on imo).
2. It is not needed to block props as users are able to configure on what props data from database nodes is returned.
3. Users have to now add cumbersome brittle plumbing that is tied to nodes which might get removed (as in the "solution" you suggested). This is a very common problem we run into all the time.
4. When you give users the "power" to choose their own configuration to let them use props to flow forward, you should ALSO leave them responsible for their actions and just help them learn.

It seems n8n opted for a mixed bag, translating into some nodes not passing props because n8n team suddenly decides "oh no, users will get confused, we have to make this node behave differently!", which feels like being treated as a toddler by a mom with ADHD ;p


I strongly advise the team to revisit this, as it might fix this once and for all, and MOST OF ALL, gives a smooth future where users can rely on a paradigm, and trust workflows not to break because of nodes not honoring this super powerful flow paradigm...I rest my case now...

**Comment by Morriz** [comment]
It is better to refactor this to become reliable imo, and do it asap, before it becomes too big and leads to more frustration amongst the user base.

I see no reason that unforeseen "breaking changes" would arise from such refactoring, as it all pertains userland configuration, which should be expected to work with props from previous nodes in the first place. It is up to users to make sure that props do not get overwritten by choosing unique names, (or not, in case we DO want overwrites).

I think documentation in the release notes should address this with an explanation and a warning akin to "existing/previous props will now ALL be passed on in EVERY node, making this paradigm work consistenly and reliably. Before this change users were already expected to know the props-passing paradigm and have a clean property naming scheme that makes use of this powerful core functionality"

**Comment by Morriz** [comment]
So, from a business and maintenance perspective this would be a major win, and users could all breathe again, knowing we would not have to workaround so many issues....

**Comment by Joffcom** [comment]
@Morriz there are multiple parts to this...

> It breaks the rest of the chain when any of such nodes is put in between during building, when we rely on $json.{prop} style (which we should be able to depend on imo).

It does break the workflow if you pop in a node that queries a service and you have only used `$json.x` however for multiple reasons just adding to the same schema is likely to be a bad idea.

>It is not needed to block props as users are able to configure on what props data from database nodes is returned.

Props are not blocked and users are not able to configure what props come back from all services. This happens for any node that queries a service or is likely to change the data like the code node.

>Users have to now add cumbersome brittle plumbing that is tied to nodes which might get removed (as in the "solution" you suggested). This is a very common problem we run into all the time.

If you use the $('xxx') option for previous nodes and you rename that node we will also update the expression for you, If you were to delete the node though you would have an error which I would also expect if you were to use `$json`. We have actually put some thought into this structure and approach based on feedback from user interviews and our internal use of n8n over the last 5 years.

>When you give users the "power" to choose their own configuration to let them use props to flow forward, you should ALSO leave them responsible for their actions and just help them learn.

We don't give them the "power" to choose their own confguration when it comes to our data structure but we do leave users responsible for their actions and help them learn.

>It seems n8n opted for a mixed bag, translating into some nodes not passing props because n8n team suddenly decides "oh no, users will get confused, we have to make this node behave differently!", which feels like being treated as a toddler by a mom with ADHD ;p

We don't tend to "suddenly decide" things, The nodes that do not pass on the input data as `$json` are the ones that most users would expect not to. This would be any node that interacts with an external service or a node that changes the input data and lets you set the output.

>I strongly advise the team to revisit this, as it might fix this once and for all, and MOST OF ALL, gives a smooth future where users can rely on a paradigm, and trust workflows not to break because of nodes not honoring this super powerful flow paradigm...

Reading what you have put I don't see anything that actually needs to be fixed it looks like you maybe just don't like how the data is handled between nodes and that is fine it won't be for everyone but the choices we make are based on what multiple users are feeding back and if that ever changes we may look to revisit it but for now all I can do with this is make the team aware for the future.

As there is no bug here I am going to mark this as closed, If you want to continue the converstaiton feel free to raise a feature request on the forum and we can take it from there.

**Comment by Morriz** [comment]
Don't get me wrong, I think you guys have gold in your hands, and it could be better than all the proprietary workflow tools that the big 4 are implementing in their walled gardens....but please be aware that suggestions like mine make it sooooo much easier and reliable for newcomers to n8n. Take away that friction so nobody jumps ship because of it...

**Comment by Morriz** [comment]
@Joffcom I have a very common use case that I am trying to build which is now not possible:

I created this sub-workflow that I want all data to pass through when I call it, as it just uses some parts for its own internals, but the parent workflow expects vars to pass through them but now it doesn't because the redis node in the sub-workflow blocks unknown vars passing through:
[Auth_status.json](https://github.com/user-attachments/files/17801346/Auth_status.json)

There is currently no workaround for me, and I can't use reusable sub-workflows like this because of this problem in n8n's architecture design.

I think my issue is a larger issue that needs to be addressed and taken on by the team. Shall I create a separate issue for that?

**Comment by Morriz** [comment]
There would be no breaking change if we were offered the same toggle on ALL nodes to let vars pass through, and just leave it at "no" by default for all such nodes that over time you made exceptions for for whatever reasons.

I rest my case

**Comment by Morriz** [comment]
@Joffcom for that I have created this feature request: https://community.n8n.io/t/all-nodes-should-have-toggle-to-pass-previous-inputs-to-fix-all-nodes-now-blocking/62279
