### ISSUE TITLE
Canvas animation not shown 

### ISSUE THREAD

**Issue by mlvnedward** [n8n-io/n8n#11789]
### Bug Description

Canvas animation not working & it shows execution. not complete tyhe workflow while testing

### To Reproduce

https://github.com/user-attachments/assets/1e036b2b-c288-4b32-9ae7-8fb22f280c28

### Expected behavior

Workflow completion not yet happened after 1 hr

### Operating System

Linux 20

### n8n Version

1.67.1

### Node.js Version

nil

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mlvnedward,

We have created an internal ticket to look into this which we will be tracking as "GHC-461"

**Comment by netroy** [comment]
What does the "Executions" tab show? it the execution stuck in that view as well?

**Comment by netroy** [comment]
This sounds like your websocket connection isn't working. 
Do you have a reverse-proxy setup in front of n8n? like nginx, caddy, or AWS ALB?
