### ISSUE TITLE
Slack Node: conversations.members & reactions.add

### ISSUE THREAD

**Issue by diadas** [n8n-io/n8n#1179]
Please add the following options to the Slack node:

- https://api.slack.com/methods/conversations.members
- https://api.slack.com/methods/reactions.add

I am thinking about creating a pull request for this, but I never did that yet.

**Comment by janober** [comment]
As our issue template clearly states are Github issues only for bugs and feature requests have to be posted to the community forum here:
https://community.n8n.io/

![Screenshot from 2020-11-18 14-36-55](https://user-images.githubusercontent.com/6249596/99537141-9623b100-29ab-11eb-8045-f817c968f628.png)

Thanks!
