### ISSUE TITLE
Received tool input did not match expected schema

### ISSUE THREAD

**Issue by rovictorbh** [n8n-io/n8n#11804]
### Bug Description

I keep getting this error even after the last update. I use the postegres database as an Agent AI tool. I use it to update my database. This is an important service. There are executions that work and executions that don't. This is complicated because I can't wait to put it into production.
<img width="1308" alt="Captura de Tela 2024-11-19 às 19 22 26" src="https://github.com/user-attachments/assets/14381ca5-2192-4529-b984-ba9a68330c67">
<img width="1473" alt="Captura de Tela 2024-11-19 às 19 22 04" src="https://github.com/user-attachments/assets/66512848-e499-4814-9c08-42000024bca3">

### To Reproduce

Just executing my workflow.

### Expected behavior

I just would like to execute correctly my workflow

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa)

### n8n Version

n8nVersion: 1.67.1

### Node.js Version

nodeJsVersion: 20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @rovictorbh,

We have created an internal ticket to look into this which we will be tracking as "GHC-464"

**Comment by jeanpaul** [comment]
Hi @rovictorbh, could you share the JSON for a minimal example that shows this error?

**Comment by rovictorbh** [comment]
Hi! Thank you for your help. I think my suggestion would be update this message error: “ Received tool input did not match expected schema” showing which tool node and parameter that is doing this issue. Usually… we have a lot of tool conected with agent and know what node is making problem and what parameters will be helpful. Tks again.I am a huge fan of N8N.RVEnviado do meu iPhone 14 ProOn 5 Dec 2024, at 07:46, jeanpaul ***@***.***> wrote:﻿
Hi @rovictorbh -- I'm closing the issue for now. Please feel free to re-open if you can still reproduce this issue and can provide the workflow JSON with a minimal example.

**Comment by stormliucong** [comment]
I had the same issue, the trick I found is you can not specify the type of placeholder as JSON. Leave it Not Specified (Default) solved my issue
