### ISSUE TITLE
not able to update the community nodes, when new version is available

### ISSUE THREAD

**Issue by anantanandgupta** [n8n-io/n8n#11840]
### Bug Description

when I try to update a community node to a new version, by clicking the update button visible next to the node name, it simply throws error. 

here is the example for the node showing the update 

![image](https://github.com/user-attachments/assets/2fdef3bb-13bb-4297-88a3-49e030a0364f)

and error message 

![image](https://github.com/user-attachments/assets/5e98cdfa-c808-437a-9715-b503aca8ca64)

it is not only this node, I have tried many other nodes.

### To Reproduce

1. install any community node (but pick an older version e.g. `n8n-nodes-mongodb@0.1.8`,
2. click on the `update` button next to the node.
  
![Google Chrome 2024-11-22 03 18 44](https://github.com/user-attachments/assets/7b359434-5b35-42af-998c-5208620ba4b3)

3. error pops up at the bottom right corner of the window.
  
![Google Chrome 2024-11-22 03 16 07](https://github.com/user-attachments/assets/c6e55b29-842e-40ce-80d6-a5acb518aec2)

### Expected behavior

newer version of the node should be installed

### Operating System

macOS (npm), Container (docker)

### n8n Version

1.66.0, 1.67.1

### Node.js Version

20

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @anantanandgupta,

We have created an internal ticket to look into this which we will be tracking as "GHC-475"

**Comment by Joffcom** [comment]
Hey @anantanandgupta 

This has been fixed in 1.69.0 can you try upgrading and let me know if you still have the same issue.

You can find the PR that fixed this here: https://github.com/n8n-io/n8n/pull/11727

**Comment by anantanandgupta** [comment]
@Joffcom it works in 1.69.0 as expected. 

thanks, i searched this issue in the open issues, my bad didn't see that in the closed issues. Otherwise might have not reports.

will be able to update the to latest version in prod when it is generally available, for now i have to live with the latest (1.68.0) :)
