### ISSUE TITLE
Sticky Notes misplaced on new canvas

### ISSUE THREAD

**Issue by TomSpidge** [n8n-io/n8n#11841]
### Bug Description

Sticky notes are misplaced on the new (Alpha) canvas compared to where they're placed on the old canvas. Moving them to the correct position on the new canvas and saving results in them moving back to the wrong position the next time the page is reloaded.
The wrong position is, in my experience, always lower and to the right of the correct positioning.
On pages with multiple sticky notes, not all of the are moved. It seems to happen mostly when switching between old and new canvas, and not all the time. Once it happens once it seems to continue indefinitely.

### To Reproduce

Create a sticky note using the old canvas and align it under a node.
Save the flow
Switch to the new canvas.
If the node has moved, put it back in the correct place, save and reload.
Before reload: ![image](https://github.com/user-attachments/assets/011a5dfc-ad8b-4e00-8ee3-f210a762cafb)
After reload: ![image](https://github.com/user-attachments/assets/2b729cf4-7c50-4fcf-8baa-f11090dec524)

### Expected behavior

Sticky note should remain in position

### Operating System

Ubuntu 22.04 / Docker

### n8n Version

1.67.1

### Node.js Version

20

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @TomSpidge,

We have created an internal ticket to look into this which we will be tracking as "GHC-476"

**Comment by Joffcom** [comment]
Hey @TomSpidge,

I have seen this in my own instance, My assumption was it is likely down to where the new canvas is a complete overhaul of the old one and not just an update so it could be that the positions in the canvas space are not the same.

**Comment by alexgrozav** [comment]
Fixed in https://github.com/n8n-io/n8n/pull/11624
