### ISSUE TITLE
Access to Excel 365 File

### ISSUE THREAD

**Issue by luca-manallarte** [n8n-io/n8n#11842]
### Bug Description

I am currently using Make to accomplish my internal business integration. But befor to consider to moove to n8n I shoub be able to convert the same worlflow I have in Make. Most of them starting from access all rows in an excel sheet. I tryed to connetc the same account I use in other services but it seems not working as I try to use the Excel 365 node and Get Rows operation, but no file appears in the list
![image](https://github.com/user-attachments/assets/528c643b-9123-41bf-b5f1-2fe81310850b)

### To Reproduce

Add an Excel 365 node
Access to my sharepoint file storage with correct credentials
Use Table and Get Rows action

### Expected behavior

I expect that the dropdown shows me the listo of file and folder into my one drive data storage

### Operating System

windows 11

### n8n Version

1.68.0

### Node.js Version

none

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @luca-manallarte,

We have created an internal ticket to look into this which we will be tracking as "GHC-477"

**Comment by Joffcom** [comment]
Hey @luca-manallarte,

Are the files in your personal OneDrive or Sharepoint?

**Comment by luca-manallarte** [comment]
yes my files are in the sharepoint (One drive folder)

________________________________
Da: Jon ***@***.***>
Inviato: venerdì 22 novembre 2024 12:06
A: n8n-io/n8n ***@***.***>
Cc: luca-manallarte ***@***.***>; Mention ***@***.***>
Oggetto: Re: [n8n-io/n8n] Access to Excel 365 File (Issue #11842)


Hey @luca-manallarte<https://github.com/luca-manallarte>,

Are the files in your personal OneDrive or Sharepoint?

**Comment by Joffcom** [comment]
@luca-manallarte if you add them to the normal OneDrive folder and not the Sharepoint folder do they then appear? I believe the problem could be that we don't support Sharepoint at the moment only OneDrive.

**Comment by luca-manallarte** [comment]
I tryed both nodes, One Drive and Share Point. Nope.
If I add the Excel Node connected to my perosnal one drive it works. But it doesn't if connected to the business account.
Luca

________________________________
Da: Jon ***@***.***>
Inviato: martedì 3 dicembre 2024 17:14
A: n8n-io/n8n ***@***.***>
Cc: luca-manallarte ***@***.***>; Mention ***@***.***>
Oggetto: Re: [n8n-io/n8n] Access to Excel 365 File (Issue #11842)


@luca-manallarte<https://github.com/luca-manallarte> if you add them to the normal OneDrive folder and not the Sharepoint folder do they then appear? I believe the problem could be that we don't support Sharepoint at the moment only OneDrive.

**Comment by rockygiglio** [comment]
same issue for me. Using OneDrive for Business the Excel nodes won't list any files. I haven't tried to my personal account, but can do that to see if I get a different result.
