### ISSUE TITLE
Unable to use o1 with AI agent node

### ISSUE THREAD

**Issue by BrandonTN1** [n8n-io/n8n#11854]
### Bug Description

o1 does not accept the system parameter, and there is no way to remove this from the AI agent node so we can select an O1 model as the chat model for the N8N AI agent node.

### To Reproduce

1. Add an AI Agent node
2. Add Open AI as the AI model
3. Try to execute using o1 preview or mini as the model

### Expected behavior

I expect it to complete the request like it would if 4o or any other model were selected

### Operating System

n8n cloud

### n8n Version

Latest

### Node.js Version

Latest

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by jeanpaul** [comment]
Hi @BrandonTN1 -- Since the o1 models don't support system messages or tools (yet), a safer bet would be to use the Basic LLM Chain node. There's no reason to use the Agent for now.

**Comment by leonardomarcao** [comment]
> Hi [@BrandonTN1](https://github.com/BrandonTN1) -- Since the o1 models don't support system messages or tools (yet), a safer bet would be to use the Basic LLM Chain node. There's no reason to use the Agent for now.

Are you kidding me? 

How explain that tool is a shit: "There's no reason to use the Agent for now."

**Comment by jeanpaul** [comment]
Please moderate your language. You come across as hostile, and that will not earn you any points.

Please try again, because `o1` and/or `o3-mini` might be usable with agents now.
