### ISSUE TITLE
While try to send Photo as Binary via Telegram SendPhoto I get 'source.on is not a function' error

### ISSUE THREAD

**Issue by Toxblh** [n8n-io/n8n#11855]
### Bug Description

small flow 
Http request node return a file PNG, which I whould like to send via sendPhoto telegram, while the try I to send as Binary and get source.on is not a function error

Other
Node type

n8n-nodes-base.telegram

Node version

1.1 (Latest version: 1.2)

n8n version

1.68.0 (Self Hosted)

Time

23.11.2024, 03:46:19

Stack trace

NodeApiError: source.on is not a function at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Telegram/GenericFunctions.js:115:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Telegram/Telegram.node.js:1758:36) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20

### To Reproduce

![image](https://github.com/user-attachments/assets/f37fcac7-8ece-4705-b996-e2f1e4a5ba48)
Super easy
Http return on request an image in PNG
Telegram sendPhoto to send it with Binary flag "on"

### Expected behavior

Photo sent to telegram

### Operating System

docker

### n8n Version

1.68.0

### Node.js Version

-

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Toxblh,

We have created an internal ticket to look into this which we will be tracking as "GHC-480"

**Comment by Joffcom** [comment]
Hey @Toxblh 

Can you share a screenshot of what you have set in the telegram node? It could be that you are using an expression instead of the binary data field value.

**Comment by Toxblh** [comment]
![image](https://github.com/user-attachments/assets/525c1002-40fd-409a-baee-fbd6aacac132)
sure

**Comment by Toxblh** [comment]
I found 🙈 
Yes, you are right 
![image](https://github.com/user-attachments/assets/bdcce605-6e25-43ee-8f18-3f283efc373f)

reply markup been broken while manipulations

**Comment by Toxblh** [comment]
Thank you so much

**Comment by Joffcom** [comment]
@Toxblh no problem at all

**Comment by Salutelamort** [comment]
good afternoon, I have the same problem and I don't understand how to fix it, please help

<img width="1898" height="887" alt="Image" src="https://github.com/user-attachments/assets/48882de9-48f3-47d5-b756-f3707bdd6234" />
