### ISSUE TITLE
Bug on editor ui

### ISSUE THREAD

**Issue by zhiru** [n8n-io/n8n#11856]
### Bug Description

on https i have a problem on editor that i don`t know how to solve it, even changing the version

![image](https://github.com/user-attachments/assets/d5f15533-a9e7-47d5-bcfa-42d39e94d219)

### To Reproduce

1. access using https on self hosted docker

### Expected behavior

Works like using without https:

![image](https://github.com/user-attachments/assets/0df170f5-618a-4554-95f1-84be1a0090c5)

### Operating System

Almalinux 8 

### n8n Version

1.68.0

### Node.js Version

node 20

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @zhiru,

We have created an internal ticket to look into this which we will be tracking as "GHC-481"

**Comment by Joffcom** [comment]
Hey @zhiru 

I have 3 possible thoughts on this one.

1) Clear the browser cache and see if that sorts it out.

2) Check the configuration of your reverse proxy, if it works without https the issue is likely in the middle.

3) Make sure you are not using Cloudflare with caching.

**Comment by zhiru** [comment]
Tks @Joffcom

1. was the first one who did this

I'll try the others, but Cloudflare is not because I always disabled the proxy, but now I'm forcing development mode

late i came to say if works

**Comment by Joffcom** [comment]
Hey @zhiru 

Are they both pointing to the same n8n instance?

The second url hits a plesk page so it could that you have webhook_url pointing to one domain, editor_url pointing to the other and the load balancer not configured correctly.

**Comment by zhiru** [comment]
yes, both are a docker in plesk, with proxy, now both are buggy haha

x-n8n-base: &n8n-base
  env_file: ./.env  
  image: n8nio/n8n:1.68.0
  restart: always
  environment:
    DB_TYPE: postgresdb
    DB_POSTGRESDB_HOST: ${N8N_POSTGRES_HOST}
    DB_POSTGRESDB_PORT: ${N8N_POSTGRES_INTERNAL_PORT}
    DB_POSTGRESDB_DATABASE: ${N8N_POSTGRES_DATABASE}
    DB_POSTGRESDB_USER: ${N8N_POSTGRES_USER}
    DB_POSTGRESDB_PASSWORD: ${N8N_POSTGRES_PASSWORD}
    DATA_FOLDER: ${N8N_DATA_FOLDER}
    SUBDOMAIN: 'n8n'
  links:
    - n8n-postgres
    - n8n-redis
  volumes:
    - n8n:/home/node/.n8n
  networks:
    - aireset-all-containers
  # extra_hosts:
    # - "host.docker.internal:host-gateway"
  depends_on:
    n8n-redis:
      condition: service_healthy
    n8n-postgres:
      condition: service_healthy

  n8n:
    <<: *n8n-base
    hostname: $N8N_HOST_NAME
    ports:
      - $N8N_EXTERNAL_PORT:$N8N_INTERNAL_PORT
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: $N8N_MEMORY_LIMIT

  n8n-webhook:
    <<: *n8n-base
    hostname: $N8N_WEBHOOK_HOST_NAME
    command: webhook
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: $N8N_WEBHOOK_MEMORY_LIMIT

  n8n-worker:
    <<: *n8n-base
    hostname: $N8N_WORKER_HOST_NAME
    command: worker --concurrency=5
    #command: worker
    depends_on:
      - n8n
      - n8n-webhook
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: $N8N_WORKER_MEMORY_LIMIT
          
          
 .env:

N8N_HIRING_BANNER_ENABLED=false
N8N_REINSTALL_MISSING_PACKAGES=true

N8N_CONTAINER_NAME="n8n.${DOMAIN}"
N8N_HOST_NAME="n8n.${DOMAIN}"
N8N_WEBHOOK_HOST_NAME="webhookn8n.${DOMAIN}"
N8N_WORKER_HOST_NAME="workn8n.${DOMAIN}"

N8N_MEMORY_LIMIT=2048M
N8N_WEBHOOK_MEMORY_LIMIT=2048M
N8N_WORKER_MEMORY_LIMIT=2048M

N8N_DEFAULT_LOCALE="en"

N8N_DATA_FOLDER="./data/n8n/data"

N8N_HOST="n8n.${DOMAIN}"

N8N_PROTOCOL="http" # changed because of bug
N8N_EDITOR_BASE_URL="http://${DOMAIN}" # changed because of bug
WEBHOOK_URL="http://webhookn8n.${DOMAIN}" # changed because of bug

N8N_SECURE_COOKIE=false
N8N_BASIC_AUTH_ACTIVE=true

GENERIC_TIMEZONE=${TZ}

# The email address to use for the SSL certificate creation
SSL_EMAIL=${EMAIL}

N8N_EMAIL_MODE=smtp
N8N_SMTP_SENDER=${MAILER_SENDER_EMAIL}
N8N_SMTP_HOST=${SMTP_ADDRESS}
N8N_SMTP_PORT=${SMTP_PORT}
N8N_SMTP_USER=${SMTP_USERNAME}
N8N_SMTP_PASS=${SMTP_PASSWORD}
N8N_SMTP_SSL=true

EXECUTIONS_MODE=queue

EXECUTIONS_DATA_SAVE_ON_ERROR=all
EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
EXECUTIONS_DATA_SAVE_ON_PROGRESS=all
EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=all
EXECUTIONS_TIMEOUT=160
EXECUTIONS_TIMEOUT_MAX=300

N8N_DEFAULT_BINARY_DATA_MODE=filesystem

EXECUTIONS_DATA_PRUNE=true
EXECUTIONS_DATA_MAX_AGE=336
EXECUTIONS_DATA_PRUNE_MAX_COUNT=5000

N8N_CONCURRENCY_PRODUCTION_LIMIT=10

Apache/LiteSpeed Proxy:

SSLProxyEngine On
ProxyPreserveHost On
ProxyRequests Off
ProxyTimeout 36000
AllowEncodedSlashes NoDecode
HttpProtocolOptions Unsafe

SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
SetEnvIfNoCase ^Upgrade$ "(.+)" HTTP_UPGRADE=$1
SetEnvIfNoCase ^Connection$ "(.+)" HTTP_CONNECTION=$1
SetEnvIfNoCase ^Host$ "(.+)" HTTP_HOST=$1
SetEnvIfNoCase ^X-Forwarded-Proto$ "(.+)" HTTP_X_FORWARDED_PROTO=$1
SetEnvIfNoCase ^X-Forwarded-Ssl$ "(.+)" HTTP_X_FORWARDED_SSL=$1

RequestHeader set X-Real-IP %{REMOTE_ADDR}s
RequestHeader set X-Forwarded-For %{REMOTE_ADDR}s
RequestHeader set X-Forwarded-Proto "https"

ProxyPass "/" "http://127.0.0.1:45100/"
ProxyPassReverse "/" "http://127.0.0.1:45100/"

ProxyPass "/webhook" "http://127.0.0.1:45100/"
ProxyPassReverse "/webhook" "http://127.0.0.1:45100/"

<Proxy *>
	Require all granted
</Proxy>

RewriteEngine On

RewriteCond %{HTTP:Upgrade} ^WebSocket$ [NC]
RewriteCond %{HTTP:Connection} ^Upgrade$ [NC]
RewriteRule .* ws://127.0.0.1:45100%{REQUEST_URI} [P]

Header always set Connection "Upgrade"
Header always set Upgrade "websocket"

**Comment by zhiru** [comment]
looking for the erro i saw that .ndv-wrapper css is after .el-dialog

 .ndv-wrapper has width: 100% and when is before .el-dialog then works, but i dont why is on diferente positions on file when in https

**Comment by Joffcom** [comment]
Hey @zhiru,

We have taken a look and this looks to be an issue with your configuration. Can you first start with a smaller install using just the one n8n instance then once that is working you can look at scaling out.

Looking at your config options you have some options set that don't exist anymore which makes me wonder if you used something like ChatGPT to get up and running which will result in you having a bad time.

To start with I would make sure you unset `N8N_EDITOR_BASE_URL` or set it to the url you plan to use for the main n8n instance as at the moment you are trying to load from it but it isn't running n8n which is likely causing things to go wrong. If this doesn't solve it can you try following one of our official install guides and we can go from there.

For now though I am going to mark this as closed.
