### ISSUE TITLE
OpenAI node bug generate an image

### ISSUE THREAD

**Issue by cedric-dev01** [n8n-io/n8n#11866]
### Bug Description

Hi,
There's a bug with the expression mode for the prompt, see image.

### To Reproduce

![Capture d’écran 2024-11-25 100035](https://github.com/user-attachments/assets/4ba5eea9-c5e6-415a-a2f3-9e74912cd453)

### Expected behavior

Fix node n8n

### Operating System

Windows11

### n8n Version

1.68.0

### Node.js Version

v20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by OlegIvaniv** [comment]
Hi @cedric-dev01,

thanks for reporting this! This issue has already been fixed in #11825 and will go out with the next release

**Comment by OlegIvaniv** [comment]
@cedric-dev01 Let's please keep the conversation in a single thread — https://github.com/n8n-io/n8n/pull/11825
