### ISSUE TITLE
agent  memory: human message that triggered workflow appended too late (at end of agent run)

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11862]
### Bug Description

When a human chat message comes in it is saved at the very end of an agent run. This is wrong, it should of course store any incoming message asap to enforce correct ordering. When we now insert a message from another workflow tool, these messages are inserted BEFORE the message of the human that triggered it, which is not correct....

### To Reproduce

1. run the workflow: 
[test_agent_message_ordering.json](https://github.com/user-attachments/files/17893590/test_agent_message_ordering.json)

2. observe in latest run that message order is wrong in memory

### Expected behavior

The agent abstraction to save the human message at the very first, before doing anything else (and save the ai message at the very last of course ;)

### Operating System

docker

### n8n Version

1.68.0

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz 

Is this a bug or a change in functionality that you think we should make?

**Comment by Morriz** [comment]
Ok, this is core langchain stuff, so I created an issue there: https://github.com/langchain-ai/langchainjs/issues/7255
