### ISSUE TITLE
OpenAI nodes, not connecting Memory and Tools to previous nodes

### ISSUE THREAD

**Issue by felipefcastro-okay** [n8n-io/n8n#11875]
### Bug Description

it was working before the n8n update.

![image](https://github.com/user-attachments/assets/edffa4fa-f63f-491a-aaec-90a73de010ac)
![image](https://github.com/user-attachments/assets/fc2a7633-8e3d-43e2-ac5d-36008d94a88f)

connect "Redis Chat Memory" to "Edit Fields"

### To Reproduce

{
  "meta": {
    "instanceId": "c2d78417a1e6a36f73022282d488d3bb7900d4edd19925c7feb0d3fa809b41e7"
  },
  "nodes": [
    {
      "parameters": {
        "options": {}
      },
      "id": "f515d790-6039-4ea4-8c46-b66cc2d2ac90",
      "name": "When chat message received",
      "type": "@n8n/n8n-nodes-langchain.chatTrigger",
      "typeVersion": 1.1,
      "position": [
        400,
        600
      ],
      "webhookId": "53187daf-0622-4369-97d1-267b6aceda62"
    },
    {
      "parameters": {
        "sessionIdType": "customKey",
        "sessionKey": "={{ $node[\"Edit Fields\"].json[\"idd\"] }}",
        "sessionTTL": 10000
      },
      "id": "48a83126-0dfd-4191-b0b8-d2008076dd80",
      "name": "Redis Chat Memory",
      "type": "@n8n/n8n-nodes-langchain.memoryRedisChat",
      "typeVersion": 1.4,
      "position": [
        1260,
        860
      ],
      "credentials": {
        "redis": {
          "id": "0sPXVMjMo4h9Z9mI",
          "name": "Redis account"
        }
      }
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "f5a49b6d-86fe-44cd-81a8-0fd474128f97",
              "name": "idd",
              "value": "asdas",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "1f90c71d-077a-421c-9e42-4cf3df01ea22",
      "name": "Edit Fields",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        620,
        600
      ]
    },
    {
      "parameters": {
        "resource": "assistant",
        "assistantId": {
          "__rl": true,
          "value": "asst_FN9jnsBgO7eWk1plqTQoh8Mj",
          "mode": "list",
          "cachedResultName": "Vendedor Inventorify - INSTAGRAM"
        },
        "prompt": "define",
        "text": "={{ $('When chat message received').item.json.chatInput }}",
        "options": {}
      },
      "id": "816425dd-f3a8-44fd-80b2-ea685f723464",
      "name": "OpenAI",
      "type": "@n8n/n8n-nodes-langchain.openAi",
      "typeVersion": 1.7,
      "position": [
        1140,
        600
      ],
      "credentials": {
        "openAiApi": {
          "id": "z2MUTQL2Caq8GqHz",
          "name": "OpenAi ATENDIMENTO VENDAS"
        }
      }
    }
  ],
  "connections": {
    "When chat message received": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Redis Chat Memory": {
      "ai_memory": [
        [
          {
            "node": "OpenAI",
            "type": "ai_memory",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields": {
      "main": [
        [
          {
            "node": "OpenAI",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}

### Expected behavior

It should get the information from previous nodes, as happend before.

### Operating System

Ubuntu Linux

### n8n Version

1.68.0

### Node.js Version

using hub.docker.com/r/n8nio/n8n

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @felipefcastro-okay,

We have created an internal ticket to look into this which we will be tracking as "GHC-492"

**Comment by OlegIvaniv** [comment]
@felipefcastro-okay The issue seems to be with the expression in the `Redis Chat Memory` node. Right now you're accessing the property via an outaded `$node` getter which fails to resolve correctly when using sub-nodes:
`{{ $node["Edit Fields"].json["idd"] }}`, please try it using the `$($NODE}` expression like this  `{{ $('Edit Fields').item.json.idd }}` that should fix the issue:
![CleanShot 2024-11-25 at 16 00 37](https://github.com/user-attachments/assets/27f321ca-7ac9-4d92-9c35-28ae5c43dcd9)

```json
{
  "meta": {
    "instanceId": "178ef8a5109fc76c716d40bcadb720c455319f7b7a3fd5a39e4f336a091f524a"
  },
  "nodes": [
    {
      "parameters": {
        "options": {}
      },
      "id": "f92440be-5424-46b9-aa12-3a9d19051da7",
      "name": "When chat message received",
      "type": "@n8n/n8n-nodes-langchain.chatTrigger",
      "typeVersion": 1.1,
      "position": [
        1280,
        560
      ],
      "webhookId": "53187daf-0622-4369-97d1-267b6aceda62"
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "f5a49b6d-86fe-44cd-81a8-0fd474128f97",
              "name": "idd",
              "value": "asdas",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "e8522a61-13f9-416b-b400-ed57d05656be",
      "name": "Edit Fields",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        1500,
        560
      ]
    },
    {
      "parameters": {
        "resource": "assistant",
        "assistantId": {
          "__rl": true,
          "value": "asst_pmdUnClm5gru5fOwtrhW8bnV",
          "mode": "list",
          "cachedResultName": "JP's test assistant"
        },
        "prompt": "define",
        "text": "={{ $('When chat message received').item.json.chatInput }}",
        "options": {}
      },
      "id": "776a4586-b69d-4c77-a618-b4a4da0160b5",
      "name": "OpenAI",
      "type": "@n8n/n8n-nodes-langchain.openAi",
      "typeVersion": 1.7,
      "position": [
        1760,
        560
      ],
      "credentials": {
        "openAiApi": {
          "id": "wJtZwsVKW5v6R2Iy",
          "name": "OpenAi account"
        }
      }
    },
    {
      "parameters": {
        "sessionIdType": "customKey",
        "sessionKey": "={{ $('Edit Fields').item.json.idd }}"
      },
      "id": "81de66ec-8ff5-4ff7-bfc6-d52060479430",
      "name": "Window Buffer Memory",
      "type": "@n8n/n8n-nodes-langchain.memoryBufferWindow",
      "typeVersion": 1.3,
      "position": [
        1980,
        740
      ]
    }
  ],
  "connections": {
    "When chat message received": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields": {
      "main": [
        [
          {
            "node": "OpenAI",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Window Buffer Memory": {
      "ai_memory": [
        [
          {
            "node": "OpenAI",
            "type": "ai_memory",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}

```

**Comment by felipefcastro-okay** [comment]
Thank you a lot! It worked!
I was getting the path from the "Copy Parameter Path" thought that was the safest way.
