### ISSUE TITLE
N8N (cloud) UI freezes when opening HTTP or Code node

### ISSUE THREAD

**Issue by weareturnone** [n8n-io/n8n#11878]
### Bug Description

Whenever I open the HTTP node or a code node in a workflow that uses the DeepGram API, the UI freezes and becomes unresponsive. Then the browser times out the session and need to reload the page. This happens consistently and it does not matter which canvas I use.

### To Reproduce

Create a HTTP request node with a POST request to the DeepGram API get a response...

### Expected behavior

To be able to open the Node in the UI and interact with the UI

### Operating System

n8n Cloud

### n8n Version

1.68.0

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @weareturnone,

We have created an internal ticket to look into this which we will be tracking as "GHC-494"

**Comment by netroy** [comment]
Is this with data on the nodes, or is this happening for you even before you execute the workflow?

**Comment by weareturnone** [comment]
> Is this with data on the nodes, or is this happening for you even before you execute the workflow? @netroy 

This only happens after a execution/ the HTTP and/ or code node have executed. Tried it in Chrome and Arc and Safari, also after restarting and updating the hosted n8n cloud instance as well as my mac.

**Comment by netroy** [comment]
Can you please check how much data the http request returns? This sounds like an issue of too much data being loaded into the UI.

Another thing you could try is to open the Node details view, switch to `Table` or `JSON` view, instead of the `Schema` view, and then try executing the workflow.
The schema view is currently not optimized for performance, but that will be fixed in the next release.

**Comment by netroy** [comment]
Would it be possible for you to create and share a minimal workflow with which you can consistently reproduce this issue? that would help significantly in narrowing down what the issue might be.

**Comment by weareturnone** [comment]
unfortunately the issue also persists on table and json views. I do not
have the issue when self hosting n8n on a digital ocean or hetzner vps
though.

**Comment by janober** [comment]
Fix got released with [`n8n@1.73.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.73.0)

**Comment by netroy** [comment]
@weareturnone Closing this as completed. But please let us know if the updates did not address the performance issue for you 🙏🏽
