### ISSUE TITLE
Error when trying to pass a expression to OpenAI Image creation node

### ISSUE THREAD

**Issue by AurioNeto** [n8n-io/n8n#11881]
### Bug Description

![image](https://github.com/user-attachments/assets/99d29453-da7c-4f55-af2b-930ad68972d9)

![image](https://github.com/user-attachments/assets/03058d34-8565-4fe0-9cf8-e9fdbd91406f)

After updating to v.1.68, I'm getting the error 'Text from 'Previous Node' is required".

### To Reproduce

1. Add a trigger
2. Add a 'Edit Fields" node
3. Set a string field with the intended prompt
4. Add a "OpenAI Generate Image" node
5. Set the prompt as the one defined on 'Edit Fields' (Actually, any expression will result on the same error, even if you just pass a text to it)
6. Run

### Expected behavior

Receive the prompt from the previous nodes and create the imagem without an error.

### Operating System

Windows 11

### n8n Version

1.68

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @AurioNeto,

We have created an internal ticket to look into this which we will be tracking as "GHC-497"

**Comment by Joffcom** [comment]
Hey @AurioNeto,

This has been fixed in https://github.com/n8n-io/n8n/pull/11825 and will be available in the next release, As this is fixed I am going to mark this closed for now.
