### ISSUE TITLE
OpenAI Generate Image doesn’t work with expression prompt

### ISSUE THREAD

**Issue by paulmeller** [n8n-io/n8n#11885]
### Bug Description

Generate Image doesn’t work with expression prompt. Works fine with fixed prompt.

### To Reproduce

Change prompt from fixed to expression

### Expected behavior

Node generates image

### Operating System

Debian 12

### n8n Version

1.68.0

### Node.js Version

18

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @paulmeller,

We have created an internal ticket to look into this which we will be tracking as "GHC-500"
