### ISSUE TITLE
Error when sending HTTP GET request

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#11893]
### Bug Description

I am a beginner with n8n. A few days ago, I registered for an official n8n cloud account. I encountered a problem when using the "HTTP Request Node" to send a GET request. This request is directed to a specific port on my test host, and after executing the node, I get the following error message.

> message:connect ECONNREFUSED 127.0.0.1:11436
name:Error
stack:Error: connect ECONNREFUSED 127.0.0.1:11436\n    at Function.AxiosError.from (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:620:25)\n    at RedirectableRequest.emit (node:events:531:35)\n    at RedirectableRequest.emit (node:domain:488:12)\n    at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:49:24)\n    at ClientRequest.emit (node:events:519:28)\n    at ClientRequest.emit (node:domain:488:12)\n    at emitErrorEvent (node:_http_client:101:11)\n    at Socket.socketErrorListener (node:_http_client:504:5)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at requestFn (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:617:33)\n    at proxyRequestToAxios (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:620:26)\n    at Object.request (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:2087:50)
code:ECONNREFUSED

Additionally, I also deployed the n8n service on a host at render.com and encountered the same issue.

On the render.com host, I also deployed services like Flowise and Langflow, and the requests mentioned above work correctly.

To better describe the issue, I have recorded a GIF demonstration as follows:
![BUG](https://github.com/user-attachments/assets/575e4ec3-287c-4b9c-a404-b0f5bc42d2ff)

### To Reproduce

mport the following configuration code and click Test Step to test.
```
{
  "nodes": [
    {
      "parameters": {
        "url": "http://free.frpee.com:11436/playTextAsVoice",
        "sendQuery": true,
        "queryParameters": {
          "parameters": [
            {
              "name": "Text",
              "value": "hello world"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        -20,
        -100
      ],
      "id": "209fd02c-0a20-4fbc-bf96-1b641a2168ea",
      "name": "playTextAsVoice1",
      "onError": "continueRegularOutput"
    },
    {
      "parameters": {},
      "type": "n8n-nodes-base.executeWorkflowTrigger",
      "typeVersion": 1,
      "position": [
        -240,
        -100
      ],
      "id": "6180f098-c730-4a5a-b2e1-2099d4e2778f",
      "name": "Execute Workflow Trigger"
    }
  ],
  "connections": {
    "Execute Workflow Trigger": {
      "main": [
        [
          {
            "node": "playTextAsVoice1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

### Expected behavior

I believe n8n should support sending GET requests. What settings might be required? I couldn't find any relevant information in the help documentation.

### Operating System

n8n cloud

### n8n Version

1.68.0

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-502"

**Comment by Joffcom** [comment]
Hey @xhzkp,

I am going to mark this as closed as this isn't a bug with n8n.

The domain you are trying to use `free.frpee.com` points to `127.0.0.1` which is the local loopback address, The problem here is `127.0.0.1` is always the address of the machine you are using so on your laptop or desktop it will be local only to that machine and on my laptop it is local to my machine.

When you use it in n8n cloud or render it will be local to those services so it will likely never connect back to your machine if that is where you are running your service.

To allow n8n or anything else to connect you would need to either run n8n directly on your machine and configure the docker networking to allow the connection or expose the service from your machine to the outside world using a reverse proxy or a tunnel (cloudflared / ngrok).

**Comment by xhzkp** [comment]
> Hey @xhzkp,
> 
> I am going to mark this as closed as this isn't a bug with n8n.
> 
> The domain you are trying to use `free.frpee.com` points to `127.0.0.1` which is the local loopback address, The problem here is `127.0.0.1` is always the address of the machine you are using so on your laptop or desktop it will be local only to that machine and on my laptop it is local to my machine.
> 
> When you use it in n8n cloud or render it will be local to those services so it will likely never connect back to your machine if that is where you are running your service.
> 
> To allow n8n or anything else to connect you would need to either run n8n directly on your machine and configure the docker networking to allow the connection or expose the service from your machine to the outside world using a reverse proxy or a tunnel (cloudflared / ngrok).

I am using a proxy, and my issue is the same as the one mentioned in the post below. Is there any solution for this?
https://community.n8n.io/t/http-request-via-proxy-connect-econnrefused-127-0-0-1-80/8469

**Comment by Joffcom** [comment]
Hey @xhzkp 

As long as you are not trying to connect to something using 127.0.0.1 you should be ok.

The url you shared is not a proxy but hopefully you have now set up a reverse proxy the firewall routes, have you verified that the port is open and the url you are using points to the correct ip address?

**Comment by xhzkp** [comment]
> Hey @xhzkp
> 
> As long as you are not trying to connect to something using 127.0.0.1 you should be ok.
> 
> The url you shared is not a proxy but hopefully you have now set up a reverse proxy the firewall routes, have you verified that the port is open and the url you are using points to the correct ip address?

I don't quite understand what you mean.
I deployed n8n on another cloud storage platform, and the HTTP request mentioned above was successfully executed. Below is a screenshot. Therefore, I believe this is a configuration issue, but I’m not sure which parameter should be configured.
![ok](https://github.com/user-attachments/assets/23af3dc2-6309-4381-a4ca-b0262917f79c)
