### ISSUE TITLE
Let's make the node work predictable

### ISSUE THREAD

**Issue by dima-takoy** [n8n-io/n8n#1190]
**Describe the bug**
Many nodes work completely unpredictably if several values come into them, for example:
1. Airtable (list)
2. HTTP

This leads to subtle mistakes and the false impression that everything is going according to plan.

I regularly encounter a situation where workflow works correctly at test runs, but then behaves in the real world in a completely different way. It turned out that for two weeks my workflow worked like this.

1. Airtable started returning 3 entries instead of one. I found out about the error a week later, and the workflow worked correctly only for the 1st record of 3. I only found out about the error because the sorting of entries in Airtable changed.
2. Next, in one of the branches of workflow I "pull" webhook another workflow. If the HTTP node had multiple values, the following workflow was successful, but it did nothing because no data came into it.

Earlier I also faced a similar problem and described it here - https://github.com/n8n-io/n8n/issues/881.

The main problem is that due to the successful execution of workflow you may not even guess that nothing works. If the source of your data suddenly starts sending multiple entries, then for at least one entry the workflow will work and will successfully complete.

I understand that fixing such an error is a break change, but let's at least try to make it clear that for the correct functioning of the node you need to use splitInBatches.

**To Reproduce**
1. Just use the nodes. You will definitely meet such an error in an unpredictable place.

**Expected behavior**
Just help me not to make a mistake.

**Environment (please complete the following information):**
- n8n 0.93.0

**Comment by mecurc** [comment]
The existing services do not have such problems, no matter how much data comes in the collected "scenarios" they work equally and predictably.

My workflow was broken and I didn't even know about it. Today I have spent 8 hours searching and fixing the problem. In addition, I failed my subscribers and did not provide them with the promised content on the right dates.

I am very upset, but anyway, thank you for the tremendous work you are doing. I hope my pain will help to avoid similar mistakes for other users.

**Comment by janober** [comment]
Yes totally agree! Is actually something that is already on our roadmap. That all node operations always execute once for every item. We have to be however also very careful as many workflows would break if we would suddenly change the behavior of those operations that currently behave differently.
So is something which requires some proper planning and thoughts.

**Comment by Joffcom** [comment]
Hey @dima-takoy,

Just an update on this one we are still working on this and it will be fixed, For now though I am going to close this issue as we are tracking it internally :+1:
