### ISSUE TITLE
feedback overlay can't be closed and hides a lot of the canvas

### ISSUE THREAD

**Issue by Morriz** [n8n-io/n8n#11906]
### Bug Description

A new update is drawing some rating overlay on the canvas in execution mode:
<img width="381" alt="Screenshot 2024-11-26 at 7 15 16 PM" src="https://github.com/user-attachments/assets/9851545e-089c-4b6f-809a-819d6dd4aa2e">

How can we close it? The UX is clearly at a miss here. I advise scrum and giving demos to stakeholders ;p)

### To Reproduce

go to the new canvas in execution mode

### Expected behavior

overlay elements to be able to be closed

### Operating System

docker

### n8n Version

1.69.0

### Node.js Version

docker

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Morriz,

We have created an internal ticket to look into this which we will be tracking as "GHC-504"

**Comment by Morriz** [comment]
If you think you can just put a 248x210px div over the canvas without the option to click it away, then I am seriously doubting your stakeholders business perspective. @janober please look into this as it becomes inevitable to have a good scrum process imo...this shouldn't happen and we shouldn't be brushed off like this...

**Comment by Joffcom** [comment]
Hey @Morriz 

As mentioned this is something that we already have on our list of things to change in the future so it has not been dismissed.

This issue however has been closed as it is not really a bug report and this is instead either feedback or a feature request which is better suited to our support forum and this is something that is already in progress internally.

Every GitHub issue that gets opened is posted into an internal Slack channel for the entire company to see and an engineering ticket is created in Linear and passed to the team responsible for the area it relates to, while you feel this has been "brushed off" the public status of closed on GitHub doesn't mean we are not fully aware or that we won't do anything there is a lot that happens behind the scenes.
