### ISSUE TITLE
postgres table list not searchable

### ISSUE THREAD

**Issue by Skarema** [n8n-io/n8n#11916]
### Bug Description

The list of tables is not searchable and it's not sorted alphabetically. Please implement one or the other. With a list of tables like my screenshot shows, it's nearly impossible to find the table.

![CleanShot 2024-11-27 at 11 23 22@2x](https://github.com/user-attachments/assets/1e747f0e-7752-43aa-9bf2-65239a73efe4)

### To Reproduce

1. use postgres node
2. try to select a table

### Expected behavior

table field searchable or at least sorted alphabetically

### Operating System

-

### n8n Version

1.65.2

### Node.js Version

-

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Skarema,

We have created an internal ticket to look into this which we will be tracking as "GHC-508"

**Comment by Joffcom** [comment]
Hey @Skarema,

While this is annoying it doesn't seem to be a bug, Can you raise a feature request for this on our [community support forum](https://community.n8n.io/c/feature-requests/5) as we only use GitHub for tracking bugs.

For now I will be marking this as closed, Let me know if you have any questions.
