### ISSUE TITLE
HTTP Request node & ISO-8859-15 charset

### ISSUE THREAD

**Issue by scebll** [n8n-io/n8n#11928]
### Bug Description

Greetings!
Using the HTTP Request node to make a request to an endpoint that returns something like:

`Content-Type: application/json;charset=ISO-8859-15`

is raising the following error:

`TypeError: Unknown encoding: iso-8859-15 at Buffer.toString (node:buffer:859:11) at Object.binaryToString (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:583:19) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:547:42) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20`

### To Reproduce

1. Go to any workflow.
2. Select the `HTTP Request` node.
3. Use any URI that returns a response with `ISO-8859-15` encoding.
4. Error appears

### Expected behavior

No error at all.

ISO-8559-15 is a valid charset: https://en.wikipedia.org/wiki/ISO/IEC_8859-15

### Operating System

Linux, Docker n8n image

### n8n Version

1.67.1

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by netroy** [comment]
This should be out in tomorrow's minor release: `1.71.0`.
