### ISSUE TITLE
Critical Data Rollback Incident

### ISSUE THREAD

**Issue by MaximeGratens** [n8n-io/n8n#11932]
### Bug Description

Production environment has experienced an unexpected data rollback affecting all workflow data, resulting in approximately 2 weeks of data loss.
Impact Assessment

All production data and workflows have been rolled back to a state from 2 weeks ago
Current data state is inconsistent with recent operations

Our instance is self hosted on ubuntu and runned with docker.

### To Reproduce

..

### Expected behavior

.

### Operating System

Ubuntu linux 20

### n8n Version

 1.66.0

### Node.js Version

18

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MaximeGratens,

We have created an internal ticket to look into this which we will be tracking as "GHC-512"

**Comment by Joffcom** [comment]
Hey @MaximeGratens 

We use GitHub for tracking bugs, this sounds more like a support request unless you have any logs or a way to reproduce the issue.

Have you opened a topic on the support forum for this yet as it would be a great place to start.
