### ISSUE TITLE
Lines between nodes disappear when hovering over sticky note box

### ISSUE THREAD

**Issue by Alexandero89** [n8n-io/n8n#11938]
### Bug Description

When you use a sticky node as a box for a group of nodes the lines of the nodes disappear when you hover of the sticky box.
This happens since update to version 1.70

https://github.com/user-attachments/assets/700efea6-42fe-4595-ab84-aa697796bb42

### To Reproduce

1. Add sticky node
2. add nodes
3. connect nodes
4. put nodes inside of sticky box
5. hover over any area the sticky node covers
6. all lines disappear

### Expected behavior

the lines should still be visible and the nodes/lines should be clickable.
it was like this in all versions before

### Operating System

docker compose

### n8n Version

1.70

### Node.js Version

...

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Alexandero89,

We have created an internal ticket to look into this which we will be tracking as "GHC-516"

**Comment by Alexandero89** [comment]
Fixed with https://github.com/n8n-io/n8n/pull/11950
