### ISSUE TITLE
Page drag do not work

### ISSUE THREAD

**Issue by hekiri** [n8n-io/n8n#11942]
### Bug Description

can not drag page on web UI using (Ctl+Left Click) in new canvas

### To Reproduce

hold down control key
drag the canvas using mouse by holding left button down

### Expected behavior

user should be able to drag the canvas using mouse ( ctl+left_button_down )

### Operating System

Windows

### n8n Version

1.68.0

### Node.js Version

0.0.0.0 (no idea, not shown in web ui)

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @hekiri,

We have created an internal ticket to look into this which we will be tracking as "GHC-519"

**Comment by tomi** [comment]
Duplicate of #11755
