### ISSUE TITLE
Can't find integrations with DataStax Astra DB and/or Apache Cassandra® vector databases

### ISSUE THREAD

**Issue by msmygit** [n8n-io/n8n#11956]
### Bug Description

Can't find integrations with [DataStax Astra DB®](https://docs.datastax.com/en/astra-db-serverless/get-started/quickstart.html) and/or [Apache Cassandra™](https://cassandra.apache.org) vector databases. Please implement those components/nodes!

### To Reproduce

n/a

### Expected behavior

Easily use DataStax Astra DB® & Apache Cassandra™ vector database components easily.

### Operating System

everywhere

### n8n Version

latest

### Node.js Version

latest

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @msmygit,

We have created an internal ticket to look into this which we will be tracking as "GHC-522"

**Comment by Joffcom** [comment]
Hey @msmygit,

We use GitHub to track bugs as there is not a bug here I will need to mark this as closed. If you would like to request new nodes or features the best bet is to create a post on the community support forum and we can see if it is something the community are generally after.
