### ISSUE TITLE
OpenAI Immage Generation Node - Expression not working

### ISSUE THREAD

**Issue by MrFr33man123** [n8n-io/n8n#11954]
### Bug Description

If you switch from fixed to expression it will error and tell you: "Parameter: Text from previous node" is required
A fixed query works.
{{ $json.text }} is previewing the trigger input string correctly but the node has the exclamation mark still and the flow can not be testet.
![image](https://github.com/user-attachments/assets/3d85c7cc-6f00-440a-9b27-ca128e47ea5b)
![image](https://github.com/user-attachments/assets/6f987bf0-197a-40e1-a655-31131fbbc762)
![image](https://github.com/user-attachments/assets/60777213-6b68-40d4-932c-67b229d34ea1)

### To Reproduce

Click + on the right side
Advanced AI => OpenAI => Generate an Image
Settings as in the screenshot: 
Resource => Image
Operation => Generate Image
Modell => Dall-E 3
Promt => {{ $json.text }}

### Expected behavior

No Error when creating the node with these settings

### Operating System

platform: docker (self-hosted) debian 12

### n8n Version

1.69.2

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MrFr33man123,

We have created an internal ticket to look into this which we will be tracking as "GHC-521"

**Comment by Joffcom** [comment]
Hey @MrFr33man123,

This was fixed in `1.70.0` in this PR: https://github.com/n8n-io/n8n/pull/11825 can you try upgrading and see if you have the same issue? If you do let me know and we can re-open this.
