### ISSUE TITLE
Webhooks failing after updating to ver 1.70.0

### ISSUE THREAD

**Issue by Toolfolks** [n8n-io/n8n#11962]
### Bug Description

{
  "errorMessage": "Cannot read properties of undefined (reading 'getNode')",
  "errorDetails": {},
  "n8nDetails": {
    "n8nVersion": "1.70.0 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "TypeError: Cannot read properties of undefined (reading 'getNode')",
      "    at WebhookContext.webhook (C:\\Users\\sales\\AppData\\Roaming\\npm\\node_modules\\n8n-nodes-base\\nodes\\Webhook\\Webhook.node.ts:182:64)",
      "    at Workflow.runWebhook (C:\\Users\\sales\\AppData\\Roaming\\npm\\node_modules\\n8n\\node_modules\\n8n-workflow\\src\\Workflow.ts:1265:29)",
      "    at Object.executeWebhook (C:\\Users\\sales\\AppData\\Roaming\\npm\\node_modules\\n8n\\src\\webhooks\\webhook-helpers.ts:258:39)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at C:\\Users\\sales\\AppData\\Roaming\\npm\\node_modules\\n8n\\src\\webhooks\\test-webhooks.ts:117:25"
    ]
  }
}

### To Reproduce

I have a webhook trigger - mysql - response to webhook 

### Expected behavior

Passes a parameter to mysql and returns the result.

### Operating System

win 10

### n8n Version

1.70.0

### Node.js Version

10.8.2

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Toolfolks,

We have created an internal ticket to look into this which we will be tracking as "GHC-526"

**Comment by netroy** [comment]
Do you have any community nodes installed?

**Comment by Toolfolks** [comment]
No

**Comment by Toolfolks** [comment]
FYI I have downgraded to 1.68.0 ( where it was working ) It now fails.

**Comment by netroy** [comment]
Can you check if there are any files in the `.n8n/nodes` folder?
On Windows I'm guessing it should be `C:\Users\sales\.n8n\nodes`

**Comment by Toolfolks** [comment]
The only file I have  ins C:\sales\.n8n\node_modules\.pakacge-lock.json

There is no nodes folder

**Comment by netroy** [comment]
If this is a standard installation, please let us know, and we can open this ticket again.
