### ISSUE TITLE
The "+" key on the numeric keypad zoom out the canvas.  

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#11964]
### Bug Description

Pressing the "+" key on the numeric keypad shrinks the canvas. Has anyone noticed this? This is consistent with the behavior of pressing the "-" key, but I think this is incorrect.

### To Reproduce

press + key

### Expected behavior

zoom in

### Operating System

n8n cloud

### n8n Version

1.70.0

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-528"

**Comment by moh0009** [comment]
facing the the same issue

**Comment by Joffcom** [comment]
This will be fixed in the next release which should be out later today.

**Comment by Joffcom** [comment]
This has been fixed as part of `1.71.0` which has just been released.
