### ISSUE TITLE
The "Allowed File Mime Types" setting in the chat node is not working

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#11960]
### Bug Description

The "Allowed File Mime Types" setting in the chat node is not working,
The GIF demonstration below explains everything. This feature is also ineffective on mobile devices..
When using the previous version of n8n, I confirmed that this feature was working correctly, but it is no longer functional in the latest version.
![BUG2](https://github.com/user-attachments/assets/f147f4f6-96cb-4d2d-a6ef-bbca4773a122)

### To Reproduce

The GIF demonstration above explains everything.

### Expected behavior

The GIF demonstration above explains everything.

### Operating System

n8n cloud

### n8n Version

1.70.0

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-524"

**Comment by OlegIvaniv** [comment]
Thanks for that, @xhzkp! This will be fixed as part of other chat improvement fixes we're working on: #11924

**Comment by xhzkp** [comment]
> Thanks for that, @xhzkp! This will be fixed as part of other chat improvement fixes we're working on: #11924

Another question: Is it possible to disable the pop-up confirmation when clicking the reset button? I don't think it's necessary here. Details are as follows:
https://community.n8n.io/t/feature-suggestion-remove-the-confirmation-dialog-when-clicking-the-reset-button/63367

**Comment by Joffcom** [comment]
Moving this to closed as the issue was fixed in this weeks `1.71.0` release.
