### ISSUE TITLE
OpenAI Node can't use json Expression anymore

### ISSUE THREAD

**Issue by parlt** [n8n-io/n8n#11972]
### Bug Description

OpenAI Node can't use json Expression anymore - error

### To Reproduce

create a set/edit node
add a field with name prompt
add the value test
add a OpenAI Image gen Node
set Dale E 2 or 3
use as promt in expression
use as value {{$json.prompt}}

### Expected behavior

The value "test" from the previous node is used in the OpenAI Node

### Operating System

Ubunutu

### n8n Version

1.69.2

### Node.js Version

-

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @parlt,

We have created an internal ticket to look into this which we will be tracking as "GHC-531"

**Comment by OlegIvaniv** [comment]
@parlt This should be fixed in 1.70, can you please try updating? Thanks!

**Comment by parlt** [comment]
is the latest docker image with 1.70?

**Comment by parlt** [comment]
![image](https://github.com/user-attachments/assets/6f40b493-7ea6-4398-90e2-5d877cb9e009)

in 1.70 the OpenAi Node is marked as "Not Working"

**Comment by OlegIvaniv** [comment]
> is the latest docker image with 1.70?

We just released 1.70.1, so that would be the latest.



> ![image](https://private-user-images.githubusercontent.com/280411/391078282-6f40b493-7ea6-4398-90e2-5d877cb9e009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODYwOTYsIm5iZiI6MTczMjg4NTc5NiwicGF0aCI6Ii8yODA0MTEvMzkxMDc4MjgyLTZmNDBiNDkzLTdlYTYtNDM5OC05MGUyLTVkODc3Y2I5ZTAwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQxMzA5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjllNDBjYjQ5OTQzNzQwN2FhYmU5N2MyMWY4OTQyZmRkNmJmODc0YWIxN2E5YzAxMDc4YjA3ZTc1OTI0YThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fgQ-KP8bzVgNaRqMIfrg82g3N4gjBFkw7Log-YIHWdY)
> 
> in 1.70 the OpenAi Node is marked as "Not Working"

Can you elaborate? What's the error? Would be helpful if you could share the workflow.

**Comment by parlt** [comment]
1.7.1 its fixed, thx
