### ISSUE TITLE
Code Node only works while testing workflow

### ISSUE THREAD

**Issue by erictmnz** [n8n-io/n8n#11970]
### Bug Description

We have a code node that converts a bytestream into json.
While testing the workflow (even when replaying completed executions) it behaves as expected and outputs json.

However, when the actual executions run the output remains unchanged instead of converting to json.
That means subsequent nodes fail.

![image](https://github.com/user-attachments/assets/836830e6-46bc-4e5f-b850-3c11604eaba4)

![image](https://github.com/user-attachments/assets/490e386d-f6eb-44fb-84c9-9e842bc0f233)

### To Reproduce

**1. Create input node and set to bytestream for example:**

`[
  {
    "body": {
      "typecode": 117,
      "content": {
        "type": "Buffer",
        "data": [
           170,
             70,
             69,
             7,
             135,
             92,
             66,
             238,
             191,
             238,
             79,
             17,
             136,
             249,
             122,
             140
        ]
      }
    }
  }
]`

**2. Create code node to convert to json:**

`
for (const item of $input.all()) {
  // 1. Transform `body.content.data` from byte array to JSON object
  if (item.json.body?.content?.data) {
    try {
      const dataArray = item.json.body.content.data;
      const buffer = Buffer.from(dataArray);
      const jsonString = buffer.toString('utf8');
      const jsonObject = JSON.parse(jsonString);
      item.json.body = jsonObject;
    } catch (error) {
      // Handle JSON parsing errors
      console.error(`Error parsing body.content.data for item with message_id ${item.json.message_id}: ${error.message}`);
      // Optionally, you can set a default value or leave the original data
      // item.json.body = null;
    }
  }
}

// Return the modified items array
return $input.all();
`
**3. Observe output when running manually in the workflow editor (change to json)
4. Observe output when triggered by amqp / webhook (output remains unchanged)**

### Expected behavior

Code node correctly transforms bytestream to json when triggered by AMQP / Webhook / etc. node.

### Operating System

Docker on Azure Container Apps

### n8n Version

1.69.2

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by netroy** [comment]
Can you please create a simple workflow in the UI to reproduce this, and then share the entire workflow JSON? That would help debugging this quicker 🙏🏽

**Comment by erictmnz** [comment]
[Code_node_issue.json](https://github.com/user-attachments/files/17958476/Code_node_issue.json)

When I set the byte stream in a "set field" node it worked fine. The attached is a version with webhook.
The production workflow uses a AMQP node as trigger which causes the issue.

The body needs a byte stream input ie
{
  "typecode": 117,
  "content": {
    "type": "Buffer",
    "data": [
      123,
      34,
      69,
      118,
      101,
      110,
      116,
      83,
      111,
      117,
      114,
      99,
      101,
      34,
      58,
      110,
      117,
      108,
      108,
      44,
      34,
      69,
      118,
      101,
      110,
      116,
      86,
      101,
      114,
      115,
      105,
      111,
      110,
      34,
      58,
      49,
      44,
      34,
      69,
      118,
      101,
      110,
      116,
      78,
      97,
      109,
      101,
      34,
      58,
      34,
      85,
      115,
      101,
      114,
      85,
      112,
      100,
      97,
      116,
      101,
      100,
      34,
      44,
      34,
      82,
      101,
      97,
      115,
      111,
      110,
      34,
      58,
      34,
      85,
      115,
      101,
      114,
      32,
      104,
      97,
      115,
      32,
      117,
      112,
      100,
      97,
      116,
      101,
      100,
      32,
      116,
      104,
      101,
      105,
      114,
      32,
      112,
      114,
      111,
      102,
      105,
      108,
      101,
      34,
      44,
      34,
      65,
      99,
      116,
      111,
      114,
      34,
      58,
      34,
      57,
      52,
      54,
      51,
      49,
      101,
      102,
      57,
      45,
      101,
      52,
      50,
      53,
      45,
      52,
      55,
      52,
      49,
      45,
      57,
      57,
      55,
      52,
      45,
      99,
      53,
      100,
      53,
      100,
      50,
      48,
      53,
      51,
      55,
      56,
      48,
      34,
      44,
      34,
      69,
      118,
      101,
      110,
      116,
      84,
      105,
      109,
      101,
      34,
      58,
      34,
      50,
      48,
      50,
      52,
      45,
      49,
      49,
      45,
      50,
      57,
      84,
      48,
      50,
      58,
      53,
      48,
      58,
      53,
      55,
      46,
      56,
      52,
      55,
      52,
      54,
      55,
      53,
      90,
      34,
      44,
      34,
      67,
      111,
      114,
      114,
      101,
      108,
      97,
      116,
      105,
      111,
      110,
      73,
      100,
      34,
      58,
      34,
      51,
      102,
      50,
      54,
      55,
      48,
      100,
      53,
      45,
      101,
      100,
      52,
      97,
      45,
      52,
      101,
      53,
      57,
      45,
      97,
      98,
      53,
      52,
      45,
      52,
      56,
      98,
      97,
      52,
      53,
      53,
      100,
      102,
      52,
      54,
      52,
      34,
      44,
      34,
      79,
      112,
      101,
      114,
      97,
      116,
      105,
      111,
      110,
      73,
      100,
      34,
      58,
      110,
      117,
      108,
      108,
      44,
      34,
      80,
      97,
      114,
      101,
      110,
      116,
      73,
      100,
      34,
      58,
      110,
      117,
      108,
      108,
      44,
      34,
      83,
      101,
      115,
      115,
      105,
      111,
      110,
      73,
      100,
      34,
      58,
      110,
      117,
      108,
      108,
      44,
      34,
      80,
      97,
      121,
      108,
      111,
      97,
      100,
      34,
      58,
      123,
      34,
      86,
      101,
      114,
      115,
      105,
      111,
      110,
      34,
      58,
      49,
      44,
      34,
      68,
      97,
      116,
      97,
      34,
      58,
      123,
      34,
      85,
      115,
      101,
      114,
      34,
      58,
      123,
      34,
      85,
      115,
      101,
      114,
      73,
      100,
      34,
      58,
      34,
      100,
      52,
      50,
      56,
      100,
      48,
      48,
      97,
      45,
      50,
      97,
      98,
      100,
      45,
      52,
      56,
      99,
      49,
      45,
      57,
      56,
      56,
      101,
      45,
      53,
      49,
      53,
      53,
      100,
      56,
      57,
      53,
      53,
      97,
      48,
      51,
      34,
      44,
      34,
      69,
      109,
      97,
      105,
      108,
      34,
      58,
      34,
      116,
      101,
      115,
      116,
      116,
      109,
      110,
      122,
      99,
      117,
      115,
      116,
      111,
      109,
      101,
      114,
      64,
      103,
      109,
      97,
      105,
      108,
      46,
      99,
      111,
      109,
      34,
      44,
      34,
      70,
      105,
      114,
      115,
      116,
      78,
      97,
      109,
      101,
      34,
      58,
      34,
      116,
      101,
      115,
      116,
      84,
      77,
      78,
      90,
      34,
      44,
      34,
      76,
      97,
      115,
      116,
      78,
      97,
      109,
      101,
      34,
      58,
      34,
      67,
      117,
      115,
      116,
      111,
      109,
      101,
      114,
      34,
      44,
      34,
      68,
      97,
      116,
      101,
      79,
      102,
      66,
      105,
      114,
      116,
      104,
      34,
      58,
      34,
      50,
      48,
      48,
      49,
      45,
      48,
      49,
      45,
      48,
      49,
      84,
      48,
      48,
      58,
      48,
      48,
      58,
      48,
      48,
      90,
      34,
      44,
      34,
      83,
      117,
      98,
      115,
      99,
      114,
      105,
      98,
      101,
      100,
      84,
      111,
      77,
      97,
      114,
      107,
      101,
      116,
      105,
      110,
      103,
      73,
      110,
      102,
      111,
      34,
      58,
      116,
      114,
      117,
      101,
      44,
      34,
      73,
      115,
      65,
      99,
      116,
      105,
      118,
      101,
      34,
      58,
      102,
      97,
      108,
      115,
      101,
      44,
      34,
      85,
      115,
      101,
      114,
      84,
      121,
      112,
      101,
      73,
      100,
      34,
      58,
      51,
      125,
      125,
      44,
      34,
      65,
      100,
      100,
      105,
      116,
      105,
      111,
      110,
      97,
      108,
      73,
      110,
      102,
      111,
      34,
      58,
      123,
      125,
      125,
      44,
      34,
      77,
      101,
      116,
      97,
      100,
      97,
      116,
      97,
      34,
      58,
      123,
      125,
      44,
      34,
      65,
      112,
      112,
      108,
      105,
      99,
      97,
      116,
      105,
      111,
      110,
      34,
      58,
      34,
      84,
      97,
      120,
      77,
      97,
      110,
      97,
      103,
      101,
      114,
      32,
      67,
      117,
      115,
      116,
      111,
      109,
      101,
      114,
      32,
      65,
      112,
      112,
      34,
      44,
      34,
      68,
      111,
      109,
      97,
      105,
      110,
      34,
      58,
      34,
      73,
      100,
      101,
      110,
      116,
      105,
      116,
      121,
      34,
      44,
      34,
      69,
      110,
      118,
      105,
      114,
      111,
      110,
      109,
      101,
      110,
      116,
      34,
      58,
      34,
      65,
      122,
      117,
      114,
      101,
      32,
      68,
      101,
      118,
      32,
      69,
      110,
      118,
      105,
      114,
      111,
      110,
      109,
      101,
      110,
      116,
      34,
      125
    ]
  }
}

**Comment by erictmnz** [comment]
If I add this "dummy node" after AMQP everything works as expected but not straight from the trigger node to the code node.
![image](https://github.com/user-attachments/assets/4df2a3a1-9a47-4e9d-b349-bbd415e5f857)

**Comment by netroy** [comment]
Can you please share a test workflow with the AMQP trigger node, and also suggest a way to add such a message to the message broker, to trigger a non-manual execution.

I think the issue might be in the AMQP trigger node, and If we can reproduce this locally with that node, I think we might be able to fix this quickly. 🙏🏽

**Comment by erictmnz** [comment]
The AMQP trigger is listening to a Azure Service Bus subscription.
Another service is publishing messages via .net to the service bus - which arrives as a byte stream.

**Comment by tomi** [comment]
Hey @erictmnz . When AMQP trigger receives data and emits the output the `item.json.body.content` property is an instance of `Buffer`. This changes when the data is **pinned**, because it gets serialized into JSON and serializing a nodejs `Buffer` to string produces an object with form

```json
{
  "type": "Buffer",
  "data": [...]
}
```

So there's a discrepancy between test executions (when data is pinned) and production executions. You could turn on the "Convert Body To String" and "JSON Parse Body" options from the node. That way the body gets automatically converted to JSON:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/fe695a7d-566d-41cc-b614-b96a548ea128" />

**Comment by erictmnz** [comment]
Great that seems to be working fine at least for the body. Thank you!
