### ISSUE TITLE
No mouse navigation when pressing CTRL

### ISSUE THREAD

**Issue by mastyo** [n8n-io/n8n#11973]
### Bug Description

No mouse navigation when pressing CTRL
Windows 11
Chrome

### To Reproduce

CTR + left click + move mouse

### Expected behavior

Move the canvas

### Operating System

windows 11

### n8n Version

1.68

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mastyo,

We have created an internal ticket to look into this which we will be tracking as "GHC-532"

**Comment by tomi** [comment]
Duplicate of #11755
