### ISSUE TITLE
Slack get user profile by User ID loop

### ISSUE THREAD

**Issue by Serendeepa** [n8n-io/n8n#1198]
**Describe the bug**
When trying to retrieve the user details by user ID the response takes a while and then returns the details of the user which is trying to get the info x50 times. There must be a loop somewhere (can't find where) (this works: https://api.slack.com/methods/users.profile.get/test)

**To Reproduce**
1. Create Slack node
2. Add credentials
3. Resource: User Profile
4. Operation: Get
5. Add field: User ID
6. Set the ID to a valid one

**Expected behavior**
Expected the details of the user with the User ID provided x1

**Environment (please complete the following information):**
 - OS: Windows 10 (Major 10, build 18363)
- Browser: Chrome 87.0.4280.66
 - n8n Version 0.91.0
 - Node.js Version 15.2.1

**Comment by janober** [comment]
Is it possible that you send 50 items into the node? Because then you would also get 50 results. If you want the node to execute only once you have to select "Execute Once".

**Comment by janober** [comment]
Did it solve your issue?

**Comment by Serendeepa** [comment]
Sorry for the delay, I was executing once as I even insolated the node to test it out. The node didn't even gave me data about the user I was asking about, it just displayed the data of the logged in user, repeatedly (and took a bunch of time to run, hinting at a loop)

**Comment by janober** [comment]
With "Execute Once" activated? That should not be possible. It would then only execute once.

**Comment by Serendeepa** [comment]
I'll try to reproduce the issue and get back to you ASAP

**Comment by RicardoE105** [comment]
@Serendeepa any update on this?

**Comment by krynble** [comment]
HI.

I was reviewing this PR and realized that the get profile with user id was not working properly.

This was fixed [here](https://github.com/n8n-io/n8n/pull/1799) and should be released soon.

Regarding the `Execute once` I made a few tests and it's working fine, executing only once for the first input the node receives.

I will be closing this issue for now as the reported issue was fixed. Please feel free to add updates or reopen.

**Comment by janober** [comment]
Thanks a lot for fixing this @krynble. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.121.0
