### ISSUE TITLE
HTTP REQUEST  and PINECONE BUG API KEY

### ISSUE THREAD

**Issue by jfelipesjc** [n8n-io/n8n#11986]
### Bug Description

Apparently, there is a bug in the API authentication for the HTTP Request and Pinecone.

I am using the latest version and tested the same workflow that was producing an HTTP Request error in the latest version (1.69.2):

"Forbidden - perhaps check your credentials?
403 Forbidden Error: Forbidden
Your client does not have permission to get URL /v1/text-to-speech/QJd9SLe6MVCdF6DR0EAu from this server."

Then, I copied and pasted the same node with the same information into a much older version I have here (1.8.2), and it worked perfectly in the older version, showing that the issue lies in this latest version.
![V1 8 2](https://github.com/user-attachments/assets/316516ae-c72c-4a39-9642-e2a971de7271)
![V1 8 2](https://github.com/user-attachments/assets/0ae19756-f775-4bf4-9136-fa1a037cbcd4)

And also, even after configuring Pinecone credentials, it is unable to connect, saying that the API key is apparently incorrect. However, I created and recreated the API key multiple times and tried to connect several times without success.

### To Reproduce

In the HTTP Request calls for ElevenLabs and Pinecone credentials, all necessary authentication details were provided. This includes the API keys, endpoint URLs, and any additional headers or parameters required for successful integration with these services. Despite following the proper setup, the connection did not work as expected, raising questions about potential issues with the current configuration or compatibility in the latest version.

### Expected behavior

Successfully connected using the correct credentials and configuration settings. All required parameters were properly set, and the connection was established without any issues. This indicates that the provided API key, endpoint URL, and other relevant details were accurate and aligned with the service's requirements.

### Operating System

LINUX 20.04

### n8n Version

1.69.2

### Node.js Version

1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jfelipesjc,

We have created an internal ticket to look into this which we will be tracking as "GHC-536"

**Comment by MarcL** [comment]
Hey @jfelipesjc!

We haven’t heard back for a while so we’re going to close this for now.

If you’re still running into the issue, or have more details to share, feel free to reopen it or create a new one. 

Thanks!
