### ISSUE TITLE
i cant start my workflow, when i click test step the workflow isnt running and telegram trigger is not answering

### ISSUE THREAD

**Issue by toninhash** [n8n-io/n8n#11981]
### Bug Description

i have two vms running self hosted n8n, one of them was created yesterday, the other one was working perfectly, but when i try to do the same workflows none of them are working, it could be a config but idk, im not an expert in n8n 

### To Reproduce

add any trigger and test
mines not working and if it is, it dont go to next step

### Expected behavior

trigger responds and follow the workflow

### Operating System

Ubuntu linux 24.04.1 LTS

### n8n Version

1.70.0

### Node.js Version

idk :(

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @toninhash,

We have created an internal ticket to look into this which we will be tracking as "GHC-535"

**Comment by Joffcom** [comment]
Hey @toninhash,

Is this impacting all triggers or just a specific one? You mentioned Telegram one of the things with Telegram is you can only use webhook for each bot so if you use the same bot credentials on 2 n8n instances it won't work, If you test the trigger while it is active you will also need to disable and activate the workflow again.

**Comment by toninhash** [comment]
> Hey @toninhash,
> 
> Is this impacting all triggers or just a specific one? You mentioned Telegram one of the things with Telegram is you can only use webhook for each bot so if you use the same bot credentials on 2 n8n instances it won't work, If you test the trigger while it is active you will also need to disable and activate the workflow again.

i did deleted the api from the other n8n instance before testing , all triggers isnt working, the workflow is deactivated

**Comment by Joffcom** [comment]
What happens if you try a webhook trigger? What error do you see when trying to load the webhook url?

**Comment by toninhash** [comment]
![Uploading imagem_2024-11-29_105652063.png…]()

**Comment by toninhash** [comment]
it says: {"message":"Workflow was started"}
but when i opened my n8n said that it was still running, so it dont go to next step, maybe a conf?

**Comment by toninhash** [comment]
Only running or waiting executions can be stopped and 4 is currently error
WorkflowOperationError: Only running or waiting executions can be stopped and 4 is currently error
    at ExecutionService.assertStoppable (/usr/local/lib/node_modules/n8n/dist/executions/execution.service.js:349:19)
    at ExecutionService.stop (/usr/local/lib/node_modules/n8n/dist/executions/execution.service.js:334:14)
    at ExecutionsController.stop (/usr/local/lib/node_modules/n8n/dist/executions/executions.controller.js:81:16)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26

The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "arollnx9jo" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
Failed to renew license: renewal failed because current cert is not initialized
Failed to renew license: renewal failed because current cert is not initialized
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "sgnornzoyl" is not registered.
The session "y7hzgax9j1" is not registered.
The session "y7hzgax9j1" is not registered.
The session "y7hzgax9j1" is not registered.

**Comment by toninhash** [comment]
i ´´solved´´ tysm for ur time

**Comment by Joffcom** [comment]
Ah perfect, What was it in the end? My thought is a reverse proxy maybe nginx not using websockets.

**Comment by denisyakimov07** [comment]
how did you fix it? i have same issue

**Comment by denisyakimov07** [comment]
The session "2v63s41ew9" is not registered.
The session "2v63s41ew9" is not registered.
The session "2v63s41ew9" is not registered.
The session "2v63s41ew9" is not registered.
Only running or waiting executions can be stopped and 95 is currently success
WorkflowOperationError: Only running or waiting executions can be stopped and 95 is currently success
    at ExecutionService.assertStoppable (/usr/local/lib/node_modules/n8n/dist/executions/execution.service.js:349:19)
    at ExecutionService.stop (/usr/local/lib/node_modules/n8n/dist/executions/execution.service.js:334:14)
    at ExecutionsController.stop (/usr/local/lib/node_modules/n8n/dist/executions/executions.controller.js:81:16)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
