### ISSUE TITLE
copy to clipboard not working

### ISSUE THREAD

**Issue by repoman1964** [n8n-io/n8n#11992]
### Bug Description

using the "call workflow tool" subnode, examining executions. both the input and output json items show a click to copy button but after copying contents to clipboard, only an empty array is stored

![screenshot-primary-production-26ac_up_railway_app-2024_12_01-13_38_57](https://github.com/user-attachments/assets/73721d3b-be5f-4726-a882-c7c43bc09300)

![screenshot-primary-production-26ac_up_railway_app-2024_12_01-13_40_04](https://github.com/user-attachments/assets/c71b0605-67b4-4d39-94d5-811e29574eef)

  

### To Reproduce

1. Go to executions
2. Click on recent execution
3. Click on call workflow subnode
4. Select to display Input/Output as JSON
5. Click on "Copy to Clipboard" 
6. Test copied contents

### Expected behavior

Actual JSON object should be stored to clipboard. Instead all we get is "[]"

### Operating System

UBU 22

### n8n Version

1.69.2

### Node.js Version

20.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @repoman1964,

We have created an internal ticket to look into this which we will be tracking as "GHC-539"

**Comment by MarcL** [comment]
Hey @repoman1964,

I've just tried this with our latest version (1.70.0) and it seems to be working.
Can you try that version and let me know if it works for you?

Thanks!

**Comment by repoman1964** [comment]
im self hosted on railway. it pulls the docker image when it redeploys. i
just fired off another redeployment and im still at 1.69.2. not eager to go
bleeding edge anyway, will keep an eye out for the 1.7 and see if that
fixes the bug on my end. thx for your attention

**Comment by MarcL** [comment]
OK no problem. I'll close the issue for now but please reopen if it still happens.
