### ISSUE TITLE
The connection lines between nodes disappear

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#11990]
### Bug Description

When I copy the configuration code from the link below into the new canvas, the connection lines between nodes will hide as the mouse pointer enters. The lines will only be visible again when the pointer moves out of the comment box.
https://n8n.io/workflows/2269-get-a-birds-eye-view-of-your-n8n-instance-with-the-workflow-dashboard/

**I think a lock button should be added to the top right corner of the comment box. This would solve many inconveniences in various situations.**

https://github.com/user-attachments/assets/7357ec5d-775d-4063-9fdc-356717b51745

### To Reproduce

1. copy config code
2. paste

### Expected behavior

show

### Operating System

n8n cloud

### n8n Version

1.70.1

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-538"

**Comment by tomi** [comment]
This has been fixed in #11950
