### ISSUE TITLE
ERROR: 404 in Nextcloud

### ISSUE THREAD

**Issue by jwillmer** [n8n-io/n8n#120]
I have a `test.txt` in the root of my Nextcloud and try to download it. But I always get 404. Can someone explain me what the problem is and how to solve it?

![image](https://user-images.githubusercontent.com/1503577/68745271-a960ab80-05f6-11ea-8a1f-2659b4736bba.png)

```
ERROR: 404 - {"type":"Buffer","data":[60,33,68,79,67,...]}

StatusCodeError: 404 - {"type":"Buffer","data":[60,33,68,79,67,...]}
    at new StatusCodeError (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:185:22)
    at Request.emit (events.js:209:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:209:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:297:20)
    at IncomingMessage.emit (events.js:214:15)
```

**Comment by janober** [comment]
Sorry for the late answer. But please post questions always to:
https://community.n8n.io/
like written in the issue-template. Only if it is a bug for sure, an issue should be created on Github. Questions are at two different locations and nobody knows where to look for answers.

About the issue you are facing. I just tested it again and it seems to work perfectly fine. If it says that the file is not there it is probably not there. Maybe you are not actually in the root folder or connected as a totally different user. You can simply set the node to Resource: "Folder" and Operation: "List". Then you should see which files and folders it lists and if the file "test.txt" exists.

If you find the problem please comment here with the solution and close the issue. If not please post in the forum and also close the issue. Thanks!

**Comment by jwillmer** [comment]
We are using Nextcloud 16.0.5. Maybe n8n does not support it?

![image](https://user-images.githubusercontent.com/1503577/69133143-b3caeb80-0ab5-11ea-999d-97509d513010.png)

**Comment by janober** [comment]
I am currently using it with Nextcloud 17.0.0 but have it running now for a while and guess before I used it also with version 16.

Are you sure the "Web DAV URL" is correct? It should look similar to this:
`https://nextcloud.exampl.com/remote.php/webdav/`

**Comment by jwillmer** [comment]
`/remote.php/webdav/` was missing. It wasn't clear for me that I need to supply a direct link to the webdav. Does that change from instance to instance? Why not only take the NextCloud domain?

**Comment by janober** [comment]
Ah sorry. Thought because the parameter is called "Web DAV URL" and not "Server Domain" or similar that should be clear. That is also exactly the URL it displays in NextCloud so it made sense to use it as it gets displayed that people can simply copy and paste it. 

I do honestly not know much about NextCloud at all. So do not know if it ever changes, changed or could change in the future.

**Comment by jwillmer** [comment]
Maybe a link or description on how to get this url would help. I honestly needed to google how to find the url. Hint: You need to click on settings in the left-bottom corner in the Nextcloud UI.

Maybe a simple placeholder url that shows the format would also help?

**Comment by janober** [comment]
Totally agree. It is planned to create instructions on how to get the different credentials. Sadly will it take quite some time to create and I am currently more than swamped. So I did sadly not get to it yet.

The placeholder sounds like a great idea. Got added:
https://github.com/n8n-io/n8n/commit/f811094dc5a9dd46e2a0aea6ebc203e2400087ab

Will be released with the next version.

**Comment by sutidor** [comment]
For fellow googlers who might come accross this:

Same error will be thrown if you use incorrect windows backslash in path.
Replace cloud\path with cloud/path and all will be fine.

Also a username containing a space in nextcloud is totally fine; paths with spaces and special characters work also fine without quoting the path.
