### ISSUE TITLE
GraphQL errors aren't interpreted as errors

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1200]
**Describe the bug**

This result is a success in n8n / the GraphQL node:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/193115/99875273-7defa400-2bee-11eb-9b5e-994214dd0a06.png">

**To Reproduce**
1. Have the GraphQL query fail, e.g. by including a property that doesn't exist

**Expected behavior**
This should fail the node, allowing retries and the error workflow to be executed.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04] 0.94 / latest docker
 - n8n Version [e.g. 0.26.0] 0.94 / latest docker
 - Node.js Version [e.g. 10.16.0]: 0.94 / latest docker

**Comment by janober** [comment]
Is this the case for all GraphQL APIs the same? So that they return a 200 success-response if they actually fail? Because I am not sure if here n8n is misbehaving or the GraphQL server. Is a serious question as I honestly do not know.

**Comment by haf** [comment]
All GQL servers return 200 OK for all conditions, error- or successful-. I haven't looked into exactly how the relay/apollo clients know it's an error, but they all call the error callback instead. I've tried with clients in F#, NodeJS/Apollo and Haskell/Hasura and it's the case for all of them.

**Comment by frane** [comment]
GraphQL convention is to always return a a set of { data: ..., errors: ... } on the top level of the response. One is required the other should be empty or null. In the case that error is not null or empty, there is an error and needs to be treated like this.

Regarding HTTP: It is totally fine to always return 200 as it is just a transport and could theoretically also be something entirely different, like TCP. HTTP errors should be considered as transport errors, but they have no significance and should not be interpreted as GraphQL (application) errors.

**Comment by frane** [comment]
See also: http://spec.graphql.org/June2018/#sec-Response
