### ISSUE TITLE
how to delete the old executions?

### ISSUE THREAD

**Issue by Alex-Levinson** [n8n-io/n8n#12006]
### Bug Description

Now I cant find a place do delete old executions

### To Reproduce

there is no option to delete all execution in the new canvas

### Expected behavior

It suppose to have a place to delte them

### Operating System

ubuntu 22.04

### n8n Version

1.69.2

### Node.js Version

1.69.2

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Alex-Levinson,

We have created an internal ticket to look into this which we will be tracking as "GHC-547"

**Comment by Joffcom** [comment]
Hey @Alex-Levinson,

If you go to Overview > Executions you can still check the boxes next to executions to delete them.

![image](https://github.com/user-attachments/assets/02297205-b17e-4f37-9980-af506575f663)

**Comment by xhzkp** [comment]
@Joffcom 
This will delete all execution records, but I only want to delete the execution records of the workflow I am currently editing. Therefore, could a button for this feature be added at the location shown in the image below?
![AA](https://github.com/user-attachments/assets/7dd43b78-f53d-4fdb-a1b8-1f68b1bc45c5)

**Comment by Joffcom** [comment]
Hey @xhzkp 

That would be a feature request and better suited to the support forum but if enough users want that we could look at making it happen.

For now in the main execution view you could filter by the workflow and delete that way.

As there doesn't appear to be anything that needs fixing here I am going to mark this as closed. Let me know if you have any questions on this.

**Comment by xhzkp** [comment]
> For now in the main execution view you could filter by the workflow and delete that way.

I think using the filtering method is not convenient enough. Adding the button in the location shown below would make it more straightforward.
![dell all](https://github.com/user-attachments/assets/1c01939c-2617-44fa-ba83-3599197994b8)
