### ISSUE TITLE
( Twilio Trigger ) There is a Schema structure difference between test and production

### ISSUE THREAD

**Issue by StevenBLR** [n8n-io/n8n#12016]
### Bug Description

Hello,

I’m trying to use Twilio Trigger node to get new messages from Whatsapp (text and audio), the trigger works but I realized that the reponse schema is different when I’m testing within the app and when I’m using it in production which break the whole system (I’m trying to use “MessageType” to process text and audio differently but this attribut doesn’t show up on prod mode). I looked at twilio documentation and it seems like the structure I’m receiving on test mode is the right one.

**Test schema**
<img width="763" alt="response_test_webhook" src="https://github.com/user-attachments/assets/13b7993f-79f0-4df8-9ec7-c7b11fcd2a91">

**Production schema**
<img width="827" alt="response_prod_webhook" src="https://github.com/user-attachments/assets/13611a57-1ad0-46b0-b045-1b8c1f86c1dd">

### To Reproduce

1. Create a Twilio trigger node
2. Copy/paste the webook url to Twilio sender page 
<img width="889" alt="image" src="https://github.com/user-attachments/assets/f55e7bda-d5b3-4a52-a6bc-fd38e67b5922">
3. Send a message within test mode & outside test mode 
4. Check the structure difference in logs

### Expected behavior

We would expect to get the same data structure on test and production mode so we can have the same outcome in both situations 

### Operating System

MacOS

### n8n Version

n8n@1.69.2

### Node.js Version

??

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @StevenBLR,

We have created an internal ticket to look into this which we will be tracking as "GHC-550"

**Comment by Joffcom** [comment]
Hey @StevenBLR,

I have just taken a quick look at the node and it looks like we return whatever we are sent by Twilio, I suspect what is happening is the test tool Twilio has doesn't send all of the fields.

The way to handle this in your workflow would be to normalise the data so you could add an If after the trigger and check to see if `{{ $json.data }}` exists if it does extract that and only use those fields if it doesn't continue like normal. You can then put both inputs into the same next node and from there the data should match up.

It may be worth reporting to Twilio that their test tool does not send the exact same structure as the production webhooks. For now as this isn't something we control I am going to mark this as closed, Let me know if you have any questions on this.
