### ISSUE TITLE
TypeError: request.headers.split is not a function

### ISSUE THREAD

**Issue by Alexandero89** [n8n-io/n8n#12025]
### Bug Description

After enabling the sentry node module using:
`NODE_FUNCTION_ALLOW_EXTERNAL=@sentry`
I see a lot of exceptions in the log when using the sentry module in a custom code node:
`TypeError: request.headers.split is not a function`
It also crashes n8ns GUI most of the time. So it restarts a lot!

I found this issue which is exactly the mentioned error https://github.com/getsentry/sentry-javascript/issues/10936

The currently sentry module is version 7.87.0 and this bug was fixed in 7.106.0 ( see https://github.com/getsentry/sentry-javascript/issues/10936#issuecomment-1986208220)

Please bump the sentry version at least to version 7.106.0 if not higher.
The newest version right now is 8.42.0

### To Reproduce

1. Install n8n
2. enable @sentry node module via environmental variable in docker-compose
3. use sentry module in a code node

### Expected behavior

not throw an exception and crash the Editor/GUI

### Operating System

docker-compose

### n8n Version

1.69.2

### Node.js Version

...

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Alexandero89,

We have created an internal ticket to look into this which we will be tracking as "GHC-552"

**Comment by Joffcom** [comment]
Hey @Alexandero89 

Can you provide a minimal workflow example that shows this happening so we have some thing to test against to make sure that updating will resolve it.

**Comment by janober** [comment]
Fix got released with [`n8n@1.72.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.72.0)
