### ISSUE TITLE
Spotify Integration - Get Playlists Fails

### ISSUE THREAD

**Issue by thomasnorris** [n8n-io/n8n#12026]
### Bug Description

As of a few days ago, the Spotify "Get Playlists" node has started to fail with this error:
![image](https://github.com/user-attachments/assets/845e978c-93c0-4b60-80e8-b29e57d77273)

Here are my current settings for the node. I have verified that my credentials are correct and can authenticate appropriately:
![image](https://github.com/user-attachments/assets/2a944ac5-fb4d-41e4-9fe3-4e118abd5e84)
![image](https://github.com/user-attachments/assets/32b63192-439d-489c-be25-36fd3423a24f)

I was able to find [this post](https://community.n8n.io/t/spotify-api-broken/63642) on the official N8N forums, but wanted to open an issue for additional visibility.

Much love to the developers of this wonderful tool!

### To Reproduce

1. Create a new node, selecting Spotify -> Get a user's playlists
2. Create a new credential (or use an existing Spotify credential) following the node's instructions
3. Hit the "Test step" button in the upper righthand corner
4. Observe the error message, playlists will not appear in the output window

### Expected behavior

Playlists should appear in the output window and an error should not appear

### Operating System

Docker

### n8n Version

v1.69.2

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @thomasnorris,

We have created an internal ticket to look into this which we will be tracking as "GHC-553"

**Comment by Joffcom** [comment]
Hey @thomasnorris,

As this is opened on the forums I am going to close it here so we don't split the attention, It looks like one of our developers is replying to the forum post and looking into it so it is in good hands.

Thanks for letting us know anyway 👍🏻

**Comment by thomasnorris** [comment]
Perfect, thank you!

**Comment by janober** [comment]
Fix got released with [`n8n@1.75.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.75.0)
