### ISSUE TITLE
The "Add Workflow" button often doesn't work

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#12029]
### Bug Description

The "Add Workflow" button often doesn't work, though sometimes it works fine. It's strange, there's no pattern, and it cannot be reproduced.

https://github.com/user-attachments/assets/3dfd3e5f-5dbb-46c8-aef4-9b2665734271

### To Reproduce

see demo

### Expected behavior

see demo

### Operating System

n8n cloud

### n8n Version

1.70.1

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-555"
