### ISSUE TITLE
Node in my personal project still connected to another project

### ISSUE THREAD

**Issue by jeanyvesl** [n8n-io/n8n#12047]
### Bug Description

It appears that one of my Gmail node is still connected to a different workflow (from a different project) and therefore also has different credentials linked. I cannot simply modify the credentials to fix this problem unfortunately.

<img width="762" alt="image" src="https://github.com/user-attachments/assets/1b25163c-a673-4cea-9d19-6c5fe5d68e25">

### To Reproduce

1. Create a workflow and related Gmail credentials in a given project (everything must be part of that project)
2. Duplicate the workflow
3. Verify that you do not have credentials registered for your personal space yet, that's important to replicate
4. Move the duplicated workflow into your personal workflows
5. Open the "Workflow copy" 
6. Most Gmail node appear with a warning
7. Open any node, the former credentials appear locked into the node itself

### Expected behavior

I would expect the credentials field to be left blank, meaning without any credentials so that I can take the step to add one which is relevant without having to create a new node and link it back again into my workflow.

### Operating System

MacOs

### n8n Version

1.70.1

### Node.js Version

v22.12.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jeanyvesl,

We have created an internal ticket to look into this which we will be tracking as "GHC-559"
