### ISSUE TITLE
Error Message window.crypto.randomUUID

### ISSUE THREAD

**Issue by R41z0r** [n8n-io/n8n#12051]
### Bug Description

I updated to the new latest which appeared as a popup (1.70.2) and now every click I do in workflows produces a popup message with: window.crypto.randomUUID is not a function. I am using the latest docker image.

![CleanShot 2024-12-04 at 17 24 59](https://github.com/user-attachments/assets/1f795b55-135f-429f-95e5-49824d5d2fe9)

NodeViewSwitcher-BXWGR8PZ.js:33469 TypeError: window.crypto.randomUUID is not a function
    at Object.assignNodeId (index-BT7276bJ.js:205848:31)
    at resolveNodeData (NodeViewSwitcher-BXWGR8PZ.js:33643:41)
    at addNode (NodeViewSwitcher-BXWGR8PZ.js:33513:22)
    at addNodes2 (NodeViewSwitcher-BXWGR8PZ.js:33453:25)
    at async onAddNodesAndConnections (NodeViewSwitcher-BXWGR8PZ.js:35077:26)
addNodes2 @ NodeViewSwitcher-BXWGR8PZ.js:33469
await in addNodes2
onAddNodesAndConnections @ NodeViewSwitcher-BXWGR8PZ.js:35077
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
nodeTypeSelected @ NodeCreation-CrD-YRlw.js:292
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
selectNodeType @ NodeCreator-_l4IOkdC.js:1700
onSelected @ NodeCreator-_l4IOkdC.js:1735
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
emit @ index-BT7276bJ.js:7027
wrappedEmit @ NodeCreator-_l4IOkdC.js:1100
onClick @ NodeCreator-_l4IOkdC.js:1171
callWithErrorHandling @ index-BT7276bJ.js:2169
callWithAsyncErrorHandling @ index-BT7276bJ.js:2176
invoker @ index-BT7276bJ.js:9277
index-BT7276bJ.js:2227 TypeError: Cannot read properties of undefined (reading 'id')
    at onAddNodesAndConnections (NodeViewSwitcher-BXWGR8PZ.js:35115:54)

### To Reproduce

Go to workflow
Create a new workflow
Add first step
Choose any available

Popup message appears in the bottom right corner

### Expected behavior

Every step works

### Operating System

MacOS 15.1.1 Build: 24B91

### n8n Version

1.70.2

### Node.js Version

Node from Docker Image

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @R41z0r,

We have created an internal ticket to look into this which we will be tracking as "GHC-560"

**Comment by R41z0r** [comment]
> What browser are you on?

Brave [Version 1.73.91 Chromium: 131.0.6778.85 (Offizieller Build) (arm64)](https://brave.com/latest/)

**Comment by netroy** [comment]
Can you please try executing `window.crypto.randomUUID()` in the browser console to see if that also throws an error, or if that returns a UUID string?
![image](https://github.com/user-attachments/assets/3d25ef6d-4856-4d86-9b8d-47a3bf3d0cfe)

**Comment by R41z0r** [comment]
> Can you please try executing `window.crypto.randomUUID()` in the browser console to see if that also throws an error, or if that returns a UUID string? ![image](https://private-user-images.githubusercontent.com/196144/392483917-3d25ef6d-4856-4d86-9b8d-47a3bf3d0cfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzA1OTIsIm5iZiI6MTczMzMzMDI5MiwicGF0aCI6Ii8xOTYxNDQvMzkyNDgzOTE3LTNkMjVlZjZkLTQ4NTYtNGQ4Ni05YjhkLTQ3YTNiZjNkMGNmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNjM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODRhZmRiYTA2ZDlkZmZiYmU3OTVkOWU1MDJmODU2ODI3NjJmNTlhODBiYjVkMmY4YjY4NTcyODY1NmRhMTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6LjnzMZwdtNxpVoXNx0gtrsml1ummcZKY8HcEzxz19A)

If I do that inside of github.com I correctly get a randomUUID, but inside of n8n there is nothing, only an error message.

n8n:
![CleanShot 2024-12-04 at 17 40 27](https://github.com/user-attachments/assets/e0018911-0639-46d5-be00-cf54bc854469)

github:
![CleanShot 2024-12-04 at 17 40 46](https://github.com/user-attachments/assets/79fe443e-6d3e-44fe-bf06-8516660be301)

**Comment by Joffcom** [comment]
@R41z0r are you accessing n8n over http or https?

**Comment by netroy** [comment]
also, Do you have `N8N_SECURE_COOKIE` set to `false`?

**Comment by R41z0r** [comment]
As it's a local instance I am using http for access.

that's my compose file, the red arrow I just changed to the latest stable for me to use it, normally it had "latest" Tag.
![CleanShot 2024-12-04 at 17 47 25](https://github.com/user-attachments/assets/1146c5fa-94f2-4910-9543-d955976f0364)

**Comment by netroy** [comment]
We'll try to get this fixed. In the meanwhile can you please revert to `1.69.2`.

BTW, you can delete the `N8N_BASIC_AUTH_` env variables. Those were removed over a year and a half ago.

**Comment by R41z0r** [comment]
> We'll try to get this fixed. In the meanwhile can you please revert to `1.69.2`.
> 
> BTW, you can delete the `N8N_BASIC_AUTH_` env variables. Those were removed over a year and a half ago.

Thanks for the quick help - I already reverted to 1.69.2 - and thanks for the information to remove unneeded stuff.

**Comment by ashepp** [comment]
Also seeing this fwiw. Trying to revert.
