### ISSUE TITLE
window.crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by synapsevzla** [n8n-io/n8n#12059]
### Bug Description

When I try to add any object to a new workflow I get the following message:

window.crypto.randomUUID is not a function

### To Reproduce

![image](https://github.com/user-attachments/assets/56660614-1ac5-4c47-85f6-a89b9f8b995a)

### Expected behavior

Esperaba crear un nuevo workflow pero no es posible no me lo permite genera el siguiente error cuando agrego cualquier tipo de disparador:

![image](https://github.com/user-attachments/assets/03bb4d1d-2b3d-4eff-b46a-c67be6338338)

### Operating System

Ubuntu Server  24.04.1 LTS

### n8n Version

1.70.2

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @synapsevzla,

We have created an internal ticket to look into this which we will be tracking as "GHC-566"

**Comment by netroy** [comment]
Duplicate of #12051
