### ISSUE TITLE
Add localization options for validation messages

### ISSUE THREAD

**Issue by xhzkp** [n8n-io/n8n#12058]
### Bug Description

I noticed that the validation messages shown in the form controls (e.g., as seen in the image below) lack localization options. It doesn't look very elegant.

It would be great to add an option to localize these messages for better flexibility and usability.

![tip](https://github.com/user-attachments/assets/e4cc9d02-7cde-4b03-a27d-cffef59b1872)

**Suggestion:**  
1.For the localization option of "This field is required," Add it to the location shown in the image below. (**To the right of the required field button**.)
![tip0](https://github.com/user-attachments/assets/61b6f23d-2cb5-499a-a0f0-1a0960415fa3)

2.For the localization options of **email** and **dropdown List** controls, add them to their control settings.
![tip3](https://github.com/user-attachments/assets/91839a47-783a-4e37-bfd4-14f39ae8b837)

PS: These improvements are easy to implement and highly anticipated. They would make n8n stand out by excelling in the details.
### To Reproduce

no

### Expected behavior

no

### Operating System

n8n cloud

### n8n Version

1.68.0

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @xhzkp,

We have created an internal ticket to look into this which we will be tracking as "GHC-565"

**Comment by Joffcom** [comment]
Hey @xhzkp 

We only use GitHub issues for tracking bugs and this looks like a feature request.

As there is nothing that needs fixing here would you be able to create a feature request topic on our [Community Support forum](https://community.n8n.io/c/feature-requests/5) and we can pick it up from there.

For now I am going to close this, let me know if you have any questions on this.

**Comment by Joffcom** [comment]
Hey @xhzkp 

We only use GitHub issues for tracking bugs and this looks like a feature request.

As there is nothing that needs fixing here would you be able to create a feature request topic on our [Community Support forum](https://community.n8n.io/c/feature-requests/5) and we can pick it up from there.

For now I am going to close this, let me know if you have any questions on this.

**Comment by xhzkp** [comment]
@Joffcom 
thank you for your reminder. I have already posted it on the forum. Could you please help me delete this post?
