### ISSUE TITLE
drag and select nodes rollback

### ISSUE THREAD

**Issue by matheus-b7** [n8n-io/n8n#12057]
### Bug Description

when I move nodes from a click and drag selection they rollback after a short time or another single node movement.

The multiple nodes movimentation works fine when they are selected one by one using "ctrl"

### To Reproduce

select multiple nodes by click and drag, move selected nodes, select another node alone and move.

### Expected behavior

 the multiple nodes moved before should get back for the last position.

### Operating System

windows

### n8n Version

1.69.2

### Node.js Version

?

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @matheus-b7,

We have created an internal ticket to look into this which we will be tracking as "GHC-564"

**Comment by Joffcom** [comment]
Hey @matheus-b7 

Can you try updating to 1.71.0 which was released today and let me know if you still have the same issue.
