### ISSUE TITLE
Postgres Connection Failure

### ISSUE THREAD

**Issue by wukimidaire** [n8n-io/n8n#12065]
### Bug Description

When trying to connect to a GCP hosted Postgres instance, where IP whitelisted has been double checked, it still fails to connect. 

It keeps loading to save the credentials. 

Facing no issues connecting to postgres database with my SQL Client.

This issue is existing with existing credentials and new credentials, bug is something recent.

This recent issue on the n8n forum might be related to it: https://community.n8n.io/t/ai-agent-tool-connectivity-to-postgresql/64007/3

### To Reproduce

Go to Postgres node

Enter Postgres credentials

See error popping up like: unable to connect 172.xxx. ... (this shown ip address isn't the right ip address of the postgres instance)

### Expected behavior

Just having the credentials working when calling any endpoints on the postgres node.

### Operating System

N8N Cloud

### n8n Version

1.70.1

### Node.js Version

/

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @wukimidaire,

We have created an internal ticket to look into this which we will be tracking as "GHC-567"

**Comment by wukimidaire** [comment]
UPDATE: potentially found the issue as there where some extra ip addresses added to the whitelist found here: 

https://docs.n8n.io/manage-cloud/cloud-ip/

**Comment by Joffcom** [comment]
@wukimidaire there were some IPs added recently, Has adding them all worked? I am surprised you didn't see any failed connection attempts in the GCP logs or are failed attempts not logged?

**Comment by wukimidaire** [comment]
I have added the new IP n8N addresses to my postgres instance, found from here: https://docs.n8n.io/manage-cloud/cloud-ip/

When trying to connect from n8n, it's still returning this error message:

<img width="360" alt="Screenshot 2024-12-05 at 12 22 12" src="https://github.com/user-attachments/assets/6fcbe908-f959-4784-ac84-9d0ca504289b">

**Comment by wukimidaire** [comment]
Looking into my GCP logs

**Comment by Joffcom** [comment]
@wukimidaire that error looks different, Can you check that the credential you are using can be used by the user and / or project you are using in n8n. The message is not related to not being able to connect.

**Comment by wukimidaire** [comment]
yeah it's a different error, the change in error might be caused by adding the latest IP addresses.

To my surprise GCP isn't auto enabling logging, so can not find any logs immediately.

I duplicated the credentials for both environments but no change yet. 


<img width="1093" alt="Screenshot 2024-12-05 at 12 27 19" src="https://github.com/user-attachments/assets/aac7e94c-b9d6-4ce5-add0-ecb865a99210">

Ps: think you in advance for looking into this issue

**Comment by Joffcom** [comment]
@wukimidaire Are you making the workflow in your personal project or in GTM Engineer Agent? You won't be able to use Personal in the project or GTM in a personal project.

When you add the credential does it say that it connects at the top of the page?
