### ISSUE TITLE
Error loading records from Postgres by typing own query.

### ISSUE THREAD

**Issue by wilsonfe** [n8n-io/n8n#12073]
### Bug Description

Note that in the first query, running in Pgadmin, the records are returned correctly. In this case, there are only two records with these conditions.

![image](https://github.com/user-attachments/assets/72297ae6-8b2b-4f2f-a39b-4a2db6dcb519)

But see in the image below that the same query, when using the postgres node, typing the query itself, returns many more records with the same condition.

![image](https://github.com/user-attachments/assets/f1f7fdfd-d366-4f7e-8354-d93585859332)

### To Reproduce

Create a query in a Postgres database joining two tables with conditions that result in few records, run this same query using pgadmin and run the query using node Postgres. You will see that the results are different.

### Expected behavior

Return the same amount of records.

### Operating System

Debian 12

### n8n Version

1.70.3 (Self Hosted)

### Node.js Version

1.2 (Latest version: 1.3)

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @wilsonfe,

We have created an internal ticket to look into this which we will be tracking as "GHC-571"
