### ISSUE TITLE
New Canvas shows in dark mode in executions

### ISSUE THREAD

**Issue by javedh-dev** [n8n-io/n8n#12087]
### Bug Description

In executions tab for a workflow the new canvas always displays in dark. while in editor it works as per theme.
<img width="1436" alt="Screenshot 2024-12-07 at 5 13 27 PM" src="https://github.com/user-attachments/assets/72ca50ec-5418-4920-bd5b-47c61f94c24e">

### To Reproduce

1. Enable new canvas beta from the workflow.
2. Create a workflow in light mode.
3. Go to the executions tab to see what was executed.
4. There the canvas is shown in dark mode while whole UI is in light mode

### Expected behavior

In light mode the canvas should also follow the light theme.

### Operating System

Linux

### n8n Version

1.70.3

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @javedh-dev,

We have created an internal ticket to look into this which we will be tracking as "GHC-576"

**Comment by netroy** [comment]
This is possibly the same issue as the one fixed in https://github.com/n8n-io/n8n/pull/12079
We'll release this in a patch release on Monday.
