### ISSUE TITLE
New Canvas - panning with Ctrl + left button is missing

### ISSUE THREAD

**Issue by fungdanielv** [n8n-io/n8n#12090]
### Bug Description

the existing funcationality of quilkly panning over a large set of nodes with Ctrl + left mouse is a create convenience and should not be removed. the mini window on the bottom of the new canvas should not be considered anything near as an alternative to the panning function. 

### To Reproduce

1.  for any laoded workflow, use CTRL + Left mouse to pan over the workflow
2.  switch to the new canvas CTRL+ left mouse does not work for panning

### Expected behavior

CTrl + left mouse click should allow me to pan over a canvas just as it does today in the old canvas

### Operating System

Ubuntu 24

### n8n Version

1.70.2

### Node.js Version

20.18

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @fungdanielv,

We have created an internal ticket to look into this which we will be tracking as "GHC-579"
