### ISSUE TITLE
TheHive5 - context not refreshed when credential changed

### ISSUE THREAD

**Issue by kmahyyg** [n8n-io/n8n#12097]
### Bug Description

Switch between two different credentials in the TheHive5 node, try to update case assignee, assignee validation will fail due to `user not found`.

### To Reproduce

1. Create two independent instances of TheHive5, with users:
- Instance 1: User-A (userA@example **.com** ), User-B (userB@example **.com** )
- Instance 2: User-A (userA@example **.net** ), User-B (userB@example **.net** )
2. Ingest an alert to the Hive.
3. Use Credential of **User-B of Instance 1**, to fetch an alert by triggering "test flow".
4. On the same node, switch credential to **User-B of Instance 2** and triggering "test flow" again.
5. Create next node to "Promote to case" with any template. (Actually, at this step, you could already see that template is mismatch comparing with the reality. Here template listed is on Instance 1 instead of Instance 2.)
6. Create next node to change "assignee" for the case just created. 

If you tried to select "User-A" from the dropdown list, then click test, server will tell you "404 User Not Found" (This actually selected `userA@example .com`
If you choose to "$input.assignee" from previous input, then N8N will tell you you've chosen an invalid user (This actually selected `userA@example .net`) and valid user is `userA@example .com`.

### Expected behavior

after switching credentials, all such kind of volatile bounded data cache should be refreshed.

### Operating System

Arch Linux (Official Docker Deployment)

### n8n Version

1.70.3

### Node.js Version

Official Docker Deployment

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @kmahyyg,

We have created an internal ticket to look into this which we will be tracking as "GHC-585"

**Comment by kmahyyg** [comment]
Description updated to provide more clearer instruction for reproduce.

**Comment by Joffcom** [comment]
Hey @kmahyyg 

Just to confirm on this one, when you change the credential are you also updating any ID fields as it sounds like it is working correctly and telling you the user doesn't exist when it doesn't.

**Comment by kmahyyg** [comment]
No, no action except changing cred.

It seems it uses prefetched users list in instance A to validate input after switching to instance B.

**Comment by Joffcom** [comment]
So when you are fetching an alert are you doing from the drop down list or using an ID? Typically if you see boxes with From List you would need to manually refresh the data as it is loaded and saved from the server. Is this maybe what you are seeing?
 
![image](https://github.com/user-attachments/assets/e5699ba5-122d-41e3-b4ee-d095efa75d15)

**Comment by kmahyyg** [comment]
By ID. Alert ID is directly copied from TheHive Web UI.

**Comment by Joffcom** [comment]
Hey @kmahyyg,

Perfect and I assume the ID is the same on both instances and you are not doing any data pinning on the output?

**Comment by kmahyyg** [comment]
I didn't pin anything, just configure minimal param and click test.

No, except the display name of users, none of the data is the them between two instances.

**Comment by Joffcom** [comment]
@kmahyyg so you input the id, run the node, input the second id and run the node again but you see the data output from the first id?

**Comment by kmahyyg** [comment]
Yes, after run it the second time, I go next to the update case node and it shows  users on the first instance.

**Comment by kmahyyg** [comment]
Wait, I see the alert data from the second instance and go to the next node (update case), try to change assignee, but users in the next node is from first instance

**Comment by Joffcom** [comment]
and in update case assuming you are using the automatic mapping are you refreshing that data so it picks up the fields from the new credential? We should probably update the docs to mention that the fields are not auto refreshed

**Comment by kmahyyg** [comment]
BTW, may I request if there is any guidance to update such mapping manually to make sure it is working?

Actually, instance A and B is two separated 
 Prod and Dev environment.

**Comment by Joffcom** [comment]
@kmahyyg to manually update click on the 3 dots above the fields and there should be an option to refresh data

**Comment by kmahyyg** [comment]
I use the "map each column manually", and after I manually click "refresh fields list", everything is good.

Thanks for guidance, It would be best if you could add docs for letting user know it won't auto-refresh.

**Comment by Joffcom** [comment]
Hey @kmahyyg,

That is a good idea, I might even add it to the nodes as a note at the bottom. For now as this is intended I will mark this as closed but I will make another internal ticket for the change.
