### ISSUE TITLE
File upload via Slack - missing channels in the list

### ISSUE THREAD

**Issue by katealexandria** [n8n-io/n8n#1210]
**Describe the bug**
Not able to see all the channels in the Slack node when setting up a file upload.

**To Reproduce**
1. Add a Slack node and select valid credentials for the Slack API.
2. Set `Resource=File` and `Operation=Upload`
3. Under `Options`, click `Add options` -> `Channels`. This will result in a list of channels, but there are many channels which are not available in this list.

**Expected behavior**
All Slack channels should be listed. 

**Environment**
 - n8n Version: 0.94.1

**Additional context**
Note that the selected credentials are valid for the channels which are missing in the list i.e. the Slack app was properly installed for those channels.

**Comment by RicardoE105** [comment]
@katealexandria By default, just the public channels were listed. Now public and private channels will be listed. It should fix the issue. Thanks for letting us know. We will let you know when is released.

**Comment by janober** [comment]
Got released with n8n@0.96.0
