### ISSUE TITLE
AI Agent Multiple Tools Execution Takes Only First Run

### ISSUE THREAD

**Issue by lucaspeyrin** [n8n-io/n8n#12113]
### Bug Description

When an AI Agent creates multiple tool calls, such as for example creating 5 calendar events, then the tools only get the first run of {{ $fromAI('event_description') }} and creates 5 events but with the first run's data.

So for {{ $fromAI('event_description') }} the event_description would actually be the same for every event, even if the AI had correctly created different descriptions.

### To Reproduce

1. Create an AI Agent with tools for example google calendar and set some AI-filledexpressions using {{ $fromAI('event_field') }}
2. Ask the AI to create a schedule for today with multiple events
3. Go check your calendar to see that multiple events have been created but are actually duplicates****

### Expected behavior

Dupliation of the data in every run of the tool using the first run's data only.

### Operating System

Ubuntu Linux

### n8n Version

1.71.1

### Node.js Version

?

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @lucaspeyrin,

We have created an internal ticket to look into this which we will be tracking as "GHC-590"

**Comment by netroy** [comment]
A fix for this was released in `1.72.0`

**Comment by BrianMont** [comment]
This bug is still on version 1.76.1
