### ISSUE TITLE
Gmail Trigger always triggered by Draft

### ISSUE THREAD

**Issue by jeanyvesl** [n8n-io/n8n#12134]
### Bug Description

I noticed that the Gmail Trigger is also triggered by Draft emails even though I haven't setup the filter to "Include Drafts".

### To Reproduce

1. Add the Gmail Trigger (every minute, message received). Make sure not to include any filter.
2. Add any flow
3. Save and activate the workflow
4. Write a draft in your Gmail account
5. The workflow will be triggered

### Expected behavior

Gmail trigger is only working for inbound email unless specified in the filter to include Drafts

### Operating System

MacOs

### n8n Version

1.70.1

### Node.js Version

v22.12.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jeanyvesl,

We have created an internal ticket to look into this which we will be tracking as "N8N-7935"

**Comment by jeanyvesl** [comment]
@Joffcom here is what the node says - `Gmail Trigger node version 1.1 (Latest version: 1.2)`

**Comment by riascho** [comment]
Hi @jeanyvesl 
Can you check if that toggle is on for you? On version `1.1`, if no filter specified it will be on by default (including drafts). 
Can you try to switch it off and see if that helps or use the next node version `1.2` where the toggle is off by default. 

![image](https://github.com/user-attachments/assets/7eefc8c4-2b6b-43c6-ad0b-a7b3da22028e)

Thanks for sharing your findings!

**Comment by tomi** [comment]
Closing this since this is most likely due to the (expected) behaviour of the older version of the Gmail Trigger node. Please let us know if you are still experiencing the issue on version `1.2`.
