### ISSUE TITLE
Community Edition activation key issue

### ISSUE THREAD

**Issue by gustavon8n** [n8n-io/n8n#12143]
### Bug Description

I requested and received the key in my email (gustavod1000@gmail.com). However, when I tried to enter it on the platform, a failure message appeared. I tried again, and now it says the token has already been used.

### To Reproduce

1 settings
2 usage plan

### Expected behavior

I expected the Community Edition plan to work.

### Operating System

Docker on Ubuntu 22.04

### n8n Version

1.70.4

### Node.js Version

i dont now

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @gustavon8n,

This sounds like a support issue not a bug report, can you email help@n8n.io including your license key or create a post on the support forum (without the key).

**Comment by gustavon8n** [comment]
Sorry!

Thank you for the support.

________________________________
De: Jon ***@***.***>
Enviado: terça-feira, 10 de dezembro de 2024 13:56
Para: n8n-io/n8n ***@***.***>
Cc: gustavon8n ***@***.***>; Mention ***@***.***>
Assunto: Re: [n8n-io/n8n] Community Edition activation key issue (Issue #12143)


Hey @gustavon8n<https://github.com/gustavon8n>,

This sounds like a support issue not a bug report, can you email ***@***.******@***.***> including your license key or create a post on the support forum (without the key).

**Comment by Joffcom** [comment]
No problem, I will keep an eye on the ticket as well :)
