### ISSUE TITLE
generic OAuth2 API credentials wont connect instead it saves settings

### ISSUE THREAD

**Issue by mstelios** [n8n-io/n8n#1214]
**Describe the bug**
after setting all the required parameters on a generic OAuth2 credentials dialogue and save it i press the connect button to initiate the trust link. instead of popping up the expected window i get the following and no connection attempt is made whatsoever.
![image](https://user-images.githubusercontent.com/14014015/100514174-24055600-317b-11eb-85a9-2f3489a00e48.png)

**To Reproduce**
1. Go to 'Credentials->New-> Credential type: choose OAuth2 API'
2. fill in all the details with valid or even fake data on Credential Data (connect will be enabled)
3. Clock on ' Not connected ' button to connect

**Expected behavior**
instead i would expect to popup a new browser window and take me to auth url in order to login and approve the trust link.

**Environment (please complete the following information):**
 - OS: docker 19.03.11
 - n8n Version   0.95.1 latest docker image with id 577738d60ada 
 
**Additional context**
![Screenshot_2020-11-28 n8n - ⚠️ playground](https://user-images.githubusercontent.com/14014015/100514396-076a1d80-317d-11eb-90c6-73257031e40d.png)

**Comment by janober** [comment]
I am a little bit confused. What is the error that appears you are talking about? Do you mean with the error the success message "Credentials updated"?

For me, it opens a new window just fine. Is it possible that something blocks it?

What operating system are you running on with what browser?

**Comment by mstelios** [comment]
firefox  83 on windows 10 pro 20H2

the 1st time (i had wrong data on the form) it did tried to pop up. the browser notified me of this and i accepted the window popup to see the error.

after that i tried to fix the problem and try again and never again i could bring this popup up again. instead it signals with a short lived dialogue on the bottom right that the settings are saved (the 1st image i sent).

it's like i clicked on "Save" instead on "Not connected".

the difference is, with the Save button, that it won't leave the dialogue, while if i press Save it will and let me know the exact same feedback, that my credentials were successfully saved.

**Comment by mstelios** [comment]
is there a way for me to reset the relevant state on the backend? (mb delete something from the sqlite?) i tried restarting docker and upgrade to 0.95.1 from 0.94.1(this is where i created the problem but persists on the latest version as well).

**Comment by janober** [comment]
You can simply create totally new credentials with the same settings and delete the old ones. No need to reset anything manually.

But if the window does not appear it is probably browser-related (the only other time that should happen is when you already gave access and it connected successfully). So would look in Firefox again if it got blocked anyway or just try with another browser like Chrome.

**Comment by mstelios** [comment]
true, didn't manage to do it with firefox but edge was ok.

ty! for the guidance and your time!

closing this issue

**Comment by janober** [comment]
Happy to hear that it works now for you. Have fun!
