### ISSUE TITLE
Unable to write data to pgvector table with schema when collection is configured

### ISSUE THREAD

**Issue by Yao-sss** [n8n-io/n8n#12148]
### Bug Description

I am using pgvector store node to write data to DB, and I have configured collection, but when I specify schema, I get the following error. If I don’t specify schema, data can be written successfully. How should I solve this problem?

Error msg : Error adding column or creating index: syntax error at or near “.”

Detail error info :
Error: Error adding column or creating index: syntax error at or near “.” at PGVectorStore.ensureCollectionTableInDatabase (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules@langchain\community\dist\vectorstores\pgvector.cjs:690:23) at processTicksAndRejections (node:internal/process/task_queues:105:5) at Function.initialize (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules@langchain\community\dist\vectorstores\pgvector.cjs:332:13) at Function.fromDocuments (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules@langchain\community\dist\vectorstores\pgvector.cjs:727:26) at Object.populateVectorStore (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules@n8n\n8n-nodes-langchain\nodes\vector_store\VectorStorePGVector\VectorStorePGVector.node.ts:274:3) at Object.execute (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules@n8n\n8n-nodes-langchain\nodes\vector_store\shared\createVectorStoreNode.ts:308:7) at Workflow.runNode (C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-workflow\src\Workflow.ts:1382:8) at C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-core\src\WorkflowExecute.ts:1167:27 at C:\Users\xxx_user\AppData\Roaming\npm\node_modules\n8n\node_modules\n8n-core\src\WorkflowExecute.ts:1887:11

### To Reproduce

Select postgres pgvector store node, then use collection and enter the table name with schema

### Expected behavior

after run the workflow, will encountered error : Error adding column or creating index: syntax error at or near “.”

### Operating System

windows 10

### n8n Version

1.62.4

### Node.js Version

22.11.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Yao-sss,

We have created an internal ticket to look into this which we will be tracking as "N8N-7939"

**Comment by OlegIvaniv** [comment]
Hi @Yao-sss, it would help if you could provide a workflow to demonstrate this issue. Thanks!

**Comment by Yao-sss** [comment]
Hi @OlegIvaniv this is the template i'm using. thank for you help.

[issue_template.json](https://github.com/user-attachments/files/18161738/issue_template.json)

**Comment by OlegIvaniv** [comment]
> Hi @OlegIvaniv this is the template i'm using. thank for you help.
> 
> [issue_template.json](https://github.com/user-attachments/files/18161738/issue_template.json)

Thank you! 
Unfortunately, we don't support schema for PGVector table name yet. I've raised it as a feature request within the team. We'll post an update to this thread once it's implemented & released
