### ISSUE TITLE
HTTP Request node does not run when testing the node with pinned input

### ISSUE THREAD

**Issue by nmatton** [n8n-io/n8n#12162]
### Bug Description

I have a workflow with a previous node that has "pinned" output. When I test the entire workflow, the node functions as expected. However, when I make a change and test just that node (with the pinned data still present), it appears to run, but no output is generated. Additionally, the console shows no network activity.

### To Reproduce

1. Create a workflow with several nodes
2. Pin output on node before the HTTP
3. run the complete workflow, results are OK
4. run the HTTP request node again

### Expected behavior

I expect the same result as when running the complete workflow

### Operating System

Docker version (self-hosted)

### n8n Version

1.70.4

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nmatton,

We have created an internal ticket to look into this which we will be tracking as "N8N-7944"

**Comment by RicardoE105** [comment]
@nmatton could not replicate the issue in `1.73.1`. Can you please provide a sample workflow replicating the issue? Bellow the workflow I used for testing.

```
{
  "nodes": [
    {
      "parameters": {},
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        -620,
        -60
      ],
      "id": "b8ad407c-1f3e-478d-bba3-f5dcda39e74f",
      "name": "When clicking ‘Test workflow’"
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "b319441d-94a4-4982-87b8-04caae401289",
              "name": "todo",
              "value": "1",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.4,
      "position": [
        -400,
        -60
      ],
      "id": "352ff821-62f2-4a51-af20-c96f484bf19d",
      "name": "Edit Fields"
    },
    {
      "parameters": {
        "url": "=https://jsonplaceholder.typicode.com/todos/{{ $json.todo }}",
        "options": {}
      },
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.2,
      "position": [
        -180,
        -60
      ],
      "id": "cbae2ba5-1ff6-410d-89ce-5788673189e5",
      "name": "HTTP Request"
    }
  ],
  "connections": {
    "When clicking ‘Test workflow’": {
      "main": [
        [
          {
            "node": "Edit Fields",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "Edit Fields": [
      {
        "todo": "1"
      }
    ]
  }
}
```

**Comment by nmatton** [comment]
It seems to be working now. I encountered the issue in a different workflow with other nodes, which may have caused the failure. Since I'm still relatively new to n8n, I might have overlooked something. I apologize for the false report!
