### ISSUE TITLE
Unhelpful error message trying to activate "Workflow could not be activated: Validation Failed"

### ISSUE THREAD

**Issue by serkandurusoy** [n8n-io/n8n#12166]
### Bug Description

When I try to activate my workflow, I get this error message and then no further information. The workflow remains inactive.

Workflow could not be activated:
Validation Failed

I'm on latest stable version 1.71.2 as of now.

### To Reproduce

Go to activate and click on it.

### Expected behavior

Workflow activates.

### Operating System

Cloud

### n8n Version

1.71.2

### Node.js Version

cloud

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @serkandurusoy,

We have created an internal ticket to look into this which we will be tracking as "N8N-7946"

**Comment by serkandurusoy** [comment]
@Joffcom [this](https://github.com/n8n-io/n8n/issues/10074#issuecomment-2260132007) solved my problem.

I'm leaving the issue open as the solution is rather a clunky workaround that involves figuring out which node causes the issue and then deleting it to create a new one.

The upside is, the nodes to look at seems to be narrowed down to triggers with webhooks.
