### ISSUE TITLE
Pipedrive Custom Property Feature Disparity

### ISSUE THREAD

**Issue by MarleTangible** [n8n-io/n8n#12174]
### Bug Description

There is a feature disparity between Deal-Update and Organization-Update in Pipedrive node. It would be ideal if the users can select the custom property from a dropdown for all resource types. Only deal-update currently shows the list of custom properties.

### To Reproduce

1. Add a Pipedrive node and configure it to update a deal.
2. Add "Custom Properties" field and then click "Add Custom Property".
3. List of custom properties for deals are shown in the "Property Name or ID" field. 
4. Change the Resource to "Organization" and repeat the previous two steps.
5. Field name is updated to "Property Name" only and dropdown list is not shown.

Deal-Update (Awesome!)

![image](https://github.com/user-attachments/assets/8002f0ae-1ae8-489a-b223-faf59bcc83fa)

Organization-Update (Great but can be Awesome!)

![image](https://github.com/user-attachments/assets/913b4aaf-e884-413b-bda0-16afb091ed89)

### Expected behavior

The same feature set to be available for all resource types.

### Operating System

Debian 12

### n8n Version

1.70.3

### Node.js Version

20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MarleTangible,

This doesn't appear to be a bug and looks like it is a feature / enhancement request which would be better suited to the requests section of our support forum.

As this is not a bug I am going to mark this as closed but... I am going to keep the internal ticket open as I do think we should make sure the fields are the same.
