### ISSUE TITLE
Baserow Node: "Always Output Data" Not Returning All Items for Partial Matches

### ISSUE THREAD

**Issue by admdanielspalma** [n8n-io/n8n#12183]
### Bug Description

When using the Baserow node with the "Always Output Data" option enabled and feeding multiple items (e.g., 100 items) into it, the output does not include all input items if some are found and some are not. For example, if 50 records exist in the database and 50 do not, the node only returns the 50 found items, and the other 50 items do not appear in the output at all. The expectation is that all 100 items would be returned, with empty or null data for the non-found items.

### To Reproduce

1. Create a workflow that sends multiple items (e.g., 100 items) into a Baserow node.
2. Configure the Baserow node to perform a lookup on a database table and enable the "Always Output Data" option.
3. Run the workflow when you know that only a subset of those items (e.g., 50 out of 100) exist in the database.
4. Check the output of the Baserow node.

### Expected behavior

The Baserow node should return the same number of items as the input, providing data for the found records and empty (or null) values for the non-found records. In other words, if 100 items are input, the node should output 100 items, even if some are not found.

### Operating System

Ubuntu Server 22.04

### n8n Version

1.71.2

### Node.js Version

20.18.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @admdanielspalma,

We have created an internal ticket to look into this which we will be tracking as "N8N-7950"

**Comment by Joffcom** [comment]
Hey @admdanielspalma,

Always output data will make sure the node outputs something if there is nothing there what it doesn't do it output the exact amount of input items to handle that a merge node would be needed. It looks like we don't document this very well other than the help text when you hover.

> If active, will output a single, empty item when the output would have been empty. Use to prevent the workflow finishing on this node.

For now as this is intended I am going to mark this as closed but I will add this to an old feature request we have for tweaking this and I will make sure we get the docs updated to make this clearer.

Let me know if you have any questions on this.
