### ISSUE TITLE
Redis Chat Memory - "Context Window Length" not Working

### ISSUE THREAD

**Issue by klausgibin** [n8n-io/n8n#12193]
### Bug Description

The Context Window Length of the Redis Chat Memory is not working; it does not respect the interaction limit set as a restrictor.

### To Reproduce

1 - Create an AI agent and add Redis Chat Memory (also add a model and a calculator as a tool). 
2 - Set the context window length to 2. 
3 - Open the chat and say your name in the first iteration. 
4 - Make more than 2 random iterations with the agent.
 5 - Ask what its name is, it will respond. 

### Expected behavior

I expected it wouldn't know my name because I set the context window length to 2.

### Operating System

Debian 12

### n8n Version

1.67.1

### Node.js Version

18.16.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @klausgibin,

We have created an internal ticket to look into this which we will be tracking as "N8N-7952"

**Comment by OlegIvaniv** [comment]
@klausgibin I tried with tools agent and Redis chat memory with context set to 2 and could't reproduce this. Is it possible that LLM knew the name because it used it in some other iteration?

https://github.com/user-attachments/assets/f3f35051-9ba7-495a-961a-fb6d7c789c6f

**Comment by klausgibin** [comment]
Hi, I did the same test as you and I couldn't reproduce the error.
I think I did something wrong, I apologize for wasting your time.

**Comment by OlegIvaniv** [comment]
> Hi, I did the same test as you and I couldn't reproduce the error. I think I did something wrong, I apologize for wasting your time.

No worries! Glad to hear, that it works :)
