### ISSUE TITLE
ralfs

### ISSUE THREAD

**Issue by ralfscom** [n8n-io/n8n#12207]
### Bug Description

@

### To Reproduce

ne vienmēr var atrast 

### Expected behavior

we are going to be a little bit of the time to go to the point of the time and I will 

### Operating System

342

### n8n Version

43

### Node.js Version

5

### Database

MySQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @ralfscom,

We have created an internal ticket to look into this which we will be tracking as "N8N-7957"
