### ISSUE TITLE
HubSpot Get All + SupaBase Get All

### ISSUE THREAD

**Issue by samas-ai** [n8n-io/n8n#12213]
### Bug Description

When i tried to Get all contacts from Hubspot and Get all rows in Supabase, the Supabase returns 48000+ itens (in my hubspot i  have 239 contacts, and in mine Supabase i have 239 rows)
![Captura de tela 2024-12-13 101545](https://github.com/user-attachments/assets/eac0ef18-6269-4a94-bf9a-f6f97eae7c68)

### To Reproduce

1. Add Hubspot get many node
2. Add Supabase get many rows
3. Run

### Expected behavior

something like all the contacts and all the rows

### Operating System

Windows

### n8n Version

1.71.3

### Node.js Version

i dont know

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @samas-ai,

We have created an internal ticket to look into this which we will be tracking as "N8N-7958"
