### ISSUE TITLE
Slack Redirect URL not displayed

### ISSUE THREAD

**Issue by JVL1** [n8n-io/n8n#12228]
### Bug Description

I am looking for the redirect URL to add to the slack config but it's missing.   

Here is what it looks like before connecting
<img width="1202" alt="Screenshot 2024-12-13 at 1 24 05 PM" src="https://github.com/user-attachments/assets/0a90fb89-30de-4160-abc2-d854c3c9bd15" />
and here is after
<img width="1345" alt="Screenshot 2024-12-13 at 1 21 31 PM" src="https://github.com/user-attachments/assets/79399d82-dc86-48bf-810c-c2504990f4f5" />

This is what I'm expecting based on tutorials:

<img width="948" alt="Screenshot 2024-12-13 at 1 24 46 PM" src="https://github.com/user-attachments/assets/e81d728b-0925-4878-8f87-ff786e9a071d" />

### To Reproduce

I first used the API method to auth but then later the 0Auth 2 method.  I'm not certain that is what caused this issue

### Expected behavior

I can access the redirect URL

### Operating System

Mac 14.5 (23F79)

### n8n Version

1.70.4

### Node.js Version

NA I'm using the hosted version

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @JVL1,

We have created an internal ticket to look into this which we will be tracking as "N8N-7965"

**Comment by JVL1** [comment]
# Debug info

## core

- n8nVersion: 1.70.4
- platform: npm
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community
- consumerId: 00000000-0000-0000-0000-000000000000

## storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

## pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

## client

- userAgent: mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/131.0.0.0 safari/537.36
- isTouchDevice: false

Generated at: 2024-12-13T21:29:44.735Z

**Comment by Joffcom** [comment]
Hey @JVL1 

On Cloud we manage part of the credentials for some services to make life easier.

We normally mention this on the documentation page for the service, I will make sure we add this to Slack if it isn't there already but for now there is nothing to do just click connect and away you go.

As this is intended I am going to mark this as closed, let me know if you have any questions on this.
