### ISSUE TITLE
Error in youtube upload video node

### ISSUE THREAD

**Issue by Ejik007** [n8n-io/n8n#12231]
### Bug Description

When uploading a video to youtube (youtube node), the message "Request failed with status code 400" is displayed.
Node account connected with AOuth 2.

When I do the same actions in the cloud version, everything works.

 ```
n8n version

1.71.3 (Self Hosted)

Stack trace

AxiosError: Request failed with status code 400 at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:19:12) at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:599:11) at IncomingMessage.emit (node:events:531:35) at IncomingMessage.emit (node:domain:488:12) at endReadableNT (node:internal/streams/readable:1696:12) at processTicksAndRejections (node:internal/process/task_queues:82:21) at Axios.request (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/Axios.js:45:41) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.httpRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/NodeExecuteFunctions.js:776:18) at ExecuteContext.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/YouTube/YouTube.node.js:616:50) at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:741:19) at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:724:51 at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1155:20
```
When I do the same actions in the cloud version, everything works.
<img width="1170" alt="Снимок экрана 2024-12-14 в 15 49 08" src="https://github.com/user-attachments/assets/0fcb4fa9-6366-424c-85e0-287c644df63e" />
<img width="1663" alt="Снимок экрана 2024-12-14 в 15 50 10" src="https://github.com/user-attachments/assets/05f852da-ddd6-4d51-9a1b-3605d74994a7" />
<img width="1663" alt="Снимок экрана 2024-12-14 в 15 52 12" src="https://github.com/user-attachments/assets/be82af08-7f73-4020-b37a-f02e97ba21c6" />

### To Reproduce

1. Add http node request (Get file from https://vlizing.pro/1209.mp4 for example)
2. Add node youtube video upload:
3. Test step.

### Expected behavior

Video upload to YouTube is complete

### Operating System

Ubuntu 24.04.1 LTS

### n8n Version

 1.71.3 (Self Hosted)

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Ejik007,

We have created an internal ticket to look into this which we will be tracking as "N8N-7967"

**Comment by Joffcom** [comment]
Hey @Ejik007 

Can you set the `N8N_DEFAULT_BINARY_DATA_MODE` environments variable to `filesystem` and let me know if that helps.

**Comment by Ejik007** [comment]
It's working! Thanks for the help!

**Comment by neozbr** [comment]
had the same error and N8N_DEFAULT_BINARY_DATA_MODE environments variable to filesystem is not working...

**Comment by dbjpanda** [comment]
I have been getting same issue here. N8N_DEFAULT_BINARY_DATA_MODE is set to filesystem. It was working previously but getting issue since 15 days.
