### ISSUE TITLE
Slack request signature validation failed. [line 56, for item 0]

### ISSUE THREAD

**Issue by dustinhirner** [n8n-io/n8n#12233]
### Bug Description

![image](https://github.com/user-attachments/assets/43443f8a-0583-4a94-a0dc-adfab5101c2d)

Can't get my Webhook to Respond properly. Trying to properly validate the Slack request signature. 

My code used to work in previous versions of n8n or Slack... but, it breaks sometimes. Want it to work 100% of the time so I'm never concerned about this issue again.

### To Reproduce

You can't easily reproduce this unless you ask Slack a question... so it sends the Slack signature.

![image](https://github.com/user-attachments/assets/1b61cbb1-cd53-4118-ae29-8de9e947cd5d)

### Expected behavior

Slack should have the 'RPTS Property Tax Chatbot' respond with an intelligent answer from the embeddings database it is pulling from in supabase + ChatGPT LLM.

### Operating System

Windows 11 Home 22631.4602

### n8n Version

1.72.1

### Node.js Version

NA

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dustinhirner,

We have created an internal ticket to look into this which we will be tracking as "N8N-7969"

**Comment by Joffcom** [comment]
Hey @dustinhirner 

I am going to close this as it doesn't look like a bug with n8n and instead looks like it is an issue with the code you are using.

Can you create a topic on the [support forum](https://community.n8n.io) and complete the template there and we can take a look.

It would be useful if you can share the full workflow so we can check the code node as line 56 with the error is not visible, I suspect this could be a manually thrown error though.

Let me know if you have any questions or if you believe this is a bug with n8n itself.
