### ISSUE TITLE
Triggering a webhook with n8n URL autopauses the webhook automation in Notion, while the same flow works with Make.com

### ISSUE THREAD

**Issue by mundanewaves** [n8n-io/n8n#12257]
### Bug Description

When using the new Webhook functionality through database Automations in Notion, triggering the webhook automatically pauses the automation in Notion. I tested the same flow with a Make.com URL, and it works perfectly.

### To Reproduce

1. Go to Notion
2. Add Webhook automation
3. Trigger the webhook
4. Watch as the Automation gets paused in the Automations tab of your chosen database

### Expected behavior

Send the requested data through the webhook to n8n, just like it did to Make.com

### Operating System

Mac OS Sequoia - 15.1.1

### n8n Version

1.71.3

### Node.js Version

/

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mundanewaves,

We have created an internal ticket to look into this which we will be tracking as "N8N-7980"

**Comment by Joffcom** [comment]
Hey @mundanewaves 

Where are you getting the webhook url from that you are adding to Notion? We don't currently have a direct integration with Notion webhooks so I assume you are maybe adding a webhook node to a workflow? If this is the case are you using a test url or production url and do you have the webhook method set to Post?

**Comment by mundanewaves** [comment]
Yes, I’m using the webhook node

N8n build view
￼

Notion Automation build view

￼

After Automation gets triggered in Notion, it autopauses the automation like below.

￼

**Comment by mundanewaves** [comment]
Make.com produces data for the same workflow.

￼

**Comment by Joffcom** [comment]
Hey @mundanewaves,

Have you shared a screenshot as I can't see anything.

**Comment by mundanewaves** [comment]
Did not know emails were copied to here. 

<img width="1280" alt="PastedGraphic-1-1" src="https://github.com/user-attachments/assets/5b072d35-c73a-40dd-b87f-e70254442420" />
<img width="1200" alt="PastedGraphic-1" src="https://github.com/user-attachments/assets/0aee1cf8-2259-4bfa-900c-0dd85f9b9a7e" />
<img width="1191" alt="PastedGraphic-2" src="https://github.com/user-attachments/assets/5f393c83-bae9-46cd-bc9c-cd1215560ab4" />
<img width="395" alt="PastedGraphic-3" src="https://github.com/user-attachments/assets/2f199ccb-a85c-4ae9-ad1b-49fd738236f4" />

**Comment by Joffcom** [comment]
Hey @mundanewaves,

That is perfect, when you say it isn't working are you checking the execution log? It looks like it should be going through ok

**Comment by mundanewaves** [comment]
There are no execution logs in n8n. 
Just tried sending a webhook in a different way through a button. (In Notion)
Works to Make.com
Doesn't work to n8n

<img width="1246" alt="image" src="https://github.com/user-attachments/assets/63dd68bd-cfee-480e-a5c9-8aed48cb6010" />

**Comment by mundanewaves** [comment]
Extra info: I'm currently on the trial period, in case there are certain feature locks during this period.
