### ISSUE TITLE
Groq Chat Model requires enable cookies

### ISSUE THREAD

**Issue by horn1kube** [n8n-io/n8n#12250]
### Bug Description

When I try to send prompt via Groq Chat Model I get error:
```
403 Attention Required! | Cloudflare
Please enable cookies.
```

### To Reproduce

1. Create node AI Agent
2. Create and link Groq Chat Model node to AI Agent
3. Add API token to Groq Chat Model
4. Set any prompt in AI Agent
5. Start AI Agent node

### Expected behavior

Get success connection to groq chat

### Operating System

Windows 11

### n8n Version

1.71.3

### Node.js Version

22.11.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @horn1kube,

We have created an internal ticket to look into this which we will be tracking as "N8N-7977"

**Comment by OlegIvaniv** [comment]
@horn1kube Can you please elaborate on your environment? Are you self-hosting or using cloud version? I just tried on cloud with the same version and it works as expected 🤔 Are you using Cloudflare tunnels for your n8n instance by any chance?
![CleanShot 2024-12-17 at 16 37 39](https://github.com/user-attachments/assets/1981e61b-63e7-4a46-98c0-559197874fdf)

**Comment by horn1kube** [comment]
> @horn1kube Can you please elaborate on your environment? Are you self-hosting or using cloud version? I just tried on cloud with the same version and it works as expected 🤔 Are you using Cloudflare tunnels for your n8n instance by any chance? ![CleanShot 2024-12-17 at 16 37 39](https://private-user-images.githubusercontent.com/12657221/396563189-1981e61b-63e7-4a46-98c0-559197874fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NzYzNzgsIm5iZiI6MTczNDQ3NjA3OCwicGF0aCI6Ii8xMjY1NzIyMS8zOTY1NjMxODktMTk4MWU2MWItNjNlNy00YTQ2LTk4YzAtNTU5MTk3ODc0ZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDIyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYThlZGQwNDExODc0MzA2MTVkODgzOWUzYTRjNGMwYmFjYTU0MjhkODEzZjE1ZWMzOTRkNDQ1NWM0MGFiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6S9g3VpfNk_A7s-yqx-2pYQBWN86pUFq_ZL_Xl26hQE)

I have self-hosted n8n on Windows 11. And, yes, i use tunnel, but not cloudflared: i use cloudpub. I configured it via env WEBHOOK_URL. Does Groq Chat Model use tunnel?

**Comment by OlegIvaniv** [comment]
> > @horn1kube Can you please elaborate on your environment? Are you self-hosting or using cloud version? I just tried on cloud with the same version and it works as expected 🤔 Are you using Cloudflare tunnels for your n8n instance by any chance? ![CleanShot 2024-12-17 at 16 37 39](https://private-user-images.githubusercontent.com/12657221/396563189-1981e61b-63e7-4a46-98c0-559197874fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NzYzNzgsIm5iZiI6MTczNDQ3NjA3OCwicGF0aCI6Ii8xMjY1NzIyMS8zOTY1NjMxODktMTk4MWU2MWItNjNlNy00YTQ2LTk4YzAtNTU5MTk3ODc0ZmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDIyNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYThlZGQwNDExODc0MzA2MTVkODgzOWUzYTRjNGMwYmFjYTU0MjhkODEzZjE1ZWMzOTRkNDQ1NWM0MGFiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6S9g3VpfNk_A7s-yqx-2pYQBWN86pUFq_ZL_Xl26hQE)
> 
> I have self-hosted n8n on Windows 11. And, yes, i use tunnel, but not cloudflared: i use cloudpub. I configured it via env WEBHOOK_URL. Does Groq Chat Model use tunnel?

Then it sounds like an infrastructure issue that you need to resolve on Cloudpub side, seems like it's swallowing some cookies. As this is not directly tied to n8n, I'll close this issue.
