### ISSUE TITLE
TheHive Node - Alert Update keeps status: "New"

### ISSUE THREAD

**Issue by arkhelieldan** [n8n-io/n8n#1226]
**Describe the bug**
Using TheHive Nodes - Action: Alert Update Ignored, don`t work, keeping status as "New"

**To Reproduce**
1. Create The Hive Node 
2. Action Alert - Update
3. Define the ID of Alert
4. Status type: Ignored
5. Run the Node

**Expected behavior**
The alert triggered should be updated with the new status: Ignored, but keeps the "New".

**Comment by janober** [comment]
Very strange, can you think of any reason why that could happen @nadouani ? An issue with the API?

**Comment by mluhta** [comment]
Are you using TheHive 4? It seems to use different way of marking alerts as read (=ignored) internally, it doesn't PATCH the alert status, but sends a POST request to `/api/alert/<alert id>/markAsRead `. I would guess that updating the status still works with TheHive 3.

**Comment by arkhelieldan** [comment]
Sure @mluhta, i`m using TheHive4.

**Comment by nadouani** [comment]
Hello @arkhelieldan, There is no status `ignored` in TheHive 4. 

Let me take a look to what's the possible actions in the Node for TheHive 4 and I'll be back to you.

**Comment by mluhta** [comment]
> Are you using TheHive 4? It seems to use different way of marking alerts as read (=ignored) internally, it doesn't PATCH the alert status, but sends a POST request to `/api/alert/<alert id>/markAsRead `. I would guess that updating the status still works with TheHive 3.

PATCHing the alert status doesn't seem to work for TheHive 3 either. I'll update my PR #1255 to include Mark as Read operation for TheHive 3 too.

**Comment by Joffcom** [comment]
Hey there,

It looks like the change for this was released with n8n@0.112.0, Any objections to closing this one @mluhta @arkhelieldan?
