### ISSUE TITLE
The fn8n form trigger value path issue

### ISSUE THREAD

**Issue by malabbas** [n8n-io/n8n#12273]
### Bug Description

I have built a workflow with trigger using n8n form. The next node extract value correctly from the the form output. The issue with the last node, after IF node, doesn't extract value even though the value JSON path is correct !! it shows in gray font !!

### To Reproduce

Start a form trigger flow, make it 6 steps, and last step after an IF node. 

### Expected behavior

Retrieve value 

### Operating System

Ubunut

### n8n Version

1.25

### Node.js Version

18.16

### Database

MySQL

### Execution mode

own (deprecated)

**Comment by Joffcom** [comment]
Hey @malabbas,

We have created an internal ticket to look into this which we will be tracking as "N8N-7983"

**Comment by Joffcom** [comment]
Hey @malabbas 

If you are on 1.25 I would upgrade, can you also share a workflow that reproduces the issue.

**Comment by malabbas** [comment]
Sure, here it is:

See the video attached
 Screen Recording 2024-12-17 at 1.43.09 PM.mov
<https://drive.google.com/file/d/1_jGTqiCB8EyPTaKIT_G-_aQmnlHgpnG_/view?usp=drive_web>

**Comment by malabbas** [comment]
Hi,

Never mind, I got it fixed.

Thank you

**Comment by Joffcom** [comment]
@malabbas perfect I will mark this as closed.
