### ISSUE TITLE
Unable to active workflow

### ISSUE THREAD

**Issue by weiqingtao** [n8n-io/n8n#12299]
### Bug Description

I have a Trigger manually,but active button disabled
![image](https://github.com/user-attachments/assets/6150b521-a241-492e-881a-17ffd68121ce)

### To Reproduce

I have a Trigger manually,but active button disabled

### Expected behavior

I have a Trigger manually,but active button disabled

### Operating System

window

### n8n Version

1.72.0

### Node.js Version

v20.18.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @weiqingtao,

You can't enable a workflow that only has a manual trigger as there is nothing to start it from, For now I am going to mark this one as closed but I will raise this with our documentation team as maybe we can make this clearer in the docs.

Let me know if you have any other questions about this.
