### ISSUE TITLE
Unnecessary Increase in Token Consumption After Version 1.67.0

### ISSUE THREAD

**Issue by WilliamAlmeida** [n8n-io/n8n#12313]
### Bug Description

Starting from version 1.67.0 of n8n, I noticed behavior that causes an increase in token consumption during interactions with the AI model. Before this version (tested on 1.66.0), the tools associated with the agent were only sent when necessary, optimizing token usage. However, from version 1.67.0 onwards, the system began sending the description of all tools linked to the agent, even when not explicitly required, resulting in unnecessary token usage.

I would like to confirm whether this change was intentional or if it is a bug introduced in this update.

### To Reproduce

1. Set up an agent in n8n using version 1.66.0.
2. Send a simple input like "hi" to the agent and observe the token usage in the response.
3. Update n8n to version 1.67.0 or later (also tested on version 1.71.3).
4. Repeat the same test by sending "hi" to the agent and observe the token usage.
5. Compare the logs: in version 1.66.0, the tool descriptions are not sent with the initial input, while in version 1.67.0, they are sent automatically, significantly increasing the number of tokens used. In version 1.66.0, the AI can utilize the tools without needing the description of all associated tools to be sent each time, reducing token usage. Otherwise, it would make more sense to include the descriptions directly in the main prompt if they are always going to be sent.

**Version 1.66.0**

![version 1.66.0](https://github.com/user-attachments/assets/295eaaae-3324-4c08-863e-b401c114db68)

**Version 1.17.1**

![version 1.71.3](https://github.com/user-attachments/assets/2990101f-2b71-41b0-9631-2520ce7f9e13)

### Expected behavior

The expected behavior would be to maintain the optimization standard observed in version 1.66.0, where the tool descriptions are only sent to the model when necessary, saving tokens and avoiding additional costs.

### Operating System

Ubuntu 22.04.4 LTS

### n8n Version

1.66.0 - 1.72.1

### Node.js Version

20.18.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @WilliamAlmeida,

We have created an internal ticket to look into this which we will be tracking as "N8N-7993"
