### ISSUE TITLE
S

### ISSUE THREAD

**Issue by Akim2689** [n8n-io/n8n#12369]
## Please share your workflow/screenshots/recording

```
(Select the nodes on your canvas and use the keyboard shortcuts CMD+C/CTRL+C and CMD+V/CTRL+V to copy and paste the workflow.)
```

### core

- n8nVersion: 1.72.1
- platform: npm
- nodeJsVersion: 20.18.0
- database: sqlite
- executionMode: regular
- concurrency: 5
- license: community

### storage

- success: all
- error: all
- progress: false
- manual: true
- binaryMode: filesystem

### pruning

- enabled: true
- maxAge: 168 hours
- maxCount: 2500 executions

### client

- userAgent: mozilla/5.0 (linux; android 10; k) applewebkit/537.36 (khtml, like gecko) chrome/125.0.0.0 mobile safari/537.36
- isTouchDevice: true

Generated at: 2024-12-25T19:03:47.907Z}

**Comment by Joffcom** [comment]
Hey @Akim2689,

We have created an internal ticket to look into this which we will be tracking as "N8N-8010"
