### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Grimgog** [n8n-io/n8n#12392]
### Bug Description

I've setup n8n with docker and docker-compose and this is what docker logs is saying:

`(node:7) [EISDIR] Warning: Error
module: @oclif/core@4.0.7
task: findCommand (audit)
plugin: n8n
root: /usr/local/lib/node_modules/n8n
code: EISDIR
message: EISDIR: illegal operation on a directory, read
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)`

### To Reproduce

1. docker-compose a standard docker-compose yaml like:

services:
  n8n-ssl:
    image: n8nio/n8n
    container_name: n8n-ssl
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=your-usr
      - N8N_BASIC_AUTH_PASSWORD=your-pw
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=https://your.domain
      - WEBHOOK_URL=https://your.domain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-ssl.rule=Host(`your.domain`)"
      - "traefik.http.routers.n8n-ssl.entrypoints=websecure"
      - "traefik.http.routers.n8n-ssl.tls.certresolver=myresolver"
      - "traefik.http.services.n8n-ssl.loadbalancer.server.port=5678"
    ports:
      - "5678:5678"
    volumes:
      - "/usr/n8n/config:/home/node/.n8n/config"
      - "/usr/n8n/database.sqlite:/home/node/.n8n/database.sqlite"
    networks:
      - your-network
    restart: always

networks:
  your-network:
    driver: bridge
    external: true

2. check docker logs

### Expected behavior

n8n should run out of the box

### Operating System

Debian 12.8

### n8n Version

latest docker image

### Node.js Version

latest docker image

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Grimgog 

Can you try following one of our documented install guides, you are using options that have not been valid for over a year. 

The error is likely to be down to the volume permissions so you could also make sure the .n8n path is owned by the node user and group or uid / guid 1000

As this is not a bug and an installation issue I am going to mark this as closed for now.

**Comment by Grimgog** [comment]
Thanks for that, I'm looking int othe new guides.
I was afaik just using old docker-compose yaml of myself from another "older" version of n8n
