### ISSUE TITLE
Gitlab OAuth authentication with custom URL open gitlab.com

### ISSUE THREAD

**Issue by Armaldio** [n8n-io/n8n#1243]
**Describe the bug**
When using the Gitlab Oauth credentials and using a custom domain, when clicking on the button to authenticate open on `https://gitlab.com/xxx` instead of the URL I have defined

**To Reproduce**
1. Add a custom URL to the Gitlab OAuth credential
2. Try to login

**Expected behavior**
I'm able to Authorize the request because the URL match the one I entered

**Environment (please complete the following information):**
 - OS: Windows10
 - n8n Version 0.96.0
 - Node.js Version The one in the Docker

**Additional context**
I'm running through Docker

**Comment by janober** [comment]
Thanks a lot for reporting this issue.

Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.98.0
