### ISSUE TITLE
Ubuntu Docker images show as Debian Stretch

### ISSUE THREAD

**Issue by weslambert** [n8n-io/n8n#1250]
**Describe the bug**
Docker images tagged with Ubuntu (also in the Dockerfile) are using Debian Stretch instead of Ubuntu.

**To Reproduce**
1. Download Docker image, run it, and `cat /etc/os-release` inside of container.

**Expected behavior**
`cat /etc/os-release` should produce output detailing an image relating to a version of Ubuntu, not another Debian variant.

**Environment (please complete the following information):**
 - Using Docker on top of Ubuntu Linux 18.04
 - n8n Version 0.97.0
 - Node.js Version 12.19

**Additional context**
https://hub.docker.com/layers/n8nio/n8n/0.97.0-ubuntu/images/sha256-f55491c672a42b54bf89ad0d832ace17e2d8da967c616e7cb898be29a3100d98?context=explore
https://github.com/n8n-io/n8n/blob/master/docker/images/n8n-ubuntu/Dockerfile

**Comment by weslambert** [comment]
@janober Any thoughts on this?

**Comment by janober** [comment]
Thanks a lot! Yes, you are correct. Just checked the output and also the description of the image. It is actually Debian and not Ubuntu based.

Renamed it. Starting from the next version will the name correctly be `-debian`.
