### ISSUE TITLE
Different results when executing single node vs full workflow (HTML extraction issue?)

### ISSUE THREAD

**Issue by MaciejGorczyca** [n8n-io/n8n#1256]
**Describe the bug**
Different results when executing single node vs full workflow. Happens with HTML extraction before function. Does not happen with the same data set in set-nodes before function.

When you execute node, there are no properties added to item objects. Example:

```
{ title: "Wikipedia:Today's featured article/December 2020" }

{ title: 'mail:daily-article-l', class: 'extiw' }

{ title: 'Wikipedia:Featured articles' }
```

When you execute full workflow, the first and last items will get new property called "class" which is the same property item number two has. They will be undefined but they are here.

```
{

title: "Wikipedia:Today's featured article/December 2020",

class: undefined

}

{ title: 'mail:daily-article-l', class: 'extiw' }

{ title: 'Wikipedia:Featured articles', class: undefined }
```

Notice the multi-line console.log output. I assume the n8n does something under the hood when you run full workflow compared to when you run a single node.

I checked this behavior in a new workflow by preparing data in set nodes BUT everything was working alright and as intended. Which makes me think that the HTML extraction is the culprit and not the engine/lower-level logic.

**To Reproduce**
Run the attached workflow. Check upper function output and compare it to the lower function output. Re-run bottom function node by opening it and clicking the execute-node button.

**Expected behavior**
Items without property don't get that property during HTML extraction attached with "undefined" value. Running `item.json.hasOwnProperty("class")` should return false-true-false instead of true-true-true. The output data should stay the same no matter if you run a single node or full workflow.

**Environment (please complete the following information):**
 - OS: Windows 10, run in Docker
 - n8n Version 0.98.0
 - Node.js Version v12.19.1

**Additional context**
I tried to look briefly for the issue but didn't find anything related.

Please check the attached workflow to quickly see the issue. Connect start to the first noop node. As to why it happens, check console.log - you will see "class" property added when running workflow and no property when running node alone.

[test_bug.txt](https://github.com/n8n-io/n8n/files/5706612/test_bug.txt)

Quick gif view:

![PeDNRtdZo5](https://user-images.githubusercontent.com/26925976/102449383-6c09f100-4034-11eb-8960-e7a73bb7b36c.gif)

**Comment by RicardoE105** [comment]
@MaciejGorczyca thanks for putting that together. If you change $items() for items then it should work fine. However, in my mind it should work with $items() as well. This is definitely weird. Will investigate, in the meantime you can fix it by making the change I previously mentioned.

**Comment by janober** [comment]
Looking at it makes actually sense.

The reason is that when the workflow executes it passes around JavaScript Objects. Such an Object can have properties which are `undefined`. So if you check via `hasOwnProperty()` it will return `true`. Because it exists but it has the value `undefined`. So that is why it returns correctly `true` for all three.

When the data then gets saved in the database or send to the frontend, it gets converted to JSON (via `JSON.stringify`). In JSON a property that is set to `undefined` it will not be saved.
If you then manually execute the last node again from the frontend, it sends all the data it has (the JSON-data without the properties which are undefined) to the backend and executes it. The properties will then not be there anymore and so your `hasOwnProperty` will resolve to `false`.

A actually try to avoid `hasOwnProperty` for a long time. Instead of: `item.json.hasOwnProperty("class")` do I use for example `!!item.json.class`. If you do that it will work identical both times.

Can not think of a good way to make that more consistent except always stringifying all data before it hits a node. That would, however, not just increase memory usage, it would also make n8n much slower. For that reason do we simply have to live with that inconsistency here. Sorry. Hope that makes sense.

**Comment by MaciejGorczyca** [comment]
It makes sense, yes, thanks.

I would like to understand why the upper branch works fine while the bottom branch doesn't when executing full workflow. The input data is prepared and exactly the same in both cases. Is the data from HTTP request or HTML extract handled differently than set node? The only thing I can think about is that set node will set exactly what we set in it while HTML extract will extract the fields/values we want or set them to undefined if they are not found. If that's the case, I think the property should be simply deleted instead of setting it to undefined.

I'm also a bit confused when it comes to `items` and `$items()` - I assume the first references the variable items and the other is a function that returns items. Is using `items` whenever we can better than calling `$items()` for that reason? We get the data directly with `items` while `$items()` returns the result of stringify? (which is slower for that reason)

I think we should then adjust docs and use `items` instead of `$items()`, [for example here](https://docs.n8n.io/reference/javascript-code-snippets.html#_2-create-a-single-item-from-multiple-items). Overall I'm slightly confused about variables because snippets page has both `$items()` and `items`, meanwhile expressions page has listed lots of $... variables but the first snippet uses `items[]` and `return items`. The tool is really great but it gets confusing sometimes and docs don't explain things fully.

**Comment by janober** [comment]
Ah no, they are not exactly the same.
In the upper one you specifically just create the properties. So only that ones exist.
In the lower one you use the "HTML Extract" Nodes which use cheerio to extract data. Cheerio adds always the "class" property but if the element does not have classes it sets it to `undefined`.

`$items()` and `items` should be totally identical if called like this. Both of them are JSON stringified. All data that gets used in the Function-Node is, else it would mess up the data for other nodes.

If you are in the Function-Node and you want to access its current items you should by default always use `items`. Only if you want to access data from other nodes normally `$items("node-name")`. But again, data is identical so if somebody prefer that it would also be fine. Here the documentation about `$items`:
https://docs.n8n.io/nodes/expressions.html#method-items-nodename-string-outputindex-number-runindex-number

Yes totally agree. The documentation there should be adjusted and will in the next days.

The variable `items` only exists in the Function-Node. The method `$items` exists both in Function-Node and Expressions. 

Yes agree that the documentation is still not perfect there and in many other regards. For that reason does it get improved and extended on almost a daily basis. Making it clearer what is available where is one thing that is still on our To-Do list.
