### ISSUE TITLE
Properties that depend on other properties

### ISSUE THREAD

**Issue by Narretz** [n8n-io/n8n#126]
Hi,

sometimes the value(s) of a node property are dependant on the value of another node property. For example in Asana, there exist both "Workspaces" and "Projects". In the existing Asana integration, https://github.com/n8n-io/n8n/blob/af5c7e75fac8ed23ac01e77baed9ecdf09e93055/packages/nodes-base/nodes/Asana/Asana.node.ts, the workspaces are loaded with loadOptions (works well), but there is no property for "project". Now I tried to add it, but it's not that easy, because in order to get the relevant project ids, you need the workspace id.

So there needs to be a way to mark a node property as dependant on another property. If property B is dependant on A, then if A changes, the loadOptions function is called (again). I realize that this is not trivial, as you need to check depth of depdency / circular dependency etc., but it's quite necessary in my opinion.

**Comment by janober** [comment]
@Narretz Thanks a lot! I agree that this would be a very important feature. Can you, however, please post it in the forum here:
https://community.n8n.io/
as described in the issue template.

Github issues should really only be created to report bugs and not for questions or feature requests. They should all be collected in the forum to have them all in one spot. If we have them here and there things start to get messy. Thanks a lot!

So are closing this issue.

**Comment by Narretz** [comment]
Oh okay. Then ou should really remove "Feature Request" from the list you see in  "New Issue". It doesn't make any sense to list "Feature Request" there just to tell you in the template that you shouldn't open a Feature Request.

**Comment by janober** [comment]
I actually disagree there. I added it on purpose. Because if it would not be there, people would not know where to post feature requests to. Then they would either not add it at all and leave or they would simply select anything else and post it here anyway.

By having the "Feature Request" option I have at least the chance to guide the people. They click on it, read what the template says and then post it to the forum.

**Comment by Narretz** [comment]
But it's sending a confusing message. People often don't read the template texts. Or if they do, they might be confused by the fact that the feature request template is telling them not to open a feature request. I was in fact, and though this was an error. Because why would the option for Feature Request tell me not to open one?
This could probably be improved by re-wording the "name" and the "about" of the issue template.

**Comment by Narretz** [comment]
It looks like you can redirect users to an external site instead of prompting them to open a blank issue: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository 

I think this is the better solution.

**Comment by janober** [comment]
Thats great, thanks a lot! I was not aware of that. Got changed.
