### ISSUE TITLE
getInputData should always clone data

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#1264]
**Describe the bug**
Currently nodes can modify input data that are recieved by `getInputData()`.

**Expected behavior**
It should be ensured that a node cannot change the input data.
`getInputData()` should always return clone of the input data to be safe and consistent.

**Environment (please complete the following information):**
 - n8n Version 0.98.0

**Additional context**
Mostly important for community based nodes.

**Comment by janober** [comment]
Yes, that is like that on purpose. It is on the node creator to make sure that they do not change the incoming data.

Here the information about that in the documentation:
https://docs.n8n.io/nodes/creating-nodes/create-node.html#do-not-change-incoming-data

Background is that cloning the data is not just incredible slow it makes the memory usage of n8n explode. Currently, it always passes around references which makes it very fast and memory efficent.

**Comment by lublak** [comment]
Hmmm okay. Thenthe  behavior shouldn't be changed to be efficient.

**Comment by janober** [comment]
Originally (before I publicly released n8n) I had it actually working as you proposed. But that caused problems very fast and so then adjusted the behavior and changed all the nodes to work as documented above. So also my intuition was like yours.

Thanks a lot for helping to make n8n better!
