### ISSUE TITLE
Persist result data / set data manually / import data from previous runs

### ISSUE THREAD

**Issue by Narretz** [n8n-io/n8n#127]
This is a bit of a broad topic, but essentially it's about setting the data in a workflow during development.
The biggest problem I have right now, is that the data of a workflow execution is lost after I refresh the editor / or go to another section, and if I'm using a webhook, I first have to execute the workflow / node again, even though I have execution data from previous runs. So there should be an option for each node / the whole workflow to import / restore data from previous runs (if it matches the nodes ofc). Ideally there should also be an option to import data manually for testing. Sure, you have to make sure that the data is valid, but sometimes pasting data manually is easier than triggering an external event.

**Comment by janober** [comment]
@Narretz Thanks a lot! I also agree here that it would make sense but can you please also post that in the forum here:
https://community.n8n.io/
as described in the issue template.

Github issues should really only be created to report bugs and not for questions or feature requests. They should all be collected in the forum to have them all in one spot. If we have them here and there things start to get messy. Thanks a lot!

So are closing this issue.
(Sorry more or less same text as in #126)
