### ISSUE TITLE
XAmzContentSHA256 Mismatch in S3 node

### ISSUE THREAD

**Issue by sesa-me** [n8n-io/n8n#1278]
**Describe the bug**

Uploading multiple files using the S3 node results in an SHA256 error. 

This issue was fixed for the AWS S3 node in 0.86.0 in PR #1011 but the same fix should be applied to the S3 node as well. 

The original issues related to the AWS S3 node are:

https://community.n8n.io/t/xamzcontentsha256mismatch-when-passing-more-than-one-item-to-the-aws-s3-node/2582
https://community.n8n.io/t/error-on-copying-files-from-gmail-to-s3/2537

The issue is fixed simply by making the same changes as PR #1011 to the S3 node.

**Comment by janober** [comment]
Thanks a lot for the info @sesa-me! Got also applied and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.100.0
