### ISSUE TITLE
Amqp Trigger starts all Workflows with Amqp Trigger

### ISSUE THREAD

**Issue by erbg** [n8n-io/n8n#1284]
We have two different Workflows that listens on a AMQP Topic on different Subscriptions.
When we get a new Message in one of the Subscriptions both Workflows starts. 

It seems as if the Trigger node shares the same instance of ITriggerFunctions.

Create 2 Workflows with a AMQP Trigger on different Subscriptions.
Launch a message on one Subscriptions
Both Workflows will start

**Expected behavior**
Just the Workflow with the Subscription Trigger should start.

**Comment by erbg** [comment]
@janober : Can you help me? I would like to implement an asyncron Delivery -> Accept message flow for AMQP - So that a message can be rejected if the n8n Workflow throws an error. 

The RHEA on_message event passes a delivery Object on which you have an "Accept" or "Reject" method. Do you see any posibility to passa reference to this object in the Workflow so that we can create a second node for Accepting or Rejecting the message on the bus? 

Thanks

**Comment by janober** [comment]
No, sorry that is sadly not possible. Currently, n8n only supports passing around data as JSON, it is not build to handle objects.

**Comment by erbg** [comment]
I immaged that, would it be possible to have a callback event when the workflow finishes or similar? In this case we could get the trigger and accept the message on the end of the workflow.

**Comment by atakchidi** [comment]
We have the exact same issue, almost all workflows are based on amqp so we are kinda struggling, for now I solved this by putting an "IF" node after each trigger that check fro proper message type

**Comment by janober** [comment]
@erbg No sorry such a callback does currently not exist and we would have to think about properly how something like that should be implemented to be as useful for as many cases as possible.

@atakchidi The issue got fixed by @erbg. I did just check the PR, made some changes, and merged. Will be released with the next version.

**Comment by janober** [comment]
Fix got released with n8n@0.103.1
