### ISSUE TITLE
node-redis undefined argument deprecation with v2.8.0 and error from v3+

### ISSUE THREAD

**Issue by immanuelfodor** [n8n-io/n8n#1295]
**Describe the bug**
This is not a bug yet, just a warning message, but will be a bug/error after `node-redis` is upgraded from the current 2.8.0 version to 3.0.0+. This is why I think this should be here as an issue and not as a thread in the community discussion. Please feel free to close if you think otherwise.

Docker compose logs when using the Redis node in a workflow:

```
n8n      | node_redis: Deprecated: The TYPE command contains a "undefined" argument.
n8n      | This is converted to a "undefined" string now and will return an error from v.3.0 on.
n8n      | Please handle this in your code to make sure everything works as you intended it to.
```

**To Reproduce**
1. Get data from Redis. I have multiple nodes for key search, get key (automatic type), set keys, so I'm not sure which one causes it or it's just enough to have a Redis node in a project. When I ran the workflow with just the key search attached, it resulted in the same logs as when all the nodes were running, no multiple warnings, just once per run. So it might be enough to just have a Redis node included in the workflow.
2. Check the Docker logs
4. See the above logs

**Expected behavior**
There are several issues in other projects on Github for related deprecations with `HSET`, etc. and they say the `undefined` (wherever is passed) is needed to be replaced with `null` to solve this. I just did a quick Google search, not an expert in this. 

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version: 0.100.0
 - Node.js Version: Docker version

**Additional context**
There have been already a dependency upgrade request that was closed which avoided getting an error for this deprecation: https://github.com/n8n-io/n8n/pull/559

Current node-redis version: https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/package.json#L552

Changelog of the node-redis package: https://github.com/NodeRedis/node-redis/blob/master/CHANGELOG.md

**Comment by krynble** [comment]
Hey @immanuelfodor

Sorry for the late response. The library has been upgraded here: https://github.com/n8n-io/n8n/pull/1655

The warnings should not be happening anymore. Please let us know if you have similar issues or the error persists, but before merging we did a lot of testing and everything was working fine.
