### ISSUE TITLE
Start with tunnel : what about privacy ?

### ISSUE THREAD

**Issue by thomasleveil** [n8n-io/n8n#13]
I have not dug into the source code to try to figure out what this tunnel feature does under the hood, but the question that arose when I read this chapter was : **which server ?**

It would be great if you could develop the documentation for [Start with tunnel](https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/README.md#start-with-tunnel) so that we can understand if our data can be seen or stored anywhere on your server when using the tunnel feature.

A schematic explaining how things are connected together would be very helpful

**Comment by janober** [comment]
It is actually only ment for local testing and development (to get a n8n instance web accessible fast and simple). It is definetly not ment to be used in a production setup and even less with any kind of sensitive data. 

You are right! I definetly have to make that very very clear, what it is currently not, as I did not mention that at all. Somehow just totally wrongly assumed that this is clear as sending all your data through a server that is not yours sounds already bad ;-)

Just fyi what code is behind the tunnel. It is an own instance of this:
https://github.com/localtunnel/localtunnel

**Comment by janober** [comment]
Ok added it to documentation and CLI option description. Thanks for making me aware of that!
