### ISSUE TITLE
Updated Credentials not getting reflacted

### ISSUE THREAD

**Issue by pratikgajjar** [n8n-io/n8n#1315]
**Describe the bug**
Pretext
We have configured an API request block which uses Header based credentials
These credentials expire every week
We update cred manually. 
Test workflow -> It's working fine.
Issue:
When workflow gets executed by CRON block - It's fails due to authentication in API Request block.
Meaning when we update the credentials they don't get updated for the same workflow which gets executed by cron job. 

**To Reproduce**
1. Create A Workflow with CRON - Use API request block with Some Auth Header
2. Update the Auth Header credentials
3. Monitor request done by cron block. It will have older auth details

**Expected behavior**
Workflow executed by cron shouldn't fail

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n 0.91.0
 - Node.js Version v12.19.0

**Additional context**

**Comment by krynble** [comment]
Hey @pratikgajjar 

Sorry for the late response. A fix is on the way but considering this will be a breaking change, we're waiting for the best moment to release.

You can see the pull request and follow up on progress here: https://github.com/n8n-io/n8n/pull/1741

**Comment by pratikgajjar** [comment]
Hi @krynble ,
  Thanks for the revert. I didn’t understand this part in your pr.

> keeping tokens in memory n8n refreshes tokens too many times.

Problem is that workflow never refreshes the credentials even if they gets updated. Anyway fetching cred from DB should solve this problem.

**Comment by krynble** [comment]
Hey @pratikgajjar

That comment relates specifically to OAuth tokens that were not getting updated and possibly being refreshed multiple times.

My PR relates OAuth tokens but as a side effect the issue you are having should also be solved.

**Comment by pratikgajjar** [comment]
Agreed

**Comment by janober** [comment]
Fix got released with 0.135.0

**Comment by Harikarthyk** [comment]
I am getting the same issue again. The n8n version used is 0.195.5.

I am using HubSpot OAuth for some HTTP requests. When I execute the workflow, everything is good. But when I make it active for 30 minutes, it is fine, but after the OAuth expires, the HubSpot node gets executed, but the HTTP request, which uses the same authentication, is not working.
