### ISSUE TITLE
[bug] node collection parameter same name

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#1318]
**Describe the bug**
Currently some issues with invisible input fields:
![89F3SIxpzj](https://user-images.githubusercontent.com/44057030/103764421-b969f480-501b-11eb-957c-7566689f8339.gif)
Based on the draft: https://github.com/n8n-io/n8n/pull/1313

**To Reproduce**
Have a node with a collection with options that use the same name with different displayOptions.

**Expected behavior**
The same behavior like directly in root.

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version:  0.100.0 
 - Node.js Version: v14.15.1

**Comment by RicardoE105** [comment]
Thanks for letting us know. Was able to replicate the issue. In the meantime, you can just change the name and it should work.

**Comment by lublak** [comment]
@RicardoE105 should i change the draft? Because the additions to SpreadsheetFile helps us. Internal we use other names for each entry or merge the information to one option (like instance of Sheet name to read, Sheet name to write => Sheet name to read or write)

**Comment by janober** [comment]
This bug got fixed a while ago. Sadly do not remember exactly in which version. So close this issue. Thanks again for reporting!
