### ISSUE TITLE
Gmail node with HTML send option has false requirement

### ISSUE THREAD

**Issue by Adrian-Samuel** [n8n-io/n8n#1326]
Hey!

So with the new version of n8n, you are able to send HTML via the Gmail Node.
However the HTML is meant to be an option instead of the plain text option. You can't have both. However if you remove the contents of the "message" field in the UI/JSON then the flow won't save or work.

Whatever you put in the message field doesn't get sent, but the node won't let you execute it unless you fill it out.
This is most clearly a bug.

An example flow can be found here:

```json
{
  "name": "Test Email Flow",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        520,
        300
      ]
    },
    {
      "parameters": {
        "resource": "message",
        "subject": "Testing",
        "includeHtml": true,
        "htmlMessage": "<!DOCTYPE html>\n<html>\n<body>\n  \n  <h1> Some Email Title </h1>\n  \n</body>\n</html>",
        "toList": [
          "your_email@gmail.com"
        ],
        "additionalFields": {}
      },
      "name": "Gmail",
      "type": "n8n-nodes-base.gmail",
      "typeVersion": 1,
      "position": [
        280,
        240
      ],
      "credentials": {
        "gmailOAuth2": "Some Credentials"
      }
    }
  ],
  "connections": {},
  "active": false,
  "settings": {
    "saveManualExecutions": true
  },
  "id": "2"
}
```

The ideal behaviour would simply be that the UI message field gets removed when the HTML option is selected
<img width="1172" alt="Screenshot 2021-01-10 at 17 45 55" src="https://user-images.githubusercontent.com/31516988/104131019-d2e8a480-536b-11eb-8d03-6af11091e4f9.png">

**Comment by janober** [comment]
That is actually not correct. Both versions do get send:
![Screenshot from 2021-01-08 07-48-12](https://user-images.githubusercontent.com/6249596/104132073-65dd0b00-537b-11eb-8775-14332f443332.png)

Will probably display one or the other depending on the device. So I guess if the device does not support HTML it will fall back to the text version. So both should be set. So would at a pure minimum write something like "HTML support is needed to display message".

Hope that makes sense.
