### ISSUE TITLE
HTTP request follow redirects option does not work 

### ISSUE THREAD

**Issue by matt-laird** [n8n-io/n8n#1331]
**Describe the bug**
When the option "Follow HTTP 3xx redirects" is selected (it is by default), the request does not get redirected when a status code 3xx is received. 

**To Reproduce**
1. Create HTTP Request node.
2. Point to endpoint that you know requests 3xx status.
3. Submit request.
4. Observe Status code error returned.

**Expected behavior**
When an HTTP status code in the range of 3xx is received in the request chain, the client should respect the redirect and follow the navigation expected for redirection.

**Environment (please complete the following information):**
 - OS: Raspbian Linux 10 - Docker Container
 - n8n Version: 0.100.0-rpi (Experienced the issue on previous versions as well)
 - Node.js Version: v12.19.1 (pre-installed in Image)

**Additional context**
![image](https://user-images.githubusercontent.com/14907718/104343731-fa26a980-5504-11eb-87b4-126ca335f097.png)

**Comment by mutdmour** [comment]
thank you @matt-laird for the report. I created a PR here https://github.com/n8n-io/n8n/pull/2046 to add an option to follow all redirects.

**Comment by janober** [comment]
Fix got released with n8n@0.133.0
