### ISSUE TITLE
Google Sheet Node Update Operation not working

### ISSUE THREAD

**Issue by Adrian-Samuel** [n8n-io/n8n#1336]
Bug Report: 
I should be able to set some data, specify they matching key, the sheet range of the given sheet and have the keys for the respective column(s) updated on that given row. However, nothing happens besides a success message.

Here is an example sheet. This screenshot is found on Sheet2
<img width="495" alt="Screen Shot 2021-01-13 at 2 21 33 PM" src="https://user-images.githubusercontent.com/31516988/104464273-a5d60500-55aa-11eb-9145-e20eb7b10347.png">

Here is my workflow

```json
{
  "name": "Test update",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "operation": "update",
        "sheetId": "1dBZfMQBMPYsUXcAqRmR3aVIp10ilC5O2wbXvupYR6tM",
        "range": "Sheet2!A:B",
        "key": "ID",
        "options": {
          "valueInputMode": "USER_ENTERED",
          "valueRenderMode": "UNFORMATTED_VALUE"
        }
      },
      "name": "Google Sheets",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 1,
      "position": [
        650,
        450
      ],
      "credentials": {
        "googleApi": "Sheet Credentials"
      }
    },
    {
      "parameters": {
        "values": {
          "number": [
            {
              "name": "ID",
              "value": 2
            }
          ],
          "string": [
            {
              "name": "Email",
              "value": "Adrian"
            }
          ]
        },
        "options": {}
      },
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        450,
        450
      ]
    }
  ],
  "connections": {
    "Set": {
      "main": [
        [
          {
            "node": "Google Sheets",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "saveManualExecutions": true,
    "executionTimeout": -1
  },
  "id": "9"
}
```

I try to then execute this sheet and nothing changes, nothing is appended. Every other operation works perfectly (lookup, read, clear, delete). I've simply never been able to do anything with "update". I believe there is a bug.

I have followed this verbatim: https://docs.n8n.io/nodes/n8n-nodes-base.googleSheets/#example-usage

Here's a full-page screenshot showing the output on the right from the node, but no change on the left from the node

<img width="1789" alt="Screen Shot 2021-01-13 at 2 36 58 PM" src="https://user-images.githubusercontent.com/31516988/104466299-f9e1e900-55ac-11eb-8561-9415c8d90291.png">

**Comment by janober** [comment]
Can you please try to set "ID" as a string. Because the data gets returned from the Sheet as a string. As you currently set ID as number and `2 !== '2'` it is probably not able to match them.

**Comment by Adrian-Samuel** [comment]
Hey @janober! This works! This makes sense now everything is turned into a string, I thought it inherited the type as set by the cell.

Another thing I've noticed. If I manually edit a row in the google sheets UI, that specific record might not be updatable again via the Update Node, even after changing the options to UI edited.

**Comment by janober** [comment]
Glad to hear that it works now.

About the second part. Can currently not see a way how that is possible unless Google does return the data then differently or not at all anymore. What do you mean with "even after changing the options to UI edited"?

**Comment by Adrian-Samuel** [comment]
Ah this was my bad! I didn't at first understand how to view the types by using the "Formatted" option and thus I could only see strings returned.

So my issue was that I was attempting to update a value in the spreadsheet with a string value when it's type was an int.
It would be nice if you could specify an option to "force" match a value to be updated by its corresponding type.

Thank you for your help and assistance! It took more playing around with the google sheet API and then coming back to see what the purpose of all the options were.

**Comment by sanebg** [comment]
I'm having the exact same issue. Can someone tell me how to set the ID as a string? I'm not a coder and I have no idea what that even means.
