### ISSUE TITLE
Please add support for telgram

### ISSUE THREAD

**Issue by vicdorke** [n8n-io/n8n#135]
I need to send multiple pictures at once, now your api only supports sending one picture at a time

**Comment by janober** [comment]
It looks like the `sendPhoto` endpoint does not support sending multiple files. Am I asuming correclty you are refering to [`sendmediagroup`](https://core.telegram.org/bots/api#sendmediagroup)?

**Comment by vicdorke** [comment]
yes, i hope use sendmediagroup?

**Comment by janober** [comment]
Got added and released with n8n@0.39.0
