### ISSUE TITLE
IF node stops further execution if there are two inputs for next node

### ISSUE THREAD

**Issue by MaciejGorczyca** [n8n-io/n8n#1351]
**Describe the bug**
To understand the issue, here is the scenario we are looking at: Assume that we got our data and found that there are elements that we want to process. We go to true path, process elements then continue with nodes that should be always executed. If there are no elements that we want to process, we skip processing elements and go to the false path that should always be executed.

The issue lies in the fact that if you connect to node multiple inputs and at least one of them has no results, the node won't get executed AT ALL. Here is the screenshot of the scenario I'm talking about:

![2021-01-18-08-08-53-476-1003x432-n8n_-_▶️_—_Mozilla_Firefox](https://user-images.githubusercontent.com/26925976/104883407-011a4580-5965-11eb-8968-8e4ac083046f.png)

When we go to do the true path and process our data, everything is okay until we reach the "common" route. Because if returns results for true and returns nothing for false, the merge won't be executed AT ALL. After processing data I need the results from the function again, that's why I merge nodes and pass thru function results once the upper path is finished.

**To Reproduce**
Execute attached workflow.

**Expected behavior**
The common path should get executed - input 1 has results from the true path and input 2 has results from the function.

**Environment (please complete the following information):**
 - OS: Win10 in Docker (WSL)
 - n8n Version 12.19.1
 - Node.js Version 0.102.0 (up to date)

Workflow attached below:

[unsaved_workflow.txt](https://github.com/n8n-io/n8n/files/5828427/unsaved_workflow.txt)

Here is how I was able to get around this issue for now.

![2021-01-18-08-22-46-529-1090x541-n8n_-_▶️_—_Mozilla_Firefox](https://user-images.githubusercontent.com/26925976/104884310-720e2d00-5966-11eb-8953-c9bf7aac2588.png)

**Comment by janober** [comment]
Thanks a lot for reporting!

Found the issue and know what is causing it. Now just have to find a way to fix it without breaking another functionality. I will update here once it is fixed.

**Comment by janober** [comment]
Bug got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.103.1
