### ISSUE TITLE
RequestError: Error: socket hang up

### ISSUE THREAD

**Issue by recollir** [n8n-io/n8n#1352]
**Describe the bug**
We have two n8n instances deployed in Kubernetes. A workflow in instance A is calling a workflow in instance B. Sometimes we see an error in instance A when this call happens:

```
"ERROR: RequestError: Error: socket hang up
Error: RequestError: Error: socket hang up
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest.node.js:804:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:395:47"
```

Instance A is using the http request node with a http post to call the workflow in instance B that is using a webhook to receive the call.

**To Reproduce**
No clear way. This happens every now and then.

**Expected behavior**
No failing invocations from the http request node in instance A when calling the webhook in the workflow in instance B.

**Environment (please complete the following information):**
 - docker images deployed to Kubernetes. Workflows are called through the configured kubernetes service that exposes the webhooks inside the cluster to the other n8n instances.
 - n8n Version 0.101.0 and 0.100.0
 - Node.js Version - the one provided by the docker image n8nio/n8n:0.101.0 and n8nio/n8n:0.100.0

**Comment by janober** [comment]
How long does it take until instance B sends an answer? Because if that is very long that could be the problem. 

If the Webhook-Node is set up in a way to return the data of the workflow and the workflow executes a long time then it would probably return something like that at some point.

**Comment by recollir** [comment]
The webhook node in instance B is configure to response with a 200 and the mode is on-received. I also don't see it being executed at all in the execution history in B.

**Comment by recollir** [comment]
Can we increasing logging in both A and B through an option to the docker image or an environmental variable? Perhaps we can see more then.

**Comment by janober** [comment]
OK, then this can not be the problem. Now it is getting harder.
So can just think of two things:
 1. It never receives the call. So could that be somehow k8s network related? 
 2. n8n crashes or is crashed. Can you see if that is the case?

No sorry. No such environment variable exists. It is however on the roadmap to improve that situation.

**Comment by recollir** [comment]
You mean n8n in B is crashed? No, B does process other workflows (also invoked via web hooks) just fine. Only when A calls B it fails sometimes. Not always.

We will dig a little bit more into this. Thanks for jumping on this quickly.

**Comment by janober** [comment]
Yes exactly.

Is it possible that B is doing something blocking and the event loop is blocked and so does not answer? So would depend on the kind of workflows you are running and also if you execute in the main process or a separate one.

**Comment by recollir** [comment]
How can I see if the event loop is blocked in B or if the workflow is running in the main process or a separate one. I can try to describe the workflow in B later on by listing the nodes involved if that helps.

**Comment by krynble** [comment]
A quick update on this topic is that we released logging for n8n.

You can find details about it here: https://docs.n8n.io/reference/logging.html#logging-in-n8n

Are you still experiencing this issue?

**Comment by recollir** [comment]
Thanks for the heads up on logging. Will give it a try and then test again with calling a workflow on a different instance. We implemented a workaround in the meantime by having the workflow on instance A post a msg to AWS SQS and the workflow on instance B subscribe to that AWS SQS topic,

**Comment by krynble** [comment]
Interesting feedback @recollir 
I think this is a safer approach as we cannot safely tell what is wrong, and there are many variables involved in your first scenario.

It could be networking, datacenter instability, etc. I am glad it is now working fine.

I will be closing this issue for now but feel free to reopen or add more information in the future.
