### ISSUE TITLE
Since 0.101.0 AWS Lambda node reports error "The request signature we calculated does not match the signature you provided"

### ISSUE THREAD

**Issue by ctrl-freak** [n8n-io/n8n#1360]
**Describe the bug**
Since 0.101.0, running a workflow with a AWS Lambda (possibly all AWS) node results in error returned:

> ERROR: AWS Error: Error: AWS error response [403]: 403 - "{\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\"}"

I tried generating another set of credentials, however the same error occurs and reverting back to 0.100.0 works with both old and new credentials.

I suspect the issue was introduced in [:sparkles: Add support for custom AWS endpoints (#1312)](https://github.com/n8n-io/n8n/commit/1501175b81dabccde0c74d4e6d0b6af909b9e602#diff-cd54be1f62a531bce4762b4fb91df9c6036496a9305f1ca421118f713c34adb6L21-R40) and specifically around the changes to signing.

I'm not using any custom endpoints, the switch is turned off on the credentials.

**To Reproduce**
1. Add AWS credentials with Access Key and Secret, without using custom endpoints
2. Create workflow with AWS Lambda node
3. Set Lambda node to Invoke, pick function and provide body
4. Run Node or Execute Workflow

**Expected behavior**
Lambda function is called and runs

**Environment (please complete the following information):**
 - OS: Linux 5.4.0-1024-oracle #24~18.04.1-Ubuntu SMP Sun Sep 6 00:18:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - n8n Version: 0.101.0
 - Node.js Version: Docker

**Additional context**
For now I've dropped back to running 0.100.0 without any issues.

**Comment by janober** [comment]
Thanks a lot for reporting this issue. Got fixed with #1361 and will be released with the next version.
