### ISSUE TITLE
Selection offset

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#1364]
**Describe the bug**
Multiple node selection has an offset if the workspace is zoomed.

**To Reproduce**
1. Open any workflow
2. Zoom Out or Zoom In
3. Click and hold on any empty space and select with drag drop (rectangle selection)

**Expected behavior**
Scale selection with the workspace zooming. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version:  0.102.0 
 - Node.js Version: v14.15.1

**Additional context**
Another useful thing would be zooming with ctrl and the mouse wheel.

Here is the function for the selection that needed to be fixed.: https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/mixins/mouseSelect.ts#L89

**Comment by janober** [comment]
Ah yes, that is sadly a known issue. Do not know how much time it would take to fix. As we currently do not have that many resources and is not too "pressing" in my eyes, is fixing that issue currently not scheduled.

Maybe somebody in the community could tackle that. Would be very appreciated.

**Comment by janober** [comment]
Thanks a lot @jonmbake for fixing this issue. Just got merged and will be released with the next version.

**Comment by lublak** [comment]
Thank you, also from me @jonmbake :+1:

**Comment by jonmbake** [comment]
@janober @lublak No problem. If similar bugs come up in the future, feel free to ping me. I want to support this project and enjoy fixing bugs like this.

**Comment by janober** [comment]
That is really great to hear and appreciated @jonmbake! Expect to hear from me in the future ;-)

**Comment by janober** [comment]
Got released with n8n@0.110.0
