### ISSUE TITLE
Error on Rocketchat node on n8n@0.103

### ISSUE THREAD

**Issue by fcollonval** [n8n-io/n8n#1367]
**Describe the bug**

After updating from 0.101.0 to 0.103.0, I'm getting the following error in the Rocketchat node for all worflows:

```
ERROR: Cannot read property 'body' of undefined

TypeError: Cannot read property 'body' of undefined
    at Object.rocketchatApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Rocketchat/GenericFunctions.js:25:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This is also happening with 0.103.1

> The workflows were working without problem on 0.101.0

**Expected behavior**

RocketChat node is working.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04] Alpine (Build using the docker image)
 - n8n Version [e.g. 0.26.0] 0.103.0 & 0.103.1
 - Node.js Version [e.g. 10.16.0] node:12.19

**Additional context**
N/A

**Comment by fcollonval** [comment]
Ok diving into the JS code the error comes from:

https://github.com/n8n-io/n8n/blob/cc4d6ab02a7da2a94674b3b13793ebf407c4b0c8/packages/nodes-base/nodes/Rocketchat/GenericFunctions.ts#L34

It should probably be modified to:

```ts
if (error.response?.body?.error) {
```

**Comment by RicardoE105** [comment]
@fcollonval  thank you for letting us know. Got fixed. We will let you know when is released.

**Comment by janober** [comment]
Sorry forgot to update here. Got merged and released a while ago. Please update to the latest version.
