### ISSUE TITLE
Strange Date/Timezone Bug is misleading in IF-Node

### ISSUE THREAD

**Issue by ixidion** [n8n-io/n8n#1380]
**Describe the bug**
Creating a Date() in an expression applies Timezone-Settings for the UI.

**To Reproduce**
1. Own Timezone should not be UTC. UTC+1 in my case (Berlin-Time)
2. Create an IF-Node
3. Enter 1611273600000 for "2021-01-22T00:00:00.000Z" as Param1
4. {{new Date(2021,0,22,0,0,0,0).getTime()}} as Param 2
5. In the preview box the result is shown as: 1611270000000
6. The IF-Node will evaluate to true (would expect that), even those shown numbers are different.

**Expected behavior**
The Box should show "1611273600000" as expected with no Timezone-Settings applied. But maybe it's more complicated cause of the timezones.

**Environment (please complete the following information):**
 - OS: Debian
 - n8n Version 0.102.0
 - Node.js Version (from official Docker-Image)

**Additional context**

**Comment by naskio** [comment]
Hey @ixidion 
Thanks for reporting. Are you using Postgres ?

**Comment by ixidion** [comment]
@naskio Yes, I think there was also a Postgres-Node somewhere, but it's not necessary to reproduce.

**Comment by Joffcom** [comment]
Hey @ixidion,

I am just running through some of the older issues and have attempted to reproduce this one but I have not had any luck. I have set my default timezone in the container and the TZ variable to Europe/Berlin instead of my normal Europe/London setting and the expressions seems to evaluate correctly.

Are you still seeing this issue on the latest release?

**Comment by naskio** [comment]
> Hey @ixidion,
> 
> I am just running through some of the older issues and have attempted to reproduce this one but I have not had any luck. I have set my default timezone in the container and the TZ variable to Europe/Berlin instead of my normal Europe/London setting and the expressions seems to evaluate correctly.
> 
> Are you still seeing this issue on the latest release?

Hey @Joffcom 
The problem still exists
I opened #2813 which should fix it (you can find more details about the PR at #2810)
Good luck

**Comment by Joffcom** [comment]
Hey @naskio,

That is interesting, I can't see what the link could be though 🤔

For the UI to display the date from the expression I wouldn't have thought the database would be touched.

I will test in the morning using a Postgres DB and see if that changes anything, I take it you have been able to reproduce this issue?

**Comment by naskio** [comment]
> Hey @naskio,
> 
> That is interesting, I can't see what the link could be though 🤔
> 
> For the UI to display the date from the expression I wouldn't have thought the database would be touched.
> 
> I will test in the morning using a Postgres DB and see if that changes anything, I take it you have been able to reproduce this issue?

Hey @Joffcom 
My bad, I just checked and found out that it is not really related to the other issue.
The problem here is that during the evaluation of the expression {{new Date(2021,0,22,0,0,0,0).getTime()}} the displayed value is different from the actual value that is being used in the comparison
(The problem here is only related to the UI assuming that we use GMT during evaluation expressions)
You can run the following workflow to get more details:

```
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        560,
        400
      ]
    },
    {
      "parameters": {},
      "name": "NoOp",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1320,
        380
      ]
    },
    {
      "parameters": {},
      "name": "NoOp1",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1320,
        720
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": 1611273600000,
              "operation": "equal",
              "value2": "={{new Date(2021,0,22,0,0,0,0).getTime()}}"
            }
          ]
        }
      },
      "name": "IF using new Date(",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        860,
        700
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": 1611273600000,
              "operation": "equal",
              "value2": "={{Date.UTC(2021, 0, 22, 0, 0, 0, 0)}}"
            }
          ]
        }
      },
      "name": "IF using Date.UTC",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        860,
        400
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "IF using Date.UTC",
            "type": "main",
            "index": 0
          },
          {
            "node": "IF using new Date(",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF using new Date(": {
      "main": [
        [
          {
            "node": "NoOp",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "NoOp1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF using Date.UTC": {
      "main": [
        [
          {
            "node": "NoOp",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "NoOp1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```


```javascript
// I am on GMT+2
let dateTZ = new Date(2021, 0, 22, 0, 0, 0, 0);
console.log("dateTZ", dateTZ.getTime()); // dateTZ 1611270000000
let dateUTC = Date.UTC(2021, 0, 22, 0, 0, 0, 0);
console.log("dateUTC", dateUTC); // dateUTC 1611273600000
```

**Comment by ixidion** [comment]
> @naskio Yes, I think there was also a Postgres-Node somewhere, but it's not necessary to reproduce.
Sorry, that was misleading. I use Postgres as DB-Backend for n8n.

**Comment by ixidion** [comment]
Still exists in 0.174.0
![image](https://user-images.githubusercontent.com/5589359/165234638-8da83c75-5b84-4100-b16e-077b269ad600.png)

**Comment by Joffcom** [comment]
Interesting, For me on 174 I am not seeing the issue.

![image](https://user-images.githubusercontent.com/4688521/165253554-29caeba6-7c13-434a-852e-ab633a8b368c.png)

Can you tell me what you have generic timezone and tz environment variables set to?

**Comment by Joffcom** [comment]
Hey @naskio,

Can you send me the environment variables you have set? In thoery I should be seeing an incorrect value as my machine is set to GMT but n8n is set to +2 but I see the +2 result in the browser so I am wondering if maybe this is more of a config issue or there is another option that I am missing.

**Comment by naskio** [comment]
> Hey @naskio,
> 
> Can you send me the environment variables you have set? In thoery I should be seeing an incorrect value as my machine is set to GMT but n8n is set to +2 but I see the +2 result in the browser so I am wondering if maybe this is more of a config issue or there is another option that I am missing.

My n8n environment:
```
GENERIC_TIMEZONE=Etc/GMT
TZ=Etc/GMT
```
My machine is set to GMT+2

**Comment by ixidion** [comment]
> Interesting, For me on 174 I am not seeing the issue.
> 
> ![image](https://user-images.githubusercontent.com/4688521/165253554-29caeba6-7c13-434a-852e-ab633a8b368c.png)
> 
> Can you tell me what you have generic timezone and tz environment variables set to?
My local time is set to CEST (is: UTC+2). I have run your code snippet.

UTC-Branch (looks ok)
![image](https://user-images.githubusercontent.com/5589359/165326476-734518c2-2af3-418d-84bc-fc9fd4efedf5.png)

new Date (looks not ok)
![image](https://user-images.githubusercontent.com/5589359/165326596-ae8da515-c670-4fcf-82d0-9d19c4a166d1.png)

**Comment by Joffcom** [comment]
This is very odd, maybe I need to change my desktop timezone to see the problem 🤔

@RicardoE105 you are on a different timezone to me, are you able to reproduce this?

**Comment by michael-radency** [comment]
Hello @ixidion , I do not think this is a bug, here for example from browser's console when timezone isn't specified:
![image](https://user-images.githubusercontent.com/88898367/195509749-828c677a-0f13-4c36-b8be-0aeee382e710.png)
behavior is reproducible, but it's nothing specific to IF node:
date1: just string
date2: `{{DateTime.fromISO("2021-01-22T00:00:00.000Z").toMillis()}}`
date3:` {{new Date('2021-01-22T00:00:00.000Z').getTime()}}`
date4:` {{new Date('2021-01-22T00:00:00').getTime()}}`
![image](https://user-images.githubusercontent.com/88898367/195510411-e3666e7a-9d05-482d-8eec-31435341faa3.png)

**Comment by ixidion** [comment]
@michael-radency Thank you for elaborating. So, it seems like it is a JavaScript/Browser Pitfall. I'm with you, doesn't look like a IF-Node bug.

**Comment by michael-radency** [comment]
Hello @ixidion , thanks for replying, as we agree that this behavior is not a n8n bug and it's not related to IF node I'll close this issue
