### ISSUE TITLE
export / import crashes

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1394]
**Describe the bug**
Creating a workflow, export it, import it back.

1. Export it

```
$ yarn export
yarn run v1.22.10
$ yarn export:credentials && yarn export:workflows
$ N8N_USER_FOLDER=$(pwd) n8n export:credentials --backup --output credentials
Successfully exported 2 credentials.
$ N8N_USER_FOLDER=$(pwd) n8n export:workflow --backup --output workflows
Successfully exported 1 workflows.
✨  Done in 4.86s.
```

2. Import it

```
$ yarn run import
yarn run v1.22.10
$ yarn import:credentials && yarn import:workflows
$ N8N_USER_FOLDER=$(pwd) n8n import:credentials --separate --input credentials
Successfully imported 2 credentials.
$ N8N_USER_FOLDER=$(pwd) n8n import:workflow --separate --input workflows
 ›   Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: workflow_entity.createdAt
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Should roundtrip.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04] macos
 - n8n Version [e.g. 0.26.0] 0.104.2
 - Node.js Version [e.g. 10.16.0] v15.5.1

'createdAt' exists:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/193115/106369142-3f453b00-634f-11eb-93aa-fe277ee901ee.png">

**Comment by janober** [comment]
Are you exporting and importing with the same n8n version or are they different?

**Comment by haf** [comment]
The should be the same (image: n8nio/n8n:0.104.2) but the server is running in docker and the client (n8n@^0.104.2:  version "0.104.2") is running on the host.

**Comment by janober** [comment]
hm I just tested again the full round-trip with 0.104.2 and worked perfectly without a problem with 341 credentials and 534 workflows. So currently do not understand why it would not work for you.

What database is the source n8n using and which database the destination (from the output guess SQLite)?
Did you maybe make changes to the database manually at some point? Because the output suggests that the workflow you export does not have a `createdAt` date and that is the reason why the import fails.

**Comment by haf** [comment]
Yes, I've imported an old workflow that I had exported to file first. But I don't see how that can go around the non null column requirement.

**Comment by haf** [comment]
I wasn't able to reproduce this a second time. I think the JSON we used may not have had the 'last updated' field or the like. Don't know why.
