### ISSUE TITLE
Running workflow twice causes $env to disappear second time

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#1395]
**Describe the bug**

When using `$env` in your workflow, you have to clear the run before pressing "Run" again, otherwise your nodes using `$env` crash.

**To Reproduce**
1. Set an env var in the container running n8n
2. Define a function, with code alike `const env = inputs.env || $env["OUR_ENV"]`
3. Run the workflow twice
4. See error: <img width="404" alt="image" src="https://user-images.githubusercontent.com/193115/106367657-7f52f080-6344-11eb-99d4-3d1035331f2e.png">

**Expected behavior**
Should not crash

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0] 0.104.2
 - Node.js Version [e.g. 10.16.0]

**Comment by janober** [comment]
Do not understand. What is the variable `inputs`? For me, it looks more like the error message says that `env` of `inputs` does not exist.

**Comment by haf** [comment]
Sorry, not working on this anymore. Will re-open next time I'm faced with this.

**Comment by janober** [comment]
Ok sounds good. Keep me updated.
