### ISSUE TITLE
IMAP Triggers randomly stop processing new messages

### ISSUE THREAD

**Issue by pcross616** [n8n-io/n8n#1400]
**Describe the bug**
When a IMAP workflow trigger is in an active workflow new messages will be processed until a certain time when they will cease working.  The workflow will remain active and no errors are reported.  Without inspecting the inbox the workflow looks as if no new emails were received, but when in actuality there are new emails.  If you deactivate the trigger and reactivate all messages that were not read they will now be processed.

**To Reproduce**
1. Create new workflow
2. Add IMAP trigger and configure to IMAP server
3. Add a node that handel down stream data from the IMAP trigger (eg slack or ftp)
4. Activate
5. on a long job say ever 12 hours send an email the address the IMAP triggers on
6. wait, typically the workflow will process on email but after the first one something timeout internally and nothing further processes.

**Expected behavior**
I would expect that each email no matter the time between occurrences that the IMAP email trigger fires.

**Environment (please complete the following information):**
 - n8n docker image 0.90 with Postgres 

** Notes **
There are no errors in n8n i see in the logs, I have tried increasing the log level but haven't had much luck.
The IMAP email trigger does process a attachment, I have tested with and without attachments and have similar results.

I can get more information if someone tells me what would be useful.  I have seen forum posts about this issue but no one has filed a bug.

**Comment by pcross616** [comment]
Actually did a bit more debugging... got this error

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on ImapSimple instance at:
    at Connection.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/imap-simple/lib/imapSimple.js:39:14)
    at Connection.emit (events.js:310:20)
    at TLSSocket._onError (/usr/local/lib/node_modules/n8n/node_modules/imap/lib/Connection.js:151:10)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._emitTLSError (_tls_wrap.js:873:10)
    at JSStreamSocket.<anonymous> (_tls_wrap.js:805:36)
    at JSStreamSocket.emit (events.js:310:20)
    at Socket.<anonymous> (internal/js_stream_socket.js:58:38)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  source: 'socket'
}


I use Office 365 as the email provider and looks like at times the connection will reset and the IMAP trigger is not reestablishing a connection till I deactivate and activate the workflow.

**Comment by pcross616** [comment]
Think I found the issue,

https://github.com/n8n-io/n8n/blob/2568b4b571449f7e41b251ed7591ef5f5cfa61b7/packages/nodes-base/nodes/EmailReadImap.node.ts#L384

When a connection resets (for many reason, such as a timeoute on the service provider for an active connection) there is no attempt to reconnect to the connection.

I am looking to see and test a fix I have locally, but having issue with the development environment.

**Comment by janober** [comment]
Cool, thanks a lot for reporting and looking into an issue. What problems do you have with the dev environment?

**Comment by pcross616** [comment]
I needed to add credentials to test it and it was reporting unable to connect to api credentials server endpoint on save of the creds.  I am sure it’s an issue with my node env but haven’t been able to track it down yet.


Thanks,
Pete
________________________________

**Comment by pcross616** [comment]
I have a fix in the works.  Testing in my prod environment to ensure it solves my problems with O365 reseting the IMAP connection after a period of time.  PR incoming soon.

**Comment by AhmetHuseyinDOK** [comment]
I also need this fix ASAP. Is there any news ?

**Comment by janober** [comment]
We are still working on it. Sadly do we have a hard time figuring out when the connecting did close as apparently none of the events fire in this case. Additionally is testing very slow as each iteration can take a day. But we are still on it.

**Comment by AhmetHuseyinDOK** [comment]
Hey, I kinda urgently need this right now. If you have even any "hacky" way to fix this and can share the current fix with me, I would like to implement it on my server and temporarily fix it till this feature got merged.

**Comment by hermanmaleiane** [comment]
I'm facing this issue right now. 
My workflow only works when i click **Execute Node**. 
Is there something I'm doing wrong?

**Comment by janober** [comment]
Sounds like you did not activate the workflow via the top right corner.

**Comment by hermanmaleiane** [comment]
> Sounds like you did not activate the workflow via the top right corner.

Hi @janober , i did that. 
![image](https://user-images.githubusercontent.com/13849459/114355900-49b25b00-9b70-11eb-8552-feb1be503822.png)

**Comment by janober** [comment]
Then you seem to suffer an even more extreme form of this issue.

**Comment by hermanmaleiane** [comment]
Can I put the trigger working with cron job ?

**Comment by janober** [comment]
No that is sadly not possible.

**Comment by hermanmaleiane** [comment]
Last question.
The workflow needs to be completed successfully to be able to listen to new triggers?

**Comment by krynble** [comment]
Hello @hermanmaleiane , @AhmetHuseyinDOK  and @pcross616 

I implemented a reconnect feature and hope it helps solve this issue.

Could you please try it and return to me if it works for more than a few days?

Considering the behavior remains the same (it still works) we might even consider releasing this in the next version and see if the errors stop happening.

You can find the PR here: https://github.com/n8n-io/n8n/pull/1667

Thanks!

**Comment by hermanmaleiane** [comment]
Hi @krynble!! 
Thanks for this awesome announcement. 
The new release is already available in docker?

**Comment by krynble** [comment]
Hi @hermanmaleiane 

Not yet available on docker, but I believe it can be released in the next version.

I would greatly appreciate your feedback after you test it =)

**Comment by janober** [comment]
Got released with n8n@0.116.0

If it did not solve the issue please comment here that we open the issue again.

**Comment by hermanmaleiane** [comment]
Hi @krynble and @janober .

I will test and give my feedback. 
I think it’s already updated on docker image.

**Comment by hermanmaleiane** [comment]
Hi @team. 

I have tested it and the problem i reported it's gone. 
I will do more tests in the coming days and i will let you guys know in case of issues.

Thanks guys for this fix.
You're guys are amazing.

**Comment by krynble** [comment]
That is great news @hermanmaleiane 

Yes, if you see this issue again please do let us know!

**Comment by gregorgrove** [comment]
This issue is still there it seems.

IMAP Trigger in a active Workflow on n8n@0.117.0 gets triggered by new mail for some time, then just ignores new mails without any error. Deactivating/Activating gets it started again.

Trigger is connected to a GSuite Mail Account.

**Comment by pcross616** [comment]
The fix that was pushed was the same approach I took initially and had the same results.  I started removing simpleimap to get exposed to the low level client which seems to handle reconnects.  The other option is to fix simpleimap client.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pcross616** [comment]
> Got released with n8n@0.116.0
> 
> If it did not solve the issue please comment here that we open the issue again.

This needs to be reopened.  The fix does not solve the issue as I tested it locally.  The connection reset handle is disconnected from the underlying connection.  As I mentioned above this was the same approach I took but never submitted the PR since it was not solved.

**Comment by janober** [comment]
We never stopped working on a fix. A fix got merged with #1792 and just released with n8n@0.120.0

**Comment by hermanmaleiane** [comment]
Hi @all.

I tested the version n8n@0.120.0 with outlook. When i activate the workflow i don't have the emails triggered. 
I tried  to downgrade to version n8n@0.116 where it was running but got same result.
I don't know what's wrong.

**Comment by krynble** [comment]
Hi @hermanmaleiane 

I made a few tests with Yahoo and Gmail and it was working fine.

Perhaps could this be a problem with the inbox? Could you test using another account?

**Comment by krynble** [comment]
Hum that is strange indeed @hermanmaleiane 

If you check the execution logs is it empty? Also, once the node starts it searches for unread messages, so you need to have at least one unread messages for it to work.

**Comment by janober** [comment]
Actually do not think this is the best place to discuss this issue:
1. Not sure it is a bug (considering that it worked before fine with 0.116.0 but stopped working now even with that version)
2. Has nothing to do anymore with the original issue (IMAP Trigger stops working)

The best place to discuss this would be the forum that people who have the same issue can find it easily:
https://community.n8n.io/

Thanks!
