### ISSUE TITLE
Can't fetch GitLab Repositories in Sub-Groups

### ISSUE THREAD

**Issue by ascherren** [n8n-io/n8n#142]
**Describe the bug**
When the repository is inside a subgroup it can't be fetched. It only gives the error "404".
![image](https://user-images.githubusercontent.com/35495373/70048635-0edb0300-15cb-11ea-85b5-f6faf45a0005.png)
It would be nice if for example the project ID could be entered instead. This way the "owner" field is no longer necessary.

**Comment by janober** [comment]
Got fixed and released with n8n@0.39.0
