### ISSUE TITLE
Cannot set port in using N8N_HOST

### ISSUE THREAD

**Issue by flypenguin** [n8n-io/n8n#1431]
**Describe the bug**
if you set `N8N_HOST` including a port it will take `:5678` _and then add_ the port number.

**To Reproduce**
1. start n8n using: `N8N_HOST=thing.thang.thong:8080 node_modules/n8n/bin/n8n`
2. see this on startup: `http://thing.thang.thong:8080:5678/`
3. check HTTP trigger nodes, which will have the same setting (which won't work, of course)

**Expected behavior**
to see this: `http://thing.thang.thong:18443/`

**Environment (please complete the following information):**
 - OS: Mac OS 11.1.2
 - n8n Version from git, Feb 8th, 22:44h
 - Node.js Version [e.g. 15.5.0]

**Additional context**
This is important when running n8n behind a load balancer, for example.

**Comment by janober** [comment]
`N8N_HOST` is for the host and `N8N_PORT` for the port. So if you set them separately it will work fine.

You can find the documentation here:
https://docs.n8n.io/reference/configuration.html#publish

Have fun!
