### ISSUE TITLE
n8n-node-dev: Build Module_not_found error

### ISSUE THREAD

**Issue by PhantomIsGod** [n8n-io/n8n#1435]
**Describe the bug**
When i try to build my custom node using n8n-node-dev build it throws the error code: 'MODULE_NOT_FOUND' 

```
C:\Users\Juan Finol\Desktop\n8n-master\n8n-nodes-folder>n8n-node-dev build

Build credentials and nodes
=========================
The nodes got build and saved into the following folder:
C:\Users\Juan Finol\.n8n\custom
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\Juan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**To Reproduce**
1. npm install -g n8n-node-dev
2. Make a new folder called "n8n-nodes-folder"
3.  Run the cmd n8n-node-dev new
4. Run the cmd n8n-node-dev build

**Expected behavior**
To work as described in [https://docs.n8n.io/nodes/creating-nodes/create-node.html#create-the-first-basic-node](url)

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version 0.107.0
 - Node.js Version v12.18.3

**Comment by ivov** [comment]
The whitespace in `Juan Finol` seems to be causing the failure to resolve the path.

As a quick check, in `C:\Users\Juan Finol\AppData\Roaming\npm\node_modules\n8n-node-dev\dist\src\Build.js`, can you please replace line 43 with the following and re-run the build command?

```
let buildCommand = `"${tscPath}" --p "${tsconfigData.path}" --outDir "${outputDirectory}" --rootDir "${process.cwd()}" --baseUrl "${nodeModulesPath}"`;
```

**Comment by janober** [comment]
As we did not hear back for multiple months will I close this issue now. If that is not the problem please comment here. We can then open the issue again.
