### ISSUE TITLE
0.108.0: Accessing non-existent property 'MongoError' of module exports inside circular dependency

### ISSUE THREAD

**Issue by syphernl** [n8n-io/n8n#1452]
**Describe the bug**
During startup `0.108.0` of I see a warning:
```
Accessing non-existent property 'MongoError' of module exports inside circular dependency
```

Not sure if it is related, but we are unable to reach the web-interface since we upgraded from `0.107.0` to `0.108.0`. Since this is just a warning I assume this is an unrelated issue.

**To Reproduce**
1. Upgrade from `0.107.0` to `0.108.0`
2. Error shows in log

**Expected behavior**
No error

**Environment (please complete the following information):**
We're using `n8nio/n8n:0.108.0`

**Additional context**

**Comment by janober** [comment]
Thanks for reporting.

That warning got already discussed here:
https://community.n8n.io/t/mongoerror-warning-detected/4350/4

That can however not be related to the web-interface not showing up. Sadly have no idea why that would happen but it must be something else.

**Comment by syphernl** [comment]
> Thanks for reporting.
> 
> That warning got already discussed here:
> https://community.n8n.io/t/mongoerror-warning-detected/4350/4

Glad to hear that's already spotted & fixed 👍🏻 

> That can however not be related to the web-interface not showing up. Sadly have no idea why that would happen but it must be something else.
> 
> Does downgrading resolve the issue with the web-interface?

It's a weird issue, my Chrome asks for basic auth but keeps on loading indefinitely after that. It works fine in Firefox and Incognito in Chrome so must be some strange local problem in combination with my KeePass integration or something I guess..

**Comment by janober** [comment]
The issue is fixed in the library but sadly did they not release a new version yet. But I am sure when we release the next n8n version it will also be out and we can then release it together.

Wow, that sounds very strange. Maybe really worth trying to delete cache, cookies, ... and then see if it works. Because nothing in n8n changed which should have any impact. At least nothing I can think of right now.

**Comment by syphernl** [comment]
The interface works again. It appears to have been a blip within in KeePassXC plugin, after restarting KeePassXC itself it's now working fine again. 
In regards to the initial issue, not a big issue for us since we don't use Mongo in our installation so it should be fine.

**Comment by janober** [comment]
Ah perfect. Thanks for the update. Also great to know if other people have similar problems in the future.
