### ISSUE TITLE
Auto-Refresh in Executions log view doesn't work properly

### ISSUE THREAD

**Issue by arladmin** [n8n-io/n8n#1456]
**Describe the bug**
The recently added Auto-Refresh feature does not honor the Filter settings at all, and hence is almost infeasible to use.

**To Reproduce**
1. Open Executions from the UI.
2. Verify that Auto-Refresh is checked.
3. Filter the executions, by wither Workflow name or Status.
4. The executions get filtered.
5. In a few seconds, the executions get unfiltered, despite the filters still being selected.

**Expected behavior**
Once filter(s) have been selected, the execution list should continue to adhere to them, until the user changes/disables the filter(s).

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version: 0.108.0
 - Node.js Version: v14.15.5
 - Setup: Docker

**Additional context**

**Comment by janober** [comment]
Thanks for reporting! @krynble fixed the bug. It just got merged into master and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.109.0
