### ISSUE TITLE
Cant export workflows and credentials in docker

### ISSUE THREAD

**Issue by soerenuhrbach** [n8n-io/n8n#1482]
**Describe the bug**
I'm trying to export all credentials and workflows from n8n running in docker.
The exports are failing. I can access them trough the ui and the rest api.

**To Reproduce**

1. Executing follow command: docker exec <container-id > packages/cli/bin/n8n export:workflow --all
2. See output
    >  Error: No workflows found with specified filters.

**Expected behavior**
All worksflow can be exported through the cli

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version: docker - n8nio/n8n:nightly
- Database: SQlite

**Additional context**
-

**Comment by janober** [comment]
The above command can not work, that is simply not how "docker exec" works. You have to set the name of the container you want to execute the command in, as part of the command. Are you sure that you are running that? 

Anyway, can you please post in the forum https://community.n8n.io/ as the command is working fine (so no bug) and it is just about how to run it correctly.

**Comment by soerenuhrbach** [comment]
Hi @janober, 

Thanks for your fast answer. The "docker exec" command works fine. Its just the markdown that messed up because I wrote `docker exec <container-id>`. Would the "docker exec" fail the command output would be different. 

Could you please reopen the issue?

**Comment by janober** [comment]
OK, that explains that. But sadly would still not make sense to reopen it as I am still sure that the command is working correctly, it just does not get executed correctly and is so not a bug. Can you please for that reason post into the forum as written above. We will then help you there asap. Thanks!

**Comment by janober** [comment]
I just tested. Works for me. 

With the nightly build
```bash
# Start n8n
docker run -it --rm \
	--name n8n \
	-p 5678:5678 \
	-v ~/.n8n:/root/.n8n \
	n8nio/n8n:nightly
	
# Export workflows
docker exec n8n packages/cli/bin/n8n export:workflow --all
```

With the regular image:
```bash
# Start n8n
docker run -it --rm \
	--name n8n \
	-p 5678:5678 \
	-v ~/.n8n:/root/.n8n \
	n8nio/n8n:0.109.0
	
# Export workflows
docker exec n8n n8n export:workflow --all
```
