### ISSUE TITLE
Losing Hubspot OAuth Credentials

### ISSUE THREAD

**Issue by jwaldrip** [n8n-io/n8n#1486]
**Describe the bug**
When configuring n8n with OAuth, after the 6 hour mark, which is the time in which the hubspot token expires, it is not refreshing the token. This is causing all subsequent runs to fail. Is there a setting I need to set to ensure the token is refreshing automatically without manual intervention?

**To Reproduce**
1. Configure a hubspot node with oauth creds with an interval trigger
2. Wait 6 hours
3. See requests fail with 400 errors.

**Expected behavior**
The token should refresh, thus allowing continued access to the api.

**Environment (please complete the following information):**
 - OS: 0.109.0 Docker Image running on Kubernetes
 - n8n Version 0.109.0
 - Node.js Version 14.x

**Additional context**

**Comment by RicardoE105** [comment]
@jwaldrip thanks for letting us know. Investigating this. I will keep you posted.

**Comment by jwaldrip** [comment]
@RicardoE105 Thank you.

**Comment by RicardoE105** [comment]
@jwaldrip got fixed. We will let you know when is released.

**Comment by janober** [comment]
Fix got released with n8n@0.110.0
