### ISSUE TITLE
Unable to send e-mail from n8n

### ISSUE THREAD

**Issue by twkrol** [n8n-io/n8n#1491]
**Describe the bug**
I'm creating a "Send email" node to send e-mail notification from n8n to my mailbox, but the node is unable to execute properly. The error is: "Error: 140163622717248:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:"

**To Reproduce**
1. Go to a new n8n editor
2. Click on '+' and and 'Send email' node
3. Set SMTP credentials eg. username, password, host, port (587), SSL/TLS on
4. Set e-mail sender, recipient and message content
5. Click 'Execute Node'

**Expected behavior**
The e-mail message should be delivered to mail host

**Environment (please complete the following information):**
 - OS: Debian 10
 - Docker v20.10.3
 - n8n v0.109.0 (image: n8nio/n8n:latest-debian)
 - Node.js v14.15.5

**Additional context**
Tried ports 25, 465 and 587 and no success.
"Ignore SSL Issues" option turned on or off - doesn't make any difference

**Comment by janbaykara** [comment]
Hey there, I had the same issue and discussed it over on the forum: https://community.n8n.io/t/smtp-ssl-error/1916/7

The solution at the time was to switch onto `n8n:latest-debian` but I see you've already done that.

What I see is different is you're using Debian 10 whereas I've had success with Debian 9.

**Comment by stouch** [comment]
With Debian 10 and n8n:latest-debian, it worked for me by disabling SSL/TLS and by checking Access/Send email (in the credential settings).

**Comment by axeleroy** [comment]
Hello,

I'm having the same problem and I understand [it is because of Alpine](https://community.n8n.io/t/smtp-ssl-error/1916/2) and that we should use the `-debian` images, but unfortunately I'm running n8n on an ARM-powered host and thus forced to use `-rpi`images.

Is there any plan to provide ARM-compatible images based on Debian in the future or to fix this issue in the `-rpi` images?

**Comment by janober** [comment]
fyi: We are working on getting multi-arch images working: https://github.com/n8n-io/n8n/pull/1625

That should then also solve this problem

**Comment by janober** [comment]
Can you please try with the latest image. That should hopefully work now fine.

**Comment by axeleroy** [comment]
Hello,

I updated my container to `n8nio/n8n:0.127.0` but when I tried sending an e-mail I got the same error as in the original message. Using `n8nio/n8n:0.127.0-debian` leads to the same error.

Maybe it has to do with the way OpenSSL is packaged on ARM, not Alpine?
