### ISSUE TITLE
Hue Credentials Expiring

### ISSUE THREAD

**Issue by jwaldrip** [n8n-io/n8n#1507]
**Describe the bug**
Hue OAuth Credentials have to be manually unauthenticated after a few days.

**To Reproduce**
1. Go to Hue
2. Authorize It
3. Wait a few days
4. Get 400s

**Expected behavior**
Expect Hue to Remain Authorized

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0]
 - Node.js Version [e.g. 10.16.0]

**Additional context**

**Comment by Ken-Michalak** [comment]
I'm seeing a similar issue with the OAuth2 API credentials against Keycloak. It looks like it might be an issue with the refresh in general. I'm not seeing errors in n8n logs, but I'm seeing this in Keycloak, every few seconds:
`WARN [org.keycloak.events] (default task-99) type=REFRESH_TOKEN_ERROR, realmId=master, clientId=n8n, userId=null, ipAddress=..., error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret`

**Comment by ivov** [comment]
@jwaldrip Apologies for the delay. Are you still facing this issue?

**Comment by 3DDario** [comment]
I’m facing the same issue with Raindrop credentials. I have to manually login every 14 days.

**Comment by ivov** [comment]
@3DDario 

We migrated from `request` to `axios` over past few months, so if you are experiencing this at 0.150.0, it is likely a separate issue from the author's. If you could please post in [the forum](https://community.n8n.io/) with details. Thanks.

**Comment by ivov** [comment]
Closing this for now. @jwaldrip If the issue persists, please comment and we will reopen.

**Comment by elidoteixeira** [comment]
Currently experiencing the same issue. After a few days my credentials need to be updated.

**Comment by Joffcom** [comment]
Hey @elidoteixeira,

Are you seeing this issue with Hue or another service?

**Comment by elidoteixeira** [comment]
It's with the Hue service. After 2 days it stops working and I need to authenticate again.

**Comment by Joffcom** [comment]
Have you tried toggling the old request library with the environment variable to see if that helps?

N8N_USE_DEPRECATED_REQUEST_LIB=true

It may be worth posting on the community forum and including all the version information and how you have n8n setup as well.

**Comment by elidoteixeira** [comment]
Hi @Joffcom. I'll give this a try a report back in a couple of days.

**Comment by elidoteixeira** [comment]
Been a while. I updated n8n a couple weeks ago and since then my credentials are not expiring anymore. This can be closed again. Thank you for your help @Joffcom.

**Comment by janober** [comment]
Great, thanks a lot @elidoteixeira for confirming! The issue got closed.
