### ISSUE TITLE
Facebook Graph Node v9.0

### ISSUE THREAD

**Issue by basstea** [n8n-io/n8n#1508]
Hi, could you please support v9.0 in Facebook Graph Node, maximum is only v7.0.

Unfortunately, there are errors with version 7.0:

ERROR: 400 - {"error":{"message":"(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v9.0.", "type": "OAuthException", "code":2635, "fbtrace_id": "xxxxx_xxxxxxxxxxxxxx"}}

**Comment by janober** [comment]
The versions 8, 9 and 10 got added and will be released with the next version.

In the future please post feature requests as defined in the issue-template to: https://community.n8n.io/
GitHub issues are only for bugs. Thanks!

**Comment by janober** [comment]
Got released with n8n@0.111.0
