### ISSUE TITLE
Workflow executions return the same items on "Load more"  

### ISSUE THREAD

**Issue by Libermentix** [n8n-io/n8n#152]
When workflows are automatically executed, they are included in the Workflow Executions List. The included Pagination allows to load more. Yet, always the same items (they have the same IDs) are listed as new loaded items.  

**Steps to reproduce the behavior:**
1. Have more Workflows run than displayed in the initial Workflow Execution overview (causing the Load More Action to appear)
2. Click on Load more
3. The same executed workflows should appear (they should have the same ID as the previous ones), see attached screenshot

<img width="958" alt="Screenshot 2019-12-12 at 09 38 39" src="https://user-images.githubusercontent.com/4686284/70705123-b5ae5600-1cd3-11ea-95ed-02d348cf6b4b.png">

**Expected behavior**
The Executed Workflows that are not already in the list should appear.

**Environment (please complete the following information):**
 - Standard Docker Image with n8n version 0.38

**Comment by janober** [comment]
hm, code seems ok but for some reason does it not filter correctly with the dates. Changed it now to use the id instead. That works now fine. I will release a new n8n version with the fix tomorrow.

**Comment by janober** [comment]
Got released with n8n@0.39.0
