### ISSUE TITLE
Cannot verify webhook secret

### ISSUE THREAD

**Issue by madchap** [n8n-io/n8n#1521]
**Describe the bug**
I should be able to verify incoming requests. There is currently no such option.

**Expected behavior**

**Environment (please complete the following information):**
n8n.cloud

**Comment by janober** [comment]
Sorry, do not understand what this issue is about. There is simply not enough information. 

The only thing I get from it, is that it is probably not a bug, it is rather a feature request and all feature requests have to be posted here: https://community.n8n.io/
