### ISSUE TITLE
Cron hours bug?

### ISSUE THREAD

**Issue by dumblob** [n8n-io/n8n#1528]
This `60` doesn't look correct to me somehow:

https://github.com/n8n-io/n8n/blob/80dfa75eb56171bb5b9af4d16031ffc6be8d4391/packages/nodes-base/nodes/Cron.node.ts#L291

**Comment by janober** [comment]
Not sure I understand. Did you have problems?

The code looks correct to me. It chooses by default a random second so that if there are a lot of crons used in n8n, they do not all start exactly at second 0, rather in a random one between 0 and 59.

**Comment by dumblob** [comment]
Yep, that's what I find weird - the precision is 1 minute instead of 1 second :cry:.

**Comment by janober** [comment]
If you want 1-second precision you can simply set a cron expression.

**Comment by dumblob** [comment]
Could you please add this suggestion to documentation? Thanks!

**Comment by janober** [comment]
The documentation already explains how custom cron expressions work:
https://docs.n8n.io/nodes/n8n-nodes-base.cron/#why-there-are-six-asterisks-in-the-cron-expression

**Comment by dumblob** [comment]
I mean document:
1. that there is loss of precision if custom cron expressions are not being used
2. that to overcome this built-in loss of precision one **has** to use custom cron expressions
