### ISSUE TITLE
Jira - global issue type

### ISSUE THREAD

**Issue by zvikarp** [n8n-io/n8n#1535]
**Describe the bug**
Hi there! I'm using Jira in the cloud, with the default issues type, all global. 
When creating a node to create a Jira issue, it shows me an empty issue type list.

**Expected behavior**
There should be a list of all global issue types + the scoped types.

**Environment (please complete the following information):**
 - OS: Windows  10
 - n8n Version 0.110.3
 - Node.js Version v14.15.4

**Additional context**
As you can see in [L188](https://github.com/n8n-io/n8n/blob/b655153431c2ca63b9c5859c911c5837653d880d/packages/nodes-base/nodes/Jira/Jira.node.ts#L188), if Jira is in the cloud, we ignore the issue type if it doesn't have a scope.

I tested locally and can confirm that if there is no scope you can still create an issue

Tested locally and changed:

https://github.com/n8n-io/n8n/blob/b655153431c2ca63b9c5859c911c5837653d880d/packages/nodes-base/nodes/Jira/Jira.node.ts#L206

To:

```
if (issueType.scope === undefined || issueType.scope.project.id === projectId) {
```

Do you want me to open a PR, or you got it from here?

**Comment by RicardoE105** [comment]
@zvikarp actually, it was like that before. I added this condition because, for us, it loading the issue types repeated. Can the global issue types be the same as the scope types?  Perhaps, it was something with our Jira config? 🤔

**Comment by zvikarp** [comment]
@RicardoE105 That is interesting. the truth is that I'm new to both Jira and n8n... [But in the Jira API documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-types/#api-rest-api-2-issuetype-get), it mentions (and I tested it) that global issue types do not have a scope object at all (as a scope can have only one project ID).

**Comment by RicardoE105** [comment]
@zvikarp I change the way the issue types are loaded in #1627. Can you please test it locally and let me know if that fixes your issue? Thanks

**Comment by zvikarp** [comment]
@RicardoE105 there is good news and bad news... 😅

I ran it locally and now I also get the issue types twice... But since I opened this issue, I changed from 'jira classic to 'jira next-gen' (and assume you also use next-gen). Unfortunately, you can't create 'jira classic' project anymore so I can't verify that jira classic uses global issue types and next-gen uses project-based types. I have read on this site it seems the global issue types are really for the classic and in the next-gen they want to implement the issue types in each project: https://community.atlassian.com/t5/Next-gen-articles/Everything-you-want-to-know-about-next-gen-projects-in-Jira/ba-p/894773.

So sorry for the confusion, I guess (assuming my hypothesis is correct...) it's up to you if you want to make it support the old classic version, or look good for the rest (or maybe jira has an API to check the project type). Either way, I'll be happy to help if needed.

Mystery solved but issue still open...

**Comment by ivov** [comment]
Closing for now - will revist once we have a request for Jira classic support for issue types.
