### ISSUE TITLE
JS nodes ignore Timezone settings

### ISSUE THREAD

**Issue by keshamin** [n8n-io/n8n#1538]
**Describe the bug**
I set my local timezone (Europe/Moscow) in "Settings" in UI, but JS code I write still use UTC. Maybe it takes it from OS, maybe it is just default behavior.

**To Reproduce**
1. Set timezone in Settings
2. Create a workflow with "Function" node
3. Call `new Date().getTimezoneOffset()` and check that it doesn't reflect the Timezone from Settings

**Expected behavior**
Timezone property from settings affects JS nodes. 
In my case `new Date().getTimezoneOffset()` should return `-180` for Moscow time and when I convert date to ISO it should apply this offset.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - n8n: Docker image n8nio/n8n:0.111.0

<img width="866" alt="image" src="https://user-images.githubusercontent.com/25623173/111069683-411e2480-84df-11eb-9f26-42094b3bcff7.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/25623173/111069695-4bd8b980-84df-11eb-8d55-8984d2134dac.png">

**Comment by luisherranz** [comment]
I have seen the same problem in my system.

**Comment by Joffcom** [comment]
Hey @keshamin,

Bit of a delay from me on this one, Are you still seeing this issue?

**Comment by Joffcom** [comment]
I am going to close this one for now, If this is still an issue let me know and we can open it again.
