### ISSUE TITLE
Importing separate decrypted credentials is not supported

### ISSUE THREAD

**Issue by schroedan** [n8n-io/n8n#1546]
**Describe the bug**
Because of #1463 exporting and importing decrypted credentials via CLI is possible. But importing separate decrypted credentials from backup leads to an error.

**To Reproduce**
1. Run `n8n export:credentials --backup --decrypted --output=credentials`
2. Run `n8n import:credentials --separate --input=credentials`
3. Try to open credentials in UI

**Expected behavior**
Separated, decrypted credentials can be imported.

**Environment (please complete the following information)**
 - OS: Alpine 3.11
 - n8n Version 0.111.0
 - Node.js Version 14.15.5

**Additional context**
The import of separate credentials does not support encryption: https://github.com/n8n-io/n8n/blob/master/packages/cli/commands/import/credentials.ts#L59
The implementation is incomplete.

**Comment by janober** [comment]
Thanks a lot for reporting. Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.112.0

**Comment by billux** [comment]
Thanks for your commit. Unfortunatly I still run into the same error described by @schroedan with the latest n8n release.

Here is how you could reproduce the issue:
```
docker run --rm -ti -v $(pwd)/credentials:/home/node/credentials n8nio/n8n:latest sh
/data $ n8n --version
0.133.0
/data $ cat /home/node/credentials/credentials.json 
[
  {
    "id": 1,
    "name": "test",
    "data": {
      "test": ""
    },
    "type": "",
    "nodesAccess": [],
    "createdAt": "2021-07-12T13:12:25.042Z",
    "updatedAt": "2021-07-12T13:12:25.042Z"
  }
]
/data $ n8n import:credentials --separate --input=/home/node/credentials/
UserSettings got generated and saved to: /home/node/.n8n/config
Successfully imported 1 credential.
/data $ n8n export:credentials --id=1 --pretty --decrypted
Error exporting credentials. See log messages for details.
Credentials could not be decrypted. The reason is that probably a different "encryptionKey" got used to encrypt the data than now to decrypt it.
```

Instead, if I run the `import:credentials` without `--separate` switch, the credential is readable:
```
docker run --rm -ti -v $(pwd)/credentials:/home/node/credentials n8nio/n8n:latest sh
/data $ n8n import:credentials  --input=/home/node/credentials/credentials.json
Successfully imported 1 credential.
/data $ n8n export:credentials --id=1 --pretty --decrypted
[
  {
    "id": 1,
    "name": "test",
    "data": {
      "test": ""
    },
    "type": "",
    "nodesAccess": [],
    "createdAt": "2021-07-12T13:12:25.042Z",
    "updatedAt": "2021-07-12T13:12:25.042Z"
  }
]
```

**Comment by yonathan9669** [comment]
Hey @billux, I'm still facing the same issue!! If I import the credentials 1 by 1, it works, but the bulk process does not.

@janober can you please consider looking at this bug?

---

Some insights that could be useful are that the bulk process injected the `data` field directly into the DB as a raw pass-through. I mean, after the import, I checked on the DB and the `credentials_entity` table had the `data` field unencrypted.
