### ISSUE TITLE
CoinGecko: can't set Base Currencies with an expression

### ISSUE THREAD

**Issue by peterjcarroll** [n8n-io/n8n#1549]
I am attempting to set the Base Currencies field with an expression. The data is coming from an Airtable node. I am using CoinGecko ids in the data, values like "bitcoin", "tezos", etc. I've attempted to use a raw array, a list of values separated by a space, and even a single value. No matter what I try, I get the same error:

```
TypeError: baseCurrencies.join is not a function
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/CoinGecko/CoinGecko.node.js:185:49)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:492:37)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:416:62
```

**To Reproduce**
1. Create a Set node
2. Add Value, select String
3. Name: coins, Value: bitcoin
4. Add a connection to a CoinGecko node
5. Resource: Coin, Operation: Price, Search By: Coin ID, Quote Currencies: USD
6. Click the gears next to Base Currencies to add an expression: {{$json["coins"]}}
7. Execute workflow, see error

**Expected behavior**
I expected the CoinGecko node to successfully query the price of bitcoin

**Environment (please complete the following information):**
 - n8n Version 0.111.0 (from Docker)

**Comment by janober** [comment]
Can you please post this in the forum [here](https://community.n8n.io) as GitHub issues are only for bugs. Thanks a lot!
