### ISSUE TITLE
Error in documentation. No install method via documentation.

### ISSUE THREAD

**Issue by brandonskerritt** [n8n-io/n8n#155]
**Describe the bug**
This readme:
https://github.com/n8n-io/n8n/blob/master/packages/cli/README.md
Has a table of contents. In that ToC, it says "installation".
This link leads to:
https://github.com/n8n-io/n8n/blob/master/packages/cli/README.md#installation
Which does not exist.

**Expected behavior**
An actual manual on installation.

**Comment by janober** [comment]
Thanks a lot. The links got removed as installation instructions and other content got moved to documentation.
