### ISSUE TITLE
Execute Workflow node ignores timeout

### ISSUE THREAD

**Issue by MaciejGorczyca** [n8n-io/n8n#1572]
**Describe the bug**
Using execute workflow node ignores the timeout of said workflow.

The issue forces users to set the timeout to every "initial" workflow (where you only set parameters and run sub-workflow).

**To Reproduce**
1. Prepare workflow that will run for few seconds (or use attached file) and set timeout to 10 seconds
2. Prepare workflow that will execute sub-workflow prepared in previous step and don't set timtout
3. Run the workflow with timeout to see that it is correctly stopping
4. Run the main workflow that executes sub-workflow to see that it is not respecting the timtout

**Expected behavior**
Main workflow gets the error caused by timeout from sub-workflow

**Environment (please complete the following information):**
 - OS: Win10
 - n8n Version latest docker image (0.112.0)
 - Node.js Version (the one used in latest docker image)

**Additional context**
![2021-03-23-18-20-25-086-923x350-n8n_-_⚠️_TEST_-_SUB_WORKFLOW_—_Mozilla_Firefox](https://user-images.githubusercontent.com/26925976/112189654-82f84a80-8c04-11eb-8583-a273e56ed7a4.png)
![2021-03-23-18-20-35-223-370x353-n8n_-_▶️_TEST_-_MAIN_WORKFLOW_—_Mozilla_Firefox](https://user-images.githubusercontent.com/26925976/112189662-84297780-8c04-11eb-8f63-c03a3dc1ce09.png)

[TEST___SUB_WORKFLOW.txt](https://github.com/n8n-io/n8n/files/6191587/TEST___SUB_WORKFLOW.txt)

**Comment by krynble** [comment]
Hello @MaciejGorczyca

Actually this is known and is expected at the moment. I have been talking to @janober recently and I am not sure if this is something we will be changing now.

Perhaps this behavior should be on the docs. Can we add this @tanay1337 and @harshil1712 ? That only the first workflow's timeout is taken into account. Subworkflows initiated from the `Execute Workflow` node will have their timeouts ignored.

**Comment by harshil1712** [comment]
hey@MaciejGorczyca, thanks for reporting this. As suggested by @krynble, I will add it to the documentation.

**Comment by krynble** [comment]
Hi @MaciejGorczyca and @harshil1712 

Just an update: I talked to @janober and we decided to fix this behavior, so the timeout set in subworkflows will also be taken into consideration.

**Comment by MaciejGorczyca** [comment]
> 
> 
> Hi @MaciejGorczyca and @harshil1712
> 
> Just an update: I talked to @janober and we decided to fix this behavior, so the timeout set in subworkflows will also be taken into consideration.

Might as well make the switch "Take subworkflow timeout into consideration: true/false" as parameter of "Execute Workflow" node if it won't be too hard/complex to implement.

Anyway, it's good that timeout will be checked now! Thanks.

**Comment by janober** [comment]
Got released with n8n@0.119.0
