### ISSUE TITLE
Github Trigger failed to run

### ISSUE THREAD

**Issue by Kermit-Xuan** [n8n-io/n8n#162]
**Describe the bug**

**To Reproduce**

Follow the steps of youtube video

**Expected behavior**

Workflow should run normally

**Environment (please complete the following information):**
 - OS: [Mac OS 10.15.2 Docker]
 - n8n Version [0.40.0]

**Additional context**

![image](https://user-images.githubusercontent.com/33770367/71335446-b077c380-257d-11ea-8269-622f1f348882.png)

error message: A webhook with the identical URL exists already. Please delete it manually on Github!

I have checked webhook of repo, it has nothing.

![image](https://user-images.githubusercontent.com/33770367/71335504-f896e600-257d-11ea-9c4f-9b911cac8bf3.png)

**Comment by janober** [comment]
Sorry to hear that you have problems! Sadly will probably nobody except you be able to debug that exact problem as it seems to work for other people including myself. To be 100% sure I tested again with 0.40.0.

It seems like that the current code is not correct as it assumes that the 422 error always means that a Webhook-URL already exists. We should probably change that in a future version that it returns the actual error.

Till that version with the fix gets released is what you can do is to add a console.log to output the actual error here :
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Github/GithubTrigger.node.ts#L379

It should then show you what is actually going wrong and you should then be able to fix the problem.

**Comment by Kermit-Xuan** [comment]
But it doesn't work when I add `console.log` to code. I clone the repo and then add `console.log` to code. Finally I run `npm run build` 、`npm run start`,  it has no effect.

**Comment by Kermit-Xuan** [comment]
Are there any requirements for access token permissions?

**Comment by Kermit-Xuan** [comment]
I already know the reason. Because I deployed and created the trigger locally, Github cannot verify the local webhook URL. Thank you for your patience.

**Comment by janober** [comment]
You are right. Github sadly seems to return exactly the same error for the case that "localhost" gets used and for when the webhook already exists. I added now extra code to catch the first case specifically. So it will then at least be easier for people that face the same issue you did.

Thanks!

**Comment by janober** [comment]
Fix got released with n8n@0.41.0
