### ISSUE TITLE
the -rpi image does not work

### ISSUE THREAD

**Issue by caarlos0** [n8n-io/n8n#1624]
**Describe the bug**
The `latest-rpi` image does not work, failing with `chown: cannot access '/home/node/.n8n': No such file or directory` everytime,

**To Reproduce**

```sh
docker run --rm n8nio/n8n:latest-rpi
```

**Expected behavior**
Should work.

**Environment (please complete the following information):**
irrelevant.

**Additional context**
Should also probably use the same Dockerfile as the amd64 image, just passing a different platform on build:

```sh
docker build -t n8n:0.114.0-rpi --platform linux/arm64 --build-arg N8N_VERSION=0.114.0 .
```

Also a good idea to create docker manifests (aka multi-architecture images) (can be done using `docker buildx` or `docker manifest`).

**Comment by janober** [comment]
Thanks for reporting @caarlos0. Sounds like #1240

Can you confirm that @lupa18? Made the proposed changes which I thought should solve those problems but can sadly not test as I do not have an Rpi myself.

**Comment by caarlos0** [comment]
@janober you can test by passing --platform linux/arm64 (for example) to Docker run, you don't really need a rpi 👌

**Comment by caarlos0** [comment]
FWIW just tested building the regular Dockerfile for platform Linux/arm64 and it works like a charm: caarlos0/n8n:0.114.0-arm64

**Comment by lupa18** [comment]
Yes, looks the same. 

In RPI images, permissions change was done in Dockerfile while in others was done in docker-entrypoint file. 

Not sure why is not working (also don't have here a RPI to test)

**Comment by caarlos0** [comment]
Opened a PR : #1625

**Comment by crazy-max** [comment]
I have also made [some tests on my side to reduce image size and also leverage multi-platform support](https://github.com/crazy-max/docker-n8n) using buildx and bake if you want to try it out on your raspberry:

```shell 
$ uname -a
Linux rasp3 5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

$ docker run --rm -it -p 5678:5678 crazymax/n8n:edge
UserSettings got generated and saved to: /data/.n8n/config
n8n ready on 0.0.0.0, port 5678
Version: 0.114.0

Editor is now accessible via:
http://localhost:5678/

Press "o" to open in Browser.
```

```shell 
$ uname -a
Linux rasp4 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

$ docker run --rm -it -p 5678:5678 crazymax/n8n:edge
UserSettings got generated and saved to: /data/.n8n/config
n8n ready on 0.0.0.0, port 5678
Version: 0.114.0

Editor is now accessible via:
http://localhost:5678/

Press "o" to open in Browser.
```

With your image:

![image](https://user-images.githubusercontent.com/1951866/113584389-209f4100-962b-11eb-98c2-1ac020d69b5d.png)

Multi-platform and Dockerfile enhancement:

![image](https://user-images.githubusercontent.com/1951866/113584796-9d321f80-962b-11eb-94cc-d027229f21f1.png)

**Comment by janober** [comment]
Wow that is amazing.

How did you get it so small? Is there now anything missing that could cause problems? Anything else that is different which could cause problems for people or could people switch them simply out?

**Comment by crazy-max** [comment]
Hey @janober, I think you should [remove `/root`](https://github.com/crazy-max/docker-n8n/blob/d84e10651db514b1aa4f5e1dbe513b683a3fb166/Dockerfile#L33-L34) because it contains gyp and cache metadata (~85MB) you don't need after the building process.

**Comment by crazy-max** [comment]
@janober PR #1625 looks good to me but we could improve the CI workflow a bit with bake I think but not required atm.
