### ISSUE TITLE
npm run dev not fully working

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [n8n-io/n8n#163]
**Describe the bug**
When I run `npm run dev` and make some changes to `packages/nodes-base/nodes/Webhook.node.ts` `displayName`,  CLI tool pick up there has been some changes but it does not display the new changes on the browser, I have to kill the process and run `npm run dev` to get the update to display

**To Reproduce**
Steps to reproduce the behaviour:
1. Run npm run dev
2. edit the file packages/nodes-base/nodes/Webhook.node.ts
3. change the displayName value
4. reload the browser
5. The changes should be updated

**Comment by janober** [comment]
Ah yes that is known and OK like this. Got also documented here:
https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#create-a-new-node-to-contribute-to-n8n
