### ISSUE TITLE
Matrix: End-to-end encryption for messages

### ISSUE THREAD

**Issue by articlecat** [n8n-io/n8n#1645]
Currently, all messages created by the Matrix node are unencrypted, even when they are posted in end-to-end encrypted rooms.

It would be great if the Matrix node were able to create end-to-end encrypted messages.

**Comment by janober** [comment]
Agree to 100% but GitHub issues are only for bug reports (as also stated in the issue-template). All feature requests have to be posted to the community forum here: https://community.n8n.io/

Thanks!

**Comment by articlecat** [comment]
Thanks, and sorry about that. The feature request is now at: https://community.n8n.io/t/matrix-node-end-to-end-encryption-for-messages/5222

**Comment by janober** [comment]
Perfect, thank you very much! Just try to keep everything tidy that people can find things easy ;-)
