### ISSUE TITLE
N8N_BASIC_AUTH_PASSWORD_FILE doesn't work

### ISSUE THREAD

**Issue by DTvGe45vc** [n8n-io/n8n#1656]
**Describe the bug**
N8N_BASIC_AUTH_PASSWORD_FILE doesn't work
I didn't find examples in docs how to use this variable from file.
What I need to write in file.

I tried to write this "N8N_BASIC_AUTH_PASSWORD=test" in file. It doesn't work.

Help me please

**Comment by janober** [comment]
If you define anything with "_FILE" then you have to set that variable to the path of a file. It then reads that file and uses the content as value. Meaning in this case, would the content of that file simply be `test`.

**Comment by DTvGe45vc** [comment]
I try run like this:
sudo docker run -it --rm --name n8n -p 5678:5678 -e N8N_BASIC_AUTH_ACTIVE=true -e N8N_BASIC_AUTH_USER=alex -e N8N_BASIC_AUTH_PASSWORD_FILE=/vault/secrets/password  -v ~/secrets:/vault/secrets -v ~/.n8n:/home/node/.n8n n8nio/n8n n8n start

But AUTH isn't work

**Comment by DTvGe45vc** [comment]
@janober could you see my example?
