### ISSUE TITLE
N8N_BASIC_AUTH_PASSWORD_FILE doesn't work FROM #1656

### ISSUE THREAD

**Issue by DTvGe45vc** [n8n-io/n8n#1658]
@janober You answered and closed my Issue but your offer doesn't work

I try to run like this:
sudo docker run -it --rm --name n8n -p 5678:5678 -e N8N_BASIC_AUTH_ACTIVE=true -e N8N_BASIC_AUTH_USER=alex -e N8N_BASIC_AUTH_PASSWORD_FILE=/vault/secrets/password -v ~/secrets:/vault/secrets -v ~/.n8n:/home/node/.n8n n8nio/n8n n8n

But AUTH isn't work
uncorrect login or password

cat secrets/password
test

**Comment by DTvGe45vc** [comment]
I need to use Hashicorp Vault for saving passwords and mounting them in docker as a file.

**Comment by krynble** [comment]
Hey @DTvGe45vc I think it's best if we try to isolate the problem.

Can you try using this file running n8n locally (without docker)?

We had an issue in the past where the error was in the credentials file, so I just wanted to double check this. Possibly empty spaces at the end of lines. With this simple test, we can make sure to isolate that the issue is related to docker.

Thanks!

**Comment by DTvGe45vc** [comment]
@krynble Ok. I'll try it and show my result later

**Comment by DTvGe45vc** [comment]
Hello @krynble 

I tested locally on version 
n8n Version: 0.115.0

Same result.

**Comment by krynble** [comment]
Hey @DTvGe45vc considering you are having the same issue locally, I guess we can safely assume this is not a docker related problem.

We had a similar issue recently reported by another user, using Kubernetes. You can see it here: https://github.com/n8n-io/n8n/issues/128

When sending the password as a file, Kubernetes (and potentially docker as well) added a new line to the end of the file.

This newline caused the authentication not to work.

Can you please check this? Is there a new line at the end of the password?

**Comment by DTvGe45vc** [comment]
I checked. no new lines.
Could you say how I can enable debug log for service?

**Comment by DTvGe45vc** [comment]
@krynble I was wrong. Sorry
It was a new line

**Comment by krynble** [comment]
Hey @DTvGe45vc 

Cool, thanks for the update. Did you manage to fix it? Is it working correctly now?

**Comment by DTvGe45vc** [comment]
@krynble  Yes I did. It's working.
Thank you very much.
