### ISSUE TITLE
Errors in 0.116

### ISSUE THREAD

**Issue by AllanDaemon** [n8n-io/n8n#1682]
**Describe the bug**
After the update to the 0.116 most my workflows are failing, but when I open it doesn't show any errors
![image](https://user-images.githubusercontent.com/607994/115275514-4262f280-a118-11eb-8c65-62f43c528407.png)

![image](https://user-images.githubusercontent.com/607994/115275409-24958d80-a118-11eb-8d39-b53d785af491.png)

![image](https://user-images.githubusercontent.com/607994/115275779-9e2d7b80-a118-11eb-8d2b-5cacfcb87a45.png)

I'm looking for further info to be added, but if this is as bad as I think it may be, it would be better to create an issue now, so this one.

**Comment by janober** [comment]
Thanks a lot for reporting this. What version did you use before?

How are you run executions? In the "main" process or in an "own"?

**Comment by AllanDaemon** [comment]
I don't remember which one was before, but I downgraded it to 0.115 and these errors stoped.
I'm running in "Main". Usually there are run by triggers, like cron or webhook.

**Comment by AllanDaemon** [comment]
Also, I always erase do a `rm -r node_modules/ package-lock.json` and install it with `npm i`, inside a folder with the following `package.json`:

```json
{
  "name": "n8n-local",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "n8n": "^0.115.0",
    "n8n-nodes-redacted": "file:n8n-nodes-redacted"
  }
}
```

**Comment by janober** [comment]
I am "sadly" (for you, generally happy about that) to reproduce that problem. Can you please download that workflow (via the side-menu) and then attach it here. Maybe that will help us. Thanks!

**Comment by janober** [comment]
I was now able the reproduce the problem. We will now have a look what is going on.

**Comment by janober** [comment]
Release new version with fix right now.

**Comment by janober** [comment]
Just released `n8n@0.116.1` with the fix. Please check if it works now also for you.

**Comment by lublak** [comment]
For me the problem has been solved with 0.116.1. I had the same issue.

**Comment by janober** [comment]
Thanks a lot for confirming @lublak!

**Comment by AllanDaemon** [comment]
0.116.1 fixed it.

Thanks a lot @janober !
