### ISSUE TITLE
SSE node is not working.

### ISSUE THREAD

**Issue by santiblanko** [n8n-io/n8n#1692]
**Describe the bug**
this node is not working all the past year. Also the node doesn't have headers configuration for auth.

**To Reproduce**
1. Go to nodes
2. Click on SSE trigger
3. Add a sse endpoint
4. play and try to receive events.

**Expected behavior**
you need to receive events from the sse server.

**Environment (please complete the following information):**
 - OS: Osx catalina.
 - n8n latest
 - Node.js Version latest

**Comment by janober** [comment]
I just tested it and it works totally fine for me. We did also not change the node since it has been created, so can also not think of a reason why it should have stopped working.

Are you sure that it is connecting correctly and that you then send an SSE event in the time that n8n is listening (so after you pressing "Execute Workflow" and then 120 seconds)?

**Comment by santiblanko** [comment]
Check: 

n8n server for testing: https://hello-world-santiblanko.cloud.okteto.net/workflow/1
SSE server for testing: https://sse-growup.herokuapp.com/sse
POST SSE server push https://sse-growup.herokuapp.com/push
{
 "input": "123",
  "eventName": "example"
}

No messages are received. Also a good idea is an option for change the headers for example for add authorization.

**Comment by janober** [comment]
None of the above URLs does seem to work for me. Is the server running?

Yes agree, is for sure a good idea to add authorization. Sadly are there literally a million things we could add but simply not enough developers to do so. So we have to prioritize. If you are interested in that feature please post a Feature-Request here:
https://community.n8n.io/
Other people can then vote and we so prioritize accordingly. Thanks!

**Comment by ivov** [comment]
@santiblanko The above URLs do not seem to be working. Are you still facing this issue?

**Comment by ivov** [comment]
Closing for now. If the issue persists, feel free to comment here and we will reopen.

**Comment by lazmo88** [comment]
> None of the above URLs does seem to work for me. Is the server running?
> 
> Yes agree, is for sure a good idea to add authorization. Sadly are there literally a million things we could add but simply not enough developers to do so. So we have to prioritize. If you are interested in that feature please post a Feature-Request here:
> https://community.n8n.io/
> Other people can then vote and we so prioritize accordingly. Thanks!

It seems SSE authentication has not yet been implemented, would it be possible to add this as feature requests?
