### ISSUE TITLE
Workflow Execution Sort/Order failing with Auto refresh

### ISSUE THREAD

**Issue by cmprmsd** [n8n-io/n8n#1694]
**Describe the bug**
The latest executed workflows are sorted by the ID. This works fine, when I open up the Executions view.
Once the Ajaxrequest refreshes the list the sorting of the list will look like the following, when it counts over 100:
```
99
98
...
67
66
111
110
109
...
```

**To Reproduce**
1. Create 100 events
2. Open the `workflow Exectutions` view
3. Wait for the refresh to happen.

**Expected behavior**
It should look like this:
![image](https://user-images.githubusercontent.com/73472903/115722566-696f2d80-a37f-11eb-835d-2ba37932b426.png)

but looks like this:
![image](https://user-images.githubusercontent.com/73472903/115722662-80ae1b00-a37f-11eb-9b97-9a56eb288915.png)

**Additional context**
I guess the ID is sorted as a string and not as a number. But only on automatic refreshes.

BTW: It would be cool to have the columns sortable, so you could identify long running jobs easily by sorting by `Running Time`.

**Comment by krynble** [comment]
Hey @cmprmsd thanks you for your report!

I have seen this behavior previously and it's in my to-do list. I will be working on this soon and should be fixed quickly.

Will keep you posted!

**Comment by janober** [comment]
Issue got fixed by @krynble and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.120.0

**Comment by cmprmsd** [comment]
Good stuff, thanks!
