### ISSUE TITLE
OAauth2 token refresh does not update workflow credentials

### ISSUE THREAD

**Issue by alexrsagen** [n8n-io/n8n#1695]
**Describe the bug**
When an OAuth2 token refresh happens, the (loaded) workflow credentials are not updated. Only database credentials are updated.

**To Reproduce**
1. Spawn an OAuth2 mock server, such as [axa-group/oauth2-mock-server](https://github.com/axa-group/oauth2-mock-server)
2. Create a OAuth2 credential in n8n using the mock server
3. Create a new workflow in n8n
4. Add a HTTP request node to the workflow, using OAuth2 against the mock server as the authentication method, with the "Retry on fail" option enabled (only 1 retry should be fine)
5. Duplicate the HTTP request node, ensure it runs after the first node
6. Run the workflow once to see that it normally works fine
7. Wait until the access token expires (or expire the access token manually)
8. Run the workflow again

**Expected behavior**
- The first HTTP request fails, attempts to refresh the OAuth2 access token, retries and succeeds on the 2nd attempt.
- The second HTTP request succeeds

**Actual/observed behavior**
- The first HTTP request fails, attempts to refresh the OAuth2 access token, retries and succeeds on the 2nd attempt.
- The second HTTP request fails due to expired access token, attempts to refresh the OAuth2 access token, fails.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - n8n Version: 0.115.0
 - Node.js Version: 14.15.5

**Technical explanation of the bug**
- When an OAuth2 token refresh is needed, the [`requestOAuth2` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/core/src/NodeExecuteFunctions.ts#L202) performs the OAuth2 token refresh, then calls the [`updateCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L176) to update the credentials in the database
- The [`updateCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L176) calls the [`getCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L51) to get the credentials to update, which gets the credential from the `workflowCredentials` member of its own instance (from the current workflow execution, i assume). It then copies the credential data into a new instance of the [`Credentials` class](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/core/src/Credentials.ts#L11) and returns that instance
- The [`updateCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L176) then updates the `data` (string) member of the instance created earlier of the [`Credentials` class](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/core/src/Credentials.ts#L11) using its `setData` function
- The [`updateCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L176) then updates the database using the data in the newly created [`Credentials`](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/core/src/Credentials.ts#L11) instance, but does nothing further with that instance (leaving it to later be garbage collected)
- The existing credential data in `workflowCredentials` is never updated.
- The next HTTP request node uses the existing credential data in `workflowCredentials` to authenticate its request, but those credentials are expired, as they did not get updated during the refresh.

**Comment by alexrsagen** [comment]
Hoping the issue is understandable, even without reproducing it, by reading the technical explanation.

I opted to not submit any pull request to fix this, as I don't know the codebase that well and there are multiple ways to fix the issue, such as:
1. Update the existing credential in `workflowCredentials` in the [`updateCredentials` function](https://github.com/n8n-io/n8n/blob/882e2f8e7434cb647a9367c34896f14fec48c049/packages/cli/src/CredentialsHelper.ts#L176)
2. Always load credentials from database before use

I think the first solution would be the most optimal out of the two suggestions.

Again, not so sure how that would affect the rest of the codebase or if the same fix would have to be implemented several places or anything like that.

Eagerly awaiting your reply @janober 😄

**Comment by RicardoE105** [comment]
Thanks for letting us know. I can confirm that it is a bug. We will work on it and let you know when it is fixed.

> Update the existing credential in workflowCredentials in the updateCredentials function

If we do it like that, it will work for the current workflow but not for other workflows using the same credentials.

> Always load credentials from database before use

Yes, this is the way to go.

**Comment by krynble** [comment]
Just for documentation purposes, I would like to link this issue that relates to the same problem: https://github.com/n8n-io/n8n/issues/1315

**Comment by krynble** [comment]
Closing this issue as it was solved on PR https://github.com/n8n-io/n8n/pull/1741

Should be merged soon and released.

**Comment by janober** [comment]
The PR #1741 got now merged and will be released with the next version.

**Comment by janober** [comment]
Got released with 0.135.0

**Comment by Harikarthyk** [comment]
I am getting the same issue again. The n8n version used is 0.195.5.

I am using HubSpot Outh for some HTTP requests. When I execute the workflow, everything is cool. But when I make it active for 30 minutes, it is fine, but after the aouth expires, the HubSpot node gets executed, but the HTTP request, which uses the same authentication, is not working.
