### ISSUE TITLE
New bcrypt library would not works with alpine on arm.

### ISSUE THREAD

**Issue by tingtingths** [n8n-io/n8n#1696]
**Describe the bug**
I'm using a [custom](https://github.com/tingtingths/docker-n8n) alpin based docker image on raspberry-pi. The new [@node-rs/bcrypt](https://github.com/napi-rs/node-rs) bcrypt library introduced in `0.116.0` only provides arm binary built with `glibc` but not `musl-libc`. Thus, n8n would fail to start on such environment, i.e. arm-based os built upon musl-libc.

Error output
```
TypeError: Can not find node binding files from
    @node-rs/bcrypt-linux-arm-gnueabi, @node-rs/bcrypt-linux-arm-gnueabihf,
    @node-rs/bcrypt-linux-arm-musleabi, @node-rs/bcrypt-linux-arm-musleabihf,
    @node-rs/bcrypt-linux-arm-gnueabi, @node-rs/bcrypt-linux-arm-gnueabihf,
    @node-rs/bcrypt-linux-arm-musleabi, @node-rs/bcrypt-linux-arm-musleabihf
    and /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-gnueabi.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-gnueabihf.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-musleabi.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-musleabihf.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-gnueabi.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-gnueabihf.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-musleabi.node,
    /home/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-arm-musleabihf.node
```
Incompatible binary
```
...
Error: Error relocating /home/n8n/node_modules/@node-rs/bcrypt-linux-arm-gnueabihf/bcrypt.linux-arm-gnueabihf.node: __register_atfork: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadBinding (/home/n8n/node_modules/@node-rs/helper/lib/loader.js:15:24)
    at Object.<anonymous> (/home/n8n/node_modules/@node-rs/bcrypt/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
Error: Cannot find module '@node-rs/bcrypt-linux-arm-musleabi'
Require stack:
  ...
```

**To Reproduce**
1. Start container, `docker run -it --rm node:14-alpine sh`
2. Install n8n, `apk add --update-cache make g++ python && npm install full-icu n8n@0.116.0`
3. Start n8n, `/node_modules/n8n/bin/n8n`

**Expected behavior**
n8n starts successfully

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster) armv7l
 - Base image: node:14-alpine
 - n8n Version: 0.116.0
 - Node.js Version: 14

**Comment by orangetone08** [comment]
I am also getting the same error in my computer
os: Windows

Error: 

```TypeError: Can not find node binding files from @node-rs/bcrypt-win32-x64-gnu, @node-rs/bcrypt-win32-x64-msvc and
C:\Users\Owner\AppData\Roaming\npm\node_modules\n8n\node_modules\@node-rs\bcrypt\bcrypt.win32-x64-gnu.node,
C:\Users\Owner\AppData\Roaming\npm\node_modules\n8n\node_modules\@node-rs\bcrypt\bcrypt.win32-x64-msvc.node```

**Comment by janober** [comment]
@tingtingths The [default n8n image](https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/Dockerfile) is also based on Alpine so was a little bit confused. Looks like the issue is that you have to change your Dockerfile a little bit to install the build tools:
https://betterprogramming.pub/quickly-improve-your-docker-and-node-js-containers-b841858a0b38 (and then search for Bcrypt)

@orangetone08 Seems to be the same for Windows. This is the first result I get when I Google the error message you did post above:
https://stackoverflow.com/questions/34546272/cannot-find-module-bcrypt
So you can try to run `npm install -g windows-build-tools` and see if that fixes your problem.

**Comment by tingtingths** [comment]
Hi @janober, thanks for the reply and sorry for the confusion.
The problem is [@node-rs/bcrypt](https://www.npmjs.com/package/@node-rs/bcrypt) only provides a limited set of binaries, and `bcrypt-linux-arm-musl` not being one of them. Thus, `musl` based OS i.e. alpine, together with `ARM` arch would fail.
```
Dependencies (10)
@node-rs/helper
@node-rs/bcrypt-win32-x64-msvc
@node-rs/bcrypt-darwin-x64
@node-rs/bcrypt-linux-x64-gnu
@node-rs/bcrypt-win32-ia32-msvc
@node-rs/bcrypt-linux-arm-gnueabihf
@node-rs/bcrypt-linux-x64-musl
@node-rs/bcrypt-linux-arm64-gnu
@node-rs/bcrypt-darwin-arm64
@node-rs/bcrypt-android-arm64
```

Although the default n8n image was built upon Alpine, it was meant to run on x86 machine. Which should be fine since `@node-rs/bcrypt-linux-x64-musl` provides the necessary binary.

Nevertheless i tried install build tools beforehand but no luck.

Possible solutions would be having `@node-rs/bcrypt` provides said binary or revert to `bcryptjs` which has no native dependency.

cheers

**Comment by janober** [comment]
n8n uses now again `bcryptjs`.
So the problem should be solved with the next release.

**Comment by janober** [comment]
Got released with n8n@0.122.0

**Comment by tingtingths** [comment]
thanks

**Comment by janober** [comment]
You are welcome. Have fun!
