### ISSUE TITLE
dyld: Symbol not found: _os_unfair_lock_trylock

### ISSUE THREAD

**Issue by thosanmaytinh** [n8n-io/n8n#1712]
**Describe the bug**
Got Error when installing

Message error
dyld: Symbol not found: _os_unfair_lock_trylock

**To Reproduce**
1. npm i -g n8n@0.117.0

**Environment (please complete the following information):**
 - OS: macos 10
 - n8n Version latest
 - Node.js Version 12

**Comment by RicardoE105** [comment]
Just test it, and it works fine for me. Also, googling that just returned what appears to be an issue with macOS? If you try to install another package, do you get the same error? Or it just happens with n8n.

**Comment by janober** [comment]
@thosanmaytinh Can you please retry with Node.js version 14. We do not support version 12 anymore. Maybe that fixes also your problem.

**Comment by janober** [comment]
Closing this issue as we did not hear back.

If the issue still exists after updating to Node.js v14 please simply comment. I will then open the issue again.
