### ISSUE TITLE
Post as LinkedIn org

### ISSUE THREAD

**Issue by madchap** [n8n-io/n8n#1714]
**Describe the bug**
When wanting to post as an org, I have

```
403 - {"serviceErrorCode":100,"message":"Field Value validation failed in REQUEST_BODY: Data Processing Exception while processing fields [/author]","status":403}
```

The token works fine with postman.

Also, no problem to post as a person.

**To Reproduce**
1. Request all necessary rights to yield to LinkedIn to get the following scopes
![image](https://user-images.githubusercontent.com/5468769/116319347-a9d30f00-a7b6-11eb-9d2b-a77dcfffc6f1.png)

```
- r_organization_social
Retrieve your organization's posts, comments, reactions, and other engagement data
- r_1st_connections_size
Use your 1st-degree connections' data
- r_ads_reporting
Retrieve reporting for your advertising accounts
- r_emailaddress
Use the primary email address associated with your LinkedIn account
- rw_organization_admin
Manage your organizations' pages and retrieve reporting data
- r_liteprofile
Use your name and photo
- r_basicprofile
Use your basic profile including your name, photo, headline, and public profile URL
- r_ads
Retrieve your advertising accounts
- rw_ads
Manage your advertising accounts
- w_member_social
Create, modify, and delete posts, comments, and reactions on your behalf
- w_organization_social
Create, modify, and delete posts, comments, and reactions on your organization's behalf
```
The latter being the one that's important.

2. Configure the workflow such as
![image](https://user-images.githubusercontent.com/5468769/116319463-dab34400-a7b6-11eb-9100-a37127fd0620.png)

3. See the error

**Expected behavior**
The post is created as the org.

**Environment (please complete the following information):**
 - docker - n8n v0.117.0

**Comment by RicardoE105** [comment]
@madchap thanks for reporting. Did you turn on the organization support in the credentials?

![image](https://user-images.githubusercontent.com/16496553/116327182-2dc7cf80-a794-11eb-9ff2-960db08fbb63.png)

**Comment by madchap** [comment]
Yes, I have.

**Comment by janober** [comment]
I get exactly the same message if I use credentials that have been authenticated without "Organization Support" enabled (as expected). Sadly can not test with it enabled as my "Marketing Developer Platform" API access is not yet approved yet. Will check again as soon as I get access.

**Comment by janober** [comment]
API got approved so I could properly test now. Works totally fine for me.

What is important, is that in the field "Organization URN" you just write the number.
So none of the following:
- `urn:li:company:1234567`
- `li:company:1234567`
- `company:1234567` 

Really just:
- `1234567`

Hope that helps!

**Comment by madchap** [comment]
> What is important, is that in the field "Organization URN" you just write the number.
> So none of the following:
> 
> * `urn:li:company:1234567`
> * `li:company:1234567`
> * `company:1234567`
> 
> Really just:
> 
> * `1234567`
> 
> Hope that helps!

That's helpful, yes. I don't recall seeing that in the docs but maybe it's my bad. I was putting `urn:li:company:1234567`.

I'll close the issue given your successful testing. If I don't report back, then that was it.

Thank you.

**Comment by janober** [comment]
Yes, I think that is definitely on us. I added yesterday also a placeholder value to the field with `1234567` that makes that hopefully clearer. We will also update the documentation accordingly.
