### ISSUE TITLE
Hue API seems broken since march the 29th 

### ISSUE THREAD

**Issue by LiquidITGuy** [n8n-io/n8n#1734]
EDIT : please see my answer before reading this 👍 

**Describe the bug**
Since 2021-04-29 at 11pm (utc+2) the workflows with phillips hue seems broken (even to retrieve all bulb) with à bad parameter response)
**To Reproduce**
1. Go to 'workflow'
2. Add a Philips hue credential
3. Add a Philips hue get all the light call
4. execute the workflow
5.  See error

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Caprover on debian Buster
 - n8n Version [e.g. 0.116.1]

**Additional context**
<img width="1015" alt="Capture d’écran 2021-05-04 à 22 18 49" src="https://user-images.githubusercontent.com/39310468/117066026-836a2200-ad28-11eb-8d50-b33a6cf586cf.png">
```
ERROR: Bad request - please check your parameters
HTTP status 400
 Details
Time
04/05/2021, 22:14:12
HTTP-Code
400
Cause
Data below may contain sensitive information. Proceed with caution when sharing.
{
"status": 400,
"body": "{"ErrorCode" : "invalid_request", "Error" :"The request is missing required parameters."}",
"code": "ESTATUS"
}
Stack
NodeApiError: Bad request - please check your parameters
    at Object.philipsHueApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/PhilipsHue/GenericFunctions.js:29:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.getUser (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/PhilipsHue/GenericFunctions.js:34:27)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/PhilipsHue/PhilipsHue.node.js:112:34)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:417:47
```

**Comment by LiquidITGuy** [comment]
I recreate a new credentials and all seems works.

That's a strange behaviour because the old credentials seems works and the error message is not explicit.

So the issue is rather on the message display than on the error itself.

**Comment by RicardoE105** [comment]
@LiquidITGuy The only thing I can think of it's the refresh token expired.  How often is this workflow being triggered?

**Comment by ivov** [comment]
@LiquidITGuy Are you still facing this issue in the latest 0.146.0?

**Comment by LiquidITGuy** [comment]
I had to upgrade my server.
I'll do this this week end 👍

**Comment by ivov** [comment]
Closing for now. If the issue persists, let us know and we will reopen.
