### ISSUE TITLE
n8n Update Google Sheets the wrong row if there is any extra row above the key row

### ISSUE THREAD

**Issue by mleungriot** [n8n-io/n8n#1736]
**Describe the bug**
I have a spreadsheet with ID and Value in row 2. Row 3 and all rows below are data. Row 1 is a dummy row. When I used the Google Sheets node to "update" the data, Google Sheets update the value of the row that is one row below the target row.

If I removed the row 1 (dummy row), the update ran fine without problem. I have set the "Data Start Row" and "Key Row" correctly in both case so I believe it is a bug in the Google Sheets node.

**To Reproduce**
1. Set up a sheet like this: 

Dummy Row |  
ID | Value
car1 | 1HKD
car2 | 2HKD
car3 | 3HKD

2. Setup the Google Sheet Node to update "car1" value to 100HKD. Set "Data Start Row" to 2 and "Key Row" to 1
3. Run the workflow
4. You can see the value of car2 is being updated instead.
5. If I remove the dummy row and set the "Data Start Row" to 1 and "Key Row" to 0. I can see "car1" was updated correctly

**Expected behavior**
Car1 should be updated instead

**Environment (please complete the following information):**
 - OS: MacOS (I run the n8n in docker)
 - n8n Version 0.118.0
 - Node.js Version No idea but I am using latest docker image (n8nio/n8n)

**Additional context**

**Comment by janober** [comment]
Thanks a lot for reporting this issue @mleungriot. Just fixed this issue. I will release with the next version.

**Comment by janober** [comment]
Got released with n8n@0.119.0
