### ISSUE TITLE
Webhook Deregistration on dedicated n8n webhook commands

### ISSUE THREAD

**Issue by mvhirsch** [n8n-io/n8n#1739]
**Describe the bug**
I'm running a "HA"-setup (okay, sort of), utilizing everything that's described in [Scaling N8N](https://docs.n8n.io/reference/scaling-n8n.html). So my setup looks like this (using docker, redis and mysql):

* 1x main process (started with default docker command)
* 2x webhook processes (started with `n8n/cli webhook`)
* 3x workers processes (started with `n8n/cli worker`)

Referring to https://github.com/n8n-io/n8n/issues/1122#issuecomment-776689339 this works on the main process.
But after restarting a webhook-process, all webhooks get deregistered. Only while restarting the main-process, it seems to work correctly. Is that intended? Or should the SKIP_DEREGISTERING* env also be respected on any webhook process?

**To Reproduce**
1. Start a main process, webhook process, and worker process
2. Set `N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true`
2. Setup a simple webhook test workflow
3. Restart webhook process
4. Try webhook -> 404

**Expected behavior**
Webhook should work

**Comment by krynble** [comment]
Hi @mvhirsch 

Thanks for your report.

This is certainly a bug. I will be working on it soon. Will keep you posted!

**Comment by janober** [comment]
Just merged #1753. Will be released with the next version.

**Comment by mvhirsch** [comment]
Awesome, thank you!

**Comment by janober** [comment]
Got released with n8n@0.119.0
