### ISSUE TITLE
Type error on build of nodes-base

### ISSUE THREAD

**Issue by abhay-singh-au3** [n8n-io/n8n#1754]
**Describe the bug**
There are 2 error which comes on running the build command.
Errors are coming from type files of cheerio module.

**To Reproduce**
1. Clone the repo
2. `lerna bootstrap --hoist`
3. `npm run build`

![image](https://user-images.githubusercontent.com/52338948/117455584-f829a000-af64-11eb-8d13-dcdc36608d52.png)

**Expected behavior**
Build without error

**Environment :**
 - OS: Windows 10 2004
 - n8n-nodes-base Version 0.115.0
 - Node.js Version 12.16.1

**Comment by janober** [comment]
Thanks a lot for reporting.

It seems like the cheerio module changed and caused problems. Did now set an old version manually which solves the problem.

**Comment by abhay-singh-au3** [comment]
> Thanks a lot for reporting.
> 
> It seems like the cheerio module changed and caused problems. Did now set an old version manually which solves the problem.

Thanks a ton!

**Comment by janober** [comment]
Closing this issue as everything seems to be working fine now.

**Comment by janober** [comment]
Got released with n8n@0.119.0
