### ISSUE TITLE
Oauth Callback URL seems to be hardcoded to http://localhost:5678

### ISSUE THREAD

**Issue by joehillen** [n8n-io/n8n#1769]
**Describe the bug**
I'm running n8n using docker-compose on a server and I was trying to set up Reddit credentials, but the callback URL seems to be hardcoded to `http://localhost:5678`

**To Reproduce**
1. Start n8n on a remote server with docker-compose
2. Add Reddit Oauth 2 credentials
3. Create a Reddit app using a callback URL to the remote server
4. Click: "Not Connected"

The request will fail because the Oauth callback URL doesn't match the app settings in Reddit.

**Expected behavior**

It should use the address for the remote server in the callback URL, not `http://localhost:5678`

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version: 0.119.0
 - Node.js Version: 14
**Additional context**

I dug through the code and I've tried setting `VUE_APP_URL_BASE_API=http://192.168.1.101:5678/` in the docker-compose.yml yet it seems to have no effect.

**Comment by janober** [comment]
Please check here:
https://docs.n8n.io/reference/configuration.html#webhook-url

**Comment by joehillen** [comment]
Thanks! Set `N8N_HOST=192.168.1.101` in docker-compose.yml and that fixed it!
