### ISSUE TITLE
On flow inactivation id is not sent to web-hook function

### ISSUE THREAD

**Issue by mdasmendel** [n8n-io/n8n#1786]
**Describe the bug**
On bot inactivations, the client sends back just field active with value false without id of flow. Because in the hook is injected body only, id is missing.

`
PATCH /rest/workflows/6 
Body: {"active":false}
`

**To Reproduce**
1. Go to an eligible workflow (can be activated/deactivated), activate if is inactive
2.  Click on the switch to inactivate
3. check the data sent to 'workflow.update'
4. received data: {"active":false}, id is missing
**Expected behavior**
Id to be present

**Environment (please complete the following information):**
 - OS: MacOS Big Sur
 - n8n Version 0.119.0
 - Node.js Version 14.15.5
 - Database system SQLite
 - Operation mode own

**Comment by janober** [comment]
Thanks, seems like you fixed it yourself with #1788 which got merged.

**Comment by janober** [comment]
Got released with n8n@0.120.0
