### ISSUE TITLE
Spreadsheet node "sheet name" option not selectable.

### ISSUE THREAD

**Issue by Maelstrom96** [n8n-io/n8n#1808]
**Describe the bug**
Right now, I'm not able to set the `Sheet name` option on the Spreadsheet node. Not seeing any error in the chrome console.

**To Reproduce**
1. Go into a workflow
2. Add the `Spreadsheet File` node
3. Select the `Write to file` operation
4. Click on "Add options"
5. Click on "Sheet name"
6. See error

**Expected behavior**
The option should display an editable field.

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - n8n Version 0.119.0
 - Node.js Version [e.g. 14.16.0]
 - Database system: SQLite
 - Operation mode: main

**Screenshots of the behavior**

![2021-05-20_09h58_55](https://user-images.githubusercontent.com/9983268/118993002-23dc5b00-b953-11eb-8f1b-5fcb0d535391.png)
![2021-05-20_09h58_59](https://user-images.githubusercontent.com/9983268/118993030-2939a580-b953-11eb-9bdd-a74ef300077c.png)
![2021-05-20_10h05_14](https://user-images.githubusercontent.com/9983268/118993033-29d23c00-b953-11eb-8ca9-1b64cfc52b00.png)

**Comment by janober** [comment]
Thanks for making us aware of that. Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.122.0
