### ISSUE TITLE
Parameters expressions doens't match the execution parameters when selecting execution other than 1

### ISSUE THREAD

**Issue by Bruno-Tome** [n8n-io/n8n#1809]
**Describe the bug**
Parameters expressions doens't match the execution parameters when selecting execution other than 1. 
When using expressions to fill parameters of the node from the workflow, the content of the parameter on the UI doens't match the parameter on the workflow.

**To Reproduce**
1. Create an expression parameter using templates 
2. Run a workflow with more than 1 execution run
3. Change Id of execution to other than 1 
4. Parameter of the UI doesnt match selected execution parameter

**Expected behavior**
A match between UI parameter and execution ID paramenter

**Environment (please complete the following information):**
 - OS: Amazon Linux 2(I believe its debian based) -> Docker compose container
 - n8n Version: n8n@0.120.0
 - Node.js Version [e.g. 14.16.0]
 - Database system: SQLite
 - Operation mode: Own 

**Additional context**
![print](https://user-images.githubusercontent.com/26755391/119001651-8b4dd700-b962-11eb-9bae-a3e75e224747.png)

**Comment by janober** [comment]
Thank for reporting this but this is sadly a known shortcoming. The editor-UI does always just display the data of:
- the first input
- the first execution
- the first item

**Comment by ivov** [comment]
Closing for now. Hopefully to be addressed once we revamp node expressions.
