### ISSUE TITLE
linux run n8n typeError by bcrypt 

### ISSUE THREAD

**Issue by amaoo** [n8n-io/n8n#1822]
**Describe the bug**
linux n8n start error
TypeError: Can not find node binding files from @node-rs/bcrypt-linux-x64-gnu, @node-rs/bcrypt-linux-x64-gnux32, @node-rs/bcrypt-linux-x64-musl and 
    /etc/node-v14.17.0/lib/node_modules/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-x64-gnu.node, 
    /etc/node-v14.17.0/lib/node_modules/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-x64-gnux32.node, 
    /etc/node-v14.17.0/lib/node_modules/n8n/node_modules/@node-rs/bcrypt/bcrypt.linux-x64-musl.node`

https://www.npmjs.com/package/@node-rs/bcrypt/v/1.2.1
 this package not support @node-rs/bcrypt-linux-x64-gnux32
'@node-rs/bcrypt/' folder is not have bcrypt/bcrypt.linux-x64-gnu.node,bcrypt.linux-x64-gnux32.node,and bcrypt/bcrypt.linux-x64-musl.node file

**Comment by z790490122** [comment]
Me too.

**Comment by janober** [comment]
Thanks for reporting. But please file the bug again and this time use the full template (and add everything else you think could be helpful or is special) that we are able to debug this issue. Because for me it builds totally file. Thanks!
