### ISSUE TITLE
Switch node returns an error when used with "Expression"

### ISSUE THREAD

**Issue by luisherranz** [n8n-io/n8n#1843]
**Describe the bug**
The Switch node returns `Could not get parameter "dataType"!` error when used with "Expression" mode in n8n 0.121.0.

**To Reproduce**
1. Add a Switch node.
2. Change mode to "Expression"
3. Run it

https://user-images.githubusercontent.com/3305402/120108494-a3450800-c165-11eb-9a9c-9e00209f3586.mp4

**Expected behavior**
Before 0.121.0 it works fine.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n Version 0.121.0
 - Node.js Version 12
 - Database system MySQL
 - Operation mode `own`

**Comment by janober** [comment]
Thanks a lot for making us aware of this issue. Got fixed and will be released with the new version today.

**Comment by janober** [comment]
Got released with n8n@0.122.1

**Comment by luisherranz** [comment]
No problem. Thanks @janober!
