### ISSUE TITLE
Notion node returns body failed validation, when LastEditedTime property used (in Notion database)

### ISSUE THREAD

**Issue by seba5496** [n8n-io/n8n#1844]
**Describe the bug**
Executing Notion node returns 400 error (Validation Error) with body: 
`body failed validation. Fix one: body.filter.last_edited_time.equals should be defined, instead was "undefined".`

**To Reproduce**
1. New Notion node
2. Set Resource to "Database page"
3. Set Operation to "Get All"
4. Set Return All to "True"
5. Set Simple to "True"
6. Add Filter field
7. Add filter Multiple condition
8. Add Condition AND
9. Set Property Name to {some property name, in my case is "LastEditedTime"} (last_edited_time)
   - Condition: On or After
   - Date: Yesterday
10. Add Condition AND
11. Set Property Name to {in my case "Estado" (State in spanish)} (select)
   - Condition: Equal
   - Option: "Completado" 
12. Run node

**Expected behavior**
Should return all tasks edited the day before or after that have state set to completed ("completado" in english)

 - OS: Ubuntu 20.04.2 LTS (WSL 2 on Windows 10 Pro (Version: 21H1) (Compilation: 19043.1023))
 - n8n Version 0.122.0
 - Node.js Version 14.15.5
 - Database system [Default]
 - Operation mode [Default]

**Additional context**
I'm running n8n inside a docker container, after running the following command inside Ubuntu terminal (WSL 2):
`docker run -it --rm \
  --name n8n \
  -p 5678:5678 \
  n8nio/n8n`
![Sin título](https://user-images.githubusercontent.com/47981550/120121307-b4474680-c170-11eb-8838-bbc157c34dc4.png)

Next is the node configuration:
`{
  "nodes": [
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "getAll",
        "databaseId": "1b4c734c-c835-4504-9210-48409766a364",
        "returnAll": true,
        "options": {
          "filter": {
            "multipleCondition": {
              "condition": {
                "and": [
                  {
                    "key": "Created Date|created_time",
                    "condition": "after"
                  },
                  {
                    "key": "Estado|select",
                    "condition": "equals",
                    "selectValue": "Completado"
                  }
                ]
              }
            }
          }
        }
      },
      "name": "Notion",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 1,
      "position": [
        750,
        190
      ],
      "alwaysOutputData": false,
      "retryOnFail": false,
      "maxTries": 2,
      "credentials": {
        "notionApi": "Notion API"
      }
    }
  ],
  "connections": {}
}`

The complete error message is the following:
`ERROR: 400 - {"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one: body.filter.and[0].created_time.equals should be defined, instead was "undefined". body.filter.and[0].created_time.before should be defined, instead was "undefined". body.filter.and[0].created_time.after should be a valid ISO 8601 date string, instead was `\"\"`. body.filter.and[0].created_time.on_or_before should be defined, instead was "undefined". body.filter.and[0].created_time.on_or_after should be defined, instead was "undefined". body.filter.and[0].created_time.past_week should be defined, instead was "undefined". body.filter.and[0].created_time.past_month should be defined, instead was "undefined". body.filter.and[0].created_time.past_year should be defined, instead was "undefined". body.filter.and[0].created_time.next_week should be defined, instead was "undefined". body.filter.and[0].created_time.next_month should be defined, instead was "undefined". body.filter.and[0].created_time.next_year should be defined, instead was "undefined". body.filter.and[0].created_time.is_empty should be defined, instead was "undefined". body.filter.and[0].created_time.is_not_empty should be defined, instead was "undefined"."}`

`StatusCodeError: 400 - {"object":"error","status":400,"code":"validation_error","message":"{**The body message shown above**}"}
    at new StatusCodeError (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/n8n/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)`

It seems this error appears only with some type of properties of the notion database, so far I've seen this error occur with Last Edited Time and some formula properties (that return True or False).

**Comment by janober** [comment]
Got fixed by @ivov with #1861. Will be released with the next version.

**Comment by janober** [comment]
Fix got released with n8n@0.122.3

**Comment by seba5496** [comment]
> Fix got released with n8n@0.122.3

Thank you very much :)
