### ISSUE TITLE
Not able to build the project behind a proxy

### ISSUE THREAD

**Issue by tom555my** [n8n-io/n8n#1846]
**Describe the bug**
I was trying to create a new node and it seems that the project cannot be built when building `node-base` behind a proxy, due to the `node-fetch` is not able to accept the proxy configuration in the environment (eg: HTTP_PROXY, HTTPS_PROXY).

**To Reproduce**
1. Set yourself up with a network environment, so that you can only access the network via a proxy layer
2. cd n8n
3. npm run build
4. You should see something like this:
```bash
> n8n-nodes-base@0.118.0 build /Users/tommy.chung/Projects/n8n/packages/nodes-base
> tsc && gulp --continue

⠹  Building for production...[18:17:00] Using gulpfile ~/Projects/n8n/packages/nodes-base/gulpfile.js
[18:17:00] Starting 'default'...
⠦  Building for production...[18:17:00] Finished 'default' after 305 ms
⠦  Building for production...(node:52659) UnhandledPromiseRejectionWarning: FetchError: request to https://google-webfonts-helper.herokuapp.com/api/fonts failed, reason: connect ETIMEDOUT 54.220.192.176:443
    at ClientRequest.<anonymous> (/Users/tommy.chung/Projects/n8n/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:376:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:52659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:52659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦  Building for production...^C
```

**Expected behavior**
The project should be built.

**Environment (please complete the following information):**
 - OS: Mac 11.2.3
 - n8n Version: version in the master branch
 - Node.js Version 14.17.0
 - Database system  SQLite
 - Operation mode own

**Additional context**

**Comment by janober** [comment]
Sorry not sure if we can do anything here. If `node-fetch` is the problem, you would have to open an issue there.

Generally is building `n8n-nodes-base` behind a firewall no problem. The only problem would be if you try to build `n8n-editor-ui`. A workaround would be to comment out the following 5 lines:
https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/vue.config.js#L16-L20

It will then also build fine offline or behind a proxy. Obviously, will it then use the wrong font but that should not matter much.

**Comment by tom555my** [comment]
Thanks @janober . I comment out the 5 lines and it works.

**Comment by janober** [comment]
Glad to hear that it worked! Have fun!
