### ISSUE TITLE
Notion node: issue when assigning value to 'date' properties

### ISSUE THREAD

**Issue by starise** [n8n-io/n8n#1878]
**Describe the bug**
It looks like it's not possible to assign a date without a time when updating dates on database pages.

**To Reproduce**
1. Notion node -> Res: 'Database Page' | Op: 'Update' | Simple: Checked
2. Property -> Key: use a 'date' type field
3. Assign a value like: '2021-06-09'
4. Run the node

On the Notion page, UTC timezone is forced and time is assigned automatically.

**Expected behavior**
We should be able to push only the date without the time, respecting user's timezone.

**Environment (please complete the following information):**
 - OS: n8nio/n8n Docker image (on Win10)
 - n8n Version 0.123.1

**Comment by RicardoE105** [comment]
Got fixed. We will let you know when it is released.

**Comment by janober** [comment]
PR got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with n8n@0.124.0
