### ISSUE TITLE
n8n@0.124.0 breaking or giving bad gateway on the docker image - reverted to n8n@0.123.1

### ISSUE THREAD

**Issue by wmuza** [n8n-io/n8n#1899]
**Describe the bug**

**To Reproduce**
1. Folllow [these steps](https://snippets.wilbertzgroup.com/snippet/eJuj5816P) to update n8n on server 
2. After everything is done the server starts giving bad gateway

**Expected behavior**
Server should work as normal

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 20.04.2]
 - n8n Version [e.g. 0.124.0]
 - Node.js Version [e.g. 14.16.1]
 - Database system [SQLite]
 - Operation mode [own]

**Additional context**
n8n@0.124.0 breaking or giving bad gateway on the docker image - reverted to n8n@0.123.1 twice and it worked

**Comment by janober** [comment]
Do not understand the referenced instructions. You pull an image but then start n8n with `sudo docker-compose up -d`. How does the docker-compose file look like that you use?
For me and other users that version seems to work fine so there must be something special in your case and the docker-compose file will probably be able to give that answer.

**Comment by wmuza** [comment]
Thank you, here is the [docker image code](https://snippets.wilbertzgroup.com/snippet/cTi1bz-EqaYFi1J3eXNdd)

**Comment by janober** [comment]
Thanks. And just to be sure. Does it also fail to start if you start with a totally empty database? Because if not, then it will not be possible for us to reproduce this issue.

And do you have two different issues? It breaking or giving a bad gateway (from the description)? If so what happens in the none gateway issue case?

**Comment by janober** [comment]
We also just released n8n@0.124.1 which fixed a bug. You can try that version maybe this also fixes your issue.

**Comment by wmuza** [comment]
n8n@0.124.1 has no issue, its running smooth now

**Comment by janober** [comment]
Ah, that is great to hear that this also fixed your issue. 

Have fun!
