### ISSUE TITLE
Redis connection doesn't support TLS

### ISSUE THREAD

**Issue by amity0** [n8n-io/n8n#1926]
**Describe the bug**
I am unable to connect to redis with tls, there isn't an option to set tls: true and pass ca.pem

The server throws:
```
Error with Redis: 
```

ioredis support tls. see here: https://github.com/luin/ioredis#tls-options

**To Reproduce**
Try to connect to redis with tls

**Environment (please complete the following information):**
 - OS: Kubernetes
 - n8n Version 0.118.1
 - Operation mode own

**Comment by janober** [comment]
Thanks a lot for reporting.

But sounds for me less like a bug, more like a feature request.

Can you please post it to:
https://community.n8n.io/

Thanks!
