### ISSUE TITLE
Nested Array iteration [object,object]

### ISSUE THREAD

**Issue by wifiuk** [n8n-io/n8n#1954]
**Describe the bug**
When iterating nested result from an array into google sheets the output on the google sheet is processed oddly.

**To Reproduce**
Get a nested array JSON as your output and map it to a google sheet the results are like this:

![image](https://user-images.githubusercontent.com/3785545/123797292-f08bd500-d8dd-11eb-976e-909c58e1dfac.png)

**Expected behavior**
The nested arrays to show as separate results in the cell

![image](https://user-images.githubusercontent.com/3785545/123797442-174a0b80-d8de-11eb-841d-af441cbd3506.png)

**Environment (please complete the following information):**
latest:latest docker

**Comment by ivov** [comment]
Can you provide an example workflow to reproduce?

**Comment by ivov** [comment]
Closing for now. If this persists, feel free to comment here and we will reopen.
