### ISSUE TITLE
Importing workflow downloaded from IHM fails

### ISSUE THREAD

**Issue by jrmi** [n8n-io/n8n#1955]
**Bug description**

When downloading a workflow from the frontend, the exported json contains the key as a string:

```json
{
  "id": "2",
   ...
}
```

That's prevent for importing it later with CLI with error:

```
An error occurred while exporting workflows. See log messages for details.
SQLITE_CONSTRAINT: UNIQUE constraint failed: workflow_entity.id
```
Note: the message tell "exporting workflows" but that's an other error from the code [here](https://github.com/n8n-io/n8n/blob/38f0cc1a8f53c80d48d2b1d754f2faa0c406cfec/packages/cli/commands/import/workflow.ts#L85).

**To Reproduce**

1. Open any workflow
2. Click on 'Download' and save the generated json file
3. Try to import it via CLI by executing: `n8n import:workflows  --input=_youfile_.json`

**Expected behavior**

Should export the workflow with the id as a number:

```json
{
  "id": 2,
   ...
}
```

To be able to reimport it without modification.

**Environment:**
 - OS: Docker image n8nio/n8n
 - n8n Version: 0.126.1
 - Node.js Version: 14.15.5
 - Database system: SQLite

**Comment by janober** [comment]
Fix got released with n8n@0.128.0
