### ISSUE TITLE
Unable to reset community.n8n.io password

### ISSUE THREAD

**Issue by dokime7** [n8n-io/n8n#1962]
Sorry to create issue here but I'm blocked because the mails of password reset are sent many hours later (or never) and the link is already expired.
Could you see what's happening?
Thanks

**Comment by janober** [comment]
Sorry to hear that you have problems.

Can sadly not see anything. As you did not share your user name do I assume you did choose the username "dokime7" as it is on GitHub. Sadly does no such user exists.

In the future, for you and other people that have the same problem, please write to `hello@n8n.io` if it is n8n.io related or `hello@n8n.cloud` if n8n.cloud related. Thanks!

**Comment by dokime7** [comment]
OK, thanks, I will contact hello@n8n.io
