### ISSUE TITLE
Duplicated workflow with Webhook can not be activated

### ISSUE THREAD

**Issue by dploeger** [n8n-io/n8n#1967]
**Describe the bug**
After duplicating a workflow, that uses a Github Trigger, node it can't be activated.

**To Reproduce**
1. Create a workflow and add a Github trigger node to it
2. Save and activate it
3. Duplicate it
4. Change the repository in the Github trigger
5. Save and activate it
6. See error:

> There was a problem and the workflow could not be activated:
> Duplicate entry '<redacted guid>/webhook-POST' for key 'PRIMARY'

**Expected behavior**
The duplicated workflow can be executed

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version: 0.125.0
 - Database system: MySQL 5.7.34
 - Operation mode: own

**Comment by krynble** [comment]
Hey @dploeger 

Thank you for reporting this.

I created a PR with a fix and therefore will be closing this issue. You can find the PR progress here: https://github.com/n8n-io/n8n/pull/2098

**Comment by dploeger** [comment]
Thanks a lot!

**Comment by janober** [comment]
Got released with 0.135.0

**Comment by dploeger** [comment]
Works like a charm. Thanks.
