### ISSUE TITLE
Invoice Ninja -alpha 2 or alpha 3- country code values not supported

### ISSUE THREAD

**Issue by victorburgos12** [n8n-io/n8n#1982]
**Describe the bug**
When using invoice ninja node, if I select the option to create a client and want to assign billing address, the Country field asks for country code, for example PE for Peru or CO for Colombia.

However, if I put PE or CO, or US manually on the field, there is a warning indicating that the value is not supported.

![image](https://user-images.githubusercontent.com/37320468/125182368-1f098a00-e1d3-11eb-8449-7c60897ff56a.png)

I just checked the source code file where country codes are defined: https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/InvoiceNinja/ISOCountryCodes.ts

According to this file it should accept either, Alpha 2, Alpha 3 or numeric but it only works if I put the country in numeric UN M49 code number ( 604 for Peru or 170 for Colombia).

I think it should accept either, Alpha 2, Alpha 3 or numeric.

On my application, I receive the country codes in Alpha 2, for example: US, AU, CO
Is this how it is suppose to work?

**Comment by janober** [comment]
Sorry, but it is currently simply not possible to have two different lists in n8n. That would result in every option (in this case country) being displayed twice. But if you say that the REST API accepts the country code in the format you supply, then all should be fine. You can ignore that warning. The node should still execute totally fine.

**Comment by janober** [comment]
I am closing this issue for now as I did not hear back and the above workaround should fix this problem. If you have problems simply comment here again. Thanks!
