### ISSUE TITLE
several nodejs packages are deprecated

### ISSUE THREAD

**Issue by RMHogervorst** [n8n-io/n8n#1994]
**Describe the bug**
I have no experience with nodejs, but I think you should update the dependencies?
This is what my raspberry pi is saying:

```
npm install n8n -g
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
```

**To Reproduce**
1. Install nodejs
2. install n8n

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04] raspbian
 - n8n Version [e.g. 0.119.0]  don't know yet, still installing
 - Node.js Version [e.g. 14.16.0] https://deb.nodesource.com/node_14.x buster/main armhf nodejs armhf 14.17.2-1nodesource1 [22.9 MB]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by David-Hari** [comment]
It also won't work on NodeJS v16 and seems to use a *very* old version of node-gyp.

**Comment by Joffcom** [comment]
Hey @RMHogervorst & @David-Hari,

I am just going through the issues we have opened and it looks like the some of this has been solved over the last year like support for Node v16. For now I am going to mark this one as closed as we are updating packages as required.
