### ISSUE TITLE
[feature request] Fliter events/actions in realtime

### ISSUE THREAD

**Issue by phanirithvij** [n8n-io/n8n#2]
**Feature:**
Searching **node related events** with realtime filtering while typing.

e.g: For the `Github Trigger` node
[image](https://user-images.githubusercontent.com/29627898/62630288-45ba4880-b94c-11e9-9a57-90efeb9cb5f3.png)

**Comment by phanirithvij** [comment]
I'd like to implement this. @janober what do you think about this.
1. Is this a good idea?
2. Can this be done easily?

**Comment by janober** [comment]
n8n is using Element (https://element.eleme.io) as UI LIbrary. For that field it uses an "el-select" with the "multiple" and "filterable" option. So it is theoretically set up to do the filtering already and it works for other fields which do not allow multiple options.
Sadly does it seem to make problems when both options are set at the same time. So to make it  work correctly actually a bug in Element would have to get fixed.

**Comment by phanirithvij** [comment]
I see.
Closing this.

**Comment by janober** [comment]
I open the issue again. I checked on Element if they already have a bug report for it. Did not find anything but found that issue: https://github.com/ElemeFE/element/issues/16559

Is not really related to this problem but it contains a link to a Codepen to show the problem they are talking about there. Anyway in that Codepen "multiple" and "filterable" seem to work together so something in the n8n code seems to mess it up. 

Btw. the code for that field can be found here:
https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/ParameterInput.vue#L57

**Comment by janober** [comment]
btw. could be quite possibly css related
