### ISSUE TITLE
Very long interval is evaluated as 1 second

### ISSUE THREAD

**Issue by Schnouki** [n8n-io/n8n#2007]
**Describe the bug**
While working on a big workflow, I added an Interval node, and set it to 960 hours (40 days). This caused n8n to crash, the Docker container it's running in to restart repeatedly, and to a 100% CPU usage on the host.

I only had a quick look in the logs (using `docker logs`) and saw that there was some error message about the interval being too small, and getting capped to 1 second. I understand that 960 hours converted to milliseconds causes an int32 to overflow, but it would be nice to just error out when this happens, instead of turning it to 1 second 😅

**To Reproduce**
1. Create a workflow that causes some CPU-intensive operations to run
2. Create an Interval trigger and set it to 960 hours
3. Save and activate your workflow
4. Try to run it: it will run every second instead of every 960 hours...

**Expected behavior**
The workflow should run correctly.
If it doesn't, an error should be displayed while setting the value, or the workflow should just stop running if the value is invalid. In any case, it should *not* cause n8n to use 100% CPU, and crash its Docker container repeatedly...

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2, running Docker 20.10.7
 - n8n Version: 0.126.0
 - Node.js Version: v14.15.5 (official n8n Docker image)
 - Database system: SQLite
 - Operation mode: own

**Comment by janober** [comment]
Thanks a lot for making us aware of that. Just got fixed:
https://github.com/n8n-io/n8n/commit/7c94ee3ccecb8373863fcf067fbaf3a49ab54a8b

Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.132.0

**Comment by Fadiabukhadrah** [comment]
Hello, I thank you very much dear.relu.
I have a Samsung phone a20s I have done a factory reset. Now I'm having trouble unlocking the phone because I forgot the email it was in.Is there a solution to this problem now how can open the phone again

**Comment by Schnouki** [comment]
@janober Thanks a lot, but I'm afraid this fix is incorrect: in my case, 960 hours is 82,944,000,000 milliseconds, way less than `Number.MAX_SAFE_INTEGER` (2**53 - 1, i.e. 9,007,199,254,740,991).

The [doc for `setInterval`](https://nodejs.org/api/timers.html#timers_setinterval_callback_delay_args) is actually quite specific:

> When `delay` is larger than `2147483647` or less than `1`, the `delay` will be set to `1`.

So here we should really check if `updateInterval` is less than 2147483647 (2**31 - 1, the max value for a signed 32bit integer), not `Number.MAX_SAFE_INTEGER`.

Thanks!

**Comment by janober** [comment]
Got changed.

**Comment by janober** [comment]
Got released with 0.135.0
