### ISSUE TITLE
N8n creates everygrowing files. How to delete unnecessary data via cronjob?

### ISSUE THREAD

**Issue by ascherren** [n8n-io/n8n#201]
Is there a possibility to clean up as much space as possible via a command like `docker system prune --all` to delete everything from the N8n logs/database that is not needed?

Currently I have an N8n instance within Docker with 10 Graphs and 4 API Connections with lots of executions (some graphs execute every minute). And the total storage need currently is 1 Gigabyte and growing daily by 50 Mb.
I already deleted the execution history, but that doesn't shrink the file size down.

**Comment by janober** [comment]
Can you please post your question here:
https://community.n8n.io/

I will then answer it asap.

GitHub issues are only for bugs.

**Comment by janober** [comment]
Here for reference the question in the forum:
https://community.n8n.io/t/n8n-creates-everygrowing-files-how-to-delete-unnecessary-data-via-cronjob/620/2
