### ISSUE TITLE
Mailchimp Trigger Active doesn't work.  Exec works fine.

### ISSUE THREAD

**Issue by shaneburrell** [n8n-io/n8n#2018]
**Describe the bug**
Mailchimp trigger will not go active. Exec works fine, once.  The webhook URL it creates always is the test version.   Exec works but going active 404 is returned "Unknown Problem" looks like it's getting confused about what webhook URL it is setting up when in Exec mode vs active mode.

**To Reproduce**
Create a Mailchimp trigger that works when executed but will not go active.  

**Expected behavior**
Expect it to go active successfully.

**Environment (please complete the following information):**
 - OS:  Ubuntu Linux 20.04
 - n8n Version 130

 - Operation mode own

**Additional context**
Works fine manual exec.
![Screen Shot 2021-07-22 at 3 27 11 PM](https://user-images.githubusercontent.com/673906/126698127-5d24fcc0-370b-4542-b961-8bc48ed6b263.png)
Error when trying to go active

![Screen Shot 2021-07-22 at 3 27 04 PM](https://user-images.githubusercontent.com/673906/126698128-4b405137-1872-4656-86f6-48c3562daa8a.png)

**Comment by janober** [comment]
I just tested. Works totally fine.

The only way I am able to reproduce the error you are seeing is by trying to subscribing to a list that does not exist (so setting an invalid ID for on the parameter "List"). Do you select the "List" via the dropdown or do you set the ID manually?

**Comment by shaneburrell** [comment]
I am using the list dropdown.  I have two lists' at mailchip and both do same. Both of the lists show as options on the dropdown.

**Comment by shaneburrell** [comment]
Manually exec works fine.  Trying to save as active does not.

**Comment by janober** [comment]
Thanks for that info. Very interesting. We will see if we can reproduce.

**Comment by ctholho** [comment]
I don't know why @shaneburrell closed this. I can reproduce this error.
Activating the workflow will prompt this error:
<img width="2177" alt="Screenshot 2022-02-28 at 14 03 10" src="https://user-images.githubusercontent.com/28910105/155988093-a8b467f1-c6a6-4747-b004-3ad46dbc688e.png">

**Comment by snapdragontechnical** [comment]
Did anyone manage to find a solution to this? I'm experiencing this same issue in n8n cloud. The Mailchimp trigger works perfectly when manually executed, but when I attempt to activate the workflow, I get the same error as ctholho and shaneburrell.

I'm new to n8n and so first ran into this on version 0.210.0. Interestingly, when I upgraded a few days ago to .1, the error message changed and now just says, "Workflow could not be activated: UNKNOWN ERROR - check the detailed error for more information" without additional details. (I'm now on .2 beta and getting the same, shorter error.)

**Comment by mwt** [comment]
Is this still broken or does it work now?
