### ISSUE TITLE
Install and execute "youtube-dl" in container n8n

### ISSUE THREAD

**Issue by tiger360** [n8n-io/n8n#2019]
Hello,
I am running n8n in **Docker**, the commands will run on the n8n container and not the Docker host.
So how can I run for example "**youtube-dl**" with n8n ?
The workflow I wanna do is : share a link to **Telegram trigger**, download with "youtube-dl" the video and then put it in **Jellyfin**, the  Media System.

Thanks

**Comment by janober** [comment]
As you could see in our GitHub issue template:
![Screenshot from 2021-07-23 09-13-35](https://user-images.githubusercontent.com/6249596/126748828-8f3f7abf-0c15-43c0-88a4-78bd77d50e49.png)

are GitHub issues only for bugs. If you have questions or problems please post them to the community forum:
https://community.n8n.io/

Thanks!
