### ISSUE TITLE
Gitlab Webhook Duplication

### ISSUE THREAD

**Issue by bruno-robert** [n8n-io/n8n#2042]
**Describe the bug**
When testing Gitlab Trigger nodes, duplicate webhooks are created.
The final result is the flow getting executed more than one time per action performed in Gitlab unless the duplicate webhooks are deleted from gitlab.

**To Reproduce**
1. Create a workflow 
2. Add and configure a Gitlab Trigger node
3. Save and deploy the workflow
4. In gitlab, open the project and navigate to "Settings > Webhooks" 
5. Notice a webhook was created
6. Test the Gitlab Trigger node by pressing on the "execute node" button above the Gitlab trigger node
7. Make a test request (either via postman, or in Gitlab)
8. Open the Gitlab trigger node and close it
8. Save the workflow
9. In gitlab, open the project and navigate to "Settings > Webhooks" 
10. The original webhook is now duplicated

**Expected behavior**
In Gitlab, there should only ever be one webook (with the same url) at a given time.

**Environment (please complete the following information):**
 - OS: Ubuntu server 20.04 running docker
 - n8n version: **n8nio/n8n:latest** or **n8nio/n8n:0.132.1-debian**
 - docker image full digest:  sha256:07b582d28dbec3725e57943a6f013f74cf77cacd6ef16d9151efe48705342631
 - Node.js Version 14.15.5
 - Database system SQLite
 - Operation mode default (own)

**Comment by constant-roussel** [comment]
Any updates on this issue or workaround ? I have the same issue and it makes difficult to suppress duplicated webhooks in each repo (I have multiples Gitlab Trigger nodes in a workflow)

**Comment by Joffcom** [comment]
Hey There,

Looks like I missed this one, Thanks for bringing it up in the other issue @mark-monteiro 👍🏻 

I have created an internal dev ticket to look into this issue and another issue that results in 404 errors when activating Gitlab triggers, We will be tracking this one as N8N-4829. I will be back as soon as we have pushed a fix.

**Comment by janober** [comment]
Fix got released with [`n8n@1.0.5`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.0.5)
