### ISSUE TITLE
Workflow name duplicates

### ISSUE THREAD

**Issue by pashkatrick** [n8n-io/n8n#2063]
**Describe the bug**
Available to create same name flows

**To Reproduce**
1. Go to top bar
2. Click on "My Workspace" naming field
3. Set the exsisting name
4. Save + See no error
5. ![image](https://user-images.githubusercontent.com/8003175/128570796-c1d426f9-553d-4375-aa54-d489f071bb64.png)

**Expected behavior**
Duplicate error

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version: 0.129.0
 - Node.js Version: 14.16.0

**Comment by janober** [comment]
I can not reproduce this issue and can not create workflows with the same name.

Also in your example above are the names actually different (one uses an upper-case and the other one a lower-case "b" for "bot").
