### ISSUE TITLE
Bug in merge node append mode

### ISSUE THREAD

**Issue by robertodamiani** [n8n-io/n8n#2111]
Hi,

by documentation the append mode of the merge node should output the concatenation of the two lists in input.

This seems to work only if the first input is not empty (tested in 0.134.0):
* if both inputs are not empty, the result is the concatenation of the inputs
* if the first input is not empty and the second one is empty, the result is the first input
* if the first input is empty and the second one is not empty, te result is an empty list

In the third case, I expect that the output is the second input, and not an empty list,.

Here is an example workflow:

```
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "return [];"
      },
      "name": "Empty",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        510,
        260
      ]
    },
    {
      "parameters": {
        "functionCode": "return [{\njson: {\nvalue: \"item value\",\n}}];"
      },
      "name": "Non-Empty",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        510,
        430
      ]
    },
    {
      "parameters": {},
      "name": "Merge",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        790,
        340
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Empty",
            "type": "main",
            "index": 0
          },
          {
            "node": "Non-Empty",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Empty": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Non-Empty": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 1
          }
        ]
      ]
    }
  }
}
```

Thank you.

**Comment by janober** [comment]
That has sadly nothing to do with the Merge-Node, rather than with n8n works generally. If a node does not have any data to process, it does not run. So each node has to receive at least one item on its first input.

So it is on the user to make sure that the first input of the Merge-Node always receives at last one item. That can be done with for example activating "Always output data" on the node before it. That will so obviously result in empty items that then sadly have to be filtered out again.

**Comment by robertodamiani** [comment]
Hi @janober, thanks for the quick reply.

I figured out that this was the problem just after opening this issue, but I decided to leave it opened because this behavior still seems incorrect to me.

As you say, this is sadly, but the question is "why" is sadly. The reason is that, in this scenario, the first input has nothing more special than the second. They are equivalent, and should not be threaten differently.
I understand that is a "by design" behavior, but this scenario suggests to extend the design to allow a coherent behavior as expected by users.

For example I may suggest the following for multiple input nodes:
* change the behavior so that, if at least one input is not empty, the node is triggered (so change the check to all nodes instead of only the first)
* alternatively, add a node property to allow these kind of scenarios. For example a "triggerOnNoInput", making the node triggered also if no input is passed, or "optionalInputs", a list of inputs which will be ignored if empty, making the node triggered

Please apologize if I replied to a closed issue, I was not fast enough to make a reply.

Thank you again.

**Comment by janober** [comment]
Yes totally agree! This is definitely something we will reevaluate in the future. Right now this would however be something that could break the workflows of people and needs generally some deeper thinking. We have to make sure that not one thing gets improved but something else gets harder. Also that not other unforeseen side-effects arise.

**Comment by robertodamiani** [comment]
Ok @janober, I understand and makes sense to me.

Thank you!

**Comment by janober** [comment]
Glad to hear! We have planned to at some point (probably together with the release of n8n v1) to also change some behavior. That will be combined with creating workflows of version 2 (all currently created workflows would be v1). That will then allow to not break existing workflows. "Old" (v1) workflows would then be executed according to old (current) rules and "new" (v2) workflows could behave differently.
