### ISSUE TITLE
joseph.lent@my.tccd.edu

### ISSUE THREAD

**Issue by nnd16** [n8n-io/n8n#2118]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.119.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by ivov** [comment]
Likely opened in error. Closing. Let us know otherwise.
