### ISSUE TITLE
Imap Email Trigger attachment 

### ISSUE THREAD

**Issue by richilp** [n8n-io/n8n#213]
Hello guys,

we're using the Imap Email Trigger to get the body and other info without problems. It works great. Even the attachment get download as binary without problems.

The problem is retriving the download file from others nodes, for example Telegram.
If we attach the download file as image to Telegram it reports as error because is not a valid url.

What's the way to access the downloaded file from the email to use it elsewhere?

Thanks !!

**Comment by janober** [comment]
Can you please post the question to https://community.n8n.io
I will then answer asap.

The Github Issues are only for bugs like described here:
https://github.com/n8n-io/n8n/issues/new/choose
Thanks!
