### ISSUE TITLE
Error Forbidden perhaps check your credentials InvoiceNinja

### ISSUE THREAD

**Issue by rodrigomeyer** [n8n-io/n8n#2134]
Hi, the API InvoiceNinja updated 

X-Ninja-Token to X-Api-Token

https://github.com/n8n-io/n8n/blob/69745c93d8002538c06246cdcdd2aacc68c90dc7/packages/nodes-base/nodes/InvoiceNinja/GenericFunctions.ts#L30

**Comment by RicardoE105** [comment]
Related to #1776

**Comment by jjrich** [comment]
Unable to connect to self-hosted Invoice Ninja 5 - Invalid Token. Any updates on this issue?

**Comment by Joffcom** [comment]
Hey @jjrich & @rodrigomeyer,

It looks like we missed the notification on this one, We fixed this a couple of months ago in `n8n@0.200.0` so you should be good to go.

I am going to mark this one as closed for now.
