### ISSUE TITLE
Unable to connect to n8n in Docker container after upgrade from 0.123.1 to 0.135.2

### ISSUE THREAD

**Issue by TimothyVermeirenBiztory** [n8n-io/n8n#2138]
**Describe the bug**
We've performed an upgrade of n8n in Docker as we've done a dozen times before. We always follow [the suggestions here](https://community.n8n.io/t/how-to-upgrade-n8n-with-docker-compose-setup/660), and this has always worked well.

The container does go up:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
2a2682857a01        n8nio/n8n           "tini -- /docker-ent…"   9 seconds ago       Up 4 seconds        127.0.0.1:5678->5678/tcp   n8n_n8n_1
```

However, it's impossible to reach it or connect to it (also after waiting for several minutes):

```
timothy.vermeiren@biztory-application-server:/opt/n8n$ curl http://localhost:5678
curl: (52) Empty reply from server
timothy.vermeiren@biztory-application-server:/opt/n8n$ curl http://localhost:5678
curl: (56) Recv failure: Connection reset by peer
```

**To Reproduce**
(See above)

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04 w/ Docker 19.03.13
 - n8n Version 0.135.2

**Additional context**
The docker-compose logs:

```
Attaching to n8n_n8n_1
n8n_1  | Initializing n8n process
n8n_1  |
n8n_1  | n8n now checks for new versions and security updates. You can turn this off using the environment variable N8N_VERSION_NOTIFICATIONS_ENABLED to "false"
n8n_1  | For more information, please refer to https://docs.n8n.io/getting-started/installation/advanced/configuration.html
n8n_1  |
```

Happy to provide additional troubleshooting information upon request!

**Comment by TimothyVermeirenBiztory** [comment]
Oh, wow, apologies. It did take quite a bit longer than previously, but all good now. My mistake!

**Comment by janober** [comment]
Glad to hear that it works now. Have fun!
