### ISSUE TITLE
SQLITE_BUSY error after retrieving credentials

### ISSUE THREAD

**Issue by matt-laird** [n8n-io/n8n#2145]
**Describe the bug**
When a node that utilises a credential (e.g. HTTP) is called an error occurs on the Type ORM layer, when the node tries to retrieve the credential from the DB, in this case the SQLite DB. This results in the SQLite error, SQLITE_BUSY. The issue seems to exhibit itself after a second call or after multiple calls.

**To Reproduce**
Steps to reproduce the behaviour:
1. Simply execute a node that utilises a credential once
2. Then again, multiple times (> 1)
3. Observe SQLITE_BUSY error.

**Expected behaviour**
Call chain of multiple nodes that utilise credentials should retrieve from the DB without encountering error.

**Environment (please complete the following information):**
 - OS: Raspbian Linux 10 - Docker Container
 - n8n Version - 0.135.3
 - Node.js Version - internal to docker image
 - Database system - SQLite
 - Operation mode - own

**Additional context**
See below:
![Screenshot 2021-08-28 233255](https://user-images.githubusercontent.com/14907718/131231566-89324970-8cbb-4424-98ff-b81239d4fdc2.jpg)

**Comment by krynble** [comment]
Hey @matt-laird 

I am sorry you are facing this issue.

This is somewhat expected for a busy n8n instance. The error you are facing means that there are too many attempts to write and/or read data from the database simultaneously.

We recently released a change for loading the credentials from the database always, which can aggravate the problem or cause it, if not existent.

Is your n8n instance running multiple executions simultaneously? if so, I would recommend you switching to a more powerful database system such as Postgres. This will certainly resolve the problems you are facing.

Let me know if this helps and feel free to provide more information.

**Comment by janober** [comment]
Alternatively to Postgres could you also run n8n in "main" mode. Like that will it run all executions in the main process and the problem can so also not occur.
You can find more information about that [here](https://docs.n8n.io/getting-started/installation/advanced/configuration.html#examples).

**Comment by matt-laird** [comment]
Great thanks for the suggestions guys, both points make sense and will be investigating further. Are there plans to maybe drop SQLite at this rate, as this would potentially confuse some new users?

**Comment by krynble** [comment]
Hey @matt-laird 

As a hit, you can use the command line to migrate your existing workflows and credentials from a database to another.

In regards to dropping SQLite, actually this is a great feature as it's simple and non-techy users can easily use it and understand. Asking people to always deploy a database system can make it harder for new users.

For this reason, we will continue using SQLite as the main database.

**Comment by matt-laird** [comment]
Hey @krynble, that is a very good point, I completely agree I never thought of it that way. Is there some documentation for migration of workflows?

**Comment by krynble** [comment]
Sure there is :)

You can find it here: https://docs.n8n.io/reference/start-workflows-via-cli.html#export-workflows-and-credentials

I will be closing this issue for now but feel free to comment or reopen if necessary!
