### ISSUE TITLE
field 'createdat' doesn't have a default value

### ISSUE THREAD

**Issue by llaumgui** [n8n-io/n8n#2146]
**Describe the bug**
When I try to save a workflow or add a tag :

```
There was a problem saving the workflow: "field 'createdat' doesn't have a default value"
```
**To Reproduce**
1. Go to new workflow
2. Click on save.

**Expected behavior**
Save work.

**Environment (please complete the following information):**
 - OS: docker n8nio/n8n image
 - n8n Version  0.135.3
 - Node.js Version [e.g. 14.16.0]
 - Database system MariaDB 10.1

**Comment by llaumgui** [comment]
Issue seem from 0.122.x.  0.121.1 works fine

**Comment by mutdmour** [comment]
@llaumgui thanks for sharing. Closing this since it has already been fixed.

**Comment by llaumgui** [comment]
Nice, is there a commit or a version fixed ?

**Comment by mutdmour** [comment]
sorry I misunderstood your comment. Will take a look again.

**Comment by llaumgui** [comment]
Hum, I've fixed this. It's a DB update not entire passed.
