### ISSUE TITLE
Several telegram trigger nodes with error

### ISSUE THREAD

**Issue by pashkatrick** [n8n-io/n8n#2156]
**Describe the bug**
Error: 
`There was a problem and the workflow could not be activated:
SQLITE_CONSTRAINT: UNIQUE constraint failed: webhook_entity.webhookPath, webhook_entity.method`

![image](https://user-images.githubusercontent.com/8003175/131549208-94fbb935-9a38-4bc8-902f-7b127095cb4c.png)

**To Reproduce**
1. Create a workflow with telegram trigger node
2. Save it and activate
3. Create new workflow with telegram trigger node
4. And try to activate it

**Expected behavior**
Works both

**Environment (please complete the following information):**
- OS: Ubuntu Linux 20.04
- n8n Version: 0.129.0
- Node.js Version: 14.16.0

**Comment by pashkatrick** [comment]
@janober

**Comment by janober** [comment]
Did you try to delete the Telegram Trigger node and then recreate it.

Looks like the node did get duplicated and has so the same internal ID as another one that is already active.

**Comment by pashkatrick** [comment]
Yep, it was help, sorry
