### ISSUE TITLE
Wrong timezone in completed workflows in Workflow Executions since n8n:0.131.0 with PostgreSQL

### ISSUE THREAD

**Issue by auntieyi** [n8n-io/n8n#2178]
**Describe the bug**
When we set the timezone in env:
      - GENERIC_TIMEZONE=Asia/Hong_Kong
      - TZ=Asia/Hong_Kong

The timezone in the running workflows are correct (see first 2 rows in the screenshot below), but after completed it showing the time in wrong timezone (see 3nd row in screenshot below). 

![image](https://user-images.githubusercontent.com/1725966/132317631-3d4f8b98-1a33-4d64-9c57-ca98637e0633.png)

**To Reproduce**
1. Set GENERIC_TIMEZONE, TZ in env
2. Click on 'Executions'
3. See error

**Expected behavior**
The completed workflows should keep in correct timezone.

**Environment (please complete the following information):**
 - OS: CentOS 7
 - n8n Version: 0.137.0
 - Docker version: 19.03.1

**Comment by marcofucito** [comment]
If I'm not mistaken, with an old version of n8n, it also marked an incorrect time zone to me despite having set the time zone in the docker.

With the latest current version, n8n@0.141.0, the time reported in the execution tab, correctly respects the set time zone.

**Comment by auntieyi** [comment]
@marcofucito 
I tried n8n@0.141.0, the problem still persists.
The old version of n8n do not have this problem, the problem after I update the n8n to v0.137.0.
And I found that the wrong timezone issue if I use postgresdb in n8n. 
    environment:
      - DB_TYPE=postgresdb

**Comment by auntieyi** [comment]
I guess there is an update after v0.128.0, this caused the incorrect timezone.
https://docs.n8n.io/reference/changelog.html#n8n-0-128-0
Performance improvement for loading of historical executions (> 3mil) when using Postgres. 

@janober hope you have time to look into this. Thanks

**Comment by auntieyi** [comment]
The timestamp changed to use timestamptz that caused the problem since 0.131.0.
https://github.com/n8n-io/n8n/compare/n8n@0.130.0...n8n@0.131.0#diff-22fc99be9309a8b7f569bab560c0e04ce308a1200d724a6c748ee922b4e79117
![image](https://user-images.githubusercontent.com/1725966/135769647-acf5eb09-c2b0-4c82-8810-6912ab72eff6.png)

**Comment by auntieyi** [comment]
@ivov Is it safe if I change back to use timestamp? I hope you can give me advice, thanks.

**Comment by ivov** [comment]
Column type was switched to `timestamptz` for UTC storage, so it is not advisable to revert. Timestamps are being correctly stored in UTC in PG; the issue seems to be caused during retrieval via TypeORM.

**Comment by auntieyi** [comment]
Thanks your advice @ivov.
I have altered all existing timestamp column to type timestamptz in PG.
The problem seems to be solved.

**Comment by Joffcom** [comment]
Just going to leave a note here to say that internally this has a tracking reference of `n8n-2490`.

**Comment by Joffcom** [comment]
Good news, This should now be fixed in `1.9.0`. For now I am going to mark this as closed if you are still seeing this let me know and we can open it again.
