### ISSUE TITLE
N8N Shell Command module displaying random behavior when environment variables are modified

### ISSUE THREAD

**Issue by tl-Bruno-Braga** [n8n-io/n8n#2181]
**Describe the bug**
I have a workflow that involves querying AWS. For this i need to assume a role. I am using N8N with Kubernetes and Kube2iam to have the proper creds injected into the container.

I am running into an intermittent issue where basically AWS cli command used to assume role is failing with: 

`Unable to locate credentials. You can configure credentials by running "aws configure". `

The command i am using is:

```
ASSUMERULERESULT=$(aws sts assume-role --role-arn "[ROLE_ARN_TO_BE_ASSUMED]" --role-session-name AWSCLI-N8N-Session --output text --query='Credentials.[[join(`=`,[`AWS_ACCESS_KEY_ID`,AccessKeyId])],[join(`=`,[`AWS_SECRET_ACCESS_KEY`,SecretAccessKey])],[join(`=`, [`AWS_SESSION_TOKEN`, SessionToken])]]')
AWSENVVARIABLES=$(echo "$ASSUMERULERESULT" | tr ' ' '\r\n')
for i in $AWSENVVARIABLES
do
	export "$i"
done
...query dynamo...
```

This error i mention is intermittent which makes it harder to resolve. I am using single process mode and not parallel workflows. 

**To Reproduce**
1. Deploy N8N in single process mode as a container in kubernetes and use kube2iam to assume the proper role and get creds
2. Run command above or similar
3. See error (maybe?)

**Expected behavior**
I would expect the command to run all the time.

**Environment (please complete the following information):**
 - N8N helm chart version 0.5.0 (https://github.com/8gears/n8n-helm-chart)
 - Database system: postgres
 - Operation mode: main

**Additional context**
- This could be a problem with kube2iam. However, given that i am getting mostly successes but some errors in the middle, i assume this must be some n8n detail that i am not grasping
- Do you guys see any potential issues with my approach? Since the workflow is executed in the same process? If you parallelize using threads, i can see a problem where variables are being overwritten while being used. 
- Since i need to renew this creds every couple of minutes, do you recommend a cleaner way?

**Comment by Joffcom** [comment]
Hey @tl-Bruno-Braga,

Sorry for the delay on this one, I assume by now you may have worked out what is going wrong. Looking at the error you are getting it doesn't look to be an issue with n8n and is probably more environmental.

If you are still seeing this I would recommend opening a post on the community support forum which can be found here: https://community.n8n.io and we can see if the wider community there has any thoughts on what could be missing in the deployment. For now though I am going to mark this one as closed.
