### ISSUE TITLE
Cannot push newly created nodes

### ISSUE THREAD

**Issue by quansenB** [n8n-io/n8n#2192]
I created 3 nodes and want to open a PR for them. 

Unfortunately I cannot push them. 
When running this command:
`git push --set-upstream origin quansenB`

I get this error: 
```
remote: Permission to n8n-io/n8n.git denied to quansenB.
fatal: unable to access 'https://github.com/n8n-io/n8n.git/': The requested URL returned error: 403
```

Do I need to get approved first?

**Comment by mutdmour** [comment]
@quansenB Thanks for making a contribution. You need to create a fork of n8n first and create a PR from the fork. You can find more information here
https://github.com/n8n-io/n8n/blob/d86cbc9f015fd1781ba7b7d65e82c8b499e6135f/CONTRIBUTING.md#actual-n8n-setup
https://guides.github.com/activities/forking/#fork
