### ISSUE TITLE
Add missing filter option for Unknown and Unknown Retried

### ISSUE THREAD

**Issue by ad-si** [n8n-io/n8n#2195]
**Describe the bug**

The execution list has following filter options:

![image](https://user-images.githubusercontent.com/36796532/132872679-221340af-9cd3-4e4d-873d-168eee46f678.png)

, but there are 2 more available states:

![image](https://user-images.githubusercontent.com/36796532/132872876-a49fad3c-fc16-4a41-8325-707ea77d9b97.png)

**Expected behavior**

There should filter options for **all** available states.

**Environment (please complete the following information):**
 - n8n Version: 0.134.0
 - Database system: Postgres

**Comment by mutdmour** [comment]
Makes sense. Will open a PR to add a filter for this soon.. Though possibly just for `Unkown` rather than `Unkown` and `Unkown retried`

**Comment by Joffcom** [comment]
Hey @ad-si,

It looks like this didn't make it into the recent execution view overhaul but I have created an internal ticket which we will be tracking as `N8N-5965`.

**Comment by flipswitchingmonkey** [comment]
With the recent changes `unknown` should(tm) not show up any more since n8n now better identifies the state of an execution and assigns the `failed` state to crashed executions.

**Comment by janober** [comment]
Fix got released with `n8n@0.217.1`
