### ISSUE TITLE
Executions list only shows "Unknown" status

### ISSUE THREAD

**Issue by JinxuWang** [n8n-io/n8n#2245]
Describe the bug
The list of executions only shows the status "Unknown" and the tooltip says "The workflow execution is probably still running but it may have crashed and n8n cannot safely tell."
![image](https://user-images.githubusercontent.com/82506758/134640598-0084fa74-806d-403b-b421-21a86bc7ff2b.png)

To Reproduce

Plan the execution of a workflow using a Execute Workflow
Wait until the execution has been run
Show the list of executions
See error
Expected behavior
The list of executions show wether the workflow was run successfully.

Environment (please complete the following information):

OS: Docker Image
n8n Version 0.137.0
Node.js Version bundled with docker image

**Comment by JinxuWang** [comment]
![image](https://user-images.githubusercontent.com/82506758/134641113-d35e3f3e-e58e-47c3-b199-647dd70970b1.png)
workflowId:2

**Comment by JinxuWang** [comment]
![image](https://user-images.githubusercontent.com/82506758/134641113-d35e3f3e-e58e-47c3-b199-647dd70970b1.png)

workflowId:2
![image](https://user-images.githubusercontent.com/82506758/134641191-2bd0dd3b-adb2-40be-acd0-9299463e4064.png)
workflowId:3

**Comment by JinxuWang** [comment]
workflowId:1
![image](https://user-images.githubusercontent.com/82506758/134641552-660c5abc-39ad-410d-a9e3-81d87acf80ae.png)
workflowId:2
![image](https://user-images.githubusercontent.com/82506758/134641631-5d40f139-3f83-4b0b-966d-00c88d5f8997.png)
workflowId:3
![image](https://user-images.githubusercontent.com/82506758/134641698-b054c07e-fd41-48a0-a7b3-de98929acef9.png)
![image](https://user-images.githubusercontent.com/82506758/134641738-5bf81934-d0a1-49b8-8e73-8c2763f3636c.png)
workflow: ffff
![image](https://user-images.githubusercontent.com/82506758/134641861-6b970ef3-37c0-403a-ac1c-10bdd1c6c0ef.png)

**Comment by janober** [comment]
Seems like you deleted some of the questions we ask. Please also fill them in, thanks!

 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Comment by JinxuWang** [comment]
Database system: mysql 8.0
Operation mode: own

**Comment by BHesseldieck** [comment]
@JinxuWang can you upgrade your system to the latest version and confirm that the issue still exists?
Thank you!

**Comment by ivov** [comment]
@JinxuWang Are you still facing this issue after upgrading?

**Comment by Joffcom** [comment]
Hey @JinxuWang,

I am going to mark this one as closed for now, If you are still seeing an issue let me know and we can look at opening it again.
