### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [n8n-io/n8n#2248]
Hey there!

I belong to an open source security research community, and a member (@thelabda) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by janober** [comment]
Thanks a lot for making us aware of that. I did just add a basic version of that file:
https://github.com/n8n-io/n8n/blob/master/SECURITY.md

Looking forward to hear from you or @thelabda!
