### ISSUE TITLE
Google contact oauth token expiring

### ISSUE THREAD

**Issue by WilliamPeralta** [n8n-io/n8n#2264]
**Describe the bug**

**To Reproduce**
the workflow works correctly for a few minutes after which it starts to give authentication problems.
If I do "recconect" on the credentials it starts working again.
I think a refresh token is not done before the request.
Thank you guys

**Expected behavior**
the token should always be refreshed

**Environment (please complete the following information):**
 - OS: Ubuntu Linux  20

```
{
   "message":"Request failed with status code 401",
   "name":"Error",
   "stack":"Error: Request failed with status code 401\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
   "config":{
      "url":"https://people.googleapis.com/v1/people:createContact",
      "method":"post",
      "data":"{\"names\":[{\"familyName\":\"Alam\",\"givenName\":\"* Md xxx\",\"middleName\":\"\"}],\"organizations\":[{\"current\":false,\"domain\":\"\",\"name\":\"Autoscuola xxx\",\"title\":\"Student\"}],\"phoneNumbers\":[{\"type\":\"main\",\"value\":\"35xxx1\"}],\"memberships\":[{\"contactGroupMembership\":{\"contactGroupResourceName\":\"contactGroups/xxxxx\"}}]}",
      "headers":{
         "Accept":"application/json",
         "Content-Type":"application/json",
         "Authorization":"Bearer xxxx",
         "User-Agent":"axios/0.21.4",
         "Content-Length":328
      },
      "transformRequest":[
         null
      ],
      "transformResponse":[
         null
      ],
      "timeout":300000,
      "xsrfCookieName":"XSRF-TOKEN",
      "xsrfHeaderName":"X-XSRF-TOKEN",
      "maxContentLength":-1,
      "maxBodyLength":-1,
      "transitional":{
         "silentJSONParsing":true,
         "forcedJSONParsing":true,
         "clarifyTimeoutError":false
      }
   }
}
```

**Comment by janober** [comment]
Can you please make sure to answer all the questions in our template. We put them in there because only like that can we help. Especially about which n8n version you are using.

**Comment by beyondlevi** [comment]
I'm having the same issue with all Google apps that authenticates with oAuth2. If we do reconnect at the credential edit page it works back for 1 hour.

**Comment by janober** [comment]
Please try again with the just released n8n@0.141.0

**Comment by marcofucito** [comment]
Thanks, I updated to n8n@0.141.0 at the exact moment it came out and the Google Oauth token has never expired since.
This is therefore 30 hours of uninterrupted operation.

Thanks for the fix

**Comment by WilliamPeralta** [comment]
@janober also for me everything is fine now, thank you very much for the intervention and sorry for not completing the request template, it is my first time that I write an issue and my english is not very good.

**Comment by ivov** [comment]
Closing as resolved.
