### ISSUE TITLE
Ui shows wrong default value

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#2271]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/44057030/135609822-b48a3176-35be-4c74-9d8c-ac8e5b761e72.png)
The workflow is also saved.
![grafik](https://user-images.githubusercontent.com/44057030/135610238-2096320e-e492-4ecb-a099-9976918a8e04.png)

**To Reproduce**
1. Set saveDataManualExecutions to true
2. Look into the settings

**Expected behavior**
Shouldn't it say yes then?

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version  0.141.0 
 - Node.js Version v14.15.1
 - Database system Postgres 13
 - Operation mode main

**Comment by mutdmour** [comment]
thanks @lublak for reporting. looking into this

**Comment by janober** [comment]
The issue got fixed and merged. Will be released with the next version.

**Comment by janober** [comment]
Fix got released with n8n@0.142.0
