### ISSUE TITLE
RSS 2.0 Namespaces are not supported

### ISSUE THREAD

**Issue by Taknok** [n8n-io/n8n#2276]
**Description of the bug**
The RSS 2.0 specification allow to [extend the feed with namespaces](https://validator.w3.org/feed/docs/rss2.html#extendingRss). Those namespaces are not return in the JSON/Table as mentioned here: https://community.n8n.io/t/rss-node-doesnt-return-all-elements/2554

**To Reproduce**
1. Create an RSS Read
2. Use link: https://www.youtube.com/feeds/videos.xml?channel_id=UCftwRNsjfRo08xYE31tkiyw
3. Execute
4. Cannot see `media:group`

**Expected behavior**
JSON return should have keys and subkeys according to the namespaces.

**Environment:**
 - n8n Version : 0.141.1

**Comment by janober** [comment]
Makes total sense. If you are interested in that feature please open a Feature Request in the forum. Depending on the interest can we then prioritize it accordingly. Thanks a lot!
