### ISSUE TITLE
Function JSON values does not get updated in a retry

### ISSUE THREAD

**Issue by calvintwr** [n8n-io/n8n#2303]
**Describe the bug**
When retrying an execution, the function nodes does not seem to be executed. Rather, old values are used.

**To Reproduce**
1. Create the following workflow:

```json
{
  "name": "retry-demo",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "// Code here will run only once, no matter how many input items there are.\n// More info and help: https://docs.n8n.io/nodes/n8n-nodes-base.function\n\n// Loop over inputs and add a new field called 'myNewField' to the JSON of each one\nfor (item of items) {\n  item.json.myNewField = 1;\n}\n\n// You can write logs to the browser console\nconsole.log('Done!');\n\nreturn items;"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        430,
        540
      ]
    },
    {
      "parameters": {
        "path": "test2",
        "options": {}
      },
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        270,
        540
      ],
      "webhookId": "1b08931a-7487-4e52-a393-de127f308bb7"
    },
    {
      "parameters": {
        "functionCode": "throw Error('Foo')"
      },
      "name": "Function1",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        580,
        540
      ]
    }
  ],
  "connections": {
    "Function": {
      "main": [
        [
          {
            "node": "Function1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Webhook": {
      "main": [
        [
          {
            "node": "Function",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {}
}
```
2. Save it.
3. Open a browser and trigger the webhook url "https://n8n.greyandsanders.com/webhook/test2"
4. Open "Executions" to see that the workflow has errorred. This is expected.
5. Open up "Function" node and change `item.json.myNewField` to any value, say 2:
```js
item.json.myNewField = 2
``` 
6. Save the workflow.
7. Open "Executions". Select "Retry with currently saved workflow".
8. Open up the failed workflow. See that `item.json.myNewField` still retains the value of 1.
![Screenshot 2021-10-09 at 9 51 43 PM](https://user-images.githubusercontent.com/6825277/136660976-3f4991b3-376b-445a-ae2f-5730ddc139f9.png)

**Expected behavior**
`item.json.myNewField` should a new value of 2.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - n8n Version 0.142.0
 - Node.js Version 16.1.0
 - Database system SQLite
 - Operation mode Own

**Additional context**
Nil

**Comment by janober** [comment]
Yes, that is expected. The reason is that the retry starts the workflow from the last successfully executed node. As the Function-Node you changed, was successfully executed, will it not be executed again.

We currently do not have a retry functionality implemented that replaces all the data from the first node. Not sure if there is a feature request already in the forum. If there is, upvote it. If not you, can create a new one. We can then prioritize accordingly.

**Comment by calvintwr** [comment]
@janober I am following https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md

It worked previously when I contributed some code, but now it didn't.

After having merged upstream, I ran `lerna bootstap --hoist`, and got the following: 

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: n8n-editor-ui@0.110.0
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"~4.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I tried to delete and clone a fresh copy to no avail.

**Comment by janober** [comment]
Are you using node.js v14 and mom v6?
