### ISSUE TITLE
AWS SES Credentials producing a 403

### ISSUE THREAD

**Issue by bamboowonder** [n8n-io/n8n#2304]
This is in reference to a forum post: https://community.n8n.io/t/aws-error-forbidden-perhaps-check-your-credentials/8353

I've confirmed that both the region and key/secret are correct.

I've confirmed that the AWS user has full scope on both SES and SNS(if that is necessary).  I've even tested with the AWS user having Admin scope.

I'm able to successfully post a message to a SNS topic from n8n node, using the same credentials as SES.  Both are us-west-2

I've deleted and recreated both the n8n credentials and aws credentials.  and restarted n8n.

In triaging, I changed the aws endpoint to a postbin I have, and noted that it is authenticating with us-east-1, which is incorrect.  See forum post for details.

**Expected behavior**
Amazon SES should connection without producing a 403

**Environment 
 - OS: [e.g. Ubuntu Linux 20.04]
 - n8n Version [0.142.0]
 - Node.js Version :  whatever is in the stock Docker image
 - Database system [postgres 13]
 - Operation mode [no idea, i'm in design mode.]

**Comment by janober** [comment]
Answered in forum that problem is sadly not reproducible for me.

**Comment by bamboowonder** [comment]
Ok.  I'll close this.  I'm going to redeploy my n8n instance from scratch as something is wonky.

**Comment by timoha** [comment]
@janober We are hitting the same issue with `The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`.
Interesting thing is that somehow the first time always works, however the second time the error above is thrown. We are on `0.160.0` and running n8n using docker on ECS.

Also, seems to be related to the following issues:
https://community.n8n.io/t/amazon-ses-error-on-valid-body-subject/11116/11
https://community.n8n.io/t/aws-error-forbidden-perhaps-check-your-credentials/8353/3
