### ISSUE TITLE
Unable to select database id in Notion Node

### ISSUE THREAD

**Issue by EnglederLucas** [n8n-io/n8n#2311]
**Describe the bug**

I've been trying create a Notion node that adds a database item to a database page. I added my API key and the first problem that I encountered was my inability to add a database id. I wasn't able to select one and manually adding one was only possible by creating an expression, which later returned a 400 HTTP Error.

![grafik](https://user-images.githubusercontent.com/26169816/136810527-037be2d7-4c19-41da-8b08-c684a3e70787.png)

I've also tried other Notion Operations with some showing similar results and others simply returning no data at all.

EDIT: I just notice a log message in the console. Do I have to input my Notion Credentials somewhere?

```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    ...
    node: {
      parameters: [Object],
      name: 'Temp-Node',
      type: 'n8n-nodes-base.notion',
      typeVersion: 1,
      position: [Array],
      credentials: {}
    },
    timestamp: 1634034939506
  },
  node: {
    parameters: {
      resource: 'databasePage',
      operation: 'create',
      databaseId: '',
      simple: true,
      propertiesUi: {},
      blockUi: {}
    },
    name: 'Temp-Node',
    type: 'n8n-nodes-base.notion',
    typeVersion: 1,
    position: [ 0, 0 ],
    credentials: {}
  },
  timestamp: 1634034939515,
  httpCode: null,
  description: 'Node does not have any credentials set for "notionApi"!'
}
```

**To Reproduce**
1. Go to Workflow
2. Create new Notion Node
3. Select "Database Page" as Resource
4. Select "Create" as Operation

**Expected behavior**

I expected the Node to give me the option to select my desired database. Or to at least not return an Error upon entering the database id myself.

**Environment (please complete the following information):**
 - OS: Windows: 10
 - n8n Version: 0.142.0
 - Node.js Version: 14.18.0
 - Database system: SQLite 
 - Operation mode: own

**Comment by RicardoE105** [comment]
If it does not load the databases for you, it's likely an issue with the credentials. Did you add the bot (API Key) to the page you want the node to have access to? Check the link below for instructions on how to do that.

https://docs.n8n.io/credentials/notion/#using-api-key

**Comment by EnglederLucas** [comment]
As already mentioned in the original comment: **I already added my API Key** to the bot. 
Furthermore, I also used the exact docs page you linked to and tried it with two different pages. The problem still arises.

**Comment by EnglederLucas** [comment]
Yes, I was able to fix it this way. Unfortunately the n8n notion interface is too limited for my needs. I wanted to create a table and content to the table, which seems to not be possible with the current UI (or expressions) yet.
