### ISSUE TITLE
Slack api return all parameter  limits to 100

### ISSUE THREAD

**Issue by bbougon** [n8n-io/n8n#2335]
**Describe the bug**
Using Slack API node, I wanted to fetch all the data from `conversation.list`.

Expected behavior:
When I want to fetch all the data from `conversation.list`, I want to have them all (i.e over 100)

**To Reproduce**
1. Go to 'Add a Node'
2. Search for 'Slack'
3. Parameterized the Slack Node Credentials
4. Choose Resource Channel
5. Choose Operation History
6. Fill the Channel with a channel ID
7. Toggle Return All
8. Execute the node

**Expected behavior**
I want to have all the results returned (i.e: limit over 100 and see in the Items option list the number of results returned by the api call

**Environment (please complete the following information):**
 - Image Docker n8n:latest (i.e 0.144.0)

**Additional context**
The issue is in this [part of the code](https://github.com/n8n-io/n8n/blob/4b857b19ac52ea75cea157b8e627c3f000e2131f/packages/nodes-base/nodes/Slack/GenericFunctions.ts#L82) 
=> `response_metadata.mext_cursor` instead of `response_metadata.next_cursor`

**Comment by janober** [comment]
Fix got merged and will be released with the next n8n version.

**Comment by janober** [comment]
Got released with n8n@0.145.0
