### ISSUE TITLE
Slack Node oldest and latest parameter datetime picker for channel history does not work  

### ISSUE THREAD

**Issue by bbougon** [n8n-io/n8n#2338]
**Describe the bug**
When I wanna get a slack channel history with Oldest and / or Latest messages, I pick a date and time from the input datetime picker but the results are not within the range of the choosen date and time  

**To Reproduce**
1. Go to a 'Slack Node' with channel history parameterized
2. Pick a date from the datetime picker for either Latest or Oldest messages
3. Execute the workflow

**Expected behavior**
I wanna retrieve the results corresponding to the date and time chosen

**Environment (please complete the following information):**
 - Image Docker n8n:latest (i.e 0.144.0)

**Additional context**
The issue is [here](https://github.com/n8n-io/n8n/blob/c3e3d9d46eede64ad0b08cf3afac814905371d1f/packages/nodes-base/nodes/Slack/Slack.node.ts#L417) (and a few lines down for oldest). The date time picked through the datetime picker is sent as datetime string (i.e: `2021-10-18 23:00:00`) to the slack API whereas it should be a timestamp based string (i.e `1634590800.000000`). See the slack [API doc](https://api.slack.com/methods/conversations.history))

**Comment by janober** [comment]
Thanks a lot @bbougon for reporting this issue. Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.145.0
