### ISSUE TITLE
Stripe's "Get All" charges operation always returns 10 items

### ISSUE THREAD

**Issue by brapifra** [n8n-io/n8n#2354]
**Describe the bug**
Apparently this is because n8n does not pass the "limit" parameter to the HTTP request.
![image](https://user-images.githubusercontent.com/17855450/138441216-230ab4de-8857-46f6-b30d-780af2bb13e7.png)

**To Reproduce**
1. Add a stripe node
2. In resource, select "Charge"
3. In operation, select "Get All"
4. Run node

**Expected behavior**
It should return 50 items, but instead it always returns 10 items.

**Environment (please complete the following information):**
 - Ubuntu
 - n8n Version: 0.144.0
 - Node.js Version: 14.16.0
 - Database system: SQlite
 - Operation mode: own

**This will probably happen in other Get All operations too**

**Comment by ivov** [comment]
> It should return 50 items, but instead it always returns 10 items.

@brapifra Is it possible you only have 10 charges to fetch? Limit param behaves as expected based on my tests:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/44588767/139832761-21004eb6-567a-4740-a19e-2493fd48281c.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44588767/139832807-e3412493-a06b-4211-ae51-add3cac0b49e.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44588767/139832845-8d68b9a6-dc9c-47f6-b213-9b3fc6bcf169.png">

**Comment by brapifra** [comment]
No @ivov 
I'm 100% sure I have more than 10 charges :slightly_smiling_face: 
If I use the HTTP connector to fetch them, I get 33 items:
![image](https://user-images.githubusercontent.com/17855450/139929512-ebac02fb-8418-4909-aa96-8dd62d9bc36e.png)

**Comment by ivov** [comment]
Fixed. We will let you know when this is released.

**Comment by janober** [comment]
Fix got released with n8n@0.148.0
