### ISSUE TITLE
TheHive trigger - Trigger when task is deleted does not work

### ISSUE THREAD

**Issue by Analystn8n** [n8n-io/n8n#2366]
**Describe the bug**
The node **TheHive trigger** cannot be triggered while choosing the Events "task deleted"

**To Reproduce**
1. Add the node TheHive Trigger
2. Choose the Events: "Task deleted"
3. Configure the webhook on TheHive
4. Delete a task on TheHive

**Expected behavior**
The webhook is triggered while deleting the task.

**Environment (please complete the following information):**
- n8n Version [0.142.0]
- official docker image n8nio/n8n:0.142.0
- TheHive 4.1.10-1

**Additional context**
I think the problem here is the fact that TheHive use a particular syntax for the tasks. While they use "deleted" for the other objects, a task is never deleted but is **updated** with the status "Deleted".
A temporary workaround consists in using the option "Task Updated" and to filter the events with the status.

**Comment by Joffcom** [comment]
Hey @Analystn8n,

It looks like the notification didn't get triggered, This was fixed with n8n@0.200.0
