### ISSUE TITLE
Custom n8n-nodes-* packages are not loaded when n8n is installed globally.

### ISSUE THREAD

**Issue by marcuson** [n8n-io/n8n#2371]
**Describe the bug**
If n8n is installed globally via npm and also some custom node packages (developed as per this [guide](https://docs.n8n.io/nodes/creating-nodes/node-dev-cli.html#create-own-custom-n8n-nodes-module)) are installed globally, such packages are not loaded by n8n on startup.

**To Reproduce**
1. `npm install -g n8n`
2. Install some custom node packages globally (you can use the [starter project](https://github.com/n8n-io/n8n-nodes-starter) for example, just `npm pack` it and then `npm i -g <packname>.tgz`)
3. Launch the global n8n from shell (just run `n8n`)
4. Base nodes are loaded, but custom ones are not

**Expected behavior**
n8n should load the nodes in the globally installed custom package.

**Environment (please complete the following information):**
 - OS: WSL Ubuntu 20.04.3 LTS (on Windows 10 Pro ver. 21H1, build 19043.1288)
 - n8n Version 0.145.0
 - Node.js Version 14.17.0
 - Database system SQLite
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**
The main reason for such behaviour is that when installed globally, n8n scan only the "node_modules" folder underneath its main folder, but does not take into account the global "node_modules" folder.

I've opened PR #2364 with a possible fix, feel free to close it if this is the expected behaviour.

**Comment by yencolon** [comment]
I'm facing this issue too, any workaround?

**Comment by marcuson** [comment]
You can try the fork in my PR if you want; otherwise I've found a little workaround (tested only on Linux).
First of all, you have to install n8n and your node package globally.
Then you have to create a symlink of your globally installed node package inside the n8n installation folder. This are some basic commands that I've used for such purpose:

```bash
NPM_GLOB_ROOT=$(npm root -g) // path of npm packages installed globally
ln -s $NPM_GLOB_ROOT/<your-package-name-here> $NPM_GLOB_ROOT/n8n/node_modules/<your-package-name-here> // link your package inside the "node_modules" folder of n8n, which is itself installed globally
```

It's not very elegant, but for me this works.

**Comment by zobayer1** [comment]
It might be more of a feature request, but it would be nice to be able to link the node packages without having to install both the nodes-library and n8n globally.
