### ISSUE TITLE
ECONNREFUSED Supabase Postgres connection

### ISSUE THREAD

**Issue by NicolasRoehm** [n8n-io/n8n#2382]
**Describe the bug**
I'm not able to connect n8n to [supabase](https://supabase.io/) Postgres database.
I get the following error message :
```
Error: connect ECONNREFUSED IP_ADDRESS:6543
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```

**To Reproduce**
1. Create a [supabase](https://supabase.io/) account and create a table
2. In `n8n`, click on `+` button
3. In `DATA & STORAGE` section, click on `Postgres` node
4. In `Parameters` tab, `Credentials` section, `Postgres` field : click on `- Create New -`
5. Set the values according to your supabase configuration : 
- `host` to `db.{id}.supabase.co`
- `database` to `postgres`
- `user` to `postgres`
- `password` ...
- `port` to `6543`
6. In `Operation` field, select `Execute Query`
7. In `Query` field, write a simple query like `SELECT * FROM mytable`
8. Click on `Execute Node`

**Expected behavior**
I expected to get a json based on the query.

**Environment (please complete the following information):**
 - OS: I don't know sorry, I created the Node.js app using Cpanel on shared hosting so probably Linux
 - n8n Version **0.145.0**
 - Node.js Version **14.17.6**
 - Database system **SQLite**
 - Operation mode **own**

**Additional context**

**Comment by ivov** [comment]
There is no Supabase node on `master` as of 0.145.0 or the latest.

Can you link us to the hosting service you are using?

**Comment by NicolasRoehm** [comment]
I'm using [o2switch](https://www.o2switch.fr/hebergement-illimite/) and there is only one plan.

I found a workaround, instead of logging into Supabase Postgres, we can query the DB using `HTTP Request` node
- Set the `URL` to `https://{id}.supabase.co/rest/v1/{mytable}`
- Add the `apiKey` header with the appropriate value
([Documentation](https://supabase.io/docs/guides/api#api-url-and-keys))

Maybe this issue is related to https://github.com/brianc/node-postgres/issues/1789

**Comment by ivov** [comment]
Thank you for sharing the link and the solution. Since we do not currently have a Supabase node, this is a custom node of o2switch, so we cannot offer support on this.
