### ISSUE TITLE
Google Service Account Impersonation failing validation (but working)

### ISSUE THREAD

**Issue by Yann-J** [n8n-io/n8n#2397]
**Describe the bug**

Google Service Account authentication works fine, but fails whenever we try to configure impersonation (even though the same works from other apps).

The returned error from Google is:

```
 Private key validation failed: 401 - {"error":"unauthorized_client","error_description":"Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."} 
```

**To Reproduce**

1. Create a Google Service Account and generate JSON key.
2. Enable the Drive API to the account's project
3. Grant it domain-wide delegation by adding its client id in the Google Workspace delegation settings, and enable the `https://www.googleapis.com/auth/drive` scope for domain delegation
4. Create a new Google API credentials in n8n, set service account email and Private key. Verify that it works fine
5. Enable Impersonation and provide a valid email from the domain. Test credential again, it fails, even with minimal API scopes (Drive).

**Expected behavior**

Credential should work with impersonation.

**Environment (please complete the following information):**
 - OS: Official Docker image
 - n8n Version: 0.145.0
 - Database system: SQLite
 - Operation mode: `own`

**Additional context**

The same Service Account / impersonated user combination has been confirmed to work fine with other applications (rclone) which can successfully read and write files from my drive, ruling out any misconfiguration in the user / workspace settings.

The service account is also working fine without impersonation (but this is not a solution for us, since those accounts have a serious Drive quota limitation).

I suspect that n8n is maybe asking for too many scopes when authenticating (?). We've only enabled the Drive scope for delegation... But we haven't been able to figure out which other scopes might need adding...

![image](https://user-images.githubusercontent.com/59641363/139837146-50279a9e-658f-4cc2-9b8c-6c2315b2a896.png)

Any help appreciated!

**Comment by Yann-J** [comment]
OK, apologies for the update here, but after much fiddling, and trying to emulate n8n authentication code, I eventually reached the conclusion that... the credentials actually work (for the Drive nodes at least) but only **fail the validation in the credentials UI**.

I suppose it's because the validation might be querying for more scopes than we gave... but we could not figure out which ones to add...

**Comment by janober** [comment]
Ah yes, that seems like something we have to improve as the same credentials get shared by multiple nodes and in this case it uses the check from Google Sheets and so uses the scopes:
```
		'https://www.googleapis.com/auth/drive',
		'https://www.googleapis.com/auth/drive.file',
		'https://www.googleapis.com/auth/spreadsheets',
```

**Comment by chadfaurie** [comment]
Can confirm this works for sheets as well, however still causing issues on the credentials pages in version 0.169.0

Hey @Yann-J do you have any additional insight into the Drive Node? I am getting an error 
```txt 
401 - {"error":"unauthorized_client","error_description":"Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."}
```
with drive, but not with sheets, I wanted to check if there are any additional scopes I should be aware of?

**Comment by einarpersson** [comment]
I just stumbled upon this myself, after spending way too much time troubleshooting. See [community thread](https://community.n8n.io/t/cannot-impersonate-user-for-gmail-with-service-account/14668/3).

1. I am able to use Google Sheets node with service account credentials and impersonation (note: even though the credentials give an error message in UI)
2. I am **not** able to use Gmail node with the same credentials.

Running version n8n@0.179.0 on cloud

**Comment by einarpersson** [comment]
I found this [this definition of scopes](https://github.com/n8n-io/n8n/pull/1481/files) regarding gmail.
After I added all those, it started working! @chadfaurie maybe you can find something similar for the drive node? Or maybe you already have?

1. Necessary scopes for these nodes should really be available in the node documentation. **Should I create another issue for that?** (this issue relates to fact that the credentials UI gives an error msg when it shouldn't)

2. It would be nice if we could be more fine grained when it comes to necessary scopes. If I only want to build automation that reads emails I don't want to authorize all kinds of scopes, only bare minimum for actual requests.

**Comment by Joffcom** [comment]
Hey There,

It looks like we now have a list of the scopes we use which can be found here: https://docs.n8n.io/integrations/builtin/credentials/google/oauth-generic/#scopes

We have had talks about allowing more control over scopes but have not made a choice on that, If that is something that there is interest in it would be worth opening a feature request on our support forum (https://community.n8n.io), We can then track the votes from community members.

For now I am going to mark this one as closed, If it is still an issue let me know and we can open it again.

**Comment by swanzeyb** [comment]
For anyone trying to setup Gmail node with a Google Workspace account with service key auth, n8n WILL report an HTTP 401 unauthorized error even when it will connect. The exact scopes I had to enter for domain wide delegation in Google Admin:
`https://mail.google.com/, https://www.googleapis.com/auth/gmail.labels, https://www.googleapis.com/auth/gmail.modify, https://www.googleapis.com/auth/gmail.compose, https://www.googleapis.com/auth/gmail.send, https://www.googleapis.com/auth/gmail.readonly, https://www.googleapis.com/auth/gmail.addons.current.action.compose, https://www.googleapis.com/auth/gmail.addons.current.message.action`

**Comment by groundbreakersonline** [comment]
> For anyone trying to setup Gmail node with a Google Workspace account with service key auth, n8n WILL report an HTTP 401 unauthorized error even when it will connect. The exact scopes I had to enter for domain wide delegation in Google Admin: `https://mail.google.com/, https://www.googleapis.com/auth/gmail.labels, https://www.googleapis.com/auth/gmail.modify, https://www.googleapis.com/auth/gmail.compose, https://www.googleapis.com/auth/gmail.send, https://www.googleapis.com/auth/gmail.readonly, https://www.googleapis.com/auth/gmail.addons.current.action.compose, https://www.googleapis.com/auth/gmail.addons.current.message.action`

love you man! this is the only solution, even if validation is failing, the node it works!
