### ISSUE TITLE
Toggl node no longer functional - domain deprecated

### ISSUE THREAD

**Issue by mcat-ee** [n8n-io/n8n#2417]
**Describe the bug**
Using the toggl _new time entry_ trigger results in a 410 error - this is due to the [old API being deprecated as of yesterday/today](https://support.toggl.com/en/articles/5708431-why-did-my-integration-stop-working)

**To Reproduce**
1. Create toggl node
2. Configure toggl node with valid parameters
3. Create a test time entry in toggl
4. Attempt to trigger toggl node
5. View 410 error returned

**Expected behavior**
The new time entry is detected, and passed into the further steps of the workflow

**Environment (please complete the following information):**
 - OS: Ubuntu 21.10
 - n8n Version: Current stable
 - Node.js Version: Current stable
 - Operation mode: Own(?)

**Comment by mcat-ee** [comment]
I've created a PR for this modification 
https://github.com/n8n-io/n8n/pull/2418

**Comment by janober** [comment]
Thanks a lot for fixing this. Got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.149.0
