### ISSUE TITLE
tag_entity already exists

### ISSUE THREAD

**Issue by jwillmer** [n8n-io/n8n#2422]
**Describe the bug**
I was about to update my docker n8n version from 0.115.0 to 0.148.0 but it failed with the error below.
After some try&error I can pinpoint the error happens when switching from version 0.121.0 to 0.122.0.

```
Initializing n8n process
There was an error initializing DB: "SQLITE_ERROR: table "tag_entity" already exists"

Stopping n8n...
```

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version: 0.121.0 to 0.122.0
 - Database system: SQLite - using build in default
 - Operation mode: default

**Comment by BHesseldieck** [comment]
Hi @jwillmer 

it seems that a migration did not complete or crashed and left your database in a "broken" state.

Easy solution would be that you are removing the "tag_entity" table, which would probably solve the problem. Depending on how comfortable you are with command line tools this can be also achieved with database UI managers.

It is failing to upgrade from 0.121.0 to 0.122.0, because we introduced workflow-tagging in 0.122.0

**Comment by jwillmer** [comment]
Is there a guide how to remove the (any) table? Can I do it inside the docker container? I would certainly try this to solve it.

**Comment by that-one-tom** [comment]
Hi @jwillmer, the container wouldn't have a suitable command line tool installed by default. To delete a table as suggested by @BHesseldieck, you could install and use `sqlite3` on your host machine (`sudo apt install sqlite3` on Ubuntu). You could also install it inside the container if needed (the command should be `apk add sqlite`), but I haven't tried this myself, so can't share first-hand experience there.

You can then connect to the database like this: `sqlite3 ~/.n8n/database.sqlite` (adjust the path if you store your n8n data elsewhere)
Delete the table using `DROP TABLE tag_entity;`
And exit sqlite3 by pressing Ctrl+D.

Hope this helps! Going forward, you might want to reach out on our [community forum](https://community.n8n.io/) where you'd usually get much faster responses to questions like this.

**Comment by jwillmer** [comment]
works like a charm! Thank you very much @that-one-tom 👑
