### ISSUE TITLE
Workflow with Stripe Trigger can not be actived - "No such webhook endpoint"

### ISSUE THREAD

**Issue by brapifra** [n8n-io/n8n#2429]
**Describe the bug**
When trying to save a workflow with a Stripe Trigger, it sometimes fails. In order to work around the issue, I need to clone the workflow, remove the trigger and add it again.

**To Reproduce**
1. Create a workflow with a Stripe Trigger.
2. Test that it works by clicking on "Execute workflow" and waiting for a new event.
3. Save the workflow and try to activate it.

![image](https://user-images.githubusercontent.com/17855450/141436126-5eee6ae6-97ee-4470-88e3-6a76fa4988b2.png)

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.xxx
 - n8n Version: 0.148.0
 - Node.js Version: 14.18.0
 - Database system: SQlite
 - Operation mode: own

**Comment by janober** [comment]
That seems to occur when n8n tries to check for an old existing webhook. Problem got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.149.0
