### ISSUE TITLE
Slack Bot - Access token test is invalid, but bot still works

### ISSUE THREAD

**Issue by mjquinlan2000** [n8n-io/n8n#2436]
**Describe the bug**

**To Reproduce**
1. Create a new Slack API credential
2. Add a _bot_ access token
3. Test the connection
4. Notice that it fails even if the token is valid. The error code is "missing_scopes"

<img width="953" alt="image" src="https://user-images.githubusercontent.com/1171608/141831843-426022e9-28f6-4a88-b84b-4104e1c0b983.png">

**Expected behavior**
I would expect the test connection behavior to pass. The token is valid and works in my workflows, but does not pass the test call

**Environment (please complete the following information):**
 - Docker Image
 - n8n: 0.149.0
 - Whatever is in the docker image
 - Postgres
 - queue

**Additional context**

This does not affect the functionality of workflows, but it fails the test when saving the credentials. This is confusing as the credentials still work, but it displays that they won't.

**Comment by Joffcom** [comment]
Hey @mjquinlan2000,

I was just taking a look through some of the issues and spotted this one.

The credentials test uses [users.profile.get](https://api.slack.com/methods/users.profile.get), to remove the error you would need to include this scope for your bot.

This is something that will need to be updated in the documentation.

**Comment by RicardoE105** [comment]
@Joffcom, I think we. can omit the error: "missing_scopes" and only errors when "invalid_auth." That way, we only care about the token validity and not whether it has the right scopes for the call.

**Comment by janober** [comment]
Fix got merged with #3151

**Comment by janober** [comment]
Fix got released with `n8n@0.174.0`
