### ISSUE TITLE
workflow executions - allow to unselect items after "select all" clicked

### ISSUE THREAD

**Issue by yureckey** [n8n-io/n8n#2438]
In the workflow executions, when I click "select all" in the header, I would like to be able to unselect some items - which is not possible currently. (I wanted to remove most of the executions but keep couple of it)

**Comment by janober** [comment]
Thanks for raising this feature request but as you probably saw when you created that issue are GitHub issues are only for bugs and not feature requests. They have to be raised on our forum here: https://community.n8n.io/

**Comment by yureckey** [comment]
ah, I see. Actually, I thought it was a bug, since the obvious and expected UX would be to be able to deselect manually after all select.

**Comment by janober** [comment]
Yes, you can probably see it both ways ;-)
