### ISSUE TITLE
Google Sheets - can't select ..sheet

### ISSUE THREAD

**Issue by rafalkrupinski** [n8n-io/n8n#2442]
**Describe the bug**
Settings modal for Google Sheets is missing sheet

**To Reproduce**
1. add google sheets node
1. apply your auth settings
2. select resource = sheet, operation = read or any other operation that works on the sheet data (not on entire sheet)
3. range and row selection occurs, but can't choose a sheet. In result only the first sheet is used

**Expected behavior**
I should be able to choose a sheet

**Environment (please complete the following information):**
  - n8n 0.149.0 

**Additional context**
It's even shown in the official documentation of the google sheets node

**Comment by janober** [comment]
We will make that for sure simpler in the future. For now can you find the solution in the docs:
![Screenshot from 2021-11-16 18-14-45](https://user-images.githubusercontent.com/6249596/142033175-c1d645ec-b4a5-4c1c-b629-524727a417b3.png)
https://docs.n8n.io/nodes/n8n-nodes-base.googleSheets/#faqs

**Comment by rafalkrupinski** [comment]
@janober thanks. I've just seen so much software that reads only the first sheet, I just assumed it's one of those cases and I didn't search thoroughly for this.

**Comment by janober** [comment]
Sure, makes sense.

Have fun!
