### ISSUE TITLE
EmailReadImap stop working after timeout

### ISSUE THREAD

**Issue by rottmann** [n8n-io/n8n#2449]
**Describe the bug**
The n8n node `EmailReadImap` stop working after a timeout occured.

We had some Mail-Server issues, so the connection was very slow, got a timeout.
After the server issues solved, the node still not work.

We must restart the task manually (with re-activate or execute workflow).

The problem is, that the timeout error did not trigger the global error handler, so we did not know that something not worked and we could not react on the problem.

The execution-list shows that everything was OK, but it wasn't.

**Comment by janober** [comment]
Here is an earlier issue about the same topic: https://github.com/n8n-io/n8n/issues/1400

Did you activate the option "Force reconnect"?

**Comment by rottmann** [comment]
Did not see that. Thank you!

**Comment by janober** [comment]
Glad to hear that it helped. Have fun!
