### ISSUE TITLE
Problem with HTTP Request node response

### ISSUE THREAD

**Issue by guilhermeagirardi** [n8n-io/n8n#245]
Hello guys!

It is the first time that I am using n8n, I apologize if my question is stupid.

I created a new **HTTP Request** for a request to my API. The request is successful, and the data is returned, however, the data should not be encapsulated in an array, like this:
![image](https://user-images.githubusercontent.com/2306117/73037993-9e649b80-3e2f-11ea-9e9c-78065c765256.png)

This is not a problem with my API response, it only returns the array that houses the items.

This problem seems to impact the data visualization as a table:
![image](https://user-images.githubusercontent.com/2306117/73038142-14690280-3e30-11ea-9750-52f2fa71a751.png)

So, I try to "fix" this in a subsequent node called "Function" by defining the expression
```javascript
return items[0];
```
, however, I get the following error message:
**ERROR: Always an Array of items has to be returned!**

Does anyone know how I can fix this problem?

**My workflow:**
![image](https://user-images.githubusercontent.com/2306117/73038342-da4c3080-3e30-11ea-9e8a-a7319373359a.png)

**Environment:**
 - OS: Windows 10 x64
 - n8n Version: 0.49.0
 - Node.js Version: 10.16.0

**Comment by janober** [comment]
Sorry to hear that you have problems. But can you please post the question into the forum where it belongs. Github issues are only for bugs like described in the issue-template. Thanks!

You can find the forum here:
https://community.n8n.io/
