### ISSUE TITLE
JIRA node is missing the components field. How do I configure it?

### ISSUE THREAD

**Issue by CometNet** [n8n-io/n8n#2454]
When configuring JIRA today, we found that JIRA has the components field, which is a required option

JIRA service version

https://n8n.io/integrations/n8n-nodes-base.jira

![image](https://user-images.githubusercontent.com/20129614/142575458-9399621a-d2cd-468d-a10b-484a2414e647.png)

API documentation：https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-post

**Comment by janober** [comment]
There is already an open PR about that which can be found here:
https://github.com/n8n-io/n8n/pull/2428

**Comment by janober** [comment]
Got released with `n8n@0.150.0`
