### ISSUE TITLE
Interface frozen or buggy (wrong label displayed or data not updated)

### ISSUE THREAD

**Issue by vincentwinkel** [n8n-io/n8n#2466]
**Describe the bug**
The interface sometimes seems frozen / buggy, and doesn't display the correct data. It works well when we refresh.

-----

**To Reproduce (1/2)**
1. Run your workflow
2. Stop it, the webhook is still waiting and we get the info about the workflow successfully deleted (refreshing the page fixes it)
<img width="1040" alt="Screenshot 2021-11-23 at 10 12 27" src="https://user-images.githubusercontent.com/1402505/142997827-6577afa1-15e6-4d02-ad87-263b102c62f9.png">

After investigation, a click on the Stop button seems sending a DELETE HTTP request but refreshing the page still displays the workflow.

**Expected behavior (1/2)**
The workflow stopping and saying it's successfully stopped and not deleted (I almost got a heart attack).

-----

**To Reproduce (2/2)**
1. Write manually an expression in a node parameters
2. Save it and close the modal
3. Reopen the modal
2. Select a variable from the modal suggestions, replacing the manual expression
2. The preview is still the old manual expression instead of the new selected one
<img width="594" alt="Screenshot 2021-11-22 at 13 51 27" src="https://user-images.githubusercontent.com/1402505/142998310-c1294978-0d62-486f-ab32-02931827af1d.png">

**Expected behavior (2/2)**
The preview being updated with the correct value.

**Environment (please complete the following information):**
 - OS: MacOS X
 - n8n Version 0.136.0
 - Node.js Version unknown
 - Database system unknown
 - Operation mode unknown

**Comment by vincentwinkel** [comment]
Another issue I just got, I start the workflow, waiting for the webhook to be called:
<img width="356" alt="Screenshot 2021-11-23 at 18 46 15" src="https://user-images.githubusercontent.com/1402505/143077322-9231c895-6328-4183-aac5-8ddbdf7f7ccb.png">

then when I call the webhook, I get still error (even tho the workflow is still waiting for a connection):
<img width="1054" alt="Screenshot 2021-11-23 at 18 46 32" src="https://user-images.githubusercontent.com/1402505/143077396-d4107993-f5a0-4193-8d59-c66925e9f9d2.png">

Also, the workflow stays stuck on some modes, I cannot stop it because of the DELETE call or I get this 500 error:
<img width="526" alt="Screenshot 2021-11-23 at 18 49 54" src="https://user-images.githubusercontent.com/1402505/143077694-f968147e-2ee2-4a27-9233-65ab2b86c1a8.png">

**Comment by vincentwinkel** [comment]
Everything fixed in v0.150.0.

**Comment by janober** [comment]
Great to hear. There are actually a few more fixes in the next version that will probably be released today.
