### ISSUE TITLE
$variables not available in Function Item

### ISSUE THREAD

**Issue by rafalkrupinski** [n8n-io/n8n#2475]
**Describe the bug**
Accessing $variable ($node in my case) doesn't return a value.
Same code works in the Function node

**To Reproduce**
1. Create a new workflow
1. Create a Set node
2. Create a Function Item node
3. in the Function Item type
    ````
    console.out($node.Set.json)
    return item
    ````

**Expected behavior**
Expect to work the same way Function node does - accessing $node should work and not cause errors

**Environment (please complete the following information):**
 - n8n Version  0.149.0 
 - Operation mode: own

**Comment by janober** [comment]
I assume you mean `console.log` not `console.out`. Because of you use that it works fine:
`console.log($node.Set.json)`
