### ISSUE TITLE
n8n always runs out of memory after I activate the workflow

### ISSUE THREAD

**Issue by hyingreborn** [n8n-io/n8n#2479]
**Describe the bug**
I was very excited to see the N8N，I try to use it instead of ETL for daily development work. But in use, it consumes an irrational amount of memory until it runs out

**To Reproduce**
1. Create a workflow，it consume message by kafka trigger , and mapping info  by functionItem, finally, the information is stored in PostgresQL
2. Save workflow
3. Active this workflow

**Expected behavior**
When testing workflows, single executions are fast and maintain normal memory consumption.
But when I activate this workflow to make it run in the background, when there are more messages in kafka, it immediately consumes a lot of memory until it overflows.

**Environment (please complete the following information):**
 - OS: [docker image]
 - n8n Version [0.150.0]
 - Node.js Version [docker images]
 - Database system [MySQL]
 - Operation mode [Default is `own`]

**Additional context**
1、When there are few messages from kafka, there will be no problem.
2、After testing, this problem will arise after about 50 messages from kafka.
3、Each time, the message size consumed by kafka is less than that of 1kb, but judging from the memory consumption of n8n, it seems that it far exceeds its due memory footprint.

**Comment by janober** [comment]
Please set the environment variable `EXECUTIONS_PROCESS=main` it will then not start a new process for each execution and so reduce the memory footprint a lot.

It is also always better to first post to the community forum here: https://community.n8n.io/

**Comment by hyingreborn** [comment]
thanks a lot ! @janober  I can now safely use it in a production environment.

**Comment by janober** [comment]
Glad to hear that it works now. Have fun!
