### ISSUE TITLE
No images for Customer Datastore nodes

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#2481]
**Describe the bug**
Icons of Customer Datastore and Customer Messengers are missing.
![image](https://user-images.githubusercontent.com/20184727/143505348-c1559e00-f5c5-42f1-b52b-c4b91b37ed40.png)

**To Reproduce**
1. Type "cus" in the Nodes search bar
2. See error

**Expected behavior**
There were icons for these nodes

**Environment (please complete the following information):**
 - Ubuntu Linux 20.04
 - n8n Version 0.150.0
don't know the rest of the parameters

**Comment by janober** [comment]
Thanks a lot. Got already fixed with #2463

**Comment by janober** [comment]
Got released with `n8n@0.151.0`
