### ISSUE TITLE
Slack channel:invite fails on user ids expression

### ISSUE THREAD

**Issue by jan-thoma** [n8n-io/n8n#2484]
**Describe the bug**
When trying to fill the user ids as an expression n the slack node at the invite:channel action the node fails.

![Bildschirmfoto 2021-11-26 um 14 53 37](https://user-images.githubusercontent.com/24450307/143594195-f13efd8e-217c-4c3a-9929-6e3189e4610a.png)
**To Reproduce**
Create a Workflow with a slack invite:channel node
Fill the user ids from an expression

**Expected behavior**
Expressions should work

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version 0.151.0
 - Node.js Version v14.15.5
 - Database system SQL
 - Operation mode own

**Additional context***
i'm using the docker container

**Comment by janober** [comment]
"User IDs" expects an Array. So you have to write `{{ [$node....] }}`

**Comment by GlitchWitch** [comment]
@janober I am running into the same issue with both the "Channel" and "User IDs".
My expression `{{$node["Webhook"].json["query"]["slack_internal_channel_id"]}}` was based off the suggestion from @RicardoE105 on an [older forum post](https://community.n8n.io/t/dynamically-insert-channelid-into-slack-for-reading-channel-history/9225/2), however it produces the same error noted above.

I tried to change it to an array by implementing your suggestion as follows: 
`{{ [ $node["Webhook"].json["query"]["slack_internal_channel_id"] ] }}` 

However this produces the result `[Array: ["C03FZ871MCK"]]` which causes n8n to display the following warning.
>  The value "[Array: ["C03FZ871MCK"]]" is not supported!

Subsequent execution shows 
> Slack error response: {"ok":false,"error":"channel_not_found"}
> [...]
> "channelId": "={{ [ $node["Webhook"].json["query"]["slack_internal_channel_id"] ] }}",

However the same slack bot auth token can see and invite users to that channel when the slack API is called directly.
