### ISSUE TITLE
OAuth2 callback raises an error while retrieving token from Reddit

### ISSUE THREAD

**Issue by sergio-ns** [n8n-io/n8n#2488]
**Describe the bug**
The following error is displayed at the end of the Reddit Oauth2 validation process both in the browser dialog and in the server log file:
```
at getAuthError (/usr/local/lib/node_modules/n8n/node_modules/client-oauth2/src/client-oauth2.js:122:15),
at /usr/local/lib/node_modules/n8n/node_modules/client-oauth2/src/client-oauth2.js:276:21,
at processTicksAndRejections (internal/process/task_queues.js:93:5),
at async /usr/local/lib/node_modules/n8n/dist/src/Server.js:1101:36 {,
Error: 401,
ERROR RESPONSE,
  body: { message: 'Unauthorized', error: 401 },,
  code: 'EAUTH',
}
```

**To Reproduce**
1. Go to Credentials and click on Add New
2. Select Reddit OAuth2 API from the drop down list
3. In the dialog enter Client ID and Client Secret, then click button "Connect my account"
4. A browser pop-up opens on Reddit.com asking to authorize the application. 
5. Click on "Authorize" button
6. A JSON error message is displayed in the dialog. The same error message is reported in the server log file

**Expected behavior**
The Reddit OAuth2 authentication process should complete successfully after authorizing the app.

**Environment (please complete the following information):**
 - OS: Alpine Linux 
 - n8n Version: 0.151.0
 - Node.js Version: v14.15.5
 - Database: MySQL (MariaDB)
 - Operation mode: own

**Additional context**
Scenario is similar to what was reported in #1906 although the error message is different

n8n is deployed via Docker Client, served from behind a , see below:

```
docker run -d --name n8n --network=mynet -p 5678:5678
--restart always
-v /share/DockerVolumes/n8n/.n8n:/home/node/.n8n
-v /share/DockerVolumes/n8n/data:/data
--env-file=n8n.env
n8nio/n8n
n8n start
```

Relevant variables in env file:

```
# N8n docker environment file

DB_TYPE=mysqldb
DB_MYSQLDB_HOST=db_host_name
DB_MYSQLDB_PORT=3306
DB_MYSQLDB_USER=db_user
DB_MYSQLDB_PASSWORD=secret_password
GENERIC_TIMEZONE="Europe/Rome"
TZ="Europe/Rome"


# The top level domain to serve from
DOMAIN_NAME=mydomain.com

# The subdomain to serve from
SUBDOMAIN=n8n_host

# The user name to use for authentication - IMPORTANT ALWAYS CHANGE!
N8N_BASIC_AUTH_USER=user

# The password to use for authentication - IMPORTANT ALWAYS CHANGE!
N8N_BASIC_AUTH_PASSWORD=another_secret_password

# Webhook URL for OAuth redirect (correctly displayed in the OAuth dialog's callback URL field)
WEBHOOK_URL=https://n8n_host.mydomain.com
```

**Comment by Joffcom** [comment]
Hey @sergio-ns,

Are you still having this issue?

**Comment by Joffcom** [comment]
Hey @sergio-ns,

I am going to mark this one as closed, If you are still having this issue let me know and we can open it again.

**Comment by Joffcom** [comment]
Hey @brianclemens 

Could you create a post on our community support forum and we can take a look.

**Comment by LeonChenWenJia** [comment]
I'm having this exact same issue, I get an email notification saying app was successfully authorised but the OAuth 2.0 still doesn't authorise/work in n8n. How did others solve the issue?

n8n version: 1.88.0
Database (default: SQLite): SQLite
n8n EXECUTIONS_PROCESS setting (default: own, main): main
Running n8n via (Docker, npm, n8n cloud, desktop app): official n8n docker image
Operating system: Ubuntu 24.04.2 LTS
