### ISSUE TITLE
Todoist Node Datetime Issue

### ISSUE THREAD

**Issue by X-pech** [n8n-io/n8n#2489]
**Describe the bug**
Todoist node works incorrectly with Due Date Time option due to conflicts between ISO and RFC formats

**To Reproduce**
Try to create new task with Todoist Node and set Due Date Time additional field. There would be an error with code 400.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n 0.151.0

**Additional context**
The bug is due to the format conflicts, which is proven by creating a new task woth HTTP Request node and slicing millis from datetime string before request.

**Comment by krynble** [comment]
Thanks for the report and also for the fix.

I requested small changes on your PR so we can merge it.

**Comment by krynble** [comment]
Thanks a lot for your contribution.

I did review the PR and assigned another colleague to have a second look. Should be merged and released soon.
