### ISSUE TITLE
Twitter node error: You currently have Essential access

### ISSUE THREAD

**Issue by sergio-ns** [n8n-io/n8n#2490]
**Describe the bug**
I tried to use the Twitter node to collect my Likes but workflow execution fails with:

```
You currently have Essential access which includes access to Twitter API v2 endpoints only.
If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal.
You can learn more here: 
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
```

**To Reproduce**
1. Register a dev account with "Essential" access
2. Add Twitter credentials after registering an app
2. Add a Twitter node with Operation "Like"
3. Test the Workflow

```
{
"message": "Request failed with status code 403",
"name": "Error",
"stack": "Error: Request failed with status code 403 at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (events.js:327:22) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
} 
```
**Stack:**
```
NodeApiError: Forbidden - perhaps check your credentials?
    at Object.twitterApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Twitter/GenericFunctions.js:26:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Twitter/Twitter.node.js:197:40)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:447:47
```

**Expected behavior**
Successful execution of the workflow

**Environment (please complete the following information):**
    OS: Alpine Linux
    n8n Version: 0.151.0
    Node.js Version: v14.15.5
    Database: MySQL (MariaDB)
    Operation mode: own

**Additional context**

**Comment by Joffcom** [comment]
Hey @sergio-ns,

Have you applied for Elevated Access like the message suggests?

This isn't technically a bug with n8n but it is something that should maybe be documented as a warning.

**Comment by sergio-ns** [comment]
Hello @Joffcom.
thanks for the swift reply.
Definitely not an n8n bug and no, I did not apply for Elevated Access as I doubt it will be approved for a pet project like mine.
I mistakenly thought that using Essential vs. Elevated access was a matter of choice on the n8n side when in fact it just derives from the specific action performed: a bit weird that Twitter requires elevated access to just retrieve information about one's liked tweets.

Closing this issue

**Comment by tanuja840** [comment]
ar params = {screen_name: 'tanujagu'};
var one_way_followers=[];
client.get('followers/ids', params, function(error, followers_results, response) {
  if (error) 
    throw error;
  
  var followers = followers_results.ids;

client.get('friends/ids', params, function(error, followeing_results, response) {
    if (error) 
      throw error;
      var following = followeing_results.ids;
      console.log(followeing_results);


following.forEach(function(person){
    if(followers.indexOf(person)===-1){
        one_way_followers.push(person);
    }
});


//console.log(one_way_followers);

    });
});










   throw error;
    ^
[
  {
    message: 'You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve',
    code: 453
  }
]
