### ISSUE TITLE
Function node: console.log prints only first arg

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#2496]
**Describe the bug**
When manually executing a Function node in the browser, only the first argument to `console.log` ist printed.

**To Reproduce**
1. Paste node:
  ```json
	{
		"nodes": [
			{
				"parameters": {
					"functionCode": "console.log(\"Test\", \"1\", {x:1})"
				},
				"name": "Function1",
				"type": "n8n-nodes-base.function",
				"typeVersion": 1,
				"position": [
					920,
					480
				]
			}
		],
		"connections": {}
	}
  ```
2. Execute manually
3. See this in browser console:
  `Node: "Function" Test`

**Expected behavior**
Should print all args.

**Environment (please complete the following information):**
 - OS: e.g. Ubuntu Linux 18.04
 - Browser: Firefox 94
 - n8n: docker image `n8nio/n8n@904ea610d1680d745210ae21769532f0156c1a65ec513c85a6186f49db517648`
  `n8n -v` = `0.151.0`

**Comment by janober** [comment]
Got released with `n8n@0.152.0`
