### ISSUE TITLE
Credential cannot be deleted (docker-compose with MongoDB)

### ISSUE THREAD

**Issue by tommywalkie** [n8n-io/n8n#250]
**Describe the bug**
Successfully launched n8n via [docker-compose with a MongoDB instance](https://github.com/n8n-io/n8n/tree/master/docker/compose/withMongo) behind a NGINX proxy. When deleting a certain credential named "_XXX_" from UI, I tried re-creating a new credential but with the same title, "_XXX_", UI tells me that the credential couldn't be saved.
```
Problem Creating Credentials
There was a problem creating the credentials:
Credentials with the same type and name exist already.
```
I tried another name and it worked. When refreshing the UI, the old credential "_XXX_" still appears in credentials list.

**To Reproduce**
1. Create new credential "_XXX_"
2. Save the new credential "_XXX_"
3. Delete the newly created credential
4. Create new credential "_XXX_"
5. Try to save the new credential "_XXX_"
6. Refresh UI
7. Go to Credentials > "Open"

**Expected behavior**
Deletes completely the credential and allow user to create a new one with same title. 

**Environment (please complete the following information):**
 - OS: Alpine Linux
 - n8n Version: 0.49.0
 - Node.js Version: 12.13.0

**Additional context**
Didn't try with other database handlers like **PostgreSQL** and **SQLite** though.
I tried with workflows, successfully can delete a newly created workflow.

**Comment by janober** [comment]
Thanks a lot! That sounds odd. Will check it out.

**Comment by krynble** [comment]
Hey @tommywalkie we deprecated MongoDB a little while ago and it was recently removed in version 0.104.0.

I was checking older issues and found yours. Were you able to solve this? I would strongly suggest you migrate to SQLIte, MySQL or Postegres as we have made available a CLI command to export and import workflows and credentials, making this migration very easy. You can check the docs here: https://docs.n8n.io/reference/start-workflows-via-cli.html

**Comment by tommywalkie** [comment]
Hi @krynble , well I didn't dig further into this issue, it didn't bother me a lot. I know I can just stop / remove the related Docker container/volume and recreate a new one whenever I want.

Anyway, thanks for the heads-up, I'll make sure tu update my Compose configuration. 👍
