### ISSUE TITLE
Mention of rpi docker image should be removed from docs

### ISSUE THREAD

**Issue by simonmaris** [n8n-io/n8n#2504]
The old `latest-rpi` docker is still referenced here in the docs..

https://docs.n8n.io/getting-started/installation/#docker

> n8n also offers a Docker image for Raspberry Pi: n8nio/n8n:latest-rpi.

Took me a while to find out, why I was getting an old version :)

**Comment by ivov** [comment]
Thank you for your report. This belongs in the [docs repo](https://github.com/n8n-io/n8n-docs).
