### ISSUE TITLE
Notion "Block Append" node returns not own but parent data

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#2562]
**Describe the bug**
When use the Notion node in the Block / Append mode, irrelevant data is returned. It shoud provide newly created items data. But instead it returns the parent block data. So no id-s for the new blocks, no possbile work with them.

Notion API Reference [shows](https://developers.notion.com/reference/patch-block-children) that these details are provided for the correct reqeusts.

**To Reproduce**
1. Add a Notion node, set it as Block / Append
2. Insert the parent id (f.e. the page id)
3. Type in any text paragraph to append, like this: "A very new text" 
4. In the responce see the details of the parent block from p. 2. It looks like this:
`[
{
"object": "block",
"id": "a83c1f88-3595-4351-95a9-327e2cc85077",
"created_time": "2021-12-13T13:44:00.000Z",
"last_edited_time": "2021-12-13T15:29:00.000Z",
"has_children": true,
"archived": false,
"type": "child_page",
"child_page": {
"title": "Blocks"
}
}
]`

**Expected behavior**
Details if the newly created blocks should be in the responce, with their id's. Like this (taken from Notion API Reference):
`[[
       {
            "object": "block",
            "id": "9bc30ad4-9373-46a5-84ab-0a7845ee52e6",
            "created_time": "2021-03-16T16:31:00.000Z",
            "last_edited_time": "2021-03-16T16:32:00.000Z",
            "has_children": false,
            "type": "heading_2",
            "heading_2": {
                "text": [
                    {
                        "type": "text",
                        "text": {
                            "content": "Lacinato kale",
                            "link": null
                        },
                        "annotations": {
                            "bold": false,
                            "italic": false,
                            "strikethrough": false,
                            "underline": false,
                            "code": false,
                            "color": "default"
                        },
                        "plain_text": "Lacinato kale",
                        "href": null
                    }
                ]
            }
        },
        {
            "object": "block",
            "id": "7face6fd-3ef4-4b38-b1dc-c5044988eec0",
            "created_time": "2021-03-16T16:34:00.000Z",
            "last_edited_time": "2021-03-16T16:36:00.000Z",
            "has_children": false,
            "type": "paragraph",
            "paragraph": {
                "text": [
                    {
                        "type": "text",
                        "text": {
                            "content": "Lacinato kale",
                            "link": {
                                "url": "https://en.wikipedia.org/wiki/Lacinato_kale"
                            }
                        },
                        "annotations": {
                            "bold": false,
                            "italic": false,
                            "strikethrough": false,
                            "underline": false,
                            "code": false,
                            "color": "default"
                        },
                        "plain_text": "Lacinato kale",
                        "href": "https://en.wikipedia.org/wiki/Lacinato_kale"
                    },
                    {
                        "type": "text",
                        "text": {
                            "content": " is a variety of kale with a long tradition in Italian cuisine, especially that of Tuscany. It is also known as Tuscan kale, Italian kale, dinosaur kale, kale, flat back kale, palm tree kale, or black Tuscan palm.",
                            "link": null
                        },
                        "annotations": {
                            "bold": false,
                            "italic": false,
                            "strikethrough": false,
                            "underline": false,
                            "code": false,
                            "color": "default"
                        },
                        "plain_text": " is a variety of kale with a long tradition in Italian cuisine, especially that of Tuscany. It is also known as Tuscan kale, Italian kale, dinosaur kale, kale, flat back kale, palm tree kale, or black Tuscan palm.",
                        "href": null
                    }
                ]
            }
        }
    ]`

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version [e.g. 0.152.0

**Additional context**

**Comment by Joffcom** [comment]
Hey @artemdzyuba,

Are you still running into this issue? I just gave it a test on the lastest release and it looks like it is now working as you would expect.
