### ISSUE TITLE
HTTP Node - Digest Auth not working

### ISSUE THREAD

**Issue by aberndt-hub** [n8n-io/n8n#2567]
In the HTTP Node, the Digest Auth seems not to work correctly, authentication is rejected, server responds with **Authorization type not allowed.**
It seems there may be a problem with the headers, in 0.137.0 the request is different to 0.153.0, please see the pictures attache
***0.153.0:***
![01530](https://user-images.githubusercontent.com/65352601/146144374-47e4e741-81d7-4c7c-b761-2c22be8471ed.png)
***0.137.0:***
![01370](https://user-images.githubusercontent.com/65352601/146144379-286cad90-140e-4b79-bd58-6e04a01cd27f.png)

Env **N8N_USE_DEPRECATED_REQUEST_LIB=true** fixed the issue

**Comment by janober** [comment]
The fix just got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.157.0`

**Comment by aberndt-hub** [comment]
Hey n8n Team,
unfortunately, we are facing issues with DigestAuth also with 0.163.0
We get "Authorization failure" using the axios client. If we set the N8N_USE_DEPRECATED_REQUEST_LIB env, the request end successfully. 
<img width="1922" alt="Bildschirmfoto 2022-02-23 um 08 39 33" src="https://user-images.githubusercontent.com/65352601/155280118-8b8b1c61-8720-40df-a3ce-1ec0ea42b668.png">

**Comment by janober** [comment]
Do you have anything you can share that we can reproduce that issue? You can also share via email.

**Comment by aberndt-hub** [comment]
Unfortunately, I do not have any test data or test credentials. The application we want to reach is Xentral ERP.

**Comment by janober** [comment]
Fix got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.166.0`

**Comment by aberndt-hub** [comment]
Hello n8n team,
not sure if it should be a new ticket, but it´s related to DigestAuth so I decided to comment here again.
We found out, that there is still a problem with the DigestAuth on HTTP-request. Everything seems to be ok so far, but as we need to send query parameters with the Http-Request, the request fails. Same Request without any query params works fine. Please see the examples here:
Without query params:
<img width="1330" alt="Bildschirmfoto 2022-03-23 um 10 13 30" src="https://user-images.githubusercontent.com/65352601/159666200-f9d62b0f-04ba-422e-b01d-8397a70c3732.png">


with query params:
<img width="1328" alt="Bildschirmfoto 2022-03-23 um 10 22 17" src="https://user-images.githubusercontent.com/65352601/159666476-58b31d03-244e-4a51-96ff-e873310ba52d.png">
