### ISSUE TITLE
GitLab Trigger: unable to trigger from some event types (Release, Deployment, ...)

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#2590]
**Describe the bug**
I cannot select some event types for Gitlab trigger node - and they are also not available when selecting Wildcard (`*`) as events filter, as the gitlab webhook is created with the following events not subscribed to:
![Screenshot from 2021-12-22 20-54-01](https://user-images.githubusercontent.com/2084639/147147978-5902c192-73df-44ea-acfd-cd5525eb434d.png)

**To Reproduce**
1. Create Gitlab workflow trigger node
2. Select Wildcard as event
3. Check the created webhook in gitlab
4. Create a release / deployment / ...

**Expected behavior**
1. subscribe to all types when using wildcard
2. add types to list of available events

**Environment (please complete the following information):**
 - n8n Version: 0.151.0

**Comment by tennox** [comment]
Example workflow:
https://n8n.io/workflows/1375

**Comment by janober** [comment]
As you fixed the problem yourself and the PR got merged do I close this issue.

Thanks again!
