### ISSUE TITLE
Unable to build due to compile error

### ISSUE THREAD

**Issue by tom555my** [n8n-io/n8n#2594]
**Describe the bug**
Unable to build due to compile error.
```bash
 ERROR  Failed to compile with 4 errors                                                                                       12:13:35 PM

 error  in /Users/tommy.chung/Projects/n8n/packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue

ERROR in /Users/tommy.chung/Projects/n8n/packages/editor-ui/src/components/CredentialEdit/CredentialConfig.vue(216,29):
216:29 Property 'translation' does not exist on type 'INodeTypeDescription'.
    214 | 			const nodeInfo = nodesInfo.pop();
    215 |
  > 216 | 			if (nodeInfo && nodeInfo.translation) {
        | 			                         ^
    217 | 				addNodeTranslation(nodeInfo.translation, this.$store.getters.defaultLocale);
    218 | 			}
    219 | 		},
```

**To Reproduce**
1. Checkout to `master` branch
2. Pull the latest update
3. `npm run bootstrap && npm run build`

**Expected behavior**
The project is built

**Environment (please complete the following information):**
 - OS: MacOS 11.2.3
 - n8n Version [e.g. 0.119.0]
 - Node.js Version 14.18.0
 - Database system MySQL
 - Operation mode queue

**Additional context**

**Comment by rmaroun** [comment]
I have the same issue

**Comment by ivov** [comment]
The property exists on master:

https://github.com/n8n-io/n8n/blob/15aa0b79bd13e657b9a965ac8df479e869c8729f/packages/workflow/src/Interfaces.ts#L802-L821

Try this:

```
git reset --hard; git clean -dffx: lerna bootstrap --hoist; npm run build
```

Beware `git clean` will remove untracked files.

**Comment by rmaroun** [comment]
> The property exists on master:
> 
> https://github.com/n8n-io/n8n/blob/15aa0b79bd13e657b9a965ac8df479e869c8729f/packages/workflow/src/Interfaces.ts#L802-L821
> 
> Try this:
> 
> ```
> git reset --hard; git clean -dffx: lerna bootstrap --hoist; npm run build
> ```
> 
> Beware `git clean` will remove untracked files.

this works!! Thanks!

**Comment by Joffcom** [comment]
@tom555my any luck with the suggestion from @ivov?

**Comment by ivov** [comment]
Closing for now. If the issue persists, let us know and we will reopen.
