### ISSUE TITLE
Execute Workflow - Executions History

### ISSUE THREAD

**Issue by mizagog** [n8n-io/n8n#260]
Can’t seem to find Executions History for a workflow that ran from inside of a workflow (using Execute Workflow node)
without it, it is a bit difficult to see what went wrong with the “Sub Flow”.

**Comment by janober** [comment]
Github issues are only for bugs. Please post questions to the forum:
http://community.n8n.io/

**Comment by mizagog** [comment]
Oops sorry.

**Comment by janober** [comment]
No problem. I just want to make sure that all questions are in a single location that people have an easier time finding answers.
