### ISSUE TITLE
Duplicating nodes doubling 1111... index instead of 1, 2, 3

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#2600]
**Describe the bug**
When I duplicate a node, lets say, Set, instead of Set1, Set2, Set3, I get Set1, Set11, Set1111, Set11111111 and so on. So it doubles the 1111 suffix

Maybe it's made so intentionally
![image](https://user-images.githubusercontent.com/20184727/147354490-214be92e-9e6c-4a5f-91ea-3d29f02ec483.png)

**Environment (please complete the following information):**
 - Ubuntu Linux 20.04
 - n8n Version [e.g. 0.155.2]

**Comment by janober** [comment]
Fix got released with `n8n@0.157.0`
