### ISSUE TITLE
IF condition dont go forward to next node

### ISSUE THREAD

**Issue by simonlkch** [n8n-io/n8n#2616]
IF condition dont go forward to next node.
In my workflow, have a telegram trigger, than i check the sendid is admin or not.
In the below pic, the condition result is true, but the process goto the false .

![image](https://user-images.githubusercontent.com/3492546/147632917-8ca9d355-7d24-4f59-bca3-9cbb74cce005.png)
![image](https://user-images.githubusercontent.com/3492546/147632970-698e8d91-476c-40d6-adf6-56ba7c4b0214.png)

**Environment (please complete the following information):**
 - OS: docker
 - n8n Version 0.153.0

**Comment by janober** [comment]
Your picture actually shows the opposite. You have the "True" output selected and it does not contain any data. If you select "False" you will see that it correctly displays data there, the data it outputs on the false-branch.

The issue you are seeing is that you probably compare a number with a string (123 != "123"). Best delete the String-Condition and add a Number one instead. It should then work as epxected.

**Comment by simonlkch** [comment]
thanks for your hints, i cast int to string and it works perfectly

**Comment by janober** [comment]
Great, have fun!
