### ISSUE TITLE
[BigQuery] Cannot list a table of type VIEW

### ISSUE THREAD

**Issue by roycegeo** [n8n-io/n8n#2622]
**Describe the bug**
When connecting to BigQuery and executing a VIEW I get the following error - "Cannot list a table of type VIEW"

`ERROR:400 - {"error":{"code":400,"message":"Cannot list a table of type VIEW.","errors":[{"message":"Cannot list a table of type VIEW.","domain":"global","reason":"invalid"}],"status":"INVALID_ARGUMENT"}}
`
**To Reproduce**
1. Go to BigQuery Node
2. Connect to your GCP Project
3. Query a VIEW
4. See error below 

`ERROR:400 - {"error":{"code":400,"message":"Cannot list a table of type VIEW.","errors":[{"message":"Cannot list a table of type VIEW.","domain":"global","reason":"invalid"}],"status":"INVALID_ARGUMENT"}}`

**Expected behavior**
Expect the same behavior as with a standard table

**Environment (please complete the following information):**
 - OS: Mac OS
 - n8n Version [e.g. 0.119.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Comment by Joffcom** [comment]
Hey @roycegeo,

I was just looking at this one and it appears to be a limitation with the Google BigQuery API being used which is TableDataList (documented here: https://cloud.google.com/bigquery/docs/views-intro#view_limitations).

It looks like the solution would be to implement the jobs.query method which would be a feature request, I have created a feature request here: https://community.n8n.io/t/google-big-query-view-support/10372 that you can add your vote to and if you want add any additional information that may help us prioritise the request.

**Comment by Joffcom** [comment]
Hey @roycegeo,

I am going to mark this one as closed for now as it is more of a feature request than an issue.
