### ISSUE TITLE
Notion Trigger doesn't trigger

### ISSUE THREAD

**Issue by baptisteArno** [n8n-io/n8n#2645]
When executing a workflow that starts with a Notion Trigger block it works fine. However, the workflow is not executed on the defined Poll Time. The trigger is set on "Page added to Database".

My database is sorted by ascending Created date. Could that cause the issue? What are the requirements in order to execute the trigger?

 - n8n Version  0.157.1

**Comment by Joffcom** [comment]
Hey @baptisteArno,

It might be worth posting this on the community forum here: https://community.n8n.io/, I am not aware of any issues with the Notion Trigger at the moment so it might be worth posting your workflow as well and we can have a play.

~ Jon

**Comment by baptisteArno** [comment]
Thank you for your quick answer 💪

Here is the workflow:
```json
{
  "name": "Populate TV Watch list",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "event": "pageAddedToDatabase",
        "databaseId": "=9ad9c9bcbb6548008ea4b64e8c16a530"
      },
      "name": "Notion Trigger",
      "type": "n8n-nodes-base.notionTrigger",
      "typeVersion": 1,
      "position": [
        440,
        440
      ],
      "credentials": {
        "notionApi": {
          "id": "7",
          "name": "Notion account"
        }
      }
    },
    {
      "parameters": {
        "url": "=http://www.omdbapi.com/?apikey=<YOUR_API_KEY>&t={{encodeURIComponent($json[\"Title\"])}}",
        "allowUnauthorizedCerts": true,
        "options": {}
      },
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        650,
        450
      ]
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": "={{$node[\"Notion Trigger\"].json[\"id\"]}}",
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "Directed by|rich_text",
              "textContent": "={{$json[\"Director\"]}}"
            },
            {
              "key": "Status|select",
              "selectValue": "373e2fc2-4201-4b07-b3b0-4a25b600b279"
            },
            {
              "key": "Tags|multi_select",
              "multiSelectValue": "={{$json[\"Genre\"]}}"
            },
            {
              "key": "Actors|multi_select",
              "multiSelectValue": "={{$json[\"Actors\"]}}"
            },
            {
              "key": "Rating|number",
              "numberValue": "={{parseFloat($json[\"imdbRating\"])}}"
            },
            {
              "key": "Year|number",
              "numberValue": "={{parseInt($json[\"Year\"])}}"
            },
            {
              "key": "Imdb|url",
              "urlValue": "=https://www.imdb.com/title/{{$json[\"imdbID\"]}}"
            },
            {
              "key": "Title|title",
              "title": "={{$json[\"Title\"]}}"
            }
          ]
        }
      },
      "name": "Notion",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 1,
      "position": [
        850,
        450
      ],
      "credentials": {
        "notionApi": {
          "id": "7",
          "name": "Notion account"
        }
      }
    }
  ],
  "connections": {
    "Notion Trigger": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "Notion",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": true,
  "settings": {
    "timezone": "Europe/Paris",
    "executionTimeout": -1
  },
  "id": 2
}
```

Make sure to replace `<YOUR_API_KEY>` with an API key from Open Movie Database that can be created easily [here](http://www.omdbapi.com/apikey.aspx)

And [here is the Notion template](https://baptistearno.notion.site/f4a0f9d748874fdbb1c7f1a16adafe96?v=b0ca2768e05541478f9079aa71bc3120)

**Comment by Joffcom** [comment]
Hey @baptisteArno,

I have tested it here and it appears to be working as expected and every minute it is connecting and updating the entries, Have you checked your execution log in n8n if you have it enabled?

**Comment by baptisteArno** [comment]
Thank you for reproducing!

This is odd, no logs since yesterday's manual execution:
![CleanShot 2022-01-07 at 11 24 01@2x](https://user-images.githubusercontent.com/16015833/148530247-3a3fe118-43e5-40d3-b0be-5786488cd548.png)

Also on Notion trigger block I have this odd warning:  The value "9ad9c9bcbb6548008ea4b64e8c16a530" is not supported!
<img width="462" alt="CleanShot 2022-01-07 at 11 24 21@2x" src="https://user-images.githubusercontent.com/16015833/148530293-b44c8568-86e6-4bc6-9ac1-e0349f9cfc35.png">

**Comment by Joffcom** [comment]
Hey @baptisteArno,

That could be it, So what I did was on the cog reset the value then tell it to refresh the list and it will pull the names down.

![image](https://user-images.githubusercontent.com/4688521/148536861-43882036-dba2-4ee5-bc36-3880837b67cf.png)

I wonder if that is why it isn't working, I take it you have saved and activated the workflow on the top right as well.

**Comment by baptisteArno** [comment]
I had to remove the block, add it again and now it displays the database. 👍

But still, it only triggers an execution when saving the workflow.

Question: Is it supposed to display a log even though nothing has been added to the database?

**Comment by Joffcom** [comment]
Hey @baptisteArno,

No it will only log if there is new data in the table from what I can see, Is the workflow active on the top right as well?
