### ISSUE TITLE
Sao Paulo timezone should be GMT-3

### ISSUE THREAD

**Issue by m2scared** [n8n-io/n8n#2647]
**Describe the bug**
Sao Paulo is configured as GMT-2 but it should be GMT-3.

See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Fix at: https://github.com/sanohin/google-timezones-json/pull/3/files

**To Reproduce**
1. Go to 'Workflow'
2. Click on 'Settings'
3. Click on 'Timezone'
4. Scroll down to 'Sao Paulo'
5. See GMT-2

**Expected behavior**
See GMT-3.

**Environment (please complete the following information):**
 - OS: any
 - n8n Version 0.157.1
 - Node.js Version 14.15.0
 - Database system SQLite
 - Operation mode own

**Additional context**
N/A.

**Comment by luizeof** [comment]
@harshil1712 we no longer have daylight save in brazil, now sao paulo is always -3:00 ;)

**Comment by Joffcom** [comment]
Hey,

Been chatting internally about this one, the module used has not been updated for a while so I don't know if they will accept the pull request so we may have to take another route.

I did find it interesting that the time has not changed since 2019 though.

**Comment by Joffcom** [comment]
Hey @m2scared & @luizeof,

Not forgotten about this one, We wanted to give the maintainer of the package enough time to accept the pull request before taking other routes to resolving this one. We have a couple of ideas so are just working out which one will be better to take long term.

**Comment by m2scared** [comment]
Thanks @Joffcom.

**Comment by kimtiago** [comment]
Any news about this?

**Comment by Joffcom** [comment]
@kimtiago looks like the package we use has not accepted the fix yet so we will likely have to move on an alternative approach.

I will find see if I can find anything internally on this one.

**Comment by kimtiago** [comment]
I need to tell you that the other timezones from Brazil are wrong too.

**Comment by Joffcom** [comment]
Hey @kimtiago,

Here is fine, There are also Australian zones missing as well.

**Comment by netroy** [comment]
Would it make sense to switch to either of these 2 well-maintained libraries?

* https://github.com/dmfilipenko/timezones.json
* https://github.com/vvo/tzdb

**Comment by Joffcom** [comment]
@m2scared they merged it 🙂
