### ISSUE TITLE
Node 16 compatibility

### ISSUE THREAD

**Issue by maitrungduc1410** [n8n-io/n8n#2659]
**Describe the bug**
When building this project with Node 16 I'm receiving this issue: `Assertion `thread_id_key != 0x7777' failed`

It's because of `fibers` which is used for `design-system` doesn't work since Node 16. Remove it and re-run `lerna bootstrap --hoist` fixes the issue

**Comment by Joffcom** [comment]
Hey @maitrungduc1410,

Do you get the same issue if you try running on Node 14.18?

**Comment by ivov** [comment]
Thank you for the information. Ideally we'd need a way to disable `fibers` only on Node 16 so that build times on older versions are unaffected.

**Comment by maitrungduc1410** [comment]
@Joffcom haven't tried with node 14, but when searching on the Internet node 14 seems okay, just from node 16
