### ISSUE TITLE
HTTP headers should be trated as case-insensitive

### ISSUE THREAD

**Issue by rafalkrupinski** [n8n-io/n8n#2663]
When setting custom 'Accept' header, the line below makes the HTTPRequest node add its own 'accept' header

https://github.com/n8n-io/n8n/blob/8386d7c73ee7d7a4242d6730a4eab400336b0bd6/packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts#L924

**Comment by janober** [comment]
Thanks a lot. Very good point. Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with `n8n@0.160.0`
