### ISSUE TITLE
Jira Node cropping user's selection list to max of 50 results

### ISSUE THREAD

**Issue by Lngramos** [n8n-io/n8n#2670]
**Describe the bug**

Both the Assignees and Reporters field options are incomplete and only shows up to 50 results, despite the real count of users being higher than that.

According to the [getUsers](https://github.com/n8n-io/n8n/blob/688cfc76b384d20a180ba63b5bf1269d65928cb1/packages/nodes-base/nodes/Jira/Jira.node.ts#L306-L337) data fetching function uses the `jiraSoftwareCloudApiRequest`, maybe using the other paginated method called `jiraSoftwareCloudApiRequestAllItems` might be enough to fix this? (or perhaps not, since I'm not too familiar with Jira's APIs).

**To Reproduce**

Steps to reproduce the behaviour:

1. First ensure your Jira server/cloud have >50 users that can be used as assignees or reporters.
2. Add a new Jira node
3. Set resource field to issue
4. Set operation field to create
5. Add a reporter/assigned additional field
6. Count the number of options available to pick from in the dropdown menu

**Expected behaviour**

I would like to be able to see all organisation member names in the options dropdown menus, in other words, a count that is higher than 50 entries.

**Environment (please complete the following information):**
 - OS: n/a
 - n8n Version: 0.158.0
 - Node.js Version: n/a
 - Database system: n/a
 - Operation mode: n/a

**Additional context**

This particular issue wouldn't be a massive problem if I was able to target a user by their ID instead of having to always pick an option from the dropdown menu.

I also noticed that the APIs are returning deactivated users which isn't very useful.

**Comment by robertrodrigues** [comment]
This is also a problem for us too.
If you need any more investigatory work, please let me know.

**Comment by pemontto** [comment]
> This particular issue wouldn't be a massive problem if I was able to target a user by their ID instead of having to always pick an option from the dropdown menu.

@Lngramos FYI it's possible to ignore the dropdown and set the ID manually. You just need to make it an expression
<img width="341" alt="n8n_-_⚠️_My_workflow_4" src="https://user-images.githubusercontent.com/939704/152698455-a1cc2e6a-be2f-43a6-95fb-957057a56817.png">

**Comment by robertrodrigues** [comment]
@pemontto Is the ID one that is acquired through JIRA's API by querying the user?

**Comment by robertrodrigues** [comment]
Out of curiosity, do we know if this has been put into bug fixes yet?
