### ISSUE TITLE
MongoDB find not working with _id: String

### ISSUE THREAD

**Issue by achtan** [n8n-io/n8n#2682]
**Describe the bug**
getting this error `Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters` when I use a `find` Operation with `{"_id": "616033733ad60125a0ef578t"}` Query
I store `_id` as a regular String (not an ObjectId).

**To Reproduce**
1. setup MongoDB node
2. Operation: Find
3. Query: `{"_id": "616033733ad60125a0ef578t"}`

**Expected behavior**
Result from MongoDB search

**Environment (please complete the following information):**
 - OS: mac
 - n8n APP 1.0.0

**Comment by janober** [comment]
That is very confusing. Sadly no idea why it does not work for you. That is already possible for quite a while. n8n automatically converts what it finds as `_id` and converts it to an ObjectID. I did just test it locally with the below workflow (in a second step did I copy over the resolved value into the disconnected node to make sure that it works to 100%). It found both times the record without a problem.

```json
{
  "nodes": [
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "name",
              "value": "test"
            },
            {
              "name": "date",
              "value": "={{new Date().toISOString()}}"
            }
          ]
        },
        "options": {}
      },
      "name": "Set1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        580,
        320
      ]
    },
    {
      "parameters": {
        "operation": "insert",
        "collection": "workflow",
        "fields": "name,date",
        "options": {
          "dateFields": "date"
        }
      },
      "name": "MongoDB1a",
      "type": "n8n-nodes-base.mongoDb",
      "typeVersion": 1,
      "position": [
        820,
        320
      ],
      "credentials": {
        "mongoDb": {
          "id": "396",
          "name": "Docker Mongo local"
        }
      }
    },
    {
      "parameters": {
        "collection": "workflow",
        "options": {},
        "query": "={\"_id\": \"{{ $json[\"id\"] }}\"}"
      },
      "name": "MongoDB4",
      "type": "n8n-nodes-base.mongoDb",
      "typeVersion": 1,
      "position": [
        1040,
        320
      ],
      "credentials": {
        "mongoDb": {
          "id": "396",
          "name": "Docker Mongo local"
        }
      }
    },
    {
      "parameters": {
        "collection": "workflow",
        "options": {},
        "query": "{\"_id\": \"61e2b13a7c4675002b5f684a\"}"
      },
      "name": "MongoDB",
      "type": "n8n-nodes-base.mongoDb",
      "typeVersion": 1,
      "position": [
        1260,
        320
      ],
      "credentials": {
        "mongoDb": {
          "id": "396",
          "name": "Docker Mongo local"
        }
      }
    }
  ],
  "connections": {
    "Set1": {
      "main": [
        [
          {
            "node": "MongoDB1a",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "MongoDB1a": {
      "main": [
        [
          {
            "node": "MongoDB4",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by janober** [comment]
As we did not hear back do I assume that the issue got solved, so I close this issue. If you still have problems simply comment here again.

**Comment by helder-mattos** [comment]
@janober I'm having the same issue. The problem comes exactly from the conversion of an ID to an ObjectId as you said.

> n8n automatically converts what it finds as _id and converts it to an ObjectID

As @achtan I store all my collection Ids as strings instead of ObjectId. Currently, there are almost no limitations on what kind of BSON object can be used as an ID (except Array). This means that in our case converting the string to an ObjectId type automatically causes the query to fail.

I think that an improvement should be made to convert to object id only as a function on the query parameters. Or have an explicit option that would disable this automatic conversion.

As a workaround I used the aggregate option instead of find, which didn't have the ID transformed.  

KO
```
Operation: Find
Query: { "_id": "AnB6HBYbTC"}

```
OK
```
Operation: Aggregate
Query: [{"$match": { "_id": "AnB6HBYbTC"}}]
```

**Comment by trialsin** [comment]
Really Really bad! Same behaviour in 2024!

Thank you @helder-mattos for workaround

**Comment by codev911** [comment]
update method is not work too btw

**Comment by davidbalivo** [comment]
Any update on this topic? I am facing the same issue when trying to find by id:

`{   "_id": "67973e98fece5f8b9783e7c6" }`

Even though the document exists, it does not find it

**Comment by acekevin** [comment]
👋  It's not explained why this issue was closed but it continues to be a problem if you use Mongo with non-objectId formatted _ids. Would the team be open to re-opening and adding an option to override the ObjectId function overloading?

**Comment by natalieAceable** [comment]
Yes this absolutely is still an active issue that I hope the team will reopen.

**Comment by snowdog773** [comment]
I have had this issue intermittently, where retrieving an _id from a find query. Sometimes this gets passed on to the next node as an object ID, and sometimes as I assume a string where it gets wrapped in quotes. I can find no clear reason for this intermittent behaviour. 

I did however discover that placing an empty Javascript code node immediately after the Mongo node seems to reset it back to an object ID. No idea why or how but judging by the messages on this post people are still getting stuck with this. Hopefully a useful workaround for some of you.
