### ISSUE TITLE
Error: 'Edit Image' node not known 

### ISSUE THREAD

**Issue by alt-shreya** [n8n-io/n8n#2683]
**Describe the bug**
I get this error: _'Edit Image: Node Type is not known.'_ when trying to add a node to resize an image on n8n Desktop app.

**To Reproduce**
1. Go to [Edit image Workflow](https://n8n.io/workflows/591)
2. Copy and paste the given workflow onto the workspace.

**Expected behavior**

![image](https://user-images.githubusercontent.com/70858293/149629697-e0ab9234-2af3-4aed-8bf6-9b1d0f1cf5ec.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - n8n Version 0.153.0
 - Node.js Version v16.7.0
 - Database system PostgreSQL

**Additional context**

**Comment by janober** [comment]
Yes, the Desktop Version does for technical reasons sadly not contain that node.
