### ISSUE TITLE
cannot execute cmd command

### ISSUE THREAD

**Issue by connected201** [n8n-io/n8n#2684]
Hi, i want to execute "cmd" but no success!
![LgR4ubf8Kh](https://user-images.githubusercontent.com/20506433/149640631-8e88bfad-9ee8-4647-804c-e07ad37a5519.gif)
![image](https://user-images.githubusercontent.com/20506433/149640649-8484d820-8b65-4894-b4bb-5e21e0c6dbc7.png)

another commands, like "calc" work well

 - OS: Windows 10
 - n8n Version last

**Comment by connected201** [comment]
UPD, also please check "dxdiag" n8nwill not be considered a successful launch until the dxdiag window will not be closed

**Comment by janober** [comment]
That does not sound like a bug. Please post in the community forum about that here:
https://community.n8n.io/
Thanks!
