### ISSUE TITLE
Create Gitlab integration

### ISSUE THREAD

**Issue by janober** [n8n-io/n8n#27]
Create an integration for Gitlab similar to the Github one.
https://docs.gitlab.com/ee/api/

Github-Node is a good reference and starting point:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Github/Github.node.ts

Discussion in forum:
https://community.n8n.io/t/gitlab-integration/21

**Comment by estevam31** [comment]
I would love to work on this!

**Comment by janober** [comment]
@estevam31 Thanks, great to hear! In the forum (link above) CrystalMethod said he would work on it but that was 19 days ago. Did not hear anything since and also never got an answer to my question. I guess he maybe decided differently. I just wrote him in the forum to ask. Let's see if he answers. Anyhow, in the end you can decide yourself. Who ever creates it first gets it merged.
Would however also be sad if two people create the same integration when so many other ones are still missing ;-) So not sure how fast you wanted to start.

**Comment by estevam31** [comment]
@janober No problem. I'm currently developing an integration with Gitlab in a personal project and at worst working on this would bring me some piece of knowledge. I will try to implement this, but as he has already taken on this task, if he answers the priority is all his.

Thanks for your time.

**Comment by janober** [comment]
@estevam31 Like how you approach things! Btw. great to have you on board and as a future contributor. Very appreciated!

**Comment by janober** [comment]
@estevam31 Ok would say you are good to go. Did not get any answer. So looking forward to it!

**Comment by lucafaggianelli** [comment]
Great, I was looking for the GitLab node! @estevam31 @janober if you need any help for building or testing it, just drop a line.

**Comment by estevam31** [comment]
@lucafaggianelli I'm quite busy these days, if u want to take this on your own, it will be better for the project.

**Comment by lucafaggianelli** [comment]
@estevam31 no problem, I can work on this next week

**Comment by janober** [comment]
Sorry totally forgot about that issue. Close now as the integration got created already a while ago.
