### ISSUE TITLE
Chokidar update causes type failure

### ISSUE THREAD

**Issue by UlisesTorrella** [n8n-io/n8n#2702]
**Describe the bug**
I was running this proyect but at the time of built if failed with this error:
`Type 'null' is not assignable to type 'AnymatchMatcher | undefined'`
At /packages/nodes-base/nodes/LocalFileTrigger/LocalFileTrigger.node.ts (196) 

**To Reproduce**
1. Delete previous n8n-custom image
2. docker build -t n8n-custom -f docker/images/n8n-custom/Dockerfile .

There it failed to me

**Expected behavior**
Should build the image

**Environment (please complete the following information):**
 - Docker image: FROM node:14.15-alpine

**Additional context**

I solved it in my instance, just went into /packages/nodes-base/package.json and changed line 701 to:
    "chokidar": "3.5.2",

**Comment by Joffcom** [comment]
Hey @UlisesTorrella,

This looks like a change that was pushed yesterday to the master branch (https://github.com/n8n-io/n8n/commit/f5991e17db92e959f4f6f87622fbc0c7f4c60b8c), When you did the build were you using the latest source?

**Comment by ivov** [comment]
This was fixed by the linked commit. Please pull again. Thank you.
