### ISSUE TITLE
emailReadImap not trigger further nodes

### ISSUE THREAD

**Issue by rottmann** [n8n-io/n8n#2729]
**Describe the bug**

When using emailReadImap and execute it manually, it loads the unseen mail, marks it as seen and process the mail to the next node (which sends me a mail).

I mark the mail as unread, press "Execute Workflow" again, it work (again).

I mark the mail as unread again, set workflow to "active", wait 1 minute, the mail got marked as read, but no further processing is executed.

This worked since some weeks. But i am not sure if it stops working after Update to 0.160. or after i purge the sqlite-log file (cause it was 900 MB huge).

**To Reproduce**

Have 2 nodes, emailReadImap and after that send me a notification/mail node (i omitted the sent mail node here):

```
    {
      "parameters": {
        "format": "resolved",
        "options": {
          "customEmailConfig": "[\"UNSEEN\"]",
          "allowUnauthorizedCerts": true,
          "forceReconnect": 1
        }
      },
      "name": "New E-Mail",
      "type": "n8n-nodes-base.emailReadImap",
      "typeVersion": 1,
      "position": [
        430,
        -640
      ],
      "alwaysOutputData": false,
      "credentials": {
        "imap": {
          "id": "14",
          "name": "IMAP Mailbox"
        }
      }
    }
```

**Environment:**
 - OS: docker container latest
 - n8n Version 0.160.0

**Comment by Joffcom** [comment]
Hey @rottmann,

Have you checked the execution log to see what that shows?

**Comment by rottmann** [comment]
Weird, send the exactly same testmail this morning, as i do it last week 10 times, now it works again. It create log-entries too.
Close this, if it happen again i check debug logs in details. Thx and sorry for the unnecessary post.
