### ISSUE TITLE
Database improvement - please implement

### ISSUE THREAD

**Issue by sutidor** [n8n-io/n8n#273]
Hey, my PostgreSQL database grew to 3GB because of some webhook-gone-wild and so I decided to shrink it to 1,5 MB - which was not as easy as expected. I share my workflow for others that might run into these issues and for developers who want to implement the behaviour into core.

First of all I "installed" adminer, a neat database maintenance tool, which is a single PHP file. Dont forget to secure access via .htpasswd or similar. The tool is similar to PHPmyadmin and can execute SQL queries.

First I deleted the rows of the workflow executions mentioned above.

What is the execution count per workflow:
Workflow execution count per workflow_entity
`SELECT b.name, COUNT (a.id) FROM execution_entity as a
LEFT JOIN workflow_entity as b
ON a."workflowId" = b.id::character varying
WHERE b.id::character varying = a."workflowId"
GROUP BY b.id;`

Check execution data of missing workflows:
`SELECT COUNT (a.id) FROM execution_entity as a
LEFT JOIN workflow_entity as b
ON a."workflowId" = b.id::character varying
WHERE b.id IS NULL;`

Delete them:
`DELETE FROM execution_entity
USING execution_entity as a
LEFT OUTER JOIN workflow_entity as b ON 
a."workflowId" = b.id::character varying
WHERE
execution_entity.id = a.id AND
b.id IS NULL;`

But the database is still the same size.
`VACUUM full;`
does not help.

I exported the table, dropped it and imported it again. (Maybe I should have used truncate instead)
Because of that, the table fell out of sync with the auto-increment IDs.

Check (values must be the same):
`SELECT MAX(id) FROM execution_entity;
SELECT nextval('execution_entity_id_seq');`

realign SEQUENCE only
`SELECT setval('execution_entity_id_seq',(SELECT MAX(id) FROM execution_entity));`

I think it is not recommended to alter ids, but I like my table in order. So I issued new ids:
`UPDATE execution_entity SET id=1000000+ nextval('execution_entity_id_seq');
ALTER SEQUENCE execution_entity_id_seq RESTART;
UPDATE execution_entity SET id = DEFAULT;`

This gives me a weird order. I want the ids to be ordered by Timestamp
`UPDATE execution_entity SET id=1000000+ nextval('execution_entity_id_seq');
UPDATE execution_entity t
SET id = rn
FROM (
   SELECT *, ROW_NUMBER () OVER (ORDER BY "startedAt") as rn
   FROM   execution_entity
   ORDER  BY "startedAt" ASC
   ) as u
WHERE  u."startedAt" = t."startedAt";
SELECT setval('execution_entity_id_seq',(SELECT MAX(id) FROM execution_entity));`

Finally I want to make sure, whenever a workflow gets deleted, the execution data is deleted too. First we need the "workflowId" column be integer (instead of varchar)
`ALTER TABLE "execution_entity"
ALTER COLUMN "workflowId" TYPE integer USING ("workflowId"::integer),
ALTER "workflowId" DROP DEFAULT,
ALTER "workflowId" SET NOT NULL;`

And finally I want the cascade to fire, when I delete / update a workflow by establishing a foreign key relation
`ALTER TABLE "execution_entity"
ADD FOREIGN KEY ("workflowId") REFERENCES "workflow_entity" ("id") ON DELETE CASCADE ON UPDATE CASCADE;`

I would love to see the foreign key relationship directly implemented in n8n and some delete functions in the execution window.

Database size is now 1,5 MB (!).

**Comment by janober** [comment]
Thanks a lot for writing that up. I can see how it can be very helpful for people in a similar situation and is definitely something where n8n still has to get improved!

But I wonder if you could maybe for now avoid that problem by not saving successful executions? Or do you need them for some reason? Normally saving just the ones that fail should be enough in the most situations.

Something that is definitely also needed is autodeleting past executions after x days. I guess, for now, you can, however, fix that with a simple n8n workflow that runs every day to clean up old ones directly in Postgres. Normally the freed up disk space should become available again and so be reused. Even though it will for sure get larger than 1.5MB it should so at least not hit the 3GB again.

**Comment by RicardoE105** [comment]
Closing this issue. @sutidor  Again, thanks for putting that up. You can go to our community and request this feature https://community.n8n.io/. There, the community can vote for this feature, the more votes the more chance is added to the next release.
