### ISSUE TITLE
Brandfetch node does not authenticate

### ISSUE THREAD

**Issue by jayvaglio** [n8n-io/n8n#2755]
**Describe the bug**
The Brandfetch node seems to be outdated / does not work. 

**To Reproduce**
1. Add Brandfetch node to canvas
2. Add credential
3. Paste API from Brandfetch dev website and save
4. Add domain URL
5. Execute workflow
6. See error: ERROR: Forbidden - perhaps check your credentials? "Request failed with status code 403",

**Expected behavior**
API would pull back brand content for the domain (name, brand colors, logo, etc)

**Environment (please complete the following information):**
 - OS: Mac OS version 11.6.1
 - n8n Version **Desktop version 1.00**

**Additional context**
I was able to use HTTP Request node and it works... so it appears the node is broken.

**Comment by Joffcom** [comment]
Hey @jayvaglio,

I have just given this a go here and I have not been able to reproduce the issue, If I input an incorrect API token though it does fail as expected with a 403 Forbidden error.

It may be worth making sure there are no spaces hiding in the API Key field.

**Comment by jayvaglio** [comment]
Hmm... I have tested and so has another teammate and we both keep getting the error. It works when using the HTTP Request node using the same API key.

**Comment by Joffcom** [comment]
That is strange, I have tried our testing api key on Mac Desktop, Docker and Cloud with no issue.

I will sign up for a new key today and see if that changes anything but I would expect it to work if the HTTP Request node is working.

I would also expect it to fail for me if it was a node issue as well though. I will be back once I have tested with a new key.

**Comment by Joffcom** [comment]
Hey @jayvaglio,

Good news, I have managed to reproduce this issue by generating a new API key. I will dig into this more this week and see what I can find.

**Comment by Joffcom** [comment]
Hey @jayvaglio,

What has happened here is Brandfetch have moved to v2 of their API and the newer tokens being issued don't support v1 which is a bit of a pain.

As this is more of a feature request and you have a solution using the HTTP Request node I have created a new request post on the community forum here: https://community.n8n.io/t/brandfetch-support-v2/11254 feel free to go and give it a vote.

This will allow us to track demand and prioritise the change, For now though I will get this issue marked as closed.
