### ISSUE TITLE
Mouse button up event cancels dialogs

### ISSUE THREAD

**Issue by mponton** [n8n-io/n8n#2759]
**Describe the bug**
If you have a dialog open in n8n and click a mouse button inside the dialog but release it outside of the dialog, the dialog will close. This is happening to be regularly when selecting text. I click a field, drag the mouse quickly to select the text and release the mouse button outside the dialog which then closes said dialog.

**To Reproduce**
1. Do any action that opens a dialog in n8n
2. Click inside the dialog, leave mouse button pressed, drag mouse outside and release button

More specific example:

1. Open a workflow
2. Open the menu and click "Duplicate"
3. In the dialog shown, click at the end of the text field for the workflow name, leave button pressed to select text in the field, drag outside of the dialog, release mouse button. Dialog will close.

**Expected behavior**
Dialogs should not close if the mouse button is pressed INSIDE and released OUTSIDE of the dialog. I can understand closing the dialog if the mouse button is pressed OUTSIDE (i.e. mouse button down event outside) but even that is questionable with most of the current UI design that has both a CANCEL and an "ACTION" button (e.g. SAVE). But very acceptable since usual behaviour of web apps.

**Environment (please complete the following information):**
 - OS: Mac OS 12.1
 - n8n Version: 1.2.0 DESKTOP
 - Node.js Version: N/A (included with desktop version)
 - Database system: N/A
 - Operation mode: own

**Additional context**
None but happy to provide any further information needed. Thanks!

**Comment by bolshoytoster** [comment]
@mponton it sounds like this is intended, but it would probably be better if it closed on mouse button down though.

**Comment by janober** [comment]
@mponton Totally agree that should not happen and is quite annoying.

@bolshoytoster Is probably intended by element UI, which we are using right now underneath the hood, but not from our side.

So generally should be changed. Contributions are always welcome.

**Comment by Jsnxyz** [comment]
@janober I have a way to make it work, although like you mentioned, the root of the issue is from element UI and should be fixed from their side. 

But anyway, just in case somebody is interested, on **Modal.vue**, here are the following changes - 

```html
<el-dialog
	v-on:mouseup.native="checkMouseEventElement"
	v-on:mousedown.native="markMouseDownEventElement"
	:visible="visible"
	:before-close="closeDialog"
	:class="{'dialog-wrapper': true, [$style.center]: center, scrollable: scrollable}"
	:width="width"
	:show-close="showClose"
	:custom-class="getCustomClass()"
	:close-on-click-modal="closeOnClickModal"
	:close-on-press-escape="closeOnPressEscape"
	:style="styles"
	append-to-body
>
```
```typescript
data () {
    return {
	mouseEventElement: null as EventTarget | null, //EventTarget element to keep note of when `mousedown` event occurs.
	shouldModalClose: false, // Tracker to check if Modal should close since element UI has weird behavior as suggested in issue #2759.
   };
},
```
```typescript
async closeDialog() {
	if (this.beforeClose) {
		const shouldClose = await this.beforeClose();
		if (shouldClose === false) { // must be strictly false to stop modal from closing
			return;
		}
	}
	if(!this.shouldModalClose) {
		this.shouldModalClose = false; // reset ModalClose to false.
		return;
	}
	this.$store.commit('ui/closeModal', this.$props.name);
}
```
```typescript
markMouseDownEventElement(e:Event) {
	this.mouseEventElement = e.target; // Mark the element where mousedown occurred
	this.shouldModalClose = false; // reset ModalClose to false
},
checkMouseEventElement(e:Event): boolean {
	const element = e.target;
	if(element === this.mouseEventElement) { // if mouseup and mousedown events happened on same element, allow modal to close. 
		this.shouldModalClose = true;
	}
        this.mouseEventElement = null; // reset mouseEventElement 
	return this.shouldModalClose;
},
```


P.S.: I was almost about to leave it at that and was about to ask for a PR since this would have been my first contribution ever until I realized Dialogs like Import from Url etc uses Element UI's MsgBox which to me seems like is just too much to hack around for this to work. :(

**Comment by mponton** [comment]
@janober @Jsnxyz Sorry for not responding earlier. Been swamped at work. I did not realize this might indeed be the behaviour of the underlying framework used for the UI. I appreciate your work @Jsnxyz but I think like you it might be a kludge to attempt to workaround this in n8n instead of reaching out to the Element UI team to see if this is something that could be addressed on their side. I will have a look and reach out to them see myself and keep you posted if you want to keep this issue open for a while.  Thanks!

**Comment by mponton** [comment]
Well, this seems related https://github.com/ElemeFE/element/issues/19223 but I'm not holding my breath as there are over 2000 issues open and this is dated April 2020. There are also over 247 PRs open so yeah, I have a feeling I'll have to live with this behaviour. Thanks for the great work on n8n though, I may complain about this but I still love n8n 😃 I'll close this as I feel it's not an issue for the n8n team to fix. Thanks!

**Comment by Jsnxyz** [comment]
@mponton The root issue is also really not hard to fix. But yeah, if it's a fairly inactive or slow moderators, there's not much that can be done immediately. =)

**Comment by mponton** [comment]
@Jsnxyz I wish I have better frontend JS skills to understand and help but again if it takes months and years for them to integrate into the codebase I'm not sure I'd put the effort to do a PR. I appreciate your feedback on this though. Thanks!
