### ISSUE TITLE
Token is not valid: undefined. Github token credentials

### ISSUE THREAD

**Issue by olsh** [n8n-io/n8n#2766]
**Describe the bug**
When I try to add new Github credentials (personal token), I get the following error message:
```
Couldn’t connect with these settings 
Token is not valid: undefined
```

**To Reproduce**
1. Go n8n
2. Credentials new
3. Select `Github API` in the credentials selector
4. Fill credentials and click save
5. Get the error 

**Expected behavior**
There is no error and credentials were successfully created

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n 0.161.1
 - Node.js Version v16.13.2
 - Database system SQLite

**Additional context**
Github OAuth authorization works without any issues

**Comment by janober** [comment]
I just tested, for me, it works fine. Additionally did we not change anything on the node for quite a while. So is the chance that it is a bug very small. For that reason please post in the forum instead. There you will find help the fastest. 

The forum URL: https://community.n8n.io/
