### ISSUE TITLE
No output on Redis node in other nodes expression editor when the Redis key is not found

### ISSUE THREAD

**Issue by immanuelfodor** [n8n-io/n8n#278]
**Describe the bug**
Upon getting a Redis key, if the key is not found in the DB, the output parameter is set to null. This causes other nodes' expression editors not to display the Redis node's output value.

**To Reproduce**
1. Add a Redis node and look for a non-existent key (like an uninitialized cache key)
2. Run the node, it displays the output key as null value
3. Add a new node, e.g., an IF, and try to add a new expression to use the Redis node's output in a condition
4. No output is displayed on the Redis node (but there should be one with null value), and if you add it by hand, the node fails with an expression error

**Expected behavior**
The Redis output is available in the expression editor even if it's null. 

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version: latest DockerHub build
 - Node.js Version: latest DockerHub build

**Additional context**
I could circumvent the bug using a Set node after the Redis node to set up an expression if the Redis output key is null, then use an empty string as default (`{{ redis.data[redis.parameter[name]] || ""}}` can't remember the exact syntax right now). However, it feels like a hack, there should be an option to provide a default value if the key returns a null value or make the returned null also visible on other nodes.

**Comment by janober** [comment]
Thanks for reporting this.Try to have a look the next days.

**Comment by janober** [comment]
Ok got fixed. Changed two things.
 1. If a key does not get found it sets it now to `null` instead of `undefined` that makes sure that it does not get "lost" as in JSON they get simply removed. But at the same time still allows to specifically check if the key exists or not (would not be possible with "" as an empty string and not set would be the same)
 2. Fixed issue that the variable selector did not display properties with the value `null` and was so also not selectable

Will be released with the next version.

**Comment by immanuelfodor** [comment]
Thank you so much, I'm waiting for the release to test it! :)

**Comment by janober** [comment]
You are welcome. Happy if it helps. Enjoy your weekend! I will update here once the new version got released.

**Comment by janober** [comment]
Got released with n8n@0.53.0

**Comment by immanuelfodor** [comment]
It works as expected, nulls now propagate from Redis nodes, and it can be selected in other nodes' expression editors, so I could remove the extraneous set nodes from the workflows. Thanks!

**Comment by janober** [comment]
Very glad to hear! Wish you a great day!
