### ISSUE TITLE
HubSpot Credentials OAuth Redirect URL is wrong

### ISSUE THREAD

**Issue by carlin-q-scott** [n8n-io/n8n#2783]
**Describe the bug**
The OAuth Redirect URL given in the HubSpot OAuth2 Credentials dialog is not the one it used.

**To Reproduce**
1. Credentials
2. New
3. Hubspot OAuth2 API
4. Copy OAuth Redirect URL
   > https://tasty-snail-91.hooks.n8n.cloud/rest/oauth2-credential/callback
5. Paste URL into callback configuration for my app in HubSpot and click save
6. Enter my Client ID and Secret key from HubSpot
7. Click "Connect my account"
8. Accept app installation in new HubSpot window
9. Get rejected because configured callback url doesn't match one used in the oauth request.

**Expected behavior**
My request is approved to install/connect the app.

**Environment (please complete the following information):**
 - OS: Windows 10 build 19043.1466
 - n8n Version 1.2.0.0 (Windows App)

**Additional context**
Actual callback url used by n8n:
> https://cold-firefox-62.hooks.n8n.cloud/rest/oauth2-credential/callback

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

Sometimes the generated tunnel URL  for the desktop app changes, are you sure it is still the value you have added to the app and not the value it is trying to use?

**Comment by carlin-q-scott** [comment]
Yes, I regenerated it a couple times, and it kept giving me the wrong url in the Desktop UI.

**Comment by Joffcom** [comment]
It can sometimes make a new URL when you restart the application but I have not yet seen it generate the wrong URL, If you go to the credentials page in n8n or add a webhook node do you still see the wrong URL and does that URL provided work if you try to reach it?

**Comment by carlin-q-scott** [comment]
Creating a new node didn't fix it. Restarting the app generated a new URL, but I didn't verify that it was correct. And now I'm using the self-hosted version, which may not have this issue?

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

I would be surprised if it had the issue as with the self hosted version you would normally set your own domain to point to the instance.

**Comment by Joffcom** [comment]
That is handy, it should just be a case of setting the environment options and you will be sorted.

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

I am going to mark this one as closed for now, Any questions let me know 👍🏻
