### ISSUE TITLE
Expression Editor: markdown-ish auto-complete sometimes problematic

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#2798]
**Describe the bug**
When I want to edit e.g. JSON code, as part of a HTTP request node's body:

https://user-images.githubusercontent.com/2084639/153492131-7831dad0-10c6-49c4-a2d8-38e1a41c6ef7.mp4

**To Reproduce**
- press space while on an empty line
  => a `  1.` is inserted
- press tab on an empty line
  => the tab is inserted but the cursor moves back to start

**Expected behavior**
No interference (or togglable when wanted for markdown-like content)

**Environment (please complete the following information):**
 - OS: Firefox Developer 98.0b2 (64-bit)
 - n8n Version  0.161.1

**Comment by janober** [comment]
Thanks a lot for making us aware of that @tennox. Got fixed and will be released with the next version.
