### ISSUE TITLE
[Function node] Monaco doesn't resize with modal

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#2800]
**Describe the bug**
When I resize my browser window while having a Function node editor open:
![n8n js resize](https://user-images.githubusercontent.com/2084639/153520339-75ca71cc-3319-4f2f-8155-1f70ee787365.gif)

**Environment (please complete the following information):**
 - n8n Version  0.161.1 
 - Browser: Firefox Developer 98

**Comment by Jsnxyz** [comment]
In **CodeEdit.vue**,

`monaco.editor.create()` needs `automaticLayout: true` option added, as suggested [here](https://stackoverflow.com/questions/47017753/monaco-editor-dynamically-resizable).

**Comment by janober** [comment]
Thanks a lot @tennox for the report and esp. @Jsnxyz for providing directly the fix. Got fixed as suggested and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.163.0`
