### ISSUE TITLE
CLI command `n8n import:credentials --separate` does not work

### ISSUE THREAD

**Issue by JaZo** [n8n-io/n8n#2804]
**Describe the bug**
The CLI command `n8n import:credentials --separate --input=backups/latest/` does not import the credentials and responds with "Successfully imported 0 credentials.". Exporting and importing to one big JSON file works fine.

**To Reproduce**
1. Make sure you have some credentials;
2. Run `n8n export:credentials --backup --output=backups/latest/`;
3. See it exported x credentials;
3. Run `n8n import:credentials --separate --input=backups/latest/`;
4. See it imported 0 credentials.

**Expected behavior**
I'd expect it to import all credentials found in the specified directory.

**Environment (please complete the following information):**
- OS: Windows 10 Business (21H1)
- n8n Version: 0.162.0
- Node.js Version: 14.17.3
- Database system: default
- Operation mode: default

**Additional context**
N/A

**Comment by janober** [comment]
I do not think we changed anything in there for quite a while. So can not imagine that it is a bug in n8n and think it has rather a different reason.
Can you please post in our forum (https://community.n8n.io/) instead. There you will get help the fastest. Thanks!

**Comment by JaZo** [comment]
I've found the cause and created a PR: #2805

**Comment by janober** [comment]
Great, thanks a lot. Interesting, I thought we fixed an issue with windows before. Looks like there were multiple ones. Thanks a lot for fixing it!

So I assume if it is an issue in credentials it will be the same for workflows.

**Comment by Joffcom** [comment]
Hey @JaZo,

I have just been going through some of our older PRs and Issues and it looks like we may have fixed this one around 6 months ago.

For now I am going to close this issue and the PR, If you are are still seeing an issue let me know and we can open it again.

Thanks for taking the time to report the issue and submitting a fix.
