### ISSUE TITLE
AWS SNS Authentication Bug

### ISSUE THREAD

**Issue by ixidion** [n8n-io/n8n#2838]
**Describe the bug**
The SNS Node causes an authentication error when the Message-Text contains linebreaks.

**To Reproduce**
1. Setup the node
2. Enter a message with multiple lines (hit Enter)
3. Try to run the node
4. See error below

`ERROR: Forbidden - perhaps check your credentials?
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

{"message":"403 - \"<ErrorResponse xmlns=\\\"http://sns.amazonaws.com/doc/2010-03-31/\\\">\\n  <Error>\\n    <Type>Sender</Type>\\n    <Code>SignatureDoesNotMatch</Code>\\n    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\\n  </Error>\\n  <RequestId>removed</RequestId>\\n</ErrorResponse>\\n\"","name":"Error","stack":"Error: Request failed with status code 403\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
`

**Expected behavior**
Message is sent as expected or an error is thrown at message entry.

**Environment (please complete the following information):**
 - OS: Debian
 - n8n Version 0.163.1
 - Node.js Version default from Docker Image
 - Database system default sqlite
 - Operation mode own

**Additional context**

**Comment by Joffcom** [comment]
Hey @ixidion,

Are you still having this issue? I have just given it a go on `0.211.1` and it appears to be working.

**Comment by ixidion** [comment]
Doesn't produce bug for me anymore. Close.
