### ISSUE TITLE
Unable to build project due to type error

### ISSUE THREAD

**Issue by tom555my** [n8n-io/n8n#2840]
**Describe the bug**
After pulling `master` branch and running `npm run bootstrap`, the following error is shown when i was running `npm run build`.
![image](https://user-images.githubusercontent.com/19559068/154618268-c34ef666-5eab-4463-b11b-10c6f26b6d6f.png)

**To Reproduce**
1. git checkout master
2. npm run bootstrap
3. npm run build

**Expected behavior**
Project is built successfully.

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - n8n Version [e.g. 0.119.0]
 - Node.js Version: 14.17.0
 - Database system: MySQL
 - Operation mode: queue

**Comment by ivov** [comment]
Please try:

```
git checkout master
git reset --hard; git clean -dffx
lerna bootstrap --hoist; npm run build
```

**Comment by janober** [comment]
Yes also think what @ivov wrote should work. I checked n8n out in parallel and build it. For me, it worked totally fine. Also the automatic build at night worked without any issues. So think that the code in master is fine.

**Comment by ivov** [comment]
@tom555my Are you still facing this issue?

**Comment by ivov** [comment]
If the issue persists, please comment and we will reopen.

**Comment by tom555my** [comment]
Thanks @ivov! It is helpful!
