### ISSUE TITLE
Microsoft Outlook node - shows error on Message Move operation

### ISSUE THREAD

**Issue by alexdogaru** [n8n-io/n8n#2876]
A Microsoft Outlook node shows an error after performing a Message Move operation, though the move operation itself gets well done and the email message moves to the correct destination folder in my Outlook 365 mailbox.

**To Reproduce**
1. Create a Microsoft Outlook node
2. Resource: Message
3. Operation: Move
4. Fill in a correct MessageID and FolderID
5. Execute the node

**Expected behavior**
The specified email should be moved to the new destination folder. No errors should be displayed.

**Environment (please complete the following information):**
 - OS: Win 11
 - n8n Version [0.160.0]
 - Node.js Version [...]
 - Database system [-]
 - Operation mode [own]

**Error response from Outlook**
{
"message": "400 - {"error":{"code":"RequestBodyRead","message":"One or more parameters of the operation 'move' are missing from the request payload. The missing parameters are: DestinationId."}}",
"name": "Error",
"stack": "Error: Request failed with status code 400 at createError (C:\Users\adogaru\AppData\Local\Programs\n8n\resources\app\node_modules\axios\lib\core\createError.js:16:15) at settle (C:\Users\adogaru\AppData\Local\Programs\n8n\resources\app\node_modules\axios\lib\core\settle.js:17:12) at IncomingMessage.handleStreamEnd (C:\Users\adogaru\AppData\Local\Programs\n8n\resources\app\node_modules\axios\lib\adapters\http.js:269:11) at IncomingMessage.emit (node:events:406:35) at IncomingMessage.emit (node:domain:470:12) at endReadableNT (node:internal/streams/readable:1331:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}

**Comment by Joffcom** [comment]
Hey @alexdogaru,

I have just been going through some of our issues an I noticed I didn't actually reply to this one properly, Are you still seeing this issue with the latest version of n8n? I have just done a a test on `0.211.1` with a Message move and it appears to be working.

**Comment by Joffcom** [comment]
Hi @alexdogaru,

As I can't reproduce this I suspect it has been fixed at some point and we just missed the notification. For now I am going to mark this as closed and if you are still having an issue let me know and we can open it again.
