### ISSUE TITLE
Scroll not working when creating fields for Hubspot(creating contact) 

### ISSUE THREAD

**Issue by MarkoKurtovic** [n8n-io/n8n#2884]
**Describe the bug**
When you try to create contact with Hubspot node, when you add multiple fields scroll doesn't work(can't see button to add more fields).

**To Reproduce**
1. Go to Add Node
2. Search for Hubspot
3. Open node, Additional Fields (left bellow)
4. Try to add multiple additional fields (more then 2)
5. See error

**Expected behavior**
Scroll should work when you add multiple fields

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.164.1]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by MarkoKurtovic** [comment]
I'm using 0.164.1 on raspberry pi

**Comment by Joffcom** [comment]
Hey @MarkoKurtovic,

I have just tested on 0.165.1 on my Raspberry Pi and it appears to be working as expected.

**Comment by MarkoKurtovic** [comment]
Hello,

I pulled latest version via docker.
version is updated to 0.166.0 

Still same error, can't scroll.

I also checked in inkognito mode.

**Comment by janober** [comment]
To be able to help you can you please tell us what browser you are using and post a screenshot as @Joffcom requested above. Thanks!

**Comment by MarkoKurtovic** [comment]
Sorry for that.

Here is the screenshot:
![Screenshot from 2022-03-12 13-01-40](https://user-images.githubusercontent.com/61917143/158017240-390a894f-d660-4280-af00-87870964013d.png)

I'm using firefox.

I tested on Chrome and it is working.

Maybe because it is older version of firefox. 
Version 83.0

**Comment by Joffcom** [comment]
Hey @MarkoKurtovic,

That could be it, I am currently using v98 of Firefox. I can try and grab an installer for 83 to give it ago if you are not able to upgrade.

Out of interest what is the size of the browser window? If I make the window smaller I can get the same size but if I scroll in that part of the dialog it will move, Can you try scrolling and see if that does anything?

**Comment by Susangriffis** [comment]
I’m using coinbase app rn also with Firefox and safari 


Sent from Yahoo Mail for iPhone


On Saturday, March 12, 2022, 03:59, Jan Oberhauser ***@***.***> wrote:




To be able to help you can you please tell us what browser you are using and post a screenshot as @Joffcom requested above. Thanks!

**Comment by Joffcom** [comment]
Hey @MarkoKurtovic,

I have not heard anything else on this one and it looks like it wasn't easy to reproduce so I am assuming something local, For now I am going to mark this one as closed and if it happens again let me know and we can re-open it.
