### ISSUE TITLE
فیس‌بوک

### ISSUE THREAD

**Issue by doroodgar** [n8n-io/n8n#2888]
"فیس‌بوک" https://m.facebook.com/oauth/error/?error_code=PLATFORM__LOGIN_DISABLED_FROM_WEBVIEW&display=touch

**Comment by janober** [comment]
Please make sure to fill out the template if you want to report a bug.
If you have problems and want help please post to the forum:
https://community.n8n.io/

Both have to be done in English. Thanks!
