### ISSUE TITLE
Facebook API v13 support

### ISSUE THREAD

**Issue by lpadula** [n8n-io/n8n#2889]
**Describe the bug**
n8n is using a deprecated version of the Ads API.

**To Reproduce**
1. Add a Facebook Graph API node.
2. Configure parameters.
3. Execute node.

**Expected behavior**
Return json.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version 0.161
 - Node.js Version 14.16.0
 - Database system Postgres
 - Operation mode own

**Additional context**
![image](https://user-images.githubusercontent.com/1341504/155629697-56b0f070-83f8-4672-80ab-bc6cc590199a.png)

**Comment by Joffcom** [comment]
Hey @lpadula,

Thanks for reporting this one, Out of interest what version of the API are you using? N8N supports v12.0 which Facebook have listed as supported until August 9th 2022 which I would have expected to work.

In theory it looks like changing it to v13 won't take a lot of work so I will get an internal ticket created for it.

**Comment by lpadula** [comment]
Im using v13, because new apps only works with that version :(

**Comment by Joffcom** [comment]
Hey @lpadula,

That is annoying, So do you hit that error if you set the node to use v12? I don't have a Facebook Ads account but if you are able to do some testing I can get a potential fix together, In theory it is just a case of adding v13 to the list.

**Comment by lpadula** [comment]
Yes, let me know how i can help!

**Comment by janober** [comment]
Support for v13 got added with `n8n@0.167.0`

**Comment by gadgrandez** [comment]
Hello. Is it possible to add support for v14 as well? Some APIs return are deprecated in v13
![Screenshot_8](https://user-images.githubusercontent.com/16307528/176978137-448775e4-1f86-4e72-a5de-7566dfc43ec9.png)
 Thanks
