### ISSUE TITLE
[ExecuteCommand node] Dupplicate parameter "Execute Once"

### ISSUE THREAD

**Issue by naskio** [n8n-io/n8n#2895]
**Describe the bug**
The param "Execute Once" exists twice, once in the "Parameters" tab and again in the "Settings" tab as shown in the bellow.

- Parameters tab
![Screen Shot 2022-02-27 at 12 11 27](https://user-images.githubusercontent.com/18899702/155937140-e16c6557-7df4-42c0-a99a-24b59707dd08.png)

- Settings tab
![Screen Shot 2022-02-27 at 12 11 32](https://user-images.githubusercontent.com/18899702/155937142-cdc9d4a5-2912-41a4-9337-f3451db0d882.png)

I am ready to fix it, if you think that it is a bug.

**Comment by janober** [comment]
Yes, thanks. That is sadly a known "issue". It got added to the Execute Command node (Parameters Tab) a long time before generally to n8n (Settings Tab). For now, is removing not possible without breaking the workflows of people. We are hower, working through all n8n core nodes, and as part of that process will that parameter be removed with the next version of the node.

**Comment by naskio** [comment]
It may be possible to remove it without breaking any workflows by adding a script for migrating workflows automatically after the update (moving all existing values from Parameters to Settings).
Just an idea but ofc It is not a critical problem.

**Comment by janober** [comment]
Ah yes, agree to 100%. It would theoretically be possible. But the work it would involve, and possible risks currently outweigh the advantage it brings. After all, is mainly a cosmetic thing, something that is inconsistent but does not cause any harm. As we are a small team do we have to be very cautious about what we spend our time on. I hope that makes sense.
