### ISSUE TITLE
Create MailJet integration

### ISSUE THREAD

**Issue by janober** [n8n-io/n8n#29]
Create an integration for MailJet similar to the Mailgun one.
https://dev.mailjet.com/guides/

Mailgun-Node is a good reference and starting point:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Mailgun/Mailgun.node.ts

Discussion in forum:
https://community.n8n.io/t/mailjet-integration/64

**Comment by janober** [comment]
https://community.n8n.io/t/mailjet-integration/64

**Comment by julianadenauer** [comment]
hey, what happened to this integration? will it be in the next release?

**Comment by janober** [comment]
Sorry but nothing exists that could be included with the next version. This was only an issue. So it was about that somebody should create it. That, however, never happened. It got closed because all requests for new nodes get collected in the forum. For that reason did I post the link and then closed it.

So you can follow the link and upvote there. No matter what we can have a look to implement the node that it is in the next version or the one after that.
