### ISSUE TITLE
FTP Node: HTTP Error 500

### ISSUE THREAD

**Issue by btxluke** [n8n-io/n8n#2906]
**Describe the bug**
FTP Node returns error http: 500 post connection

**To Reproduce**
Connect to FTP server using FTP node, run any command.

**Expected behavior**
Expected command to run.

**Environment (please complete the following information):**
 - OS: Ubunto 20.04
 - n8n Version [e.g. 0.164.1] (Latest Docker Image)

**Additional context**
FileZilla Connection Log, with matching credentials:

`Status:	Resolving address of ftp.****.co.uk
Status:	Connecting to **.**.**.**:21...
Status:	Connection established, waiting for welcome message...
Response:	220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response:	220-You are user number 4 of 50 allowed.
Response:	220-Local time is now 08:00. Server port: 21.
Response:	220-This is a private system - No anonymous login
Response:	220 You will be disconnected after 15 minutes of inactivity.
Status:	Plain FTP is insecure. Please switch to FTP over TLS.
Command:	USER ***@***.co.uk
Response:	331 User ***@***.co.uk OK. Password required
Command:	PASS ************
Response:	230 OK. Current restricted directory is /
Command:	OPTS UTF8 ON
Response:	504 Unknown command
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is your current location
Status:	Directory listing of "/" successful`

**Comment by Joffcom** [comment]
Just a quick note... This is being looked into here: https://community.n8n.io/t/ftp-server-cant-connect-command-unknown/10187/26

**Comment by Joffcom** [comment]
Closing this one off, After talking to @btxluke it was discovered to be a firewall issue on the FTP server blocking passive ports.
