### ISSUE TITLE
Basic auth not works anymore

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#2916]
**Describe the bug**

Currently, after entering the basic auth data, you are asked again and again for the data. This means that you cannot get into n8n.

**To Reproduce**

install n8n with config:

```
{
	"protocol": "http",
	"host": "localhost",
	"listen_address": "0.0.0.0",
	"port": 5678,
	"executions": {
		"process": "main",
		"saveDataOnSuccess": "all",
		"saveDataOnError": "all",
		"saveDataManualExecutions": true,
		"pruneData": true,
		"pruneDataMaxAge": 336,
		"pruneDataTimeout": 3600
	},
	"generic": {
		"timezone": "Europe/Berlin"
	},
	"security": {
		"basicAuth": {
			"active": true,
			"user": "admin",
			"password": "admin"
		}
	},
	"database": {
		"type": "postgresdb",
		"postgresdb": {
			"database": "n8n",
			"host": "localhost",
			"port": 5432,
			"user": "n8n",
			"password": "somepassword",
			"schema": "n8n"
		}
	}
}
```

**Expected behavior**

That after successfully entering the data n8n lets you into the system.

**Environment (please complete the following information):**
 - OS: Windows Server 2016
 - n8n Version: 0.165.1
 - Node.js Version: v17.5.0
 - Database system: postgres
 - Operation mode: main

**Additional context**

Unfortunately, I can not say from which version it originated because we were still working on an old version.
(The previous version still had rounder icons).
As a side info: We use n8n behind iis reverse proxy.

**Comment by Joffcom** [comment]
Hi @lublak,

If you try loading the page directly bypassing IIS does it have the same issue? I have just checked on my instance here using Basic Auth and I am not able to reproduce the issue. I am not using the config file option for my instance so it could be related to that but it may be worth going around IIS and maybe making sure the credentials are correct.

**Comment by lublak** [comment]
@Joffcom this works fine.
http://localhost:5678/ directly one the server just ask once for the password.
But we have not changed anything on iis have only updated n8n.

**Comment by Joffcom** [comment]
Hey @lublak,

To me that would suggest that basic auth is working as expected and it is possibly something on the proxy side causing the issue. It may be worth looking into what the proxy is doing, In my test here I used nginx which while not the same thing does show that proxies are generally working.

I have checked the breaking changes and can't see anything mentioned there either. Let me know how you get on with checking IIS and if I get a chance I will set up a Windows VM with IIS and ARR to test.

**Comment by lublak** [comment]
Okay I think the bug can be closed here since n8n is not the only application that stopped working. Therefore it must be a change (not by me) to the IIS causing this error.
I will close the error here but if I find out what the problem is I will post the solution here too in case someone else gets the same problem.

**Comment by lublak** [comment]
After disabling windows authentication. It works fine. (I don't know why it's suddenly a problem now.)

**Comment by Joffcom** [comment]
Hey @lublak,

Windows Auth can be a pain as it will provide another basic auth prompt, I suspect the IIS logs or DC event viewer logs would have displayed a lot of failed login attempts.

**Comment by lublak** [comment]
@Joffcom That may well be.
In general, I am not a fan of the iis server, unfortunately I am obliged to use it.
Especially on sites like stackoverflow there are enough solutions to nginx or apache. IIS is rather hard to find any solutions. Windows auth is fortunately no longer needed in our company, so I could turn it off completely. Why the problem occurs only now I do not know.

**Comment by Joffcom** [comment]
@lublak it wouldn't surprise me if something changed in an IIS or browser update, I remember Firefox and Chrome always being a pain. On the plus side User Management is right around the corner so you could move to that in the coming weeks.
