### ISSUE TITLE
Migration Error after upgrade to 0.165.0

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#2924]
**Describe the bug**
Migration Error after upgrade to 0.165.0 from table execution_entity.

`
There was an error initializing DB: "Can't DROP 'IDX_c4d999a5e90784e8caccf5589d'; check that column/key exists"
`

**To Reproduce**
1. Upgrade N8N Docker Container

**Expected behavior**
All migrations running.

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version 0.165.0
 - Node.js Version [e.g. 14.16.0]
 - Database system MySQL
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

![image](https://user-images.githubusercontent.com/257004/156460551-dc5d4caf-91af-4271-ae44-0ba15c86f34b.png)

**Comment by Joffcom** [comment]
Hey @luizeof,

It looks like you have asked this one the [community support forum](https://community.n8n.io/t/database-error-after-upgrade-to-0-165-0/11846) as well where there is a reply waiting.

What I will do for now as this is being handled there is mark this issue as closed for now.

**Comment by danyflorez** [comment]
Were you able to resolve this issue?
