### ISSUE TITLE
[Announcement] A new license for n8n

### ISSUE THREAD

**Issue by janober** [n8n-io/n8n#2932]
We have decided to change from our current license - Apache 2.0 with Commons Clause - to a new, custom license. The main motivations for making this change are:

1. to make it clearer to people what use is restricted
2. to be more permissive: the Commons Clause restricts people’s from charging fees for consulting and support: services we want to freely allow and encourage

We will be announcing the change later this month, but wanted to give you some advance notice. We have been consulting with a few community members, as well as software licensing lawyers on making this change, but are open to more input! So if you want to provide feedback, please send a PM to [@claudianotclaud](https://community.n8n.io/u/claudianotclaud) on our forum. Thanks!

**Comment by janober** [comment]
General discussion around it happening in the forum here:
https://community.n8n.io/t/a-new-license-for-n8n/11873/6

**Comment by janober** [comment]
We now officially changed our license to the new Sustainable Use License.
More information about it can be found in the following blog post:
https://n8n.io/blog/announcing-new-sustainable-use-license/

**Comment by iosifnicolae2** [comment]
I've put a lot of effort into implementing n8n and now suddenly it's not anymore free of charge for commercial use.

I kind of understand that n8n needs money to sustain the growth and make some profit for investors but I suggest to state very clearly on the README page that this product is not anymore free of charge for commercial use.

Thank you!

**Comment by janober** [comment]
Nothing is now forbidden which was not already forbidden before. On the contrary, now is actually more allowed than before, as Consulting & Support is not limited to $30k anymore.

You can find more information allowed and none allowed use cases here:
https://docs.n8n.io/reference/faq.html#license

And to make it perfectly clear. Commercial use is (and always was) allowed as long as it is internal. What never was allowed (and still is not) is to offer n8n externally and so make money with n8n (again more information about that in the linked FAQ above). Here also a link to the very very old docs (more or less the state they were when n8n launched) where that was also already mentioned:
https://docs-old.n8n.io/#/faq

Additionally did also exchange emails in April 2020 about the special license n8n used and your worries. I even offered to have set up a call to talk about it more, which you declined back then. So I am honestly a little bit confused.

**Comment by iosifnicolae2** [comment]
Sorry for my comment which was a bit too aggressive.
I'll contact you by email to establish further details.

Thank you very much!
