### ISSUE TITLE
Mongdb node find method executes only once per workflow 

### ISSUE THREAD

**Issue by ebunders** [n8n-io/n8n#2935]
For an array of items in the workflow, the mongodb node only runs a search 1 time.

**To Reproduce**
```{
  "name": "testWorkflow",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        120,
        660
      ]
    },
    {
      "parameters": {
        "collection": "aurora-items",
        "options": {},
        "query": "={\"ID\": \"{{$json[\"nr\"]}}\"}"
      },
      "name": "MongoDB",
      "type": "n8n-nodes-base.mongoDb",
      "typeVersion": 1,
      "position": [
        600,
        660
      ],
      "alwaysOutputData": true,
      "executeOnce": false,
      "retryOnFail": false,
      "credentials": {
        "mongoDb": {
          "id": "7",
          "name": "MongoDB account"
        }
      }
    },
    {
      "parameters": {
        "functionCode": "// Code here will run only once, no matter how many input items there are.\n// More info and help: https://docs.n8n.io/nodes/n8n-nodes-base.function\n\n// Loop over inputs and add a new field called 'myNewField' to the JSON of each one\n\n\nreturn [1,2,3].map(i=>({json: {nr: i}}));"
      },
      "name": "Function2",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        360,
        660
      ],
      "alwaysOutputData": true
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Function2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function2": {
      "main": [
        [
          {
            "node": "MongoDB",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "MongoDB": {
      "main": [
        []
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": 3
}
```
A simple workflow that creates three nodes. Mongodb node does a search for each node, but emits data regardless of success.

**Expected behavior**
I expect the search to be executed 3 times, but no, only once

**Environment (please complete the following information):**
 - OS: Ubuntu: 21.10
 - n8n Version: 0.165.1 
 - Node.js Version: i'm running the docker image, which has: v14.15.5
 - Database systemSQLite
 - Operation mode: main
 -

**Comment by Joffcom** [comment]
Hey @ebunders,

Thanks for reporting this one, We know there are a few nodes that don't currently support multiple input items which we list here: https://docs.n8n.io/getting-started/key-concepts/looping.html#node-exceptions

I will get an internal ticket raised to get this resolved in a future release. For now the workaround is to use the Split in Batches node which would take the outputs of the previous node and handle them one at a time.

**Comment by luizeof** [comment]
@ebunders as an alternative way that i am using for this scenario, just put a split in batches (1 batch size) before node mongo and connect the output of node mongo to the beginning of split in batch.

![image](https://user-images.githubusercontent.com/257004/156804366-6c306022-25ef-4ad0-bd48-891e94161ad4.png)

**Comment by ebunders** [comment]
Thanks guys. In the meantime I learned all about the relation between items and executions. It was not obvious to me bu now it is. Maybe the mongdb node should be mentioned on [this page](https://docs.n8n.io/getting-started/key-concepts/looping.html#creating-loops) (under 'node exceptions')?

**Comment by Joffcom** [comment]
Hey @ebunders,

You are not wrong there, I put in a request to the documentation team to get that added.

I do have some PRs to review next week for the MongoDB node so I may sneak in multiple item support at the same time.

**Comment by Joffcom** [comment]
Hey @ebunders,

I forgot to mention MongoDB is now listed on that page, For now I am going to close this issue as this is a documented limitation.

We will likely change the node in the future to support this.
