### ISSUE TITLE
Split In Batches node currentRunIndex does not reset for each iteration of the parent loop thus exceeding maxRunIndex in the second iteration

### ISSUE THREAD

**Issue by den5o** [n8n-io/n8n#2943]
**Describe the bug**
The Split In Batches node does not reset currentRunIndex for every iteration of a nested loop while keeping the maxRunIndex at the value of the first iteration.

For example let’s say the parent loop sends the following number of items in each iteration:

    3 items
    1 item
    2 items

Then at the end of each iteration of the nested loop currentRunIndex will be:

    3
    4
    6

Since maxRunIndex of the first iteration was 3, all subsequent iterations have a value higher than that and return false when the condiition is set to: currentRunIndex < maxRunIndex

**To Reproduce**
You can use this workflow to see the issue in action. Excuse the newbie and messy way at the start of the workflow I didn't know how to create the necessary data in a function.

`{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        -700,
        700
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "number": [
            {
              "name": "key1",
              "value": 5687
            }
          ]
        },
        "options": {}
      },
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -460,
        580
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "number": [
            {
              "name": "key2",
              "value": 3565678
            },
            {
              "name": "key1",
              "value": 645756
            }
          ]
        },
        "options": {}
      },
      "name": "Set1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -460,
        720
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "number": [
            {
              "name": "key3",
              "value": 1234
            },
            {
              "name": "key2",
              "value": 5678678
            },
            {
              "name": "key1",
              "value": 7835
            }
          ]
        },
        "options": {}
      },
      "name": "Set2",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -460,
        860
      ]
    },
    {
      "parameters": {},
      "name": "Merge",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        -220,
        660
      ]
    },
    {
      "parameters": {},
      "name": "Merge1",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        -40,
        840
      ]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "name": "ParentLoop",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        1120,
        720
      ],
      "alwaysOutputData": false
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "name": "ChildLoop",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        1600,
        720
      ],
      "alwaysOutputData": true
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{$node[\"ParentLoop\"].context[\"currentRunIndex\"]}}",
              "value2": "={{$node[\"ParentLoop\"].context[\"maxRunIndex\"]}}"
            }
          ]
        }
      },
      "name": "ParentLoopEnd",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        2280,
        840
      ]
    },
    {
      "parameters": {
        "fieldToSplitOut": "key1",
        "include": "allOtherFields",
        "options": {}
      },
      "name": "Item Lists",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 1,
      "position": [
        1360,
        720
      ]
    },
    {
      "parameters": {
        "operation": "aggregateItems",
        "fieldsToAggregate": {
          "fieldToAggregate": [
            {
              "fieldToAggregate": "key1"
            }
          ]
        },
        "options": {}
      },
      "name": "Item Lists1",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 1,
      "position": [
        220,
        400
      ]
    },
    {
      "parameters": {
        "operation": "aggregateItems",
        "fieldsToAggregate": {
          "fieldToAggregate": [
            {
              "fieldToAggregate": "key1"
            }
          ]
        },
        "options": {}
      },
      "name": "Item Lists2",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 1,
      "position": [
        220,
        600
      ]
    },
    {
      "parameters": {
        "operation": "aggregateItems",
        "fieldsToAggregate": {
          "fieldToAggregate": [
            {
              "fieldToAggregate": "key1"
            }
          ]
        },
        "options": {}
      },
      "name": "Item Lists3",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 1,
      "position": [
        220,
        820
      ]
    },
    {
      "parameters": {},
      "name": "Merge2",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        600,
        520
      ]
    },
    {
      "parameters": {},
      "name": "Merge3",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        800,
        740
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{$node[\"ChildLoop\"].context[\"currentRunIndex\"]}}",
              "value2": "={{$node[\"ChildLoop\"].context[\"maxRunIndex\"]}}"
            }
          ]
        }
      },
      "name": "ChildLoopEnd - cur>max",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1860,
        800
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{$node[\"ChildLoop\"].context[\"currentRunIndex\"]}}",
              "value2": "={{$node[\"ChildLoop\"].context[\"maxRunIndex\"]}}"
            }
          ]
        }
      },
      "name": "ChildLoopEnd - cur<max",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1860,
        600
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          },
          {
            "node": "Set1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Set2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 0
          },
          {
            "node": "Item Lists1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set1": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Set2": {
      "main": [
        [
          {
            "node": "Merge1",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Merge": {
      "main": [
        [
          {
            "node": "Merge1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Item Lists2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Merge1": {
      "main": [
        [
          {
            "node": "Item Lists3",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ParentLoop": {
      "main": [
        [
          {
            "node": "Item Lists",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ChildLoop": {
      "main": [
        [
          {
            "node": "ChildLoopEnd - cur<max",
            "type": "main",
            "index": 0
          },
          {
            "node": "ChildLoopEnd - cur>max",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ParentLoopEnd": {
      "main": [
        [
          {
            "node": "ParentLoop",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Item Lists": {
      "main": [
        [
          {
            "node": "ChildLoop",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Item Lists1": {
      "main": [
        [
          {
            "node": "Merge2",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Item Lists2": {
      "main": [
        [
          {
            "node": "Merge3",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Item Lists3": {
      "main": [
        [
          {
            "node": "Merge2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Merge2": {
      "main": [
        [
          {
            "node": "Merge3",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Merge3": {
      "main": [
        [
          {
            "node": "ParentLoop",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ChildLoopEnd - cur>max": {
      "main": [
        [
          {
            "node": "ParentLoopEnd",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "ParentLoopEnd",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ChildLoopEnd - cur<max": {
      "main": [
        [
          {
            "node": "ParentLoopEnd",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "ParentLoopEnd",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Expected behavior**
currentRunIndex should reset every time a new iteration of the parent loop comes through.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version:  0.165.1 
 - Node.js Version: Unknown - I use the official docker image
 - Database system SQLite
 - Operation mode own

**Comment by Joffcom** [comment]
Hey @den5o,

Is this still causing an issue for you? I have read through this a few times now and to be honest I am not sure I fully understand what the issue is.

Looking at the workflow the child loop is not being iterated in a loop so it would only run once which could be part of what you are seeing.

**Comment by den5o** [comment]
Hey @Joffcom,

I don't recall exactly what I wanted to accomplish with this.  I've since abandoned that project altogether.  It looks like I made more than a few mistakes in it and the whole thing was probably a waste of time.

**Comment by Joffcom** [comment]
Hey @den5o,

No problem at all, For now I will mark this as closed and if you decide to give it another bash and run into the same problem let me know and I can open it again.

Out of interest are you still using n8n or have you moved on from us as well?

**Comment by den5o** [comment]
> Out of interest are you still using n8n or have you moved on from us as well?

I still self host n8n mostly for homelab automation and other personal stuff.
