### ISSUE TITLE
chore: website footer is clustered with both icons and usernames

### ISSUE THREAD

**Issue by yeganathan18** [n8n-io/n8n#2975]
**Describe the bug**
The website footer has been clustered with the social icons and usernames which makes the UI inconsistent.

**To Reproduce**
1. Go to [n8n.io](https://n8n.io)
2. Scroll down to footer of the site
3. See social icons and usernames of n8n

**Expected behavior**
I would suggest only the social icons rather than their usernames with it, if it's only icon then the UI would be much better and consistent.

Perhaps, pretty much everyone today knows the social handles

Also, we already have a banner which contains social handles for n8n updates, maybe we should also consider changing or updating it since the footer already has them.

**Screenshot**
<img width="1792" alt="Screenshot 2022-03-11 at 6 31 19 PM" src="https://user-images.githubusercontent.com/63534555/157872809-8b33ca48-a18c-46a5-babc-6277b6c81cee.png">

**Environment (please complete the following information):**
 - OS: macOS Monterey v12.2.1 
- Browser: Safari

**Comment by Joffcom** [comment]
Hey @yeganathan18,

Thanks for reporting this one 👍🏻, This is one that I don't see as an issue but I can see why some people may not like it. I know we are talking about making some changes to our site so this may be part of those changes. I will pass on the feedback to our marketing / design team though.

As this is not an issue with n8n itself I am going to mark this one as closed for now.
