### ISSUE TITLE
SMTP configuration is not seen by the application

### ISSUE THREAD

**Issue by AntonAndreevichMoroz** [n8n-io/n8n#2988]
**Describe the bug**
In the new version 0.168.0 I set up SMTP variables. But despite this, on the Settings->Users page, I see the error "Set up SMTP before adding users (so that n8n can send them invitation emails).", which means I cannot send an invitation to the user.

**Environment (please complete the following information):**
 - OS: Debian 10
 - n8n Version [e.g. 0.168.0]
 - Node.js Version v14.17.4
 - Database system SQLite
 - Operation mode main

**Additional context**
I also reboot the N8N, to check I add other variables that work as expected

**Comment by janober** [comment]
Can you please confirm what variables you are setting and which values (obviously obfuscate sensitive information). Because it seems to work fine for us and other users so wonder what is different in your case.

**Comment by luizeof** [comment]
@janober same here.

my ENVS:
![image](https://user-images.githubusercontent.com/257004/158301579-32d217f3-3e3d-415c-ae69-ddc850bfdc87.png)

**Comment by AntonAndreevichMoroz** [comment]
The question arises which port N8N uses for smtp. Our server is using 465 with TLS

![n8n](https://user-images.githubusercontent.com/51225180/158307219-ab2bd389-f011-4d9c-8b64-87e1e04fdfc6.jpg)

![n8n2](https://user-images.githubusercontent.com/51225180/158307172-a849ee74-0406-4616-8226-69fd9a9c9cf4.jpg)

**Comment by Joffcom** [comment]
Hey @luizeof & @AntonAndreevichMoroz,

The default port is `465` but you can change this using `N8N_SMTP_PORT` the problem is likely to be the `N8N_SMTP_EMAIL_MODE` variable, It looks like we have the wrong one documented and it should be `N8N_EMAIL_MODE` instead.

You can find the options and default values [here](https://github.com/n8n-io/n8n/blob/a03c368d2cfb1e2f886a10ea754e3c3d749ebb7c/packages/cli/config/index.ts#L603) if needed.

**Comment by Joffcom** [comment]
Hey @luizeof,

Perfect, The documentation changes have been published now as well which should help 👍🏻 

@AntonAndreevichMoroz if you get a chance can you try the same thing? It would be worth updating to 168.1 as well if you plan to invite others to your instance.

**Comment by Joffcom** [comment]
Hey @AntonAndreevichMoroz,

I am going to mark this one as closed, If you are still having issues let me know and we can open it again 👍🏻

**Comment by abennani82** [comment]
Hello,
I have a similar problem but setting all environment var doesn't fix any think. 
This is our context:
- We deploy n8n to our kube cluster using chart helm https://github.com/a5r0n/n8n-chart.git
- I add smtp vars as requested ( in n8n container):
/data # env | grep -i smtp
N8N_EMAIL_MODE=smtp
N8N_SMTP_SENDER=cdc@egerie.eu
N8N_SMTP_HOST=egerie-eu.mail.protection.outlook.com
N8N_SMTP_SSL=false
N8N_SMTP_PORT=25

- Our SMTP server don't need any authentication ( user and pass var not set)
![image](https://github.com/user-attachments/assets/c6e5f0f6-a7c5-4f5d-b71f-b9218e3690c8)
But we have warning for smtp not setup in users menu. 
Can u help us please?
