### ISSUE TITLE
Unable to start n8n due to `There was an error initializing DB: "Table 'role' already exists"`

### ISSUE THREAD

**Issue by tom555my** [n8n-io/n8n#2994]
**Describe the bug**
Unable to start n8n due to `There was an error initializing DB: "Table 'role' already exists"`

**To Reproduce**
1. npm run build
2. npm run start
3. See error

```sh
1|n8n-main  | Initializing n8n process
1|n8n-main  | query is slow: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'n8n' AND `TABLE_NAME` = 'migrations'
1|n8n-main  | execution time: 4126
1|n8n-main  | There was an error initializing DB: "Table 'role' already exists"
1|n8n-main  | Stopping n8n...
```

**Expected behavior**
n8n start correctly

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20
 - n8n Version 0.168.1
 - Node.js Version: 14.17.0
 - Database system: MySQL
 - Operation mode: queue

Thanks for your time!

**Comment by Joffcom** [comment]
Hey @tom555my,

Did you already have n8n running before using the latest version? I see you are using queue mode as well, Is this your main n8n instance or one of the workers?

**Comment by tom555my** [comment]
@Joffcom Yes, I have my automated process to start main instanc, 2 workers and 2 webhook workers.

**Comment by tom555my** [comment]
I was able to run normally after removing the `role` table. BTW I believe I upgraded from `0.166.0`.

**Comment by tom555my** [comment]
@krynble That's exactly what i did after removing the `role` table. I started the main process before other processes. I believe I can close the issue now. Thanks!
