### ISSUE TITLE
Cannot create an event due Google Calendar Node at v0.165.0

### ISSUE THREAD

**Issue by sergeygalay** [n8n-io/n8n#2995]
**Describe the bug**
I have two versions of n8n at 0.165.0 and 0.163.1
I cant create new event at v0.165.0, but at v0.163.1 all events created successfully with identical settings.

Error at Invalid time zone definition for start/end time.
And it doesn't matter if I choose the date in the internal data picker or use expression (example "2022-04-04T16:00:00+03:00")

Full error msg:
`{"message":"400 - {\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"invalid\",\"message\":\"Invalid time zone definition for start time.\"},{\"domain\":\"global\",\"reason\":\"invalid\",\"message\":\"Invalid time zone definition for end time.\"}],\"code\":400,\"message\":\"Invalid time zone definition for start time.\"}}","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}`

**Comment by Joffcom** [comment]
Hey @sergeygalay,

Have you checked on the [community forum](https://community.n8n.io)? I have just given this a go on 0.168.1 and it is working as expected. The error coming back looks like like the Google API is unhappy with the time zone being used, As this doesn't look like a bug it would be handy if you could open this on the forum and include information about your setup and provide a sample workflow.

For now I will mark this one as closed and if it does end up being a bug we can open it again.
