### ISSUE TITLE
npm start throw Error: Cannot find module '@oclif/command'

### ISSUE THREAD

**Issue by le-ross** [n8n-io/n8n#301]
**Describe the bug**
Executing the code from the repo with `npm start` is crashing on windows

**To Reproduce**
1. clone the repo
2. `npm start` from the repo
3. crash

```
LeChat@...... MINGW64 ~/Documents/git_repos/n8n (master)
$ npm run start

> n8n@ start C:\Users\LeChat\Documents\git_repos\n8n
> run-script-os


> n8n@ start:windows C:\Users\LeChat\Documents\git_repos\n8n
> cd packages/cli/bin && n8n

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@oclif/command'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\LeChat\Documents\git_repos\n8n\packages\cli\bin\n8n:45:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ start:windows: `cd packages/cli/bin && n8n`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n@ start:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LeChat\AppData\Roaming\npm-cache\_logs\2020-02-11T17_05_03_596Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ start: `run-script-os`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\LeChat\AppData\Roaming\npm-cache\_logs\2020-02-11T17_05_03_616Z-debug.log


```

**Expected behavior**
no error

**Environment (please complete the following information):**
* OS: win10
* n8n Version 0.52.0
* Node.js 10.15.1
* npm 6.13.7

**Additional context**
none

**Comment by janober** [comment]
Yes, there is some more work needed as just what you mentioned. You have to make sure that the needed tools are installed, everything is linked and that it got built.

The exact steps how to make it work, can be found here:
https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md

**Comment by janober** [comment]
Does it work now?

**Comment by janober** [comment]
I close this issue for now. If you still have problems please reopen it.

**Comment by volumetric** [comment]
Thanks for responding @janober I have executed all the steps as mentioned here: https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md

But I am getting the same above error. My environment is Ubuntu 18.04, nodev12.16.1

Here is the full log of the error:

`internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '@oclif/command'
Require stack:
- /media/v***t/ubuntu_old/home/v***t/.../exp/alternative/n8n/packages/cli/bin/n8n
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/media/v***t/ubuntu_old/home/v***t/.../exp/alternative/n8n/packages/cli/bin/n8n:32:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/v***t/ubuntu_old/home/v***t/.../exp/alternative/n8n/packages/cli/bin/n8n'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ start:default: `cd packages/cli/bin && ./n8n`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the n8n@ start:default script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/v***t/.npm/_logs/2020-12-27T13_27_50_411Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ start: `run-script-os`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the n8n@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/v***t/.npm/_logs/2020-12-27T13_27_50_427Z-debug.log`

**Comment by janober** [comment]
That does honestly not make sense. `@oclif/command` is a dependency of the "n8n" module:
https://github.com/n8n-io/n8n/blob/master/packages/cli/package.json#L82

So if you follow all steps (and it does not error) it has to get installed.

**Comment by frustrated-coder** [comment]
@janober 

```
FROM ubuntu
WORKDIR /workflow
COPY lerna.json /workflow
COPY package.json /workflow
RUN apt update && apt install -y nodejs
RUN apt install -y npm
RUN apt-get install -y curl
RUN  npm install n -g
RUN  n stable
RUN apt update && apt-get install -y build-essential python
RUN npm install -g lerna
RUN lerna bootstrap --concurrency=1
RUN lerna bootstrap --hoist
COPY . /workflow
CMD ["npm","start"]
```


Using this docker file to build the project with latest pull but continuously getting above error.

**Comment by EbiPenMan** [comment]
> @janober
> 
> ```
> FROM ubuntu
> WORKDIR /workflow
> COPY lerna.json /workflow
> COPY package.json /workflow
> RUN apt update && apt install -y nodejs
> RUN apt install -y npm
> RUN apt-get install -y curl
> RUN  npm install n -g
> RUN  n stable
> RUN apt update && apt-get install -y build-essential python
> RUN npm install -g lerna
> RUN lerna bootstrap --concurrency=1
> RUN lerna bootstrap --hoist
> COPY . /workflow
> CMD ["npm","start"]
> ```
> 
> Using this docker file to build the project with latest pull n8n version 105 but continuously getting above error. while the same was working with 93 version of n8n

Hello,
I had the same problem. After several attempts, I found the solution.
I think you should change the order of these two lines:

`RUN lerna bootstrap --hoist
COPY . /workflow`

It should be like this:

`COPY . /workflow
RUN lerna bootstrap --hoist`

I put my docker file for you:

`FROM node:14.15-alpine


# Update everything and install needed dependencies
RUN apk add --update graphicsmagick tzdata git tini su-exec

# # Set a custom user to not have n8n run as root
USER root

# Install n8n and the also temporary all the packages
# it needs to build it correctly.
RUN apk --update add --virtual build-dependencies python build-base ca-certificates && \
	npm_config_user=root npm install -g full-icu lerna && \
	apk del build-dependencies \
	&& rm -rf /root /tmp/* /var/cache/apk/* && mkdir /root;

# Install fonts
RUN apk --no-cache add --virtual fonts msttcorefonts-installer fontconfig && \
	update-ms-fonts && \
	fc-cache -f && \
	apk del fonts && \
	find  /usr/share/fonts/truetype/msttcorefonts/ -type l -exec unlink {} \; \
	&& rm -rf /root /tmp/* /var/cache/apk/* && mkdir /root

ENV NODE_ICU_DATA /usr/local/lib/node_modules/full-icu

WORKDIR /data
COPY *.json ./
COPY . .
RUN lerna bootstrap --hoist
RUN npm run build

RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"]
RUN ["chmod", "+x", "./packages/cli/bin/n8n"]

EXPOSE 5678/tcp
# CMD [ "./packages/cli/bin/n8n", "start" ]
CMD [ "npm" ,"run" ,"start" ]
`
