### ISSUE TITLE
Error Fetching Workflows using REST API

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#3013]
When enabling user management, I can no longer get the workflows through `/rest/workflows`.

In the documentation there is a BC, but I didn't find a solution or the documentation on how to authenticate `/rest/workflows` requests.

## To Reproduce

1. Enable User Management
2. Disable Basic Auth ENVS
3. Try to list workflows at `/rest/workflows`
4. Error 401

## Expected behavior

List my workflows from REST endpoints.

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version `0.168.1`
 - Node.js Version [e.g. 14.16.0]
 - Database system MySQL
 - Operation mode `queue`

## Additional context

![WhatsApp Image 2022-03-18 at 13 46 29](https://user-images.githubusercontent.com/257004/159063385-2a03e648-59ab-4174-8011-87555e5c1e76.jpeg)

**Comment by janober** [comment]
Yes, that is sadly known as the authentication works now totally different and got also called out specifically here:
https://docs.n8n.io/reference/user-management.html#user-management

Meaning it will also not get "fixed" as we do not see it as a bug. It will be possible again with the upcoming official API

If you require access to the internal API, then it is best to disable Use Management again.

For that reason do I close this issue. What you can try is to post in the forum. One of the engineers who worked on it, will then maybe be able to help you there to authenticate these requests.

**Comment by janober** [comment]
Just saw that there is already a post about that subject:
https://community.n8n.io/t/http-request-authorization-issue-after-n8n-update/12345
