### ISSUE TITLE
Google Drive Upload to Shared drive fails with Resolve Data

### ISSUE THREAD

**Issue by chadfaurie** [n8n-io/n8n#3024]
**Describe the bug**
Google Drive Upload to Shared drive fails with Resolve Data

**To Reproduce**
1. Create Google Drive Upload Node
2. Set Parent as Shared Drive Folder sub folder

**Expected behavior**
Resolve File Data of returned file

**Environment (please complete the following information):**
 - OS: Docker Official
 - n8n Version 0.166.0
 - Database system : MySQL
 - Operation mode own
 - 
**Additional context**

**Comment by Joffcom** [comment]
Hey @chadfaurie,

I have just given this a go here using 0168.2 and I am not able to reproduce the issue, Do you have an error message you can share or ideally can you update your container and see if the issue persists?

**Comment by Joffcom** [comment]
Hey @chadfaurie,

I didn't hear anything back on this one so for now I am going to mark this one as closed and if it is still an issue let me know and we can open this one again.
