### ISSUE TITLE
Wise funding transfer requests are falsely reported as errors

### ISSUE THREAD

**Issue by rontav** [n8n-io/n8n#3037]
**Describe the bug**
Wise SCA requests (#2734) introduced a new bug: executing a transfer always throws an error because the status code is 201 instead of 200.

**To Reproduce**
1. Create a Wise Quote
2. Create a Wise Transfer
3. Fund the transfer

**Expected behavior**
Even though the status code is not 200, the request is completed successfully.

**Environment:**
 - OS: Rocky Linux 8.4
 - n8n Version: 0.166.0
 - Node.js Version [e.g. 14.16.0]
 - Database system: SQLite
 - Operation mode: own

**Additional context**
Wise API docs: https://api-docs.transferwise.com/#errors-http-status-codes

**Comment by janober** [comment]
Thank you very much for reporting and directly fixing this issue. Your PR got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.170.0`
