### ISSUE TITLE
Issue upgrading from 0.165.0 to 0.169.0

### ISSUE THREAD

**Issue by maynardpa** [n8n-io/n8n#3042]
Hi, I have a local install via npm.

I have a scari log file with a long list of errors. I'm using a Silicon Mac (Apple M1 MacBookPro).

Any support/guidance appreciated
[2022-03-24T16_33_10_582Z-debug-0.log](https://github.com/n8n-io/n8n/files/8344647/2022-03-24T16_33_10_582Z-debug-0.log)
!

**Comment by janober** [comment]
Please always fill out the template we provide, rather than delete it. We did set it up for a reason.

The only thing I can say for now, is to try again with Node.js v16 and see if that works.

**Comment by maynardpa** [comment]
I have tried downgrading to node@16 and it doesn't work.
Saw a 403 HTTP error for sqlite.
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@16.14.2 | darwin | arm64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/opt/homebrew/lib/node_modules/n8n/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@5.0.2 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok

**Comment by Joffcom** [comment]
Hey @maynardpa,

Looking at the error it is failing to get the sqlite 5.0.2 package so attempts to build it but for some reason the Python command is not found.

```
4818 error /bin/sh: python: command not found
```

If you run python --version from a terminal do you get any issues? Are you also using MacOS 12.3?

If you are using 12.3 and the python command returns a not found message it could be worth trying

```
npm config set python python3
```

Then trying to see if an npm install then works.

**Comment by maynardpa** [comment]
Hi Jonathan, thanks for taking a look and taking the time to respond.

You are correct that I am on a mac, on 12.3.

I have ran the npm command you suggested in your comment and python –version shows the same message afterwards.

I think there might have been a delay with the sqlite build/package not being available for the Apple Silicon version.

I have just ran the npm install -g ***@***.*** and can now see that I am at 0.170.0.

Here is the terminal log/console output if you see anything critical here worth looking into. I have seen the 9 high severity vulnerabilities for a while but I am unsure if those will get fixed eventually.
I am sure our security team would appreciate that this count lowers over time.

Thanks again!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


***@***.*** ~ % npm install -g ***@***.***

npm WARN deprecated ***@***.***: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

npm WARN deprecated ***@***.***: this library is no longer supported

npm WARN deprecated ***@***.***: Please upgrade to latest, ***@***.*** or ***@***.***! Check these notes: https://bit.ly/2ZEqIau

npm WARN deprecated ***@***.***: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated ***@***.***: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated ***@***.***: request has been deprecated, see https://github.com/request/request/issues/3142

npm WARN deprecated ***@***.***: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

npm WARN deprecated ***@***.***: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.



added 14 packages, removed 16 packages, changed 947 packages, and audited 962 packages in 57s



84 packages are looking for funding

  run `npm fund` for details



9 high severity vulnerabilities



To address all issues (including breaking changes), run:

  npm audit fix --force



Run `npm audit` for details.

***@***.*** ~ % n8n start

Initializing n8n process

Migrations in progress, please do NOT stop the process.

query is slow: CREATE TABLE "shared_workflow" ("createdAt" datetime(3) NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), "updatedAt" datetime(3) NOT NULL DEFAULT (STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')), "roleId" integer NOT NULL, "userId" varchar NOT NULL, "workflowId" integer NOT NULL, CONSTRAINT "FK_3540da03964527aa24ae014b780" FOREIGN KEY ("roleId") REFERENCES "role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_82b2fd9ec4e3e24209af8160282" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b83f8d2530884b66a9c848c8b88" FOREIGN KEY ("workflowId") REFERENCES "workflow_entity" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("userId", "workflowId"))

execution time: 1577

n8n ready on 0.0.0.0, port 5678

Version: 0.170.0



Editor is now accessible via:

http://localhost:5678/



Press "o" to open in Browser.

Migrations finished.


From: Jonathan Bennetts ***@***.***>
Date: Tuesday, March 29, 2022 at 07:01
To: n8n-io/n8n ***@***.***>
Cc: Pier-André Maynard ***@***.***>, Mention ***@***.***>
Subject: Re: [n8n-io/n8n] Issue upgrading from 0.165.0 to 0.169.0 (Issue #3042)
EXTERNAL EMAIL : Do not click any links or open any attachments unless you trust the sender and know the content is safe.


Hey @maynardpa<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaynardpa&data=04%7C01%7Cpier-andre.maynard%40autodesk.com%7Ca22f982a3a684d53f6ac08da11737227%7C67bff79e7f914433a8e5c9252d2ddc1d%7C0%7C0%7C637841484783956386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LPWASnUeUmtBy8V1toqjlkxNup9tYNmr1hcf182wook%3D&reserved=0>,

Looking at the error it is failing to get the sqlite 5.0.2 package so attempts to build it but for some reason the Python command is not found.

4818 error /bin/sh: python: command not found

If you run python --version from a terminal do you get any issues? Are you also using MacOS 12.3?

If you are using 12.3 and the python command returns a not found message it could be worth trying

npm config set python python3

Then trying to see if an npm install then works.

**Comment by Joffcom** [comment]
That is good to hear, I did some digging this morning and there have been a few reports about the Node SQLite package not working on Apple Silicon with 12.3.

When you ran the python command I take it you did get a message about it not being found? The npm command would tell it that when it needs python it should instead use python3 which may be what happened, I have not yet updated to 12.3 I should probably get that done tonight.

I will mark this one as closed for now 👍🏻
