### ISSUE TITLE
Integration with ERPNext using Self-Signed/Locally-Signed SSL Certificate

### ISSUE THREAD

**Issue by mitchgreen** [n8n-io/n8n#3053]
**Describe the bug**
Apologies if this is more of a feature request rather than a bug. This issue applies to circumstances in which a user is attempting to configure the ERPNext node with an on-premise/self-hosted ERPNext server that leverages a self-signed or locally signed SSL Certificate. While attempting to integrate n8n with my on-premise/self-hosted ERPNext server, I have discovered that it does not seem possible to tell n8n to ignore the certificates validity, and my only solution is to allow and use non-https connection to my server.

**To Reproduce**
1. Add credentials associated with self-hosted ERPNext server that uses self-signed or locally-signed SSL Certificate
2. Create new Workflow
3. Add ERPNext node to workflow
4. See error next to DocType indicating "There was a problem loading the parameter options from server: "UNKNOWN ERROR - check the detailed error for more information"
5. If you check the docker container logs you will see errors that indicate "cause: Error: unable to verify the first certificate".

**Expected behavior**
It would be ideal if there was an option similar to that available in the Node for "The Hive" in order to Ignore SSL Issues.

**Environment (please complete the following information):**
 - n8n Version: n8n official docker container version 0.169.0

**Comment by Joffcom** [comment]
Hey @mitchgreen,

Normally we like to have all the feature requests on the community forum (https://community.n8n.io) this allows us to track votes to work out some kind of priority.

It looks like this should be a fairly quick fix though and I suspect it will work just like the option we have for "The Hive".

**Comment by Joffcom** [comment]
Hey @mitchgreen,

It looks like the ERPNext node has an option in the credential to ignore ssl issues this should solve the issue you were seeing. I am going to mark this one as closed and if you are still seeing this problem let me know and we can open this again.
