### ISSUE TITLE
Helper Message Box Behind Window

### ISSUE THREAD

**Issue by RevRebel** [n8n-io/n8n#3054]
**Describe the bug**
The helper information box is displayed behind the window. 

**To Reproduce**

Open the node setting window and, click on the "?" information icon. Occurring from all windows regardless of resolution size.

**Environment (please complete the following information):**
 - OS: macOS Monterey
 - n8n Version 0.165.1
 - Node.js Version v16.14.2

**Additional context**
See ScreenShot

<img width="429" alt="Screen Shot 2022-03-27 at 4 59 32 PM" src="https://user-images.githubusercontent.com/93675875/160307029-5e307b9a-c4a0-44e3-8234-fa12486bbdec.png">

**Comment by janober** [comment]
Thanks a lot for reporting this issue. But please update to a more up-to-date n8n version. The problem got already fixed in that.
