### ISSUE TITLE
[Mautic OAuth Credential] Slash at the end of URL isn't being handled

### ISSUE THREAD

**Issue by kimtiago** [n8n-io/n8n#3056]
**Describe the bug**
When create a OAuth credential of Mautic node and when type the URL of your Mautic with a slash at the end, you can't finish the integration because a error. Without the slash, the integration is OK.

**To Reproduce**
1. Go to the screen to create a Mautic Credential
2. Select OAuth
3. Type the information required and URL of your Mautic like "https://mautic.domain.com/" with a slash at the end
4. Receive the error like this {"errors":[{"message":"Requested URL not found: \/\/oauth\/v2\/authorize?client_id=xxxxxxxx\u0026redirect_uri=https%3A%2F%2Fn8n.domain.com%2Frest%2Foauth2-credential%2Fcallback\u0026response_type=code\u0026state=xxxxxxxxx\u0026scope=","code":404,"type":null}]}

**Expected behavior**
The creation of a Mautic OAuth Credential

**Environment (please complete the following information):**
 - OS: CentOS 7.9.2009
 - n8n Version 0.169.0
 - Node.js Version 17.8.0
 - Database system MariaDB 10.3.34
 - Operation mode [I don't know what is this]

**Comment by Joffcom** [comment]
Hey @kimtiago,

Thanks for reporting this one, I take it for now you are happy with not having the slash at the end?

**Comment by kimtiago** [comment]
When you copy the URL from a browser, the URL comes with the slash in the end, this can be frustrating for non advanced users.
To the user, i think have or dont have slash is irrelevant, i believe the system must handle this.

**Comment by Joffcom** [comment]
I agree we should be handling with and without the slash at the end. I was just trying to work out how urgent this is and if it could wait a couple of days for a fix.

**Comment by kimtiago** [comment]
owww sorry, isn't urgent, take your time

**Comment by Joffcom** [comment]
Hey @kimtiago,

Just popped in a PR that will resolve this one 👍🏻

**Comment by janober** [comment]
Fix got released with `n8n@0.171.0`
