### ISSUE TITLE
Maximum 4 workflows in browser opened, the 5th does not load

### ISSUE THREAD

**Issue by Passana** [n8n-io/n8n#3057]
I can have 4 workflows simultaneously open in browser tabs. But if I open the 5. one, it does not open it and it continues showing "Loading". 

Also, the other workflows get unresponsive. 

After closing another tab, it starts loading. 

Conclusion: I can edit max. 4 workflows at a time. 

Server performance should be not an issue, running self-hosted on 
8 CPU / 16 GB / 320 GB Disk - Ubuntu 20.04 (LTS) x64

Memor usage is 5%, CPU load 3%

Browser: Chrome
Version 99.0.4844.74 (Official Build) (x86_64)
macOs 12.2.1

**Comment by TheFSilverSP** [comment]
Hi @Passana 
You're definitely right. I noticed it a while ago and never said anything.

Thanks for bringing that up.
I'll add that my instances are self-hosted.

**Comment by TheFSilver** [comment]
Hi @Passana
You're definitely right. I noticed it a while ago and never said anything.

Thanks for bringing that up.
I'll add that my instances are self-hosted.

**Comment by Joffcom** [comment]
Hey @Passana & @TheFSilver,

I have just tried to reproduce this on my Mac with Chrome and I am up to 11 workflows with no issues or slowdown yet, Are you loading complex workflows and running them or just opening them?

How do you both have n8n installed as well is it npm, docker, something else and are there any reverse proxies involved?

**Comment by janober** [comment]
Just wanted to follow up here again as we did not hear back for 12 days.

**Comment by Passana** [comment]
Some workflows are complex, some very simple. Even if I open /workflow (empty one) it happens. 
This behaviour still persists. 

npm installation on ubuntu
Very powerful machine, see below

**Comment by Joffcom** [comment]
Do you have steps on what you are doing to reproduce it? I have opened a bunch of different workflows and ran them all once then opened another one to make a new workflow and it still works.

If we can find a way to reproduce the issue we should be able to fix it.

**Comment by TheFSilver** [comment]
Hi @Joffcom & @Passana 

As far as I'm concerned, I'm using a fork of this repo: https://github.com/sarveshpro/n8n-heroku 
It is running with the latest n8n version on heroku.

And I never managed to have more than 5 n8n tabs opened at the same time. the 6th doesn't load. (even on previous versions...)
I just tried it again.

**Comment by netroy** [comment]
I can reproduce this when running with Postgres as the database, but not with SQLite.

Interestingly this happens across browsers. 
I can open 5 tabs in one browser, and then login into another browser, and the single tab in the second browser never loads.

I suspect this has something to do with one of the middlewares, as the xhr requests for the last tab don't even make it to the handler for `/rest/workflows/new` or `/rest/workflows/{id}`. 

Unfortunately my current dev setup for this is too frustrating to debug this any further.
I'll try to improve my dev setup next week, and can then investigate further.

**Comment by Joffcom** [comment]
Hey @netroy,

What steps did you take to reproduce this? Did you just open the tabs then open a new one or did you perform some actions then open a new tab?

**Comment by netroy** [comment]
@Joffcom I created (and saved) a few empty workflows, and then tried to open a tab for each workflow.
I could not reproduce this unsaved workflows.

**Comment by Joffcom** [comment]
@netroy perfect, I will give that a bash on Postgres later this week.

**Comment by netroy** [comment]
I investigated this further, and looks like my previous suspicion was completely wrong.

This is an issue of `EventSource` connections starving other requests, when not running over HTTP/2.  
Once you open 6 concurrent `EventSource` connections, browser stops other SSE/XHR/Websocket requests from going through.  
This is supposed to be by-design [on Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=275955), as well as [on Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=906896).

If I comment out all calls to [`pushConnect()`](https://github.com/n8n-io/n8n/blob/n8n-workflow%400.104.0/packages/editor-ui/src/components/mixins/pushConnection.ts#L56), I can open as many tabs as I like, and they all load perfectly fine.

To solve this we'd need to stop opening multiple  `EventSource` connections, and either have the first tab open a connection and all other tabs get updates as `postMessage` events, or the single `EventSource` connection could be in a service-worker, and all tabs would then talk to that service-worker instead.

Switching over to Websockets could also be a solution.

**Comment by janober** [comment]
Thanks for investing! Uh if that is the problem then it would be actually something that is more complex to fix and so not sure if we would get to it any time soon. Esp. switching to web sockets would have some larger implications for all existing self hosted users.

**Comment by netroy** [comment]
Agreed.
However, a stop-gap solution could be to keep track of open tabs, and disconnect push for any background tabs, keeping push enabled only for the tab that was last in focus.
But even that makes sense only if this is a blocker for any users.

@Passana @TheFSilver How critical is this for you folks?

**Comment by netroy** [comment]
In `0.215.0` [we added support for WebSockets](https://github.com/n8n-io/n8n/pull/5443) as an alternative transport for push messages.

@Passana @TheFSilver If you folks are still facing this issue, We recommend trying to switch over to websockets by setting the env variable `N8N_PUSH_BACKEND` to `websocket`.
