### ISSUE TITLE
[cron] : mistake in Cron node documentation

### ISSUE THREAD

**Issue by branch3** [n8n-io/n8n#3060]
**Describe the bug**
The order of the asterixs are mismatched in the cron node documentation.
It says : second | minute | hour | day | **week | month**
But it is : second | minute | hour | day | **month | week**

**To Reproduce**
Go to the documentation : [https://docs.n8n.io/nodes/n8n-nodes-base.cron/#faqs](https://docs.n8n.io/nodes/n8n-nodes-base.cron/#faqs)
Where it explains the order of the asterixs, the WEEK and MONTH are mismatched

**Expected behavior**
In the tooltip helper on the node itself in n8n, the order is correct however. (Same as in Crontab Guru as suggested in the documentation)
Bonus points for specifying the "optional" status of the first asterix in the tooltip !

**Comment by StarfallProjects** [comment]
Thanks for the report 🙏
Fixed by: https://github.com/n8n-io/n8n-docs/pull/788
