### ISSUE TITLE
Weird behaviour "Problem running workflow Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by Passana** [n8n-io/n8n#3076]
I have a workflow with Postgres node, and others.

It worked fine when starting in the UI. 

But suddenly I get "Problem running workflow Cannot read property '0' of undefined"

I had no idea why, because the workflow worked fine. 

When I reload the browser with F5,  the workflow works one time, then after the first run,
I get ""Problem running workflow Cannot read property '0' of undefined"" again.

Reloaded again and it worked for one execution, then same error. 

I am clueless .. what could be the reason ? 

Happened on n8n cloud,  n8n@0.163.1

**Comment by Joffcom** [comment]
Hey @Passana,

Can you post this on the [community forum](https://community.n8n.io)? It doesn't look like a bug with n8n and is potentially just an issue with the data output / workflow.

When opening the post can you post an example workflow and some screenshots of the output data if possible as well?  For now I am going to close this one, Let me know if you have any questions.
