### ISSUE TITLE
After running npm run build, last changes are not appearing 

### ISSUE THREAD

**Issue by endritgojanikodelabs** [n8n-io/n8n#3088]
I'm creating node like in the [docs](https://docs.n8n.io/nodes/creating-nodes/create-node.html#adding-the-node-to-editor-ui). I have npm version 6.14.13 and node version v14.17.2, I'm following all the steps in the docs but after running npm build and npm run dev my node is not appearing. Also I do not have any errors or anything everything run like expected but just my node is not appearing. 

If anyone can help me with this.

**Comment by Joffcom** [comment]
Hey @endritgojanikodelabs,

This is possibly something that may be better being on the [community forum](https://community.n8n.io) as it doesn't sound like it is going to be a bug with n8n.

To get you started though did you remember to add your new node to the package file (`/packages/nodes-base/package.json`)? When I made my first node I spent about 30 minutes trying to work out why I couldn't see it and it was because I didn't add it to that file.

**Comment by endritgojanikodelabs** [comment]
Yes I'm doing that but again no results, after doing build the same code to many times its appearing again if I make any change I have to try to many times or restart my laptop until its showing the changes. This is a bit weird.

**Comment by Joffcom** [comment]
Hey @endritgojanikodelabs,

It does sound very odd, Is it the node that is missing or the changes that you are making? I have found with the latest code using Node 16 seems to work a bit better for me. When the issue happens do you notice any errors in the console output while it is building? It can scroll pretty quick but sometimes there are hints in there.

**Comment by endritgojanikodelabs** [comment]
@Joffcom I found what is happening so when I am stoping the current n8n process by pressing ctrl + c, the port of the UI 8080 and the port of the backend 5678 are still open so when I'm build the project again ports are open and they are not getting the last changes. So what I need to do is to write a bash scrip that every time kills my port and build the project again.

**Comment by Joffcom** [comment]
Hey @endritgojanikodelabs,

I sometimes have a similar issue when building and Node will crash on one part but run the other to get around it I have to the same thing and look for the process and kill it.

I have not seen a ctrl / cmd + c fail to stop it before though, Sounds like that is potentially something on the OS side not playing ball but it is worth keeping an eye on.

**Comment by Joffcom** [comment]
Hey @endritgojanikodelabs,

I have not heard anything else about this for a while so I am going to mark it as closed, If you are still having this issue let me know and we can open it again.
