### ISSUE TITLE
XML node does not convert to JSON properly

### ISSUE THREAD

**Issue by valentina98** [n8n-io/n8n#3090]
**Describe the bug**
The XML node does not put attributes inside a "$":{ } property when converting XML to JSON.

**To Reproduce**
1. Add a function node
2. Return the XML:
`<Foo xmlns="http://foo.com"/>`
4. Add a node which converts XML to JSON
5. Run the workflow and see attributes as properties but not inside a "$":{ }

**Expected behavior**
Expected output is:
```
{
	Foo: {
		$: {
			"xmlns": "http://foo.com"
		}   
	}
};
```
not
```
{
	"Foo": {
		"xmlns": "http://foo.com"
	}
}
```

**Environment**
 - OS: Ubuntu 20.04 LTS
 - n8n Version: 0.171.0
 - Node.js Version: v14.17.5
 - Database system: SQLite (default)
 - Operation mode: own (default)

**Additional context**
This way we're not able to convert to JSON and back to XML without change.

**Comment by Joffcom** [comment]
Hey @valentina98,

Have you tried adding the Merge Attributes option and disabling it? That will result in the below output.

``` json
[
  {
    "Foo": {
      "$": {
        "xmlns": "http://foo.com"
      }
    }
  }
]
```

**Comment by valentina98** [comment]
Hi @Joffcom , thank you! Setting mergeAttrs to false fixed it.

**Comment by valentina98** [comment]
Should it be the default behavior? I can open a pull request for it.

**Comment by Joffcom** [comment]
Hey @valentina98,

I don't think it needs to be the default behavior, I think you might be the first to ask about it so it would potentially be a breaking change for the existing users which we would rather avoid.

**Comment by valentina98** [comment]
Okay, thank you for the quick response. I'm closing the issue.
