### ISSUE TITLE
AWS Integration

### ISSUE THREAD

**Issue by mscansian** [n8n-io/n8n#31]
I think an integration with some AWS services would be a really good thing to have implemented. I will starting working in some of them, but it might take a while since I'm new with TS (though I have a lot of experience with AWS).

There would be multiple nodes (one for each AWS Service) but only a single credential provider, since all services require only and ACCESS_KEY and a SECRET and it can be used with multiple services.

## Services to integrate
The plus flag means that this item I consider less important or more difficult to implement.

### CloudWatch
* Trigger Alarm changes the state
* Send logs to CloudWatch Logs

### S3
* Upload a file to an S3 bucket
* Create a pre-signed link to an S3 Object
* Plus: Delete/Rename a file in a S3 bucket

### DyanmoDB
* Put an item
* Get item
* Plus: Query and Scan

### SNS
* Send message to topic

### SQS
* Send messages to queue
* Plus: Trigger Consume queue

### Lambda
* Start an execution

### SES
* Send email

**Comment by mscansian** [comment]
@janober Can I use a library to abstract the endpoints or is it better if I write code that send REST requests directly?

**Comment by janober** [comment]
Yes that would be great! Think that would allow to automate some cool things! Thanks!

Actually already created some docs about node creation which can be found here:
https://docs.n8n.io/#/create-node?id=node-development-guidelines
There is also a specific section about libraries. The short version is: "Please use REST with built in library if possible but it is OK to add new librariest if there is a very good reason to do so".

**Comment by prasad8mhatre** [comment]
> I think an integration with some AWS services would be a really good thing to have implemented. I will starting working in some of them, but it might take a while since I'm new with TS (though I have a lot of experience with AWS).
> 
> There would be multiple nodes (one for each AWS Service) but only a single credential provider, since all services require only and ACCESS_KEY and a SECRET and it can be used with multiple services.
> 
> ## Services to integrate
> The plus flag means that this item I consider less important or more difficult to implement.
> 
> ### CloudWatch
> * Trigger Alarm changes the state
> * Send logs to CloudWatch Logs
> 
> ### S3
> * Upload a file to an S3 bucket
> * Create a pre-signed link to an S3 Object
> * Plus: Delete/Rename a file in a S3 bucket
> 
> ### DyanmoDB
> * Put an item
> * Get item
> * Plus: Query and Scan
> 
> ### SNS
> * Send message to topic
> 
> ### SQS
> * Send messages to queue
> * Plus: Trigger Consume queue
> 
> ### Lambda
> * Start an execution
> 
> ### SES
> * Send email

If you want any help, I can help you with it. I am also new to node development. But we can do it together

**Comment by janober** [comment]
To have everything at one spot. Just got the following request in the forum:
https://community.n8n.io/t/aws-sns-integration/96
```
It would be very handy to be able to use AWS SNS as a trigger
```

**Comment by mscansian** [comment]
@janober I'm implementing the `publishing` of SNS messages, not the `subscription`. To use SNS as **trigger** you need to configure a webhook and configure SNS to send messages to that webhook. There's no custom integration needed, since there's no API to implement.

Relevant docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SNS.html#subscribe-property

PS: That's one reason I think full documentation per node is really important. AWS can be really complex and bite you.

@prasad8mhatre I'm just removing the aws-sdk depency that I introduced a few commits ago. After that @janober can review and merge. With the code merged you are free to implement other AWS services or extend the ones already available.

**Comment by Stvad** [comment]
@mscansian Thank you for working on this. Things from myself that I think would be great to have: 

* trigger by CloudWatch Event
* Calling AWS Polly for tts

**Comment by fcecagno** [comment]
Hi, one of the suggestion in the original post was to create pre-signed links to S3 objects, but as I can see it was never implemented. Since this issue is already closed, would it be OK to open a new issue as a feature request for this?
