### ISSUE TITLE
AWS S3 and S3 node excludes empty files in the `getAll` results

### ISSUE THREAD

**Issue by RichardFourie** [n8n-io/n8n#3118]
**Describe the bug**
Retrieving a list of files from S3 using the `getAll` operation in the AWS S3 and S3 nodes does not include files that have a size of 0. I suspect this is due to trying to filter out directories.
https://github.com/n8n-io/n8n/blob/94a52b93582578b3f2f3905c94d1c95b7c834fc8/packages/nodes-base/nodes/Aws/S3/AwsS3.node.ts#L518

**To Reproduce**
1. Create an AWS S3 or S3 node with resource set to `File` and operation to `Get All` and then point it to an S3 bucket containing empty files.
2. Execute the node and it should return a list of only non-empty files.

**Expected behavior**
The `Get All` operation for the `File` resource should return a list of all files regardless if they are empty or not or at least an option should be given for excluding empty files or not.

**Environment (please complete the following information):**
 - n8n Version: 0.171.0

**Comment by Joffcom** [comment]
Hey @RichardFourie,

That is a good spot, I am not sure this is a bug though as it looks like it was something that was intentionally added. I think a quick solution would be to maybe set up showing 0 byte files as a toggle option.

We don't tend to deal with Feature Requests here so I have created a feature request post on our community forum here: https://community.n8n.io/t/amazon-s3-show-0-byte-files/13141 so we can track votes and prioritize this one.

That being said if you wanted to pop in a pull request for it we can get it reviewed and merged in. For now though I am going to close this one off, If you have any questions let me know.
