### ISSUE TITLE
Unguarded Error Handling NPE Hiding Exception Cause

### ISSUE THREAD

**Issue by rhyswilliamsza** [n8n-io/n8n#3119]
**Describe the bug**
```
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/FunctionItem/FunctionItem.node.js:120:103)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:451:47
```

Offending line is `const lineParts = stackLines.find((line) => line.includes('FunctionItem')).split(':');`, unfortunately introduced as part of #2837 🌱  It looks like certain errors induce an undefined result from `stackLines.find((line) => line.includes('FunctionItem'))`, thus introducing a second NPE during error handling, hiding the original bug. 

**To Reproduce**
1. Implement a `FunctionItem` node [implementing an external library](https://docs.n8n.io/nodes/n8n-nodes-base.functionItem/#external-libraries)
2. Throw an error from the external library during execution.
3. See error.

**Expected behavior**
The `stackLines` block should be guarded to prevent unexpected actions on undefined results.

**Comment by Joffcom** [comment]
Hey @rhyswilliamsza,

That is a good question I am not sure why it was changed but I am sure the core team had a reason behind it. I will get a dev ticket opened internally to get this one resolved.

**Comment by Joffcom** [comment]
Hey @rhyswilliamsza,

Out of interest are you still seeing this on the latest release?

**Comment by Joffcom** [comment]
Closing for now, Will open again if this is still an issue.
