### ISSUE TITLE
Hardcoded Freshworks URL doesn't respect EU DC location

### ISSUE THREAD

**Issue by JanThiel** [n8n-io/n8n#3120]
Our Freshworks account is setup in the EU DC of Freshworks. 
The account is setup under a domain of `<company>.freshworks.com`. The current n8n node only supports  `<company>.myfreshworks.com`.

The node has to be able to support both locations / domains. Should be configurable as part of the credentials.

https://github.com/n8n-io/n8n/blob/50868c2a95638551aa48c21d4dd8bfbed56f3687/packages/nodes-base/nodes/FreshworksCrm/GenericFunctions.ts#L43

**Comment by Joffcom** [comment]
Hey @JanThiel,

As there is a PR open for this I am going to mark this as closed, I will aim to get that PR sorted out and merged this month.

**Comment by konstantinkoeppe** [comment]
Hello @Joffcom,

just wondering if there is any chance of this happening sometime soon, seeing that the PR has been open for quite a while now. At our company we make extensive use of the FreshWorks CRM running in their EU datacenter.

If you need any help testing things out I'd be happy to assist.

Kind regards
