### ISSUE TITLE
Connection lost (https://docs.n8n.io/#/server-setup)

### ISSUE THREAD

**Issue by sabatale** [n8n-io/n8n#315]
Hello,

I've deployed n8n on Ubuntu 18.04 by following this tutorial: [https://docs.n8n.io/#/server-setup](https://docs.n8n.io/#/server-setup). Everything works fine but I get the following error displayed at the top-right corner of the screen: "Connection lost". Whenever I try to run a workflow, the following error is triggered as well: "Problem running workflow. There was a problem running the workflow: No active connection to server. It is maybe down.".

I've only changed the .env file to get the domain working as well as setting a user/pwd. I've also removed the GENERIC_TIMEZONE option altogether.

Can you please help us clarify the issue?

Thanks!

**Comment by janober** [comment]
It sounds like something is blocking the EventSource connection. The setup works for sure and for everyone else. So I am not sure what is different in your case. Make sure there is nothing on your server  that blocks anything, that there is not any kind of proxy in-between and that also on your computer nothing gets blocked.

**Comment by sabatale** [comment]
OK. All I can say is that I get it working with the "standard" docker run command.

Definitely a problem with the configuration but probably not with the proxy. I'll let it be for now.

Thank you!

```
docker run -it --rm \
  --name n8n \
  -p 5678:5678 \
  n8nio/n8n
```
