### ISSUE TITLE
[Mautic Trigger] creates a new webhook every time when workflow is saved

### ISSUE THREAD

**Issue by kimtiago** [n8n-io/n8n#3158]
**Mautic Trigger creates a new webhook in Mautic identical to the original webhook, every time when the workflow is saved**

**To Reproduce**
1. Create a Workflow and add Mautic Trigger node
2. Create an OAuth2 API Credential on Mautic installation
3. On Mautic Trigger node, configure Authentication to OAuth2 and add a Credential for Mautic OAuth2 API from your Mautic installation
4. Add events (I don't know if this happens with specific events, but I'm using Contact identified Event and Contact Updated Event)
5. Save the workflow and n8n will create the webhook on Mautic, you can see it in your Mautic installation in Settings -> Webhooks
6. Add other nodes, do some changes and save again, n8n will create the same webhook again on Mautic

**Expected behavior**
Create the webhook only if it doesn't exist

**Environment:**
OS: CentOS 7.9.2009
n8n Version 0.172.0
Node.js Version 17.8.0
Database system MariaDB 10.3.34
Mautic Version 4.2.1
Operation mode [I don't know what is this]

**Comment by Joffcom** [comment]
Hey @kimtiago,

Just took a quick look and it looks like we delete the old webhook and add a new one to replace it, Is that the same thing you are seeing or are you seeing multiple webhooks being added?

It looks like you don't need to add a new node just move a node and hit save and it triggers the creation as well.

**Comment by kimtiago** [comment]
Hi @Joffcom ,

Thanks for the reply.

> Just took a quick look and it looks like we delete the old webhook and add a new one to replace it, Is that the same thing you are seeing or are you seeing multiple webhooks being added?

No, the old webhook was kept existing and active.
After saving, I'm with two identical webhooks doing duplicate actions.
I looked at mautic logs to see if there's an error in deleting the webhook, but I found nothing. 

> It looks like you don't need to add a new node just move a node and hit save and it triggers the creation as well.

I didn't try only to move a node and save, but if you are saying I believe.

**Comment by Joffcom** [comment]
Hey @kimtiago,

That could be it, I tested with v3 so it could be that something has changed with v4. I will update my instance and test again.

**Comment by kimtiago** [comment]
I had to change something in the workflow and happened again. Now I have a screenshot for you
![2022-04-22_09-15-53](https://user-images.githubusercontent.com/11681263/164722377-14c09871-0604-43c3-9654-fccafdf84758.jpg)
.

**Comment by kimtiago** [comment]
any news about this? it's very annoying...

**Comment by Joffcom** [comment]
Hey @kimtiago,

Updating from 3 to 4 seemed to break my container image so I need to install it again, I have had a note for a few days to do it. I have set aside a bit of time this week to rebuild and test again.

**Comment by Joffcom** [comment]
Hey @kimtiago,

I have managed to get my instance working and I am still not able to reproduce this with vesion version 4. If you move a node and hit save does the ID on both go up? I am just wondering if a previous update has done something funky. What I would try is disable the workflow then in Mautic delete the webhooks if they still exist then enable the workflow again and see if you still get the same issue.

**Comment by kimtiago** [comment]
> I have managed to get my instance working and I am still not able to reproduce this with vesion version 4. If you move a node and hit save does the ID on both go up?

ID of what? The webhook ID? If is it, the original is keep and another webhook is created with a new ID.

>  What I would try is disable the workflow then in Mautic delete the webhooks if they still exist then enable the workflow again and see if you still get the same issue.

I did this test right now. And I think that this worked. I can't reproduce anymore with small changes and save. I will I will observe for a few days and any news i inform you.

**Comment by Joffcom** [comment]
That is possible good news, With the ID it was the number at the end I was talking about.

![image](https://user-images.githubusercontent.com/4688521/166472274-5e162919-7672-4f66-9fe8-9af1ac54607d.png)

I have a feeling that the 48 would maybe stay and the 58 would increment by one on each save, From what I can tell it is "normal" for the ID to increase although a bit annoying and I am not sure why we remake the trigger but I will check in next week to see how things are looking and we might be able to get this one closed :)

**Comment by kimtiago** [comment]
10 days after... no problem with this anymore... I think we can close this.

**Comment by Joffcom** [comment]
Hey @kimtiago,

That sounds good to me, if it happens again let me know.
