### ISSUE TITLE
n8n Windows does not use the default system settings for proxy

### ISSUE THREAD

**Issue by JulienDelRio** [n8n-io/n8n#3159]
**Describe the bug**
I use n8n windows at work.
We are behind a proxy.
The proxy is configured by default in the machine as "detect proxy automatically".
n8n does not use the proxy.
As a result, the tunnel at start is not created and the app does not start (neither crash).

**To Reproduce**
1. Install n8n on a computer in a network blocked by a proxy
2. start the app

**Expected behavior**
The app should retrieve the proxy settings and use it to connect.
Or, we should be able to set a proxy.
Or, the app should start with a message explaining the tunnel is not created.

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n windows Version 1.3.0
 - Node.js Version ?
 - Database system ?
 - Operation mode ?

**Comment by Joffcom** [comment]
Hey @JulienDelRio,

I popped a note on your community question, Any chance you could check and report back? It would be nice to know what the console says is happening if anything. I thought we did fix this one a while back so it could be something else going on.

Have you tried manually setting the proxy using the Electron flags? Something like `n8n.exe --proxy-server=address:port` should do the job.

**Comment by JulienDelRio** [comment]
The proxy is too much protected. I can't see if the  app is well connected to the proxy thanks to the option proxy-server

But, the workaround was to disable the tunnel. https://community.n8n.io/t/how-to-use-automatic-proxy-in-n8n-for-windows/12415/9

`To disable tunnelling in desktop, append DESKTOP_ENABLE_OFFLINE_MODE=true to the n8n-desktop.env in your .n8n dir.`

I will close the issue.

Thank for the help.
