### ISSUE TITLE
Save button remains disabled after a node position is changed

### ISSUE THREAD

**Issue by pbac-sk** [n8n-io/n8n#3167]
**Describe the bug**
Issue with saving position of nodes from version 0.172.0
While editing a workflow, after a node is moved, the Save button remains disabled.
If some other change is made to the workflow, e.g. a node is deactivated, the Save button is enabled. But when saving the workflow, the position of the nodes, which was changed before, is ignored. After refreshing the page, the position of the nodes is different from what was in the editor before.
This issue is not in version 0.171.0

**To Reproduce**
1. Go to 'Workflows / New'
2. Click on 'Add Notes / Flow / IF'
3. Click on 'Save'
4. Move the 'IF' node
5. Disable the 'IF node
6. Click on 'Save'

**Expected behavior**
After step 4: The 'Save' button is enabled
After step 6: Position of the nodes is saved

**Environment (please complete the following information):**
 - Docker: n8nio/n8n
 - Tags: 0.172.0, 0.173.1
 - Database system: SQLite
 - Operation mode: own

**Additional context**

**Comment by pbac-sk** [comment]
I tried with Firefox 91.8.0esr and Edge 100.0.1185.44 and got the same
result.
For certain reason, I'm running VirtualBox with Ububtu Server 20.04 as a
guest system, with Docker. Port forwarding is enabled on VirtualBox to the
guest port 5678. The browsers are running on the host system Windows 10.

**Comment by Joffcom** [comment]
That sounds like it should be working, I am on a newer version of Firefox (99) but I suspect 91 would also work. If you check the network log and console of either browser are there any errors?

**Comment by pbac-sk** [comment]
No network errors.
There is one console error, while loading the editor page in Firefox:
`The connection to http://localhost:5678/rest/push?sessionId=a03178d77ug was interrupted while the page was loading. - app.bfdc94ac.js:1:284261`
There are no errors after click on the Save button.
However, when tried with version 0.171.0, I can see similar error message there, but after a node position is changed, the Save button is enabled and after clicking on it, the position is saved - remains after the page is refreshed in the browser.

I just found the behavior is different in Edge. After step 6 (from the issue description), the position is saved. In Firefox, only the activation status (enabled/disabled) is saved, not the position.
After step 4, the Save button is disabled in both browsers.

**Comment by Joffcom** [comment]
That is really odd, Are you able to record a gif or similar so we can see it in action?

**Comment by pbac-sk** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/6715805/164730269-adf46326-2dcf-4dec-8730-a2e66f97f729.gif)

**Comment by pbac-sk** [comment]
I found issue #1989 is similar to this one. My laptop has touch screen.

Just tried the same on different computer (no touch screen), using Firefox 99 and n8n 0.173.1
I was able to save the workflow after the node position was changed. So no issue there.

**Comment by Joffcom** [comment]
Ah, Yeah I forget about that one and I mentioned it to someone today :). I wonder why the problem is not in 171 but is in 173. @mutdmour any thoughts on that?
