### ISSUE TITLE
Error when uploading more than 10mb with HTTP Request

### ISSUE THREAD

**Issue by chemi392** [n8n-io/n8n#3171]
**Describe the bug**
When posting a binary larger than 10MB the node will fail with the error "Request body larger than maxBodyLength limit"

**To Reproduce**
1. Create an HTTP Request node
2. Set to POST
3. JSON/RAW Parameters = True
4. Body Content Type = Raw Custom
5. Send Binary = True
6. Binary Property = data
7. Headers = {{ {"Content-Type": "application/binary"} }}
8. Upload a file larger than 10MB

**Expected behavior**
File Uploads

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version 0.169.0
 - Database system MySQL (problem also persisted in SQLite)
 - Operation mode own
 - Using Docker Image

**Additional context**
In the docker image maxBodyLength and maxContentLength in /usr/local/lib/node_modules/n8n/node_modules/axios/lib/defaults.js are both set to -1 which would imply unlimited, however that fails with files over 10MB.  If -1 is replaced with a number larger than 1024 * 1024 * [max expected file size] it works with files over 10MB up to the max expected file size.

**Comment by Joffcom** [comment]
Hey @chemi392,

This is something we are aware of, At the moment the workaround is to use Axios from a function node to upload the data which isn't ideal and can get tricky depending on what auth is needed.

**Comment by janober** [comment]
The problem should be fixed by this PR #3370 which got already merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.179.0`
