### ISSUE TITLE
Cannot connect credentials for Outlook node

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#3245]
**Describe the bug**
When I'm trying to configure oAuth2.0 authentication details for my Azure APP, I get the error:
`AADSTS50194: Application '0577224d-0e94-xxxx-xxxx-xxxxx'(My Application Name) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant`.

So for now, I can't use Outlook node as I can't specify a tenant_id in the configuration, thus the node is trying to get a token from /common endpoint instead of using my tenant. And I also can't configure a multi-tenant app due to the security restrictions.

And also a big issue is using delegated context for credentials instead of application context

**To Reproduce**
1. Create a single tenant APP in Azure
2. Configure authentication details for OAuth2 Outlook credential profile
3. Get the error

**Expected behavior**
Tenant-id in the configuration profile and option to use application context instead of using delegated context 

**Environment (please complete the following information):**
 - OS: Docker (AWS Elastic Container Service) - docker pull n8nio/n8n:latest
 - n8n Version: 0.174.0

**Comment by Joffcom** [comment]
Hey @barn4k,

Have you tried changing the Authorization and Token URL to contain your tenant ID? I have done a quick test following the MS documentation and it appears to work.

Try using the options below replacing `{tenant}` with your tenant ID.

**Authorization URL:** https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize
**Access Token URL:** https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token

![image](https://user-images.githubusercontent.com/4688521/166930655-ff4fba70-6a1e-4bf5-aa3c-27f36c8c1a24.png)

**Comment by Joffcom** [comment]
I have not tried application context before either but I suspect that could be where you might find some issues.

**Comment by barn4k** [comment]
Yes, I suppose the issue will be with the API urls, as with delegated context it is always /me, but with application context we need to specify the endpoint explicitly, so it required adding additional field in the Outlook node

**Comment by Joffcom** [comment]
That might need an HTTP Request node approach and a bit of playing around.

Could be worth a feature request on the community forum though if you are after that we track them there rather than here as we use this for bugs.

**Comment by barn4k** [comment]
Yeah, good point. Closing the issue
