### ISSUE TITLE
Error: command start not found

### ISSUE THREAD

**Issue by woss** [n8n-io/n8n#325]
**Describe the bug**
When following the README file and running `npm run start` after bootstraping it throws the error:
```
/P/g/w/n8n ❯❯❯ npm start                                                                                               ✘ 2 

> n8n@ start /$PATH/n8n
> run-script-os


> n8n@ start:default /$PATH/n8n
> cd packages/cli/bin && ./n8n

 ›   Error: command start not found
```

**To Reproduce**
1. Go to root dir
2. Run `npm run start`
3. See error

**Expected behavior**
to start the app

**Environment (please complete the following information):**
 - OS: OSX 10.13.6
 - n8n Version n8n@0.54.0
 - Node.js Version  v13.7.0

**Additional context**

**Comment by woss** [comment]
i have to mention that Docker image works perfectly. I'd like to experiment with and maybe add debug since it would be very useful to have info on what is going on

**Comment by janober** [comment]
Sorry to hear that you have problems! It is possible that for MacOS it works differently. You can check this line:
https://github.com/n8n-io/n8n/blob/master/packages/cli/package.json#L27
and maybe change it to the Windows version or try some different combinations. If you find one that works we can add a special command for MacOS like for Windows.

**Comment by janober** [comment]
Just to be sure. Did you run `npm run build` before?

**Comment by woss** [comment]
> Just to be sure. Did you run npm run build before?
Nope, but when i do it works. :) 

I just noticed that `oclif` commands config is `dist/commands` which means that i must run `build` before i can run the app in dev mode. why is that? 

I've tried setting the same config to `./commands` but it starts failing on missing deps. Any idea why?

**Comment by janober** [comment]
If I remember correctly does oclif create some files on build that are needed. For that reason does it have to be executed first. Should also be written like that in the documentation.

**Comment by woss** [comment]
I'm talking about the file in the `packages/cli/packages.json` 
```
...

"oclif": {
	"commands": "./commands",
	"bin": "n8n"
},
...
```

If I have that then it fails on the `ts-node` is not found, which i install in the `cli` package, then 
on `npm run start` i start getting 
```
(node:11082) ColumnTypeUndefinedError Plugin: n8n: Column type for CredentialsEntity#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
module: @oclif/config@1.14.0
task: toCached
plugin: n8n
root: /Users/woss/Projects/github/n8n-io/n8n/packages/cli
See more details with DEBUG=*
ColumnTypeUndefinedError Plugin: n8n: Column type for CredentialsEntity#name is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.
    at new ColumnTypeUndefinedError (/Users/woss/Projects/github/n8n-io/n8n/src/error/ColumnTypeUndefinedError.ts:9:9)
    at /Users/woss/Projects/github/n8n-io/n8n/src/decorator/columns/Column.ts:139:23
    at DecorateProperty (/Users/woss/Projects/github/n8n-io/n8n/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/Users/woss/Projects/github/n8n-io/n8n/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate (/Users/woss/Projects/github/n8n-io/n8n/packages/cli/src/databases/mongodb/CredentialsEntity.ts:4:92)
    at Object.<anonymous> (/Users/woss/Projects/github/n8n-io/n8n/packages/cli/src/databases/mongodb/CredentialsEntity.ts:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/Users/woss/Projects/github/n8n-io/n8n/packages/cli/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/woss/Projects/github/n8n-io/n8n/packages/cli/node_modules/ts-node/src/index.ts:817:12)
```
Which is really weird because the files on these lines don't exist at all

```
  at new ColumnTypeUndefinedError (/Users/woss/Projects/github/n8n-io/n8n/src/error/ColumnTypeUndefinedError.ts:9:9)
    at /Users/woss/Projects/github/n8n-io/n8n/src/decorator/columns/Column.ts:139:23
```

**Comment by woss** [comment]
can you please do me a favour and run on the clean env setting up this repo? 
also `npm run bootstrap && npm install` or just `bootstrap`

**Comment by janober** [comment]
Yes, that flow looks good and is actually exactly what is in the guide:
https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#actual-n8n-setup

With the difference that the guide says to execute: `lerna bootstrap --hoist`
which is identical to `npm run bootstrap`
https://github.com/n8n-io/n8n/blob/master/package.json#L6

**Comment by woss** [comment]
out of curiosity, why do we need to build it? Why we can't `start` or `dev`?

**Comment by janober** [comment]
Because like mentioned before does oclif have to create some files which are needed.
https://github.com/n8n-io/n8n/blob/master/packages/cli/package.json#L25

Did, not check how long the command takes to execute. So it is possible that it would also be OK to be added as pre-step for the other commands. Never looked into it again once it worked as there are so many other things that are still missing and could be optimized, so this simply never seemed worth investing any more time or thought.

**Comment by woss** [comment]
ok, thanks for clearing this up :) now i can test it a bit maybe even make few nodes.

**Comment by janober** [comment]
You are welcome and happy to hear! Have fun. 

If you have any problems or questions reach out anytime via the forum. Try to get back to you asap.

**Comment by Chinaniu** [comment]
@n8n/chat#build: command (D:\VScode\newN8n\n8n\packages\@n8n\chat) pnpm run build exited (1)   how  to ?

**Comment by janober** [comment]
@Chinaniu This issue is over 2 years old, and your problem seems to be in a totally different part of the code (which did not even exist back then). Please open a new issue instead and provide all the necessary information so that we can help you with your problem. Thanks!
