### ISSUE TITLE
Modal window containing expression is not shown on firefox

### ISSUE THREAD

**Issue by laurent-lemke** [n8n-io/n8n#3269]
**Describe the bug**
When we open a workflow execution and we want to see the value of an expression within a field, the modal is not displayed with Firefox.

With Google chrome, it works.

**To Reproduce**
With Firefox:
1. Open a previous workflow execution
2. Open a node that has a field containing an expression
3. Try to open the field => impossible.

**Expected behavior**
Have the window modal showing the expression content

**Environment (please complete the following information):**
 - OS: macOS 12
 - n8n Version 0.174
 - Node.js Version LTS
 - Database system default
 - Browser version: Firefox 100.0 (but occured also with previous version)

**Additional context**

**Comment by Joffcom** [comment]
Hey @AilurusFulgenz,

Thanks for reporting this one, I have just given it a quick test and was able to reproduce it. I will get it added to our internal ticket system.

**Comment by Joffcom** [comment]
Hey @laurent-lemke,

Looks like I did the random tag on this as well... Anyway just tested this on the latest release of n8n and it looks to be working now. I am going to mark this one as solved and if you still happen to run into this let me know and we can open it again.
