### ISSUE TITLE
Angular Integration : Do we have any integration document or sample app available for Angular + n8n

### ISSUE THREAD

**Issue by PradneshShinde** [n8n-io/n8n#3275]
Hello,
I'm looking to integrate n8n into my existing angular project.
But I didn't find any article or any packages with which we can customize the n8n with angular or any iframe option.

any help will be appreciated
thank you.

**Comment by Joffcom** [comment]
Hey @PradneshShinde,

It looks like @that-one-tom has answered this question for on our community support forum. I will mark this one as closed and we can carry on the conversation over there 👍🏻
