### ISSUE TITLE
ShopiFy Trigger -  Not Working - Shopify Private Apps Deprecated

### ISSUE THREAD

**Issue by ivorsmorenburg** [n8n-io/n8n#3295]
**Describe the bug**
Shopify doesn't trigger due private app deprecation in Shopify and now replaced by custom apps

https://community.n8n.io/t/shopify-triggers-on-n8n-cloud-trigger-not-working/13208/10

**To Reproduce**
1. Go to 'ShopiFy Trigger'
2. Click on 'Add Credentials & Trigger from webhook in shopify (`https://<shopifysubdomain>.myshopify.com/admin/settings/notifications`)'
3. Scroll down to the bottom and add weebhook for cart creation event, then send test weebhook'
4. See error, Trigger doesn't isn't received or not valid 

**Expected behavior**
Shopify should trigger on webhook event from shopify

Using Latest Shopify Version API (2022-04)

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version 0.176.0
 - Node.js Version provided in image

**Comment by Vultik** [comment]
I have the same issue #3516 , the shopify trigger doesn't work anymore with the new way of creating custom private apps :/

**Comment by Joffcom** [comment]
Hey @Vultik,

I have just nudged this one internally so that we can bump up the priority.

**Comment by Vultik** [comment]
Any updates on it ?

**Comment by ItsJamesMurray** [comment]
Any updates here? I'm in the same boat (self hosting on docker) and would love to use n8n for my shopify notifications and and management

**Comment by Vultik** [comment]
Yeah it's still not fixed, i'm very disapointed of n8n about that ...

**Comment by Joffcom** [comment]
I will have a check in the morning and see if I can find anything.

**Comment by Joffcom** [comment]
Looking at the release notes we added oauth support to 187 which can be used by the trigger node, does this not solve the issue?

**Comment by yotamcuralife** [comment]
what about shopify integration? it is still not working...:/
