### ISSUE TITLE
smtp config not friendly with STARTTLS

### ISSUE THREAD

**Issue by tolgaulas** [n8n-io/n8n#3297]
**Describe the bug**
We can't create users, getting error: There is a problem with your SMTP setup! 140374200150832:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/reco

**To Reproduce**
Any mail server requiring STARTTLS on port 587, setup with N8N_SMTP_PORT=587

**Environment (please complete the following information):**
 - OS: Debian 10 
 - n8n Version : docker n8nio/n8n
 - Node.js Version : docker n8nio/n8n
 - Database system : sqlite
 - Operation mode : own

**Comment by Joffcom** [comment]
Hey @tolgaulas,

Have you tried setting `N8N_SMTP_SSL` to false?

**Comment by tolgaulas** [comment]
> Hey @tolgaulas,
> 
> Have you tried setting `N8N_SMTP_SSL` to false?
@Joffcom that did work well, missed that. thanks a lot.

**Comment by Joffcom** [comment]
Hey @rvalle,

That key is only for User Management, If it is in the node you can try toggling the SSL/TLS option for the Credential and see if that helps.

**Comment by rvalle** [comment]
@Joffcom I think it is attempting an SSL conneciton on my 587 delivery port which is TLS only. 
kind of the same issue but on the email sender module.

**Comment by Joffcom** [comment]
Hey @rvalle,

TLS shouldn't be an issue, I use Mail Trap for testing which uses TLS and I have the port to 587 and SSL/TLS set to off this also works for gmail. This should also work for you, What error message do you get with that setting?
