### ISSUE TITLE
Error: There was an error: options.port should be >= 0 and < 65536. 

### ISSUE THREAD

**Issue by fenggolang** [n8n-io/n8n#3298]
![image](https://user-images.githubusercontent.com/16982786/168541253-411e30b9-6186-474e-81e0-1816a29ed11c.png)

**Comment by Joffcom** [comment]
Hey @fenggolang,

Could you use the template we provide when opening an issue it tends to save a lot of questions. This one I suspect is down to your config file containing a port value that is incorrect, Can you check what you have the port value set to.

**Comment by janober** [comment]
And here are other closed issues with the same error:
https://github.com/n8n-io/n8n/issues/88
https://github.com/n8n-io/n8n/issues/863
