### ISSUE TITLE
Slack: upload file not finding slack channels

### ISSUE THREAD

**Issue by jakub-milanowski** [n8n-io/n8n#3303]
I created a basic workflow consisting of a webhook that receivers binary file data and I want to upload it to slack. I followed your guide (https://n8n.io/workflows/1570) and I could not choose the channel from the list (actually, there was no list which is the problem). The app permissions on slack are set to all chat: options and file: options with remotefiles: too.

The error there said: 
  - There was a problem loading the parameter options from server: "UNKNOWN ERROR - check the detailed error for more information"
  
![image](https://user-images.githubusercontent.com/92891000/168625180-71445825-0b56-4a25-8de2-2e3251778187.png)

**Comment by Joffcom** [comment]
Hey @jakubmilanowskiwcy,

We try to keep the Github issues for bugs only, Our support is handled on our community forum which you can find here: https://community.n8n.io

That being said I suspect it is a scope issue and the app doesn't have any of the channel options like channels:read, You may also need to invite your Slack integration into the channel you are posting to.

**Comment by nivb06** [comment]
Hi @jakub-milanowski, is this problem solved for you after @Joffcom's suggestions?

**Comment by Joffcom** [comment]
Hey @jakub-milanowski,

I have just been clearing up some older issues and noticed that we never got a reply on this one, for now I am going to mark this one as closed and if you are still having this problem let me know and we can open it again.
