### ISSUE TITLE
Creating a node with optional credentials

### ISSUE THREAD

**Issue by naskio** [n8n-io/n8n#3306]
**Describe the bug**
During node creation In older version of n8n, it was possible to create a node with optional credentials `required: false` but in recent version doing so is throwing the exception `ERROR: Node does not require credentials` when we run the node.

**To Reproduce**
Create a node with a description containing:
```
...
credentials: [
			{
				name: 'test',
				required: false,
			},
		],
...
```
**Expected behavior**
Making the credentials optional and not required to run the node.

**Environment (please complete the following information):**
 - OS: Linux
 - n8n Version: 0.176.0
 - Database system: PostgreSQL
 - Operation mode: default

**Additional context**
I created a [custom node](https://github.com/naskio/n8n-nodes-python) 
In older versions of n8n, it was running normally with or without providing credentials
But recently when I upgraded n8n it started throwing this error when the credentials aren't provided
Read more about this [issue here](https://github.com/naskio/n8n-nodes-python/issues/1)

**Comment by janober** [comment]
Ah yes, that changed recently. What you can still do, is to wrap the `this.getCredentials` call in a `try ... catch`.

**Comment by janober** [comment]
As I did not hear back do I close this issue for now. Please report back if you run into problems.
