### ISSUE TITLE
Workflows Automatically Shutting off 

### ISSUE THREAD

**Issue by jsdanie1** [n8n-io/n8n#3319]
The minute I view a workflow, it automatically sets it too "Inactive". even if I don't make any changes. This does seem to happen on Edge browser and not chrome. 

Expected Behavior: 
  - Honestly think save state shouldn't impact active or inactive at all. Should be two entirely separate things. 
  - If you make an edit, or not the workflow is on regardless, and it can just prompt for do you want to save those changes or not. 

Environment:
 - Windows 11
 - n8n Ver: 0.175.1
 - Node.js Version: Unsure where to find this.

**Comment by Joffcom** [comment]
Hey @jsdanie1,

Have you also opened a support ticket with us about this one?

**Comment by Joffcom** [comment]
Hey @jsdanie1,

Do you happen to have any Edge extensions running?

**Comment by jsdanie1** [comment]
Yeah I believe i found the issue. I use the LastPass extension. and have the extension setup to autofill your login page. But after inspecting the n8n login page I notieced it doesn't have a name or ID values for the input fields, so lastpass saved the autofill as generic input id. For example most webpages have:

<input name="username" or id="username">
<input name="password" or id="password">

so nomrally lastpass would save the autofill as username and password. Then the extension probable searches for these pages as i navigate around the site. but right now it saves it as input. this causes the autofill to search the n8n interface and because the active button are considered input fields it triggering a autofill on that field. I want ahead in the mean time and turned off lastpass autofill for the n8n site, but curious if the login page can be updated eventually to be more password plugin friendly.

**Comment by Joffcom** [comment]
Hey @jsdanie1,

I have a feeling I have been chatting to you on our ticket system, We have this one raised in our internal tracker so for now I am going to close this issue.
