### ISSUE TITLE
Slack node error response "missing required field: channel" when using kick operation

### ISSUE THREAD

**Issue by GlitchWitch** [n8n-io/n8n#3352]
**Describe the bug**
When using a Slack node with "Resource:Channel" and "Operation:Kick" an error occurs.

> Slack error response: {"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] missing required field: channel"]}}

**To Reproduce**
Steps to reproduce the behaviour:
1. Confirm the provided Slack API credentials can perform this action using the [API tester](https://api.slack.com/methods/conversations.kick/test).
2. Create a Slack node with "Resource:Channel" and "Operation:Kick"
3. Select a Channel and User
4. Execute the node
5. See error

![Screenshot_2022-05-22_17-55-17](https://user-images.githubusercontent.com/32590246/169709111-583735d6-170b-4b91-a3a4-c7397e492db9.png)

**Expected behaviour**
The user should should be kicked from the channel and no error should occur.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version: 0.177.0
 - Database system: SQLite
 - Operation mode: own

**Additional context**
This error occurs regardless of if an expression is used to set the Channel and User fields of the node.

**Comment by GlitchWitch** [comment]
Just to be sure I tested this again in n8n.cloud on n8n@0.176.0 and n8n@0.177.0 and both produce the same error.

**Comment by janober** [comment]
Thanks a lot for reporting this issue. Got fixed and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.178.0`
