### ISSUE TITLE
Orbit node member upsert not consistent with docs

### ISSUE THREAD

**Issue by technovangelist** [n8n-io/n8n#3353]
**Describe the bug**
The docs for the n8n node for Orbit.love is in agreement with the Orbit docs that says you can add a member with any source. But when you try to set a source of anything beyond 4 in the dropdown it says its not allowed.

**To Reproduce**
1. Add a Orbit node
2. Set Resource to Member
3. Set operation to Upsert
4. Set a workspace
5. Set Source to any string you want to use as a source

Notice that it errors saying "The value xxx is not supported"

**Expected behavior**
I would expect it to work as the docs suggest allowing any source to be possible

**Environment (please complete the following information):**
n8n.cloud

**Additional context**

**Comment by technovangelist** [comment]
this should not be closed. @ivov submitted a PR that removed the doc saying how the api call works, but even with that, the issue described here is still broken. A custom source is possible, but not with n8n as it is today.

**Comment by Joffcom** [comment]
Hey @technovangelist,

I have just taken a quick look at the PR and I think the quickest option would be to add a Custom field to the sources so you can select that and input the name then set the search by between ID, Email, Username and URL.

Would this sort of thing work for you?

![image](https://user-images.githubusercontent.com/4688521/193643184-1680a1cc-2d96-4fab-a521-dc924ade1dca.png)

We would also need to update the other operations to support this change as well but if this sort of thing would work for you I can look at implementing it properly when I get some time to add a new feature to the node.

**Comment by technovangelist** [comment]
I think that might work. Its been a while since I thought about the problem

**Comment by Joffcom** [comment]
Hey @technovangelist,

No worries, I have it on my list of things to implement anyway as I think it would be very handy.

**Comment by Joffcom** [comment]
Just adding that the internal reference for this one is `NODE-75`

**Comment by Joffcom** [comment]
Moving this to closed as Orbit no longer exists as a service.
