### ISSUE TITLE
Google Drive Trigger for Shared Drive

### ISSUE THREAD

**Issue by dominikmukrecki** [n8n-io/n8n#3358]
**Describe the bug**
Greetings, it seems like a Google Drive Trigger node does not work with shared drives yet. Regards, Dominik.

**To Reproduce**
Steps to reproduce the behaviour:

1. Make workflow with Google Trigger
2. Use details appropriate for the shared drive.
3. For example, try to modify the folder if the trigger is set to monitor it.

**Environment (please complete the following information):**
 - n8n Version 0.177.0
 - Database system postgresql
 - Operation mode `main`

**Comment by kaarelen** [comment]
If you wont to collaborate\vote here is forum [link](https://community.n8n.io/t/google-drive-trigger-and-shared-drive/11673)

**Comment by Joffcom** [comment]
Hey @dominikmukrecki,

As this one is a feature request and not a bug I am going to mark this one as closed, If you have not already done it popping a vote on the feature request will let us get an idea of how popular this is with the community.
