### ISSUE TITLE
[HTTP Request node] failling requests due to Cloudflare DDoS protection

### ISSUE THREAD

**Issue by dokime7** [n8n-io/n8n#3376]
**Describe the bug**
When an API server is protected by Cloudflare DDoS protection, requests are failing.
But many other HTTP client like `curl` doesn't seems to have the issue.

**To Reproduce**
1. Add HTTP Request node
2. Choose method: GET
3. Use URL: https://fusion.runonflux.io/coinbase/summary
4. Execute node

Received: ERROR: UNKNOWN ERROR - check the detailed error for more information
HTTP 503

**Expected behavior**
Receiving HTTP 200 or 400 with json
```
$ curl https://fusion.runonflux.io/coinbase/summary
{"status":"error","data":{"name":"Error","message":"Missing query of coinbase mining address"}}
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - n8n Version 0.178.2
 - Docker image tag: 0.178.2
 - Database system: Postgresql
 - Operation mode: queue

**Comment by Joffcom** [comment]
Hey @dokime7,

It sounds like Cloudflare might be limiting your connection, I have given it a test here and it is working as expected so I don't think the issue is with the node itself.

![image](https://user-images.githubusercontent.com/4688521/170228246-1f5e3f57-a47d-4de0-a25b-ac032effee9f.png)

When you are testing are you only calling that URL or are you doing some other actions before it? If you were maybe reading a file first or creating a list of items it could case that error as you would be firing off multiple requests at once which would cause Cloudflare to put a bit of a block in place.

**Comment by dokime7** [comment]
Hmmm...
I can request like `http https://fusion.runonflux.io/coinbase/summary` (HTTPie client) from the n8n server without any problem...
But it seems that with `curl` the error is returned sometimes. So if I change the user-agent of curl, it's working well all the time.

But in n8n, adding header User-Agent: HTTPie/3.2.1 doesn't solve anything. Is User-Agent header is well overrided?

**Comment by dokime7** [comment]
So, I've just check for user-agent, it is well sent with the custom value.

Notice that I put in request header:
 - Name: User-Agent
 - Value: HTTPie/3.2.1
And the request is sent like this: `user-agent: HTTPie/3.2.1`
See that header name seems to be transformed in lowercase `user-agent`

Not a big issue but Cloudflare is a bit picky.

**Comment by Joffcom** [comment]
That makes sense we use the Axios user agent for requests but I can only reproduce the error if I send a lot of requests. I think Cloudflare depending on settings will perform a soft block no matter what the user agent is if there are enough requests being sent so I am not sure if this is actually a bug with n8n or just Cloudflare working as expected.

**Comment by rcnavas** [comment]
I think this is the same problem I was facing with API endpoint: `https://game-api.skymavis.com/game-api/clients/:address/items/1` which is also behind Cloudflare. 
Doing the request from *Postman* or `curl` didn’t have any problems, but *n8n HTTP Request Node* had the reported problem in this issue. The only difference I found was: Other HTTP clients use HTTP `Keep-Alive` *by default* while *n8n HTTP Request Node* does NOT.
I had to fork *n8n* repo, and did a monkey patch to add `HTTP Keep-Alive` option to the *HTTP Request Node*.
Here is the Fork repo: https://github.com/rcnavas/n8n
I submitted a Pull Request here, but I don’t have the time to provide a sample, so it was closed/rejected by n8n team. Here: https://github.com/n8n-io/n8n/pull/2993

**Comment by Joffcom** [comment]
@rcnavas Did Cloudflare also return a 503 error in your case? I was not able to reproduce the same issue with the URL provided in this issue on Desktop, Cloud or self hosted in Docker, I believe this is down to rate limiting and there could be mutliple input items being sent to the node which is causing the limiting to kick in.

The 503 error is documented by Cloudflare here: https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#503error which I think further supports the theory.

As with any issue we can only go from the information we have and what we can reproduce so if we have a workflow that can reproduce the issue we are then able to work quicker on fixing it if it is something on our side.

**Comment by dokime7** [comment]
In my side, I don't call so much the url, just one time and get 503 with n8n.
When I request the same url from the n8n server with curl there is not issue, so I guess that `Keep-Alive` impact the response and I am in favor of adding `Keep-Alive` option on HTTP request node.

**Comment by Joffcom** [comment]
Evening @rcnavas & @dokime7,

As we were not able to reproduce using the same URL the issue seems unlikely to be directly related to n8n, The Keep Alive may have been a useful addition but it probably wouldn't have solved this looking at the error and the cloudflare docs.

For now I am going to mark this one as closed and if this does pop up again we can look into it in more detail.
