### ISSUE TITLE
Catch error on ssh node

### ISSUE THREAD

**Issue by henres** [n8n-io/n8n#3377]
Hello,

Thanks for your awesome tool.

**Describe the bug**
I have a problem with the ssh node.
The workflow was marked as successful but the code error = 1

```json
[
  {
    "code": 1,
    "signal": null,
    "stdout": "",
    "stderr": "Too many arguments to "create-project" command, expected arguments "package " "directory" "version". create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]"
  }
] 
```

**To Reproduce**
1. Go to a workflow and create a ssh node
2. Click on the ssh node, set the remote host and add a command that will fail `ehco "Hello world"`
3. Execute the node or the workflow
4. The node or the workflow is successful. It shows exit code 1. It should be unsuccesful. 

**Expected behavior**
The execution should be unseccussful. 

**Environment (please complete the following information):**
 - OS: official n8n docker image
 - n8n Version : 0.178.2
 - Database system : default 
 - Operation mode : default

Thanks in advance

**Comment by Joffcom** [comment]
Hey @henres,

Can you fill out the template we provide, Knowing the version and install type is sometimes handy for troubleshooting. For this one though under the node settings do you have it set to continue on fail? 

![image](https://user-images.githubusercontent.com/4688521/170233327-d2c2b147-89bc-4329-8de3-6b72f735e869.png)

**Comment by henres** [comment]
Hello,

No, Continue on fail is not enable.

For the version :
You’re on 0.177.0, which was released 1 week ago and is 1 version behind the latest and greatest n8n

For the type, I am testing for now on my local with docker, I just use the command provided on the docker hub page:
```bash
docker run -it --rm \
    --name n8n \
    -p 5678:5678 \
    -v ~/.n8n:/home/node/.n8n \
    n8nio/n8n
```

```json
{
  "name": "test copy",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        -260,
        620
      ]
    },
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "mode": "custom"
            }
          ]
        }
      },
      "name": "Cron",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        -280,
        200
      ]
    },
    {
      "parameters": {
        "command": "set -o errexit; \\\nset -o nounset; \\\nset -o pipefail; \\\ndocker run --rm composer create-project symfony/skeleton /project && \\\ncd /project && \\\ncomposer require webapp && \\\nbin/console about"
      },
      "name": "SSH",
      "type": "n8n-nodes-base.ssh",
      "typeVersion": 1,
      "position": [
        -60,
        200
      ],
      "retryOnFail": false,
      "credentials": {
        "sshPassword": {
          "id": "1",
          "name": "SSH Password account"
        }
      }
    }
  ],
  "connections": {
    "Cron": {
      "main": [
        [
          {
            "node": "SSH",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "timezone": "Europe/Paris",
    "saveDataSuccessExecution": "all",
    "saveExecutionProgress": true,
    "saveManualExecutions": true
  },
  "id": 2
}
```

**Comment by henres** [comment]
I just try with the last one : 0.178.2. Still same problem

**Comment by janober** [comment]
Ah yes, that is sadly how that node currently behaves. Is the same for the "Execute Command" node. Is something we should probably change in the future. But for now, if you want to know if the command did execute successfully, you would have to add an IF-Node afterward. Then you can either run some other nodes or fail the workflow with the "Stop and Error" node.

That is something that annoyed me also for a while but we could not change that because it would have broke existing workflows. With recent changes to n8n that should now however be possible now. So I created an internal ticket about it.

**Comment by henres** [comment]
It works with execute command node !

**Comment by henres** [comment]
Hello, @janober do I let this issue open ?

If you have a ticket open on your side, maybe we can let this one open waiting for the correction ?

Thanks

**Comment by Joffcom** [comment]
Hey @henres,

I think as this is more of a feature change than a bug it is safe to close this one, We have not yet implemented the change but when we do I will let you know.

**Comment by lingfish** [comment]
Surprised to see this issue still isn't fixed.
