### ISSUE TITLE
Calendly discontinuing support for v1 API keys. Credentials will not work for new Calendly tokens.

### ISSUE THREAD

**Issue by cheap-geek** [n8n-io/n8n#3392]
**Describe the bug**
Calendly is phasing out support for v1 API keys June 30th 2022. The current Calendly Node only authenticates using v1 API keys.  Trying to use Calendly tokens does not work. 

**To Reproduce**
1. Use Calendly tokens as credentials. will result in error.

**Expected behavior**
Authenticate using Calendly tokens instead of v1 API key. 
It appears the new v2 API is not backwards compatible with v1

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version 0.178.2
 - Node.js Version 16.15.0
 - Database system SQLite
 - Operation mode Own

**Additional context**

**Comment by Joffcom** [comment]
Hey @cheap-geek,

Thanks for reporting this one.

**Comment by janober** [comment]
Fix just got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.187.1`
