### ISSUE TITLE
Woocommerce Trigger throws an error from the beginning of the execution

### ISSUE THREAD

**Issue by romainsaillant** [n8n-io/n8n#3398]
**Describe the bug**
In a workflow that starts with Woocommerce Trigger, I had two executions that failed from the trigger node, so the error can't be in the workflow that follows. The error is 'ERROR: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined'. And the trigger is set on a 'product.updated' event.

**To Reproduce**
1. Create a workflow that starts with a Woocommerce Trigger with 'product.updated' event
2. Wait for it to trigger
3. See error

**Expected behavior**
I expected the Woocommerce Trigger to work as usual

**Environment (please complete the following information):**
 - OS: not sure, I host n8n using Heroku
 - n8n Version: 0.177.0
 - Node.js Version
 - Database system: Postgres
 - Operation mode

**Comment by romainsaillant** [comment]
It seems that the problem stopped a few hours after my post, so I'm closing this issue.

**Comment by alanfrigo** [comment]
I am having the exact same issue right now
