### ISSUE TITLE
only 10 items list when select return all using the hive

### ISSUE THREAD

**Issue by heywiorld** [n8n-io/n8n#3401]
**Describe the bug**
Only 10 items list when select return all using the hive.

**To Reproduce**
1. Go to 'thehive'
2. Click on 'alert'
3. Scroll down to 'getall'
4. Click "return all"
5. only 10 items return, not all the alerts

**Expected behavior**
Return all alerts.

**Environment (please complete the following information):**
 - OS: WIN11
 - n8n Version [0.174.0]
 - Node.js Version [not sure]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [own]

**Additional context**

![image](https://user-images.githubusercontent.com/43668597/171135721-65ac7a00-5c30-49e3-9d28-aa6dc00e6013.png)

**Comment by heywiorld** [comment]
4.1.18-1

**Comment by Joffcom** [comment]
Perfect thanks, I am in the middle of another issue at the moment but I will try and get a look at this one later today .

**Comment by michael-radency** [comment]
Hello @heywiorld, do you still have this issue? I did test it and on v5 it works correctly, returns all alerts

**Comment by heywiorld** [comment]
> Hello @heywiorld, do you still have this issue? I did test it and on v5 it works correctly, returns all alerts

@michael-radency  yeah, still return 10 when I open get all option

**Comment by michael-radency** [comment]
Hello @heywiorld , 
still can not reproduce this issue, I'm using v4, getting all alerts from TheHive, 
are you sure that you have more alerts? did you use any filters?

![image](https://user-images.githubusercontent.com/88898367/177761408-343db1ef-25d5-406b-8527-2ae32f3c3db8.png)
![image](https://user-images.githubusercontent.com/88898367/177761764-f9ba172c-b20c-43e1-b33b-d20d02991fab.png)

**Comment by michael-radency** [comment]
> how could I get v5?

you can build it `docker run --rm -p 9000:9000 strangebee/thehive:latest`

**Comment by heywiorld** [comment]
> > how could I get v5?
> 
> you can build it `docker run --rm -p 9000:9000 strangebee/thehive:latest`

Hi @michael-radency ， thanks for your reply, but I am using v4 not v5

**Comment by michael-radency** [comment]
> thanks for your reply, but I am using v4 not v5

Hi @heywiorld as I mention in previous comment I did test it in v4 and can not reproduce issue

**Comment by heywiorld** [comment]
![image](https://user-images.githubusercontent.com/43668597/178912433-4d955610-85fd-4820-867a-f90d6d7d60be.png)
![image](https://user-images.githubusercontent.com/43668597/178912460-0f15fd80-4cfa-4727-9fa9-ba81b234936f.png)
I use the same option with you, but still only 10 items return, while alert is over 1000

**Comment by Joffcom** [comment]
Hey @heywiorld,

Are you seeing this issue on the latest release of n8n?

**Comment by Joffcom** [comment]
Closing this for now as I believe it has been solved, If it is still an issue let me know and we can open it again.
