### ISSUE TITLE
Similar Case is null

### ISSUE THREAD

**Issue by heywiorld** [n8n-io/n8n#3409]
**Describe the bug**
When using thehive connector, always return null for get alert.

**To Reproduce**
1. Go to add 'the hive'
2. Click on 'alert'
3. Scroll down to 'get'
4. Fill the alert id and run
5. No similar case in the result

**Expected behavior**
return related case info

**Environment (please complete the following information):**
 - OS: [win11]
 - n8n Version [0.174.0]
 - Node.js Version [not sure]
 - Database system [default]
 - Operation mode [own]
 - the hive version[4.1.18-1]

**Additional context**
the hive API: think N8N should pass the second value as "True" which filled by the frontend.

![image](https://user-images.githubusercontent.com/43668597/171314851-7fe2617f-2fe6-443e-975e-c497ff0fc51f.png)

![image](https://user-images.githubusercontent.com/43668597/171314396-63abd7dc-ed3a-4fd4-96db-926df8f99701.png)
![image](https://user-images.githubusercontent.com/43668597/171314424-797b4ab7-864d-4c19-b11b-e2135a0aa9b8.png)

**Comment by Joffcom** [comment]
Hey @heywiorld,

It looks like the notification didn't get triggered, This was fixed with n8n@0.200.0
