### ISSUE TITLE
Development setup instructions do not work on Windows using PowerShell

### ISSUE THREAD

**Issue by simshaun** [n8n-io/n8n#3423]
**Describe the bug**
Following the instructions on https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md, when running `npm run dev`, I noticed this error fly by in the console as it was doing its thing:
![image](https://user-images.githubusercontent.com/379519/171599553-21f0020b-24e6-453f-a446-63123c1b157f.png)

This is happening because of the `start:windows` script in `packages/cli/package.json`. To make it work in both PowerShell and CMD, instead of `cd bin && n8n`, it should be `cd bin && .\\n8n` (Double backslash for escaping within package.json)

**To Reproduce**
1. Using PowerShell, clone the repo and follow the instructions down to `npm run dev`.
2. Pay attention to the console to see the error. (It goes by quickly and disappears, so PrtScrn may be necessary to catch it.)
3. Try opening http://localhost:8080/ and see the Error connecting to n8n error. 
![image](https://user-images.githubusercontent.com/379519/171600004-1b958fa7-3823-4d6b-aaef-0d659ffe14d7.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version 0.179.0
 - Node.js 16.13.1
 - Database system: SQLite
 - Operation mode: own

**Additional context**

**Comment by Joffcom** [comment]
Hey @simshaun,

I am going to close this issue as you have put in a PR for this, I will make sure we get to the PR soon as well as this has been open for a while now and it seems like such a simple change.
