### ISSUE TITLE
There is no security with N8N_BASIC_AUTH

### ISSUE THREAD

**Issue by jani123** [n8n-io/n8n#345]
**Describe the bug**

When N8N_BASIC_AUTH security functionality is in use, the UI it self gives unauthorized when not authenticated, but the rest-endpoint still serves data for everyone.

**To Reproduce**

1. Start the n8n `docker run -it --rm --env N8N_BASIC_AUTH_ACTIVE=true --env N8N_BASIC_AUTH_USER=user --env N8N_BASIC_AUTH_PASSWORD=password -p 5678:5678 n8nio/n8n`
2. `curl -v "http://localhost:5678/"` gives `HTTP/1.1 401 Unauthorized` as expected
3. `curl -v "http://localhost:5678/rest/credentials"` gives `HTTP/1.1 200 OK` but `HTTP/1.1 401 Unauthorized` was expected

**Expected behavior**

User should not be able to fetch credentials or any other details. You can also fetch workflows same way as credentials.

**Environment (please complete the following information):**

 - OS: Linux Mint 18.2 Sonya
 - Docker version 19.03.6, build 369ce74a3c
 - n8n Version 0.54.0
 - Docker image version: latest
 - Node.js Version: 6.12.0

**Additional context**

Results for `http://localhost:5678/`:
```
➜  ~ curl -v "http://localhost:5678/"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5678 (#0)
> GET / HTTP/1.1
> Host: localhost:5678
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< X-Powered-By: Express
< WWW-Authenticate: Basic realm="n8n - Editor UI"
< Date: Sun, 01 Mar 2020 08:00:31 GMT
< Connection: keep-alive
< Content-Length: 26
```

Results for `http://localhost:5678/rest/credentials`
```
➜  ~ curl -v "http://localhost:5678/rest/credentials"
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 5678 (#0)
> GET /rest/credentials HTTP/1.1
> Host: localhost:5678
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: http://localhost:8080
< Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, sessionid
< Content-Type: application/json; charset=utf-8
< Content-Length: 11
< ETag: W/"b-EFAlOux7Kcr/ZEgGkn2r+oFAbu4"
< Vary: Accept-Encoding
< Date: Sun, 01 Mar 2020 08:10:50 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"data":[]}% 
```

**The problem scope**

I'm very interested taking this into production use for us. But I cannot since public access is needed for webhooks and while doing that I give permission for everyone to fetch or do anything. Is there some some proper way to harden this for production usage? I have not gotten very far on configuring/testing N8N yet but is there way to only expose webhooks interface? Does webhooks have anykind of authorization scheme?

**Comment by janober** [comment]
Thanks a lot @jani123! Yes, that should definitely not be the case! Only the webhook-endpoints and /healthz should work without authentication. Else it really does not make any sense.  I will check it out.

**Comment by jani123** [comment]
That would be great :) Thank you!

**Comment by janober** [comment]
Just released n8n@0.55.0

Nothing to thank for. This case is actually one of the worst one I could have imagined. Not the slightest idea why the rest API path was excluded. It does absolutely not make any sense for me right now.

It is available via npm and Docker.

For me, it works correctly now. Please check and confirm also. Thanks a lot!

**Comment by janober** [comment]
Did share information about security fix via Twitter and LinkedIn. I also posted in the forum and did send emails to all newsletter recipients. So hope that everybody that uses n8n should now be aware of the issue and the fix.

**Comment by jani123** [comment]
Let's hope so everyone sees the information. I tested and it works now as expected. And big plus for acting fast on this, I bet everyone appreciates it. I'll close this issue and will continue working on this next week, will be reporting if more problems are found :).

**Comment by janober** [comment]
Thank you very much @jani123 for your help! Is very appreciated!
