### ISSUE TITLE
Attempt to read execution was blocked due to insufficient permissions...

### ISSUE THREAD

**Issue by ebecaf** [n8n-io/n8n#3469]
**Describe the bug**
My executions - when executed manually - keep being blocked.

**To Reproduce**
1. setup n8n 164+ on Postgre 14+ (wait a few days)
2. Create a HTTP GET node (which is what I did) or something like Google Drive that retrieves information.
3. Manually execute
4. Wait... (and wait and wait...)

_note; the HTTP GET node I used is a simple API retrieval, it works in Postman without issue_

**Expected behavior**
Workflow should execute

**Environment (please complete the following information):**
 - OS: Ubuntu 18 (Also tried Ubuntu 22)
 - n8n Version: tried 164,167,178,179
 - Node.js Version: v8.10.0
 - Database system Postgre 14
 - Operation mode: own
 
**Additional context**

I have tried different servers, different domains, different Ubuntu versions, and different n8n versions.
It always comes back to this, and I don't understand.
Okay, so I use CapRover (it handles NGINX and SSL) to create the Docker Image, but I did that last year and it worked for months without out issue.
The ENVs are as standard, I haven't added anything unusual. 
The strangest thing is that the new server (ubuntu 18) worked for a few days, then it stopped finishing executions and just keeps spinning. Please note; executions WILL run if not executed manually. I can't fathom why it's doing this. Please see two sets of logs below.

`{"executionId":"22","sessionId":"o1bi7ob6ik","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"workflowExecuteAfter"}
debug | Save execution progress to database for execution ID 22 {"executionId":"22","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"workflowExecuteAfter"}
debug | Send data of type "executionFinished" to editor-UI {"dataType":"executionFinished","sessionId":"o1bi7ob6ik","file":"Push.js","function":"send"}
debug | Wait tracker querying database for waiting executions {"file":"WaitTracker.js","function":"getwaitingExecutions"}
ERROR RESPONSE
ResponseError: Execution not found
at /usr/local/lib/node_modules/n8n/dist/src/Server.js:1566:23
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /usr/local/lib/node_modules/n8n/dist/src/ResponseHelper.js:90:26 {
httpStatusCode: 404
}
info | Attempt to read execution was blocked due to insufficient permissions {"userId":"1234-MY-USER-ID","executionId":"22","file":"Server.js"}`

`{"executionId":"23","sessionId":"sxs22w71ja","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"nodeExecuteAfter"}
verbose | Workflow execution finished successfully {"workflowId":"1","file":"WorkflowExecute.js","function":"processSuccessExecution"}
debug | Send data of type "nodeExecuteAfter" to editor-UI {"dataType":"nodeExecuteAfter","sessionId":"sxs22w71ja","file":"Push.js","function":"send"}
debug | Received child process message of type processHook for execution ID 23. {"executionId":"23","file":"WorkflowRunner.js"}
debug | Executing hook (hookFunctionsSave) {"executionId":"23","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"workflowExecuteAfter"}
debug | Received child process message of type end for execution ID 23. {"executionId":"23","file":"WorkflowRunner.js"}
debug | Executing hook (hookFunctionsPush) {"executionId":"23","sessionId":"sxs22w71ja","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"workflowExecuteAfter"}
debug | Save execution progress to database for execution ID 23 {"executionId":"23","workflowId":"1","file":"WorkflowExecuteAdditionalData.js","function":"workflowExecuteAfter"}
debug | Send data of type "executionFinished" to editor-UI {"dataType":"executionFinished","sessionId":"sxs22w71ja","file":"Push.js","function":"send"}`

At this point I stoppted the workflow as it was just spinning...

`debug | Wait tracker querying database for waiting executions {"file":"WaitTracker.js","function":"getwaitingExecutions"}
ERROR RESPONSE
ResponseError: Execution not found
at /usr/local/lib/node_modules/n8n/dist/src/Server.js:1566:23
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /usr/local/lib/node_modules/n8n/dist/src/ResponseHelper.js:90:26 {
httpStatusCode: 404
}
info | Attempt to read execution was blocked due to insufficient permissions {"userId":"1234-MY-USER-ID","executionId":"23","file":"Server.js"}
debug | Wait tracker querying database for waiting executions {"file":"WaitTracker.js","function":"getwaitingExecutions"}`

**Comment by Mehdi-YC** [comment]
this happens to me too , i struggeled for like 2 days t find out it was nginx , pls any solution ?

**Comment by Joffcom** [comment]
Hey @ketansp and @Mehdi-YC,

What does your nginx config look like? Back when I was using nginx as a reverse proxy my config looked like this...

```
server {
  listen 443 ssl;
  server_name n8n.my_domain.tld;
  location / {
    proxy_pass http://127.0.0.1:5678;
    proxy_set_header Connection '';
    proxy_http_version 1.1;
    chunked_transfer_encoding off;
    proxy_buffering off;
    proxy_cache off;
  }
  ssl_certificate # removed
  ssl_certificate_key # removed
}
```

**Comment by Mehdi-YC** [comment]
same , i have almost the same config ,  what i did now , is that i used the sub domain to connect to some OAuth2 services , and i use the ip to run workflow

**Comment by Joffcom** [comment]
@Mehdi-YC when you say almost the same config what is different with yours? I set up another instance over the weekend just to test the config and all appears to be working so it would be interesting to know what config you are using for nginx.

**Comment by Mehdi-YC** [comment]
ok i will send it once im in the office

**Comment by Mehdi-YC** [comment]
@Joffcom here is my config 
`
...
        location / {
                proxy_set_header Host $host;
                proxy_pass http://xx.xxx.xxx.xxx:5689;
                proxy_redirect off;
                chunked_transfer_encoding off;
                proxy_buffering off;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_cache_bypass $http_upgrade;
                proxy_http_version 1.1;

        }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/n8n.smsima.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/n8n.smsima.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

`

**Comment by Joffcom** [comment]
@Mehdi-YC I would start by removing some of the options so you match what I use and from there add parts in to see at what stage it stops

If I had to take a guess I would say it could be the Host header or the cache bypass causing the issue.

**Comment by Mehdi-YC** [comment]
@Joffcom , well that actually worked , i think the problem was  proxy_set_header Host $host; maybe we can close this issue

**Comment by Joffcom** [comment]
Hey @Mehdi-YC,

I guess that depends on @ketansp and @ebecaf, What I will do is keep it open until Friday to allow some response time then close it off.

**Comment by ketansp** [comment]
My nginx config looks like this
```
server {
    listen 443 ssl;
    server_name abc.example.com;

    ssl_certificate     /etc/letsencrypt/live/abc.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/abc.example.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass http://localhost:5678;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

Unfortunately removing `proxy_set_header Host $host;` did no difference to this issue.

**Comment by ketansp** [comment]
@Joffcom adding the two options in my nginx config solved the problem. Now my nginx config looks like
```
server {
    listen 443 ssl;
    server_name abc.example.com;

    ssl_certificate     /etc/letsencrypt/live/abc.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/abc.example.com/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

    location / {
        proxy_pass http://localhost:5678;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        #proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_cache off;
     }
}
```

**Comment by Joffcom** [comment]
Perfect thanks for the update @ketansp, Just @ebecaf to go 😃

**Comment by ebecaf** [comment]
I will test this out using what is posted above and report back, but I'm not 100% sure my nginx _is_ behind a proxy, because honestly I don't have much experience with nginx as a whole.

_Having said that some executions appear to have started working since I updated to 0.185.0_

**Comment by Joffcom** [comment]
Hey @ebecaf,

It isn't that nginx is behind a proxy it is more that nginx is being as a reverse proxy and is just missing a small config option.

The quickest way to check if it is nginx is to connect directly to the IP and port for n8n to see if that changes anything.

**Comment by ocedric** [comment]
Deactivating buffering worked for me:
`proxy_buffering off;`

Or in OPNSense: Services > Nginx > Configuration > HTTP(S) tab > Locations > Edit your location > Advanced mode > untick both "Response Buffering" and "Request Buffering"

**Comment by Igcorreia** [comment]
Worked for me, in Plesk Server, edit Nginx domain settings: 
```
proxy_buffering off;
proxy_cache off;
```

**Comment by Igcorreia** [comment]
My suggestion above does not work anymore on version 1+ I had to change from Websocket to SSE
