### ISSUE TITLE
Google Drive OAuth2 creds are switched to Service Account when sharing a folder

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#3473]
**Describe the bug**
Swithes to Service account auth instead of OAuth2

**To Reproduce**
1. Go to Google Drive and select an OAuth2 cres
2. Click on Folder -> Share
3. Choose any role, e.g. Reader
4. See error - the OAuth2 creds are switched to Service account

Before:
![image](https://user-images.githubusercontent.com/20184727/172182856-a01a1436-a8fd-4a34-91d9-1e8e19a43987.png)

After
![image](https://user-images.githubusercontent.com/20184727/172183257-e543a213-86e7-473f-8cd8-778b145e3aeb.png)

**Expected behavior**
Choosing a sharing role.

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version  0.179.0

**Comment by Joffcom** [comment]
Hey @artemdzyuba,

Bit of a delay on this one but this should now be fixed, Can you give it a go on the latest release and if you still have the issue let me know and we can open this again.

We have also updated the node so you won't need to mess around with finding the folder id you can just select it from a list.

**Comment by artemdzyuba** [comment]
@Joffcom Checked. The issues has gone, thank you.
