### ISSUE TITLE
TheHive create observable do not switch next binary item

### ISSUE THREAD

**Issue by dream91** [n8n-io/n8n#3482]
**Describe the bug**
TheHive node doesn't switch next binary item on observable create. When I have more than 1 item then it always use data from 1st item and cause error in Thehive.

Error on TheHive
```
Exception raised, rollback (Observable already exists)
```
Error on N8n
```
ERROR: Forbidden - perhaps check your credentials?
Operation not permitted
```

**To Reproduce**
1. Send multiple binary files to TheHive node
2. Using binary data from 1st point try create new file observables in existing case

**Expected behavior**
N8n should create multiple file observables. Now create only first and raise the error on 2nd item.

**Environment (please complete the following information):**
 - n8n Version 0.165.1

**Additional context**
I tested with 3 files. When I write those files using Write Binary File node then it wrote all files without error.
![image](https://user-images.githubusercontent.com/5249896/172590389-a7e8cb74-a85e-4297-8ef7-aa18ef1d4191.png)
![image](https://user-images.githubusercontent.com/5249896/172590284-e75eac20-3dbf-417a-a7fe-18c171677de6.png)

**Comment by michael-radency** [comment]
Hello @dream91 can you please share workflow that causes issue? For me it's working correctly:

![image](https://user-images.githubusercontent.com/88898367/177934352-3fca9ab9-94d0-4ea3-b50a-15f2b5a7b96f.png)
![image](https://user-images.githubusercontent.com/88898367/177934432-c4d86f87-2b04-4234-85b0-530123b74cb5.png)

and when I try to add same files to case only then I'm getting error
![image](https://user-images.githubusercontent.com/88898367/177934690-823854c3-45f9-41dd-98f0-ef646a810146.png)

**Comment by dream91** [comment]
Hello @michael-radency,
today I was building other simmilar workflow and I noticed that I made wrong data structude in this case. I just opened github to write about that and noticed you aready tested this issue. Sorry for this false issue report. Lets close this issue.
