### ISSUE TITLE
import/export via cli would cause duplicate key error

### ISSUE THREAD

**Issue by rfehling-mittwald** [n8n-io/n8n#3483]
**Describe the bug**
!n8n 0.180.0 Tag Change!
Importing via cli will cause duplicate key error when the n:m entries in **workflows_tags** already exists.

```
n8n import:workflow --separate --input=./assets/processes/
An error occurred while exporting workflows. See log messages for details.
duplicate key value violates unique constraint "PK_a60448a90e51a114e95e2a1[25]([...])b3"
```
```
public.workflows_tags
Indexes:
    "PK_a60448a90e51a114e95e2a125b3" PRIMARY KEY, btree ("workflowId", "tagId")
```

**To Reproduce**
1. Export any workflow with some tags
2. Import the workflow via cli

**Expected behavior**
If you import workflow "1231231", the **workflows_tags** should delete all tag entries of this workflow before inserting new ones.
`DELETE FROM workflows_tags WHERE "workflowId" = 1231231;`

**Environment (please complete the following information):**
 - n8n Version 0.180.0
 - Node.js Version 14
 - Database system: Postgre

**Comment by rfehling-mittwald** [comment]
Old code: findOrCreateTag()
https://github.com/n8n-io/n8n/pull/2653/files#diff-7a9afdbd0b6bffb89d9ef91af2d73b8cbfd49172c1315acc3482fa41cc0cadb2R47

New code:  recude() ?
https://github.com/n8n-io/n8n/pull/3130/files#diff-6a6f60dc8916cd15c2d6b97e6503796d04304b6df22a0dd72efdb4b054a55595R1310

**Comment by rfehling-mittwald** [comment]
Missing remove already existing tags in list?
https://github.com/n8n-io/n8n/pull/2653/files#diff-6a6f60dc8916cd15c2d6b97e6503796d04304b6df22a0dd72efdb4b054a55595R1226

**Comment by rfehling-mittwald** [comment]
addWorkflowTagIds
[[...new Set([...(state.workflow.tags || []), ...tags])]](https://github.com/n8n-io/n8n/pull/3130/files#diff-6a6f60dc8916cd15c2d6b97e6503796d04304b6df22a0dd72efdb4b054a55595R1310)

const currentTags = ["tag1", "tag2", "tag3"];
const newTags = ["tag2", "tag3", "tag4"];
console.log([...new Set([...(currentTags|| []), ...newTags])]));

Will return ["tag1", "tag2", "tag3", "tag4"] 
not the expected result of newTags!

**Comment by wifiuk** [comment]
i also get this error when importing a flow

**Comment by ivov** [comment]
@rfehling-mittwald @wifiuk Thank you for your report.

Unable to reproduce. Tested exporting my current workflows, deleting them from PG and re-importing them. Also tested setting up a fresh PG, creating a new workflow with tags, exporting and re-importing.

Can you please provide more detailed steps to reproduce?

**Comment by rfehling-mittwald** [comment]
I tried three testcases, all worked:

- docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n n8nio/n8n
- docker-compose with postgres with version 14
- docker-compose with postgres with version 10

I guess I have to debug in our current prod system :/
Please let this issue alive, I want to give informations when I may find the solution.
