### ISSUE TITLE
merge node is broken on v 0.180

### ISSUE THREAD

**Issue by draglabs** [n8n-io/n8n#3485]
**Describe the bug**

**To Reproduce**
1. Go to '...' this forum post 
https://community.n8n.io/t/error-in-workflow-cannot-set-properties-of-undefined-setting-merge/14701
2. Use the merge node, and opt for the pass through functionality. 
3. Attempt to use this node in a way where you may need to wait for one branch to complete before moving on. 

**Expected behavior**
The pass through will behave similar to the wait behavior waiting for all prior tasks to be complete before running. 

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 20.x]
 - n8n Version [e.g. 0.180.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. postgresql; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own, `main` `]

**Additional context**
This is drectly related to the update reverting to v 0.179 fixes the problem

**Comment by nivb06** [comment]
Thanks for reporting the issue @draglabs, this was fixed with 0.181.1
