### ISSUE TITLE
TheHive update custom field bugs

### ISSUE THREAD

**Issue by dream91** [n8n-io/n8n#3488]
**Describe the bug**
I am testing Case's Custom Fields update on TheHive node.

I noticed two bugs:
1. when new CF is added then all other CFs disappear (looks like N8n TheHive node overwrite them)
2. when CF is an integer then the CF is not passed correctly (in results I see variable as null)

**To Reproduce**
Steps to reproduce the behavior 1:
1. Create TheHive case with some custom field
2. Update TheHive case - try add new custom field
3. When N8n node is executed then CF from step 1 disappear. We see only CF from 2nd step.

Steps to reproduce the behavior 2:
1. Create TheHive case with custom field which is an integer
2. Update TheHive case - try add custom field from step 1. with integer value. (I treid use an expression `{{$executionId}}`)
3. After execution in TheHive update node I see this CF as null.
![image](https://user-images.githubusercontent.com/5249896/172848391-f0cb9454-6037-4c5f-9bf5-2c4d04979daa.png)

**Expected behavior**
Bug 1. New CF is added and old CF are not deleted.
Bug 2. CF with an integer is added correctly.

**Environment (please complete the following information):**
 - n8n Version 0.165.1

**Comment by Joffcom** [comment]
Hey @dream91,

It looks like the notification didn't get triggered, This was fixed with n8n@0.200.0
