### ISSUE TITLE
404 when open the hive trigger webhook URL

### ISSUE THREAD

**Issue by heywiorld** [n8n-io/n8n#3492]
**Describe the bug**
when open the hive trigger webhook URL, it return error, even click workflow.

**To Reproduce**
1. Go to add 'the hive trigger' using docker N8N
2. Copy the webhook url and open in the browser
3. You will see error such as "{"code":404,"message":"The requested webhook \"GET 7352a0a1-1114-4b23-885d-558e191498d0/webhook\" is not registered.","hint":"Click the 'Execute workflow' button on the canvas, then try again. (In test mode, the webhook only works for one call after you click this button)","stack":"ResponseError: The requested webhook \"GET 7352a0a1-1114-4b23-885d-558e191498d0/webhook\" is not registered.\n    at TestWebhooks.callTestWebhook (/usr/local/lib/node_modules/n8n/dist/src/TestWebhooks.js:25:23)\n    at /usr/local/lib/node_modules/n8n/dist/src/Server.js:1664:52\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:144:13)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:138:14)\n    at Route.dispatch (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/route.js:114:3)\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:284:15\n    at param (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:365:14)\n    at param (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:421:3)\n    at next (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:280:10)\n    at /usr/local/lib/node_modules/n8n/dist/src/UserManagement/routes/index.js:126:9\n    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:328:13)\n    at /usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/index.js:346:12)"}"
4. When you click the 'Execute workflow' button, and open the webhook url again, it's still same error

**Expected behavior**
it should return right info

**Environment (please complete the following information):**
 - OS: [centos 7]
 - n8n Version [0.177.0]
 - Node.js Version [docker N8N]
 - Database system [default]
 - Operation mode [`own`]

**Additional context**
Error PIC:
![image](https://user-images.githubusercontent.com/43668597/172997393-9b1c38e4-31e7-427e-94a1-34ad43dfa2be.png)

**Comment by janober** [comment]
The Hive Webhook URL uses POST:
![Screenshot from 2022-06-10 07-58-23](https://user-images.githubusercontent.com/6249596/173000297-5d240ff1-273e-4a7d-bbbb-f17ff5be1476.png)
and you are making a GET request. For that reason is it not known. If you make a POST request it will work fine.
