### ISSUE TITLE
Cortex node doesn't return any data when execute analyzer on File observable

### ISSUE THREAD

**Issue by dream91** [n8n-io/n8n#3500]
**Describe the bug**
Cortex node doesn't return any data when executing new analyzer job with binary item.

**To Reproduce**
1. Create Cortex node
Resource: Analyzer
Operation: Execute
Analyzer: EmlParser_2_0 (or any other File analyzer)
Observable Type: File
Binary Property: Set some binary property
2. Run Workflow
3. It doesn't return any data

![image](https://user-images.githubusercontent.com/5249896/177321695-174178e9-2ff3-4a2c-a8a8-bdd838e1bca1.png)

But the job was sent to Cortex.

![image](https://user-images.githubusercontent.com/5249896/177321758-06866e8a-66be-4960-a496-639bb8cfa0e6.png)

**Expected behavior**
It should return at least id of executed job.

**Environment (please complete the following information):**
 - n8n Version 0.165.1

Update 02.01.2023: Tested on 0.209.3 and the problem still exists.

**My workflow**
![image](https://user-images.githubusercontent.com/5249896/177322720-2c953a75-369d-47b2-89e6-5683b7fa9b0c.png)

**Comment by dream91** [comment]
I noticed that on older N8n version it return some data. I have to repeat the scenario, maybe it was an issue on my environment.

**Comment by dream91** [comment]
Checked again - that works. Closing - false issue

**Comment by dream91** [comment]
Updated issue

I checked the issue again and noticed that the problem appear only when I use binary item in Cortex (Observable type: file). I updated issue description.

**Comment by dream91** [comment]
I found a community post showing the same problem.

https://community.n8n.io/t/some-cortex-nodes-are-not-running-jobs/6015/6

**Comment by Joffcom** [comment]
Hey @dream91,

Just to add internally we are tracking this as `NODE-181`, I have just given it a go and I am currently getting an error rather than a response not sure if that is just down to my setup but both things should be fixed soon.

**Comment by chrimuel-tubs** [comment]
Any updates? Its been over a year without any news.

**Comment by Joffcom** [comment]
👋🏻 sorry for the delay on this one, I am going through some older issues at the moment and have just put in a PR to fix this which once reviewed should be available in the next release.

**Comment by janober** [comment]
Fix got released with [`n8n@1.42.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.42.0)
