### ISSUE TITLE
Shopify Trigger integration doesn't work

### ISSUE THREAD

**Issue by Vultik** [n8n-io/n8n#3516]
**Describe the bug**
The Shopify trigger using webhook doesn't work anymore since Shopify change the private app configuration.

**To Reproduce**
1. Use the Shopify trigger node, with for example the topic "customer created"
2. Create a new customer on Shopify
3. The webhook is not triggered 
![image](https://user-images.githubusercontent.com/55872753/173753520-85cec898-2a59-4f94-8f43-6d9ee80461e1.png)

Note that i receive a lot of mail from shopify warning the webhook doesn't work :
![image](https://user-images.githubusercontent.com/55872753/173753712-ef0f4592-f29e-4f30-8ea0-5cd43d7ec92c.png)

The other Shopify node works great though so it's not related to credentials.

**Expected behavior**
The node should be triggered when some data are updated on Shopify using webhook

**Environment (please complete the following information):**
 - n8n cloud version

**Additional context**
It's the same issue discribed here #3295

**Comment by Joffcom** [comment]
Hey @Vultik,

Thanks for the report, As you have noticed this is the same as #3295 so for now I will close this one so that we don't have duplicate issues.

Let me know if you have any questions.
