### ISSUE TITLE
httpRequest with `URLSearchParams` body does not work anymore

### ISSUE THREAD

**Issue by d3rwan** [n8n-io/n8n#3540]
**Describe the bug**
httpRequest with `URLSearchParams` body does not work anymore, axios sent an empty body instead. 

I think it's due to this recent https://github.com/n8n-io/n8n/blob/master/packages/core/src/NodeExecuteFunctions.ts#L720 

**To Reproduce**
1. Create a HTTP request options (axios) with a `URLSearchParams` object in the body 
2. Call `this.helpers.httpRequest` with this options
3. The sent body is empty

**Expected behavior**
As before, the body should not be empty in this case

**Environment (please complete the following information):**
 - OS : MacOS & Docker
 - n8n Version :0.182.1
 - Node.js Version : v16.15.0
 - Database system : PostgresSQL
 - Operation mode : own

**Additional context**

**Comment by Joffcom** [comment]
Hey @d3rwan,

Do you have an example workflow that reproduces this?

**Comment by d3rwan** [comment]
Let's imagine you create a new custom node, in which you will use `httpRequest` with `URLSearchParams`

```
import { IExecuteFunctions } from "n8n-core";
import {
  IHttpRequestOptions,
  INodeExecutionData,
  INodeType,
  INodeTypeDescription,
} from "n8n-workflow";

export class ErrorHttpRequest implements INodeType {
  description: INodeTypeDescription = {
    displayName: "ErrorHttpRequest",
    name: "hrrorHttpRequest",
    group: ["transform"],
    version: 1,
    description: "Reproduce issue 3540 (n8n-io/n8n)",
    defaults: {
      name: "ErrorHttpRequest",
    },
    inputs: ["main"],
    outputs: ["main"],
    credentials: [],
    properties: [],
  };

  async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
    const outputItems: INodeExecutionData[] = [];

    const params = new URLSearchParams();
    params.append("grant_type", "client_credentials");

    const optionsPost: IHttpRequestOptions = {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params,
      url: `https://webhook.site/90858178-cadd-4a85-9615-255954d7d017`,
      encoding: "json",
    };

    const response = await this.helpers.httpRequest(optionsPost);

    outputItems.push({ json: { response } });
    return this.prepareOutputData(outputItems);
  }
}

```

In previous versions, (for example 0.177.0), URLSearchParams are added into the body and sent to the target server (cf. https://webhook.site/#!/90858178-cadd-4a85-9615-255954d7d017/83dbac2d-d688-434e-b651-f685f26913f7/1 used in my test for example)

```
docker run -it --rm --name n8n -p 5678:5678 -v "$(pwd)"/dist/nodes/ErrorHttpRequest:/home/node/.n8n/custom n8nio/n8n:0.177.0
```

But with last version, the sent body is empty (cf. https://webhook.site/#!/90858178-cadd-4a85-9615-255954d7d017/bc898a27-34d6-45c7-be6a-6bd41ed469ba/1 used in my test) 

```
docker run -it --rm --name n8n -p 5678:5678 -v "$(pwd)"/dist/nodes/ErrorHttpRequest:/home/node/.n8n/custom n8nio/n8n:0.182.1
```

**Comment by Joffcom** [comment]
An ok so this is custom node related and not a workflow issue with the HTTP Request node.

I will take a look at this one later. I had maybe incorrectly assumed when trying to test in the node earlier that `urlsearchparams` was only for the url query and not the body of a post request.

**Comment by d3rwan** [comment]
> An ok so this is custom node related and not a workflow issue with the HTTP Request node.

Yes, sorry if it was not clear in the initial issue 🙏

**Comment by netroy** [comment]
@d3rwan [this](https://github.com/n8n-io/n8n/pull/3567) should fix the issue
