### ISSUE TITLE
Zulip Node: Attachments / Uploads not working as expected

### ISSUE THREAD

**Issue by cmprmsd** [n8n-io/n8n#3579]
@RicardoE105 
Thank you for the Zulip integration in https://github.com/n8n-io/n8n/pull/330. I'm trying to upload files to the server and send it to some user or stream. However, this functionality does not work as expected.

I can upload binary data and get back an URL from Zulip. However, it seems only the bot would have access to this file as it's the uploader. When I copy the link and try to open it in my user session, it will just tell me that I am not authorized to see this file. 
`You are not authorized to view this file.`

I could add a second Zulip node that sends me the message with the upload-URL (from the bot). But this does not lead to the file being shared with me. 

May I suggest to implement attachments as part of the message functionality?
Something like a "Attach file to message" button with binary data object as it is now in the upload functionality.
I invested some time in the Taiga node and learned that I have no idea of implementing such stuff so hopefully you'll find some time. :see_no_evil: 

Thanks in advance! 

If I'm missing how the feature should work correctly, maybe it could be described in the documentation of the node. 

**Environment (please complete the following information):**
 - OS: Alpine
 - n8n Version: 0.182.1 

**Additional context**
I have some output file in this case an mp4 file, that I'd like to send to chat as upload. In Zulip it would be displayed as viewable video.

**Comment by cmprmsd** [comment]
I had a look and the Zulip API returns a relative local path to the file, which then could be linked in a message in order to give access permissions to other users or streams.

Your integration currently adds the host URL (authority) in front of the path in the response.
As the integration adds `https://host.name/` and the path is already an absolute path `/user_uploads/xyz/file.jpg` the result is `https://host.name//user_uploads/xyz/file.jpg` with two slashes, which will not be matched by Zulip as internal shared resource. 

This has the effect that the file permissions are not updated properly.

**Comment by Joffcom** [comment]
Hey @cmprmsd,

Sorry for the delay on this one, Looking at this one it looks like we add the URL from the credential in front of the returned URI.

I have just given it a test and as a quick fix removing the trailing slash from the URL in the credential appears to provide a workaround.

Internally we are tracking this one as `NODE-183`.

**Comment by cmprmsd** [comment]
Yup that was causing the issue as described. 
Great. Thank you :)

**Comment by Joffcom** [comment]
No problem @cmprmsd, As this is a fairly quick fix I am planning to do it at the same time as a few other quick ones.

**Comment by Joffcom** [comment]
Hey @cmprmsd,

I have just popped in a PR for this one, Once reviewed and merged it will be in a future release (possibly `0.223.0` or `0.224.0`)

**Comment by janober** [comment]
Fix got released with [`n8n@0.234.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.0)
