### ISSUE TITLE
Cortex node doesn't return all analyzers

### ISSUE THREAD

**Issue by dream91** [n8n-io/n8n#3586]
**Describe the bug**
I have configured 31 analyzers and Cortex node doesn't return all on Analyzer Type field.
I noticed that analyzers are get by POST `/analyzer/_search`.
Analyzers should be get by POST `/analyzer/_search?range=all`. This return all enabled analyzers.

**To Reproduce**
1. Configure more than 15 analyzers in Cortex
2. Create Cortex node
Resource: Analyzer
Operation: Execute
4. Check how much analyzers do you have in Analyzer Type selector.

**Expected behavior**
All enabled analyzers are returned by Cortex node.

**Environment (please complete the following information):**
 - n8n Version 0.165.1

**Additional context**
It should be fixed by replacing
Cortex.node.ts:114
```
`/analyzer/_search`
````
to 
```
`/analyzer/_search?range=all`
```
or via GET `/analyzer?range=all`

**Comment by Joffcom** [comment]
Hey @dream91,

Thanks for reporting this one, I have just popped in a PR to resolve it.

**Comment by janober** [comment]
Fix got released with `n8n@0.184.0`
