### ISSUE TITLE
FileMaker Node: API calls need to logout after execution

### ISSUE THREAD

**Issue by stathisaska** [n8n-io/n8n#3593]
**Describe the bug**
When using FileMaker Data API, it is a good practice to logout after each API call. Otherwise FileMaker server will get bloated with open sessions and crash. An alternative would be to handle the token, but handling it would require unneeded effort. After testing FileMaker node with n8n, I found out that n8n opens new session for each call made, which is a critical issue for FileMaker servers.

**To Reproduce**
Add the FileMaker node and execute any action

**Expected behavior**
After execution, a maximum of 1 open session are left on the FileMaker server

**Actual behavior**
After execution, at least 3 sessions are open, I assume it's because n8n FileMaker node is querying FileMaker to auto populate layouts and fields -which is awesome btw-

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - n8n Version 0.183.0
 - Node.js Version -Docker-
 - Database system SQLite
 - Operation mode own

**Additional context**
I assume that (almost) API call starts with a login

POST https://{{server}}/fmi/data/vLatest/databases/{{file}}/sessions

then every API call should end with a logout 

DELETE https://{{server}}/fmi/data/vLatest/databases/{{file}}/sessions/{{token}}

vLatest could be substituted with either v1 or v2

**After reviewing the code, there is the logout function, so it just needs to be used after every call - not just to reset values**

**Comment by Joffcom** [comment]
Hey @stathisaska,

I forgot to mark this one as closed last year, As it is more of a feature change than a bug it will need to go through our normal prioritisation process.

If you fancied it we would of course always be happy with a PR to make the change, If you feel this is a bug however let me know and we can reopen this.

**Comment by stathisaska** [comment]
Hey @Joffcom 

This issue is preventing almost all FileMaker developers from using the FileMaker node unfortunately. It would only be usable if you knew that the workflow will only run once and only every now and then. FileMaker server will spike its CPU when a lot of sessions are open, so for the time being I am manually integrating with the FileMaker Data API using HTTP requests.

I fancy it, but my development skills are constrained to FileMaker, so am not fluent enough to do it. 🤠

**Comment by Joffcom** [comment]
Hey @stathisaska,

That is a bit unexpected, I know there are a few users on our support forum that use the Filemaker node fairly heavily but have not yet reported this one.

It is one of those tricky things where it feels right to implement it but at the same time the node is not broken, What I can do is if I find some time I can pop in the logout request and give you a custom docker image you can test with as I don't have a FileMaker server handy.

**Comment by stathisaska** [comment]
Hi @Joffcom 

That would be great, I have a test development environment for you to use. Drop me an e-mail at sa@pineapple.gr to set you up.

Thanks
