### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by markusobi0** [n8n-io/n8n#36]
I tried to setup N8N behind a Reverse Proxy (Nginx) it worked, but the Control Panel said it hadn't connection to the Internet. I used also the `--tunnel` option of the docker image. How about adding this possibility for securing the Panel with SSL through Let'sEncrypt?

**Comment by janober** [comment]
What you described should work. But I just checked and it seems like there is some documentation missing. Very sorry about that. Will try to add it asap.

For now make sure to set the following environment variables that everything knows how to connect:
```
N8N_HOST="example.com"
N8N_PROTOCOL="https"
N8N_PORT="443"
VUE_APP_URL_BASE_API="https://example.com/"
WEBHOOK_TUNNEL_URL="https://example.com/"
```

**Comment by markusobi0** [comment]
Now I'm slightly confused. How should I configure Nginx then, when n8n already blocks Port 443?

**Comment by janober** [comment]
Yes that is correct. You then just have to remove the "--tunnel" and it should display you the correct URLs in the nodes.

**Comment by markusobi0** [comment]
No, it doesn't. Now is the Tunnl URL Section completly gone and on the Panel is the "Connection Lost back"

**Comment by janober** [comment]
Yes,, the tunnel-section on startup gets only displayed when the n8n tunnel gets used. 

What do you mean with "Connection Lost"? In the top right corner of the page? That informs about if the connection via EventSource is established to display updates about what is currently executing. So it is not webhook related. You can check in the Console or Network-Pane to see to where it tries to connect. Maybe that helps you.

Does it display the connection issue from the start or after a while?

**Comment by markusobi0** [comment]
From the Start

**Comment by janober** [comment]
And the where does the "Connection Lost" get displayed? In the top right corner or do you mean something else?

**Comment by markusobi0** [comment]
In the top right corner.
https://imgur.com/Gv4JFRp

**Comment by cadecairos** [comment]
Shot in the dark here, but are you seeing this error on Firefox? 

I think this is the implementation of server sent events being broken in Firefox, because for me it's working in Chromium and not FX (Developer edition).

**Comment by cadecairos** [comment]
Forget that, found a helpful thread on [server-sent events and nginx](https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx)

I added `proxy_buffering off;`, `proxy_cache off;`, `proxy_http_version 1.1;`, `chunked_transfer_encoding off;`, and `proxy_set_header Connection '';` and now the web UI is working in Firefox.

in case you need it, I launched n8n like so: 
```bash
docker run -d -p 5678:5678 -v ~/.n8n:/root/.n8n -e N8N_BASIC_AUTH_ACTIVE=true -e N8N_BASIC_AUTH_PASSWORD=$N8N_PASS -e N8N_BASIC_AUTH_USER=$N8N_USER -e N8N_HOST=$N8N_HOST -e N8N_PROTOCOL=$N8N_PROTO -e VUE_APP_URL_BASE_API=$N8N_VUE_URL_BASE_API -e WEBHOOK_TUNNEL_URL=$N8N_WEBHOOK_TUNNEL_URL --name n8n  n8nio/n8n:0.23.0
```

**Comment by lmariscal** [comment]
The `N8N_HOST` does change the host value but in the webhook urls it still shows the port behind the proxy. `N8N_PORT` wouldn't solve this issue as I do want that port to be used at serving the server behind the proxy but I don't want it in my webhooks.

**Comment by janober** [comment]
@lmariscal to change the URL of only the webhook set the environment variable:

That sets the webhook URL (totally ignoring what is in `N8N_HOST` and `N8N_PORT`)

```
WEBHOOK_TUNNEL_URL="https://example.com/"
```

**Comment by janober** [comment]
I hope that did answer your questions. If not you can follow up anytime. Close the issue for now.

**Comment by brauliodiasribeiro** [comment]
I can't configure this.
It doesn't work on my self-hosted N8N, my workflow doesn't run.

![image](https://github.com/user-attachments/assets/b684ca79-5826-4507-a0c7-a5dc7620499e)

![image](https://github.com/user-attachments/assets/1aa1e568-22b7-41e7-bac5-fe5b70aa0318)
