### ISSUE TITLE
GitHub node doesn't support multiple items as input

### ISSUE THREAD

**Issue by fcecagno** [n8n-io/n8n#3604]
**Describe the bug**
It would be expected that, if multiple items are received by a GitHub node, it would perform the operation for each item individually. However, it runs for the first item and fails for the second (and the others are ignored).
Because of that, I needed to use SplitInBatches with size 1 and loop it with the GitHub node, so it receives one item at a time.

**To Reproduce**
Create a list of file paths (multiple items), connect it to a GitHub node, create file operation. Problem occurs on any file operation.
I discovered the issue while modifying this workflow: https://n8n.io/workflows/1534/

**Environment (please complete the following information):**
0.183.0 on the official docker image

**Comment by janober** [comment]
There must be a misunderstanding. The GitHub node does already execute once per item. If it fails for the second item, then there must be a problem with that item. The error message the node returns should help to debug what exactly is wrong.
 
If you want that the node keeps on processing the other items even if any of the others failed you can activate "Continue on fail".

I hope this is helpful!

**Comment by fcecagno** [comment]
Thanks for your answer @janober .
I tested again with a very minimal setup (copying below for the benefit of others), and it worked as expected and as you explained. Sorry about that.

```
{
  "name": "test-3604",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "const times = 3;\nvar result = [];\nfor (var i = 0; i < times; i++) {\n  result.push({\n    json: {\n      path: \"file_\" + Math.random() + \".txt\"\n    }\n  })\n}\n\nreturn result;"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        460,
        300
      ]
    },
    {
      "parameters": {
        "resource": "file",
        "owner": "",
        "repository": "",
        "filePath": "={{$json[\"path\"]}}",
        "fileContent": "Not empty!",
        "commitMessage": "=Push {{$json[\"path\"]}}"
      },
      "name": "GitHub",
      "type": "n8n-nodes-base.github",
      "typeVersion": 1,
      "position": [
        680,
        300
      ],
      "credentials": {
        "githubApi": {
          "id": "17",
          "name": ""
        }
      }
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Function",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function": {
      "main": [
        [
          {
            "node": "GitHub",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": 16,
  "tags": []
}
```

**Comment by janober** [comment]
Nothing to be sorry about. We have for sure still a lot to do making such things more obvious.

Glad to hear that I could help! Have fun!

**Comment by fcecagno** [comment]
Hi @janober , just wanted to comment that the problem I had with the GitHub node was related to this topic: https://community.n8n.io/t/set-http-request-loop/15317

I was using this syntax to access a Set node:
```
{{$node["Globals"].json["repo"]["owner"]}}
```
However, it worked well when I changed it to:
```
{{$items("Globals")[0].json.repo.owner}}
```
