### ISSUE TITLE
sendemail report cert issue even disable ssl

### ISSUE THREAD

**Issue by heywiorld** [n8n-io/n8n#3605]
**Describe the bug**
When send email, return self signed certificate issue, while unenable ssl.

**To Reproduce**
1. Go to add 'send email'
2. Click on 'create new', fill the info, and disable the SSL.
3. run node

**Expected behavior**
send email ok

**Environment (please complete the following information):**
 - OS: [windows 11]
 - n8n Version [e.g. 0.174.0]
 - Node.js Version [default]
 - Database system [default]
 - Operation mode [default]

**Additional context**

![QQ截图20220627081910](https://user-images.githubusercontent.com/43668597/175845534-ddf3ff22-ccb7-469c-a969-2f3a97c77fb9.png)
![QQ截图20220627081946](https://user-images.githubusercontent.com/43668597/175845547-5259d56d-c708-4c89-a36e-58c0c70918f0.png)

**Comment by Joffcom** [comment]
Hey @heywiorld,

Under the options in the node is there an option to ignore ssl issues?

**Comment by heywiorld** [comment]
> Hey @heywiorld,
> 
> Under the options in the node is there an option to ignore ssl issues?

Hi @Joffcom , there is no other options for the node

**Comment by Joffcom** [comment]
Hey @heywiorld,

Assuming it is the Send Email node at the bottom there should be an options section and in there you will find this.

![image](https://user-images.githubusercontent.com/4688521/176860206-a91fff23-9c67-469c-b533-b8baaba7c701.png)

**Comment by heywiorld** [comment]
> Hey @heywiorld,
> 
> Assuming it is the Send Email node at the bottom there should be an options section and in there you will find this.
> 
> ![image](https://user-images.githubusercontent.com/4688521/176860206-a91fff23-9c67-469c-b533-b8baaba7c701.png)

yeah, fount it, thanks
