### ISSUE TITLE
Can't create multiple tasks at once with Todoist

### ISSUE THREAD

**Issue by danoc** [n8n-io/n8n#3613]
**Describe the bug**
Hello! There's an issue in the Todoist integration that causes it to create multiple copies of the same task when it receives multiple items.

I believe the problem is related to a recent refactor. Notice how `CreateHandler`'s `handleOperation` function expects an `itemNumber` (first link) and that the `itemNumber` is hardcoded as `0` (second link):

https://github.com/n8n-io/n8n/pull/3074/files#diff-7569657bb643f975e22272d9c9b11a255a0ce409845a59a2e0605f55c5b59354R10-R12

https://github.com/n8n-io/n8n/pull/3074/files#diff-10b0852fb2ddcadcdfd9bc00e6718fa0e8eea340f32fba38cf8e0a404551e1adR18-R20

**To Reproduce**
1. Pass in a list of X items to the Todoist Task Create operation.
2. Notice that X items get created, but they all share the same title despite using an expression.
3. Switch Todoist for another integration like "Send Email" and notice that it works as expected and each email has unique content.

**Expected behavior**
X number of items get created with unique details

**Environment (please complete the following information):**
 - OS: Official Docker image
 - n8n Version: 0.183.0
 - Node.js Version Unknown
 - Database system: SQLite
 - Operation mode: own

**Additional context**
N/A

**Comment by danoc** [comment]
cc: @agobrech and @RicardoE105 who recently worked on the integration: https://github.com/n8n-io/n8n/pull/3074

**Comment by Joffcom** [comment]
Hey @danoc,

Good spot, I have just popped in a PR to fix this.
