### ISSUE TITLE
[Mailchimp] Parameter "Status" is required

### ISSUE THREAD

**Issue by pedrogryzinsky** [n8n-io/n8n#3615]
**Describe the bug**
The parameter "Status" is considered required in the Mailchimp node, even on Operations where it shouldn't be. Also, adding the parameter to these operations through the 'Options' section does not yield a different result. The exception is the 'Create' operation, which displays a different "Status" field by default and works just fine.

**To Reproduce**
1. Create a simple workflow with a Mailchimp node (attached in the **Additional context** section);
2. Select one of the following operations ('Delete', 'Get', 'Get All', 'Update');
3. Execute the workflow;
4. See error (a tooltip with the title "Workflow has issues" with the message "Please fix them before executing:  - Mailchimp: Parameter "Status" is required.").

**Expected behavior**
Operations like 'Get All', 'Get', 'Delete' or 'Update' should not require the "Status" parameter to be set. 'Update' requires a "status_if_new" query parameter, [as documented in Mailchimp API](https://mailchimp.com/developer/marketing/api/list-members/add-or-update-list-member/), but only if adding a user that does not exist.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - n8n Version: 0.183.0
 - Node.js Version: 16.15.1
 - Database system: PostgreSQL
 - Operation mode: own

**Additional context**
Below is the workflow used to run this test, also, I've attached screenshots of the problem.

I've found this behavior both on my production deployment and locally (using the n8n-io/n8n:0.183.0-debian docker image). I did not test this behavior using n8n from a npm install or the Desktop app.

A quick fix was to downgrade to 0.181.0, which seems to solve the problem.

```json
{
  "name": "Test Workflow",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        -400,
        300
      ]
    },
    {
      "parameters": {
        "operation": "getAll",
        "list": "527d1cb071",
        "options": {
          "status": "subscribed"
        }
      },
      "name": "Mailchimp",
      "type": "n8n-nodes-base.mailchimp",
      "typeVersion": 1,
      "position": [
        -60,
        300
      ],
      "credentials": {
        "mailchimpApi": {
          "id": "3",
          "name": "Mailchimp account"
        }
      }
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Mailchimp",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "tags": []
}
```

![image](https://user-images.githubusercontent.com/8284669/176448940-105d9f7b-747c-4cb8-8e11-f1b5fa7be396.png)
![image](https://user-images.githubusercontent.com/8284669/176449270-8af770cf-5f12-4516-829f-81ee85e4d30f.png)
![image](https://user-images.githubusercontent.com/8284669/176449347-243fe35f-30a7-4429-b323-73b3beeaf1ac.png)
![image](https://user-images.githubusercontent.com/8284669/176449397-3b3ca82d-96dc-4b16-8d2c-49c12f2ca509.png)
![image](https://user-images.githubusercontent.com/8284669/176449450-07b5dbdf-d463-43e5-9695-069ced1bae06.png)
![image](https://user-images.githubusercontent.com/8284669/176449503-50318abf-15ae-48e1-ba27-fe44c24d822f.png)

**Comment by Joffcom** [comment]
Hey @pedrogryzinsky,

Can you try upgrading to 0.184.0 this should be fixed now.
