### ISSUE TITLE
Checkboxes in sticky notes are not displayed/escaped correctly

### ISSUE THREAD

**Issue by CommandLord** [n8n-io/n8n#3616]
**Describe the bug**
When trying to use checkboxes in sticky notes like 
`- [ ] Example Todo` 
there will only be the plain text 
`<input class="task-list-item-checkbox" disabled="" type="checkbox" id="task-item-4482900"><label class="task-list-item-label" for="task-item-4482900"> Example Todo</label>`
but no html checkbox is added.

**To Reproduce**
1. Go to a workflow
2. Click on the "add sticky note" button in the top right
3. But a line in there like `- [ ] Example Todo` 
4. Exit the edditing of the sticky note
5. See error

**Expected behavior**
An (interactable) is displayed.

**Environment (please complete the following information):**
 - OS: MacOS/Firefox
 - n8n Version: 0.182.1
 - Node.js Version: ?/default with docker
 - Database system: SQLite/default
 - Operation mode: `own`/default

**Additional context**
none?

Image illustrating the issue:
<img width="399" alt="Bildschirmfoto 2022-06-29 um 15 58 04" src="https://user-images.githubusercontent.com/18055729/176455068-77b0e45b-d25d-4240-9738-69fef27f320b.png">

**Comment by Joffcom** [comment]
Hi There,

Looks like I missed this one, I have created `N8N-5972` as our internally ticket to investigate this one. I suspect we didn't intend on having checkboxes in the initial release and forgot to clean up the output.

**Comment by janober** [comment]
Fix got released with [`n8n@1.45.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.45.0)

**Comment by Joffcom** [comment]
Hey @CommandLord,

Good news we have now fixed this.

![image](https://github.com/n8n-io/n8n/assets/4688521/00f5a3d5-65ff-4480-a333-50acabd5c68d)

I am going to mark this as closed, If you are still seeing this after updating let me know.
