### ISSUE TITLE
Nextcloud / Foreach does not process next item on error

### ISSUE THREAD

**Issue by TobenderZephyr** [n8n-io/n8n#362]
**Description**:
In my workflow, n8n retrieves a list of Confluence Pages via HTTP Request and Uploads them to Nextcloud after converting to PDF.
My problem is, that it should create Folders based on the Page name beforehand.
Yet it throws errors because the folder exists - so i checked "Continue on Fail" which in return does not proceed any further - resulting in missing Files and Folders.

**Detail**:

> ERROR: 405 - "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n <s:exception>Sabre\\DAV\\Exception\\MethodNotAllowed</s:exception>\n <s:message>The resource you tried to create already exists</s:message>\n</d:error>\n"

**Expected Result**:
Node should continue processing the next item on fail.

**Actual Result**:
Node continues on fail and passes to next node after first fail.

**Comment by TobenderZephyr** [comment]
Attached is the n8n Workflow:

`
{
  "name": "AutoUpload Documentation",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "authentication": "basicAuth",
        "url": "=https://<confluence>/rest/api/content/search?cql=space=DOC%20AND%20label=\"main-page\"&expand=space,metadata.labels",
        "allowUnauthorizedCerts": true,
        "options": {
          "fullResponse": false
        },
        "headerParametersUi": {
          "parameter": [
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Accept",
              "value": "application/json"
            }
          ]
        },
        "queryParametersUi": {
          "parameter": [
            {
              "name": "="
            }
          ]
        }
      },
      "name": "Retrieve All Pages",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        450,
        300
      ],
      "credentials": {
        "httpBasicAuth": "<Confluence User>"
      }
    },
    {
      "parameters": {
        "authentication": "basicAuth",
        "url": "=https://<Confluence>/plugins/servlet/scroll-pdf/api/public/1/export-sync?templateId=954d2f32-4fa6-417f-a358-6a68ee751fb7&scope=descendants&pageId={{$node[\"Function-Transform\"].data[\"id\"]}}",
        "allowUnauthorizedCerts": true,
        "responseFormat": "file",
        "options": {},
        "headerParametersUi": {
          "parameter": [
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Accept",
              "value": "application/json"
            }
          ]
        }
      },
      "name": "Generate PDF",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        900,
        300
      ],
      "credentials": {
        "httpBasicAuth": "<Confluence User>"
      }
    },
    {
      "parameters": {
        "fileName": "=/home/n8n/tmp/{{$node[\"Function-Transform\"].data[\"id\"]}}"
      },
      "name": "Write Binary File",
      "type": "n8n-nodes-base.writeBinaryFile",
      "typeVersion": 1,
      "position": [
        1050,
        300
      ]
    },
    {
      "parameters": {
        "functionCode": "const newItems = [];\n\nfor (const item of items[0].json.results) {\n  newItems.push({json: item});\n}\n\nreturn newItems;"
      },
      "name": "Function-Transform",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        600,
        300
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "title",
              "value": "={{$node[\"Function-Transform\"].json[\"title\"].replace(\"/\",\" \")}}"
            }
          ]
        }
      },
      "name": "Replace Title",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        750,
        300
      ],
      "notes": "This node strips non-printable characters."
    },
    {
      "parameters": {
        "path": "=<Parent Folder>/{{$node[\"Replace Title\"].json[\"title\"]}}/{{$node[\"Replace Title\"].json[\"title\"]}}.pdf",
        "binaryDataUpload": true
      },
      "name": "NC Upload File",
      "type": "n8n-nodes-base.nextCloud",
      "typeVersion": 1,
      "position": [
        1350,
        300
      ],
      "retryOnFail": false,
      "maxTries": 2,
      "waitBetweenTries": 5000,
      "credentials": {
        "nextCloudApi": "Nextcloud User"
      },
      "continueOnFail": true
    },
    {
      "parameters": {
        "resource": "folder",
        "path": "=<Parent Folder>/{{$node[\"Replace Title\"].json[\"title\"]}}"
      },
      "name": "NC Create Folder",
      "type": "n8n-nodes-base.nextCloud",
      "typeVersion": 1,
      "position": [
        900,
        150
      ],
      "retryOnFail": false,
      "maxTries": 2,
      "waitBetweenTries": 5000,
      "credentials": {
        "nextCloudApi": "Nextcloud User"
      },
      "continueOnFail": true
    },
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "mode": "everyWeek",
              "hour": 15,
              "weekday": "0"
            }
          ]
        }
      },
      "name": "Cron",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        250,
        150
      ]
    }
  ],
  "connections": {
    "Retrieve All Pages": {
      "main": [
        [
          {
            "node": "Function-Transform",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Generate PDF": {
      "main": [
        [
          {
            "node": "Write Binary File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Write Binary File": {
      "main": [
        [
          {
            "node": "NC Upload File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function-Transform": {
      "main": [
        [
          {
            "node": "Replace Title",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Start": {
      "main": [
        [
          {
            "node": "Retrieve All Pages",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Replace Title": {
      "main": [
        [
          {
            "node": "NC Create Folder",
            "type": "main",
            "index": 0
          },
          {
            "node": "Generate PDF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Cron": {
      "main": [
        [
          {
            "node": "Retrieve All Pages",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": true,
  "settings": {
    "timezone": "Europe/Berlin"
  },
  "id": "1"
}
`

**Comment by janober** [comment]
Yes, that is expected behavior as the setting only gets applied on a lower level. So when the node fails it simply goes on. It does not do it on a per-item level. Anyway, adding that makes sense.

**Comment by janober** [comment]
Ok please check with n8n@0.56.0 which I released today. 

If you set now "Continue on Fail" it should try with the next item and the one that fails will have one property called "error" with the error-message.
