### ISSUE TITLE
n8n sending invalid GET requests

### ISSUE THREAD

**Issue by pemontto** [n8n-io/n8n#3620]
**Describe the bug**
n8n's axios library appears to send invalid GET requests with an HTTP body. While most services accept this, intermediate proxies often reject them. I have confirmed this occurs with both Github and Clockify nodes.

**To Reproduce**
1. Configure http_proxy and https_proxy environment variables to use an http proxy
1. Add a Github or Clockify node, potentially others
1. Configure a resource and operation that makes a GET request
    * Github: Resource: User, Operation: Get Repositories
    * Clockify: Resource: Workspace, Operation: Get all
1. Send the request
1. See error

Packet capture showing empty body with GET request:
![SCR-20220630-ev4-2](https://user-images.githubusercontent.com/939704/176648726-2e64cd1e-a436-4a3e-9763-ca1a9044932c.png)

Squid proxy error:
![SCR-20220630-eu2](https://user-images.githubusercontent.com/939704/176648610-36dd4d1a-e0a2-40c5-b68e-d7de389367cd.png)

**Expected behavior**
GET requests should not have request bodies. Although not strictly prohibited by the spec, a GET body has no semantic meaning. Similar to Python `requests` library a GET request with a body should be considered invalid.
```
>>> requests.get(url='http://ipinfo.io', body='')
TypeError: request() got an unexpected keyword argument 'body'
```

**Environment (please complete the following information):**
 - OS: MacOS 12 & Docker Alpine
 - n8n Version: 0.184.0
 - Node.js Version: v16.15.1
 - Database system: SQLite & PostgreSQL
 - Operation mode: own & queue

**Additional context**
None

**Comment by Joffcom** [comment]
@pemontto as you have put in a PR for this I am going to close this and we can handle this on the PR.
