### ISSUE TITLE
[Rudder] error when using docker N8N

### ISSUE THREAD

**Issue by heywiorld** [n8n-io/n8n#3664]
**Describe the bug**
found rudder error when using docker N8N 

**To Reproduce**
1. run command 'docker logs  xxxxx -f '
2. then will see error '2022-07-06T06:37:19.947Z [Rudder] error: got error while attempting send for 3 times, dropping 3 events
' while running workflow for the hive

**Expected behavior**
no error.

**Environment (please complete the following information):**
 - OS: [e.g. centos 7]
 - n8n Version [0.184.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [default ]
 - Operation mode [ `own`]

**Additional context**

![image](https://user-images.githubusercontent.com/43668597/177485617-76ff1876-dfd1-44b3-adfc-982d37f4239a.png)

**Comment by Joffcom** [comment]
Hey @heywiorld,

I believe that could be the Telemetry data failing to send, it is not anything anything to worry about and is potentially to be expected if you are on an internal private network with outbound network calls restricted.

You can try setting `N8N_DIAGNOSTICS_ENABLED` to false if you want to disable it.

**Comment by Joffcom** [comment]
@heywiorld,

That looks like it is someone trying to log in or acces something they don't have access to.

**Comment by heywiorld** [comment]
> @heywiorld,
> 
> That looks like it is someone trying to log in or acces something they don't have access to.

yeah, but no more details, so I don't know where is the error

**Comment by Joffcom** [comment]
Hey @heywiorld,

Is your instance available to the internet or are you doing any service checks to make sure it is online?

Depending on your setup it could be a few things but I can't think of anything that would be an issue with n8n itself.

If you are using a reverse proxy you could check the logs there to see if that shows where the connection is coming from and what url it is trying to access. If there is nothing in those logs it would be something that isn't using the reverse proxy and something that is able to connect directly.

**Comment by heywiorld** [comment]
ok. will check reverse proxy log, thanks

**Comment by joelgaribaygz** [comment]
@heywiorld Could you solve it? It's giving me the same problem
