### ISSUE TITLE
Webhooks - Body received empty from FreeScout

### ISSUE THREAD

**Issue by tufloc** [n8n-io/n8n#3679]
**Describe the bug**
When attempting to send a webhook from FreeScout to n8n, the body is always received empty.

The request works properly on other webhook testing sites (Tested on Zapier, IFTTT and  others)

```
[
{
"headers": {
"host": "domain",
"x-forwarded-for": "ip",
"x-forwarded-host": "domain",
"x-forwarded-port": "443",
"x-forwarded-proto": "https",
"x-forwarded-ssl": "on",
"connection": "close",
"content-length": "5289",
"user-agent": "GuzzleHttp/6.3.3 curl/7.68.0 PHP/7.4.3",
"content-type": "application/hal+json",
"accept-encoding": "gzip",
"x-freescout-event": "convo.created",
"x-freescout-signature": "hash",
"accept": "*/*"
},
"params": {
},
"query": {
},
"body": {
}
}
]
```

**To Reproduce**
1. Send a webhook request from FreeScout.
2. Receive an empty body on n8n.
3. See error

**Expected behavior**
Receive the actual body.

**Environment:**
 - OS: Ubuntu Linux 22.04
 - n8n Version 0.185.0

**Comment by freescout-helpdesk** [comment]
> I took a look at Freescout to give it a test but it looks like webhooks is a paid module with no trial so if we can check the above first if that doesn't help show anything I will make the purchase.

Just email us at support@freescout.net to get a license for debugging this.

**Comment by Joffcom** [comment]
Hey @freescout-helpdesk,

That is handy, I will drop you an email shortly.

**Comment by Joffcom** [comment]
Hey @tufloc,

I have a key applied and have managed to reproduce the issue, I have a few days off but coming up but I will start to dig into it a bit more when I get back.

**Comment by tufloc** [comment]
@Joffcom, Thanks for all the help. Waiting patiently.

**Comment by Joffcom** [comment]
Hey @tufloc,

So it looks like when the webhook body is sent it is sent with a HAL content type which our webhooks don't currently handle, I had not heard of HAL before but it was an interesting hole to fall into.

The good news though is you can get around this, In your webhook if you go to options and add the `Binary Data` option that will get the body in.

![image](https://user-images.githubusercontent.com/4688521/180398381-66ec65d3-313d-4983-8349-19b7b1012e93.png)

From here if you add in a `Move Binary Data` node it will then convert the binary data to json and you can use it like normal.

![image](https://user-images.githubusercontent.com/4688521/180398661-da7e85f6-90b3-42f3-a759-2e4b8c2ed067.png)

Let me know how you get on or if you have any questions and a big thanks to @freescout-helpdesk for sorting out a key so I could dig into this one.

**Comment by tufloc** [comment]
@Joffcom  This seems to work perfectly. Thanks for all your assistance! I see @freescout-helpdesk already updated their documentation to point to this issue and your workaround.

@freescout-helpdesk  Thanks for being willing to assist in this matter.

Thanks again to everyone!
