### ISSUE TITLE
Odoo node sends field values in the wrong syntax, leading to a workflow error. (Only applies to integers?)

### ISSUE THREAD

**Issue by Lanhild** [n8n-io/n8n#3700]
##### Disclaimer:
I'm almost certain the issue comes from the Odoo node.

**To Reproduce**
1. Place an Odoo node in your workflow
2. Select "Cusstom resource"
3. Select "Create"
4. Add a field with "Add Field"
5. Input field name
6. Input field value, e.g, `16`

Assuming you're trying to create a new sales order, you added the field `partner_id` and it's value, which in this example is `16`. When executing the node, you will be returned this error:
```
Database fetch misses ids (('16',)) and has extra ids ((16,)), may be caused by a type incoherence in a previous request
```

A very cumbersome and inconvenient fix to this is to put your field value in between round brackets `{{16}}`, like this. When executing the workflow again, it will work. Though this is very limited as it prevents you from using an expression for the field value.

### Screenshots
![2022-07-12_19-53](https://user-images.githubusercontent.com/73610779/178617538-eb3e867f-7b8f-4b95-bc46-b1160df8040b.png)
>When sending the field value `16` using an expression.
---
![2022-07-12_19-54](https://user-images.githubusercontent.com/73610779/178617731-54d27746-7305-40d1-a01b-1be68dba5e4d.png)
>When sending the field value `{{16}}` using an expression.
---
![2022-07-12_19-56](https://user-images.githubusercontent.com/73610779/178617861-dd490486-922d-4dbc-9354-d488f8bc02cf.png)
>The only way to make it "work".

 - n8n Version 0.185.0
- Ubuntu with Cloudron

**Comment by Joffcom** [comment]
Hey @Lanhild,

Out of interest what happens if you change your expression to use parseInt()? So something like {{parseInt($json['query'].partner_id)}}

**Comment by Lanhild** [comment]
**It looks like it worked using your suggestion**. Though, it's not practical as it forcefully takes the JSON values of the preceding node, which depending on the use case can be useless.

**Comment by Lanhild** [comment]
Seems like this issue only applies to integer field values? I tried putting a string as a field value in the Odoo node and it worked.
![2022-07-13_12-33](https://user-images.githubusercontent.com/73610779/178785147-22f20aa1-4913-46ea-8ceb-b251384fef83.png)

**Comment by Joffcom** [comment]
Hey @Lanhild,

So the thing I noticed was the data coming into the node is a string not an int, In the incoming node you have....
```
"partner_id":"16"
```

If it was an int it would be
```
"partner_id":16
```

I would say this is working as intended as we don't know what the field type is in Odoo we are taking the data as it is provided and passing it on. What we could maybe do in the future is have a dropdown box so you could specify the datatype but that would need to go through our feature request process.

What I like to do if it helps is use a Set node before I write anything out so I can set the values and make sure the datatypes are correct if they are not being sent in the format I would expect, It also allows me to check that is it the correct data before processing it.

**Comment by Joffcom** [comment]
Hey @Lanhild,

I am going to mark this one as closed for now as I don't believe this is a bug with n8n and it appears to be intentional based on the data being sent.

I do however still believe that in the future we should add a "type" option if we are asking for data to be set to be sent.
