### ISSUE TITLE
Old glob-parent Version 

### ISSUE THREAD

**Issue by shit-png** [n8n-io/n8n#3712]
We tried to install n8n:latest and n8n:0.186.1 on Kubernetes. 

Our security check (Trivy) detected an older verion (3.1.0) of glob-parent library.
This version got an security bug to cause an denial of service with regular expression.

An update to version 5.1.2 should fix this issue. Otherwise we can´t use n8n. 
![Screenshot 2022-07-14 134151](https://user-images.githubusercontent.com/52354974/178974597-33028ad8-3e70-4262-8067-3063c606f3b6.png)

**Comment by Joffcom** [comment]
Just adding that internally we are tracking this as `N8N-4110`

**Comment by Joffcom** [comment]
Hey @shit-png,

I have just checked and it looks like this has been taken care of in the fast-glob package we use and we now use 5.1.2 of glob-parent.

I am going to get this one marked as closed for now, Let me know if your scanner is still detecting this on newer releases.
