### ISSUE TITLE
Clickup node not able to get teams, spaces, etc

### ISSUE THREAD

**Issue by fbeauvais** [n8n-io/n8n#3717]
Last N8N installed on Ubuntu with Cloudron. Tried different access (o2auth, token, etc). This video says it all ;)

[https://watch.screencastify.com/v/GTmK0QaG7QqrTO8kfw7k](https://watch.screencastify.com/v/GTmK0QaG7QqrTO8kfw7k)

Version info:

![image](https://user-images.githubusercontent.com/5061749/179033173-fc1b4d03-c640-4d27-932a-1b5460205e86.png)

**Comment by fbeauvais** [comment]
Its now working. Looks like a delay with the auth maybe?

**Comment by Joffcom** [comment]
Hey @fbeauvais,

Could be or maybe a slight network hiccup, I will mark this one as closed if it pops again let me know and we can re-open.
