### ISSUE TITLE
Allow SMTP connection without auth

### ISSUE THREAD

**Issue by xavier-calland** [n8n-io/n8n#3740]
**Describe the bug**
It's not possible to use a SMTP server with anonymous connecion (like a local SMTP relay)

**To Reproduce**
1. Configure n8n with `N8N_SMTP_HOST`, `N8N_SMTP_PORT` and `N8N_SMTP_SENDER` but no `N8N_SMTP_USER` nor `N8N_SMTP_PASS`
2. Start n8n
3. Go to "User management"
4. The message "_Set up SMTP before adding users (so that n8n can send them invitation emails)_" is displayed and it is not possible to invite users.

**Expected behavior**
Allow SMTP configuration without configuration.

**Comment by nepodev** [comment]
You can enter dummy values for N8N_SMTP_USER and N8N_SMTP_PASS. If your SMTP server does not ask for a user and password, the values are not used. Works for my local SMTP.

**Comment by xavier-calland** [comment]
Yes, I tried this solution.
It works for some SMTP servers (like mailhog which I use in a development environment) but not the one I've to use on another environment.

As [NodeMailer](https://nodemailer.com/smtp/#authentication) accepts configuration without authentication parameters, it seems like a good idea to use this behavior in N8N.

**Comment by Joffcom** [comment]
Hey @xavier-calland,

As you have opened a PR for this one I am going to mark this issue as closed as it is more of a feature than a bug and we can chat on the PR.

I do plan on getting the PR reviewed soon as well so this should be something that we have support for soon. Let me know if you have any questions on this.
