### ISSUE TITLE
Login error after upgrade to 0.187.1 for non-admin users

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#3752]
**Describe the bug**

After upgrading to version 0.187.1 non-admin users receive the following message:

![photo_2022-07-21_08-41-23](https://user-images.githubusercontent.com/257004/180205819-a343ee1b-6ac6-46bf-9f27-37597b328ad5.jpg)

**To Reproduce**
1. Upgrade N8N
2. Login with admin account (it works)
3. Login with non-admin account (not works)

**Expected behavior**

Non-admin users can access the platform

**Environment (please complete the following information):**
 - OS: Debian / Docker
 - n8n Version 0.187.1
 - Node.js Version 
 - Database system: MySQL
 - Operation mode Docker with Queue

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof,

Thanks for reporting this one, I have just reproduced it here I will get an internal ticket opened.

**Comment by janober** [comment]
Thanks a lot.

Our engineers are already working on it and we will release a bug-fix version as soon as the fix is available.

**Comment by janober** [comment]
Got fixed with #3754. New version will be available soon.

**Comment by janober** [comment]
Fix got released with `n8n@0.187.2`

**Comment by kwmc-lucas** [comment]
Confirmed working, thanks!
