### ISSUE TITLE
Allow users to delete tags

### ISSUE THREAD

**Issue by Lanhild** [n8n-io/n8n#3757]
Allow users to delete tags.
![2022-07-21_22-30](https://user-images.githubusercontent.com/73610779/180349823-2633e0a2-138d-4f31-9690-fe5566046053.png)

**Comment by ivov** [comment]
The delete button should be next to the edit button in the latest. Which n8n version and browser are you on?

<img width="752" alt="image" src="https://user-images.githubusercontent.com/44588767/180406952-4ed51fb5-a268-4875-b9ea-2952afddee63.png">

**Comment by Lanhild** [comment]
Latest update fixed it.
