### ISSUE TITLE
Node Mautic unusable for those who using Basic Auth

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#3760]
**Describe the bug**

N8N version 0.187.1 [modifies node Mautic](https://github.com/n8n-io/n8n/blob/13483497484e205975ef71091e3892f757f608e1/packages/nodes-base/credentials/MauticApi.credentials.ts#L37) to add Credentials Test. #3668

But the /api/users/self endpoint works by OAuth2,  for all users using Mautic Basic Auth API the node Mautic is broken

![erro-api-mautic-n8n](https://user-images.githubusercontent.com/257004/180471682-3bc2eccb-9eb1-4abb-9187-710815cef24b.png)

**To Reproduce**
1. Upgrade N8N
2. Authenticate to Mautic Node using OAuth2 (it works)
3. Authenticate to Mautic Node using Basic Auth (not work)

**Expected behavior**

Mautic allows accessing the API by two modes: Basic Auth and OAuth, allowing N8N to work with both modes.

**Environment (please complete the following information):**
 - OS: Debian  Docker
 - n8n Version: 0.187.2
 - Node.js Version [e.g. 14.16.0]
 - Database system MySQL 8
 - Operation mode: Queue

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof,

Thanks for reporting this one, I am just testing a fix now.

**Comment by janober** [comment]
But does the node not still work perfectly? The test should not matter at all for the functionality, is just a frontend thing .

**Comment by luizeof** [comment]
@janober not work at all (only using Basic Auth)

Using OAuth works perfectly as usual.

**Comment by janober** [comment]
Ah then more than just the test got updated. We will have a look.

**Comment by janober** [comment]
Fix got merged and will be released with the next version.

**Comment by janober** [comment]
Fix got released with `n8n@0.188.0`
