### ISSUE TITLE
RocketChat node always return ERROR: Authorization failed - please check your credentials

### ISSUE THREAD

**Issue by DonBamboo** [n8n-io/n8n#3776]
**Describe the bug**
RocketChat node always return ERROR: Authorization failed - please check your credentials

**To Reproduce**
After inserting the correct user ID, Auth Key and domain the error always return

**Expected behavior**
successfully sending the message or run custom API for RocketChat.

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 Enterprise]
 - n8n Version [e.g. 0.187.2]
 - Node.js Version [e.g. 14.19.3]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @DonBamboo,

Thanks for reporting this one, I will look into it now and see what has gone wrong.

**Comment by janober** [comment]
Fix got merged and will be released with the next version.

**Comment by DonBamboo** [comment]
Thank for fixing this issue! you guys rock!

**Comment by chotaire** [comment]
I had downgraded my dockerized n8n to tag 0.186.1 as a workaround for this issue, it still worked fine in that version.

**Comment by janober** [comment]
Fix got released with `n8n@0.188.0`
