### ISSUE TITLE
Start Node could not be deleted.

### ISSUE THREAD

**Issue by naishweb** [n8n-io/n8n#379]
When i am using a trigger, the workflow will not begin the execution at the trigger, it begins at the "Start"-node.
1. I cant remove the Starting node (it doesn't matter if the node is active or not)
2. The workflow does not begin with the trigger node, it begins with the starting node.

**To Reproduce**
1. fresh docker latest image
2. Create new Workflow
3. Add Trigger Node of choice
4. Trashcan symbol of startnode does not delete the start node
4.a [optional] press the pause icon from the start button
5. press "Execute Workflow" 
6. workflow will begin executing @ "Start" Node

**Expected behavior**
I assume that the trigger is the starting point of the workflow. Therefore i want to delete the "Start"-node but the trashcan-symbol does not fullfill this operation

**Environment (please complete the following information):**
- latest docker image [
 - n8n Version [0.55.1]
 - Node.js Version [12.13.0]
]

**Comment by janober** [comment]
Ah yes, that behavior is as expected. Each workflow has to contain a Start-Node, so it can not be deleted. 

Also, the way it executes was planned that way. If it should get executed differently then the "Play-Button" of the last node of the branch which should be executed can be pressed. It will then find the first node of this branch and executes starting from there. I can, however, understand that it is maybe confusing for beginners and so just changed the default behavior to look first if there is a Trigger-Node in the flow and if yes, it chooses the very first one it finds as starting point. Only if no Webook-Node or Trigger-Node can be found will it start to execute from the Start-Node.

Will be released with the next version. 

And the next time please post to the forum first as Github-Issues are only for confirmed bugs. Thanks!

**Comment by janober** [comment]
Got released with n8n@0.56.0
