### ISSUE TITLE
Cursor doesn't work on /executions

### ISSUE THREAD

**Issue by fcecagno** [n8n-io/n8n#3830]
**Describe the bug**
Cursor doesn't affect pagination when [retrieving all executions](https://docs.n8n.io/api/api-reference/#tag/Execution/paths/~1executions/get). It was discussed and confirmed in the forums: https://community.n8n.io/t/does-pagination-work-for-retrieve-all-executions/16146/4

**Comment by csuermann** [comment]
Hi @fcecagno! Thank you for reporting this issue. We have have created an internal ticket for it and will look into it.

**Comment by ivov** [comment]
This should have been fixed with #3834. If it persists, please let us know and we will reopen.
