### ISSUE TITLE
ERROR: Cannot find module 'spex'

### ISSUE THREAD

**Issue by hckhanh** [n8n-io/n8n#3837]
**Describe the bug**
I try to deploy webhook instance then trigger a webhook flow, I receive this error

```
Error: Cannot find module 'spex'
Require stack:
- /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/task.js
- /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/database.js
- /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/main.js
- /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/index.js
- /home/ubuntu/deployments/my-project/node_modules/n8n-nodes-base/dist/nodes/CrateDb/CrateDb.node.js
- /home/ubuntu/deployments/my-project/node_modules/n8n/dist/src/LoadNodesAndCredentials.js
- /home/ubuntu/deployments/my-project/node_modules/n8n/dist/src/index.js
- /home/ubuntu/deployments/my-project/node_modules/n8n/dist/commands/worker.js
- /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/plugin.js
- /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/config.js
- /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/index.js
- /home/ubuntu/deployments/my-project/node_modules/@oclif/command/lib/command.js
- /home/ubuntu/deployments/my-project/node_modules/@oclif/command/lib/index.js
- /home/ubuntu/deployments/my-project/node_modules/n8n/bin/n8n
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/task.js:13:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/database.js:22:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at $main (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/main.js:237:22)
    at Object.execute (/home/ubuntu/deployments/my-project/node_modules/n8n-nodes-base/dist/nodes/Postgres/Postgres.node.js:249:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Joffcom** [comment]
Hey @hckhanh,

Can you send over the steps you took to produce that error? Are you trying to use your own node or include a package to use in a function node?

**Comment by hckhanh** [comment]
Hi @Joffcom, I am using some packages for the function node.

NODE_FUNCTION_ALLOW_EXTERNAL=lodash,fast-array-diff

**Comment by Joffcom** [comment]
Hey @hckhanh,

What about how you are producing the error? It just looks like an npm package is missing from somewhere so it could be the deployment method or something else I am missing.

**Comment by hckhanh** [comment]
I try to reinstall `node_modules` then the webhook can only run 9 times before it's getting this error. I don't know why, It seems unstable

Even I try to set

```
NODE_FUNCTION_ALLOW_BUILTIN=*
NODE_FUNCTION_ALLOW_EXTERNAL=*
```

**Comment by hckhanh** [comment]
Here is my flow

[Get_list_of_changesets.zip](https://github.com/n8n-io/n8n/files/9268016/Get_list_of_changesets.zip)

**Comment by hckhanh** [comment]
I am using queue mode

![image](https://user-images.githubusercontent.com/6380436/183065559-5e89a5cd-56f1-4a0a-946c-0d1f1f666396.png)

**Comment by hckhanh** [comment]
> **Describe the bug** I try to deploy webhook instance then trigger a webhook flow, I receive this error
> 
> ```
> Error: Cannot find module 'spex'
> Require stack:
> - /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/task.js
> - /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/database.js
> - /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/main.js
> - /home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/index.js
> - /home/ubuntu/deployments/my-project/node_modules/n8n-nodes-base/dist/nodes/CrateDb/CrateDb.node.js
> - /home/ubuntu/deployments/my-project/node_modules/n8n/dist/src/LoadNodesAndCredentials.js
> - /home/ubuntu/deployments/my-project/node_modules/n8n/dist/src/index.js
> - /home/ubuntu/deployments/my-project/node_modules/n8n/dist/commands/worker.js
> - /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/plugin.js
> - /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/config.js
> - /home/ubuntu/deployments/my-project/node_modules/@oclif/config/lib/index.js
> - /home/ubuntu/deployments/my-project/node_modules/@oclif/command/lib/command.js
> - /home/ubuntu/deployments/my-project/node_modules/@oclif/command/lib/index.js
> - /home/ubuntu/deployments/my-project/node_modules/n8n/bin/n8n
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/task.js:13:11)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/database.js:22:11)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at $main (/home/ubuntu/deployments/my-project/node_modules/pg-promise/lib/main.js:237:22)
>     at Object.execute (/home/ubuntu/deployments/my-project/node_modules/n8n-nodes-base/dist/nodes/Postgres/Postgres.node.js:249:46)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```

This is the error I get from the pg node

**Comment by Joffcom** [comment]
Hey @hckhanh,

What were the steps you took to set up n8n? When you mention installing node_modules how are you doing that? There is still a good chunk of information missing that could be useful.

**Comment by janober** [comment]
Are we sure this is a bug in n8n? Because if not it should be posted in the forum https://community.n8n.io/
Also did the issue template not get filled, but rather deleted. Please always fill it, no matter what. Thanks!

**Comment by Joffcom** [comment]
Hey @hckhanh,

Did you have a chance to check the above yet?

**Comment by hckhanh** [comment]
Hi @Joffcom, I think the issue is resolve for now. I shall close the issue
