### ISSUE TITLE
WEBHOOK_URL for OAuth 2

### ISSUE THREAD

**Issue by hckhanh** [n8n-io/n8n#3838]
Is that correct with the OAuth URL when I try to change `WEBHOOK_URL` to a different domain?

For my case it will be 

```
WEBHOOK_URL=https://staging-n8n-webhook.domain.vn
```

![image](https://user-images.githubusercontent.com/6380436/183061318-9a81fd37-5c7c-40fc-bf0a-a82861a9f5eb.png)

**Comment by Joffcom** [comment]
Hey @hckhanh,

This doesn't appear to be an issue and is more of a question, For support questions we prefer to use our community forum here: https://community.n8n.io which is monitored by more people and our community members.

To answer your question though, That looks right to me.

**Comment by hckhanh** [comment]
I think this is not correct, since I get this error when I try to access the above link

![image](https://user-images.githubusercontent.com/6380436/183066269-75ac8cbd-26b6-475a-ac11-309138368f2e.png)

But when I try to access the domain of the main process instead of the webhook one, it still work.

**Comment by Joffcom** [comment]
Hey @hckhanh,

That is a good point, So from my understanding when you use scaling mode it is only the webhooks that get handled by the webhook workers the oauth process is still handled by the main worker.

@krynble may have a solution to this one.

**Comment by pemontto** [comment]
Same core issue as I was having where I can’t complete OAuth flows because it redirects to my webhook domain/URL.

Use instance URL for OAuth callback #3560

**Comment by Joffcom** [comment]
Hey @hckhanh,

In 0.193 you can now use `N8N_EDITOR_BASE_URL` for the oauth address, Can you do an upgrade and give it a bash to see if it works for you?

**Comment by krynble** [comment]
One side note is that the frontend is temporarily displaying a wrong URL, but as per @pemontto 's PR, this has been fixed in the backend. There is a ticket for our FE team to fix this issue already.

**Comment by hckhanh** [comment]
Hi @Joffcom,
Now everything run smoothly right now.

**Comment by Joffcom** [comment]
Hey @hckhanh,

That is good to hear, I will get this one marked as closed thanks for letting us know.
