### ISSUE TITLE
Memory Issue??

### ISSUE THREAD

**Issue by codeNgamer** [n8n-io/n8n#385]
**Describe the bug**
I've linked to the [workflow](https://www.dropbox.com/s/uf5fuwhejks1xac/download_hcad_files.json?dl=0)  that raises this issue. the workflow simply tries to download a bunch of files over some years, then unzip to the associated folder. I first tried to run all downloads in parallel but the workflow was always crashing. I then came up with this final workflow that downloads the files sequentially before unzipping. The ui still crashes but the task that handles the downloads and unzipping seems to run in the background and finish out the workflow. I checked the node process and its virtual memory was as high as 16gb. 
I'm curios as to how you handle file saves and if the resources are released afterwards.
Also is there a way to grant the ui more memory to prevent it from crashing.
After crashes occur on the ui, if i refresh the page, the workflow comes up and seems like nothing's happening while in fact (in this case) some associated background task is still running and executing the workflow

**Comment by codeNgamer** [comment]
Also the terminal shows this after ui crashes and refresh `The session "h1g3muywzks" is not registred.` May be related to the disconnect between workflow and background process

**Comment by janober** [comment]
Yes, that is sadly expected as n8n did not get built to process GB of data. All data in the workflow stays there until the workflow is finished. So if you download very many files then it will build up till at some point it crashes he the process as it will run out of memory. If you additionally started it manually via the Editor-UI, it will also crash the browser as all the data get streamed to it.

You would have to decouple it to make it work.

So you would need one workflow which processes only one file depending on an input. That could be either via Webhook and you call it with the Execute-Workflow Node.
Then you would have a second workflow which calls the first one for each file. 

Like that will the data of each workflow not get too large (make sure that the response is very small and does not include the whole file else we are back where we started) and processing it should not be a problem.

I hope that helps.

**Comment by codeNgamer** [comment]
Ah I see, that's definitely doable. I have some additional questions:
1. What's the max threshold for one workflow
2. How do you foresee  n8n working in the future? (i.e. being able to handle complex prod operations or mostly just automating little tasks)
3. The additional step I wanted to make on this workflow was to then ingest tsv files into mongo using mongoimport, I'm guessing this might not be achievable even if the workflow processes one file at a time because a file can be as much as 1gb for example.

**Comment by janober** [comment]
About your questions:
1. Honestly no idea. The limiting factors are probably mainly Node.js itself and how much RAM your computer has.
2. It depends on how you define complex workflows. If you define it as being able to move GB of binary data around and processing it. I honestly do not know, as that was never the functionality I designed n8n for. But for sure do not want to say it will not be possible. If you mean actually doing creating a complex workflow do automate a complex task, then you can do that already now. 
3. Probably not possible right now. To do that we would have to add the possibility to read parts of a file. Even though it is not supported right now, it would not be too complicated to implement.

**Comment by codeNgamer** [comment]
Okay no worries. You can close this and maybe pin for other users. Thank you

**Comment by janober** [comment]
Perfect, will do!

**Comment by chrisgereina** [comment]
> * Honestly no idea. The limiting factors are probably mainly Node.js itself and how much RAM your computer has.

Not sure how to make this work in the context of n8n (although I suspect I may have to find out) but Node.js' default memory limit can be increased

https://stackoverflow.com/questions/34356012/how-to-increase-nodejs-default-memory
