### ISSUE TITLE
ActiveCampaign - Remove Tag Fails

### ISSUE THREAD

**Issue by blew-pdx** [n8n-io/n8n#3851]
Hello,

At the start of my workflow, I'm getting all users with a specific ActiveCampaign tag, and at the end of the workflow, I'd like to remove that same tag.

The "Add Tag" works (see screenshot) and has a drop-down for all available tags and the contact ID.
However, with the "Remove Tag", only has a "Contact Tag Id" field. Adding the same ID as the start of my workflow fails, as does any other ID.

![Remove-Tag-Error](https://user-images.githubusercontent.com/110795990/183321958-8ce455c2-feb0-42c1-9a58-0b74dc03cab3.png)
![Add-Tag-Correct](https://user-images.githubusercontent.com/110795990/183321965-f1ab2b06-4d27-485f-b92a-1ea1f4938ea1.png)

**Comment by Joffcom** [comment]
Hey @blew-pdx,

When you say it fails what do you mean? Is there an error message you get or does it just not delete anything? It looks like we could probably do with adding a dropdown for the tags on that field as well.

**Comment by blew-pdx** [comment]
Hey @Joffcom 

Thanks for your reply. I've attached a screenshot of the error. 

The tag id in ActiveCampaign is 7, however, the node needs to find and delete the "reference id" that links the tag to the contact. 

I've managed to remove the tag by using a HTTP request to:
1) Find any instances of the tag id of 7 & then get the reference id
2) Delete the reference id

![Error](https://user-images.githubusercontent.com/110795990/184265007-0aaa0f6e-e988-4062-8d3d-3b2942474020.png)

**Comment by Joffcom** [comment]
Hey @blew-pdx,

That is interesting, So in that error ActiveCampaign is coming back and saying "no result found for SubscriberTag with id 7" I am not sure what is going on there but it is strange that ActiveCampaign says it doesn't exist.

When you are checking the ID of the tag are you using the tag ID or the associated tag id which is a different value? Looking at the API docs we are making the correct call but it does have the below.

```
This call will only remove the tag on the individual contact.
For example, "John Doe", a contact with and id of 6 has the tag "foo," and that tag has the id of 11.
When the tag id foo is placed on John Doe's contact, an "association id" is created, id 22.
```

**Comment by blew-pdx** [comment]
Hey @Joffcom 

The tag I want to remove has an ID of 7, however, the node deletes the association ID.
The only way I can get the association ID is with an HTTP lookup.

So the "Contact Tag" option in the ActiveCampaign node is technically working correctly, however, as you can't get the association ID without a separate HTTP lookup is where I got confused. 

I hope that makes sense?

**Comment by Joffcom** [comment]
Hey @blew-pdx,

Sorry for the delay on this one, that makes sense. It does also make things more interesting as the API call is correct. What you could do if the ID is outputted in another node earlier in the workflow is reference it with `$node["node_name"].json["item_that_contains_id"]` and that should do the job.

**Comment by Joffcom** [comment]
Hey @blew-pdx,

I am just going through some old tickets and this looks like one that can be closed as it isn't really a bug with n8n, For now I am going to close it and if you feel it is a bug let me know and we can look at opening it again.

**Comment by ThiagoRoberth** [comment]
@Joffcom, how are you?
Even using the TAG ID reference from the previous node gives the error, so I would like to reopen the ticket, see print:

![Captura de tela 2024-11-21 114849](https://github.com/user-attachments/assets/951cdd0a-1713-47ce-9b41-e3fc38cd5484)
