### ISSUE TITLE
TheHive node buggy when checking the status of executeAnalyzer

### ISSUE THREAD

**Issue by martinr103** [n8n-io/n8n#3857]
Hey guys,

these lines of code, in the TheHive.node.ts, are not good:

```
841: do {
842: 	responseData = await theHiveApiRequest.call(this, 'GET', `/connector/cortex/job/${jobId}`, body, qs);
843: } while (responseData.status === 'Waiting' || responseData.status === 'InProgress');
```

This produces an infinite loop, and in our environment generates like 31000 GET calls on Thehive within 15 minutes.
GET request every fraction of a second.
I think you need to find a different way of checking the status of the executeAnalyzer job.

If it has to be a do-while loop, then there should be some kind of delay between subsequent GET calls.
And also, the loop break condition probably is not sufficient with ```(responseData.status === 'Waiting' || responseData.status === 'InProgress') ``` because apparently in some scenarios it never matches - infinite loop. 
Maybe there are other values possible for ```responseData.status```  ?

**Comment by Joffcom** [comment]
Hey @martinr103,

I am just going through some old issues and it looks like this is one I missed, You are not wrong there with the constant requests we should probably have a bit of a delay there and maybe check once a second for a job to complete. I will need to check the API docs to see what status options can be used but I suspect at the time of the node being created they were correct.

Looking at the API docs there are a few different status options but we only want to run the loop while the status is waiting or in progress so any other status returned should exist the loop.

I guess if the status in The Hive never changes or takes a long time it is going to keep running so maybe having an option to say... check for X minutes is a possible solution to that. For now though I am not sure if this is actually a bug as such as while it is sending a lot of requests it is working as expected so this feels more like a couple of feature suggestions.

Let me know what you think.

**Comment by martinr103** [comment]
Hey Jonathan,

thanks for your comments.
There are two points to mention.
For one:  Yes, there is also a bug in Thehive or Cortex itself, which contributes to this n8n problem.
Because in some cases the Cortex job status is endlessly reported as "Waiting" in Thehive. Which makes the above loop infinite.
Regarding Cortex jobs, there are two ways to query their status: either via Thehive API, or directly via Cortex API.
I have proven, that sometimes the job status reported via Thehive API is "Waiting", while at the same-point-in-time !,
the job status queried via Cortex API is finished. ("success")
I have filed a bug report to Thehive team: https://github.com/TheHive-Project/TheHive/issues/2411 - but unfortunately: no reaction.
But the second point here is: I still do think that the code in the n8n node is at least 'incorrect programming'.
It would be correct only, if the request
    await theHiveApiRequest.call(...)
would indeed wait asynchronously for the competion OF THE JOB.
But no, the request only waits for the completion of the API-Call to "check the job status". And it gets the response very fast.
And then the loop continues, and immediately sends the next API-Call to Thehive. Without any delay.
So well, this is not only inefficient for n8n, it is also "bombarding" Thehive API with a high frequency, and putting
(completely unnecessary) stress on Thehive. So a delay between the requests is the minimum that can be done here.

I kind of like your idea of having an option/parameter to force exit the node after X minutes.
Or maybe, it is also possible to query the Cortex API directly for the job status, instead of the Thehive API.
Yes I know, this would require to store another (Cortex) API Key. At least the Cortex API is reliable, regarding the actual job status.

Best Regards...

**Comment by Joffcom** [comment]
Hey @martinr103,

The problem with using the Cortex API would be integrating another service into that node, We do already have a Cortex node though so we do have the credentials for that but it feels like it would go against what we do in our nodes with one node being specifically created to work with one API.

This of course doesn't help with the requests being fired so quickly in the loop and I am actually surprised this has not come up before, What I will do next week is pop a test PR together with a delay and exit for the analyzer call and we can see if it works as a possible thing to roll out to other nodes in the future.

**Comment by Joffcom** [comment]
We are planning on an overhaul of TheHive node soon so this should be addressed as part of that, For now I am going to mark this as closed and we can look again when the new node version is released to see if it is still an issue.

**Comment by dream91** [comment]
I've commented on https://github.com/TheHive-Project/TheHive/issues/2411. It seems the issue is with the database configuration, not with TheHive itself.
