### ISSUE TITLE
Cannot curl or perform HTTP requests in Docker

### ISSUE THREAD

**Issue by joshghent** [n8n-io/n8n#386]
**Describe the bug**
Using the Nodes HTTP Request or Run Command, I am unable to get any data back from an API that I am calling. I am hosting n8n as a docker container

**To Reproduce**
1.  Create a command node
2. Enter `curl -i -H "Authorization: token xxx" https://api.github.com/search/issues\?q\=is:pr+review-requested:{username}+archived:false+state:open` - replacing your username and token
3. Run the node

**Expected behavior**
To return the JSON body of data as it does on the command line

**Environment (please complete the following information):**
 - Host OS: Ubuntu 18
 - n8n Version - 0.37.0
 - Node.js Version: - whatever the version that the docker image uses

Any help appreciated - thanks a lot

**Comment by janober** [comment]
Please always post into the forum under:
https://community.n8n.io
unless you are sure it is a bug.

To your issue. That is expected as the Docker image does not contain curl and so it can not be used. If you want to make an HTTP Request simply use the HTTP Request Node as it is specially made to make requests like that.

I hope that helps.
