### ISSUE TITLE
baserow API not reachable through node // Fields in baserow node won't propagate // Request failed with status code 504

### ISSUE THREAD

**Issue by leisefuxX** [n8n-io/n8n#3870]
**Describe the bug**
when adding baserow node you can not select database name or table name. fields hang infinite and are red bordered. after some time red trianlge appears with error code 504

**Describe the setup**
baserow: latest docker container (fresh build to confirm)
n8n: latest docker container (fresh build to confirm)
reverse proxy via nginx proxy manager (docker container), which servers let's encrypt ssl certs

i can use curl from any machine in any part of the network/internet to query the api  `curl -X GET -H "Authorization: Token MYF4NCYT0K3NG03SH3R3" https://baserow.mydomain.net/api/database/fields/table/100` and get proper response. so baserow and reversy proxy work flawless.

tested it on fresh vps with latest docker containers: can't reach api and running into 504 ...

i add baserow credentials to get all baserow nodes with baserow node. no connection through node. field "Database Name or ID" and "Table Name or ID" are loading infinite

**To Reproduce**
1. add baserow credentials (username + token + host)
2. add baserow node 
3.1. select added credentials in field "Credential for Basero API"
3.2 select type row in field "Resource"
3.3 select get all in field "Operation"
4. watch 

**Expected behavior**
baserow node won't timeout and get Database Names and Table Names

**Environment (please complete the following information):**
 - Ubuntu 22.04 LTS, docker version 20.10.15, build fd82621
 - n8n Version: latest docker (n8nio/n8n)
 - Node.js Version from latest docker
 - Database system from latest docker
 - Operation mode: default from latest docker (own?)

**Additional context**
no additions

**Comment by Joffcom** [comment]
Hey @leisefuxX,

A 504 tends to be a network timeout, I have tested from the instance I run and I can reach my self hosted instance of Baserow and the Baserow hosted version with no issues.

Have you tried using a Baserow cloud account to see if that works or using the HTTP Request node to see if that has any issues connecting to it?

Out of interest when you did the connection testing did you try from inside the container itself just to confirm the container can actually connect?

**Comment by Joffcom** [comment]
Hey @leisefuxX,

How did you get on with this one in the end? Is it working now?

**Comment by tiptoptailor** [comment]
So, I stumbled upon this, and I found the solution for me that worked and might be relevant.

When setting the domain name in n8n don't use the domain set in source but instead destination since they are in the same docker environment.

for me it was 
http://baserow:80

**Comment by Joffcom** [comment]
Hey @tiptoptailor,

That is unusual the full domain should technically work as well 🤔

**Comment by tiptoptailor** [comment]
Well, I'm entirely new to all of this (networking docker etc..), so I'm not certain why this was the case. If there is anything I can offer that can help find out why, I'm happy to look into it.

If it makes a difference, I'm also running seatable to see what option works best for me, and I had the same issue.

Keep in mind, there are no issues when using other tools like make or Zapier externally. I just did a process of elimination and trial and error to come to this solution.

**Comment by Joffcom** [comment]
If it works it works 🙂 with one of my setups I have everything on a VPS using nginx proxy manager and I use the full domain for baserow on that one.

**Comment by Joffcom** [comment]
@leisefuxX are you still having this issue?

**Comment by leisefuxX** [comment]
yes @Joffcom i am still having this issue. 

n8n and baserow are running in vanilla docker, no changes to environment or container. i can't use FQDN, IP:Port or (Docker-)DNS like http://basrow:80

**Comment by Joffcom** [comment]
Hey @leisefuxX,

I am just cleaning up some old issues and I have not seen any more replies to this one so for now I am going to mark this one as closed.
