### ISSUE TITLE
github trigger

### ISSUE THREAD

**Issue by mathgonzlez** [n8n-io/n8n#3872]
**Describe the bug**
The github trigger only listen one time and the stop. i need to activate everytime i need to listen for an event

**To Reproduce**
1. Create a github trigger
2. Configure events
3. Start listen for event

**Expected behavior**
The github trigger dont stop listen events, because i want to log all the events when its started

**Environment (please complete the following information):**
 - OS: Macos MOJAVE
 - n8n Version 1.6.0 (app)
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode won

**Additional context**
Others template that use github trigger have the same issue.
As an extra comment, all templates that use github trigger can only be saved when it is started, once it received an event and the template ends, it cannot be saved since it does not find the trigger

**Comment by mathgonzlez** [comment]
I close the issue since I was using it wrong. it has to be saved for the trigger to start listening in the background

**Comment by Joffcom** [comment]
Hey @mathgonzlez,

On the top right of the workflow if you toggle it to active that will keep it running and should solve the issue.

If you want to log the events in the workflow settings there is an option to save executions this will let you see the runs in the executions log.

Let me know how you get on.
