### ISSUE TITLE
Are asana trigger's not secured?

### ISSUE THREAD

**Issue by melink14** [n8n-io/n8n#3880]
I was trying to add a webhook to Asana which failed due to basic auth set in my reverse proxy.

It felt unsafe to not have auth but I saw that Asana had a custom shared secret method for securing their webhook API and think it should work to create a webhook URL which has basic auth disabled.

That said, I was looking at the code for confirmation and saw this TODO which implies that the secret is not actually validated. Am I missing something or is there another safety catch somewhere?

https://github.com/n8n-io/n8n/blob/3608d132c0fbdb193758ba9a9c0f1da725d2313a/packages/nodes-base/nodes/Asana/AsanaTrigger.node.ts#L232

**Comment by Joffcom** [comment]
Hey @melink14,

That looks to be the case, and we really should fix that.

For now if you want to verify the data using the webhook node would be the best option and manually building out the logic.

**Comment by janober** [comment]
As @Joffcom wrote does it currently not happen and is probably also nothing that can be fixed easily as it would need core changes (for that reason the TODO). That said, the webhook URLs use random UUIDs so even though not perfect, will it still be impossible for anybody to "guess" it.

**Comment by melink14** [comment]
Thanks! I wasn't able to quite understand the difficulty from the TODO but agree that there's realistically but much risk.

I'd also encourage worried folk to confirm the asana state before mutating any data either way. Even if the trigger could be spoofed, the real data you can fetch afterwards is definitely valid so in most cases even the small risk can be avoided.

**Comment by Joffcom** [comment]
Hey @melink14,

I am just going through some old issues and this looks like one that can be closed as there isn't really a bug here, If you feel this should be opened again let me know and we can open it again 👍🏻
