### ISSUE TITLE
Monica "Return All" returns repeated items

### ISSUE THREAD

**Issue by sandoche** [n8n-io/n8n#3881]
**Describe the bug**
Monica integrations does not handle well the pagination of the API.
The first 15 items are corrected, then from the 16th it starts repeating the same as the previous.

**To Reproduce**
1. Add Monica CRM node and configure the token
2. Select Resource Contact
3. Select Get All
4. Toggle "Return all" and run

**Expected behavior**
I expect to see all my contacts. Instead I see the same number of contacts but the first 15 are repeated many times.

**Environment (please complete the following information):**
 - OS: Unbuntu 18.04 Running Docker on Caprover
 - n8n Version  0.166.0

**Comment by Joffcom** [comment]
Hey @sandoche,

I have just given this a quick test and I was able to reproduce the issue on the latest version of n8n, We will let you know when a fix has been put in place.

**Comment by sandoche** [comment]
Thanks for now I am using a workaround (using HTTP requests nodes) to manually get the number of pages and paginated manually. Thanks!
