### ISSUE TITLE
Node connection arrow can be deleted in read-only execution view

### ISSUE THREAD

**Issue by Raqbit** [n8n-io/n8n#39]
Hovering over a connection arrow I can simply hit the X to delete it. This seems to be a client-side thing as it is not persisted.

![image](https://user-images.githubusercontent.com/11144180/66419042-a117be00-ea03-11e9-921f-f90e3405f0e0.png)

**Comment by janober** [comment]
Thanks a lot. That should not be possible will have a look at it.

**Comment by janober** [comment]
Got fixed and will be released with the next version.

**Comment by janober** [comment]
Fix got released with n8n@0.68.2
