### ISSUE TITLE
Renaming a Node Remove All Previous Node Connections

### ISSUE THREAD

**Issue by rizalfauzie** [n8n-io/n8n#3900]
**Describe the bug**
Rename a node more than 2 depths, all previous node will disconnected.

**To Reproduce**
1. Upgrade n8n from `0.187.2` to `0.191.0`
2. Start n8n
3. Create New workflow
4. Add 3 connected nodes, any node
5. Rename the last node
6. Node connection between node 1 & 2 disconnected

**Expected behavior**
No node disconnection after renaming a node.

**Environment (please complete the following information):**
 - OS: Mac OS 12.1 Intel
 - n8n Version: 0.191.0
 - Node.js Version: v16.16.0
 - Database system: SQLite
 - Operation mode `own`

**Comment by Joffcom** [comment]
Hey @rizalfauzie,

This one was reported on our community support forum the other day, The good news is we do have a fix in place here: https://github.com/n8n-io/n8n/pull/3899 which has been merged and will be in the next release.

**Comment by Joffcom** [comment]
Hey @rizalfauzie,

This has been fixed in 0.191.1 which should be available now, I will mark this one as closed 👍🏻
