### ISSUE TITLE
Rename of node clears all other flow links

### ISSUE THREAD

**Issue by GarryG** [n8n-io/n8n#3904]
By renaming a node, all other nodes' flow links are deleted

**To Reproduce**
Have several nodes in your setup, with links between them. Rename any of the nodes. All links - except any that are directly connected to the renamed node - are deleted.

**Expected behavior**
D'uh. Links shouldn't be deleted ;)

**Environment (please complete the following information):**

- OS: Ubuntu 18.04, Docker-based n8n installation
- n8n Version 0.191.0
- Node.js Version - whatever is part of the official 0.191.0 docker image
- Operation mode own

**Comment by Joffcom** [comment]
Hi @GarryG,

This was fixed in 0.191.1 which was released earlier today, Give it an update and let me know how you get on .

**Comment by GarryG** [comment]
Confirmed, sorry for missing the update ....
