### ISSUE TITLE
MongoDB node does not work with serverless instances.

### ISSUE THREAD

**Issue by JoeyFenny** [n8n-io/n8n#3910]
**Describe the bug**
The MongoDB node cannot connect to instances of MongoDB that are serverless.

**To Reproduce**
For MongoDB connection details, enter a string that points to a serverless MongoDB instance. You will get an error if you test the connection or try to perform any operations on it.
See this error message:
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/16143306/185846668-3f73799b-8037-40dd-81fc-931d95e18feb.png">
Here is the text from the error:
```
MongoParseError: Load balancer mode requires driver version 4+
    at QueryReqWrap.callback (/usr/local/lib/node_modules/n8n/node_modules/mongodb/lib/core/uri_parser.js:111:27)
    at QueryReqWrap.onresolve [as oncomplete] (node:dns:215:10)
```

Here is a link to a potential solution on the MongoDB forums:
https://www.mongodb.com/community/forums/t/moongose-connection-error-with-mongodb-atlas/144094/2

I am on n8n version: 0.178.2 (docker version)

**Expected behavior**
It should work no different than non-serverless mong
**Environment (please complete the following information):**

**Additional context**
Should only need to upgrade the MongoDB driver to fix it.

**Comment by Joffcom** [comment]
Hey @JoeyFenny,

What error message are you getting and where is your serverless instance of MongoDB set up?

Could you also share what version of n8n you have running and how that is set up (Desktop, Docker, NPM, Cloud, something else)?

**Comment by JoeyFenny** [comment]
@Joffcom I have updated the post with the requested details.

**Comment by Joffcom** [comment]
@JoeyFenny perfect thanks, Are you also using Atlas or another serverless provider? It looks like it probably wouldn't matter but it would he handy to know just for testing the fix.

**Comment by JoeyFenny** [comment]
@Joffcom I am using Atlas.

**Comment by Joffcom** [comment]
Quick update for you @JoeyFenny, I was letting the team know about this one and it turns out we do have a fix in place as part of updating the MongoDB node here (https://github.com/n8n-io/n8n/pull/3163) as soon as it has been reviewed it will be good to go.

**Comment by JoeyFenny** [comment]
Amazing. Thanks for the quick answers.
