### ISSUE TITLE
upgrade fail: pinDataPerNode.every is not a function

### ISSUE THREAD

**Issue by vbarrier** [n8n-io/n8n#3937]
**Describe the bug**
Upgrade to 0.192 fail

`query is slow: INSERT INTO `xxxx`.`migrations`(`timestamp`, `name`) VALUES (?, ?) -- PARAMETERS: [1658932910559,"AddNodeIds1658932910559"]
execution time: 3737
Migrations in progress, please do NOT stop the process.
Migration "AddJsonKeyPinData1659895550980" failed, error: pinDataPerNode.every is not a function
There was an error initializing DB: "pinDataPerNode.every is not a function"
Stopping n8n...`

**Comment by csuermann** [comment]
Thanks for reporting this issue, which we'll internally track under N8N-3937

**Comment by MichalisDBA** [comment]
Same thing happened to me. Tried to upgrade from 0.191.1 to 0.192

```
Initializing n8n process

Migrations in progress, please do NOT stop the process.

Migration "AddJsonKeyPinData1659895550980" failed, error: pinDataPerNode.every is not a function

There was an error initializing DB: "pinDataPerNode.every is not a function"

Stopping n8n...
```
