### ISSUE TITLE
Public api definitions

### ISSUE THREAD

**Issue by dankristensen** [n8n-io/n8n#3940]
**Describe the bug**
Using createCredential operation in the public api, the data field is required in #/components/schemas/Credential. That makes sense, but this operation also returns a #/components/schemas/Credential on statusCode 200.

Unfortunately the data being returned from the server does not contain these data.

This gives problems in clients generated based on this openapi.yml specification, because they are validating the required fields in #/components/schemas/Credential. And this one contains data as a required:

    Credential:
      required:
        - name
        - type
        - data

I see a similary problem, when creating a workflow. Here pinData is not available in the openapi.yml file, but is being returned from the server.

**Expected behavior**
That what is defined in openapi.yml file, is also what is being returned from server.

**Comment by csuermann** [comment]
Thank you for reporting this issue. We'll track it internally as N8N-4413
