### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading '_')

### ISSUE THREAD

**Issue by hckhanh** [n8n-io/n8n#3947]
I get this bug with `S3` node when I try to upgrade to `v0.192.0`

```
TypeError: Cannot read properties of undefined (reading '_')
    at Object.execute (/home/ubuntu/deployments/Project/node_modules/n8n-nodes-base/dist/nodes/Aws/S3/AwsS3.node.js:501:72)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Workflow.runNode (/home/ubuntu/deployments/Project/node_modules/n8n-workflow/dist/src/Workflow.js:598:28)
    at async /home/ubuntu/deployments/Project/node_modules/n8n-core/dist/src/WorkflowExecute.js:552:53
```

**Comment by Joffcom** [comment]
Hey @hckhanh,

What version were you on before the update?

**Comment by hckhanh** [comment]
> Hey @hckhanh,
> 
> 
> 
> What version were you on before the update?

Hi @Joffcom, my previous version is '0.191.2'

**Comment by csuermann** [comment]
Seems to be related to this [commit](https://github.com/n8n-io/n8n/commit/5285fc1de684748d249e74829f2d6140ed222b51).

**Comment by Joffcom** [comment]
Hey @hckhanh,

The fix for this one in this PR: https://github.com/n8n-io/n8n/pull/3967 which will be in the next release. For now I will mark this one as closed, Thanks for letting us know about this one 👍🏻
