### ISSUE TITLE
Bug - Merge Node does not wait for both inputs

### ISSUE THREAD

**Issue by Brulijam** [n8n-io/n8n#3949]
The Merge Node in Mode "Wait" does not wait until both inputs are given.
It already executes when previous Nodes were executed. (Even when they don't output anything to the Merge Node).
I am using n8n Version 0.191.1 in a Docker Container.

**Comment by janober** [comment]
Thanks a lot for reporting this issue. But I am not sure I understand. Can you please provide an example workflow. Thanks!

**Comment by g5b63u3n** [comment]
Sure!
[Merge_not_Working_Example.zip](https://github.com/n8n-io/n8n/files/9427878/Merge_not_Working_Example.zip)

![image](https://user-images.githubusercontent.com/70335380/186757799-2f76c471-2161-4535-8be9-4ebfc86ff15d.png)

**Comment by Joffcom** [comment]
Hey @g5b63u3n,

Thanks for the example, I have just given it a run and managed to reproduce the issue. It looks like if you swap the 2 inputs around it then doesn't trigger the merge node.

![image](https://user-images.githubusercontent.com/4688521/187714870-11c13187-d27b-497b-aefd-fd5320cb36d4.png)

I have created an internal ticket for this issue which we will track as [N8N-4492](https://linear.app/n8n/issue/N8N-4492)

**Comment by g5b63u3n** [comment]
Jup, that works just fine.
Thank you guys for your help :)

**Comment by umanamente** [comment]
I have the same problem, and swapping inputs doesn't help.
Merge node is getting executed even if I disconnect preceding nodes from the trgger.

![2023-04-21 11_10_06](https://user-images.githubusercontent.com/10637425/233706965-a34d55fe-1d29-4ff6-a0de-bf422b01d0c1.png)

![2023-04-21 11_09_51](https://user-images.githubusercontent.com/10637425/233706983-eb0d000a-ed40-4ba8-afb8-a61f91631df3.png)

**Comment by Joffcom** [comment]
@umanamente your issue might be different, it might be worth opening a post on our community support forum and completing the template there and sharing the workflow and we can take a look.

**Comment by umanamente** [comment]
> @umanamente your issue might be different, it might be worth opening a post on our community support forum and completing the template there and sharing the workflow and we can take a look.

Created this post: https://community.n8n.io/t/bug-merge-node-makes-all-preceding-nodes-execute/25939

**Comment by Joffcom** [comment]
It looks like the main isssue for this one should be resolved in v1.0 when it is released, For now I am going to close this one and if it is still an issue after 1.0 we can open it again.

https://docs.n8n.io/1-0-preview/#changes-to-how-the-merge-node-processes-data

**Comment by zeekhuge** [comment]
The "Merge" is still not waiting for both the inputs, even in v1.0.1

**Comment by vivek12345** [comment]
This problem still exists. I have a gmail wait for node and merge block after that does not wait for both the outputs to arrive.

for example: Here you can see both true and false are active and the false branch executed without waiting for output of previous node.

<img width="804" alt="Image" src="https://github.com/user-attachments/assets/9ae77262-eb55-4e22-a47a-567de3be8363" />

**Comment by YangVincent** [comment]
<img width="742" height="418" alt="Image" src="https://github.com/user-attachments/assets/4d3aa3dc-a341-42b4-bd40-02d05efc3dfa" />

I'm getting the same issue here.
