### ISSUE TITLE
AWS S3 'upload' error undefined property at n8n 0.192.2

### ISSUE THREAD

**Issue by eontrix** [n8n-io/n8n#3954]
AWS S3 'upload' error undefined property at n8n 0.192.2
cannot read binary data from previous node, it's working okay in 0.191.1

step to reproduce:
1. Create function node with name: Initiate sample data
- add code in that node:
let data = [
  {
    "json": {
      "name": "john",
      "age": 26
    }
  }
]

data[0].json.prettified = JSON.stringify(data, null, 2)
return data

2. Add 'Move Binary Data' node with name: Convert prettified to Binary
- Mode: JSON to Binary
- Source Key: prettified
- Options.Encoding: utf 8
- Options.MIME Type: application/json
turn on 'Use Raw Data'

3. Add 'AWS S3' node (the red one)
- upload data from previous node

**Comment by Joffcom** [comment]
Hey @eontrix,

I am just looking into this now as part of #3947, It looks like when the credentials were updated recently it broke some of the functionality.

**Comment by eontrix** [comment]
Thank @Joffcom thats really fast response, yeap no problem, i downgrade to 0.191.1 and back to normal again, will wait until fixed and will upgrade again 😎🤟

**Comment by Joffcom** [comment]
Hey @eontrix, 

The fix for this one is in this PR: https://github.com/n8n-io/n8n/pull/3967 it should be part of the next release. For now I will get this one marked as solved.
