### ISSUE TITLE
ClickupTrigger fails after receiving updates

### ISSUE THREAD

**Issue by matthijs166** [n8n-io/n8n#3959]
**Describe the bug**
When I'm listening to click-up events with the ClickupTrigger node noting is coming in.

When I'm fetching the active webhook it has a fail inside the health object:
```
{
  "webhooks": [
    {
      "id": "********-********",
      "userid": *********,
      "team_id": *******,
      "endpoint": "https://*******/webhook/4ff25fa0-************/webhook",
      "client_id": "****************",
      "events": [
        "taskStatusUpdated"
      ],
      "task_id": null,
      "list_id": null,
      "folder_id": null,
      "space_id": null,
      "health": {
        "status": "failing",
        "fail_count": 1
      },
      "secret": "****************"
    }
  ]
}
```

**To Reproduce**

1. Create a workflow
2. Add the ClickupTrigger node
3. Add your auth method (OAuth or access token both don't work)
4. Listen for events and wait... or start the flow
5. Fetch all the active webhooks and see that the fail count is now +1

**Expected behavior**
I expect that data is coming in.

**Environment (please complete the following information):**
- Ubuntu 22
- "n8n": "^0.192.2"
- Node.js v17.9.0
- Database system SQLite
- Operation mode own

**Additional context**
When I change the webhook URL to https://webhook.site/ the data is still coming in.

Als tried running it in the docker container. Got the same error

Also saw that de response is verified here:
https://github.com/n8n-io/n8n/blob/0ecbb4a19d0087844053a1f4a01fe9ddbcea3101/packages/nodes-base/nodes/ClickUp/ClickUpTrigger.node.ts#L332-L335
Remove this and got the same problem except now I could send a request in with postman.
Maybe we can return an error here if the signature is not correct?

**Comment by Joffcom** [comment]
Hey @matthijs166,

Is the url correct that is listed in ClickUp?

I have checked a test workflow I had from before and it appears to be working but the instance is on an older version.

If you use the test webhook does it work? Does ClickUp happen to list the reason for the failure as well?

**Comment by matthijs166** [comment]
@Joffcom yes the url is correct and works when I send a postman request to the endpoint with removed signature check

Clickup doesn't give me more info about the error

**Comment by matthijs166** [comment]
@Joffcom On what version did you test it? Im going to check if I got the same with that older version

**Comment by matthijs166** [comment]
Found the issues... It was the bot protection service of cloudflare.
I disabeld this on my domain config in Cloudflare under Security > Bots
