### ISSUE TITLE
IF Node "Is Not Empty" not the contraty than "Is Empty"

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#3982]
I noticed many times that the IF Node and Switch Node using the "Is Empty" condition is working fine. 

Normally I suppose that the "Is Not Empty" condition should be just the opposite, but it is behaving randomly strange and is not reliable giving the opposite results.

To solve this and get reliability I then use the "Is Empty" condition and use the other output, but I guess that is a bug to get rid of.

**Comment by Joffcom** [comment]
Hey @prononext,

Do you have a workflow that reproduces this issue?

**Comment by Joffcom** [comment]
Hey @prononext,

For now I am going to mark this one as closed and if you do manage to pop an example workflow together that reproduces this we can open it again.
