### ISSUE TITLE
Docker Image Bug

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#3989]
**Describe the bug**

Error after upgrade

/bin/busybox:1
ELF
^

SyntaxError: Invalid or unexpected token
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1055:15)
    at Module._compile (node:internal/modules/cjs/loader:1090:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 18.04]
- n8n Version [e.g. 0.119.0]
- Node.js Version [e.g. 14.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by luizeof** [comment]
@janober docker image `n8nio/n8n:latest-debian` works well ... but `n8nio/n8n:latest` was broken

**Comment by netroy** [comment]
@luizeof what architecture are you on? amd64 or arm64?

**Comment by wifiuk** [comment]
i also have this issue, using docker on synologynas

**Comment by wifiuk** [comment]
![image](https://user-images.githubusercontent.com/3785545/187850536-ee5cdb04-bce5-4847-9f08-0deeaf8e0ab7.png)

**Comment by ovizii** [comment]
jepp. getting this error after the last upgrade:

`/bin/busybox:1                                                                                                                                  ││   ELF                                                                                                                                             ││   ^                                                                                                                                               ││   2022-09-01T06:58:03.036970452Z                                                                                                                  ││   SyntaxError: Invalid or unexpected token                                                                                                        ││       at Object.compileFunction (node:vm:360:18)                                                                                                  ││       at wrapSafe (node:internal/modules/cjs/loader:1055:15)                                                                                      ││       at Module._compile (node:internal/modules/cjs/loader:1090:27)                                                                               ││       at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)                                                                 ││       at Module.load (node:internal/modules/cjs/loader:1004:32)                                                                                   ││       at Function.Module._load (node:internal/modules/cjs/loader:839:12)                                                                          ││       at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)                                                       ││       at node:internal/main/run_main_module:17:47                               `

**Comment by netroy** [comment]
@wifiuk what model of the synology nas do you have? we need to know if this is an issue on the arm64 builds or armv7 builds.

**Comment by netroy** [comment]
@ovizii can you please share more info on 
* operating system/device are you running n8n on
* if you are running n8n via docker, docker-compose, portainer, or something else.

**Comment by ovizii** [comment]
> @ovizii can you please share more info on
> 
> * operating system/device are you running n8n on
> * if you are running n8n via docker, docker-compose, portainer, or something else.

running image: n8nio/n8n:latest   on a debian 11 host via docker-compose - happy to share the compose file if needed.

**Comment by wifiuk** [comment]
> @wifiuk what model of the synology nas do you have? we need to know if this is an issue on the arm64 builds or armv7 builds.


ds918+ synology

CPU: INTEL Celeron J3455

**Comment by wifiuk** [comment]
ive had to drop back to 

`n8nio/n8n:0.192.2`

to get it working again

**Comment by netroy** [comment]
@wifiuk @ovizii @luizeof Can you please try again with `n8nio/n8n:0.193.2`?

**Comment by ovizii** [comment]
> @wifiuk @ovizii @luizeof Can you please try again with `n8nio/n8n:0.193.2`?

Works. Thanks for looking into it! 
I guess some time later we can switch back to the latest tag.

**Comment by netroy** [comment]
@ovizii `0.193.2` is `latest` now. you can already switch back to using `latest` :slightly_smiling_face:

**Comment by luizeof** [comment]
@netroy thanks for listening. I started my day now.

I use Debian 11, AMD64.

I'm confirming that the latest image is stable again.

**Comment by wifiuk** [comment]
confirmed working on synologynas using v0.193.2

**Comment by bruddlee** [comment]
@netroy @wifiuk @luizeof @tcurdt 

I also have this issue when using the folder in /docker/images/n8n-custom to build a docker image. It build successfully, but when trying to run it via docker-compose using the folder /docker/compose/withPostgres. 

It runs successfully when using this command I found in a readme file in the docker folder: 
``` 
docker run -it --rm \
	--name n8n \
	-p 5678:5678 \
	-e DB_TYPE=postgresdb \
	-e DB_POSTGRESDB_DATABASE=<POSTGRES_DATABASE> \
	-e DB_POSTGRESDB_HOST=<POSTGRES_HOST> \
	-e DB_POSTGRESDB_PORT=<POSTGRES_PORT> \
	-e DB_POSTGRESDB_USER=<POSTGRES_USER> \
	-e DB_POSTGRESDB_SCHEMA=<POSTGRES_SCHEMA> \
	-e DB_POSTGRESDB_PASSWORD=<POSTGRES_PASSWORD> \
	-v ~/.n8n:/home/node/.n8n \
	n8nio/n8n \
	n8n start

```

I'm not sure what needs to be changed in the compose file to get this to work. For a bit I thought the issue was changes I made in doing some testing. But I have tested this with a fresh clone of the master branch using git clone and get the same error as shown above with the other people in thread. Any help here is appreciated :)

**Comment by netroy** [comment]
@bruddlee can you please check if the volume in your docker compose file is mounted on `/home/node` or `/home/node/.n8n`. If it's the first one, you'd have issues with the custom image, as the compiled code is also mounted in that folder.
I'm working on moving that to another folder, and I can send you a branch name, if you'd like to help test.

**Comment by bruddlee** [comment]
@netroy
It looks to me like it's going to the correct folder. For verification I've included the code below. Thanks a ton for the help. I'd be happy to help test. Just let me know what you'd like for me to do. 
 
Here is my docker compose file:
`version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8n-clean-3
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    command: /bin/sh -c "n8n start --tunnel"
    depends_on:
      postgres:
        condition: service_healthy
`

**Comment by netroy** [comment]
@bruddlee Can you please test if this PR fixes this issue for you? https://github.com/n8n-io/n8n/pull/4924

**Comment by bruddlee** [comment]
@netroy 
When I build the image, I get no errors. But I still get the ELF error when trying to run the image using the docker compose in /docker/compose/withPostgres
I edit the image line and add the freshly built n8n-custom image in the compose file and it gives me error when doing docker compose up. The postgres runs fine, just not the custom n8n image.

**Comment by netroy** [comment]
@bruddlee can you please update your `command` from `command: /bin/sh -c "n8n start --tunnel"` to `command: n8n start --tunnel` in the compose file?

**Comment by bruddlee** [comment]
This gives me a new error. no longer ELF but it now says this:
```
n8n_1       | node:internal/modules/cjs/loader:988
n8n_1       |   throw err;
n8n_1       |   ^
n8n_1       | 
n8n_1       | Error: Cannot find module '/home/node/n8n'
n8n_1       |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
n8n_1       |     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
n8n_1       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
n8n_1       |     at node:internal/main/run_main_module:22:47 {
n8n_1       |   code: 'MODULE_NOT_FOUND',
n8n_1       |   requireStack: []
n8n_1       | }

```
