### ISSUE TITLE
Sharing files on nextcloud creates a new share link per n8n run

### ISSUE THREAD

**Issue by despens** [n8n-io/n8n#3998]
**Describe the bug**
When sharing files on nextcloud, each sharing call creates a new share link. This happens even though the sharing parameters are exactly the same each run. These share links pile up in the user interface, too. Currently there is no way in n8n to check if a file is already shared to avoid sharing it again.

![Screenshot-20220901143321-357x263](https://user-images.githubusercontent.com/571494/187916354-d824b4f6-2a20-484a-83e0-e7e78d6446d0.png)

**To Reproduce**

1. Create an automation that selects a file on your nextcloud and share it.
2. Run the automation multiple times.

**Expected behavior**
If a file is already shared with the requested parameters, the previous share link should be returned rather than creating a new one.

**Environment (please complete the following information):**

- Official n8n docker container, version 0.193.2

**Additional context**
- nextcloud version 24.0.3

**Comment by Joffcom** [comment]
Hey @despens,

I will need to check the NextCloud API docs but this could be "by design" which may not be ideal, I have set aside a bit of time to take a look in the morning.

**Comment by despens** [comment]
Thank you @Joffcom! Perhaps this could be solved on the n8n side if there was an API to get information about a file by id or path includes the possible share links? Then it could be solved via a few n8n nodes.

**Comment by Joffcom** [comment]
Hey @despens,

So it looks like the API does support getting shares for a file so maybe a solution could be to add a new operation to the file resource like `get shares` or something that can return the URLs if they exist that way you would still be free to create hundreds of different share urls if you wanted to.

I think this does change this one from an issue to a feature request though so I will get this one closed, I am going to add it to our internal product ideas list as well so when / if we overhaul the Nextcloud node we can look at adding this as a new feature.

As a temporary solution (Example workflow at the bottom) what you can do is use the HTTP Request node to get the shares first, If you select Predefined Credential Type > Next Cloud API then select your credentials in the dropdown, Set the URL to `https://nc24.yourdomain.com/ocs/v2.php/apps/files_sharing/api/v1/shares`then add a header of `OCS-APIRequest` with a value of `true` and then finally add a query parameter of `path` with a value that matches the path to the file you are after this will return the share information.

Let me know if you have any questions on this one :)

<details>
<summary>Example Workflow</summary> 

```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "0eee1d48-54f0-4cc3-8eba-0724c89e6d4b",
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        400
      ]
    },
    {
      "parameters": {
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "nextCloudApi",
        "url": "={{$json[\"nextCloudURL\"]}}/ocs/v2.php/apps/files_sharing/api/v1/shares",
        "options": {},
        "headerParametersUi": {
          "parameter": [
            {
              "name": "OCS-APIRequest",
              "value": "true"
            }
          ]
        },
        "queryParametersUi": {
          "parameter": [
            {
              "name": "path",
              "value": "/Nextcloud Manual.pdf"
            }
          ]
        }
      },
      "id": "9fab26a5-3f7e-4c2a-ac8b-24c79cc10e13",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 2,
      "position": [
        580,
        400
      ],
      "credentials": {
        "nextCloudApi": {
          "id": "98",
          "name": "NC24"
        }
      }
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "nextCloudURL",
              "value": "https://nc24.yourdomain.com"
            }
          ]
        },
        "options": {}
      },
      "id": "4135a1ad-07ca-44fb-9f98-b461d14e55b2",
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        400,
        400
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

</details>
