### ISSUE TITLE
n8n tries to access "Anwendungsdaten"

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#4007]
**Describe the bug**

I have had this strange error for a while. It still doesn't make sense to me and I currently use Linux under Windows to test things.
After I completely rebuilt my PC I thought I could try it again.
But as soon as you start n8n it looks for the folder "Anwendungsdaten" (German) which of course does not exist.
Note here "C:\Users" which is not German.

![grafik](https://user-images.githubusercontent.com/44057030/188086188-450eb7e3-9724-4774-8233-f89cc2e35ad2.png)

**To Reproduce**

Strangely enough, I can't mirror it on any computer. Unfortunately, I currently have no idea what the problem is and how to reproduce it. Since I have a completely rebuilt PC as well as another PC, it makes no sense.
I have already changed the language of the operating system and many other things.

**Expected behavior**

That it works the same way as on the other computers.

**Environment (please complete the following information):**

- OS: Windows 10 Pro 21H2
- n8n Version 0.193.3
- Node.js Version v16.17.0
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @lublak,

Thanks for reporting this one, I remember we had a quick chat about it on Discord and I have also not been able to reproduce it. @ivov do you have any thoughts on this one?

**Comment by Joffcom** [comment]
Hey @lublak,

Couple of questions for you that I don't think we covered before...

You said it is only this machine that has an issue, Is there anything different about it and how you use Node processes (sandbox, nvm)? Maybe a different AV or it is part of a domain / device management system? When you installed n8n what npm options did you use as well?

**Comment by lublak** [comment]
@Joffcom 

Unfortunately not. I have the same installation of nodejs.
https://nodejs.org/dist/v16.17.0/node-v16.17.0-x64.msi
My computer at home is not in the domain (which has these problems), the one at work is in a domain.
`npm install -g n8n`
It is the only command I execute.
So nothing special here.

As long as no one else encounters this problem, we can just leave it as it is. I'm fine with Linux. And in the next few months I'll be getting a new private PC here, too. Maybe it will be functional there again.
Of course, it would be interesting to know what the problem is.

**Comment by Joffcom** [comment]
Hey @lublak,

That rules out some of the other options I thought it could be, I am going to get an internal ticket created so we can look into this a bit more as it is very strange.  Any AV running on it or just Defender?

**Comment by lublak** [comment]
Just default windows defender

**Comment by netroy** [comment]
I suspect [this](https://github.com/shelljs/shelljs/issues/1095) ShellJS issue is the cause.
