### ISSUE TITLE
[HTTP Request Node] The expression in the `URL` does not work

### ISSUE THREAD

**Issue by theuargb** [n8n-io/n8n#4021]
**Describe the bug**
When you run requests via HTTP Request Node in batches, the expression in the url address stops resolving data and only results in constant parts

**To Reproduce**

1. Create HTTP Request Node with multiple input items
2. Configure `URL` as an `expression` with ref to the outer node - in my case =`{{$node["CONFIG"].json["magentoBaseUrl"]}}/rest/{{$node["CONFIG"].json["storeCode"]}}/V1/inventory/sources`
3. Configure 0 < `Batch Size` Option < count(input) - in my case = `5` 
4. Configure `Batch Interval` Option > 0 - in my case = `3000`
5. See an error

**Expected behavior**
URL of any request equals the result of the expression.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 on WSL2 Windows 11
- n8n Version: 0.193.3
- Node.js Version: 16.17.0
- Database system: SQLite (default)
- Operation mode: own (default)

**Additional context**
![image](https://user-images.githubusercontent.com/83121880/188413151-600df2d6-a981-4794-8d46-6e6f22103a8d.png)

**Comment by theuargb** [comment]
Researching behavior I found `packages/nodes-base/nodes/HttpRequest/HttpRequest.node.ts:812`
```const url = this.getNodeParameter('url', itemIndex) as string;```
wich trying to get the 2nd+ items on the CONFIG node with just one.

I replaced autogenerated expression fragments in the URL with hand-crafted ones as `{{$items("CONFIG", 0)[0].json["magentoBaseUrl"]}}/rest/{{$items("CONFIG", 0)[0].json["storeCode"]}}/V1/inventory/sources` and it works perfectly fine :)

**Comment by Joffcom** [comment]
Hey @theuargb,

This is one of those things that we are aware of, So most nodes will loop the input items so in your case it would be 57 loops of the true input items but if you are referencing a node that isn't the if node it will try to use the index from the input. They way you have found to get around it is one method and in the future we will have a paired items feature available that should also help.

**Comment by Joffcom** [comment]
Hey @theuargb,

I am just going through some old issues and this one is by design at the moment and not really a bug, For now I am going to mark this one as closed and if needed we can open it again in the future.
