### ISSUE TITLE
AWS Lambda messed up in 0.193.3

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#4027]
**Describe the bug**
Hello! After upgrading n8n from 0.185.0 to 0.193.3 AWS lambda (python) node gets broken. In the 0.185.0 the payload of the node has been treated by Python Lambda as a **dict** class (native object for JSON). In the 0.193.3 it became a **string**, so now to fix the issue, I need to rewrite all lambdas to convert a string to dict class prior getting any information from it.

So it seems that prior to send the payload to the Lambda, n8n converts it with JSON.stringify() explicitly.

**To Reproduce**

1. Create a simple AWS Lambda function:
```python
import json

def lambda_handler(event, contex):
    return event.get('test', {})
```

2. Create n8n node with Lambda and JSON code:
`{"test": "some value"}`

**Expected behavior**
The output will be "some value"

**Actual behavior:**
An error that str object does not have the 'get' method

**Environment (please complete the following information):**

- n8n Version: 0.193.3

**Comment by Joffcom** [comment]
Hey @barn4k,

Thanks for reporting this one, I have just put in a PR that has resolved this issue in testing 👍🏻
