### ISSUE TITLE
result is not iterable in Postgress node response in 0.193.2

### ISSUE THREAD

**Issue by ismanapa** [n8n-io/n8n#4035]
**Describe the bug**
After updating to version 0.193.2 the Postgress node throws the "result is not iterable" error in insert operations. The error only appears in "insert" operations and not in "raw" queries.

I have made a rollback to version 0.191.0 and the error has disappeared.

**To Reproduce**

1. Create a node of Postgress
2. Configure it to make an "insert" operation
![image](https://user-images.githubusercontent.com/10558907/188609434-73de19fd-4ee7-4d64-abdf-431ef462be1e.png)
3. Start workflow and receive "result is not iterable error"
![image](https://user-images.githubusercontent.com/10558907/188609660-d51d78f3-47f9-4f34-aca9-4728372120ed.png)

**Expected behavior**
Before updating to version 0.193.2 we obtain the result of the insert operation.

![image](https://user-images.githubusercontent.com/10558907/188610285-7fad3960-2e88-4dbc-b0ca-b3ac2891562d.png)

**Environment (please complete the following information):**

- OS: Ubuntu Linux 18.04
- n8n Version: 0.193.2
- Node.js Version: v16.17.0
- Database system: postgress
- Operation mode queue

Thanks for the work and support :)

**Comment by krynble** [comment]
Hey @ismanapa thank you for reporting this!

We have fixed this issue yesterday on this pr https://github.com/n8n-io/n8n/pull/4020

It will be released in a next version (possibly today).

**Comment by ismanapa** [comment]
Thanks!

You are awesome! 😁
