### ISSUE TITLE
lintfix removes declarative properties during n8n-nodes-base/node-param-options-type-unsorted-items 

### ISSUE THREAD

**Issue by geckse** [n8n-io/n8n#4037]
**Describe the bug**

When running npm run lintfix and having wrong ordered (not alphabetical) options and the linter tries to fix it be reordering it, it removes the ```routing```  property e.g.

**To Reproduce**

1. Have a Node with more than options on operation property. The options need to be wrong ordered.
Like here:
```
{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,

		displayOptions: {
			show: {
				resource: ['httpVerb'],
			},
		},
		options: [
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a record from a table',
				description: 'Delete a record from a table',
				routing: {
					request: {
						method: 'POST',
						url: '/delete',
					},
				},
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create new records in a table',
				action: 'Create new records in a table',
				routing: {
					request: {
						method: 'POST',
						url: '/create',
					},
					send: {
						paginate: false,
						type: 'body',
					},
				},
			},
			
			{
				name: 'List',
				value: 'list',
				action: 'List data from a table',
				description: 'List the data from a table',
				routing: {
					request: {
						method: 'GET',
						url: '/list',
					},
				},
			},
			{
				name: 'Read',
				value: 'read',
				action: 'Read data from a record',
				description: 'Read the data from a record',
				routing: {
					request: {
						method: 'GET',
						url: '/get',
					},
				},
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update the data of a record in a table',
				action: 'Update the data of a record in a table',
				routing: {
					request: {
						method: 'POST',
						url: '/update',
					},
					send: {
						paginate: false,
						type: 'body',
					},
				},
			},


		],
		default: 'list',
	},
```
2. run ```npm run lintfix```

**Expected behavior**
The routing property should not be dropped, since it removes the functionality.

**Environment (please complete the following information):**

- OS: macOS 12.2.1
- n8n Version 0.190.0
- Node.js Version v14.19.3
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @geckse,

Thanks for reporting this one, This is the issue tracker for the n8n application the linter has it's own repo and issues board which can be found here: https://github.com/ivov/eslint-plugin-n8n-nodes-base

Would you be able to create this issue on that project?

**Comment by geckse** [comment]
Ok transfered it to https://github.com/ivov/eslint-plugin-n8n-nodes-base
