### ISSUE TITLE
Typeform Trigger: only the last question-answer pair is delivered

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#404]
**Describe the bug**
Typeform Trigger: within a list of nested questions/answers, only the last question-answer pair is delivered. 

**To Reproduce**
1. Create new Typeform Trigger
2. Create Typeform with nested questions
3. Setup Tyeoform to post to n8n
4. Fill out questionnaire with nested questions
5. Trigger receives correct payload but only shows the last question-answer pair from the nested question set

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Alpine / Docker
 - n8n Version 0.58
 - Node.js Version 12.16

**Additional context**
You can compare result with a webhook trigger, which receives the full payload correctly.

**Comment by RicardoE105** [comment]
Hey, @frane thanks for writing that up.

I have not been able to replicate this. You said "nested questions" did you mean question groups?

I set up a form like this:

![image](https://user-images.githubusercontent.com/16496553/77569457-9c0ad600-6ea0-11ea-8b6c-3acb7418e181.png)

The trigger gets the following data:

![image](https://user-images.githubusercontent.com/16496553/77569577-ca88b100-6ea0-11ea-80fd-bb817da40bad.png)

**Comment by frane** [comment]
Seems the issue is affecting conditional groups (see screenshot).
<img width="644" alt="Screenshot 2020-03-26 at 09 20 58" src="https://user-images.githubusercontent.com/35420/77665561-1d856580-6f80-11ea-97e0-83d0c02d766e.png">

Example:

1. Group Product 1:
  - Name:
  - Price:
  - Enter another product: Y/N
2. Group Product 2: 
  - Name:
  - Price:
  - Enter another product: Y/N
3. Group Product 3: 
  - Name:
  - Price:
  - Enter another product: Y/N

E.g. if you answer the question "Enter another product" with no, the next product group is skipped. If you answer it with yes, you need to fill out the next group. However, we _only see the payload for the last answered group_.

**Comment by frane** [comment]
@RicardoE105 I cannot reproduce the issue anymore and also I'm currently not using Typeform. So feel free to close this.

**Comment by krynble** [comment]
Thanks for the update @frane 

If you encounter this or any other issue in the future do not hesitate to reopen or create a new issue.
