### ISSUE TITLE
Mailjet - Send Template: Template id shouldn't be a string but an integer

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#405]
**Describe the bug**
Mailjet - Send Template: Template id shouldn't be a string but an integer.

**To Reproduce**
1. Create transactional template in MailJet
2. Get template ID for configuration in n8n
3. In n8n configure MailJet node to send template with template ID
4. On sending / executing  MailJet API will respond with an error, as the template ID is sent as a *string* but the API *expects a number*.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Alpine / Docker
 - n8n Version 0.58
 - Node.js Version 12.16

**Comment by janober** [comment]
Fix got released with n8n@0.59.0
