### ISSUE TITLE
GoogleSheet node: Lookup Operation fails on empty fields

### ISSUE THREAD

**Issue by frane** [n8n-io/n8n#406]
**Describe the bug**
The Lookup operation fails on empty fields

**To Reproduce**
1. Create a new Google Sheet.
2. Name cell A1 "TEST"
3. Fill in cells A2 and A4 with values 2 and 4, leave A3 empty
4. Set up a Google Sheet node with 
    - Operation: Lookup
    - Sheet ID: <your sheet ID>
    - Range: Sheet1!A:B
    - Data Start Row: 1
    - Key Row: 0
    - Lookup Column: TEST
    - Lookup value: 4

**Expected behavior**
The node should return a payload with the row 4, containing something like { "TEST": 4 }. Instead |TypeError: Cannot read property 'toString' of undefined" is returned.

**Environment (please complete the following information):**
 - OS: Alpine / Docker
 - n8n Version 0.58
 - Node.js Version 12.16

**Additional context**
I've traced the issue back to https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Google/GoogleSheet.ts#L447.
```inputData[rowIndex][returnColumnIndex].toString()``` should be ```(inputData[rowIndex][returnColumnIndex] || "").toString()``` to fix the issue.

**Comment by janober** [comment]
Fix got released with n8n@0.59.0
