### ISSUE TITLE
Merge by key is not working

### ISSUE THREAD

**Issue by draglabs** [n8n-io/n8n#4074]
**Describe the bug**
Merge by key is not working
**To Reproduce**
Attempt to merge two json bodies by key/ 

Copy the below json code and paste it into N8N
`
{
  "meta": {
    "instanceId": "f77575586270e9ffb47a9d1567d0363244ad4b86ffa0d36369032fdb3af7fd7d"
  },
  "nodes": [
    {
      "parameters": {
        "mode": "mergeByKey",
        "propertyName1": "email",
        "propertyName2": "email"
      },
      "id": "62d16d53-93a4-489a-8f09-67a3054001a3",
      "name": "Merge2",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        2220,
        -1360
      ]
    },
    {
      "parameters": {
        "functionCode": "// Code here will run only once, no matter how many input items there are.\n// More info and help: https://docs.n8n.io/nodes/n8n-nodes-base.function\n// Tip: You can use luxon for dates and $jmespath for querying JSON structures\n\n// Loop over inputs and add a new field called 'myNewField' to the JSON of each one\nitems = [\n  {\n    \"email\": \"buider_16DigitHex@placeholder.email\",\n    \"quizMetafields\": \"apples\"\n  }\n]\n\n// You can write logs to the browser console\nconsole.log('Done!');\n\nreturn items;"
      },
      "id": "eda2e2a4-9bcd-4bcc-9b9f-48fa90b49775",
      "name": "Function1",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        1940,
        -1420
      ]
    },
    {
      "parameters": {
        "functionCode": "// Code here will run only once, no matter how many input items there are.\n// More info and help: https://docs.n8n.io/nodes/n8n-nodes-base.function\n// Tip: You can use luxon for dates and $jmespath for querying JSON structures\n\n// Loop over inputs and add a new field called 'myNewField' to the JSON of each one\nitems = [\n  {\n    \"email\": \"buider_16digithex@placeholder.email\",\n    \"id\": \"gid://shopify/Customer/6316482330785\",\n    \"metafields\": \"oranges\"\n  }\n]\n\n// You can write logs to the browser console\nconsole.log('Done!');\n\nreturn items;"
      },
      "id": "20bac20f-82db-495c-9614-01ca1f8ec017",
      "name": "Function2",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        1940,
        -1280
      ]
    },
    {
      "parameters": {},
      "id": "472f3161-1204-4be6-aaf3-887e8218c183",
      "name": "NoOp1",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1640,
        -1360
      ]
    }
  ],
  "connections": {
    "Function1": {
      "main": [
        [
          {
            "node": "Merge2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Function2": {
      "main": [
        [
          {
            "node": "Merge2",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "NoOp1": {
      "main": [
        [
          {
            "node": "Function1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Function2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
`

**Expected behavior**
This should return a body combining the json data of input 1 with input 2
**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.x]
- n8n Version [e.g. 0.193.5]
- Node.js Version [e.g. 18.8.0]
- Database system [e.g. POSTGRES]
- Operation mode [e.g. own; operation modes are `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @draglabs,

The node appears to be working as expected, It took me a bit longer than expected to find the issue in the flow but in your first function you have an email of `buider_16DigitHex@placeholder.email` and the second one has `buider_16digithex@placeholder.email` it looks like the case of the emails are different and the key check for the merge node is case sensitive.

Can you test again using the same case and let me know if it works for you, If all is good we can open a separate feature request internally to maybe have an option to ignore case for key matches. As a manual solution when getting the data you can convert it to upper or lowercase to get around the issue.

**Comment by draglabs** [comment]
Awww snaps good catch! Thanks for taking a look!

**Comment by Joffcom** [comment]
@draglabs no worries, I will make this one as closed 👍
