### ISSUE TITLE
Error when `npm run start`

### ISSUE THREAD

**Issue by samuelmtimbo** [n8n-io/n8n#41]
I just tried to run the repository locally and got the following error: 

<img width="706" alt="Screen Shot 2019-10-08 at 3 21 14 PM" src="https://user-images.githubusercontent.com/5302127/66422134-83386200-e9df-11e9-8887-ef0ad4341c51.png">

I felt it was important to share and I wasn't able to find any related issue.

**Comment by mjhea0** [comment]
I think you need to:

```sh
$ packages/cli
$ npm run build
$ npm start
```

**Comment by mjhea0** [comment]
Disregard, this is how you get started for development: https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#actual-n8n-setup

**Comment by janober** [comment]
@samuelmtimbo Did what @mjhea0 suggest work?

Thanks a lot @mjhea0 !

**Comment by samuelmtimbo** [comment]
@janober it did! Thank you @mjhea0! Perhaps these steps should be referenced on README.md?

**Comment by janober** [comment]
@samuelmtimbo Great to hear!

I just checked it is already referenced. Regular users do not have to do that, only users who want to develop for n8n. And for those do the `README.md` files have a special "Development Setup" section on the bottom and that one links to the `CONTRIBUTING.md` which describes the setup.
