### ISSUE TITLE
Microsoft Sql Node returns Error when update updates something

### ISSUE THREAD

**Issue by Autoradiowecker** [n8n-io/n8n#4104]
**Describe the bug**
When I use the "Microsoft Sql" Node to update a Database we get the following Error:
"TypeError: Cannot read properties of undefined (reading 'json')
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/NodeExecuteFunctions.js:851:18
    at Array.forEach (<anonymous>)
    at Object.returnJsonArray (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/NodeExecuteFunctions.js:850:14)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Microsoft/Sql/MicrosoftSql.node.js:311:84)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:598:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:557:53"
I use the Execute Query Operation. 
The Database update gets passed through without problems. Just the n8n Error is the problem.

The Node was working as expected befor update **0.193.5**

**To Reproduce**

1. create a Microsoft sql Node
2. select valid credential
3. pick Execute Query option
4. update Database

**Expected behavior**
Get an Json with Error Successful 

**Environment (please complete the following information):**

- OS: latest Docker Image
- n8n Version 0.193.5
- Database system MS Sql

**Comment by Joffcom** [comment]
Hey @Autoradiowecker, 

Thanks for reporting his one, It should be fixed in the next release the PR if you are interested can be found here: https://github.com/n8n-io/n8n/pull/4067

**Comment by janober** [comment]
Fix got released with `n8n@0.194.0`

**Comment by Autoradiowecker** [comment]
Thanks for the quick reply
