### ISSUE TITLE
OAuth2 Not implemented error

### ISSUE THREAD

**Issue by tomaszkiewicz** [n8n-io/n8n#4132]
**Describe the bug**

While trying to establish OAuth2 credentials for Withings (a producer of smart watches, scales and other devices) I get:

```
{
"code": 0,
"message": "Not implemented",
"hint": ""
}
```

On callback request.

https://n8n.xxxxx/rest/oauth2-credential/callback?code=XXXXXX&state=XXXXXXXXXXXXXXXXX0lKOCIsImNpZCI6IjQifQ%3D%3D

Where state parameter resolves to base64 encoded:

```
{"token":"XXXXXXXXXXXXXXXXXX","cid":"4"}
```

**To Reproduce**

1. Create new generic OAuth2 credentials for HTTP request
2. Grant type: Authorization code
3. Authorization URL: https://account.withings.com/oauth2_user/authorize2
4. Access Token URL: https://wbsapi.withings.net/v2/oauth2
5. Client ID and Client Secret - values generated on Withings portal
6. Scope: user.activity,user.metrics,user.sleepevents
7. Auth URI Query Parameters: empty
8. Authentication: Body (but I tried Header as well)
9. Then I click Connect my account button
10. Go with Oauth authorization on Withings side
11. Get redirected back to my n8n host
12. The I get error as stated at the beginning

**Expected behavior**

Proper OAuth2 flow with saved credentials (like with all other sites)

**Environment (please complete the following information):**

- OS: Amazon Linux 2
- n8n Version 0.193.2
- Node.js Version - the one from n8n container
- Database system MySql
- Operation mode Probably own, I host it as a container on my own server.

**Additional context**

I also tested my n8n instance with connection to https://www.oauth.com/playground/authorization-code.html and it works without any issues.

**Comment by Joffcom** [comment]
Hey @tomaszkiewicz,

I have had a quick look and I also have the same problem but looking on the community forum it looks like someone was able to get this working earlier this year so this could be a configuration issue somewhere or there is an odd bug.

I will look into this more tomorrow.

**Comment by Joffcom** [comment]
Hey @tomaszkiewicz,

You might be able to enable debug logging and see if it outputs anything extra, I have not had a chance to spend more time on this one yet as it seems to be service specific and not a bug with n8n.

**Comment by Joffcom** [comment]
Hey @tomaszkiewicz,

As this one looks to not be a bug with n8n directly I am going to mark this one as closed and we can pick this up on the community support forum if you are still having issues with it.
