### ISSUE TITLE
Seatable Node: Convert Link ID not working

### ISSUE THREAD

**Issue by ampxtreme** [n8n-io/n8n#4155]
**Describe the bug**
Seatable Node: Convert Link ID not working, so I get no results in linked columns.

**To Reproduce**

0. Having a Seatable with Links to other Tables (Like [here](https://cloud.seatable.io/dtable/external-links/f8cbffefa532432e9ca8/?tid=35oe&vid=0000) in column "Goals") 
1. Add a "Seatable" Node. (Credentials to be set).
2. In the Node Options, set: 
- [ ] Resource=Row
- [ ] Operation=Get Many
- [ ] Choose Table Name
- [ ] Add Option: Convert Link ID
- [ ] Set "Convert Link ID" to True
3. Execute Node and look in the Results.

**Expected behavior**
The Columns with Links to other tables should have content, but as soon as "Convert Link ID" == True, we see no result. Without it we only see the ID of the entry.

**Environment (please complete the following information):**

- OS: [Ubuntu]
- n8n Version [0.194.0]
- Database system [postgres]

**Additional context**
I have also asked in the forum of Seatable, but it seems like it could be a bug on N8N (node) side. Discussion in Forum: 
[N8N Seatable.](https://forum.seatable.io/t/convert-link-id-from-n8n-not-working/1636)

**Comment by Joffcom** [comment]
Hey @ampxtreme,

Thanks for the report, I have taken a quick look and I can see the issue and have fixed it locally. I will get a PR created shortly for internal review so we can get this one closed.

It looks like we were not checking the object types and were just ignoring them in the output.

**Comment by ampxtreme** [comment]
Thank you very much! 😃

**Comment by ampxtreme** [comment]
Thanks for the fix / merge. I´ve tested it and it works.
