### ISSUE TITLE
Latest version error on migration with postgres

### ISSUE THREAD

**Issue by OlivierMary** [n8n-io/n8n#4163]
**Describe the bug**
Error at startup:
Migration "CreateCredentialsUserRole1660062385367" failed, error: relation "role" does not exist
2022-09-21T16:21:15.099Z | error    | There was an error initializing DB: "relation "role" does not exist" "{ file: 'start.js' }"

and this relation exist. but the schema missing I the request.

**To Reproduce**

1. Just start to the new version with a postgres db

**Expected behavior**
no error at startup

**Environment (please complete the following information):**

- OS: Ubuntu 18.04.6 LTS
- n8n Version latest
- docker image
- Database system postgres

**Additional context**

A rapid analyse:
on this file : https://github.com/n8n-io/n8n/blob/97cd564f7b4c5ba1472e517e0d54897b2cabcc26/packages/cli/src/databases/migrations/postgresdb/1660062385367-CreateCredentialsUserRole.ts
there are missing something like:
```ts
			const tablePrefixPure = tablePrefix;
			const schema = config.getEnv('database.postgresdb.schema');
			if (schema) {
				tablePrefix = schema + '.' + tablePrefix;
			}

```

**Comment by Joffcom** [comment]
Hi @OlivierMary,

Thanks for reporting this one, I have just popped a message internally about it and we should have it fixed shortly.
