### ISSUE TITLE
Error After Upgrade using MySQL

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4165]
**Describe the bug**

Migration Error after upgrade N8N.

Running [postgres](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/databases/migrations/postgresdb/1660062385367-CreateCredentialsUserRole.ts#L17) `ON CONFLICT DO NOTHING` [on a mysql migration](https://github.com/n8n-io/n8n/blob/master/packages/cli/src/databases/migrations/mysqldb/1660062385367-CreateCredentialsUserRole.ts#L13). I believe `INSERT IGNORE` is more appropriate.

```
Initializing n8n process
UserSettings were generated and saved to: /home/node/.n8n/config
Migration "CreateCredentialsUserRole1660062385367" failed, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 3
There was an error initializing DB: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONFLICT DO NOTHING' at line 3"
Stopping n8n...
```

**To Reproduce**

1. Upgrade N8N using Docker

**Expected behavior**

SQL command corresponding to MySQL on migrations

**Environment (please complete the following information):**

- OS: Debian / Docker
- n8n Version 0.195.0
- Node.js Version [e.g. 14.16.0]
- Database system MySQL
- Operation mode : queue

**Additional context**

**Comment by luizeof** [comment]
ping @Joffcom @janober

**Comment by Joffcom** [comment]
Hey @luizeof,

Created PR here: https://github.com/n8n-io/n8n/pull/4166
