### ISSUE TITLE
Wehbook URL switch to localhost when using PM2

### ISSUE THREAD

**Issue by melakhvision** [n8n-io/n8n#4167]
**Describe the bug**
When I run n8n with n8n the webhooks URL is set to the subdomain
But when I start n8n with PM2 it switched back the webhooks URL to local.

**To Reproduce**
```
export N8N_HOST=auto.mydomain.br
export N8N_PROTOCOL=https
export NODE_ENV=production
pm2 start n8n

```

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 18.04]
- n8n Version [0.195.1]
- Node.js Version [e.g. 16]
- Database system [SQLite]

**Additional context**

**Comment by Joffcom** [comment]
Hey @melakhvision,

I have ran into a few issues in the past when using env variables with PM2, but on a clean install I am not able to reproduce this one. Did you run the pm2 command before maybe? It could be that it needs the `--update-env` option added as well.

It could be worth trying a pm2 config file.

**Comment by fandujar** [comment]
@melakhvision Did you try WEBHOOK_URL env var? It's working for me along with PM2

**Comment by Joffcom** [comment]
Hey @melakhvision,

I am going to mark this one as closed for now as it doesn't appear to be an issue with n8n itself and more of an issue with PM2.

Let me know if you have any questions about this.
