### ISSUE TITLE
Retry execution menu appears in background behind modal window

### ISSUE THREAD

**Issue by christiaanwesterbeek** [n8n-io/n8n#4188]
**Describe the bug**
When clicking on the execution retry button the menu appears in the background (most of the time).
![image](https://user-images.githubusercontent.com/465989/192236205-599d34e1-e9d8-4d8b-b38f-966147a75044.png)

**To Reproduce**

1. Go to 'Executions
2. Filter on some workflow with status=Error
3. Click on red retry button
4. The menu button now appears in the background where you cannot click on it.

**Expected behavior**
The retry menu should appear anchored to the retry button

**Environment (please complete the following information):**

- OS: Mac
- n8n Version 190
- browser: Chrome Latest

**Additional context**
During our session today this problem didn't occur always. Sometimes the menu would appear where you would expect it (anchored to the retry button). But most of the time it was in the top left corner behind de modal. In those cases we had no way of actually retrying (through the UI at least).

**Comment by Joffcom** [comment]
Hey @christiaanwesterbeek,

Can you try upgrading to 0.191.0 (or later) this should fix the issue.

**Comment by Joffcom** [comment]
Hey @christiaanwesterbeek,

As this issue appears to be resolved now I am going to mark this one as closed, If you do happen to see this again let me know and we can open this back up.
