### ISSUE TITLE
JIRA cloud authentication fails with error "Basic authentication with passwords is deprecated."

### ISSUE THREAD

**Issue by thisisthedave** [n8n-io/n8n#4205]
**Describe the bug**
Authenticating with JIRA cloud fails because Atlassian has removed support for username/password header authentication and wants a base64 encoded basic authorization header instead. Jira cloud requests always fail with a 401 HTTP code and error message "Basic authentication ... is deprecated"

```bash
curl -D- \
   -u fred@example.com:freds_api_token \
   -X GET \
   -H "Content-Type: application/json" \
   https://your-domain.atlassian.net/rest/api/2/issue/JIRA-15937
```

**To Reproduce**

1. Create a workflow
2. Add a JIRA node.
3. Click the `Credential` dropdown and select `Create New`
4. Follow the documentation to create an access token in your JIRA account and configure the n8n credential node. It will complain that it cannot connect. Click `Save`
![image](https://user-images.githubusercontent.com/5162625/192377197-fbc526ba-22e0-45df-80d8-81051884e81e.png)
5. Fill the parameters to execute an Issue / Get call and click `Execute node`. The execution fails with the error message "Basic authentication with passwords is deprecated" 
![image](https://user-images.githubusercontent.com/5162625/192377523-c747a617-f3c2-4da3-8389-4a1aa5350e76.png)

**Expected behavior**
Authentication with Jira should not fail when using an API token.

**Environment (please complete the following information):**

- OS: Windows 11
- n8n Version 0.195.5
- Node.js Version v16.15.1
- Database system SQLite
- Operation mode: not sure, probably the default `own`. I'm using the Windows desktop version of n8n

**Additional context**
JIRA deprecation info: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/
JSON payload from Atlassian containing extended error details:
```json
{"message":"401 - \"Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/\\n\"","name":"Error","stack":"Error: Request failed with status code 401\n    at createError (C:\\Users\\magel\\AppData\\Local\\Programs\\n8n\\resources\\app\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n    at settle (C:\\Users\\magel\\AppData\\Local\\Programs\\n8n\\resources\\app\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (C:\\Users\\magel\\AppData\\Local\\Programs\\n8n\\resources\\app\\node_modules\\axios\\lib\\adapters\\http.js:269:11)\n    at IncomingMessage.emit (node:events:406:35)\n    at IncomingMessage.emit (node:domain:470:12)\n    at endReadableNT (node:internal/streams/readable:1331:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
}
```

**Comment by Joffcom** [comment]
Hey @thisisthedave,

That is interesting, from what I can see from a quick look is we are using the updated endpoint so as long as an API token is being used it should work.

When you generated the token did you follow the steps on this page?  Hopefully it is just our doc that needs to be updated.

https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

**Comment by thisisthedave** [comment]
Huh. I could swear I followed those exact instructions. But I just made a new API token, and it's working without problems. Thank you for pushing me in the right direction!
