### ISSUE TITLE
Pipedrive Resolve Properties not working anymore

### ISSUE THREAD

**Issue by moon86** [n8n-io/n8n#4213]
**Describe the bug**
I'm doing a "Get Many" research in the "Deals" with the "Resolve Properties" activated and the answer I received do not have the fields resolved, I have them with their IDs.
I just upgraded from 12 versions earlier, so the bug might be "old"

**To Reproduce**
Send a request to Pipedrive with Resolve Properties activated.

**Expected behavior**
We should get the list of fields by names, not by IDs

**Environment (please complete the following information):**
- OS: [Debian 11]
- n8n Version 0.195.5

Thank you for the help.

**Comment by Joffcom** [comment]
Have created N8N-4782 as our internal reference for this one.

**Comment by moon86** [comment]
Hello @Joffcom ,

Thank your for your help.
Yes the issue seems to be on IDs only.
If this can help, I had to revert back to version 0.193.0 where the bug is still present but in the version 0.192.0 this is working correctly.

**Comment by Joffcom** [comment]
Hey @moon86,

This has been fixed in n8n@0.205.0, I am going to mark this one as closed for now. If you still have the issue after updating let me know.
