### ISSUE TITLE
GitLab Trigger 404 Error

### ISSUE THREAD

**Issue by mark-monteiro** [n8n-io/n8n#4217]
**Describe the bug**
A previous workflow I had working using the GitLab trigger can no longer be activated due to a 404 error returned from the GitLab API when starting the workflow. The following error information is returned in the console output with the label `Request proxied to Axios failed` (I have formatted the error details to be more readable):

```txt
{
    error: Error: Request failed with status code 404
      at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)
      at IncomingMessage.emit (node:events:525:35)
      at IncomingMessage.emit (node:domain:489:12)
      at endReadableNT (node:internal/streams/readable:1358:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      config: {
        url: 'https://gitlab.com/api/v4/projects/senti-solutions%2Fmarketing%2Fyellowstone-website/hooks/13781892',
      method: 'delete',
      data: '{}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      paramsSerializer: [Function (anonymous)],
      timeout: 300000,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      validateStatus: [Function: validateStatus],
      transitional: [Object],
      'axios-retry': [Object]
    },
    request: ClientRequest {
        _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'DELETE /api/v4/projects/senti-solutions%2Fmarketing%2Fyellowstone-website/hooks/13781892 HTTP/1.1
' +
        'Accept: application/json
' +
        'Private-Token: wTov7iR4A6AziBFcfDyi
' +
        'Content-Type: application/json
' +
        'User-Agent: axios/0.21.4
' +
        'Content-Length: 2
' +
        'Host: gitlab.com
' +
        'Connection: close
' +
        '
',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'DELETE',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v4/projects/senti-solutions%2Fmarketing%2Fyellowstone-website/hooks/13781892',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'gitlab.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
        status: 404,
      statusText: 'Not Found',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  },
  file: 'NodeExecuteFunctions.js'
}
```

**To Reproduce**

1. Create a workflow with a GitLab trigger
2. Activate workflow
3. See error

The node triggering the error from my workflow is included below:

```json
{
  "meta": {
    "instanceId": "68735d76c280ad1dfe471a14412290b75ece7bf78b20fcca1d43251a64620fed"
  },
  "nodes": [
    {
      "parameters": {
        "owner": "senti-solutions",
        "repository": "marketing/yellowstone-website",
        "events": [
          "merge_requests"
        ]
      },
      "name": "Gitlab MR (Yellowstone)",
      "type": "n8n-nodes-base.gitlabTrigger",
      "typeVersion": 1,
      "position": [
        440,
        420
      ],
      "webhookId": "5762932c-1aec-4c45-96e1-fdc158815e26",
      "id": "16002b18-29ae-4d34-915a-c67f50dd99b9",
      "credentials": {
        "gitlabApi": {
          "id": "11",
          "name": "Senti Gitlab account"
        }
      }
    }
  ],
  "connections": {}
}
```

**Expected behavior**
The workflow should be activated without error.

**Environment:**

- OS: Docker (host: Ubuntu Linux 20.04.2)
- n8n Version: 0.195.5
- Node.js Version: Docker
- Database system: PostgreSQL
- Operation mode: `own`

**Additional context**
N/A

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

Just to check does the repo exist and the credential being used have access to it?

It could be worth trying an earlier version like 193 or 192 to see if the issue is there as well.

**Comment by mark-monteiro** [comment]
The repo does exist and I have access to it.

I may have also found a workaround for the issue. I took the broken trigger node and duplicated it. The copy of the node appears to work correctly. A new webhook id was generated for the copied node and I deleted the old webhook manually on GitLab's side. Testing the copied webhook works as expected and I am able to activate the workflow without errors.

However, if I rename the copied webhook to match the original node name (the copy has a '1' appended to the name), the exact same error as outlined in my original issue post occurs when I saving changes to the workflow. It appears that for some reason the save action is sending a `DELETE` request to GitLab for the old webhook of the original node (which I already deleted manually).

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

That is a nice bit of detective work there, I will get an internal ticket created so we can work on fixing that.

**Comment by mark-monteiro** [comment]
Great, thanks for looking into it! It might be worthwhile also keeping #2042 in mind while looking at this, it's possible they are closely related. The issue with #2042 is that the webhook on GitLab is duplicated every time the workflow is saved.

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

That is interesting I must have missed that one coming in, I will add a note to the dev ticket so we can go for both at the same time.

**Comment by hintva** [comment]
Hi ! Had same issue than you @mark-monteiro, and found same workaround, but this worked for like a few days, before having the same issue again, so it seems it is repeating, but don't have an idea of the frequency yet or the reason... And since I have about 20 Gitlab triggers this is quite time-consuming... 
Credentials are fine and repo are accessible to us. 
Thank you for submitting this and working on this @Joffcom, hope you will find a solution to this.

**Comment by Joffcom** [comment]
Morning,

I have just fixed this locally and will get a commit in shortly, Just going to take a look at the other issue now and see if it is related.
