### ISSUE TITLE
Airtable Read fails with NOT FOUND

### ISSUE THREAD

**Issue by cromulus** [n8n-io/n8n#4218]
**Describe the bug**
Version:
Using the Airtable node, a read request to a known records fails with  404 "not found".
Using the http node, with the airtable credentials, accessing the same record returns the record.

**To Reproduce**

1. create an Airtable node, that reads a specific record.
2. click on "execute node" 
3. See error

**Expected behavior**
Expected the read node to return the record.

**Environment (please complete the following information):**

- OS: 	Ubuntu 18.04.6 LTS
- n8n Version :  0.195.4
- Node.js Version:  v16.15.0
- Database system: postgres
- Operation mode: queue

**Additional context**
Using an http request with the airtable credentials is successful.

**Comment by Joffcom** [comment]
Hey @cromulus,

I just tried to reproduce this on 195.5 and it was working as expected, I can't see anything in the .5 release that would fix this but it could be worth updating anyway. The 404 tends to mean something isn't found so it is a bit odd that the HTTP Request node can find the value using the same options. Could it be the Base and Table options in the node causing the issue? Are you using URL or ID?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/4688521/192599782-57307f2f-0568-4203-aaf7-bbf12953b94f.png">

**Comment by Joffcom** [comment]
Hey @cromulus,

I have not seen a reply to this one yet so for now I am going to mark it as closed, If you do continue to see this let me know and we can open it again.

**Comment by Jainavvr** [comment]
Hello, I am experiencing the exact same issue. While trying to Get a Record, I get this error:

ERROR: The resource you are requesting could not be found
404 - {"error":"NOT_FOUND"} - NOT_FOUND

NodeApiError: The resource you are requesting could not be found
    at Object.requestWithAuthentication (/usr/local/lib/node_modules/n8n/packages/core/dist/NodeExecuteFunctions.js:1156:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/packages/nodes-base/dist/nodes/Airtable/v2/actions/record/get.operation.js:52:34)
    at Object.router (/usr/local/lib/node_modules/n8n/packages/nodes-base/dist/nodes/Airtable/v2/actions/router.js:48:30)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/packages/workflow/dist/Workflow.js:673:19)
    at /usr/local/lib/node_modules/n8n/packages/core/dist/WorkflowExecute.js:652:53

The connection is established because I can select a Base and a Table from the list. I also put the correct Record ID and still doesn't work. What could be the problem?
