### ISSUE TITLE
Typo in GitHub node options

### ISSUE THREAD

**Issue by RCheesley** [n8n-io/n8n#4221]
**Describe the bug**
There is a typo in the GitHub node option for Pull Request - it says Pull Pequest. Happy to contribute a fix but not sure where to do so.

![screenshot-mautic app n8n cloud-2022 09 27-18_50_19 (1)](https://user-images.githubusercontent.com/2930593/192728079-3a2e3474-86e7-47ec-9fb9-9ef5f80a433b.png)

**To Reproduce**
Select GitHub and choose the relevant option - notice the typo 😄 

**Expected behavior**
It should say Pull Request.

**Environment (please complete the following information):**

n8n cloud v0.194.0

**Comment by Joffcom** [comment]
Hey @RCheesley,

Thanks for reporting this one, I have just taken a quick look at the node and it looks like this has been fixed. On Cloud it looks like 0.195.5 has the correct spelling.

For now I am going to mark this one as closed.
