### ISSUE TITLE
Webhook changing the field "Binary Property" does not bring results

### ISSUE THREAD

**Issue by maxmarines** [n8n-io/n8n#423]
https://community.n8n.io/t/handling-of-binary-data-in-webhook/1035/3
when receiving a file via a web hook (POST, Binary) changing the "Binary Property" field does not produce a result, which interferes with further work with the file (for example, sending to Google disk)

<img width="523" alt="Webhook-Bagreport" src="https://user-images.githubusercontent.com/62845038/77853247-e2876a00-71eb-11ea-8661-c2b2067d0ca9.png">

<img width="534" alt="Http" src="https://user-images.githubusercontent.com/62845038/77853244-e0bda680-71eb-11ea-99f2-85d141182995.png">

**Comment by RicardoE105** [comment]
Hey, @maxmarines thanks for writing that up. It is working for me. Am I missing something?

![image](https://user-images.githubusercontent.com/16496553/77855154-a1c42c80-71bc-11ea-9e20-e4efe4fbd9b5.png)

![image](https://user-images.githubusercontent.com/16496553/77855162-abe62b00-71bc-11ea-958d-9239600da763.png)

**Comment by maxmarines** [comment]
error appears when i try send file from Webhook to google disk or dropbox (becouse field change Binary Property no result) and the file is transferred with the value Binary Property "File name + format")

<img width="686" alt="WebHook + Google Disk" src="https://user-images.githubusercontent.com/62845038/77857169-a6143800-7204-11ea-81e4-19d327e6c612.png">


HTTP-reqest successfully processes such a request 
<img width="771" alt="Http + Google Disk" src="https://user-images.githubusercontent.com/62845038/77857167-a4e30b00-7204-11ea-9499-63ff9cefd1d1.png">

**Comment by maxmarines** [comment]
> Hey, @maxmarines thanks for writing that up. It is working for me. Am I missing something?
> 
> ![image](https://user-images.githubusercontent.com/16496553/77855154-a1c42c80-71bc-11ea-9e20-e4efe4fbd9b5.png)
> 
> ![image](https://user-images.githubusercontent.com/16496553/77855162-abe62b00-71bc-11ea-958d-9239600da763.png)

Please take a look at workflow ( I attach the json on zip )
[test.zip](https://github.com/n8n-io/n8n/files/4399708/test.zip)

**Comment by RicardoE105** [comment]
Hey, @maxmarines  just tested it and it is working fine for me. I uploaded the same file using the HTTP request node and the Webhook node. Can you make sure you have the latest version of n8n? 

The version I used to test **0.59.0**

**Comment by maxmarines** [comment]
I submit the file using the form

<form action="WebHookURL.." method="POST" enctype="multipart/form-data">
    <input type="file" id="test" name="myfile">
    <input type="submit" name="Submit">

![1](https://user-images.githubusercontent.com/62845038/77894578-24f98700-727e-11ea-94d8-8ba0393ab984.jpg)
![2](https://user-images.githubusercontent.com/62845038/77894595-2925a480-727e-11ea-94f9-b429246be819.jpg)
![3](https://user-images.githubusercontent.com/62845038/77894604-2cb92b80-727e-11ea-84d9-ec6af5d50ad2.jpg)
![4](https://user-images.githubusercontent.com/62845038/77894619-30e54900-727e-11ea-8c2b-b2075a891dad.jpg)

**Comment by maxmarines** [comment]
> Hey, @maxmarines just tested it and it is working fine for me. I uploaded the same file using the HTTP request node and the Webhook node. Can you make sure you have the latest version of n8n?
> 
> The version I used to test **0.59.0**

Yes, i use last version 0.59.0

On  HTTP request, the Binary Property field changes the value to which you specify.
But with a WEBHOOK, changing this field does not produce a result.

In order to successfully transfer data to Google disk, you need to specify the "Binary Property" field, as in the previous step (web hook or request).

The problem is that changing the “Binary Property” field in the WEBHOOK does not bring results, and as a result, the data is transferred to the next step with the data of the “File name” field transmitted via the webhook, and not the value that is indicated in the “Binary Property” field in the webhook.

**Comment by janober** [comment]
Thanks a lot for the additional information. I found the bug which you are describing and will fix it asap.

**Comment by janober** [comment]
Ok fixed it now.

If option "Binary Property" did not get set on the Webhook-Node, it simply takes the name it got sent as with for "Form-Data Multipart". If one got defined it uses the name as a prefix. So if "data" got defined, it uses for the first file "data0" and the second one "data1" and so on. That is needed as multiple requests can send multiple files. 

Will be released with the next version.

**Comment by RicardoE105** [comment]
@maxmarines ahhh you were using multipart/form-data I thought you were sending just a binary file in the body. That's why I was not able to replicate it.

**Comment by janober** [comment]
@RicardoE105 yes thought the same. It took me also a very long time today to figure that out ;-)

**Comment by maxmarines** [comment]
@RicardoE105 please treat with understand, this is my first bug report in my life))
I understood what was the matter and next time I will provide more complete information)

**Comment by RicardoE105** [comment]
@maxmarines Of course my dude. Thanks again for writing that up. Keep you the good work.
