### ISSUE TITLE
Not all SNS topics are listed

### ISSUE THREAD

**Issue by ulich** [n8n-io/n8n#4235]
**Describe the bug**
When trying to configure a SNS trigger node and when having hundrets of SNS topics in an AWS account, not every topic is displayed and therefore cannot be selected. This is because pagination of the list response is not implemented i assume.

**To Reproduce**

1. Create an AWS SNS trigger node
2. Select or create AWS credentials to an AWS account with more than 200 (?) topics
3. Not all topics can be selected

**Expected behavior**
Any topic of the AWS account can be selected

**Environment (please complete the following information):**

- OS: MacOS 12.4
- n8n Version 0.195.5
- Node.js Version 18.8.0
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @ulich,

Thanks for reporting this one, I have created an internal dev ticket that will we be tracking as N8N-4828. I will let you know when we have pushed a fix.

**Comment by ulich** [comment]
Thank you. I would be happy to create a PR as well if you like.

**Comment by Joffcom** [comment]
Hey @ulich,

I am going to mark this one as closed, The fix got released with n8n@0.206.1

**Comment by SpiritusDeos** [comment]
@Joffcom do we have any news on it ?
