### ISSUE TITLE
HTTP Request rejected

### ISSUE THREAD

**Issue by matndev** [n8n-io/n8n#4240]
**Describe the bug**

The HTTP Request node failed with the url : [https://www.java.com/releases/](url)
I get an error : 

ERROR: UNKNOWN ERROR - check the detailed error for more information
getaddrinfo ENOTFOUND www.java.com

Code  : 
`
{
"status": "rejected",
"reason": {
"message": "getaddrinfo ENOTFOUND www.java.com",
"name": "Error",
"stack": "Error: getaddrinfo ENOTFOUND www.java.com at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
"code": "ENOTFOUND"
}
}
`

**To Reproduce**

1. Open a new workflow
2. Add a HTTP Request node after the start node
3. Write 'https://www.java.com/releases/' in the url field
4. Choose response format as 'File'

**Expected behavior**

Get a file in the output section but instead I have the error above.

**Environment (please complete the following information):**

- OS: Windows 10 Enterprise
- n8n Version : 0.195.5
- Node.js Version : v16.17.0
- Database system SQLite
- Operation mode : own

**Additional context**

I installed n8n within a docker container with the guide from the site.

Screenshot : 

![n8n error](https://user-images.githubusercontent.com/46798367/193145426-594fee95-7cbf-473c-98c0-08c20091823e.PNG)

**Comment by Joffcom** [comment]
Hey @matndev,

Thanks for reporting this one, is it failing for other sites as well?

My initial thought on this one is this is not a bug with n8n and is likely to be a dns or configuration issue so may be better suited to our community support forum.

**Comment by matndev** [comment]
Hello thanks @Joffcom , no I can scrap from another site but I think this one fails maybe because of javascript.
I would have advices about that so I posted and if you say it can be dns or configuration I will look into that.

**Comment by Joffcom** [comment]
Hey @matndev,

Javascript seems a bit unlikely with that message as it is saying it can't find the address. My thought very early this morning was maybe DNS or some kind of redirect issue.

I have just given it a test on my instance now and it is working as expected.

![image](https://user-images.githubusercontent.com/4688521/193224132-89cb6633-a9f8-4c64-89b1-79699e084dbc.png)

The downside here though is the next issue you hit will be down to javascript being required.

**Comment by matndev** [comment]
Ok so it's a connection problem I'll check that. For the next issue how could I enable javascript to get the real content with n8n ?

**Comment by Joffcom** [comment]
Hey @matndev,

Enabling javascript isn't an option we have with our http request node, It is a bit like using CURL so anything that is "interactive" won't really work.

There are some nodes made by the community to use things like Puppeteer to scrape pages which uses a chrome browser to get the content.

**Comment by matndev** [comment]
Ok thank you I will use community nodes for that then
