### ISSUE TITLE
Webhook Mode not working

### ISSUE THREAD

**Issue by dwinurhadia** [n8n-io/n8n#4241]
**Bug**
I've running n8n with mode webhook, but when i try to access path `/webhook` it nothing happend

**Expected behavior**
The idea is make separate process webhook like this tutorial [Tutorial](https://www.youtube.com/watch?v=PnoE0xV8BX8)

**Environment** 

- OS: Ubuntu Linux 20.04
- n8n Version 0.195.5
- Database system Postgres
- Operation mode Running docker with Webhook mode and command `n8n webhook`

**Output**
Here is output via command line
```
n8n-n8n-wh-1      | Webhook listener waiting for requests.
n8n-n8n-wh-1      | n8n ready on 0.0.0.0, port 5678
n8n-n8n-wh-1      | Version: 0.195.5
```

**Comment by Joffcom** [comment]
Hey @dwinurhadia,

Thanks for the report this doesn't sound like a bug and is likely to be more of a configuration issue.

Can you open a thread on our community support forum (community.n8n.io) and include your setup configuration with anything sensitive removed and your load balancer configuration.

For now I am going to mark this one as closed and if it does turn out to be a bug we can open it again.
