### ISSUE TITLE
Error starting N8N 0.196.0: EACCES: permission denied, mkdir 

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4246]
**Describe the bug**

Using external libraries with this envs:

```
- NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash,moment-with-locales,luxon,libphonenumber-js
- N8N_REINSTALL_MISSING_PACKAGES=true
```

This will produce this error:

```
Initializing n8n process
UserSettings were generated and saved to: /home/node/.n8n/config
n8n detected that some packages are missing. For more information, visit https://docs.n8n.io/integrations/community-nodes/troubleshooting/
Attempting to reinstall missing packages
Packages reinstalled successfully. Resuming regular initialization.
 ›   Error: There was an error: EACCES: permission denied, mkdir 
 ›   '/usr/local/lib/node_modules/n8n/dist/public'
```

With external libraries removed:

```
Initializing n8n process
UserSettings were generated and saved to: /home/node/.n8n/config
 ›   Error: There was an error: EACCES: permission denied, mkdir 
 ›   '/usr/local/lib/node_modules/n8n/dist/public'
```

**To Reproduce**

Upgrade N8N Docker to 0.196.0

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 18.04]
- n8n Version [e.g. 0.119.0]
- Node.js Version [e.g. 14.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof,

Already on it 👍🏻 New version should be out shortly

**Comment by Joffcom** [comment]
You will need to redownload the image as we will use the same 0.196.0 tag.

**Comment by luizeof** [comment]
thanks @Joffcom !!!

**Comment by Joffcom** [comment]
@luizeof you should be good to go now.

**Comment by luizeof** [comment]
fixed! Thanks a lot @Joffcom
