### ISSUE TITLE
TheHive node Alert UPDATE Invalid format for  severity

### ISSUE THREAD

**Issue by Canon88** [n8n-io/n8n#4256]
**Describe the bug**
When i use TheHive node UPDATE alert severity level, i see error: `{"type":"org.thp.scalligraph.InvalidFormatAttributeError","message":"Invalid format for  severity: FString( severity), expected attributeName ()"}`

**To Reproduce**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/19372121/193733952-840529e5-abe9-4e08-b430-1b7d14898246.png">

**Expected behavior**

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 0.194.0
- TheHive Version: 4.1.24-1
- Node.js Version [e.g. 14.16.0]

**feedback:**
I don't know how to update n8n TheHive Node, but I seem to have found the problem.
Since TheHive Node has an extra " "space when updating severity, this prevents TheHive server from parsing this data.

n8n TheHive Node update alert severity POST Body
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/19372121/193734779-626b869e-f634-4fed-b7d1-2b8a393319a9.png">

Correct format：
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/19372121/193734736-c3221cae-8943-430d-a6b2-f97df807411e.png">

**Comment by Joffcom** [comment]
Hey @Canon88,

Thanks for reporting this one, I have just put in a PR to fix this one which can be found here #4259

**Comment by Canon88** [comment]
@Joffcom Thanks.  
When i try to use thehive alert update tags, i see new err "ERROR: UNKNOWN ERROR - check the detailed error for more information". 


n8n TheHive Node error HTTP PATCH

`PATCH /api/alert/~205013152 HTTP/1.1
Accept: application/json
Authorization: Bearer ynLw0AULSM+qFdLuSdfaLseutZKirf2G
Content-Type: application/json
User-Agent: axios/0.21.4
Content-Length: 14
Host: 192.168.199.35:9000
Connection: close

{"tags":"exp"}

HTTP/1.1 400 Bad Request
Request-Time: 24
Date: Tue, 04 Oct 2022 17:24:40 GMT
Connection: close
Content-Type: application/json
Content-Length: 247

{"type":"AttributeCheckingError","message":"[Invalid format for tags: FString(exp), expected object ([string])]","errors":[{"name":"tags","format":"object","acceptedInput":["[string]"],"field":"FString(exp)","type":"InvalidFormatAttributeError"}]}`

Correct format：
`{"tags":["exp"]}`

tags type must be array not string

**Comment by Joffcom** [comment]
Hey @Canon88,

When you added the tag did you use the tags option in the node or an expression?

**Comment by Canon88** [comment]
> Hey @Canon88,
> 
> When you added the tag did you use the tags option in the node or an expression?

when i select expression everything is ok, but i select Fixed write `exp` , i see error.

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/19372121/195054615-987a8d82-59c2-468e-917d-69aca7dffed9.png">
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/19372121/195054690-8484f0de-7cdc-4acd-9bc7-2099d18fe8ca.png">
