### ISSUE TITLE
Subworkflow execution timestamp mismatch

### ISSUE THREAD

**Issue by aschuma** [n8n-io/n8n#4258]
**Describe the bug**

- WF executing some subworkflows 
- Execution timestamps in subworkflow have a different timestamp (2h delta), see screenshot 

ID 3099 was the main workflow. 3100, 3101, 3102, 3103 are called via workflow node in main workflow (workflow from DB)

 <img width="1934" alt="Screenshot 2022-10-04 at 09 33 48" src="https://user-images.githubusercontent.com/5055033/193763234-c3988715-b15d-4a16-9ecd-3cbb73e62b07.png">

**Expected behavior**
- Execution timestamp should have a similar timestamp

**Environment (please complete the following information):**

- OS: `Windows Server 2019`
- n8n Version `0.178.0`
- Node.js Version `v16.5`
- Database system `Postgresql 14`
- Operation mode `own`

**Comment by Joffcom** [comment]
Hey @aschuma,

This looks very similar to #3855, Are you running Postgres in a container?

**Comment by aschuma** [comment]
After using UTC for Postgres and for N8N, everything works fine for me so fare:

postgressql.conf
```
timezone = 'UTC'
log_timezone = 'UTC'
```

N8N Env:
```

GENERIC_TIMEZONE="UTC"
TZ="UTC"
```

@Joffcom Thank you for the hint
