### ISSUE TITLE
While executing `lerna bootstrap --hoist` gives dependency deprecated errors

### ISSUE THREAD

**Issue by achhranitesh** [n8n-io/n8n#426]
While executing `lerna bootstrap --hoist` gives dependency deprecated errors:

npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/open@6.2.1: This is a stub types definition. open provides its own type definitions, so you do not need this installed.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Unexpected end of JSON input while parsing near '.../6uVpjKmLEAcS4\n7luU5'

**Comment by janober** [comment]
Uh wow, request got deprecated. That is bad. We have to look for an alternative and then update everything.

**Comment by achhranitesh** [comment]
@janober : I'm lock down on trying this through local modifications. Can you help me with any alternative & bypassing this

**Comment by janober** [comment]
That is actually nothing that can be done fast as currently almost every integration with n8n depends on it. So it will take quite some work and so take time.

Anyway, that should not matter to you at all right now. It is just a warning nothing more. So it should still work totally fine. I did not see that you got some kind of error. No idea where that would come from, maybe some temporary issue? I would just start again from the beginning. Clone n8n, npm install and then do the bootstrap. It should work fine. Just to be sure, I just tried myself. Everything worked without any issues.

**Comment by achhranitesh** [comment]
Thanks @janober : Let me try it once again and if i get any errors, I will post the entire stack trace here

**Comment by janober** [comment]
Sounds good. And if you do, please post also with it the following information every bug report should contain as set up in the template:

**Environment:**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.26.0]
 - Node.js Version [e.g. 10.16.0]

**Comment by achhranitesh** [comment]
@janober : The project executed successfully. One step I had to do in addition, which was 

> npm i

> npm cache clear --force

> bootstrap

As it was throwing Z_BUF_ERROR while bootstrapping

Environment:

OS: macOS Catalina 10.15.3
Node.js Version 10.15.3

**Comment by janober** [comment]
Ah great to hear that it worked now.

So close the issue now.
