### ISSUE TITLE
NocoDB doesn't update

### ISSUE THREAD

**Issue by zblesk** [n8n-io/n8n#4266]
The NocoDB connector's Get/List work, but Update doesn't. It doesn't report any error, either: it says 'succeeded' (and generates no output), but no data is changed in NocoDB. 

**To Reproduce**

I have created a new, empty workflow, that only contains a NocoDB component with User Token auth. 
To make sure the error isn't somewhere else, I have chosen a table and hardcoded a specific record's ID, and tried setting it to a constant value. 

![image](https://user-images.githubusercontent.com/4245227/194017424-2539d0b4-e558-41f5-9a87-c77c30b9315b.png)

I have also tried the variant with 'auto map input data to columns' with the same result. 

**Expected behavior**

I would expect the new value to show up in the relevant column in NocoDB.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version 0.196.0
- using the latest Docker image
- DB_TYPE=mysqldb
- Operation mode - no idea what this is, sorry. 
It's a small instance, used just by me. 

**Additional context**

NocoDB info (provided by the "Copy project info" menu item):

Node: **v12.22.12**
Arch: **x64**
Platform: **linux**
Docker: **true**
Database: **pg**
ProjectOnRootDB: **false**
RootDB: **pg**
PackageVersion: **0.97.0**

Both NocoDB and n8n are running on the latest docker images. 

Created as a followup from #3170 .

**Comment by Joffcom** [comment]
Thanks for opening this one @zblesk, I will update my local nocodb install to 0.97.0 and see if I can reproduce this one.

**Comment by zhzy0077** [comment]
+1 the error on my instance is:
```json
"cause": {
"message": "404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /nc/demo_0r5n/api/v1/notifications/bulk</pre>\n</body>\n</html>\n"",
"name": "Error",
"stack": "Error: Request failed with status code 404 at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
```

Sounds like the URL in [API docs](https://apis.nocodb.com/#tag/DB-table-row/operation/db-table-row-bulk-create) is different from what I saw in the error message: `/nc/demo_0r5n/api/v1/notifications/bulk`

**Comment by Joffcom** [comment]
Hey @zhzy0077,

If you got to the node settings what version is selected?

![image](https://user-images.githubusercontent.com/4688521/194824658-fd7b6766-e5d5-48bf-9ff3-b9674b200fec.png)

**Comment by zhzy0077** [comment]
@Joffcom it works after setting 'v0.90.0 onwards'. thank you!

**Comment by Joffcom** [comment]
@zblesk does this work for you as well?

**Comment by zblesk** [comment]
@Joffcom I've added some info here: https://github.com/n8n-io/n8n/issues/3476#issuecomment-1274199626 
re-tried today, the behavior is still the same.

**Comment by zblesk** [comment]
Hello, any news? :)

**Comment by Joffcom** [comment]
Hey @zblesk,

Sorry for the delay I got caught up with some other issues, I have just updated my NocoDB install to 0.98.3. Set the node to use v0.90.0 Onwards under the settings and I have done a quick update and it has worked as expected.

![image](https://user-images.githubusercontent.com/4688521/198983784-610f6524-66c2-40cc-9d32-d843e76aa4cf.png)

I have done a test without setting expressions and that seems to ok as well.

![image](https://user-images.githubusercontent.com/4688521/198984104-7fcc238d-8984-41b9-82a9-e6afadf43578.png)

Can you share the workflow with me that isn't working?

**Comment by zblesk** [comment]
@Joffcom thanks. 

I've noticed that your update says 'success: true'. Mine doesn't; it either doesn't generate anything, or when I turn on 'always output event', it looks like this. 

![image](https://user-images.githubusercontent.com/4245227/199037111-5d1d701d-1c2e-44d0-8851-ac66a04728d9.png)

In the meantime, I've created a WF that just creates a new record in that table (to ensure I have the column names and format right, etc) and then tries to update that same record. (So I've modified the Update step to use the ID from the previous, Create step.)

The create works exactly as expected; the Update does nothing.

[NocoDB_create_and_update.zip](https://github.com/n8n-io/n8n/files/9902188/NocoDB_create_and_update.zip)


... it doesn't seem to be the case, but please do let me know it that exported file contains sensitive info, like the API token or something.

**Comment by zblesk** [comment]
@Joffcom hello again. 
Is there any way I could make n8n log request/response pairs sent to nocodb? 
I have tried setting the log level env var (in docker) to Verbose, but it doesn't contain that information.

**Comment by zblesk** [comment]
Hello, 
if you don't want to address this, you can close the issue. I will have to implement it in something else anyway. 
(I'm not closing the issue myself in case you still want to keep track of it.) 

Thank you for your time.

**Comment by Joffcom** [comment]
Hey @zblesk

Still interested in this one but it is tricky as I can't reproduce it and for some odd reason the issue only appears to be in your environment which makes it tricky.

There is no option to debug the requests at the moment which would be useful thing to have.

In the NocoDB log I would expect to see some kind of request come in even if it just says it can't do anything.

Is there any chance I could get access to your NocoDB instance to test sending a request from here?

If you are still up for it of course.

**Comment by Joffcom** [comment]
Hey @zblesk,

That is a bit strange, I thought the Table ID was in the URL not the body. It is a bit strange that the project and table name fields don't update.

Which endpoint are you using? We use `/api/v1/db/data/bulk/noco/${projectId}/${table}`.

As a quick test I have just set up a clean docker instance of NocoDB which I can give you access to and I am able to update that without having to make the changes you have done.

Taking a look at the request we have the below which matches what you have found...

```
{
  "method": "PATCH",
  "body": [
    {
      "id": "1",
      "Title": "Changed"
    }
  ],
  "qs": {},
  "uri": "https://removed/api/v1/db/data/bulk/noco/removed/removed",
  "json": true
}
```

Interestingly when I check my nocodb API docs it shows for my table that the request needs to contain...
![image](https://user-images.githubusercontent.com/4688521/207601742-dbf5d631-a2e3-4681-b039-1ecb599240e3.png)

My table in NocoDB looks like this
![image](https://user-images.githubusercontent.com/4688521/207601508-87184379-e784-4fbd-86ed-a8e18b32595d.png)

If you check the API docs for your NocoDB instance is it missing the id field? I still feel like this is going to be an environmental setting of some kind.

Curious to see where the ID field is I just found that under Fields there is a checkbox to show System Fields in there I found ID but I am not able to rename or edit it as it is being used as a primary key. 
![image](https://user-images.githubusercontent.com/4688521/207602683-ae9d0e15-f8b4-49be-bbfc-1cd1d53ac05b.png)

It would be great to know more about your table or if you are interested I can give you access to my quick test instance that you can have a play with so we can get to the bottom of this one.

**Comment by zblesk** [comment]
Hello @Joffcom 

>That is a bit strange, I thought the Table ID was in the URL not the body. It is a bit strange that the project and table name fields don't update.

Must be a misunderstanding. I didn't mean to say that. Maybe it sounded that way because the ID column was named <tablename>Id. 
The payload I posted here was the entire thing, so the table name was not in it.

> If you check the API docs for your NocoDB instance is it missing the id field? I still feel like this is going to be an environmental setting of some kind.

This made it click for me. Thanks. I completely understand what's been happening, now. 😁
It's not a _setting_ per se, but the tables I tried to do it on weren't created by the NocoDB UI; the DB existed beforehand and Noco started using them. 
So in those tables, the name of the ID column was TableNameId; but now that I checked in the API docs, I see that yes, they do say that, and also just say `id` with all the tables that _were_ created via the Noco UI.

Thank you.

**Comment by Joffcom** [comment]
Hey @zblesk,

Ahh so that is the missing piece, This has been an interesting one and it is good to finally be at the bottom of it.

I will have a think about a nice way to handle this one without having something overly complex, My first thought is we just have an option for "Use TableID" and we can then swap out the id field name based on that.

I know the NocoDB node will need an overhaul at some point to use the newer resource locator component and to work like other database style nodes so I think this is something we could fit into those changes.

**Comment by zblesk** [comment]
Hey @Joffcom, yeah, a least one puzzle satisfactorily solved. :) 

I also thought about that, but there are complexities and also more bugs. 
For one, I think what is happening is that Noco just takes the column names as-is. That is, you can probably have any name you want, and "Use TableId" would just cover one of them. Maybe it would be better to have a "Specify ID column" Option in the component?
Also a disclaimer, I've never tried composite keys with Noco, so I have no idea what those would do. 

I think I've also found a NocoDB bug, though: when I create a record via API, I got a Success response with `id: null`. I had to make a separate request to get the actual `TableNameId`.

**Comment by Joffcom** [comment]
Just going to add that internally we are tracking this as `node-156`

Specify ID Column might be a better option as it looks like there can be multiple options, My note on the internal ticket was to have 4 options.

Default - Data has been created in NocoDB
Imported - Data has been imported from a third party service Airtable
Existing - Data is being loaded from an Existing database
Custom - Manually set the ID field name
