### ISSUE TITLE
CONSTAIN_TOKEN is sent to Hubspot rather than CONTAINS_TOKEN when searching a deal

### ISSUE THREAD

**Issue by adriendurepaire** [n8n-io/n8n#4276]
Just a typo issue: https://github.com/n8n-io/n8n/blob/3a9c7acb04866e71d10f126d188dd7e84d80a2fe/packages/nodes-base/nodes/Hubspot/DealDescription.ts#L620

**Comment by Joffcom** [comment]
Hey @adriendurepaire,

Thanks for reporting this one, I will get a PR put in shortly.

**Comment by adriendurepaire** [comment]
Thank you @Joffcom! I also noticed some operators are missing. Here are the operators accepted by Hubspot: IN, NOT_HAS_PROPERTY, LT, EQ, GT, NOT_IN, GTE, CONTAINS_TOKEN, HAS_PROPERTY, LTE, NOT_CONTAINS_TOKEN, BETWEEN, NEQ.

It would be great to be able to use IN, NOT_IN and BETWEEN with n8n

**Comment by Joffcom** [comment]
Hey @adriendurepaire,

Seems to make sense to sneak them in while fixing the typo, I will see what I can do 👍🏻

**Comment by Joffcom** [comment]
Hey @adriendurepaire,

Had a quick look and is a bit more to it so for now I have just fixed this issue and I will make a ticket to support the full list of operators when we next do a bigger refresh on the node.

**Comment by adriendurepaire** [comment]
Thanks a lot @Joffcom :)
