### ISSUE TITLE
chown: /home/node/.n8n: Permission denied

### ISSUE THREAD

**Issue by geekhuashan** [n8n-io/n8n#4280]
**Describe the bug**
When i use docker to install on my DO vps. The wrong message showed

**To Reproduce**

1.rebuild my vps
2.install docker
3. install n8n

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. centos 7 Linux ]
- n8n Version 0.196.0

The wrong message:

chown: /home/node/.n8n: Permission denied
Initializing n8n process
UserSettings were generated and saved to: /home/node/.n8n/config
There was an error initializing DB: "SQLITE_CANTOPEN: unable to open database file"

Stopping n8n...

**Comment by Joffcom** [comment]
Hey @geekhuashan,

Can you confirm which docker image you are using? Are you running the docker run command as a user that has permission to write to the volume (assuming there is one) as well?

**Comment by geekhuashan** [comment]
> Hey @geekhuashan,
> 
> Can you confirm which docker image you are using? Are you running the docker run command as a user that has permission to write to the volume (assuming there is one) as well?

Hey @Joffcom The docker image version is 0.196.0. I'm a newbie and I don't know how to run command as a user or root. I just copy the code from the doc. 


docker run -it --rm \
	--name n8n \
	-p 5678:5678 \
	-v ~/.n8n:/home/node/.n8n \
	n8nio/n8n

**Comment by Joffcom** [comment]
Hey @geekhuashan,

That is good to hear, I will get this one marked as closed.
