### ISSUE TITLE
Upgrade for n8n:latest-debian fails - ACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by Lars147** [n8n-io/n8n#4281]
**Describe the bug**
After doing a `docker-compose pull` followed by `docker-compose down` & `docker-compose up -d`. The n8n instance cannot start anymore. The docker logs show the following error

```
n8n_1      | Initializing n8n process
n8n_1      |  ›   Error: There was an error: EACCES: permission denied, mkdir
n8n_1      |  ›   '/usr/local/lib/node_modules/n8n/dist/public'
```

I have the feeling that this could be related to https://github.com/n8n-io/n8n/issues/4246

**To Reproduce**

Pull newest image for n8n:latest-debian.

There could be the possibility that this error only happens when you already mounted a volume in the past.

**Expected behavior**
New version of n8n running without errors.

**Environment (please complete the following information):**

- OS: Docker on Debian GNU/Linux 11 (bullseye)
- n8n Version: docker image n8n:latest-debian
- Node.js Version [e.g. 14.16.0]
- Database system: SQLite
- Operation mode: own

**Additional context**

**Comment by Joffcom** [comment]
Hey @Lars147,

I believe this will be fixed by #4275, There is a community thread about this one which can be found here: https://community.n8n.io/t/eaccss-permission-denied-after-upgrade/18385

**Comment by Lars147** [comment]
Hi @Joffcom,

thank you for the quick response. Is there a possibility to track the progress when the new version will be released on DockerHub?

**Comment by Joffcom** [comment]
Hey @Lars147,

If you want I can let you know when we do the release.

**Comment by Lars147** [comment]
That would be awesome. Thank you!

**Comment by Joffcom** [comment]
Hey @Lars147,

We have just kicked off the release process, Once the action links below has finished you will be good to upgrade... It normally takes about an hour.

https://github.com/n8n-io/n8n/actions/runs/3217954006

**Comment by Lars147** [comment]
Awesome, thank you very much. It is working now!
