### ISSUE TITLE
ui poor performance with 100000 execution history

### ISSUE THREAD

**Issue by mdbetancourt** [n8n-io/n8n#4283]
**Describe the bug**
when i have a lot of execution history the ui feels laggy

**Expected behavior**
run the ui smoothly

**Comment by Joffcom** [comment]
Hey @mdbetancourt,

What do you mean? Like the entire application is slow or just loading the execution list?

**Comment by mdbetancourt** [comment]
@Joffcom just loading execution list i find out the problem is here
/executions-current returns too many records

Server.ts file
```ts
this.app.get(
			`/${this.restEndpoint}/executions-current`,
...
						const findOptions: FindManyOptions<IExecutionFlattedDb> = {
							select: ['id', 'workflowId', 'mode', 'retryOf', 'startedAt'],
							order: { id: 'DESC' }, 
							where: {
								id: In(currentlyRunningExecutionIds),
							},
						};

						const sharedWorkflowIds = await getSharedWorkflowIds(req.user);

						if (!sharedWorkflowIds.length) return [];

						if (req.query.filter) {
							const { workflowId } = JSON.parse(req.query.filter);
							if (workflowId && sharedWorkflowIds.includes(workflowId)) {
								Object.assign(findOptions.where!, { workflowId });
							}
						} else {
							Object.assign(findOptions.where!, { workflowId: In(sharedWorkflowIds) });
						}

						const executions = await Db.collections.Execution.find(findOptions);

						if (!executions.length) return [];

						return executions.map((execution) => {
							return {
								id: execution.id,
								workflowId: execution.workflowId,
								mode: execution.mode,
								retryOf: execution.retryOf !== null ? execution.retryOf : undefined,
								startedAt: new Date(execution.startedAt),
							} as IExecutionsSummary;
						});
```

**Comment by Joffcom** [comment]
Hey @mdbetancourt,

Ah ok yeah, on the execution list itself I am fairly sure we are aware of it having a hard time to load lots of data. Do you see the slow down instantly or after scrolling through the list a bit?

**Comment by mdbetancourt** [comment]
> Hey @mdbetancourt,
> 
> Ah ok yeah, on the execution list itself I am fairly sure we are aware of it having a hard time to load lots of data. Do you see the slow down instantly or after scrolling through the list a bit?
instantly for now i just limited the amount of returned records with

```ts
const findOptions: FindManyOptions<IExecutionFlattedDb> = {
	select: ['id', 'workflowId', 'mode', 'retryOf', 'startedAt'],
	order: { id: 'DESC' }, 
        take: 100,
	where: {
		id: In(currentlyRunningExecutionIds),
	},
};
```

**Comment by Joffcom** [comment]
Hey @mdbetancourt,

Are you still seeing the slow performance on the latest release?

**Comment by Joffcom** [comment]
Marking this as closed, We recently put out an update that massively improves the speed of the execution view.
