### ISSUE TITLE
[whatsapp-business-node] Locale parameter missing of Send Template

### ISSUE THREAD

**Issue by imagina** [n8n-io/n8n#4291]
We cannot configure the Locale parameter to send a template.

![image](https://user-images.githubusercontent.com/758247/194727711-4e985b61-0e1c-4e14-9160-84470fbd1503.png)

Documentation: https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates#:~:text=the%20whatsapp_business_messaging%20permission.-,Text%2DBased%20Message%20Templates,-To%20send%20a talk about a language parameter in the template
![image](https://user-images.githubusercontent.com/758247/194727715-92577f62-0b12-4b0d-8b7d-1e09320a955a.png)

**Comment by Joffcom** [comment]
Hey @imagina,

Can you share the template you have created in WhatsApp business manager and can you confirm it has been approved to use.

**Comment by imagina** [comment]
Sure, this is it
![image](https://user-images.githubusercontent.com/758247/194890472-e884fe75-1608-46d5-90f1-69eba499fb27.png)

**Comment by Joffcom** [comment]
Hey @imagina,

Has that been approved to be sent? The same error was reported on the community forum the other day and it was a template issue so I am wondering if this is the same thing.

**Comment by imagina** [comment]
Yes, it is approved. if we send manually with the locale parameter it works
![image](https://user-images.githubusercontent.com/758247/195118188-189e6e4c-703e-4c4a-81af-734023957182.png)

**Comment by Joffcom** [comment]
Hey @imagina,

That is a bit strange, if you send that template from n8n what message do you get? Your original screenshot looks to be a different template.

**Comment by imagina** [comment]
![image](https://user-images.githubusercontent.com/758247/195411452-0e3b598c-f53f-40b1-b5ae-4b6ea847ae3d.png)
the message with the same template it like the first screenshot... for the field of the templateName we got these message just like the senderId anyway for other message type (text, audios, images, documents...) works setting it manually

**Comment by Joffcom** [comment]
Hey @imagina,

So that is likely to be your problem, the template looks like it needs to be set from the drop-down.

If that isn't working try setting the value to `template_id|lang_Code` and see if that works.

**Comment by imagina** [comment]
Works joining the templateName with the locale! Thank you @Joffcom 
![image](https://user-images.githubusercontent.com/758247/195462377-8fbbae5b-deaa-427e-9400-4ee4ba90f6c6.png)
just another thing, why don't the dropdowns load this data for us?

**Comment by Joffcom** [comment]
Hey @imagina,

I am not sure, What happens if you click on the dots and select refresh list?

**Comment by imagina** [comment]
@Joffcom is it possible setting an entry expression for `components`?
![image](https://user-images.githubusercontent.com/758247/195733050-edaaa9c0-31d7-42cf-99bb-ba40e8895bb1.png)

**Comment by Joffcom** [comment]
Hey @imagina,

You would need to add the items first then change to an expression.

**Comment by Joffcom** [comment]
Hey @imagina,

It looks like the original issue for this one was solved and potentially not a bug so I am going to mark this one as closed for now, If you have any questions about this let me know.
