### ISSUE TITLE
Box node producing 2 items on Folder creation

### ISSUE THREAD

**Issue by jjboardman** [n8n-io/n8n#4293]
**Describe the bug**
When the box node is used to create a new folder it outputs 2 items but the UI only displays 1, it seems that the second item is the actual out put and the first one is empty/ doesn't really exist

**To Reproduce**
Set version to 0.195.5 or 0.196.0 execute the Box node to create a new folder.

**Expected behavior**
1 item in output

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- n8n Version 0.195.5/0.196.0
- Node.js Version 14.6
- Database system PostgreSQL
- Operation mode queue

**Comment by Joffcom** [comment]
Hey @jjboardman,

Do you have a screenshot of the 2 items? Is it only when creating a new folder as well?

**Comment by jjboardman** [comment]
Hey @Joffcom 
Here is the json output: 
![image](https://user-images.githubusercontent.com/58300788/194773707-a5545a60-8d5d-4e8c-94d6-178b52f16aa7.png)
Here shows the array of items only has 1 item in it:
![image](https://user-images.githubusercontent.com/58300788/194773762-3debbff4-6259-48ce-bc1d-7091ad1af026.png)

I also tried Get folder and update folder both returned 1 item.

**Comment by Joffcom** [comment]
Hey @jjboardman,

Thanks for the info, I managed to reproduce and have put a PR in that will fix this in a future release.
