### ISSUE TITLE
Need execution time on each node instead of going into each node and checking the time 

### ISSUE THREAD

**Issue by prasad8mhatre** [n8n-io/n8n#43]
Need execution time on each node instead of going into each node and checking the time 

1. when the workflow has executed, it is intuitive to see the execution time of each node at glance instead of going instead each node and checking

2. also at top bar total execution time needs to be present

**Comment by janober** [comment]
About 1:
I can understand why you want that to see it but are however not sure it is the right way to go.

I tried very hard to keep the interface as clean as possible without making it look to technical and full by just displaying the important information. Even though executing time can be important do I normally not care that much about it as long as the node did succeed. Could imagine adding it, however, on "hover".

About 2: 
Agree

**Comment by prasad-mhatre-incontact** [comment]
Yes, on "hover" can also work

**Comment by mscansian** [comment]
@prasad8mhatre Could you describe your use case for this?

I think that the value from n8n comes when you automate stuff that you just need to get done and don't care about performance. The main goal is flexibility, not performance. In case you need a high volume or fast responses, it might be better to just write the code.

**Comment by RicardoE105** [comment]
Hey, @prasad-mhatre-incontact, thanks for the feedback. Feature requests can be made on our community https://community.n8n.io/. Thanks.
