### ISSUE TITLE
For some workflows inspecting any executed node crashes the browser tab after a while

### ISSUE THREAD

**Issue by christiaanwesterbeek** [n8n-io/n8n#4314]
**Describe the bug**
When I manually run a workflow or looking at a past execution, and I double click on a Node, there is no response. And after a while the browser tab either crashes (Chrome) or just freezes (Firefox+Safari). Instead I expected the node to open with the usuals: dialog with input data on the left, the node details in the middle and output on the right.

**To Reproduce**
See description

**Expected behavior**
See description

**Environment (please complete the following information):**

iMac+Chrome and Windows+Firefox with n8n Version 0.197.1 running in the cloud.

In the video underneath you see it happening in a workflow that actually has bug, that we try to investigate but couldn't debug since opening up any node caused our tabs to freeze.

https://nprc.app.n8n.cloud/workflow/1011

https://user-images.githubusercontent.com/465989/195113369-3a2300a7-040b-4b19-b45b-98b8e0b6e1d1.mp4

**Comment by Joffcom** [comment]
Hey @christiaanwesterbeek,

Does that happen for any workflow or just that one?

**Comment by christiaanwesterbeek** [comment]
Not any workflow. Also this one https://nprc.app.n8n.cloud/workflow/1012 . But others are fine it seems

Also any of the executions of the problematic workflow can't bes inspected. If you click on a node that was executed. Same thing; tab crashes in Chrome, freezes in Firefox and Safari. This execution is one of them https://nprc.app.n8n.cloud/execution/27860

**Comment by Joffcom** [comment]
Hey @christiaanwesterbeek,

As this is related to Cloud it might be better to email our support address so we can look into it there.

Anything I ask you to try and do here you likely won't be able to access.

**Comment by Joffcom** [comment]
Hey @christiaanwesterbeek,

I can see the ticket has been created and our team have been busy looking into it, For now I am going to the issue here 👍🏻
