### ISSUE TITLE
Missing Trello API Credential Type for HTTP Request node

### ISSUE THREAD

**Issue by np** [n8n-io/n8n#4341]
**Describe the bug**

I am running the latest n8n desktop app.
I have one Trello auth setup.
I have one HTTP Request node in the canvas and in Credential Type drop down select, I see plenty of APIs but not Trello.

**To Reproduce**

1. New workfolw
2. Create HTTP Request
3. Select "Predefined Credential Type"
4. No Trello in the Credential Type drop down menu.

**Expected behavior**
Trello API should be here.

**Environment (please complete the following information):**

- OS: Windows 11
- n8n Version: 1.6.0.0 (on the exe)

**Comment by janober** [comment]
That would actually be more of a feature request than a bug. Can you please post about it here:
https://community.n8n.io/

Thanks a lot!
