### ISSUE TITLE
"if"-Node behaves strangely when different (multiple) input is passed

### ISSUE THREAD

**Issue by dewdeded** [n8n-io/n8n#4344]
We run the latest self-hosted n8n (in an Docker env).

We see an behaviour we didn't expect. If multiple line input with different values is passed into an "if"-n8n-Node,
the result is unexpected. 

We had a decision if a value is 1 or 0, we passed two lines into the if-Node, one with value 1 and one with value 0.
The node passed line 1 in both direction (yes and no). Line 2 was ignored.

Any comments? :-)

**Comment by janober** [comment]
Can you post a simple example workflow that shows that behavior so that we can debug and have a look. Thanks!

**Comment by dewdeded** [comment]
Sorry Jan, this can be closed, we found the error on our side.
