### ISSUE TITLE
Cannot run n8n locally nor in a docker container locally

### ISSUE THREAD

**Issue by Subtixx** [n8n-io/n8n#4352]
**Describe the bug**
I want to try to develop some nodes but am unable to install n8n locally nor in a docker container locally. Both return an empty white page with a javascript error in the console:

```
Uncaught SyntaxError: missing ) after argument list
```

**To Reproduce**

No idea. Just tried the Tutorial on the Website to develop nodes. And then tried a local docker copy of the production server.

**Expected behavior**
See the n8n interface.

**Environment (please complete the following information):**

- OS: Windows and docker
- n8n Version both latest
- Node.js Version llocally 17.3, docker container no idea.
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @Subtixx,

This sounds like an issue we fixed earlier today, can you confirm the n8n version you are trying to use?

**Comment by Subtixx** [comment]
Yep. Works flawlessly with the .2
