### ISSUE TITLE
Notion "Add Block" button is inaccessible off-screen

### ISSUE THREAD

**Issue by memetican** [n8n-io/n8n#4353]
**Describe the bug**
In the Notion node configurator, when a few **properties** have been added, the **Add block** button becomes inaccessible off-screen ( Chrome, Windows ). See screenshot. I was able to access it by adding margin-bottom: 100px; through chrome devtools.

The scrollbar ends well below the bottom of the configuration frame, by about 100px- so whatever is at the bottom of the config pane becomes inaccessible.

NOTE: this may be a systemwide config panel issue, but I encountered it in the Notion node, so I've tagged it as such.  

This is scrolled to the bottom.
![image](https://user-images.githubusercontent.com/1810892/195970313-e171111f-c885-4927-8e9d-9e66009195ae.png)

**To Reproduce**

1. Create a notion node
2. Add a few properties
3. Scroll to the bottom
4. See the Add block button is off-screen

**Expected behavior**
Should be visible, and accessible. 

**Environment (please complete the following information):**

- OS: [e.g. Browser access via Windows Chrome]
- n8n Version [e.g. 0.198.0]

**Additional context**

**Comment by Joffcom** [comment]
Hey @memetican,

Can you try updating to the latest release (0.198.2)?

**Comment by memetican** [comment]
Perfect, thanks @Joffcom !

**Comment by memetican** [comment]
UI issue resolved.
