### ISSUE TITLE
Twitter Node image attachments are not working

### ISSUE THREAD

**Issue by macaron** [n8n-io/n8n#4354]
**Describe the bug**
Twitter Node image attachments are not working. (multiple image upload)
However, multiple attachments in the Send Email node work well.
<img width="320" alt="スクリーンショット 2022-10-17 6 13 41" src="https://user-images.githubusercontent.com/19354702/196058638-40908f76-a562-48b0-879e-1d33c947f5f4.png">

**To Reproduce**

1. Get sample images. (binary data)
<img width="1411" alt="スクリーンショット 2022-10-17 5 55 49" src="https://user-images.githubusercontent.com/19354702/196057868-2de49925-5b9e-44c8-aa6d-166e2f410a36.png">

2. Transform binary data.
<img width="1400" alt="スクリーンショット 2022-10-17 5 56 32" src="https://user-images.githubusercontent.com/19354702/196057911-d1d77151-203c-497f-9b77-1450ed305ae2.png">

3. Next, Use Twitter node. Enter the "data" and "data1" to attachements of additional fields.
<img width="929" alt="スクリーンショット 2022-10-17 5 33 09" src="https://user-images.githubusercontent.com/19354702/196057826-d99616a3-5357-41ab-a10b-2264eb43bd1c.png">

4. Go your twitter. Only first attachment Uploaded…🤔 

**Expected behavior**
Upload multiple images.

**Environment (please complete the following information):**
It's a Docker image.
- OS: Alpine Linux v3.16
- n8n Version 0.198.2
- Node.js Version 16.17.0
- Database system SQLite
- Operation mode own

Thank you 🙏

**Comment by Joffcom** [comment]
Hey @macaron,

Thanks for reporting this one, I will look into it shortly.

**Comment by Joffcom** [comment]
Hey @macaron,

I have managed to reproduce the same issue, I know we are planning to overhaul the Twitter node soon which will fix some of the issues and make use of the v2 API so I suspect this will be fixed as part of that but I am going to find out if this is something we plan to fix before then or if it would be a case of waiting a bit longer.

**Comment by Joffcom** [comment]
Afternoon,

We are currently in the process of reviewing the changes for the update to the Twitter node so this should be resolved very soon. I am going to mark this one as closed for now and if it still fails after the updated node comes out we can open it again.

**Comment by rastarr** [comment]
Hi, 
per https://community.n8n.io/t/twitter-x-just-getting-started-but-error/47871/4
This looks to be again broken
Can this please be fixed again?
