### ISSUE TITLE
Sendinblue trigger node unrecognized credentials

### ISSUE THREAD

**Issue by feelgood-interface** [n8n-io/n8n#4356]
**Describe the bug**
The credentials in the sendinblue trigger node are not recognized.

**To Reproduce**
Cannot execute any trigger method.

**Environment (please complete the following information):**
- n8n Version 0.198.2

**Comment by Joffcom** [comment]
Hey @feelgood-interface,

Good spot, Once the CLA is signed I will get this one merged in.

**Comment by Joffcom** [comment]
Hey @feelgood-interface,

This change was merged and released in `0.202.0`
