### ISSUE TITLE
Execution view shows pinned data instead of actual data

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#4385]
**Describe the bug**
I love the addition of pinned data to quickly develop new nodes while having actual data in there.
But now I wanted to check out what data was output by the webhook node during an actual execution, but I only see the pinned data and cannot even unpin it in the read-only view, so I am unable to see the actual data that the webhook node put out.

![image](https://user-images.githubusercontent.com/2084639/196678198-a850a1b2-7e9c-4f78-ab62-6dd37b4d486f.png)

**To Reproduce**

1. Pin data on a webhook node
2. produce an actual execution
3. Open the execution
4. See pinned output of node

**Expected behavior**
I don't think I'd ever care about pinned data in the execution view.
And in general, it might be good to be able to view actual data even if there's something pinnned.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 18.04]
- n8n Version 0.192.2 (docker)
- SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @tennox,

Thanks for reporting this one, we have had a few reports of the same issue on the community forum as well. I have created an internal ticket for this which we will be tracking as N8N-5115.

**Comment by memetican** [comment]
Excellent, was just about to report this as well.

**Comment by Joffcom** [comment]
Hey @tennox,

Bit of a delay on this one, It looks like the notification from November didn't go out but this should be resolved with n8n@0.203.0

The approach taken is...
In executions view, if it's a production execution (not triggered manually), never show a node is pinned or pinned data
In executions view, if it's a manual execution, show pinned output and that node is pinned in canvas

As this should be resolved I am going to mark this one as closed, If you are still seeing this let me know and we can open it again.
