### ISSUE TITLE
Postgresql / cockroachdb serverless `options` db connection param not configurable

### ISSUE THREAD

**Issue by jpizzle34** [n8n-io/n8n#4398]
**Describe the bug**
I would like to connect to a CockroachDB serverless instance using the Postgres node. CRDB Serverless requires specifying the cluster identifier in the `options` db connection property to make a connection, however the current UI for configuring Postgres credentials doesn't support specifying this parameter.

**To Reproduce**

1. Go to 'Credentials" `http://<your-n8n-host>/credentials`
2. Click on 'Add credential' and add a Postgres credential.
3. Enter db connection config based on CRDB connection string `postgresql://<dbuser>:<ENTER-SQL-USER-PASSWORD>@free-tier8.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3D<cluster-identifier>`
4. Click 'Save' to test connection.
5. See error `codeParamsRoutingFailed: missing cluster identifier`

**Expected behavior**
Allow, the user to enter an optional `options` parameter OR a DB connection string instead of parameters.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 18.04
- n8n Version 0.198.2
- Node.js Version [e.g. 16.14.0]
- Database system Postgres, CockroachDB Serverless
- Operation mode: own

**Additional context**
This will affect users attempting to connect to other DB offerings which may require specifying other db connection properties as url query parameters e.g. MySQL

**Comment by Joffcom** [comment]
Hey @jpizzle34,

This looks like more of a feature request than a bug. We track feature requests and allow the community to vote on the features they want on our community support forum.

Would you be able to create a feature request on https://community.n8n.io for this one?

**Comment by jpizzle34** [comment]
Hi @Joffcom,

Sure thing! :) I've created a feature request here: https://community.n8n.io/t/allow-the-user-to-enter-a-connection-string-as-an-alternative-to-parameters-for-database-credentials/18908

Closing this issue as it's a feature request rather than a bug.
