### ISSUE TITLE
In Http request node: Need to raw response of http instead of only when its success

### ISSUE THREAD

**Issue by prasad8mhatre** [n8n-io/n8n#44]
Usecase:
1. There is a need of handling various case as per status code and response from http request.
2. What is default timeout of the http request?
3. let say when there is timeout then a email needs to be sent.
4. So need raw response from http request module and that response will be forwarded to if block and it will transfer it to either true or false flow(sending email).

Please suggest any way to achieve this

**Comment by janober** [comment]
I am trying to have all usage questions in the forum that people have one single place to look if they have a problem. The Github-Issues are planed more for actual bugs in the code. Sorry still have to communicate that properly by for example creating an Issue Template. Hope to get to that soon.

Reposted and answered your questions here:
https://community.n8n.io/t/in-http-request-node-need-to-raw-response-of-http-instead-of-only-when-its-success/99
