### ISSUE TITLE
Airtable update data in table

### ISSUE THREAD

**Issue by IgorKha** [n8n-io/n8n#4415]
**Describe the bug**
Field value not updating from notion to airtable

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- Debian 11 (aarch64)
- docker (20.10.5+dfsg1, build 55c4c88)
- containter build version [0.199.0](https://hub.docker.com/layers/n8nio/n8n/0.199.0/images/sha256-e939054b04a1221b671dc12d5a17768a488bf501ab4b18ca19ccfe9dec69a567?context=explore)

**Additional context**
run container command `docker run -d --name n8n -h rocky --network host -v ~/.n8n:/home/node/.n8n n8nio/n8n`

![2022-10-24_02-08](https://user-images.githubusercontent.com/2268209/197418634-babbbf1c-7fea-4edb-9203-e73c76440330.png)

**Comment by Joffcom** [comment]
Hey @IgorKha,

Thanks for reporting this one, I have just given it a quick go and I have not been able to reproduce it. Looking at your screenshot though I think I can see what the problem might be.

The Fields in Update need to match the name of the Field in Airtable so if you had the default columns in Airtable of...

Name
Notes
Asignee
Status

You would need to make sure the field is set to one of those values, You would also need to make sure that you have the same field name on the incoming items for it to work. Looking at your image removing the expression and just typing in Location and Name it should do the job.

Let me know how you get on.

**Comment by IgorKha** [comment]
Hey @Joffcom
Thanks for your answer!
I removing the expression and just typing in "Location". This is works for me! Thank you!

I also faced the problem of extracting the last modified record from airtable.
The data received relates to record2 although the latest updated record is number 4. How can i fix it?
![Screenshot_20221029_010259](https://user-images.githubusercontent.com/2268209/198741132-965b512e-5beb-4694-988a-ffea646f6a8c.png)
![Screenshot_20221029_010428](https://user-images.githubusercontent.com/2268209/198741156-5d715c4f-ac4d-4c43-9673-0f02d96ce64e.png)

**Comment by IgorKha** [comment]
Does anyone know how to fix it?

**Comment by Joffcom** [comment]
Hey @IgorKha,

It sounds like it might not be a bug and maybe more of a support issue. When you schedule the workflow to run instead of doing a manual run does it work as expected?

**Comment by Joffcom** [comment]
Hey @IgorKha,

I am going to mark this one as closed for now as there is nothing for us to fix, If you are still seeing an issue with using the node I would recommend posting on our [community support forum](https://community.n8n.io) and we can pick it up there and work out if there is a bug or not.

Let me know if you have any questions on this one.
