### ISSUE TITLE
Todoist: migration to new API versions is needed before Nov 30

### ISSUE THREAD

**Issue by Schnouki** [n8n-io/n8n#4430]
**Describe the bug**
The n8n Todoist node is currently using the Todoist [REST v1](https://github.com/n8n-io/n8n/blob/1f4eaeb3ae33ad88a4b07e664e2f8f8f1235bc6f/packages/nodes-base/nodes/Todoist/GenericFunctions.ts#L26) API (and the [Sync v8](https://github.com/n8n-io/n8n/blob/1f4eaeb3ae33ad88a4b07e664e2f8f8f1235bc6f/packages/nodes-base/nodes/Todoist/GenericFunctions.ts#L59) API for moving tasks across projects). These API versions will both be deprecated on Nov 30, and all clients should use the REST v2 and Sync v9 APIs instead:
- [migration guide for the REST API](https://developer.todoist.com/rest/v2/#migrating-from-v1)
- [migration guide for the Sync API](https://developer.todoist.com/sync/v9/#migrating-from-v8)

Between REST v1 and v2, some fields are renamed, and most importantly, all ID types are changed from integers to strings. (At the moment, current int IDs can safely be converted to strings.)

I'm not comfortable enough with Typescript and the n8n codebase to do it myself (especially for the part about migration IDs to a different type), but as a Todoist backend developer and n8n user, I'm willing to help 🙂

**To Reproduce**

- it's not broken yet, but REST API v1 and Sync API v8 will be deprecated on Nov 30.

**Expected behavior**
I'd love if n8n continued working after Nov 30 😅

**Environment (please complete the following information):**

- OS: any
- n8n Version: git master
- Node.js Version: any

**Comment by Joffcom** [comment]
Hey @Schnouki,

Thanks for reporting this one, I am going to take a look later today to see what we need to do. I am sure we will be all good to have any changes added before November 30th.

**Comment by Schnouki** [comment]
Hey @Joffcom,

Sorry, looks like the docs were not updated, but I confirm that Sync v8 will be removed on Nov 30 only. It was initially announced for Oct 31st, but we postponed that; this was announced a few days ago in our [API mailing list](https://groups.google.com/a/doist.com/g/todoist-api/c/08RH6rWTA_8/m/wO-1ZtAwBAAJ). So, no need to rush it this week 🙂

**Comment by Joffcom** [comment]
Perfect that makes life easier thanks @Schnouki

**Comment by Joffcom** [comment]
Hey @Schnouki,

Thought I would let you know that I have started to work on this, Found a couple of little things that need tweaking but it is mostly looking good.

**Comment by Schnouki** [comment]
Thanks for the heads-up, @Joffcom! Again, if you need any help from our side, feel free to ask 😊

**Comment by lukasz18dg** [comment]
@Joffcom , @Schnouki , did you have plan to merge MR?
I am asking, because deadline of update is soon also I hit "brownouts" on Todoist API ( https://groups.google.com/a/doist.com/g/todoist-api/c/33g1sC_ov3Q ), where API just returned information about change version of API or did you have some workaround to avoid problem?

**Comment by Joffcom** [comment]
Hey @lukasz18dg & @Schnouki,

I was away last week but did a quick test yesterday when I got back and passed it over for review, This has been merged and will be in the next release so there may be a few hours of it not working but all will be good when we do the next release later this week.

**Comment by Schnouki** [comment]
Great news, thanks a lot @Joffcom!
