### ISSUE TITLE
DynamoDB nodes failed to Scan large data

### ISSUE THREAD

**Issue by bram-abe** [n8n-io/n8n#4436]
**Describe the bug**
DynamoDB node with Get Many operation and large dataset failed to do `Scan` when returning all result but success if doing `Scan` when returning limited result.

**To Reproduce**
1. Choose DynamoDB table which contain large dataset
2.  Choose `Get Many` on operation field
3. Toggle on `Scan` option
4. Toggle on `Return All` option *Which will lead to failed scan
5. See error messages `ERROR: AWS error response [undefined]: Bad request - please check your parameters`
6. Toggle off `Return All` and set `Limit` field *Which will lead to Success scan
7. The node success to retrieve the data.

**Expected behavior**
Should be able to do `Scan` method and returning all data.

**Environment (please complete the following information):**
- Docker image: n8nio/n8n:0.199.0
- n8n Version: 0.199.0
- Database system: SQlite
- Operation mode: own

**Additional context**
The symptom only happen with large dataset and maybe it is related to how DynamoDB Scan Command handle pagination on each retrieving result that exceed 1MB of size

**Comment by Joffcom** [comment]
Hey @bram-abe,

Thanks for reporting this one, I will take a look at this shortly and see if I can reproduce the issue.

**Comment by Joffcom** [comment]
Hey @bram-abe,

I have not had a chance to look yet some other issues popped up, I will see if I can get to it later this week or next week.

**Comment by Joffcom** [comment]
Hey @bram-abe,

Good news, This has been fixed by a community member and was released with n8n@0.209.1. I am going to mark this one as closed for now and if you still happen to see this issue let me know and we can open it again.
