### ISSUE TITLE
Cloned repo does not start or build with node 

### ISSUE THREAD

**Issue by hixus** [n8n-io/n8n#444]
**Describe the bug**
I cloned the master to check how this thing is build. However I can't get it to build or start. Bootstrap works without errors.

**To Reproduce**
1. git clone git@github.com:n8n-io/n8n.git
2. cd n8n
3. npm run bootstrap
3. npm run build (or npm start dev)
4. Throw multiple scandir errors like
Error parsing bundle asset "/Users/hixus/projects/n8n/packages/editor-ui/dist/js/app.13af670e.js": no such file
Error parsing bundle asset "/Users/hixus/projects/n8n/packages/editor-ui/dist/js/chunk-vendors.a6c588c3.js": no such file

**Expected behavior**
Would build or start without errors.

**Environment (please complete the following information):**
 - OS: OSX Catalina 15.04
 - n8n Version: last git commit hash c5e8f9f0235345fb65b3bf343b1fafd79ce05550
 - Node.js Version: v13.9.0

**Additional context**
Might be node issue but supported version is not stated anywhere

**Comment by janober** [comment]
Ok did now do exactly what you described above with "npm run build" as step 4. 

Tested with node v10.16.0 and the same version you have v13.9.0 both times it did run through perfectly without any error. So no idea why it would fail for you. The main difference between you and me seems to be that I run Ubuntu 18.4 . Not sure if the issue is OSX related. But know from multiple people that they build n8n on OSX fine so would be surprised.

There was however a few commits ago a change to how editor-ui gets build adding cross-env. Not sure if that  could cause that issue. So you could maybe try to build with the hash c267daf778c1f5dd31e1fa946b238e8c72661372

**Comment by hixus** [comment]
> Ok did now do exactly what you described above with "npm run build" as step 4.

`npm run build` was the build step from https://github.com/n8n-io/n8n/blob/master/package.json

> Tested with node v10.16.0 and the same version you have v13.9.0 both times it did run through perfectly without any error. So no idea why it would fail for you. The main difference between you and me seems to be that I run Ubuntu 18.4 . Not sure if the issue is OSX related. But know from multiple people that they build n8n on OSX fine so would be surprised.
> 
> There was however a few commits ago a change to how editor-ui gets build adding cross-env. Not sure if that could cause that issue. So you could maybe try to build with the hash [c267daf](https://github.com/n8n-io/n8n/commit/c267daf778c1f5dd31e1fa946b238e8c72661372)

changed to c267daf and removed node_modules. After reinstall had to add `npm i typscript nodemon` but it still fails

➜  n8n git:(c267daf) ✗ npm run dev

> n8n@ dev /Users/hixus/projects/n8n
> lerna exec npm run dev --parallel

lerna notice cli v3.20.2
lerna info versioning independent
lerna info Executing command in 6 packages: "npm run dev"
n8n: > n8n@0.59.0 dev /Users/hixus/projects/n8n/packages/cli
n8n: > nodemon
n8n-core: > n8n-core@0.28.0 dev /Users/hixus/projects/n8n/packages/core
n8n-core: > npm run watch
n8n-editor-ui: > n8n-editor-ui@0.39.0 dev /Users/hixus/projects/n8n/packages/editor-ui
n8n-editor-ui: > npm run serve
n8n-node-dev: > n8n-node-dev@0.6.0 dev /Users/hixus/projects/n8n/packages/node-dev
n8n-node-dev: > npm run watch
n8n-nodes-base: > n8n-nodes-base@0.54.0 dev /Users/hixus/projects/n8n/packages/nodes-base
n8n-nodes-base: > npm run watch
n8n-workflow: > n8n-workflow@0.25.0 dev /Users/hixus/projects/n8n/packages/workflow
n8n-workflow: > npm run watch
n8n: [nodemon] 2.0.2
n8n: [nodemon] to restart at any time, enter `rs`
n8n: [nodemon] watching dir(s): commands/**/* index.ts src/**/*
n8n: [nodemon] watching extensions: ts
n8n: [nodemon] starting `npm start`
n8n-node-dev: > n8n-node-dev@0.6.0 watch /Users/hixus/projects/n8n/packages/node-dev
n8n-node-dev: > tsc --watch
n8n-editor-ui: > n8n-editor-ui@0.39.0 serve /Users/hixus/projects/n8n/packages/editor-ui
n8n-editor-ui: > env VUE_APP_URL_BASE_API=http://localhost:5678/ vue-cli-service serve
n8n-editor-ui: env: vue-cli-service: No such file or directory
n8n-core: > n8n-core@0.28.0 watch /Users/hixus/projects/n8n/packages/core
n8n-core: > tsc --watch
n8n-editor-ui: npm ERR! code ELIFECYCLE
n8n-editor-ui: npm ERR! syscall spawn
n8n-editor-ui: npm ERR! file sh
n8n-editor-ui: npm ERR! errno ENOENT
n8n-editor-ui: npm ERR! n8n-editor-ui@0.39.0 serve: `env VUE_APP_URL_BASE_API=http://localhost:5678/ vue-cli-service serve`
n8n-editor-ui: npm ERR! spawn ENOENT
n8n-editor-ui: npm ERR!
n8n-editor-ui: npm ERR! Failed at the n8n-editor-ui@0.39.0 serve script.
n8n-editor-ui: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
n8n-nodes-base: > n8n-nodes-base@0.54.0 watch /Users/hixus/projects/n8n/packages/nodes-base
n8n-nodes-base: > tsc --watch
n8n-workflow: > n8n-workflow@0.25.0 watch /Users/hixus/projects/n8n/packages/workflow
n8n-workflow: > tsc --watch
n8n-editor-ui: npm ERR! A complete log of this run can be found in:
n8n-editor-ui: npm ERR!     /Users/hixus/.npm/_logs/2020-04-02T05_57_08_020Z-debug.log
n8n-editor-ui: npm ERR! code ELIFECYCLE
n8n-editor-ui: npm ERR! errno 1
n8n-editor-ui: npm ERR! n8n-editor-ui@0.39.0 dev: `npm run serve`
n8n-editor-ui: npm ERR! Exit status 1
n8n-editor-ui: npm ERR!
n8n-editor-ui: npm ERR! Failed at the n8n-editor-ui@0.39.0 dev script.
n8n-editor-ui: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
n8n-editor-ui: npm ERR! A complete log of this run can be found in:
n8n-editor-ui: npm ERR!     /Users/hixus/.npm/_logs/2020-04-02T05_57_08_042Z-debug.log
lerna ERR! npm run dev exited 1 in 'n8n-editor-ui'
lerna ERR! npm run dev stdout:

> n8n-editor-ui@0.39.0 dev /Users/hixus/projects/n8n/packages/editor-ui
> npm run serve


> n8n-editor-ui@0.39.0 serve /Users/hixus/projects/n8n/packages/editor-ui
> env VUE_APP_URL_BASE_API=http://localhost:5678/ vue-cli-service serve


lerna ERR! npm run dev stderr:
env: vue-cli-service: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! n8n-editor-ui@0.39.0 serve: `env VUE_APP_URL_BASE_API=http://localhost:5678/ vue-cli-service serve`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the n8n-editor-ui@0.39.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hixus/.npm/_logs/2020-04-02T05_57_08_020Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n-editor-ui@0.39.0 dev: `npm run serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n-editor-ui@0.39.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hixus/.npm/_logs/2020-04-02T05_57_08_042Z-debug.log

lerna ERR! npm run dev exited 1 in 'n8n-editor-ui'
lerna WARN complete Waiting for 5 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! n8n@ dev: `lerna exec npm run dev --parallel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the n8n@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by janober** [comment]
Yes, there is nothing wrong with `npm run build`. It is totally correct. But as you mentioned two different commands as step 4 I wanted to tell you with which of both I did the test.

Does `npm run build` now work for you because the above output seems to be from `npm run dev`.

Strange that you have to install typescript and nodemon manually as it is already a dependency in n8n.

The problem seems now to be the missing "vue-cli-service". I have that also installed globally and so that is then probably the reason why everything works for me and others but not for you. Can you try to add `@vue/cli` as a dev-dependency and then test again. Because that should for sure also be a dev-dependency.

**Comment by maxmarines** [comment]
@hixus 
I also had many similar problems.
my recipe for solving:

1. installing the latest version of Node.JS & NPM
2. execution of instructions indicated on this page https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#development-setup
3. The result is a successful build & launch n8n locally Windows Subsystem for Linux.

![n8n](https://user-images.githubusercontent.com/62845038/78228948-fd9df680-74d7-11ea-8b69-96db45f917d3.jpg)

**Comment by pestevez** [comment]
@hixus - I am also running macOS Catalina and had the same issues; but I managed to get n8n running locally.

After a lot trial and error I ended up getting the following line in one of the errors:

> gyp: No Xcode or CLT version

First, I followed the steps described at https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d to get rid of that issue.

Then, I followed the installation steps described at https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#development-setup starting at the installation of lerna.

I got a few errors but finally got it to build and run successfully. I hope this helps!

**Comment by janober** [comment]
Thanks a lot @maxmarines and @pestevez for your help! With all Mac and Windows related issues, I am always totally lost. So is great to have people like you in the community that help!

**Comment by hixus** [comment]
@pestevez thanks but gyp is working fine and I also followed those guides. Somehow the paths the build tires to use seem incorrect (not too falimiliar with lerna and multiple packages). Did you need to do anything extra that is not in the contributing doc?

**Comment by hixus** [comment]
Ok, removed the whole repo and tried again and it worked. Initally I just installed lerna as dep of n8n as didin't want it to global. Also initially while retrying i just removed toplevel node_modules which might have not been enough as this is monorepo project.
