### ISSUE TITLE
[Consumer] Crash: KafkaJSNotImplemented: Snappy compression not 

### ISSUE THREAD

**Issue by gw123** [n8n-io/n8n#4444]
**Describe the bug**
 I use n8n kafka trigger  ,  when the message coming  , an error occurred.

**{"level":"ERROR","timestamp":"2022-08-24T07:00:30.551Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 10)","broker":"[192.168.58.176:9092](http://192.168.58.176:9092/)","clientId":"n8n-xxxx","error":"Snappy compression not implemented","correlationId":97,"size":202}
{"level":"ERROR","timestamp":"2022-08-24T07:00:30.553Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNotImplemented: Snappy compression not implemented","groupId":"sssssss","stack":"KafkaJSNotImplemented: Snappy compression not implemented\n    at 2 (/usr/local/lib/node_modules/n8n/node_modules/kafkajs/src/protocol/message/compression/index.js:16:11)\n    at lookupCodecByAttributes 

I found a solution.  
https://github.com/nodefluent/node-sinek/issues/162

**Comment by Joffcom** [comment]
Hey @gw123,

Nice find, I don't think this is a bug as such though and is more of a feature request as we don't support Snappy compressed data at the moment. I can see you have a PR open for this one so I will create an internal ticket for it so we can get it reviewed.

For now I will get this one closed and we can talk on the PR 👍🏻
