### ISSUE TITLE
Continue on Fail is not working properly with AWS Lambda node

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#4452]
**Describe the bug**
Hello! For some nodes (e.g. Lambda) the mode option "Continue On Fail" does not shows the error details.

**To Reproduce**

1. Create a Lambda node
2. Add broken JSON (like forget some quotes)
 `{"hello":123"}`
3. Turn on "Continue On Fail"

Example workflow:
`{
  "meta": {
    "instanceId": "b2b258e8cf8e4b51c801b3bc5a9906c37aad0545d9cdbdf096a6542b5d192385"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "e98a6223-004d-4d18-8393-7657f525d416",
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        300
      ]
    },
    {
      "parameters": {
        "function": "arn:aws:lambda:us-west-2:114025810846:function:soc-prd-GraphAPI",
        "payload": "{\"helo\":123\"}"
      },
      "id": "9cc5cf1c-e680-48b0-8c77-79afed512e7b",
      "name": "AWS Lambda",
      "type": "n8n-nodes-base.awsLambda",
      "typeVersion": 1,
      "position": [
        460,
        300
      ],
      "credentials": {
        "aws": {
          "id": "2",
          "name": "AWS account"
        }
      },
      "continueOnFail": true
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "AWS Lambda",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Expected behavior**
We can see that the error is related to the JSON syntax in the output, but getting the basic "Unknown error"

**Environment (please complete the following information):**

- n8n Version 0.195.5

**Additional context**
Expected behaviour - we see the NodeApiError in output
![image](https://user-images.githubusercontent.com/15629670/198056268-921d4881-8998-4dad-8b7d-a86d887a5818.png)

But there is no NodeApi related info in the output
![image](https://user-images.githubusercontent.com/15629670/198056334-362214d2-61be-4574-8171-d17adf2f7f1e.png)

**Comment by Joffcom** [comment]
Hey @barn4k,

Thanks for the report, That looks like continue on fail has worked correctly but it doesn't have a meaningful error message. This doesn't look like a bug which is what we use Github issues for but it is something we could and should look at improving in a future release.

**Comment by Joffcom** [comment]
Hey @barn4k,

I am going to mark this one as closed for now as it isn't really a bug, We are slowly working on making the errors better. If you have any other questions on this one let me know and we can look at opening this again.
