### ISSUE TITLE
Failed execution There was a problem executing the workflow: "Cannot read properties of undefined (reading 'node')"

### ISSUE THREAD

**Issue by gw123** [n8n-io/n8n#4456]
**Describe the bug**

Failed execution
There was a problem executing the workflow:
"Cannot read properties of undefined (reading 'node')"

 webhook
http://172.21.125.38/webhook/e6c61b21-5388-4df0-a26f-76971c805c6d

press test
wrk  -t50 -c1000 -d20s --latency http://172.21.125.38/webhook/e6c61b21-5388-4df0-a26f-76971c805c6d
Running 20s test @ http://172.21.125.38/webhook/e6c61b21-5388-4df0-a26f-76971c805c6d
  50 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.65s   221.43ms   2.00s    73.25%
    Req/Sec    17.76     16.47   130.00     81.78%
  Latency Distribution
     50%    1.67s
     75%    1.82s
     90%    1.90s
     99%    1.97s
  11575 requests in 20.10s, 5.55MB read
  Socket errors: connect 0, read 0, write 0, timeout 559
Requests/sec:    575.86
Transfer/sec:    282.87KB

i found a lot of Failed execution

**Comment by Joffcom** [comment]
Hey @gw123,

It looks like you have not filled out the template which normally gives us information on how you have n8n setup. In this case though what is the bug you are seeing and what is the output you are expecting?  If you are load testing it would be worth looking into scaling mode so that it can handle more connections and you would then be able to automatically add workers nodes as the load increases depending on what you are using.

**Comment by gw123** [comment]
This is the workflow template json.  
`{
  "name": "My workflow 3",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "position": [
        240,
        300
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "content": "## (/static/quickstart_thumbnail.png#full-width)](https://www .youtube.com/watch?v=RpjQTGKm-ok)",
        "height": 300,
        "width": 380
      },
      "name": "_QUICKSTART_NOTE_",
      "type": "n8n-nodes-base.stickyNote",
      "position": [
        -260,
        200
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "path": "e6c61b21-5388-4df0-a26f-76971c805c6d",
        "options": {}
      },
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "position": [
        460,
        300
      ],
      "webhookId": "e6c61b21-5388-4df0-a26f-76971c805c6d",
      "typeVersion": 1
    }
  ],
  "pinData": {},
  "connections": {},
  "active": true,
  "settings": {},
  "id": 3,
  "tags": []
}`

i have  use scaling mode  like this.    
1 master 4 webhook  6 worker
`NAME                           READY   STATUS    RESTARTS   AGE
n8n-84df86bccc-f6smd           1/1     Running   0          10h
n8n-webhook-7bb84987f7-cc92f   1/1     Running   3          10h
n8n-webhook-7bb84987f7-ftms8   1/1     Running   1          10h
n8n-webhook-7bb84987f7-njrzs   1/1     Running   3          23h
n8n-webhook-7bb84987f7-nvzmc   1/1     Running   1          10h
n8n-worker-57c87589dd-8xctc    1/1     Running   0          10h
n8n-worker-57c87589dd-j6n65    1/1     Running   0          10h
n8n-worker-57c87589dd-r8lgz    1/1     Running   0          10h
n8n-worker-57c87589dd-twnlk    1/1     Running   0          10h
n8n-worker-57c87589dd-v4lgz    1/1     Running   0          10h
n8n-worker-57c87589dd-vvlx4    1/1     Running   0          10h`

**Comment by Joffcom** [comment]
Hey @gw123,

What about the other part? The main things I need to know at the moment are what is the bug you are actually seeing and what you do expect to see happen?

**Comment by gw123** [comment]
a lot of error  
![image](https://user-images.githubusercontent.com/13729169/198912496-928ad6f2-009f-447e-b1c8-7b9a3049a494.png)

**Comment by Joffcom** [comment]
Hey @gw123,

Can you be more specific? Are you currently load testing n8n or doing something else?

**Comment by gw123** [comment]
i just do load testing n8n， just one workflow.   one webhook node in workflow.
![image](https://user-images.githubusercontent.com/13729169/199139604-be344eba-a12a-46bc-8101-e5c424459f71.png)
![image](https://user-images.githubusercontent.com/13729169/199139666-4ef6c294-e81c-4509-a26e-f9d798d7ee2a.png)

**Comment by Joffcom** [comment]
Hey @gw123,

What are you expecting the outcome of the testing to be? At some point you will likely always hit an issue so it would be a case of adding more webhook workers to deal with the load.

I am still not actually sure what the actual issue is here.

**Comment by gw123** [comment]
In the above workflow, when my http pressure reaches 100QPS, there will be a lot of failures in process execution. The error "Cannot read properties of undefined (reading 'node')" will be reported.  Let me ask the reason for this error.

**Comment by Joffcom** [comment]
Hey @gw123,

It sounds like it is trying to read a value and it is not defined, This could be coming from a few places the full error message from the log may be useful, Did you work out which node was sending the message back and was the load distributed evenly or was it weighted?

**Comment by Joffcom** [comment]
Hey @gw123,

As this is likely going to be an issue with with workflow or configuration for now I am going to mark this one as closed and if you are still running into this feel free to pop open a post on our [community support forum](https://community.n8n.io) with information on your existing environment, the workflow and what the goal is and we can take a look.
