### ISSUE TITLE
n8n-core doesn't provide typescript .d.ts files

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#4464]
**Describe the bug**

When importing `n8n-core` files, the TypeScript types are missing:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/193115/198540023-9890d5ec-23b9-4221-94d8-a5693daf6f19.png">

    yarn add n8n-core

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/193115/198540161-9ef21949-abd6-4be0-b993-1a3fe73a3df8.png">

**Comment by Joffcom** [comment]
Hey @haf,

Would you be able to share more information on what you are trying to do?

**Comment by haf** [comment]
I'm creating a new node following https://github.com/n8n-io/n8n-nodes-starter and https://docs.n8n.io/integrations/creating-nodes/plan/
