### ISSUE TITLE
EditorTypes missing 'codeNodeEditors'

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#4472]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/193115/198635613-a4aa3ca8-1b54-48d9-891c-0fe280f6e07e.png">

**Comment by Joffcom** [comment]
Hey @haf,

Would you be able to fill out the provided template? For this one it looks like it is a valid option: https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/Interfaces.ts#L950

Did you run the npm install command to get everything set up or are you maybe using an old version of n8n?
