### ISSUE TITLE
How to static average running time of my workflow?

### ISSUE THREAD

**Issue by dolphin111213** [n8n-io/n8n#4479]
** Description **
I need to know average running time of my workflow,  But now I can only see the total time cost in Executions page, How can I do some statics of executed workflows? For example, average running time, status, total counts during a specified time period.

BTW, I would really appreciate it if I can static time cost of specified component in my flow.

**Comment by janober** [comment]
Sorry but GitHub issues are only for bugs. All question and feature requests have to be posted to the community forum here:
https://community.n8n.io/

Thanks!
