### ISSUE TITLE
GitLab Webhook is not been created

### ISSUE THREAD

**Issue by Eweol** [n8n-io/n8n#4483]
**Describe the bug**
I created an workflow, which starts with an GitLab-Trigger.
After creation and testing I want to activate the workflow but this fails with frontend error message

``Workflow could not be activated:
The URL path that the "Gitlab Trigger" node uses is already taken. Please change it to something else.``

In the logs I see following error

``Could not remove webhooks of workflow "23" because of error: "relation "public.webhook_entity" does not exist"``

**To Reproduce**

1. Create a new workflow which starts with an GitLab trigger
2. Configure the trigger with an Access Token Authentication and everything else what is needed.
3. Test the GitLab trigger with auto created Test URL -> everything works quite fine
4. Try to activate the workflow

**Expected behavior**
Workflow activation fail, Webhook is not been created on GitLab Repo

**Expected behavior**
Workflow will been activated and the Webhook will been set automatically within GitLab repo

**Environment (please complete the following information):**

- OS: [Docker]
- n8n Version [0.194.0]
- Node.js Version [I don't know]
- Database system [postgres]
- Operation mode [own]

**Additional context**

**Comment by Joffcom** [comment]
Hey @Eweol,

Can you try upgrading? I remember fixing an issue with Gitlab a couple of versions back so this could be resolved already.

**Comment by Eweol** [comment]
Hi @Joffcom,

Thanks for that info, I upgraded my n8n instance to 0.200.1 but the issue is still there with same error messages.
I also tried in the new version to recreate my workflow but the issue is still there.

**Comment by Joffcom** [comment]
Hey @Eweol,

That is worrying, Is there any webhooks setup in your Github repo? I have just given a quick test here and I am unable to reproduce the error.

The initial error sounds like maybe the Gitlab trigger node has been copied from another workflow that is active already but if you have remade the workflow that shouldn't be an issue.

**Comment by Joffcom** [comment]
Hey @Eweol,

That is very strange, is it self hosted Gitlab?

Can you share what environment variables you have set for your n8n instance?

**Comment by Eweol** [comment]
Hi @Joffcom,

No its the official cloud hosted
 GitLab.![Screenshot_20221031-212154.png](https://user-images.githubusercontent.com/22490016/199104116-dc1e788d-a4fa-4d87-ba58-d1a1d68fe4d6.png)

**Comment by Eweol** [comment]
Hi @Joffcom,

Today I changed "N8N_SKIP_WEBHOOK_DEREGISTRYTION_SHUTDOWN" to false.
After that change my N8N instance isn't starting anymore.

No I get in logs 
``There was an error: relation "webhook_entity" does not exist``

Can you provide me information how webhook stuff is stored in DB?

**Comment by Eweol** [comment]
It seems also like I don't have the webhook_entity table in postgres which is maybe needed?

**Comment by Joffcom** [comment]
Hey @Eweol,

I am not sure why that is failing, last time the issue happened I was able to reproduce it but this time everything appears to be looking good.

I will need to dig out the schema for the database to check what we do there, has there ever been issues with your installs and maybe a downgrade was needed?

**Comment by Eweol** [comment]
No so far I didn't had problems with N8N, but before I didn't used GitLab Trigger.
So far I only upgraded no downgrades.

**Comment by Eweol** [comment]
It becomes more wired
I had a look to an fresh installation and figured out, that in my installation the webhook database is not there.

After that I wanted to create the missing table.
This fails with following error.
``ERROR:  type "webhook_entity" already exists
HINT:  A relation has an associated type of the same name, so you must use a name that doesn't conflict with any existing type.``

I'm not an expert but I could imagen, that the database is whyever broken on my installation.
Is there a chance to recreate the webhook_entity table?

**Comment by Eweol** [comment]
with \dt public.* I can see table webhook_entity
with \d I cannot

**Comment by Joffcom** [comment]
Hey @Eweol,

What is `\d` and `\dt` I assume maybe some postgres command?

We should be using the public schema by default so that should be ok, On my test instance I also use Postgres so I don't think it is directly related to that. Missing the webhook database would be very strange though and the only thing I can think of for it missing would be a downgrade at some point and maybe a migration didn't go as planned.

**Comment by Eweol** [comment]
Yeah,
Thank you for your help.
I don't think that this is reproduceable in any case but it looks like an data storing issue.

I will recreate my database by dumping data, than completely create in from scratch and that import my still existing data again.

should I have further issues after reimporting the data I will reopen but so far I think this can be closed.

THX
