### ISSUE TITLE
Error Importing Workflow from File

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4485]
**Describe the bug**

When exporting a workflow to a file and importing it again, the Editor does not respond... not allowing select nodes.

This error only happens in version 0.200.1. The same procedure in version 0.199 works well.

**To Reproduce**

1.  Export Workflow to a File
2. Import Workflow from File

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version  0.200.1
- Node.js Version [e.g. 14.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by luizeof** [comment]
Hello @Joffcom .. how are you?

This is strange behavior noticed in version 0.200.1

Copying and pasting works normally, but importing crashes everything.

**Comment by Joffcom** [comment]
Hey @luizeof,

Thanks for the report, I will check this out in the morning when I start unless someone gets to it before me.

**Comment by Joffcom** [comment]
Hey @luizeof,

I have managed to reproduce this one and I have created `N8N-5333` as our internal ticket for tracking it.

**Comment by cgsmith** [comment]
Is it possible to have build instructions for node 14? I run into an error on `turbo run build` when trying to build with older node versions. I can open a new ticket if necessary.

**Comment by Joffcom** [comment]
Hey @cgsmith,

Are you on the right issue?

**Comment by cgsmith** [comment]
I think so. I tried duplicating the issue of importing from a file - it worked for me with node 16 but i could not build n8n with node 14 after switching with `nvm use 14.16.0`

**Comment by Joffcom** [comment]
Ah ok, When I tried with was node 16.

I think there may be some steps for 14 in the github action but I think we moved away from 14 and onto 16 a few months back.

**Comment by cgsmith** [comment]
Oh interesting. I didn't have an issue that @luizeof had with node 16 in 0.200.1 - tested on two instances. Mind sharing the steps you tried or a workflow I could test importing?

**Comment by Joffcom** [comment]
Pretty much the steps in the report, did an export from the UI then tried an import once imported the nodes can't be interacted with and it looks like it may be doubling up on the nodes. 

It does work if you use the cli tool.

**Comment by cgsmith** [comment]
That's what I thought was strange. I am running 0.200.1 on docker but with node 16.17.0 in the docker container.

Hopefully this GIF will render to show you it works.

Here is the "My Workflow.json" file I tried importing that worked on mine.

```json
{
  "name": "My workflow",
  "nodes": [
    {
      "parameters": {},
      "id": "8bc50d39-a0af-4e94-a25b-49dfdcc06c35",
      "name": "On clicking 'execute'",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        820,
        420
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "value": "test"
            }
          ]
        },
        "options": {}
      },
      "id": "da8aae56-11a2-44ff-ad3b-adfbe6c02bec",
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        1040,
        420
      ]
    }
  ],
  "pinData": {},
  "connections": {
    "On clicking 'execute'": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "meta": {
    "instanceId": "3df5f1aff19d2be2730ded8678afd2b749354c522e10d48da03969a73a7d5c8b"
  },
  "tags": []
}
```

![Peek 2022-11-03 13-37](https://user-images.githubusercontent.com/570018/199806800-c37c2adb-79cd-4115-ac4a-8fe6c1581f73.gif)

**Comment by Joffcom** [comment]
How odd, 2 of us have managed to reproduce internally.

**Comment by cgsmith** [comment]
Can you share the workflow or did you use the one I pasted?

**Comment by Joffcom** [comment]
Hey @cgsmith,

I could but it won't be until Monday now although I believe the front end team have actually fixed this now so it won't be an issue in the next release.

**Comment by devtrex007** [comment]
I am also having the same issue with n8n v0.201.0 on node v16.18.0

**Comment by devtrex007** [comment]
> same problem, docker version

Docker Desktop 4.13.1 (90346)

**Comment by Joffcom** [comment]
Hey all,

Can you try on the version released today and let me know if the issue is still there for you.

**Comment by devtrex007** [comment]
Hi @Joffcom, The new version (v0.202.1) has solved this problem, Thank you, you’re amazing!

**Comment by Joffcom** [comment]
@luizeof you should be good to go now, I am going to mark this one as closed 🙌🏻 thanks again for the report.

**Comment by luizeof** [comment]
@Joffcom tested today .. Works fine 👍
