### ISSUE TITLE
HTTP Request node with ISO Date Format Error after update to 0.200.1 version

### ISSUE THREAD

**Issue by juangarat** [n8n-io/n8n#4489]
Hi, we update n8n to last version (0.200.1) from 0.197.1.

After update to this last version, one Workflow starts to fail. 
I'm troubleshooting and found that the fail is in "HTTP Request" node, with a request to an api, that has some date's in ISO format in the body. 
The failed error is:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/35067502/199141228-faa02e8c-a04a-4158-9f2c-5666df234c7e.png">

with this stack trace:
`NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1158:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:658:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:562:53`

The problem is that the node is making the request with ISO Format, like you can see in this image:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/35067502/199141363-8404957f-632b-4887-8a6c-d0cbfc789c93.png">

`{"start": "2022-10-02T01:49:29.992Z", "end": "2022-12-01T01:49:29.992Z","pa...`

I enabled debug log in n8n and found the error and the request body is **NOT** in ISO format date
<img width="668" alt="image" src="https://user-images.githubusercontent.com/35067502/199141674-9014e4b1-1314-47b6-b808-5914b6d6c5d0.png">

This same error happens in HTTP Request V2
`NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V2/HttpRequestV2.node.js:907:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:658:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:562:53``

I go back to 0.197.1 version and the HTTP Request Node works fine:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/35067502/199142349-d40a7382-c2bb-4487-a7cd-e9a1f6b7a5be.png">

Thanks

**Comment by Joffcom** [comment]
Hey @juangarat,

Can you share the workflow you are using or an example workflow that reproduces the issue? The issue might be seen at the http request but the problem could be coming from a node earlier in the process.

**Comment by juangarat** [comment]
Hi @Joffcom 

This is a workflow snapshot:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/35067502/199226645-3ac26304-2331-48b3-bd68-f526cb27e2e2.png">


The node before is a Javascript generating a JSON output, this works fine.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/35067502/199227197-65f33d5d-aee5-4fb3-93c5-925fd7b9c237.png">


You can see in an attached screenshot that the body of the request is fine.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/35067502/199227077-619fbcf1-3ffc-44a5-85e7-0f7dae409ec4.png">

The input data is fine and in ISO format.
If I copy and paste the body and made the request with Postman works fine.

The HTTP Request makes a POST against a paid feature of Clockify (clockify.me). I don't know if the workflow would work if I share it to you.

Hope this can work.
Let me know if this is useful or do you need anything else.

Thanks.

**Comment by juangarat** [comment]
This is the HTTP Request JSON POST Body
`{"start": "2022-10-02T11:55:13.882Z", "end": "2022-12-01T11:55:13.883Z","page":1,"pageSize":100,"status":["APPROVED"],"users":{"contains":"DOES_NOT_CONTAIN","ids":[],"status":"ACTIVE"},"userGroups":{"contains":"DOES_NOT_CONTAIN","ids":[],"status":"ACTIVE"}}`

Maybe this help making a request to a Mock or something like that.

I go back to 0.197.1 and the workflow works fine in this version
![image](https://user-images.githubusercontent.com/35067502/199249700-5f3575e6-f75b-42da-825b-eb318f911f7a.png)

**Comment by Joffcom** [comment]
Hey @juangarat,

There was a report on the support forum as well, looks like adding `toString()` to the end of the variable may work around it for now.

**Comment by juangarat** [comment]
I try again with the last version, 0.202.1 and this issue was fixed. 
Thanks.
