### ISSUE TITLE
Node References Incorrect Google Folder ID

### ISSUE THREAD

**Issue by helpdesk-at-REVREBEL** [n8n-io/n8n#4506]
**Describe the bug**

**To Reproduce**

See screen from Workflow, I have a Google Drive Folder ID referenced to save a file to yet it errors out trying to keep to another entirely different ID I have not idea where it came from.

**Expected behavior**
Error Occurs

ERROR: The resource you are requesting could not be found
File not found: 1e7Bbf2ffYKVV0dtdDcJaA8mDyi7ne5Tf.
 Details
Time
11/2/2022, 4:51:11 AM
HTTP Code
404
Cause
Data below may contain sensitive information. Proceed with caution when sharing.
{
"message": "404 - {"error":{"code":404,"message":"File not found: 1e7Bbf2ffYKVV0dtdDcJaA8mDyi7ne5Tf.","errors":[{"message":"File not found: 1e7Bbf2ffYKVV0dtdDcJaA8mDyi7ne5Tf.","domain":"global","reason":"notFound","location":"fileId","locationType":"parameter"}]}}",
"name": "Error",
"stack": "Error: Request failed with status code 404 at createError (/home/n8n/node_modules/axios/lib/core/createError.js:16:15) at settle (/home/n8n/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/home/n8n/node_modules/axios/lib/adapters/http.js:269:11) at IncomingMessage.emit (node:events:525:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
Stack
NodeApiError: The resource you are requesting could not be found
    at Object.googleApiRequest (/home/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Drive/GenericFunctions.js:41:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.execute (/home/n8n/node_modules/n8n-nodes-base/dist/nodes/Google/Drive/GoogleDrive.node.js:2243:40)
    at async Workflow.runNode (/home/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:619:28)
    at async /home/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:557:53

**Environment (please complete the following information):**

- OS: UBUNDU
- n8n Version [e.g. 0.119.0]
- Node.js Version v0.195.5
- Database system SQLLite
- Operation mode own

**Additional context**

{
  "meta": {
    "instanceId": "ef9fe3dacc55489eadbf625f73a13ca89eec8d94c901a2ef424724cab8fce3e0"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "04e69622-bc95-49ee-bff5-17681ac2933b",
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        -60,
        1800
      ]
    },
    {
      "parameters": {
        "operation": "limit"
      },
      "id": "8b6e5305-bdc7-426a-a9ed-6f16f6486818",
      "name": "Remove Other Item, Keep Primary Keys",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 1,
      "position": [
        -1340,
        1760
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "string": [
            {
              "name": "rr_hotelcode",
              "value": "={{$json[\"rr_hotelCode\"]}}"
            }
          ]
        },
        "options": {}
      },
      "id": "c72e80b0-e46a-4138-b3c6-a093a1a5882c",
      "name": "Break-Out City",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -1340,
        1960
      ]
    },
    {
      "parameters": {
        "mode": "multiplex"
      },
      "id": "76a5c69e-5190-4207-baaf-980e2e0f37fb",
      "name": "Merge",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        -1100,
        1820
      ]
    },
    {
      "parameters": {},
      "name": "NoOp1",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        -1160,
        2320
      ],
      "id": "93e57334-b52d-4652-95d0-a94a9955e296"
    },
    {
      "parameters": {
        "workflowId": "25"
      },
      "id": "e9c25580-0be9-4a00-af63-9cc7b241b59e",
      "name": "Execute Workflow",
      "type": "n8n-nodes-base.executeWorkflow",
      "typeVersion": 1,
      "position": [
        -600,
        2320
      ]
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "operation": "download",
        "fileId": "={{$json[\"id\"]}}",
        "options": {}
      },
      "id": "38991d5a-8eae-467e-996c-3fa21e2454b4",
      "name": "Download Original File",
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 2,
      "position": [
        -860,
        2040
      ],
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "operation": "list",
        "useQueryString": true,
        "queryString": "'1VUuc5YGToe2eWbRsrhg2Vh4xv_IE-4LP' in parents and trashed = false",
        "limit": 1,
        "options": {}
      },
      "id": "02acf78f-1444-46a9-829c-88d97da1d66c",
      "name": "Query for Files",
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 2,
      "position": [
        -560,
        1800
      ],
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "operation": "delete",
        "fileId": {
          "__rl": true,
          "value": "={{$node[\"Query for Files\"].json[\"id\"]}}",
          "mode": ""
        }
      },
      "id": "eb800dfb-a81f-44b0-b3bb-5dc3bc57fda0",
      "name": "Delete Original File",
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 2,
      "position": [
        -960,
        2320
      ],
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "sheetId": "1JojD_hMCsRgHOL7-XJ6oHhd3zyXtrj2j6Xa9tEAni4s",
        "range": "rr_hotelCode!A:G",
        "options": {}
      },
      "id": "0ba0f43d-0e63-454b-9954-b236d2862940",
      "name": "Get Hotel Codes",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 2,
      "position": [
        -1560,
        1900
      ],
      "executeOnce": true,
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "operation": "lookup",
        "sheetId": "1JojD_hMCsRgHOL7-XJ6oHhd3zyXtrj2j6Xa9tEAni4s",
        "range": "rr_hotelCode!A:G",
        "lookupColumn": "rsd_hotelId",
        "lookupValue": "={{$node[\"Read File Pass 1\"].json[\"Hotel_ID\"]}}",
        "options": {
          "returnAllMatches": true
        }
      },
      "name": "Find HotelCode",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 1,
      "position": [
        -1560,
        1720
      ],
      "alwaysOutputData": true,
      "id": "2ae7b7af-f2ac-4251-8555-ff6dab38d544",
      "executeOnce": true,
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "sheetId": "1JojD_hMCsRgHOL7-XJ6oHhd3zyXtrj2j6Xa9tEAni4s",
        "range": "dataMapping!A:D",
        "options": {}
      },
      "id": "41842e24-03dc-4b9a-a3ad-6eeb874e7d4b",
      "name": "Get Config File",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 2,
      "position": [
        -1560,
        1560
      ],
      "executeOnce": true,
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "operation": "lookup",
        "sheetId": "1JojD_hMCsRgHOL7-XJ6oHhd3zyXtrj2j6Xa9tEAni4s",
        "range": "dataMapping!A:D",
        "lookupColumn": "lookUpKey",
        "lookupValue": "={{$node[\"Find HotelCode\"].json[\"rr_hotelCode\"]}}_03-ShopIn",
        "options": {
          "returnAllMatches": true
        }
      },
      "name": "Find File ID",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 1,
      "position": [
        -1340,
        1560
      ],
      "alwaysOutputData": true,
      "id": "cad93aa2-325e-4304-af66-cf101052ee31",
      "executeOnce": true,
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "252d11e3-0fda-4f0d-9def-5421c64c0b59",
      "name": "Read File Pass 1",
      "type": "n8n-nodes-base.spreadsheetFile",
      "typeVersion": 1,
      "position": [
        -1560,
        2060
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "7ffd337a-85c3-4dd2-ae33-f74a95b2d462",
      "name": "Read File Pass 2",
      "type": "n8n-nodes-base.spreadsheetFile",
      "typeVersion": 1,
      "position": [
        -1140,
        2040
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "Rateshop_Date",
              "value": "={{new Date(Math.round($json[\"Rateshop_Date\"] - 25569) * 86400 * 1000).toLocaleString(DateTime.DATETIME_SHORT)}}"
            },
            {
              "name": "Arrival_Date",
              "value": "={{new Date(Math.round($json[\"Arrival_Date\"] - 25569) * 86400 * 1000).toLocaleString(DateTime.DATETIME_SHORT)}}"
            }
          ]
        },
        "options": {
          "dotNotation": false
        }
      },
      "name": "Format Dates",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -1100,
        1580
      ],
      "id": "57ff2b2c-c3d5-4557-a9b4-6c4a5e886d92"
    },
    {
      "parameters": {
        "fileName": "={{$node[\"Format Dates\"].json[\"rr_hotelCode\"]}}_{{$node[\"Format Dates\"].json[\"rsd_rateshop_date\"].replace(/\\,.*/g,\"\").replace('/', '').replace('/', '')}}_rateshopdata.csv"
      },
      "name": "Move from Binary to CSV",
      "type": "n8n-nodes-base.writeBinaryFile",
      "typeVersion": 1,
      "position": [
        -1360,
        2320
      ],
      "id": "cdfbbd82-ec6b-4562-b69e-2e7722ee36f5"
    },
    {
      "parameters": {
        "conditions": {
          "boolean": [
            {
              "value1": true,
              "operation": "notEqual",
              "value2": "={{Object.keys($items()[0].json).length === 0}}"
            }
          ]
        }
      },
      "id": "ef4baf8c-b5b1-41d2-a9eb-39d1fd66103c",
      "name": "Check if Files Exist",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        -860,
        1820
      ]
    },
    {
      "parameters": {
        "table": "rsd_rateshop_data",
        "columns": "rsd_arrivaldate, rsd_channelid, rsd_hotelname, rsd_currency, rsd_demand, rsd_guests,rsd_los, rsd_mealtype, rsd_membershiptype, rsd_rate, rsd_rate_1_days_ago, rsd_rate_3_days_ago, rsd_rate_7_days_ago, rsd_rateremark, rsd_rateremark_1_days_ago, rsd_rateremark_3_days_ago, rsd_rateremark_7_days_ago, rsd_rateshop_date, rsd_ratetype, rsd_requested_ratetype, rsd_roomname, rsd_roomtype, rr_hotelcode, rsd_hotelid",
        "additionalFields": {
          "mode": "multiple"
        }
      },
      "name": "Send Data to Postgres",
      "type": "n8n-nodes-base.postgres",
      "typeVersion": 1,
      "position": [
        -420,
        1360
      ],
      "id": "ee3da395-5754-444e-9f33-b2be33ead6a6",
      "credentials": {
        "postgres": {
          "id": "12",
          "name": "Postgres - STRDB_TEST"
        }
      }
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "binaryData": true,
        "name": "={{$node[\"Rename to Match Database\"].json[\"rr_hotelcode\"]}}_{{$node[\"Rename to Match Database\"].json[\"rsd_rateshop_date\"].replace(/\\,.*/g,\"\").replace('/', '').replace('/', '')}}_rateshopdata.csv",
        "parents": [
          "={{$node[\"Find File ID\"].json[\"folderId\"]}}"
        ],
        "options": {}
      },
      "id": "2370da19-6103-4285-a821-0cf247341e0d",
      "name": "Save Processed File1",
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 2,
      "position": [
        -60,
        1580
      ],
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    },
    {
      "parameters": {
        "operation": "toFile",
        "fileFormat": "csv",
        "options": {}
      },
      "id": "defc8cca-613e-4e31-866b-462d005983e5",
      "name": "Write Database File to CSV",
      "type": "n8n-nodes-base.spreadsheetFile",
      "typeVersion": 1,
      "position": [
        -240,
        1580
      ]
    },
    {
      "parameters": {
        "unit": "minutes"
      },
      "id": "6ae3e78e-83ae-4956-b530-e8a482136f93",
      "name": "Wait 1 Min Before Restart",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        -560,
        2040
      ],
      "webhookId": "bc9c3390-814a-4eda-be53-15f5c9e972b4"
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "rsd_key",
              "value": "={{$json[\"rr_hotelcode\"]}}-{{$json[\"Rateshop_Date\"].replaceAll('/',\"\")}}-{{$json[\"Arrival_Date\"].replaceAll('/',\"\")}}-{{$json[\"Competitor_ID\"]}}"
            }
          ]
        },
        "options": {
          "dotNotation": false
        }
      },
      "name": "Add Unique Rate Shop Key",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -700,
        1580
      ],
      "id": "e36f0d4b-33be-4a23-be54-85d40198477c"
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "Rateshop_Date",
              "value": "={{$json[\"Rateshop_Date\"].replace(/\\,.*/g,\"\")}}"
            },
            {
              "name": "Arrival_Date",
              "value": "={{$json[\"Arrival_Date\"].replace(/\\,.*/g,\"\")}}"
            }
          ]
        },
        "options": {
          "dotNotation": false
        }
      },
      "name": "Remove Time from Dates",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        -900,
        1580
      ],
      "id": "5ac647de-9143-458b-b968-897066ac4cd4"
    },
    {
      "parameters": {
        "keys": {
          "key": [
            {
              "currentKey": "Hotel_ID",
              "newKey": "rsd_hotelid"
            },
            {
              "currentKey": "Competitor_ID",
              "newKey": "rsd_hotelid"
            },
            {
              "currentKey": "Rateshop_Date",
              "newKey": "rsd_rateshop_date"
            },
            {
              "currentKey": "Competitor_Name",
              "newKey": "rsd_hotelname"
            },
            {
              "currentKey": "Arrival_Date",
              "newKey": "rsd_arrivaldate"
            },
            {
              "currentKey": "LOS",
              "newKey": "rsd_los"
            },
            {
              "currentKey": "Guests",
              "newKey": "rsd_guests"
            },
            {
              "currentKey": "Currency",
              "newKey": "rsd_currency"
            },
            {
              "currentKey": "Rate",
              "newKey": "rsd_rate"
            },
            {
              "currentKey": "Room_Type",
              "newKey": "rsd_roomtype"
            },
            {
              "currentKey": "Room_Name",
              "newKey": "rsd_roomname"
            },
            {
              "currentKey": "Meal_Type",
              "newKey": "rsd_mealtype"
            },
            {
              "currentKey": "Membership_Type",
              "newKey": "rsd_membershiptype"
            },
            {
              "currentKey": "Channel_ID",
              "newKey": "rsd_channelid"
            },
            {
              "currentKey": "Requested_Rate_Type",
              "newKey": "rsd_ requested_ratetype"
            },
            {
              "currentKey": "Rate_Type",
              "newKey": "rsd_ratetype"
            },
            {
              "currentKey": "Rate_Remark",
              "newKey": "rsd_rateremark"
            },
            {
              "currentKey": "Demand",
              "newKey": "rsd_demand"
            },
            {
              "currentKey": "Rate_1_Days_Ago",
              "newKey": "rsd_rate_1_daysago"
            },
            {
              "currentKey": "Rate_Remark_1_Days_Ago",
              "newKey": "rsd_rateremark_1days_ago"
            },
            {
              "currentKey": "Rate_3_Days_Ago",
              "newKey": "rsd_rate_3days_ago"
            },
            {
              "currentKey": "Rate_Remark_3_Days_Ago",
              "newKey": "rsd_rateremark_3days_ago"
            },
            {
              "currentKey": "Rate_7_Days_Ago",
              "newKey": "rsd_rate_7days_ago"
            },
            {
              "currentKey": "Rate_Remark_7_Days_Ago",
              "newKey": "rsd_rateremark_7days_ago"
            },
            {
              "currentKey": "rsd_datakey",
              "newKey": "={{$json[\"rr_hotelcode\"]}}-S{{$json[\"rsd_rateshop_date\"].replace(/\\,.*/g,\"\").replace('/', '').replace('/', '')}}-A{{$json[\"rsd_arrivaldate\"].replace(/\\,.*/g,\"\").replace('/', '').replace('/', '')}}"
            }
          ]
        },
        "additionalOptions": {}
      },
      "id": "2d0e538c-81f3-4711-8180-f0490ef3235f",
      "name": "Rename to Match Database",
      "type": "n8n-nodes-base.renameKeys",
      "typeVersion": 1,
      "position": [
        -420,
        1580
      ]
    },
    {
      "parameters": {
        "value": "={{$json[\"Arrival_Date\"]}}",
        "dataPropertyName": "Arrival_Date",
        "options": {}
      },
      "id": "1b31fd77-8b50-4067-9a16-c76fdb39f23d",
      "name": "Format Arrival Date",
      "type": "n8n-nodes-base.dateTime",
      "typeVersion": 1,
      "position": [
        -1100,
        1360
      ]
    },
    {
      "parameters": {
        "value": "={{$node[\"Format Dates\"].json[\"Rateshop_Date\"]}}",
        "dataPropertyName": "Rateshop_Date",
        "options": {}
      },
      "id": "7c8c2a07-478e-47f8-83d1-4c33caf62b6c",
      "name": "Format Rate Shop Date",
      "type": "n8n-nodes-base.dateTime",
      "typeVersion": 1,
      "position": [
        -900,
        1360
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "authentication": "serviceAccount",
        "triggerOn": "specificFile",
        "event": "fileCreated"
      },
      "id": "12bddfa8-db4e-4fc7-925a-128b95b7086d",
      "name": "Google Drive Trigger",
      "type": "n8n-nodes-base.googleDriveTrigger",
      "typeVersion": 1,
      "position": [
        -360,
        1800
      ],
      "credentials": {
        "googleApi": {
          "id": "15",
          "name": "RR-N8N Google Service Account"
        }
      }
    }
  ],
  "connections": {
    "Remove Other Item, Keep Primary Keys": {
      "main": [
        [
          {
            "node": "Break-Out City",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Break-Out City": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Merge": {
      "main": [
        [
          {
            "node": "Format Dates",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "NoOp1": {
      "main": [
        [
          {
            "node": "Delete Original File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Execute Workflow": {
      "main": [
        [
          {
            "node": "Wait 1 Min Before Restart",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Download Original File": {
      "main": [
        [
          {
            "node": "Read File Pass 1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Read File Pass 2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Query for Files": {
      "main": [
        [
          {
            "node": "Check if Files Exist",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Delete Original File": {
      "main": [
        [
          {
            "node": "Execute Workflow",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Hotel Codes": {
      "main": [
        [
          {
            "node": "Find HotelCode",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Find HotelCode": {
      "main": [
        [
          {
            "node": "Get Config File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Config File": {
      "main": [
        [
          {
            "node": "Find File ID",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Find File ID": {
      "main": [
        [
          {
            "node": "Remove Other Item, Keep Primary Keys",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Read File Pass 1": {
      "main": [
        [
          {
            "node": "Get Hotel Codes",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Read File Pass 2": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Format Dates": {
      "main": [
        [
          {
            "node": "Format Arrival Date",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Move from Binary to CSV": {
      "main": [
        [
          {
            "node": "NoOp1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Check if Files Exist": {
      "main": [
        [
          {
            "node": "Download Original File",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Write Database File to CSV": {
      "main": [
        [
          {
            "node": "Move from Binary to CSV",
            "type": "main",
            "index": 0
          },
          {
            "node": "Save Processed File1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Wait 1 Min Before Restart": {
      "main": [
        [
          {
            "node": "Query for Files",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Add Unique Rate Shop Key": {
      "main": [
        [
          {
            "node": "Rename to Match Database",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Remove Time from Dates": {
      "main": [
        [
          {
            "node": "Add Unique Rate Shop Key",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Rename to Match Database": {
      "main": [
        [
          {
            "node": "Write Database File to CSV",
            "type": "main",
            "index": 0
          },
          {
            "node": "Send Data to Postgres",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Format Arrival Date": {
      "main": [
        [
          {
            "node": "Format Rate Shop Date",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Format Rate Shop Date": {
      "main": [
        [
          {
            "node": "Remove Time from Dates",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Google Drive Trigger": {
      "main": [
        [
          {
            "node": "Query for Files",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}

**Comment by Joffcom** [comment]
Hey @RevRebel,

For some reason the workflow doesn't want to import, In your workflow for the folder path are you using an expression or setting the ID manually?

**Comment by RevRebel** [comment]
Yes, I am using an expression to pull in the file ID but in some cases, after testing, I experience the same result using a static file id It's so storage I'm stumped on this one.

**Comment by RevRebel** [comment]
It works for the first few times, then stops again.
