### ISSUE TITLE
Disable redirect for HTTP Request

### ISSUE THREAD

**Issue by feelgood-interface** [n8n-io/n8n#4531]
**Describe the bug**
I am not able to disable redirects in the HTTP Request node. This is only possible for a GET request. In the pull request [#1961](https://github.com/n8n-io/n8n/pull/1961) the `axiosConfig.maxRedirects = 0` is only set for GET requests. Manually setting the max redirects in the node is also not possible, as the 0 is handled as falsy.

**To Reproduce**
Make any redirect call (except a GET). Currently I am trying to post login details and get the session cookie from the response.

**Expected behavior**
Disable redirects for any request.

**Environment (please complete the following information):**
- n8n Version 0.199.0

**Additional context**

**Comment by Joffcom** [comment]
Hey @feelgood-interface,

Just to confirm on this one do you want to disable redirects on post requests? We tend to use GitHub to track bugs / issues and this is more of a feature request which we track on our community support forum which can be found at https://community.n8n.io

I have made an internal ticket to add this to a future release which we will be tracking as `N8N-5423` and for now I am going to mark this one as closed.

**Comment by feelgood-interface** [comment]
Yes, I want to disable redirects on post requests.

**Comment by suhl79** [comment]
@Joffcom this actually looks like a bug. Method POST, GET, etc. is set as a parameter, but the switch "Follow redirects" doesn't seem to work correctly for POST requests. Doesn't matter if it's ON, OFF, or ON with Max Redirects set to 0 it always follows POST redirects. I verified the behavior with mitmproxy tool in place.
