### ISSUE TITLE
The iframe used in the WorkflowPreview does not support N8N_PATH

### ISSUE THREAD

**Issue by smalot** [n8n-io/n8n#4551]
**Describe the bug**

On custom build (required for VUE_APP_URL_BASE_API), a path is called (http://localhost:5678/workflows/demo) which does not take care of N8N_PATH or VUE_APP_URL_BASE_API prefix.

**To Reproduce**

1. Use the custom docker image with the env var `VUE_APP_URL_BASE_API` set to `/n8n/`
2. Run 'docker build ...'
3. Access to N8N admin UI through a Nginx proxy on `/n8n/`
4. Go to UI
5. Open a workflow
6. Display the "Executions" tab
7. In the network tab of the browser, you can see a 404 response on `http://localhost:5678/workflows/demo`

**Expected behavior**

I don't know the exact expected behavior because I don't know what if this `iframe` is for, but at least it should be a http code 200 with this path : `http://localhost:5678/n8n/workflows/demo`

I suppose I should see the corresponding workflow with its details.
Currently I only see a circular loader on the right area.

**Environment (please complete the following information):**

- OS: Alpine (docker)
- n8n Version: 0.201.0
- Node.js Version: 16
- Database system: MySQL
- Operation mode: queue

**Additional context**

code : https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/WorkflowPreview.vue#L17

**Comment by Joffcom** [comment]
Hey @smalot,

What are you doing with the execution tab in demo mode? I had assumed the demo mode was only used to display workflows like we do on our site and community forum.

Not that any of that helps with your issue, I will find out who would be best to look into this / provide a response.

**Comment by smalot** [comment]
It seems there is a correlation between the `workflows/demo` endpoint and the `workflow preview` used to render executed workflow but I don't know which one exactly, neither why

**Comment by smalot** [comment]
Thanks guys !

**Comment by smalot** [comment]
Hi,

The path is fixed, but now I have a javascript error on the first page (login page) and the same javascript error when I try to display a workflow preview:

```js
vendor.5dbbb4c7.js:5 TypeError: Cannot read properties of undefined (reading 'identify')
    at UH.identify (index.942f1c52.js:116:191852)
    at s.currentUserId (index.942f1c52.js:100:175185)
    at me (vendor.5dbbb4c7.js:5:24645)
    at e.run (vendor.5dbbb4c7.js:5:29028)
    at cf (vendor.5dbbb4c7.js:5:34135)
    at Array.<anonymous> (vendor.5dbbb4c7.js:5:25713)
    at $t (vendor.5dbbb4c7.js:5:25099)
zn @ vendor.5dbbb4c7.js:5
Un @ vendor.5dbbb4c7.js:5
Ue @ vendor.5dbbb4c7.js:5
me @ vendor.5dbbb4c7.js:5
e.run @ vendor.5dbbb4c7.js:5
cf @ vendor.5dbbb4c7.js:5
(anonymous) @ vendor.5dbbb4c7.js:5
$t @ vendor.5dbbb4c7.js:5
Promise.then (async)
ft @ vendor.5dbbb4c7.js:5
ur @ vendor.5dbbb4c7.js:5
Mr @ vendor.5dbbb4c7.js:5
e.update @ vendor.5dbbb4c7.js:5
e.notify @ vendor.5dbbb4c7.js:5
set @ vendor.5dbbb4c7.js:5
set value @ vendor.5dbbb4c7.js:5
set @ vendor.5dbbb4c7.js:5
loginWithCookie @ index.942f1c52.js:26
await in loginWithCookie (async)
(anonymous) @ pinia.97836cfe.js:7
loginWithCookie @ index.942f1c52.js:100
initialize @ index.942f1c52.js:100
await in initialize (async)
mounted @ index.942f1c52.js:100
me @ vendor.5dbbb4c7.js:5
se @ vendor.5dbbb4c7.js:5
insert @ vendor.5dbbb4c7.js:5
pe @ vendor.5dbbb4c7.js:5
(anonymous) @ vendor.5dbbb4c7.js:5
e._update @ vendor.5dbbb4c7.js:5
n @ vendor.5dbbb4c7.js:5
e.get @ vendor.5dbbb4c7.js:5
e @ vendor.5dbbb4c7.js:5
of @ vendor.5dbbb4c7.js:5
W.$mount @ vendor.5dbbb4c7.js:5
(anonymous) @ index.942f1c52.js:116

```

Are these issues related ?
Do you need more details ?

Many thanks

**Comment by netroy** [comment]
@smalot That error looks like you have telemetry enabled, but your system is blocking the frontend from loading the telemetry script. The relevant code is [here](https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/Telemetry.vue#L70).
To fix the issue you need to either 
* disable telemtry by setting the env variable `N8N_DIAGNOSTICS_ENABLED=true` for the server, or 
* allow your browser/network to load [this script](https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/plugins/telemetry/index.ts#L242).
