### ISSUE TITLE
N8N hangs when clicking Duplicate on AWS S3 node

### ISSUE THREAD

**Issue by stevennt** [n8n-io/n8n#4583]
**Describe the bug**
N8N hangs when clicking Duplicate on the AWS S3 node.

**To Reproduce**
Click Duplicate on the AWS S3 node.

**Expected behavior**
The AWS S3 node should be duplicated.

**Environment (please complete the following information):**

- OS: Docker on Debian
- n8n Version: 0.202.1
- Operation mode: own

**Comment by Joffcom** [comment]
Hey @stevennt,

I have just taken a look and I am not able to reproduce this, What browser are you using and does it happen for all nodes or just that one?

**Comment by stevennt** [comment]
It was just this AWS S3 node. 
However, I attempted that workflow again today and the problem seems to go away now. I was upgrading Docker and Debian in between, not sure if they had any impact on this issue. However I will close it for now. Thank you!
