### ISSUE TITLE
Outlook Node loses HTML table tags

### ISSUE THREAD

**Issue by dewdeded** [n8n-io/n8n#4598]
**Describe the bug**
The Outlook node loses HTML table tags (during draft and sending), when using expressions instead of fixed body content.

**Expected behavior**
Clean HTML. :-)

**Environment (please complete the following information):**
Latest n8n docker version.

**Comment by kasgithub8** [comment]
We have the same problem here.
Any ideas?

**Comment by Joffcom** [comment]
Hey @dewdeded & @kasgithub8,

We have an internal ticket created for this which we will be tracking as `NODE-168`, I plan to look into this one this week to get it resolved.

**Comment by dewdeded** [comment]
Thank you Joff.

**Comment by Autoradiowecker** [comment]
Hey Joff, 

did you came to a conclusion how to solve the issue?
Looking forward to hear from you :)

**Comment by Joffcom** [comment]
@Autoradiowecker not yet, To be honest I have not had a chance to look yet but it is at the top of my list of issues to look into.

**Comment by Joffcom** [comment]
Afternoon @Autoradiowecker, @dewdeded & @kasgithub8,

I have just been looking at this and I read the issue as "When I use a table with Expressions in it the tags are removed", I have given it a quick test using the workflow json in this [gist](https://gist.github.com/Joffcom/f1d8aaa75efeaaba14369dc0797153ab) but it appears to be working for me, I am not sure if this has already been solved or if I have missed something.

The workflow Creates a Draft, gets the draft then sends the draft and to me everything looks to be all good, If any of you have an example of a workflow that fails or wants to try the above one it would be a big help.
