### ISSUE TITLE
Editor UI live reload does not work

### ISSUE THREAD

**Issue by psamim** [n8n-io/n8n#4658]
**Describe the bug**
After running `pnpm run dev`, when I change a file in `editor-ui`   package, the build is not restarted and the change does not take effect. But if I change something in any other package, it causes the build to restart.

**To Reproduce**

1. Clone the repo
2. Install requirements
3. Run `pnpm i` and then `pnpm build` and finally `pnpm dev`
4. Change something in any file in `editor-ui` package
5. Nothing happens

**Expected behavior**
When running `pnpm dev` when a file is changes, the changed should take effect instantly.

**Environment (please complete the following information):**

- OS: Archlinux
- n8n Version 0.202.1 and main
- Node.js Version 16.18.1
- Database system Default
- Operation mode Default

**Comment by ivov** [comment]
Cannot reproduce. Are you testing on `http://localhost:8080`?

**Comment by psamim** [comment]
@ivov No, I test on `http://localhost:5678`.

**Comment by netroy** [comment]
@psamim `:5678` is the backend, that can also serve a static copy of the frontend. 
The frontend development-server runs on `:8080`.
