### ISSUE TITLE
IMAP Inject & Move Message?

### ISSUE THREAD

**Issue by rcarmo** [n8n-io/n8n#47]
It would be nice to be able to inject & move IMAP messages, for two reasons:

* Copying or moving a new message to another mailbox or folder is a common pattern in customer service
* Injecting a new message (without going through an SMTP server) is useful to provide results from an action (using thread message IDs, etc. makes it very human-friendly)

I've done this in the past in https://github.com/rcarmo/rss2imap (feel free to use the same header generation logic - I'd donate it as TypeScript if I had the time).

**Comment by vuchl** [comment]
`imap-simple` provides [https://github.com/chadxz/imap-simple#imapsimple-class](`append`) and [https://github.com/chadxz/imap-simple#imapsimple-class](`moveMessage`) methods so maybe they can be exposed somehow.

**Comment by rcarmo** [comment]
Creating folders would also be necessary.

**Comment by RicardoE105** [comment]
Hey @rcarmo, sorry for the late response, and thanks for the feedback. Feature requests can be made in our community https://community.n8n.io/.

**Comment by rcarmo** [comment]
Thanks for the feedback. Do you have any sort of feature roadmap for tracking this sort of thing? Asking for technical features in a public forum seems risky in terms of prioritization and requirements capture...

**Comment by janober** [comment]
Currently, the only thing we have is the forum where people can request features/integrations and tell us what functionality they need. We then prioritize them depending on interest (upvotes) and resources available.

**Comment by rcarmo** [comment]
Thanks, I think I’ll pass. Even if the forum might have some form of social auth, having yet another place to log into and wading through what (at first glance) seems like a lot of unrelated discussions (and talk about bugs, too) seems a little too much when a label on issues would do the trick and keep feature discussions easy to reference from the code itself.

**Comment by vuchl** [comment]
I created a topic in the forums: https://community.n8n.io/t/imap-inject-move-message/1518
