### ISSUE TITLE
Error Saving Workflow

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4706]
**Describe the bug**

When a Trigger receives the data, it is no longer possible to save the workflow.

![bee4c13f-be11-4037-8407-4a2684a262af](https://user-images.githubusercontent.com/257004/203611423-cd061959-91b0-4328-a977-189f85127a88.png)

same behavior in more than 10 instances using this version.

**To Reproduce**

1. Add any Trigger to Workflow
2. Get data
3. Try save Workflow

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.203.1
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by vinitercariol** [comment]
The same problem here n8n Version 0.203.1 MYSQL

**Comment by 1itt1eB0y** [comment]
same problem with 
* Docker `latest` Image (Version 0.203.1)
* SQLite

**Comment by 1itt1eB0y** [comment]
Here is a link about this bug.
https://community.n8n.io/t/bug-not-fixed/20051

`0.202.1` can work properly, you can downgrad to `0.202.1` as a temp solution.

**Comment by janober** [comment]
Fix got released with `n8n@0.204.0`

**Comment by ivov** [comment]
Closing, but please let us know if it persists.
