### ISSUE TITLE
Error: Cannot find module 'node:path' display when i do n8n start

### ISSUE THREAD

**Issue by ROHAN-WAGH-ROOT** [n8n-io/n8n#4722]
Error: Cannot find module 'node:path'

**Comment by ROHAN-WAGH-ROOT** [comment]
node version @14.16.0

**Comment by netroy** [comment]
`14.16` is close to two years old. Can you please upgrade to `14.21`?
PS: Node 14 will be end-of-life in about 4 months. We highly recommend that you upgrade to version `16` ?

**Comment by ROHAN-WAGH-ROOT** [comment]
ok
