### ISSUE TITLE
Unknown Error on AWS SNS Node

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4725]
**Describe the bug**

Existing workflows that were working now show SNS Unknown Error after upgrade to 0.204.0

![download](https://user-images.githubusercontent.com/257004/203979142-5988acae-ae62-4224-8883-37ee3acc1985.png)

**To Reproduce**

1. Upgrade to 0.204.0

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by luizeof** [comment]
hello @Joffcom how are you?

SNS stopped again. I investigated and did not find a more appropriate log, just the one in the image.

Thanks for your time ;)

**Comment by netroy** [comment]
@luizeof are you by any chance running this on an instance without a public url, like `localhost` ?

**Comment by luizeof** [comment]
> @luizeof are you by any chance running this on an instance without a public url, like `localhost` ?

hello.. no, it's an instance in production environment...
