### ISSUE TITLE
Initializing n8n process Last session crashed 

### ISSUE THREAD

**Issue by ROHAN-WAGH-ROOT** [n8n-io/n8n#4727]
Initializing n8n process
Last session crashed
 »   Error: There was an error: EBUSY: resource busy or locked,

**Comment by netroy** [comment]
@ROHAN-WAGH-ROOT Please use the issue template when filing issues. 
Without that we have no context about what version of n8n you are on, and if you are running it via Docker or NPM.

![image](https://user-images.githubusercontent.com/196144/204002630-f2b41ecf-bb28-4c64-9ac1-a88ff6cbc069.png)

**Comment by janober** [comment]
Closing this issue as we did not hear back for 13 days with the information we require to debug this issue.

If you still experience this problem please open a new ticket with all the information necessary. Thanks a lot!
