### ISSUE TITLE
Error on filter failed executions on update to n8n version 0.204.0

### ISSUE THREAD

**Issue by dannyeuu** [n8n-io/n8n#4729]
**Describe the bug**
On Workflow executions, after update n8n to version 0.204.0 with Postgres and Docker Compose, and trying to filter for workflow execution failed, this error occurs:
![Screenshot from 2022-11-25 10-15-52](https://user-images.githubusercontent.com/6808348/203993906-45ca8b65-b05a-413a-b74c-ab106b12b796.png)

![Screenshot from 2022-11-25 10-15-33](https://user-images.githubusercontent.com/6808348/203993831-ddce6cdc-8b5f-4998-a656-27e69c2eb2bf.png)

**Environment (please complete the following information):**

- OS: Debian 11
- n8n Version: 0.204.0
- Node.js Version - Docker
- Database system: PostgreSQL 11
- Operation mode: own

**Additional context**
```
withpostgres-postgres-1  | 2022-11-25 13:13:40.825 UTC [49] ERROR:  invalid input syntax for type timestamp: "{"_type":"isNull","_useParameter":false,"_multipleParameters":false}"
withpostgres-postgres-1  | 2022-11-25 13:13:40.825 UTC [49] STATEMENT:  SELECT COUNT(1) AS "cnt" FROM "public"."execution_entity" "ExecutionEntity" WHERE ("ExecutionEntity"."workflowId" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) AND "ExecutionEntity"."finished" = $11 AND "ExecutionEntity"."waitTill" = $12 AND NOT(0=1)
```

**Comment by csuermann** [comment]
Hi @dannyeuu,
Thank you for reporting this issue and apologies for the delay in getting back to you. Our team is currently working on a [fix](https://github.com/n8n-io/n8n/pull/4856) and we'll update you here once we have released it.

**Comment by janober** [comment]
Fix got merged and will be released soon.
