### ISSUE TITLE
NocoDB node no longer listing projects/tables

### ISSUE THREAD

**Issue by naamval** [n8n-io/n8n#4741]
**Describe the bug**
After updating the NocoDB service from 0.98.4 to 0.99.2, the NocoDB node in n8n is no longer listing the projects and tables.

**To Reproduce**
1. Create a new NocoDB node (or edit an existing one)
2. Select your credentials
3. Fields 'Project Name or ID' and 'Table Name or ID' remain empty

**Expected behavior**
Previously, a drop down list would appear that made it possible to select the project/table that you need. The node still works when you input the project and table names in the respective fields, but this is obviously less convenient.

**Environment (please complete the following information):**
- OS: Ubuntu Linux 22.04
- n8n Version 0.204.0
- Node.js Version ? (using the n8n Docker)
- Database system MariaDB
- Operation mode own

**Comment by Joffcom** [comment]
Hey @naamval,

If you go to the node settings what NocoDB api version is the node set to use?

**Comment by naamval** [comment]
'v.0.90.0 Onwards'

**Comment by Joffcom** [comment]
Hey @naamval,

I can't see any changes in the NocoDB release notes, If you go back to 98.4 does it still work? I will get a NocoDB test instance set up later this week and take a look, I deleted my old test ones over the weekend.

**Comment by naamval** [comment]
Thanks in advance for checking. I tried to revert back to 0.98.4 but I am getting an error during startup.

**Comment by naamval** [comment]
I just checked with a clean local test setup and it's the same result. With NocoDB 0.98.4, there is a drop down menu that allows you to select the project and table. After I upgraded to 0.99.2, it does not appear any longer.

**Comment by Joffcom** [comment]
Hey @naamval,

That sounds like there has been a change to the API, I will let you know when I start looking into it.

**Comment by naamval** [comment]
Something I noticed that might help identify the underlying issue: when inserting the ID in the 'project name or ID' field (rather than the project name), the drop down list with the tables within that project _does_ appear.

**Comment by naamval** [comment]
I did a clean install of nocodb 0.99.2 and the issue is resolved. Something must have happened to the database during the upgrade.
