### ISSUE TITLE
How to Upgrade Nocodb on Digital Ocean

### ISSUE THREAD

**Issue by AbhiSingh75** [n8n-io/n8n#4754]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by AbhiSingh75** [comment]
Dear Team Plz help me, How can we upgrade nocodb on Digital Ocean Cloud?

**Comment by janober** [comment]
This is the n8n repository. Best ask for that on the nocodb repository instead.
