### ISSUE TITLE
Retrieve calls made with API does not respect workflowSettings object

### ISSUE THREAD

**Issue by smalot** [n8n-io/n8n#4776]
**Describe the bug**

Invalid attribute value and extra attribute are retrieve with a workflow using API if settings are set in the UI.

In the retrieve response, the `settings.saveExecutionProgress` should be a boolean as in the documentation.
Another error seen quickly, is the extra attribute : `callerPolicy` which is not supported.

**To Reproduce**

1. Create a workflow with the "Webhook trigger" node
2. Open the worflow settings dialog box
3. Save the dialog box without changing anything
4. Use API to `get` this new workflow
5. Note in the response attribute `settings` : `{"saveExecutionProgress":"DEFAULT","saveManualExecutions":false,"callerPolicy":"any"}`
6. Use the payload you just obtained to call the `update` API restricted to the supported properties (`name`, `nodes`, `connections`, `settings`, `staticData`)
7. You obtain this error : `400 Bad Request` response:
      `{"message":"request.body.settings should NOT have additional properties, request.body.settings.saveExecutionProgress should ...`

**Expected behavior**

Settings attributes retrieve in the `get workflow` API calls should be supported as it in the `update workflow` API calls.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version : 0.203.1
- Node.js Version v16.17.0
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode : own

**Additional context**

**Comment by Joffcom** [comment]
Hey @smalot,

Sorry for the delay on this one, That is a good spot it looks like we should also handle 'DEFAULT' as an option as well although technically the API is working as documented so this isn't a bug as such.

I will get a dev ticket created for this in the morning.

**Comment by Joffcom** [comment]
Hey @smalot,

I just gave this a quick go again on the latest release and it looks like we no longer return the default values so this looks to be resolved.

![image](https://github.com/n8n-io/n8n/assets/4688521/edd409b3-df7b-4070-a6a2-034f7d7ecf24)


```
    "connections": {},
    "settings": {
        "saveManualExecutions": false,
        "callerPolicy": "workflowsFromSameOwner"
    },
    "staticData": null,
    "pinData": {},
```

I am going to mark it as closed for now but if you are still seeing this let me know and I can open it again.
