### ISSUE TITLE
Pipedrive API connection "No testing function found for this credential"

### ISSUE THREAD

**Issue by zborowa** [n8n-io/n8n#4780]
**Describe the bug**
Connecting to Pipedrive through API token results in `Couldn’t connect with these settings, No testing function found for this credential.`

**To Reproduce**

1. Go to 'Credentials'
2. Click on 'Add Credential'
3. Scroll down to 'Pipedrive API'
4. Fill in API token
5. Click on 'Save'
6. See error

**Expected behavior**
This error is happening on the Docker image of n8n. The n8n Desktop application behaves as expected and returns a successful connection.

**Environment (please complete the following information):**

- OS: Docker 20.12.21 (on Windows 10 19045)
- n8n Version: 0.204.0
- Node.js Version: ?
- Database system SQLite
- Operation mode: own

**Comment by netroy** [comment]
Thanks for reporting this. This was fixed in https://github.com/n8n-io/n8n/pull/4760, and will be released in the next couple of days.
