### ISSUE TITLE
Unable to use overwritten Postgres credentials in Postgres Node

### ISSUE THREAD

**Issue by kamalptw** [n8n-io/n8n#4781]
Its related to this issue https://github.com/n8n-io/n8n/issues/4611 which was fixed and released in n8n@0.204.0

**Describe the bug**
After overwriting postgres credentials via `CREDENTIALS_OVERWRITE_DATA` environment variable, when creating a new postgres credential, the overwritten fields are not visible in the form which is expected. After saving this credential, when trying to use this new Postgres credential inside a workflow there is an ERROR: connect ECONNREFUSED 127.0.0.1:5432 upon executing the query.

**To Reproduce**

As a self hosted instance, we would like to hide postgres connection parameters from the users who are accessing the instance. We do this using CREDENTIALS_OVERWRITE_DATA environment variable. After this,

1. Go to credentials page
2. Click on Add credential
3. Select Postgres
4. Save
5. Confirm that you can see a Connection tested successfully 
6. Now, go to a workflow, add postgres node, select the newly created credential and execute a query
7. See the error ECONNREFUSED 127.0.0.1:5432

**Expected behavior**
The expectation is that the overwritten credentials should be used when executing the query.

**Environment (please complete the following information):**

- OS: AWS Ec2 Linux
- n8n Version: Version 0.204.0
- Database system: Postgres
- Operation mode: Own
- Deployment: via docker-compose

**Comment by kamalptw** [comment]
@janober @netroy @ivov
Again, requesting for help. Like last time, Any help here would be much appreciated. Thank you.

**Comment by Joffcom** [comment]
Hey @kamalptw,

No need to tag, We get alerted internally when new issues are created and we try to handle them in the order they arrive.

**Comment by Joffcom** [comment]
Hey @kamalptw,

It looks like a PR has been put in to fix this issue here: #4782

**Comment by Joffcom** [comment]
Hey @kamalptw,

The fix for this has been released with n8n@0.205.0

**Comment by kamalptw** [comment]
@Joffcom 😮 you folks are unreal! 
Amazed by the swiftness with which you tackle issues.
Right now, for our org you folks are an extended development team !

**Comment by kamalptw** [comment]
I've tested the fix on my end. it works!
