### ISSUE TITLE
Cron weekday scheduling seems erratic

### ISSUE THREAD

**Issue by Yann-J** [n8n-io/n8n#4784]
**Describe the bug**

Hello!

I'm noticing that some of my cron triggers are firing at unexpecting times.

See the example below, with a cron trigger configured to fire on _Fridays_, but has clearly fired on other days too (but at the correct hour).

See the executions fired (25th Nov is expected, the other 2 aren't):

![image](https://user-images.githubusercontent.com/59641363/205066695-6e9b49fa-7706-4fce-bc4b-123ee854c38a.png)

As you can see in the execution logs, the trigger's output is inconsistent with its configuration:

![image](https://user-images.githubusercontent.com/59641363/205066523-44b4a208-611c-488f-b40b-4a3e9939dc01.png)

**To Reproduce**

Not sure how to reproduce reliably, since obviously testing cycles are pretty slow as I need to wait for the right days to see it fired :)

I expect that this affect any weekday-based trigger implemented through the UI. I have switched to a cron expression to see if this solves the problem.

**Environment (please complete the following information):**

- n8n Version: latest docker image, `0.203.1`
- Database system: `postgres`
- Operation mode: `queue`

**Additional context**

**Comment by Joffcom** [comment]
Hey @Yann-J,

That is interesting, It has also triggered 2 hours later than scheduled as well 🤔

@agobrech any thoughts?

**Comment by agobrech** [comment]
Hey @Yann-J, we fixed this issue in [n8n@0.204.0](https://docs.n8n.io/reference/release-notes/#bug-fixes), if you still have some issues please let me know! 
@Joffcom The 2 hours later is probably due to timezone different format
