### ISSUE TITLE
Create Notion integration

### ISSUE THREAD

**Issue by rdewolff** [n8n-io/n8n#48]

**Comment by janober** [comment]
Thanks a lot. But can you please post it here:
https://community.n8n.io/c/feature-requests/nodes

As that is the central place to request new integrations (added just some here already for the #hacktoberfest).

Btw. would be a big fan of that. Are however not sure that is even possible as the last time I checked (properly) they did not have an API. And my fast search now seems to come to the same conclusion:
https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c
It is in the coming up section so does not seem like it is available yet.

**Comment by janober** [comment]
I did not get an answer so close this issue for now. If API is really available please post in form with a link to API documentation. Thanks!

**Comment by mpj** [comment]
Notion API now available:
https://developers.notion.com/

**Comment by janober** [comment]
Yes, the notion node got released on the 21.05.2021:
https://github.com/n8n-io/n8n/pull/1811
