### ISSUE TITLE
Main process appears to crash on unexpected analytics DNS query reply

### ISSUE THREAD

**Issue by nonmaterialistically** [n8n-io/n8n#4855]
**Describe the bug**
n8n appears to crash if it gets a NXDOMAIN response to a DNS query to app.posthog.com.

**To Reproduce**

1. Block app.posthog.com by replying NXDOMAIN to the query (PiHole can do this, but it's not the default blocking mode)
2. Use the editor. Try to execute some test nodes and save the workflow
3. See error in logs:

```
n8n  | 2022-12-07T23:36:31.667Z | verbose  | Updating versionId for workflow 27 for user a910a4b9-c99d-41de-9c01-84df7fb73e72 after saving "{\n  previousVersionId: 'dc5a180f-388c-457c-bb0f-a05be9ac5bc4',\n  newVersionId: '1ca6d219-8e59-4123-9eb7-c3d5c8673e11',\n  file: 'workflows.services.js',\n  function: 'update'\n}"
n8n  | Error: getaddrinfo ENOTFOUND app.posthog.com
n8n  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)  
n8n  |     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17)  
n8n exited with code 1  
n8n  | 2022-12-07T23:36:46.811Z | info     | Initializing n8n process "{ file: 'start.js', function: 'run' }"  
n8n  | 2022-12-07T23:36:46.817Z | error    | Last session crashed "{ file: 'CrashJournal.js', function: 'init' }"
```

**Expected behavior**
Handle the error by logging or notify the user.

**Environment (please complete the following information):**

- OS: Official docker image
- n8n Version 0.206.1
- Node.js Version 16.18.1
- Database system: SQLite
- Operation mode: own

**Additional context**
I was getting "lost connection" errors while saving/editing/testing workflows. I thought it was caused by my nginx settings but after checking the logs I found the crash. I'm not sure what changed: I didn't know I was blocking this domain and I cannot check if it was recently added to one of the automatically updated blocklists.  
I don't think this is too common, since Pihole's and AdGuard's blocking mode is set to reply 0.0.0.0 by default and doesn't send NXDOMAIN.

**Comment by oddcc** [comment]
same issue here

**Comment by ns-bruno** [comment]
I also have the same problem.

**Comment by Joffcom** [comment]
Good news, This looks to have been resolved a couple of months ago. I am going to mark this one as closed and if you are still seeing an issue let me know and we can open it again.
