### ISSUE TITLE
Getting frequent "Workflow cannot be saved because it was changed by another user"

### ISSUE THREAD

**Issue by Yann-J** [n8n-io/n8n#4857]
**Describe the bug**

When editing a workflow, it has become very common that we're unable to save it, getting the error "cannot be saved because it was changed by another user", both in the UI and in the master node logs:

```
ERROR RESPONSE
ResponseError: Workflow ID 3 cannot be saved because it was changed by another user.
    at Function.update (/usr/local/lib/node_modules/n8n/dist/workflows/workflows.services.js:169:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/local/lib/node_modules/n8n/dist/workflows/workflows.controller.js:179:29
    at async /usr/local/lib/node_modules/n8n/dist/ResponseHelper.js:91:26 {
  httpStatusCode: 400
}
```

While it's true that our instance has several users, it is extremely unlikely that those would be editing the same workflow at the same time with this kind of frequency - in fact, in our QA environment it's very unlikely that there would be 2 concurrent users at all on the system.

The frequency is very high. In fact, this happens almost every time after a few minutes in the UI without saving the workflow.

The error is recovered by refreshing, redoing our changes, and saving. But it comes back after a few minutes.

It's difficult to provide much more troubleshooting guidance, since we don't have more useful logs.

This is not entirely new, it's been happening for some time now, but it seems that the frequency has really increased.

Could it be due to workflow executions being considered as a workflow change?

**To Reproduce**

In our environment:

- Open a workflow and make a change
- Wait 2-3 min
- Try to save
- 90% of the time the error will pop up

**Environment (please complete the following information):**

- OS: Debian
- n8n Version: Official Docker `0.203.1-debian`
- Database system: postgres
- Operation mode: `queue`
- Setup:
  - 1 single `main` node + 3 workers

**Comment by janober** [comment]
Can you please try with the latest version

**Comment by Yann-J** [comment]
Tricky because it (since a couple of versions actually) is somehow breaking [one of our custom nodes](https://www.npmjs.com/package/@oneacrefund/n8n-nodes-newreleases), so we need to fix that first...

**Comment by janober** [comment]
Ah ok, but as far as I know did that get fixed already.

**Comment by netroy** [comment]
@Yann-J we try to be backward compatible for all custom nodes. If one of our new releases is breaking your nodes, please let us know with more details on what error you are seeing. 
It's likely a regression on our end, and we'll like to fix it, if possible.

**Comment by Yann-J** [comment]
Sure, I'm actually not really sure what's going on, trying to troubleshoot locally, but it seems doing `npm link` breaks the `pnpm run dev`... Still figuring this out, will let you know and I might open a separate issue for this.

**Comment by Yann-J** [comment]
OK, I think I see the problem... please see #4863

**Comment by Yann-J** [comment]
FYI we have now upgraded (after a few more issues on our end) and will report back soon. So far we haven't seen the error again.

**Comment by Yann-J** [comment]
Hey there @netroy so my team confirms that the issue is fixed! They haven't seen the issue all day!

Thanks!
