### ISSUE TITLE
Full Text Search fails with error: "Sorting is not supported for queries with fullText terms. Results are always in descending relevance order."

### ISSUE THREAD

**Issue by artakpetrosyan** [n8n-io/n8n#4874]
https://github.com/n8n-io/n8n/blob/4cb4c5e8188fd930312e3bf720472af35731a968/packages/nodes-base/nodes/Google/Drive/GoogleDrive.node.ts#L2484

**Comment by artakpetrosyan** [comment]
For reproducing the reported problem please just use  followed Google Drive node options:
Resource: File
Operation: List
Query String: fullText contains 'any text'

API call returns 403 with:
`{"error":{"code":403,"message":"Sorting is not supported for queries with fullText terms. Results are always in descending relevance order.","errors":[{"message":"Sorting is not supported for queries with fullText terms. Results are always in descending relevance order.","domain":"global","reason":"forbidden","location":"orderBy","locationType":"parameter"}]}}`

**Comment by Joffcom** [comment]
Hey @artakpetrosyan,

This looks to be working now, Can you try on the latest release and let me know if it works for you? If it fails we can open this again but it looks to be all good.

![image](https://github.com/n8n-io/n8n/assets/4688521/b719b4d3-d12a-4b77-b262-00313d488bd4)

**Comment by artakpetrosyan** [comment]
It is not fixed

**Comment by Joffcom** [comment]
Hey @artakpetrosyan

Can you share a screenshot of your nodes settings and the error? For me as the image shows it is working as expected so it would be handy to see what you are setting.

**Comment by robinbobin2** [comment]
@Joffcom 
The bug happens only with "fullText" query string, see screenshot 
<img width="995" alt="image" src="https://github.com/n8n-io/n8n/assets/6996665/39fbef01-c1d4-4131-941d-243daf166524">
