### ISSUE TITLE
Schedule Trigger Cron expression node returns Invalid cron expression

### ISSUE THREAD

**Issue by zborowa** [n8n-io/n8n#4876]
**Describe the bug**
The Schedule Trigger node describes that the cron expression can be generated/validated on the [Cronmaker](http://www.cronmaker.com/) website. The expression that I want to use for my workflow is supposed to execute every workday between 6 and 23. This expression would look like this and is correctly validated by Cronmaker (and other websites) `0 0 6-23 ? * MON-FRI` but entering it into the Cron expression field results in an `Invalid cron expression`. The hint underneath the input field also looks wrong to me if I compare it with any other type of format, `[Minute] [Hour] [Day of Month] [Month] [Day of Week]`. At some point I did get the Schedule Trigger to run but with the following expression `0 6-23 * * MON-FRI` which is not a valid Quarts cron expression (which is used on the Cronmaker website). My question now is why is the cron format different and providing a website that will not provide you with the proper format?

**To Reproduce**

1. Create the `Schedule Trigger` node
2. Change trigger interval to custom
3. Input `0 0 6-23 ? * MON-FRI` as the expression

**Environment (please complete the following information):**

- OS: Cloud
- n8n Version 0.204.0

**Comment by Joffcom** [comment]
Hey @zborowa,

I have a feeling the issue could be with the Cronmaker website, Cron should be `[Minute] [Hour] [Day of Month] [Month] [Day of Week]` but the example you got from the site has an extra field so we should probably update the node to link to a different site.

I tend to use crontab.guru when workout out the pattern to use as it is more generic and will let you know if something doesn't fit the standard. For your example I would probably use `0 6-23 * * 1-5` assuming you want it to run every hour between 6 and 11 Monday to Friday.

**Comment by zborowa** [comment]
Hi @Joffcom,

crontab.guru seems to be much better! The example that you've sent is exactly what I ended up doing. The exact value became `0 6-23 * * MON-FRI`. Seeing as there is no issue attached to this regarding changing the cronmaker reference to crontab I'll just close this issue.
