### ISSUE TITLE
Can't view old executions

### ISSUE THREAD

**Issue by romainsaillant** [n8n-io/n8n#4891]
**Describe the bug**
When I open a recent execution of a workflow, I can see it. But if I try to open an old execution (i.e that is not in the list of recent executions on the left side of the new executions view inside the workflow), n8n doesn't open it and opens the most recent execution for this workflow.

**To Reproduce**

1. Go to the executions view
2. Select an old execution of a workflow
3. Open it
4. You see the last execution and not the one you wanted to see

**Expected behavior**
View the execution I clicked on

**Environment (please complete the following information):**

- Heroku server
- n8n Version 0.205.0
- Database system Postgres

**Comment by romainsaillant** [comment]
It seems that the problem is in the URL that the "view execution" button is linking to: it links to {n8n domain}/workflow/{workflow id}/executions/{execution id}. For older executions, it should link to {n8n domain}/execution/{execution id}

**Comment by janober** [comment]
Are you sure it is displaying the wrong execution? I just tested and for me, it looks like it is actually opening the correct execution just the data in the top left corner (date, status, and ID) is not being displayed correctly.

Obviously still has to be fixed.

**Comment by janober** [comment]
Fix got released with `n8n@0.208.1`
