### ISSUE TITLE
Twitter authentication isn't working on Docker Image - Railway.app

### ISSUE THREAD

**Issue by JustJerem** [n8n-io/n8n#4897]
**Describe the bug**
When I try to connect my twitter account following the documentation, it works locally, on my computer. But when I try to follow the same procedure on Railway.app, it does not work. N8N directly displays an error when I click on the "Connect My Account" button without opening any other web tab.

I get the following error:
`
OAuth Authorization Error
There was a problem generating the authorization URL
Unknown error
`

Of course, in the Twitter settings, I have changed the Redirect URL since my project is now online but nothing happens and anyway, N8N does not open the other tab.

**To Reproduce**

1. Go to https://railway.app/.
2. Click on 'Start New Project'
3. Search for 'N8N', enter a name and username. 
4. Click Deploy
5. Give some time to Railway to setup everything.
6. Click on the URL on the deployment panel, under Github.
7.  Create a new Workflow and follow [this documentation](https://docs.n8n.io/integrations/builtin/credentials/twitter/?utm_source=n8n_app&utm_medium=left_nav_menu&utm_campaign=create_new_credentials_modal).
8. See error "Unknown error" when clicking on "Connect to my account" 

**Expected behavior**
As for other services that work properly such as Google Drive, Dropbox, etc., I would like Twitter to be able to connect too.

**Environment (please complete the following information):**

- OS: Docker Image on Railway.app
- n8n Version 0.206.1
- Node.js Version [e.g. 16.17.0]
- Database system ProgreSQL  2.1.1
- Operation mode own

**Comment by Joffcom** [comment]
Hey @JustJerem,

I suspect this issue is down to the change with the Twitter API and newly registered apps, We only support the v1 api at the moment and newly created apps don't always work with it. We do have a development ticket open for updating the twitter node which I believe will solve this.

**Comment by aNobre-redhat** [comment]
> Hey @JustJerem,
> 
> I suspect this issue is down to the change with the Twitter API and newly registered apps, We only support the v1 api at the moment and newly created apps don't always work with it. We do have a development ticket open for updating the twitter node which I believe will solve this.

Hello @Joffcom 
Any updates about how to use Twitter API v2 on n8n?  My Twitter developer just allow me use v2. It's a must have update for our n8n .

**Comment by Joffcom** [comment]
Hey @aNobre-redhat 

We are planning to update the Twitter node but it involves a fairly large change to our oauth implementation so it hasn't been as quick as we would have liked.

**Comment by aNobre-redhat** [comment]
> Hey @aNobre-redhat 
> 
> We are planning to update the Twitter node but it involves a fairly large change to our oauth implementation so it hasn't been as quick as we would have liked. 

Sure, mate. I'm not talking about how long has been taking. Sorry if sounds like that. Just asking for an update about it.  Thanks for you quickly reply.

**Comment by Joffcom** [comment]
So the good news is we have implemented PKCE support as part of the Twitter node overhaul so this is going to be solved very soon, They are currently going through the review process so should be available in a couple of weeks.

For now as we are fixing this I am going to mark this as closed and if for some reason Railway still has an issue when the new node version is released we can look at opening this back up.
