### ISSUE TITLE
NODES_INCLUDE not working

### ISSUE THREAD

**Issue by brookqin** [n8n-io/n8n#4901]
**Describe the bug**
in pod cli:
```
~ $ echo $NODES_INCLUDE

["n8n-nodes-base.amqp","n8n-nodes-base.amqpTrigger","n8n-nodes-base.code","n8n-nodes-base.compareDatasets","n8n-nodes-base.compression","n8n-nodes-base.crateDb","n8n-nodes-base.cron","n8n-nodes-base.crypto","n8n-nodes-base.dateTime","n8n-nodes-base.editImage","n8n-nodes-base.elasticsearch","n8n-nodes-base.elasticSecurity", ...]
```
but the editor loads all nodes.

**Environment (please complete the following information):**

- OS: [n8n docker image]
- n8n Version [0.205.0]
- Database system [mysql 5.7]
- Operation mode [queue]

**Comment by netroy** [comment]
@brookqin this was fixed and released last week. 
Can you please update to `0.207.0` and check if the fix works for you?

**Comment by brookqin** [comment]
It's fixed, thanks!
