### ISSUE TITLE
HTTP Request with Digest Auth alway error 401 if "never error" is set

### ISSUE THREAD

**Issue by mwoelk** [n8n-io/n8n#4908]
**Describe the bug**
When using the HTTP Request node with Digest Auth and the option "Never Error", the authentication does not seem to be performed and we always recieve a 401 response from the endpoint.

In our concrete use case, we have an API that returns 404 for missing entities. We need to filter a list of all entities for which we recieve a 404 response. The API uses Digest Auth for authentication.

With The option "never error" unset, the node errors on the first 404 response it receives. With "never error", the node returns only 401 Unauthorized errors. It seems like no digest authentication is performed.

**To Reproduce**

1. Set up HTTP Request using Digest Auth and option "Never Error" set
2. Let it run
3. See only 401 errors returned

**Expected behavior**
It should authenticate and return data if it exists or the real error (in our case 404).

**Environment (please complete the following information):**
- Running in Docker using image: n8nio/n8n:0.196.0
- Database system [SQLite]
- Operation mode [own]

**Comment by mwoelk** [comment]
Setting `N8N_USE_DEPRECATED_REQUEST_LIB: 'true'` as a workaround helps and results in correct behaviour.

**Comment by Joffcom** [comment]
Hey @mwoelk,

Do you get the same issue with `0.207.1` as well?

**Comment by bestwishCT** [comment]
> Setting `N8N_USE_DEPRECATED_REQUEST_LIB: 'true'` as a workaround helps and results in correct behaviour.

thanks a lot , It solved my problem

**Comment by Joffcom** [comment]
Going to mark this as closed for now, I suspect if this wasn't resolved recently it will pop up again soon as we have removed the old library from 1.0.

If this does still happen let me know and we can open this again.
