### ISSUE TITLE
LocalFileTrigger does not work with mounted network shares and related options

### ISSUE THREAD

**Issue by marzn** [n8n-io/n8n#4915]
**Describe the bug**

I am not sure if this is a bug or works as intended.
Chokidar (the used library) requires to **use polling** to watch files over a network [source](https://github.com/paulmillr/chokidar#performance).
As this decreases the performance it should be an option, which can be activated if required.
Some users discussed this in the [forum](https://community.n8n.io/t/local-file-trigger-node-not-triggering/18132).

More like a feature is the **await write finish** which helps to avoid partially read.
In some situations this is very helpful ;)

I am not sure about only watching the file change event.
As I observed sometimes there is no file change event, but a file add event if I added files.
And maybe one only wants to watch file add event, but not the file change event.
Therefore a multi option field like for watching folders should be implemented for watching files.
Or as an alternative, there should be no difference between file and folder watching, as both configures a path which is watched ignoring the triggerOn option.

And last one, if I stop n8n for updates or something, I want to process files which appeared in the meantime.
**Ignore initial** should be an option.

**Expected behavior**

Provide options for 
- polling
- await write finish
- ignore initial

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.200.1
- Node.js Version 16.17.0
- Database system SQLite

**Additional context**

Here is a [PR](https://github.com/n8n-io/n8n/pull/4914)

**Comment by Joffcom** [comment]
Hey @marzn,

This looks like an interesting one, I will get an internal ticket raised to look at the PR and get it reviewed. For now I think as you have put in a PR I will close this issue and we can work from the PR.
