### ISSUE TITLE
bug(rest/executions-current) the filter parameter not work, return other workflow's execution logs

### ISSUE THREAD

**Issue by brookqin** [n8n-io/n8n#4926]
**Describe the bug**

Open a workflow in editor, switch to exection log view, UI begin to request `executions-current`
> rest/executions-current?filter=%7B%22workflowId%22:%22**6**%22%7D

the result is:
`{"data":[{"id":66042,"workflowId":"3","mode":"webhook","startedAt":"2022-12-14T10:06:04.549Z"}]}`

workflowId(3) from result not equal to filter options(6), and exection log view will crash after few minutes.

![loading](https://user-images.githubusercontent.com/405636/207582375-50ad523d-4e06-488a-b373-d009f0d2313e.png)

**Environment (please complete the following information):**

- OS: [n8n custom docker image]
- n8n Version [0.207.0]
- Node.js Version [16]
- Database system [postgreSql]
- Operation mode [queue]

**Comment by Joffcom** [comment]
Hey @brookqin,

When you say the view will crash what happens? What do you see?

**Comment by brookqin** [comment]
> When you say the view will crash what happens? What do you see?

log view will back to blank looks like the workflow never executed.

Also you can try to reproduce in other way:
1. Create a new blank workflow, no need to save or any operations;
2. switch to log view;
3. you will see several of running exections

![logs](https://user-images.githubusercontent.com/405636/207593012-4a0e7a58-86e8-4d26-a0e6-d941aab708ff.png)

**Comment by Joffcom** [comment]
Hey @brookqin,

I have had the window opened on my instance for about 40 minutes now and it has not happened yet. How often are your workflows running, I wonder if it is somehow linked to load. Does n8n actually crash or do you just see an empty window, the screenshot you have posted is for a running workflow are you able to see a finished workflow?

**Comment by brookqin** [comment]
No, that is not a running workflow, its empty and unsaved.

This problem may be related to the queue mode, n8n have 1 main pod / 2 webhook pods / 4 worker pods in k8s. 
webhook & worker env: EXECUTIONS_PROCESS = main

n8n have 5 actived workflows and all start with webhook node, about 2000 queries per minute.

**Comment by Joffcom** [comment]
That is odd, so on an empty workflow you are still seeing executions loading instead of the empty execution page?

**Comment by brookqin** [comment]
> That is odd, so on an empty workflow you are still seeing executions loading instead of the empty execution page?

Yes!

Filter workflowid 6 returns 3, maybe  the problem from here:
![image](https://user-images.githubusercontent.com/405636/207629390-82877c3e-f664-416b-9622-0e6d5f8c92c6.jpeg)

**Comment by Joffcom** [comment]
@netroy what do you think buddy?

**Comment by brookqin** [comment]
@Joffcom 
I have found a simple way to reproduce this bug.

1. start up withPostgresAndWorker
2. create 2 actived workflows:
  A: only 2 nodes, webhook -> reponse to webhook;
  B: webhook -> wait(15s) -> response to webhook;
3. open execution logs page of workflow A
4. request workflow B

Workflow B executing log will show in workflow A page.


I am not familiar with typeorm so not sure following script work or not.
```
withpostgresandworker-n8n-1         | query: SELECT "ExecutionEntity"."id" AS "ExecutionEntity_id", "ExecutionEntity"."data" AS "ExecutionEntity_data", 
"ExecutionEntity"."finished" AS "ExecutionEntity_finished", "ExecutionEntity"."mode" AS "ExecutionEntity_mode", "ExecutionEntity"."retryOf" AS "ExecutionEntity_retryOf", 
"ExecutionEntity"."retrySuccessId" AS "ExecutionEntity_retrySuccessId", "ExecutionEntity"."startedAt" AS "ExecutionEntity_startedAt", 
"ExecutionEntity"."stoppedAt" AS "ExecutionEntity_stoppedAt", "ExecutionEntity"."workflowData" AS "ExecutionEntity_workflowData", "ExecutionEntity"."workflowId" AS "ExecutionEntity_workflowId", "ExecutionEntity"."waitTill" AS "ExecutionEntity_waitTill" 
FROM "public"."execution_entity" "ExecutionEntity" 
WHERE "ExecutionEntity"."workflowId" IN ($1, $2) 
AND "ExecutionEntity"."workflowId" = $3 
ORDER BY id DESC LIMIT 20 -- PARAMETERS: [1,3,"1"]
```
> workflow_entity: "id" int4
> execution_entity: "workflowId" varchar

**Comment by brookqin** [comment]
Hi @Joffcom , 

I'm sure the bug is caused by the field type
> workflow_entity: "id" int4
> execution_entity: "workflowId" varchar

https://github.com/n8n-io/n8n/blob/231257d0817df711cf900703fd686efb8307eeb2/packages/cli/src/Server.ts#L1320
sharedWorkflowIds is an array of number, but `req.query.filter.workflowId` is string type, so `sharedWorkflowIds.includes(workflowId)` always return false. 

> withpostgresandworker-n8n-1         | sharedworkflowids:  [1,2]
> withpostgresandworker-n8n-1         | req.query:  {"filter":"{\"workflowId\":\"1\"}"}
> withpostgresandworker-n8n-1         | findOptions:  {"select":["id","workflowId","mode","retryOf","startedAt"],"order":{"id":"DESC"},"where":{"id":{"_type":"in","_value":["7","7"],"_useParameter":true,"_multipleParameters":true}}}
> withpostgresandworker-n8n-1         | query: SELECT "ExecutionEntity"."id" AS "ExecutionEntity_id", "ExecutionEntity"."mode" AS "ExecutionEntity_mode", "ExecutionEntity"."retryOf" AS "ExecutionEntity_retryOf", "ExecutionEntity"."startedAt" AS "ExecutionEntity_startedAt", "ExecutionEntity"."workflowId" AS "ExecutionEntity_workflowId" FROM "public"."execution_entity" "ExecutionEntity" WHERE "ExecutionEntity"."id" IN ($1, $2) ORDER BY "ExecutionEntity"."id" DESC -- PARAMETERS: ["7","7"]

**Comment by netroy** [comment]
Fixed in https://github.com/n8n-io/n8n/pull/4971
