### ISSUE TITLE
Execute Command Node not found in version 0.207.1

### ISSUE THREAD

**Issue by ItsDeva** [n8n-io/n8n#4934]
Execute Command node is not present in the available nodes. Previously I]ve used it in the 0.203 versions

**To Reproduce**

1. Upgrade n8n to 0.207.1 through yarn 
2. Start n8n server
3. Search Execute Command in nodes

**Expected behavior**
There will be no execute command node.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 LTS (GNU/Linux 5.15.0-1021-oracle aarch64)
- n8n Version0.207.1
- Node.js Version 14.21.1
- Database system Postgres
- Operation mode own

**Additional context**

<img width="955" alt="image" src="https://user-images.githubusercontent.com/19466930/207806097-4a58046c-238d-4cb6-97d6-89df9ea17e3e.png">

<img width="270" alt="image" src="https://user-images.githubusercontent.com/19466930/207806188-9fd0d2d2-46cb-4d75-8ebd-65594ee1da9b.png">

**Comment by Joffcom** [comment]
Hey @ItsDeva,

I have just taken a quick look on my install of n8n and the Execute Command node appears to be there, Have you maybe set the `NODES_EXCLUDE` environment option at some point? It looks like your node version could do with an update to 16 as well.

**Comment by ItsDeva** [comment]
Have you installed and tested using npm or yarn?
I didn't set NODES_EXCLUDE env. I'll update my node.js version

**Comment by ItsDeva** [comment]
Removed Everything completly. A Clean install worked for me. Now I can see the Execute Command. Thanks for the time @Joffcom ;-)
