### ISSUE TITLE
RabbitMQ Trigger does not appear in On App Events listing

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4952]
**Describe the bug**

RabbitMQ Trigger does not appear in On App Events listing

**To Reproduce**

![a2056cce-26b5-475f-a3be-0dee25af3303](https://user-images.githubusercontent.com/257004/208183273-d638b317-8d13-4cbb-ad1c-32e5a98c7365.png)

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version 0.208.0
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by janober** [comment]
Fix got released with `n8n@0.209.0`

**Comment by netroy** [comment]
The fix for this needed to be reverted. We'll try addressing this again.

**Comment by janober** [comment]
Fix got released with `n8n@0.209.4`
