### ISSUE TITLE
duplicate aws job

### ISSUE THREAD

**Issue by carloslencargorges** [n8n-io/n8n#4953]
**Describe the bug**
whenever I try to carry out a transcription with aws transcribe it returns a message that there is already a job with that name. I noticed that when I run the flow it is running twice.

**To Reproduce**

![image](https://user-images.githubusercontent.com/98112671/208202631-40cae250-4cde-4631-9a58-59d6bd5b9089.png)

**Expected behavior**
the test flow should be executed only once and not return the error:
"The requested job name already exists. Use a different job name."

**Environment (please complete the following information):**

- OS:  Ubuntu Linux 22.04 (Digital Ocean)
- n8n Version  0.208.0
- Node.js Version [e.g. 16.17.0]
- Database system SQLite
- Operation mode own

Below is the print:
![image](https://user-images.githubusercontent.com/98112671/208202492-89a5e166-d4c1-424f-80c0-71ff589a9f7f.png)

**Comment by Joffcom** [comment]
Hey @carloslencargorges 

It might sound odd but I can't see an issue in the screenshot. The s3 file fetch is returning 3 items so I would expect the transcribe node to run 3 times once for each input item.

Assuming this is what you are referring to when you say it is running twice you will need to either tell the node to run only once under the node settings which means it would only process the first item or change the name so it uses the key value from the previous node if that is an option.

As this doesn't look like a bug I am going to mark this one as closed and if it does turn out to be one we can open it again.

**Comment by rrcsoares** [comment]
Hello
I have the same problem and I haven't found the solution yet.
Could you be more specific please?
Thanks
