### ISSUE TITLE
IMAP is missing a test function

### ISSUE THREAD

**Issue by luketainton** [n8n-io/n8n#4955]
**Describe the bug**
The IMAP Credential connector is not able to confirm if it can connect to the email server as the test function appears to be missing.

**To Reproduce**

1. Create a new Credential of type IMAP
2. Fill in the form with valid details and save it
3. Attempt to test your connection

**Expected behavior**
A confirmation that the connection works, or an alert that it failed **due to incorrect configuration**.

**Environment (please complete the following information):**

- OS: Alpine 3.16.2 (Docker image n8nio/n8n:latest)
- n8n Version: 0.208.0
- Node.js Version: 16.18.1
- Database system: SQLite
- Operation mode: own

**Screenshot**
<img width="305" alt="Screenshot 2022-12-17 at 19 50 11" src="https://user-images.githubusercontent.com/22561713/208264109-f17ab6fc-a55b-402b-b470-5f12dcda1ca5.png">

**Comment by Joffcom** [comment]
Hey @luketainton 

That is an interesting one, it looks like we have the test function in the code 🤔

@netroy could this be related to the change in node loading?

**Comment by netroy** [comment]
@Joffcom It was indeed related to that change. 
Can you please review [this fix PR](https://github.com/n8n-io/n8n/pull/4962) ?

**Comment by janober** [comment]
Fix got released with `n8n@0.208.1`
