### ISSUE TITLE
Data missing from dynamodb connector when using “simplify” setting

### ISSUE THREAD

**Issue by napter** [n8n-io/n8n#4957]
When the dynamodb connector is in “simple” mode, columns containing JSON data (datatype “map”) are being set to null. Here is the results of a query with simplify on, note the null value:
![image](https://user-images.githubusercontent.com/6260841/208264862-7649029a-fc8d-4e92-9443-203a4b8492c0.png)

Here is the output of the exact same query with simplify turned off, note the same field with “M” data (map) now shows data:
![image](https://user-images.githubusercontent.com/6260841/208264869-6fd0649f-c200-472f-a783-6b83f410c316.png)

Here is the workflow:
`{
  "meta": {
    "instanceId": "774a1610bb3dee8ad6ccba09f537e24bcd176ae4f9a16da8b8b4ce530d1284a4"
  },
  "nodes": [
    {
      "parameters": {
        "operation": "getAll",
        "tableName": "orders",
        "scan": true,
        "filterExpression": "#et=:et",
        "eavUi": {
          "eavValues": [
            {
              "attribute": ":et",
              "value": "OrderParent"
            }
          ]
        },
        "options": {
          "projectionExpression": "",
          "eanUi": {
            "eanValues": [
              {
                "key": "#et",
                "value": "_et"
              }
            ]
          }
        }
      },
      "id": "9a44f16c-f3ab-4744-a181-86f8c6bd92ba",
      "name": "AWS DynamoDB",
      "type": "n8n-nodes-base.awsDynamoDb",
      "typeVersion": 1,
      "position": [
        140,
        300
      ],
      "credentials": {
        "aws": {
          "id": "6",
          "name": "AWS account"
        }
      }
    }
  ],
  "connections": {}
}
          `

n8n version:
0.207.0 running in Docker

**Comment by janober** [comment]
Fix got released with `n8n@0.209.1`
