### ISSUE TITLE
OpenAI models are not listed

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4963]
**Describe the bug**

OpenAI models are not listed and an error message appears next to them

![image](https://user-images.githubusercontent.com/257004/208415454-c3499b30-dbde-48cf-968f-a96d58039d82.png)

Even though it doesn't appear, when typing the name of the model it works correctly.

**To Reproduce**

1. Add OpenAI Credentials
2. Add an OpenAI node to Workflow
3. Choose your Credential
4. Models are not listes and an error message appears next to them

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by netroy** [comment]
@luizeof Can you please try again on `0.208.1` ?

**Comment by luizeof** [comment]
![image](https://user-images.githubusercontent.com/257004/208488177-710bf9ff-3c13-488c-8927-f047336f4450.png)

It Works!

**Comment by luizeof** [comment]
Resolved 0.208.1

**Comment by NoAArrr365** [comment]
The issue came back with latest updates both :
1.8.2 (latest stable)
1.9.1 (latest beta)
