### ISSUE TITLE
Copying icons fails on second run if source directory is read-only

### ISSUE THREAD

**Issue by K900** [n8n-io/n8n#4973]
**Describe the bug**
When the node_modules directory is read-only, the [icon copying code](https://github.com/n8n-io/n8n/blob/3754c49f0cf22e1728536412853125679f7065cc/packages/cli/src/LoadNodesAndCredentials.ts#L336) will also copy the icon files as read-only, and fail to overwrite them on the next startup.

**To Reproduce**

1. `chmod -R -w node_modules`
2. Run n8n
3. Stop n8n
4. Run n8n

**Expected behavior**
n8n starts correctly.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04] NixOS unstable
- n8n Version [e.g. 0.200.1] 0.208.1
- Node.js Version [e.g. 16.17.0] 16.18.1
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] SQLite
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`] own

**Additional context**
The NixOS packaging model requires things to be read only, so we currently can't update n8n to the versions that added the icon copying code.

**Comment by Joffcom** [comment]
Hey @K900,

It looks like this should be resolved now, I am going to mark it as closed. If you are still seeing this issue let me know and we can look into it again.

**Comment by K900** [comment]
Thanks, it is in fact resolved, I thought the PR would auto-close this.
