### ISSUE TITLE
How to host under subpath ?

### ISSUE THREAD

**Issue by jigardafda** [n8n-io/n8n#50]
I have depoyed n8n behind nginx under `/workflow/admin` subpath.

https://example.com/ -> is main website
https://example.com/workflow/admin -> is n8n path

What are configuration changes i need to do achieve this ?

**Comment by janober** [comment]
In the meantime maybe that is helpful:

```bash
# How n8n should be made available. Gets by default also used to create the 
# base of the webhook URL.
N8N_HOST="n8n.example.com"
N8N_PORT=443
N8N_PROTOCOL="https"

# If the Webhook URL is different because for example there is a reverse proxy
# in front of it and n8n does use port 4000 but is reachable from the outside via
# 443 it can be overwritten with:
WEBHOOK_TUNNEL_URL="https://n8n.example.com/"

# This URL gets used in the Frontend to tell it where the backend can be found
VUE_APP_URL_BASE_API="https://n8n.example.com/"
```

So if you set for `WEBHOOK_TUNNEL_URL` and `VUE_APP_URL_BASE_API` the URL with the subdirectory it should work (both with trailing slash).

**Comment by janober** [comment]
Close for now as it should be on https://community.n8n.io like written above.
