### ISSUE TITLE
todoist oAuth connection broken with `invalid_scope` error.

### ISSUE THREAD

**Issue by kquinsland** [n8n-io/n8n#5032]
**Describe the bug**

When attempting to set up ToDoist oAuth connection, I get an `invalid scope` error.

**To Reproduce**

I am self hosted so please excuse the (lightly) edited URLs.

I was following the instructions here: https://docs.n8n.io/integrations/builtin/credentials/todoist/
I successfully set up a new oAuth app / obtained my client/secret details and plugged them in to n8n.

After clicking the "connect" button, a new window launched and - since I was already signed into Todoist - quickly redirected to an error:

```text
URL: https://n8n.testing.my-domain.net/rest/oauth2-credential/callback?error=invalid_scope

Err:
{"code":503,"message":"Insufficient parameters for OAuth2 callback. Received following query parameters: {\"error\":\"invalid_scope\"}"}
```

side note: please consider changing the behavior so clicking on the "connect" button launches a _new tab_ and not a new window or even just shows the user the URL they need to enter. It makes debugging a lot easier!

In any event, I was able to capture the URL that initiates the oAuth dance:

```text
https://n8n.testing.my-domain.net/rest/oauth2-credential/auth?id=3&clientId=...&clientSecret=...&csrfSecret=...&grantType=authorizationCode&authUrl=https://todoist.com/oauth/authorize&accessTokenUrl=https://todoist.com/oauth/access_token&scope=data:read_write,data:delete&authQueryParameters=&authentication=body
```

Clicking that URL issues a re-direct to this URL:

```text
https://todoist.com/oauth/authorize?client_id=...&redirect_uri=...testing.my-domain.net%2Frest%2Foauth2-credential%2Fcallback&response_type=code&state=...&scope=data%3Aread_write%20data%3Adelete&scope=data%3Aread_write%2Cdata%3Adelete
```

If I then click _that_ url, todoist does not like it. Thinking back to the `invalid_scope` I figured i'd try reversing the URL decode on the `scope` query param:

```text
https://todoist.com/oauth/authorize?client_id=...&redirect_uri=...testing.my-domain.net%2Frest%2Foauth2-credential%2Fcallback&response_type=code&state=...&scope=data%3Aread_write%20data%3Adelete&scope=data:read_write,data:delete
```

And clicking **that** url worked. I was brought to the consent screen asking me if I wanted to allow my app to have access to my data.

**Expected behavior**

I would expect that the `oauth2-credential` endpoint render a `todoist.com/oauth` url with the `scope` query param values _properly_ encoded.

**Environment (please complete the following information):**

I am self hosting in a k8s cluster. The k8s version is 1.24.x and the container that I am using is your `0.209.2` container image. I am using postgres for the database.

**Additional context**

**Comment by Joffcom** [comment]
Hey @kquinsland,

I will take a look at this one in the morning, Thanks for reporting it. I tend to use the API Key option which might be why I missed this when updating the node recently.

**Comment by kquinsland** [comment]
> I tend to use the API Key option which might be why I missed this when updating the node recently.

Same, but I am playing around with webhook driven automation rather than cron to trigger a sync and _then_ process every matching task.

I had no trouble setting things up with the API token for my initial testing.

**Comment by kquinsland** [comment]
Slightly unrelated but I figured i'd ask here first for some basic guidance before opening a new issue outright (but let me know if this is something that I should open a new issue for!)

----

I am very happy that it's trivial to put the incoming webhook into `test` mode but is there a way to _not_ change the URL based on the test/prod mode?

The reason im asking: I have to keep updating the Todoist app integration settings to use the updated URL when I want to debug something.

RIght now, switching between test/prod mode results in two URLs:

`https://n8n.com/webhook/some-uuid` versus ``https://n8n.com/webhook-test/some-uuid`

What i'd like to do is click the "listen for incoming" button on the webhook node and - without changing the incoming URL - see the raw incoming payload instead of running the rest of the nodes chained to the incoming webhook node. 

Is that a new issue/feature-request or is there something obvious that i'm missing? I looked for a simple "display the text fed as input to $self" node but didn't find anything unless I also wanted that text sent to google docs/markdown file ... etc.

**Comment by Joffcom** [comment]
@kquinsland that sounds more like a support question / feature request than an issue so would be better placed on our community support forum (https://community.n8n.io/)

Chances are we probably won't change the behaviour as I can see it possibly breaking some workflows or leading to the wrong data being captured if it is a fairly active webhook but then again if the community vote for the request then maybe it will happen.

On the oauth side of things I had a quick look and for some reason we double up the scope in the URL which I think is causing the issue, The encoded scopes do appear to work as expected manually which is handy.

**Comment by kquinsland** [comment]
> @kquinsland that sounds more like a support question / feature request than an issue so would be better placed on our community support forum (https://community.n8n.io/)

Got it / thanks.  Thread opened [there](https://community.n8n.io/t/toggle-inbound-webhook-node-into-test-produciton-mode-without-changing-url/21543)

> Chances are we probably won't change the behaviour as I can see it possibly breaking some workflows or leading to the wrong data being captured if it is a fairly active webhook but then again if the community vote for the request then maybe it will happen.

Does this mean that the prod workflow is still active when in dev mode?  Otherwise I don't see how this changes anything. I'm simply proposing a (slight) change:  the URL does not change, only weather the incoming request body is displayed or sent down the chain.



> On the oauth side of things I had a quick look and for some reason we double up the scope in the URL which I think is causing the issue, The encoded scopes do appear to work as expected manually which is handy.

**DOH!**

I do not know how I missed that, the first time ... But it's RIGHT THERE in my opening post:

> &scope=data%3Aread_write%20data%3Adelete&scope=data%3Aread_write%2Cdata%3Adelet


Yep. `scope=` shows up twice.  `theresyourproblem.jpg`

**Comment by mariusc23** [comment]
@Joffcom Any update on fixing this? I noticed the repeated scope is an issue for custom integrations too. If it helps, I noticed it's only an issue if there are multiple scopes (comma separated). If a single scope is set it doesn't double it up.

**Comment by Joffcom** [comment]
Hey @mariusc23 

Not yet I will double check this morning that I created an internal dev ticket for this one though and get it updated to include that it is an issue for more than just one node.

**Comment by Joffcom** [comment]
Internal ticket for this one is `N8N-6337`

**Comment by Joffcom** [comment]
Hey @mariusc23 & @kquinsland,

Good news this was fixed and has been working since `0.234.0`, If you have not already done it update your instances and let me know how you get on.

I am going to mark this as closed for now and if you are still seeing the same issue let me know and I will open it again.

**Comment by mannnish** [comment]
i am still facing this issue, i am trying to login in nodejs cli application (using this doc https://developer.todoist.com/guides/#step-1-authorization-request) and in return i am getting invalid scope error

**Comment by Joffcom** [comment]
Hey @mannnish which version of n8n are you using?

**Comment by mannnish** [comment]
how do i check that?

**Comment by Joffcom** [comment]
@mannnish if you open the n8n web interface it will be under about, how did you install n8n as well that can sometimes provide a hint.
