### ISSUE TITLE
Notion: Create page node fails when relation is empty

### ISSUE THREAD

**Issue by papykhader** [n8n-io/n8n#5050]
`n8n version : 0.209.3`

Hello, I am encoutering an issue with the Notion node to create a new database page.

## What I am trying to do

In my workflow, I need to create pages in a database in notion. This database has a field that is a `relation` to another database. The value for the relation is set using an expression as the data comes from another node. Sometimes that expression might result in `null`, `undefined` or an `empty array` as the relation id might not be available. I expect the page to be created without the relation to the other database.

## Issue

When the expression inside `Relation IDs` is not a valid UUID, the node throws an error and the page is not created. 

After some investigation, I understood that the problem was related to [this line of code ](https://github.com/n8n-io/n8n/blob/26e2321a710d7b42559492a6605cef3a248d918e/packages/nodes-base/nodes/Notion/GenericFunctions.ts#L287
).

``` javascript
value.relationValue.reduce((acc: [], cur: any) => {
    return acc.concat(cur.split(',').map((relation: string) => ({ id: relation.trim() })));
}, [])
```

When the expression is `null` or `undefined`, it is the piece of code above that throws an exception as the `cur` object is not a string. Calling the `split` function is impossible.

When the expression results in an `empty string` or an `empty array`, it is the call to the notion API that fails due to payload validation error: ```body failed validation: body.properties.Category.relation[0].id should be a valid uuid, instead was `""` ```
This is because in the piece of code above, the `split` function will always return an array with at least one empty string inside. Which will be tuned by the `map` function call to something like `{id: ""}` which is invalid for the API.

In both cases, the node will fail and the page will not be created. 

## Desired behaviour

The [notion API documentation](https://developers.notion.com/reference/property-value-object#relation-property-values) specifies that if the relation is empty, the value of that property should be an `empty array`. 

To fix this issue, you can modify the implementation of the Notion node as follows:
``` javascript
value.relationValue.reduce((acc: [], cur: any) => {
    // Check if cur is a string before calling split
    if (typeof cur === 'string') {
        return acc.concat(cur.split(',').map((relation: string) => ({ id: relation.trim() })));
    }
    // Return an empty array if cur is not a string
    return acc;
}, [])
```
This modification will check if the `cur` object is a string before calling the `split` function. If it is not a string, it will return an `empty array` instead of attempting to call split on it. This should prevent the error from occurring when the `Relation IDs` expression returns `null`, `undefined`, or an `empty array`.

**Comment by GuillaumeDeGroote** [comment]
Here is an example of how you could modify your workflow to solve the issue without changing the implementation of the Notion node:

- Remove the `Relation IDs` field from the `Create Page` node.
- Connect the `Create Page` node to a `Conditional` node.
- In the `Conditional` node, set up a condition to check if the value for the relation property exists in the payload. For example, you could use an expression like `{{$node["Create Page"].json['categoryId']}}` to check if the Category relation property is set in the payload.
- If the condition is true, connect the `True` output of the `Conditional` node to a `Update Page` node.
- In the `Update Page` node, set the `Page ID` to the ID of the page that was created by the `Create Page` node. You can use the ID field from the Create Page node output as the value for the Page ID field.
- In the `Update Page` node, set the relational property to the value you want to update. For example, you could use an expression like `{{$node["Before Create Page"].json["categoryId"]}}` to set the Category relation property to the value that was passed to the `Create Page` node.
- Connect the `False` output of the `Conditional` node to the next node in your workflow. This will allow the workflow to continue if the relation property is not set in the payload.

This solution will allow you to create a page without setting the relation property, and then update the page with the relation property if it is available. It will avoid the error that occurs when the Relation IDs expression returns null, undefined, or an empty array, and allow you to create the page even if the relation property is not set.

I hope this helps! Let me know if you have any further questions.

**Comment by csuermann** [comment]
Hi @papykhader,
Thanks for reporting this issue and hinting at the fix. And apologies for the delay in getting back to you. We'll address this asap.
