### ISSUE TITLE
Monica CRM Api not working for selfhosted option

### ISSUE THREAD

**Issue by tlwt** [n8n-io/n8n#5053]
**Describe the bug**
I am trying to connect to a selfhosted Monica CRM version. When trying to utilize the API (e.g. Contact => get many) a "404 - ERROR: The resource you are requesting could not be found". Trying the same step with the hosted version of MonicaHQ works but when switching the settings to selfhosted with the hosted service, the same error occures.

**To Reproduce**

1. Get MonicaHQ API key from hosted instance
2. Set credentials for Monica CRM on n8n, Environment = hosted
3. Add work flow item "Monica CRM" => Contacts => Get many
4. Execute node works fine
5. Go back to credentials, edit Monica CRM account and switch environment to selfhosted, enter https://app.monicahq.com/api as server
7. Go back to work flow item and click again on execute
8. See error
9. ERROR: The resource you are requesting could not be found 404 - {"message":""}

**Expected behavior**
execution on selfhosted environment should be the same as with the hsoted version

**Environment (please complete the following information):**

- OS: Docker on Synology running n8nio/n8n:latest
- n8n Version 0.209.3 
- Node.js Version [e.g. 16.17.0]
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @tlwt,

What version of Monica are you running on your self hosted instance? I will have to set up a test environment to look into it further but that could be a good starting point. It may also be worth double checking the URL and either adding or removing any trailing slashes.

**Comment by romainvaltier** [comment]
Same issue with monica docker version => 3.7.0

**Comment by tlwt** [comment]
Hi @Joffcom, sorry for the delayed responds - I am using Version: 3.7.0.

**Comment by romainvaltier** [comment]
Issue solved on my side! It was my mistake.

I am using **https://my.mydomain.com** as Self-Hosted Domain (as it is recommended) and NOT https://my.domain.com**/api**.

**Comment by Joffcom** [comment]
@romainvaltier that is handy to know, @tlwt looks like you might be using /api as well so this will also solve it for you.

Out of interest was using `/api` documented anywhere?

**Comment by romainvaltier** [comment]
@Joffcom In one hand, in Monica administration interface, endpoint is referenced like this : https://my.domain.com/api and in another hand in n8n Monica : Self-Hosted URL is referenced https://my.domain.com (without /api). On my side I have been influenced by Monica "official" administration interface reference.
Maybe for consistency it would be better that both sources are aligned to avoid such misinterpretation.
Again it was my mistake : most of the time the bug is between the chair and the keyboard :-)
You are doing a great job. Thanks a lot!

**Comment by tlwt** [comment]
@Joffcom - yes, thanks! That did it. (just as a note with a trailing slash it throws errors).

**Comment by Joffcom** [comment]
@tlwt That is annoying with the slash, I will create a ticket to cover that one off. I have also noticed we don't support self signed certificates or have a credential test implemented.
