### ISSUE TITLE
Opening past executions on new tab loads most recent

### ISSUE THREAD

**Issue by felipequinaglia** [n8n-io/n8n#5070]
When using CTRL (Win) or CMD (Mac) to open an execution in a new tab it always loads the most recent execution instead.

- OS: MacOS
- n8n Version 0.208

**Comment by Joffcom** [comment]
Hey @felipequinaglia,

I have just done a quick test in Brave and Safari and this appears to be working for me at the moment, Can you try updating your instance to see if that changes anything for you? If it doesn't can you confirm which browser you are using?

**Comment by felipequinaglia** [comment]
Hello @Joffcom,

Last week I updated the n8n and forgot to test to see if it was still happening and it seems that was a problem with the version I was using at the time. As for now on the version 0.210.2 it's oppening the right execution.
