### ISSUE TITLE
Trigger Node in Queue Mode w/ Filesystem Binary Storage

### ISSUE THREAD

**Issue by rhyswilliamsza** [n8n-io/n8n#5138]
**Describe the bug**
In queue mode, some trigger nodes, like `EmailReadImap`, will always trigger on the `main` instance before handing off the rest of the workflow to a `worker` instance. This causes a failure when `Filesystem` binary storage is enabled, as the `worker` instances do not have access to the data persisted by the trigger node on the `main` instance. 

**To Reproduce**

1. Configure `n8n` in [queue mode](https://docs.n8n.io/hosting/scaling/queue-mode/#configuring-workers)
2. Create a workflow with a trigger node that persists data.
3. Try to access the persisted binary data later in the workflow.

**Expected behavior**
Option 1: Trigger nodes should, if possible, begin their execution on the `worker` instance that runs the rest of the workflow. This may be difficult, though, especially with webhook-based trigger nodes - but there may be some clever things that one could implement to address this.
Option 2: The documentation should be updated to require a common `binaryData` volume/folder across `main` and `worker` instances:

**Environment (please complete the following information):**

- OS: All
- n8n Version: 0.210.2
- Node.js Version: All
- Database system: MySQL
- Operation mode: Queue

**Additional context**

**Comment by Joffcom** [comment]
@krynble is this by design?

**Comment by krynble** [comment]
Hey @rhyswilliamsza thanks for reporting this and thanks for mentioning me @Joffcom 

Def we should add this to the docs - n8n does not support queue mode + binary data storage. As you mentioned, it should be possible with a shared storage but this is not a scenario we've thoroughly tested.

By design those two solutions are not supported simultaneously.

Can you add this to the docs @StarfallProjects ?

**Comment by StarfallProjects** [comment]
https://github.com/n8n-io/n8n-docs/pull/1069

**Comment by rhyswilliamsza** [comment]
Thanks for the feedback! We may give shared storage a go regardless (with the understanding that it's unsupported), and will add some feedback here about how it goes.
