### ISSUE TITLE
jira node Additional Fields( Assignee )not work

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [n8n-io/n8n#515]
**Describe the bug**
as shown
![image](https://user-images.githubusercontent.com/29906873/80294982-26e13800-87a1-11ea-9009-505943952b74.png)

**To Reproduce**
Create the jira node as shown
results: 
Error: Jira Error: {}
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Jira/JiraSoftwareCloud.node.js:273:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Expected behavior**
normal operation

**Environment (please complete the following information):**
 - OS: [Alpine Linux 3.11]
 - n8n Version [0.63.0]
 - Node.js Version [e.g. 12.16.2]

**Additional context**
nothing

**Comment by RicardoE105** [comment]
Hey @MyCupOfTeaOo, thanks for letting us know.

Seems like the issue is with the Server version. I just tested it with Jira Cloud and it worked fine. I will check out and let you know.

**Comment by MyCupOfTeaOo** [comment]
> Hey @MyCupOfTeaOo, thanks for letting us know.
> 
> Seems like the issue is with the Server version. I just tested it with Jira Cloud and it worked fine. I will check out and let you know.

My jira is self-hosted,
As long as I don't use Assignee or Labels, the operation is ok

**Comment by janober** [comment]
Can you please retry with the latest version n8n@0.64.0

Not sure if the problem is fixed there but we fixed at least a bug with the error handling in the Jira-Node so it should then at least display the correct error message which will allow knowing what exactly it is complaining about.

**Comment by MyCupOfTeaOo** [comment]
![image](https://user-images.githubusercontent.com/29906873/80693495-ab1b1e80-8b05-11ea-9ffc-783c22ece20d.png)
The interface here is wrong, it should be name
