### ISSUE TITLE
Migration failure moving from 0.210.1 to 0.211.0

### ISSUE THREAD

**Issue by jeremybep** [n8n-io/n8n#5168]
**Describe the bug**
i'v simple update n8n npm : `npm update -g  n8n` on powershell

run n8n command 
```
Migrations in progress, please do NOT stop the process.
Migration "DeleteExecutionsWithWorkflows1673268682475" failed, error: SQLITE_CORRUPT: database disk image is malformed
Error exporting credentials. See log messages for details.
SQLITE_CORRUPT: database disk image is malformed
```

Complete `npm update -g  n8n` prompt 
```
PS C:\Users\jeremyb\.n8n> npm update -g  n8n
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: typeorm@0.2.45
npm WARN Found: ioredis@5.2.5
npm WARN node_modules/n8n/node_modules/ioredis
npm WARN   ioredis@"^5.2.4" from n8n@0.211.0
npm WARN   node_modules/n8n
npm WARN     n8n@"*" from the root project
npm WARN   1 more (bull)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional ioredis@"^4.28.3" from typeorm@0.2.45
npm WARN node_modules/n8n/node_modules/typeorm
npm WARN   typeorm@"0.2.45" from n8n@0.211.0
npm WARN   node_modules/n8n
npm WARN
npm WARN Conflicting peer dependency: ioredis@4.28.5
npm WARN node_modules/ioredis
npm WARN   peerOptional ioredis@"^4.28.3" from typeorm@0.2.45
npm WARN   node_modules/n8n/node_modules/typeorm
npm WARN     typeorm@"0.2.45" from n8n@0.211.0
npm WARN     node_modules/n8n
npm WARN deprecated n8n@0.211.0: please use version 0.210.2 instead

changed 1 package in 45s
```

**Expected behavior**
A fresh update, BUT after checking from release page isn't 0.211.0 the latest one but 0.210.2.
(https://docs.n8n.io/reference/release-notes/)

- OS: microsoft windows 10.0.19045 Build 19045
- n8n Version 0.211.0
- Node.js Version v18.12.0
- Database system SQLite

**Comment by jeremybep** [comment]
i've juste try to made a recover, but isn't working ether
`.\sqlite3.exe .\database.sqlite ".recover" | .\sqlite3.exe reco.sqlite`

```
PS C:\Users\brutus\.n8n> n8n
Initializing n8n process
Migrations in progress, please do NOT stop the process.
Migration "DeleteExecutionsWithWorkflows1673268682475" failed, error: SQLITE_CORRUPT: database disk image is malformed
```

**Comment by jeremybep** [comment]
even if i delete `database.sqlite` i'v got issue ? where this issue come from ?

**Comment by Joffcom** [comment]
Hey @jeremybep,

That looks like the migration failed because the database was unhappy, I take it going back to 0.210.1 doesn't really do anything?

Before the update was everything working smoothly and is there any chance that maybe 2 instances of n8n were running (Desktop and npm)?

**Comment by Joffcom** [comment]
Hey @jeremybep,

There is a chance that a database that large has caused an issue, Did you have a backup of your workflows and credentials? Another option could be to just move the old database file and let n8n create a new one then import the workflow backups.

**Comment by jeremybep** [comment]
The only backup i had is that databdase.sqlite, so i think open it with dbbrowser and clean `execution_entity` then re-open with n8n to see...
Not choice to export workflow one by one with dbBrowser...
Beacause `n8n export:workflow --all` won't work due to the Sqlite connexions issue.

**Comment by jeremybep** [comment]
ok, i'found issue.

1. My sqlite was so huge, so i put an auto vacuum to clean a bit...64Go > 5Mo :)
2. `DeleteExecutionsWithWorkflows1673268682475` is a missing key/value of `Migration` Table
So i append to it like other with the same convention 
![image](https://user-images.githubusercontent.com/72266507/212691222-f6870edf-bbc1-4172-b49a-f09d69a996a6.png)

And voila ! my n8n came back
