### ISSUE TITLE
Harvest API not working on self-hosted version

### ISSUE THREAD

**Issue by phillipfickl** [n8n-io/n8n#5169]
**Describe the bug**
Harvest is just not connecting (403 Forbidden) on the self-hosted version (0.210.2), neither the OAuth2 Connector, nor the Access-Token connector. Both work just fine on the desktop version (0.209.4). I can even just copy the credentials entry from the SQLite database on docker and it works on desktop (same encryption key).

**To Reproduce**

1. Add a harvest access token
2. Add a workflow with a harvest node
3. See the "Account Name or ID" call failing with a 403 - forbidden

**Expected behavior**
Harvest node connecting just like on desktop

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.210.2
- Node.js Version: 16.8.1
- Database system: SQLite
- Operation mode: own

**Additional context**
I double and triple checked access keys and the OAuth2 flow. I also tested different Google OAuth2 flows, they all worked flawlessly on docker and on the desktop app. Not sure if this is a problem introduced in 0.210.2, but from a quick search here and in the forum, there's quite a couple of services that do not work properly in a self-hosted environment.

**Comment by Joffcom** [comment]
Hey @phillipfickl,

I have just signed up for a Harvest account and it looks like the Access Token is working as expected for me on a self hosted docker instance.

![image](https://user-images.githubusercontent.com/4688521/212644966-da4944a4-c3b2-4677-8670-45a15ef812ed.png)

It looks like OAuth is connecting and returning data for me as well.
![image](https://user-images.githubusercontent.com/4688521/212645436-eb64c72d-9173-433c-b7a2-12156ff01c67.png)

![image](https://user-images.githubusercontent.com/4688521/212645513-4c93e1c7-c3b6-4e15-8ee9-66c918f544e4.png)

Out of interest does the HTTP Request node work with the access token if you copy the CURL command Harvest provides?

**Comment by phillipfickl** [comment]
> Hey @phillipfickl,
> 
> I have just signed up for a Harvest account and it looks like the Access Token is working as expected for me on a self hosted docker instance.
> 
> ![image](https://user-images.githubusercontent.com/4688521/212644966-da4944a4-c3b2-4677-8670-45a15ef812ed.png)
> 
> It looks like OAuth is connecting and returning data for me as well. ![image](https://user-images.githubusercontent.com/4688521/212645436-eb64c72d-9173-433c-b7a2-12156ff01c67.png)
> 
> ![image](https://user-images.githubusercontent.com/4688521/212645513-4c93e1c7-c3b6-4e15-8ee9-66c918f544e4.png)
> 
> Out of interest does the HTTP Request node work with the access token if you copy the CURL command Harvest provides?

Hi @Joffcom, thanks for your quick response!
Very weird indeed. This is how it works on desktop for me.
I tried curl on the command line (on the host running the docker instance) which worked well:
<img width="601" alt="Screenshot 2023-01-16 at 10 49 40" src="https://user-images.githubusercontent.com/1156835/212648500-56fa54dc-d932-49ae-9bc4-1c2117f003cb.png">

The HTTP Request node does not (I used the import curl button):
<img width="1099" alt="Screenshot 2023-01-16 at 10 51 29" src="https://user-images.githubusercontent.com/1156835/212648878-714ab4ad-6207-4504-98bc-b144ac6d010b.png">

**Comment by Joffcom** [comment]
Hey @phillipfickl,

That is strange, Are you using a custom image?

**Comment by phillipfickl** [comment]
I don't, just the normal n8nio/n8n image. 
For deploying, I followed the quick start guide for a hetzner server und only changed what's necessary, the .env file and the caddy config. 
Other than the authentication with Harvest, it runs smoothly..

**Comment by phillipfickl** [comment]
It gets weirder, running the docker image n8nio/n8n locally works like a charm (Mac). I guess that means that my docker setup on the Hetzner server is to blame. I will still update this issue once I find out what the root cause is - maybe there are others with the same problem.

**Comment by phillipfickl** [comment]
And here we go: the server had both, an IPv4 address and an IPv6 address. I just shutdown the server, removed the IPv6, rebooted it and Harvest works. I have no idea what the actual issue is/was, but it seems IPv6 is to blame. Maybe you want to place a hint in the documentation to disable IPv6, or a hint of what to do so it works.
