### ISSUE TITLE
Wrong url in Error Trigger node

### ISSUE THREAD

**Issue by ismanapa** [n8n-io/n8n#5197]
**Describe the bug**
After updating to version 0.211.2 we have an issue with the Error Trigger node because the URL generated by the node to review the executions with errors is not working now.

The URL given by the node has this format: `https://n8n-server.com/execution/executionID` but it seems like this URL is no longer working and now the executions URLs have this format `https://n8n-server.com/workflow/workflowID/executions/executionID`.

**To Reproduce**

1. Set the Error Workflow in any of your workflows
2. Execute a workflow that throws an error. For example with the "Stop and Error" node
3. Check the execution of the error workflow with the invalid URL

![image](https://user-images.githubusercontent.com/10558907/213391313-efd19ed7-2d99-40f3-9fdb-7948de563925.png)

**Expected behavior**
Receive the new URL format in the "Error trigger" node

**Environment (please complete the following information):**

- n8n Version:  0.211.2
- Node.js Version: 16
- Database system: PostgreSQL
- Operation mode: queue

Thanks for all! 🎉

**Comment by Joffcom** [comment]
Hey @ismanapa,

Thanks for reporting this one, I have managed to reproduce it and have created an internal ticket which we will be tracking as `N8N-5975`.

**Comment by Joffcom** [comment]
Hey @ismanapa,

Good news, This has been fixed and will be available in the next release. For now I am going to mark this one as closed, Thanks again for reporting this and have a good weekend 🙌🏻

**Comment by ismanapa** [comment]
Thank you for all!

You are awesome! 🎉
