### ISSUE TITLE
Cannot find module magic

### ISSUE THREAD

**Issue by arnaudknobloch** [n8n-io/n8n#52]
Hi,

I wanted to test n8n but I encountered the following error:
`Error: Cannot find module '../build/Release/magic'
    at Object.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/mmmagic/lib/index.js:1:75)`

I just did `npm install n8n -g` then `n8n`

Did I miss something?

LEMP on Ubuntu 18.04
node v8.10.0
npm 3.5.2

**Comment by janober** [comment]
Uh your node/npm versions look quite old. They could be the problem. n8n got always tested with v10+.

Please try updating them. Hope that fixes your problem.

**Comment by arnaudknobloch** [comment]
After updating node (12.10), it works, thank you.

**Comment by janober** [comment]
Ah great to hear! 

If you have further problems simply post them to:
http://community.n8n.io

I try then to get back to you asap.

**Comment by RosemaryOrchard** [comment]
Would it be helpful to have n8n check the current node version before anything else and then fail with an error message that the node version is too old? I ran into this same error today :)

**Comment by janober** [comment]
@RosemaryOrchard that is a great idea. Did add it and will be released with the next version.
https://github.com/n8n-io/n8n/commit/a2b589880ff52b117601254de78f36084d6de647
