### ISSUE TITLE
Cannot activate workflow with Stripe webhook trigger

### ISSUE THREAD

**Issue by despens** [n8n-io/n8n#5205]
When using a Stripe webhook trigger node, the workflow cannot be activated. Instead, the error message "Workflow could not be activated: Bad request - please check your parameters" is shown.

**To Reproduce**

1. Create a new workflow
3. Create a Stripe webhook trigger
4. Save 
5. Try to activate the workflow

**Expected behavior**
The workflow should be activated, or a reason given why it is not activated.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04, running n8n via docker behind nginx reverse proxy
- n8n Version n8nio/n8n:0.212.0
- Database system: Postgresql 14
- Operation mode `own`

**Additional context**
No log message visible in docker logs.
The PATCH request to  https://n8n.mydomain.org/rest/workflows/10 returns a 400 error with just the message "Bad request - please check your parameters".

**Comment by Joffcom** [comment]
Hey @despens 

Is this related to the url being localhost?

**Comment by despens** [comment]
It might be… since it is impossible to set a working webhook URL for Stripe behind a reverse proxy maybe it is blocked?
→ #5204

**Comment by Joffcom** [comment]
Hey @despens,

That will likely be it then, If your webhook url is localhost it should fail to activate as there would be no way for the webhook to reach you.

For now I am going to mark this one as closed and we can focus on the other issue as they are likely related.
