### ISSUE TITLE
ERROR: Failed to extend syntax

### ISSUE THREAD

**Issue by rfehling-mittwald** [n8n-io/n8n#5209]
We updated to the newest n8n version v0.212.0, and our already existing workflows are crashing.

**ERROR: Failed to extend syntax**

Create a code node with just an empty list and use an expression with "?". This will crash, but did not crash in 0.210.

Easiest Example that exists:

Code Node Once Each Item:
```
return {
  json: {
    test: [],
  }
}
```

If Node :boom: :
`{{$json["test"]?.length >0}}`

If this is not a bug, do we have to to manual type checks like?:
`{{$json["test"] !== undefined && $json["test"].length >0}}`

We may overused the expression function in the past :sweat_smile:

**Comment by Joffcom** [comment]
Hey @rfehling-mittwald,

Thanks for reporting this one, We already have this one logged internally and we are tracking it as `PAY-105`.

**Comment by ivov** [comment]
Should be addressed by https://github.com/n8n-io/n8n/pull/5219

**Comment by janober** [comment]
Fix got released with `n8n@0.212.1`
