### ISSUE TITLE
Broken `DeleteExecutionsWithWorkflows` migration

### ISSUE THREAD

**Issue by ifokeev** [n8n-io/n8n#5212]
Bug not fixed, so reopen the issue.
Same situation as described in https://github.com/n8n-io/n8n/issues/5183 while migrating to 0.212.0 from 0.210.0.

<img width="815" alt="Screen Shot 2023-01-21 at 10 51 52" src="https://user-images.githubusercontent.com/2017148/213845900-6578be06-6287-41a7-b31d-8b08903fd611.png">

After checking the codebase, it looks like `DB_POSTGRESDB_SCHEMA` https://github.com/n8n-io/n8n/blob/9b032d68bc8a7a45aae73e9442315e872902d50a/packages/cli/src/config/schema.ts#L100 is not used anymore? 

I'm using a specified schema for n8n, but I don't see that migrations are executed in this scope.

All new migrations are not specifying the schema as here: 
https://github.com/n8n-io/n8n/blob/0da338f9b5f850b25e97383ae1f4cec8d0e4c17b/packages/cli/src/databases/migrations/postgresdb/1658932090381-AddNodeIds.ts#L13-L16

For example:
https://github.com/n8n-io/n8n/blob/master/packages/cli/src/databases/migrations/postgresdb/1673268682475-DeleteExecutionsWithWorkflows.ts

I see there is a function `getTablePrefix`, but it's not used everywhere:
https://github.com/n8n-io/n8n/blob/0da338f9b5f850b25e97383ae1f4cec8d0e4c17b/packages/cli/src/databases/migrations/postgresdb/1669823906995-AddTriggerCountColumn.ts#L11

It looks like all new migrations should use this function

Environment:
* n8n Version 0.210.0

**Comment by Joffcom** [comment]
Hey @ifokeev 

Thanks for reporting this one, will get a fix in place shortly for the next release.

**Comment by krynble** [comment]
We plan on releasing a hotfix today, the fix can be seen here: https://github.com/n8n-io/n8n/pull/5218

**Comment by ifokeev** [comment]
Hi @krynble!
Thanks for the fix, but the same code
```
 const tablePrefix = getTablePrefix(); 
 ```
 
 should be in every migration, not only in this one

**Comment by krynble** [comment]
Good point @ifokeev, added the others too.

**Comment by janober** [comment]
Fix got released with `n8n@0.212.1`

**Comment by Joffcom** [comment]
Hey @ifokeev,

As this is resolved I am going to close this issue, We will also be updating all of the older migrations to use the newer approach to keep things consistent.

Thanks again for reporting this.
