### ISSUE TITLE
HTTP Request Node: Ignore empty response body for auto detect json

### ISSUE THREAD

**Issue by feelgood-interface** [n8n-io/n8n#5214]
**Describe the bug**
Some APIs return an empty body (and not a JSON object), even though the _content-type_ is specified as _application/json_. This causes the HTTP Request  node to fail when calling `jsonParse()`. One has to manually set the response format to text as to not cause workflow errors.

**To Reproduce**
Empty string/buffer as response body.

**Expected behavior**
Node should return empty body and not fail for empty response bodies.

**Environment (please complete the following information):**
- n8n Version 0.212.0

**Comment by Joffcom** [comment]
Hey @feelgood-interface 

Sounds like a good thing to fix to me, If it helps in the future we don't need an issue and a PR just the PR would do the job with a little note in it or a comment 🙂

I will get the PR added to the internal review list.

**Comment by Joffcom** [comment]
Should have closed this sooner, The PR was merged :)
