### ISSUE TITLE
External Backend Hook not working properly

### ISSUE THREAD

**Issue by maurimuchico-work** [n8n-io/n8n#5234]
**Describe the bug**
When updating from 0.200.0 to 0.201.0 or further an error thrown from a workflow.activate backend hook renders as 
![image](https://user-images.githubusercontent.com/123373946/214140705-7d130231-0978-4b94-b60c-2d8f35719edf.png)
I tried updating to 0.202.1 and later versions as mentioned here: https://community.n8n.io/t/workflow-could-not-be-activated/19621/7 with no luck.

**To Reproduce**
1. Develop a workflow.activate backend hook as explained here https://docs.n8n.io/embed/configuration/#hook-files
2. Register n8n hook using the environment variable EXTERNAL_HOOK_FILES
3. Try to activate more than two flows
4. The "No entity column hash was found n8n" is thrown instead of the custom message

**Expected behavior**
When trying to activate more than one flow this message should be displayed: "Active workflow limit reached."

**Environment**External Backend Hook not working properly
OS: Ubuntu 20.04.5
n8n: 0.201.0
Node.js: 16.19.0
Database: sqlite
Operation mode: main

**Comment by Joffcom** [comment]
Hey @maurimuchico-work,

Can you share the backend hook you are using?

**Comment by Joffcom** [comment]
Hey @maurimuchico-work,

I guess as it is solved this one could be closed then. It could be related to the other issue although it looks like the other issue is different but you seem to have a few different issues going on that could be related to how you are using n8n. Just seen the message about the packages which I think has been posted about on the community support forum as well, Possibly by you?

I will close this one for now and we can check the other one next.
