### ISSUE TITLE
helpscout node does not respect tag filter

### ISSUE THREAD

**Issue by bamboowonder** [n8n-io/n8n#5236]
with helpscout node, I do a getall on conversations:   https://api.helpscout.net/v2/conversations?status=closed&tag=imported%20from%20gmail%20inbox&sortField=createdAt&sortOrder=asc

however, n8n does not respect the "tag" filter.   When I reproduce this in something like insomnia, the filter works correctly.

it does not matter what tag I choose in n8n, the result is the same.  It effectively ignores tag filter.

However, when I do the raw api call with an Http Request node, the filter works correctly.  I seems this is a bug in the specific Helpscout node.

- OS: [Ubuntu Linux 22.04]
- n8n Version [e.g. 0.212.0]
latest Docker install
- Database system [e.g. postgres 15]
- Operation mode [default]

Helpscout node:
{
  "meta": {
    "instanceId": "xxx"
  },
  "nodes": [
    {
      "parameters": {
        "operation": "getAll",
        "limit": "={{ $json[\"interval\"] }}",
        "options": {
          "sortField": "createdAt",
          "sortOrder": "asc",
          "status": "closed",
          "tags": [
            "imported from gmail"
          ]
        }
      },
      "id": "70761f26-ccd2-42d9-97e9-69dd418f69d9",
      "name": "get conversations",
      "type": "n8n-nodes-base.helpScout",
      "typeVersion": 1,
      "position": [
        600,
        680
      ],
      "alwaysOutputData": true,
      "credentials": {
        "helpScoutOAuth2Api": {
          "id": "18",
          "name": "HelpScout account"
        }
      },
      "continueOnFail": true
    }
  ],
  "connections": {}
}

http request node:
{
  "meta": {
    "instanceId": "xxx"
  },
  "nodes": [
    {
      "parameters": {
        "url": "https://api.helpscout.net/v2/conversations",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "helpScoutOAuth2Api",
        "sendQuery": true,
        "queryParameters": {
          "parameters": [
            {
              "name": "status",
              "value": "closed"
            },
            {
              "name": "tag",
              "value": "imported from gmail inbox"
            },
            {
              "name": "sortField",
              "value": "createdAt"
            },
            {
              "name": "sortOrder",
              "value": "asc"
            }
          ]
        },
        "options": {}
      },
      "id": "3d2b1e85-3650-4a50-b353-bd07bc09d6dc",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        520,
        160
      ],
      "credentials": {
        "helpScoutOAuth2Api": {
          "id": "18",
          "name": "HelpScout account"
        }
      }
    }
  ],
  "connections": {}
}

**Comment by Joffcom** [comment]
Hey @bamboowonder,

Thanks for reporting this one, Internally we are tracking this as `NODE-207`. I have also popped in a quick PR that will resolve this issue.

**Comment by Joffcom** [comment]
Hey @bamboowonder,

Looks like this was solved in the `0.213.0` release, I am going to get this one closed for now. If you do still have this issue let me know and we can open this again.
