### ISSUE TITLE
Odoo node credentials can't connect to instances that have more than one database 

### ISSUE THREAD

**Issue by Lanhild** [n8n-io/n8n#5275]
Even when specifying the correct database name, the Odoo node credentials returns a 404 when the instance has multiple databases

**Comment by Joffcom** [comment]
Hey @Lanhild 

Can you fill out the template we provide, it saves us having to ask what error you are seeing and what version you running.

**Comment by Lanhild** [comment]
![image](https://user-images.githubusercontent.com/73610779/215125582-296508fb-6087-4bda-ac0d-856d98b9310c.png)

```
Settings are not valid: StatusCodeError: 404 - {"jsonrpc":"2.0","id":70,"error":{"code":404,"message":"404: Not Found","data":{"name":"werkzeug.exceptions.NotFound","debug":"Traceback (most recent call last):\n File \"/usr/local/lib/python3.8/site-packages/odoo/http.py\", line 1486, in _dispatch_nodb\n func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()\n File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 1799, in match\n raise NotFound()\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File \"/usr/local/lib/python3.8/site-packages/odoo/http.py\", line 639, in _handle_exception\n return super(JsonRequest, self)._handle_exception(exception)\n File \"/usr/local/lib/python3.8/site-packages/odoo/http.py\", line 315, in _handle_exception\n raise exception.with_traceback(None) from new_cause\nwerkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\n","message":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","arguments":[],"context":{}},"http_status":404}}
```
>If you ignore the credential error does the node still work?

No.

Version 0.212.1

**Comment by sutidor** [comment]
you might want to try [@digital-boss/n8n-nodes-odoo](https://www.npmjs.com/package/@digital-boss/n8n-nodes-odoo)

**Comment by Lanhild** [comment]
Any updates on when this might be a supported? 
It's a struggle to not be able to connect to instances that have more than one DB.

**Comment by Joffcom** [comment]
Hey @Lanhild 

I had forgotten about this one will get the internal ticket created on Monday to get this resolved in a future release.

**Comment by Lanhild** [comment]
Thanks, please keep us updated

**Comment by Lanhild** [comment]
Hey @Joffcom 

Any chance I could add documentation to that internal ticket? I know the exact reason for this issue, and it's mostly because of how Odoo ORM layer works.

There are essentially 2 different APIs in Odoo. The web services API, using the `/jsonrpc` endpoint (the one used in the Odoo node) and the `/xmlrpc` endpoint. The latter is the one that supports connections to instances that ship more than one DB. 

Now, to fix this issue, the Odoo node would need to be a bit overhauled. In the Odoo node code, requests to the `/jsonrpc` endpoint should be made using the xmlrpc lib and parameters to work properly. This implies that not only the endpoint and methods have to be changed, but also the code structure. 

I'll link documentation pages from Odoo about the xmlrpc lib and API that explain how to interact with an instance using that DB. (Please note that even if there are different versions of Odoo, the ORM layer hasn't changed in more than 10 years. This means that on the level of the API, compatibility with older versions shouldn't be a problem)

- https://www.odoo.com/documentation/14.0/developer/reference/external_api.html
- [This node package can be used as a reference point to understand Odoo API mechanics](https://www.npmjs.com/package/odoo-xmlrpc)

**Comment by Joffcom** [comment]
Hey @Lanhild

I can get that added to it, at the moment this has a fairly low priority when compared to other issues so will likely take a while to be resolved.

I have not checked to see if there is an existing PR to resolve this from the community though.

**Comment by Lanhild** [comment]
Hey @Joffcom 

Coming back on this one. 

Internally, we found out that the issue was related to an undocumented problem on the side of Odoo. We finally solved it by adding the `base` module to the `server_wide_modules` param in `odoo.conf`. 

This issue can therefore be closed as it is not related to n8n and specific to an Odoo server configuration.
