### ISSUE TITLE
431 with the Notion integration

### ISSUE THREAD

**Issue by sweenu** [n8n-io/n8n#5280]
**Describe the bug**
After adding a certain number of properties, the uri of the GET request becomes too long when fetching available values for the properties, resulting in a large header request exceeding the size limit.

**To Reproduce**

1. Add a Notion node to a workflow with a "database page" resource and "create" operation.
2. Add properties until the header request exceeds 4kb (for some reason, it's not 8kb for me)
3. You should now get 431 errors

**Environment (please complete the following information):**

- OS: docker
- n8n Version: 0.212.1
- Node.js Version: Whatever the docker image has
- Database system: SQLite
- Operation mode: own

**Additional context**
I have seen [this issue](https://github.com/n8n-io/n8n/issues/466) and hesitated commenting there instead of creating an issue, but this does not seem to be an edge case and seems to be too easily reproducible. It seems like a fix should be made for the notion integration. If not, I would love to know how I can increase the size limit when using docker because adding `command: /bin/node --max-http-header-size=65536 bin/n8n start` does not work as it is not how n8n is launched with docker, there is no `/bin/{node,n8n}`.

**Comment by Joffcom** [comment]
Hey @sweenu,

Have you tried using `/usr/local/bin/node --max-http-header-size=65536 /usr/local/bin/n8n start` to see if that helps or maybe just `node --max-http-header-size=65536 n8n start`

**Comment by sweenu** [comment]
Sorry for my late answer. With `/usr/local/bin/node --max-http-header-size=65536 /usr/local/bin/n8n start` as the docker command, n8n will run normally, however I'm still having the 431, even though the request header is only about 4 kB.
The request url, starting with `GET /rest/node-parameter-options?nodeTypeAndVersion=%7B%22name%22...` is what takes so much space, it's super long request for some reason.

In any case, `--max-http-header-size` does not seem to be taken into account for some reason 🤔

**Comment by sweenu** [comment]
I realize the problem might be on Traefik's side: https://github.com/traefik/traefik/issues/8846

**Comment by sweenu** [comment]
The problem was actually with Authelia. The fix was to add :
```yaml
server:
  buffers:
    read: 16384
```
To Authelia's config.
