### ISSUE TITLE
pnpm build report error

### ISSUE THREAD

**Issue by bjdaijun** [n8n-io/n8n#5281]
**Describe the bug**
pnpm build returned error

**To Reproduce**

1.git clone latest n8n 
2. pnpm install
3. pnpm build

**Expected behavior**
`
turbo run build
• Packages in scope: @n8n_io/eslint-config, n8n, n8n-core, n8n-design-system, n8n-editor-ui, n8n-node-dev, n8n-nodes-base, n8n-workflow
• Running build in 8 packages
• Remote caching disabled
n8n-design-system:build: Failed to check if we can skip restoring outputs for n8n-design-system#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/9.cookie: no space left on device. Proceeding to check cache
n8n-workflow:build: Failed to check if we can skip restoring outputs for n8n-workflow#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/9.cookie: no space left on device. Proceeding to check cache
n8n-design-system:build: cache miss, executing 15301ed64ac06678
n8n-workflow:build: cache miss, executing b8b9d5a5eaf7af9e
n8n-workflow:build:
n8n-workflow:build: > n8n-workflow@0.134.0 build /data/projects/git/HaiYang/n8n/packages/workflow
n8n-workflow:build: > tsc -p tsconfig.build.json
n8n-workflow:build:
n8n-design-system:build:
n8n-design-system:build: > n8n-design-system@0.52.0 build /data/projects/git/HaiYang/n8n/packages/design-system
n8n-design-system:build: > vite build
n8n-design-system:build:
n8n-design-system:build: vite v4.0.4 building for production...
n8n-design-system:build: transforming...
n8n-workflow:build: Failed to mark outputs as cached for n8n-workflow#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/11.cookie: no space left on device
n8n-core:build: Failed to check if we can skip restoring outputs for n8n-core#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/12.cookie: no space left on device. Proceeding to check cache
n8n-core:build: cache miss, executing 1e09b88fea695520
n8n-core:build:
n8n-core:build: > n8n-core@0.152.0 build /data/projects/git/HaiYang/n8n/packages/core
n8n-core:build: > tsc -p tsconfig.build.json
n8n-core:build:
n8n-core:build: Failed to mark outputs as cached for n8n-core#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/13.cookie: no space left on device
n8n-node-dev:build: Failed to check if we can skip restoring outputs for n8n-node-dev#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/14.cookie: no space left on device. Proceeding to check cache
n8n-node-dev:build: cache miss, executing 0e71d0022f3f1d53
n8n-nodes-base:build: Failed to check if we can skip restoring outputs for n8n-nodes-base#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/14.cookie: no space left on device. Proceeding to check cache
n8n-nodes-base:build: cache miss, executing 4a5b5295ae99017e
n8n-node-dev:build:
n8n-node-dev:build: > n8n-node-dev@0.91.0 build /data/projects/git/HaiYang/n8n/packages/node-dev
n8n-node-dev:build: > tsc --noEmit
n8n-node-dev:build:
n8n-nodes-base:build:
n8n-nodes-base:build: > n8n-nodes-base@0.211.0 build /data/projects/git/HaiYang/n8n/packages/nodes-base
n8n-nodes-base:build: > tsc && gulp build:icons && gulp build:translations && pnpm build:metadata
n8n-nodes-base:build:
n8n-nodes-base:build: node:internal/modules/cjs/loader:998
n8n-nodes-base:build:   throw err;
n8n-nodes-base:build:   ^
n8n-nodes-base:build:
n8n-nodes-base:build: Error: Cannot find module '/data/projects/git/HaiYang/n8n/node_modules/.pnpm/registry.npmmirror.com+typescript@4.8.4/node_modules/typescript/bin/tsc'
n8n-nodes-base:build:     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
n8n-nodes-base:build:     at Module._load (node:internal/modules/cjs/loader:841:27)
n8n-nodes-base:build:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
n8n-nodes-base:build:     at node:internal/main/run_main_module:23:47 {
n8n-nodes-base:build:   code: 'MODULE_NOT_FOUND',
n8n-nodes-base:build:   requireStack: []
n8n-nodes-base:build: }
n8n-nodes-base:build:
n8n-nodes-base:build: Node.js v18.12.0
n8n-nodes-base:build:  ELIFECYCLE  Command failed with exit code 1.
n8n-nodes-base:build: ERROR: command finished with error: command (/data/projects/git/HaiYang/n8n/packages/nodes-base) pnpm run build exited (1)
n8n-node-dev:build:  ELIFECYCLE  Command failed.
n8n-design-system:build:  ELIFECYCLE  Command failed.
n8n-editor-ui:build: Failed to check if we can skip restoring outputs for n8n-editor-ui#build: rpc error: code = Unknown desc = failed adding watch to /home/daijun/.local/share/turborepo/cookies/9ce774ce0eba5743/16.cookie: no space left on device. Proceeding to check cache
n8n-editor-ui:build: cache miss, executing 6888ea5511d88b73
command (/data/projects/git/HaiYang/n8n/packages/nodes-base) pnpm run build exited (1)

 Tasks:    2 successful, 3 total
Cached:    0 cached, 3 total
  Time:    3.762s

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
`
**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.213.0
- Node.js Version v8.12.0
- Database system SQLite
- Operation mode own
**Additional context**
As the log says , no space on device, but df -h shows there are spaces.

![image](https://user-images.githubusercontent.com/1940592/215298845-a2895374-cfb6-4427-8fc1-660595574e65.png)

**Comment by netroy** [comment]
@bjdaijun it likely that there are deleted files on `/dev/vda1`, but some process is still holding references to them, preventing the OS from reusing that disk space.
Can you please try restarting the machine?

**Comment by Joffcom** [comment]
I am going to mark this one as closed as it doesn't appear to be a bug with n8n, If you are still seeing this issue let us know and we can have a chat about this to see if the issue needs to be opened again or not.
