### ISSUE TITLE
Pasting doesn't allow the undo functionality in expression fields or code nodes at first.

### ISSUE THREAD

**Issue by mprytoluk** [n8n-io/n8n#5297]
**Describe the bug**
If the first interaction with any expression field on any node, or the main field on a Code node (i.e. any field that accepts javascript) is a "Ctrl + V" (or right click -> Paste), this doesn't seem to trigger the "Undo" functionality, meaning you can't "Ctrl + Z" if your first action in one of those field is a "Ctrl + V".

If directly after a "Ctrl+V" you write anything, you can now Undo your previous actions, even the paste action.

**To Reproduce**

1. Open a "Code" node or an "Expression" field in any node.
2. Immediately past something, without writing anything before
3. Try to Undo
4. Undo action is not available
5. Write anything
6. Undo action is available!

**Expected behavior**
Undo action should be available even if pasting is your first action in said nodes

**Environment (please complete the following information):**

- Ubuntu Linux 22.04
- n8n Version 0.212.1

**Additional context**
This bug doesn't seem to happen on the old Function and FunctionItem nodes.

**Comment by Joffcom** [comment]
Hey @miguel-mconf,

Thanks for reporting this one, I have created an internal ticket which we are tracking as `N8N-6082`.
