### ISSUE TITLE
The credential node with authenticate doesn't follow the interface for requestOptions

### ISSUE THREAD

**Issue by ladislavstefan** [n8n-io/n8n#5317]
Hi,
I have a custom credential node for adding an authentication header. `authenticate` method receives `credentials` and `requestOptions`. Unfortunately,  `requestOptions` data isn't aligned with `IHttpRequestOptions` interface, and instead of `url` there is `uri`.

interface [link](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/Interfaces.ts#L492):
```
export interface IHttpRequestOptions {
	url: string;
	baseURL?: string;
        ...
}        
```
dump of `requestOptions`:
```
{ 
   "headers": {  .. }, 
   "method": "POST", 
   "uri": "https://someurl/test", 
   "gzip": true, 
   "rejectUnauthorized": true, 
   "followRedirect": false, 
   "resolveWithFullResponse": true, 
   "timeout": 3600000, 
   "body": {  ...json body... },
   "encoding": null, 
   "json": false
}
```

simplified example: 

```
export class ApiToken implements ICredentialType {
  name = 'apiToken'
  displayName = 'API Token'

  properties: INodeProperties[] = [
    {
      displayName: 'Secret Key',
      name: 'secretKey',
      type: 'string',
      default: '',
      typeOptions: {
        password: true,
      },
    },
  ]

  authenticate = (
     credentials: ICredentialDataDecryptedObject,
     requestOptions: IHttpRequestOptions,
   ): Promise<IHttpRequestOptions> => {
      const endPointUrl = new URL(requestOptions.url)
      const token = // ... some other magic

      return {
         ...requestOptions,
         headers: {
             ...requestOptions.headers,
            Authorization: `Bearer ${token}`,
         }
      }
  }

}

```

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.213.0, workflow version for development: 0.134.0
- Node.js Version: 16.18.0
- Database system: postgres
- Operation mode: own

**Comment by Joffcom** [comment]
Hey @ladislavstefan,

Are you seeing an error at all? I am not sure that this is actually a bug with n8n which is what we use the Github issues for.

**Comment by ladislavstefan** [comment]
Hi @Joffcom,
for testing purposes, I have just one HTTP request node with this credential set and the node fails. 
If I change `requestOptions.url` to `requestOptions.uri` in the credential node code, it starts working.

Error:
```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.execute (/home/stefi/0_opt/git/n8n/node_modules/n8n-nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts:1312:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Workflow.runNode (/home/stefi/0_opt/git/n8n/node_modules/n8n-workflow/src/Workflow.ts:1270:19)
    at /home/stefi/0_opt/git/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:938:29    
 ```
 
 and reported cause:
 
 ```
 {
  "status": "rejected",
  "reason": {
    "context": {},
    "name": "NodeApiError",
    "timestamp": 1675245317879,
    "node": {
      "parameters": {
        "curlImport": "",
        "method": "POST",
        "url": "https://sometesturl.com/test",
        "authentication": "predefinedCredentialType",
        "nodeCredentialType": "apiToken",
        "sendQuery": false,
        "sendHeaders": false,
        "sendBody": true,
        "contentType": "json",
        "specifyBody": "json",
        "jsonBody": "{ ... json body... }",
        "options": {}
      },
      "id": "2c93d0c8-af44-4f9a-b4e0-7d1c690d3c49",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        1620,
        740
      ],
      "alwaysOutputData": false,
      "credentials": {
        "apiToken": {
          "id": "4",
          "name": "Token account"
        }
      }
    },
    "httpCode": "ERR_INVALID_URL",
    "description": "Invalid URL"
  }
}
 ```

**Comment by Joffcom** [comment]
Hey @ladislavstefan,

What happens if you use something like the below? Normally you wouldn't need to return the rest of the requestOptions only what you are setting for the authentication as the node handles the rest in `requestWithAuthentication()`

```
authenticate = (
     credentials: ICredentialDataDecryptedObject,
     requestOptions: IHttpRequestOptions,
   ): Promise<IHttpRequestOptions> => {
      const endPointUrl = new URL(requestOptions.url)
      const token = // ... some other magic

      return {
         headers: {
             ...requestOptions.headers,
            Authorization: `Bearer ${token}`,
         }
      }
  }
```

**Comment by ladislavstefan** [comment]
Hi @Joffcom,
with your version of code it fails with `ERR_INVALID_URL`. It is the same result as I described above.

If I use `.uri` instead it fails with `ERR_INVALID_ARG_TYPE`.

Transpiled js code:
```
authenticate = async (credentials, requestOptions) => {
    const endPointUrl = new URL(requestOptions.uri);

    const token = // ... some other magic

    return {
        headers: {
            ...requestOptions.headers,
            Authorization: `Bearer ${token}`,
        },
    };
};
```  
Error:
```
{
"status":"rejected",
"reason":{
"context":{
},
"name":"NodeApiError",
"timestamp":1675331075153,
"node":{
"parameters":{...}, // 12 items
"id":"2c93d0c8-af44-4f9a-b4e0-7d1c690d3c49",
"name":"HTTP Request",
"type":"n8n-nodes-base.httpRequest",
"typeVersion":3,
"position":[...], // 2 items
"alwaysOutputData":false,
"credentials":{...} // 1 items
},
"httpCode":"ERR_INVALID_ARG_TYPE",
"description":"The "url" argument must be of type string. Received undefined"
}
}
```
Thank you for your time!

**Comment by Joffcom** [comment]
Hey @ladislavstefan,

That is very odd, We use the same thing with other credentials and it works. I know we need to do an update at some point to the request helper but I believe it has a fairly low priority as nothing has yet broken because of it.

I guess if you are using the HTTP Request node do you need to set the URL in the credential anyway? I know this doesn't resolve the underlying issue but I am just wondering if you are doing that would change the priority of the issue.

**Comment by ladislavstefan** [comment]
Hi @Joffcom,
I'm OK with this. I have a workaround. I've just wanted to point out this weird behavior.

Btw, I saw similar handling of `requestOptions.url` vs. `requestOptions.uri` in other implementations, i.e.:

`n8n-nodes-base/dist/credentials/CustomerIoApi.credentials.js`
or
`n8n-nodes-base/dist/credentials/MindeeReceiptApi.credentials.js`:
```
const url = requestOptions.url ? requestOptions.url : requestOptions.uri;
```
Anyway, thank you.

**Comment by Joffcom** [comment]
Hey @ladislavstefan,

I remember those ones, I suspect it was the way we worked around it and what led to the tech debt ticket to get this one sorted.

I think for now as we are aware of this and it is not breaking functionality I am going to mark this one as closed, Thanks for taking the time to report this one though 🙌🏻
