### ISSUE TITLE
Failed to extend syntax error on 0.213.0 when using the null coalescing ?? operator

### ISSUE THREAD

**Issue by joshpainter** [n8n-io/n8n#5330]
I'm seeing this error on 0.213.0 when using the null coalescing ?? operator and $now.minus(). Screenshots:

![image](https://user-images.githubusercontent.com/16468670/216209041-52c6d49c-769f-455c-9c6a-9b6755d99197.png)

Ternary operator seems to work fine:

![image](https://user-images.githubusercontent.com/16468670/216209194-75afebc7-5fbb-4f91-8700-7c1f108eff3c.png)

Also see: https://github.com/n8n-io/n8n/issues/5229#issuecomment-1413026072_

**Comment by Joffcom** [comment]
Hey @joshpainter,

Thanks for reporting this, looks like there are a still a couple of cases of this one. We are working on fixing it and I have linked this to our internal ticket which we are tracking as `PAY-105`

**Comment by Joffcom** [comment]
Hey @joshpainter,

This should be resolved in `n8n@0.215.1`, I am going to mark this one as closed and if you are still seeing this issue let me know and we can open it again.
