### ISSUE TITLE
Problem with Error trigger node

### ISSUE THREAD

**Issue by MatyVar** [n8n-io/n8n#5358]
**Describe the bug**

Looking to use the "Error Trigger" and "Stop and Error" nodes to achieve a "catch" I have come across the following problem:

According to the documentation, to achieve a catch, an isolated error handling workflow must be created.

Then the main workflow, which contains the code, must be told from its configuration which is the workflow that will listen to the errors, that is, where will it send the error report once a failure occurs in the flow. You can configure the stop and error node which is used to throw exceptions and send a custom error message.

I understand that the workflow error must contain the trigger error since this node is activated due to the production of an error from the assigned main flow.

In the tests I ran it was by no means possible to get this to work.

I tried placing a main workflow with a webhook (Http GET) and at the output of this node a stop and error node to cause an error and the trigger was not executed.

I tried misconfiguring several nodes to cause an error, the error appears on my n8n screen but the trigger was not executed,
apparently something is missing so that the trigger can be executed and the error handling flow is activated.

**To Reproduce**

In order to reproduce the error:

1. First configure a main flow, placing a Stop and Error node, with its corresponding message and press "save"
2. Then create another flow and name it as "error handling flow" and you must place the "Error trigger" node as the first node, as the second node you can place any other node since the purpose is to test the trigger. In my case I placed a "Set" node.
3. Go back to the main node and in the configuration tab go to properties, and then in the "Error workflow" section you must select the previously created workflow that contains the Error trigger node.
4. Finally, execute the stop and error node within the main workflow.

Following these steps, nothing happens, that is, I don't see any error handling flow execution warning.

**Expected behavior**
Being able to make use of a system for error control using the mentioned nodes.

**Environment**
OS: Ubuntu 20.04.5
n8n: 0.201.0
Node.js: 16.19.0
Database: sqlite
Operation mode: main

**Comment by janober** [comment]
From what I am reading above, is that potentially expected behavior. Error workflows do only get executed for production executions. Do you execute the workflow that throws an error manually or in production mode?

**Comment by janober** [comment]
Just looked in the docs. There we do not call it in "production" but rather write "automatically:
https://docs.n8n.io/courses/level-two/chapter-4/#catching-erroring-workflows
![Screenshot from 2023-02-03 14-30-16](https://user-images.githubusercontent.com/6249596/216704707-2e421b4f-2539-434d-ab76-5a77b4347a6a.png)

**Comment by MatyVar** [comment]
Hi! @janober ! how are you? 
Thanks for the feedback, 
I will tell you about the tests I have carried out:

1.First I triggered a webhook , (GET) in production mode and triggered the flow.
2.I wired a "stop and error" node to the output of the "WebHook" node.
3.I executed the production url through POSTMAN, to validate if the error handling flow was executed, but nothing happens

Could I be doing something wrong or am I missing a step?

Greetings!

**Comment by janober** [comment]
Thanks a lot. I just tested and created a totally new workflow that errors and a new error workflow. Works totally fine and as expected.

Are you sure that the Error Workflow is set on the workflow that fails? Did you maybe set it and then you did not press "Save"? So if you open the workflow and then the settings it does get displayed as selected?

Do you save successful executions of the Error Workflow? So maybe it executes and you just do not know it.

**Comment by MatyVar** [comment]
@janober  Thank you so much! The problem was that I was not seeing correctly where the execution notification of the error flow came from. Currently I can see it in workflow executions..

**Comment by Joffcom** [comment]
I am going to mark this as closed as it looks to be resolved, If this is still an issue can you open a post on our community support forum: https://community.n8n.io and we can pick it back up from there 👍🏻
