### ISSUE TITLE
SERIOUS bug in UI 0.214.0 - Node connections are not saved

### ISSUE THREAD

**Issue by ed-parsadanyan** [n8n-io/n8n#5359]
**Describe the bug**
In the n8n Docker version 0.214.0 node connections are not saved. Check the webm video attached

**To Reproduce**

1. Create new workflow
3. Add a bunch of nodes and try connection them
4. Observe that new connections don't trigger workflow save button
5. On workflow reload all connections are gone

**Expected behavior**
Node connections stay in the workflow after they are added.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.214.0
- Node.js Version NA, run in Docker
- Database system Postgres
- Operation mode main

**Additional context**
[Video](https://drive.google.com/file/d/1zzo62ti-g1mfPaFePJrlJ5GlAKObyw7G/view?usp=sharing)

**Comment by Joffcom** [comment]
Hey @ed-parsadanyan 

Thanks for the report, just tried to view the video but it was still processing.

Out of interest what browser are you using? I made a couple of workflows this morning and didn't run into this issue.

**Comment by ed-parsadanyan** [comment]
> Hey @ed-parsadanyan
> 
> Thanks for the report, just tried to view the video but it was still processing.
> 
> Out of interest what browser are you using? I made a couple of workflows this morning and didn't run into this issue.

Yes, google doesn't show the webm video for some reason. But when you download it then it works.
I'm using Chrome and had to revert to 0.213.0 to fix the issue.

The problem is with a specific way of adding node connections (as shown in the video). When you add a separate node and connect two nodes, **then** it doesn't work.

First, add 2 **separate** nodes:
![vlcsnap-2023-02-04-17h34m48s567](https://user-images.githubusercontent.com/10472129/216778859-086a96e0-9a00-42d9-9ac8-3335d2ef3694.png)

After connecting them nothing happens and "Save" button is not activated.
![vlcsnap-2023-02-04-17h35m07s887](https://user-images.githubusercontent.com/10472129/216778865-a323acf0-a6ab-4b8c-8e66-e15be09f87e2.png)

**Comment by ed-parsadanyan** [comment]
> Hey @ed-parsadanyan
> 
> Thanks for the report, just tried to view the video but it was still processing.
> 
> Out of interest what browser are you using? I made a couple of workflows this morning and didn't run into this issue.

I tried a bit further. Looks like the issue is limited to the Merge Node. Other nodes look fine

**Comment by janober** [comment]
Thanks a lot for that information. I was also wondering. I tried to reproduce this bug earlier but was totally unable to. Then I tried to build a workflow a few hours afterward regularly, and then I also ran into that issue. It was also with the Merge-Node.
We will release a bug-fix version on Monday with a fix.

**Comment by janober** [comment]
Fix got released with `n8n@0.214.1`
