### ISSUE TITLE
How can I install n8n with Plesk obsidian 18 ? 

### ISSUE THREAD

**Issue by zmayyem** [n8n-io/n8n#537]
Hello Dear , Please I need your help to make n8n run on a subdomain managed by Plesk Obsidian
I Folowed this documentation https://github.com/n8n-io/n8n/issues/9#issuecomment-522746909
But unfortonly it did not work with me , I dont know if I did a mistake or no so i will tell you
what I did exactly and I hope you help to resolve the problem please!

So I started from scratch by creating new VPS on Digitalocean.

**1)** I start by creating fresh Droplet (Debian 9 64bit).

**2)** I Installed New Plesk Obsidian 18.0 on the VPS. (Via SSH)

**3)** I added the main Domain (besthotelguides.com).  

**4)** I Created subdomain (n8n.besthotelguides.com).

**5)** I Installed SSL on both Main Domain and Subdomain.

**6)** I Installed Nodejs from (Plesk tools->update->Add New Component).
**Plesk 18 Already have the NodeJs v 12.4.0 Like used on the documentation of @sutidor**

**7)** I disabled PHP & FastCGI of the subdomain (n8n.besthotelguides.com.com)
 from the subdomain Hosting Setting.

**8)** I created New MySql Database n8n (I pass the PostgreSql Installation because I try 5 Time 
installing it and no Result , So I decide in the last try to use MySql, because I read that lastest version of n8n is compatible with MAriaDB/MySql)

**9)** Via SSH  and folowing your documentation

**9.1)** `cd /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/`

**9.2)**  `npm init --yes`
here i got an error **(-bash: npm: command not found)**
So I fix it By Installing npm with those commands:
**9.2.1)** `curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`
**9.2.2)** `apt-get update && sudo apt-get install yarn`
**9.2.3)** `apt-get install nodejs npm`
**9.2.4)** ` npm -v`  and  the result is  6.14.4. so here **npm** is installed.

Backing to the step **9.2**  executing the command  `npm init --yes` and the result is : 

```
{
  "name": "n8n.example.com",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}
```

**9.3)**  ` npm install n8n`
After excuting this command this is the result

```
`npm WARN deprecated pg-promise@9.3.6: This version of pg-promise is obsolete. You should update to a newer version.

> mmmagic@0.5.3 install /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/mmmagic
> node-gyp rebuild

make: Entering directory '/var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/mmmagic/build'
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apprentice.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/apptype.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/ascmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/cdf_time.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/compress.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/der.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/encoding.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fsmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/funcs.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/is_tar.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/magic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/print.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readcdf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/readelf.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/softmagic.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/fmtcheck.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcat.o
  CC(target) Release/obj.target/libmagic/deps/libmagic/src/strlcpy.o
  AR(target) Release/obj.target/deps/libmagic/magic.a
  COPY Release/magic.a
  CXX(target) Release/obj.target/magic/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/magic.node
  COPY Release/magic.node
make: Leaving directory '/var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/mmmagic/build'

> sqlite3@4.2.0 install /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[sqlite3] Success: "/var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN request-promise-native@1.0.8 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.3 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN n8n.besthotelguides.com@1.0.0 No description
npm WARN n8n.besthotelguides.com@1.0.0 No repository field.

+ n8n@0.64.0
added 510 packages from 707 contributors and audited 1292 packages in 47.133s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities`
```
**9.4)** executing the command `npm install sqlite3 --save`
and this is the result of this command 

```
> sqlite3@4.2.0 install /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[sqlite3] Success: "/var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote
npm WARN request-promise-core@1.1.3 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.8 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN n8n.besthotelguides.com@1.0.0 No description
npm WARN n8n.besthotelguides.com@1.0.0 No repository field.

+ sqlite3@4.2.0
updated 1 package and audited 1389 packages in 6.606s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
**9.5)** **Fixing Permession**
**9.5.1)** to see permessions I executed  the command : `cd /var/www/vhosts/besthotelguides.com/` then the command `ls -l `and the result is 

```
total 16
drwxr-xr-x 2 kais psacln  4096 Apr 28 21:28 error_docs
drwxr-x--- 3 kais psaserv 4096 Apr 28 21:29 httpdocs
drwx------ 3 kais root    4096 Apr 28 22:21 logs
drwxr-x--- 3 kais psaserv 4096 Apr 28 23:57 n8n.besthotelguides.com
```

**9.5.2)** executing the command : `chown kais:psacln -R /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/`
**9.5.3)** executing the command : `chown kais:psaserv /var/www/vhosts/besthotelguides.com/n8n.besthotelguides.com/`

**10)** **Adjusting NodeJS Setting From Plesk Panel**
From The Plesk Panel this screenshot show how I set configuration

![n8n-nodejs-config](https://user-images.githubusercontent.com/64484195/80551855-317c1700-89c5-11ea-84d0-4bfcd1b2e865.png)

**11** I disabled the Proxy Mode From the Apache/Nginx Configuration

**12** I access to the subdomain url https://n8n.besthotelguides.com
and this is the result on this screenshot 

![n8n-not-accessible](https://user-images.githubusercontent.com/64484195/80552437-e531d680-89c6-11ea-81e6-7902cd6f6742.png)

Ps: I back to check the MySQl Database and I find it empty , I dont know if environnement that
i set it is valid or no, as well I dont know if I miss other commands to start n8n or only 
the Plesk node configuration is satisfisant !!

So , Please **help me** how can I run n8n on a subdomain managed by Plesk Panel.

Thanks in advance .

**Comment by janober** [comment]
Please post your question here: https://community.n8n.io/

As defined in the issue template on Github should an issue here only be created if it is a bug. Thanks!
