### ISSUE TITLE
License for contributed packages?

### ISSUE THREAD

**Issue by hgezim** [n8n-io/n8n#539]
I'm unclear what the license for the externally contributed packages is but it should definitely be open source it's external contributors adding benefit to the community.

Thoughts?

**Comment by janober** [comment]
All contributors have to sign a CLA and so have the same license as everything else. All code in the n8n repository has exactly the same license and is so fair-code licensed but not open-source (the OSI definition of it).

**Comment by hgezim** [comment]
Your CLA grants you right but in no way does it prevent the contributor from licensing the code in such a way to grant others more rights than core n8n does.

**Comment by janober** [comment]
Yes, that is correct.
