### ISSUE TITLE
Running n8n in Azure container images fails from version 0.212.1

### ISSUE THREAD

**Issue by pregress** [n8n-io/n8n#5394]
**Describe the bug**
Try to create an azure container image with the `n8nio/n8n:0.212.1` or later.   `n8nio/n8n:0.212.0` does work
Fails with 

> cli.azure.cli.core.azclierror: (InaccessibleImage) The image 'n8nio/n8n:0.214.2' in container group 'redacted' is not accessible. Please check the image and registry credential.
Code: InaccessibleImage

I also have a support ticket in Azure for this, will update this ticket if its Azure related.

**To Reproduce**

1. Sign in to Azure CLI using: `az login`
2. Execute the following script: `az container create --resource-group TBD --name TBD --image n8nio/n8n:0.214.2 --ports 5678 --debug`

**Expected behavior**
Docker image should run anywhere

**Environment (please complete the following information):**

- n8n Version 0.212.1 and later (previous versions work)
- Database system: Tried with SQLite and Postgress
- Operation mode: own

**Additional context**
n/a

**Comment by Joffcom** [comment]
Hey @pregress,

Where is Azure getting the container from? My initial thought is that this is not an n8n issue and is likely down to the container registry that is being used. If you are using Azure Container registry you might have to push your own image there first.

**Comment by Joffcom** [comment]
The error seems to mention a container group and registry credentials, is there something there that needs to be done?

Are you able to try the image from ghcr.io and see if that helps?

**Comment by pregress** [comment]
Same result (tried with multiple versions)

> ContainerGroupsCreateOrUpdate: containerinstance.ContainerInstanceClient#ContainerGroupsCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InaccessibleImage" Message="The image 'ghcr.io/n8n-io/n8n:latest' in container group 'Redacted' is not accessible. Please check the image and registry credential.

I do think this is something Azure related, because I run Caddy as reverse proxy for HTTPS in the same container group and that always works. 
Azure already confirmed they can reproduce this issue.

Also when I run n8n locally from docker hub or ghcr.io it works fine.

**Comment by pregress** [comment]
@Joffcom got the following info from microsoft. 

> The docker image manifest is required by ACI

And indeed If I try `docker manifest inspect n8nio/n8n:latest` there is no manifest.
But if if try `docker manifest inspect n8nio/n8n:0.201.0` there is.
Is this something than can be solved during the docker image build?

If you have a preview build I can try to confirm if this solves it?

**Comment by netroy** [comment]
@pregress When I run `docker manifest inspect n8nio/n8n:0.216.0`, I'm getting this:
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2568,
         "digest": "sha256:2ff57c63bab66fbb2866eca25e8668c91818567e7a58e5e1094541d36cdbfe32",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2568,
         "digest": "sha256:2cf1bc39552b0e01ea2bdc2a1a71480fb8d84901f21101aade74e7db3842744f",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2568,
         "digest": "sha256:36579aaac5cc1de4c0bd8c90cf8f1a43b7048c4dff163dae6eb3ac16c70a4357",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:ba1e4faf2a8f694ce86576987b825e15f7f86c89fa8599ed9ef14414a708c65a",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:43b19ed7983a8a5882d0f5029d9767874a948316a01e511d1eaa580609e6345f",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:d20f170a2b62d145584e9021f95ade8462f359841bdebe07d352576bbb99fc41",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}

```

Can you try again with one of the newer tags and see if this issue still exists?

**Comment by netroy** [comment]
@pregress I've also pushed a custom image `n8nio/n8n:disable-attestation` that possibly fixes this issue. Can you also please test that and let us know?

**Comment by pregress** [comment]
@netroy I can confirm  `n8nio/n8n:disable-attestation` works on ACI
