### ISSUE TITLE
scheduler does not work with custom node in versions >=205

### ISSUE THREAD

**Issue by sutidor** [n8n-io/n8n#5400]
**Describe the bug**
After version 0.200.5 (we checked 0.205.0 and latest) custom nodes break workflow execution in queue mode. When executing scheduler and then calling the workflow the reason is revealed: "cant find CUSTOM.<whatevernode" - although it is installed on each one (webhook, worker) as well.

**To Reproduce**

1. add scheduler to workflow
2. add custom node (does not even have to be connected)
3. wait for execution
4. see it does not execute (failed) without any error indication
5. instead of calling custom node directly, call other workflow with custom node)
6. see error from workflow execution node

**Expected behavior**
work like versions 0.200.5 and below: Just execute workflows normally

**Environment (please complete the following information):**

- docker official image
- n8n Version >0.205.0
- Database system postgres, mysql tried
- Operation mode queue

**Additional context**
Cron, copied from earlier versions, does not work either.

**Comment by Joffcom** [comment]
Hey @sutidor,

Does this happen with all custom nodes? I use a custom node in a few of my workflows with the schedule node and I have not yet seen this. Does the workflow run when manually triggered from the editor and have you checked the debug output to see if anything is displayed in the docker logs?

**Comment by sutidor** [comment]
Hey @Joffcom, 
we discovered that our Docker Compose was overriding the docker-entrypoint.sh in worker/webhook. The entrypoint specifies the user "node" with which the n8n process was executed - without it it would execute as root. Therefore it did not take into account the /home/node/.n8n directory (in favor of /root/.n8n). This means it didnt use the custom nodes and the scheduler failed.

Since it is not a bug but a misconfiguration, I close.
