### ISSUE TITLE
Error messages extending beyond screen

### ISSUE THREAD

**Issue by petersaunderss** [n8n-io/n8n#5418]
**Describe the bug**

**To Reproduce**

1. Create a workflow
2. Give it multiple nodes with errors
3. Execute
4. See too many errors

**Expected behavior**
Can scroll through or dismiss errors.

**Environment (please complete the following information):**
- OS: [macOS 13.2]
- n8n Version [web]

**Additional context**
<img width="390" alt="Screenshot 2023-02-08 at 11 38 45 AM" src="https://user-images.githubusercontent.com/115567836/217596953-e39a64c7-08a5-4864-87df-aac651ffe1a7.png">

**Comment by Joffcom** [comment]
Hey @petersaunderss,

That is an interesting one, Thanks for reporting it 👍🏻 . I have created an internal ticket so that this can be looked into which we will be tracking as `N8N-6137`

**Comment by Joffcom** [comment]
Hey @petersaunderss,

A fix for this has been merged and will be available in the next release of n8n, I will mark this as closed and once the release is available someone will be back to drop a message on here to let you and anyone else interested know which version has the fix.

**Comment by janober** [comment]
Fix got released with [`n8n@0.221.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.221.2)
