### ISSUE TITLE
Import Workflow from URL

### ISSUE THREAD

**Issue by JabSYsEmb** [n8n-io/n8n#5421]
I do believe there is something wrong with importing a workflow from URL since whatever URL I am entering I got an 'invalid URL' error.

I did check the documentation I didn't find any example about this issue or if there is a specific valid URI!

I have a web server that serves a workflow as JSON file, I tried to import the workflow as a file it worked but the n8n isn't obtaining the JSON from the URL.

I have both n8n and web server running locally on my machine.

![Recording 2023-02-09 at 00 29 44](https://user-images.githubusercontent.com/32222578/217655251-2da06db7-06b0-461c-baf0-ff9deaa0c718.gif)

**Comment by Joffcom** [comment]
Hey @JabSYsEmb 

It should be a json file in the url, can you try with the link below and let me know if it works.

https://raw.githubusercontent.com/n8n-io/n8n/master/packages/nodes-base/nodes/ExecuteCommand/test/workflow.json

**Comment by JabSYsEmb** [comment]
Hey @Joffcom,

Thanks, it worked adding ".json" will make the url valid. May we have a placeholder showing how a valid url look like or better error?

I can help with that if you can point me to where I have to look because I still am new to this project I didn't get head around it yet

**Comment by Joffcom** [comment]
Hey @JabSYsEmb,

Possibly worth doing or adding it to the documentation although using a file was my first thought. I will get a doc update sorted out later today or tomorrow.

For now though as there is no bug here I am going to mark this one as closed.
