### ISSUE TITLE
0.215.0 does not start in queue mode

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5460]
**Describe the bug**

In this version 0.215.0 the queue mode containers do not start:

```n8n start``` works
```n8n webhook``` won't start
```n8n worker``` won't start

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by luizeof** [comment]
@Joffcom Has anything changed in the command line executables for those running n8n in queue mode?

**Comment by janober** [comment]
Thanks a lot for making us aware of this issue. Will have a look.

**Comment by Joffcom** [comment]
@luizeof do you get any error messages?

**Comment by janober** [comment]
Created a fix and will release.

fyi is then probably the same issue as reported here:
https://community.n8n.io/t/i-have-a-crash-with-n8n-worker-at-newest-version/22921/3

**Comment by janober** [comment]
Fix got released with `n8n@0.215.1`
