### ISSUE TITLE
"AWS SNS Trigger" doesn't work with n8n version: 0.215.1.

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [n8n-io/n8n#5465]
"AWS SNS Trigger" doesn't work with n8n version: 0.215.1.
Don't see errors in a docker container,
Just not receiving incoming events from AWS SNS.

Returned to version: n8nio/n8n:0.214.2 
And it works again.

**Comment by Joffcom** [comment]
Hey @Valentyn-Kubrak,

Thanks for reporting this one, I was just taking a look and it looks like there was a change made 2 weeks ago which touched the node but that would have impacted 213 (I think).

I gave it a quick go anyway on 0.214.3 and it worked as expected so I then tried 0.215.1 and you are not wrong it doesn't work, I took a look in AWS and it has not registered the URL in the subscription when manually executing the workflow but Activating the workflow seems to register it.

I have raised it internally and there is an idea of what the issue might be, I will let you know when a PR is in place.
