### ISSUE TITLE
Replace depencency: cron

### ISSUE THREAD

**Issue by Hexagon** [n8n-io/n8n#5470]
**Describe the bug**

I noticed that you depend on `cron`, which is broken in many ways. Here are a few examples

* It does not follow standards and expects 0-11 as the input for the month, while all other cron implementations expect 1-12.
* It has numerous active issues, some of which are unpredictable and serious, but no one seems to care.
* At top of it all, the readme states:
```
Looking for maintainers/contributors
This project is looking for help! If you're interested in helping with the project please reach out to me [ncb000gt] nd let me know. I'd love for it to continue on, **but it needs a lot of attention**.
```

I am the creator of [croner](https://github.com/hexagon/croner), an *almost* drop-in replacement that supports all the features of cron and more. It has been tried and tested (by pm2, for example) and works well.

I would recommend you to consider switching library for your schedule node.

**Comment by Joffcom** [comment]
Hey @Hexagon 

Thanks for raising this, as we have not seen a lot of issues with the package I will create an internal ticket to look into if we need to replace the package and to evaluate alternatives. 

For now though I am going to mark this as closed, if you happen to have a workflow example that breaks because of the package let me know and we can reopen this and treat it as a bug.

**Comment by Hexagon** [comment]
Simplest way to get unwanted behavior should be to enter a custom expression specifying months. 

The ´cron´ package use non-standard notation for months. '0 0 0 * 2 *' won't trigger at all in february, as an example - and your documentation points to crontab.guru, which uses standard notation.

Also, there is a lot of other interesting bugs, look at the example below, where i specify 31th of february (which does't exist).

```
const CronJob = require("cron").CronJob;    // Using 2.2.0
const Croner = require("croner");           // Using 5.7.0

// Test of pattern '12:00:00, 31st of february
// - Expected result: undefined

// - 0 0 12 31 2 * in 'standard' cron implementations
console.log(Croner("0 0 12 31 2 *", { utcOffset: 0}).next()?.toISOString());
// > undefined - as expected

// - 'Correct' pattern when using 'cron' should be: 0 0 12 31 1 *, as it expects non-standard notation for months. Let's try that.
console.log(new CronJob("0 0 12 31 1 *", { utcOffset: 0}).nextDate()?.toUTC().toISO());
// > Month '1' is limited to '29' days. <- This is an unwanted console log
// > 2024-02-02T11:00:00.000Z           <- This is clearly the wrong date, also, the time is also wrong

// - Trying to use a standard cron expression (0 0 12 31 2 *) with package 'cron'
console.log(new CronJob("0 0 12 31 2 *", { utcOffset: 0}).nextDate()?.toUTC().toISO());
// > 2024-03-31T11:00:00.000Z           <- This will run on the wrong month (and on the wrong time)
```

**Comment by Joffcom** [comment]
Hey @Hexagon 

I will set up some internal tests so we can evaluate what is happening then if needed we can look into other packages to replace it with.
