### ISSUE TITLE
Webhook problem with "Content-Type"

### ISSUE THREAD

**Issue by gregfr** [n8n-io/n8n#5506]
**Describe the bug**
Adding a "Content-Type" header to a webhook is ignored ; adding "Content-Type:" (with colon) makes n8n crash and corrupt the node.

**To Reproduce**

1. Add a webhook
2. Add option "Response header"
3. Set name to either "Content-Type" or "Content-Type:"

**Expected behavior**
The answer to the request should have its Content-Type header set accordingly.

**Environment (please complete the following information):**

- OS: I don't know? (latest docker)
- n8n 0.216.0
- Node.js: I don't know? (latest docker)
- Database system default
- Operation mode default

**Additional context**
If trying with the colon, n8n crashes and restart ; afterwards editing the node doesn't allow to add custom headers.

**Comment by Joffcom** [comment]
Hey @gregfr,

Is it a specific content type that is failing? I have done a quick test with `Content-Type` and value of `text/plain` and this has worked and set the correct header.

![image](https://user-images.githubusercontent.com/4688521/220079998-91b6cc38-089c-4e16-9fbb-fa4baf726ca3.png)

```
> curl -v http://localhost:5678/webhook-test/3d8d4af2-82aa-4e07-98ea-20ea7d19acb4
*   Trying 127.0.0.1:5678...
* Connected to localhost (127.0.0.1) port 5678 (#0)
> GET /webhook-test/3d8d4af2-82aa-4e07-98ea-20ea7d19acb4 HTTP/1.1
> Host: localhost:5678
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Content-Length: 34
< ETag: W/"22-6OS7cK0FzqnV2NeDHdOSGS1bVUs"
< Vary: Accept-Encoding
< Date: Mon, 20 Feb 2023 10:26:56 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{"message":"Workflow was started"}%
```

I have also tried a value of `application/json` which has also worked.

```
> curl -v http://localhost:5678/webhook-test/3d8d4af2-82aa-4e07-98ea-20ea7d19acb4
*   Trying 127.0.0.1:5678...
* Connected to localhost (127.0.0.1) port 5678 (#0)
> GET /webhook-test/3d8d4af2-82aa-4e07-98ea-20ea7d19acb4 HTTP/1.1
> Host: localhost:5678
> User-Agent: curl/7.86.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 34
< ETag: W/"22-6OS7cK0FzqnV2NeDHdOSGS1bVUs"
< Vary: Accept-Encoding
< Date: Mon, 20 Feb 2023 10:28:44 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
{"message":"Workflow was started"}%
```

With the typo in the header name there is an error returned but it didn't appear to crash n8n and I was also able to edit the workflow.

```
{"code":0,"message":"There was a problem executing the workflow","stacktrace":"Error: There was a problem executing the workflow\n    at Object.executeWebhook (/Users/jon/.nvm/versions/node/v16.16.0/lib/node_modules/n8n/src/WebhookHelpers.ts:678:21)\n    at /Users/jon/.nvm/versions/node/v16.16.0/lib/node_modules/n8n/src/TestWebhooks.ts:117:25"}
```

**Comment by Joffcom** [comment]
Hey @gregfr

I am going to mark this as closed for now as I not able to reproduce the issue, If this is still an issue let me know and we can have a chat to work out how to reproduce it and open this back up again.
