### ISSUE TITLE
~[bug]~ Expressions with Chinese, Japanese or Korean character can't **DISPLAY** properly in 0.216.0

### ISSUE THREAD

**Issue by 1itt1eB0y** [n8n-io/n8n#5527]
## Describe
Some characters will make `Expression` to `Plain Text`, so that the node can't work properly.

**It can _work_ properly, just can't _display_ properly on the web page**

### Korean
![图片](https://user-images.githubusercontent.com/29831189/220233091-71d72e42-4928-466c-918e-2a1c70230408.png)

### Japanese
![图片](https://user-images.githubusercontent.com/29831189/220233145-b25c2715-dd9e-439a-87fb-ffdb22d1fa92.png)

### Chinese
![图片](https://user-images.githubusercontent.com/29831189/220233311-eaa6cd8a-638a-43ca-b627-68ac77db4baa.png)

### Russian and French
![图片](https://user-images.githubusercontent.com/29831189/220233483-32dbcf4b-db38-4df8-8654-378022fe5f9c.png)

## **Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.216.0

**Comment by Joffcom** [comment]
Hey @1itt1eB0y,

Thanks for reporting this one, I have just given it a test and managed to reproduce the problem. I have created an internal ticket for this one which we will be tracking as `ADO-387`

**Comment by janober** [comment]
Fix got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)
