### ISSUE TITLE
Got Blank pages - And not appear login page 

### ISSUE THREAD

**Issue by mzayn** [n8n-io/n8n#5543]
## Describe the issue/error/question

- I Got Blank pages when want to login. This happen this morning. But yesterday night i can login to n8n and edit some workflow. but today i can't login and when kept refresh and go incognito mode browser still same are blank pages. 

- im using n8n latest version 
- use standalone Dockers with portainer to monitor n8n

## What is the error message (if any)?

- got error at console when use guest / incognito browser like this : 

![image](https://user-images.githubusercontent.com/15009301/220581969-9460e239-a621-432b-9b4e-40ed937832ad.png)

for other configuration at docker im not change anything.. just update n8n to latest version that all. 

## Information on your n8n setup

```
Initializing n8n process
n8n ready on 0.0.0.0, port 5678
Version: 0.216.1
 ================================
   Start Active Workflows:
 ================================
```

- **n8n version:**  0.216.1
- **Database you're using (default: SQLite):** Default SQLite
- **Running n8n with the execution process [own(default), main]:** -
- **Running n8n via [Docker, npm, n8n.cloud, desktop app]:** Docker Standalone with monitor with Portainer - Im using ARM Server with Ubuntu Installed

**Environment (please complete the following information):**

- OS: ubuntu Ubuntu 22.04.2 LTS aarch64(Py3.7.8)
- n8n Version 0.216.1
- Node.js Version v18.14.0

Hope Can Help for fix this issue.

**Comment by Joffcom** [comment]
Hey @mzayn,

Thanks for reporting this one, I have just checked my instance and I am not able to reproduce it with the settings I have. Can you share the environment options you have set for your instance? Feel free to remove any values containing usernames, passwords and URLs.

**Comment by mzayn** [comment]
> Hey @mzayn,
> 
> Thanks for reporting this one, I have just checked my instance and I am not able to reproduce it with the settings I have. Can you share the environment options you have set for your instance? Feel free to remove any values containing usernames, passwords and URLs.

here the env setting in my instance 

```

ENTRYPOINT	tini -- /docker-entrypoint.sh
ENV	
EXECUTIONS_TIMEOUT	3600
EXECUTIONS_TIMEOUT_MAX	7200
GENERIC_TIMEZONE	Asia/Singapore
N8N_BASIC_AUTH_ACTIVE	true
N8N_BASIC_AUTH_PASSWORD	xxx
N8N_BASIC_AUTH_USER	xxx
N8N_EMAIL_MODE	smtp
N8N_HOST	xxx
N8N_PORT	5678
N8N_PROTOCOL	https
N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN	true
N8N_SMTP_HOST	xxx
N8N_SMTP_PASS	xxx
N8N_SMTP_PORT	465
N8N_SMTP_SENDER	xxx
N8N_SMTP_SSL	true
N8N_SMTP_USER	xxx
N8N_VERSION	0.216.1
NODE_ENV	production
NODE_ICU_DATA	/usr/local/lib/node_modules/full-icu
NODE_VERSION	18.14.0
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VUE_APP_URL_BASE_API	xxx
WEBHOOK_TUNNEL_URL	xxx
WEBHOOK_URL	xxx
YARN_VERSION	1.22.19
```

**Comment by Joffcom** [comment]
Hey @mzayn,

Out of interest are you using the user management feature (the n8n log in page) as well? If you are it might be worth removing the basic auth options and seeing if that helps.

**Comment by mzayn** [comment]
> Hey @mzayn,
> 
> Out of interest are you using the user management feature (the n8n log in page) as well? If you are it might be worth removing the basic auth options and seeing if that helps.

not using any feature for login page. just use for my self.

**Comment by Joffcom** [comment]
Does that look like this?

![image](https://user-images.githubusercontent.com/4688521/220590842-591eca9f-d103-4bc8-8fc7-72716e380eb2.png)

**Comment by mzayn** [comment]
> Does that look like this?
> 
> ![image](https://user-images.githubusercontent.com/4688521/220590842-591eca9f-d103-4bc8-8fc7-72716e380eb2.png)

yes. but right now all blank pages and that login pages not appear

**Comment by Joffcom** [comment]
Excellent so that is user management, As a test can you remove the basic auth parts of your config as they are no longer needed then restart the instance and see if that helps. The 3 options to remove are below, Are you also using a reverse proxy and if so which one?

```
N8N_BASIC_AUTH_ACTIVE	true
N8N_BASIC_AUTH_PASSWORD	xxx
N8N_BASIC_AUTH_USER	xxx
```

**Comment by mzayn** [comment]
> N8N_BASIC_AUTH_USER

done remove that at env. But still same result with blank page. when trying

**Comment by Joffcom** [comment]
Few more questions...

What version of n8n were you on before the upgrade?
Did you manually do the upgrade?
What settings do you have enabled in Cloudflare?

**Comment by mzayn** [comment]
> version before upgrade if mistaken ( n8n@0.215.1 or n8n@0.215.0 )
> upgrade using portainer 
>settings do you have enabled in Cloudflare > Yes, Same like before i can use n8n and not change any setting in nginx rewrite and other. cause yesterday night i still can use for edited some workflow after update. but this morning i can't login the pages. 

for some my reverse proxy configure like this...

```
    location ^~ /
{
  
  	 location ~ /\.well-known\/acme-challenge {
        allow all;
    }
  
    proxy_pass http://localhost:5678;
     proxy_set_header Connection '';
     proxy_http_version 1.1;
     chunked_transfer_encoding off;
     proxy_buffering off;
     proxy_cache off;
    proxy_set_header Host localhost;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;

    #Persistent connection related configuration

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache
    
    
    set $static_fileH0yhLM28 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_fileH0yhLM28 1;
    	expires 12h;
        }
    if ( $static_fileH0yhLM28 = 0 )
    {
    add_header Cache-Control no-cache;
    }
}
```

**Comment by Joffcom** [comment]
Hey @mzayn,

One thing we noticed looking at your site was extra stuff being added which could be from Cloudflare, Can you confirm the settings you have enabled or if possible can you try disabling rocket loader and zaraz to see if that helps along with anything else that might be trying to optimize the files.

I am not sure why you have nginx caching enabled but could be worth disabling that as well for now. One test that would be useful is if you could try accessing n8n without going through cloudflare or nginx that will tell us if it is n8n or something else, We have not been able to reproduce this yet so we assume something outside of n8n is causing the issue we just don't know what it is so the more information we can get the better.

**Comment by mzayn** [comment]
> rocket loader

zaraz was disable 
and rocket loader not using this as default are disable 

fot nginx cache which one i need to disable  ?

**Comment by Joffcom** [comment]
Hey @mzayn,

Any of the cache lines, Did you try accessing n8n directly to see if it works that would be a massive help. For now can you roll back to the previous version you were using and see if that gets things running?

**Comment by mzayn** [comment]
this issue was been detected conflict with cache in CF. 

was test when disable cache in CF in global, i normally can load the page of N8N login page. so right now i want to use cache to other my site setting in CF

so i rollback to previous version so i can use N8N back. but i can't use for latest version for fix bug.

thanks,

**Comment by Joffcom** [comment]
Hey @mzayn 

That is good to know, out of interest why are you using the CF cache with n8n? Because of the dynamic nature of the application and workflows I don't think the cache would really help with anything.

**Comment by mzayn** [comment]
> Hey @mzayn
> 
> That is good to know, out of interest why are you using the CF cache with n8n? Because of the dynamic nature of the application and workflows I don't think the cache would really help with anything.

im using subdomain with CF and and use Security feature in CF with firewall. so in other main/subdomain i need use cache in CF. 

-----

one more i want to ask, before this i want delete all execution history not problem for a total list `29802 ` but im getting error when delete all of that 

Problem deleting executions
SQLITE_ERROR: Expression tree is too large (maximum depth 1000

only can delete 1000 only. 

so, how to i want delete all the history.

---
one more suggestion where can make option for a month/weekly/day for setting automatic delete the execution history that.

**Comment by Joffcom** [comment]
Hey @mzayn,

I would probably exclude the n8n subdomain from the cache you will likely have a better experience. It looks like for some reason it is modifying our files which is causing the issue.

We have an environment option to delete old executions which will help.

EXECUTIONS_DATA_PRUNE - Whether to delete data of past executions on a rolling basis.
EXECUTIONS_DATA_MAX_AGE - The execution age (in hours) before it's deleted.

**Comment by mzayn** [comment]
> EXECUTIONS_DATA_PRUNE - Whether to delete data of past executions on a rolling basis.
> EXECUTIONS_DATA_MAX_AGE - The execution age (in hours) before it's deleted.

for that env what the values recommend ?

```
YARN_VERSION	1.22.19
EXECUTIONS_DATA_PRUNE	null
EXECUTIONS_DATA_MAX_AGE	null

```

**Comment by Joffcom** [comment]
EXECUTIONS_DATA_PRUNE true
EXECUTIONS_DATA_MAX_AGE - This is up to you.

**Comment by mzayn** [comment]
@netroy 

i already update latest n8n, that version for Fix execution pruning right  ?

```
n8n Version0.217.1
```

and i got issue 
![image](https://user-images.githubusercontent.com/15009301/221324505-bb57d9ec-ca66-450f-b04b-8eff4dc22faa.png)

**Comment by netroy** [comment]
@mzayn The PR linked above isn't released yet. It'll be included in the next release.

Regarding the 504s, those imply that n8n is likely busy processing a heavy query, and you have a reverse proxy that is forcing a timeout on the requests.

regarding the `sessionId` error, that happens when the frontend sends a request to `/rest/push` without the `sessionid` parameter. That should not be happening, and I suspect that your reverse proxy might be modifying the request urls.

**Comment by eliasff** [comment]
> 

I had this same issue after atualize to 0.212.0. But after 0.221.2 this problem is gone.

**Comment by eliasff** [comment]
> > Hey @mzayn
> > That is good to know, out of interest why are you using the CF cache with n8n? Because of the dynamic nature of the application and workflows I don't think the cache would really help with anything.
> 
> im using subdomain with CF and and use Security feature in CF with firewall. so in other main/subdomain i need use cache in CF.
> 
> one more i want to ask, before this i want delete all execution history not problem for a total list `29802 ` but im getting error when delete all of that
> 
> Problem deleting executions SQLITE_ERROR: Expression tree is too large (maximum depth 1000
> 
> only can delete 1000 only.
> 
> so, how to i want delete all the history.
> 
> one more suggestion where can make option for a month/weekly/day for setting automatic delete the execution history that.

I had this same issue after atualize to 0.212.0. But after 0.221.2 this problem is gone.
