### ISSUE TITLE
Telegram node "send document" is missing "parse_mode" option

### ISSUE THREAD

**Issue by JokerQyou** [n8n-io/n8n#5549]
**Describe the bug**

According to [Telegram API doc](https://core.telegram.org/bots/api#senddocument) the `sendDocument` method accepts the same "parse_mode" option as other APIs. (e.g. `sendPhoto`, `sendVideo`, `sendAudio`, etc.) But on n8n UI there is no such option. See the screenshot:

![image](https://user-images.githubusercontent.com/1465267/220816371-aa28abff-2f19-4ace-a698-b0b413cd36da.png)

The "parse_mode" specifies how Telegram should render the document caption.

**To Reproduce**

1. Create or open a work flow
2. Add a "Telegram" node
3. Set "Resource" to "Message"
4. Set "Operation" to "Send Document"
5. In "Additional Fields" section, add a "Caption" field
6. In "Additional Fields" section, there's no way to add a "parse_mode" field

**Expected behavior**

I expect to be able to set "parse_mode" when using the Telegram node with "Send document" operation.

**Environment (please complete the following information):**

- OS: General Linux, I don't think OS version is relevant.
- n8n Version: `0.216.1`
- Node.js Version: I don't known, I'm using the official n8n docker image.
- Database system: SQLite
- Operation mode: maybe `own`? I don't know what this is.

**Additional context**

I've checked all other operations of the Telegram node that sends (or edits) text content, and `sendDocument` is the only one missing this option. Clearly this is a bug.

**Comment by Joffcom** [comment]
Hey @JokerQyou 

Thanks for letting us know about this, As this is an optional parameter and nothing is broken this doesn't feel like a bug to me although I do get what you are saying and this should be a feature that we add to make it consistent.

This should be a fairly quick change though so I will see if I can fit this in today.

**Comment by Joffcom** [comment]
Hey @JokerQyou,

the change for this one has been merged and should be available in the next release.

**Comment by janober** [comment]
Fix got released with [`n8n@0.218.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.218.0)
