### ISSUE TITLE
The Execute Workflow node is disappeared from default nodes

### ISSUE THREAD

**Issue by AFirouzi** [n8n-io/n8n#5579]
**Describe the bug**
When the user searches for the `Execute Workflow` node to add it to the workflow, the search results only include the `Execute Workflow Trigger`.
However, it is still possible to have it in the workflow by copying from another workflows but not using the search option. 

**To Reproduce**

1. Go to **`Workflows`** Tab on the left side bar. 
2. Click on **`Add Workflow`**
3. Click on the **`+`** sign on the top right corner
4. Search for the `Execute Workflow`
5. The `Execute Workflow` node is not showing in the results.

**Expected behavior**
The user can find the `Execute Workflow` in the search results from the default nodes.

**Environment (please complete the following information):**

- OS: Windows
- n8n Version: 0.217.0
- Node.js Version: 16.18.1
- Database system PostgreSQL
- Operation mode: own

**Comment by Joffcom** [comment]
Hey @AFirouzi,

Thanks for reporting this one, This is being tracked internally as `ADO-404` and can also be found on the community support forum here: https://community.n8n.io/t/execute-workflow-node-missing/23418

**Comment by Joffcom** [comment]
Hey @AFirouzi,

The fix for this has just been merged so this will resolved in the next release, I am going to mark this one as closed but you will get a notification here once the release is available.

**Comment by janober** [comment]
Fix got released with [`n8n@0.218.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.218.0)
