### ISSUE TITLE
Fresh install debian 10 no login asked

### ISSUE THREAD

**Issue by guizmoau** [n8n-io/n8n#558]
**Describe the bug**

I just install n8n in a fresh debian instance scaleway
and when I connect to the URL I have no security, no login and password asked !!

The variables N8N_BASIC_AUTH_USER and N8N_BASIC_AUTH_PASSWORD are set in .env 

**To Reproduce**
strictly follow the step of the guide below in a fresh debian 10 install
https://docs.n8n.io/#/server-setup?id=example-setup-with-docker-compose

**Expected behavior**
having a basic auth security with login and password

**Environment (please complete the following information):**
 - OS: debian 10
 - n8n Version latest docker
 - Node.js Version see docker

**Additional context**

**Comment by janober** [comment]
Can you try to replace the following lines in the file `docker-compose.yml`:
```yaml
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
```
with 
```yaml
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
```
The only thing I can think of right now is that there is for some reason a bug in Docker that it does not read the environment variables correctly in Debian 10 anymore. As it sounds like everything else is working fine writing it differently could be a good temporary "fix" till the Docker-Team fixes it properly.

**Comment by guizmoau** [comment]
no I think it is a mistake from my browser cache. 
I must have the autologin from bitwarden working too quickly :p
 
There is no bug in there in fact.
This project is awesome !!

**Comment by janober** [comment]
Ah very happy to hear! I was already wondering how something like that could happen.

Glad to hear that you enjoy n8n. Have fun!
