### ISSUE TITLE
Define the webhook method in the custom node. If an error occurs in the webhook method, the error will not be displayed on the UI and will continue to execute

### ISSUE THREAD

**Issue by sdghf** [n8n-io/n8n#5580]
**Describe the bug**
Define the webhook method in the custom node. If an error occurs in the webhook method, the error will not be displayed on the UI and workflow will continue to execute

**To Reproduce**

I call the webhook url generated by the wait node, trigger the webhook method,

I am actively throwing an error in the webhook method and always returns
 {
    "code": 0,
    "message": "Workflow Webhook Error: Workflow could not be started!"
},

If an error workflow is set it will trigger an error workflow,but the UI shows that the workflow is executed correctly，That is, if an error occurs in the webhook method, it will not affect the subsequent execution of the workflow. Why?
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/33833181/221733796-d9b57c53-f6e4-45da-8460-4aba417fa641.png">
![image](https://user-images.githubusercontent.com/33833181/221734295-cc24711a-3a48-4da0-99e3-c9bb6b8889a6.png)

**Expected behavior**
The workflow should be stopped at the error node instead of continuing

**Environment (please complete the following information):**

- OS: [Mac Studio Apple M1 Max]
- n8n Version [e.g. 0.217.0]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. postgreSql; ]
- Operation mode [e.g. main; ]

**Additional context**

**Comment by Joffcom** [comment]
Hey @sdghf,

Would you be able to share your node so I can take a look? I have done a quick test with a webhook node that just returns the error and it works as expected so I am not sure if maybe it is something specific to your node or something with the wait node that works differently.

**Comment by sdghf** [comment]
I directly copied the wait node as my own node, and just did some logic in the webhook method and execute method. I want that if there is an error during the execution of the webhook method it will end the workflow instead of continuing the workflow
![image](https://user-images.githubusercontent.com/33833181/221866041-348610f7-1dd3-476a-82ae-f01acdeb28f2.png)

The picture above is my execution record. The "custom wait" node has already thrown an error in the webhook method,
However, the UI does not display an error, and the workflow will continue to be executed later, and the execution process before the "custom wait" disappears.

I want to ask is this normal?

**Comment by sdghf** [comment]
@Joffcom

**Comment by Joffcom** [comment]
Hey @sdghf,

Managed to reproduce it and looking at the wait node I suspect this is expected as the `execute` method is returning without issue, It might be a case of adding an if node after it to check for an empty output and treat that as your error.

@netroy do you have any thoughts on this one?

**Comment by sdghf** [comment]
Hey@Joffcom ,

I do not quite understand，The `execute` method does return the expected result, and the above problem occurs only when an error occurs in the `webhook` method

I don't know what to do next.

**Comment by Joffcom** [comment]
Hey @sdghf

My theory is that the webhook error is ignored because it is a secondary method in the node, the Execute is ran first and that is successful which is allowing the node to continue.

From a custom node view I don't think there is anything you can do and it would come down to how you build your workflow. Although that does also depend on what you are actually planning to do with your node and you are likely to see an error on the webhook side.

**Comment by sdghf** [comment]
Hey @Joffcom 
I tried to find the call chain in the executeWebhook method under the source code cli/src/WebhookHelpers, and indeed caught the error in the webhook method through try/catch, and then start to run the workflow， It seems that we can only try to solve this problem by modifying the code
![image](https://user-images.githubusercontent.com/33833181/222305576-bd300117-0e44-4acc-b289-826ad8075725.png)

**Comment by Joffcom** [comment]
Hey @sdghf 

That could do it although a normal webhook node will work as expected it only appears to be an issue when using both execute and webhook from my testing.

**Comment by Joffcom** [comment]
Hey @sdghf,

As this is expected at the moment I am going to mark this as closed for now, We do have a feature request opened for this but I wouldn't expect it anytime soon. 

I will let you know when this has changed.
