### ISSUE TITLE
Icon broken for custom node using npm scoped name

### ISSUE THREAD

**Issue by David-Hari** [n8n-io/n8n#5585]
**Describe the bug**
I have a node that is in an npm package. It is using npm scoped name like "@companyName/n8n-nodes-ourNode".

Since updating to 0.217.2 the icon is no longer showing.
`/icons/@companyName/n8n-nodes-ourNode/dist/icon.svg` gives a 404

**Expected behavior**
The URL should return the icon and it should be visible in the UI

**Environment (please complete the following information):**

- OS: Windows 10
- n8n Version: 0.217.2
- Node.js Version: 16.17.0
- Database system: SQLite

**Additional context**
This seems to have been broken by https://github.com/n8n-io/n8n/pull/5481, which uses a regex in the /icons URL served. That regex matches ":packageName" to only the scope part of the name (e.g. "@companyName") instead of the full name.

**Comment by Joffcom** [comment]
Hey @David-Hari,

Thanks for reporting this one, I have created `N8N-6217` as our internal ticket to get this resolved.

**Comment by Joffcom** [comment]
Hey @David-Hari,

Just to let you know this has been fixed and will be available from the next release, There will be another notification here once the release is available.
