### ISSUE TITLE
Migrations taking too long on 0.217.2

### ISSUE THREAD

**Issue by j-norwood-young** [n8n-io/n8n#5590]
**Describe the bug**
Upgrading to v0.217.2 takes a really long time on a large database. 

We have a fairly big N8N SQLite db (currently 81GB). Upgrading to v0.217.2 is taking extremely long (it hasn't completed yet after a few hours) and it's unclear how long it will take.

I've tried downgrading and can get N8N up and running again. I thought I could move over to a MySql DB, but now I get the error "NodeTypes not initialized yet" if I try to export.

**To Reproduce**

1. npm i -g npm
2. systemctl restart n8n
3. journalctl -u n8n -f
4. `debug    | Starting migration MigrateExecutionStatus1676996103000 "{ file: 'migrationHelpers.js', function: 'logMigrationStart' }"`

**Expected behavior**
n8n upgrade expected to complete

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version 0.217.2
- Node.js Version v16.18.1
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @j-norwood-young,

That is a lot of data to get through, It might be worth clearing out your execution history and if you have the space on the machine available doing a vacuum which should reduce the size and allow the migration to finish a bit quicker.

**Comment by j-norwood-young** [comment]
Thanks @Joffcom.

I updated my environment to do a vacuum and keep the file size low from now on:
```
Environment="EXECUTIONS_DATA_PRUNE=true"
Environment="EXECUTIONS_DATA_MAX_AGE=168"
Environment="EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000"
Environment="DB_SQLITE_VACUUM_ON_STARTUP=true"
```

The database dropped down to just 20GB and the upgrade completed in a reasonable amount of time.
