### ISSUE TITLE
Some nodes are missing (Eg: RabbitMQ)

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#5597]
**Describe the bug**

Some nodes are missing. For example, only the RabbitMQ Trigger is displayed and not the Regular Node.

![CleanShot 2023-03-02 at 07 54 18](https://user-images.githubusercontent.com/257004/222409804-1b34ddc1-6c9d-4cbe-85b1-a8ce4af89780.gif)

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.217.2]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof,

Thanks for reporting this one, I just popped in a fix for it. You have said that 'some nodes are missing' do you have examples of others?

**Comment by luizeof** [comment]
RabbitMQ and Execute Workflow

**Comment by Joffcom** [comment]
Hey @luizeof,

Execute Workflow has already been resolved which is handy.

**Comment by Joffcom** [comment]
Hey @luizeof,

The PR has been merged, This will be available in the next release. We also found that AMQP was missing so there is another PR that will fix that.

For now I am going to mark this one as closed.

**Comment by janober** [comment]
Fix got released with [`n8n@0.218.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.218.0)
