### ISSUE TITLE
Provide CDK/SAM template to simplify setup on AWS

### ISSUE THREAD

**Issue by Stvad** [n8n-io/n8n#56]
It'd be great to have a CDK or SAM template to set up all required resources in 1 click/command to run n8n on AWS.   
I'd imagine it'd include something like:

* RDS Postgress/ DocumentDB (in lieu of MongoDB)
* ECS Fargate setup (to run the container)
  * Cluster
  * Task
  * Service
* Security groups

**Comment by RicardoE105** [comment]
Hey @Stvad, Sorry for the late response, and thanks for the feedback. You can go to our community [here](https://community.n8n.io/) and request this.

**Comment by netroy** [comment]
@Stvad [I created a CDK stack to simplify deploying n8n to Fargate](https://github.com/netroy/cdk-fargate-n8n). 
it's not really production-ready (yet), but it works.

**Comment by sid137** [comment]
@netroy  is this still around somewhere?

**Comment by netroy** [comment]
@sid137 I'm still working out how to get EFS volumes working with fargate containers with the right filesystem permissions, but for most part, you can use [this updated branch](https://github.com/netroy/cdk-fargate-n8n/tree/queue-mode) now. 
PS: this uses n8n's queue mode now, which means that there is an additional redis instance deployed, and workers run in a scalable way (although auto-scaling them isn't implemented yet).

**Comment by sid137** [comment]
> @sid137 I'm still working out how to get EFS volumes working with fargate containers with the right filesystem permissions, but for most part, you can use [this updated branch](https://github.com/netroy/cdk-fargate-n8n/tree/queue-mode) now. PS: this uses n8n's queue mode now, which means that there is an additional redis instance deployed, and workers run in a scalable way (although auto-scaling them isn't implemented yet).

@netroy  awesome, thanks!  If you've got more info on your EFS problem, maybe i'll look into it
