### ISSUE TITLE
(Generic)OAuth2 API refresh_token is not used with teamleader.eu

### ISSUE THREAD

**Issue by nesretep-anp1** [n8n-io/n8n#5607]
**Describe the bug**
We try to use TeamLeader.eu API via N8N and created an OAUTH2 API credential in N8N which works fine (account is connected). Appropriate requests to the API are working well for around 60 minutes. Then the error "access token expired" is issued. 

**To Reproduce**

1. Register an OAuth client on TeamLeader.eu
2. Create the credential in N8N (we tried both, Header and Body)
3. Connect works well.
4. Having a workflow with HTTP Request and Authentication => Generic, Generic Auth Type => OAUTH2 API.
5. Workflow works well for around 60 minutes, then "access token expired".

**Expected behavior**
It is proven that TeamLeader.eu API returns a refresh_token from the very beginning. So the expected behavious is that there should not be an expiry due to having the refresh_token being used to get a new access_token.

**Environment (please complete the following information):**

- Ubuntu Linux 22.04
- n8n Version 0.217.2
- Node.js Version 14.21.3
- Database system Postgres
- Operation mode main

**Additional context**

**Comment by Joffcom** [comment]
Hey @nesretep-anp1,

I can't see a node for TeamLeader.eu so I assume you are using an HTTP Request node, As this is not a bug and likely a configuration issue with how the API is being used can you open a post on our community support forum: https://community.n8n.io so we can look into this further.

**Comment by nesretep-anp1** [comment]
Yes, we are using the HTTP Request Node, but we do use OAuth2 Credentials and OAuth2 authentication, therefore OAuth2 flow should come from/via N8N, where the (Generic) OAuth2 API should follow the refresh token mechanics!?
