### ISSUE TITLE
ERPNext custom domain does not work

### ISSUE THREAD

**Issue by monolithonadmin** [n8n-io/n8n#5631]
ERPNext custom domain does not work. 

I am experiencing an issue with my ERPNext custom domain. Currently, I am using Frappe hosting and I am able to connect to n8n using my credentials when I choose the cloud-hosted option. However, I am unable to connect when I use my custom domain.

You can see on the screenshot

![n8n-erpnext-custom-domain-issue](https://user-images.githubusercontent.com/5338127/223250988-cd66f05e-45c8-4f44-9ece-1ea88e1261cb.jpg)

**Comment by Joffcom** [comment]
Hey @monolithonadmin,

That is odd. If you ignore the credential test does it still work? Does the user also have full permissions or a limited set?

**Comment by monolithonadmin** [comment]
Despite granting my user full permissions, self-hosting is still not functioning correctly. The Ignore option does not seem to have any effect on resolving this issue.

**Comment by monolithonadmin** [comment]
Despite granting my user full permissions, self-hosting is still not functioning correctly. The Ignore option does not seem to have any effect on resolving this issue.

**Comment by Joffcom** [comment]
Hey @monolithonadmin,

When you say self hosting is that you hosting it yourself rather than using the FrappeCloud offering? As a test could you try using the HTTP request node to see if you can get any data from `yourdomain.com/api/resource/Doctype` using an authorization header of `token apikey:apisecret` to see if it returns anything?

**Comment by monolithonadmin** [comment]
@Joffcom 

sorry for the delay. I tried many things. And bc it worked from my shell with curl I went deeper. 

We changed frappe.cloud to erpnext.com with our subdomain, but we have a redirect from this to our real domain. But in this case, as you can see on the image I could save the credential. 

And then I was able to use it in HTTP requests and we got the right data. 

But the issue is that when I try to use the ERPNext node the document list is still empty, so I can't use it.

Do you have any idea? 

thank you

![Screenshot (2)](https://user-images.githubusercontent.com/5338127/225672231-65c9de8d-6827-42a4-8981-cf21d57444f0.png)
![httprequest-works](https://user-images.githubusercontent.com/5338127/225672242-589b4559-1615-4036-8642-06a45d692824.jpg)

**Comment by monolithonadmin** [comment]
FYI: I have set CORS headers in my site too. And I still struggle with this.

**Comment by Joffcom** [comment]
Hey @monolithonadmin,

It is probably not CORS related but I will need to set up a trial account on the ERP Next cloud offering to see if I can reproduce it.

When you say you can't save your domain what do you mean? Like it won't save or it won't work? Can you also confirm which version of n8n you are running?

**Comment by monolithonadmin** [comment]
@Joffcom Sorry to bring this up again. If there is anything I can do to help, please let me know. ps: The guys at Frappe have been helpful too, so I think we can work this out together.

**Comment by monolithonadmin** [comment]
@Joffcom I created a tutorial for you about custom domain settings on Frappe Cloud:
https://app.tango.us/app/workflow/Adding-a-Custom-Domain-to-FrappeCloud-s-Accounting-Application-f2fc9141db80486d9b4e32af01ab7bff

I hope it helps!

**Comment by NayanGajjar** [comment]
we having the same issue with self-hosted ERP instance

ERP version is: v14

![image](https://user-images.githubusercontent.com/122445476/232398173-7149c23f-3998-4a32-b5a3-9ed08060df0c.png)

**Comment by Joffcom** [comment]
Hey @monolithonadmin,

Perfect thanks, I will give it a go this week and see if we can get to the bottom of it.

**Comment by monolithonadmin** [comment]
Sorry to bother you @Joffcom , but is there anything I can help you with? Thank you

**Comment by Joffcom** [comment]
Hey @monolithonadmin,

Like the other issue I have just merged the change for this one and it should be resolved in the next release (0.230.0), I am going to mark this as closed and if you still see it in the next release let me know and we can open it again but from my testing it was working so I suspect all is good.

**Comment by janober** [comment]
Fix got released with [`n8n@0.230.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.230.1)

**Comment by Joffcom** [comment]
@monolithonadmin your guide was very helpful thanks for that 🙌
