### ISSUE TITLE
[Compare Datasets node] Same data input throws in "different" branch

### ISSUE THREAD

**Issue by Pheggas** [n8n-io/n8n#5645]
**Describe the bug**
When Compare Datasets node is given with same input data in both - A and B Inputs, it activates the "different" branch

**To Reproduce**

1. Make 2 caledars in Google calendar
2. Configure "Get many Google Calendar events" for both calendars
3. Populate both calendars - each with the same event name and start / end dateTimes
4. Connect both "Get many Google Calendar events" nodes to each input in Compare datasets
5. Set the Fields to match to "summary" (as name of the event), start.dateTime (as for start of the event), and end.dateTime (as for end of the event)
6. Set the "When There Are Differences" field to "Include Both Versions"
7. Start the workflow

You'll see that both events from each calendars (that are the same) have the same start dateTime, end dateTime and summary. However, for some reason it was thrown to different branch.

**Expected behavior**
I expect it to throw it to "same" branch as match fields do match

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 TLS (GNU/Linux 5.15.0-58-generic x86_64)
- n8n Version 0.218.0
- Node.js Version I'm not sure where to look for it
- Database system PostgresDB
- Operation mode own

**Additional context**
I've noticed that i'm not the only one having this issue. There is [thread on n8n community ](https://community.n8n.io/t/compare-datasets-issue/21995)asking about this issue. I'm pretty sure this is a real bug and not just a "alright, now i understand it" problem.

**Comment by Joffcom** [comment]
Hey @Pheggas 

Out of interest do you have the same issue if you use 2 set nodes? In theory a bug with the would would also occur with other nodes and it is easier to reproduce issues sometimes with a set or code node to mock data.

**Comment by Pheggas** [comment]
I wanted to make steps with my exact setup as i spotted the issue there. To answer your question, i'm not sure how to redo the setup as i had.

It shows in each variable the second input as null shown here:
![image](https://user-images.githubusercontent.com/9994511/223825984-b2288d2b-c0b0-46a3-a5b8-f76f88e85fc1.png)

However, as i [described in this thread](https://community.n8n.io/t/compare-datasets-issue/21995/5), the output thrown to different branch even the second input is set in each variable.

**Comment by Pheggas** [comment]
> but I assume you are not actually using the expressions.

The trick is i did try using expression and treating it like javascript code or whatever it was. But that didn't help either as shown in this picture (also posted in the thread)

![image](https://user-images.githubusercontent.com/9994511/223840861-72716e35-648c-4b07-affc-6d5f2a703a04.png)

**Comment by Joffcom** [comment]
Hey @Pheggas,

As David is still working on this in the forum post I am going to close this issue so that we are not working on this in 2 different places.
