### ISSUE TITLE
Google Sheets Node - Browser not reacting Anymore

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#5646]
**Describe the bug**

When having some fields inside a Google Sheets node which I use to add rows to a table I have the problem, that 
when there are over 3 Sheets nodes inside a Workflow and I open one of them to edit the fields, the Browser starts 
hanging with the n8n UI. 

**To Reproduce**

Make a workflow. Add 3 Google Sheet nodes with to add Rows to a Table with minimum 6 Rows to edit.
Add some Calculations to the fields like  `{{ (($node["Input1"].json["value1"])/60)*$node["Input2"].json["value2"]) }}`

**Expected behavior**

Browser starts to hangs "Site is not reacting" and you cannot edit the workflow anymore.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.218.0
- Database system Postgres
- Operation mode queue
- UI Browsers tested: latest Firefox, Chrome and Edge on Windows

**Comment by Joffcom** [comment]
Hey @prononext,

I have had a go and have not been able to reproduce this, Could you provide a workflow that you are using? Is this something that has started to happen recently after an upgrade or have you had this problem for a while? If it started after an upgrade what version did you upgrade from and if you go back to that version is it ok?

**Comment by prononext** [comment]
I am not sure when it started. I noticed when I am editing variables and references inside the google sheets node. which in the moment of editing could be incorrect for a short time., then it starts hanging instead of letting me finish it.

**Comment by Joffcom** [comment]
Hey @prononext,

I have seen some issues in the past where some expressions can cause a bit of a hang but I have not been able to reproduce it recently.

A workflow to reproduce it would be very handy.

**Comment by Joffcom** [comment]
Hey @prononext,

As this is likely to not be a bug and I am not able to reproduce it I am going to mark this as solved for now. If you are still able to reproduce this and have steps to achieve the same issue let me know and we can open this back up. It sounds like the issue could instead be a known problem with how expressions can be handled.
