### ISSUE TITLE
cannot build because of the node_modules which under the packages folder occur error

### ISSUE THREAD

**Issue by Tiramisupxl** [n8n-io/n8n#5685]
**Describe the bug**
I use docker to build the project, but some error occur and I don't know how to fix it.

**To Reproduce**
This is the log:
+ cd n8n
+ docker build -t ****/business/hjmos-business-plan-n8n:SNAPSHOT-45 -f docker/images/n8n-custom/Dockerfile .
Sending build context to Docker daemon  19.06MB

Step 1/27 : FROM node:14.15-alpine as builder
 ---> c1babb15a629
Step 2/27 : USER root
 ---> Using cache
 ---> abd367836765
Step 3/27 : RUN apk --update add --virtual build-dependencies python build-base ca-certificates && 	npm_config_user=root npm install -g lerna
 ---> Using cache
 ---> 21a3671f7343
Step 4/27 : WORKDIR /data
 ---> Using cache
 ---> 7c6a87fd5f32
Step 5/27 : COPY lerna.json .
 ---> Using cache
 ---> 7c50bc6feff6
Step 6/27 : COPY package.json .
 ---> Using cache
 ---> 468de76d9a6c
Step 7/27 : COPY packages/cli/ ./packages/cli/
 ---> Using cache
 ---> 2d6e498c407f
Step 8/27 : COPY packages/core/ ./packages/core/
 ---> Using cache
 ---> 4c336df39412
Step 9/27 : COPY packages/design-system/ ./packages/design-system/
 ---> Using cache
 ---> 1331d8debbe2
Step 10/27 : COPY packages/editor-ui/ ./packages/editor-ui/
 ---> Using cache
 ---> 02a0120ca55b
Step 11/27 : COPY packages/nodes-base/ ./packages/nodes-base/
 ---> Using cache
 ---> 96924142ccf4
Step 12/27 : COPY packages/workflow/ ./packages/workflow/
 ---> Using cache
 ---> ca22764dbfd2
Step 13/27 : RUN rm -rf node_modules packages/*/node_modules packages/*/dist
 ---> Using cache
 ---> e0483afa511e
Step 14/27 : RUN npm install --production --loglevel notice
 ---> Using cache
 ---> b0e587680d17
Step 15/27 : RUN lerna bootstrap --hoist -- --production
 ---> Using cache
 ---> 368237be7e16
Step 16/27 : RUN npm run build
 ---> Running in e84f85ac47c0

> n8n@ build /data
> lerna exec npm run build

[91mlerna[0m[91m notice cli v5.4.3
[0m[91mlerna info versioning independent
[0m[91mlerna info Executing command in 6 packages: "npm run build"
[0m
> n8n-design-system@0.8.0 build /data/packages/design-system
> npm run build:theme

> n8n-workflow@0.78.0 build /data/packages/workflow
> tsc

> n8n-design-system@0.8.0 build:theme /data/packages/design-system
> gulp build:theme

[13:35:49] Using gulpfile /data/packages/design-system/gulpfile.js
[13:35:49] Starting 'build:theme'...
[13:35:49] Starting 'compileTheme'...
[13:35:53] Finished 'compileTheme' after 3.74 s
[13:35:53] Starting 'copyThemeFonts'...
[13:35:53] Finished 'copyThemeFonts' after 12 ms
[13:35:53] Finished 'build:theme' after 3.75 s

> n8n-core@0.95.0 build /data/packages/core
> tsc

> n8n-editor-ui@0.118.0 build /data/packages/editor-ui
> cross-env VUE_APP_PUBLIC_PATH="/%BASE_PATH%/" vue-cli-service build

[91m-  Building for production...
[0m
> n8n-nodes-base@0.148.0 build /data/packages/nodes-base
> tsc && gulp

 WARNING  Compiled with 3 warnings1:36:35 PM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/app.85d67788.js (396 KiB)
  js/chunk-vendors.591796d5.js (1.88 MiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (2.55 MiB)
      css/chunk-vendors.3402e927.css
      js/chunk-vendors.591796d5.js
      css/app.dc1ffa56.css
      js/app.85d67788.js

 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

Webpack Bundle Analyzer saved report to /data/packages/editor-ui/dist/report.html
  File                                   Size              Gzipped

  dist/js/chunk-vendors.591796d5.js      1925.13 KiB       477.98 KiB
  dist/js/app.85d67788.js                395.72 KiB        102.70 KiB
  dist/css/chunk-vendors.3402e927.css    226.31 KiB        32.21 KiB
  dist/css/app.dc1ffa56.css              59.88 KiB         11.74 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
**../../node_modules/@types/mongodb/index.d.ts(58,74): error TS2724: '"bson"' has no exported member named 'ObjectID'. Did you mean 'ObjectId'?**
[91mnpm [0m[91mERR! [0m[91mcode ELIFECYCLE
[0m[91mnpm ERR! [0m[91merrno 2
[0m[91mnpm ERR! n8n-nodes-base@0.148.0 build: `tsc && gulp`
npm [0m[91mERR! Exit status 2
npm[0m[91m ERR! 
npm ERR![0m[91m Failed at the n8n-nodes-base@0.148.0 build script.
npm ERR![0m[91m This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
[0m[91mnpm ERR![0m[91m A complete log of this run can be found in:
npm[0m[91m [0m[91mERR![0m[91m     /root/.npm/_logs/2023-03-14T13_36_40_272Z-debug.log
[0m[91mlerna[0m[91m ERR! [0m[91mnpm run build exited 2 in 'n8n-nodes-base'
[0m[91mlerna [0m[91mERR! npm run build exited 2 in 'n8n-nodes-base'
[0m[91mnpm ERR! code ELIFECYCLE
[0m[91mnpm ERR! [0m[91merrno[0m[91m 2
[0m[91mnpm ERR! n8n@ build: `lerna exec npm run build`
npm ERR! Exit status 2
npm ERR![0m[91m 
npm ERR![0m[91m Failed at the n8n@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0m[91m
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-14T13_36_40_307Z-debug.log
[0mThe command '/bin/sh -c npm run build' returned a non-zero code: 2
script returned exit code 2

the error occor in **packages/nodes-base/node_modules/@types/mongodb/index.d.ts**  and how to fix this?Please Help!Thanks

**Comment by netroy** [comment]
@Tiramisupxl That looks like a really old version of n8n. Can you please update to the latest code, and try again?

**Comment by Joffcom** [comment]
Hey @Tiramisupxl 

What version of n8n are you trying to build and is it from our repo or a fork?

It looks like it might be really old so an update might be worth doing.

**Comment by Tiramisupxl** [comment]
> @Tiramisupxl That looks like a really old version of n8n. Can you please update to the latest code, and try again?

Thank you for your reply. Your reply was faster than I expected. Yes, I use the old version, but I dare not update it easily because I developed some custom nodes in packages/nodes-ba and made some modifications to editor. My n8n-core is 0.95.0, and n8n-nodes-base is 0.148.0

**Comment by Tiramisupxl** [comment]
@Joffcom Thank you for your reply. Your reply was faster than I expected. Yes, I use the old version, but I dare not update it easily because I developed some custom nodes in packages/nodes-ba and made some modifications to editor. My n8n-core is 0.95.0, and n8n-nodes-base is 0.148.0

**Comment by Joffcom** [comment]
Hey @Tiramisupxl,

Supporting an old version like that is always a pain, We don't support Node 14 anymore and we moved away from Lerna. I would strongly recommend upgrading. Your custom nodes should be fine but you would have to do the editor changes again.

**Comment by Joffcom** [comment]
Hey @Tiramisupxl,

I am going to mark this as closed for now as I suspect an upgrade is going to be needed. If this is still an issue on a newer release let me know and we can open this again.
