### ISSUE TITLE
Error description not visible to user

### ISSUE THREAD

**Issue by Nurgak** [n8n-io/n8n#5691]
**Describe the bug**
Currently, the front-end error message contains a title and a stack trace. It is not possible to show a **description** of that error which would allow a user to correct their request.

Looking at other nodes, it feels like this has been possible [in the past](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Odoo/GenericFunctions.ts#L222-L225), but I cannot make an **error description** appear in n8n, only a title.

**To Reproduce**
1. Throw a `NodeOperationError` or `NodeApiError`. The error message appears in red, such as `ERROR: ...`.
2. Open the erroneous node.
3. Expand the error details.
4. We see the time of the error and the stack, possibly an empty `cause` field when using `NodeApiError`, but no error description.

I could not make the `cause` field to show anything either. Even when the [description field](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/NodeErrors.ts#L317) was explicitly set it was marked as `undefined` when the error was viewed from the terminal (logging must be set to `verbose`).

**Expected behavior**
I expect to see a field named `Error Description` in the error details.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]: mac OS via Docker
- n8n Version [e.g. 0.200.1]: 0.219.1
- Node.js Version [e.g. 16.17.0]: 16.?
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: MariaDB
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]: queue

**Additional context**
Generally speaking, the [error functions](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/NodeErrors.ts) are a bit confusing to use in n8n, they seem to have different ways of being called and with various parameters (what is `runIndex` used for?). There is also [some guessing going on](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/NodeErrors.ts#L322).

For my use cases, having an error title and description are plenty to work with. Although, the stack trace is an amazing thing to have 😃

**Comment by Joffcom** [comment]
Hey @Nurgak 

Are you seeing this with a custom node or one of the core nodes? We have a few nodes where we have updated the error handling to show a more meaningful error message which is working.

**Comment by Nurgak** [comment]
Hi @Joffcom 

I see this with my custom node. I would gladly follow the example of core nodes, which ones handle the error more meaningfully?

**Comment by Joffcom** [comment]
Hey @Nurgak 

Google Sheets does a pretty good job and will show a couple of different messages.

I think our [DebugHelper](https://github.com/n8n-io/n8n-nodes-debughelper) node also does it.

Then again we might just be using the title I would need to check again.

**Comment by Nurgak** [comment]
Hi @Joffcom 

I tried to figure out my issue, but I keep getting this error message:
```bash
nodes/CustomNode/CustomNode.node.ts(307,9): error TS2345: Argument of type '{ message: string; }' is not assignable to parameter of type 'NodeOperationErrorOptions'.
  Object literal may only specify known properties, and 'message' does not exist in type 'NodeOperationErrorOptions'.
The command '/bin/sh -c npm install && npm run build' returned a non-zero code: 2
```

This is where is error comes from:
```TS
throw new NodeOperationError(this.getNode(), error_title, {
    message: error_message as string
});
```

In the [DebugHelper node](https://github.com/n8n-io/n8n-nodes-debughelper/blob/master/nodes/DebugHelper/DebugHelper.node.ts#L216-L218) it's declared exactly this way. The `NodeOperationErrorOptions` actually [does have the message property](https://github.com/n8n-io/n8n/blob/master/packages/workflow/src/NodeErrors.ts#L233)!

The way I build everything is via Docker, because I do not want to have `npm` installed in the host (due to potential dependency issues). My Dockerfile contents are the following

```Dockerfile
ARG NODE_VERSION=16
FROM node:${NODE_VERSION}-alpine as builder

WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM n8nio/n8n

COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
WORKDIR /app
RUN npm link

WORKDIR /usr/local/lib/node_modules/n8n
RUN npm link n8n-nodes-custom

EXPOSE 5678/tcp
CMD ["tini", "--", "n8n", "start"]
```

The following builds, but I cannot see the message in the front-end.
```TS
throw new NodeOperationError(this.getNode(), error_title, {
    description: error_message as string
});
```

Would you know where the issue can come from? My `n8nio/n8n` image is the latest, 0.219.1 at this time.

**Comment by Nurgak** [comment]
Hi @Joffcom 

As you pointed out the `DebugHelper` node is working properly, therefore I must have done something wrong and will continue investigating. Thank you for your input.

**Comment by Joffcom** [comment]
Hey @Nurgak,

No problem, If the code for your node is public feel free to create an issue on it and tag me on it and I can take a proper look at the node if I get a chance.

For now I am going to mark this one as closed though.
