### ISSUE TITLE
Problem loading data Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by gw123** [n8n-io/n8n#5710]
**Describe the bug**
Problem loading data
Cannot read properties of null (reading 'data')
![image](https://user-images.githubusercontent.com/13729169/225825823-1729f846-5fb6-47b4-b48d-af9aab0b2919.png)

**To Reproduce**
1.   a  workflow  has a kafka  trigger  and a 60s  http request node 。 
2.   kafka  trigger  with 30 message pre second  
3.  open the Executions
4.  than i get  that error Cannot read properties of null (reading 'data')

env：
    databasetype  ：                   mysql
    n8n commit_id:                     26b69b5ffc308185b82d50b9cb0239f7ea9e55f9
    EXECUTIONS_PROCESS:    main
    EXECUTIONS_MODE:          queue
    DB_TYPE:                              mysqldb

**Comment by janober** [comment]
Thank you for reporting this. It looks like there is a problem with the image you added, it does not get displayed. Additionally did also most fields of the issue template got deleted instead of filled. Can you please make sure to add those so that we can get started on looking into that issue. Thanks!

**Comment by gw123** [comment]
> Thank you for reporting this. It looks like there is a problem with the image you added, it does not get displayed. Additionally did also most fields of the issue template got deleted instead of filled. Can you please make sure to add those so that we can get started on looking into that issue. Thanks!
of course

**Comment by Joffcom** [comment]
Hey @gw123,

Don't forget the rest of the template fields, It is always handy to know what version of n8n is being used, How it is running and which database is in use.

**Comment by gw123** [comment]
i run  n8n with  this env:

databasetype ： mysql
n8n commit_id: https://github.com/n8n-io/n8n/commit/26b69b5ffc308185b82d50b9cb0239f7ea9e55f9
EXECUTIONS_PROCESS: main
EXECUTIONS_MODE: queue
DB_TYPE: mysqldb

**Comment by janober** [comment]
So do I understand it correctly that you are building your own n8n version with changes rather than using a version we release?

**Comment by gw123** [comment]
I found some bug on srouce code:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/13729169/226856576-abc3c2a9-5b4d-49bd-92ce-3ed3aea04f1b.png">

`const currentJobs = await queue.getJobs(['active', 'waiting']); `
currentJobs has some  null  undefined， that cause  the error " Cannot read properties of null (reading 'data')"
`executingWorkflowIds.push(...currentJobs.map(({ data }) => data.executionId));`

**Comment by gw123** [comment]
> So do I understand it correctly that you are building your own n8n version with changes rather than using a version we release?

I just add some  kafka with backpress  trigger node .

**Comment by Joffcom** [comment]
Hey @gw123,

I have not seen any other reports of this issue so for now I am going to mark this as closed, If you are still seeing this on the latest version of n8n using our image let me know and I will open it again.
