### ISSUE TITLE
ERROR: Invalid value "undefined" for header "Content-Length"

### ISSUE THREAD

**Issue by rosano** [n8n-io/n8n#5725]
**Describe the bug**
Uploading to YouTube fails on self-hosted installation.

**To Reproduce**

1. Get video file either via *HTTP Request* or *Read Binary Files* (sample file at https://static.rosano.ca/test/n8n.mp4)
2. Send to *YouTube* node with resource *Video*, operation *Upload*, binary property *data*
3. See error

**Expected behavior**
Node should succeed

**Environment (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS via Cloudron v7.3.6
- n8n Version 0.220.0
- Node.js Version ?
- Database system ?
- Operation mode ?

**Additional context**
The same workflow works on my desktop.

Here is a workflow export: [youtube_test.json.zip](https://github.com/n8n-io/n8n/files/11014491/youtube_test.json.zip)

And here is a screenshot of the workflow and error:
<img width="905" alt="Screen Shot 2023-03-20 at 12 32 50" src="https://user-images.githubusercontent.com/1680612/226255775-7a7db338-f78f-4538-8645-b19d40fdc83e.png">

**Comment by Joffcom** [comment]
Hey @rosano 

Can you set `N8N_DEFAULT_BINARY_DATA_MODE` to filesystem and let me know if that works.

**Comment by rosano** [comment]
@Joffcom that worked, thank you! I notice sometimes a memory error would randomly appear, and now I notice on the [documentation](https://docs.n8n.io/hosting/scaling/binary-data/) that this property can solve some memory issues. If you think it would be a good idea to link there from the [Memory-related errors](https://docs.n8n.io/flow-logic/error-handling/memory-errors/#memory-related-errors) page (which was linked from the memory error), I can make a PR.

**Comment by Joffcom** [comment]
Hey @rosano,

Not a terrible idea we will just need to make sure it is listed as self hosted only :)
