### ISSUE TITLE
Editable domain for docker

### ISSUE THREAD

**Issue by Gabbalo** [n8n-io/n8n#5728]
Hi there

I am experience the problem, my n8n docker instance does not recognize the domain it's running on. 
For safety, I configured a domain n8n.domain.com for reverse proxy usage to the exposed docker port. Everything works fine until you need to call for some kind of generated web address, be it a webhook (easily fixable) or a OAuth (not fixable) ... every generated address is created as localhost:port/[...] instead of n8n.domain.com/[...].
For the webhook, you can change the localhost:port part to the proper address - which is absolutely functional, but the OAuth address is coded into the call and thus is not changeable. 
My suggestion would be - at least for docker - to present a ENV to be configured, which transports the proper domain (maybe even including the https:// part as you MIGHT want to NOT configure SSL - there are chaotic-evil persons out there) into the in-docker-configuration, maybe!?

**Comment by janober** [comment]
Thanks a lot for opening this issue, but for me, it looks like it is all already possible and gets used in all of our example setups like this one:
https://docs.n8n.io/hosting/installation/server-setups/docker-compose/#1-install-docker

Here also the docs which list all the available environment variables:
https://docs.n8n.io/hosting/environment-variables/environment-variables/

Can you please check it out.

**Comment by Gabbalo** [comment]
Found everything I need to know
Thank you for the reply and the help :)
