### ISSUE TITLE
Webhook URL with Path Variable creates Path with UUID 

### ISSUE THREAD

**Issue by simgero** [n8n-io/n8n#5738]
**Describe the bug**

If the path has a path variable, there is always a generated UUID in the path of the Webhook. 

**To Reproduce**

If I create the Webhook Trigger with a path like this: "something/:value1" the created path looks like: " .../webhook/f87ff9e0-1bcf-4ae3-9cb8-70967570306f/something/:value1"

If I create the webhook trigger with a path without a path variable, then the webhook looks like this: 
path:"something/novalue"
created path "webhook/something/novalue"

**Expected behavior**

The Path should be the same without a generated UUID like this: 
 " .../webhook/something/:value1"
**Environment (please complete the following information):**

- OS: Ubuntu Linux
- n8n Version 0.220.0]
- Node.js Version v18.12.1.
- Database system mySQL
- Operation mode own

**Comment by Joffcom** [comment]
Hey @simgero,

This is something we are aware of and it is expected behaviour, there is a post on our support forum which explains it here: https://community.n8n.io/t/webhook-enhanced-with-dynamic-elements-in-path-restful-api-approach-got-created/3090/9

Last time I checked there were no plans to change this but I will take a look to see if this has changed.

**Comment by simgero** [comment]
@Joffcom Thanks for your quick answer. I am currently trying to build a small api with n8n and have a Get request that returns all items and would now like to provide a single item endpoint in the classic way, which is usually constructed with path/:id.
But here the path should not behave differently than with POST, GET, etc.

But if this is not possible via the path variables, I can also solve it via the headers, which is less elegant but just as possible.
