### ISSUE TITLE
All executions appearing as failed on 0.221.0

### ISSUE THREAD

**Issue by MeesJ** [n8n-io/n8n#5768]
**Describe the bug**
After I upgraded my n8n instance to 0.221.0, all executions are appearing as failed in the list with all executions, even though in reality the executions did not fail.

**To Reproduce**

1. Go to the homepage of your n8n instance
2. Go to the executions tab (all executions)

**Expected behavior**
I expect the list of executions to show the actual status of executions, instead of letting all executions appear as failed.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- n8n Version 0.221.0
- Node.js Version [e.g. 16.17.0]
- Database system MariaDB
- Operation mode Main

**Additional context**
![](https://user-images.githubusercontent.com/77725857/227367512-a719f252-c2c8-455d-aeb7-656108ffeef6.png)

**Comment by Joffcom** [comment]
Hey @MeesJ 

Is this the same as #5765?

**Comment by MeesJ** [comment]
> Is this the same as #5765?

Partially. The errors that OP showed in his issue do not appear on my side, but I do have the issue with executions appearing as failed. This not only affects workflows with webhooks, but also workflows that use HTTP request nodes. No errors appear in the logs though.

> Are your workflows webhook based as the trigger or a mix of schedule and webhook?

Webhook based as the trigger. Not a mix of schedule and webhook.

**Comment by mzayn** [comment]
i have same issue on this. got error on webhook, also with workflow backup to github

**Comment by netroy** [comment]
if either of you are running n8n via docker or docker-compose, can you please share docker command or the compose file to help us reproduce this?

**Comment by MeesJ** [comment]
Thanks for the swift resolution @netroy and the rest of your team!

**Comment by janober** [comment]
Fix got released with [`n8n@0.222.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.222.0)
