### ISSUE TITLE
Production Webhook URL incorrect

### ISSUE THREAD

**Issue by glhoste** [n8n-io/n8n#5783]
**Describe the bug**
The webhook production URL is wrong in the webhook node, though it is correct in the test URL tab. It shows a domain which is not the one set with WEBHOOK_URL env variable.
It looks like it is just a question of displyaing the correct URL (the actual and correct URL can be called via webhook).

**To Reproduce**

1. Go to 'Webhook node'
2. Click on 'Production URL'
4. See production URL

**Expected behavior**
It should show a domain name compliant with what has been set with the environment variable.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version 0.221.2
- Database system PostgreSQL
- Operation mode : queue

**Additional context**
Self hosted.

**Comment by Joffcom** [comment]
Hey @glhoste 

Can you provide a bit more information? What url are you seeing and what are you expecting it to be? What other environment options do you have set as well?

**Comment by Joffcom** [comment]
Hey @glhoste 

Can you share your environment options?

**Comment by glhoste** [comment]
Hi @Joffcom 
Here it is. I hope it is what you are expecting.

DB_POSTGRESDB_DATABASE | n8n
DB_POSTGRESDB_HOST | postgres
DB_POSTGRESDB_PASSWORD | xxx
DB_POSTGRESDB_PORT | xxx
DB_POSTGRESDB_USER | xxx
DB_TYPE | postgresdb
EXECUTIONS_DATA_MAX_AGE | 336
EXECUTIONS_DATA_PRUNE | true
EXECUTIONS_MODE | queue
GENERIC_TIMEZONE | Europe/Paris
N8N_BASIC_AUTH_ACTIVE | false
N8N_BASIC_AUTH_PASSWORD | xxx
N8N_BASIC_AUTH_USER | xxx
N8N_EDITOR_BASE_URL | https://xxx.com
N8N_METRICS | true
N8N_SMTP_HOST | smtp.gmail.com
N8N_SMTP_PASS | xxx
N8N_SMTP_PORT | 465
N8N_SMTP_USER | xxx
N8N_VERSION | 0.221.2
NODE_ENV | production
NODE_ICU_DATA | /usr/local/lib/node_modules/full-icu
NODE_VERSION | 16.19.1
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
QUEUE_BULL_REDIS_HOST | redis
QUEUE_BULL_REDIS_PORT | 6379
QUEUE_HEALTH_CHECK_ACTIVE | true
TZ | Europe/Paris
WEBHOOK_URL | https://xxx.com
YARN_VERSION | 1.22.19

**Comment by glhoste** [comment]
I found the "problem".
My main n8n instance was in tunnel mode, and it was displaying the subdomain tunnel url
