### ISSUE TITLE
Odoo node models are not correctly fetched when selecting "Custom resource"

### ISSUE THREAD

**Issue by Lanhild** [n8n-io/n8n#5804]
When selecting `Custom resource` inside the Odoo node, models are not loaded because of a permissions issue. [PR#5803](https://github.com/n8n-io/n8n/pull/5803) should fix this.

**Comment by Joffcom** [comment]
Hey @Lanhild,

As there is a PR open rather than draft I will get this issue closed and we can work from the PR.
