### ISSUE TITLE
Postgres: invalid reference to FROM-clause entry for table "xx_workflows_tags"

### ISSUE THREAD

**Issue by brookqin** [n8n-io/n8n#5806]
If you have set the DB_TABLE_PREFIX, following code may not working:

https://github.com/n8n-io/n8n/blob/06d7a46bdcd2173835ede762aff3c37b21f0a530/packages/cli/src/TagHelpers.ts#L35-L49

it will output SQL like this:
```sql
SELECT
	"xx_tag_entity"."createdAt" AS "createdAt",
	"xx_tag_entity"."updatedAt" AS "updatedAt",
	"xx_tag_entity"."id" AS "id",
	"xx_tag_entity"."name" AS "name",
	COUNT ( "xx_workflows_tags"."workflowId" ) AS "usageCount" 
FROM
	"xx_tag_entity" "tag_entity"
LEFT JOIN "xx_workflows_tags" "workflows_tags" ON "xx_workflows_tags"."tagId" = "tag_entity"."id" 
GROUP BY
	"xx_tag_entity"."id"
```

**Comment by Joffcom** [comment]
Hey @brookqin,

Are you seeing an issue with this? At a quick glance we pass in the table prefix if it is set so it looks to be ok to me although I have not tested it. I noticed you mentioned it may not work so I am curious to the reasoning behind that as well.

**Comment by Joffcom** [comment]
Hey @brookqin,

Perfect that error is very useful and was missing from the issue template, I will get an internal ticket created for this shortly.
