### ISSUE TITLE
n8n new

### ISSUE THREAD

**Issue by BurstyRhymes** [n8n-io/n8n#5821]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @BurstyRhymes 

It looks like there is no content other than the template, I am going to close this one for now and we can open it again once it has been edited.
