### ISSUE TITLE
Redis hset misbehavior

### ISSUE THREAD

**Issue by BlackSazha** [n8n-io/n8n#5822]
Sorry, it's hard for me to correctly describe in English, I'll try to describe with screenshots

**Describe the bug**
Redis hset misbehavior
![2023-03-30_11-22-59](https://user-images.githubusercontent.com/35872063/228729350-2f308256-8754-438d-b133-e6268094e558.png)
![2023-03-30_11-25-14](https://user-images.githubusercontent.com/35872063/228729375-0e91862b-f4d7-4c87-aecc-045e2d092a50.png)

**To Reproduce**

![2023-03-30_11-23-08](https://user-images.githubusercontent.com/35872063/228729401-e38ddf80-8210-4a60-b077-bf29f16cc652.png)

**Expected behavior**
![2023-03-30_11-25-47](https://user-images.githubusercontent.com/35872063/228729428-36ce7cc8-b803-4c50-bc8a-ce8d06e67d9d.png)

I understand that this problem has existed for a long time, here is an example - https://community.n8n.io/t/how-to-set-a-key-and-value-in-a-hashmap-using-redis-node/18314

**Environment (please complete the following information):**

- OS: [docker]
- n8n Version [latest]
- Node.js Version [e.g. 16.17.0]
- Database system [pg+redis(queue mode)]]

**Comment by Joffcom** [comment]
Hey @BlackSazha 

This is one that I have looked into a few times and even created a fix for but it turns out there is a way to use it which is why nothing was changed before.

I will get the change put in today now that we have node versioning and it won't break anything for existing users.

**Comment by BlackSazha** [comment]
@Joffcom 
Thank you! Can you tell me how to use it? I need it now
Thank you very much

**Comment by Joffcom** [comment]
Hey @BlackSazha 

I can see if I can dig out how it was done before.

**Comment by Joffcom** [comment]
Hey @BlackSazha,

So the trick is to set the value to be a json object so either pass the value from a previous node or add an expression and do...

`{{ { key: "value", key2: "value2" } }}`

![image](https://user-images.githubusercontent.com/4688521/228764991-96fc76f6-cd10-4cb8-89f4-ead10579b593.png)

This will then give you an output like this...

![image](https://user-images.githubusercontent.com/4688521/228765089-cb2d6620-7cb7-4b6c-905c-ce766c97a783.png)

**Comment by Joffcom** [comment]
Hey @BlackSazha,

I have put in a fix for this so we can finally get it sorted, I am going to get this one marked as closed and once the fix is released we will pop a note on here to let you know.

**Comment by janober** [comment]
Fix got released with [`n8n@0.223.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.223.0)
