### ISSUE TITLE
Discord Node got HTTP 429 status code error message.

### ISSUE THREAD

**Issue by dreamerc** [n8n-io/n8n#5866]
**Describe the bug**

> packages/nodes-base/nodes/Discord/Discord.node.ts

It mentions that the cache error function is not resolving this error.

**To Reproduce**

Run the workflow. (send 38 items once)

```
{
  "name": "Discord_429_Test",
  "nodes": [
    {
      "parameters": {},
      "id": "2eadc0f3-d19e-459c-9536-b8aa1a0d22ce",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        880,
        400
      ]
    },
    {
      "parameters": {
        "jsCode": "const returnItems = [];\nfor (let index = 0; index < 38; index++) {\n  returnItems.push({\n    json: {url:'http://www.example.com/'+index,title:'example'+index}\n  });\n}\nreturn returnItems;"
      },
      "id": "90c07892-c551-4f3b-a8e7-b003e9afe30b",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1100,
        400
      ]
    },
    {
      "parameters": {
        "webhookUri": "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXX",
        "text": "={{ $json.url }} - {{ $json.title }}",
        "options": {}
      },
      "id": "53a5f8c6-dc88-4ef9-8431-eee785604cf2",
      "name": "Discord",
      "type": "n8n-nodes-base.discord",
      "typeVersion": 1,
      "position": [
        1320,
        400
      ]
    }
  ],
  "pinData": {},
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "Discord",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "versionId": "3c8b21c3-c364-43f6-bb35-1aa4957ea3c8",
  "id": "39",
  "meta": {
    "instanceId": "1c41bcdbe16e2483a3675b2ff08436eefaf66d912078c6f85b509ddd71602b77"
```
Discord catch 37, then it failed at 38.

Return :
> Problem in node ‘Discord‘
> 429 - {"global":false,"message":"The resource is being rate limited.","retry_after":1.672}

**Expected behavior**

No Error output, and send 38 items.

**Environment (please complete the following information):**

- OS: Debian 10
- n8n Version : 0.222.0 (from docker-hub n8nio/n8n:0.222.0)
- Database system : sqlite (default)
- Operation mode : own

**Comment by Joffcom** [comment]
Hey @dreamerc,

This doesn't look to be an n8n error, Discord is replying back to say "the resource is being rate limited" you will need to look at sending your items in smaller chunks and maybe adding a wait to the loop to slow down the requests. The other option would be to enable the retry option on the node and set it to retry say 5 times with a 10 second wait between attempts.

You can find more about Discord rate limits here: https://discord.com/developers/docs/topics/rate-limits

For now I am going to mark this one as closed and it if you do feel like this is a bug with n8n let me know and we can look at opening it again.

**Comment by dreamerc** [comment]
> Hey @dreamerc,
> 
> This doesn't look to be an n8n error, Discord is replying back to say "the resource is being rate limited" you will need to look at sending your items in smaller chunks and maybe adding a wait to the loop to slow down the requests. The other option would be to enable the retry option on the node and set it to retry say 5 times with a 10 second wait between attempts.
> 
> You can find more about Discord rate limits here: https://discord.com/developers/docs/topics/rate-limits
> 
> For now I am going to mark this one as closed and it if you do feel like this is a bug with n8n let me know and we can look at opening it again.

After verifying versions between 0.220.1 and 0.221.2, I did not encounter any issues. However, I did notice push request #5351, which seems to be relevant. I suggest considering it as a default feature and testing it accordingly.

**Comment by Joffcom** [comment]
Hey @dreamerc 

We could think about handling rate limiting but we need to put some proper thought into and come up with a design pattern that would work for all nodes.

To get things working it would be a case of doing the auto retry or using split in batches to loop smaller chunks.
