### ISSUE TITLE
Cannot use Jira credentials for self-hosted server

### ISSUE THREAD

**Issue by mvhirsch** [n8n-io/n8n#587]
**Describe the bug**
I want to create a jira node, using new (or previous created) credentials using "self-hosted" server version. It will always state "no credentials got returned". 

**To Reproduce**
1. Create new workflow and add Jira node
2. Select version "self-hosted"
3. create new credentials
4. See error while trying to select project or issue type

**Expected behavior**
Seeing my projects / issue types.

**Environment (please complete the following information):**
 - Docker `n8nio/n8n:0.67.3`

**Comment by janober** [comment]
Sorry, we sadly do not have a self-hosted version of Jira. For that reason can we not debug that issue. 

So we either have to depend on other community memeber which have to either debug themself or which give us access to their self-hosted instance.

**Comment by route100** [comment]
Had the same issue, which was gone after uprading to
Docker 0.68.2

**Comment by janober** [comment]
@mvhirsch can you please confirm that it also works now for you. If not it would be great if you give us access to your self-hosted version so that we can debug.

**Comment by janober** [comment]
Close this issue now as I did not hear back for 19 days and @route100 confirmed that it works for him after having had the same issue before.

**Comment by akamensky** [comment]
Honestly it is not that hard. Self-hosted Jira does not use Basic auth with tokens. Just look at documentation, it is right there -- https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

![image](https://github.com/n8n-io/n8n/assets/985805/f879e37b-fc67-42b2-90d0-5e2db6b9a92f)

![image](https://github.com/n8n-io/n8n/assets/985805/9edbf7ac-2445-4bbc-b91a-ef8d754fd3ee)

**Comment by jvdboog** [comment]
Is it possible to be able to authenticate using "Authorization: Bearer <token_input_in_n8n>"? Is this on the planning? I am running into the same issue.
