### ISSUE TITLE
Custom rest endpoint

### ISSUE THREAD

**Issue by sergwx** [n8n-io/n8n#5880]
When using a custom path for the REST endpoint (N8N_ENDPOINT_REST), value it's not reflected in the interface (Vue.js) and will use the default value /rest, which is not available and the UI will not work.

Error connecting to n8n
Could not connect to server. Refresh to try again
---
Version 0.221.2 @ Ubuntu+Docker

**Comment by Joffcom** [comment]
Hey @sergwx,

That is not a setting I am familiar with, What are you changing it to?
