### ISSUE TITLE
arm64 version does not exist in latest tag in docker hub

### ISSUE THREAD

**Issue by albertopasqualetto** [n8n-io/n8n#5881]
**Describe the bug**
arm64 version does not exist in latest tag in docker hub

**Expected behavior**
It existed in the previous latest release

**Comment by Joffcom** [comment]
Hey @albertopasqualetto 

I suspect this is down to where we removed a release on Friday. For now can you set the version and that should work, last released version would be 0.221.2

**Comment by dongphuchaitrieu** [comment]
It crashes my AWS EC2 setup...

**Comment by Joffcom** [comment]
Hey @dongphuchaitrieu, 

What is crashing your EC2 setup?

**Comment by Joffcom** [comment]
Afternoon,

So we are aware of this and it will be fixed when we do the next release which will likely be `0.222.1`, For now I am going to mark this as closed. Let me know if you have any other questions around this one.
