### ISSUE TITLE
Strava Node : missing hide_from_home field in Activity Update

### ISSUE THREAD

**Issue by ZergRael** [n8n-io/n8n#5882]
Strava API has a boolean `hide_from_home` field in activity update action :
https://developers.strava.com/docs/reference/#api-Activities-updateActivityById
https://developers.strava.com/docs/reference/#api-models-UpdatableActivity

Unfortunately it is missing from the dropdown in n8n 0.221.2 :
![image](https://user-images.githubusercontent.com/1707775/229368132-817a3053-b5b8-4c5c-8ba9-86e707bba1b0.png)

**Comment by Joffcom** [comment]
Hey @ZergRael,

Thanks for this one, I will mark this as closed and we can move the chat to the PR.
