### ISSUE TITLE
Dist folder missing on Windows Desktop installation for MSAL-NODE

### ISSUE THREAD

**Issue by Lequeuxa** [n8n-io/n8n#5889]
Hi,

Just noticed the "Dist" folder for does not exist anymore here: Programs\n8n\resources\app\node_modules\@azure\msal-node

I am on the following N8N for Windows version: 0.216.2

**Comment by Lequeuxa** [comment]
This leads to impossibility to use MS SQL node in any workflow. Copy pasting the folder in the right path from an older N8N version solves the issue.

**Comment by Joffcom** [comment]
Hey @Lequeuxa,

With the Desktop application being removed there is a very good chance that this won't get fixed. The solution now would be to use either npm or docker to run n8n locally.
