### ISSUE TITLE
HTTP request binary mime type set incorrectly in version 0.222.0

### ISSUE THREAD

**Issue by MeesJ** [n8n-io/n8n#5894]
**Describe the bug**
Since I upgraded my n8n instance to 0.222.0 I'm having issues with the HTTP request node. To be specific, when the HTTP request node gets a binary file, it now incorrectly sets the mime type in n8n.

Getting a jpeg file before 0.222.0:
![](https://user-images.githubusercontent.com/77725857/229550400-2e3b4945-3dab-4cc3-bf26-ecc80d7a08d0.png)

Getting a jpeg file after 0.222.0:
![](https://user-images.githubusercontent.com/77725857/229550720-22bb4830-9850-426b-8f7a-804e92ccaa2e.png)

In both cases the content-type header from the file source is set to `image/jpeg`.
![](https://user-images.githubusercontent.com/77725857/229550882-b34587a2-ca12-44e9-9e47-f5584d464e75.png)

**To Reproduce**

1. Create a workflow with a HTTP request node
2. Execute the HTTP request node once you set it to get any binary file from any source
3. See that the mime type in n8n is set to `text/plain`, regardless of the content-type header from the binary file source

**Expected behavior**
I expect n8n to look at the content-type header from the binary file source and use it to set the mime type within n8n.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04.02 LTS
- n8n Version: 0.222.0
- Node.js Version [e.g. 16.17.0]
- Database system: MariaDB
- Operation mode: main

**Additional context**

I have downgraded my n8n instance to 0.221.2 and I can confirm that this bug isn't present there.

**Comment by Joffcom** [comment]
Hey @MeesJ,

Thanks for the report, I have created an internal ticket for this which we will be tracking as `NODE-440`
