### ISSUE TITLE
Create Stripe integration

### ISSUE THREAD

**Issue by YoniFei** [n8n-io/n8n#59]
Stripe API:
https://stripe.com/docs/api

TODO:
-Create triggers for all of the webhooks

Ideally I'd like to try working on this but haven't gotten run/dev to work yet following [these instructions](https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#development-setup)

**Comment by janober** [comment]
@YoniFei Thanks for offering to create the Stripe integration! Can you please post what problems you are having exactly to http://community.n8n.io
I can try to help you and at the same time help all other people who face the same problem in the future. Thanks a lot!

**Comment by janober** [comment]
I did sadly not hear back because of the setup issues. But just want to keep you updated that @lucafaggianelli created a pull-request for a Stripe Trigger-Node not that you also start working on it. Have a great day!

**Comment by YoniFei** [comment]
Ah, I got stuck on side issues, and it seems he is a little farther ahead.
We both basically tried to replicate via the Github node.
Mine is [here](https://github.com/YoniFei/n8n/tree/Stripe-Node)

Though I see the verification still needs to be done.

**Comment by janober** [comment]
Ah very very sorry! Merged the other one a few hours ago and released with n8n@0.26.0
