### ISSUE TITLE
Connection lost docker https but all seems work

### ISSUE THREAD

**Issue by LiquidITGuy** [n8n-io/n8n#593]
I tried to run n8n.io on docker and all seems to work (except webhook run) but when I use https I got "connection lost" message.
After some tries, I can call webhook (https api call), open or save configuration and there is no console nor network error.
But we have this error message and we cannot run workflow.

**To Reproduce**
1. Launch the docker with https 
2. see error

you can see it here : https://n8.sandox.fr (also accessible via http) 
user : test
password : bug
(if needed I can reproduce and create more instance to test on the fly, just ask 👍 )

**Expected behavior**
Think it should work on http and https (I dont investigated if it's an application error, an docker image error, a deployment error ?)

**Environment (please complete the following information):**
 - docker

**Additional context**
Currently working to deploy n8n on caprover for my personal usage, you can find my mr with the caprover file to do the same configuration as me. (https://github.com/caprover/one-click-apps/pull/176)
if I can help, feel free to ask what I can do to help :) 

maybe similar to this closed issue : https://github.com/n8n-io/n8n/issues/315 ?

**Comment by janober** [comment]
Even though you did not mention it above, it looks like you are using Nginx in front of n8n as a reverse proxy. At least that is what the response headers say which makes me believe that the issue you are seeing is the same as this one:
https://community.n8n.io/t/nginx-configuration/111/7

As a general guideline. Please make sure to always search in the forum first and ask questions there. Only if 100% certain that it is a bug, report them here. If we always do that, we can make sure that if people have the same problem in the future, they will find the answers easily by themself. Thanks a lot!

**Comment by LiquidITGuy** [comment]
hi @janober, I searched but did not find this message. Sorry to be noisy, I will check if it fix.
Thanks for your answer.

**Comment by janober** [comment]
Ah no nothing to be sorry for! I just try to keep everything as much together as possible to make it easier for users to help themselves. 

I hope it works. If not simply get back to me.

**Comment by janober** [comment]
Did it fix the issue for you?

**Comment by LiquidITGuy** [comment]
Sadly it does not but I had to try with different nginx configuration (I do not use nginx straight to expose the docker but a generated one by caprover, so it's a little bit more difficult to localise where the problem is :s

I will keep you informed when I will successfully do it

**Comment by janober** [comment]
Ah ok sorry to hear. So to make your search easier. n8n is using EventSource for the communication and that is why that additional configuration is needed and what seems to make problems right now. So if some other tool in caprover also uses that, you can maybe find the solution there.

**Comment by Brandutchmen** [comment]
+1

**Comment by RicardoE105** [comment]
Closing this issue.

**Comment by Libermentix** [comment]
I assume you intended to mention @LiquidITGuy correct? I didn't have any issues with this.

**Comment by RicardoE105** [comment]
yes, @Libermentix my bad.

**Comment by sandrohanea** [comment]
Hi!
I'm having the same issue(caprover + n8n not working with https). @LiquidITGuy , did you managed to fix it?

**Comment by janober** [comment]
@sandrohanea Sorry to hear that you have problems! It is not working at all or it displays you "Connection lost" in the top right corner?

**Comment by LiquidITGuy** [comment]
@RicardoE105  yeah sorry, I'm the one who made the PR to add n8n to one click app on cap rover but I did not find how to solve the problem yet.
I think I will try harder this week :)
@sandrohanea sorry I did not find how to solve it yet.
If I find the solution (or someone else :) ) I would be happy to fix it into the template I make.

I will notify you if I do.

**Comment by chrisdietr** [comment]
Hey @LiquidITGuy , thank so much for the caprover template. Works great (just https would be nice as well) of course!

Here is the nginx config for the n8n image in caprover:

> Templates are built using EJS template pattern. Do not change the areas between <% and %> , unless you really know what you're doing! To revert to default, simply remove all the content.


`<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri$is_args$query_string;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;

        ssl_session_cache   shared:SSL:20m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;


        # Mozilla Intermediate configuration. tweak to your needs.
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
    <%
    }
    %>

        client_max_body_size 500m;

        server_name  <%-s.publicDomain%>;

        # 127.0.0.11 is DNS set up by Docker, see:
        # https://docs.docker.com/engine/userguide/networking/configure-dns/
        # https://github.com/moby/moby/issues/20026
        resolver 127.0.0.11 valid=10s;
        # IMPORTANT!! If you are here from an old thread to set a custom port, you do not need to modify this port manually here!!
        # Simply change the Container HTTP Port from the dashboard HTTP panel
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

    <%
    if (s.httpBasicAuthPath) {
    %>
            auth_basic           "Restricted Access";
            auth_basic_user_file <%-s.httpBasicAuthPath%>; 
    <%
    }
    %>

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

    <%
    if (s.websocketSupport) {
    %>
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
    <%
    }
    %>
        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
                root <%-s.customErrorPagesDirectory%>;
                internal;
        }
}
`

Maybe it's easy to spot for someone on how to adjust this to work with.

**Comment by LiquidITGuy** [comment]
thanks a lot for the help.
I currently upgrade a lot of one click apps I used and I will take all the returns to make it works better :)

**Comment by LiquidITGuy** [comment]
ps : last version of tag seems works totally fine without any customization.
I will make the upgrade tomorrow 👍
