### ISSUE TITLE
after navigating with middle mouse button nodes selection breaks

### ISSUE THREAD

**Issue by yureckey** [n8n-io/n8n#5931]
**Describe the bug**
if navigated using pressed middle mouse button then selection with border isn't working properly. It could be fixed by "old moving" with ctrl+left mouse - after that border selection is working again

**To Reproduce**
1. move view around by moving mouse with pressed middle mouse button.
2.  try to select nodes using border with pressed left button - you can't, you will be moving view again.
3. move around by "old way" with ctrl+left mouse.
4. try select now - it works now.

update:
also node connection (after "middle mouse move") is a bit broken in a same way - when user start moving end point whole view also moves.

**Expected behavior**
user can select nodes with mouse border selection after it used navigation with middle mouse button

**Environment:**
- n8n Version 0.222.1
- browser Chrome 112 on Windows 10

**Comment by Joffcom** [comment]
Hey @yureckey,

Thanks for the report, I have created `N8N-6317` as our internal ticket for tracking this one.

**Comment by LET-Felix** [comment]
https://user-images.githubusercontent.com/80766635/233399821-86a123f0-781c-4ce8-9998-f34c4dc13017.mp4

Video for the Bug in Version 0.225.1

**Comment by Joffcom** [comment]
@yureckey I have let the team know.
