### ISSUE TITLE
misspelling in S3 node option

### ISSUE THREAD

**Issue by yureckey** [n8n-io/n8n#5932]
S3 node ->
Additional Fields ->
Parent Folder Key
tooltip - "Parent file you want to create the file in".
Since it's called "Parent **Folder** Key" then tooltip should be "Parent **folder** you want to create the file in"

**Comment by Joffcom** [comment]
Thanks for the report @yureckey I have put in a PR to resolve this, For now I will mark this as closed. Let me know if you have any other questions on this 🙌🏻

**Comment by janober** [comment]
Fix got released with [`n8n@0.224.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.224.0)
