### ISSUE TITLE
weird behavior when rename and duplicate certain nodes

### ISSUE THREAD

**Issue by yureckey** [n8n-io/n8n#5934]
**Describe the bug**
For a nodes that originally have numbers (I tested on "Magento 2", "MSG91", "S3", "AWS S3", "SIGNL4", "sms77") there is situations when renaming and duplicating leads to browser tab crash.

**To Reproduce**

1. Add any of those nodes "Magento 2", "MSG91", "S3", "AWS S3", "SIGNL4", "sms77". Let's say "S3".
2. duplicate it
3. rename new node to "S3" plus any other symbol(s) but not a number. Let say "S3_"
4. duplicate it
5. observe that new node have name "S3NaN"
6. duplicate new node or "S3_"
7. observe in a few seconds browser tab crash

**Expected behavior**
no NaN names, no browser tab crash

**Environment:**

- OS: Windows 10
- Browser: Chrome 112
- n8n Version: 0.222.1

**Comment by Joffcom** [comment]
Hey @yureckey,

That is nice, I just had a quick play and it has killed my browser. I have created an internal ticket for this which we will be tracking as `N8N-6316`
