### ISSUE TITLE
HTTP Request - 400 after update version

### ISSUE THREAD

**Issue by ShawNexT** [n8n-io/n8n#5937]
**Describe the bug**
HTTP Request response with status code 400 on new version 223, but works on 217.2

**To Reproduce**
1. Insert node in 217.2 and try to run (in Additional context) 
2. Update to 223
3. Get Error 400.

**217.2**
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/7688062/230867109-a3b6cfd3-203c-4b11-a383-846743985388.png">

**223.0**
<img width="1168" alt="image2" src="https://user-images.githubusercontent.com/7688062/230867194-5b43be79-d3da-4ed2-8f08-b27db9c689d9.jpg">

- OS: Ubuntu Linux 22.04
- n8n Version: 223
- Database system: PostgreSQL 15
- Operation mode: queue
- Docker Swarm 

**Additional context**
node:
```json
{
  "meta": {
    "instanceId": "9d78180a58da35811daba08371062d230c7d8fbdcdeac9a1db9e95ff66385ae7"
  },
  "nodes": [
    {
      "parameters": {
        "method": "POST",
        "url": "https://api.openai.com/v1/chat/completions",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Authorization",
              "value": "=Bearer {{ $node[\"API\"].json[\"api\"] }}"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={{ JSON.stringify({   model:  $node[\"Telegram\"].json[\"thread\"][\"model\"],   messages: $json.dialog,  max_tokens: $node[\"Telegram\"].json[\"thread\"][\"tokens\"],   temperature:$node[\"Telegram\"].json[\"thread\"][\"temperature\"],  user: $node[\"Telegram\"].json[\"data\"][\"message\"][\"from\"][\"id\"].toString(), }) }}",
        "options": {
          "response": {
            "response": {
              "fullResponse": true
            }
          },
          "timeout": "600000"
        }
      },
      "id": "2f4c4f1a-5b13-4e99-87e9-9caa970d59b0",
      "name": "Generate Chat Response",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        2700,
        560
      ],
      "alwaysOutputData": true,
      "retryOnFail": true,
      "continueOnFail": true
    }
  ],
  "connections": {}
}

```

**Comment by Joffcom** [comment]
Hey @ShawNexT 

If you paste in the json rather than using an expression does that work?

Are you also sending the same body in both requests?

**Comment by ShawNexT** [comment]
> Are you also sending the same body in both requests?

Yes, it's the same body, I just updated version to 223 and it stopped working.

**Comment by ShawNexT** [comment]
When I rolled back to version 217.2 from 223, everything started working again.

**Comment by Joffcom** [comment]
Hey @ShawNexT 

The bit I was curious about was if you just input text and not use an expression...

The API is returning the error status and it probably down to the wrong information being sent which could be down to the expression being used or maybe something else.

I will do some testing when I am back in tomorrow to see what the cause is.

**Comment by Joffcom** [comment]
Hey @ShawNexT,

Had a quick play and it looks like the issue is likely to be coming back from the `$json.dialog`, If I set the dialog as a string when I use `JSON.stringify` it is escaping it even though it already a string and doesn't need to be touched.

To get around this I changed the expression to wrap the dialog in `JSON.parse($json.dialog)` this then results in the correct data being sent and should solve the issue you are seeing.

Let me know how you get on, If this is the cause then we can look at adding a notice to the docs to mention this.

**Comment by ShawNexT** [comment]
Hi @Joffcom,

So code block starts returning string in 223? 

```
function formatRole(raw) {
  if(raw?.is_bot && (raw?.username !== "GroupAnonymousBot" || raw?.username !== "Channel_Bot")) return 'assistant'
  return `user`
}

const prompt = "here my custom prompt string"
const messages = $('Get Chat History').all(); // this is array from PostgreSQL request

const dialog = messages.reverse().map(reply => ({
  role: formatRole(reply.json.raw),
  content: reply?.json?.text || ""
}))

if(prompt && prompt.length > 3) {


    dialog.unshift({role: 'assistant', content: "Sure, I will respond as per given instructions."})
    dialog.unshift({role: 'user', content: prompt});
    // dialog.unshift({role: 'system', content: 'Dont tell that you are AI.'})
}

return {
 dialog
}
```
This is how it looks like in workflows:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7688062/231137618-7d7e3a3d-eab3-49e5-a20c-0959a03391ac.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/7688062/231137777-a66350d1-86f4-4c22-bc3f-453f6452cd41.png">

**Comment by Joffcom** [comment]
Hey @ShawNexT,

That depends on what you are asking the code node to return, Without seeing the actual data structure it is hard to say but it looks like the code node still returns objects for me. If you can provide the data the code node is using I can take a look, There were some changes to the code node and I suspect expressions recently so it could be either of them.

Have you tried using the suggestion to see if it works?

**Comment by ShawNexT** [comment]
Maybe the problem is with the 'code' node, as it returns a JSON string instead of JSON?

**Comment by Joffcom** [comment]
Hey @ShawNexT,

If you can share what the output of the code node is I can take a look, At the moment though there is not really much else I can do with this one.

I have tested the code node and it still has the ability to return JSON which is something I use multiple times a day when testing issues.

**Comment by Joffcom** [comment]
I am going to mark this as closed for now, If we can get that data to play with we can open it and take another look.
