### ISSUE TITLE
AWS Lambda node is throwing 500.

### ISSUE THREAD

**Issue by kunal5** [n8n-io/n8n#5942]
**Describe the bug**
We have created a workflow where we invoke a lambda function for our use case. For this, we are using the AWS Lambda node. When I click on AWS lambda node one internal n8n's API is failing and throwing 500. Here is the screenshot for the same

<img width="1470" alt="Screenshot 2023-04-11 at 12 53 27 PM" src="https://user-images.githubusercontent.com/15965156/231086337-4ce9c073-9a0c-4c57-802b-16fad2b60cbd.png">

**Whole URL endpoint -** `https://brahmastra.squadstack.com/rest/node-parameter-options?nodeTypeAndVersion=%7B%22name%22:%22n8n-nodes-base.awsLambda%22,%22version%22:1%7D&path=parameters.function&methodName=getFunctions&currentNodeParameters=%7B%22operation%22:%22invoke%22,%22function%22:%22arn:aws:lambda:<deleted-some-part>:load_actions_into_action_log%22,%22qualifier%22:%22$LATEST%22,%22invocationType%22:%22Event%22%7D&credentials=%7B%22aws%22:%7B%22id%22:%2223%22,%22name%22:%22AWS+account%22%7D%7D`

**Request Type:** GET
Response: 
<img width="1470" alt="Screenshot 2023-04-11 at 1 22 59 PM" src="https://user-images.githubusercontent.com/15965156/231093571-1e654812-a7fe-4d61-b1f8-e1cb8b4e84d9.png">

Also, if you see the Network tab screenshot it takes a Time of around 2.5 minutes before throwing 500 error.
Recently only this has started to occur. I tried upgrading n8n version but that also did not fix this. 

**Steps I have taken to fix this**
- Upgrade n8n version from `0.221.2` to `0.222.1`.
- Make sure that AWS user has lambda access or not.

**Environment (please complete the following information):**

- OS: Ubuntu Linux(Amazon AMI)
- n8n Version 0.222.1
- Database system - Postgres
- Operation mode - own
- Self hosted using docker

**Comment by Joffcom** [comment]
Hey @kunal5,

I have just checked my local install on 223.0 and I am not seeing this issue.

![image](https://user-images.githubusercontent.com/4688521/231091162-fca29362-eec7-4566-b75f-ddbf9d0fce19.png)

Can you share a bit more about your setup? Are you going through a reverse proxy and is it caching anything? It might also be worth checking the n8n server log to see if there is anything outputted there. If possible I would also recommend trying it as directly as possible, So if you have an IP and port for the container try that or if possible create an SSH tunnel to the host and see if you can connect that way.

**Comment by kunal5** [comment]
Hey @Joffcom ,
I tried upgrading n8n to 0.223.0 but still got the same error. No, we are not caching anything. I tried searching for n8n container logs but I was not able to find anything worthy.

**Comment by Joffcom** [comment]
Hey @kunal5,

Did you try any direct connection and are you using a reverse proxy at all? As I can't reproduce it I am going to need more information around your setup, I guess it could also be the region for the credentials or the credential itself.

**Comment by Joffcom** [comment]
Hey @kunal5,

That looks to be ok, So in that setup Traefik is a reverse proxy but shouldn't be causing any issues. Have you checked the region in the credentials is correct? I found I can get a similar issue if I change my region so it could just be a credential issue.

**Comment by kunal5** [comment]
@Joffcom, Yes the region is correct... The correct region is `ap-south-1`. I tried changing the region to `us-east-1`. In this case, I was able to see lambda functions in the `us-east-1` region. But when I switch back to `ap-south-1` then again `Loading` is coming which eventually returns a 500 response. What else can I check regarding this region?

**Comment by Joffcom** [comment]
Hey @kunal5,

I guess if changing the region works it is a good sign and sounds like less like a bug, I will set up a Lambda in ap-south-1 and see if I get the same issue there.

**Comment by kunal5** [comment]
but @Joffcom  for the past 3-4 months, ap-south-1 was working perfectly fine. But since Friday, the issue started to come up.

**Comment by Joffcom** [comment]
Hey @kunal5,

That is good to hear I am glad we didn't break anything, Thanks for the update.
