### ISSUE TITLE
n8n throws http 500, when trying to select notion database from list for Notion Node

### ISSUE THREAD

**Issue by kamit-transient** [n8n-io/n8n#5988]
I am trying to select notion databases from the list on the Notion node but it's throwing HTTP 500 error:

![image](https://user-images.githubusercontent.com/12546338/232320743-c5a6810c-a7f7-4ba9-a59c-c74e992b67b3.png)

Please note, 

I have already added the notion credential and its showing connection as successful as well, please check below image:
![image](https://user-images.githubusercontent.com/12546338/232321652-ffdc175f-cc7b-4a45-a168-76f2806e2fb1.png)

## Error log on console

```

GET | https://<hostname>.com/rest/nodes-list-search?nodeTypeAndVersion={"name":"n8n-nodes-base.notion","version":2}&path=parameters.databaseId&methodName=getDatabases&currentNodeParameters={"notionNotice":"","version":2,"resource":"databasePage","operation":"create","databaseId":{"__rl":true,"mode":"list","value":""},"title":"Time  Machine: Peking (Beijing) in 100 years ago, Ancient China  (Around1910-1920)","simple":true,"propertiesUi":{"propertyValues":[{"key":"","title":"","richText":false,"textContent":"","text":{},"phoneValue":"","multiSelectValue":[],"selectValue":"","statusValue":"","emailValue":"","ignoreIfEmpty":false,"urlValue":"","peopleValue":[],"relationValue":[],"checkboxValue":false,"numberValue":0,"range":false,"includeTime":true,"date":"","timezone":"default","fileUrls":{}}]},"blockUi":{},"options":{}}&credentials={"notionApi":{"id":"1","name":"Notion account"}}
-- | --




```
![image](https://user-images.githubusercontent.com/12546338/232321540-d5a245bf-e370-4237-b422-ed4627448473.png)

**Environment (please complete the following information):**

- n8n Version: 0.221.2 

**Additional context**

**Comment by Joffcom** [comment]
Hey @kamit-transient 

Have you shared your notion page with your n8n integration?

**Comment by kamit-transient** [comment]
@Joffcom 
yes. that's the reason credentials able to connect to the notion. plz, check the attached image for reference.

**Comment by Joffcom** [comment]
Hey @kamit-transient 

I can't see an image of the integration being shared with the notion page. Can you grab a shot of that as well?

**Comment by kamit-transient** [comment]
@Joffcom please find below.

![image](https://user-images.githubusercontent.com/12546338/232373846-abad66ad-e3f2-4009-8f13-c7c8ab9b18d4.png)

**Comment by kamit-transient** [comment]
@Joffcom 
Also, would you please share a typical config for n8n server,  which you use on your server?

**Comment by Joffcom** [comment]
Hey @kamit-transient 

That looks right so far, I will check one of my instances this morning to see if it is a general issue.

You can find different configurations in our docs but there isn't really a "typical" one as it depends on how you plan to run n8n and what you are using.

Are you able to share more about your current config as well? Is it docker, npm, from source? Are you using a reverse proxy?

**Comment by kamit-transient** [comment]
sure @Joffcom 

my n8n instance is running behind **Nginx proxy manager** and apart from n8n's built in auth, its is also protected by **authelia** 

Also I am using **docker-compose** to run all these containers and they are on **same docker network** .


Here is my docker-compose of n8n:


``

version: '3.1'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgresql
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE= the_db_name
      - DB_POSTGRESDB_USER=the_user
      - DB_POSTGRESDB_PASSWORD=the_password
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - WEBHOOK_URL=https://n8n.exemple.com
    volumes:
      - ./.n8n:/home/node/.n8n
    # Wait 5 seconds to start n8n to make sure that PostgreSQL is ready
    # when n8n tries to connect to it
    command: /bin/sh -c "sleep 5; n8n start"
networks:
 default:
  external: true
  name: <the tetwork name>
``

**Comment by Joffcom** [comment]
That looks ok in theory, I have just done a quick test on my local setup and I am able to list the databases.

![image](https://user-images.githubusercontent.com/4688521/232434215-5fb0b0b1-bd3f-4535-92fe-7bd234cdcbc1.png)

Have you tried clicking on the 3 dots and selecting refresh menu to see if that helps?
![image](https://user-images.githubusercontent.com/4688521/232434474-f6ffae77-e2ee-4dec-87b5-5ba63b668be0.png)

Is "Time Machine....." the name of your database? Just wondering if maybe there is something odd in the name we don't like or are not handling properly.

It would also be worth testing a direct connection to your instance bypassing the reverse proxy to see if that works then we can start to narrow down where the issue is coming from.

**Comment by kamit-transient** [comment]
@Joffcom I debugged the issues and found that HTTP 500 was thrown **due to the limitation on the size of  the request body** by proxy server.

**Comment by Joffcom** [comment]
Hey @kamit-transient,

Thanks for the update that is useful to know.
