### ISSUE TITLE
Using mouse wheel click to drag a workflow breaks the mouse button drag behavior

### ISSUE THREAD

**Issue by umanamente** [n8n-io/n8n#5992]
**Describe the bug**

I'm using a mouse wheel button to drag the diagram (I assume that the expected method is to hold a Ctrl button). 
This breaks the "select" behavior: left mouse button starts to drag the diagram, so I couldn't select or connect the nodes anymore until I refresh the page.

**To Reproduce**

1. Go to any workflow
2. Click and hold the mouse wheel button and move the mouse to drag the workflow diagram
3. Release the mouse wheel
4. Click and hold left mouse button and move it around to select nodes
5. The workflow diagram is getting dragged around instead of holding still

**Expected behavior**

**Environment (please complete the following information):**

- OS: `Windows 10`
- n8n Version `0.222.1`
- browser `Chrome (latest)`

**Comment by Joffcom** [comment]
Hey @umanamente 

Is this the same issue as #5931?

**Comment by Joffcom** [comment]
Perfect, in that case I am going to close this one as we are already aware of this and we will update the other issue once this is resolved.
