### ISSUE TITLE
ERPNext selfhosted site not working

### ISSUE THREAD

**Issue by NayanGajjar** [n8n-io/n8n#5999]
ERP version is: v14
The self-hosted erp site is not getting connected with the n8n desktop app as well or as docker self-hosted setup.

![image](https://user-images.githubusercontent.com/122445476/232746227-10e7fc3a-10e7-4074-9f4a-c479387fa369.png)

**Comment by Joffcom** [comment]
Hey @NayanGajjar,

Are you able to connect to ERPNext using curl or with the http request node from n8n?

**Comment by NayanGajjar** [comment]
yes with HTTP requests it's getting connected to our ERP.

**Comment by Joffcom** [comment]
Interesting, Was that with the http request node to the API? For the credential test we use `/api/resource/Doctype` would be interesting to see what the node returns for that.

**Comment by NayanGajjar** [comment]
we have tried using http request as below snapshot.

![image](https://user-images.githubusercontent.com/122445476/232769294-5a0bbbd0-b689-4942-971e-cb48bbdc3d80.png)

**Comment by Joffcom** [comment]
Hey @NayanGajjar,

That is interesting we expect the response to be json, Is that json data or is it html / xml?

**Comment by NayanGajjar** [comment]
it was json response

eg.

JSON
![image](https://user-images.githubusercontent.com/122445476/232771423-69c981c1-80d2-4045-9dfc-14aa55df4c16.png)

Table
![image](https://user-images.githubusercontent.com/122445476/232771484-35710aca-7b2c-48a6-a214-259708081080.png)

**Comment by NayanGajjar** [comment]
yeah, we misread it but the response is there using an HTTP request.
we have opened the HTML file in a web browser it's not showing any error.  browser response is attached in pdf file.

[n8n.pdf](https://github.com/n8n-io/n8n/files/11261939/n8n.pdf)

**Comment by Joffcom** [comment]
Hey @NayanGajjar,

That looks like the API is not working for your domain, This doesn't appear to be a fault with n8n itself and is likely to be an ERPNext configuration issue.

Do you have the API enabled or maybe a custom api route?

**Comment by Joffcom** [comment]
Hey @NayanGajjar,

Quick update, If you ignore what the credential test says and try to use the node does that work?

**Comment by NayanGajjar** [comment]
seems it's giving a response via HTTP and same we are already doing quite a few things using API from Postman.

Quick update, If you ignore what the credential test says and try to use the node does that work?-- didn't get that can you please elaborate a little on this so we  can check

**Comment by NayanGajjar** [comment]
just FYI.. via HTTP it's working.

![image](https://user-images.githubusercontent.com/122445476/232971708-016aa9bc-9106-4bd6-8811-844aa276fb65.png)

**Comment by Joffcom** [comment]
Hey @NayanGajjar 

So I think the issue is actually the endpoint we use for the credential test.

If you ignore what the credential says and try to use the node anyway does it work?

**Comment by NayanGajjar** [comment]
What does it mean by use node?

if its the same as HTTP or using from canvas it does not allow me to set up the cred

**Comment by Joffcom** [comment]
Hey @NayanGajjar 

Add the ERPNext node to your workflow, select the ERPNext Credential that can't connect and see if that works. It doesn't matter that the credential says it can't connect, click save and try using it. 

During my testing yesterday I found that this works.

**Comment by NayanGajjar** [comment]
yeah on that way it is working.. hope it didn't cause any issues in workflow.?

**Comment by Joffcom** [comment]
Hey @NayanGajjar,

It won't cause any issues with the workflow but the good news is I fixed this locally yesterday when I noticed it so I will get a proper fix in place for it shortly.

For now I am going to mark this one as closed though.
