### ISSUE TITLE
Manage tags are not working with a table prefix

### ISSUE THREAD

**Issue by danyflorez** [n8n-io/n8n#6019]
**Describe the bug**
The "Manage tags" view is not working, this is due to a failure in the "/tags" GET api, the reason is that we have a tablePrefix='n8n_' and the query typeorm is generating is incorrect.

The problem is located on TagsController class (tags.controller.ts)

```
	// Retrieves all tags, with or without usage count
	@Get('/')
	async getAll(req: TagsRequest.GetAll): Promise<TagEntity[] | ITagWithCountDb[]> {
		const { withUsageCount } = req.query;
		if (withUsageCount === 'true') {
			return this.tagsRepository
				.find({
					select: ['id', 'name', 'createdAt', 'updatedAt'],
					relations: ['workflowMappings'],
				})
				.then((tags) =>
					tags.map(({ workflowMappings, ...rest }) => ({
						...rest,
						usageCount: workflowMappings.length,
					})),
				);
		}

		return this.tagsRepository.find({ select: ['id', 'name', 'createdAt', 'updatedAt'] });
	}
```

The sql generated by typeorm is the following:

```
SELECT n8n_tag_entity.id AS `id`, n8n_tag_entity.name AS `name`, 
		n8n_tag_entity.createdAt AS `createdAt`, n8n_tag_entity.updatedAt AS `updatedAt`, 
        COUNT(n8n_workflows_tags.workflowId) AS `usageCount` 
FROM `n8n_tag_entity` `tag_entity` 
	LEFT JOIN `n8n_workflows_tags` `workflows_tags` ON n8n_workflows_tags.tagId = `tag_entity`.`id` 
GROUP BY n8n_tag_entity.id;
```

Here we can see that the alias of the table is `tag_entity` but it's trying to select it as`n8n_tag_entity.id AS `id``

![image](https://user-images.githubusercontent.com/16990780/233155853-ce913ddc-3ac1-4240-b449-d2a0ccb4a2fa.png)

**To Reproduce**

Set the table prefix as 'n8n_'

1. Go to a Workflow
2. Click on the tags
3. Click on "Manage tags"
4. The view keeps loading forever.

**Expected behavior**
The Tags view loads correctly

**Environment (please complete the following information):**

  DB_TYPE: 'mysqldb'
  DB_TABLE_PREFIX: 'n8n_'
  DB_LOGGING_ENABLED: 'true'
  DB_LOGGING_OPTIONS: 'all'

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version 0.222.3
- Node.js Version 16
- Database system mysql
- Operation mode: own

**Additional context**
Error on the console:

```
query: SELECT n8n_tag_entity.id AS `id`, n8n_tag_entity.name AS `name`, n8n_tag_entity.createdAt AS `createdAt`, n8n_tag_entity.updatedAt AS `updatedAt`, COUNT(n8n_workflows_tags.workflowId) AS `usageCount` FROM `n8n_tag_entity` `tag_entity` LEFT JOIN `n8n_workflows_tags` `workflows_tags` ON n8n_workflows_tags.tagId = `tag_entity`.`id` GROUP BY n8n_tag_entity.id
query failed: SELECT n8n_tag_entity.id AS `id`, n8n_tag_entity.name AS `name`, n8n_tag_entity.createdAt AS `createdAt`, n8n_tag_entity.updatedAt AS `updatedAt`, COUNT(n8n_workflows_tags.workflowId) AS `usageCount` FROM `n8n_tag_entity` `tag_entity` LEFT JOIN `n8n_workflows_tags` `workflows_tags` ON n8n_workflows_tags.tagId = `tag_entity`.`id` GROUP BY n8n_tag_entity.id
error: Error: Unknown column 'n8n_tag_entity.id' in 'field list
```

**Comment by danyflorez** [comment]
Got it, do you know when this version is gonna be released? 

The last version released on npm is:

n8n
0.222.3 • Public • Published 5 days ago

**Comment by janober** [comment]
The last version released on npm is actually `0.225.0`:
https://www.npmjs.com/package/n8n?activeTab=versions
but the version with the "latest" tag is `0.222.3`. Meaning you can already pull any of that versions by specifically defining them.

Can you please give that a try. Thanks!

**Comment by danyflorez** [comment]
@janober Now I'm 0.225.0, working pretty good, thanks

**Comment by janober** [comment]
Great to hear. Have fun!

**Comment by janober** [comment]
Great to hear. Have fun!

**Comment by janober** [comment]
Also linking the in parallel opened community issue:
https://community.n8n.io/t/manage-tags-view-is-not-working-with-a-table-prefix/25377/2

**Comment by janober** [comment]
Also linking the in parallel opened community issue:
https://community.n8n.io/t/manage-tags-view-is-not-working-with-a-table-prefix/25377/2
