### ISSUE TITLE
Docker hub "latest" tag is not been updated

### ISSUE THREAD

**Issue by lpadula** [n8n-io/n8n#6037]
Hello! The Docker Hub "latest" tag hasn't been updated for a while.

**Comment by netroy** [comment]
Hi @lpadula, the `latest` on Docker Hub is 6 days old. 

There are newer releases on github, but those are all currently release-candidates, and would only be marked as `latest` after we have tested them for a while.

**Comment by Joffcom** [comment]
Hey @lpadula 

We have a new release process so latest will be an older more stable release and next will be the newest release that may contain issues. I would expect latest to updated weekly once we are happy that next is good to be promoted.

**Comment by lpadula** [comment]
Ok thanks!

**Comment by kimtiago** [comment]
What tag is supposed to use to always have the last version?

Is it "nightly"?

**Comment by netroy** [comment]
> What tag is supposed to use to always have the last version?
> 
> Is it "nightly"?

@kimtiago running `nightly` isn't recommended at all, as it's barely tested to guaranty any stability, and the image isn't 100% compatible with release images. 

If you want the latest release, **please use the tag `next`**. These are expected to be stable releases, that would get retagged as `latest` only after we've tested the release for a week or two. 

we'll be documenting this and communicating it with the community over the next days.
