### ISSUE TITLE
cannot compile with Docker

### ISSUE THREAD

**Issue by robertodamiani** [n8n-io/n8n#6040]
**Describe the bug**
Compile process takes a very long time, and ends with an error when using n8n-custom Dockerfile.

**To Reproduce**

1. docker build -f docker/images/n8n-custom/Dockerfile .
2. after a long time (4 hrs on my machine), an error occur on command `pnpm build`

```
#22 208.6 n8n-nodes-base:build: info Detected 311 credentials {}
#22 218.5 n8n-nodes-base:build: debug No codex available for: N8nTrainingCustomerDatastore.node.js {}
#22 218.5 n8n-nodes-base:build: debug No codex available for: N8nTrainingCustomerMessenger.node.js {}
#22 218.6 n8n-nodes-base:build: debug No codex available for: StickyNote.node.js {}
#22 224.5 n8n-nodes-base:build: debug No codex available for: WhatsApp.node.js {}
#22 224.9 n8n-nodes-base:build: debug Loaded all credentials and nodes from n8n-nodes-base { credentials: 312, nodes: 384 }
#22 14298.8 n8n-editor-ui:build: ERROR: command finished with error: command (/data/packages/editor-ui) pnpm run build exited (1)
#22 14298.8 command (/data/packages/editor-ui) pnpm run build exited (1)
#22 14298.8  ERROR  run failed: command  exited (1)
#22 14298.8 n8n-editor-ui:build:  ELIFECYCLE  Command failed with exit code 1.
#22 14298.8
#22 14298.8  Tasks:    4 successful, 5 total
#22 14298.8 Cached:    0 cached, 5 total
#22 14298.8   Time:    3h58m15.919s
#22 14298.8
#22 14299.6  ELIFECYCLE  Command failed with exit code 1.
#22 ERROR: executor failed running [/bin/sh -c pnpm build]: exit code: 1
------
 > [builder 12/23] RUN pnpm build:
------
executor failed running [/bin/sh -c pnpm build]: exit code: 1
```

**Expected behavior**
Compile succedes.

**Environment (please complete the following information):**

- OS: Windows 10
- n8n Version: 0.222.3
- Node.js Version: FROM n8nio/base:16

Also tried in GitLab shared runners, same behavior.

**Comment by Joffcom** [comment]
Hey @robertodamiani 

Last time I went through this process I think it only took about 10 minutes to complete.

What sort of hardware are you running in it could be a resource issue I know we had an issue with memory using during the build process a few versions back.

Could be worth making sure you are using the lastest master branch.

**Comment by robertodamiani** [comment]
Hi @Joffcom,

I tried adding more RAM to the WSL and it worked.

It looks like this behavior happens when RAM is not enough.

Thanks for yor help.
