### ISSUE TITLE
Execute Workflow Node : Converting circular structure to JSON

### ISSUE THREAD

**Issue by airmoi** [n8n-io/n8n#6046]
**Describe the bug**
I have a workflow running a subprocess (using Execute workflow) which use to run fine for over a year.
Since latests update (can't tell which one as I made a jump from 210 to 224) this workflow throws a "Converting circular structure to JSON"
The sub process does not produce any error.

Here is the full error thrown : 
`TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Object'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:847:17)
    at process.target.send (node:internal/child_process:747:19)
    at /usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:257:17
    at new Promise (<anonymous>)
    at sendToParentProcess (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:256:12)
    at Object.additionalData.executeWorkflow (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:169:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/ExecuteWorkflow/ExecuteWorkflow.node.js:172:34)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:653:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:592:53`

**To Reproduce**
Not sure how to reproduce.
The sub process may produce different output (some of them are HTTP request)

**Expected behavior**
No error ?

**Environment (please complete the following information):**

- OS: Official Docker image n8nio/n8n:0.224.1
- n8n Version : 0.224.1
- Node.js Version : v16.19.1
- Database system : mysql
- Operation mode: own

**Comment by Joffcom** [comment]
Hey @airmoi,

I thought we had fixed this, Do you always see this when the workflow runs and if you run a different sub workflow do you get the same error?

**Comment by airmoi** [comment]
It always happen.
I did not try with another sub workflow.

On the other hand, I set the sub-workflow to log data on successful execution, but nothing appears in the execution log so the problem may be with the sub-flow

**Comment by Joffcom** [comment]
Hey @airmoi,

It could be, Can you try with another workflow that would then narrow down the scope a bit.

**Comment by airmoi** [comment]
Ok, I will try that and let you know what I find

**Comment by vbezhenar** [comment]
We have a similar issue. We updated from 0.209.4 to 0.231.0 and we encounter those errors.

Here's one error among others (logged to discord):
```
Workflow: JOB_GetAppointment_Dostyk_V2
URL: https://n8n-test.cmctech.pro/workflow/145/executions/874101
Node: 
Message: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
Stack: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:847:17)
    at process.target.send (node:internal/child_process:747:19)
    at /usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:257:17
    at new Promise (<anonymous>)
    at sendToParentProcess (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:256:12)
    at process.<anonymous> (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:274:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Workflow: JOB_GetAppointment_Green_V2
URL: https://n8n-test.cmctech.pro/workflow/132/executions/874096
Node: 
Message: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
Stack: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:159:20)
    at process.target._send (node:internal/child_process:847:17)
    at process.target.send (node:internal/child_process:747:19)
    at /usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:257:17
    at new Promise (<anonymous>)
    at sendToParentProcess (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:256:12)
    at process.<anonymous> (/usr/local/lib/node_modules/n8n/dist/WorkflowRunnerProcess.js:274:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It shows in the interface as

```
Issues:
Execution stopped at this node (n8n may have run out of memory while executing it. More context and tips on how to avoid this [in the docs](https://docs.n8n.io/flow-logic/error-handling/memory-errors))
Execution Error.
```

though I'm pretty sure that there's enough memory and it's not memory error.

What I've found is that we had some errors before related to DNS:

```
Issues:

getaddrinfo EAI_AGAIN lkp-akm.dmed.kz (getaddrinfo EAI_AGAIN lkp-akm.dmed.kz)
Execution Error.
```

So the issue above could've been caused by improper error handling for DNS resolution.

**Comment by vbezhenar** [comment]
@Joffcom our node just does HTTP POST with some very small JSON object as a payload and receives very small text string which it stores in a property.

We used "main" mode in the past but after update I switched to "own" mode.

I'm not sure about binary data stuff, I never researched it. Basically it runs in kubernetes pod without any persistent storage and connects to postgres database (which runs in another pod).

**Comment by Joffcom** [comment]
Hey @vbezhenar 

I guess that will be fairly easy to test, it will be a bit worrying if we have messed up the dns but this issue seemed to be when executing sub workflows so there could be 2 issues at play.

Will do some testing and see what we can find. Which http request node version are you using? If you copy / paste it to a text editor it will show the version in the typeVersion key.

**Comment by vbezhenar** [comment]
Hey. Here's full JSON for failing node:

```json
{
  "meta": {
    "instanceId": "d46ac6b8dafda1a6acb71df97a56085f5ce64cf88d9213529258ac8a8cee4ec3"
  },
  "nodes": [
    {
      "parameters": {
        "requestMethod": "POST",
        "url": "={{ $json[\"mis_url\"] }}api/Authentication/SignInExternalApp",
        "allowUnauthorizedCerts": true,
        "responseFormat": "string",
        "jsonParameters": true,
        "options": {},
        "bodyParametersJson": "={ \"systemUsername\": \"{{ $node[\"GetOrgByID\"].json[\"mis_username\"] }}\", \"systemPassword\": \"{{ $node[\"GetOrgByID\"].json[\"mis_password\"] }}\" }"
      },
      "name": "Auth dmed",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 2,
      "position": [
        1520,
        660
      ],
      "id": "7af04216-82c8-4015-a3dc-b7e8607fbfa4",
      "retryOnFail": true
    }
  ],
  "connections": {}
}
```

**Comment by vbezhenar** [comment]
Before this node there's one node that does simple postgres request, one IF node and one node with JS text which doesn't do anything really interesting, I'll add it for completeness:

```
const data = new Date(Date.now() - 86400000 * 2)
data.setHours(8, 0, 0, 0);
const date2 = new Date(Date.now() + 86400000 * 2)
date2.setHours(20, 0, 0, 0);


for (const item of $input.all()) {
  item.json.BeginDate = data;
  item.json.EndDate = date2;
  item.json.ReceiverMoID= item.json.mis_id.split('\r\n'),
  item.json.service_code = item.json.service_code.split('\r\n')
}
return $input.all();
```

**Comment by Joffcom** [comment]
Hey @vbezhenar,

Can you try adding a new http request node to your workflow and use that to see if the same issue occurs, It looks like your current one is v2 and the node itself is on v4.1 so it could be that something we changed when making a new version has broken the older one.

**Comment by airmoi** [comment]
Hi, 

Sorry it's been a while, I've been too busy to dig into this earlier.

Today I did some more testing and figure out this issue occurs (in my case), when the remote server which il called is down.
In this particular case, the node will throw an error (even with the "never error" option activated.  

If you just place a "Code" node right after, you will get the Converting circular structure error 
With other node it gives a "Not Enough Memory" on the GUI
```json
{
  "meta": {
    "instanceId": "4509641b60cb4837bca3c2313226a61f0321b90b4d7b85b721431daf0f6a9e9f"
  },
  "nodes": [
    {
      "parameters": {
        "jsCode": "// Loop over input items and add a new field called 'myNewField' to the JSON of each one\nfor (const item of $input.all()) {\n  item.json.myNewField = 1;\n}\n\nreturn $input.all();"
      },
      "id": "85f6978c-06d6-4bc4-97bd-79f6ccb16ff4",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "position": [
        1520,
        520
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://server-down.covid19-out.com/fmi/admin/api/v2/user/auth",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Authorization",
              "value": "=basic dG90bzp0YXRh"
            }
          ]
        },
        "options": {
          "allowUnauthorizedCerts": true,
          "response": {
            "response": {
              "neverError": true,
              "responseFormat": "json"
            }
          }
        }
      },
      "id": "fba0ce15-17e3-4683-a5d1-57d0a5ac7600",
      "name": "failing request",
      "type": "n8n-nodes-base.httpRequest",
      "position": [
        1300,
        520
      ],
      "typeVersion": 4.1,
      "alwaysOutputData": true,
      "continueOnFail": true
    },
    {
      "parameters": {},
      "id": "4fbac639-375c-460c-9b3b-156469ecb598",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "position": [
        1100,
        520
      ],
      "typeVersion": 1
    }
  ],
  "connections": {
    "failing request": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "failing request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}

```
