### ISSUE TITLE
Newest Version as reported in N8N Application is not released

### ISSUE THREAD

**Issue by rstens** [n8n-io/n8n#6066]
**Describe the bug**
In the tool I get a notification that there is a new version available, but this new version is not released. Today the tool is reporting that version **0.224.2** is available but only version **0.222.3** is available to install.

See: 
- https://www.npmjs.com/package/n8n
- https://github.com/n8n-io/n8n/releases

It looks like the pre-releases are reported in the tool, instead of the actual latest releases.

**Expected behavior**
If the tool reports that there is a new version available, it should be available for implementation.
Or, alternatively, it should only report on **latest** releases.

**Comment by Joffcom** [comment]
Hey @rstens 

You have an interesting point there although 0.225.1 is the latest you can install from npm or Dockerhub.

How are you running n8n currently?

**Comment by rstens** [comment]
I run N8N in Kubernetes (OpenShift). Full bore install with psql, redis, worker, webhook and main pods, I build my own image (due to OpenShift requirements) and I install `npm install -g n8n` latest (which happens to be [0.222.3](https://www.npmjs.com/package/n8n/v/0.222.3) ) . So now we have 0.222.3 as latest, N8N (the application) reports that [Version 0.224.2](https://docs.n8n.io/reference/release-notes.html#n8n-0-224-2) is available, but actually [0.225.1](https://www.npmjs.com/package/n8n/v/0.225.1) seems to be the latest version.

I have a workflow that detects a version change and I'll will rebuild my N8N image to keep everything up-to-date (first in test for verification of course). This has been working flawlessly for quite some time now. My workflow queries https://registry.npmjs.org/n8n/latest to obtain the latest version and compares that with the current version and trigger a rebuild of the image if different. 

So it looks like new versions are not propagated to npmjs.com with the correct label 'latest', and N8N (the application) is looking at something else. So it is a bit confusing, because this is the first time I ran into that.

**Comment by Joffcom** [comment]
So the change could be where we have changed how we do release to provide more stability.

The "latest" version should be 222, "next" is 224 and then we have 225. The product will display the "next" version which can be installed using the version tag or next.

We now promote to latest when we consider a version to be stable, the choice is there to upgrade to the latest release this means you can now use the latest tag to have hopefully a more stable experience or you can use Next if you want new then the other version if you want to see what is about to come out.

At first I was thinking we should maybe change the notification but it does seem to be correct, we have just not made a post yet about the new versioning which is causing a bit of confusion.

**Comment by rstens** [comment]
I'll be more than happy to just stay with "latest" for my purposes. Now that I know how it actually works, I am fine. Was just confused.
