### ISSUE TITLE
Cannot connect my account to oAuth 2.0 because of 403 Error on rest/oauth2-credential/callback

### ISSUE THREAD

**Issue by todaysday** [n8n-io/n8n#6067]
**Describe the bug**
I'm trying to connect to Upwork API oAuth 2.0 https://developers.upwork.com/#authentication_oauth-20
A week ago everything worked well but now HTTP status 403 always in the end instead of "Account connected".
The url of the popup window is https://n8n-production-247e.up.railway.app/rest/oauth2-credential/callback?code=33cae5c{removed_by_me}f36904b&state=eyJ0b2tlbiI6ImhWT2{removed_by_me}EN2WSIsImNpZCI6IjEifQ%3D%3D

**To Reproduce**

1. Create HTTPrequest node
2. Choose Generic Auth Type OAuth2 API
3. Fill: 
- Grant Type: Autorization code
- Access Token URL: https://www.upwork.com/ab/account-security/oauth2/authorize
- Access Token URL: https://www.upwork.com/api/v3/oauth2/token
- Client ID: Your_Client_ID
- Client Secret: Your_Client_Secret
- Authentication: Header
4. Click: Connect my Account
5. First time Pop-up opens with url https://www.upwork.com/ab/account-security/oauth2/authorize?client_id=c9d44{removed_by_me}b2646e6&redirect_uri=https%3A%2F%2Fn8n-production-247e.up.railway.app%2Frest%2Foauth2-credential%2Fcallback&response_type=code&state=eyJ0b2tlbiI6Il{removed_by_me}3D%3D&scope 
Next time it just redirects to next one
6. Pop-up with url https://n8n-production-247e.up.railway.app/rest/oauth2-credential/callback?code=931d97386{removed_by_me}bd0c6ff&state=eyJ0b2tlbiI6IlNlTFpQblVlLUtnZHY{removed_by_me}yb2ZzUGc0USIsImNpZCI6IjEifQ%3D%3D with message  
"Error:
HTTP status 403
Failed to connect. The window can be closed now."
7. There is no message account connected and there is not available to use token for HTTPResuest node requests 

**Expected behavior**
Account connected 

**Environment (please complete the following information):**

- OS: last test done on Railway.app
- n8n Version ive tested a lot of versions starting from 0.171.0 and until 0.225.0

**Additional context**
Everything works like a charm on Postman because Postman done care about 403 from ttps://n8n-production-247e.up.railway.app/rest/oauth2-credential/callback and just use code=931d97386{removed_by_me}bd0c6ff&state=eyJ0b2tlbiI6IlNlTFpQblVlLUtnZHY{removed_by_me}yb2ZzUGc0USIsImNpZCI6IjEifQ%3D%3D this part to get all needed

**Comment by Joffcom** [comment]
Hey @todaysday,

That is interesting, Did anything change just before it stopped working? I just tried to sign up for an account on Upwork to test this but they don't make it easy and require ID verification which is mildly annoying.

A 403 typically means part of the data is wrong, When you did the test in Postman did that also show a 403 or something else?

**Comment by Joffcom** [comment]
Hey @todaysday,

I was curious to know if you had made any changes before it stopped working, I had assumed the upgrades were done after it stopped are you able to confirm if you updated before or after it stopped working?

I also thought you said that Postman didn't care about the 403 but it looks like Postman gets a 302 instead which is fine as it is a redirect.

I guess the only way to get the bottom of this would be for me to go through the verification process on Upwork to set up a test account. I will see if I can free up some time to dig out the ID required this week.

**Comment by todaysday** [comment]
hey @Joffcom 
Usually it's kind of long term process to get key for Upwork.
Can we just find each other in any kind of messenger and I will provide you with all necessary to make the tests and also switch  redirect_uri to your endpoint ?

**Comment by Joffcom** [comment]
Hey @todaysday,

I use a few different things but maybe email is better? You can find an email address for me on my profile 👍🏻

**Comment by Joffcom** [comment]
Hey @todaysday,

We released an update recently that shows more information when oauth fails, Can you try again using the latest release and see if that shows anything useful in the response body.

**Comment by Joffcom** [comment]
Moving to closed for now, if this is still an issue let me know and we can open it again.
