### ISSUE TITLE
Chinese node cannot parse data properly

### ISSUE THREAD

**Issue by mingjinglyh** [n8n-io/n8n#6068]
I come from China and I found a bug. If the node name contains Chinese, the result cannot be displayed in the function editor

![image](https://user-images.githubusercontent.com/45187089/233822456-8f3a9f19-903a-4afa-b322-5a6d481cffb8.png)

![image](https://user-images.githubusercontent.com/45187089/233822529-b2c7ac1d-4ea2-4a9f-9724-fdd73a401587.png)

![image](https://user-images.githubusercontent.com/45187089/233822560-4ba55d13-5c4d-467b-a1d5-7b3f20198a20.png)

**Comment by Joffcom** [comment]
Hey @mingjinglyh,

This is the same issue that is reported in #5527 which we are tracking as `ADO-387` internally. As we are already aware of this I am going to mark this as closed for now.
