### ISSUE TITLE
Possible redirect issue with HTTP node

### ISSUE THREAD

**Issue by CommoDor64** [n8n-io/n8n#6090]
**Describe the bug**
It seems that when a redirect takes more than some amount of time, say 2 seconds. The request ends before the redirect chain completes.

**To Reproduce**
I can't specify a unique case but here some ways to reproduce

1. Store a file on a fileserver that has a long latency - say more than 2 seconds
2. Redirect to this file
3. Set HTTP node options to allow redirects

In this case, the chain will halt on the long latency `location`

**Expected behavior**
The redirect chain should be resolved up to a limit

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04 on Digital Ocean, running on docker
- n8n Version: 0.224.4
- ~~Node.js~~ Running on docker
- Database system: Sqlite3
- Operation mode: Own

**Additional context**
I am not really sure what the issue is.
At first I suspected the timeout. I checked the code and it seems to be 10 seconds, not the issue probably.

**Comment by Joffcom** [comment]
Hey @CommoDor64 

When it fails do you get an error?

**Comment by CommoDor64** [comment]
Nope. I'll try to illustrate better what happens.

This is the redirect chain:
initial link -> first redirect -> second redirect to cloudflare -> third to s3 to a pdf file

what happens is that that the second redirect `html` file is being downloaded instead of the `pdf` file after all the redirects

**Comment by CommoDor64** [comment]
After digging into it, I have observed the following - I get different results for file downloads when I trigger manually for test purposes or whenever I let the pipeline be activated. I tried 3 different ways to download files all have the same behavior.

**Comment by Joffcom** [comment]
Hey @CommoDor64,

Can you share a URL that has this issue?

**Comment by Joffcom** [comment]
Closing for now, Will re-open this when we get more information.
