### ISSUE TITLE
Create Toggl Integration

### ISSUE THREAD

**Issue by Stvad** [n8n-io/n8n#61]
Toggl is a time tracking service:  https://toggl.com/

API: https://github.com/toggl/toggl_api_docs

**Comment by janober** [comment]
@stvad Do you have planned to work on that yourself? If so all is fine and we can leave the ticket here. If it is however only a suggestion that somebody else should create it please post it here: https://community.n8n.io/c/feature-requests/nodes 
That is the place to add integration requests. Other users can then upvote them if they are also interested. That gives me than the chance to know what is in demand and should be integrated next. Thanks!

**Comment by Stvad** [comment]
Created https://community.n8n.io/t/toggl-integration/140

**Comment by janober** [comment]
@Stvad Thanks a lot! Closing this issue than for now.
