### ISSUE TITLE
UI Bug: Scroll does not go all the way

### ISSUE THREAD

**Issue by wildsonc** [n8n-io/n8n#6115]
**Describe the bug**
When the list of options is too long, the scroll does not go to the end, not showing the options part. This happens in all the nodes that I tested that have the possibility to add items.

![CleanShot 2023-04-27 at 10 03 18](https://user-images.githubusercontent.com/72408418/234870107-dbf43dbe-b426-4c39-a461-e6167ef7c4cb.png)

**To Reproduce**

1. Go to IF (or another node with the option to add fields)
2. Add more than 4 items
3. Scroll down to end

**Expected behavior**
When there is a scroll it should show all options.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 0.226.0
- Database system PostgreSQL
- Operation mode queue

**Additional context**

**Comment by Joffcom** [comment]
Hey @wildsonc,

Thanks for reporting this one, I have created an internal ticket which we are tracking as `N8N-6392` for now it might be worth dropping down to the latest or next release.

**Comment by janober** [comment]
Fix got released with [`n8n@0.226.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.226.1)
