### ISSUE TITLE
Re-running failed executions does not re-execute workflow

### ISSUE THREAD

**Issue by damoncasale** [n8n-io/n8n#6122]
Same bug as before, happening in 0.224.4.  When I retry a failed execution using the currently saved workflow, it still uses the old workflow.

My installation of n8n is through npm install -g.

**Comment by Joffcom** [comment]
Hey @damoncasale 

Would you like to handle this here or on the forum? Opening the same issue in multiple places is going to split the attention and potentially have different teams looking at the same thing.

**Comment by damoncasale** [comment]
Hi @Joffcom .  I was able to track down the issue via getting help on Discord.  Turns out that my Apache reverse proxy was caching when it shouldn't have been.

Currently using the non-proxied URL so I can debug the rest of the workflow, before fixing the proxy.
