### ISSUE TITLE
Error: CONSTRAINT `user.settings` failed for `n8n`.`user`

### ISSUE THREAD

**Issue by floryn90** [n8n-io/n8n#6152]
**Describe the bug**
Migration error using the latest 0.226.x docker image with MySQL database:

 docker logs n8n -f
Migrations in progress, please do NOT stop the process.
query failed: UPDATE user SET settings = '"{\\"isOnboarded\\": true, \\"userActivated\\": true}"' WHERE id = 'user id'
error: Error: CONSTRAINT `user.settings` failed for `n8n`.`user`

**Expected behavior**
Migration of database to succeed and n8n to start correctly 
**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.226.1
- Database system: MySQL
- Operation mode: own;

**Additional context**

**Comment by Joffcom** [comment]
Hey @floryn90,

Thanks for reporting this one, We will get it fixed shortly. Which version of MySQL are you running and which version did you upgrade from?

**Comment by Joffcom** [comment]
Internal ticket for this is `N8N-6397`

**Comment by floryn90** [comment]
> Hey @floryn90,
> 
> Thanks for reporting this one, We will get it fixed shortly. Which version of MySQL are you running and which version did you upgrade from?

MySQL: Docker image mariadb:10
old n8n image: n8nio/n8n:0.225.2

**Comment by floryn90** [comment]
Using the latest tag version, 0.226.2, this issue is fixed now!
