### ISSUE TITLE
MongoDB node `find` operations does not handle multiple input items

### ISSUE THREAD

**Issue by geoza2000** [n8n-io/n8n#6174]
**PR: https://github.com/n8n-io/n8n/pull/6173**

**Describe the bug**
MongoDB  node's operation `find` does not account for multiple input items, only processes the first one

**To Reproduce**

1. Add a Node that outputs more than 1 item
2. Add a MongoDB Node with the `find` operation
3. Connect the first node with MongoDB Node
4. Run the workflow
5. See that the MongoDB Node outputs only one item

**Expected behavior**
MongoDB Node should be executed recursively for all input items and output the same number for outputs

**Environment (please complete the following information):**

- OS: MacOS
- n8n Version 0.227.0
- Node.js Version v16
- Database system SQLite
- Operation mode `own`

**Additional context**
--

**Comment by Joffcom** [comment]
Hey @geoza2000,

This is one of those things that we documented as not working but I am not sure why multi item support was not added. I will ask around internally to see if anyone knows why that is assuming it wasn't intentional we can look at reviewing your PR.

**Comment by Joffcom** [comment]
Closing as there is a PR to fix this, I will get the PR reviewed soon so we can merge it in.
