### ISSUE TITLE
Cron and Manual triggers priority

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#6191]
**Describe the bug**
Seems the Manual Trigger node does not have the top priority among other trigger nodes

**To Reproduce**
Here is the workflow with unpredictable start point.

I have a flow that prepares different payloads at different time and passes that payload to the base workflow to get the needed report from the API. It is simplier then creating a separate workflow for each report as I have about 30 such reports.

`{
  "meta": {
    "instanceId": "b2b258e8cf8e4b51c801b3bc5a9906c37aad0545d9cdbdf096a6542b5d192385"
  },
  "nodes": [
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "hour": 7,
              "minute": 30
            }
          ]
        }
      },
      "name": "At 7:30",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        1060,
        400
      ],
      "id": "518acdcc-f1fc-47b6-847b-c05b4fe54249"
    },
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "hour": 7,
              "minute": 20
            }
          ]
        }
      },
      "name": "At 7:20",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        800,
        400
      ],
      "id": "335cd846-07be-4976-9f1f-39af70c6d924"
    },
    {
      "parameters": {
        "triggerTimes": {
          "item": [
            {
              "hour": 7,
              "minute": 40
            }
          ]
        }
      },
      "name": "At 7:40",
      "type": "n8n-nodes-base.cron",
      "typeVersion": 1,
      "position": [
        1300,
        400
      ],
      "id": "995f18da-513b-4255-b520-63551e0b8ab9"
    },
    {
      "parameters": {
        "jsCode": "return {\n  \"test_pd\": \"report1_pd\",\n  \"meta\": {\n    \"execution_id\": $execution.id,\n    \"workflow_id\": $workflow.id,\n    \"workflow_name\": $workflow.name,\n  }\n}"
      },
      "id": "5cd67101-2b3a-4813-b390-f504abc01c26",
      "name": "Report 1",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        800,
        620
      ]
    },
    {
      "parameters": {
        "jsCode": "return {\n  \"test_pd\": \"report2_pd\",\n  \"meta\": {\n    \"execution_id\": $execution.id,\n    \"workflow_id\": $workflow.id,\n    \"workflow_name\": $workflow.name,\n  }\n}"
      },
      "id": "e42d1281-bce0-4eb3-a559-3daf3058ee28",
      "name": "Report 2",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1060,
        620
      ]
    },
    {
      "parameters": {
        "jsCode": "return {\n  \"test_pd\": \"report3_pd\",\n  \"meta\": {\n    \"execution_id\": $execution.id,\n    \"workflow_id\": $workflow.id,\n    \"workflow_name\": $workflow.name,\n  }\n}"
      },
      "id": "9324c2c4-0240-4e21-93e8-a4e2fa743e5c",
      "name": "Report 3",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1300,
        620
      ]
    },
    {
      "parameters": {
        "workflowId": "1"
      },
      "id": "7c9f4b66-8b36-4726-a280-e1c85d50f37d",
      "name": "Flow to fetch data",
      "type": "n8n-nodes-base.executeWorkflow",
      "typeVersion": 1,
      "position": [
        800,
        880
      ],
      "disabled": true
    },
    {
      "parameters": {},
      "id": "7d33a8b8-37ad-4ac5-9d86-63d056afc11a",
      "name": "Next",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        600,
        880
      ]
    },
    {
      "parameters": {},
      "id": "233a5a59-25b6-423e-99b0-129e23f75347",
      "name": "For tests",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        440,
        400
      ]
    }
  ],
  "connections": {
    "At 7:30": {
      "main": [
        [
          {
            "node": "Report 2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "At 7:20": {
      "main": [
        [
          {
            "node": "Report 1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "At 7:40": {
      "main": [
        [
          {
            "node": "Report 3",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Report 1": {
      "main": [
        [
          {
            "node": "Next",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Report 2": {
      "main": [
        [
          {
            "node": "Next",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Report 3": {
      "main": [
        [
          {
            "node": "Next",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Next": {
      "main": [
        [
          {
            "node": "Flow to fetch data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "For tests": {
      "main": [
        [
          {
            "node": "Report 1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Expected behavior**
When I press the "execute workflow" button the workflow will run from the manual trigger node.

But the flow executes in the below priority (tested by disabling cron trigger each time):
1. Cron trigger "At 7:30 "
2. Cron trigger "At 7:20"
3. Cron trigger "At 7:40"
4. Manual Trigger "For tests"

So I suppose they executes in top-down priority based on the position in the JSON file. Even if the manual trigger has the lowest id

**Environment:**
- OS: docker
- n8n Version: 0.220.0

**Comment by Joffcom** [comment]
Hey @barn4k,

This is one of those things that we are aware of and don't consider it to be a bug at the moment. We do have an internal feature request somewhere to change this though so in the future this might be something we look at changing, One thing I would like is the option to select which node is used as the trigger which can be handy if you have multiple triggers in the same workflow.

I will dig out the feature request and add this as a vote to it, For now now though as this isn't really a bug I will mark this one as closed. If you do feel it is a bug let me know and we can evaluate it again.
