### ISSUE TITLE
Google Sheets (Core) Node: "Append or update" Operation will fail if the Sheet (Tab) name has less than 6 characters. 

### ISSUE THREAD

**Issue by ken1901** [n8n-io/n8n#6203]
**Describe the bug**

We have a Google Sheet file with Sheets of Mo1 to Mo12 (represent 12 months in a year, we keep the Sheet names short to easily switch between Sheets (Tabs)). 

When use Google Sheets Node with "Append or update" Operation, it will fail with any of the above 12 Sheets. 
Currently to make a work around, we have to change the Sheet name to "Month1", "Month2", ... "Month12" (which make the Tabs are long).

**To Reproduce**

1. Make a workflow and use Google Sheets Node with "Append or update" Operation
2. Connect it with a Google Sheet file with a Sheet name less than 6 characters. (example: Mo1)
3. Try to run the workflow to append data to that Sheet.

**Expected behavior**
The data should be appended or updated successfully

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 0.225.2
- Node.js Version: v16.19.1
- Database system: SQLite
- Operation mode: own

**Additional context**
It is running inside a Docker container.

**Comment by Joffcom** [comment]
Hey @ken1901,

Thanks for reporting this one, I have just taken a quick look and it isn't that anything under 6 characters fails as using 3 character month names appears to work. It looks like instead when using a value that could be considered a column name (A - ZZZ with a number at the end) it fails as it treats it as a range.

I have created an internal ticket for this which we are tracking as `NODE-522` for now using Jan, Feb, Mar, Apr, May,... would also work around this and give you smaller tab names.

**Comment by ken1901** [comment]
Thanks @Joffcom so much for your explanation. I was wondering why it has such weird behavior, now I understand. We will try a workaround solution like you suggested, while waiting for the fix. Thanks again!

**Comment by janober** [comment]
Fix got released with [`n8n@1.4.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.4.1)
