### ISSUE TITLE
GitLab label not set when creating issues

### ISSUE THREAD

**Issue by dgrieser** [n8n-io/n8n#6237]
**Describe the bug**

When creating an issue in GitLab, the specified label is not added.

**To Reproduce**

The following spec:
```
    {
      "parameters": {
        "owner": "={{$json[\"gitlabNamespace\"]}}",
        "repository": "={{$json[\"gitlabProject\"]}}",
        "title": "=Ticket {{$json[\"conversation\"][\"shortId\"]}}: {{$json[\"conversation\"][\"title\"]}}",
        "body": "={{ $json[\"issueText\"] }}",
        "due_date": "=",
        "labels": [
          {
            "label": "type::support"
          }
        ],
        "assignee_ids": []
      },
      "id": "0acab741-c710-4676-99cf-1e9b7992c1ea",
      "name": "Create Gitlab issue",
      "type": "n8n-nodes-base.gitlab",
      "typeVersion": 1,
      "position": [
        2200,
        880
      ],
      "credentials": {
        "gitlabApi": {
          "id": "15",
          "name": "GitLab Conversation Integration, new"
        }
      }
    },

```

**Expected behavior**
The created issue should have the specified label.

**Environment (please complete the following information):**

- OS: Alpine 3.17.3 Container on Kubernetes
- n8n Version 0.225.2
- Node.js Version v18.16.0
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @dgrieser,

I have just given it a quick test and for me it is creating the label.

![image](https://github.com/n8n-io/n8n/assets/4688521/43236ed9-042d-4d51-b905-9360ab4aacf7)

Are you seeing any error messages?

**Comment by dgrieser** [comment]
Hi @Joffcom!

I don't see no error messages, sadly. Is the syntax correct?

```
         "labels": [
          {
            "label": "type::support"
          }
        ],
```

Or should it be `~type::support`?

Does it make a difference, whether the label is defined globally or on the group the issue is created in?

Thanks for your help :smiley:

**Comment by Joffcom** [comment]
Hey @dgrieser,

I didn't have the label set up at all in my test jira instance and it just worked, To test I used the same `type::support` option that you sent.

If there is no error what shows up in the issue in Jira?

**Comment by Joffcom** [comment]
Hey @dgrieser,

As this doesn't look to be a bug I am going to mark this as closed for now, If you are still having an issue with this feel free to pop open a new thread on our [community support forum](https://community.n8n.io) and we can take another look there.

**Comment by Joffcom** [comment]
Hey @dgrieser 

Thanks for the update that is good to know.
