### ISSUE TITLE
Bug with node reference in specific case

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#6250]
**Describe the bug**
Hello! I've discovered a bug with very specific case. Bug is happening when I try to access the IF item data (false branch only) from Code node inside Split node and via node reference ($('name')). All is working fine without the split node, but starting to get messy with it.

**To Reproduce**
Pinned data for Start trigger:
`[
  {
    "name": "First item",
    "code": 1
  },
  {
    "name": "Second item",
    "code": 2
  }
]`

Workflow json:
`{
  "meta": {
    "instanceId": "b2b258e8cf8e4b51c801b3bc5a9906c37aad0545d9cdbdf096a6542b5d192385"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "d487a86f-96c9-4e55-8416-433ff8d57a23",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        820,
        800
      ]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "id": "482c5fb2-88ca-44e7-82bd-59d39219958f",
      "name": "Split",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        1220,
        1060
      ]
    },
    {
      "parameters": {},
      "id": "5b559678-b6a6-435e-b69f-3d2d4cd56689",
      "name": "Next",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        2060,
        1180
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{ $json.code }}",
              "operation": "equal",
              "value2": 1
            }
          ]
        }
      },
      "id": "264aecfc-6ebc-41a8-81ea-34612842d41e",
      "name": "IF 2",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1480,
        1040
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{ $json.code }}",
              "operation": "equal",
              "value2": 1
            }
          ]
        }
      },
      "id": "24d5ccb3-ac12-4bc8-a2bf-a018ef8d2b82",
      "name": "IF 1",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1240,
        580
      ]
    },
    {
      "parameters": {
        "jsCode": "const inputId = $input.last().json.code\nconst absId = $('IF 1').last().json.code\n\nreturn $input.all()"
      },
      "id": "c12358c2-0214-4322-9782-4e1d85af5287",
      "name": "Code 1 True",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1480,
        460
      ]
    },
    {
      "parameters": {
        "jsCode": "const inputId = $input.last().json.code\nconst absId = $('IF 1').last().json.code\n\nreturn $input.all()"
      },
      "id": "5e8733f3-d666-4a5e-bf46-666b379b61f2",
      "name": "Code 1 False",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1480,
        720
      ]
    },
    {
      "parameters": {
        "jsCode": "const inputId = $input.last().json.code\nconst absId = $('IF 2').last().json.code\n\nreturn $input.all()"
      },
      "id": "6b0d09d9-b56c-4cd9-885f-a71fa1e5c571",
      "name": "Code 2 True",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1720,
        920
      ]
    },
    {
      "parameters": {
        "jsCode": "const inputId = $input.last().json.code\nconst absId = $('IF 2').last().json.code\n\nreturn $input.all()"
      },
      "id": "cdcd4d2a-3981-4c4f-a701-d443970da0d5",
      "name": "Code 2 False",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1720,
        1180
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "IF 1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Split",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Split": {
      "main": [
        [
          {
            "node": "IF 2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Next": {
      "main": [
        [
          {
            "node": "Split",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF 2": {
      "main": [
        [
          {
            "node": "Code 2 True",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Code 2 False",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF 1": {
      "main": [
        [
          {
            "node": "Code 1 True",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Code 1 False",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code 2 True": {
      "main": [
        [
          {
            "node": "Next",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code 2 False": {
      "main": [
        [
          {
            "node": "Next",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

![image](https://github.com/n8n-io/n8n/assets/15629670/6247931c-0400-41aa-9a5e-7cbc4c8264a5)

**Expected behavior**
All code nodes has been executed without any errors. 'Code 2 False' node returned the Second Item

**Environment (please complete the following information):**

- **OS**: docker
- **n8n Version**: 0.220.0

**Comment by Joffcom** [comment]
Hey @barn4k,

When using `$('nodename').x` if you specify the index it should work so in this case `const absId = $('IF 2').last(1).json.code` would be the syntax to use to make sure you get the result from the false branch. Can you give it a go and make sure it works for you? We should probably update our docs to mention that this is important when using split in batches.

**Comment by barn4k** [comment]
hi @Joffcom 

Yes, with last(1) it works. What the magic? And why it doesn't required without split?

**Comment by barn4k** [comment]
And how does the **$node("node name").json** works in that case? Is it tied to the current branch or is it better to rewrite it to the new format?

**Comment by Joffcom** [comment]
Hey @barn4k,

I am not sure why without split it isn't required but the split node can sometimes do some odd things which I think is why we have the option to specify the branch and run index if needed.

I would use the new format as we will be making it the default soon, Not sure how it actually works though.

**Comment by sirdavidoff** [comment]
Hi @barn4k if you want to reference data in a previous node the recommended syntax is `$('node name').item.json`. This replaces the old syntax of `$node['node_name'].json`

Does that syntax work for you?

**Comment by sirdavidoff** [comment]
Although just realised you're using a 'code' node, so this syntax will only work in 'run once for each item' mode. For 'run once for all items' you can use `$('node name').itemMatching(item_index_in_current_node)`

**Comment by barn4k** [comment]
hi @sirdavidoff 

The tricky part is how to get the current item index in the Code node?

I see the `$itemIndex` is not supported according to the [docs](https://docs.n8n.io/code-examples/methods-variables-reference/#current-node-input). So I wondering how to use the `$("<node-name>").itemMatching(currentNodeinputIndex)` in that case (I thought the code node in the 'run for each item' mode already knows what the current index, but seems I still need to specify the index)

**Comment by Joffcom** [comment]
Moving to closed as this should now be resolved with all of the paired item changes we have made. If this is still an issue let me know and we can open it again.

Tested the example workflow in `1.61.0` with no issues.
