### ISSUE TITLE
Invoice ninja Trigger URL not responding

### ISSUE THREAD

**Issue by o-psi** [n8n-io/n8n#6254]
**Describe the bug**
When using the webhook URL links that are generated in invoice ninja, I get a 403 response. 

**To Reproduce**

1. Install most recent versions of n8n and invoice ninja.
2. setup invoice ninja credentials
3. Make a workflow that has an invoice ninja trigger, and activate it.
4. check the webhook urls in invoice ninja to ensure the trigger populated.
5. run the action that would trigger the webhook, and go to dashboard and systemlogs to see result

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version Most recent release. I use NPX to run

**Comment by o-psi** [comment]
![Screenshot 2023-05-15 at 3 40 15 PM](https://github.com/n8n-io/n8n/assets/24534046/3061c694-134c-4c18-bd08-2dbbaa865742)
![Screenshot 2023-05-15 at 3 40 05 PM](https://github.com/n8n-io/n8n/assets/24534046/b712211f-3119-4d41-bbb2-5648f720b165)
![Screenshot 2023-05-15 at 3 41 44 PM](https://github.com/n8n-io/n8n/assets/24534046/e936560b-0e10-49e4-b0f0-e8684b16f693)
Im self hosted there as well

**Comment by Joffcom** [comment]
Hey @o-psi 

Are you able to post to the same webhook using curl from the same machine Invoice Ninja is running on?

My current thinking is this going to be a networking / routing issue.

**Comment by o-psi** [comment]
I will test and get back with you.

**Comment by Joffcom** [comment]
Hey @o-psi,

Not sure if you are still seeing this but for now I am going to mark this as closed as it doesn't appear to be a bug with n8n itself. If you are still having an issue with this feel free to pop open a thread on our [community support forum](https://community.n8n.io) and we can get more eyes on it.
