### ISSUE TITLE
OAuth Connection Error Is Not Displayed Correctly

### ISSUE THREAD

**Issue by mark-monteiro** [n8n-io/n8n#6256]
**Describe the bug**
When an error occurs during an OAuth callback, the error is not displayed correctly in the UI. Instead `[object Object]` is displayed instead of an error message.

![image](https://github.com/n8n-io/n8n/assets/2626103/905ce3d5-1197-4ef3-933c-8b9cf00a214d)

**To Reproduce**

1. Set up an OAuth2 credential. I'm not sure how to trigger this error, so I'm also not sure how to set up the OAuth credential to make this error appear. In my case I am updating an existing credential for OpenCollective.
2. Initiate the connection for the credential
3. See the error during the OAuth callback phase

**Expected behavior**
The actual error message or a JSON serialized string of the error object should be displayed instead of `[object Object]`

**Environment (please complete the following information):**
- OS: Docker
- n8n Version: 228.2
- Node.js Version: Docker version
- Database system: PostgreSQL
- Operation mode: own

**Additional context**
This credential for OpenCollective was working previously and has recently stopped working. I am unable to determine what went wrong because no error message is displayed in the UI and no error is logged either.

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

We have a PR opened that should fix this here: https://github.com/n8n-io/n8n/pull/5794 normally there is some useful text so I am not sure if anything changed recently to change that though.

@netroy any thoughts?

**Comment by netroy** [comment]
I was just about to mention #5794.
I'll have a look.

**Comment by mark-monteiro** [comment]
Thanks, https://github.com/n8n-io/n8n/pull/5794 looks like the solution I was hoping for to this problem.

I would also consider logging these error messages so they can be reviewed later on in the log files. But if the error is displayed in the UI, that would solve the immediate problem for my use case.

**Comment by Joffcom** [comment]
Hey @mark-monteiro,

Google news, This change is now available from 0.229.0. As this is released I am going to mark this one as closed, Let me know if you have any questions about it.
