### ISSUE TITLE
Activate a workflow that contains a redis trigger node, this request blocked.

### ISSUE THREAD

**Issue by MotorFu** [n8n-io/n8n#6258]
**Describe the bug**
Activate a workflow that contains a redis trigger node, this request blocked.

**To Reproduce**
1.  create a new workflow
2. add redis triiger node and save workflow
3. then click activate button , It's always loading
4. this activate workflow request blocked

**Expected behavior**
activate workflow

**Environment (please complete the following information):**
- OS: [mac os 13.3]
- n8n Version [0.227.0]
- Node.js Version [18.14.0]
- Database system [mysql]
- Operation mode [own]

**Additional context**
 none

**Comment by Joffcom** [comment]
Hey @MotorFu,

As you have already opened this on our support forum here: https://community.n8n.io/t/activate-a-workflow-that-contains-a-redis-trigger-node-this-request-blocked/26205 I am going to mark this one as closed.

I will get an internal dev created to resolve the issue but having this open in 2 places is going to double up the work for the team.
