### ISSUE TITLE
No handling of the insufficient oauth permissions

### ISSUE THREAD

**Issue by shubham773** [n8n-io/n8n#6268]
**Describe the bug**
The n8n doesn't seem to be handling the case if we do not grant all the passed scopes from the OAuth consent window.
I am using a googleOAuth2API type credentials in which I pass these 2 custom scopes:

- https://www.googleapis.com/auth/contacts.readonly
- https://www.googleapis.com/auth/userinfo.email

**To Reproduce**

1. Create a new credential of type `Google OAuth2 API` with scopes mentioned above.
<img width="925" alt="image" src="https://github.com/n8n-io/n8n/assets/56577902/7b335191-11a3-4242-8dd9-d2d689b9671d">

2. Click on Sign In with Google Button

3. In the PopUp Window, Do not check the box which asks for the contact view/download permission. Just click on the continue button in bottom.
<img width="484" alt="image" src="https://github.com/n8n-io/n8n/assets/56577902/d4023c3b-a02f-4151-8aa6-543c64dd267d">

4. You will get connected with insufficient scopes, with a callback window saying got connected.
<img width="473" alt="image" src="https://github.com/n8n-io/n8n/assets/56577902/0e8468e2-dfe5-402a-a648-2a15e9d40cdb">

**Expected behavior**
The expected behavior is not to get connected with insufficient scopes. It should be considered as an error event and accordingly, the callback window should show an error message and pass an error event to the parent window. (Ref: https://github.com/n8n-io/n8n/blob/n8n%400.226.2/packages/cli/templates/oauth-error-callback.handlebars)

There is already a block in n8n's source code that throws an insufficient permission error but as per my understanding it's nowhere checking the scopes requested against the scopes received.
Ref: https://github.com/n8n-io/n8n/blob/n8n%400.226.2/packages/cli/src/credentials/oauth2Credential.api.ts#LL211C4-L221C1

**Environment (please complete the following information):**

- OS: Ubuntu, Mac
- n8n Version 0.226.2
- Node.js Version Default (using docker image)
- Database system Postgres 14
- Operation mode own

**Comment by Joffcom** [comment]
Hey @shubham773 

I have just mentioned this one internally as I don't believe this is really a bug. So in this case the authentication has happened and the provider has returned a token successfully so there is no error to display. 

Sure it could lead to unexpected behaviour in the workflow but part of OAuth is giving the user control over what they allow access to.

It sounds like this would really be more of a feature to mark scopes as "mandatory" that could be checked, but let's wait and see what the rest of the team say.

**Comment by shubham773** [comment]
Thanks for sharing your thoughts on this @Joffcom. 🙏 
I assumed the scopes are already considered as mandate because if we are requesting certain scopes then don't we always expect them to be provided by the user? The aim here is not to just fetch an access token but a valid access token with asked permissions.
 
Granting/Not granting them can be the user's choice as per oAuth but If we know that it will lead to unexpected behavior in workflows then we should not allow the successful completion of such credentials. 

Looking forward to hearing the team's thoughts on this.

**Comment by Joffcom** [comment]
Of course, Most of the time you would expect the scopes to all be accepted but we can't just assume that people are going to put in the specific scopes and not add too many but I think we need to have a way to handle both so maybe a field to mark as mandatory so we can show a warning would be a good solution.

It is a public holiday in Berlin today so a lot of the team won't be around but as soon as I see anything back from them I will let you know.

**Comment by shubham773** [comment]
Hey @Joffcom , Is there any update on this?

**Comment by Joffcom** [comment]
Hey @shubham773,

I was going to reply to this yesterday but got caught up with another issue, I had a chat with @maspio and this isn't likely to be something that we will change soon but we also don't currently see this as a bug so it will be treated like a feature request.

For now we are going to add this to our internal feature tracker to be reviewed by our product team to work out where the priority is, As this is going down the feature route I am going to mark this as closed for now.

Let me know if you have any questions about this.
