### ISSUE TITLE
Licensing Bugs (me)

### ISSUE THREAD

**Issue by richlysakowski** [n8n-io/n8n#6273]
**Describe the bug**

The actual meaning of this source code license is very murky.  This github repo hosts open source software code for something that is also used by the n8n Commercial Company, a business with rather expensive monthly per-user subscription payments when it is hosted by the n8n commercial business.    

See licensing / subscription cost: https://n8n.io/pricing/ 

- "Free and **source-available** _fair-code_ licensed" - WHAT DOES "source-available" MEAN?   

- IS IT FREE AND OPEN SOURCE?  OR OPEN COMMERCIAL LICENSE USE?  

- WHAT DOES **"VISIBLE"** SOURCE MEAN?  

- WHAT TYPE OF SOURCE CODE LICENSE DOES THIS CODE ACTUALLY HAVE?  

- IS THE LICENSE A PERPETUAL RIGHT-TO-USE LICENSE FOR SELF-HOSTED VERSIONS?  

- IS THE FREE LICENSE JUST FOR INDIVIDUAL USE?  

- CAN ANY COMPANY SELF-HOST THEIR OWN COPY FOR INTERNAL BUSINESS USE **FREE OF CHARGE**? 

FOR MORE INFORMATION SEE: 
See licensing / subscription cost: [https://n8n.io/pricing/ ](https://n8n.io/pricing/ )

**Comment by Joffcom** [comment]
Hey @richlysakowski 

Some of this is covered in our license FAQs here: https://docs.n8n.io/choose-n8n/faircode-license/ Have a look and let us know if anything is still unclear. 

Normally questions like this would be better suited to our community support forum as it is not a bug but I will keep this open for now.

**Comment by Joffcom** [comment]
Hey @richlysakowski,

I am going to mark this as closed now. If you still have questions on the license feel free to open a thread on our [community support forum](https://community.n8n.io) or email our license team.
