### ISSUE TITLE
n8n docker conteiner crashes after read ECONNRESET and write EPIPE errors in IMAP node

### ISSUE THREAD

**Issue by akhudolev** [n8n-io/n8n#6276]
I have faced with same issue described in [N8n server(container) after read ECONNRESET and write EPIPE errors in IMAP (version 2) node](https://community.n8n.io/t/n8n-server-container-after-read-econnreset-and-write-epipe-errors-in-imap-version-2-node/24012)

Docker Logs:
ubuntu-n8n-1  | 2023-05-19T09:42:06.843280593Z Editor is now accessible via:
ubuntu-n8n-1  | 2023-05-19T09:42:06.843301192Z https://__________
ubuntu-n8n-1  | 2023-05-19T09:44:47.647365315Z The trigger node "Email Trigger (IMAP) check sales folder" of workflow "Mattermost missed dbi site phone calls notification for Sales" failed with the error: "read ECONNRESET". Will try to reactivate.
ubuntu-n8n-1  | 2023-05-19T09:44:47.651040684Z The trigger node "Email Trigger (IMAP) check sales folder" of workflow "Mattermost missed dbi site phone calls notification for Sales" failed with the error: "write EPIPE". Will try to reactivate.
ubuntu-n8n-1  | 2023-05-19T09:44:47.654833850Z
ubuntu-n8n-1  | 2023-05-19T09:44:47.654966245Z /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:91
ubuntu-n8n-1  | 2023-05-19T09:44:47.654999644Z             throw new Error(`The workflow with the id "${id}" is currently not active and can so not be removed`);
ubuntu-n8n-1  | 2023-05-19T09:44:47.655013343Z                   ^
ubuntu-n8n-1  | 2023-05-19T09:44:47.655175738Z Error: The workflow with the id "13" is currently not active and can so not be removed
ubuntu-n8n-1  | 2023-05-19T09:44:47.655195037Z     at ActiveWorkflows.remove (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:91:19)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655206737Z     at Object.returnFunctions.emitError (/usr/local/lib/node_modules/n8n/dist/ActiveWorkflowRunner.js:417:44)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655217836Z     at ImapSimple.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/EmailReadImap/v2/EmailReadImapV2.node.js:470:26)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655229136Z     at runMicrotasks (<anonymous>)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655239335Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655249535Z     at runNextTicks (node:internal/process/task_queues:65:3)
ubuntu-n8n-1  | 2023-05-19T09:44:47.655259735Z     at processImmediate (node:internal/timers:437:9)
ubuntu-n8n-1  | 2023-05-19T09:44:56.604925599Z Last session crashed
ubuntu-n8n-1  | 2023-05-19T09:45:09.105732005Z Initializing n8n process
ubuntu-n8n-1  | 2023-05-19T09:45:14.558844554Z n8n ready on 0.0.0.0, port 5678
ubuntu-n8n-1  | 2023-05-19T09:45:14.559065946Z Version: 0.227.1
ubuntu-n8n-1  | 2023-05-19T09:45:14.736149575Z  ================================
ubuntu-n8n-1  | 2023-05-19T09:45:14.736552661Z    Start Active Workflows:
ubuntu-n8n-1  | 2023-05-19T09:45:14.737039843Z  ================================
ubuntu-n8n-1  | 2023-05-19T09:45:16.380585240Z    - Mattermost missed dbi site phone calls notification for Sales (ID: 13)
ubuntu-n8n-1  | 2023-05-19T09:45:17.572928519Z      => Started
ubuntu-n8n-1  | 2023-05-19T09:45:17.574011680Z
ubuntu-n8n-1  | 2023-05-19T09:45:17.574102477Z Editor is now accessible via:
ubuntu-n8n-1  | 2023-05-19T09:45:17.574125276Z https://_____
ubuntu-n8n-1  | 2023-05-19T09:47:58.897866354Z The trigger node "Email Trigger (IMAP) check sales folder" of workflow "Mattermost missed dbi site phone calls notification for Sales" failed with the error: "read ECONNRESET". Will try to reactivate.
ubuntu-n8n-1  | 2023-05-19T09:47:58.903855443Z The trigger node "Email Trigger (IMAP) check sales folder" of workflow "Mattermost missed dbi site phone calls notification for Sales" failed with the error: "write EPIPE". Will try to reactivate.
ubuntu-n8n-1  | 2023-05-19T09:47:58.909529544Z
ubuntu-n8n-1  | 2023-05-19T09:47:58.909704838Z /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:91
ubuntu-n8n-1  | 2023-05-19T09:47:58.909811134Z             throw new Error(`The workflow with the id "${id}" is currently not active and can so not be removed`);
ubuntu-n8n-1  | 2023-05-19T09:47:58.909837733Z                   ^
ubuntu-n8n-1  | 2023-05-19T09:47:58.909855432Z Error: The workflow with the id "13" is currently not active and can so not be removed
ubuntu-n8n-1  | 2023-05-19T09:47:58.909937430Z     at ActiveWorkflows.remove (/usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/ActiveWorkflows.js:91:19)
ubuntu-n8n-1  | 2023-05-19T09:47:58.909967329Z     at Object.returnFunctions.emitError (/usr/local/lib/node_modules/n8n/dist/ActiveWorkflowRunner.js:417:44)
ubuntu-n8n-1  | 2023-05-19T09:47:58.910047926Z     at ImapSimple.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/EmailReadImap/v2/EmailReadImapV2.node.js:470:26)
ubuntu-n8n-1  | 2023-05-19T09:47:58.910125223Z     at runMicrotasks (<anonymous>)
ubuntu-n8n-1  | 2023-05-19T09:47:58.910153222Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ubuntu-n8n-1  | 2023-05-19T09:47:58.910170921Z     at runNextTicks (node:internal/process/task_queues:65:3)
ubuntu-n8n-1  | 2023-05-19T09:47:58.910218720Z     at processImmediate (node:internal/timers:437:9)
ubuntu-n8n-1  | 2023-05-19T09:48:08.809929181Z Last session crashed
ubuntu-n8n-1  | 2023-05-19T09:48:21.573501079Z Initializing n8n process
ubuntu-n8n-1  | 2023-05-19T09:48:27.154633773Z n8n ready on 0.0.0.0, port 5678
ubuntu-n8n-1  | 2023-05-19T09:48:27.179572697Z Version: 0.227.1
ubuntu-n8n-1  | 2023-05-19T09:48:27.358831902Z  ================================
ubuntu-n8n-1  | 2023-05-19T09:48:27.359341884Z    Start Active Workflows:
ubuntu-n8n-1  | 2023-05-19T09:48:27.359883265Z  ================================

**To Reproduce**
Set active workflow with IMAP trigger node

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 227.1
- Database system Postgres 14
- Operation mode `main`

**Comment by Joffcom** [comment]
Just as a heads up @akhudolev a fix for the crash has been pushed and should be available in an upcoming release.
