### ISSUE TITLE
[Self-Hosted] Workflow could not be activated: There is already an entry with this name

### ISSUE THREAD

**Issue by kmanwar89** [n8n-io/n8n#6287]
**Describe the bug**
On a self-hosted instance of n8n, in a completely isolated/fresh/separate install, after creating a workflow with Cisco WebEx, it appears that after the first successful run I receive the "Workflow could not be activated" generic error.  This workflow was not duplicated, imported or copied from any other instance of n8n. n8n is currently the *only* container running on this machine and the error is reproducible.

**To Reproduce**

1. Follow the instructions on the n8n website for a self-hosted setup using *docker-compose*
2. Bring up the docker container and walk through all the setup steps
3. Create a workflow using Webex by Cisco triggers and other nodes (screenshot will be attached)
4. Save & Activate the workflow - this succeeds the first time
5. Upon successive executions, or upon any change made to the workflow, the workflow will break and no longer be able to be activated. The "Workflow could not be activated: There is already an entry with this name" error will appear in the bottom-right.

**Expected behavior**
It is expected that this error would not appear as this is the *only* workflow configured on a completely fresh/vanilla install.

**Environment (please complete the following information):**

- OS: 22.04.2 LTS
- n8n Version: 0.227.1
- Node.js Version [e.g. 16.17.0]: Unsure how to retrieve this
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: SQLite/default
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]: Unsure, assuming default of "own"

**Additional context**
In my "production" instance, I've encountered this issue but only for this auto-reply workflow I'm working on. I have other workflows I use, so I decided to spin up a "dev" instance on a physically separate server - everything is 100% isolated from the prod instance. In addition, this dev server has no other containers running, no other n8n workflows and is basically as close to vanilla as you can get.  I'm happy to nuke the server and start from *pure scratch* to further prove the issue.  The fact it can be reliably reproduced seems to indicate *something* is going on.

Specific workflow:
![image](https://github.com/n8n-io/n8n/assets/11323060/e61dbaf2-bc57-4ba3-945d-eecfaed55e55)

Workflow list:
![image](https://github.com/n8n-io/n8n/assets/11323060/98d01802-3bd3-4e19-9221-22df7a058f70)

Proof nothing else is running:
![image](https://github.com/n8n-io/n8n/assets/11323060/38676f86-366a-464e-8efa-59108b61d810)

Additional logs:

```
> docker image list
REPOSITORY                TAG       IMAGE ID       CREATED      SIZE
docker.n8n.io/n8nio/n8n   latest    98b6bb97d46b   4 days ago   511MB

> docker network list
NETWORK ID     NAME            DRIVER    SCOPE
d8d1a7cd7d4b   bridge          bridge    local
104e69e99b9f   dev8n_default   bridge    local
6de2854b6861   host            host      local
1c9cf2164cb2   none            null      local

> docker ps -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS                                       NAMES
98b6b7239a4d   docker.n8n.io/n8nio/n8n   "tini -- /docker-ent…"   53 minutes ago   Up 53 minutes   0.0.0.0:5678->5678/tcp, :::5678->5678/tcp   dev8n-n8n-1

> docker system info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.17.3)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-72-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.52GiB
 Name: shadowserverdev
 ID: X5MA:EN7Q:RXUO:HD4C:3HLT:UJ5S:4Q2I:JOFE:V72V:YUZB:TQFK:IMR7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 
> date
Fri May 19 08:06:55 PM EDT 2023
```

**Comment by Joffcom** [comment]
Hey @kmanwar89,

Thanks for reporting this one, I suspect this will be down to the webhook checks that the trigger node does.

I will check this on Monday morning and let you know.

**Comment by kmanwar89** [comment]
Thanks @Joffcom  for the follow-up! Did you get a chance to investigate and, if so, anything interesting to report back?

I may (as a test and for my own sanity) try another/different workflow to see if maybe this is something specific to the Webex by Cisco triggers compared to other services. I'll be sure to report back.

**Comment by Joffcom** [comment]
Hey @kmanwar89 

I had the details for a WebEx sandbox account come through yesterday so that I can test, Should have more info shortly.

I suspect the issue is with the node and maybe a response we get back or the API has changed at some point and we missed a notification.

**Comment by kmanwar89** [comment]
> Hey @kmanwar89
> 
> I had the details for a WebEx sandbox account come through yesterday so that I can test, Should have more info shortly.
> 
> I suspect the issue is with the node and maybe a response we get back or the API has changed at some point and we missed a notification.

Great,  thanks for all your help and please let me know if there's any additional logs that are needed!

**Comment by Joffcom** [comment]
Hey @kmanwar89,

Oddly enough I am not able to reproduce this, I can add the Webex trigger click save then add another node and click save with no issue. I can also activate the workflow then add some nodes and hit save again with no issues.

During your testing was your workflow active and did you use the execute workflow button at all?

**Comment by kmanwar89** [comment]
So I was able to work with a colleague of mine (who's flow I've actually stolen, with his blessing) and we were able to recreate the issue and narrow it down a bit further.

As an initial step, I upgraded to the latest release, from 0.227.1 to 0.228.2.  I confirmed the issue is still present in this version.

What we discovered was if you *import* a workflow, it consistently throws the error I described, but re-creating the flow from scratch does not trigger the error.

A "fix" was to import the flow, delete the initial WebEx trigger, and re-add only the WebEx trigger.  That seemed to work and allowed me to both activate & save the workflow, and it is working as intended.

We did a diff of both workflows, imported vs. created from scratch, but couldn't not find any details in the raw .JSON that indicated why the issue is occurring.  We also don't see any logs in the container (based on the output of `docker-compose logs` that indicate what is going on.  Logging into the container itself doesn't show any logs that indicate anything either.

If you'd like, I can share the workflow (.json) files, but the troubleshooting so far seems to indicate it's something related to importing and, more specifically, importing a workflow with an existing WebEx trigger.

I have other workflows as well that I can try and prove in/prove out my theory.  If there's any ability to see more verbose logging, I'd be happy to continue troubleshooting.

**Comment by kmanwar89** [comment]
Well, now what's interesting is I imported a *different* workflow that has the same trigger (Webex), and it didn't have any issues. I deleted and re-added the original workflow that caused the original issue, and the same error message re-occurred upon trying to activate the workflow.

So, the troubleshooting would indicate it's something specific to the WebEx trigger within *that* specific workflow.  I'm attaching it here for reference in case something stands out to you as causing the issue, as well as the "working" example, which should be all but identical.

[Not working - Short_Message_Auto_Reply.txt](https://github.com/n8n-io/n8n/files/11604517/Short_Message_Auto_Reply.txt)

[Working - Unicast_Auto_Reply.txt](https://github.com/n8n-io/n8n/files/11604532/Unicast_Auto_Reply.txt)

**Comment by kmanwar89** [comment]
Hi @Joffcom , any luck in reproducing/troubleshooting this issue?

**Comment by Joffcom** [comment]
Hey @kmanwar89,

Not yet, I have been caught up with other issues. Will be checking this one again today to see if I can spot what is wrong with the workflow.

**Comment by kmanwar89** [comment]
Thanks for this - I'll give it a try this weekend and let you know.

What I'm curious about is the fact that I was able to reproduce this issue on a totally separate/isolated machine that had never run n8n before, which would point to something in the credentials that I created being the common factor.

I'll keep digging and see if I can find a clear set of reproducible steps. Thanks for your help with this.

**Comment by Joffcom** [comment]
Hey @kmanwar89,

The new instance was interesting but I tried it on multiple and could only reproduce it when I added 2 triggers by mistake but I suspect the outcome is maybe the same. It could be that the configuration of n8n was a bit odd and the front end didn't think the first attempt worked but on the second it did. I do think that changing our existing check will solve this though.

**Comment by Joffcom** [comment]
Going to mark this as closed for now and we can pick it back up again later if needed.

**Comment by kmanwar89** [comment]
Sorry, life got very busy (when it rains, it POURS) and I didn't get much of a chance to do anything around this issue.

Fully agree with closing it for now, and can pick it up later if it's still consistently repeatable. Thanks!
