### ISSUE TITLE
Bug with itemMatching after Lambda node

### ISSUE THREAD

**Issue by barn4k** [n8n-io/n8n#6316]
**Describe the bug**
**$(\<nodename>).itemMatching()** method does not return the proper results from the desired node when used directly after the **Lambda** node

**To Reproduce**

`{
  "meta": {
    "instanceId": "b2b258e8cf8e4b51c801b3bc5a9906c37aad0545d9cdbdf096a6542b5d192385"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "1e51881f-b8b2-46cf-9e9a-3fe53e64a8a9",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        1140,
        580
      ]
    },
    {
      "parameters": {
        "jsCode": "return [\n  {id:1},\n  {id:2},\n  {id:3},\n  {id:4},\n]"
      },
      "id": "7f36b2eb-6b3c-4971-af5a-13ffd71eb83c",
      "name": "Sample data",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1360,
        580
      ]
    },
    {
      "parameters": {
        "mode": "runOnceForEachItem",
        "jsCode": "const test = $('Sample data').itemMatching($itemIndex)\n\nreturn {\n  json: {\n    id: test.json.id\n  }\n}"
      },
      "id": "07892844-0417-43dd-bd7d-f9b54fa59f5c",
      "name": "Test func No Lambda",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1800,
        420
      ]
    },
    {
      "parameters": {
        "mode": "runOnceForEachItem",
        "jsCode": "const test = $('Sample data').itemMatching($itemIndex)\n\nreturn {\n  json: {\n    id: test.json.id\n  }\n}"
      },
      "id": "4d74cab5-d6f4-4da9-b805-74c19c132d1a",
      "name": "Test func Lambda",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1800,
        580
      ]
    },
    {
      "parameters": {
        "jsCode": "for (const item of $input.all()) {\n  item.json.data = item.json.id*10;\n}\n\nreturn $input.all();"
      },
      "id": "a5a110c5-bd86-4461-a4f5-f0d6637ac9e3",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1580,
        420
      ]
    },
    {
      "parameters": {},
      "id": "2340520c-b418-4b27-a7e6-44f3f345dbd6",
      "name": "No Operation, do nothing",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1760,
        800
      ]
    },
    {
      "parameters": {
        "mode": "runOnceForEachItem",
        "jsCode": "const test = $('Sample data').itemMatching($itemIndex)\n\nreturn {\n  json: {\n    id: test.json.id\n  }\n}"
      },
      "id": "fea6c5c4-d746-4934-aab6-9e818f0a937f",
      "name": "Test func Lambda1",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1960,
        800
      ]
    },
    {
      "parameters": {},
      "name": "test lambda 1",
      "type": "n8n-nodes-base.awsLambda",
      "typeVersion": 1,
      "position": [
        1580,
        580
      ],
      "id": "d1929721-4b35-41f3-b463-53cd505a8d07"
    },
    {
      "parameters": {},
      "name": "test lambda 2",
      "type": "n8n-nodes-base.awsLambda",
      "typeVersion": 1,
      "position": [
        1580,
        800
      ],
      "id": "01a429d0-8038-46c3-a0f1-5200975e7351"
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Sample data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Sample data": {
      "main": [
        [
          {
            "node": "test lambda 1",
            "type": "main",
            "index": 0
          },
          {
            "node": "Code",
            "type": "main",
            "index": 0
          },
          {
            "node": "test lambda 2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "Test func No Lambda",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "No Operation, do nothing": {
      "main": [
        [
          {
            "node": "Test func Lambda1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "test lambda 1": {
      "main": [
        [
          {
            "node": "Test func Lambda",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "test lambda 2": {
      "main": [
        [
          {
            "node": "No Operation, do nothing",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

Pinned data for both lambdas (you don't need to configure the lambda):
`[
  {
    "result": {
      "some": "thing1"
    }
  },
  {
    "result": {
      "some": "thing2"
    }
  },
  {
    "result": {
      "some": "thing3"
    }
  },
  {
    "result": {
      "some": "thing4"
    }
  }
]`

![image](https://github.com/n8n-io/n8n/assets/15629670/614ae543-6e6d-40ec-94eb-edf4ad0771ac)

**Expected behavior**
All three scenarios return id 1,2,3,4

**Environment (please complete the following information):**

- OS: docker
- n8n Version: 0.220.0

**Additional context**
Current workaround: placing the **No Operation** node between **Lambda** and **Code** nodes fix the issue

**Comment by Joffcom** [comment]
Hey @barn4k,

For me the Test func Lambda node has 4 items in it, I am using `0.229.0`. Can you try updating and see if that helps?

**Comment by barn4k** [comment]
@Joffcom 
Just updated to 0.230.2 and the problem has gone :)
