### ISSUE TITLE
The back-end startup failed

### ISSUE THREAD

**Issue by luoxiqiang** [n8n-io/n8n#6326]
I followed this article to try to run n8n [n8n/CONTRIBUTING.md at master · n8n-io/n8n · GitHub](https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md)

```
1. pnpm i
2. pnpm build
3. pnpm dev
```
However, the back-end doesn’t seem to be starting

![image](https://github.com/n8n-io/n8n/assets/32994527/97f37efa-5fc0-4fc9-bb27-8246d32b5741)

When I executed ```pnpm start``` in package/cli, I was told to exit abnormally

![image](https://github.com/n8n-io/n8n/assets/32994527/0da14ad5-885e-49e8-9eef-bf09d4d1b17c)

I don’t know what’s going on here. Could you please help me
My build environment is：
nodejs: v16.20.0
pnpm: 8.5.1

**Comment by luoxiqiang** [comment]
It runs successfully on Ubuntu

**Comment by Joffcom** [comment]
Hey @luoxiqiang,

As this already opened on our support forum here: https://community.n8n.io/t/the-back-end-startup-failed/26547 I am going to mark this as closed so we don't have any duplication of effort.
