### ISSUE TITLE
LinkedIn node error

### ISSUE THREAD

**Issue by floryn90** [n8n-io/n8n#6327]
**Describe the bug**
Unable to post on LinkedIn

**Expected behavior**

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.230.1
- Database system: Postgresql
- Operation mode: own

**Additional context**
ERROR: Your request is invalid or could not be processed by the service
ERROR :: /distribution/targetEnties :: unrecognized field found but not allowed

HTTP Code
422

NodeApiError: Your request is invalid or could not be processed by the service
    at Object.linkedInApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/LinkedIn/GenericFunctions.js:41:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/LinkedIn/LinkedIn.node.js:160:40)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:652:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:596:53

**Comment by Joffcom** [comment]
Hey @floryn90,

Thanks for reporting this one, I have just taken a quick look and after doing a simple post request as a person it is also failing for me.

I have created an internal ticket for this which we will be tracking as `NODE-561`

**Comment by pmoralesp** [comment]
I have been successfully running a LinkedIn node daily since june 1st with 0.231.0. Two days ago, it started to fail with n8n without any changes on my end, so I believe LinkedIn upgraded something on their side.

**Comment by janober** [comment]
Fix got released with [`n8n@0.233.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.233.0)

**Comment by Joffcom** [comment]
Hey @floryn90,

This has now been resolved, I am going to mark this one as closed. If you still see an issue with posting let me know.
