### ISSUE TITLE
Hitting a dot (point, full stop) key in expression editor for Google Sheets node erases all mappings

### ISSUE THREAD

**Issue by berezovskyi** [n8n-io/n8n#6329]
**Describe the bug**
Hitting a dot (point, full stop) key in expression editor for Google Sheets node erases all mappings and asks to select the sheet again.

**To Reproduce**

1. Add a Google Sheets node
2. Use Append operation, select an existing document and sheet.
3. Add a field with an expression value.
4. Press the '.' dot key.
5. See error

<img width="552" alt="image" src="https://github.com/n8n-io/n8n/assets/64734/3d5941fe-b38a-4c10-83cf-721bbb2c0f2c">

<img width="659" alt="image" src="https://github.com/n8n-io/n8n/assets/64734/cdd35bf8-80a0-43d8-a6ef-998a9e11f94f">

**Expected behavior**
No user data/code should be deleted without a direct user action.

**Environment (please complete the following information):**

- OS: **macOS with Chrome 113.0.5672.126** 
- n8n Version **0.228.2** from Docker on Ubuntu 22.04 LTS
- Database system **default**
- Operation mode: default

**Additional context**
Pasting the '.' character into the field has the same effect. But pasting an entire `{{ }}` block works fine.

**Comment by Joffcom** [comment]
Hey @berezovskyi,

This issue appears to have been resolved but I am not sure which version it was resolved in, Updating to the latest release should sort this for you.

For now I will mark this as closed and if it is still an issue for you we can open it again.
