### ISSUE TITLE
n8n slow on 100+ workflows

### ISSUE THREAD

**Issue by Hasan0ff** [n8n-io/n8n#6340]
**Describe the bug**
n8n gets very slow on frontend (browser) when there are 100+ workflows.

**To Reproduce**
1. Just add couple hundred workflows and the frontend UI will slow down so bad that you will get messages regarding the page being slow.

**Expected behavior**

**Environment (please complete the following information):**

- OS: [Ubuntu Linux 20.04]
- n8n Version [Latest]
- Node.js Version [Latest]
- Database system [mysql latest]
- Operation mode [main]

**Additional context and Possible solutions**
The problem is that "ip:5678/rest/workflows" loads all the workflow data in a json file and sometimes when you are running youtube for music, couple of other open tabs and index page of n8n loads very slowly. If possible please add pagination to /rest/workflows so that not all the workflows are loaded at the same time and the problem will be fixed. 

Thanks for your hard work

**Comment by Joffcom** [comment]
Hey @Hasan0ff 

When does n8n actually run slow is it when loading one workflow or the list of workflows?

I have 200+ in my instance and I don't have this issue but I have seen some instances with more run slow on the workflow list. 

I believe we are working on fixing the workflow list so it would be handy to know if this is where you see the slowdown.

**Comment by Hasan0ff** [comment]
@Joffcom I should have used bold or italics to mention the **index page** . It is when it lists the workflows. In my case, there are 700+ workflows and it freezes the browser and I have to wait a while for the javascript to load everything properly. That's why I'm saying it would be nice if it is possible to add pagination to the listing of workflows.

**Comment by Joffcom** [comment]
Hey @Hasan0ff 

Perfect thanks, this fits in with what we are already aware of and something we have been thinking about recently.

I will get a dev ticket created shortly for this, I noticed you are also using MySQL it won't help with this issue but it would be worth starting to think about moving to Postgres soon as we will be dropping support for MySQL in v1.0 which will be released soon.

**Comment by Joffcom** [comment]
Hey @Hasan0ff,

Can you check with `0.231.0` and see what is that like, I have just given it a quick go on a couple of instances and it looks to be a lot quicker because of a recent change to the data we load. It may not fully solve the issue but it might make it a lot better.

**Comment by Hasan0ff** [comment]
> Hey @Hasan0ff
> 
> Perfect thanks, this fits in with what we are already aware of and something we have been thinking about recently.
> 
> I will get a dev ticket created shortly for this, I noticed you are also using MySQL it won't help with this issue but it would be worth starting to think about moving to Postgres soon as we will be dropping support for MySQL in v1.0 which will be released soon.

Never tried postgres, but it seems its time to get my hands on it.



> Hey @Hasan0ff,
> 
> Can you check with `0.231.0` and see what is that like, I have just given it a quick go on a couple of instances and it looks to be a lot quicker because of a recent change to the data we load. It may not fully solve the issue but it might make it a lot better.

I'm using 0.228.2 version and only update once there is notification. Not used @next version even once as I'm afraid to break things up

**Comment by Joffcom** [comment]
Hey @Hasan0ff,

No worries, I have created an internal ticket of `N8N-6452` anyway as there are likely to be some improvements we can make there anywhere.

**Comment by Hasan0ff** [comment]
> Hey @Hasan0ff,
> 
> No worries, I have created an internal ticket of `N8N-6452` anyway as there are likely to be some improvements we can make there anywhere.

Sorry for the late reply and thanks for the hard work mate!

**Comment by Hasan0ff** [comment]
> Hey @Hasan0ff,
> 
> No worries, I have created an internal ticket of `N8N-6452` anyway as there are likely to be some improvements we can make there anywhere.

I updated to the latest release today (0.230.3) and the problem is fixed!
