### ISSUE TITLE
LDAP Node, missing DN on Update

### ISSUE THREAD

**Issue by m4rcelpl** [n8n-io/n8n#6369]
**Describe the bug**
Can't update attribute. 

**To Reproduce**

1. Go to LDAP Node
2. Select "Update"

**Expected behavior**
I would like to enter the DN of the object whose attribute I want to change.

**Environment (please complete the following information):**

- n8n Version 0.231.0

**Comment by Joffcom** [comment]
Hey @m4rcelpl,

Thanks for the report, I feel silly now as I missed that 🙂

Will get it sorted out shortly for the next release.

**Comment by Joffcom** [comment]
Hey @m4rcelpl,

Fix is in and once reviewed should be available in the next release.

**Comment by m4rcelpl** [comment]
Pefecto! Thx :)

**Comment by Joffcom** [comment]
Hey @m4rcelpl,

This fix was released in `0.232.0`, I am going to mark this one as closed for now.

**Comment by janober** [comment]
Fix got released with [`n8n@0.232.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.232.0)
