### ISSUE TITLE
n8n does not close some workflows,

### ISSUE THREAD

**Issue by joaopedroforti** [n8n-io/n8n#6370]
n8n does not close some workflows, even manually clicking cancel displays an error and the workflow continues running.

This happens in several flows, I have a flow running for 5 days, without any node, and I can't stop it.

I have already restarted the container and updated the application, but the flows do not close

I have installations of n8n in the same version, in other vm's and in all of them this bug happens
Screenshots:
https://prnt.sc/SmS3wBF7zAWX
https://prnt.sc/3gNADNaltxSo
https://prnt.sc/T_3918Mvsg_W

- OS: [Ubuntu Linux 22.04]
- n8n Version [0.228.2]

**Comment by Joffcom** [comment]
Hey @jpforti 

How are you running n8n is it in queue mode?

**Comment by jpforti** [comment]
Yes, is it in queue mode

**Comment by Joffcom** [comment]
Are the workers and the main instance all talking to Redis and the database without logging any errors?

**Comment by jpforti** [comment]
Yes, this does not happen on all streams, only on certain occasions

**Comment by Joffcom** [comment]
So typically I have seen this issue in the past when the database connection has dropped mid workflow, In these cases the main instance will show the workflow is running but really what has happened is it just has no end date to resolve this normally a restart of the main instance will fix it.

Have you already tried stopping the main instance then starting it up again (not using a restart command)?

**Comment by jpforti** [comment]
yah, i already did that

**Comment by Joffcom** [comment]
Hey @jpforti 

In that case can you enable debug logging, stop each instance then bring up the main instance then check the execution log and bring up the workers.

Can you also included your current configuration for the main instance and workers.

**Comment by Joffcom** [comment]
Hey @jpforti,

How did you get on with the above?

**Comment by Joffcom** [comment]
Going to mark this as closed for now and we can pick it back up again when we have more details.
