### ISSUE TITLE
Date&Time node completely broken: produces lots of extra items

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#6384]
New Date&Time node goes crazy. It adds lots of extra items:
![image](https://github.com/n8n-io/n8n/assets/20184727/caf79057-cb25-49ea-b788-ef16d28331a5)

Currently it is completely unusable.

**To Reproduce**
1. Add Customer Datastore with "all" option
2. Add Date&Time with "Get current time option"
3. Execute workflow and see 15 items after Date&Time

**Expected behavior**
5 items after Customer Datastore,
5 items after Date&Time

**Environment (please complete the following information):**

- Ubuntu Linux 18.04
- n8n 0.230.3
- Node.js Version [e.g. 16.17.0]
- SQLite
- main

**Comment by flipswitchingmonkey** [comment]
Can confirm that this is broken right now but fix is in the works.

**Comment by janober** [comment]
Fix got released with [`n8n@0.232.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.232.0)

**Comment by Joffcom** [comment]
Hey @artemdzyuba,

I am going to mark this one as closed, If you still see an issue after updating let me know and we can open it again.
