### ISSUE TITLE
Unable to run when using mounted filesystem due to permission denied error

### ISSUE THREAD

**Issue by tomaszkiewicz** [n8n-io/n8n#6412]
**Describe the bug**

I run n8n on OCI with mounted filesystem. The filesystem uses some kind of snapshotting technology that creates _immutable_ .snapshot directory at the root of the filesystem.

Unfortunately n8n entrypoint file does chown operation during startup on /root/.n8n directory, which is also a mount point for my external filesystem.

This results with chown operation failing due to lacking permissions ("permission denied" error) and causing whole script to fail.

**To Reproduce**
1. Run n8n container on OCI and mount NFS from FSS service on /root/.n8n directory
2. Run the script
3. Observe the error and failing container

**Expected behavior**
Being able to ignore chown operation (e.g. by setting env var) or set it to ignoring potential errors.

**Environment (please complete the following information):**

Kubernetes v1.26.2 on OCI
n8n v0.230.2

**Comment by Joffcom** [comment]
Hey @tomaszkiewicz,

At the moment while not ideal you could use a custom image to get around this assuming that the containers node user will have access to the files under `/home/node/.n8n` or `/root/.n8n` depending on configuration.

**Comment by tomaszkiewicz** [comment]
So far I hacked that using custom entrypoint and recreating the script inline as shown here: https://github.com/8gears/n8n-helm-chart/pull/40

However it's not future proof, that's why I raised it here :)

**Comment by netroy** [comment]
over the next couple of weeks, we are going to be releasing some changes that remove the need to `chown` the `/root/.n8n` folder in the entrypoint. That will address this issue.

**Comment by Joffcom** [comment]
Hey @tomaszkiewicz,

Good news, this has now been changed starting with the current `next` release which is `1.0.1`. I am going to get this one marked as closed for now and if you see the issue again after trying the newer release let me know and I can open it again.

It may be worth checking out the [migration guide](https://docs.n8n.io/1-0-migration-checklist/) as well as there are some breaking changes.
