### ISSUE TITLE
White Screen with Console Error: Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by ReturnXDev** [n8n-io/n8n#6416]
**Describe the bug**
I get a white screen when trying to engage with our n8n deployment.

- We have 3 x users signed up. A week ago none of them but me could access n8n (I am not even the admin user but had been using it the most to setup workflows - colleagues got the white page). 
- We updated n8n to the latest version (0.230.3), they still could not access it but I could. 
- After a few hours I got the same bug. 
- Returning today (13 June 2023) and I magically could access n8n with no changes on our part.
- After poking around and trying to setup an export which bugged out a little, when I refreshed the page I once again am met with the white screen and the console error: 

"Uncaught SyntaxError: Invalid or unexpected token (at ParameterInputList-518bddf7.js:57:11744)"

This almost points me to think I did something that it wasn't happy about and now some process is running that has shut me / us out.

**To Reproduce**
Literally we would just go to our n8n instance and it wouldnt load anything. 

- Trying different Chrome user profiles did nothing.
- Trying Edge and Firefox did nothing
- Clearing cache nothing - hard refresh cache clear etc did nothing

It was the same for my colleagues.

**Expected behavior**
To interact with n8n - can't login / can't see anything

**Environment (please complete the following information):**

- OS: Hosted on Digital Ocean Droplet via Docker Compose
- n8n Version [0.230.3]
- Node.js Version [e.g. 16.17.0] - we havent changed any of that
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] - we havent changed any of that
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]  - we havent changed any of that assume 'Own'

**Comment by Joffcom** [comment]
Hey @ReturnXDev,

This sounds like a deployment issue, If you access the IP for your n8n instance directly does it work?

**Comment by ReturnXDev** [comment]
So we don't have a static IP but trying the one via Digital Ocean and it does not work. 
Currently my colleague has access to it but not me.
Is there anything I could check for?

**Comment by ReturnXDev** [comment]
We obviously also have access to the CLI - is there anything we could do via that that should 'reset' anything (without losing any workflows or executions that are running) of course.

**Comment by ReturnXDev** [comment]
When using the ip address with the port I was able to see it, thank you!

the url is: https://n8n.dripcel.com/ let me know if you are able to see anything there? I still have the console error if I go to that url...

**Comment by ReturnXDev** [comment]
When I was trying to create an export of the executions of a workflow the dropdown list for filtering, workflows, "select workflow" didn't load any of my workflows even though there are a few.
Now that I access it via the port that list still does not load... 
I raise this because it was after that that it 'crashed' and I could not log back in...

**Comment by Joffcom** [comment]
Hey @ReturnXDev,

For me that URL works, It looks like you have n8n behind Cloudflare and it is caching. Turn off the caching in Cloudflare and everything will start to work.

Did you also open this on the support forum? Just noticed a similar post and I am not sure if it is you or someone else.

**Comment by ReturnXDev** [comment]
No I didn't post anywhere else but I did see a few similar issues with no resolution.
Regarding CloudFlare caching, I know you can't just know Digital Ocean settings but there is nothing on the account about CloudFlare, as far as I know I'd have to go through the actions of enabling any of that and we definitely haven't. 
I will reach out to their support to see if it is something they can shed some light on.

**Comment by ReturnXDev** [comment]
We are using the official n8n self-hosted repo - would any of the CloudFlare stuff be integrated into that?
As I say we've poked around DO settings and can't find anything to turn off.

**Comment by ReturnXDev** [comment]
As we saw with other issues and as per your advice @Joffcom it was due to Cloudflare - however it was via DNS and through the domain hosting with GoDaddy - once we deactivated it worked.

**Comment by Joffcom** [comment]
Hey @ReturnXDev,

That is good to hear, I will mark this one as closed for now. Happy automating 🎉
