### ISSUE TITLE
Executions are showing up as failed even if they succeeded, and the execution time is showing up as negative

### ISSUE THREAD

**Issue by omrijoyous** [n8n-io/n8n#6423]
**Describe the bug**
![image](https://github.com/n8n-io/n8n/assets/134003555/e8974c29-c4c5-400d-8caf-c46c2318f5a3)
I see failed executions even though they were completed successfully, these executions are alway showing up with a negative time.
This only happens if the web server crashed and came back to life and there were executions that were in progress.

**To Reproduce**

1. Trigger an execution
2. Kill the web server, I run it locally so I used kill -9 {web server pid}
3. Wait for the execution to be completed
4. Launch the server
5. Go to executions page and look for the completed execution, you should see the execution as failed but if you look at it you can see that all nodes were executed successfully.

**Expected behavior**
When the web server starts again it should not set the executions that were running successfully as failed.

**Environment (please complete the following information):**

- OS: Mac & Linux
- n8n Version: Latest
- Node.js Version: NodeJs 16-18.
- Database system: PostgresSQL
- Operation mode: Queue (Redis)

**Additional context**
You can see in this screenshot that the execution is marked as failed even though it was successfully completed.
![image](https://github.com/n8n-io/n8n/assets/134003555/a4334c95-eddc-4575-ad89-96c497c4e042)

**Comment by Joffcom** [comment]
Hey @omrijoyous 

Can you confirm the version? Is it the latest tag or the latest source and is it using our unmodified project or your own fork?

When this happens does the main instance or the worker log any output?

This issue does sound familiar so it could be something we are aware of as well, I will check our internal tickets in the morning to see if I can find it.

**Comment by omrijoyous** [comment]
Hi @Joffcom, thanks for your quick response! 
We're using our own fork that is synced with https://github.com/n8n-io/n8n/tree/master, the version we use is Version 0.231.0.
**The worker** is working as expected and doesn't log any errors, the only thing I see in the web process is this:
_**2:00:24 PM web.1 |  2023-06-13T21:00:24.985Z | debug    | Send data of type "executionRecovered" to editor-UI "{\n  dataType: 'executionRecovered',\n  sessionId: undefined,\n  file: 'abstract.push.js',\n  function: 'send'\n}"**_

One more thing that I just noticed is that the view under the workflow's executions looks good (**workflow/4/executions/195**)

And it's only the main executions page that is showing wrong data (/executions).
I added a screen recording that is showing the issue:

https://github.com/n8n-io/n8n/assets/134003555/004bb90f-fcf7-425f-91d1-b3270c6442b4

**Comment by Joffcom** [comment]
I couldn't find anything recent for this one so I have created `N8N-6499` for the team to prioritise.

**Comment by Joffcom** [comment]
Moving to closed, This should now be resolved. If this is still an issue let me know and we can open it again.
