### ISSUE TITLE
TWITTER API: "rejected client-not-enrolled" (current node doesn't support API v2)

### ISSUE THREAD

**Issue by MrCaringi** [n8n-io/n8n#6424]
**Describe the bug**
whenever I try to call a twitter API, it throws an error (http request or twitter node)
`rejected client-not-enrolled Forbidden - perhaps check your credentials?`

**To Reproduce**

Setup a HTTP request node:
1. Authentication: "Predefined CXredential type"
2. Credential type: "Twitter OAUTH API"
3. Credential for twitter OAuth API: "your credential" (credential is connected successfully)
4. Request Method: "GET"
5. URL: https://api.twitter.com/2/users/184762463/tweets
6. response format: "JSON"

**Expected behavior**

**Environment (please complete the following information):**

- OS: ubuntu aarch64
- n8n Version 0.232.0 (docker)
- Node.js Version (no idea)
- Database system postgres:14.5
- Operation mode queue
- Redis 6.2.7 

**Additional context**
Output JSON
```
{"status":"rejected","reason":{"message":"Forbidden - perhaps check your credentials?","timestamp":1686703250831,"name":"NodeApiError","description":"client-not-enrolled","context":{},"cause":{"message":"403 - {\"client_id\":\"25430649\",\"detail\":\"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.\",\"registration_url\":\"https://developer.twitter.com/en/docs/projects/overview\",\"title\":\"Client Forbidden\",\"required_enrollment\":\"Appropriate Level of API Access\",\"reason\":\"client-not-enrolled\",\"type\":\"https://api.twitter.com/2/problems/client-forbidden\"}","name":"Error","stack":"Error: 403 - {\"client_id\":\"25430649\",\"detail\":\"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.\",\"registration_url\":\"https://developer.twitter.com/en/docs/projects/overview\",\"title\":\"Client Forbidden\",\"required_enrollment\":\"Appropriate Level of API Access\",\"reason\":\"client-not-enrolled\",\"type\":\"https://api.twitter.com/2/problems/client-forbidden\"}\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}}
```

**Comment by Joffcom** [comment]
Hey @MrCaringi 

In the error back from Twitter I noticed this...

"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal."

It looks like you could be using the wrong app credentials, our current Twitter credential only supports the v1 API which could be why you are seeing this.

**Comment by Joffcom** [comment]
Hey @benborges 

The current node doesn't support v2 but we are working on that. Some users with older Twitter apps that uses v1.1 with elevated access (which is still free) can still use the Twitter node.

**Comment by benborges** [comment]
Ohhh that's why! Thanks for letting me know, I thought I was doing something wrong and the Twitter node not being ready was just a suspicion!

**Comment by MrCaringi** [comment]
> Hey @benborges
> 
> The current node doesn't support v2 but we are working on that. Some users with older Twitter apps that uses v1.1 with elevated access (which is still free) can still use the Twitter node.

thanks!
do you know if there is a git-branch including this fix?

**Comment by johackim** [comment]
I have this error too since one week :

```txt
ERROR: Forbidden - perhaps check your credentials?
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

**Comment by Joffcom** [comment]
Hey @johackim 

This is to be expected at the moment unless you have an account with elevated access but I think Twitter are removing those so you will need the v2 node which is still going through review.

**Comment by Joffcom** [comment]
I am going to mark this as closed for now and we can pick it back up again if anyone still has issues.

**Comment by mbakgun** [comment]
> I am going to mark this as closed for now and we can pick it back up again if anyone still has issues.

Hi Joffcom, my previous standalone(1.1) application was deprecated yesterday by Twitter, and I've started experiencing the same issue. So, I've created V2 and added OAuth2 credentials. However, I'm unable to see the added credential while editing previously added workflows which contain Twitte Node. If I create a new workflow containing a Twitter node, it detects the OAuth2 credentials and works fine. Any user experiencing the same issue, can remove the node and add it again. 

Version : 0.236.1

**Comment by Joffcom** [comment]
Hey @mbakgun,

You got it, So the Twitter overhaul is a new node version and I believe it has a new credential for it as well so the node needs to be added again to get the new version.

**Comment by benborges** [comment]
Steps I did : 

- removed the old node
- added the new node
- edited the auth and reconnected my account
- test tweet fails

```
ERROR: Forbidden - perhaps check your credentials?
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

**Comment by Joffcom** [comment]
Hey @benborges,

Looks like Twitter is saying you may need to do something else with your Twitter account.

> You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product

**Comment by benborges** [comment]
Perhaps and i have no idea what.. The app belongs to a project, its saying that i can do 1500 free tweets a month and that's it. There is nothing else i CAN do on Twitter side.. I have another access on Elevated that keep working just fine but using the "free tier" is resolutely impossible, even after the node upgrade.

When I connected the app it did connect to the right Twitter app.. No idea why it's not working, because there is nothing on Twitter side to actually hint me in the right direction about this.

**Comment by benborges** [comment]
`This is from Twitter dev community

TwitterDev Twitter Staff
July 19

As announced previously, we have deprecated our legacy Twitter API access tiers. By default, developers have access to the Free tier of the Twitter API. This access level gives access to:

V1.1 Media Endpoints to upload media

V1.1 OAuth endpoints (Login with Twitter)

V2 Manage Tweet endpoints to create/post Tweets

V2 users/me endpoint

If you call other v1.1 Twitter API endpoint, you will get the following response:

{
    "errors": [
        {
            "message": "You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product",
            "code": 453
        }
    ]
}
If you need access to other endpoints, you can sign up for either the Basic or Pro packages. These packages give developers access to a suite of v2 endpoints such as v2 search (in addition to the endpoints mentioned above) at different rate limits, read and post limits.

If you are an enterprise customer and are receiving this message, please contact your account manager.


`

So the way I understand this, the free tier has the ability to create tweets, but the Twitter node is making some other request that Triggers this reply from the Twitter API?
