### ISSUE TITLE
Data from previous nodes is undefined when I drag and drop the field from the tree

### ISSUE THREAD

**Issue by omrijoyous** [n8n-io/n8n#6447]
**Describe the bug**
Data from previous nodes is undefined when I drag and drop the specific field from the tree

**To Reproduce**
Please see screen recording

**Expected behavior**
The drag and drop should use a different expression, when I write the expression manually it works, I followed these instructions:
https://community.n8n.io/t/how-to-get-input-data-from-2-or-more-previous-node/7641/2

**Environment (please complete the following information):**

- OS: Linux
- n8n Version: 0.231.0
- Node.js Version: 18
- Database system : Postgres
- Operation mode: Queue

**Additional context**

https://github.com/n8n-io/n8n/assets/134003555/3ca2438e-12ad-4217-b3bf-418df5450e1a

**Comment by Joffcom** [comment]
Hey @omrijoyous,

What node is the data coming from and what does the full workflow look like?

The syntax from the selection is correct but I suspect it is data coming from a code node and there is no paired item data being set.

**Comment by T3uZ** [comment]
> Ei@omrijoyous,
> 
> De qual nó vêm os dados e como é o fluxo de trabalho completo?
> 
> A sintaxe da seleção está correta, mas suspeito que sejam dados provenientes de um nó de código e não há dados de itens emparelhados sendo definidos.

Olá,
Não estava certa, ta com algum BUG.
Antigamente era $node.... não esta aparecendo mais, com isso gerando erro.

**Comment by omrijoyous** [comment]
@Joffcom I will see if I can reproduce this issue easily with a simple workflow, I will update this thread with my findings.

**Comment by Joffcom** [comment]
@omrijoyous I suspect if you use a code node or maybe a merge node you will be able to reproduce this but at the moment that is to be expected.

**Comment by omrijoyous** [comment]
I was not able to reproduce it easily, closing the issue.

**Comment by luizeof** [comment]
@Joffcom @omrijoyous 

I got the same error on 0.235.0. Just drag and drop


[workflow.webm](https://github.com/n8n-io/n8n/assets/257004/30e09100-efbd-4e9e-8308-ec1278b1fd01)
