### ISSUE TITLE
Dropbox binary not read by Youtube node

### ISSUE THREAD

**Issue by ngeorgj** [n8n-io/n8n#6449]
**Describe the bug**
When receiving a downloaded file from dropbox as binary, youtube cannot read it.

**To Reproduce**

1. Create node Dropbox (dowload file)
2. Set filename
3. Connect node "upload youtube video"
4. Run it

**Expected behavior**
Video should be uploaded.

**Environment (please complete the following information):**

- OS: docker
- n8n Version 0.231.2
- Node.js Version 16.19.1
- Database system SQLite
- Operation mode not sure

**Additional context**

I've added the following environment variables:

N8N_DEFAULT_BINARY_DATA_MODE = filesystem
N8N_PAYLOAD_SIZE_MAX = 200

**Comment by ngeorgj** [comment]
![image](https://github.com/n8n-io/n8n/assets/60124818/55e1cd70-e715-4564-8577-70c9f6b58a71)

**Comment by Joffcom** [comment]
Hey @ngeorgj 

Are you getting any error messages?

**Comment by Joffcom** [comment]
Hey @ngeorgj,

Just a quick one of this, I have given this a go on `0.233.0` and it appears to be working as expected with the video being uploaded to Youtube.

![image](https://github.com/n8n-io/n8n/assets/4688521/1cc229b9-b68d-4ce5-ad76-f860d7ca328e)

I suspect this could be down to an issue with the workflow itself, Can you open a post on our community support forum (https://community.n8n.io) and include the workflow and error you are getting when trying.

For now as this can't be reproduced with the steps provided and it doesn't look like a bug I am going to mark this one as closed.
