### ISSUE TITLE
Recovery Password not working in latest versions

### ISSUE THREAD

**Issue by hichxm** [n8n-io/n8n#6465]
**Describe the bug**

When I use the "Recovery Password" option to retrieve the reset password link, I got "[Object Promise]" instead of the link to reset password. 

**Environment :**

- OS : Debian 11
- n8n Version : latest (0.232.0) w/ docker compose
- Node.js : IDK, I use a docker compose version
- Database system : SQLite
- Operation mode : own

**Additional context**

I'm back to 0.227.0, and is working, I can retrieve link instead of "[Object Promise]" in mail.

**Example of email received**

```
Hi Hicham,  

Somebody asked to reset your password on n8n (xxx).  

Click the following link to choose a new password. The link is valid for 2 hours. 

[object Promise]
```

**Comment by netroy** [comment]
@hichxm The fix is available on `0.233.1`
