### ISSUE TITLE
When the fixed-collection item is clicked, the data in the options  will be reloaded

### ISSUE THREAD

**Issue by ybom77** [n8n-io/n8n#6467]
**Describe the bug**

When the input loses focus, or the value of other UI elements changes, it causes the Options UI with remote requests to frequently request data again. Is this a bug?

**To Reproduce**

1.select Asana Node
![image](https://github.com/n8n-io/n8n/assets/15134783/e61613aa-88af-4d80-8f50-8f596545f8c9)

2 Click add property

3 The 'Workspace Name or ID' and 'Team Name or ID' are always making remote requests to load the data.

**Expected behavior**

The Remote data should only be loaded once

**Environment (please complete the following information):**

- OS: win11
- n8n Version  0.233.0
- Node.js Version v18.16.0
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Comment by ybom77** [comment]
Thanks for your reply @Joffcom 

This is my node : 

```
import {INodeType, INodeTypeDescription, ILoadOptionsFunctions, INodePropertyOptions} from "n8n-workflow";

export class TestRequest implements INodeType {
	description: INodeTypeDescription = {
		defaults: {
			name: "TestRequest Node"
		},
		description: "TestRequest remote request",
		displayName: "TestRequest Node",
		name: "TestRequest Node",
		group: [],
		inputs: ["main"],
		outputs: ["main"],
		version: 1,
		properties: [
			{
				displayName: 'Select Name',
				name: "testRequest",
				type: "options",
				description: 'TestRequest load data. Choose from the list',
				typeOptions: {
					loadOptionsMethod: "loadTestRequests"
				},
				default: ""
			}, {
				displayName: 'Input Something',
				name: "input",
				type: "string",
				default: ""
			}
		]
	}
	methods = {
		loadOptions: {
			loadTestRequests: async function (this: ILoadOptionsFunctions): Promise<INodePropertyOptions[]> {
				return new Promise((resolve, reject) => {
					setTimeout(() => {
						resolve([{name: 'Name1', value: "value1"}, {name: 'Name2', value: "value2"}])
					}, 5000)
				})
			}
		}
	}
}

```

What confuses me is:
1: When I click the name1 or name2 option in the drop-down box, the data will be loaded remotely
2: When I enter a character in the input, the input loses focus, and remote data will be loaded
3: When I refocus on the input and modify the value, the data will be loaded remotely


Steps

![demo](https://github.com/n8n-io/n8n/assets/15134783/322021d2-5130-4030-908e-9e86bd02efb4)

**Comment by ybom77** [comment]
Hey @Joffcom 

In the N8N (0.233.0) service I started locally, all nodes behave like this

**Comment by Joffcom** [comment]
Hey @ybom77,

I have just given it a quick test on the Baserow node as an example and that one doesn't appear to do it. I will see if I can set up a test Asana account in the morning to see if that node does it as well.

Can you share a list of the nodes you found this one... Not forgetting that if a node value is linked to a load options we do expect that to load.
