### ISSUE TITLE
Selecting Multiple Nodes not possible in 0.231.3

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#6478]
Dear Developers,

In versions 0.231.3 and the one preceding it, the ability to select multiple nodes by drawing a box around them (via click and drag) seems to be missing. This change hinders workflow efficiency as it necessitates the individual selection of nodes while holding down the 'ctrl' key.

Could this feature be fixed please 🙏🏻, as its absence complicates the process of dealing with large numbers of nodes?

My environment details are as follows:

OS: Ubuntu 22
n8n Version: 0.231.3
Node.js Version: 18x
Database: Postgres
Operation mode: Queue

Thank you for your attention to this matter.

**Comment by janober** [comment]
Thanks a lot for reporting this problem. I just tried with precisely that version, and for me, it works fine. Can you please try to make a hard refresh in the browser to make sure that there is not some strange caching stuff going on (using somehow different files from different versions or something like that) if that does not solve the issue, can you please report what operating system you are using to access n8n and which browser + version you are using. Thanks a lot!

**Comment by prononext** [comment]
Sadly still not possible to select mutiple nodes with click and drag, even in 233.1. Tested from multiple hosts and browsers without success.

**Comment by Joffcom** [comment]
Hey @prononext,

I have also tested on multiple hosts and browsers and have not been able to reproduce this. Are you able to be more specific about the hosts and browsers? Are they maybe devices with touch screens? Does this only happen with your instance of n8n or do others work as expected? As a test if you go here: https://n8n.io/workflows/1750-creating-an-api-endpoint/ and press Click to Explore does it let you select the workflows there?

**Comment by prononext** [comment]
No there I am also not able to do a drag and select. Yes I also use laptops with touchscreen, but also tested on 2 windows machines without touchscreen from different networks.

**Comment by Joffcom** [comment]
Hey @prononext,

I am out of ideas on this one, I have not been able to reproduce this at all and I am out of test machines. I have tried a Windows Laptop, 2 Chromebooks, A desktop with Windows and Linux and 2 different Macbooks with no joy.

When you try to select the multiple nodes what actually happens? Do you get the selection line or does nothing happen at all? Is there anything in the browser dev console?

Any chance you could use something like Loom to record your screen when you try so we can see what is happening?

**Comment by prononext** [comment]
Nothing happens. No selection line - nothing. All other applications, files, apps, sites let me do a drag + select - n8n not :-(
Screen recording will not do the charm, just imagine draging the mouse without clicking, sadly thats what happens at my side.
Hopefully it will work again soon.

**Comment by Joffcom** [comment]
Does everything work as expected in 0.230.3 or 0.231.2? If we can narrow down the versions we might be able to work out what changed.

**Comment by Joffcom** [comment]
@prononext I have asked around and I have found another community member with the same issue and they have had it for a while and a team member with the issue.

The only thing in common with these are the devices all have touchscreens attached and it doesn't matter if they are being used or not.

When you tested on other devices did they also have touch screens on them (even if touch is disabled)?

**Comment by Joffcom** [comment]
Just adding that I am linking this to `ADO-618` which I suspect is the same issue.

**Comment by prononext** [comment]
Hi @Joffcom, yes it is definately the touchscreen. 

When going to Device Manager and deactivating all HID-compliant devices related to the touchscreen, than it works again. 

It seems strange because other platforms have no problems allowing drag and select with the touchscreen active. 

Maybe there is a solution for n8n soon.

**Comment by prononext** [comment]
**I still get that problem on version "1.22.6"**

When disableling all touchscreen cababilities via the device manager it works, but that is quite a brutal way. 

I wonder why it worked before  version 0.200 I guess, because I alway selected multiple nodes there on the same device, without disabeling the touchscreen via hardware manager. The problem is on all major browsers: Chrome, Firefox, Edge...

**Comment by Joffcom** [comment]
Hey @prononext 

I will check the status of the ticket, I know this still comes up on the forum sometimes.

**Comment by kent-1** [comment]
Hi,

v 1.27.1 same issue. If I update to 1.30.1 is this problem will be fix ?

**Comment by gl0zzy** [comment]
I am a surface pro user and have the same problem.
Is there currently any other solution besides disabling the touch screen?

**Comment by Joffcom** [comment]
At the moment disabling the touch screen is still the only option, This should be fixed in next few weeks though.

**Comment by gl0zzy** [comment]
> At the moment disabling the touch screen is still the only option, This should be fixed in next few weeks though.

I'm glad to know that this issue will be fixed

**Comment by Joffcom** [comment]
Moving to closed, This was fixed in `1.47.0`
