### ISSUE TITLE
WordPress Credentials bug

### ISSUE THREAD

**Issue by andersonjeccel** [n8n-io/n8n#6503]
**Describe the bug**
Every workflow that uses WordPress credentials to run is giving an error.

I have identified that the cause of this is that when you create the credentials, the platform simply transforms the password (corresponding to the application password created in WordPress) into a different value than what was entered by the user.

When I click to review the password as an expression instead of a fixed value, the following value is returned: __n8n_BLANK_VALUE_e5362baf-c777-4d57-a609-6eaf1f9e87f6

So, n8n tries to use this invalid credential to log in and fails.
I have checked several things on my end regarding the WordPress installation, but I strongly believe the issue does not lie there.

**To Reproduce**

1. Proceed to the WordPress credential creation screen.
2. Fill in the user information, password, and URL.
3. Observe the encountered error.

**Expected behavior**
It was expected for the platform to indicate success upon saving the credentials.

**Environment (please complete the following information):**

OS: Debian 11 Server
n8n Version 0.227.1
Node.js Version 16.19.1
Database system n8n default on Docker
Operation mode own

**Comment by Joffcom** [comment]
Hey @andersonjeccel,

That value is to be expected as we don't return the encrypted credential to the UI and instead we will show something similar to what you are seeing.

Can you share any details on the error you are seeing that took you down this path?

**Comment by Marten-S** [comment]
I had the same problem with the Wordpress node. After filling in the credentials N8N displayed an error (Unauthorized).

In my case there was a problem with a redirect (non www to www) on the Wordpress site. I debugged the problem by querying the Wordpress api using a tool like postman. As soon as I changed the url in the N8N node to include www, therefore bypassing the redirect, the error disappeared.

I hope this helps.

**Comment by andersonjeccel** [comment]
My issue is different. The platform displays a Forbidden error.
I hadn't made any changes whatsoever in the workflow; it simply ceased to function and started encountering this issue after updating to the latest stable version.

**Comment by vinitercariol** [comment]
I have the same error, any help for the solution? thanks

**Comment by Joffcom** [comment]
@vinitercariol what error do you have? At the moment the original issue is to be expected and is not an error.

**Comment by vinitercariol** [comment]
> @vinitercariol what error do you have? At the moment the original issue is to be expected and is not an error. 

Hello, I have this error:

https://community.n8n.io/t/wordpress-credential-fail/27616

**Comment by Joffcom** [comment]
Hey @vinitercariol 

That looks like the status field is invalid, it is not the same as what is reported here.

I will check out the forum post in more detail shortly.

**Comment by Joffcom** [comment]
I am going to mark this as closed for now and we can pick it back up again if this issue remains and we can get more details on how to reproduce it.
