### ISSUE TITLE
SendInblue deprecation

### ISSUE THREAD

**Issue by NarHakobyan** [n8n-io/n8n#6504]
**Describe the bug**
Send in blue sdk is deprecated, please update to brevo [@getbrevo/brevo](https://www.npmjs.com/package/@getbrevo/brevo)

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @NarHakobyan,

Doesn't look we are using the SendInBlue SDK but we do have `NODE-578` open to rebrand the node and update the API URLs as needed.

Where did you find the SendInBlue SDK in use?

**Comment by NarHakobyan** [comment]
SendInBlue now deprecated, it's called Brevo, it's better to move to brevo's api.

**Comment by Joffcom** [comment]
Hey @NarHakobyan,

Perfect, I spotted the SDK mention. We are already tracking the rebrand and API update which will happen soon.

**Comment by Joffcom** [comment]
The change for this has been merged and will be available in the next release, For now I am going to mark this as closed.

**Comment by janober** [comment]
Fix got released with [`n8n@0.236.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.236.0)
