### ISSUE TITLE
Slack node uses deprecated scopes

### ISSUE THREAD

**Issue by trygvis** [n8n-io/n8n#651]
**Describe the bug**
The Slack-Node requests the deprecated `conversations:read` and `conversations:history` scopes leading to authorization failures when trying to authorize the app.

Message from Slack:

> Invalid permissions requested
> User tokens do not support scopes: conversations:history, conversations:read 

I'm using OAuth authentication and guessed which scopes that is required, I couldn't find a list of required scopes.

**To Reproduce**
Try to publish a slack message with OAuth authentication.

**Environment (please complete the following information):**
 - n8n Version: 0.69.1, from the published docker image

**Comment by RicardoE105** [comment]
@trygvis Just sent a PR fixing this, will let you know when is released. Again, Thanks.

**Comment by janober** [comment]
Fix got released with n8n@0.71.0
