### ISSUE TITLE
"Execute once" option in Outlook node doesn't work

### ISSUE THREAD

**Issue by sxlabs** [n8n-io/n8n#6510]
Hi,

we run the 0.228.2 release in a Docker container.

We see the following problem, the "Execute once"-option does not seem to have any effects in executions.

Can you please check?

Kind regards,
sxlabs

**Comment by Joffcom** [comment]
Hey @sxlabs 

Can you share the workflow? I can't think of a reason for it to not work unless you have 2 nodes going into the Outlook node.

**Comment by sxlabs** [comment]
Share via EMail? Public file upload would be against our compliance rules.

**Comment by Joffcom** [comment]
Hey @sxlabs 

It should be safe to share here, the workflow is just json and you can replace anything that you feel is sensitive.

Or... you can share a screenshot of the workflow which would only contain the labels and should be ok from almost any compliance framework.

**Comment by Joffcom** [comment]
Hey @sxlabs,

Any updates on this one?

**Comment by Joffcom** [comment]
Closing for now, Will re-open this when we get more information.
