### ISSUE TITLE
Slack-Node use deprecated attributes when posting messages.

### ISSUE THREAD

**Issue by trygvis** [n8n-io/n8n#652]
**Describe the bug**

The `as_user` flag for the "post message" request is deprecated and can't be included if the user is using bot tokens. If it is included this is returned from Slack:

> ok | error | deprecated_argument
> -- | -- | --
> false | invalid_arguments | as_user

https://api.slack.com/methods/chat.postMessage#arg_as_user

**To Reproduce**

Try to send a message with Authentication=Access Token and use a Bot token.

**Environment (please complete the following information):**
 - n8n Version HEAD form master.

**Additional context**

If I add `delete body.as_user` at line 456 of [Slack.node.ts](https://github.com/n8n-io/n8n/blob/c7a901083b30611ed03f403dae1473d8ad716e8e/packages/nodes-base/nodes/Slack/Slack.node.ts#L456) the message is posted as my bot user.

A proper fix I think would be to remove the as_user entirely.

**Comment by RicardoE105** [comment]
@trygvis Just sent a PR fixing this, will let you know when is released. Again, Thanks.

**Comment by janober** [comment]
Fix got released with n8n@0.71.0

**Comment by inn0kenty** [comment]
The `as_user` parameter may not be used with newer bot tokens. But still, it may be used with [user tokens](https://api.slack.com/authentication/token-types#user_tokens). This fix broken this possibility. 

The as_user with user token works fine in 0.70.0.

So, I suppose we should delete as_user from a request body only when it false. In this case, bot tokens and as_user with user tokens will be work.
