### ISSUE TITLE
CLI tool build command does not copy PNG file when using --watch flag

### ISSUE THREAD

**Issue by ivov** [n8n-io/n8n#654]
**Describe the bug**
The CLI tool command `n8n-node-dev build --watch` does not copy the PNG file inside of the directory where the command is executed.

**To Reproduce**
1. Create a new node directory: `cd packages/nodes-base/nodes/ && mkdir MyNewNode && cd MyNewNode`
2. Create a new node: `n8n-node-dev new`
3. Paste any PNG file (intended as an icon for the node) inside the directory.
4. Run `n8n-node-dev build --watch`
5. Inspect the `~/.n8n/custom/` directory. The TS files will have been transpiled into JS there, but the PNG file will _not_ have been copied.

**Expected behavior**
Per the docs, the CLI tool command `n8n-node-dev build --watch` should copy the PNG file inside of the directory where the command is executed. For reference, the `n8n-node-dev build` command (no flag) copies the PNG file properly.

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - n8n Version: 0.69.0
 - Node.js Version: 12.18.0

**Additional context**
I believe the problem is on [this line](https://github.com/n8n-io/n8n/blob/1451f94814eb5d67e6dbb5f81c5d7bd9ecb408d1/packages/node-dev/src/Build.ts#L108) of the build command.

The files are copied only when the `exit` event is triggered, which means that they are not copied when the build command has the `--watch` flag.

One solution would be to take `copyfiles()` out of `buildProcess.on()` so that it is always run regardless of whether the `exit` event is triggered. I have tried this solution and it properly copies PNG files with and without the `--watch`.

```
copyfiles(
  [path_1.join(process.cwd(), "./*.png"), outputDirectory],
  { up: true },
  () => {
    resolve(outputDirectory);
  }
);

buildProcess.on("exit", () => {
  tsconfigData.cleanup();
})
```

I'm from the [MLH Fellowship](https://github.com/MLH-Fellowship/) and I would be happy to turn it into a PR, if you think this is an appropriate solution.

**Comment by janober** [comment]
Thanks a lot @ivov!

Yes, that makes sense. Guess would not be the 100% solution as it would just copy it once in the beginning and not if people change the icon in between but would for sure help to solve it for most people. So yes please send a PR. Thanks!
