### ISSUE TITLE
233.1 with High CPU Usage and Instance Timeout/Crash

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#6544]
I just updated from 231.3 to 233.1 and noticed a very high CPU Usage (100%) on workflows wich I usually do daily and they never to higher than 30% CPU Usage for months in a row. 

On running on the load, the Instance timed out and had to be restarted. 
I checked on any container logs on my docker queue setup but more than "last session crashed" I did not see. 

Would be nice to know how to resolve this. For now I am back to 231.3. 

Server: Ubuntu 22 (8C/12GB)

Have a nice day!

**Comment by Joffcom** [comment]
Hey @prononext,

What are your workflows doing? How long were you running 233.1 for until you noticed the higher than normal usage?

**Comment by prononext** [comment]
Hi @Joffcom I noticed it immediately. 

- Tested a workflow in manual run = Timeout + Instance not reachable anymore
- Tested a workflow via cron = Timeout + Instance not reachable anymore
- Tested a workflow via webhook = Timeout + Instance not reachable anymore

Every time I waited at least 15 Minutes for the instance to get back up but even that the CPU load got back down, the instance did not get back online to reach the GUI. 

After restart the workflow in executions just showed failed without displaying any progress in the executions view.

**Comment by Joffcom** [comment]
Hey @prononext 

That is worrying but not something that has been reported by anyone else which makes me wonder if it was environmental or related to your workflows.

Can you share your n8n config and a workflow that caused the issue so we can try and reproduce it? Would be interesting to see if it happens again if you upgrade as well.

**Comment by prononext** [comment]
ok I guess all the old versions of the HTTP Request and Batch nodes where not compatible anymore and got the server hot. 
Done a big overhaul and replaced all of them... now the CPU load is acceptable again.  Thanks

**Comment by prononext** [comment]
Yes @Joffcom maybe there was also a code node existent. I guess that problem is a bit related to my issue https://github.com/n8n-io/n8n/issues/4867 were also code and http requests nodes together resulted in that high load.  
I was running about 10 pages with each 100 items in a http request loop and than used a code node to merge the requests split included arrays into single items. As every item contained about 50 different fields the new http request and code nodes did a bettter job I suppose.
