### ISSUE TITLE
Manual Execution with strange node behavior

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#6546]
When developing a workflow it is often needed to test it manually and I noticed several strange behaviors on the following nodes:

- Merge Nodes
- Compare Dataset Nodes

When the workflow is quite big and you are doing some corrections after about 5-10 nodes into the workflow and you use a merge node or compare dataset node and try to use the data of the workflow, which already executed by clicking just run on that specific merge oder compare dataset node, it gives a strange behavior: 

The Merge or Compare Dataset Node has:

- Has no output at all
- Has faulty output (compare not correct + merge not correct)

Normally when cleaning the data and starting the workflow from the beginning by pressing "execute workflow" that problem does not appear and merge and compre node behave normally. 

That behavior is quite frustrating when you are trying around on a specific part of a workflow and think you got it wrong and after long trail and error you find out its just how you start the workflow...

**Comment by Joffcom** [comment]
Hey @prononext,

Do you have a workflow that reproduces this issue?

**Comment by Joffcom** [comment]
Hey @prononext,

I was just looking at this again, This is when you use the execute node option maybe inside a loop or on the other side of a multi output node right?

**Comment by kcyd** [comment]
I guess I'm seeing the same issue with the IF node.

When the IF node receives multiple items and its manually executed with 'Execute Node' the following node gets wrongly linked data and fails.
![image](https://github.com/n8n-io/n8n/assets/106734227/541f0986-ba91-4eb1-8721-ea7eb21266e5)

![image](https://github.com/n8n-io/n8n/assets/106734227/61d80dea-8f49-4c59-9e3d-fe4273a54472)

![image](https://github.com/n8n-io/n8n/assets/106734227/a144e7bb-73b4-4eac-b76f-e4aa9ed1e2a2)

When executing the workflow with 'Execute Workflow' all is correct

**Comment by Joffcom** [comment]
Hey @kcyd,

Can you share the workflow json so we can try and reproduce this?

**Comment by kcyd** [comment]
[Test_If.zip](https://github.com/n8n-io/n8n/files/12182946/Test_If.zip)

**Comment by kcyd** [comment]
I'm using 0.233.1 currently

**Comment by Joffcom** [comment]
That works, I suspect this is similar to an issue we are tracking internally at the moment, I will check out the internal issues and see what I can dig out.

**Comment by Joffcom** [comment]
Moving this to closed as I believe this was resolved a long time ago. If this is still a problem let me know and we can open it again.
