### ISSUE TITLE
when using http_proxy and https_proxy,n8n will send http request to https port

### ISSUE THREAD

**Issue by sudoexec** [n8n-io/n8n#6554]
**Describe the bug**
My n8n instance run in a isolated network and I need to use proxy. I set http_proxy and https_proxy in container.
The bug is "n8n will send http request to https port". I've tried Telegram node and the NocoDB node. The error for Telegram node is:
```
ERROR: Bad request - please check your parameters
400 The plain HTTP request was sent to HTTPS port 400 Bad Request The plain HTTP request was sent to HTTPS port nginx/1.18.0
```
```
NodeApiError: Bad request - please check your parameters
    at Object.apiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Telegram/GenericFunctions.js:82:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Telegram/Telegram.node.js:1677:36)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:652:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:596:53
```

To understand what happend, I point the http_proxy and https_proxy to BurpSuite and here is the http request from n8n(NocoDB node):
```
GET http://n8n.example.com:443/api/v1/db/meta/projects/mydb/tables HTTP/1.1
Accept: application/json
xc-token: my_token
User-Agent: axios/0.21.4
host: n8n.example.com
Connection: close
```
The host in the credential is https://n8n.example.com. But why n8n send http request to 443 port?

**To Reproduce**

Taking Telegram node for an example:
1. set http_proxy and https_proxy in environment
2. create a Telegram node and credential
3. execute node
4. you'll get the error like I described above

**Expected behavior**
n8n axios shouldn't send http request to https port.

**Environment (please complete the following information):**

- OS: NixOS 20.09
- n8n Version: 0.233.1
- Node.js Version: (use official docker image)
- Database system: PostgreSQL
- Operation mode: (default)

**Comment by Joffcom** [comment]
Hey @sudoexec,

Is this your forum post here about the same issue: https://community.n8n.io/t/telegram-error-bad-request-please-check-your-parameters/27484?

**Comment by sudoexec** [comment]
@Joffcom  Yes, it's the same one. I'll close that in forum.
