### ISSUE TITLE
Accessing data from specific nodes no longer possible

### ISSUE THREAD

**Issue by zuuring** [n8n-io/n8n#6574]
<img width="260" alt="Screenshot 2023-06-30 at 10 07 12" src="https://github.com/n8n-io/n8n/assets/7145746/3645ad73-31b6-4bd4-9e56-980d2204434a">

**Describe the bug**
As of the latest update, it seems no longer possible to access node data using "node-name" if there are more than 1 items of data, which was previously possible. The only way around this problem was for us to combine items using the merge node and then item list to combine datasets. 

**To Reproduce**
Setup a flow with second node being a set and last node being a item list. Try to access first Set node data and you'll get "invalid expression", however it works when

**Expected behavior**
It should be like previous where you could easily access node data without worrying about it's position in the workflow chain.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.233.1
- Node.js Version: 18.16.1
- Database system: PostGRES
- Operation mode: own

**Additional context**
This seemed to happen after updated to 0.233.1 as the workflow in question was working prior to this update without changes.

**Comment by Joffcom** [comment]
Hey @zuuring,

I have just given this a go but have not been able to reproduce it, Can you share a workflow that reproduces this issue?

This is what I have

![image](https://github.com/n8n-io/n8n/assets/4688521/b5b0eaf2-8ba0-41d3-95df-064624985e24)

And in the last Set node I see this

![image](https://github.com/n8n-io/n8n/assets/4688521/8c2e3919-0be0-41c9-a4c6-074bc0b1900e)

**Comment by janober** [comment]
@zuuring I think the screenshot above says what the problem is `Invalid Expression`. You have the expression split into 3 separate lines. That is not and was never supported in n8n. If you put it all in the same as @Joffcom above it will work fine.

**Comment by zuuring** [comment]
This seems to happen only when the initial output data is greater than 1 item and this very workflow was working prior to the latest update without being altered. I was able to resolve the issue by merging inputs into one stream and then resolving output this way.

**Comment by zuuring** [comment]
> @zuuring I think the screenshot above says what the problem is `Invalid Expression`. You have the expression split into 3 separate lines. That is not and was never supported in n8n. If you put it all in the same as @Joffcom above it will work fine.

I am not sure what you mean, this has always been working for me in n8n -> see screenshot. 
<img width="289" alt="Screenshot 2023-06-30 at 11 36 37" src="https://github.com/n8n-io/n8n/assets/7145746/0eeca512-7558-45e8-8341-a419c3f6451f">

**Comment by Joffcom** [comment]
@zuuring Can you use the debug helper node to produce some mock data and provide a workflow that reproduces this issue?

**Comment by zuuring** [comment]
It looks like I've figured out the culprit. It seems like no longer this expression works but the second one does as intended:

doesn't work: `{{ $('Set').item.json.name }}`

works: `{{ $node.Set.json.name }}`
<img width="342" alt="Screenshot 2023-06-30 at 11 45 01" src="https://github.com/n8n-io/n8n/assets/7145746/bdba8f67-ccb0-4dde-bd04-d3e9a47ad66b">


I was unable to share so here is the raw JSON output of the test workflow:

```{
  "name": "Bug test",
  "nodes": [
    {
      "parameters": {},
      "id": "ec76134f-d8a7-4b88-9003-bcd43b1af1a8",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        700,
        360
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "63067848-8869-4af4-a38c-dbe69c3203ef",
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 2,
      "position": [
        920,
        360
      ]
    },
    {
      "parameters": {
        "operation": "summarize",
        "fieldsToSummarize": {
          "values": [
            {
              "aggregation": "concatenate",
              "field": "name"
            }
          ]
        },
        "options": {}
      },
      "id": "0df5a252-88f4-4436-88b6-f87adb411c29",
      "name": "Item Lists",
      "type": "n8n-nodes-base.itemLists",
      "typeVersion": 2.1,
      "position": [
        1140,
        360
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "value": "={{ $('Set').item.json.name }}\n\n{{ $node.Set.json.name }}"
            }
          ]
        },
        "options": {}
      },
      "id": "fa939f84-7946-4072-8859-1a8e7c75a784",
      "name": "Set1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 2,
      "position": [
        1360,
        360
      ]
    }
  ],
  "pinData": {
    "Set": [
      {
        "json": {
          "name": "First item",
          "code": 1
        }
      },
      {
        "json": {
          "name": "Second item",
          "code": 2
        }
      }
    ]
  },
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "Item Lists",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Item Lists": {
      "main": [
        [
          {
            "node": "Set1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "versionId": "9c07e1b1-9723-4160-8763-d78fb1c50108",
  "id": "13",
  "meta": {
    "instanceId": "bddc4b8f5e7ec3cc7cd0a824ecd9fd6391d5f9a4b96b6f1fb55902b0b2c9f370"
  },
  "tags": []
}```

**Comment by Joffcom** [comment]
@zuuring That is handy, So that looks like where the amount of items is going from 2 to 1 the paired items is not working as it doesn't know which item to link back to. I am surprised this worked on older versions as I would have expected the same issue but I will do some testing to confirm, You can still access the items though but when data goes from 2 items to 1 item it is hard to know which item is meant to be used.

![image](https://github.com/n8n-io/n8n/assets/4688521/da7953c9-199b-4ba4-9626-42dc983f508c)

**Comment by zuuring** [comment]
@Joffcom Thank you and it does sound like one of those edge cases where it was maybe working as it shouldn't of before and now is working how you want it to be. I've also remedied it by merging items in this use case so it can just be accessed with `{{ $json.propertyName }}` instead of accessing it from the specific node. Is it so that `{{ $node.Set.json.name }}` is also the old method of accessing nodes? Cheers!

**Comment by Joffcom** [comment]
@zuuring Yeah $node.Name is an old way of doing it and will likely also cause issues, You could use some of the other $() options if you know where in the data the item you want is.

**Comment by luizeof** [comment]
I have the same question .. what would be the pattern when we do drag and drop?

[workflow.webm](https://github.com/n8n-io/n8n/assets/257004/b0abb681-e2b9-4cfc-8d75-caf560867e91)

This is the new notation for referencing nodes?

{{ $('Code').item.json.myNewField }}

**Comment by luizeof** [comment]
@Joffcom 

I have a history of n8n versions here ... version 0.228.2 was the last one where when dragging and dropping a value from a previous node it came with the syntax:

```
{{ $node.Code.json.myNewField }}
````

[227.webm](https://github.com/n8n-io/n8n/assets/257004/787ccb70-102d-4a08-842c-b325b9c15dd4)

from 0.229, we started to have this new expression:

```
{{ $('Code').item.json.myNewField }}
```

[workflow.webm](https://github.com/n8n-io/n8n/assets/257004/e3801dc8-a902-4a4e-88fb-42407f771853)

What brings us confusion is this mix of expressions. older workflows have one syntax and new ones have another syntax.

Will this new syntax be the default from now on?

**Comment by luizeof** [comment]
@Joffcom thank you very much for the clarifications. I'm going to make a video about it here for the community because there are a lot of people "changing" the new syntax to the previous one.

Thank you again ;)

**Comment by Joffcom** [comment]
@luizeof in English 😄 I do enjoy seeing your videos pop up in my feed.
