### ISSUE TITLE
HTTP Request Node does not properly support PROPFIND method

### ISSUE THREAD

**Issue by FireWhale** [n8n-io/n8n#6581]
**Describe the bug**
The PROPFIND http method can send a body with the request. However, this block in the HttpRequest node apparently restricts any body being added if it is not a PATCH, POST, PUT, or GET request:
https://github.com/n8n-io/n8n/blob/7a8b85ab11fb0dbfa110fb48bad7928791e2486b/packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts#L1219

**To Reproduce**

1. Add an HTTP Request node
2. Change the method type to "Expression" and enter "PROPFIND" into it
3. Activate the Send Body section
4. Add any kind of Body content. In my case, I was trying to add Raw XML.

**Expected behavior**
I expect the body to be sent along with the request. This body is often used in PROPFIND to request extra data (or a subset of existing data)

**Environment (please complete the following information):**

- OS: Whatever OS the official n8n docker image uses
- n8n Version 0.231.1
- Node.js Version Whatever Node.js version the official n8n docker image uses
- Database system Postgres
- Operation mode own

**Additional context**
<none>

**Comment by FireWhale** [comment]
Possible Changes:
1. Add PROPFIND to the enum of HTTP methods <-- I can see arguments against this though. I personally had no idea what PROPFIND was before today.
2. Remove the `['PATCH', 'POST', 'PUT', 'GET'].includes(requestMethod)` completely <-- I have no idea if there are any bad ramifications or if it would lower the user experience
3. Just add PROPFIND to the array (aka `['PATCH', 'POST', 'PUT', 'GET', 'PROPFIND'].includes(requestMethod)`) <-- this would solve my problem
4. Disable the Send Body option when it's not in the array of approved HTTP methods (along with some info on why it's disabled). Or put some kind of warning there. <--- really anything to let the user know it's not going to work so they don't have to dig into the actual n8n code to figure out why

**Comment by Joffcom** [comment]
Hey @FireWhale,

We try to keep GitHub issues for bugs only, as this isn't a bug can you open a feature request on the community support forum?

**Comment by janober** [comment]
Btw. would then probably make sense to mention that there are apparently even more:
https://webconcepts.info/specs/IETF/RFC/4918

[COPY](https://webconcepts.info/concepts/http-method/COPY) , [LOCK](https://webconcepts.info/concepts/http-method/LOCK) , [MKCOL](https://webconcepts.info/concepts/http-method/MKCOL) , [MOVE](https://webconcepts.info/concepts/http-method/MOVE) , [PROPFIND](https://webconcepts.info/concepts/http-method/PROPFIND) , [PROPPATCH](https://webconcepts.info/concepts/http-method/PROPPATCH) , [UNLOCK](https://webconcepts.info/concepts/http-method/UNLOCK)

**Comment by Joffcom** [comment]
Perfect thanks @FireWhale, I am going to mark this as closed for now. I will also add Jans notes to the request as well.

**Comment by janober** [comment]
Also linking the community request:
https://community.n8n.io/t/add-support-in-the-http-request-node-for-the-propfind-http-method/27697/2
