### ISSUE TITLE
FileMaker Node : incorrect error handling

### ISSUE THREAD

**Issue by airmoi** [n8n-io/n8n#6584]
**Describe the bug**
When the API returns an error with status code 4XX, the node does not throw an error nor return the corresponding error response from the API.
This error occur since the API was updated and does not return a 200 status code when an error occur. It now instead returns a 4XX status code. 

**To Reproduce**
Run a create or update record action with for instance an invalid value for a fields which will trigger a validation error

**Expected behavior**
The node should return the API's error code and message in json format

**Environment (please complete the following information):**

- OS: docker 0.220.1  image

**Additional context**
I'm posting this bug report just because I'm currently creating a pull request to fix it ;)

**Comment by Joffcom** [comment]
Hey @airmoi,

Thanks for this, as there is a PR open we can handle this from there and for now I will mark this as closed.
