### ISSUE TITLE
QueryFailedError: SQLITE_ERROR: table execution_entity has no column named data + High Ram usage

### ISSUE THREAD

**Issue by Zoey2936** [n8n-io/n8n#6595]
**Describe the bug**
QueryFailedError: SQLITE_ERROR: table execution_entity has no column named data 
Additionally, the ram usage of n8n increases into the infinity until the server freezes because of too less ram, with n8n container stopped there are over 32gb of ram+swap free

**To Reproduce**

1. Run n8n using docker

**Expected behavior**

**Environment (please complete the following information):**

- OS: [Debian 12]
- n8n Version [Latest Docker version inside n8nio/n8n:latest]
- Node.js Version [Latest Docker version inside n8nio/n8n:latest]
- Database system [SQLite]
- Operation mode [own?]

**Additional context**
I've updated my n8n container and a few minutes later my server freezed

**Comment by Joffcom** [comment]
Hey @Zoey2936 

Can you confirm the version you are running on?

I suspect at some point you upgraded to 234 then downgraded to 233 or your container is automatically updating.

For now if you manually set your version to 0.234.0 you should be good to go.

**Comment by Zoey2936** [comment]
it is using 0.233.1

**Comment by Zoey2936** [comment]
so do I understand correctly that latest used 234 and then reverted to 233?

**Comment by Joffcom** [comment]
Hey @Zoey2936,

Yeah we pulled the release maybe a bit too soon so if your containers are auto updating it will cause an issue.

For now if you manually set the version in your config to 0.234.0 it should get you back up and running.

**Comment by Zoey2936** [comment]
they don't auto update (since this often breaks them), but I update them once a day by hand

**Comment by Zoey2936** [comment]
But yes pinning 234 fixed it, but could you please try to prevent something like this from happening? like stopping n8n from launching if the n8n version is older then the highest version saved in the database for example and writting this into the log, please?

**Comment by Joffcom** [comment]
Hey @Zoey2936,

We will need to do something, normally a downgrade won't break something but in this case the database migration was one way.

In this case preventing n8n from launching wouldn't have helped, we  need to think more before pulling a release, we did add a note to the release notes page as well to let users know so if you are manually updating I would recommend checking that first which would have helped with this one but won't help anyone automatically updating.

It is a tricky one but we will get better, for now though I am going to mark this as solved.
