### ISSUE TITLE
Hyphen after the word Docker

### ISSUE THREAD

**Issue by sandramsc** [n8n-io/n8n#6625]
**Describe the bug**
A hyphen after the word **Docker-**, which makes it unclear if the hyphen was meant to be followed by another word i.e Docker-**Compose** or it was unintentionally added and canbe removed.

**To Reproduce**

1. **Go to:** The README.md file [here](https://github.com/n8n-io/n8n/tree/master/docker/images/n8n)
2. **Click on:** [Passing Sensitive Data via File](https://github.com/n8n-io/n8n/tree/master/docker/images/n8n#passing-sensitive-data-via-file)
3. **Scroll down to:** "...That makes it possible to load data easily from Docker- and Kubernetes-Secrets."
4. **See error**

**Screenshot**
For more context, see attached screenshot:
![docker](https://github.com/n8n-io/n8n/assets/19821445/4a43055d-bcc9-492f-be97-33cf551d6469)

**Comment by Joffcom** [comment]
Hey @sandramsc,

I have updated this in the PR you have open so that we can handle it all in one go. For now I am going to mark this one as closed, Thanks for taking the time to report it.
