### ISSUE TITLE
Logging in redirects to wrong path if N8N_PATH is set

### ISSUE THREAD

**Issue by axsuul** [n8n-io/n8n#6627]
**Describe the bug**

We are hosting our n8n instance on a subpath by setting `N8N_PATH=/n8n/`. However the redirect after logging in adds the subpath again erroneously.

**To Reproduce**

1. Access n8n instance at https://example.com/n8n
2. Redirected to https://example.com/n8n/signin?redirect=%252Fn8n to login
3. After logging, it redirects to https://example.com/n8n/n8n

**Expected behavior**

1. Should be redirected to https://example.com/n8n after login
2. The login URL with the redirect set should also instead be https://example.com/n8n/signin?redirect=%252F

**Environment (please complete the following information):**

- OS: Ubuntu 22.04, Docker
- n8n Version: 0.234.1
- Node.js Version: Docker
- Database system: SQLite
- Operation mode: own

**Additional context**

Seems to be an issue others are also facing on the forum: https://community.n8n.io/t/issue-with-signin-redirect-from-a-custom-n8n-path/23174/4

**Comment by Joffcom** [comment]
Hey @axsuul,

I will see if I can reproduce this one, Would you be able to share your docker run command / compose file as well?

**Comment by Joffcom** [comment]
Hey @axsuul,

Is this still an issue for you on the latest release?

**Comment by Joffcom** [comment]
Closing for now, Will open again if this is still an issue.

**Comment by terrytw** [comment]
This is still happening 

```
docker run -d \
  --restart unless-stopped \
  --name n8n \
  --hostname n8n \
  --net custom --ip ****** \
  -e GENERIC_TIMEZONE="********" \
  -e TZ="**********r" \
  -e N8N_PATH=/n8n/ \
  -v /volume1/docker/n8n:/home/node/.n8n \
  docker.n8n.io/n8nio/n8n
```
