### ISSUE TITLE
Gitlab trigger always subscribes to "push" events.

### ISSUE THREAD

**Issue by trygvis** [n8n-io/n8n#663]
**Describe the bug**

No matter which event the trigger is configured to listen to, the subscription is always only subscribed to "push".

**To Reproduce**

1. Create Gitlab trigger, include something other than "push"
1. Look at subscriptions on the Gitlab project, notice that is always is subscribed to "push".

**Environment (please complete the following information):**

 - n8n: master

**Comment by RicardoE105** [comment]
Hey, @trygvis thanks for putting that together. We will check it out.

**Comment by janober** [comment]
Fix got released with n8n@0.71.0
