### ISSUE TITLE
Gitlab node: repository owner should escape slashes

### ISSUE THREAD

**Issue by trygvis** [n8n-io/n8n#664]
**Describe the bug**
Gitlab supports nested project groups `my-group/my-sub-group/my-project`, when doing API calls the slash needs to be URL encoded to %2F so the request against Gitlab becomes:

    GET .../v4/my-group%2Fmy-sub-group/my-project

As a workaround it is possible to enter the literal value "my-group%2Fmy-sub-group".

**Environment (please complete the following information):**
 - n8n master

**Additional context**
An alternative to fixing this bug is to just use the project's id. That might be a more robust solution as it handles the case when a project is renamed or moved to another group.

**Comment by RicardoE105** [comment]
@trygvis again, thanks for putting this together.

**Comment by janober** [comment]
Fix got released with n8n@0.71.0
