### ISSUE TITLE
Code Editor loads placeholder text instead of actual code

### ISSUE THREAD

**Issue by kcyd** [n8n-io/n8n#6648]
**Describe the bug**
Javascript code in the Code node is not loaded into the code editor but replaced with the placeholder text

**To Reproduce**

1. Create new workflow
2. Add Code node
3. Modify the code
4. Close the editor
5. Open the node again - code replaced with placeholder text

**Expected behavior**
previously entered code should be shown

**Environment:**

- OS: n8n docker image
- n8n Version >= 0.231.2 / 0.232
- Database system SQLite

**Additional context**
The issue seems to be introduced by https://github.com/n8n-io/n8n/pull/6390

**Comment by netroy** [comment]
@kcyd I'm not able to reproduce this in `0.236.0`.
Would it be possible for you to upgrade?

**Comment by kcyd** [comment]
happens for me also on 0.236.0

**Comment by Joffcom** [comment]
@kcyd which browser are you using? I have not been able to reproduce it either.

**Comment by kcyd** [comment]
so it looks like there was something in the .n8n folder broken (I have /home/node as a persistent volume).
after cleaning this up its working fine
