### ISSUE TITLE
CLI tool build command fails to find Typescript on Windows

### ISSUE THREAD

**Issue by ivov** [n8n-io/n8n#665]
**Describe the bug**
On Windows, the command `n8n-node-dev build` fails to find the TypeScript installed in the package's `node_modules`. Therefore, the command fails to transpile the files into `~/.n8n/custom`.

![build-fail-screenshot](https://user-images.githubusercontent.com/44588767/84508938-6f917980-ac99-11ea-9157-c83540c5dca8.png)

**To Reproduce**
1. Install CLI tool globally: `npm i n8n-node-dev -g`
2. Create a new node directory: `cd packages/nodes-base/nodes/ && mkdir MyNewNode && cd MyNewNode`
3. Create a new node: `n8n-node-dev new`
4. Transpile the node: `n8n-node-dev build`
5. Inspect the `~/.n8n/custom/` directory. The TS files will _not_ have been transpiled into JS. Note that the error message ends with a success message, but no JS files are created.

**Expected behavior**
The TS should have been transpiled into JS and placed in `~/.n8n/custom/`.

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - n8n Version: 0.69.0
 - Node.js Version: 12.18.0

**Additional context**
According [this line](https://github.com/n8n-io/n8n/blob/002437862d560c412aeaa382fd223caf6a1958d0/packages/node-dev/src/Build.ts#L67), the CLI tool's build command looks for TypeScript in the path `node_modules/.bin/tsc`. That is an extensionless file containing a bash script. The build command tries to execute this file as JavaScript, causing `SyntaxError: Missing ) after argument list`. This issue directly relates to [this commit](https://github.com/n8n-io/n8n/pull/293/files).

On Windows, I solved this by changing the path to TypeScript to `../../node_modules/TypeScript/lib/tsc` or `../../node_modules/TypeScript/bin/tsc`. This should be tested in other operating systems to ensure the CLI tool build command still works with the new path to TypeScript.

I'm from the [MLH Fellowship](https://github.com/MLH-Fellowship/) and I would be happy to turn it into a PR, if you think this is an appropriate solution.

**Comment by janober** [comment]
Fix got released with n8n-node-dev@0.10.0
