### ISSUE TITLE
BUG: execution.waitTill.getTime is not a function

### ISSUE THREAD

**Issue by caiquezanetoni** [n8n-io/n8n#6655]
**Describe the bug**
All workflows with node "Wait" never continue after time wait finish.

**To Reproduce**

1. create workflow 1: `{
  "meta": {
    "instanceId": "8b6baf9c71cd45ab5d4a4c3e88b46e4a72901c7cca53b8371bc1359060b7fd79"
  },
  "nodes": [
    {
      "parameters": {
        "amount": 65,
        "unit": "seconds"
      },
      "id": "cb896746-fb67-4ed5-94df-fcc655798b7e",
      "name": "Wait",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        1260,
        300
      ],
      "webhookId": "a7ec0f9a-70a1-4a57-9d92-85a6f2109579"
    },
    {
      "parameters": {
        "jsCode": "return [\n  {\n    test: 1,\n  },\n  {\n    test: 2\n  }\n]"
      },
      "id": "00aa38e9-255d-4174-899f-4a5b0c4cebff",
      "name": "Code",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        860,
        300
      ]
    },
    {
      "parameters": {},
      "id": "99cae07a-4e68-4a6b-8cb8-ce45342314b6",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        660,
        300
      ]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "name": "SplitInBatches",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 1,
      "position": [
        1060,
        300
      ],
      "id": "a4e893f4-5c5e-449f-8f7b-bd0f39a29512"
    },
    {
      "parameters": {
        "operation": "executeQuery",
        "query": "select * from \"Clientes\" limit 10",
        "additionalFields": {}
      },
      "name": "Postgres",
      "type": "n8n-nodes-base.postgres",
      "typeVersion": 1,
      "position": [
        1460,
        300
      ],
      "alwaysOutputData": true,
      "id": "975ea599-d1ed-4622-ad77-eca9ad66f9c8",
      "credentials": {
        "postgres": {
          "id": "1",
          "name": "Postgres account"
        }
      }
    }
  ],
  "connections": {
    "Wait": {
      "main": [
        [
          {
            "node": "Postgres",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Code": {
      "main": [
        [
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Code",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SplitInBatches": {
      "main": [
        [
          {
            "node": "Wait",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Postgres": {
      "main": [
        [
          {
            "node": "SplitInBatches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`
2. Run workflow 1;
2. Create other workflow while workflow 1 is running, with node "Postgres" ("typeVersion": 2.2), select a valid credential, select schema from list and table from list. Execute the workflow and save; ex: `{
  "meta": {
    "instanceId": "8b6baf9c71cd45ab5d4a4c3e88b46e4a72901c7cca53b8371bc1359060b7fd79"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "fcba6384-a5c4-42bb-b3dc-da528317dbbb",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        640,
        280
      ]
    },
    {
      "parameters": {
        "operation": "select",
        "schema": {
          "__rl": true,
          "mode": "list",
          "value": "public"
        },
        "table": {
          "__rl": true,
          "value": "Clientes",
          "mode": "list",
          "cachedResultName": "Clientes"
        },
        "options": {}
      },
      "id": "87d873ac-031a-42f8-8af7-5a9dd99c84c3",
      "name": "Postgres",
      "type": "n8n-nodes-base.postgres",
      "typeVersion": 2.2,
      "position": [
        860,
        280
      ],
      "credentials": {
        "postgres": {
          "id": "1",
          "name": "Postgres account"
        }
      }
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Postgres",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`
3. Workflow started in step 2 never continue after time wait finish.
4. This error log is generate: `This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: execution.waitTill.getTime is not a function
    at WaitTracker.getWaitingExecutions (/usr/local/lib/node_modules/n8n/dist/WaitTracker.js:83:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Expected behavior**
The workflow with node "Wait" must continue after wait time finish;

**Environment (please complete the following information):**

- OS: Docker `n8nio/n8n:0.236.1`
- n8n Version `0.236.1`
- Node.js Version Docker `n8nio/n8n:0.236.1`
- Database system `PostgreSQL`
- Operation mode `queue`

**Comment by Joffcom** [comment]
Hey @caiquezanetoni 

This looks like it could be related to #6624

**Comment by Joffcom** [comment]
Going to close this one in favour of the other issue for now.
