### ISSUE TITLE
Workflow trigger do not work when passing multiple items

### ISSUE THREAD

**Issue by marlom-rvvup** [n8n-io/n8n#6662]
**Describe the bug**
I've been trying to dynamically trigger an workflow. Everything works if there is only one item. But when passing multiple items, it will always trigger the workflow from the first item.

**To Reproduce**

<details>
<summary>Workflow to reproduce</summary>

The only requirement for this to work is that you have a workflow of id 1, 2 and 3 (or change in the code node named `Switch`)

```json
{
  "name": "My workflow",
  "nodes": [
    {
      "parameters": {
        "jsCode": "const { id, eventType } = $input.first().json;\n\nconst eventMappingToWorkflow = {\n  WORK1: [1,2,3],\n  WORK2: [5],\n};\n\nconst workflowIds = eventMappingToWorkflow[eventType] ?? [];\nconst workflows = workflowIds.map((workflowId) => {\n  return {\n    workflowId,\n    myId: id\n  }\n})\n\nreturn workflows"
      },
      "id": "41bcbe3b-a40b-4000-b58f-3d324cb326cf",
      "name": "Switch",
      "type": "n8n-nodes-base.code",
      "typeVersion": 1,
      "position": [
        1320,
        400
      ]
    },
    {
      "parameters": {
        "workflowId": "={{ $json.workflowId }}"
      },
      "id": "d4f14345-cfa3-488a-91d8-253234c66276",
      "name": "Execute Workflow",
      "type": "n8n-nodes-base.executeWorkflow",
      "typeVersion": 1,
      "position": [
        1500,
        400
      ],
      "notesInFlow": false
    },
    {
      "parameters": {},
      "id": "e17df5fd-792e-471f-9656-d6fb71151ebd",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        1120,
        400
      ]
    }
  ],
  "pinData": {
    "When clicking \"Execute Workflow\"": [
      {
        "json": {
          "id": "test123",
          "eventType": "WORK1"
        }
      }
    ]
  },
  "connections": {
    "Switch": {
      "main": [
        [
          {
            "node": "Execute Workflow",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Switch",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "versionId": "ac9446ef-d839-4a24-9baa-ff13480e0a94",
  "id": "467857708",
  "meta": {
    "instanceId": "4a76d51d29a71c5b99488f8a7cce39b7774a5946d79d1bf7ecaf14e675bdeaed"
  },
  "tags": []
}
```
</details> 

**Expected behavior**

If an array of items is passed from item A to Execute Workflow and using "itemA.workflowId" should dynamically trigger the correct workflow instead of always the first in the list. 

**Environment (please complete the following information):**

- OS: latest MacOS
- n8n Version 0.230.3
- Node.js Version 18
- Database system MySQL
- Operation mode own

**Additional context**
In the UI for the example workflow, in the execution log it shows as if the `workflowId` being used is from the correct item. but when checking the responses, it is the response only from the first workflow, and if you also check the workflows that should have been triggered you will notice that they are not triggered at all.

**Comment by Joffcom** [comment]
Hey @marlom-rvvup,

Thanks for the report, It looks like this is something we are of and have it documented here: https://docs.n8n.io/flow-logic/looping/#node-exceptions

For now as we know about this I am going to mark this one as closed but I will still let you know if we change this in the future.

**Comment by Joffcom** [comment]
We could do, that page is basically there to show how to do a manual loop which is the work around. I will probably have a poke at the node when I get a bit of free time to see what is involved with adding in support.
