### ISSUE TITLE
docker image n8nio/n8n:latest return 1.0.4 instead of 1.0.5

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#6726]
**Describe the bug**

docker image n8nio/n8n:latest return 1.0.4 instead of 1.0.5

**To Reproduce**

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.0.1]
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by netroy** [comment]
@luizeof we are in the process of updating versions. Can you please check again ?

**Comment by Joffcom** [comment]
This looks to be ok now, I am going to mark this as closed.
