### ISSUE TITLE
Hetzner docs incomplete (missing chown step causing permission denied errors)

### ISSUE THREAD

**Issue by rmens** [n8n-io/n8n#6733]
**Describe the bug**
Following the hosting n8n on Hetzner Cloud docs, leads to a n8n container constantly restarting with the error

```
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
Error: Exiting due to an error.
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
Error: Exiting due to an error.
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
Error: Exiting due to an error.
```

**To Reproduce**

1. Install a Hetzner Cloud instance as the instructions say
2. Follow the instructions (I installed in `/opt/`)
3. Run `docker compose up` and watch all the permission denied errors come in

**Expected behavior**
The guide to provide valid instructions

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- n8n Version: What's in the latest Docker

**Additional context**
It seems that n8n runs as user 1000, which doesn't exist on Hetzners default Docker image. Has this been tested before? I had to chown the directories `caddy_config` `caddy_data` `.n8n` and `local_files` to get it working. Please include this in the guide, or don't run as user 1000.

**Comment by netroy** [comment]
The user `1000` comes from the [official nodejs image](https://github.com/nodejs/docker-node/blob/main/18/alpine3.17/Dockerfile#L5), and n8n simply inherits it. 
This is a fairly common practice, but you don't have to use this user, as [docker run](https://docs.docker.com/engine/reference/run/#user) and [docker-compose](https://docs.docker.com/compose/compose-file/05-services/#user) both let you override the user.

> Has this been tested before?

The docker compose setup in the repo has been tested, and is actively used by many users. 
But in the past n8n containers used to start as the `root` user, and we switched to using the `node` (1000) user for security reasons **yesterday**, and are still updating the remaining deployment guides.

**Comment by Joffcom** [comment]
Moving this to closed as this should be resolved in the latest docs release with the move to volumes.
