### ISSUE TITLE
Redis SSL / Custom AC

### ISSUE THREAD

**Issue by Renizmy** [n8n-io/n8n#6735]
Hello,

There doesn't seem to be any way of enabling transit encryption on redis connections, let alone with custom certification authorities.
How can I set this up?

Best regards

**Comment by Joffcom** [comment]
Hey @Renizmy,

At the moment the Redis node doesn't support TLS options but it is something we could look at adding, Would you be able to open a feature request on our community support forum?

If this is for TLS when using Queue Mode we have an open feature request here: https://community.n8n.io/t/redis-tls-support-for-bull-in-queue-mode/17522 that you can pop a vote on.

**Comment by Renizmy** [comment]
It is for both, I will open it
Thank you for the link I did not found the request

**Comment by Joffcom** [comment]
Good news, Support for TLS with Redis will be available in 1.6.0 the PR for this can be found below.

https://github.com/n8n-io/n8n/pull/7047

This won't support self signed certificates if this is required it would be worth creating a feature request on the forum. For now I am going to mark this as closed.
