### ISSUE TITLE
Google Sheets "Could not load list - Please Check your credential" when trying to edit existing node

### ISSUE THREAD

**Issue by tiago-reganha** [n8n-io/n8n#6737]
**Describe the bug**
Google Sheets Node can't connect when editing existing node

**To Reproduce**
1. Create a Google Sheets Node, Operation Append, Select Document and File, add some data
2. Clone the workflow (I think saving it and opening it again is also displaying the same behavior)
3. When trying to edit the node, it will stop being able to get Documents and Sheets list, "Could not load list - Please Check your credential"

The only way to get it working again is to re-define the Operation to something else, then back to Append, which causes the Node to loose all previous data it had with Append Operation

**Environment (please complete the following information):**

- n8n Version 1.0.5 self-hosted
- Database system: PG
- Operation mode: default

**Comment by tiago-reganha** [comment]
Hello @Joffcom 

Here is an example:
![image](https://github.com/n8n-io/n8n/assets/11008934/cad38ae8-8c8b-47e9-8ec7-ae201be054a8)

As I saved and reloaded the workflow page, I can't edit this node unless I reset the document list. And when I do and select the same Document and Sheet, all field and filter data is gone. 

I just tried pasting it to a cloud workflow and the behavior remains. Cloud workflow ID is 6SlptGqXgjQeWgYU if you can access it

`{
  "meta": {
    "instanceId": "9ffc6dd3f39b53f84883430304c5eba24902ce6becd337bde057beb541d550f6"
  },
  "nodes": [
    {
      "parameters": {
        "path": "gerar-etiqueta-cobrancamrw",
        "responseMode": "responseNode",
        "options": {}
      },
      "id": "1a19e74b-88cb-4f88-9258-9b75d9901398",
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        460,
        460
      ],
      "webhookId": "6c6420b1-6157-4fa6-94a5-c19924a56d48"
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.query.type }}",
              "value2": "codmrw"
            },
            {
              "value1": "={{ $json.query.orderid }}",
              "operation": "isNotEmpty"
            }
          ]
        }
      },
      "id": "0bbe3eda-99fc-4052-ac10-c9a1090c18b4",
      "name": "Filter",
      "type": "n8n-nodes-base.filter",
      "typeVersion": 1,
      "position": [
        720,
        460
      ]
    },
    {
      "parameters": {
        "authentication": "serviceAccount",
        "documentId": {
          "__rl": true,
          "value": "1bbtCLPkwAQShYcnvIe0b6v8t0y3APQMSaslu4hgwh5o",
          "mode": "list",
          "cachedResultName": "Shipping Station",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1bbtCLPkwAQShYcnvIe0b6v8t0y3APQMSaslu4hgwh5o/edit?usp=drivesdk"
        },
        "sheetName": {
          "__rl": true,
          "value": 1800507718,
          "mode": "list",
          "cachedResultName": "MRWCobranças",
          "cachedResultUrl": "https://docs.google.com/spreadsheets/d/1bbtCLPkwAQShYcnvIe0b6v8t0y3APQMSaslu4hgwh5o/edit#gid=1800507718"
        },
        "filtersUI": {
          "values": [
            {
              "lookupColumn": "Lote",
              "lookupValue": "={{ $json.query.lote }}"
            }
          ]
        },
        "options": {}
      },
      "id": "36dc1365-23ce-4338-9fda-2b323a990a88",
      "name": "GoogleSheets",
      "type": "n8n-nodes-base.googleSheets",
      "typeVersion": 4,
      "position": [
        980,
        460
      ],
      "alwaysOutputData": true,
      "credentials": {}
    }
  ],
  "connections": {
    "Webhook": {
      "main": [
        [
          {
            "node": "Filter",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Filter": {
      "main": [
        [
          {
            "node": "GoogleSheets",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Comment by Joffcom** [comment]
Hey @tiago-reganha 

From a logging view it would just be if the console output had anything so if you were using docker it would be the docker log command.

Looking at the screenshot though this could be an issue we are tracking internally already as there is an expression in the field.

I will check and get back to you

**Comment by Joffcom** [comment]
Moving to closed as the issue with load options not working when an invalid expression has been resolved. If this is still an issue let me know and we can open it again.
