### ISSUE TITLE
Wehook - ERROR: Cannot read properties of undefined (reading 'getNodeParameter')

### ISSUE THREAD

**Issue by PPCM** [n8n-io/n8n#6761]
**Describe the bug**
When traying to deploy a webhook, on Test URL, n8n generate an error

**To Reproduce**
- Installation Kubernetes insfrastructure (Rancher)
  - Variables used:
    - GENERIC_TIMEZONE : Europe/Paris
    - N8N_HOST : n8n.TLD.com
    - WEBHOOK_URL : https://n8nTLD.com/
  - Networking : Cluster IP / 5678
  - Ingress Reverse proxy redirecting HTTPS/443 request to HTTP/5678
- Start a worflow with a webhook following the documentation (https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/)
- Test the URL: https://n8n.TLD.com/webhook-test/b2773083-6b58-4020-a23f-b4b09ec3773b with a browser with a GET (as configured in the webhook)
- Getting the following error in the browser:
```
{
code: 0,
message: "Workflow Webhook Error: Workflow could not be started!"
}
```
- In n8n, getting the following error
```
ERROR: Cannot read properties of undefined (reading 'getNodeParameter')
 Details
Stack
TypeError: Cannot read properties of undefined (reading 'getNodeParameter')
    at Object.webhook (/home/node/.n8n/nodes/node_modules/n8n-nodes-base/nodes/Webhook/Webhook.node.ts:99:27)
    at Workflow.runWebhook (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:592:33)
    at Object.executeWebhook (/usr/local/lib/node_modules/n8n/dist/WebhookHelpers.js:119:48)
    at /usr/local/lib/node_modules/n8n/dist/TestWebhooks.js:86:37
```
- Getting the following logs
```
{"__type":"$$EventMessageWorkflow","id":"8c5f84df-c9e3-47f1-8788-363e8d3fd927","ts":"2023-07-27T12:24:51.551+02:00","eventName":"n8n.workflow.started","message":"n8n.workflow.started","payload":{"executionId":"8","userId":"a01cf321-64f2-4ecf-9dc1-86533b442e52","workflowId":"lzNlwMmDe6xjHIzG","isManual":true,"workflowName":"My workflow 3"}}
{"__type":"$$EventMessageConfirm","confirm":"8c5f84df-c9e3-47f1-8788-363e8d3fd927","ts":"2023-07-27T12:24:51.551+02:00","source":{"id":"0","name":"eventBus"}}
{"__type":"$$EventMessageNode","id":"14d7e70d-5ab8-407e-aab3-4123f9603164","ts":"2023-07-27T12:24:51.553+02:00","eventName":"n8n.node.started","message":"n8n.node.started","payload":{"executionId":"8","nodeName":"Webhook","workflowId":"lzNlwMmDe6xjHIzG","workflowName":"My workflow 3","nodeType":"n8n-nodes-base.webhook"}}
{"__type":"$$EventMessageConfirm","confirm":"14d7e70d-5ab8-407e-aab3-4123f9603164","ts":"2023-07-27T12:24:51.553+02:00","source":{"id":"0","name":"eventBus"}}
{"__type":"$$EventMessageNode","id":"3ed6991c-3111-4d53-bb78-119fcd6c482f","ts":"2023-07-27T12:24:51.554+02:00","eventName":"n8n.node.finished","message":"n8n.node.finished","payload":{"executionId":"8","nodeName":"Webhook","workflowId":"lzNlwMmDe6xjHIzG","workflowName":"My workflow 3","nodeType":"n8n-nodes-base.webhook"}}
{"__type":"$$EventMessageConfirm","confirm":"3ed6991c-3111-4d53-bb78-119fcd6c482f","ts":"2023-07-27T12:24:51.554+02:00","source":{"id":"0","name":"eventBus"}}
{"__type":"$$EventMessageWorkflow","id":"e1b0e266-7ede-49d9-8987-36dbc9978a49","ts":"2023-07-27T12:24:51.620+02:00","eventName":"n8n.workflow.failed","message":"n8n.workflow.failed","payload":{"executionId":"8","success":false,"userId":"a01cf321-64f2-4ecf-9dc1-86533b442e52","workflowId":"lzNlwMmDe6xjHIzG","lastNodeExecuted":"Webhook","errorNodeType":"n8n-nodes-base.webhook","errorNodeId":"0","errorMessage":"Cannot read properties of undefined (reading 'getNodeParameter')","isManual":true,"workflowName":"My workflow 3"}}
{"__type":"$$EventMessageConfirm","confirm":"e1b0e266-7ede-49d9-8987-36dbc9978a49","ts":"2023-07-27T12:24:51.620+02:00","source":{"id":"0","name":"eventBus"}}
```

**Expected behavior**
Need to have a response like in the documentation

**Environment (please complete the following information):**

- OS: Debian / Kubernetes / Rancher
- n8n Version [e.g. 1.0.1] : 1.0.5
- Node.js Version [e.g. 18.16.0] : Node.js contained in the offical docker
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] : SQLite
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`] : A single node

Tnaks for your help

**Comment by netroy** [comment]
@PPCM are you by any change building a custom docker image, or updating any npm packages in the container?

**Comment by netroy** [comment]
I've tried reproducing this on `1.0.5` and `1.1.0` with no luck so far. 
Looking at the code, the only way this could be happening is if you have version of `n8n-workflow` older than `0.156.0`, and `n8n-nodes-base` newer than `0.234.0` (which should not happen unless the docker image has been customized somehow).

**Comment by netroy** [comment]
are you able to reproduce this when running n8n directly via docker like this
```bash
docker run --rm -it --name n8n -p 5678:5678 docker.n8n.io/n8nio/n8n:1.0.5
```

**Comment by PPCM** [comment]
On my side, I don't have a docker environnent. I only have Kubernetes hosts

**Comment by PPCM** [comment]
I delete my deployment and restart from scratch (no incidence in my case I just start to use n8n)
I know, with the same config, it works fine

I think that something goes wrong during the migration between the previous version and the last version

**Comment by netroy** [comment]
can you please share with us if you had any volume mounts on n8n pods? if yes, what paths ?

**Comment by PPCM** [comment]
It is a please to share :-)

I mount a volume to mount /home/node/.n8n
In fact, this what I scrapped to reset the installation

Currently, I have the same mounted path
