### ISSUE TITLE
Supabase JSON column

### ISSUE THREAD

**Issue by jeanmatthieud** [n8n-io/n8n#6762]
**Describe the bug**
n8n is not able to insert / update json / jsonb content in a supabase record.

**To Reproduce**

1. Create a table with a json or jsonb column in supabase
2. Create a workflow to insert a row into this new table
3. Set the content of the column as a valid JSON object or array with the workflow
4. Execute the workflow

**Expected behavior**
A new record is added to supabase, and the column contains JSON

**Current behavior**
The content is added as plain text in the JSON column.

**Environment**

- n8n Version 1.0.2
- Node.js Version 20
- Database system SQLite
- Operation mode  `main`

**Comment by Joffcom** [comment]
Hey @jeanmatthieud,

Can you share a workflow that reproduces this? I have just given it a go and for me it is correctly adding JSON to the field or at least appears to be.

This is what I have in my workflow...
![image](https://github.com/n8n-io/n8n/assets/4688521/0faa87ce-279e-4d91-9575-b06c74db5f29)

This is what I have in Supabase
![image](https://github.com/n8n-io/n8n/assets/4688521/e7749327-aed2-4c4f-b73f-2e1dd1eeabd3)

Is it possible that you are sending a string rather than a JSON object?

**Comment by Joffcom** [comment]
Just done another quick test... If I just input a string like `{'name':'foo'}` it is sent and stored as a string...

![image](https://github.com/n8n-io/n8n/assets/4688521/499e875e-12a3-49b6-bea0-bb38c1e9c1d1)

![image](https://github.com/n8n-io/n8n/assets/4688521/1c2c27e1-e533-4992-a037-ac8cda0a87d1)

I suspect in this case the data is actually being sent as a string and has not been converted to a JSON object before sending.

@jeanmatthieud assuming you are using an expression can you try something like `{{ JSON.parse( $json.yourVar ) }}` and see if that sends correctly? I believe this will fix issue.

**Comment by jeanmatthieud** [comment]
Hi @Joffcom , 

Thanks for the answer.

Indeed, I used an expression, but without encapsulating it in a javascript block.

Previously (not working):

```json
{
"source_url": {{$json.source_url}},
"width": {{$json.media_details.width}},
"height": {{$json.media_details.height}},
"thumbnail": {{$json.media_details.sizes.thumbnail}}
}
```

Now (working):

```json
{{
{
"source_url": $json.source_url,
"width": $json.media_details.width,
"height": $json.media_details.height,
"thumbnail": $json.media_details.sizes.thumbnail
}
}}
```

**Comment by Joffcom** [comment]
@jeanmatthieud no problem, To be honest I think we can probbaly handle that better in the future as well so I have made a note to look into it in more detail at some point.
