### ISSUE TITLE
Supabase node: ERROR: Protocol "https:" not supported. Expected "undefined"

### ISSUE THREAD

**Issue by manu7823** [n8n-io/n8n#6789]
**Describe the bug**
I got the following error at the supabase node quite often in the last 3 days. To make the node work again, I always have to restart n8n. Any idea, what causes this?

ERROR: Protocol "https:" not supported. Expected "undefined"
<img width="1558" alt="Bildschirmfoto 2023-07-28 um 16 37 46" src="https://github.com/n8n-io/n8n/assets/53856345/1c857c39-20c3-49cd-9084-3f4b0d2e3388">

<img width="949" alt="Bildschirmfoto 2023-07-28 um 16 37 20" src="https://github.com/n8n-io/n8n/assets/53856345/b6d1cf7a-df6d-457e-a743-8770664aa782">

**To Reproduce**

1. Setup a workflow with a supabase node.
2. Loop over the supabase node with around 100 entries using the the "Split into batches node" with batch size 1
3. after 30 or more loops the error occurs randomly 

**Expected behavior**
No error

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 1.0.5
- Node.js Version 18.16.0
- Database system SQLite
- Operation mode main

**Comment by Joffcom** [comment]
Hey @manu7823,

That looks new, Is your workflow just looping or are you writing data as well? The more you can share on the workflow the better.

**Comment by manu7823** [comment]
Hey @Joffcom, 

its writing. At the writing step, the error occurs. I can send you the workflow JSON, if you provide me a way to do this.

**Comment by Joffcom** [comment]
Hey @manu7823,

You can share the workflow here or post it as a gist, Have you tried a smaller test I set up something that follows the steps you provided and included an update row but for me all 202 items I had processed without issue.

![image](https://github.com/n8n-io/n8n/assets/4688521/320fe7c6-4782-41a1-b3be-1b0692d32542)

I suspect your issue could be unrelated to the node or it could be a mix of issues, Are you going out through a proxy or anything and which environment options do you have set? It could also be worth using `1.1.1` instead of `1.0.5` which has a bunch of fixes in it.

**Comment by manu7823** [comment]
Hey @Joffcom,

I'm not using a proxy and I'm using the default environment options of the docker image. 

That's the config. An API Key from [ScrapeOps](https://scrapeops.io/) needs to be added.

`{
  "name": "MyDealz Scraper: GET Deal URL",
  "nodes": [
    {
      "parameters": {
        "rule": {
          "interval": [{}]
        }
      },
      "id": "84a807f3-194e-4ae9-9b9c-d025487297f7",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1.1,
      "position": [1200, 600]
    },
    {
      "parameters": {
        "batchSize": 1,
        "options": {}
      },
      "id": "384ea7ed-8beb-4dc2-8ce1-085e815ff595",
      "name": "Split In Batches",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 2,
      "position": [1640, 600]
    },
    {
      "parameters": {
        "operation": "getAll",
        "tableId": "mydealz_id_to_notion_id",
        "limit": 1000,
        "matchType": "allFilters",
        "filters": {
          "conditions": [
            {
              "keyName": "dealUrl",
              "condition": "is",
              "keyValue": "NULL"
            },
            {
              "keyName": "urlProcessError",
              "condition": "eq",
              "keyValue": "FALSE"
            }
          ]
        }
      },
      "id": "2e8a7cd2-c281-41fa-b5c6-61d29a3bc0a2",
      "name": "GET Deals without URL",
      "type": "n8n-nodes-base.supabase",
      "typeVersion": 1,
      "position": [1420, 600],
      "credentials": {
        "supabaseApi": {
          "id": "1",
          "name": "Supabase account"
        }
      }
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "string": [
            {
              "name": "dealUrl",
              "value": "={{ decodeURIComponent($json.headers[\"sops-final-url\"]) }}"
            },
            {
              "name": "targetUrl",
              "value": "={{ decodeURIComponent($json.headers[\"sops-final-url\"].replace(\"https://mydealz.digidip.net/visit?url=\",\"\")) }}"
            },
            {
              "name": "baseUrl",
              "value": "={{ decodeURIComponent($json.headers[\"sops-final-url\"].replace(\"https://mydealz.digidip.net/visit?url=\",\"\")).split('/', 3).join('/').replace(\"https://\", \"\").replace(\"http://\", \"\") }}"
            },
            {
              "name": "cleanTargetUrl",
              "value": "={{ decodeURIComponent($json.headers[\"sops-final-url\"].replace(\"https://mydealz.digidip.net/visit?url=\",\"\")).split(\"&ppref\")[0].split(\"utm_source\")[0].split(\"utm_campaign\")[0] }}"
            }
          ]
        },
        "options": {}
      },
      "id": "eb6113f9-79c4-4178-a9f1-9fca379d3145",
      "name": "SET Deal URL",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [2120, 220]
    },
    {
      "parameters": {
        "url": "=https://proxy.scrapeops.io/v1/",
        "sendQuery": true,
        "queryParameters": {
          "parameters": [
            {
              "name": "api_key",
              "value": "xxx"
            },
            {
              "name": "url",
              "value": "={{ \"https://www.mydealz.de/visit/threadmain/\" + $json.mydealz_id }}"
            },
            {
              "name": "final_status_code",
              "value": "true"
            }
          ]
        },
        "options": {
          "response": {
            "response": {
              "fullResponse": true
            }
          },
          "timeout": 10000
        }
      },
      "id": "9716f825-cae9-47d7-9398-78d954d486e0",
      "name": "GET Deal URL",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [1860, 220],
      "retryOnFail": false,
      "continueOnFail": true
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.targetUrl }}",
              "operation": "isNotEmpty"
            },
            {
              "value1": "={{ $json.targetUrl }}",
              "operation": "isNotEmpty"
            }
          ]
        }
      },
      "id": "08952c02-8c51-4cfd-bcb7-53ff45ffd889",
      "name": "IF Has URL",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [2700, 340]
    },
    {
      "parameters": {
        "mode": "combine",
        "combinationMode": "mergeByPosition",
        "options": {}
      },
      "id": "efc5770f-c87f-4d94-a76b-b87ed8b33d1a",
      "name": "Merge",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 2.1,
      "position": [2440, 340]
    },
    {
      "parameters": {
        "operation": "update",
        "tableId": "mydealz_id_to_notion_id",
        "filters": {
          "conditions": [
            {
              "keyName": "id",
              "condition": "eq",
              "keyValue": "={{ $json.id }}"
            }
          ]
        },
        "fieldsUi": {
          "fieldValues": [
            {
              "fieldId": "dealUrl",
              "fieldValue": "={{ $json.targetUrl }}"
            },
            {
              "fieldId": "clean_url",
              "fieldValue": "={{ $json.cleanTargetUrl }}"
            }
          ]
        }
      },
      "id": "b47b9998-29bd-46fa-8f08-518b478517ab",
      "name": "ADD resolved URL to Deal",
      "type": "n8n-nodes-base.supabase",
      "typeVersion": 1,
      "position": [3100, 620],
      "credentials": {
        "supabaseApi": {
          "id": "1",
          "name": "Supabase account"
        }
      }
    },
    {
      "parameters": {
        "operation": "update",
        "tableId": "mydealz_id_to_notion_id",
        "filters": {
          "conditions": [
            {
              "keyName": "id",
              "condition": "eq",
              "keyValue": "={{ $json.id }}"
            }
          ]
        },
        "fieldsUi": {
          "fieldValues": [
            {
              "fieldId": "urlProcessError",
              "fieldValue": "TRUE"
            }
          ]
        }
      },
      "id": "e7eef543-4309-4baf-bfb2-5266cbb10282",
      "name": "SET URL process error to true",
      "type": "n8n-nodes-base.supabase",
      "typeVersion": 1,
      "position": [3100, 900],
      "credentials": {
        "supabaseApi": {
          "id": "1",
          "name": "Supabase account"
        }
      }
    }
  ],
  "pinData": {},
  "connections": {
    "Schedule Trigger": {
      "main": [
        [
          {
            "node": "GET Deals without URL",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Split In Batches": {
      "main": [
        [
          {
            "node": "GET Deal URL",
            "type": "main",
            "index": 0
          },
          {
            "node": "Merge",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "GET Deals without URL": {
      "main": [
        [
          {
            "node": "Split In Batches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "GET Deal URL": {
      "main": [
        [
          {
            "node": "SET Deal URL",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SET Deal URL": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF Has URL": {
      "main": [
        [
          {
            "node": "ADD resolved URL to Deal",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "SET URL process error to true",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Merge": {
      "main": [
        [
          {
            "node": "IF Has URL",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "ADD resolved URL to Deal": {
      "main": [
        [
          {
            "node": "Split In Batches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "SET URL process error to true": {
      "main": [
        [
          {
            "node": "Split In Batches",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  },
  "versionId": "46d1565f-290b-4a7b-b94e-9f79ed56cea9",
  "id": "ncfpuARmhaWUkzhs",
  "meta": {
    "instanceId": "df7ee200a5643fb2437c1535ca753cf3d53c684078c0da5b3f21f14496396435"
  }
}
` 

I also tried to reproduce it with a simplified example and can't reproduce it there.

**Comment by Joffcom** [comment]
Hey @manu7823 

Does it happen every time you run that workflow?

**Comment by manu7823** [comment]
Hey @Joffcom 

Not every time but almost every time.

<img width="289" alt="Bildschirmfoto 2023-07-29 um 11 48 59" src="https://github.com/n8n-io/n8n/assets/53856345/edce59aa-7691-425b-871e-dec7d7e8d2f8">

**Comment by Joffcom** [comment]
Hey @manu7823,

Is it always the `ADD resolved URL to Deal` node that fails? Looking at the workflow and from my own testing so far I am wondering if the issue is with the data you are sending.

**Comment by manu7823** [comment]
Hey @Joffcom, 

no it was sometimes the one you mentioned and some times the other one after the if clause.  

I found a workaround over the weekend. I manually recreated the entire workflow without copying and pasting nodes from other workflows as I did before, and now it works.

**Comment by netroy** [comment]
@manu7823 Can you check what the `host` property is configured to in the `Supabase account` credential? does it start with `https://` ?

**Comment by manu7823** [comment]
@netroy yes, it's starts with `https://` and ends with `supabase.co`.

**Comment by Joffcom** [comment]
Hey @manu7823,

Are you using an expression in the credential at all?

**Comment by manu7823** [comment]
@Joffcom no

**Comment by Joffcom** [comment]
Hey @manu7823,

Has this settled down on later releases?

**Comment by manu7823** [comment]
Hey @Joffcom, yes, seems so.
