### ISSUE TITLE
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'

### ISSUE THREAD

**Issue by scramjetFoam** [n8n-io/n8n#6793]
**Describe the bug**
Error: Exiting due to an error.
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'

**To Reproduce**

1. login in ubuntu 20.04 with root 
2. download the latest docker-compose file in subfolderWithSSL in github repo of n8n
3.  docker-compose up -d

**Expected behavior**
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal' appears.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04.6 LTS   armv7
- 1.0.5

**Comment by Joffcom** [comment]
Hey @scramjetFoam,

Which user are you running n8n as?

**Comment by scramjetFoam** [comment]
> Hey @scramjetFoam,
> 
> Which user are you running n8n as?

hey Joffcom,

run with root, not specified with PUID and PGID.

**Comment by Joffcom** [comment]
Hey @scramjetFoam,

Can you try with a normal user and set the permission for the .n8n folder to your_user:root that should get you up and running for now.

**Comment by scramjetFoam** [comment]
> Hey @scramjetFoam,
> 
> Can you try with a normal user and set the permission for the .n8n folder to your_user:root that should get you up and running for now.

hey Joffcom,

Thank you for your nice reply. I am not very proficient in this. Do you mean that I create another user, switch to the new user, and then grant the permissions of the. n8n file owner to root? If possible, could you show me some specific commands?

regards

**Comment by Joffcom** [comment]
Hey @scramjetFoam,

Create a user say `scramjetfoam` then set up your n8n instance and once you have ran it the first time run `chown -R scramjetfoam:root /home/scramjetfoam/.n8n` and that should get you up and running.

You could also try changing your n8n instance to use a volume instead although we don't have that documented.

**Comment by pantelis-antoniadis** [comment]
n8n switched to using the node (1000) user for security reasons some weeks ago.

I created a separate user `n8n` and installed n8n with that user by following this documentation:
https://docs.n8n.io/hosting/installation/server-setups/digital-ocean/#the-docker-compose-file

Before starting docker compose I chowned the following directories to the user `n8n`:
- caddy_config
- caddy_data
- .n8n
- local_files

`sudo chown -R 1000:1000 /home/node/n8n-docker-caddy/caddy_config`
`sudo chown -R 1000:1000 /home/node/n8n-docker-caddy/caddy_data`
`sudo chown -R 1000:1000 /home/node/n8n-docker-caddy/.n8n`
`sudo chown -R 1000:1000 /home/node/n8n-docker-caddy/local_files`

This finally worked for me, and I hope it helps you too.

**Comment by Joffcom** [comment]
You can also run...

```
docker run --rm -it --user root -v ~/.n8n:/home/node/.n8n --entrypoint chown n8nio/base:16 -R node:node /home/node/.n8n
```

Where `~/.n8n` is the path to your n8n volume, This will work if you are running the docker command as root or another OS user.

**Comment by pantelis-antoniadis** [comment]
Thank you @Joffcom!

Which part is missing here if the installation would be done according to your documentation?
https://docs.n8n.io/hosting/installation/server-setups/digital-ocean/#the-docker-compose-file

Because although all instructions were followed, this led to this error:
```shell
Error: Exiting due to an error.
Error: EACCES: permission denied, open '/home/node/.n8n/crash.journal'
```

**Comment by Joffcom** [comment]
Hey @pantelis-antoniadis,

You have not missed anything, After doing some testing it looks like for a lot of installs the docker command is needed. I am going to start work on the deployment guide today to cover a newer way of doing it that won't need the extra step.

**Comment by khanhquocnguyen** [comment]
> Hey @pantelis-antoniadis,
> 
> You have not missed anything, After doing some testing it looks like for a lot of installs the docker command is needed. I am going to start work on the deployment guide today to cover a newer way of doing it that won't need the extra step.

Hi @Joffcom 
Has deployment guide been updated? I got the same issue with the current deployment guide.

**Comment by khanhquocnguyen** [comment]
> Hey @khanhquocnguyen,
> 
> It should be, which guide did you follow?

This guide: https://docs.n8n.io/hosting/installation/server-setups/docker-compose/#5-create-docker-compose-file
But with 2 difference points : I used bind mount instead of volume and under root user.

**Comment by Joffcom** [comment]
I think for now as this isn't a bug as such and is related to a v1 change that is documented (and outdated docs) I am going to get this one closed.

The docs have now been updated and for new installs following them everything should work.
