### ISSUE TITLE
Missing primary key in `execution_data` table for PostgresDB

### ISSUE THREAD

**Issue by ndeitch** [n8n-io/n8n#6794]
**Describe the bug**

New table `execution_data` was introduced in #6345 which has `executionId` as primary key in `mysql` and `sqlite`

Postgresql migration although has no primary key definition: https://github.com/n8n-io/n8n/blob/50b0dc21fd0a698f87538e5458274ed50ab6774e/packages/cli/src/databases/migrations/postgresdb/1690000000020-SeparateExecutionData.ts#L7

Leading to slow queries and high CPU usage in production.

**To Reproduce**

1. Start a brand new version of n8n using docker with postgresql as database;
2. Check `execution_data` table index definitions, none is defined.

**Expected behavior**

Primary key set, SQL instruction:

```sql
ALTER TABLE execution_data ADD CONSTRAINT pk_executionId PRIMARY KEY ("executionId");
```

**Environment (please complete the following information):**

- OS: MacOS Ventura 13.4.1
- n8n Version: 0.235.0
- Node.js Version: v18
- Database system: Postgresql
- Operation mode: queue

**Comment by Joffcom** [comment]
Hey @ndeitch,

Good spot, We have put in a PR which will add the primary key. Once reviewed and merged this will be available in a new release.
