### ISSUE TITLE
N8N webhook configuration error with Wazuh

### ISSUE THREAD

**Issue by romeoCYS** [n8n-io/n8n#6796]
When I try to integrate **wazuh** with **n8n webhook** then, webhook **doesn't recieve any alert or event** from **Wazuh**. I have added all the integrations **ossec.conf** file of wazuh. I have tried almost every technique and have entered all the codes in **ossec.conf** and after that when I try to listen on the n8n webhook, **it doesn't recieve any response from Wazuh.**

I am using **ubuntu desktop** for **Wazuh** and also have deployed **n8n locally on my ubuntu.**

If there is any solution to this problem, please address it

**Comment by Joffcom** [comment]
Hey @romeoCYS 

Have you tried manually accessing the webhook url to see if that works that would let us know if this is an n8n bug or a support issue which would be better suited to our support forum.

**Comment by Joffcom** [comment]
Hey @romeoCYS,

In that cause I would say that this is not a bug with n8n and it is likely to be a configuration issue somewhere so should be on the support forum.

I am not familiar with how Wazuh sends webhooks but are you seeing any error messages? The most common errors I have seen when using webhooks is using localhost as the URL when using containers or having the wrong request method set in the webhook.

Knowing what Wazuh is returning will help work out what is going on or if you can share how you have n8n deployed (docker / npm / from source) and Wazuh deployed along with a screenshot of your webhook settings in n8n and your Wazuh config for sending the webhook notification I can take a quick look.

**Comment by Joffcom** [comment]
Hey @romeoCYS,

Did you manage to get to the bottom of this with Wazuh?

**Comment by Joffcom** [comment]
Hey @romeoCYS,

For now I am going to mark this one as closed, If it is still an issue I would open a topic on the [support forum](https://community.n8n.io) and we can look at it from there.
