### ISSUE TITLE
v1.1.1 reported as latest version despite being `next`

### ISSUE THREAD

**Issue by nihaals** [n8n-io/n8n#6838]
**Describe the bug**
Using n8n's [update checker](https://api.n8n.io/api/versions/1.0.5) on v1.0.5 suggests updating to v1.1.1 despite it being the `next` version, not the `latest`.

**To Reproduce**
1. Go to https://api.n8n.io/api/versions/1.0.5
2. Notice it shows v1.1.1
3. Notice on https://docs.n8n.io/release-notes/ it shows it as being the `next` version, not the `latest`

**Expected behavior**
It doesn't show an update (like how it previously worked).

**Environment**
- OS: Docker
- n8n Version: v1.0.5
- Node.js Version: Docker

**Additional context**
This used to work as expected and would only suggest the `latest` version.

**Comment by netroy** [comment]
Thanks for reporting this. Looks like we had a glitch in our release pipeline.
We've updated NPM and Docker Hub to mark `1.1.1` as the `latest`.
The release notes will be updated shortly as well.

**Comment by nihaals** [comment]
@netroy Should `createdAt` also be set? At the moment it always says it was released just now.

**Comment by nihaals** [comment]
@netroy This is also back again for v1.4.0

**Comment by netroy** [comment]
parts of our release process are still manual, and it can take up to a day for all our docs to be in sync with the code or release tags.
This will be fixed in https://github.com/n8n-io/n8n-docs/pull/1569

**Comment by nihaals** [comment]
Ah I didn't realise it was manual, every time I checked it in the past it was up-to-date so assumed there was a whole pipeline that handled updating GitHub, Docker, npm, the version check API and the docs, sorry for the unnecessary bump!
