### ISSUE TITLE
Configuration error in compose withPostgresAndWorker

### ISSUE THREAD

**Issue by Valdri** [n8n-io/n8n#6857]
[in this compose file on line 69](https://github.com/n8n-io/n8n/blob/adcf5a96e83d8b43b155f5a834a74b3a1fd4274b/docker/compose/withPostgresAndWorker/docker-compose.yml#L69)

command: worker
It won't work and should be like this:
command: n8n worker

**Comment by Joffcom** [comment]
Hey @Valdri 

From version 1 the command should just be worker, can you confirm the version of n8n you are seeing the issue with?

**Comment by Valdri** [comment]
Hi,
I was using version 0.236.3
The [documentation ](https://docs.n8n.io/hosting/scaling/queue-mode/#start-workers)page says "n8n worker" command so I thought it was a error in the compose file.
I think it should be clarified in documentation page that before version 1 it uses "n8n worker" and after just "worker"

**Comment by Joffcom** [comment]
Hey @Valdri,

That is not a bad idea although at some point we do need to work out at what point we remove the older version information. For now as this is resolved I am going to mark it as closed.
