### ISSUE TITLE
Permission denied when writing binary file

### ISSUE THREAD

**Issue by jamesbrunet** [n8n-io/n8n#687]
**Describe the bug**
Using the "write binary file" node causes the following error:

``ERROR: EACCES: permission denied, open 'test'``
``Error: EACCES: permission denied, open 'test'``

**To Reproduce**
1. Follow [server setup instructions](https://docs.n8n.io/#/server-setup) in docs.
2. Create a workflow that writes a binary file. EG: [Sample_Workflow.txt](https://github.com/n8n-io/n8n/files/4808765/Sample_Workflow.txt)
3. Access denied!

**Expected behavior**
I expect a file to be written.

**Environment:**
 - OS: Ubuntu 20.04
 - n8n Version 0.7.0
 - Node.js Version not sure how to check this in the n8n docker instance

**Comment by janober** [comment]
I guess you mean n8n version 0.70.0

Please open an issue here only when you are 100% sure that it is really a bug. Else post it to https://community.n8n.io first. That makes sure that if other people have the same problem in the future there is a single spot where to find answers. Thanks!

What you are describing is expected. You have to make sure that you are allowed to write to the location you try to write to. So in the case of docker you could mount a folder by adding `-v /local-files:/files` and then you can use as path: `/files/test` which should then work fine.
If you do not need the file to be persisted you could also write to the `/tmp` folder and so simply use the path `/tmp/test`. I hope that helps!

**Comment by jamesbrunet** [comment]
Yes, it was version 0.70.0. Typo! Sure, I will post to that forum first next time.

Thank you for letting me know why this behaviour is normal.

**Comment by janober** [comment]
Great thanks!

Yes is "normal" because if no path is supplied it write it relative meaning it writes it to the n8n-folder. So as long as you provide a full path and you have the right to write there it should work fine.
