### ISSUE TITLE
HTTP request failure caused the n8n process to crash

### ISSUE THREAD

**Issue by easydigi** [n8n-io/n8n#6919]
Using HTTP request to send a POST request will cause the entire process to crash if the following conditions are met:

1.Send arbitrary JSON content in the request body.

2.The following switches are turned on:

   2.1 Always Output Data

   2.2 Continue On Fail

Under this scenario, if the request fails, the whole process will crash. For testing, you can modify the URL to any invalid address, such as https://0.0.0.0/.

With arbitrary JSON content, generic credential authentication with basic auth enabled, and the "Always Output Data" and "Continue On Fail" switches on, sending a POST request will cause the process to abruptly crash instead of continuing if the request results in a failure, such as with an invalid test URL.

** Environment (please complete the following information): **

set N8N_DIAGNOSTICS_ENABLED false

- OS: [Docker]
- n8n Version [1.1.1 and 1.2.1]

** The error message is as follows **

```
/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:14

    this._redirectable.emit(event, arg1, arg2, arg3);

                       ^

TypeError: this._redirectable.emit is not a function

    at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/n8n/node_modules/follow-redirects/index.js:14:24)

    at ClientRequest.emit (node:events:513:28)

    at ClientRequest.emit (node:domain:489:12)

    at TLSSocket.socketCloseListener (node:_http_client:475:11)

    at TLSSocket.emit (node:events:525:35)

    at TLSSocket.emit (node:domain:489:12)

    at node:net:322:12

    at TCP.done (node:_tls_wrap:588:7)
```

**Comment by netroy** [comment]
@easydigi Thanks for reporting this.
It was fixed in #6925 and released in [`n8n@1.2.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.2)
