### ISSUE TITLE
WebSockets failing at 1.3.1 on Docker

### ISSUE THREAD

**Issue by digitalextremist** [n8n-io/n8n#6993]
![image](https://github.com/n8n-io/n8n/assets/21095/42782f0a-4267-42e4-a2a9-60e2086cd308)

Shows "connection lost" -- and getting log spam with this error:

```
e_n8n    | RangeError: Invalid status code: 1008
e_n8n    |     at new NodeError (node:internal/errors:399:5)
e_n8n    |     at ServerResponse.writeHead (node:_http_server:344:11)
e_n8n    |     at ServerResponse.writeHead (/usr/local/lib/node_modules/n8n/node_modules/on-headers/index.js:44:26)
e_n8n    |     at ServerResponse._implicitHeader (node:_http_server:335:8)
e_n8n    |     at ServerResponse.end (/usr/local/lib/node_modules/n8n/node_modules/compression/index.js:103:14)
e_n8n    |     at ServerResponse.send (/usr/local/lib/node_modules/n8n/node_modules/express/lib/response.js:232:10)
e_n8n    |     at Push.handleRequest (/usr/local/lib/node_modules/n8n/dist/push/index.js:37:30)
e_n8n    |     at /usr/local/lib/node_modules/n8n/dist/push/index.js:101:68
e_n8n    |     at newFn (/usr/local/lib/node_modules/n8n/node_modules/express-async-errors/index.js:16:20)
e_n8n    |     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/n8n/node_modules/express/lib/router/layer.js:95:5)
```
There are about three of those for every failing `Websocket` request in the browser:

![image](https://github.com/n8n-io/n8n/assets/21095/c4191f16-f748-4a26-a433-9d37c203a469)

**To Reproduce**

1. Update to latest `docker` image, with prior image from before `1.0.0`
2. Fix `/bin/sh` per breaking-change
3. Update permissions
4. Start container

**Expected behavior**

Websockets work.

---

Pardon me if I missed anything there. Can add any other diagnostic information needed.

Does seem somehow connected to this commit:

https://github.com/n8n-io/n8n/commit/a8bfb4618323731de8bc9bc265b3bbb9de69c50c

But not sure why, or what breaking-change I missed, if applicable.

**Comment by Joffcom** [comment]
Hey @digitalextremist,

Have you configured your reverse proxy to support websockets?

**Comment by digitalextremist** [comment]
Hi @Joffcom -- would there have been a change affecting `nginx` on this at the `1.0` shift or later?

Have never had trouble with websockets on this `nginx` instance, in adjacent virtual hosts.

**Comment by Joffcom** [comment]
Hey @digitalextremist,

It is a change you would have had to make to your nginx config after going to 1.0 or later. There is an example here: https://community.n8n.io/t/authentication-required-to-access-rest-login/29455/2?u=jon which might help.

**Comment by digitalextremist** [comment]
Interesting @Joffcom -- here is the relevant piece of my `nginx.conf` and it does not make a connection.

Just the errors shown above come from this, reporting an invalid error code, and a failed connection:

```
    location / {
        proxy_pass http://127.0.0.1:5678;
        proxy_set_header Connection '';
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
    }
```

**Comment by Joffcom** [comment]
Hey @digitalextremist 

There is a bit of a difference between the 2, try and make it more like the example and see if that works.

**Comment by digitalextremist** [comment]
You're right @Joffcom -- was not paying attention to the `Connection` line being blanked out, versus set to `upgrade` which does work. So this one is fixed by `nginx.conf` but I would definitely note this in the `1.0 Migration` write-up somewhere?

**Comment by Joffcom** [comment]
Hey @digitalextremist 

We did think about that, we mentioned the change to websockets but decided not to document the reverse proxy settings as that is outside of n8n and we would need to chose which ones to document.

Instead we opted to rely on the server admins as we treat self hosting as being an advanced option, not ideal for everyone but we do have examples on the support forum and in other GitHub threads where we have worked it out for users that need it.

**Comment by digitalextremist** [comment]
I appreciate the candor @Joffcom 

That makes a lot of sense. I actually enjoyed having these problems afterward ( though there is still a release outstanding to resolve the other ) just to be so forcibly immersed in the `n8n` ecosystem, which is unique, and awesome. Thanks for your help!

**Comment by SergChr** [comment]
In my case, I had `location /` only in my NGINX config while I should have configs for the other endpoints:
```nginx
location /webhook/ {
      proxy_pass http://127.0.0.1:5678;
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
   }

   location /rest {
     proxy_pass http://127.0.0.1:5678;
     proxy_ssl_verify off;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection 'Upgrade';
     proxy_set_header Host $host;
     proxy_ssl_server_name on;
   }
```

[[Source](https://community.n8n.io/t/authentication-required-to-access-rest-login/29455?u=jon)]
