### ISSUE TITLE
[Hubspot] n8n version 1.1.1 get list contact can not include parameter

### ISSUE THREAD

**Issue by trantrinhquocviet** [n8n-io/n8n#6999]
**Describe the bug**

**To Reproduce**

1. Go to 'Hubspot API get list contacts'
2. Click on 'include paramter'
3. Scroll down to 'run workflow'
4. See error: Can not include paramter with Query paramater in this node. Instead, i have to use node Http requests and add property to url.

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Docker]
- n8n Version [e.g. 1.1.1]
- Database system [e.g. Postgres; n8n uses Postgresas default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
![image](https://github.com/n8n-io/n8n/assets/26039338/ca2f8ee5-883a-424a-9fb4-f3ab5b35f2ae)

**Comment by Joffcom** [comment]
Hey @trantrinhquocviet 

Is it only that one property that doesn't get returned and is it a custom property?

**Comment by trantrinhquocviet** [comment]
yes, it's custom property. But when stay old version n8n 0.5. my node hubspot can add custom property and get data.

**Comment by Joffcom** [comment]
Hey @trantrinhquocviet 

When you say 0.5 which version do you actually mean? We did overhaul the Hubspot node recently so it could be related to that, is your workflow the same as the one from the older version or is it freshly made?

**Comment by trantrinhquocviet** [comment]
Yes, i was migrating workflow from version n8n 0.5.6 to version 1.1.1. There are many unconvenient hubspot with new version. I keep my eye the new version n8n that will releases.

**Comment by trantrinhquocviet** [comment]
I provide more information. I have to use offset to get many contacts. So, it's slowly.

![image](https://github.com/n8n-io/n8n/assets/26039338/084f28a6-4019-4610-9a39-5485553d8d81)

**Comment by Joffcom** [comment]
Hey @trantrinhquocviet,

Assuming you migrate the workflow as it was it should work as it did before if you added a new node it would maybe have this issue it would be great to get a copy of the workflow so I can see the node version with the issue and if you could confirm the version that would be handy as well as we didn't do a `0.5.6` release.

**Comment by bingvanmoorsel** [comment]
@Joffcom I'm having the same issue. im trying to add a property aswell and they dont get included. With a default HTTP node it works, but not with the hubspot node.

**Comment by Joffcom** [comment]
@bingvanmoorsel is it also a custom property for you?

**Comment by bingvanmoorsel** [comment]
@Joffcom i had to check, but yes its a custom property. i'm currently using a workaround with an http node. i'm able to get the information from that node!

**Comment by Joffcom** [comment]
It looks like we have a ticket internally already to track this which is `NODE-604`, It is currently in the backlog so I have no ETA on a fix at the moment.

**Comment by Joffcom** [comment]
Moving to closed, This looks to have been solved in [n8n@1.31.1](https://github.com/n8n-io/n8n/releases/tag/n8n%401.31.1)
