### ISSUE TITLE
Youtube Node not Working (upload)

### ISSUE THREAD

**Issue by ngeorgj** [n8n-io/n8n#7010]
**Describe the bug**
Hi everyone, I have ngrok exposing my n8n to the web, trying to make uploads but this seem to be impossible to be honest, I've spent more than 5 hours troubleshooting this and it just does not work. I'm running n8n on my docker instance.

**To Reproduce**
Nodes:
Drive (Download File by ID) -> Returns binary video
Youtube (Upload) -> Receives Binary video, connects to my Oauth2 Credentials and fails.

**Expected behavior**
The downloaded video gets uploaded.

**Environment (please complete the following information):**

- OS: linux on docker
- n8n Version most recent (python available)
- Node.js dockerized version
- Database system sqlite
- Operation mode main

**Additional context**
I really need to make this flow work, I'm spending a lot of time and it's apparently a bug, everything seems fine, I just need to know a way to make it work. Thanks!

**Comment by netroy** [comment]
I just tried this simple workflow and was able to do this without any issues:

```json
{
  "nodes": [
    {
      "parameters": {},
      "id": "c742b9c9-a74c-48b2-8691-23779fdb16ce",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        820,
        420
      ]
    },
    {
      "parameters": {
        "operation": "download",
        "fileId": {
          "__rl": true,
          "value": "REDACTED",
          "mode": "list",
          "cachedResultName": "My Video",
          "cachedResultUrl": "https://drive.google.com/file/d/REDACTED/view?usp=drivesdk"
        },
        "options": {}
      },
      "id": "11043f9f-259c-4991-87d0-1e998a4b4eec",
      "name": "Google Drive",
      "type": "n8n-nodes-base.googleDrive",
      "typeVersion": 3,
      "position": [
        1040,
        420
      ]
    },
    {
      "parameters": {
        "resource": "video",
        "operation": "upload",
        "title": "={{ $binary.data.fileName }}",
        "regionCode": "DE",
        "categoryId": "28",
        "options": {
          "privacyStatus": "private"
        }
      },
      "id": "34767892-ba97-4503-8e9f-ff21bfbd0405",
      "name": "YouTube",
      "type": "n8n-nodes-base.youTube",
      "typeVersion": 1,
      "position": [
        1260,
        420
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Google Drive",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Google Drive": {
      "main": [
        [
          {
            "node": "YouTube",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by ngeorgj** [comment]
I think I had an issue with the OAUTH2 flow, everytime it checks for the credentials it's consuming the API Quota, I have the standard 10k/day quota.

That's why, I reached my quota before executing it for the first time, created another project on the API and it ended up working, but it's certainly unstable, I would say if possible, change the way the credential part works to not consume quota.

We can close this one.
