### ISSUE TITLE
Read Binary File Node fails in ver 1.3.1

### ISSUE THREAD

**Issue by ed-parsadanyan** [n8n-io/n8n#7024]
**Describe the bug**
Read Binary File node fails to read files for some unknown reason on ver. 1.3.1
I've updated n8n in Docker from 1.1.1 to 1.3.1 yesterday and suddenly my workflows that read files stopped working. Docker-compose was not changed and it was working in the past. All the files in questions were accessible via Execute command node, so I assume file permissions and volumes are not the reason.

Downgrading to 1.1.1 solved the problem

**To Reproduce**
1. Update n8n to a recommended version of 1.3.1.
2. Try to read any files from the /home/node/.n8n/ directory
3. Get error message

**Expected behavior**
Correctly read files.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 1.3.1 / 1.1.1
- Node.js Version NA, using in Docker
- Database system Postgres
- Operation mode main

**Additional context**

Using cat command from the Execute Workflow works as expected
![image](https://github.com/n8n-io/n8n/assets/10472129/90b9ffea-bcab-42f0-847b-c3c52b7bf99b)

But the same file cannot be accessed via read binary file node in ver 1.3.1
![image](https://github.com/n8n-io/n8n/assets/10472129/58c84389-1081-4173-8824-58ea04d8279e)

I'm also using a custom n8n build. I was using latest tag before, but after 1.3.1 failed I had to revert back to 1.1.1. This dockerfile works well for me:

```
ARG tag=1.1.1
#latest 0.213.0 0.219.1
FROM n8nio/n8n:$tag
USER root

RUN apk --update add sshpass openssh imagemagick ghostscript poppler-utils curl curl-dev libcurl linux-headers g++ gfortran libxml2 libxml2-dev ffmpeg openjdk8-jre libreoffice
RUN apk add --no-cache msttcorefonts-installer fontconfig
RUN update-ms-fonts

RUN npm install -g pdf-image minify easy-template-x

USER node

```

**Comment by netroy** [comment]
This was intentionally changed in https://github.com/n8n-io/n8n/pull/6582 because letting workflows read/write to `.n8n` folder is a significant security risk.
But you can disable this check by setting the env variable `N8N_BLOCK_FILE_ACCESS_TO_N8N_FILE` to `false`.

**Comment by ed-parsadanyan** [comment]
> This was intentionally changed in #6582 because letting workflows read/write to `.n8n` folder is a significant security risk. But you can disable this check by setting the env variable `N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES` to `false`.

Thanks a lot, I was able to fix it! I wish this was documented somewhere :)
