### ISSUE TITLE
Describing the software as "open and free" is misleading

### ISSUE THREAD

**Issue by rufuspollock** [n8n-io/n8n#704]
**Describe the bug**
At top of README (and on main website) you have text like:

> n8n is a free and open fair-code licensed node based Workflow Automation Tool.

Open source software (and free software) have clear definitions that include the right to use the software for any purpose including commercial ones. fair-code license is not compatible with this. Whilst I quite understand the logic and motivation for fair-code licensing it is **not** free/open, at least as per currently accepted definitions of those terms. Using these terms in this way is clearly misleading.

BTW 👏 👏 on a great piece of software 😄 

**To Reproduce**
1. Go to your website or github repo
3. Scroll down to top
4. See error: misleading terminology

**Expected behavior**
Remove use of free and open. Instead, simply say fair-code licensed.

**Environment (please complete the following information):**
All browsers 😉 

**Additional context**

**Comment by leonstafford** [comment]
@rufuspollock, grab a beverage and read through https://github.com/n8n-io/n8n/issues/40

**Comment by janober** [comment]
Thanks a lot @leonstafford for adding the link and so the background.

@rufuspollock sorry but that will not be changed. n8n is both free and open. I know some people think that those common English words should only be allowed to be used with "OSI approved open-source", I and many other people however strongly disagree. I already spend way too many hours discussion and thinking about that issue and will so not say anything else regarding it. I hope you can understand that (especially if you really take the time to read through #40).

**Comment by paulocoghi** [comment]
@janober , in my opinion, you can put the term "open source" on your software. OSI is a tent, and we can make our own tent where fair-code is a valid software model which can be called open source.

**Comment by paulocoghi** [comment]
@rufuspollock n8n is open _(the source code is open)_ and it's free _(the use is free even for commercial purposes)_.

You can do everything you would be able to do on an approved OSI license, with the only exception being selling n8n itself.

**Comment by rufuspollock** [comment]
@paulocoghi this is a complete abuse of a well defined term - there's an open source definition for a reason https://opensource.org/osd and its to prevent the muddying of the waters like this. 

Once again I think it is great for you to make this software and to make it available in this way ... and it doesn't work to (ab)use well known terms and given them a different more restricted meaning. It's misleading and it misled me.

**Comment by paulocoghi** [comment]
Thanks for the polite explanation, @rufuspollock  . I understand what you mean and I am empathetic to your point of view. I will try to find another alternative term.
