### ISSUE TITLE
Bug: Schedule Trigger is triggered twice when running in high availability

### ISSUE THREAD

**Issue by javespi** [n8n-io/n8n#7045]
**Schedule Trigger is triggered twice when running in high availability**

When a schedule trigger is set-up with custom cron daily, the workflow is executed twice in the same second under a high availability configuration for UI (running two instances of the main process of n8n):

Executions:
![image](https://github.com/n8n-io/n8n/assets/1534117/0a95c4c1-4818-4bc6-908f-b285d49c9aa5)

![image](https://github.com/n8n-io/n8n/assets/1534117/2751ee55-ffb5-4b31-95d5-4a26621d81cb)

Custom (Cron) config:
`0 6 * * *`

[Crontab doc](https://crontab.guru/#0_6_*_*_*) 

**To Reproduce**

1. Create a workflow with Schedule trigger
2. Use as Trigger Interval the option "Custom (cron)" with Expression `0 6 * * *`

Configuration of high availability of the main process with non official helm chart for Kubernetes:
- https://github.com/8gears/n8n-helm-chart

```
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
```

**Expected behavior**

Only one execution instead of two with high availability for UI

**Environment (please complete the following information):**

- OS: Linux Bottlerocket 1.14.3
- n8n Version 1.4.0
- Node.js Version (whatever n8n docker official image has) 
- Database system Postgres
- Operation mode `queue`

**Comment by javespi** [comment]
Thank you @Joffcom for taking a look

> Did you notice this before 1.4.0?

Yes, I noticed it in 1.0.1 version

**Comment by Joffcom** [comment]
Quick update... for me it has worked as expected using the workflow below in both queue mode and normal mode, Are you able to share a workflow that reproduces this or is it all workflows using the schedule trigger node that is causing an issue for you?

```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {
        "rule": {
          "interval": [
            {
              "field": "cronExpression",
              "expression": " 0 9 * * *"
            }
          ]
        }
      },
      "id": "8e04c425-622e-41f2-a9ed-4b354079f128",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1.1,
      "position": [
        820,
        380
      ]
    },
    {
      "parameters": {
        "values": {
          "boolean": [
            {
              "name": "Ran",
              "value": true
            }
          ]
        },
        "options": {}
      },
      "id": "87ef6660-9886-4b6a-b57c-bd9910f9bfc4",
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 2,
      "position": [
        1040,
        380
      ]
    }
  ],
  "connections": {
    "Schedule Trigger": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by javespi** [comment]
> is it all workflows using the schedule trigger node that is causing an issue for you?

It is happening in more than one workflow.

Let me explain a test I have done isolated:

I have created a new workflow, this is the last version:

```
{
  "name": "[Test] Bug Github issue #7045 in n8n",
  "nodes": [
    {
      "parameters": {
        "rule": {
          "interval": [
            {
              "field": "cronExpression",
              "expression": "0 11 * * *"
            }
          ]
        }
      },
      "id": "cd0b1f50-fb27-4082-9fa6-5e9111d70ad2",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1.1,
      "position": [
        860,
        420
      ]
    },
    {
      "parameters": {
        "select": "user",
        "user": {
          "__rl": true,
          "value": "U6D8P9SGJ",
          "mode": "list",
          "cachedResultName": "javierespinosa"
        },
        "text": "=Hello, this is a message test + {{ JSON.stringify($execution) }}",
        "otherOptions": {}
      },
      "id": "d0fbae31-bead-4f55-b562-4f595228f784",
      "name": "Slack",
      "type": "n8n-nodes-base.slack",
      "typeVersion": 2.1,
      "position": [
        1080,
        420
      ],
      "credentials": {
        "slackApi": {
          "id": "3",
          "name": "Slack account"
        }
      }
    }
  ],
  "pinData": {},
  "connections": {
    "Schedule Trigger": {
      "main": [
        [
          {
            "node": "Slack",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": true,
  "settings": {
    "executionOrder": "v1",
    "timezone": "Europe/Madrid",
    "saveManualExecutions": true,
    "callerPolicy": "workflowsFromSameOwner"
  },
  "versionId": "e2173f2b-efae-4e1d-8529-6426caffa5e6",
  "id": "NgQQFTKonvubMRMU",
  "meta": {
    "instanceId": "fbde53140ea23463b18aeb512d0d71a8096750948e3b87fec4e23d07aa444eee"
  },
  "tags": []
}
```

Trigger daily at 11 AM for Madrid GMT+1
Send a message to Slack

First test was triggering at 10:39; and worked as expected

Then I edited because the object of $execution was printed as `[Object object]` and added JSON.stringify...
I set-up for 11 AM (as you can see in the template); and then it was triggered twice and with different messages:

![image](https://github.com/n8n-io/n8n/assets/1534117/19ca97cd-fa22-4434-9c82-788db8d4bb40)
![image](https://github.com/n8n-io/n8n/assets/1534117/cd99d6c6-2f42-4787-a832-17f290743abc)

If I check Executions deep dive, I can see something weird:

One of the executions node of Slack at 11AM:
![image](https://github.com/n8n-io/n8n/assets/1534117/24463bad-b44c-4914-8df6-63a60687ac59)

The other:
![image](https://github.com/n8n-io/n8n/assets/1534117/69d40603-fe04-4fd1-8db4-2c91e3da7546)

Thanks for your time; not sure how can I control or reset the cron config or previous versions of the workflow to not be triggered

**Comment by Joffcom** [comment]
@javespi if you run my test worklfow do you get the same issue? Can you share your n8n configuration as well?

**Comment by ese** [comment]
I was researching this @Joffcom and I think I know what is happening.

We have an n8n deployed as  `EXECUTIONS_MODE=queue` in order to distribute the workload across multiple workers. In addition to workers and for maintaining high availability for the UI we were running a couple of instances of the main process of n8n.

But it seems that triggers and pollers live also in this instance and they don't have a scaling mechanism or leader protocol so they are executing at the same time in all of them. I didn't find a specific mention of this in the documentation I think it would be interesting to have it

Furthermore, it seems there are inconsistency state issues also when you are balancing requests between these two instances.
* Scheduled trigger run based in cached workflows in the instances, so when you change this workflow they are only updated for the instance where the requests come. So you end up having a instance triggering an out of date workflow. If the instance is restarted it retrieve the correct state from database.

Is there any way to configure UI with high availability? Can triggers and pollers be run in a separate instance?

Thanks

**Comment by javespi** [comment]
@Joffcom @ese I've edited the title and description with latest comment details

**Comment by Joffcom** [comment]
Hey @ese,

We don't support HA for the main instance but this would explain why you are seeing this, As n8n is not correctly configure  I guess this is also not technically a bug.

**Comment by javespi** [comment]
@Joffcom okey, then is not a bug, it's a feature :wink: 

Thank you for all the support; we'll open an issue in the helm repository to let them know that main instance cannot have HA and it could provoke side and weird effects in triggers and workflows

I close this issue :+1:

**Comment by Joffcom** [comment]
@javespi if it helps we are working on improving scaling in the future and one of the things I really want is allowing the UI to run in active active configurations.
