### ISSUE TITLE
Webflow node does't work

### ISSUE THREAD

**Issue by trulala1235435** [n8n-io/n8n#7052]
Webflow node with token auth does not work. 
<img width="215" alt="Снимок экрана 2023-08-30 в 21 17 29" src="https://github.com/n8n-io/n8n/assets/21218213/6d284090-000d-4dc0-aa88-6a832acfed85">
<img width="388" alt="Снимок экрана 2023-08-30 в 21 17 54" src="https://github.com/n8n-io/n8n/assets/21218213/24ec30ee-5dc2-4999-8f11-bf12c9103466">
<img width="244" alt="Снимок экрана 2023-08-30 в 21 18 04" src="https://github.com/n8n-io/n8n/assets/21218213/7ece1b77-dbc0-4cbb-acf6-8ffa488c25cb">
<img width="351" alt="Снимок экрана 2023-08-30 в 21 18 17" src="https://github.com/n8n-io/n8n/assets/21218213/a803431e-9783-4b3e-9bec-9723e9901dd3">
<img width="891" alt="Снимок экрана 2023-08-30 в 21 18 52" src="https://github.com/n8n-io/n8n/assets/21218213/d96d1769-aaf2-4d0b-bf62-20a8c3be9b96">
<img width="872" alt="Снимок экрана 2023-08-30 в 21 19 22" src="https://github.com/n8n-io/n8n/assets/21218213/faeedc62-7477-4f94-8327-61605f0530c1">

Logs: 
2023-08-30T18:19:14.083Z | error    | NodeApiError: Request failed with status code 400 "{ file: 'ErrorReporterProxy.js', function: 'report' }"
2023-08-30T18:19:14.084Z | error    | Error: Request failed with status code 400 "{ file: 'ErrorReporterProxy.js', function: 'report' }"

I tried different tokens from different accounts but it does't work.

**Comment by Joffcom** [comment]
Hey @YGolikov,

From what I can see it looks like Webflow have an issue with their v1 API at the moment which is what we use, Sending a request manually using curl and their own API docs page fails. It looks like a user has reported this on their forum here: https://discourse.webflow.com/t/api-returns-400-unknown-error-occurred/252766

Once their v2 API is out of beta we will probably look at changing the API version we use but for now it looks like we need to wait for Webflow.

**Comment by Joffcom** [comment]
Hey @trulala1235435,

I have had a chat with Webflow, Our node currently only supports the v1 API so you would need to make sure the token you are using is the Legacy option under the apps settings. Can you try with that token and let me know if that works for you?

**Comment by Joffcom** [comment]
I have created `NODE-761` as the internal ticket to update the API in the future.

**Comment by sympherjim** [comment]
do we have updates for this? was trying to do webflow integration and still throwing the same error Bad Request

**Comment by sympherjim** [comment]
> Hey @trulala1235435,
> 
> I have had a chat with Webflow, Our node currently only supports the v1 API so you would need to make sure the token you are using is the Legacy option under the apps settings. Can you try with that token and let me know if that works for you?

API V1 works okay

**Comment by mhddngs** [comment]
Cannot get webflow v1 or v2 working on self host. Running 1.37.3.

**Comment by janober** [comment]
Fix got released with [`n8n@1.54.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.54.0)

**Comment by JMPhotos** [comment]
Almost there, but the 'Return All' toggle on the 'Get Many' operation doesn't work. "No output data returned".  If I keep the toggle turned off, and specify a limit, the node works fine, but not if I want to explicitly return everything. Obvious workaround is to just keep the limit higher than the number of items I have, but still. 


 - Currently on N8N 1.59.2 (docker)
