### ISSUE TITLE
docker compose example requires first launch to have http basic auth disabled

### ISSUE THREAD

**Issue by leonstafford** [n8n-io/n8n#706]
Using the example `docker-compose.yml` example

**To Reproduce**

1. use `docker-compose.yml` example with `N8N_BASIC_AUTH_ACTIVE=true`
2. `docker-compose up -d`
3. Access site at https://sub.domain.com
4. See cert error

**Expected behavior**

Prompt for http basic auth creds and then see dashboard served properly over TLS

**Environment (please complete the following information):**

 - host OS: Ubuntu Linux 20.04 on Vultr VPS, disabled firewall
 - n8n Version latest on Docker Hub, which is `0.71.0` / `675aa76075cc`

**Workaround**

 - delete containers and n8n data
 - set `N8N_BASIC_AUTH_ACTIVE=false`
 - `docker-compose up -d`
 - `docker-compose stop`
 - set `N8N_BASIC_AUTH_ACTIVE=true`
 - `docker-compose up -d`

Above workaround results in expected site with valid TLS and basic auth in place. 

I believe the containerized [Discourse](https://github.com/discourse/discourse) does not suffer the same issue, so if this is confirmed, may be able to gleam some fixes from there.

**Comment by RicardoE105** [comment]
Hey, @leonstafford sorry for the late response. Have not had the change to review this, but will keep you updated. Thanks for putting that together.

**Comment by leonstafford** [comment]
No worries, @RicardoE105 - I'm about 3 weeks AWOL from my FOSS work, so going to be playing catchup for a while ;)

**Comment by ahsanv** [comment]
Thanks for reporting the issue @leonstafford and apologies for the late action here. Can you please give some more details about the certificate issue? I'm not able to reproduce it, works fine the first time. Maybe it has already resolved from the changes overtime?

**Comment by ivov** [comment]
@leonstafford Are you still facing this issue?

**Comment by Joffcom** [comment]
Hey @leonstafford,

Any updates on this one? We would love to get this one resolved if you are still seeing the issue.

**Comment by janober** [comment]
As we did not hear back for over 9 months and nobody ever else reported this issue will it now be closed (is over 2 years old anyway).
