### ISSUE TITLE
No request filtering in TheHive by case startDate

### ISSUE THREAD

**Issue by alexkolnik** [n8n-io/n8n#7070]
**Describe the bug**
TheHive module has the ability to select the Start Date parameter, but it is useless, as it looks for cases that must match second by second, that is, we do not specify the time range, but the exact time
And I saw that such a situation with other fields with dates

**To Reproduce**
The screenshot shows an example, if you select a week ago, it will not be cases for the last week, but one that was created exactly a week ago at the same time

![изображение](https://github.com/n8n-io/n8n/assets/99911272/907423d8-d777-467f-a1a3-368bb928e708)

**Expected behavior**
2 fields are expected, according to which the filter logic will be created From To

**Environment:**

* OS: Arch Linux
* n8n Version: 0.230.3
* Node.js Version: v16.20.0
* Database system: Postgres 11

**Additional context**
The library for Python - thehive4py allows you to create such a filter, for example the code that I used:
```py
from thehive4py.api import TheHiveApi
from thehive4py.query import *

def thehive_get_cases(thehive_token, date_from, date_to, ):
    thehive_api = TheHiveApi(THEHIVE_HOST, thehive_token)
    query = And(
        Between('startDate', date_from, date_to)
    )
    result = thehive_api.find_cases(query=query, sort=['startDate'], range='all')
    return result.json()
```

**Comment by Joffcom** [comment]
@michael-radency is this something that will be resolved in the overhaul?

**Comment by michael-radency** [comment]
> @michael-radency is this something that will be resolved in the overhaul?

yes, we do support `_between` filter in that overhaul, we also added `executeQuery` operation that allows to execute raw query in TheHive

**Comment by Joffcom** [comment]
Perfect, @alexkolnik any objections to closing this as it will be included in the next node version?

**Comment by alexkolnik** [comment]
No, thanks!
