### ISSUE TITLE
"Webhook Response" does not respect the given Response

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7077]
**Describe the bug**

I'm using IF conditionals to make sure HTTP requests are processed correctly. If they aren't, I want to submit a response in a specific format, as seen below.

![image](https://github.com/n8n-io/n8n/assets/8274669/6efce5af-1a00-42db-a1cd-d7fd969a85e0)

For some reason, when it errors out it won't respect that JSON response. Instead, it will simply pass its input forward.

![image](https://github.com/n8n-io/n8n/assets/8274669/02f805ae-8a19-4dc3-8fa9-f9c4f6f2f23e)

**To Reproduce**

1. Create a webhook listener and bunch of nodes
2. Set up a webhook response with a custom JSON response body
3. Test the workflow
4. See the error

**Expected behavior**

The webhook response should send the custom response instead of its input.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: 1.4.0
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Comment by Joffcom** [comment]
Hey @altechzilla 

Good spot it looks like the node was created to pass on the input rather than what the node is configured to return for the webhook.

I will get a ticket created for this but it will possibly be a breaking change so we will need to think about the best way to change this, it could be that we add an option to output the node message.

**Comment by altechzilla** [comment]
Hey @Joffcom , it actually already has an option to be set as None. Which I assume is the default for the node. But for some reason even if you do select JSON it won't respect it. Thank you for having a look into it!

**Comment by Joffcom** [comment]
Hey @altechzilla,

As far as I know that node doesn't have an option and it will always pass on the input items, Maybe I have missed something here though...

Just to check this issue is around the output of the node itself and not the actual response the webhook node returns right?

**Comment by altechzilla** [comment]
Hmm... You might be right—in the sense that I mistook the output for what the response was expected to be. Perhaps there could be a toggle that says "Set output to response" if the webhook response is set to JSON.

**Comment by Joffcom** [comment]
@altechzilla that is what I am thinking although the question then is... does that make this a bug or a feature request which isn't handled here?

**Comment by altechzilla** [comment]
Let's close this for now and I'll try it again later to make sure it's an actual bug - thank you!

**Comment by altechzilla** [comment]
Hey @Joffcom , not sure if this is related but here's what happens when trying to send a JSON:

https://share.abruptive.com/o0uKbJPn

https://share.abruptive.com/2NuWdpP6

Even thought he node was ran and the input is good, the response body is good, but the node errors out on the output side.

**Comment by altechzilla** [comment]
Just confirmed @Joffcom that the node does not respect the JSON response it's configured with, unless it's set to "First Node". If you set it to JSON, it will not follow through on execution:

1. Here's how it's set up in the editor (with validated JSON): https://share.abruptive.com/v1un57yr
2. Here's how it behaves on an actual run: https://share.abruptive.com/2NuWdOAn
3. Here's the webhook response in Postman: https://share.abruptive.com/v1un57mr

**Comment by Joffcom** [comment]
Hey @altechzilla,

I can see the problem now, We expect the JSON to still be a string and not a JSON object which is why it is failing. To fix this try...

```
{{ JSON.stringify({ your json }) }}
```
I have created `NODE-750` as the internal dev ticket to automatically stringify the data if it is an object.

**Comment by altechzilla** [comment]
Epic!

**Comment by janober** [comment]
Fix got released with [`n8n@1.9.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.9.0)

**Comment by Joffcom** [comment]
Hey @altechzilla,

Great news, This has been fixed and released :) for now I am going to mark this as closed. Let me know if you have any other questions on this issue.
