### ISSUE TITLE
JS Code needs a max stack boundary to prevent infinite loops

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7080]
**Describe the bug**

When writing custom JS code (I assume Python too), an infinite loop will cause a memory spike that crashes the entire instance. Not sure if it's happening on the hosted version, but definitely happening on the self-hosted one.

For example, a while that never completes will do that. It could be solved with a max stack depth, similar to how React prevents infinite loops. 

**To Reproduce**

1. Create a custom code node
2. Write a loop that never ends (i.e. while 1 == 1) - 
3. Execute the workflow
4. Instance crashes

**Expected behavior**

An error or timeout happens to prevent the instance from being overloaded

**Environment (please complete the following information):**

- OS: DigitalOcean Ubuntu (from Docker Droplet)
- n8n Version Latest (1.4.0)
- Node.js Version N/A
- Database system SQLite
- Operation mode: main

**Additional context**

**Comment by Joffcom** [comment]
Hey @altechzilla,

That sounds like a good idea, As this is not a bug and is more of a feature request did you want to open a proper feature request on our [community forum](https://community.n8n.io) for this?

**Comment by altechzilla** [comment]
Got it, thought it would be a bug because it **completely crashes the entire instance** - seems like a pretty critical thing. I'll see to opening a feature request then, thanks!

**Comment by altechzilla** [comment]
> Hey @altechzilla,
> 
> Normally I would agree but in this case we are running what the user gives us so this isn't an application level bug as such as we are allowing you to run your infinite loop.
> 
> You can also crash an instance with the execute command node if you input something crazy but as a user you are making that choice.

I see. Is that the case on the cloud hosted instance too? If not, what would be a good failsafe to put in place? For example if I had a team member build a workflow and they made a mistake how can we avoid them crashing the entire instance? Maybe there's a memory limiter thing we can put in place? I'd appreciate any resources if you have any.

A lot of those crashes have been accidental due to an infinite loop (or a super long request) which would then try to resume on restart, etc. so it's a bit dangerous. Any articles you can point me to on how to put together some sort of safe mode?
