### ISSUE TITLE
HTTP requests should have a default timeout to prevent memory leaks

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7081]
**Describe the bug**

When running a HTTP request that never ends, the workflow will only stop when it reaches its max execution time. Which by default it may not be preset in docker. There is a HTTP timeout option which I think should be enabled by default (i.e. 10 seconds, 30 seconds, etc.)

**To Reproduce**

1. Create a HTTP request node
2. Send a request that never returns
3. Crash and burn

**Expected behavior**

A timeout or boundary should prevent a potential memory leak.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: 1.4.0
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Additional context**

**Comment by Joffcom** [comment]
Hey @altechzilla,

I think we do actually have a default timeout which is set to one hour which seems like an odd option.

https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts#L1156

I will create a dev ticket to have that default changed to 5 minutes.

**Comment by Joffcom** [comment]
Internal tracking for this is `NODE-746`

**Comment by janober** [comment]
Fix got released with [`n8n@1.8.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.1)

**Comment by shriram-balakrishnan-coder** [comment]
Is it possible to override this "5 minutes" configuration via environment variable? 
Reason - This "5 minutes" could be long for some use cases.
