### ISSUE TITLE
The "Split in Batches" node cuts off access to variables before it

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7082]
**Describe the bug**
If you place a Split in Batches node and try to access a value BEFORE that node (or the node itself), it will throw an error that says the target node cannot be found. The variables do show up right in the parameters tab, but when you execute the node it will stop because of an error (as you can see on the right).

<img width="1416" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/8a946085-26b5-4fc1-942b-c860343e4c91">

<img width="754" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/54997e0b-64c3-48cd-8b39-e1d1c00eca65">

**To Reproduce**
1. Create a bunch of nodes
2. Place a Split in Batches node
3. Try to reference a variable before the Split in Batches node inside of the loop

**Expected behavior**
The Split in Batches node should not cut off access to nodes before itself.

**Environment (please complete the following information):**

OS: Ubuntu (Latest Docker Image - DigitalOcean)
n8n Version: 1.4.0
Node.js Version: (N/A - Docker Image - DigitalOcean)
Database system: SQLite
Operation mode: main

**Additional context**

**Comment by altechzilla** [comment]
Oddly enough, after deleting, saving, and recreating that entire logic branch it worked. Might be some sort of caching issue?

**Comment by Joffcom** [comment]
Hey @altechzilla,

I don't think we cache anything but it could be an issue with the workflow itself not having items in place so some nodes like the code node can cause the item indexing to be lost if you don't handle it in the node. For now though as your flow sounds like it is working I will mark this as closed, If you run into another workflow issue it is always worth posting on the support forum.

**Comment by altechzilla** [comment]
Thank you!
