### ISSUE TITLE
PostgreSQL field is required even if set to auto increment

### ISSUE THREAD

**Issue by oalexdoda** [n8n-io/n8n#7084]
**Describe the bug**
When using the PostgreSQL node to insert a row where you map fields, the ID field should often be empty (i.e. see Supabase) because it gets auto incremented. For some reason, n8n forces you to add the ID field as required. I believe it's some sort of pre-validation issue. Perhaps required fields shouldn't be validated until the query errors out post-execution.

<img width="451" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/6c50bd5e-0e42-4915-8d10-fd5d4928a79c">

**To Reproduce**

1. Add a PostgreSQL Insert Row node
2. Feed some data into it
3. Try to leave ID empty

**Expected behavior**
It should allow you to leave auto incremental keys empty so that the database generates them automatically.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: 1.4.0
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Additional context**

**Comment by atazangene** [comment]
I have the same issue...

**Comment by sptv2reg** [comment]
Possibly related: https://community.n8n.io/t/mysql-node-parameter-query-is-required-even-if-filled/30775/6
