### ISSUE TITLE
PostgreSQL does not support vector fields

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7085]
**Describe the bug**
The node doesn't allow you to set a variable to a vector embedding. Similar to @7084 there should be an option to disable pre-validation and let the query either complete or error out post-execution.

<img width="875" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/ba78efa3-2045-48e9-a710-af8fb9e5ee57">

**To Reproduce**

1. Insert a row with the PostgreSQL node
2. Set a vector embedding as the input
3. Run the workflow

**Expected behavior**
It should not error out for field types it doesn't recognize.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: 1.4.0
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Additional context**

**Comment by Joffcom** [comment]
Hey @altechzilla,

What is the datatype in your Postgres database? I know Supabase has support for the `pgvector` extension but as it is not part of Postgres we don't have support for it at the moment.

If the database is using the custom extension the best option would be to use the `Execute Query` option of the Postgres node which should allow you to continue working. If you did want suppor for something like `pgvector` it would be worth opening a feature request on the support forum.

**Comment by altechzilla** [comment]
Hey @Joffcom,

Got it! Yup, it's a `pgvector` based column. I was able to add it using the Supabase node, but not sure why it doesn't work with the PostgreSQL node. 

Perhaps there was a way to disable pre-validation as an opt-in toggle? That way the node would instantly support any data type and let the database itself return an error if needed.

**Comment by Joffcom** [comment]
Hey @altechzilla,

For that it would need to be a feature request but I can see why it would be useful although for the most part we would want to remain standards compliant with what we are working with but we do allow you to work aroudn this using the execute query option which would allow you to do whatever you want.

For now I am going to mark this as closed and if you want to add a feature request on the support forum we can see how the rest of the community feels about it.
