### ISSUE TITLE
Node continues on fail before retrying (i.e on HTTP)

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7098]
**Describe the bug**
If you enable the "Retry on Fail" option and set it on, and then enable "Continue on Fail", then it will ignore the Retry option entirely.

**To Reproduce**

1. Create a HTTP node
2. Set the Retry On Fail option on with a bunch of retries / delay
3. Set the Continue On Fail option on
4. Run a request that will fail (i.e. a GET to an invalid URL)

**Expected behavior**
The node should first go through the retries before it continues, or at least there should be a toggle that says "Finish retrying before continuing on fail." However, I think it should be the default setting. Otherwise, the "Retry on Fail" is useless when "Continue" is enabled.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: 1.4.0
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Comment by Joffcom** [comment]
Hey @altechzilla,

I believe this came up before but I can't remember what the outcome was, @maspio do you remember what the deal was with this?

**Comment by maspio** [comment]
Hey @altechzilla and @Joffcom,
"Continue on Fail" is implemented in the nodes themselves returning a json error object instead of throwing an error. "Retry on Fail" only reacts to real errors and is thus circumvented by "Continue on Fail". If we want to change that logic we would need to know when "Continue on Fail" actually returns an error, e.g. by looking for the error object inside the return data.

**Comment by altechzilla** [comment]
> Hey @altechzilla and @Joffcom, "Continue on Fail" is implemented in the nodes themselves returning a json error object instead of throwing an error. "Retry on Fail" only reacts to real errors and is thus circumvented by "Continue on Fail". If we want to change that logic we would need to know when "Continue on Fail" actually returns an error, e.g. by looking for the error object inside the return data.

What if the node would simply have a counter that keeps increasing every time it errors out? One use case would be when generating OpenAI embeddings or completions. Sometimes their server is unavailable so we'd want to retry a few times before throwing an error via the webhook response. I think the retry mechanism would be perfect.

**Comment by Joffcom** [comment]
Hey @altechzilla,

That could work but you might also be able to manually build that logic into your workflow, I would recommend a feature request for this one though as it is currently working as intended.
