### ISSUE TITLE
Questions: performance benchmark? Logs when errors? Adding new nodes?

### ISSUE THREAD

**Issue by rajaraodv** [n8n-io/n8n#71]
Excellent project, Thanks for building this! I'm familiar with tray,io and zapier and this looks like a great project to replace them. I'm interested in participating in this. I have a couple of questions:

1. Have you done any performance benchmark as to how many requests can it handle?
2. Where do you log things when things go wrong in production?
3. Where are docs to add new nodes?
4.  What are the main features you say are missing compared to tray.io?

**Comment by janober** [comment]
Thanks a lot! That is great to hear and would love to have you on-board!

To your questions:

  1. No, I did not. So can sadly not much say here. But even though it has some overhead to for example running a custom node.js script I tried to keep it to a minimum. Also does each workflow that runs get started in a separate thread so it should utilize the resources of a machine reasonable well

  2. That depends on the setting of the workflow. Either nothing gets done at all and every trace of it is lost forever or it saves the executing and all the data in "Past Executions" for people to check what is wrong. Additionally is it also possible to define an "Error Workflow" when something goes wrong where people can do more or less whatever they want like save it in some kind of Database, send EMail/Slack/SMS, ....

  3. In the product docs: https://docs.n8n.io/#/create-node

  4. Apart from like a million integrations, it would be everything data related. Like transformations/filtering/sorting/...

I hope that helps!

And if you have questions or problems in the future please post them here:
https://community.n8n.io

That people who have the same can find it in a single location. Thanks! Have a great weekend!

**Comment by janober** [comment]
I hope that did answer your questions. If not you can follow up anytime. Close the issue for now.
