### ISSUE TITLE
Docker image doesn't expose the default port

### ISSUE THREAD

**Issue by akizor** [n8n-io/n8n#710]
Hello,

**Describe the bug**
Some docker administration systems rely on docker port exposure for port mappings. Take the Plesk administration panel as example. It has built container management. However, because the images doesn't expose the default port, Plesk is unable to map a domain/subdomain to the container itself.

**To Reproduce**
1. Have a Plesk licence and the Docker extension installed and activated
2. Go to Docker from the left menu
3. Search `n8n` image from hub.docker.com and select the image to install. The image prompted is located [here](https://hub.docker.com/r/n8nio/n8n).
4. After installation, identify the image in list and hit run latest version
5. A configuration page is opened where you can add environmental variables, volume mappings and port mappings
6. Because the `EXPOSE` method is not present Dockerfile, you cannot map the port for NGINX to attach it for a domain

A similar workaround, but with no success so far can be found on the [community forum](https://community.n8n.io/t/how-can-i-install-n8n-with-plesk-obsidian-18/1257).
This bug is also present in [Plesk forums](https://plesk.uservoice.com/forums/184549-feature-suggestions/suggestions/38134906-allow-to-specify-custom-port-mapping-even-docker-i%C2%A0), but like the above, no viable solution so far.

**Expected behavior**
If the EXPOSE method is added to docker image from hub.docker.com, it should completely run without issues inside Plesk administration panels.

**Environment (please complete the following information):**
 - OS: CentOS 7.7.1908 via Plesk Obsidian 18.0.27
 - n8n Version: 0.71.0 (latest)
 - Node.js Version: 12.16.3

**Additional context**
I'm not sure this should be considered as bug (don't throw rocks pls) or feature request. I know the EXPOSE function is not mandatory as for highly customized docker environments this is not an issue.

Thank you

**Comment by janober** [comment]
I added EXPOSE to the docker files and did manually rebuild the latest version and pushed it: `n8nio/n8n:0.71.0`

Can you please give it a try if it now works fine for you. Thanks!

**Comment by akizor** [comment]
@janober You are truly a gentlemen. Works flawlessly. For sure, this will come in handy for future Plesk installs.

**Comment by janober** [comment]
Ah great to hear! Have fun!
