### ISSUE TITLE
The repository sends a "Workflow Failed" on every new issue

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7100]
**Describe the bug**
Every time I submit an issue here I get this email:

![image](https://github.com/n8n-io/n8n/assets/8274669/abcd6718-4317-4964-8811-465cf6bb75f9)

i.e. https://github.com/n8n-io/n8n/actions/runs/6074909416

[Check Issue Template](https://github.com/n8n-io/n8n/actions/runs/6074909416/job/16479976775#step:1:35)
Unable to resolve action `n8n-io/GH-actions-playground`, repository not found

**To Reproduce**

1. Submit an issue

**Expected behavior**
No error

**Environment (please complete the following information):**
N/A (GitHub.com)

**Comment by Joffcom** [comment]
@altechzilla looks like we renamed it, I have put in a PR to use the new name.

**Comment by janober** [comment]
Fix got released with [`n8n@1.6.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.6.0)
