### ISSUE TITLE
Workflows don't stop on Timeout

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7143]
**Describe the bug**
I have a workflow with a 5 minute timeout. After the 5 minute period expired, the workflow is still running and the Stop Execution button doesn't work:

![image](https://github.com/n8n-io/n8n/assets/8274669/12dbd9f8-ddfe-4123-b2b6-3d4e4ad0d1ac)

<img width="467" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/1c0535ca-43f4-4811-996b-63fc1304c843">

There's no way to stop it afaik unless the whole instance gets restarted.

**To Reproduce**

1. Set a workflow timeout
2. Run a workflow that has an unexpectedly long execution
3. See it in the executions history and/or try to stop it

**Expected behavior**
The workflow should timeout as per its settings AND it should be stoppable.

**Environment (please complete the following information):**

- OS: Ubuntu (Latest Docker Image - DigitalOcean)
- n8n Version: Latest Docker Image
- Node.js Version: (N/A - Docker Image - DigitalOcean)
- Database system: SQLite
- Operation mode: main

**Comment by altechzilla** [comment]
I believe this might've been an out of memory issue. The instance was still working (I could still navigate around) but that workflow would never stop. Couldn't see a spike in the server monitor but the workflow would just keep hanging. Yet another example where memory boundaries are a must-have. Wasn't a workflow issue - ran perfectly fine after restart.

**Comment by Joffcom** [comment]
Hey @altechzilla,

It could be that the workflow crashed for some reason, did the docker log show anything?

What is the workflow doing as well? Are you able to share a minimal workflow that reproduces this?

**Comment by altechzilla** [comment]
Hey @Joffcom , 

Hardly able to give a minimal repro because it's a massive workflow with 50 nodes, conditional branches that calls another sub-workflow with another 40 nodes, etc. It's a rabbit hole of like 4 chained workflows. 

Normally they all execute in like 10 seconds tops and the server memory doesn't seem to spike. There's probably like 250+ notes working together across all workflows.

Basically it's a webhook listener that takes an array of URLs and it manages all the AI training on Agent.so for those links.

I upgraded the RAM, set up a failed workflow event to ping me if anything like that happens again, and will keep an eye out - but it seemed super random. 

Let's close this for now and I can reopen it if it comes up again... at first I thought it was a bug with the timeout because the instance would still work (which never happened before when a memory leak happened).
