### ISSUE TITLE
1.6.1 "Connection Lost" & Broken Workflows

### ISSUE THREAD

**Issue by altechzilla** [n8n-io/n8n#7144]
An in-depth explanation was sent to the Discord server in this thread:

https://discord.com/channels/832547762716278804/1150588552141353071

**Comment by Joffcom** [comment]
Hey @altechzilla,

This error normally appears when the reverse proxy is not configured correctly although we have also seen other reports where this happens when Cloudflare is in use and I think we were going to implement a change to help with the Cloudflare issue.

With workflows not working we will need more information as I can't see a lot of information in the thread about it.

It may also be worth checking out our support forum which is a great place to get help from the team and other community members for issues that may not be a bug, we can also escalate bugs from there once confirmed.

**Comment by digitalextremist** [comment]
Not logged into `discord` at this terminal so I cannot see the details relevant to this issue, but I think I had the same problem recently.

You might check this, if you just upgraded between major versions recently: @altechzilla https://github.com/n8n-io/n8n/issues/6993

**Comment by altechzilla** [comment]
> Hey @altechzilla,
> 
> This error normally appears when the reverse proxy is not configured correctly although we have also seen other reports where this happens when Cloudflare is in use and I think we were going to implement a change to help with the Cloudflare issue.
> 
> With workflows not working we will need more information as I can't see a lot of information in the thread about it.
> 
> It may also be worth checking out our support forum which is a great place to get help from the team and other community members for issues that may not be a bug, we can also escalate bugs from there once confirmed.

@Joffcom 

_Yup! I started checking in with the AI bot which seems to be trained on the community forums, and try all solutions I can find / think of prior to bringing them up here. With the workflows not working, it's this part:_

"It also broke some workflows (2 that use the Postgres Trigger node) after we went from 1.6.1 back to 1.5.0. Which now can't be activated anymore. Basically both workflows have a Postgres trigger:"

<img width="520" alt="image" src="https://github.com/n8n-io/n8n/assets/8274669/1fe7ec27-19ed-4580-9520-d66dd1197cab">

Looks like the new version will change something in the way the workflows/trigger work so if you go back to the previous version they'd break.

**Comment by Joffcom** [comment]
Hey @altechzilla,

I did see that line in the thread but there was no actual information there could be used, The AI bot is only trained on topics marked as "Solution" and the docs so there is a lot of information on the forum that it is still unaware of.

I suspect the postgres triggers could be broken becuase of how they work although I am not aware of any changes to the postgre trigger between the 2 versions so it could be an issue with the channel still existing, Can you try setting the `Replace if Exists` option in the trigger and see if that gets it back up again?

**Comment by altechzilla** [comment]
This is most likely related to an authentication cookie that expires or to CloudFlare. I'll go ahead and close it for now as I was able to upgrade to 1.7.1 successfully.
