### ISSUE TITLE
New error with former working workflows: Problem in node ‘1‘ invalid type format

### ISSUE THREAD

**Issue by golere** [n8n-io/n8n#7149]
**Describe the bug**
Workflows that worked fine before, can't be executed any more and are giving an error. Workflows tested on 0.221.2 and work fine.

**To Reproduce**
Create a http node with the code below
run it

ERROR: invalid type format

cause:
{"status":"rejected","reason":{}}

Stack:
NodeApiError: invalid type format
    at Object.execute (/app/code/node_modules/n8n/node_modules/n8n-nodes-base/nodes/HttpRequest/V3/HttpRequestV3.node.ts:1437:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/app/code/node_modules/n8n-workflow/src/Workflow.ts:1284:8)
    at /app/code/node_modules/n8n-core/src/WorkflowExecute.ts:1018:29

**Expected behavior**
Worked fine until the last time I checked it.

**Environment (please complete the following information):**
- verion 1.6.1
- cloudron

**Additional context**

```
{
  "meta": {
    "instanceId": ""
  },
  "nodes": [
    {
      "parameters": {
        "url": "=https://api.carbone.io/render/{{ $json.data.renderId }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "carbone-version",
              "value": "4"
            }
          ]
        },
        "options": {
          "redirect": {
            "redirect": {
              "followRedirects": true
            }
          },
          "response": {
            "response": {
              "responseFormat": "file"
            }
          }
        }
      },
      "id": "",
      "name": "download report1",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [
        1620,
        2600
      ]
    }
  ],
  "connections": {}
}
´´´

**Comment by Joffcom** [comment]
Hey @golere,

Can you share a full workflow and the output data of the node before the http request? Looking at what you have shared so far there doesn't appear to be any issues that I can see so it could be that there are multiple items or the renderId is not being correctly converted to a string.

Did you also run through the migration guide?

**Comment by that-one-tom** [comment]
Documented steps to reproduce at NODE-790
