### ISSUE TITLE
Github errors after reporting a bug

### ISSUE THREAD

**Issue by ed-parsadanyan** [n8n-io/n8n#7168]
**Describe the bug**
After adding a new bug in the n8n repo (https://github.com/n8n-io/n8n/issues/7166)
I receive some sort of error via email.

**To Reproduce**

1. Create new n8n bug report
2. Get an error message in the email

**Expected behavior**
No error messages

**Environment (please complete the following information):**

- OS: NA, this is a GitHub related issue
- n8n Version NA, this is a GitHub related issue
- Node.js Version NA, this is a GitHub related issue
- Database system NA, this is a GitHub related issue
- Operation mode NA, this is a GitHub related issue

**Additional context**

Here's what I received 1 minute after creating a previous bug
![image](https://github.com/n8n-io/n8n/assets/10472129/30f3fa22-df7a-43be-bcae-72daeadcecc3)

**Comment by Joffcom** [comment]
Cheers for this @ed-parsadanyan i suspect something went wrong with checking the template, I might remove that check tomorrow.

**Comment by Joffcom** [comment]
Ah had a quick look on mobile, I thought this was fixed last week but it looks like it still can't find the action.

Will get this sorted.

**Comment by mcnaveen** [comment]
Hi @Joffcom 
I too get this often. Any luck on this?

**Comment by Joffcom** [comment]
@mcnaveen the PR is in, I am just trying to handle a couple of other things around it at the same time :)

**Comment by mcnaveen** [comment]
Thanks for the update @Joffcom Please take time.

**Comment by Joffcom** [comment]
Moving to closed for now as this should be resolved, if this is still an issue let me know and we can open it again.
