### ISSUE TITLE
Wait node within Execute Workflow child fails

### ISSUE THREAD

**Issue by dlerman2** [n8n-io/n8n#7189]
**Describe the bug**
When you call a child workflow via Execute Workflow and that child contains a Wait node, the parent fails with `(ERROR: Cannot read properties of undefined (reading 'stack'))`.

**To Reproduce**
* Create a workflow with an Execute Workflow Trigger and then a Wait Node set to wait for 2 minutes
* Create another workflow with an Manual Execution Trigger and then an Execute Workflow Node that points to the above
* Execute the second workflow.
* See that the Execute Workflow Node fails with the error message `(ERROR: Cannot read properties of undefined (reading 'stack'))`.

**Expected behavior**
Either the parent workflow should Wait until the child workflow completes, or the parent workflow should fail with a more meaningful error (eg 'Calling Execute Workflow with a workflow containing a Wait is not supported'.

**Environment (please complete the following information):**

- OS/node: Docker n8nio/n8n:latest
- n8n Version: 1.4.1
- Database system: Postgres
- Operation mode: main

**Comment by Joffcom** [comment]
Hey @dlerman2,

Thanks for the report, this is something that was raised a few days ago by another user as well.

We are tracking this internally as `N8N-6883`, at the moment other than waited on the main workflow instead there doesn't appear to be a workaround for this.

**Comment by janober** [comment]
Fix got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)

**Comment by dlerman2** [comment]
Thanks!
