### ISSUE TITLE
Expression editor issues

### ISSUE THREAD

**Issue by vco1** [n8n-io/n8n#719]
**Describe the bug**T
The expression editor behaves like a (Markdown) text editor, not a code editor.

For example, when I enter a dash at the beginning of a line, this gets immediately converted to an indented bullet.
If I type a character behind a variable {{....}}x the "x" shows up as part of the variable (i.e. it's colored/highlighted).

This makes editing expressions hard.

Workarounds available, not blocking.
 
Environment:
Firefox 77.0.1
N8N: 0.72.0 (dockerized)

**Comment by RicardoE105** [comment]
Hey @vco1 thanks for putting that together, just added this issue to our backlog. Will keep you updated.

**Comment by janober** [comment]
Got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.74.0
