### ISSUE TITLE
Not really a bug, just a typo that I've noticed

### ISSUE THREAD

**Issue by S1lander** [n8n-io/n8n#7191]
This is not really a bug, but I've noticed that in the Spotify Actions, there's a node called "Add an Item a Playlist" and I think it should be "Add an Item to a Playlist". I'm sorry if this is not the right place for this feedback, but I didn't know where else to put it.
Also: HUUGE THANKS for this tool, I can't believe how useful this thing is!
![image](https://github.com/n8n-io/n8n/assets/25884914/4677d2f4-6d4a-4621-bfd6-0eb5bae1bf22)

**Comment by Joffcom** [comment]
Cheers @S1lander I will get that fixed tomorrow

**Comment by Joffcom** [comment]
Hey @S1lander,

This change should be in the next release so I am going to close this one for now 👍🏻

**Comment by janober** [comment]
Fix got released with [`n8n@1.8.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.1)
