### ISSUE TITLE
Google Sheets Clear Operation with 'Keep First Row' Feature making large amount of API Requests exhausting quota

### ISSUE THREAD

**Issue by Panchin99** [n8n-io/n8n#7193]
**Describe the bug**
When using the clear google sheet node, google throws error saying too many requests

**Expected behavior**
I haven't looked very deep, but from initial debugging, in the google cloud platform error came from the below API endpoint
`google.apps.sheets.v4.SpreadsheetsService.ClearValues`

So mostly it is deleting executing the clear operation for every row causing too many requests, rather than using the batchClearValues to clear the values in one go.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 1.5.1

**Error**
`429 - {"error":{"code":429,"message":"Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:250464957044'.","status":"RESOURCE_EXHAUSTED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"quota_limit_value":"60","consumer":"projects/250464957044","quota_limit":"WriteRequestsPerMinutePerUser","quota_location":"global","service":"sheets.googleapis.com","quota_metric":"sheets.googleapis.com/write_requests"}},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quota#requesting_higher_quota"}]}]}} - Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute per user' of service 'sheets.googleapis.com' for consumer 'project_number:250464957044'.
`

**Comment by Panchin99** [comment]
The thing the puzzeled me after my first analysis, was why was my quota for "write" requests was getting exceeded if I am clearing the sheet. I got into the code and have a look at this section. (I had the "Keep First Row" toggle on)

```
 for (let i = 0; i < items.length; i++) {
		const clearType = this.getNodeParameter('clear', i) as string;
		const keepFirstRow = this.getNodeParameter('keepFirstRow', i, false) as boolean;
		let range = '';

		if (clearType === 'specificRows') {
			const startIndex = this.getNodeParameter('startIndex', i) as number;
			const rowsToDelete = this.getNodeParameter('rowsToDelete', i) as number;
			const endIndex = rowsToDelete === 1 ? startIndex : startIndex + rowsToDelete - 1;

			range = `${sheetName}!${startIndex}:${endIndex}`;
		}

		if (clearType === 'specificColumns') {
			const startIndex = this.getNodeParameter('startIndex', i) as string;
			const columnsToDelete = this.getNodeParameter('columnsToDelete', i) as number;
			const columnNumber = getColumnNumber(startIndex);
			const endIndex = columnsToDelete === 1 ? columnNumber : columnNumber + columnsToDelete - 1;

			range = `${sheetName}!${startIndex}:${getColumnName(endIndex)}`;
		}

		if (clearType === 'specificRange') {
			const rangeField = this.getNodeParameter('range', i) as string;
			const region = rangeField.includes('!') ? rangeField.split('!')[1] || '' : rangeField;

			range = `${sheetName}!${region}`;
		}

		if (clearType === 'wholeSheet') {
			range = sheetName;
		}

		if (keepFirstRow) {
			const firstRow = await sheet.getData(`${range}!1:1`, 'FORMATTED_VALUE');
			await sheet.clearData(range);
			await sheet.updateRows(range, firstRow as string[][], 'RAW', 1);
		} else {
			await sheet.clearData(range);
		}
	}

	return items;
}
```

At the end you can see that the code is updating the first row for every item, I have wrote a fix and created a pull request for this.

**Comment by Joffcom** [comment]
Hey @Panchin99,

Looks good, As you have created a PR I am going to close this issue and we can handle it from the PR.
