### ISSUE TITLE
Dropbox OAuth2 Credential setup requires https

### ISSUE THREAD

**Issue by leesilverman** [n8n-io/n8n#7207]
**Describe the bug**
In the credentials dialog for Dropbox, n8n presents an OAuth redirect URL that starts with http://.  However, Dropbox only accepts redirect URLs that start with https://.  

**To Reproduce**
1. Add New credential
2. Select Dropbox Oauth2 API
3. Enter client ID and secret from Dropbox app creation page
4. paste the URL from the credentials window into the "redirect URIs" box on the dropbox app creation page
5. Dropbox rejects it because it starts with http.  WORKAROUND: change the URL to https after pasting, assuming you have https set up.  Then Drobox will let you continue
6. Press "Connect my account" in credentials creation window.  A rejection window pops up
![image](https://github.com/n8n-io/n8n/assets/4869280/1a84afb3-e99b-4c1b-ab84-53ec8f93bec7)

**Expected behavior**
The Oauth URL needs to start with https.  I don't have any simple solutions for ensuring that n8n accepts https because there are lots of ways to do it.  I use a load balancer, so n8n itself is not aware that it's capable of https.  Simplest would be to just change the url and tell users to ensure that n8n is set up to accept https, but that's probably not ideal.

** Workaround**
After Dropbox pops up the error window, copy the URL and paste it into a new tab.  Change the redirect_uri parameter to https.  (Might have to change the port number too.)  Then submit and complete the connection.  

**Environment (please complete the following information):**

- OS: Docker on AWS ECS
- n8n Version [e.g. 1.6.1
- Node.js Version 18.something from most recent n8nio/base image
- Database system postgres
- Operation mode queue

**Additional context**

**Comment by Joffcom** [comment]
Hey @leesilverman,

I don't believe this is an n8n bug and it is probably better suited to our support forum. 

If your url is showing http still it would likely mean you have not set the `WEBHOOK_URL` environment variable.

Can you try setting that option and let me know how you get on? For now I am going to close this but if you still see an issue after setting it we can look into what would be causing it to fail.

**Comment by leesilverman** [comment]
That fixed the problem, thank you.  But it's really not obvious that the WEBHOOK_URL would affect the redirect URL for an OAuth credential.  The automations I use with dropbox don't have webhooks, they all run on a schedule, so it didn't even occur to me to look at that variable.   

While I was trying to figure this out I did change N8N_EDITOR_BASE_URL, but that didn't have any effect so I un-changed it.  Since setting up the credential happens in the editor, that seemed more intuitive.

Maybe an update to the docs is in order?  Or maybe replace WEBHOOK_URL with something like PUBLIC_URL which sounds like it has a broader scope than just webhooks?

**Comment by Joffcom** [comment]
Hey @leesilverman,

I will check what we have in the documentation, We have 2 options that can be set so a small tweak may be in order.
