### ISSUE TITLE
Webhook Trigger for Post Requests Breaks when able to receive binary data

### ISSUE THREAD

**Issue by shalalalaw** [n8n-io/n8n#7213]
**Describe the bug**
Webhook trigger receiving both JSON and binary data now shows the JSON params as binary data, and the JSON params themselves look empty.

**To Reproduce**

1. Webhook trigger expecting post request (binary data on)
2. Send request with both binary data and body params
3. View webhook node output (see binary contents and JSON contents)
4. **Note**: You might have to first do a binary post, then a JSON post and review the output of each

**Expected behavior**
Binary shows attached content, JSON/Schema view should hold params

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version 1.6.1
- Docker Compose installation

**Additional context**
Same exact flow worked prior to change.

**Comment by Joffcom** [comment]
Hey @shalalalaw,

Which version of n8n were you running previously? Can you also try not setting the `Binary Data` option, I have done a quick test and that seems to be working for me so could be a workaround for you.

**Comment by shalalalaw** [comment]
@Joffcom I'm not positive, I had tried to update about two weeks ago and ran into this issue, so I rolled it back. I can say pretty positively that it was no more than three versions back, and the flow is several months old (so it worked consistently across versions until now).

I was able to get that particular workaround in place, but I figured the bug report would be helpful anyways. Thanks.

**Comment by Joffcom** [comment]
I have created `NODE-807` as our internal ticket to look into this a bit more and either fix how it works or update the documentation.

**Comment by Joffcom** [comment]
Hey,

So it looks like this was resolved in https://github.com/n8n-io/n8n/pull/7804 which was released in `1.21.0` so we believe the original reported issue to be solved.

There was another issue that has been solved since then which resulted in filenames having `file0` so both issues here should be solved with an update.

I am going to mark this as closed and if the original issue is still a problem let me know and we can open this again.
