### ISSUE TITLE
Crypto node seems to be trimming the input string for very large strings

### ISSUE THREAD

**Issue by mzohair** [n8n-io/n8n#7214]
**Describe the bug**

Crypto node seems to be trimming the input string for very large strings (~15mb response received from http node)

**To Reproduce**

1. Place a Crypto node after an http node producing a large output (not binary)
2. Inside the Crypto node, use expression: `{{ JSON.stringify($json.body) }}` In my case I used SHA256 Base64 encoded

**Expected behavior**
Expected the hash to be different if the input is different, regardless of the input size. I got the same hash for inputs that were not identical.

**Environment (please complete the following information):**

- Standard deployment running in docker, running n8n 1.1.1

**Additional context**
Our workaround: changed the file to binary, then hashed the binary. this produced the expected hash (different hash for different inputs)

**Comment by Joffcom** [comment]
Hey @mzohair,

I have just tried to reproduce this but I have not been able to, For my test I have used a 24 and 17MB file and I get different results.

<img width="530" alt="image" src="https://github.com/n8n-io/n8n/assets/4688521/81ce2a48-f86b-45fe-86f5-1252a5fb33a2">

Are you able to share a workflow that reproduces the issue?

**Comment by mzohair** [comment]
Hi @Joffcom thanks for the prompt response.

I can't recreate it either with a simple workflow. I think the issue may have been related to json.stringify hitting some kind of limit, not the node itself.
