### ISSUE TITLE
OAuth2 client still add Authentication header when authentication mode is Body

### ISSUE THREAD

**Issue by d3rwan** [n8n-io/n8n#7218]
**Describe the bug**
A header `Authentication` is added in oauth2 call even if the selected authentication mode is Body, in addition of `client_secret` in the Body. 

**To Reproduce**
1. Create a new credentials extending `oAuth2Api` with authentication mode = body 

```
import type { ICredentialType, INodeProperties } from 'n8n-workflow';

export class MyOAuth2Api implements ICredentialType {
	name = 'myOAuth2Api';

	extends = ['oAuth2Api'];

	displayName = 'My OAuth2 API';

	properties: INodeProperties[] = [
                 {
			displayName: 'Grant Type',
			name: 'grantType',
			type: 'hidden',
			default: 'clientCredentials',
		},
		{
			displayName: 'Authorization URL',
			name: 'authUrl',
			type: 'hidden',
			default: 'https://target.url/oauth2/auth',
		},
		{
			displayName: 'Access Token URL',
			name: 'accessTokenUrl',
			type: 'hidden',
			default: 'https://target.url/oauth2/token',
		},
		{
			displayName: 'Scope',
			name: 'scope',
			type: 'hidden',
			default: '',
		},
		{
			displayName: 'Authentication',
			name: 'authentication',
			type: 'hidden',
			default: 'body',
		},
	];
}

```

2. Add a new instance of this credential in the UI
3. Use this credential in a workflow/node
4. The http request sent the target contains `client_secret` field in the body AND an Authorization header 
```
requestOptions:
  {
    url: "https://target.url/oauth2/token",
    method: "POST",
    body:
      {
        grant_type: "client_credentials",
        scope: "",
        client_id: "my-client-id",
        client_secret: "my-client-secret",
      },
    query: {},
    headers:
      {
        Accept: "application/json, application/x-www-form-urlencoded",
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: "Basic XXXXYYYYZZZZ",
      },
    ignoreSSLIssues: undefined,
  }

```

**Expected behavior**
Don't add Authorization header when mode = body, some provider don't manage both mode at the same time

**Environment (please complete the following information):**

- OS: [MacOS Ventura v13.5.2]
- n8n Version [e.g. 1.6.0]
- Node.js Version [e.g. 18.16.1]
- Database system [PostgreSQL]
- Operation mode [main]

**Additional context**

**Comment by Joffcom** [comment]
Hey @d3rwan,

I am not sure I am following on this one, If you are calling the token endpoint would you not expect it to authenticate with the existing refresh token?

Do you have an example service that this doesn't work with so we can do some testing, This is not an issue that we have seen with any of the services we support.

**Comment by d3rwan** [comment]
Hey @Joffcom, sorry if I am not clear. 

When using [client credential flow](https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/) to get access token, I can choose between `Header` and `Body` authentication. 

I think right now, with the current version of n8n, when I select `body` as `authentication`, n8n send both `client_secret` in the body but also the basic auth in authorization header.

And some OAuth2 provider, as [Hydra](https://github.com/ory/hydra), doesn't allow both basic and post implementation (cf. https://www.ory.sh/docs/hydra/debug/token-endpoint-auth-method), and currently a previously working workflow is not working anymore (cf. error thrown by hydra below)

> The OAuth 2.0 Client supports client authentication method "client_secret_post", but method "client_secret_basic" was requested. 

For the record, as I said before, my workflow worked with previous n8n (last one was 0.221.2), and I think a big refacto was done with 1.X version to add custom oauth2 client - so I guess there's a regression somewhere

**Comment by Joffcom** [comment]
Hey @d3rwan,

The new client should mostly be the same but I wouldn't be surprised if something had changed. I will add a note that Hydra can be used to test as well.

I have created `N8N-6970` as the internal ticket to investigate further.

**Comment by d3rwan** [comment]
Any news about that ?

**Comment by blaze182** [comment]
the refresh token method is still not respecting the authentication mode setting though and has header hardcoded

**Comment by Joffcom** [comment]
Can you open a post on the support forum and include what you are trying to connect to so we can test?

**Comment by blaze182** [comment]
Hi @Joffcom, appreciate your response

A bit late for me atm, will have a look at support forum later. Can drop some context here in case it's a know issue.

---

We have a B2B app that implements OAuth 2.0 api authentication using `authorization_code` grant type to retrieve the initial access_token, once it expires we expect a `refresh_token` request to rotate the access_token. We also expect `client_id` and `client_secret` in request body, as per one of the options in RFC6749.

One of our customers tries to set up an integration in n8n using standard OAuth provider. It is able to retrieve the initial access_token just fine using the Body authentication mode. However he is not able to find a way to refresh it after expiration. I can see the refresh method is implemented in n8n, but it pushes the Authorization basic header:

https://github.com/n8n-io/n8n/blob/2b9391a9758041f09c2e948eab942c45a9919aad/packages/%40n8n/client-oauth2/src/ClientOAuth2Token.ts#L77-L91

I guess it has to respect the authentication mode setting to be consistent with getToken method:

https://github.com/n8n-io/n8n/blob/bc6105436ebfba5b9691d52c13b8d1dc4fce3cf1/packages/%40n8n/client-oauth2/src/CredentialsFlow.ts#L41-L46

Thank you again
