### ISSUE TITLE
APITemplate.io node shows wrong PDF action description

### ISSUE THREAD

**Issue by tmrtn** [n8n-io/n8n#7224]
**Describe the bug**
The APITemplate.io node shows "Create an image" for the PDF action.

**To Reproduce**
Create a new APITemplate.io node and see the wrong PDF action description appear in actions.

https://github.com/n8n-io/n8n/blob/b0e98b59a6500b11f306403c563191749478c3fb/packages/nodes-base/nodes/ApiTemplateIo/ApiTemplateIo.node.ts#L72

https://github.com/n8n-io/n8n/blob/b0e98b59a6500b11f306403c563191749478c3fb/packages/nodes-base/nodes/ApiTemplateIo/ApiTemplateIo.node.ts#L77

**Expected behavior**
APITemplate.io node PDF action is labeled with "Create a PDF".

**Environment**

- n8n Version 1.7.1

**Comment by Joffcom** [comment]
Hey @tmrtn,

Thanks for the report, I have split out the resource to resolve this. The PR can be found above, once approved and merged it will be able in a future for release.

**Comment by Joffcom** [comment]
@tmrtn this has been merhed now, I am going to mark this as closed. Thanks again for reporting it.

**Comment by janober** [comment]
Fix got released with [`n8n@1.8.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.2)
