### ISSUE TITLE
How to change Oauth2 Api request accessToken method from “POST” to "GET"

### ISSUE THREAD

**Issue by ybom77** [n8n-io/n8n#7241]
**Describe the bug**
When I create a custom oauth2 api, the api documentation looks like this:

![image](https://github.com/n8n-io/n8n/assets/15134783/26285301-c7a0-4808-805c-aad262811888)

**Expected behavior**
1: How to modify the request method to “GET” or other
2:”code“ value can be used as query parameter

Is there some kind of setting to achieve the above modification?

**Comment by Joffcom** [comment]
Hey @ybom77,

Can you confirm what issue you are seeing when trying to set up the credential?

We don't use GitHub issues for general support or questions so your question may be better suited to the [support forum](https://community.n8n.io).

**Comment by ybom77** [comment]
Sorry, I'm closing this question now and resubmitting it
