### ISSUE TITLE
Twitter OAuth 1 not working

### ISSUE THREAD

**Issue by AlejandroAkbal** [n8n-io/n8n#7245]
**Describe the bug**
Cannot authenticate to Twitter OAuth 1

**To Reproduce**

1. Go to the “credentials” tab
2. Create a Twitter OAuth API credential
3. Fill details
4. Click Connect my account button
5. Authenticate in Twitter popup
6. See error, check screenshots in additional context

Error: Cannot read properties of undefined (reading 'id')

**Expected behavior**
I expect to have a working OAuth credential

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 1.7.1
- Node.js Version bundled in Docker image
- Database system SQLite bundled in Docker image
- Operation mode default (main)

**Additional context**
![image](https://github.com/n8n-io/n8n/assets/37181533/1ba877b5-9caf-4ea2-bfb3-d00577a3095d)

Twitter Developer screenshots:
![image](https://github.com/n8n-io/n8n/assets/37181533/36d39ca6-4b9d-442d-b957-208327e11c54)
![image](https://github.com/n8n-io/n8n/assets/37181533/a2463c54-4f26-496f-b730-39afd1b462d4)

**Comment by Joffcom** [comment]
Hey @AlejandroAkbal,

Thanks for reporting this one I also get the same issue with OAuth1, Have you tried with the newer OAuth 2 option which is the only one the new node version supports?

I have created `NODE-806` as the internal ticket to look into this.

**Comment by AlejandroAkbal** [comment]
Thanks for the quick reply @Joffcom  <3

Trying with OAuth 2 does seem to work!

I was trying with "Consumer Key", but OAuth 2 with "OAuth 2.0 Client ID and Client Secret" works perfectly

**Comment by AlejandroAkbal** [comment]
By the way, is there any way to upload media with API v2?

**Comment by Joffcom** [comment]
Hey @AlejandroAkbal,

It looks like we don't have support for that in the node so it would need to be done with an HTTP Request node.

**Comment by Joffcom** [comment]
Moving this to closed as OAuth 1 appears to be working but there are some Twitter hoops needed.
