### ISSUE TITLE
Postgres manual mapping requiring some automatic fields

### ISSUE THREAD

**Issue by ygorre** [n8n-io/n8n#7254]
**Describe the bug**
I have a PostgreSQL 13 database and I am trying to setup some automated inserts on it. However, the insertion UI is showing some optional fields as required and not allowing me to remove them.

**To Reproduce**

1. Create table on database using SQL instruction below.
2. Create step for insertion and select this test table

```
CREATE TABLE test (
	id int8 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	reqfield varchar(4) NOT NULL,
	nonreqfield varchar(6) NULL,
	autofield date NOT NULL DEFAULT (CURRENT_DATE + '30 days'::interval)
);
```

**Expected behavior**
- `id` field should be optional (thus possible to remove from mapped values) as it is an autogenerated primary key (https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/). 
- `autofield` should appear as optional, as it has a database-defined default value.

**Environment (please complete the following information):**

- n8n 1.7.1
- node.js v18.17.1
- Debian 11
- Using PostgreSQL internal database
- queue mode

**Additional context**
The ID field works fine when using the old SERIAL/BIGSERIAL column types.

**Comment by Joffcom** [comment]
Hey @ygorre 

Thanks for the report but I am going to make this as closed as it is the same issue as #7084

Let me know if you have any questions about this.
