### ISSUE TITLE
[BUG] Uninstalling Module or Updating Community Module Does Not Update Installed Packages

### ISSUE THREAD

**Issue by ZachHandley** [n8n-io/n8n#7255]
**Describe the bug**
It's hard to describe concisely because it's a hunch. Basically, I've been knee-deep developing a custom module for Appwrite the last 36 hours or so and I noticed something. I added a new feature to my module, I had Storage, Functions, and Documents, then I added Users. When I pushed that update, suddenly I had a `do you have a child in a fixedCollection` or whatever bullcrap. I knew it was bullcrap. So I uninstalled it, restarted my docker image, and then tried again. Same error.

Frustrated, but knowing what the error was, I renamed my node from `AppwriteZach` (as the name `Appwrite` was throwing this error before due to `n8n-nodes-appwrite` node I had previously installed) to `NAppwrite`, now, magically, everything is fine again. 

I propose that the error is wrong, and that I'm right, and the NPM cache or whatever it is to uninstall and install / update packages isn't being cleared and that this is, in fact, a bug.

**To Reproduce**
1. Install any community package (say `n8n-nodes-appwrite`)
2. Download n8n-starter-base node template
3. Name the node `Appwrite`
4. Uninstall `n8n-nodes-appwrite`
5. Install your node named `Appwrite`
6. Watch it give you an error and a hint that's unrelated to your problem

Or just take my word for it, I have dealt with this *constantly* the last few days.

**Expected behavior**
If I uninstall a package I expect no naming conflicts from uninstalled packages with my package, and I expect a better error to occur if there *is* a naming confliction. Additionally, when I push an updated package or if I update a community node, I shouldn't have to rename my node entirely to push a new feature and invalidate not only my credentials but also my nodes (despite existing functionality being the same, obvs)

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 1.7.1
- Node.js Version Unknown, downloaded through Coolify via N8N template
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode idk what this means

**Additional context**
For anyone else frustrated by the error
```
Error: Could not resolve parameter dependencies. Max iterations reached! Hint: If `displayOptions` are specified in any child parameter of a parent `collection` or `fixedCollection`, remove the `displayOptions` from the child parameter.
```
you are not alone! This is not, in fact, anything related to this sometimes.

Edit to add: After running a node defined by my previous package `appwriteZach` it errored with the new name (`NAppwrite`), saying 
<img width="336" alt="image" src="https://github.com/n8n-io/n8n/assets/16495679/1a8367c0-627e-4e0f-884f-7b4bf04d0d53">

Fixed after renaming the package from `n8n-nodes-appwriten8n` to `n8n-nodes-nappwrite`

lol

pls fix

**Comment by Joffcom** [comment]
Moving to closed, This should have been solved when we changed how we load packages. If this is still an issue let me know and we can open it again.
