### ISSUE TITLE
Pager Duty Node Typo in Urgency Field for "High"

### ISSUE THREAD

**Issue by nickmanente** [n8n-io/n8n#7266]
**Describe the bug**
In the Pager Duty node, under display "Urgency" dropdown, it says "Hight" instead of "High"

**To Reproduce**
Open the Pager Duty Node and view the options under display urgency

**Expected behavior**
For it to say "High"

**Environment (please complete the following information):**

AWS EKS
Version 1.6.1

**Additional context**
N/A

**Comment by Joffcom** [comment]
Hey @nickmanente,

Thanks for the report 🙌🏻, I have just popped in a PR that will fix this. Once reviewed and merged it will be available in a future release, for now I will mark this as closed as we have the fix in place.

**Comment by janober** [comment]
Fix got released with [`n8n@1.9.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.9.0)
