### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by pragyamishra56** [n8n-io/n8n#7324]
## Bug report

I would like to request an update to the Twitter icon on the website https://n8n.io/. The current Twitter icon needs to be changed to 'X'. This update is necessary to align the website's content with the desired branding or design changes.

### Contributor's Note: 
Please make sure to follow the contributing guidelines and have a clear understanding of the website's design and branding requirements before proceeding with this update.

### Steps to Reproduce:
As this is a request for a design update, there are no specific steps to reproduce a bug. However, the following general guidelines can be followed when making this change:

- Access the website: https://n8n.io/
- Identify the location of the Twitter icon that needs to be updated.
- Replace the current Twitter icon with the new 'X' icon according to the design guidelines.
- Ensure that the updated icon fits seamlessly into the website's design and is properly linked to the official Twitter profile, if applicable.
- Test the website to confirm that the new icon is displayed correctly and functions as expected.

### Expected Behavior:

After implementing the icon update, the Twitter icon on the website should be changed to 'X' in accordance with the design requirements.

### Additional Notes:

Please consider consulting with the website's maintainers or design team to ensure that the icon update aligns with the website's broader design and branding strategy.

### Issue
![Screenshot 2023-10-03 111437](https://github.com/n8n-io/n8n/assets/115208912/9cd4bd74-1458-4b0b-834c-53f7282b4689)

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.0.1]
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Comment by Joffcom** [comment]
Hey @pragyamishra56,

As this isn't related to the n8n application I am going to mark this as closed.

I will however let our marketing know that it is probably time to update the logos on the website.
