### ISSUE TITLE
POST request to upload media to wordpress results in Node.js stream rather than JSON response

### ISSUE THREAD

**Issue by BluePointDigital** [n8n-io/n8n#7337]
I recently updated from a fairly old version, but previously I was using a POST request to upload a binary file from stablediffusion to wordpress. I would get a confirmation from wordpress and everything worked fine.

After the update, I make a POST request and get back a huge Node.js data stream. I am not sure why this is happening. It's happening with multiple websites.

I am using the Docker Hub latest version.

Any suggestions?

**Comment by Joffcom** [comment]
Hey @BluePointDigital 

Can you share a workflow that reproduces this issue if you believe this to be a bug? 

I would also try adding a new http request node to your workflow and configuring it in the same way to see if that helps.

**Comment by BluePointDigital** [comment]
I actually did some digging and have discovered the reason. 

Apparently this commit:
https://github.com/n8n-io/n8n/commit/8a21fefbc67598452872e6944313d5e3fa6567c1#diff-333e63ab0faba33d7da152be653c651e40eb4f2ddacd39215690d8ace9782fd7

if the data type is set to RAW, it will automatically expect streaming and I don't see options to change that manually.
I also may just lack some fundamental knowledge about what is happening here.

The issue is that I can't figure out how to tell it to expect a JSON response.
Below is a sample workflow to replicate the issue:

`{
  "meta": {
    "instanceId": "75c01e1bddb9b8102125afca7bfe1390f59358641d6837f7b3be5aed2b6e67bb"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "03b36d02-6ace-459f-90f5-efc3e5583b7e",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        400,
        460
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "content-disposition",
              "value": "=attachment; filename=sample.{{$binary.data.fileExtension}}"
            }
          ]
        },
        "options": {}
      },
      "name": "Set Filename",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        940,
        460
      ],
      "id": "ea8018b9-0169-48d3-b51c-11c4a6b57b7c"
    },
    {
      "parameters": {
        "authentication": "genericCredentialType",
        "genericAuthType": "httpBasicAuth",
        "requestMethod": "POST",
        "url": "https://contentfoundry.ai/wp-json/wp/v2/media",
        "jsonParameters": true,
        "options": {
          "bodyContentType": "raw"
        },
        "sendBinaryData": true,
        "headerParametersJson": "={{ $json }}"
      },
      "name": "Upload To Wordpress",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 2,
      "position": [
        1120,
        460
      ],
      "id": "a9771d89-433c-4fc7-9d08-aaaadd9d29ed",
      "credentials": {
        "httpBasicAuth": {
          "id": "10",
          "name": "Content Foundry - ContentBot"
        }
      }
    },
    {
      "parameters": {
        "method": "POST",
        "url": "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Accept",
              "value": "image/png"
            },
            {
              "name": "Authorization",
              "value": "Bearer sk-cT8x7YzGdiOEnRdKbDdgM0VvsBIjyLL0HRrrPmKDLq8N9iym"
            }
          ]
        },
        "sendBody": true,
        "contentType": "raw",
        "rawContentType": "application/json",
        "body": "={\n  \"height\": 1024,\n  \"width\": 1024,\n  \"text_prompts\": [\n    {\n      \"text\": \"a man riding a bike down the side of the eiffel tower\",\n      \"weight\": 0.5\n    }\n  ],\n  \"cfg_scale\": 7,\n  \"clip_guidance_preset\": \"NONE\",\n  \"sampler\": \"DDIM\",\n  \"samples\": 1,\n  \"seed\": 0,\n  \"steps\": 50,\n  \"style_preset\": \"photographic\"\n}",
        "options": {}
      },
      "id": "0d8eaff0-4dea-470a-8c34-8fc7913381bc",
      "name": "Get Image from SD",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4,
      "position": [
        780,
        460
      ]
    },
    {
      "parameters": {
        "keepOnlySet": true,
        "values": {
          "string": [
            {
              "name": "content-type",
              "value": "image/png"
            },
            {
              "name": "accept",
              "value": "application/json"
            }
          ]
        },
        "options": {
          "dotNotation": false
        }
      },
      "name": "Set Headers",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        600,
        460
      ],
      "id": "27e53056-78c9-4c08-8374-f988372a9492"
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Set Headers",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set Filename": {
      "main": [
        [
          {
            "node": "Upload To Wordpress",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Get Image from SD": {
      "main": [
        [
          {
            "node": "Set Filename",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set Headers": {
      "main": [
        [
          {
            "node": "Get Image from SD",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Comment by BluePointDigital** [comment]
I apologize, I now understand.

I now understood your suggestion of a new node. It appears it changed since I last used it and it keeps the legacy one on the workflow. Thank you for the help!
