### ISSUE TITLE
Mattermost - user list is limited to n entries

### ISSUE THREAD

**Issue by itsmichaelk** [n8n-io/n8n#7344]
**Describe the bug**
When I want to add a reaction to a message sent, I can only access the first 48 users in the user's drop down list.
Even when I search for someone that is not listed within these 48 users, it doesn't give me the opportunity to find and select this user.

**To Reproduce**

1. Go to 'Action in App'
2. Choose 'Mattermost'
3. Choose 'Create a reaction'
4. Click in the drop down list of 'User Name or ID' and try to select a user with an alphabetical higher letter.

**Expected behavior**
I can see the user being retrieved and can select him.

**Environment (please complete the following information):**

- OS: Docker @ Ubuntu 22.04.3
- n8n Version: 1.7.1
- Database system: SQLite
- Operation mode: main

**Comment by itsmichaelk** [comment]
Upgraded to n8n Version 1.8.2, but still the same behaviour.

**Comment by Joffcom** [comment]
Hey @itsmichaelk,

Thanks for the report, It looks like on the loadOptions we use the single apiRequest function instead of the paginated call. I have created `NODE-869` as the internal dev ticket to get this resolved.

**Comment by itsmichaelk** [comment]
Hey Joffcom,

Is there any way to keep track of the 'NODE-869' issue? We'd really like to switch from our manual webhooks to n8n workflows, but we can't select the Mattermost channel we need because it's not listed.

**Comment by itsmichaelk** [comment]
Hello @Joffcom 
Is there any way we can keep track of this issue? This is affecting us a lot and we cannot switch to our n8n workflows due to this bug.

**Comment by Joffcom** [comment]
Hey @itsmichaelk,

We don't have a public page to check but I have just taken a look and this is currently in the backlog waiting to be picked up. I have some time set aside coming up to go through and fix some of the smaller issues like this so I will make sure I get this one covered.

**Comment by Joffcom** [comment]
Hey @itsmichaelk,

I have popped in a PR for this, Once reviewed it will be merged and available in a future release.
