### ISSUE TITLE
Missing "View" button for PDFs

### ISSUE THREAD

**Issue by marzn** [n8n-io/n8n#7361]
**Describe the bug**

The "View" button is missing for PDF binaries.

Screenshot shows the expected button:

![Screenshot n8n binary view](https://github.com/n8n-io/n8n/assets/13757952/63049b94-6523-4d3a-a49b-45337b6d0370)

**To Reproduce**

1. Get a PDF as binary (Read File Node, Http Node, ...)
2. Try to view it, only the "Download" button will be available

**Expected behavior**

The possibility to view PDF binaries directly without downloading them.

**Additional context**

First guess: The fileType for PDFs is missing in the Array in [`RunData.vue:1323`](https://github.com/n8n-io/n8n/blob/f4d8c9eed5c03b4056bf591ec5c6ab8809dc7ea0/packages/editor-ui/src/components/RunData.vue#L1323)

**Comment by Joffcom** [comment]
Hey @marzn,

Thanks for the report 🙌🏻 , We have put in a fix for this which will be merged and released once reviewed.
