### ISSUE TITLE
Node error on n8n-nodes-base (npm WARN ERESOLVE overriding peer dependency)

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#7364]
**Describe the bug**
When trying to install Node modules, an error over n8n-nodes-base is shown. The new Node modules are installed, but some community nodes stop working, like n8n-nodes-rss-feed-trigger.
Don't know if some other main modules are affected.

**To Reproduce**

1. Update to n8n v1.8.2.
2. Update docker compose file to install new Node modules.
3. Install community node "n8n-nodes-rss-feed-trigger"
4. Restart container/stack (requiered by n8n-nodes-rss-feed-trigger).
5. The error is shown in the logs.
6. The node "n8n-nodes-rss-feed-trigger" stops working.

**Expected behavior**
No error over n8n-nodes-base nor n8n-core.
The node "n8n-nodes-rss-feed-trigger" should work.

**Environment (please complete the following information):**
- OS: Ubuntu Linux 23.04 + docker + portainer
- n8n Version: 1.8.2
- Node.js Version: v18.17.1
- Database system:  postgres:11
- Operation mode ? [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
The new Node modules are:
- @mozilla/readability
- jsdom

The modules are installed as forced, because of this error.
Install directory:
```
/usr/local/lib/node_modules/n8n/
```

Added to docker compose file (portainer):
```
user: root
entrypoint: sh -c
command:
  - |
    cd /usr/local/lib/node_modules/n8n/
    npm install -f @mozilla/readability jsdom
    /docker-entrypoint.sh
```

NPM output:
```
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: n8n-core@1.8.1
npm WARN Found: n8n-nodes-base@1.8.2
npm WARN node_modules/n8n-nodes-base
npm WARN   n8n-nodes-base@"1.8.2" from the root project
 
npm WARN Could not resolve dependency:
npm WARN peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm WARN node_modules/n8n-core
npm WARN   n8n-core@"1.8.1" from the root project
 
npm WARN Conflicting peer dependency: n8n-nodes-base@1.8.1
npm WARN node_modules/n8n-nodes-base
npm WARN   peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm WARN   node_modules/n8n-core
npm WARN     n8n-core@"1.8.1" from the root project
added 30 packages, removed 1 package, and changed 2 packages in 38s
```

NPM full log:
[2023-10-06T10_17_05_205Z-debug-0.log](https://github.com/n8n-io/n8n/files/12830123/2023-10-06T10_17_05_205Z-debug-0.log)

**Comment by netroy** [comment]
Hey @pablorq can you please try installing the community package either 
1. via the UI, or 
2. via `npm install --prefix=/home/node/.n8n/nodes/ n8n-nodes-rss-feed-trigger`

Since v1.0.0, `/usr/local/lib/node_modules/n8n/` should not be tampered with anymore.

**Comment by Joffcom** [comment]
Hey @pablorq 

Are you sure the issue is related to the rss trigger node? If you remove the command you are using do you get the same issue?

It also looks like you are still using the root user which we stopped using from v1 and it should be the node user.

Can you try using an unmodified image and see if you have the same issue this will let us know if the issue is with the custom deployment, the node or n8n.

**Comment by pablorq** [comment]
> Hey @pablorq
> 
> Are you sure the issue is related to the rss trigger node? If you remove the command you are using do you get the same issue?
> 
> It also looks like you are still using the root user which we stopped using from v1 and it should be the node user.
> 
> Can you try using an unmodified image (use a default command) and see if you have the same issue this will let us know if the issue is with the custom deployment, the node or n8n.

Hi @Joffcom !

No. It's no related to the n8n-nodes-rss-feed-trigger node. This only get me aware that something was wrong.

I did a few more tests before arriving to the actual "solution", with a combination of path and user:

**Test 01**
path: /home/node/.n8n/nodes
user: root
result: Installed ok. The modules couldn't be used inside a Code node.

**Test 02**
path: /usr/local/lib/node_modules/n8n/
user: node
result: Can't install because bad user permission.

**Test 03**
path: /usr/local/lib/node_modules/n8n/
user: root
result: Installed ok. The modules can be used inside a Code node. It works!


(Now I see that I didn't test /home/node/.n8n/nodes + node user. Pending to test!)

**Comment by pablorq** [comment]
More test done:

**Test 04**
path: /home/node/.n8n/nodes
user: node
result: Installed ok. The modules couldn't be used inside a Code node.

**Test 05**
path: /home/node/.n8n/nodes
user: root
result: Installed ok. The modules couldn't be used inside a Code node.

## Code node:
Code to test if the custom Node.js modules are working:

```
// Import modules
var { Readability } = require('@mozilla/readability');
var { JSDOM } = require('jsdom');
```

## Error on Code Node
When the Code node is run, this is the error shown:

```
ERROR: Cannot find module '@mozilla/readability' [line 2]
VMError
Details
Stack

VMError: Cannot find module '@mozilla/readability'
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/resolver.js:126:9)
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/resolver.js:316:16)
    at LegacyResolver.resolveFull (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/resolver-compat.js:147:17)
    at LegacyResolver.resolve (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/resolver.js:121:15)
    at resolve (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/bridge.js:485:11)
    at requireImpl (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/usr/local/lib/node_modules/n8n/node_modules/@n8n/vm2/lib/setup-node-sandbox.js:171:10)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Code:2:23
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Code:32:2
```

## Summary
The only way to be able to use Node.js modules inside the Code node is:

```
path: /usr/local/lib/node_modules/n8n/
user: root
```

But this seems to break other things.

Any idea how to solve this?

**Comment by Joffcom** [comment]
Hey @pablorq I would recommend running n8n in a recommend way first (not using root) then moving forwards.

If you are installing an npm package a custom image is normally the easier way and there are some steps on the support forum on how to do it.

At the moment though this doesn't appear to be a bug with n8n itself.

**Comment by pablorq** [comment]
## Install without --force
Trying to install on path `/usr/local/lib/node_modules/n8n/` with user `root`, without the `--force` option:
```
npm install --prefix=/usr/local/lib/node_modules/n8n/ @mozilla/readability jsdom
```

The output is:
```
npm notice 
npm notice New major version of npm available! 9.5.1 -> 10.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.0>
npm notice Run `npm install -g npm@10.2.0` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
 
npm ERR! While resolving: n8n-core@1.8.1
npm ERR! Found: n8n-nodes-base@1.8.2
npm ERR! node_modules/n8n-nodes-base
npm ERR!   n8n-nodes-base@"1.8.2" from the root project
 
npm ERR! Could not resolve dependency:
npm ERR! peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm ERR! node_modules/n8n-core
npm ERR!   n8n-core@"1.8.1" from the root project
 
npm ERR! Conflicting peer dependency: n8n-nodes-base@1.8.1
npm ERR! node_modules/n8n-nodes-base
npm ERR!   peer n8n-nodes-base@"1.8.1" from n8n-core@1.8.1
npm ERR!   node_modules/n8n-core
npm ERR!     n8n-core@"1.8.1" from the root project
 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

Please notice the "npm ERR! **Fix the upstream dependency conflict**, or retry" warning.

**Comment by pablorq** [comment]
> Hey @pablorq I would recommend running n8n in a recommend way first (not using root) then moving forwards.
> 
> If you are installing an npm package a custom image is normally the easier way and there are some steps on the support forum on how to do it.
> 
> At the moment though this doesn't appear to be a bug with n8n itself.

Hi @Joffcom !

I've already checked it here for more info:
https://community.n8n.io/t/install-npm-package/3080/2
https://docs.n8n.io/hosting/installation/npm/#windows-troubleshooting
https://community.n8n.io/t/installing-additional-module-with-npm/11682/8
https://community.n8n.io/t/can-i-install-npm-packages/18434/2
https://community.n8n.io/t/can-i-install-npm-packages/18434/2
https://blog.elest.io/how-to-install-additional-libraries-for-n8n/
https://docs.n8n.io/integrations/community-nodes/installation/manual-install/

Is it another place to check about how to do it? I mean, to install a npm package/module.

About a custom image, I can't see any difference between create a custom image like:
```
FROM n8nio/n8n:latest
RUN npm install -g @mozilla/readability jsdom
```

And manually install the same packages over the n8n official docker image. For persistence, the `/home/node/.n8n` directory is mounted over a volume.

At the end, the files are there, but n8n can't use the newly installed modules on `/home/node/.n8n/nodes/` in the Code node.

This **IS** a n8n bug. Maybe on the Code node not able to use those packages?

**Comment by pablorq** [comment]
Maybe is a problem in the Code node not being able to use Node.js modules.

Lets focus on:
```
path: /home/node/.n8n/nodes
user: node
```

If I install the `n8n-nodes-rss-feed-trigger` community node, it is installed on this path: `/home/node/.n8n/nodes/node_modules`. And it work well inside a workflow, which means that it is installed ok.

The directory `/home/node/.n8n/nodes/node_modules` looks like:
```
~/.n8n/nodes/node_modules $ ls -hal
total 40K    
drwxr-sr-x    9 node     node        4.0K Oct  6 16:24 .
drwxr-sr-x    3 node     node        4.0K Oct  3 11:04 ..
-rw-r--r--    1 node     node        2.4K Oct  6 16:23 .package-lock.json
drwxr-sr-x    3 node     node        4.0K Oct  3 11:04 entities
drwxr-sr-x    7 node     node        4.0K Oct  3 11:04 moment
drwxr-sr-x    3 node     node        4.0K Oct  3 11:04 n8n-nodes-rss-feed-trigger
drwxr-sr-x    6 node     node        4.0K Oct  3 11:04 rss-parser
drwxr-sr-x    3 node     node        4.0K Oct  3 11:04 sax
drwxr-sr-x    3 node     node        4.0K Oct  3 11:04 xml2js
drwxr-sr-x    4 node     node        4.0K Oct  3 11:04 xmlbuilder
```

You can see the newly installed community node as a npm package, along with other packages. All of the other packages are also in the `/usr/local/lib/node_modules/n8n/` directory.

Using the Code node with the following:
```
var test = require('moment');
var test = require('n8n-nodes-rss-feed-trigger');
```

(The code is only to load the npm packages, it has no other practical use)

We get an error in the second line. The same error like before about `ERROR: Cannot find module ...`

The first line didn't thrown an error, but I think that's because the `moment` package is also in the `/usr/local/lib/node_modules/n8n/` directory. So the Code node loads the package from this directory an not from the `/home/node/.n8n/nodes/node_modules` directory. It doesn't loads this package nor any other package in this last directory, including the `moment` package.

Can it be a limitation or problem related to the Code node?

By the way, the environment variable for that is set: `NODE_FUNCTION_ALLOW_EXTERNAL=*`.

Any ideas?

**Comment by Joffcom** [comment]
Hey @pablorq 

Can you provide your full configuration / docker compose file so we can take a look.

In your example n8n-nodes-rss-feed-trigger is not a node module that you can require or at least I didn't create it in that way so I would for now ignore that and let's focus on your configuration and an npm package you are using so that we can test it internally to see what is going wrong.

**Comment by pablorq** [comment]
I seems that could be 2 different things, so I close this issue an open 1 per each case (#7380 and #7381).
