### ISSUE TITLE
Support for notification

### ISSUE THREAD

**Issue by stenalpjolly** [n8n-io/n8n#74]
Hi Team,

Is there any method to generate macOS native notification using this?

Thanks
Stenal

@thomasleveil @jmargeta @wernersmit @justb81 @mikementor

**Comment by MinuteCode** [comment]
Hi N8n team, In the same train of thought, what do you think about implementing [Pushbullet](https://www.pushbullet.com/) to N8n ? 
The [API](https://docs.pushbullet.com/#pushbullet-api) is well documented and this would bring mobile notifications to Android users.

Should I create a separate issue ?

**Comment by janober** [comment]
@stenalpjolly @MinuteCode Not much of a team yet just me but do my best anyway. Hope it will grow soon and that also more contributors join. The later at least seems to start slowly already.

Sorry, I do not know anything about how macOS notifications work but could be interesting for sure! New Integrations can be requested in the forum here:
https://community.n8n.io/c/feature-requests/nodes
Other people can see them and upvote the ones which are also interesting for them. So it would be best to post it there. I will then work on it according to the demand.

**Comment by MinuteCode** [comment]
Thanks for your reply @janober it's a really nice project you have there :)

I didn't see the forum section for requests, sorry about that. I willl post the node request there :)

**Comment by janober** [comment]
@MinuteCode Thanks a lot for both!

I want to create an issue template for days to mention it there. I hope it is up soon!

**Comment by janober** [comment]
Close this issue. Request can be found in forum here:
https://community.n8n.io/t/pushbullet-integration/194

btw. issue template is up for a few days.
