### ISSUE TITLE
ERROR: Expected a Runnable, function or object. [line 6] (Langchain Code node)

### ISSUE THREAD

**Issue by EgorZakharov97** [n8n-io/n8n#7414]
**Describe the bug**
Using the default example for 'execute' code in the langchain code block

**To Reproduce**

1. add code node, add main input/output parameters through UI, connect language model
2. connect input and output nodes
3. Execute node

**Environment (please complete the following information):**

- Docker (official container)
- n8n Version ai-beta

**Additional context**
I've just tried the example code provided in the langchain code block and it does not work. My suspicion is that the parameters supplied through connected node 'chat model' is not of the correct format that could be accepted by langchain

**Comment by EgorZakharov97** [comment]
For those who are facing the same Issue!
You have to set the input limit to 1 for Language Model and whatever else. Otherwise whatever you receive in the code node will be an array.

I've also tried
const llm = await this.getInputConnectionData('ai_languageModel', 0)[0];
and it wasn't working for me then the input is not set to -1 for some reason

Tell me if I'm missing something

('ai_languageModel', 0) - The 0 parameter is supposed to return the input by id 0, isn't it? I'm receiving an array

**Comment by janober** [comment]
Also important to mention that the second parameter is the item index, not the index of the the connection.

**Comment by EgorZakharov97** [comment]
Thanks so much!
