### ISSUE TITLE
Copying output data from executions log always copies pinned data

### ISSUE THREAD

**Issue by reikjarloekl** [n8n-io/n8n#7462]
**Describe the bug**
When opening a trigger node from the execution log and clicking the "Copy to clipboard" button on the JSON tab of the output data side, the data currently pinned for the node in the editor is copied to the clipboard instead of the data received during the execution and displayed on screen.

**To Reproduce**

1. Pin output data for the trigger node in the editor.
2. Execute the workflow with different trigger data.
3. Go the "Executions" log for the workflow.
4. Open the trigger node editor.
5. Go to the "JSON" tab, click the "Copy to clipboard" button.

**Expected behavior**
The trigger data from the execution currently displayed on screen should be copied to the clipboard. Instead, the output data currently pinned to the node in the editor is copied.

**Environment (please complete the following information):**

- Self hosted n8n, using docker
- n8n Version 1.9.3
- Node.js Version whatever comes in the docker
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @reikjarloekl,

That is a good spot, At first I could reproduce it but I realised I had it selected. The internal dev ticket for this is `NODE-872`.
