### ISSUE TITLE
Save Credential is successful, but it keeps loading

### ISSUE THREAD

**Issue by simontigers** [n8n-io/n8n#7473]
**Describe the bug**

**To Reproduce**

1. Go to 'credentials'
2. Click on 'AddCredential'
3. Click on 'input data and click save button'
![Snipaste_2023-10-20_16-49-48](https://github.com/n8n-io/n8n/assets/47096077/c37a1747-a6b4-47f2-80f6-2e3fd58eafe9)

- n8n Version [1.9.3]
- Database system [SQLite]
- Operation mode [main]

**Additional context**

**Comment by Joffcom** [comment]
Hey @simontigers,

I am not able to reproduce this using the steps provided can you share more on your configuration? Are you using a reverse proxy or something like Cloudflare? If you are does this issue exist if you bypass that and connect directly?
