### ISSUE TITLE
Todoist: Move task requires a section ID

### ISSUE THREAD

**Issue by cohan** [n8n-io/n8n#7478]
**Describe the bug**

When using a Todoist "Move a task" node, the section ID value is a required field in n8n, however this field is not required in the Todoist API. Leaving it blank gives a validation error: The value "" is not supported!

Unfortunately none of the tasks I want to move have a section to be moved into.

**To Reproduce**

Try to use the Todoist "Move a task" node in a workflow. Try to leave the section ID blank.

**Expected behavior**

I'd expect a blank field to be supported in this case - if the section ID is blank it doesn't need sending to the Todoist API. This would allow me to move a task into the base project rather than a section within it.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04.6 LTS (Docker Compose install)
- n8n Version 1.11.1
- Node.js Version v18.18.0
- Database system SQLite (Default)
- Operation mode main (Default)

**Additional context**

Todoist API doc: https://developer.todoist.com/sync/v9/#move-an-item

API call is in [packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts](https://github.com/n8n-io/n8n/blob/0b42d1aa71058fec3fea888415a503e2233b14cb/packages/nodes-base/nodes/Todoist/v2/OperationHandler.ts#L263)

Somewhat difficult to debug, looks like some of the Todoist nodes return "success: true" no matter what happens during the API call.

**Comment by Joffcom** [comment]
Hey @cohan,

Thanks for the report it looks like the Move operation could do with some love as there are 3 optional fields, I have created `NODE-874` as our internal ticket to update this.

**Comment by janober** [comment]
Fix got released with [`n8n@1.62.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.62.1)
