### ISSUE TITLE
Version 1.11.x - Could not get parameter "pollTimes"!"

### ISSUE THREAD

**Issue by pablorq** [n8n-io/n8n#7497]
**Describe the bug**
Some change on version 1.11.x gets the error `Could not get parameter "pollTimes"!"` on the community node n8n-nodes-rss-feed-trigger.
Everything works well up to version 1.10.1.

**To Reproduce**
1. Install n8n version 1.9.3.
2. Install the community node n8n-nodes-rss-feed-trigger.
3. Create a workflow using the trigger by RSS.
4. Update n8n to version 1.10.1.
5. It works.
6. Update n8n to version 1.11.x (1.11.0, 1.11.1, 1.11.2)
7. It fails.
8. The error can be show in the logs (docker + portainer)

**Expected behavior**
Update to latest n8n version without errors.

**Environment (please complete the following information):**
- OS: Ubuntu Linux 23.04
- n8n Version: 1.10.1
- Node.js Version: 18.18.0
- Database system: postgresql:11
- Operation mode ? [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
Reverting from v1.11.2 to v1.10.1 makes everything working again.

Error log:
```
Try to activate workflow "RSS 01" (OyDUydZ7i8DPCcp2)
WorkflowActivationError: There was a problem activating the workflow: "Could not get parameter "pollTimes"!"
Error: Could not get parameter "pollTimes"!
 -> Activation of workflow "RSS 01" (OyDUydZ7i8DPCcp2) did fail with error: "There was a problem activating the workflow: "Could not get parameter "pollTimes"!"" | retry in 2 seconds
Try to activate workflow "RSS 02" (ikCLxLlGsCGWEwdA)
WorkflowActivationError: There was a problem activating the workflow: "Could not get parameter "pollTimes"!"
Error: Could not get parameter "pollTimes"!
 -> Activation of workflow "RSS 02" (ikCLxLlGsCGWEwdA) did fail with error: "There was a problem activating the workflow: "Could not get parameter "pollTimes"!"" | retry in 2 seconds
```

**Comment by Joffcom** [comment]
Hey @pablorq,

I noticed the same issue this morning, For now I would stay on `1.10.1` the RSS Trigger node will be included from `1.13.0` so my community node will be marked as deprecated and this will likely not be an issue from then.

**Comment by pablorq** [comment]
Hi @Joffcom,

I don't know if this affect to something else, like another community node or another internal function.

Cheers!

**Comment by Joffcom** [comment]
Hey @pablorq,

There is a good chance this will impact any community node that does polling, We are working on fixing the issue anyway as it will no doubt annoy others making some community nodes.

**Comment by pablorq** [comment]
Ok!

You can close this issue if you want it, or leave it open for others, just in case.

I'll be waiting for the docker image of v1.13.0.
