### ISSUE TITLE
Loop Node Faulty

### ISSUE THREAD

**Issue by jpardoe86** [n8n-io/n8n#7546]
**Describe the bug**
The Loop node is exhibiting unusual behaviour.

It runs the loop once, and then when it receives new data to re-run with, it instead goes down the "Done" path without actually looping through the data.

**To Reproduce**
See below simple workflow:
`{
  "meta": {
    "instanceId": "0ee4df6913afa587809e4b8ad9c86ad691f8895b988194c29532314dcc84aaa4"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "6df82715-2da0-47ab-a8f3-53115ef2e415",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        720,
        360
      ]
    },
    {
      "parameters": {
        "options": {
          "reset": false
        }
      },
      "id": "ea17b1da-a6f8-4148-a6cd-f4664046f143",
      "name": "Loop Over Items",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 3,
      "position": [
        1120,
        360
      ]
    },
    {
      "parameters": {
        "unit": "seconds"
      },
      "id": "51c7b465-ff01-4f79-ba0e-8419637b91e2",
      "name": "Wait1",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        1340,
        540
      ],
      "webhookId": "25eff8cc-3bfb-4003-9aba-c5ae96890ef9"
    },
    {
      "parameters": {
        "unit": "seconds"
      },
      "id": "87333062-7a97-4229-925f-0db9b78d7918",
      "name": "Wait",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        1340,
        320
      ],
      "webhookId": "f9742ed9-799f-4bc4-ab7a-09d627604e9d"
    },
    {
      "parameters": {
        "jsCode": "return [\n  {item: 6},\n  {item: 7},\n  {item: 8},\n  {item: 9},\n  {item: 10}\n];"
      },
      "id": "c7c8833a-6903-4717-ba50-686e2727ed61",
      "name": "Create New Data",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        1560,
        320
      ]
    },
    {
      "parameters": {
        "jsCode": "return [\n  {item: 1},\n  {item: 2},\n  {item: 3},\n  {item: 4},\n  {item: 5}\n];"
      },
      "id": "48791a76-d0b0-4f47-b2c2-6058599180e3",
      "name": "Starting Data",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        900,
        360
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Starting Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Loop Over Items": {
      "main": [
        [
          {
            "node": "Wait",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Wait1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Wait1": {
      "main": [
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Wait": {
      "main": [
        [
          {
            "node": "Create New Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Create New Data": {
      "main": [
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Starting Data": {
      "main": [
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

**Expected behavior**
I expect it to loop through the new data it is supplied with, and only fire the Done path once that new data has been looped through.

**Environment (please complete the following information):**

- OS: n8n Cloud
- n8n Version: 1.14.2 (BETA) & 1.11.2

**Comment by janober** [comment]
That sounds like expected behavior. The first time the node receives data, it initializes with that data. All the other times the node runs, it ignores the incoming data and outputs instead the next batch, until it is empty.
If the data should be re-initialized, the "Reset" option has to be added and set to true.

You can also set it to an expression to reset automatically once the last batch got processed. An example can be found here:
https://community.n8n.io/t/split-in-batches-nested-loops-new-vs-old-nodes/25768/29?u=jan

**Comment by jpardoe86** [comment]
Hi Jan, 

I'm not sure if I've misunderstood your explanation or if you've misunderstood mine :) 

When the first batch of data is sent to the loop node, it then iterates through each item correctly until it is done. When the second batch of data is sent to the loop node, it doesn't iterate through. It goes straight to done, even though the second batch is new data that needs to be iterated through.

I've experimented by turning on the reset button, but then it seems to loop over the just first item in the first batch, to infinity.

I was assuming the loop node would work much like a for loop in code, where, if you run it with new data, it will run through the loop again with the new data. Is that an incorrect assumption?

Many thanks

**Comment by Joffcom** [comment]
Hey @jpardoe86,

It won't automatically use the new data to do that you would need to reset the data using an expression. In your example though even with the reset you are going from the done branch back into the loop so it will keep going unless you add some more logic to exit the loop, You can find a quick example of this below.

![image](https://github.com/n8n-io/n8n/assets/4688521/3b0d211e-8800-45cf-82bd-f500102fdf90)

As this node is currently working as expected I am going to mark this issue as closed and we either continue the discussion here or move it to the support forum.

```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "db7bcff0-86c9-4983-9b13-6235b4edd28b",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        260,
        420
      ]
    },
    {
      "parameters": {
        "options": {
          "reset": "={{ $node[\"Loop Over Items\"].context[\"done\"] }}"
        }
      },
      "id": "f4d80783-8502-49ed-a994-16d5c5100448",
      "name": "Loop Over Items",
      "type": "n8n-nodes-base.splitInBatches",
      "typeVersion": 3,
      "position": [
        660,
        420
      ]
    },
    {
      "parameters": {
        "unit": "seconds"
      },
      "id": "33afbdfd-d38b-480f-8002-38e3492c64ff",
      "name": "Wait1",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        880,
        600
      ],
      "webhookId": "25eff8cc-3bfb-4003-9aba-c5ae96890ef9"
    },
    {
      "parameters": {
        "unit": "seconds"
      },
      "id": "d1dff664-ba8c-46c6-8475-a2f142dc455e",
      "name": "Wait",
      "type": "n8n-nodes-base.wait",
      "typeVersion": 1,
      "position": [
        880,
        380
      ],
      "webhookId": "f9742ed9-799f-4bc4-ab7a-09d627604e9d"
    },
    {
      "parameters": {
        "jsCode": "return [\n  {item: 6},\n  {item: 7},\n  {item: 8},\n  {item: 9},\n  {item: 10}\n];"
      },
      "id": "ede17f1c-25e8-415e-98ed-632c5606fa35",
      "name": "Create New Data",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        1100,
        380
      ]
    },
    {
      "parameters": {
        "jsCode": "return [\n  {item: 1},\n  {item: 2},\n  {item: 3},\n  {item: 4},\n  {item: 5}\n];"
      },
      "id": "0e3cbd89-2d46-4a54-8853-eed790a31d0e",
      "name": "Starting Data",
      "type": "n8n-nodes-base.code",
      "typeVersion": 2,
      "position": [
        440,
        420
      ]
    },
    {
      "parameters": {
        "conditions": {
          "number": [
            {
              "value1": "={{ $runIndex }}",
              "operation": "largerEqual",
              "value2": 1
            }
          ]
        }
      },
      "id": "b8292ed3-a91e-4191-a808-69764a725249",
      "name": "IF",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1320,
        380
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Starting Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Loop Over Items": {
      "main": [
        [
          {
            "node": "Wait",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Wait1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Wait1": {
      "main": [
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Wait": {
      "main": [
        [
          {
            "node": "Create New Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Create New Data": {
      "main": [
        [
          {
            "node": "IF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Starting Data": {
      "main": [
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF": {
      "main": [
        null,
        [
          {
            "node": "Loop Over Items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

**Comment by jpardoe86** [comment]
Ah amazing, thank you. I didn't realise that you could turn the reset switch into an expression and add code to it. Also I had no idea I could reference context.

Can I suggest adding this information to the documentation to help people in future (and save you guys time)? https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches/?utm_source=n8n_app&utm_medium=node_settings_modal-credential_link&utm_campaign=n8n-nodes-base.splitInBatches

I see it has some clues at the bottom, but from a layman's perspective I didn't connect those to the ability to reset the loop, as at the top it talks about the boolean nature of "Reset" and doesn't give the impression you can do anything more.

Thanks again guys :)
