### ISSUE TITLE
Loop node - if empty data, second loop going to done branch instead of loop

### ISSUE THREAD

**Issue by Rafurus** [n8n-io/n8n#7595]
**Describe the bug**
I have a loop that on input data can have empty data (getKey node can output empty data), then it's checking if it has special data. If no, go to second loop, if got data it doing things. 
Right now I see that if the loop on input has empty data, loop after data are send on done branch instead of loop branch.
![image](https://github.com/n8n-io/n8n/assets/12428720/242ef5f1-1ea2-48c6-855c-44673c923c71)
Look on behavior:
first loop is ok:
![image](https://github.com/n8n-io/n8n/assets/12428720/24362f82-e4f4-4f43-a333-0b8a4b55790f)
second loop:
![image](https://github.com/n8n-io/n8n/assets/12428720/55d1b6d2-1448-4f1c-a23e-0ee9530a69f2)

I updated from 1.10 version.
First of I update batch node to loop node for check but it has no effect, same bug. 

**Expected behavior**
All loops should send data on loop branch and only on no data on input should go done.

**Environment (please complete the following information):**
- n8n Version 1.14.2

**Comment by Joffcom** [comment]
Hey @Rafurus,

Can you share a workflow that reproduces what you are seeing? You can use a code node to mock data to keep the workflow smaller.

**Comment by Joffcom** [comment]
Closing for now, If we can geta workflow that reproduces the issue we can open it and investigate further.
