### ISSUE TITLE
LDAP node doesn't find object when searching by objectGUID

### ISSUE THREAD

**Issue by kcyd** [n8n-io/n8n#7605]
**Describe the bug**
Searching in AD by ObjectGuid should return the respective object. However it returns nothing.

**To Reproduce**

1. Create a LDAP node
2. Search for "custom"
3. Custom filter: (objectGUID=<an existing objectGUID>), I tried with GUID string and also hex format
4. Execute the node

**Expected behavior**
The object should be found

**Environment (please complete the following information):**

- OS: docker image
- n8n Version 0.236.3
- Node.js Version 
- Database system postgresql
- Operation mode main

**Comment by Joffcom** [comment]
Hey @kcyd,

I don't have an AD environment to hand at the moment but does it work if you use (objectGUID=\AA\BB\CC) and split the hex pairs with a \?

**Comment by Joffcom** [comment]
Hey @kcyd, 

How did you get on with this?
