### ISSUE TITLE
Github Node, 404 on File > Edit if you specify a branch

### ISSUE THREAD

**Issue by JulienDelRio** [n8n-io/n8n#7614]
**Describe the bug**
If you want to Edit a file with Github Node and specify a Branch, the output is always an error 404 :

> 404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"} - Not Found

This bug doesn't appear on default branch.

**To Reproduce**

1. Create a workflow
2. Add a "Github Node"
3. Set an account
4. Set Resource to "File"
5. Set operation "Edit"
6. Set a repository owner and name
7. Set file path to an existing file
8. Set a File content
9. Set a commit message
10. **IMPORTANT : add an "additional Parameter" : branch**
11. Set the branch to an existing branch

**Expected behavior**
This node should not be in error and should commit the content.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version : 1.14.2
- Node.js Version : the one set in Docker image
- Database system : Postgres
- Operation mode : default

**Additional context**

This issue doesn't appear on default branch.

**Comment by Joffcom** [comment]
Hey @JulienDelRio,

For me this is working...
![image](https://github.com/n8n-io/n8n/assets/4688521/30c89534-867c-41ac-b960-47fd23c59b9f)


I did notice I get 2 different errors depending on what I am doing though, If the branch doesn't exist I get...

> ERROR: The resource you are requesting could not be found
404 - {"message":"Branch testing not found","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents"} - Branch testing not found

If a file doesn't exist I get...
> ERROR: The resource you are requesting could not be found
404 - {"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"} - Not Found

I also get the above if the branch and the file doesn't eixst. Are you sure the branch you are using and the file path exists?

**Comment by JulienDelRio** [comment]
Yes.

To be sure. I made a "Node Create Test", than I copy it.
I change the name to "Node Edit Test", change the operation to Edit, add "+1" in the content and connect the two nodes.
The message is back.

Can you try with my data ?

Here the workflow (you just have to change the data in node "Github Data":
`{
  "meta": {
    "instanceId": "854c212d3baca2d6108faeb1187a4f6d9a3e60117068e7e872ad5e663327af93"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "6d42fb87-7251-4091-aba1-8381f47c4811",
      "name": "Execute Workflow Trigger",
      "type": "n8n-nodes-base.executeWorkflowTrigger",
      "typeVersion": 1,
      "position": [
        1180,
        540
      ]
    },
    {
      "parameters": {
        "conditions": {
          "boolean": [
            {
              "value1": "={{ $json.id == undefined }}",
              "value2": true
            },
            {
              "value1": "={{ $json.link == undefined }}",
              "value2": true
            },
            {
              "value1": "={{ $json.canonical_url == undefined }}",
              "value2": true
            },
            {
              "value1": "={{ $json.new_content == undefined }}",
              "value2": true
            }
          ]
        },
        "combineOperation": "any"
      },
      "id": "68eaa787-f995-489a-b50e-43f16ce7adfc",
      "name": "Data are ok",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1540,
        540
      ]
    },
    {
      "parameters": {
        "errorMessage": "Data are not ok."
      },
      "id": "cf84e4b7-95b0-43ee-a933-82b4669446e6",
      "name": "Stop and Error",
      "type": "n8n-nodes-base.stopAndError",
      "typeVersion": 1,
      "position": [
        1760,
        460
      ]
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "repo.owner",
              "value": "ALPE-Plaisance-du-Touch"
            },
            {
              "name": "repo.name",
              "value": "Site-2022"
            },
            {
              "name": "repo.path",
              "value": "src/"
            },
            {
              "name": "branch",
              "value": "test-workflow"
            }
          ]
        },
        "options": {}
      },
      "id": "7ae33c9d-985b-4f86-aaa3-b122a55da36f",
      "name": "Github Data",
      "type": "n8n-nodes-base.set",
      "position": [
        1760,
        620
      ],
      "typeVersion": 1
    },
    {
      "parameters": {},
      "id": "62dc9239-070c-4e77-8fff-a8c25f20369b",
      "name": "File to version",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1360,
        540
      ]
    },
    {
      "parameters": {
        "resource": "file",
        "owner": {
          "__rl": true,
          "value": "={{$node[\"Github Data\"].json[\"repo\"][\"owner\"]}}",
          "mode": ""
        },
        "repository": {
          "__rl": true,
          "value": "={{$node[\"Github Data\"].json[\"repo\"][\"name\"]}}",
          "mode": ""
        },
        "filePath": "={{$node[\"Github Data\"].json[\"repo\"][\"path\"]}}{{ $node[\"File to version\"].json[\"type\"]}}/{{$node[\"File to version\"].json[\"id\"]}}.{{$node[\"File to version\"].json[\"format\"]}}",
        "fileContent": "={{$node[\"File to version\"].json[\"new_content\"] }}",
        "commitMessage": "=[Wordpre Backup] New file for {{$node[\"File to version\"].json[\"title\"] }}",
        "additionalParameters": {
          "branch": {
            "branch": "={{$node[\"Github Data\"].json[\"branch\"]}}"
          }
        }
      },
      "id": "ce4645b0-25c2-410c-a38a-6f86dab2ca9c",
      "name": "GitHub Create Test",
      "type": "n8n-nodes-base.github",
      "position": [
        1980,
        620
      ],
      "typeVersion": 1,
      "credentials": {
        "githubApi": {
          "id": "11",
          "name": "Github account"
        }
      }
    },
    {
      "parameters": {
        "resource": "file",
        "operation": "edit",
        "owner": {
          "__rl": true,
          "value": "={{$node[\"Github Data\"].json[\"repo\"][\"owner\"]}}",
          "mode": ""
        },
        "repository": {
          "__rl": true,
          "value": "={{$node[\"Github Data\"].json[\"repo\"][\"name\"]}}",
          "mode": ""
        },
        "filePath": "={{$node[\"Github Data\"].json[\"repo\"][\"path\"]}}{{ $node[\"File to version\"].json[\"type\"]}}/{{$node[\"File to version\"].json[\"id\"]}}.{{$node[\"File to version\"].json[\"format\"]}}",
        "fileContent": "={{$node[\"File to version\"].json[\"new_content\"] }} +1",
        "commitMessage": "=[Wordpre Backup] New file for {{$node[\"File to version\"].json[\"title\"] }}",
        "additionalParameters": {
          "branch": {
            "branch": "={{$node[\"Github Data\"].json[\"branch\"]}}"
          }
        }
      },
      "id": "6850fa89-5396-4221-89cb-9cd62d4ce8a2",
      "name": "GitHub Edit Test",
      "type": "n8n-nodes-base.github",
      "position": [
        2220,
        620
      ],
      "typeVersion": 1,
      "credentials": {
        "githubApi": {
          "id": "11",
          "name": "Github account"
        }
      }
    }
  ],
  "connections": {
    "Execute Workflow Trigger": {
      "main": [
        [
          {
            "node": "File to version",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Data are ok": {
      "main": [
        [
          {
            "node": "Stop and Error",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Github Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Github Data": {
      "main": [
        [
          {
            "node": "GitHub Create Test",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "File to version": {
      "main": [
        [
          {
            "node": "Data are ok",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "GitHub Create Test": {
      "main": [
        [
          {
            "node": "GitHub Edit Test",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}`

Here an example of data to pin in the trigger :
`[
  {
    "id": 3753,
    "link": "https://alpe-plaisance.org/liste-des-adhesions/",
    "canonical_url": "https://site2022.alpe-plaisance.org/?page_id=3750",
    "title": "Liste des adhésions",
    "new_content": "<p>a content</p>\n",
    "type": "page",
    "format": "html"
  }
]`

**Comment by Joffcom** [comment]
Hey @JulienDelRio,

That looks to fail, How odd. I have a theory on what the issue might be though so I will have a quick look later to see if I can get this solved.

**Comment by janober** [comment]
Fix got released with [`n8n@1.17.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.1)

**Comment by JulienDelRio** [comment]
Thank guys ! I will test when the branch will be on latest.
