### ISSUE TITLE
Check Issue Template workflow action does not exist anymore

### ISSUE THREAD

**Issue by almereyda** [n8n-io/n8n#7629]
**Describe the bug**

When creating a bug, we receive errors about a workflow run that failed.

**To Reproduce**

1. Create an issue
2. Receive notification emails about failed runs of the Check Issue Template workflow

**Expected behavior**

No errors are being sent to collaborators.

**Environment:**

GitHub

**Additional context**

The upstream workflow action does not exist anymore:

https://github.com/n8n-io/n8n/blob/78b84af8d1cfed005c7d9c715d832e8c91fd9e3f/.github/workflows/check-issue-template.yml#L13

https://github.com/n8n-io/validate-issue-template-content yields a 404

When checking the history of runs, this workflow apparently never worked:

https://github.com/n8n-io/n8n/actions/workflows/check-issue-template.yml

It would be more sustainable to disable this workflow and remove its triggers, eventually delete it, in order to save some wasted compute resources.

Else this would have to be repaired.

**Comment by Joffcom** [comment]
Hey @almereyda 

This has been previously reported in #7168 and will be fixed once the new issue template is introduced.
