### ISSUE TITLE
Form node password field should never store plain text by default

### ISSUE THREAD

**Issue by almereyda** [n8n-io/n8n#7631]
**Describe the bug**

The form node sends the contents of password fields in plain text over the wire.

**To Reproduce**

1. Create a form node with a password field
2. Activate test or production mode
3. Create a submission with content in the password field
4. Read the contents in plain text

**Expected behavior**

The content is only available in randomly salted and hashed form, in so it is not possible to derive the plain text of the secret value.

**Environment (please complete the following information):**

- n8n v1.15.1 Docker
- PostgreSQL

**Additional context**

Commonly used implementations for salted password hashes are, in declining order:

1. Argon2ID
2. Argon2
3. bcrypt

Plain text values should only be possible with a manual override, confirming the implications this may have.

**Comment by Joffcom** [comment]
Hey @almereyda,

Typically a front end form wouldn't hash a password and the backend would handle that, in this case the form is the front end and once posted to n8n you can use the crypto node to hash the value.

The password masked field could be used for values that don't need to be hashed but should be masked when the user is inputted it like an api key.

Generally you are correct a password should always be hashed when being stored but we don't know if the field will be a password so I don't believe there is a bug or anything to fix here.

Let me know if you have any further feedback on this one, for now I am going to mark this as closed.

**Comment by almereyda** [comment]
Thank you for detailing out how to derieve a crypted password hash from the field.

Indeed the masked node doesn't make any assumptions what data it will carry. Maybe I got carried away, because it is called Password.

Actually it felt a little uncanny, that the string was immediately and plainly visible in the N8N UI, during testing and within the execution records. Maybe a masked form field's data should also only be displayed masked, and be revealed optionally?

Again, maybe this won't fix, but from a privacy protection point of view it could make sense not to unneccessarily reveal secrets, when their intended use is to be passed along in a workflow, and not primarily to be looked at.

This in itself is merely a side-effect of n8n plainly visualising involved steps in data processing, much as a literate programming environment, which in other implementations usually remains invisible.

**Comment by Joffcom** [comment]
Hey @almereyda,

It could be possible that in the future we add an option that masks certain fields but currently I wouldn't put this down as a bug it would be more of a future feature request.

I could see something like that as  being useful for other fields like headers or url parameters being sent in an http request node if manually implementing an authentication flow or if dealing which some other kind of personal data from a crm that you wouldn't logged.

**Comment by almereyda** [comment]
Thank you for your thoughtful response.
