### ISSUE TITLE
ERROR: URIError: URI malformed

### ISSUE THREAD

**Issue by maxmarines** [n8n-io/n8n#764]
**Describe the bug**
When sending an HTML letter template using the AWS SES node, an error occurs (URIError: URI malformed ); when sending via the Send Email node, no error is observed.

**To Reproduce**
1. Go to AWS SES node
2. Click on 'Is Body HTML:'
3. Paste code to body from https://github.com/konsav/email-templates/blob/master/explorational.html or https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html
4. See error ERROR: URIError: URI malformed (ERROR: URIError: URI malformed
Error: URIError: URI malformed
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsSes.node.js:265:27)

**Expected behavior**
Sending this HTML code in the form of a letter to the specified address.

**Environment (please complete the following information):**
 - OS: Ubuntu 19.03.8
 - n8n Version last version from docker hub image (0.74.0)
 - Node.js Version last version from docker hub image

**Additional context**
Cyrillic letters can also be used in the letter. ( а, б, в, г, д, е, ё, ж, з, и, й, к, л, м, н, о, п, р, с, т, у, ф, х, ц, ч, ш, щ, ъ, ы, ь, э, ю, я)

**Comment by RicardoE105** [comment]
Hey @maxmarines, thanks for putting that together. Seems like the issue is the CSS. If I remove the CSS works just fine. Of course the email it's not formatted now. I wonder if AWS has a restriction/method to add CSS into an email.

**Comment by maxmarines** [comment]
Having studied the problem in more detail, a solution was found. I need to edit the HTML code. The problem is precisely in Amazon SES, and not in n8n. The question can be considered solved, thanks.

**Comment by maxmarines** [comment]
But I still think you can solve this problem. If you manually recode to avoid the characters " or % , then everything works, including the CSS.
Used the tool https://www.url-encode-decode.com/

But the letter must be very small in this case, otherwise another error occurs

"ERROR: Error: AWS error response [414]: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n</body>\r\n</html>\r\n""

**Comment by maxmarines** [comment]
Found one working solution.
It is necessary to add the ability to change the headers in the letter using the Send Email node) Unfortunately, there is no such option at the moment, we could not consider the introduction of this option

**Comment by RicardoE105** [comment]
@maxmarines will this headers solve the issue? or is this a feature request?

**Comment by maxmarines** [comment]
@RicardoE105 adding custom headers for letters will solve the problem, since this will allow you to specify the "X-SES-CONFIGURATION-SET" header, which will allow you to use the service with full functionality without using the Amazon API, besides, send any letters with attachments / styles using the SMTP without any restrictions.
Plus, custom headers are an important email option for other services. For example, it is in the header that the "List-Unsubscribe" option is set, which is very important for delivery to the inbox.

**Comment by RicardoE105** [comment]
ok, I'm kinda lost. What do you mean without using the Amazon API? is not it this an addition to the AWS SES node?

**Comment by maxmarines** [comment]
@RicardoE105 I want to use a generic SendEmail ( via smtp) node. But with the **new option to add custom headers.**
In this case, there will be no need to use an Amazon Ses node that cannot send messages normally..

Using a Send Email node with custom headers, there is no need for a restricted AWS SES node.

**Comment by RicardoE105** [comment]
ah got it. ok, int hat case this is just for bugs. Can you please go to the community https://community.n8n.io/ and create a feature request. We can keep you posted on the progress that way.

**Comment by maxmarines** [comment]
@RicardoE105 the request has been created, thanks for your attention.
https://community.n8n.io/t/need-option-to-add-custom-headers-to-emails-using-the-send-mail-node/1804
