### ISSUE TITLE
Node Date & Time does not pass all fields to output

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#7646]
**Describe the bug**

Node Date & Time does not pass all fields forward

![c932a0fb-f519-406a-a6e0-715653cfd3ef](https://github.com/n8n-io/n8n/assets/257004/862a1d76-59ac-4f7c-9e76-22ddee102ed1)

**To Reproduce**

1. Add a Date & Time Node
2. Perform any operation
3. See that only the result of the operation is sent to the output

**Expected behavior**

**Environment (please complete the following information):**

- OS: Docker
- n8n Version 1.15.2 Beta
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof 

I take it you are expecting the node to output the input items as well like we do in some other nodes but moved away from in the newer version of this one?

**Comment by luizeof** [comment]
Hi Jon, yes . Has this changed?

**Comment by Joffcom** [comment]
Hey @luizeof 

Yeah I think we changed this in the node overhaul back in `0.228.0` but I will double check this against the overhaul plan in the morning.

**Comment by luizeof** [comment]
But @Joffcom , I could be wrong and please correct me if I am, but doesn't it remove the usefulness of the node being able to format and calculate date values together with a dataset before sending it to an integration for example?

It only returns the formatted or calculated value, it doesn't give me many options.

**Comment by luizeof** [comment]
In the example I used in the image, if I wanted to calculate a person's age, it would just add the age field to the data in the input. In this case, I would have to create an Edit Fields (SET) node and regroup the information.

I believe that an option to include all input fields in the output would be a good option.

**Comment by janober** [comment]
Fix got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)

**Comment by Joffcom** [comment]
Hey @luizeof,

As you might have noticed... We have added this an option and it should be all good from `1.17.0`. I am going to get this one marked as closed for now, Let me know if you have any other questions about it.

**Comment by luizeof** [comment]
@Joffcom Thank you very much for your help and promptness in resolving these small adjustments. N8N grows a lot because of collaborators like you... thank you very much indeed.

PS: I'm recording the video for this version right now ;)
