### ISSUE TITLE
HTTP Request Option "Pagination" not showing

### ISSUE THREAD

**Issue by nzidol** [n8n-io/n8n#7647]
**Describe the bug**
HTTP Request Option "Pagination" not showing

**To Reproduce**

1. Create new workflow
2. Add HTTP request note
3. Click on add option
4. 
![image](https://github.com/n8n-io/n8n/assets/13618973/0efa6db4-ae30-4726-a162-58dba5b2a9d8)

**Expected behavior**
Able to add pagination to request....

**Environment (please complete the following information):**

- OS: Windows 11 with Docker 4.20.1
- n8n Version 1.14.2
- Node.js Version [e.g. 18.16.0]
- Database system SQLite
- Operation mode Main

**Additional context**

**Comment by Joffcom** [comment]
Hey @nzidol 

The pagination feature was [introduced](https://docs.n8n.io/release-notes/#n8n1151) in `1.15.1`, to access it you will need to upgrade.

I am going to mark this as closed but if you still can't see it after upgrading let me know and we can open this again.
