### ISSUE TITLE
HTTP Node in pagnitation mode does not set an auth header

### ISSUE THREAD

**Issue by Dunwyn** [n8n-io/n8n#7653]
**Describe the bug**
Stored OAuth Credentials (maybe all credential types) are not sent in pagnitation mode.
If you manually generate a valid token and set it in header parameter of the node, everything works.

**To Reproduce**

1. Add HTTP Request node
2. Add Generic OAuth2 credentials
3. Enable  Pagnitation Mode
4. Get 403 Error 

**Expected behavior**
Authorization header is also sent during pagination mode.

**Environment:**

- OS: docker
- n8n Version 1.15.2
- Database system postgres
- Operation mode default

**Additional context**

**Comment by Joffcom** [comment]
Hey @Dunwyn,

I have just given this a go using the GitHub API and the generic oauth2 and and I am not able to reproduce this, It also appeared to be fine using standard header auth calls for generic and predefined credentials.

Can you share which service you are tyring to use if it is public so I can test that?

**Comment by Dunwyn** [comment]
Hey @Joffcom 

I have the problem with all oAuth credentials (for example at raindrop.io). If you send the HTTP request to requestbin.com, you can also see that an authorazation header is sent for "pagnitation off", but it is completely missing for "Parameter/Next Link".

**Comment by Joffcom** [comment]
Hey @Joffcom,

I will test that in the morning and to requestbin to see if I get the same issue there.

**Comment by Joffcom** [comment]
Hey @Dunwyn,

I have managed to reproduce this, It looks like the GitHub endpoint didn't rate limit me or need authentication which is why that worked.

So it looks like this is an issue for any generic oauth2 credential using other generic types seem to be ok (header / basic), I have created `NODE-916` to get this fixed.

**Comment by tymaks** [comment]
I faced this problem with Bearer Auth. Without pagination it works, but when the pagination is ON I received 401. Version 1.97.1
