### ISSUE TITLE
ERROR: self signed certificate

### ISSUE THREAD

**Issue by mihha** [n8n-io/n8n#769]
**Describe the bug**
I have the following setup:

- server with Virtualmin which hosts PHP applications through the Apache web server
- n8n instance installed with npm
- virtual website which allows me to access n8n using subdomian
- SSL certificate provided by Virtualmin for the n8n subdomain

When I start n8n normally with “n8n start”, I can access n8n dashboard without any issues using my subdomain with HTTPS

https://n8n.domain

In this case, if I try to execute “IMAP Email” node, I get the following error
![image](https://user-images.githubusercontent.com/3791124/87808786-9fb0d700-c85a-11ea-8b83-3a5290926441.png)

**To Reproduce**
You would have to create a virtual domain and use it as a proxy for n8n application

**Expected behavior**
I would expect to be able to use IMAP mail module without having to lower the security

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 18.04
 - n8n 0.74.0
 - Node.js Version 14.5

Already discussed in the community forum
https://community.n8n.io/t/error-self-signed-certificate/1792

**Comment by janober** [comment]
As explained in the forum are we currently not able to debug and fix this issue ourselves.

**Comment by janober** [comment]
Copy over message from Igor which he did post in the forum and close issue:
```
BTW, @jan, I was able to work this out

Now, I have the following setup which is working correctly with signed certificate from LetsEncrypt

subdomain and website created using Virtualmin
subdomain is using HTTPS
n8n instance installed with npm
SSL certificate provided by Virtualmin (from LetsEncrypt) which is working on the subdomain
I had to create the following combination of environment variables

export N8N_PROTOCOL=https
export VUE_APP_URL_BASE_API=“https://n8n.domain/”
export N8N_BASIC_AUTH_ACTIVE=true
export N8N_BASIC_AUTH_USER=myhiddenuser
export N8N_BASIC_AUTH_PASSWORD=myhiddenpassword
export WEBHOOK_TUNNEL_URL=“https://n8n.domain/”

My error in initial attempt was a combination of two things:

using variable N8N_HOST=n8n.domain. Since the host is actually localhost in this case and Apache is serving a content from localhost when you access this subdomain from the internet, N8N_HOST variable shouldn’t be set

I am using pm2 process manager for node. I wasn’t aware that when you create a process using that manager, stop the process, change some variables and then start the process again, pm2 actually saves the variables, instead of using new values. You have to delete a process and then create it with new variables active in order to change them for the process

Anyway, I have a fully working n8n application, which is using LetsEncrypt certificate, is accessible from the internet without a tunnel and is sitting behind a proxy

Regards,
Igor
```
