### ISSUE TITLE
ERROR: Cannot read properties of undefined (reading 'getNodeParameter') when trigger by webhook

### ISSUE THREAD

**Issue by siduko** [n8n-io/n8n#7690]
**Describe the bug**
When I setup a webhook for slack bot, but when I execute, it throws the error ERROR: Cannot read properties of undefined (reading 'getNodeParameter')

**To Reproduce**

<img width="1386" alt="Screenshot 2023-11-11 at 21 13 24" src="https://github.com/n8n-io/n8n/assets/3646024/8c319c77-0d43-4c78-bbcc-7312076b2a22">

**Expected behavior**

The webhook can execute

**Environment (please complete the following information):**

- OS: Amazone Linux 2
- n8n Version: 1.15.1 - AI beta
- Database system: postgres
- Operation mode: main

**Additional context**

**Comment by Joffcom** [comment]
Hey @siduko,

Do you get the same issue if you call the webhook using something like Curl?

**Comment by siduko** [comment]
@Joffcom Yes, It is the same when I try with Postman

**Comment by Joffcom** [comment]
Hey @siduko,

What data did you post? Can you share your n8n configuration as well? I have tried using an older instance and a new instance using the quick docker run command and it works as expected for me.

**Comment by siduko** [comment]
@Joffcom Sorry for the late, I tried setup with slack event subscription, and I posted like the guide
https://api.slack.com/apis/connections/events-api#verification

**Comment by Joffcom** [comment]
Hey @siduko,

Can you try pulling the latest version and let me know if that shows the same issue?

**Comment by fabian-arnold** [comment]
I was facing the same issue. The problem in my case was a reference to n8n in the dependencies of a custom node. Without the dependency everything works again.

**Comment by Joffcom** [comment]
Moving to closed for now, if this is still an issue let me know and we can open it again.
