### ISSUE TITLE
LangChain interprets prompt

### ISSUE THREAD

**Issue by haf** [n8n-io/n8n#7692]
**Describe the bug**

Create a new Basic LLM chain, with prompt `{` and run it. It yields no output, despite being a valid prompt to the API.

It is interpreted by LangChain and there's no output.

For more complicated inputs, e.g. such containing sequences of `{` and/or `}`, you get 'interpolation error' from LangChain, due to incorrect escaping of input.

**Expected behavior**

Unless otherwise specified in the UI, inputs (e.g. from users) should be not executed.

**Environment (please complete the following information):**

- n8n Version: cloud beta
- Node.js Version [e.g. 18.16.0]: don't know
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]: don't know
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]: don't know

**Additional context**

**Comment by Joffcom** [comment]
Hey @haf,

We believe we fixed this, Could you restart your cloud instance so it updates to the latest beta image and let me know if it is still an issue for you?
