### ISSUE TITLE
Missing `Content-Type` header makes webhook ignore body

### ISSUE THREAD

**Issue by leeoocca** [n8n-io/n8n#7700]
**Describe the bug**
If a webhook trigger is called without the appropriate `Content-Type` header, the body is ignored. I'll report the issue on the service of the caller but it would be nice to have it working anyways, unless there are of course security concerns.

**To Reproduce**

1. Create a dummy webhook trigger like
```json
{
  "nodes": [
    {
      "parameters": {
        "httpMethod": "POST",
        "path": "abc",
        "options": {}
      },
      "id": "ce36f2ed-dbb4-48cb-a8a2-e96065e0cdcc",
      "name": "Webhook",
      "type": "n8n-nodes-base.webhook",
      "typeVersion": 1,
      "position": [
        820,
        380
      ],
      "webhookId": "10f5ceed-0b71-498f-aba9-87ca9e30479c"
    }
  ],
  "connections": {}
}
```
2. Call the webhook with `curl` like follows:
```sh
curl -r POST https://n8n/webhook-test/abc -H 'Content-Type:' -d '{"test":"ok"}'
```
3. Inspect the input of the trigger: the body is missing.

**Expected behavior**
The body should be shown in raw text.

**Environment (please complete the following information):**

- OS: docker
- n8n Version 1.15.2
- Node.js Version docker default
- Database system default (SQLite)
- Operation mode default (main)

**Comment by Joffcom** [comment]
Hey @leeoocca,

I have created `NODE-927` as our internal ticket for this one while we work out which approach to take.

**Comment by leeoocca** [comment]
Hey @Joffcom,

Thanks for your reply. I'm already happy as I found another solution, but I can expect other people might be working with imperfect API that might have this issue. In that case I would inform the user in some way that another solution is possible.

Thanks for looking into this!

**Comment by netroy** [comment]
Starting 1.21.x, in the case of missing content-type, n8n will now automatically save the request payload as binary-data, which can then be parsed using a `Convert to/from binary data` node.
