### ISSUE TITLE
Credential name does not display when viewing credential

### ISSUE THREAD

**Issue by mjesuele** [n8n-io/n8n#7704]
**Describe the bug**
When creating a credential, the given name is not used to list it, and it instead shows up with a generic name like "Query Auth account"

**To Reproduce**

1. Go to Credentials section
2. Add a new Query Auth credential
3. Give it a name "Smartlead API Key" and arbitrary value and save it
4. See that the name is displayed as "Query Auth account"

![image](https://github.com/n8n-io/n8n/assets/871117/4608b573-938a-4ecb-9047-59bdc1992b42)
![image](https://github.com/n8n-io/n8n/assets/871117/7bc35f7b-0527-4cfd-bd23-10e92f6b9436)

**Expected behavior**
The name of the credential should be displayed as "Smartlead API Key"

**Environment**

- OS: Ubuntu 23.10 x64
- n8n Version: 1.15.2

The following versions are whatever the default for the n8n 1.15.2 docker image are - the instance is self-hosted on DigitalOcean
- Node.js Version
- Database system
- Operation mode

**Comment by mjesuele** [comment]
Ah! Of course. I'm going to blame this on still being groggy this morning.

Thank you.

**Comment by Joffcom** [comment]
Hey @mjesuele,

Perfect I am going to mark this as closed for now 🙌🏻
