### ISSUE TITLE
Manual trigger not top priority when executing workflow manually

### ISSUE THREAD

**Issue by Zortrox** [n8n-io/n8n#7740]
In my workflow with multiple triggers, webhook and form triggers have a higher priority than manual triggers when clicking "Execute Workflow".  I haven't tested all the trigger nodes though, so there may be others that have a higher priority.

I didn't see any mention of node priority in the docs, but I think having the manual execution trigger always fire when clicking "Execute Workflow" should be the expected result.

**To Reproduce**

1. Create a workflow with a manual trigger and webhook or form trigger.
2. Click "Execute Workflow".
3. The webhook or form trigger fires.

**Expected behavior**
The manual trigger should fire.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 20.04
- n8n Version: 1.16.0
- Node.js Version: 18.18.2
- Database system: SQLite
- Operation mode: main

**Additional context**
| | |
|:-------------------------:|:-------------------------:|
|Webhook Trigger|Form Trigger|
![Reproduction (Webhook)](https://github.com/n8n-io/n8n/assets/10609756/dca49cf8-7e1f-4051-b60f-06e7272e19ed)|![Reproduction (Form)](https://github.com/n8n-io/n8n/assets/10609756/80b5939b-65b2-4073-8517-3c31ac8277b7)|

**Comment by Joffcom** [comment]
Hey @Zortrox,

This is one of those things that we have been aware of for a while and have not implemented anything for it. Ideally it should probably ask you which trigger node you want to use if you have multiple. Sadly though as this is not a bug and it is currently working as intended I am going to mark this as closed.

What I will do though is link this to the internal feature request and when / if we change this we will pop an update on this issue to keep you updated.

Let me know if you have any questions about this.
