### ISSUE TITLE
Schedule Trigger Node and Webhook Trigger Node run forever until cancel them

### ISSUE THREAD

**Issue by AFirouzi** [n8n-io/n8n#7765]
**Describe the bug**
The webhook trigger and schedule trigger nodes keep running and consuming the server resources without any result. The only way to stop them is to cancel the execution manually.

**To Reproduce**

1. Create a new workflow
2. Add only the schedule trigger or webhook trigger (There is no need to add another node).
3. If you added the schedule trigger, wait until it executes. If you added a webhook trigger, send the request.
4. Check the executions list to see it keeps running without stopping.

**Expected behavior**
Since it has only one node, it should execute quickly and then show it as a successful execution. I also ran it with other nodes, but it is not working in that case also.

**Environment (please complete the following information):**

- OS:  Ubuntu Linux: 22.04
- n8n Version: 1.16.0
- Node.js Version: 16.18.1
- Database system: postgres:11.16
- Operation mode: queue

**Additional context**
I have one main instance and one worker with the same n8n version.

**Comment by Joffcom** [comment]
Hey @AFirouzi,

I have not been able to reproduce this on `1.17.1` could you try updating to see if it is still an issue? If it is still an issue if you open your browser dev console when you click on the stop button is there any error in the network or console tab?

**Comment by Joffcom** [comment]
Hey @AFirouzi,

It could be, that looks like it is saying it has been cancelled so it could be that the front end is not getting the message. Do you get the same issue if you try accessing the direct ip of your n8n instance bypassing any reverse proxies or anything else that may be configured?

**Comment by AFirouzi** [comment]
@Joffcom ,
Just tried the way you said. with two different browsers, Chrome and Firefox. I see no errors but I see an strange behaviour. The schedule trigger keeps creating new execution even when it is deactivated.

**Comment by Joffcom** [comment]
Hey @AFirouzi 

That is unexpected, I was toying with this before signing off for the week and I am not able to reproduce it at all. Are you using our standard docker image or a custom one?

**Comment by Joffcom** [comment]
Hey @AFirouzi,

I can't think of anything that would cause this and I have not seen any other reports of it 🤔 Have you tried using private browsing in your browser / making sure there are no extensions enabled?

**Comment by LMO94** [comment]
@Joffcom 
I was actually facing same issues on 1.17.1 (deployed via railway).

**Comment by Joffcom** [comment]
Hey @LMO94,

Are you still seeing it on Railway or is it working now?

**Comment by AFirouzi** [comment]
Hi @Joffcom , sorry for the late response. I found out the issue was in the config finally. From my side, we can close this issue.

**Comment by Joffcom** [comment]
Hey @AFirouzi,

Sounds good to me I will get this one closed.
