### ISSUE TITLE
Merge Node runs without both inputs

### ISSUE THREAD

**Issue by Panoplos** [n8n-io/n8n#7775]
**Describe the bug**

The "Merge Node" is executing without having received data from both inputs.

![image](https://github.com/n8n-io/n8n/assets/2549985/4e7cf2b5-91bb-4ccd-8812-9e35ab17073f)
<img width="1484" alt="image" src="https://github.com/n8n-io/n8n/assets/2549985/b2971b83-9ffe-477b-97c6-1499bd8f5e69">

**To Reproduce**

Recreate flow in the attached diagram.

**Expected behavior**
The Merge Node should not execute until it has received both inputs.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 1.16.0
- Node.js Version: 18
- Database system: Postgres 14.8
- Operation mode: main

**Additional context**

**Comment by janober** [comment]
Yes, that is expected and correct behavior. 

Merge3 waits until both connected nodes have been executed (and no node execution is outstanding). If there is no data on one of the inputs, it continues to process with the data it received. 

HTTP Request3 executes correctly 2x as it receives data 2x (it has an incoming connection from 2 different nodes). The "Execute Once" option is not about executing only once if it gets called multiple times, it is about executing only the first item for every call it receives. So if you call it once with 5 items and once with 3 it would normally make 8 requests. With "Execute Once" activated will it only run 2x. 1x for the first item of the 5 and 1x for the first item of the 3.

I hope that makes sense.

**Comment by Panoplos** [comment]
BTW, as a user of the system, we find that with many of the built-in nodes, they do not have options for augmenting the input, just drops and outputs its own output, like Read PDF, OpenAI, and HTTP Request nodes, so we have to create this whole convoluted merge flow...which also impacts conditional branch execution like this. A visitor pattern would do wonders for this DX.

Also, when binary data is present, all nodes that need access to it should allow access with use of "Expression", as most just require some hardcoded index into the binary data. In our case, we have multiple attachments that we need to select from, and I had to the following to set the attachment into a new binary entry to allow for handling the hard-coded indexer requirement.
<img width="1084" alt="image" src="https://github.com/n8n-io/n8n/assets/2549985/a846b06c-91da-428b-8244-9807f5f2ea87">

**Comment by janober** [comment]
Merge1 is different as it has the Mode "chooseBranch" set which behaves differently. If it is set to the first input (as I assume in your case) and there is no data on that input, then the node does not run. As the chosen input did not provide any data.

Agree, that is really something we have to tackle at some point. We just have to think about properly how exactly it should work and behave.

Sorry, do not understand what you mean with binary data and expressions.

**Comment by Panoplos** [comment]
How do you suggest I keep the flow from executing in this case?

For the binary data issue, see below. This is an HTTP Request node. When I want to send attachment data, I have to provide the hard-coded path to the desired attachment. (My work around was that I converted the attachment to JSON (binary format), then back to a binary object with a name I choose. Then I can just use this single path with variable content. The `Input Data Field Name` should allow me to use an Expression to set it.

<img width="618" alt="image" src="https://github.com/n8n-io/n8n/assets/2549985/a2f8683e-666e-4880-825a-1ab195c2a99f">

**Comment by janober** [comment]
Fix got released with [`n8n@1.18.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.18.1)
