### ISSUE TITLE
{Request} Icons in the Workflow Overview

### ISSUE THREAD

**Issue by brennermax** [n8n-io/n8n#7785]
Hello, for a better overview of the workflows, it would be great if the symbol of the trigger could be displayed in front of the name of each workflow and also filtered by it. This makes it easier to find workflows and optimizes the overview. Best regards

**Comment by janober** [comment]
Thanks a lot. But as defined in our template:
![Screenshot from 2023-11-23 08-44-33](https://github.com/n8n-io/n8n/assets/6249596/159bd0ab-78c7-4607-a4df-cd4d4262322b)
do all Feature Request have to be made through our [Forum](https://community.n8n.io/) and not GitHub. Could you please post your request there. Thanks!
