### ISSUE TITLE
AutoComplete not working in multiOptions properties

### ISSUE THREAD

**Issue by lucafaggianelli** [n8n-io/n8n#78]
When editing node properties, the autocomplete feature of the select element doesn't work for node properties with the type `multiOptions`

![Screenshot from 2019-10-15 02-59-07](https://user-images.githubusercontent.com/4471043/66792178-da669700-eef7-11e9-90f0-60b18a492561.png)

**Comment by janober** [comment]
Lookes like it is the same issue as #2

**Comment by lucafaggianelli** [comment]
It's an issue with the `setFocus` function called as `<el-select @focus="setFocus">` here:
https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/ParameterInput.vue#L64

see the PR for details, here a codepen that I used for fixing the issue, if you want to play around:
https://codepen.io/lucafaggianelli/pen/mddPvbm?editors=1010
