### ISSUE TITLE
mqtt node hangs in execution

### ISSUE THREAD

**Issue by Zetanova** [n8n-io/n8n#7813]
**Describe the bug**
Publishing a message with QoS2 "exactly once" with the mqtt node 
let the workflow execute for more then 12h and it cannot be stopped.

Only a n8n restarts helps.

**To Reproduce**
Create a workflow
Add a manual trigger node
Add a mqtt node
Set the topic 
Set QoS level set  "Exactly Once"
Execute the workflow

**Expected behavior**
A message should be published or the node should fail in the timeout window.

- OS: docker image
- n8n Version 1.17.1
- Database system: postgres
- Operation mode: main
- MQTT Broker: nats 2.9.20

**Comment by Joffcom** [comment]
Hey @Zetanova,

Thanks for the report this is something that was reported on our [community support forum](https://community.n8n.io/t/mqtt-trigger-node-hanging-when-listening-for-event/) a while back. Our internal reference for this is: `NODE-935`

**Comment by Zetanova** [comment]
The mqtt trigger node and publishing over QoS 0 and 1 worked fine in my tests.
Around 100 messages got processed.

**Comment by Joffcom** [comment]
Hey @Zetanova,

We have recently done some work on the MQTT node, Can you try updating and letting me know if this is still an issue.

**Comment by Zetanova** [comment]
I am using now my own node to directly use nats
https//github.com/zetanova/n8n-nodes-nats

I will try the mqtt node now out and write tomorrow

**Comment by Zetanova** [comment]
my nats version 2.9.25 does not have QoS2 support,
It got added with 2.10.0

The mqtt pub in QoS2 is hanging and does not timeout,
but the issue seams resolved.

It is possible now to stop the running test and prod executions.
