### ISSUE TITLE
BambooHR node does not allow to set onlyCurrent option.

### ISSUE THREAD

**Issue by oleksandrborniak** [n8n-io/n8n#7876]
**Describe the bug**
The BambooHR node, Resource: Company Report, Operation: Get does not allow choose "onlyCurrent" option.
<img width="359" alt="Screenshot 2023-11-29 at 22 34 03" src="https://github.com/n8n-io/n8n/assets/49722408/a8520887-f88b-4d90-a771-fefc2d8f0a96">
<img width="987" alt="Screenshot 2023-11-29 at 22 31 34" src="https://github.com/n8n-io/n8n/assets/49722408/b78d2510-f790-425a-9267-16b041e423b6">

**To Reproduce**
Try to set "onlyCurrent" option in BambooHR node, Resource: Company Report, Operation: Get

**Expected behavior**
I should be able to choose "onlyCurrent" option.
`https://api.bamboohr.com/api/gateway.php/DOMAIN/v1/reports/ReportID?onlyCurrent=false`

**Environment (please complete the following information):**

OS: MacOS
n8n Version: 1.17.1
Database system: SQLite

**Comment by Joffcom** [comment]
Hey @oleksandrborniak,

Thanks for the report, this sounds  more like a feature request than a bug to me so this would be better suited to the feature request section of the community support forum.

Could you let me know if you consider this to be a bug and if that is the case we can keep it open rather than close it.

**Comment by Joffcom** [comment]
Hey @oleksandrborniak,

While adding it may seem like an easy task we use the forum for tracking feature requests to prioritise them based on what the community are after, This can lead to requests sometimes taking longer to implement but we have a lot of requests and our own roadmap items to implement.

That being said I have created PR which can be found below that will add this feature but we will start to be stricter on this soon and close issues that are feature requests and not bugs.

https://github.com/n8n-io/n8n/pull/7878

**Comment by oleksandrborniak** [comment]
Thanks for the clarification and assistance.
I made a note and will pay attention to it in the future.
Have a nice day.

**Comment by janober** [comment]
Fix got released with [`n8n@1.20.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.20.0)
