### ISSUE TITLE
n8n fails to install due to error with sqlite3 dependency

### ISSUE THREAD

**Issue by MHarris021** [n8n-io/n8n#789]
**Describe the bug**
n8n fails to install, issue appears to be related to the sqlite3 dependency being incompatible with node 14.5.0. Looks like it may need python to build sqlite3 binary

**To Reproduce**
1. run npm i n8n -g

**Expected behavior**
n8n installs successfully

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - n8n Version 0.74.0
 - Node.js Version 14.5.0
 - Npm.js 6.14.6

**Additional context**
`node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v83-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@14.5.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/mharris/n/lib/node_modules/n8n/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
`

**Comment by janober** [comment]
Does it work in other Node.js versions without Python and build-essential packages installed for you? Because I would expect the same problem no matter which Node.js version. It is what most larger npm packages require by default.

Just tested if both are installed n8n installs fine.

**Comment by janober** [comment]
Wanted to check in again because of my previous question. Without an answer within the next days, I will close the issue.

**Comment by MHarris021** [comment]
Hi @janober , I was able to get it installed fine using node 10.21.0. There appeared to be a binary version that my system was able to download. I think the issue was actually the need to build the sqlite3 binary for node 14.5.0 on my machine. it didn't have the build-essentials package installed. the requirement on build-essentials to use the n8n cli wasn't very well spelled out in the installation steps.  regardless, i'm now able to uses n8n and thank you for your help

**Comment by janober** [comment]
That is really great to hear that it works now! Then have fun!
