### ISSUE TITLE
When there is a decimal point in the node name, the output data is empty

### ISSUE THREAD

**Issue by ybom77** [n8n-io/n8n#7896]
**Describe the bug**
When there is a decimal point in the node name, the output data is empty

**To Reproduce**

before :
![image](https://github.com/n8n-io/n8n/assets/15134783/8b153351-08d8-4ffb-9cf9-e4ac22852507)

after rename:
![image](https://github.com/n8n-io/n8n/assets/15134783/ac19e67a-ea4f-4cbb-8cc5-7336a33bdc95)

**Expected behavior**

the output data not empty

- n8n Version [e.g. 1.18.0]

**Comment by janober** [comment]
Fix got released with [`n8n@1.21.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.21.0)
