### ISSUE TITLE
IF-Node, not equal with wrong output

### ISSUE THREAD

**Issue by prononext** [n8n-io/n8n#7915]
The IF Node when in not-equal has a wrong output. Equal works but Not Equal does not.

Even if doing a any combine and defining the parameter as number and as string, the output is still wrong. 

I had that tested on a couple of workflows and changed the output to equal so I could continue using the workflows. 

I noticed the same with Not-Contains but the reproductions were only partly successful. 

n8n Version. 1.16.0 on docker in queue mode.

**Comment by Joffcom** [comment]
Hey @prononext,

Can you share a workflow and data that reproduces the issue?

**Comment by Joffcom** [comment]
Closing for now as we never did get a workflow that could reproduce this, if this is still an issue let me know and we can open it again.
