### ISSUE TITLE
Locally hosted Motorhead does not have an API key

### ISSUE THREAD

**Issue by cromulus** [n8n-io/n8n#7925]
**Describe the bug**
With a self-hosted instance of motorhead, it is impossible to connect because you cannot set the API key locally.
**To Reproduce**

1. Host an instance of Motorhead
2. create a Motorhead credential pointing at your local motorhead instance.
3. Cannot leave the API key blank, and any value in that key causes an error upon connection.

**Expected behavior**
I expected the API token for motorhead to be optional, such that I could access a locally hosted instance of motorhead.

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 1.18.0
- Node.js Version: v18.18.2
- Database system: postgres
- Operation mode: main

**Additional context**
Just that! Would love to be able to run as much of an LLM stack locally, thus nearly free, as possible!

This new langchain stuff is amazing! Thank you!

**Comment by Joffcom** [comment]
Hey @cromulus,

I was just going through some old tickets and this one came up, It looks like self hosted Motörhead is deprecated so it wouldn't make much sense for us to add this now as the project is wrapping up.
