### ISSUE TITLE
"We can’t connect to the server at e.customeriomail.com"

### ISSUE THREAD

**Issue by fcatus** [n8n-io/n8n#793]
**Describe the bug**
Cannot verify my account. When clicking on the verification link, I get the typical "We can’t connect to the server" page.
`"We can’t connect to the server at e.customeriomail.com"`

**To Reproduce**
1. Sign up to n8n.io.
2. Click on verification link.

**Expected behavior**
Verify account.

**Comment by janober** [comment]
Very strange. I just tested and for me, it worked fine. Can you please check again. Maybe it was some kind of temporary issue with the server.

**Comment by fcatus** [comment]
> Very strange. I just tested and for me, it worked fine. Can you please check again. Maybe it was some kind of temporary issue with the server.

It is working now. Thank you. Closing issue.
