### ISSUE TITLE
Data Mode option isn't displayed in Google Sheet node

### ISSUE THREAD

**Issue by antoinelin** [n8n-io/n8n#7934]
**Describe the bug**
Hi n8n team, I would like to setup a Google Sheet node to upsert a row but the field `Data Mode` won't show, even when I fill every fields above. 

**To Reproduce**

1. Create a new workflow
2. Add a Google Sheet node
3. Connect n8n using Credential to your Google account
4. Fill fields: `Sheet Within Document`, `Append Row`
5. Select document and sheet
6. `Data Mode` options are not showing up and if you try to execute node an error is triggered `ERROR: Could not get parameter "columns.mappingMode`

**Expected behavior**
To select Data Mode and where to upsert the data

**Environment (please complete the following information):**

- OS: MacOS Sonoma
- n8n Version 1.18.1
- Application setup through Cloudron

**Comment by toinelin** [comment]
As it's in `pre-release` state I can't update the package from Cloudron (the update is not available). Nothing urgent on my side I can wait for the definitive release and I will update this issue

**Comment by Joffcom** [comment]
Hey @toinelin,

How does Cloudron work out which version to use? At the moment we list `1.18.0` as latest and `1.19.5` as next, I wonder if it uses the GitHub releases.

**Comment by Joffcom** [comment]
Moving to closed as this should be fixed, If it isn't let me know and we can open it again.
