### ISSUE TITLE
Interface should be mobile responsive

### ISSUE THREAD

**Issue by JoshFialkoff** [n8n-io/n8n#7938]
**Describe the bug**
n8n should adapt to the size of each user's screen so that it's easy to navigate through work flows and update credentials etc from mobile devices. 

**To Reproduce**

1. Go to /workflows/
2. Click on a node
3. Try to edit it 

**Expected behavior**
it should be easier for users to scroll to specific nodes and then click into them and make changes and then go back to the overview. Even though there's an icon to see an entire workflow, the components often float off the screen. 

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.18.0]
- Node.js Version [e.g. 21.3.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @JoshFialkoff,

At the moment n8n is not designed to work from a mobile device so I would expect there to be some issues with this, As this is not a bug as such I am going to mark this as closed for now but feel free to put a vote on the feature request for a mobile friendly editor here: https://community.n8n.io/t/mobile-friendly-editor/1845

Let me know if you have any questions on this.
