### ISSUE TITLE
Allow to specify S3 Endpoint URL to allow usage of S3 compatible services

### ISSUE THREAD

**Issue by iFrozenPhoenix** [n8n-io/n8n#794]
Currently the S3 API is implemented to just communicate with the Amazon S3 API.
The usage of S3 compatible services like minio.io or swift is currently not possible due to
a missing option to specify the endpoint url.

**To Reproduce**

**Expected behavior**
An option should be available which let someone specify the endpoint url of
the S3 api to use, to enable the usage of S3 compatible services.

**Environment (please complete the following information):**
 - OS: Unknown (Official n8n Docker Container Image)
 - n8n Version: 0.74.0
 - Node.js Version: v12.16.3

**Comment by janober** [comment]
Got released with n8n@0.80.0
