### ISSUE TITLE
Notion Data Page Filter was not supported

### ISSUE THREAD

**Issue by weiwendu** [n8n-io/n8n#7974]
it's not n8n system problem.
Only the code node java script was not working. ask help please.

const new_items = [];
for (item of $items("Github Trigger")) {
  // Skip processing if action is 'opened'
  if (item.json["body"]["action"] == "opened") {
    continue;
  }

  // Capture the action and the possibly changed new title
  const action = item.json["body"]["action"];
  const newTitle = item.json["body"]["issue"]["title"]; // Assuming this is the path to the new title

  // Build the output template with the action and new title included
  var new_item = {
    "json": {
      "action": action,
      "newTitle": newTitle, // Adding the new title
      "notionfilter": ""
    }
  };

  // Create Notion filter to find specific database page by issue ID
  const notionfilter = {
    property: 'Issue ID',
    number: {
      equals: parseInt(item.json["body"]["issue"]["id"])
    }
  };

  // Assign the filter to new_item's json
  new_item.json.notionfilter = JSON.stringify(notionfilter);

  // Add the new item to the array
  new_items.push(new_item);
}

return new_items;

**Comment by Joffcom** [comment]
Hey @weiwendu,

I don't understand what issue you are reporting, Can you complete the template? If you are trying to contribute a missing feature feel free to create a fork of n8n, create a branch for your feature and open a PR.

**Comment by weiwendu** [comment]
I am a new person to learn n8n. I try to follow someone template that was called Github issue and Notion Integration. but it cannot complete.

**Comment by weiwendu** [comment]
here is the workflow templete. please the attachement.
[Github_Notion_Integration.json](https://github.com/n8n-io/n8n/files/13619102/Github_Notion_Integration.json)

**Comment by weiwendu** [comment]
Fixed the problem , we don't need to use the filter to seach the page.
Here is teh updated templete.
[Github_Notion_Integration.json](https://github.com/n8n-io/n8n/files/13628192/Github_Notion_Integration.json)
