### ISSUE TITLE
HTTP Request Node Incorrectly Handles HTTPS Requests with HTTP Proxy (400 or 503 Error)

### ISSUE THREAD

**Issue by biankasyo** [n8n-io/n8n#7992]
**Describe the bug**
When utilizing the HTTP Request node in n8n and configuring the Options to use an HTTP Proxy, there is an issue when performing a GET request. If the request URL uses HTTP, the response data is returned successfully. However, if HTTPS is used, it results in a 400 or 503 error.

**To Reproduce**

1. Create a workflow with the HTTP Request node.
2. Configure the node to use an HTTP Proxy.
3. Set the request URL to use HTTPS.
4. Execute the workflow.

**Expected behavior**
The HTTP Request node should be able to handle HTTPS requests when an HTTP Proxy is configured, returning the data successfully.

**Actual Behavior:**
Instead of receiving the expected data, an error is returned, such as a 400 or 503 error.

**Environment:**

- OS: CentOS Linux release 7.9.2009
- n8n Version 1.18.2
- Node.js Version 18.18.2
- Database system SQLite
- Operation mode own

**Comment by Joffcom** [comment]
Hey @biankasyo,

Thanks for reporting the issue, I believe this is the same as the issue here: https://github.com/n8n-io/n8n/issues/7037 can you take a look and let me know you think.

**Comment by biankasyo** [comment]
> Hey @biankasyo,
> 
> Thanks for reporting the issue, I believe this is the same as the issue here: #7037 can you take a look and let me know you think.

Thank you for your help. I have attempted to use the solution mentioned in the related issue to deploy the older version of n8n, specifically version 0.219.1. However, I am still facing issues when making requests via HTTPS using an HTTP proxy. It consistently returns a 503 error. On the other hand, when using the proxy with HTTP requests, I do not encounter any issues.

I would like to inquire if there are any recommended solutions to address this problem. Your guidance and suggestions would be greatly appreciated.

**Comment by Joffcom** [comment]
Hey @biankasyo,

The best solution would be to use a proxy that also implements https then set both the http_proxy and https_proxy environment variables.

As this is likely going to be related to the same underlying issue in the Axios package I will have to move this to closed for now but feel free to ask more questions on this one.

**Comment by biankasyo** [comment]
I came up with a temporary solution for this issue and left a comment in the thread you mentioned. Please take a look at it [here](https://github.com/n8n-io/n8n/issues/7037#issuecomment-1855328937).

**Comment by Joffcom** [comment]
That is a similar solution to what someone posted on the support forum a while back as well. I always forget about that option.
