### ISSUE TITLE
LinkedIn Scopes have changed

### ISSUE THREAD

**Issue by koehn** [n8n-io/n8n#7993]
**Describe the bug**
The LinkedIn scope for accessing email address has changed. It was `r_emailaddress` and is now `email`. You cannot use the LinkedIn Node to connect to your account until the scope is updated in n8n. 

**To Reproduce**

1. Create a LinkedIn Node and application on LinkedIn. Assign the "Sign In with LinkedIn using OpenID Connect” and “Share on LinkedIn” products and wait for them to be reviewed. Set up the client id, client secret, and callback URL. 
2. Click on ‘Connect My Account'
5. Wait five seconds, view details:
```
Received following query parameters: {"error":"unauthorized_scope_error","error_description":"Scope &quot;r_emailaddress&quot; is not authorized for your application","state":"eyJ0b2tlbiI6Ik1lUzhDTGtrLU5CcXNJWWJqTjlGdjE1YzdHb1RvR0pfcnNqYyIsImNpZCI6InpJOENSRUx6Y0FES0IzQ2gifQ=="}
```
6. Review documentation for new (8/23) API: https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2

**Expected behavior**
n8n LinkedIn node should use current API.

**Environment (please complete the following information):**

- OS: k3s 1.27 on ARM64 (n8n Docker image)
- n8n Version 1.18
- Node.js Version Whatever is on the docker image
- Database system postgres 16.1
- Operation mode main

**Additional context**

**Comment by Joffcom** [comment]
Hey @koehn,

Thanks for the report, The fix for this is in the PR below and is currently waiting for internal review.

https://github.com/n8n-io/n8n/pull/7451

**Comment by Joffcom** [comment]
Hey @koehn,

We have released the change to the Linkedin Credential that will resolve this, If you are using a newer LinkedIn app with the community management product enabled you will need to use that credential type.

For now as this is resolved (or should be) I am going to mark this as closed but if you are still seeing an issue with this let me know and we can open it again.
