### ISSUE TITLE
Make it easy to use Ngrok or similar for local webhook testing

### ISSUE THREAD

**Issue by YoniFei** [n8n-io/n8n#80]
Trying to poke around, I see the `getNodeWebhookUrl` method definition in the interface, but I can't seem to find where it is implemented?

I think it would be ideal if you could have a setting somewhere that would force using an Ngrok/other tunnel's URL instead of localhost.

**Comment by janober** [comment]
Ah yes, that it is already implemented. You can find information about it here:
https://docs.n8n.io/#/setup?id=start-with-tunnel
