### ISSUE TITLE
Binary data fills up filesystem. Handle better and give admins more controls.

### ISSUE THREAD

**Issue by leesilverman** [n8n-io/n8n#8028]
**Describe the bug**
N8N_DEFAULT_BINARY_DATA_MODE=filesystem.  After a number of executions, the filesystem fills up and workflow starts to error.  I tried changing the workflow setting of "Save successful execution" to "do not save" but that had no effect on binary data.  This is especially problematic in a cluster of containers, where it's hard to shell in and it's hard to know which container to shell into.

Please give admins more granular controls over what happens with binary data after workflow execution is completed.

**To Reproduce**
Any workflow that processes a bunch of binary data will eventually fill up the filesystem.  Esp on a container where there isn't much disk space.

**Expected behavior**
With the option "Save successful execution" set to "do not save", I expected binary data to be cleaned up when the execution is finished.  

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]: Alpine Linux / Docker
- n8n Version [e.g. 1.0.1] 1.18.2
- Node.js Version [e.g. 18.16.0] 18.18.2
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed] Postgres
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`] queue

**Additional context**
Running multiple containers on Amazon Elastic container service.  My containers are built from n8nio/base:18 with a few additional node packages installed.

**Comment by Joffcom** [comment]
Hey @leesilverman,

As this is already created by you on our support forum here: https://community.n8n.io/t/binary-data-processing-starts-failing-after-a-few-hundred-runs-filesystem-full/34213 I am going to close this so we don't split the attention between multiple places.

**Comment by leesilverman** [comment]
Thanks.  Sometimes posts on the forum get missed, but wanted to make sure this got picked up.  Sorry for the double coverage.
