### ISSUE TITLE
Amazon SES Node error sending message

### ISSUE THREAD

**Issue by maxmarines** [n8n-io/n8n#803]
**Describe the bug**
At the moment, the amazon SES integration allows you to send emails up to 10,000 characters, which is not enough for the job. Because of this, I can not send letters containing styles and html code.

**To Reproduce**
1. Go to Amason SES
2. Send by Email HTML code more than 10,000 symbols
3. See error `"1. ERROR: URIError: URI malformed
Error: URIError: URI malformed
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsSes.node.js:265:27)`
or
`2 ERROR: Error: AWS error response [414]: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n</body>\r\n</html>\r\n"
Error: Error: AWS error response [414]: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n</body>\r\n</html>\r\n"
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsSes.node.js:265:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Expected behavior**

But I read the documentation **and offer a solution right away.** In this case, an email template with a size of up 10 MB. ( which is more than 10,000,000, characters)  will be stored by the Amazon and I only need to send variables in the TemplateData field.

### SOLUTION
<img width="205" alt="Solution" src="https://user-images.githubusercontent.com/62845038/88852133-8282ed80-d1f6-11ea-857f-6db0ca02c9af.png">

Information from the Official Amazon documentation:
<img width="960" alt="Amazon Documentaion" src="https://user-images.githubusercontent.com/62845038/88852232-aa725100-d1f6-11ea-9b12-d3345b3be96b.png">

[Example LINK](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-personalized-email-api.html#send-personalized-email-api-operations)
[Documentaion link](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendTemplatedEmail.html)
Example from Amazon `{
  "Source":"Mary Major <mary.major@example.com>",
  **"Template": "MyTemplate",**
  "ConfigurationSetName": "ConfigSet",
  "Destination": {
    "ToAddresses": [ "alejandro.rosalez@example.com"
    ]
  },
  **"TemplateData": "{ \"name\":\"Alejandro\", \"favoriteanimal\": \"alligator\" }"**
}`
**Environment**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version 0.75 from docker

**Comment by RicardoE105** [comment]
@maxmarines Sorry for the late response. Ahh yes, it not that the operation has missing fields but that it is meant to sent emails and not templates. There is a send template operation that the AWS API has. Should not be difficult to implement as it's pretty similar to this one. Thanks for letting us know. Will try to add it this week.

**Comment by RicardoE105** [comment]
@maxmarines ok just added the availability to send templates plus template CRUD operations. We will let you know when is released.

**Comment by janober** [comment]
Got released with n8n@0.87.0
