### ISSUE TITLE
Update checker does not run

### ISSUE THREAD

**Issue by nihaals** [n8n-io/n8n#8058]
**Describe the bug**
The version endpoint (`https://api.n8n.io/api/versions/:version`) is not called anymore.

**To Reproduce**

1. Start a fresh default n8n 1.15.2 instance and go to the setup page
2. Notice the endpoint is called
3. Start a fresh default n8n 1.16.0 instance and go to the setup page
4. Notice the endpoint is not called
5. Start a fresh default n8n 1.21.1 instance and go to the setup page
6. Notice the endpoint is not called

**Expected behavior**
The endpoint is called when loading the dashboard.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version: 1.21.1
- Node.js Version: Docker
- Database system: SQLite
- Operation mode: `main`

**Additional context**
After sourcediving I noticed the hiring message is printed in the same place and that also stopped being called in the same version.

**Comment by janober** [comment]
Thanks a lot for reporting this issue. We are already working on a solution here:
https://github.com/n8n-io/n8n/pull/8067

**Comment by janober** [comment]
Fix got released with [`n8n@1.22.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.22.0)

**Comment by janober** [comment]
Closing as the issue got fixed in the meantime.
