### ISSUE TITLE
Update check endpoint doesn't include new updates

### ISSUE THREAD

**Issue by nihaals** [n8n-io/n8n#8059]
**Describe the bug**
The versions endpoint (`https://api.n8n.io/api/versions/:version`) doesn't include new versions from 1.16.0.

**To Reproduce**

1. Go to https://api.n8n.io/api/versions/1.15.0
2. Notice it includes 1.16.0 as a new version
3. Go to https://api.n8n.io/api/versions/1.16.0
4. Notice it only includes 1.16.0 despite 1.20.0 being the current stable release

**Expected behavior**
The endpoint includes the latest stable version.

**Comment by janober** [comment]
Thanks a lot for reporting this issue. We have an idea what caused that problem and are working on a solution.

**Comment by janober** [comment]
Sorry, seems like nobody updated this issue yet. It got fixed shortly after you reported it. Thanks again!

**Comment by nihaals** [comment]
The endpoint now returns 1.21.1 which, as of writing, isn't a stable version. Shouldn't the endpoint return up to 1.20.0 (current `latest`)?
