### ISSUE TITLE
update from n8n@1.18.1 to n8n@1.19.4 brings down n8n published on subpath

### ISSUE THREAD

**Issue by nosovk** [n8n-io/n8n#8061]
**Describe the bug**
We have n8n setup, that works with path prefix, specified with N8N_EDITOR_BASE_URL and N8N_PATH.

After upgrade to 1.19.4 ui fails to start, making requests from Editor to root of domain, instead of path.
Version 1.18.1 works as expected.

**Expected behavior**
Expected that n8n editor will prefix requests within path.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 1.19.4]
- Node.js Version [e.g. 20.0.0]
- Database system [PGSQL]
- Operation mode [main]

**Comment by Joffcom** [comment]
Hey @nosovk,

Thanks for the report, Can you share the full configuration you are using so we can try to reproduce this?

**Comment by nosovk** [comment]
image: registry-1.docker.io/n8nio/n8n:1.18.1@sha256:85320dd3baa2e752084f9a1dd584a249036dd3b20bed59495d9c55ed62950fa5

```bash
N8N_DIAGNOSTICS_ENABLED=false
N8N_EDITOR_BASE_URL=https://ds.kingbilly.xyz/longpath/n8n/
N8N_EMAIL_MODE=smtp
N8N_HOST=ds.kingbilly.xyz
N8N_LISTEN_ADDRESS=0.0.0.0
N8N_LOG_LEVEL=info
N8N_METRICS=false
N8N_PATH=/longpath/n8n/
N8N_PORT=5678
N8N_PUSH_BACKEND=sse
N8N_SERVICE_NAME=kbc-kbc-n8-pr-gr_n8n
N8N_SERVICE_PORT=5678
N8N_SMTP_HOST=smtp.mailgun.org
N8N_SMTP_PORT=465
N8N_SMTP_SENDER=support@kingbilly.xyz
N8N_SMTP_SSL=true
N8N_USER_FOLDER=/opt/app/n8n
N8N_VERSION_NOTIFICATIONS_ENABLED=false
NODE_ENV=production
WEBHOOK_URL=https://ds.kingbilly.xyz/longpath/n8n/
DB_TYPE=postgresdb
ENV_TYPE=production
EXECUTIONS_TIMEOUT_MAX=7200
GENERIC_TIMEZONE=Europe/Kiev
GID=1000
```

**Comment by nosovk** [comment]
configuration above is working, but next published version is 1.19.4, and it fails to load.
the same with 1.20.x

**Comment by JacerOmri** [comment]
I've been trying to get it to work for a couple of days now. I've been reading the source code to understand what's happening. I think it's this function `getSettings`
https://github.com/n8n-io/n8n/blob/a651089a10d538a017b9bb1a5263038e0090d69d/packages/editor-ui/src/api/settings.ts#L11
that is never called with a context, the context is what provides the baseUrl and passed down to `makeRestApiRequest<T>` here 
https://github.com/n8n-io/n8n/blob/a651089a10d538a017b9bb1a5263038e0090d69d/packages/editor-ui/src/api/settings.ts#L12
https://github.com/n8n-io/n8n/blob/a651089a10d538a017b9bb1a5263038e0090d69d/packages/editor-ui/src/utils/apiUtils.ts#L109

**Comment by nosovk** [comment]
Then good part - it reproduces :) Bad part - it reproduces on all new versions

**Comment by woodmin** [comment]
The same issue here. Have to stay on 1.18.3 for now.

**Comment by Joffcom** [comment]
I have managed to reproduce this and have created `N8N-7138` as the internal dev ticket for this, I am not sure what the priority would be but unless using a subpath is a requirement I would recommend looking at the sub domain route which is preferred for now.
