### ISSUE TITLE
.all() method returns only last value

### ISSUE THREAD

**Issue by nosovk** [n8n-io/n8n#8063]
**Describe the bug**
when I try to get a list of ALL runs of previous node, using `all()` I can see only latest invocation.

<img width="342" alt="image" src="https://github.com/n8n-io/n8n/assets/1398808/8317a772-9f97-4e70-b17a-458bb914f057">
```javascript
previousNodeData = $('fetchDataFromAffilka').all();
for(let i=0; i<previousNodeData.length; i++) {
	console.log(previousNodeData.length,i,previousNodeData[i].json);
}
return previousNodeData;
```
Shows only last invocation of fetch. 

**To Reproduce**

1. Create any loop
2. add node that consume loop result
3. try to merge all results into one object

example flow:

[KBC_affilka_expences.json](https://github.com/n8n-io/n8n/files/13690500/KBC_affilka_expences.json)

**Expected behavior**

**Environment (please complete the following information):**

- OS: [docker]
- n8n Version [e.g. 1.18.1]
- Node.js Version [e.g. 20]
- Database system [PGSQL]
- Operation mode [`main`]

**Additional context**
Actually, I try to use answer from that question: https://community.n8n.io/t/help-with-pagination-looping/14074/4?u=johnnyk
But its written for all code node, where was no .all() method.

**Comment by janober** [comment]
It is behaving differently. `.all` does not return all items of all runs, it rather returns all items of the specified output index and run index (by default both are 0).

You can find the docs here:
https://docs.n8n.io/code/builtin/output-other-nodes/#output-of-other-nodes

If you want to get all items you can do in Expression something like that:
```
{{ (() => { const items = []; for (let i=0;;i++) { try { items.push(...($('fetchDataFromAffilka').all(0, i))); } catch(e) { return items; } } })() }}
```

Or in a Code-Node something like that:
```
const items = [];
for (let i=0;;i++) {
  try { 
    items.push(...($('fetchDataFromAffilka').all(0, i)));
  } catch(e) {
    return items;
  }
}
```
