### ISSUE TITLE
Google Sheet node does not work within "columns.mappingMode" parameter missing error

### ISSUE THREAD

**Issue by nosovk** [n8n-io/n8n#8065]
**Describe the bug**
When I try to add google sheet node, some settings are missing in UI, causing node execution failure
<img width="956" alt="image" src="https://github.com/n8n-io/n8n/assets/1398808/920c5bc6-117f-4c15-b933-343391b84d01">

**To Reproduce**

1. Add Google Sheets node
2. Switch to append mode
3. fill settings
4. try to execute node

**Expected behavior**
I'm expext that new lines will appear in google sheets

**Environment (please complete the following information):**

- OS: docker
- n8n Version 1.18.1
- Node.js Version 20
- Database system postgresql
- Operation mode main

**Additional context**

**Comment by nosovk** [comment]
<img width="941" alt="image" src="https://github.com/n8n-io/n8n/assets/1398808/1910e215-dfc9-40f0-b225-c68c5333f9d9">

**Comment by nosovk** [comment]
https://github.com/n8n-io/n8n/pull/7972 it could be that fix landed here, but i'm not sure, because can't update due to https://github.com/n8n-io/n8n/issues/8061

**Comment by Joffcom** [comment]
Hey @nosovk,

This issue has indeed been fixed in the PR you have found, For now I am going to close this one but if after upgrading if it is still an issue let me know and we can open this again.

(after the other issue is looked into)
