### ISSUE TITLE
Asana Node - Setting a body on GET requests

### ISSUE THREAD

**Issue by jbaldo** [n8n-io/n8n#8079]
**Describe the bug**
Hi, I'm a product manager at Asana working on Asana's API. Apologies, this isn't quite a bug but could benefit from a similar level of attention. Asana is rolling out some infrastructure changes which prevent us from accepting GET requests with a body (including an empty body). We've identified n8n's Asana node / plugin as a client with an outsized number of errors for this reason.

I don't have an n8n environment setup here, but it looks like in this [asanaAPIRequest](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Asana/GenericFunctions.ts#L17) function that body is a default parameter and always passed in? 

If that's the case, I was wondering if you have someone that could patch that to not send a body in GET requests so our mutual customers / users aren't impacted by errors.

**To Reproduce**
Set up a flow which fetches information from Asana. You may not see this error at the time I'm writing this, but it will occur once we resume rollout.

**Expected behavior**
In a GET request, omit the body of the request (even if empty).

**Comment by jbaldo** [comment]
I forgot to mention that we have a way to preview the change.

You can test your updated code against the new behavior by making requests to https://cdn.app.asana.com/api/1.0/ as the Asana API base url instead of https://app.asana.com/api/1.0/

**Comment by jbaldo** [comment]
Just became aware that someone on our team submitted a patch for this. So hoping you can help with merging and change management. https://github.com/n8n-io/n8n/pull/8057

**Comment by Joffcom** [comment]
Hey @jbaldo,

Thanks for the report, It looks like the PR your team created has been merged and released so this should help. For now I am going to mark this as closed as it looks to be resolved.

**Comment by jbaldo** [comment]
Hey @Joffcom, good news. Thanks. Just to confirm for customer communication, this should be live and deployed for everyone? Is there anything a customer would need to do? Update a package or anything like that? Is there any difference between the SaaS and self-hosted options?

Thanks, again.
