### ISSUE TITLE
Text disappear if between '<' and '>' character

### ISSUE THREAD

**Issue by mbrother2** [n8n-io/n8n#8081]
**Describe the bug**
Text disappear if between '<' and '>' character

**To Reproduce**

1. Go to recent execution
2. Click on any node
3. Both INPUT and OUTPUT of node will hide all texts are between '<' and '>' character in Table and JSON mode (Schema OK)

**Expected behavior**
All texts show normally

**Environment (please complete the following information):**

- OS: Debian 11
- n8n Version: 1.20.0
- Node.js Version: v18.18.2
- Database system: SQLite
- Operation mode: Main

**Additional context**
Please see attachments:

Table Mode (error):
![error1_table](https://github.com/n8n-io/n8n/assets/11661949/1713c20f-cef2-4524-bd36-b48bc6978ee7)

JSON Mode (error):
![error2_json](https://github.com/n8n-io/n8n/assets/11661949/2aa8b5e8-0209-41d5-a27f-edffec93bc6a)

Schema Mode (OK):
![ok_schema](https://github.com/n8n-io/n8n/assets/11661949/4b5d3e2c-84af-4856-9c6f-b4c48b4e767f)

**Comment by janober** [comment]
Thanks a lot for reporting this issue. It is already tracked internally via the ticket ID `ADO-1594`

**Comment by Joffcom** [comment]
Hey @mbrother2,

It looks like this should be fixed from `1.22.1` onwards, I am going to mark this as closed if you are still seeing this on newer versions let me know and we can open it again.

**Comment by Joffcom** [comment]
Fix got released with [`n8n@1.23.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.23.0)
