### ISSUE TITLE
Cannot save workflow with Error trigger

### ISSUE THREAD

**Issue by gelleson** [n8n-io/n8n#810]
**Describe the bug**
When I trying to save workflow with Error trigger raised an error.
![Alt text](https://i.ibb.co/WHSBBM6/Screenshot-2020-08-03-n8n-io-Workflow-Automation.png "Optional title")

**To Reproduce**
1. Create workflow
2. Add Error trigger node
3. Add telegram node for sending an error message
4. Try to save the workflow
5. Profit!

**Expected behavior**
I expect to save the workflow and enjoy my life.
But I got pain and sadness.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - n8n Version 0.75
 - Node.js Version I don't know because I'm using a docker

**Additional context**

If somebody knows where this error located I'm ready to make fix it and create MR.

**Comment by janober** [comment]
It looks like you are not saving the workflow, you are activating it. Actually simply saving it will work fine.
Error-Workflows do not have to be activated, you simply save it and it will work as long as you set it as Error-Workflow on another workflow.

Here some additional information about Error-Workflows:
https://docs.n8n.io/reference/workflow.html#error-workflows
https://community.n8n.io/t/error-workflow-doesnt-start/1446/3
https://medium.com/n8n-io/creating-error-workflows-in-n8n-6e03c9ecbc0f
