### ISSUE TITLE
Error activating new workflows

### ISSUE THREAD

**Issue by pmoralesp** [n8n-io/n8n#8122]
**Describe the bug**
Error activating new workflows after upgrade to 1.22.0 (docker)

**To Reproduce**

1. Go to 'Add workflow'
2. Add any node, for example a scheduled trigger
3. Click on 'Activate'
4. See error:

```
Workflow could not be activated:
Cannot read properties of undefined (reading 'add')
```

**Expected behavior**
Successfull activate workflow

**Environment (please complete the following information):**

- n8n 1.22.0 (Docker)

**Additional context**

Was working as expected until v1.21.0. Started to fail after upgraded to 1.22.0
Also have problems when try to rename workflows already created before upgrade n8n:

```
Problem saving workflow
Cannot read properties of undefined (reading 'remove')
```

**Comment by netroy** [comment]
We are aware of this, and actively working on fixing and releasing a patch.

Just out of curiousity: Are you running watchtower? or are you using the `next` tag in your setup?

**Comment by ivov** [comment]
@pmoralesp Can you please share the env vars you're using? (redacting sensitive info)

**Comment by pmoralesp** [comment]
> @pmoralesp Can you please share the env vars you're using? (redacting sensitive info)

Sure!

```
     DB_LOGGING_ENABLED = true
     DB_LOGGING_OPTIONS = warn
     DB_MYSQLDB_DATABASE = n8n
     DB_MYSQLDB_HOST = mysql
     DB_MYSQLDB_PASSWORD = XXXXXXXXXXXX
     DB_MYSQLDB_PORT = 3306
     DB_MYSQLDB_USER = XXXXX
     DB_POSTGRESDB_DATABASE = n8n
     DB_POSTGRESDB_HOST = postgres
     DB_POSTGRESDB_PASSWORD = XXXXXXXXXXXXXXXXX
     DB_POSTGRESDB_PORT = 5432
     DB_POSTGRESDB_SCHEMA = n8n
     DB_POSTGRESDB_USER = XXXXXX
     DB_TYPE = postgresdb
     GENERIC_TIMEZONE = America/Santiago
     N8N_EDITOR_BASE_URL = https://n8n.YYYYYYYYYYY.com
     N8N_EMAIL_MODE = smtp
     N8N_HOST = n8n.YYYYYYYYYYY.com
     N8N_LOG_LEVEL = warn
     N8N_PORT = 5678
     N8N_PROTOCOL = https
     N8N_PUSH_BACKEND = sse
     N8N_SMTP_HOST = FFFFFFFFFF
     N8N_SMTP_PASS = WWWWWWWW
     N8N_SMTP_PORT = 465
     N8N_SMTP_SENDER =QQQQQQQQ
     N8N_SMTP_SSL = true
     N8N_SMTP_USER = EEEEEEEEEEE
     N8N_USER_FOLDER = /n8n
     NODE_ENV = production
     NODE_FUNCTION_ALLOW_EXTERNAL = *
     TZ = America/Santiago
     WEBHOOK_URL = https://n8n.YYYYYYYYY
```

**Comment by pmoralesp** [comment]
> We are aware of this, and actively working on fixing and releasing a patch.

Thanks!

> Just out of curiousity: Are you running watchtower? or are you using the `next` tag in your setup?

Haha, I like to try the latest version available, so manually upgrade to every beta release published. Effectilly I am a kind of guardian of the watchtower 😅

**Comment by netroy** [comment]
@pmoralesp A fix just got released with 1.22.1. Can you please upgrade and try again?

**Comment by pmoralesp** [comment]
> @pmoralesp A fix just got released with 1.22.1. Can you please upgrade and try again?

Unable to pull image 1.22.1

```
[+] Building 0.4s (3/3) FINISHED                                                                                                                                                                                               docker:default
 => [n8n internal] load build definition from Dockerfile                                                                                                                                                                                 0.0s
 => => transferring dockerfile: 397B                                                                                                                                                                                                     0.0s
 => [n8n internal] load .dockerignore                                                                                                                                                                                                    0.0s
 => => transferring context: 113B                                                                                                                                                                                                        0.0s
 => ERROR [n8n internal] load metadata for docker.n8n.io/n8nio/n8n:1.22.1                                                                                                                                                                0.3s
------
 > [n8n internal] load metadata for docker.n8n.io/n8nio/n8n:1.22.1:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests 1.22.1]: 500 Internal Server Error

```

**Comment by netroy** [comment]
[The image is on docker hub](https://hub.docker.com/layers/n8nio/n8n/1.22.1/images/sha256-e84b0d7dd166216646799810a8cce843a221a50f5cc4dd2a67a09145c0576e70?context=explore). 

Maybe try to pull it [from GHCR](https://github.com/n8n-io/n8n/pkgs/container/n8n/160535257?tag=1.22.1): `docker pull ghcr.io/n8n-io/n8n:1.22.1`

**Comment by pmoralesp** [comment]
Upgraded and working like a charm! Thanks!
