### ISSUE TITLE
Switch Node routes differently when ran actively vs manually

### ISSUE THREAD

**Issue by nickmanente** [n8n-io/n8n#8149]
**Describe the bug**
I have a Switch node that is taking an input of a binary file that was downloaded from an HTTP request node before it. Value 1 is {{ $input.item.binary.data.fileExtension }} (in my test scenarios I was using an xlsx file). The Rules are as follows:

If it equals "png" => 1
If it equals "jpeg" => 1
If it doesn't equal "png" => 2

I even tried adding another condition to see if it would help:
If it equals "xlxs" => 2

The issue is when I'm manually executing the nodes - the data is routed just fine, when I run the workflow actively - the data is routing to output 1 when the file extension is an "xlsx". When I even go into debug mode of that exact execution of the workflow and re-run the switch node without changing anything, it changes it's output from 1 to 2. 

**To Reproduce**

1. Download a file using the HTTP request node (or really anything to generate a binary file as the output.
2. Have a Switch Node connected to that
3. Setup the rules I detailed about with the top options being "Mode: Rules" and "Data Type: String"
4. Run it manually to see it work right
5. Have it run automatically (like on a timed execution trigger) to see it route incorrectly. 

**Expected behavior**
The routing output will be different in manual executions vs active ones

**Environment (please complete the following information):**

- OS: Amazon Linux 2
- n8n Version: 1.20.0
- Node.js Version: 18.18.2
- Database system: PostGresql
- Operation mode: queue

**Additional context**
Very rarely the automatic runs would work as intended - but 90%+ of the time it would be wrong.

**Comment by Joffcom** [comment]
Hey @nickmanente,

I have just given this a quick test and I am not able to reproduce it using the example workflow below, Can you share a small workflow that reproduces the issue?

![image](https://github.com/n8n-io/n8n/assets/4688521/dc511e57-7ba0-4bf0-84f3-6cdba036f7f7)


```
{
  "meta": {
    "instanceId": "8c8c5237b8e37b006a7adce87f4369350c58e41f3ca9de16196d3197f69eabcd"
  },
  "nodes": [
    {
      "parameters": {},
      "id": "6a37d23f-a2a7-4039-881b-b25c8b0220cd",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        860,
        260
      ]
    },
    {
      "parameters": {
        "url": "https://images.unsplash.com/photo-1704128728168-21b9f1381c17?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "options": {}
      },
      "id": "efd4ca31-e208-4d6d-82f8-f936bb911591",
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1080,
        380
      ]
    },
    {
      "parameters": {
        "dataType": "string",
        "value1": "={{ $input.item.binary.data.fileExtension }}",
        "rules": {
          "rules": [
            {
              "value2": "png",
              "outputKey": "png"
            },
            {
              "value2": "jpeg",
              "outputKey": "jpeg"
            },
            {
              "operation": "notEqual",
              "value2": "png",
              "outputKey": "not png"
            }
          ]
        }
      },
      "id": "8ccf520a-6d3c-4dea-bdfc-16c87b962abf",
      "name": "Switch",
      "type": "n8n-nodes-base.switch",
      "typeVersion": 2,
      "position": [
        1280,
        380
      ]
    },
    {
      "parameters": {
        "rule": {
          "interval": [
            {
              "field": "seconds",
              "secondsInterval": 5
            }
          ]
        }
      },
      "id": "aaef5e83-b6fb-43d3-b595-42f726b0d083",
      "name": "Schedule Trigger",
      "type": "n8n-nodes-base.scheduleTrigger",
      "typeVersion": 1.1,
      "position": [
        860,
        500
      ]
    }
  ],
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "Switch",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Schedule Trigger": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}
```

**Comment by nickmanente** [comment]
I have a rather large workflow that this is happening on - I know just exporting the workflow will also export credentials right?

**Comment by nickmanente** [comment]
if it helps too - here's screenshots of an execution history where it sent an xlsx file down the png/jpeg pipeline 
![image](https://github.com/n8n-io/n8n/assets/128169872/5636b1dc-d1c1-4806-9cbf-e29d6d306599)
![image](https://github.com/n8n-io/n8n/assets/128169872/2a26a954-cd65-40ae-9761-d10cd47cb02c)

**Comment by nickmanente** [comment]
Please disregard - when changing around the values in testing - I didn't notice that the output wires got changed and I was sending the opposite values where they needed to go - user error here, apologies for wasting your time!

**Comment by Joffcom** [comment]
@nickmanente no worries it happens.
