### ISSUE TITLE
Missing VACUUM of SQLite3 database after deleting execution log

### ISSUE THREAD

**Issue by immanuelfodor** [n8n-io/n8n#819]
**Describe the bug**
After deleting lots of executions, the default SQLite3 database is not vacuum-ed, so it stays hundreds of MBs in size.

**To Reproduce**
1. Check the size of the `database.sqlite` file
2. Delete lots of execution logs
3. Check the size of the DB again
4. It's the same as before, no reduction in size

**Expected behavior**
The DB is vacuumed automatically or with a manual option after deleting all the execution logs.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - n8n Version: Docker 0.73.1 (#818)
 - Node.js Version: whatever in official Docker image

**Additional context**

Deleted 853 execution logs without any change in DB size, but running a single VACUUM reduced the 250 MB+ DB file to 77 KB:
```
sqlite> .tables
credentials_entity  execution_entity    migrations          workflow_entity   
sqlite> select count(*) from credentials_entity;
2
sqlite> select count(*) from execution_entity;
0
sqlite> select count(*) from migrations;
1
sqlite> select count(*) from workflow_entity;
8
sqlite> VACUUM;
```

DB sizes before and after manual vacuum of DB. 
```bash
ls -la 
total 488672
-rw-r--r-- 1 ubuntu root        56 Jan 26  2020 config
-rw-r--r-- 1 ubuntu root     77824 Aug  5 07:31 database.sqlite
-rw-r--r-- 1 ubuntu root 250191872 Aug  5 07:31 database.sqlite.bak
```

**Comment by immanuelfodor** [comment]
More info on VACUUM: https://www.sqlitetutorial.net/sqlite-vacuum/

**Comment by RicardoE105** [comment]
@immanuelfodor Sorry for the late response. We are a small team. I talked to the team today, and this would be a feature rather than a bug. Just added it to the backlog. we will let you know as soon as we have an update on this. Thanks for putting the issue together, it's really helpful.

**Comment by janober** [comment]
As it is blocking, can take quite a while and can double the size temporarily can we not run it automatically. But with n8n@0.101.0 it is now possible to set the environment variable `DB_SQLITE_VACUUM_ON_STARTUP=true`. It will then run vacuum automatically on startup.

**Comment by immanuelfodor** [comment]
Thank you, I'll try it!
