### ISSUE TITLE
InvoiceNinja Create Invoice 'Invoice Number' Doesn't Work

### ISSUE THREAD

**Issue by tomershvueli** [n8n-io/n8n#8191]
**Describe the bug**
When creating a new invoice with the Invoice Ninja node and a custom invoice number, the custom invoice number doesn't take. Instead, Invoice Ninja assigns the invoice with the default next number.

**To Reproduce**

1. Use the Invoice Ninja node to create a new Invoice
2. Under 'Additional Fields' add Invoice Number, and set it to something other than '0001', ie '1234'. 
3. Run the Node
4. Assert that the Invoice Ninja instance created a new invoice, but with a number of `0001`

**Expected behavior**
The invoice created should have the number passed to it via the node, ie `1234`

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.234.0
- Node.js Version [e.g. 18.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `main`]

**Additional context**
I believe the issue is that the API is sending the Invoice Number parameter through as `invoiceNumber`, whereas the [API docs](https://api-docs.invoicing.co/#post-/api/v1/invoices) specify it should be simply `number`.

**Comment by Joffcom** [comment]
Hey @tomershvueli,

Thanks for raising this one, I have popped in a PR which should fix it for a future release. For now I am going to mark this one as closed and I will pop a note back on here once we have released the fix this will mean you will need to update from `0.234.0` soon so it may be worth starting to plan that and checking the migration guide for anything that has changed.

**Comment by tomershvueli** [comment]
Got it, thanks for the quick turnaround!

**Comment by Joffcom** [comment]
Fix got released with [`n8n@1.23.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.23.0)
