### ISSUE TITLE
Quickchart does not work

### ISSUE THREAD

**Issue by pyromiko** [n8n-io/n8n#8193]
Hello, i try to use Quickchart node, but i think is not working at all. Im just check the example and even that is not working. I try to use different values and method...

**To Reproduce**
Add Quickchart node and try to do the simple example (without any connection).
**Expected behavior**
It should graph the values

<img width="627" alt="image" src="https://github.com/n8n-io/n8n/assets/35033939/5f0b100f-7f9c-4e2a-86c2-d359d32de6ff">

**Environment (please complete the following information):**

- OS: debian12 (cosmos server)
- n8n Version 1.20.0 from docker

**Comment by Joffcom** [comment]
Hey @pyromiko,

If you are passing in 3 labels you would also need to pass in 3 arrays containing the data you are using so your data expression would need to be something like `{{ [ [60,10,12], [1,2,3], [4,5,6] ] }}`

This isn't the easiest node to use though and it works best with nodes connecting to it, We do have an example workflow for using this node in our test folder which you can find here: https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/QuickChart/test/QuickChart.workflow.json but we should probably either make the node easier to use or provide more docs / examples on how to to use it.

Let me know how you get on with the example.

**Comment by pyromiko** [comment]
excellent, it works, thank you for the example! i will try to start to learn or play with that.

best regards and happy new year.
