### ISSUE TITLE
Workflow Execution Issue in n8n Version 1.21.1

### ISSUE THREAD

**Issue by Caretek1** [n8n-io/n8n#8217]
Dear n8n GitHub Team,

I am writing to report a critical issue we've encountered with n8n following an update to version 1.21.1. This issue affects the workflow execution functionality and is consistent across multiple instances running in Docker containers.

Self Hosted through Cloudron

Issue Details:

Version Affected: 1.21.1
Symptom: Both automatic and manual workflow executions fail to run post-update.
Environment: The issue has been observed in 4 separate n8n instances running as Docker containers.
After updating to version 1.21.1, we noticed that neither automatic nor manual workflow executions were functioning as expected. This was consistent across all our instances. To confirm that the issue was specific to the update, we reverted back to the previous version of n8n. Post-reversion, the workflow executions returned to normal functionality.

I believe this could be a bug introduced in the latest version and thought it crucial to bring it to your attention for further investigation. If there are any additional details or diagnostic information you require, I am happy to provide them.

Thank you for your attention to this matter. We rely heavily on n8n for our workflow automations and are keen to update to the latest version once this issue is resolved.

Best regards,

**Comment by mbrother2** [comment]
Hi @Caretek1,

You said: "I believe this could be a bug introduced in the latest version and thought it crucial to bring it to your attention for further investigation" and what is the bug?

**Comment by Joffcom** [comment]
Hey @Caretek1,

Thanks for the report, I have just checked on the 2 releases we did recently (1.23.0 and 1.22.4) and I am not able to reproduce this. 

If your workflows are using scheduled triggers can you try updating to `1.22.4` and see if that resolves the issue.

**Comment by Caretek1** [comment]
I have a self host container through cloudron and they dont provide pre releases so once they provide us 1.22.4 i will check. I reverted back to previous version

**Comment by Joffcom** [comment]
Hey @Caretek1,

Have Cloudron updated their side yet?

**Comment by gramakri** [comment]
@Joffcom yes, it's been updated from Cloudron side.

**Comment by Joffcom** [comment]
@gramakri that is good news, Out of interest where do you pull the versions to use from? Do you add our releases as they happen or just follow the latest branch on Docker?

@Caretek1 if you could update and let us know if the issue is resolved it would be a big help.

**Comment by gramakri** [comment]
@Joffcom sure! We track the releases at https://github.com/n8n-io/n8n/releases . We have our own Dockerfile since we have some restrictions on how the app is packages (for example, we deploy containers as readonly filesystem) . The package code is at https://git.cloudron.io/cloudron/n8n-app . We have made over 200 package releases, thanks for the great app!

**Comment by Caretek1** [comment]
> @gramakri that is good news, Out of interest where do you pull the versions to use from? Do you add our releases as they happen or just follow the latest branch on Docker?
> 
> @Caretek1 if you could update and let us know if the issue is resolved it would be a big help.

Hi I confirmed the issue is resolved with 1.22.4
