### ISSUE TITLE
Import Error for @n8n/chat

### ISSUE THREAD

**Issue by artushin** [n8n-io/n8n#8218]
**Describe the bug**
Import of @n8n/chat fails with the following error when using the boilerplate example setup.

```
src/App.vue:5:28 - error TS7016: Could not find a declaration file for module '@n8n/chat'. '/Users/artushin/src/github.com/n8n-io/n8n/packages/@n8n/chat/dist/chat.es.js' implicitly has an 'any' type.
  There are types at '/Users/artushin/src/github.com/artushin/home/frank-chat/node_modules/@n8n/chat/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@n8n/chat' library may need to update its package.json or typings.
```

**To Reproduce**

1. Setup a new vite project (use typescript and vue)
2. Update code as per example instructions
3. Run `npm run build` in the example project

**Expected behavior**
Build succeeds

**Environment (please complete the following information):**

- OS: Mac OSX
- n8n Version @n8n/chat 0.6.0
- Node.js Version v20.10.0

**Additional context**
Pretty sure you just don't need the exports section in the dist/package.json.

**Comment by Joffcom** [comment]
Hey @artushin,

Can you share an example project that reproduces this issue?

**Comment by artushin** [comment]
Hey @Joffcom,

Try this one: https://github.com/artushin/frank-chat

**Comment by Joffcom** [comment]
Hey @artushin,

Perfect thanks, Not sure what is going on there but I have created a dev ticket so someone can look into it. We are tracking the issue internally as `ADO-1650`, For now I know that some folk have had sucess directly using the cdn to add the chat widget to their sites so that could be an option for you.

**Comment by artushin** [comment]
@Joffcom , np, thanks for looking, I'm just building from source for now.
