### ISSUE TITLE
Expression for Max Pages in Pagination option causing loop

### ISSUE THREAD

**Issue by mokkin** [n8n-io/n8n#8221]
**Describe the bug**
In the max pages setting of the pagination option at HTTP nodes expressions are accepted, but not executed in the correct way and causing a loop / endless running node.
If I set the same value (in the example `25`) as a fixed value it is working.

**To Reproduce**

1. Go to HTTP node
2. add pagination
3. set pagination max pages to an expression
4. execute and see error

**Expected behavior**
Execution should create the same result like for fixed value.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- n8n Version: 1.21.1
- Node.js Version: default
- Database system: default
- Operation mode: default

**Additional context**
![grafik](https://github.com/n8n-io/n8n/assets/2938748/ba7b31de-86ed-4b20-bb9e-4f2691cbd54b)

**Comment by mbrother2** [comment]
Hi @mokkin,
Is your variable's type `{{ $json.numberOfPages }}` an integer or a string? Could you try with  `{{ parseInt($json.numberOfPages) }}` ?

**Comment by Joffcom** [comment]
@mokkin is suspect @mbrother2 is correct and your numberOfPages is a string or a higher value.

**Comment by mokkin** [comment]
Your're right. I wasn't aware that the delivered number wasn't an integer...

Thank you for your hint. Meanwhile I got it working differently:

![grafik](https://github.com/n8n-io/n8n/assets/2938748/b81bce7f-adb1-4f32-95fe-17bb7c1a198b)

**Comment by Joffcom** [comment]
Hey @mokkin,

Perfect in that case I am going to mark this one as closed for now.
