### ISSUE TITLE
why is `insecure_ssl` set to `true` ?

### ISSUE THREAD

**Issue by ThibaudLopez** [n8n-io/n8n#8263]
Why is `insecure_ssl` set to `true` here?
https://github.com/n8n-io/n8n/blob/3b996a7da0137a75c3047656a4bc8cc336ebfc1e/packages/nodes-base/nodes/Github/GithubTrigger.node.ts#L498

That allows insecure TLS connections, e.g. man-in-the-middle attacks. That's a potential security vulnerability.

**Comment by netroy** [comment]
Thanks for catching this. It looks like this line was part of the initial commit 5 years ago, and might have been meant for debugging, and we forgot to remove the line.
We'll ping the relevant folks, and get this addressed ASAP.
