### ISSUE TITLE
404 error on GitLab Node when fetching a project

### ISSUE THREAD

**Issue by Zacharieg** [n8n-io/n8n#8279]
Hi devs, thank you for your hard work ! I believe I found a bug on the GitLab Node, when using a custom Gitlab instance.

**Describe the bug**
I'm using a self hosted n8n instance and wanted to connect it to a custom GitLab installation. I have a repository called `support` and a group also called `support`, which is hosted on a GitLab installation that has a name like "https://my-domain.com/gitlab".
When I want to fetch issues or information of this repository with the GitLab Node, I get this error :

![image](https://github.com/n8n-io/n8n/assets/58566495/38526fe0-592a-43f1-903f-49a229a9fa77)

**To Reproduce**
Add the gitlab node "Get a repository", fill the infos

**Expected behavior**
Display project information

**Environment (please complete the following information):**

- OS: Docker, on Debian 12
- n8n Version : 1.21.1
- Node.js : v20.10.0
- Database system: SQLite
- Operation mode: main
- GitLab version : GitLab Enterprise Edition [v16.3.6]

**Additional context**

- The credentials are correct, I get the "Connection tested successfully" message in the credentials section on n8n
- I can access the repository and the group with the gitlab interface AND with the api with the api point : `api/v4/groups/:group_id:` and `api/v4/projects/:project_id:`
- I'm using the NODE_TLS_REJECT_UNAUTHORIZED=0 because the certificates of the gitlab instance are not correctly set
- This is a big gitlab instance, with more than 100 groups
- Some gitlab nodes works, like the Get repositories from users

Full error : 
```
NodeApiError: The resource you are requesting could not be found
    at Object.gitlabApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Gitlab/GenericFunctions.js:34:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Gitlab/Gitlab.node.js:1456:36)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:696:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:656:53
```

**Comment by Joffcom** [comment]
Hey @Zacharieg,

That looks like Gitlab is returning the 404 to say the url is incorrect, This typically means that the Project owner or Project name is incorrect.

The URL we will be trying to access will be something like the below, Can you check that this exists?

`https://my-domain.com/gitlab/api/v4/projects/supports%2fsupports`

**Comment by Zacharieg** [comment]
Hey @Joffcom, thanks for your reactivity ! Yes it exists... 

But I got a lead, I think n8n forget the `gitlab/` and try to access `https://my-domain.com/api/v4/projects/supports%2fsupports`. It seems like the html result is not sent by gitlab because it look like this :
`<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n</body></html>\n" - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL was not found on this server.</p></body></html>`

I have found this in the n8n api call when I test the node (in the description field).

**Comment by Joffcom** [comment]
Hey @Zacharieg 

That is interesting it looks like we just append the value to the end of whatever domain is given in the credential.

Unless maybe the regex to remove any trailing slash is a bit over the top, I will test that in the morning it could be a quick fix if that is the case.

**Comment by Zacharieg** [comment]
Hello @Joffcom, I verified with Wireshark and the correct api point is pointed, but the server return a bad result. So it seems that it's not a n8n issue. (a bad result that I have not when typing the exact adress in Firefox)
I forgot to mentionned that I am behind a heavy proxy that block request by User Agent, and it may be the problem. 
I just don't understand why it works with other api calls, and not this one...

Maybe it's the "supports%2Fsupports" that is blocked by my proxy ?

Sorry to have taken up your time

**Comment by Joffcom** [comment]
Hey @Zacharieg,

That is good to hear I was about to dig into this a bit more. The `%2F` could be the issue I guess checking the logs may help, GitLab document it as the correct approach here: https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding

I guess if the authentication test is successful it is probably not the user agent 🤔

**Comment by Zacharieg** [comment]
@Joffcom I got the problem !

It is not the User Agent, it's simply that n8n use http and not https when enabling NODE_TLS_REJECT_UNAUTHORIZED, and the server does not accept http...
So I guess the solution would be to add a "ignore ssl issues" checkbox on the GitLab node (I added the option to get rid of self signed certificate problem), like it exists on other nodes.

**Comment by Zacharieg** [comment]
Ok, my bad, it's on me, I had set the url in http. So no problem in n8n.
Thank you so much to have helped me ! 
But I still think that the ignore ssl issue checkbox is a good idea, it was really hard to find the NODE_TLS_REJECT_UNAUTHORIZED environment variable.
