### ISSUE TITLE
error:1C800064:Provider routines::bad decrypt after update from 1.15.2

### ISSUE THREAD

**Issue by TauTauBenn** [n8n-io/n8n#8287]
I'm using n8n via the official Docker Container but when i try to update from 1.15.2 to any newer version i get the error:

"error:1C800064:Provider routines::bad decrypt" and credentials can not be loaded anymore.

The Encryption Key is set via Environment variable but i also checked the config file and it contains the same Encryption key.

After downgrading it works again. Is there any restriction to the Encryption Key as mine has 20 chars with special characters.

**Comment by TauTauBenn** [comment]
Hi @Joffcom 

i deployed n8n using Azure App Services. I configured the config folder to be "/home/node/n8n" and mounted this to a file share in Azure where the files are then located. Did not change anything on that after the update and before it is working without any problem. Already tried deleting the files etc.

**Comment by Joffcom** [comment]
Hey @TauTauBenn,

Can you double check that path? It should be `/home/node/.n8n`. Can you also share the config values you have set? In theory even if the path is wrong and it is `n8n` instead of `.n8n` we should still use the env option but some platforms may parse the env options in a different way.

**Comment by TauTauBenn** [comment]
yes i had to change it to "/home/node/n8n" via "N8N_USER_FOLDER" without . because azure is not allowing the dot. but n8n is definitely accessing the right folder and creating .cache and .n8n with config etc. in it if i delete the files. 
![image](https://github.com/n8n-io/n8n/assets/85042590/00bb9a15-5897-4b58-b519-7a39cca3efb8)


I attached a screenshot of the ENV variables.
![image](https://github.com/n8n-io/n8n/assets/85042590/5822c4ca-1b14-456a-8b3c-21cc28d85436)

**Comment by Joffcom** [comment]
Hey @TauTauBenn,

I wasn't expecting the `N8N_USER_FOLDER` setting to be there this is why it is handy to see the config. The settings you have other than the one option look to be fine and don't look that different to what I am using. I am not sure why Azure wouldn't allow that path as it is an option in the container so they shouldn't care 🤔 

Can you share the command that is being used to launch the container? I can then see if I am able to reproduce this.

**Comment by Joffcom** [comment]
Hey @TauTauBenn,

Is that the complete command I can't see where it is actually mounting the files or setting the env option for the key unless they were just removed.

One other thing I forgot to ask... What special characters are in your key?

**Comment by TauTauBenn** [comment]
At least this is what Azure shows me in the logs... maybe it removes the ENV variables and mounting points from the log. 

Special Characters are: _ + $ § , ! > ( # &

**Comment by netroy** [comment]
Can you please check once more that the value for the encryption key in `/home/node/.n8n/config` (and not `/home/node/n8n/config`) is identical to the value passed in via env variables in `1.15.2` as well as in one of the later versions.

My theory is that something somewhere is messing up the encryption key value before it's loaded into memory.

**Comment by TauTauBenn** [comment]
Yes it's definitely the same and even if i delete the config file it just creates a new one with exact the same key. If i start it without the ENV variable and only with the one from the config it is giving me the exact same error.

**Comment by netroy** [comment]
@TauTauBenn was this resolved for you?

**Comment by tqjason** [comment]
Provider routines::bad decrypt , it still there for v1.58.0 when rest/mfa/qr

**Comment by netroy** [comment]
@tqjason is this happening only on the MFA endpoint? or also on regular credentials?

**Comment by tqjason** [comment]
just happening on page /settings/personal and `Enable 2FA`.
popup message 'Could not check if an api key already exists.
error:1C800064:Provider routines::bad decrypt'

**Comment by tqjason** [comment]
Problem sovled. clean mfa from database `database.sqlite` using `update user set mfaSecret=null, mfaRecoveryCodes=null where email="xxxx"`
problem happend because I've changed encryptionKey in config file once
