### ISSUE TITLE
Custom - LLM Chain Node is broken

### ISSUE THREAD

**Issue by ed-parsadanyan** [n8n-io/n8n#8307]
**Describe the bug**
Hello everyone. I was trying this workflow template and it seems that the LLM Node with custom JS code is broken:
[https://n8n.io/workflows/1955-custom-langchain-agent-written-in-javascript/](https://n8n.io/workflows/1955-custom-langchain-agent-written-in-javascript/)

I tried updating the env variable, but without success. In my setup I already have some npm libs:
`NODE_FUNCTION_ALLOW_EXTERNAL=luxon,pdf-image,minify,easy-template-x,pca-js,langchain/prompts`

**To Reproduce**

1. Get the workflow example
2. Paste into the editor
3. Setup OpenAI node (no other changes were done). Click Execute Workflow
4.a See error for the upper branch ERROR: Cannot find module 'langchain/prompts' [line 1]
4.b See error for the lower branch ERROR: Cannot find module 'langchain/tools' [line 2]

**Expected behavior**
Workflow completed without errors

**Environment (please complete the following information):**
- OS: Ubuntu Linux 22.04
- n8n Version 1.22.6
- Node.js Version NA, Docker version
- Database system PostgreSQL
- Operation mode main

**Comment by Joffcom** [comment]
Hey @ed-parsadanyan,

You may have noticed but we are currently testing the PR and should have this fixed soon, Thanks for raising this 🙌🏻
