### ISSUE TITLE
Error: The module '/usr/local/lib/node_modules/n8n/node_modules/mmmagic/build/Release/magic.node

### ISSUE THREAD

**Issue by zz940522** [n8n-io/n8n#84]
Error: The module '/usr/local/lib/node_modules/n8n/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/mmmagic/lib/index.js:1:75)

**Comment by janober** [comment]
Very sorry but to be able to help you additional information is needed. Like what are you trying to do? What did you do until now? What OS, node.js version are you using?

But looking at the error message it seems like an error that has nothing to do with n8n at all. Maybe really simply try what it says. Best blow away the "node_modules" folders and then run `npm install`.

**Comment by zz940522** [comment]
os:CentOS Linux release 7.6.1810 (Core)
I run n8n start,it prints this error.
I try node version 8.11.3,10.16.3and12.12.0,when i try run npm install magic,it prints "node-waf:command not found".

**Comment by zz940522** [comment]
> Very sorry but to be able to help you additional information is needed. Like what are you trying to do? What did you do until now? What OS, node.js version are you using?
> 
> But looking at the error message it seems like an error that has nothing to do with n8n at all. Maybe really simply try what it says. Best blow away the "node_modules" folders and then run `npm install`.

but now,n8n is started,i just wanna cry.I used one day to install this one,oh my god,Jesus Christ

**Comment by janober** [comment]
Uh wow, normally it should just take a few minutes. 

So then I guess the error makes sense. You probably did the `npm install` with Node.js v8 and there it did not work. Then you tried to start with other versions without removing the "node_modules" folder.  So then the module got build with a different version than now started and therefore the error.

**Comment by janober** [comment]
Btw. it is normally always best to run Node.js applications with the current or LTS version to avoid problems unless stated differently.

**Comment by zz940522** [comment]
> Uh wow, normally it should just take a few minutes.
> 
> So then I guess the error makes sense. You probably did the `npm install` with Node.js v8 and there it did not work. Then you tried to start with other versions without removing the "node_modules" folder. So then the module got build with a different version than now started and therefore the error.

I have a lacal machine and the os is deepin,now i should try which version of nodejs?

**Comment by janober** [comment]
The one you prefer. Either 10 or 12. Both should work fine.

**Comment by zz940522** [comment]
> The one you prefer. Either 10 or 12. Both should work fine.

Ok,thank you,let me try

**Comment by zz940522** [comment]
> Great, if you have problems simply get back to me.
> 
> But normally should the installation with that versions be very simple and fast. Apart from that can I also recommend Docker as that is always the easiest to get something up and running.

/usr/local/bin/n8n -> /usr/local/lib/node_modules/n8n/bin/n8n

> mmmagic@0.5.3 install /usr/local/lib/node_modules/n8n/node_modules/mmmagic
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/n8n/node_modules/mmmagic/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/n8n/node_modules/mmmagic/.node-gyp'
gyp ERR! System Linux 4.15.0-30deepin-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/n8n/node_modules/mmmagic
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mmmagic@0.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mmmagic@0.5.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-17T09_30_43_262Z-debug.log

**Comment by zz940522** [comment]
> Great, if you have problems simply get back to me.
> 
> But normally should the installation with that versions be very simple and fast. Apart from that can I also recommend Docker as that is always the easiest to get something up and running.

I'm sorry to bother you,i have kill the truble with npm install n8n -g --unsafe-perm,and install n8n need 
make,gcc,gcc-c++

**Comment by janober** [comment]
hm sadly not related to n8n so can not be much of a help. It seems to have to do with access rights on your system. Even though I do not understand why the "root" user (which normally has the right to do everything) does not have the right to write to his own home-folder. Anyway, I would look on Google or similar for the error message you are getting.

**Comment by zz940522** [comment]
> hm sadly not related to n8n so can not be much of a help. It seems to have to do with access rights on your system. Even though I do not understand why the "root" user (which normally has the right to do everything) does not have the right to write to his own home-folder. Anyway, I would look on Google or similar for the error message you are getting.

Do you have see my another reply,n8n works.Thanks you!

**Comment by zz940522** [comment]
> hm sadly not related to n8n so can not be much of a help. It seems to have to do with access rights on your system. Even though I do not understand why the "root" user (which normally has the right to do everything) does not have the right to write to his own home-folder. Anyway, I would look on Google or similar for the error message you are getting.

![微信图片_20191017175538](https://user-images.githubusercontent.com/33046965/66998760-64d11580-f107-11e9-8383-e1f309f0fe72.png)

**Comment by janober** [comment]
Yes, it would make sense that if you install as "root" (which is normally not recommended) you need the --unsafe-perm.
The dependencies are required for normally almost all the node.js applications. Here also some information in the CONTRIBUTING guide:
https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#requirements

Ah great. It looks like you got it up and running.

**Comment by zz940522** [comment]
> Yes, it would make sense that if you install as "root" (which is normally not recommended) you need the --unsafe-perm.
> The dependencies are required for normally almost all the node.js applications. Here also some information in the CONTRIBUTING guide:
> https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md#requirements
> 
> Ah great. It looks like you got it up and running.

Congratulation!

**Comment by janober** [comment]
Great that it works now. Close this issue. Have a great day!

**Comment by sutidor** [comment]
I solved this with
npm config set scripts-prepend-node-path true

**Comment by nikukyugamer** [comment]
I solved as below.

First, `$ pm2 logs` is here (I execute n8n with `pm2`).

```
/home/ubuntu/.pm2/logs/n8n-error.log last 15 lines:
0|n8n      |     NODE_MODULE_VERSION 83. This version of Node.js requires
0|n8n      |     NODE_MODULE_VERSION 79. Please try re-compiling or re-installing
0|n8n      |     the module (for instance, using `npm rebuild` or `npm install`).
```

So I searched Node.js using `NODE_MODULE_VERSION 79`.
https://nodejs.org/en/download/releases/

The latest Node.js version using `NODE_MODULE_VERSION 79` is `Node.js 13.14.0` currently.
So I changed Node.js version to `13.14.0` and re-install `n8n` (remove a lock file, node_modules directory and install packages).

After that, `$ pm2 start n8n`. All fine.
