### ISSUE TITLE
Functional Item does not seem to receive binary data nor send it along to the next node

### ISSUE THREAD

**Issue by pcross616** [n8n-io/n8n#840]
Been trying to implement a clean up step after receiving and email with an attachment.  I have it fully functional without a Function Item.

This works:

![Screen Shot 2020-08-14 at 10 01 37 AM](https://user-images.githubusercontent.com/141865/90274616-c3dde480-de15-11ea-9ccd-d00f89a86ccc.png)

Once I add a basic step to parse the email domain from the item properties. I don't see binary data being passed in nor is it available on any node past the Functional Item.

Does not work:
![Screen Shot 2020-08-14 at 10 07 46 AM](https://user-images.githubusercontent.com/141865/90274790-099aad00-de16-11ea-9838-c42c05d51842.png)

This could very well be user error and not done correctly, but I have searched documentation and community forums and everything seems that this should work.  I have looked in to setBinaryData and getBinaryData but nothing I did seem to make a different.

Any help or guidance would be great.

**To Reproduce**
1. Add an IMAP Email Read node + configure to pull email and download attachment
2. Add Functional Item
_Note: sorry the regex messed with the code snippet option in the issue. _

var reg = /[a-z0-9!#$%&'*+\/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+\/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/
var email = reg.exec(item.from);
var domain = /@(\w+)/.exec(email)[1];
item.vendor = domain;
return item;

3. Add SFTP node + configure to upload to server using binary data
_Note: I see the updated item properties in the SFTP node with the vendor and no errors are reported in the Functional Item _
4. See error on SFTP node
`ERROR: No binary data property "attachment_0 " does not exists on item!
Error: No binary data property "attachment_0  " does not exists on item!
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Ftp.node.js:284:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:369:47`

**Expected behavior**
I would expect the binary data be available in the node downstream from Function Item just like if it was not there in the working example

**Environment (please complete the following information):**
 - Using Docker - n8nio/n8n

**Comment by janober** [comment]
Thanks a lot for making us aware of the problem @pcross616!

Sorry about that! Just fixed the bug and will release it with the next version. I will inform you here once it got released.

**Comment by janober** [comment]
Btw. as a workaround it is best to use the Function-Node instead.

**Comment by pcross616** [comment]
Thanks was just looking in to that as a next option.  Love the simple fixes, I thought it might have been that but didn't know the code well enough yet to ensure that was it.

**Comment by janober** [comment]
You are welcome! Yes was very easy to fix. Was a simple oversight when I originally programmed the node.

**Comment by janober** [comment]
Got released with n8n@0.78.0
