### ISSUE TITLE
Node Version not Supporte

### ISSUE THREAD

**Issue by PierrunoYT** [n8n-io/n8n#8402]
Your Node.js version (21.6.0) is currently not supported by n8n.
        Please use Node.js v18 (recommended), or v20 instead!

**Comment by Joffcom** [comment]
Hey @PierrunoYT 

We currently only support node 18 with limited support for 20, I am not sure there is really a bug here as the correct version of node would be a requirement.

If you are unable to use node 18 or 20 I would recommend using the docker image, for now I am going to mark this as closed as there is nothing for us to do at the moment.

**Comment by PierrunoYT** [comment]
okay
