### ISSUE TITLE
wrong favicon.ico href

### ISSUE THREAD

**Issue by mecurc** [n8n-io/n8n#841]
**Describe the bug**

**To Reproduce**
1. `npx n8n`
2. Go to `http://localhost:5678/`
3. Open Chrome Developer Tools Console
4. Favicon is missiong and console shows an errors:
<img width="1421" alt="Screenshot 2020-08-14 at 22 09 58" src="https://user-images.githubusercontent.com/33278950/90284965-988de080-de7b-11ea-9939-46626b096848.png">

**Expected behavior**

**Environment (please complete the following information):**
 - n8n Version 0.76.0
 - Node.js Version v12.18.3

**Additional context**

**Comment by janober** [comment]
Thanks a lot for making us aware of that @mecurc!

The bug got fixed and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.78.0

**Comment by mecurc** [comment]
Amazing! Thank you for letting me know.

**Comment by janober** [comment]
Sure, have a nice day!
