### ISSUE TITLE
The Node Telegram Trigger does not receive information when in Queue

### ISSUE THREAD

**Issue by dubcom** [n8n-io/n8n#8414]
Describe the bug

**The Node Telegram Trigger does not receive information when in Queue.**

If in Regular mode, Receive in Production and in Test mode
If it is in Queue mode, it receives it in the Production Webhook but does not receive it in Test mode
When we press the execute button to set the workflow to run in manual mode, the production address of the webhook (/webhook) is registered in Telegram, whereas the correct one would be to register the test address (/webhook-test).

This only happens in queue mode and if the n8n is configured with 2 addresses, one on N8N_EDITOR_BASE_URL and one for the webhook on WEBHOOK_URL.

**To Reproduce**

Set up a New Bot in Telegram
Configure the Telegram Trigger
Send a message to Bot
Message is not received
Expected behavior

Environment (please complete the following information):

OS: Docker
**n8n Version 1.24.1**
Node.js Version [e.g. 16.17.0]
Database system Postgres
Operation mode queue
Additional context

**Comment by Joffcom** [comment]
Hey @dubcom,

I think we had a report of this before, if you disable the active webhook then try a test does it work?

**Comment by Joffcom** [comment]
Closing for now until we have more information.
