### ISSUE TITLE
Unable to use Supabase node (unsupported Postgres connection options + unable to specify Supabase schema)

### ISSUE THREAD

**Issue by JavierCane** [n8n-io/n8n#8460]
# Description

## Why it is now needed to specify connection options for Supabase

[Supabase announced PGBouncer and IPv4 Deprecation](https://github.com/orgs/supabase/discussions/17817) with deadline set for today, 26th January 2024.

This means **you can not longer connect** to the Postgres server using connection parameters based on the connection string such as:
```
postgresql://${DB_USER}:${DB_PASSWORD}@db.${PROJECT_ID}.supabase.co:${DB_PORT}/${DB_NAME}
```

The new connection strings specifies the **`${PROJECT_ID}` as a connection option**:
```
postgres://${DB_USER}:${DB_PASSWORD}@aws-${DB_REGION}.pooler.supabase.com:${DB_PORT}/${DB_NAME}?options=reference%3D${PROJECT_ID}
```

## Current options in n8n

In order to connect to Supabase right now n8n offers 2 alternatives:

- Postgres credentials using Connection options
- Supabase credentials using Service role key

### Postgres credentials limitations

Right now you can not specify connection options such as `reference=${PROJECT_ID}` because there is not such input field while configuring it:

![Postgres credential edit page](https://github.com/n8n-io/n8n/assets/986235/c08f1019-9f1f-45c4-a261-6834c82e7eeb)

If you try to connect without specifying that parameter, it returns a `Tenant or user not found` error as expected.

However, taking a look at Supabase Connection parameters section, you can see that the `${PROJECT_ID}` is also specified in the `User` parameter:

![Connection parameters section](https://github.com/n8n-io/n8n/assets/986235/a457bbae-344e-4575-8281-ebe2e4298c94)

And in fact, if you choose other options such as JDBC to see the Connection string, the `${PROJECT_ID}` is only specified as part of the `user` parameter:

```
jdbc:postgresql://aws-${DB_REGION}.pooler.supabase.com:${DB_PORT}/${DB_NAME}?user=${DB_USER}.${PROJECT_ID}&password=${DB_PASSWORD}
```

Based on that, I have also tried to specify `${DB_USER}.${PROJECT_ID}` in the n8n credentials. In this case it seems like an advancement because it returns a different error, specifically `Wrong password`. I have verified that I was using the proper password, so it seems possible that this has to be more with how n8n handles the connection error and translate it to an error message.

**Conclusions**:

- You can no longer connect to Supabase using the Postgres credentials. You have to migrate ASAP all your workflows that use Postgres credentials in order to continue being able to connect to Supabase.
- This is a pity because there are some scenarios where a user would prefer to use Postgres nodes instead of the Supabase ones because it:
  - Allows to use a different schema rather than the default `public` one (see "Supabase credentials limitations")
  - Allows to migrate from Supabase to another Postgres server without having to modify all the workflows that uses Supabase

### Supabase credentials limitations

Having discarded the alternative of continue using the Postres nodes, lets see what we can do with the Supabase ones despite having to assume the caveats described in the previous conclusions.

In that case, we will be able to connect to Supabase because the integration uses the Service Role Secret:

![Supabase credential edit page](https://github.com/n8n-io/n8n/assets/986235/dacd011a-eb12-4e7e-a889-dbf8c9af2b51)

However, the limitation you will face has to be with the fact that the Supabase nodes does not support to specify the schema you want to interact with. If you have distributed the tables of a Supabase project (Postgres database) with different schemas, you will only be able to interact with tables in the `public` schema:

![Supabase node config](https://github.com/n8n-io/n8n/assets/986235/ec8ed548-045e-4bab-a1f6-5a1e543a641d)

I have tried specifying the table including the schema in a literal expression in order to be able to not be limited to the tables listed by the node, but it always prefixes the specified table with the `public` schema:

![Error while specifying the schema in the table field](https://github.com/n8n-io/n8n/assets/986235/6e68456c-5ad6-43f1-8685-315582391d00)

**Conclusion**: You can not interact with tables in schemas other than the `public` one.

# Possible solutions

As far as I understand the problem, this could be solved in two different ways:

- Add support for Postgres connection options
- Add support for specifying the schema in Supabase nodes

Is this something you would consider working on?

Thanks

**Comment by Joffcom** [comment]
Hey @JavierCane,

Just to clarify so I can work this out quickly... Is there actually an issue with the supabase node itself which connects to Supabase using the rest API they provide or is this more of a feature request to have options added to the postgres node?

**Comment by JavierCane** [comment]
Hi @Joffcom!

Right now you can successfully connect using the  Supabase node. The problem is that Supabase nodes only support interacting with tables in the default `public` database schema, so if you have other schemas in the Supabase Postgres database, you can not interact with them.

In order to interact with these tables you can connect using the Postgres nodes and credentials. The problem is that Supabase is shutting down today the only way to connect to Postgres without specifying connection options, so you can not use this approach either.

The solution as far as I understand the problem would be to allow to specify connection options in the Postgres credentials in order to continue being able to connect to Supabase database without having to replace all the current Postgres nodes.

Alternatively, another solution would be adding the schema option to the Supabase nodes in order to allow interacting with tables outside the default `public` one.

**Comment by Joffcom** [comment]
Hey @JavierCane,

So this sounds like you have 2 feature requests and this isn't a bug report.

In supabase have you already configured your schemas under exposed schemas in the api settings?

Looking at the supabase docs the Postgres node as it is should also be able to connect to the new service without issue.

I would however recommend opening a feature request on the community support forum as we only use GitHub for tracking bugs and I don't believe this counts.

Even though I am closing this I am still happy to chat about it and we can keep an eye on the amount of votes that come in from the community for the new features.

**Comment by JavierCane** [comment]
Hi @Joffcom,

Yes, I have the schema added in the Exposed schemas API settings. However, even if I expose it through the Supabase API, the Supabase n8n node does not allow to specify the schema you want to interact with as shown in the initial screenshots:
 
> ![Supabase node config](https://private-user-images.githubusercontent.com/986235/299992964-ec8ed548-045e-4bab-a1f6-5a1e543a641d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODEwNDMsIm5iZiI6MTcwNjI4MDc0MywicGF0aCI6Ii85ODYyMzUvMjk5OTkyOTY0LWVjOGVkNTQ4LTA0NWUtNGJhYi1hMWY2LTVhMWU1NDNhNjQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNDUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTlkYmMzYjY0NTA5YTlkODBkYTY0ODQ1ZDM3MTYxZjM1MDM3MmJiMDY3MzZmYWMyYmRhNmZjNjI3NTBiNWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XG9mBOgDsQHwk_nBlIJraUg5xF0sD5_oJMoLdFQOfCk)

As per your comment:

> Looking at the supabase docs the Postgres node as it is should also be able to connect to the new service without issue.

I have tried to do so with different approaches as explained in my first post, that is, appending the project ID to the username, but it always returns an error :/

I will fork the n8n repo and try to implement Postgres connection options because I do not see any other solution in order to avoid loosing access between n8n and Supabase right now 😅

**Comment by Joffcom** [comment]
Hey @JavierCane,

I have just given it a go and while I am not able to use a different schema in the node at the moment I can use a different schema in the Postgres node.

![image](https://github.com/n8n-io/n8n/assets/4688521/80271448-0f37-45e5-8470-a9d02a60398a)

I have not done anything special to do this, In supabase I went to my database settings and just copied the information from here...
![image](https://github.com/n8n-io/n8n/assets/4688521/a5fd4dc7-468f-4867-8d83-81804e810914)

into the credentials for my database

**Comment by JavierCane** [comment]
Thanks @Joffcom. It has to be something with my Supabase account/password/I don't know. I have tried out connecting via CLI with `psql` and it also throws me the "Wrong password" error. So in conclusion, it has nothing to do with n8n.

Just for the sake of completeness in case this help any other user with problems connecting from n8n to Supabase in the upcoming days after the deprecation: 

I know this seems a little bit silly because… "why can not the password be actually wrong?". The counter-example which would demonstrate that this is not the case:

- [works] If I connect directly (deprecated method):
  -   Command: `psql -h db.${PROJECT_ID}.supabase.co -p 5432 -d ${DB_NAME} -U ${DB_USER}`
  - Output:
    ```
    Password for user ${DB_USER}:
    psql (XX, server YY)
    SSL connection (protocol: TLSvXX, cipher: YY, compression: ZZ)
    Type "help" for help.

    postgres=>
    ```
- [error] If I connect through the new connection pooler specifying the project ID in the username as specified in your own settings page:
  - Command: `psql -h aws-${DB_REGION}.pooler.supabase.com -p ${DB_PORT} -d ${DB_NAME} -U ${DB_USER}.${PROJECT_ID}`
  - Output:
    ```
    Password for user ${DB_USER}.${PROJECT_ID}:
    psql: error: connection to server at "aws-${DB_REGION}.pooler.supabase.com" (${IP}), port ${DB_PORT} failed: FATAL:  Wrong password
    ```
- [works] If I connect through the new connection pooler specifying the project ID in the connection options:
  - Command: `psql "postgres://${DB_USER}@aws-${DB_REGION}.pooler.supabase.com:${DB_PORT}/${DB_NAME}?options=reference%3D${PROJECT_ID}"`
  - Output:
    ```
    Password for user ${DB_USER}:
    psql (XX, server YY)
    SSL connection (protocol: TLSvXX, cipher: YY, compression: ZZ)
    Type "help" for help.

    postgres=>
    ```

I have literally pasted the very same password I had in the clipboard between the three executions.

Conclusion: It is not possible to connect without specifying the project ID in the connection options, at least in my case 🤷

I have reported it to Supabase, lets see 😬

**Comment by Joffcom** [comment]
It is 100% possible to connect without options, I have tested with 3 accounts now and asked a supabase power user to test and they are all good as well.

Looks like it is account specific which is interesting it will be good to see what supabase say

**Comment by JavierCane** [comment]
Thanks for your response @Joffcom. +1 to your comment.

I think that it is not possible to reduce even more the scenario in order to reproduce the error, so hope that info helps Supabase. I will keep you informed when they respond.

Thanks!

**Comment by JavierCane** [comment]
Hi, thanks a lot for your help with this issue @Joffcom.

Just for the sake of completeness in case it helps other people arriving to this issue: It was because Postgres 13 does not seems to allow to specify the tenant ID in the username as Supabase forces you to do right now. This is the reason why there are users who can access to their database after Supabase migrate from PgBouncer to Supavisor (Postgres 14 and 15), and others like me could not (Postgres 13).

Taking into account the lack of responses from Supabase we decided to replicate our DB in a new Postgres 15 instance, move all our data, and make the switch in order to do not depend on Supabase actions.

As I said, thanks because even if the issue had little to do with n8n, you helped me troubleshooting it 🙌
