### ISSUE TITLE
Executing an old version of the workflow instead of the new one.

### ISSUE THREAD

**Issue by sweenu** [n8n-io/n8n#8473]
**Describe the bug**
After updating my workflow and saving it, test runs do use my latest updates, but when the workflow triggers, it uses an old version of the workflow.

**To Reproduce**
I don't know if this can be easily be reproduced. My guess is that with the RSS feed trigger, a process is started and for some reason it hasn't been properly killed when I saved. That would also explain why my workflow would run thrice instead of once.
I just restarted my container, we will see if the problem comes back.

**Environment:**
- OS: NixOS 24.05
- n8n Version: 1.26.0
- Node.js Version: Whatever the node.js version is in the official docker image
- Database system: SQLite
- Operation mode: main

**Comment by Joffcom** [comment]
Hey @sweenu,

The rss feed trigger runs on a schedule so should be ok.

Do you have some screenshots to show the issue?

**Comment by sweenu** [comment]
So I have had a 4-nodes workflow since about 20 executions from these executions. Yet, as you see in the screenshots, my 3-node version gets executed, and moreover, it got executed thrice for a same trigger at 19:00. For some reason, one of the time, it was my updated version.
![screenshot_2024-01-28-214126](https://github.com/n8n-io/n8n/assets/7051978/d7adad3b-192d-45c8-9171-a035e62e5dab)
![screenshot_2024-01-28-214111](https://github.com/n8n-io/n8n/assets/7051978/68ae1f2d-0512-4cd3-abe1-2c656310b490)
![screenshot_2024-01-28-214101](https://github.com/n8n-io/n8n/assets/7051978/dc1142e9-bab5-4d3a-8108-91c1c1e624e1)
![screenshot_2024-01-28-214034](https://github.com/n8n-io/n8n/assets/7051978/7c3b9a9d-ed28-4859-9209-55910bbfac80)
![screenshot_2024-01-28-214638](https://github.com/n8n-io/n8n/assets/7051978/d9cf3713-910f-4d6f-8c24-4302f44bfbfa)
![screenshot_2024-01-28-214629](https://github.com/n8n-io/n8n/assets/7051978/3d66a1d9-2272-4287-b7e1-535dd1b1b9c7)

**Comment by Joffcom** [comment]
That is very odd, You mentioned you are using sqlite so I take it you are not running in queue mode or anything and it is just a standard one instance install of n8n and nothing fancy.

**Comment by sweenu** [comment]
Indeed, here is my whole config: https://github.com/sweenu/nixfiles/blob/7fc5bfb9ed771ed986589cfcd24af45da359c90b/hosts/najdorf/n8n/default.nix
All my config is the environment variables you see. Nothing fancy indeed.

**Comment by Joffcom** [comment]
Hey @sweenu,

I wonder if something just got stuck in memory, Is it still looking good all good now?

**Comment by sweenu** [comment]
I've had a few issues while playing around the polling time. When doing every minute, many feed items would be skipped.
But yeah, overall, going back to 1-hour intervals it's working pretty well now. Don't hesitate to close the issue.

**Comment by Joffcom** [comment]
Hey @sweenu,

I think I know what the issue is with the node when using every hour / every minute. When we check the rss feed we look at the pubdate and see if that happened after the last run of the node.

It turns out that some rss feeds like Hackernews update hourly and becuase of this the pubdate could be anywhere in the last hour which the 1 minute check won't pick up on.

I will have a think on how to improve this, If we can extract the update frequency from the feed we could at least show an error which may help. Another option could be to keep the last pubdate instead of the run time and on each run we check for anything newer than that.

**Comment by sweenu** [comment]
Indeed, that probably is it! My rss feed comes from the public instance of piped.video. It might not be the most reliable always, it might update late sometimes.

So yeah, a more robust way that checking the date would be nice to have for some use cases. Maybe saving a hash of all the fields concatenated to one string that we can then compare, the next time we poll, to each item until we find the one with the same hash.
Or even better I think, just save the exact date of the last item we sent and on the next poll, you send all the new items with a date greater than the one saved.
