### ISSUE TITLE
RangeError: Maximum call stack size exceeded - MongoDb

### ISSUE THREAD

**Issue by gehal4** [n8n-io/n8n#8529]
**Describe the bug**
ERROR: Maximum call stack size exceeded
 Details
Stack
RangeError: Maximum call stack size exceeded
    at Object.execute ( node_modules\n8n-nodes-base\nodes\MongoDb\MongoDb.node.ts:377:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (node_modules\n8n-workflow\src\Workflow.ts:1322:8)
    at node_modules\n8n-core\src\WorkflowExecute.ts:1046:29

**To Reproduce**
Create a Mongodb node and find with limit to 0, a collection with more than 120000 records , i.e. 180000 records

You get the error message above

**Expected behavior**

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version 1.24.1
- Node.js Version 20.11.'
- Database system SQLite
- Operation mode main

**Additional context**

**Comment by Joffcom** [comment]
Hey @gehal4,

Thanks for reporting this, We have put in a fix that will be available in a future release.
