### ISSUE TITLE
Mailerlite endpoint is giving 404

### ISSUE THREAD

**Issue by jccbbb** [n8n-io/n8n#8555]
**Describe the bug**
The endpoint is wrong. Maybe a legacy one is used?

**To Reproduce**

1. Go to your editor
2. Click on Mailerlite
3. Add your API-key and choose whatever trigger you want
4. See error:
`Problem running workflow
The resource you are requesting could not be found

Show Details
MailerLite Trigger: 404 - {"error":{"message":"Endpoint not found"}} - Endpoint not found`

**Expected behavior**
Should do a successful test request,

- Git: https://github.com/n8n-io/n8n-docker-caddy
- OS: Ubuntu Linux 22.04
- Docker: 23.0.6]

![image](https://github.com/n8n-io/n8n/assets/25697666/202d791f-e007-45e7-9c19-3414b5155af0)

**Comment by Joffcom** [comment]
Hey @jccbbb,

Are you using a Classic mailerlite key or a newer one?

**Comment by jccbbb** [comment]
> Hey @jccbbb,
> 
> Are you using a Classic mailerlite key or a newer one?

Hello,

The newer one 😊

**Comment by Joffcom** [comment]
Hey @jccbbb,

Perfect, So in this case the issue will be that we only support the classic API at the moment but we do have a dev ticket opened to support the new one. Sadly I don't have a timeframe for this at the moment but I have added this issue to the dev ticket to nudge it a bit.

**Comment by jccbbb** [comment]
> Hey @jccbbb,
> 
> Perfect, So in this case the issue will be that we only support the classic API at the moment but we do have a dev ticket opened to support the new one. Sadly I don't have a timeframe for this at the moment but I have added this issue to the dev ticket to nudge it a bit.

Hoi @Joffcom,

Yeah it was one of my thoughts also that it only were for the Classic API but I had to ask 😊 
These dev tickets you are talking about is this public or internal only? Because then I could just "upvote" or see that it is already in the making in the background 😊

**Comment by Joffcom** [comment]
Hey @jccbbb,

Dev tickets are internal only at the moment. I do know that with this one there is currently no progress.

**Comment by adinata-id** [comment]
Hello guys any new update about this case? Thanks

**Comment by Joffcom** [comment]
@adinata-id no updates at the moment, I have just finished doing a similar process for Webflow so this will likely be next on my list.

**Comment by SuitcaseDesigns** [comment]
I this the same issue as this that I'm getting from an Elementor form? 

Your submission failed because of an error.
MailerLite Rest Client Error: response code 404.

**Comment by erykkruk** [comment]
Hey guys, any updates?
