### ISSUE TITLE
Error when copying and pasting steps connected to error branches in n8n workflow

### ISSUE THREAD

**Issue by Ovler-Young** [n8n-io/n8n#8573]
**Describe the bug**
An unexpected error occurs when attempting to duplicate steps in an n8n workflow that are connected to the error branch. The error message "Cannot read properties of null (reading 'forEach')" is displayed when trying to copy and paste these steps, even if the conditions for the error to occur are not met.

![image](https://github.com/n8n-io/n8n/assets/44089074/81b19d27-5ec4-4eb4-bd45-9b0748d96f2c)

**To Reproduce**
1. Start a new workflow in n8n.
2. Add a step, such as an HTTP Request to https://github.com/n8n-io/n8n.
3. In the step settings, change the "On Error" option to "Continue (using error output)".
![image](https://github.com/n8n-io/n8n/assets/44089074/9f3111d9-a665-4c3a-a2d2-df96e54c67a0)
4. Connect another step to handle errors, like a "No Operation, do nothing" step.
5. Select both the original step and the error handling step.
6. Use `Ctrl+C` to copy the selected steps.
7. Attempt to paste the copied steps using `Ctrl+V`.
8. Observe the error message stating "Cannot read properties of null (reading 'forEach')".

**Expected behavior**
The steps should be successfully duplicated without encountering any errors. The application should allow for easy duplication of steps within a workflow, including those connected to the error branch.

**Environment (please complete the following information):**

- OS: Docker on Linux
- n8n Version:   1.26.0
- Node.js Version: 18.18.2
- Database system: PostgreSQL
- Operation mode: Not specified (default if not configured)

**Additional context**
The workflow to cause the error is in the json below.
[bug.json](https://github.com/n8n-io/n8n/files/14195103/bug.json)

**Comment by Joffcom** [comment]
Hey @Ovler-Young,

I am not able to reproduce this in `1.27.2` are you able to update your n8n instance? I have imported your workflow and done a copy / paste and cmd+d with both nodes selected.

I think this was fixed in #8456

**Comment by Ovler-Young** [comment]
Thanks @Joffcom !

Upgrading to the Pre-release version  1.27.2 resolved the issue. Thank you for your prompt attention to this matter and for the fix in #8456!
