### ISSUE TITLE
1.27.2 seems to ignore configured N8N_CONFIG_FILES, unless DEBUG=* is also included

### ISSUE THREAD

**Issue by jbusuttil** [n8n-io/n8n#8607]
### Bug Description

I start n8n using the following `systemd` unit file:

```
[Unit]
Description=n8n server
After=syslog.target network.target

[Service]
Environment="N8N_CONFIG_FILES=/opt/n8n/production.json" "WEBHOOK_URL=https://[redacted]/"
WorkingDirectory=/opt/n8n
ExecStart=/usr/local/bin/n8n start
Type=simple
Restart=always
RestartSec=10
SyslogIdentifier=n8n
User=n8n
Group=n8n

[Install]
WantedBy=multi-user.target
```

On 1.26.0 and earlier versions, the environment variables were picked up with no problem.

On 1.27.2 `N8N_CONFIG_FILES` is loaded but the config parameters are not acted upon. This means startup fails with the following errors:

```
Feb 11 13:17:27 n8n n8n[895]: User settings loaded from: /opt/n8n/.n8n/config
Feb 11 13:17:27 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:27 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: Loading config overwrites [ '/opt/n8n/production.json' ]
Feb 11 13:17:28 n8n n8n[895]: (node:895) Error Plugin: n8n: configuration param 'executions.process' not declared in the schema
Feb 11 13:17:28 n8n n8n[895]: module: @oclif/core@3.18.1
Feb 11 13:17:28 n8n n8n[895]: task: cacheCommand
Feb 11 13:17:28 n8n n8n[895]: plugin: n8n
Feb 11 13:17:28 n8n n8n[895]: root: /usr/local/lib/node_modules/n8n
Feb 11 13:17:28 n8n n8n[895]: See more details with DEBUG=*
[error repeats]
```

If `DEBUG=*` is added to the `Environment` declared for the `systemd` unit (then running `systemctl daemon-reload`), however, the configuration and its settings are picked up correctly, and n8n starts normally.

Removing `DEBUG=*` from the unit file again (then running `systemctl daemon-reload`) and n8n again generates the errors and will not start.

Same behaviour is observed when exporting the environment variables and starting n8n manually from the shell.

### To Reproduce

Using 1.27.2 and the `systemd` unit file provided above attempt to start n8n

### Expected behavior

Configuration parameters declared in `N8N_CONFIG_FILES` should be picked up and n8n should start as normal

### Operating System

Debian bookworm

### n8n Version

1.27.2

### Node.js Version

18.13.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jbusuttil 

I have looked over the output and it looks like you might be including executions process as an option which was marked as deprecated with the release of v1 and has now been removed from `1.27.0`.

It looks like we forgot to update the breaking changes to include this though.

For now I would remove that setting from your config file and you should be good to go.

**Comment by jbusuttil** [comment]
Ah, good to know - thank you. Weird that it worked with debug enabled :-)
