### ISSUE TITLE
2 Google OAuth2 API in Credential type

### ISSUE THREAD

**Issue by dichvuhuuich** [n8n-io/n8n#861]
**Describe the bug**
Add credential there are 2 Google OAuth2 API in Credential type

**To Reproduce**
1. Go to Credentials> New
2. Click on Credential type
3. Scroll down to Google
4. There are  2 Google OAuth2 API in Credential type like picture

**Expected behavior**
Google OAuth2 API 2 is YouTube and Google OAuth2 API 1 should removed

**Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04.01
 - n8n Version 0.78.0
 - Node.js Version [e.g. 10.16.0]

![image](https://user-images.githubusercontent.com/4901985/90607745-d8faaf00-e22b-11ea-9a3e-603b187dd267.png)

**Comment by janober** [comment]
Thanks a lot for making us aware of that.
One "Google OAuth2 API" is OK (even though it can currently not be used directly) but the other one should be renamed to "YouTube OAuth2 API". Did already do it and will be released with the next version.

Have a great day!

**Comment by janober** [comment]
Got released with n8n@0.79.0
