### ISSUE TITLE
Bug: When creating a HTTP Node with square brackets [ ] in the title, the output is always null. 

### ISSUE THREAD

**Issue by goforbg** [n8n-io/n8n#8624]
### Bug Description

I have this node that runs a HTTP Request and works as expected: 

![image](https://github.com/n8n-io/n8n/assets/3736085/5bf70118-3287-4b41-8caf-bb8e1b65f675)

But if I just change it to Enrich Organization Info [Apollo.io] instead of Enrich Organization Info it does not return output
![image](https://github.com/n8n-io/n8n/assets/3736085/1a8adeb3-ba65-47ba-b966-ab843510b29c)

### To Reproduce

1. Create a HTTP node that works 
2. See it succeed after running the workflow 
3. Add square brackets to the title 
4. See it fail 

### Expected behavior

HTTP Nodes must be able to have square brackets and dots in the title, or at least not allow renaming with [ ] and .s 

### Operating System

Ubuntu Linux 22.4.0

### n8n Version

1.28.0

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @goforbg,

Thanks for the report, I remember that being fixed a few versions back. Can you double check that you are on `1.28.0` and not an earlier release?

**Comment by goforbg** [comment]
@Joffcom You are right, I assumed I was on the latest, I'm on 1.14.2

**Comment by Joffcom** [comment]
@goforbg perfect thanks for the update.
