### ISSUE TITLE
String (Date) is being reported by Compare node as Different when it is Same

### ISSUE THREAD

**Issue by profucius** [n8n-io/n8n#8637]
### Bug Description

When running a Compare node against two sets of JSON data, comparing a string containing a date in unix format, I find that the Compare node reports them as Different, when the text is exactly the same.

Evidence below in screenshot. The text highlighted is exactly the same. It is highlighted by my browser. I selected one row, CTRL-F and both highlighted, proving that the browser even considers their data exactly the same.

![bug report to n8n](https://github.com/n8n-io/n8n/assets/18254607/23f9fdc5-6def-4650-84d4-07fa755ec69d)

### To Reproduce

This is how I have produced the data, although you may be able to produce the data via a manual Set node.

> The general idea here is that I am using Notion as a database, and I want to save that Notion database into a local JSON file. I then compare these two sets of data, which are sometimes the same, and sometimes different. I use this as a data differentiation method to determine if I should send the new data as a Create to Notion (if a new record), or an Update to Notion (if an existing record) via a matching UID field.

1. Create a database table in Notion. Create a new record. Now create a date field and set any date to it. Also create a text field and name it UID. Put a unique identifier in this field. You should have a single record in the database with a date and UID assigned to it.
2. In n8n, Get that Notion database JSON data. Link it to a "Extract to JSON" node and then a "Write to Disk" node, saving the JSON as a local file, representative of the Notion database.
3. Create a "Read file" node reading that newly created JSON file. Link to a "Convert from JSON" node.
4. Create a Compare node. 
5. Link the original Notion get database node to the Compare node as Input 1.
6. Link the Read file/Convert JSON node to Compare node as Input 2.
7. Set the Compare node to match on the UID field. Set the node to "When There Are Differences" to "Include Both Versions"
8. Run the macro and look at the results of the Compare node. Click on the Different tab. You will see something similar to what is in my screenshot.

### Expected behavior

The date that was set into the Notion fields gets saved into the local JSON file that is written as a local copy. When that file is read, and then Compared against the live Notion database data, it should find that both of these date values are the same, because they are, the local copy was written from the remote copy via n8n itself.

### Operating System

Windows 11 22H2

### n8n Version

1.28.0

### Node.js Version

18.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @profucius 

Can you add a set node to the output of each and check the output of `{{ typeof $json.start }}`? I suspect one is a date (from Notion) and the other is a string (from the file) so the data types would be different resulting in different values but the same.

I can also test this when I am back on Monday to see if this is the case.

**Comment by profucius** [comment]
I'll give that a shot later when I catch some time. I had to abandon the testing earlier for a different workaround.

I did check to make sure that they are the same value types however. Screenshots below. Both Input A and B are a JSON with the date being a string within an object. Would what you suggested show us something deeper than this?

![image](https://github.com/n8n-io/n8n/assets/18254607/84ed0308-f04e-41d9-9181-4a477fd29993)

![image](https://github.com/n8n-io/n8n/assets/18254607/effe0899-a44e-41c6-9b8d-c18b689de458)

**Comment by profucius** [comment]
So I just tried it again by copying the nodes from the run history into a new macro. I stripped away all the other nodes to focus on the issue. Now I cant seem to reproduce it for some reason. Very strange. I don't know what to do now, so I guess we can close this ticket. I'll post here again if I can reproduce it again somehow. Thanks

**Comment by Joffcom** [comment]
Hey @profucius,

Thanks for the update, I will still give it a go when I am back as I know sometimes we don't convert all dates so while we show it as a string in the schema view it may not be although I thought we had caught them all now.

I have also seen issues with invisible characters and a way to check for those is to use a set node and base64 encode (or hash) the strings and see if they match.
