### ISSUE TITLE
Bug: RangeError when enabling Kubernetes service

### ISSUE THREAD

**Issue by drpsyko101** [n8n-io/n8n#8650]
### Bug Description

n8n crashed whenever a Kubernetes kind Service is set up before the app started.

```
User settings loaded from: /home/node/.n8n/config
Last session crashed
Initializing n8n process
RangeError: options.port should be >= 0 and < 65536. Received type number (NaN).
at new NodeError (node:internal/errors:405:5)
at validatePort (node:internal/validators:409:11)
at Server.listen (node:net:1945:5)
at /usr/local/lib/node_modules/n8n/dist/AbstractServer.js:134:52
at new Promise (<anonymous>)
at Server.init (/usr/local/lib/node_modules/n8n/dist/AbstractServer.js:134:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/BaseCommand.js:74:9)
at Start.init (/usr/local/lib/node_modules/n8n/dist/commands/start.js:133:9)
at Start._run (/usr/local/lib/node_modules/n8n/node_modules/@oclif/core/lib/command.js:303:13)
Error: Exiting due to an error.
RangeError: options.port should be >= 0 and < 65536. Received type number (NaN).
```

### To Reproduce

1. Create a YAML with a deployment named `n8n` and a service named `n8n`.
2. Apply YAML file into the Kubernetes.
3. Observe n8n crash with the error above.

### Expected behavior

Expected n8n to initialize the database and the service running properly.

### Probable cause

Environment variable collision with Kubernetes service allocation - `N8N_PORT`. This variable is set to `tcp://<pod-ip>:5678` by Kubernetes whenever a primary port is defined in the kind Service. That in turn will cause the node app to fail to parse the variable.

### Temporary workaround:

a. Set `N8N_PORT` environment variable with a valid integer value in the deployment.
b. Change deployment and service name to something other than `n8n`.

### Operating System

Ubuntu 22.04

### n8n Version

1.28.0

### Node.js Version

18.19.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @drpsyko101 

This doesn't appear to be a bug with n8n and looks like it is a configuration issue.

> options.port should be >= 0 and < 65536. Received type number (NaN).

Based on this I would say the port value is not correctly set, we expect `N8N_PORT` to be set to a number as documented.
