### ISSUE TITLE
OneDrive Node SSL Error

### ISSUE THREAD

**Issue by pcxnet** [n8n-io/n8n#8668]
### Bug Description

Updated to V1.27.3 and I get this error using OneDrive now, was working in V1.18.0 but now can't revert back :(

ERROR: SSL Issue: consider using the 'Ignore SSL issues' option
Hostname/IP does not match certificate's altnames: Host: graph.microsoft.com. is not in the cert's altnames: DNS:*.media.microsoftstream.com, DNS:*.azureedge.net, DNS:*.origin.mediaservices.windows.net, DNS:*.streaming.mediaservices.windows.net

### To Reproduce

Use OneDrive Node

### Expected behavior

Works and connects

### Operating System

Docker

### n8n Version

1.27.3

### Node.js Version

?

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @pcxnet 

Thanks for reporting this, it looks like an issue on Microsoft's side with their SSL certificate but I will do some testing to make sure shortly.

**Comment by Joffcom** [comment]
Hey @pcxnet,

I have just given this a go and I have not been able to reproce this, Can you connect again and see if you have the same issue it could have just been a temporary thing.

**Comment by pcxnet** [comment]
Hi @Joffcom ,

GetFiles works, but DownloadFiles does not 

Working:
{
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "7286cb7af5e69b909e9502fd59ea92cbd7d4a06c840dc2904f09626675230c35"
  },
  "nodes": [
    {
      "parameters": {
        "resource": "folder",
        "folderId": "01NJX73DBETSWOE4GPBNF2KAJSOG52ICJX"
      },
      "id": "f5564de5-7e02-4269-925f-2e65808e771e",
      "name": "getFiles",
      "type": "n8n-nodes-base.microsoftOneDrive",
      "typeVersion": 1,
      "position": [
        -340,
        700
      ],
      "credentials": {
        "microsoftOneDriveOAuth2Api": {
          "id": "Z38d1oum45Nx5FdN",
          "name": "Services"
        }
      }
    }
  ],
  "connections": {},
  "pinData": {}
}

Not Working:
{
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "7286cb7af5e69b909e9502fd59ea92cbd7d4a06c840dc2904f09626675230c35"
  },
  "nodes": [
    {
      "parameters": {
        "operation": "download",
        "fileId": "={{ $json.id }}"
      },
      "id": "b6a61eb3-0754-4313-84d1-2ccaf2bef378",
      "name": "downloadPayroll",
      "type": "n8n-nodes-base.microsoftOneDrive",
      "typeVersion": 1,
      "position": [
        120,
        560
      ],
      "credentials": {
        "microsoftOneDriveOAuth2Api": {
          "id": "Z38d1oum45Nx5FdN",
          "name": "Services"
        }
      }
    }
  ],
  "connections": {},
  "pinData": {}
}

**Comment by Joffcom** [comment]
Hey @pcxnet,

That breaks it thanks for providing a way to reproduce the message, The error itself seems to explain itself the graph.microsoft.com URL is not in the certifcate that Microsoft is returning so that is not something we can control.

However as the file should be downloaded from a redirect I wonder if we still have a header set that isn't needed. I will get a dev ticket created shortly to look into this.

**Comment by pcxnet** [comment]
Hi sorry I only realised it was one and not the other when I noticed the other node working.

Thanks

**Comment by pcxnet** [comment]
Also not sure what changed in the version's but it was working on the older version I listed.

**Comment by pcxnet** [comment]
While I'm waiting for the fix, is there a way I can go back to the old version or edit the files to ignore the ssl?

**Comment by netroy** [comment]
@pcxnet Can you please check if this issue exists on `1.27.2` for you?

**Comment by pcxnet** [comment]
@netroy  @Joffcom  Beautiful.  1.27.2 works :) Thanks so much, this will get me through the day :)

**Comment by netroy** [comment]
Thanks for letting us know. I believe this narrows down the issue to #8562.

**Comment by janober** [comment]
Fix got released with [`n8n@1.30.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.30.0)

**Comment by jesko-cs** [comment]
For any Stripe user who might run into this issue:

I got the same error for the Stripe node after updating to `1.29.1` at n8n.cloud:

`Hostname/IP does not match certificate's altnames: Host: pay.stripe.com. is not in the cert's altnames: DNS:s3-us-west-1.amazonaws.com, DNS:*.s3-us-west-1.amazonaws.com, DNS:s3.us-west-1.amazonaws.com, ...`

Updating to 1.30.1 beta fixed it for me.
