### ISSUE TITLE
Docker-Tags breaking auto-update tools

### ISSUE THREAD

**Issue by Ornias1993** [n8n-io/n8n#8672]
### Bug Description

Auto-update tools like Renovate, depend on docker-tags to determine which tag to update to according to semver.
The current scheme tags pre-releases (beta software) as "normal" version tags, which breaks such tools completely and is also not in semver-compliance.

Please release tags for pre-releases with a clear `x.y.z-prerelease` suffix, so said tools can correctly filter out non-release container versions. Without having to resort to "latest", because friends do not let friends use latest.

### To Reproduce

- Use renovate or lock at dockerhub
- Be amazed at bad tagging practices

### Expected behavior

Good (semver)compliant tagging of image versions

### Operating System

docker

### n8n Version

any pre-release

### Node.js Version

irrelevant

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Ornias1993** [comment]
@stavros-k this is what you ran into with https://github.com/truenas/charts/pull/2178 as well.

**Comment by Joffcom** [comment]
@netroy do you have any thoughts on this?

**Comment by netroy** [comment]
> Please release tags for pre-releases with a clear `x.y.z-prerelease` suffix, so said tools can correctly filter out non-release container versions. Without having to resort to "latest", because friends do not let friends use latest.

When we release a docker image (or NPM package) `x.y.z`, it's **not a pre-release**. These are proper releases. However we don't tag these as `latest` right away, and usually wait about a week of testing it ourselves before **we re-tag the already released image** as `latest`.
None of our pre-release/beta images on dockerhub use a semver label.

That said, our releases try to follow strict Semver already. We do however have accidental breaking changes sometimes, and we almost always address than in a patch release right away.


> ### To Reproduce
> - Be amazed at bad tagging practices

I don't know if you intended to make this sound like this, but please refrain from using emotionally-charged and passive-aggressive language when engaging with any community. 
I get your frustration, but spreading it to others isn't going to improve the chances of the issue getting addressed. It's more likely that something like might deter maintainers from engaging in the conversation.
**Please talk to others with the same respect and in the same tone as you would want them to talk you in 🙏🏽 .**

**Comment by Joffcom** [comment]
Moving to closed as there is nothing to really fix here based on the explanation provided here and on the Charts issue.

**Comment by mark-monteiro** [comment]
For anyone else who comes across this issue, there is an open feature request for this here (feel free to add your upvotes!): https://community.n8n.io/t/docker-image-versioning-for-next-releases/25378

I have also put together a workaround for Renovate, which I detailed here: https://github.com/renovatebot/renovate/discussions/34456#discussioncomment-14547624
