### ISSUE TITLE
Azure OpenAI Chat Model is Missing

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#8687]
### Bug Description

Based on this [documentation](https://docs.n8n.io/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatazureopenai/), it appears n8n *should* natively support Azure Open AI.  However, when trying to *find* this Chat Model in the n8n UI, it appears to be *missing*.

### To Reproduce

1. Create a new workflow
2. Specify `Basic LLM Chain` as a node type.
3. Click on the `Model` plus button for that node.
4. Try to find the `Azure Open AI Chat Model` and see that it's *missing*

![image](https://github.com/n8n-io/n8n/assets/85660/b1fc54d4-83cf-407e-a2fa-06f08f6359c1)

![image](https://github.com/n8n-io/n8n/assets/85660/001e244d-f3fe-4857-b347-5da5e4bb094e)

### Expected behavior

1. Create a new workflow
2. Specify `Basic LLM Chain` as a node type.
3. Click on the `Model` plus button for that node.
4. Try to find the `Azure Open AI Chat Model` and see that it's *present*

### Operating System

Google Cloud Run

### n8n Version

1.29.1

### Node.js Version

18.10

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by dkindlund** [comment]
Hey @Joffcom , I just tried again after clearing my browser cache, and I'm still not seeing the new nodes appear.  I'll rebuild my container again from the [master](https://github.com/n8n-io/n8n/tree/master) branch and see if that resolves the issue.

@Joffcom , are you also running on the master branch or some other release version?

**Comment by dkindlund** [comment]
Hey @Joffcom , okay, I literally just rebuilt my container from the master branch, logged into n8n via Incognito Mode/Private Mode (to clear the cache), and I'm still not seeing the Azure nodes show up:

<img width="899" alt="image" src="https://github.com/n8n-io/n8n/assets/85660/57d25e3f-6366-4d9e-847f-2b5962550b28">

**Comment by dkindlund** [comment]
The only other thing I can think of, is that I'm using this Dockerfile when building my container:
https://github.com/n8n-io/n8n/blob/master/docker/images/n8n/Dockerfile

And I specify `N8N_VERSION=latest` in the build process.

Let me know if I should be using something else in case your build environment is different, @Joffcom

**Comment by Joffcom** [comment]
Hey @dkindlund,

Can you check the version that n8n is showing?

I am using our published docker image which I would recommend doing if possible. The node should be in the master branch though as the code has been merged so I would assume your branch has not been pulled for a while.

**Comment by Joffcom** [comment]
Hey @dkindlund,

I don't believe this is a regression as your version is showing 1.27.3 it looks like maybe there is an issue with your build process and it is caching an old version somewhere.

**Comment by dkindlund** [comment]
@Joffcom , just to be clear, you're saying that because [n8n@1.29.1](https://github.com/n8n-io/n8n/releases/tag/n8n%401.29.1) was a pre-release as of 4 days ago, the UI should have shown `1.29.1` (pre-release) instead of `1.27.3` (latest release)?

There isn't anything I'm doing special to the build process -- simply using the standard Dockerfile provided by the n8n repo.  I'll certainly check further.  Is your docker image running n8n@1.27.3 or some other version?

**Comment by dkindlund** [comment]
Okay, that solved the issue, @Joffcom !  I'm now seeing the Azure nodes appear (see screenshots below).

The fix was to change `N8N_VERSION=latest` to `N8N_VERSION=next` in my build process.  Thanks again!

<img width="514" alt="image" src="https://github.com/n8n-io/n8n/assets/85660/88b50187-1429-4adc-8a84-2fe051bb8357">

<img width="906" alt="image" src="https://github.com/n8n-io/n8n/assets/85660/464ebfe5-2fa9-4a2b-8424-7428d15650ba">

**Comment by dkindlund** [comment]
Incidentally, @Joffcom , as a sanity check... because the build process is specifying an exact `N8N_VERSION` as part of the build arguments, I assume that means any changes made to the `master` branch that occur *after* that version will *not* be incorporated into my container... is that a correct understanding?

In other words, I shouldn't bother to sync from `master` any more frequently than until a new release (or pre-release) is issued.

Conversely, if I wanted to use "bleeding edge" code, there isn't like a `N8N_VERSION=master` parameter I could set to do that, right?

**Comment by Joffcom** [comment]
@dkindlund if you wanted to build your docker image from source instead of an existing version you would need to use the docker file in the Custom folder.
