### ISSUE TITLE
Clickup Integration Create Task set Assignee by Id invalid format when using expression

### ISSUE THREAD

**Issue by obuchmann** [n8n-io/n8n#8694]
### Bug Description

If you want to create a Task in clickup and want to set an assignee id from input via the expression the exception says - The value "123456" is not Supported!

The Node converts valid integers to strings (event when using parseInt in advance). That leads to Clickup ignoring the values.

### To Reproduce

1. Create a new Node of type Clickup "create:task"
2. Add addintional Field "Assignee Names or IDs"
3. switch to expression mode for this field
4. put an integer there (by hand or from an expression)

### Expected behavior

The assignee should be possible to set like when selecting an assignee from the list (it works)

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.27.2

### Node.js Version

docker node version

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @obuchmann,

It sounds like you are actually passing in a string not an int, Can you share a screenshot of the input data and the node field?

**Comment by Joffcom** [comment]
@obuchmann how are you setting the expression? I have tried using `{{ 49735545 }}` as an example and that is working as expected.

**Comment by obuchmann** [comment]
@Joffcom I tried several types of inputs, here are some screenshots

Number only:
![image](https://github.com/n8n-io/n8n/assets/3889302/00e84b5b-d0ba-40fe-be5c-4130a800af77)

Number from Field
![image](https://github.com/n8n-io/n8n/assets/3889302/ffefbac8-225e-4907-b7dd-763be7dcdf2d)
![Screenshot from 2024-02-21 11-54-21](https://github.com/n8n-io/n8n/assets/3889302/ffb03751-3595-499d-b4ee-1f3acb2b1788)

I even tried with parseInt

**Comment by Joffcom** [comment]
Hey @obuchmann,

I think I can see the issue there, I take it you have not actually sent the value and are referring to the text next to the field?

**Comment by obuchmann** [comment]
Hey @Joffcom I sent the value and it ended in creating a task without an assignee

**Comment by Joffcom** [comment]
Hey @obuchmann,

Perfect in that case this is a known issue we are aware of already where the expression doesn't match the nodes datatype. This is something that may be fixed in the future I am just not sure when, I think we have another issue opened for this so for now I am going to mark this as closed but I will get this linked to the internal issue so we can still pop a notification on here once fixed.

Let me know if you have any questions on this.

**Comment by obuchmann** [comment]
@Joffcom Good to know this is already known, are there any workarounds already? Maybe by calling this from a js snippet or something?

**Comment by obuchmann** [comment]
@Joffcom Any News on this? Can you link the correspondig issue you are aware of?
