### ISSUE TITLE
Unrecognized node type

### ISSUE THREAD

**Issue by nengc** [n8n-io/n8n#8707]
### Bug Description

I created a custom node, and need to save credential. But after i added the ``credentials.testedBy`` , cannot save the credential and return errors ``Unrecognized node type: ``

### To Reproduce

1. Add Credential
![image](https://github.com/n8n-io/n8n/assets/19792047/045585b5-9c3b-40c2-9022-98b4ef5bf914)
2. Save 
![image](https://github.com/n8n-io/n8n/assets/19792047/1d288584-26aa-4d4c-b6ce-6ba3f247c3d3)
3. Error
![image](https://github.com/n8n-io/n8n/assets/19792047/156236d7-7133-48a9-b020-8dd464edd3da)

### Expected behavior

can save and test successfully

### Operating System

Cent OS 7

### n8n Version

1.27.3

### Node.js Version

16.20.2

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nengc 

How have you installed your custom node?

We have another issue open for the tested by not working so this could be the same issue but the error might be different because you are using .n8n/custom instead of .n8n/nodes

**Comment by nengc** [comment]
Hi @Joffcom
I tried to install my custom node from UI and i also tried to run command ``npm i {package name}`` in the .n8n/nodes dir. But got the same error.

**Comment by Joffcom** [comment]
Hey @nengc, 

I suspect you are seeing this issue: https://github.com/n8n-io/n8n/issues/8188 just a different error for the same thing as we know the tested by option doesn't currently work.

For now as I suspect fixing the other issue will also fix this issue I think we can mark this as a duplicate. Let me know what you think.

**Comment by nengc** [comment]
Tks @Joffcom ,
That is it. And i fixed it by using the code provided by @tonymorello  https://github.com/n8n-io/n8n/issues/8188#issuecomment-1919942858
![image](https://github.com/n8n-io/n8n/assets/19792047/9ccb6c93-ebc6-45e8-8b56-17151a80a737)

**Comment by Joffcom** [comment]
Hey @nengc,

I am surprised we have not reviewed that but for now as it is the same issue I will mark this as closed, Thanks for confirming.

**Comment by nengc** [comment]
Hi @Joffcom ,
I found another issue when i reopen the custom credential from the UI. The custom credential will not be tested on opening.
![image](https://github.com/n8n-io/n8n/assets/19792047/0886f300-6b6a-44dd-9a0d-60e7c0ea5314)

**Comment by tonymorello** [comment]
@nengc that is the same issue. The test function is going to work with the changes from my PR.
Currently the path of the custom node is resolved and registered incorrectly when n8n initially starts
