### ISSUE TITLE
OpenAI > Generate Image > Prompt Type: Expression return an error OpenAI: Parameter "Text" is required.

### ISSUE THREAD

**Issue by gitpel** [n8n-io/n8n#8723]
### Bug Description

Hi, 
Typically bug: Node OpenAI > Generate Image > Prompt Type: **Expression** returns an error:

```text
Workflow has issues
OpenAI: Parameter "Text" is required.
```

There isn't any "Text" parameter at all btw.
No errors if the prompt type: **Fixed**

### To Reproduce

Add node OpenAI > Generate Image > Change prompt type to: **Expression** you will get the error no matter will you add any text or variable.

### Expected behavior

No errors when Expression or Fixed content types
Thank you

### Operating System

Debian 12

### n8n Version

1.29.1

### Node.js Version

v18.19.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @gitpel,

I have just checked and this appears to be fixed in `1.30.0` can you try updating and let me know if you see the same issue.
