### ISSUE TITLE
Question and Answer Chain - Error in sub-node ‘Embeddings OpenAI’

### ISSUE THREAD

**Issue by jfang** [n8n-io/n8n#8731]
### Bug Description

After I upgraded from n8n Version 1.28.0 (docker pull n8nio/n8n:1.28.0) to n8n Version 1.29.1 (docker pull n8nio/n8n:latest), I began to see the following error message when I executed the "Question and Answer Chain" node. I've installed an instance of n8n Version 1.28.0 and copied and pasted the same nodes and do not have this issue.

![image](https://github.com/n8n-io/n8n/assets/5340486/fc8f8caa-49a3-4cea-8d59-658d23e199ce)

Error in sub-node ‘Embeddings OpenAI’
404 404 page not found Open node
 Details
Time
2/23/2024, 7:58:53 PM
Stack
NodeOperationError: 404 404 page not found
    at OpenAIEmbeddings.callMethodAsync (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:32:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Proxy.connectionType (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:271:43)
    at MemoryVectorStore.similaritySearch (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/vectorstores/base.cjs:107:68)
    at MemoryVectorStore.callMethodAsync (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:26:16)
    at Proxy.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:367:43)
    at VectorStoreRetriever.getRelevantDocuments (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/node_modules/@langchain/core/dist/retrievers.cjs:69:29)
    at VectorStoreRetriever.callMethodAsync (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:26:16)
    at Proxy.connectionType (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:233:43)
    at RetrievalQAChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/retrieval_qa.cjs:79:22)
    at RetrievalQAChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.js:104:30)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:730:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:662:53
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1064:20
/

### To Reproduce

Using n8n 1.29.1, run the following workflow. The error will occur in the Question and Answer Chain node.
{
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "1218ccc15068a4d1b900507e0ec24eee43a2b4459048f30dcc1e224c5eb5ed39"
  },
  "nodes": [
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "7b5dad0b-ede0-4eaa-b6f3-3fbce49319b5",
              "name": "input",
              "value": "",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "2698ccfe-8058-4b08-8734-5dfc353ac47b",
      "name": "Edit Fields",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        -40,
        320
      ]
    },
    {
      "parameters": {},
      "id": "b958f052-68d9-4204-acc8-336ee4f8bf8e",
      "name": "When clicking \"Test workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        660,
        380
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "487baf27-a29b-488c-9010-c050254d27df",
      "name": "Default Data Loader",
      "type": "@n8n/n8n-nodes-langchain.documentDefaultDataLoader",
      "typeVersion": 1,
      "position": [
        340,
        560
      ]
    },
    {
      "parameters": {
        "chunkOverlap": 20
      },
      "id": "6a076867-e319-472b-8692-47a0d0f888d4",
      "name": "Recursive Character Text Splitter",
      "type": "@n8n/n8n-nodes-langchain.textSplitterRecursiveCharacterTextSplitter",
      "typeVersion": 1,
      "position": [
        200,
        720
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "9740d249-54ee-49cb-acda-e24e0ef24c53",
      "name": "Embeddings OpenAI",
      "type": "@n8n/n8n-nodes-langchain.embeddingsOpenAi",
      "typeVersion": 1,
      "position": [
        140,
        580
      ],
      "credentials": {
        "openAiApi": {
          "id": "15",
          "name": "OpenAI account"
        }
      }
    },
    {
      "parameters": {
        "model": "mistral:latest",
        "options": {
          "topK": -1
        }
      },
      "id": "bf6e01ff-1b9a-47c3-8fb9-fa64d2ad8ce3",
      "name": "Ollama Model",
      "type": "@n8n/n8n-nodes-langchain.lmOllama",
      "typeVersion": 1,
      "position": [
        1100,
        580
      ],
      "credentials": {
        "ollamaApi": {
          "id": "h2lvc9JQTFDvXsf2",
          "name": "Ollama account"
        }
      }
    },
    {
      "parameters": {
        "fields": {
          "values": [
            {
              "name": "input",
              "stringValue": "You are a senior content curator that excels at summarizing content and creating tags for the content so that you can use them later to pull in relevant content. Create a summary in 100 words and create the ten most relevant tags associated with this content.\n\nThe output should be a markdown code snippet formatted in the following schema without json or ```:\n\n{\n \"Summary\": string  // Summary of the review in paragraph format\n \"tags\": array // Put the tags into a JSON array\n}\n"
            }
          ]
        },
        "options": {}
      },
      "id": "d976fc9e-75ce-43d8-8a91-a386ea78b45f",
      "name": "Prompt",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.2,
      "position": [
        900,
        380
      ],
      "executeOnce": true
    },
    {
      "parameters": {
        "mode": "raw",
        "jsonOutput": "={{ $json.response.text }}",
        "include": "none",
        "options": {}
      },
      "id": "3a98497a-8a94-47cd-8f22-da240c58239a",
      "name": "JSON Output",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.2,
      "position": [
        1540,
        380
      ]
    },
    {
      "parameters": {
        "fieldToSplitOut": "tags",
        "options": {}
      },
      "id": "f843e1e0-949b-4e24-b569-550fc90daa52",
      "name": "Split Out",
      "type": "n8n-nodes-base.splitOut",
      "typeVersion": 1,
      "position": [
        1740,
        380
      ]
    },
    {
      "parameters": {
        "fieldsToAggregate": {
          "fieldToAggregate": [
            {
              "fieldToAggregate": "tags"
            }
          ]
        },
        "options": {}
      },
      "id": "26eed272-93c9-4eaf-bf36-214c51c50a5b",
      "name": "Aggregate",
      "type": "n8n-nodes-base.aggregate",
      "typeVersion": 1,
      "position": [
        1960,
        380
      ]
    },
    {
      "parameters": {
        "content": "## Summarizing and Tagging Vector Data",
        "height": 805.9488708940942,
        "width": 1590.1968028414062
      },
      "id": "5eecb080-f2ae-45eb-8fff-d9b7be9f077d",
      "name": "Sticky Note1",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        800,
        128.9372937293732
      ]
    },
    {
      "parameters": {
        "options": {}
      },
      "id": "ff85fb05-b3a2-441b-874b-5783688fc238",
      "name": "Embeddings OpenAI1",
      "type": "@n8n/n8n-nodes-langchain.embeddingsOpenAi",
      "typeVersion": 1,
      "position": [
        1040,
        800
      ],
      "credentials": {
        "openAiApi": {
          "id": "15",
          "name": "OpenAI account"
        }
      }
    },
    {
      "parameters": {},
      "id": "797381b0-0c13-4ac2-9f14-40a6efca171e",
      "name": "Vector Store Retriever",
      "type": "@n8n/n8n-nodes-langchain.retrieverVectorStore",
      "typeVersion": 1,
      "position": [
        1220,
        600
      ]
    },
    {
      "parameters": {
        "memoryKey": "memory1"
      },
      "id": "4cffdeef-a669-4bab-b3c2-564465f9d010",
      "name": "In-Memory Vector Store1",
      "type": "@n8n/n8n-nodes-langchain.vectorStoreInMemory",
      "typeVersion": 1,
      "position": [
        1220,
        780
      ]
    },
    {
      "parameters": {
        "fields": {
          "values": [
            {
              "name": "tags",
              "stringValue": "={{ $json[\"tags\"].join(',') }}"
            }
          ]
        },
        "options": {}
      },
      "id": "d15e57dd-1934-4234-abd2-2c5c69862eda",
      "name": "Edit Fields1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.2,
      "position": [
        2200,
        380
      ]
    },
    {
      "parameters": {
        "mode": "insert",
        "memoryKey": "=memory1",
        "clearStore": true
      },
      "id": "cd5ef271-6542-4e76-aa97-70fbb959ad72",
      "name": "In-Memory Vector Store",
      "type": "@n8n/n8n-nodes-langchain.vectorStoreInMemory",
      "typeVersion": 1,
      "position": [
        180,
        320
      ]
    },
    {
      "parameters": {
        "query": "={{ $json.input }}"
      },
      "id": "e170a0ed-2b6b-4e53-99ba-fff990256aec",
      "name": "Question and Answer Chain",
      "type": "@n8n/n8n-nodes-langchain.chainRetrievalQa",
      "typeVersion": 1.2,
      "position": [
        1160,
        320
      ]
    },
    {
      "parameters": {
        "content": "## Translating Text into Vectors and Saving it for Retrieval",
        "height": 801.1754245435806,
        "width": 701.8510827876922
      },
      "id": "8213c085-7ba9-4388-a32d-63e096605a21",
      "name": "Sticky Note",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        -80,
        120
      ]
    }
  ],
  "connections": {
    "Edit Fields": {
      "main": [
        [
          {
            "node": "In-Memory Vector Store",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "When clicking \"Test workflow\"": {
      "main": [
        [
          {
            "node": "Prompt",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Default Data Loader": {
      "ai_document": [
        [
          {
            "node": "In-Memory Vector Store",
            "type": "ai_document",
            "index": 0
          }
        ]
      ]
    },
    "Recursive Character Text Splitter": {
      "ai_textSplitter": [
        [
          {
            "node": "Default Data Loader",
            "type": "ai_textSplitter",
            "index": 0
          }
        ]
      ]
    },
    "Embeddings OpenAI": {
      "ai_embedding": [
        [
          {
            "node": "In-Memory Vector Store",
            "type": "ai_embedding",
            "index": 0
          }
        ]
      ]
    },
    "Ollama Model": {
      "ai_languageModel": [
        [
          {
            "node": "Question and Answer Chain",
            "type": "ai_languageModel",
            "index": 0
          }
        ]
      ]
    },
    "Prompt": {
      "main": [
        [
          {
            "node": "Question and Answer Chain",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "JSON Output": {
      "main": [
        [
          {
            "node": "Split Out",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Split Out": {
      "main": [
        [
          {
            "node": "Aggregate",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Aggregate": {
      "main": [
        [
          {
            "node": "Edit Fields1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Embeddings OpenAI1": {
      "ai_embedding": [
        [
          {
            "node": "In-Memory Vector Store1",
            "type": "ai_embedding",
            "index": 0
          }
        ]
      ]
    },
    "Vector Store Retriever": {
      "ai_retriever": [
        [
          {
            "node": "Question and Answer Chain",
            "type": "ai_retriever",
            "index": 0
          }
        ]
      ]
    },
    "In-Memory Vector Store1": {
      "ai_vectorStore": [
        [
          {
            "node": "Vector Store Retriever",
            "type": "ai_vectorStore",
            "index": 0
          }
        ]
      ]
    },
    "Question and Answer Chain": {
      "main": [
        [
          {
            "node": "JSON Output",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {}
}

### Expected behavior

I am expecting the process to complete without the **Error in sub-node ‘Embeddings OpenAI’** message.

### Operating System

Ubuntu 22.04 LTS

### n8n Version

1.29.1

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by jfang** [comment]
I have recreated the nodes from scratch (not copying and pasting from previous workflows) and now I have a different error message on the "Question and Answer Chain" node.

![image](https://github.com/n8n-io/n8n/assets/5340486/701327bb-a441-49c4-9e34-b16ad5c4f1ba)

ERROR: message.toJSON is not a function
 Details
Stack
TypeError: message.toJSON is not a function
    at /usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:168:73
    at Array.map (<anonymous>)
    at Proxy.connectionType (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:168:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Proxy._generateUncached (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/node_modules/@langchain/core/dist/language_models/llms.cjs:138:22)
    at LLMChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/llm_chain.cjs:157:37)
    at LLMChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
    at StuffDocumentsChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/combine_docs_chain.cjs:62:24)
    at StuffDocumentsChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
    at RetrievalQAChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/retrieval_qa.cjs:81:24)
    at RetrievalQAChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/nodes/chains/ChainRetrievalQA/ChainRetrievalQa.node.js:104:30)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:730:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:662:53
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1064:20

**Comment by Joffcom** [comment]
Hey @jfang,

For the new issue upgrading to 1.30.x will resolve that, I will look into the original workflow now.

**Comment by Mayorc1978** [comment]
> I have just tested the workflow on `1.30.1` and it appears to be working, I would recommend upgrading and see if that changes anything for you.

I was testing the scraping website template:
I have the same issue as the original poster I do get this error:
```
TypeError: message.toJSON is not a function
    at /usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:168:73
    at Array.map (<anonymous>)
    at Proxy.connectionType (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/dist/utils/logWrapper.js:168:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Proxy._generateUncached (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/node_modules/@langchain/core/dist/language_models/llms.cjs:138:22)
    at LLMChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/llm_chain.cjs:157:37)
    at LLMChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
    at async Promise.all (index 1)
    at MapReduceDocumentsChain._call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/combine_docs_chain.cjs:188:29)
    at MapReduceDocumentsChain.call (/usr/local/lib/node_modules/n8n/node_modules/@n8n/n8n-nodes-langchain/node_modules/langchain/dist/chains/base.cjs:120:28)
```

When using docker I cannot pull the 1.30.1 it will always pull the 1.29.1 version instead.
I'm using this command:
`docker run -dit --rm --name n8n -p 5678:5678 -e GENERIC_TIMEZONE="Europe/Rome" -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n`

**Comment by jfang** [comment]
> I have just tested the workflow on `1.30.1` and it appears to be working, I would recommend upgrading and see if that changes anything for you.

Thank you!

**Comment by jfang** [comment]
@Mayorc1978 You'll need to specify the version in your docker pull command to get the bleeding edge version. In this case I think it's version 1.31. 

`docker pull n8nio/n8n:1.31.0`

I'm not sure when 1.30 will be released as the "latest" general release. `docker pull n8nio/n8n`
 
Go to the "Tags" section to see other available versions.
This one is filtered on the keyword "1.3" - https://hub.docker.com/r/n8nio/n8n/tags?page=1&name=1.3
![image](https://github.com/n8n-io/n8n/assets/5340486/92c23cac-43df-4ccb-a612-640734285ae3)

I think the "Updated 16 Hours ago" (now 17) version is based on the nighly builds. 

https://hub.docker.com/r/n8nio/n8n/tags?page=1&name=nightly

![image](https://github.com/n8n-io/n8n/assets/5340486/11eee11d-c00b-4e41-a713-b1e3e6047698)

**Comment by Mayorc1978** [comment]
1.31 worked like a charm, with no error with the Summarization Chain.
