### ISSUE TITLE
Continue (using error output) & Always Output Data logic missing in Redis Node

### ISSUE THREAD

**Issue by liamdmcgarrigle** [n8n-io/n8n#8744]
## When set to Continue (using error output)
It should be continuing on the error branch, instead it goes through the success branch with no data

![Screenshot 2024-02-26 at 5 00 33 PM](https://github.com/n8n-io/n8n/assets/126508198/7a6c82da-1cca-4237-836b-9af8e6691d3c)

## When set to Always Output Data
It should continue with error data but it just stops

![Screenshot 2024-02-26 at 5 01 03 PM](https://github.com/n8n-io/n8n/assets/126508198/63923a44-eeae-4ad3-929f-e36e17421827)

## The Code
There is usually the logic for both of these operations in [this catch statement](https://github.com/n8n-io/n8n/blob/c0be43bdbed99c6bcceba662866667b8162dcf91/packages/nodes-base/nodes/Redis/Redis.node.ts#L628). Instead it is just throwing an error.

![Screenshot 2024-02-26 at 5 04 37 PM](https://github.com/n8n-io/n8n/assets/126508198/37dbc890-5757-41c1-9069-d125ce4f34b8)

### Continue (using error output)
1. Add a Redis node that will cause an error
2. Set the redis node to _Continue (using error output)_
3. Run the workflow

You'll see it has an error and is continuing on the success branch with no data

   
### Always Output Data
1. Add a Redis node that will cause an error
2. Set the redis node to _Always Output Data_
3. Run the workflow

You'll see it does not output the data

### Expected behavior

Explained in bug description section.

### Operating System

Debian 12.5

### n8n Version

1.24.1

### Node.js Version

18+

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @liamdmcgarrigle,

Thanks for the report, there are actually a few nodes without this feature and they are being slowly added as we get to them.

I am not sure if this should be tracked as a bug or not so I will keep this open and I will get a dev ticket created in the morning for this.

**Comment by Joffcom** [comment]
Internal Ticket is `NODE-1177`
