### ISSUE TITLE
N8N Environments - SSH Key changes on every new deployment despite persistent storage

### ISSUE THREAD

**Issue by Shalashtein** [n8n-io/n8n#8761]
### Bug Description

My team keeps having to resetup the git connection to our repo on every n8n main instance redeployment, despite the n8n data directory being presisted in an EFS volume that's mounted to the Fargate tasks running in the ECS services provisioned for n8n

### To Reproduce

1. Setup n8n on ECS with fargate tasks in queue mode
2. Setup EFS for data persistence and mount the /home/node/.n8n dir
3. Setup n8n environment
4. Stop main n8n task and redeploy
5. Check the environment settings and the ssh key will have changed

### Expected behavior

Since the n8n data dir is persisted on an EFS volume, we should be able to redeploy the main instance without resetting up git

### Operating System

Linux 22

### n8n Version

latest

### Node.js Version

latest

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @Shalashtein,

I have to check, Are you sure the `/home/node/.n8n` directory is correctly configured, Are you also using the same Postgres database or is that being changed as well?

Can you also confirm which version of n8n you are using, `latest` is a tag that could be any version.

**Comment by Shalashtein** [comment]
I've tested this out on 1.26.0 and 1.30.0, when mounting the efs on a separate server for debugging and `ls`ing I find the ssh folder with the keys

**Comment by Joffcom** [comment]
If the keys are there it sounds good, are you using the same database as well or a new one?

**Comment by Shalashtein** [comment]
Yes the same postgres database

**Comment by Joffcom** [comment]
How odd, I would assume if the same database was being used and the files are there as far as n8n is concerned that should be exactly the same as the files and the database have everything that is needed.


Do you need to activate the license or make the main owner user account again?

**Comment by Joffcom** [comment]
Hey @Shalashtein,

From what I understand this issue should now be fixed and `1.39.1` has an extra fix in it that is also now in `1.37.4` and `1.38.2`.

**Comment by netroy** [comment]
I believe this has been fixed a few months ago, and we have had couple of customers confirm this as well. 
I'll close this issue. but we can re-open it if someone is still facing this issue on a new release.
