### ISSUE TITLE
(bug, inconsistency) Dashboard shows Workspace is Online but my Workspace is crashed

### ISSUE THREAD

**Issue by cristian-dan-f** [n8n-io/n8n#8769]
### Bug Description

Dashboard ( https://app.n8n.cloud/dashboard ) shows:
```
My workspace
Currently online
```

But my Workspace ( https://username.app.n8n.cloud/ )shows:

```
Workspace offline (503)

Your workspace is restarting and currently offline. If you continue to see this page, [contact support](mailto:help@n8n.io).

Are you a workspace owner? [Open Admin Panel](https://app.n8n.cloud/magic-link)
```

Not sure if you keep an eye on this things, and try to fix crashed Workspaces, but my guess is that if Dashboard shows it is online, nobody could know it is actually crashed.

### To Reproduce

-

### Expected behavior

-

### Operating System

online version

### n8n Version

1.29.1

### Node.js Version

online version

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @cristian-dan-f,

Can you email support about this, This issue is not directly related to this repository.
