### ISSUE TITLE
This Code always crashes the Workspace - v1.29.1

### ISSUE THREAD

**Issue by cristian-dan-f** [n8n-io/n8n#8770]
### Bug Description

I have this Code Node that completely crashes the Workspace:

```
var taxonomies = $('Prepare WP Taxonomies Loop - New').item.json.taxonomies;
var terms_existing = [];
var terms_new = [];

for( var i = 0; i < taxonomies.length; i++ ){

  var taxonomy = taxonomies[i];

  // New Terms generated by AI for Recipe
  var terms_ai = $('Prepare WP Terms - New').all()[0].json[taxonomy];

  // Existing Terms in WP
  var terms_wp = $('All WP Terms - Existing').all()[0].json[taxonomy].wp_terms;

  // Make sure @terms_ai is Array
  if( Array.isArray(terms_ai) ){
    // Is already an Array, do nothing
  }else if( typeof terms_ai === 'string' || terms_ai instanceof String ){
    // Is a comma separated list
    var terms_ai = terms_ai.split(",");
  }else{
    // Is an integer or float
    var terms_ai = [terms_ai.toString()];
  }

  // Loop all @terms_ai
  for( var i = 0; i < terms_ai.length; i++ ){

    var term = (terms_ai[i]).trim();

    // Make sure is not empty
    if(!term){
      continue;
    }

    // Extract Matching WP Term ID, if we have a @term
    var found_wp_term = find_str_in_arr(term, terms_wp);

    if( found_wp_term === false ){
      terms_new.push({[taxonomy]: term});
    }else{
      terms_existing.push({[taxonomy]: found_wp_term.id});
    }

  }

}

return {
  'terms_existing': terms_existing,
  'terms_new': terms_new
};
```

My first guess was that the problem is the [Computed property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#computed_property_names) in here:

```
   if( found_wp_term === false ){
      terms_new.push({[taxonomy]: term});
    }else{
      terms_existing.push({[taxonomy]: found_wp_term.id});
    }
```
But I comment them out and Workspace crashes, so I really have no idea.

It should throw an error and stop execution, but instead it completely crashes the Workspace. 3 times now and it takes a few minutes to come back. I am a bit desperate because I need to be able to make it run.

I will attach an example Workflow as soon as the Workspace comes back.

### To Reproduce

-

### Expected behavior

-

### Operating System

online version

### n8n Version

1.29.1

### Node.js Version

online version

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @cristian-dan-f,

Can you post this on the community support forum? It doesn't look like this is a bug with n8n itself and is likely related to your code.

You can find the community support forum here: https://community.n8n.io

**Comment by cristian-dan-f** [comment]
Done!

Have to say that is strange that a crashed workspace is not something related to N8N when this should not happen. If my code contains errors, crashing the entire Workspace should not be the accepted solution. 

Just saying from User point of view it feels frustrating to have 15 minutes wait each time it crashes.

Anyway thank you for answering so fast.

**Comment by cristian-dan-f** [comment]
Found the problem and it is very much related to N8N because what crashes the entire Workspace are nested loops.

I feel so bad right now, because the Loop Node also has issues when nesting them.
