### ISSUE TITLE
Query Parameters in MYSQL

### ISSUE THREAD

**Issue by the-trading-ai** [n8n-io/n8n#8779]
### Bug Description

<img width="1255" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/b976b5ac-5551-442f-965b-248dc4f2dfc7">

I'm trying to set the limit of my select query. In expression I use 2 variables from the previous node. But the query parameters add quote before my number and mysql don't like it !!!

I see an option for limit. But no option for start. I tested with 10,10 but it not accepted.

### To Reproduce

Simply open mysql node

### Expected behavior

call a query with limit and start

### Operating System

hosted

### n8n Version

1.30

### Node.js Version

hosted

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Did you try without parseInt() as well? In theory it shouldn't matter but it is worth checking, I will give if a go in the morning and see if I can reproduce it.

**Comment by the-trading-ai** [comment]
@Joffcom Yes, I did. And got the same result

**Comment by the-trading-ai** [comment]
<img width="1263" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/55d22ffb-69cb-40e6-9921-38650c53daaa">

The goal of query parameters is to add quote before and after variable to block sql injection.

So, this node, need a start param, like the limit

**Comment by mbrother2** [comment]
@the-trading-ai,

You are right. For temporary solution, you can try:
![sql_query](https://github.com/n8n-io/n8n/assets/11661949/bf3a83a3-31a5-4f53-bff3-2ee19f224ac4)

P/S: not recommend use it in production :D

**Comment by Joffcom** [comment]
I have managed to reproduce this and have created `NODE-1200` as the internal dev ticket to get this fixed in a future release.

**Comment by the-trading-ai** [comment]
> @the-trading-ai,
> 
> You are right. For temporary solution, you can try: ![sql_query](https://private-user-images.githubusercontent.com/11661949/309147181-bf3a83a3-31a5-4f53-bff3-2ee19f224ac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTc5MjgsIm5iZiI6MTcwOTI5NzYyOCwicGF0aCI6Ii8xMTY2MTk0OS8zMDkxNDcxODEtYmYzYTgzYTMtMzFhNS00ZjUzLWJmZjMtMmVlMTlmMjI0YWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyNTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MWY0ZWVmNDAyZTAwYTE3YmFkNjExZWQ5N2FkYmNlZDcyMmIyYjVmMDkyZWZkOGNhNmRkNTc1MzRiZGVmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._LHKoQIeaDxbpRW-7BrSWTO-WkScnBUNYQ1QrAjSVsk)
> 
> P/S: not recommend use it in production :D

Good idea. I agree it's not the best way, but it works. Thanks

**Comment by janober** [comment]
Fix got released with [`n8n@1.37.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.37.0)
