### ISSUE TITLE
Basic LLM Chain - Require Specific Output Format as Expression (not Fixed) Causes Crashing

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#8792]
### Bug Description

When running n8n@1.30.1, when you attempt to make the `Required Specific Output Format` field in the `Basic LLM Chain` node as an `Expression` based on an earlier node's output, as soon as you add the linked field into this Expression box, the canvas in the Workflow Editor crashes -- causing the `Basic LLM Chain` node to completely disappear.

I think recently the functionality of the `Basic LLM Chain` node changed, where depending on whether the `Required Specific Output Format` field is `true` or `false`, that causes the `Output Parser` leaf to either appear or disappear.  This "show/hide" logic appeared to not correctly account for when `Required Specific Output Format` field is unknown -- which likely contributes to this crash.

### To Reproduce

1. Start a new Workflow in n8n@1.30.1
2. Add a starting node with a simple variable with the boolean value of `true`.
3. Link it to a `Basic LLM Chain` node
4. Open the `Basic LLM Chain` node's properties and attempt to link the starting node's simple variable as input to the `Required Specific Output Format` field.
5. Watch as the editor locks up and ultimately the `Basic LLM Chain` node disappears from the canvas. 

### Expected behavior

I would expect the `Required Specific Output Format` field to support expression inputs and not cause the node to disappear.

Once this field is tied to an expression, then the `Output Parser` leaf node should *always* be shown (and not hidden).

### Operating System

Google Cloud Run

### n8n Version

1.30.1

### Node.js Version

18.10

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund,

Thanks for the report, I have managed to reproduce it and have created `NODE-1209` as the internal ticket to get this fixed.

**Comment by Joffcom** [comment]
Hey @dkindlund,

This is fixed in https://github.com/n8n-io/n8n/pull/8858 and will be available as part of this weeks release.
