### ISSUE TITLE
HTTP Request decode Mime Type: text/html; charset=ISO-8859-1

### ISSUE THREAD

**Issue by eduardomazolini** [n8n-io/n8n#8799]
### Bug Description

Hello!
I need to scan a website with latin1 encoding.
The site's mimetype is correct.
However, the text has encoding errors.
I already found a way around it.

I forced the data as a file and placed a block of code afterwards.

`
//console.log("$binary",$binary)
//const data = $binary.data.data //data.data not exist other bug
//console.log("item.binary",item.binary)
const binary = $input.item.binary
const data = binary.data.data
const bin  = Buffer.from(data,'Base64')
let text = ''
if (binary.data.mimeType.includes('ISO-8859')){
  text = bin.toString('latin1')
} else {
  text = bin.toString()
}
return {data:text}
`

### To Reproduce

1) Include "Request HTML" do a GET to one page with mimetype
2) Work around
![image](https://github.com/n8n-io/n8n/assets/5448062/26dc459a-ce4b-4743-985b-00bcfe42c4dc)
![image](https://github.com/n8n-io/n8n/assets/5448062/e0529dc6-de53-46c4-a874-c1c34c3749ad)
![image](https://github.com/n8n-io/n8n/assets/5448062/ede3a5c0-ac5d-43ef-854f-de009a7daeca)
I hid the output but believe me it is correctly coded.

### Expected behavior

I expected not to need this outline, without there being errors in the text such as:
Regi�o => Região
gr�tis => grátis

### Operating System

docker.n8n.io/n8nio/n8n

### n8n Version

1.29.1

### Node.js Version

v18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
@eduardomazolini Do you have a public URL that I could reproduce this issue with?

**Comment by netroy** [comment]
since I could not easily find a public URL to test this, [I created a local server](https://gist.github.com/netroy/c1933a3ffe636ad2e954b91d5bf02045) and tested against that.

#9869 will hopefully fix this 🤞🏽
