### ISSUE TITLE
Airtable node — all params should be urlencoded

### ISSUE THREAD

**Issue by mecurc** [n8n-io/n8n#880]
**Describe the bug**
in airtable the names of tables and columns can be not only in English. In languages other than English, for the parameters to work you need to make an encodeURI parameter.

Because of this, the parameter values in the interface are urlencoded, this is also unpleasant.
<img width="315" alt="Screenshot 2020-08-25 at 01 21 52" src="https://user-images.githubusercontent.com/33278950/91102190-5df12880-e671-11ea-9a72-ca5882fd036c.png">

**To Reproduce**
1. Create a table whitespades/non-english characters
2. Try use any node action.
3. Error here.

**Expected behavior**
The parameters are automatically encoded and I see the net values in the interface.

**Environment (please complete the following information):**
 - n8n Version [0.78.0]

**Additional context**
Is probably will **be a breaking change.**

**Comment by RicardoE105** [comment]
Hey @mecurc, thanks for letting us know. I was able to replicate it, either way, in the meantime, you can use the Table ID instead of the Table Name to make it work regardless of the language used for the table name.

**Comment by Rupenieks** [comment]
@mecurc @RicardoE105 

Looking at it now, having trouble reproducing.

I changed my table name to "Таблица", and set the columns to "столбец" and "столбец2".

Data returns as expected.

**Comment by mecurc** [comment]
It is very strange. I checked now, and everything works, but I am convinced that such an error was.

There were no changes in the node. I must have made a mistake somewhere. I apologize for misleading you.

**Comment by Rupenieks** [comment]
@mecurc Glad to hear it works. No need to apologize, thanks for the report. Please let us know if anything changes / breaks!

All the best,
Ronald.

**Comment by RicardoE105** [comment]
@mecurc @Rupenieks You could replicate the issue cuz I sent the fix on another PR by mistake. closing this as it got fixed. Again @mecurc thanks.
