### ISSUE TITLE
Airtable Update Record - Refresh Column List Not Working - After New Fields Added

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#8800]
### Bug Description

When using the Airtable Update Record node, I wire it up to a workflow and set initial fields to update.  Then, I add new fields to the Airtable table.  When I press the `Refresh Column List` option, I do *not* see those newly added fields in the `Add Column to Send` dropdown.

The workaround is to duplicate the Airtable Update Record node and run the `Refresh Column List` operation on the duplicate node.  Then, I need to substitute the duplicate with the original node in order to use the newly added fields.

### To Reproduce

1. Create a new n8n workflow using an Airtable Update Record node
2. Set a couple of fields to update
3. Save the workflow
4. Add a new field to your Airtable table
5. Attempt to refresh the fields in your node by selecting `Refresh Column List`
6. See that the new fields don't appear in the `Add Column to Send` dropdown
7. Then, duplicate the node and perform the same action
8. See the new fields appear in the `Add Column to Send` dropdown in the duplicate node

### Expected behavior

`Refresh Column List` should work when new Airtable fields are added after creating the node.

### Operating System

Google Cloud Run

### n8n Version

1.30.1

### Node.js Version

18.10

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund,

This has also been reported on the forums in the past and is being tracked as `NODE-731`, As we are already aware of this I am going to mark this as closed to reduce the duplicate issues.
