### ISSUE TITLE
Airtable node — lists accepts only one input

### ISSUE THREAD

**Issue by mecurc** [n8n-io/n8n#881]
**Describe the bug**
The "list" operation returns data only from the first input.

**To Reproduce**
1. Create a node that returns multiple values
2. Try to get a list of entries for each value(maybe filter needed here)
3. You will only get the list for the first entry.

**Expected behavior**
I must get a list for each value

**Environment (please complete the following information):**
 - n8n Version [e.g. 0.78.0]

**Additional context**

**Comment by mecurc** [comment]
Sorry for my very bad English.

**Comment by RicardoE105** [comment]
Hey, @mecurc looking into this, however, have not been able to replicate it. I'm using the list operation and I get more than one item. What do you mean exactly with 'maybe filter needed here'. 

Thanks for letting us know about the issue.

**Comment by mecurc** [comment]
I will try to describe in more detail what I expect and what I get.

Workflow:
<img width="910" alt="Screenshot 2020-08-25 at 17 18 44" src="https://user-images.githubusercontent.com/33278950/91185895-09908c00-e6f7-11ea-9888-9fa42be0ccaa.png">

```json
{
  "name": "",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        90,
        300
      ]
    },
    {
      "parameters": {
        "operation": "append",
        "application": "appV5P4FtrGHccRDO",
        "table": "T2"
      },
      "name": "Airtable1",
      "type": "n8n-nodes-base.airtable",
      "typeVersion": 1,
      "position": [
        860,
        270
      ],
      "credentials": {
        "airtableApi": "AROMAT"
      }
    },
    {
      "parameters": {
        "functionCode": "return [\n  {json: {id: 1} },\n  {json: {id: 2} },\n];"
      },
      "name": "generate 2 items",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        280,
        290
      ]
    },
    {
      "parameters": {
        "operation": "list",
        "application": "appV5P4FtrGHccRDO",
        "table": "T1",
        "additionalOptions": {
          "filterByFormula": "={ID} = \"{{$node[\"generate 2 items\"].json[\"id\"]}}\""
        }
      },
      "name": "get records for every item",
      "type": "n8n-nodes-base.airtable",
      "typeVersion": 1,
      "position": [
        480,
        280
      ],
      "credentials": {
        "airtableApi": "AROMAT"
      }
    },
    {
      "parameters": {
        "functionCode": "return item.fields;"
      },
      "name": "return fields for appending",
      "type": "n8n-nodes-base.functionItem",
      "typeVersion": 1,
      "position": [
        690,
        280
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "generate 2 items",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "generate 2 items": {
      "main": [
        [
          {
            "node": "get records for every item",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "get records for every item": {
      "main": [
        [
          {
            "node": "return fields for appending",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "return fields for appending": {
      "main": [
        [
          {
            "node": "Airtable1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {}
}
```
I have a list of two identifiers, for each identifier I want to get a list of records from airtable. But the node only returns entries for the first identifier.

I get 3 entries instead of 6. The rest of the entries are ignored.

By the link, the database used in the script. T1 is the table where I look for the entries, T2 is the result of the workflow, T3 is the expected result.

https://airtable.com/shrm42GwVEdtOv9sg

**Comment by RicardoE105** [comment]
@mecurc this was very helpful, just found the issue. Thanks for letting us know. Will add this to my TODO list. Will keep you posted.  Again, thanks very much.

**Comment by mecurc** [comment]
Hi! Will a fix be added to the upcoming release?
And do you have any release schedule?

**Comment by janober** [comment]
Very unlikely. It is something bigger and a breaking change. If we change/fix this we would also have to do it on many other nodes.

For now, it is probably best if you use the Split in Batches Node and iterate over the items like this.

**Comment by mecurc** [comment]
Thank you so much for the hint and for your work. n8n is an amazing tool! 🔥

**Comment by janober** [comment]
Thanks a lot, that is great to hear!

I hope we can soon fix that issue properly on Airtable and all other nodes which currently do also not execute once per item.

**Comment by ahsanv** [comment]
Thank you for the contribution! As mentioned above, we plan to make similar improvements, closing the issue.
