### ISSUE TITLE
Clarify AWS S3 Object Copy popup help

### ISSUE THREAD

**Issue by leesilverman** [n8n-io/n8n#8820]
### Bug Description

Popup instructions should specify that the path starts with /.  The way they are written now it's not clear that an initial / is needed. 

OR, provide separate fields for the bucket name and key name, which is a closer match to the S3 API request structure

![image](https://github.com/n8n-io/n8n/assets/4869280/21ce5679-c3b5-4ec4-897f-7d3988b35d1d)

### To Reproduce

1. Drop in the AWS S3 Copy File/Object module
2. Specify a bucket and key in the source and destination fields WITHOUT the leading /.  
3. It will generate an error
4. Add a leading / to both fields.  It'll work.

### Expected behavior

Change popup instructions to:
`Format: /<source bucket name>/<source key>`
and
`Format: /<destination bucket name>/<destination key>`

### Operating System

All

### n8n Version

1.29.1

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @leesilverman,

Seems like a fair request to me although I wouldn't call this a bug as nothing is broken in the functionality of n8n so things like this would be better suited to the forum or with a quick PR.

I will get this quick change done in the morning so we can close this.
