### ISSUE TITLE
Error SIMD unsupported on docker n8n container

### ISSUE THREAD

**Issue by pyromiko** [n8n-io/n8n#8836]
### Bug Description

After install docker version (or upgrade) using docker composer i get "n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368"

It happen with any version up from 1.31.0 (on that version work ok)

### To Reproduce

1. Using a debian12 on a core2duo:
2. install with docker composer from n8n/docker/compose/withPostgres/
3. you get errors under n8n container (can be checked with "/usr/src/n8n/docker/compose/N8N# docker-compose logs" or portainer):

> postgres_1 | PostgreSQL init process complete; ready for start up.
postgres_1 |
postgres_1 | 2024-03-07 12:09:09.478 UTC [1] LOG: starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres_1 | 2024-03-07 12:09:09.478 UTC [1] LOG: listening on IPv4 address “0.0.0.0”, port 5432
postgres_1 | 2024-03-07 12:09:09.479 UTC [1] LOG: listening on IPv6 address “::”, port 5432
postgres_1 | 2024-03-07 12:09:09.568 UTC [1] LOG: listening on Unix socket “/var/run/postgresql/.s.PGSQL.5432”
postgres_1 | 2024-03-07 12:09:09.675 UTC [75] LOG: database system was shut down at 2024-03-07 12:09:09 UTC
postgres_1 | 2024-03-07 12:09:09.734 UTC [1] LOG: database system is ready to accept connections
n8n_1 | No encryption key found - Auto-generated and saved to: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | User settings loaded from: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | User settings loaded from: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | User settings loaded from: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | User settings loaded from: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | User settings loaded from: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368
n8n_1 | No encryption key found - Auto-generated and saved to: /home/node/.n8n/config
n8n_1 | CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported

4. After while you get:

> ...
n8n_1       | Finished migration DropRoleMapping1705429061930
n8n_1       | Version: 1.31.1
n8n_1       | 
n8n_1       | Editor is now accessible via:
n8n_1       | http://localhost:5678/
n8n_1       | Error fetching feature flags Error [PostHogFetchNetworkError]: Network error while fetching PostHog
n8n_1       |     at new PostHogFetchNetworkError (/usr/local/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:740:16)
n8n_1       |     at PostHog.<anonymous> (/usr/local/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:1129:51)
n8n_1       |     at step (/usr/local/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:135:27)
n8n_1       |     at Object.throw (/usr/local/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:84:53)
n8n_1       |     at rejected (/usr/local/lib/node_modules/n8n/node_modules/posthog-node/lib/index.cjs.js:71:36) {
n8n_1       |   error: TypeError: fetch failed
n8n_1       |       at Object.fetch (node:internal/deps/undici/undici:11731:11) {
n8n_1       |     cause: [CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368]
n8n_1       |   },
n8n_1       |   [cause]: TypeError: fetch failed
n8n_1       |       at Object.fetch (node:internal/deps/undici/undici:11731:11) {
n8n_1       |     cause: [CompileError: WebAssembly.compile(): Compiling function #66 failed: Wasm SIMD unsupported @+5368]
n8n_1       |   }
n8n_1       | }

I tested on two old cpu (core2duo and Athlon 64 X2). Over a interl core i3 this seems not to be happen since it has 1.31.2 now and working.

### Expected behavior

n8n container should not reboot continously....

### Operating System

Debian GNU/Linux 12

### n8n Version

1.31.1, 1.32.0

### Node.js Version

container

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @pyromiko 

I spotted someone open this on the support forum as well which can be found here: https://community.n8n.io/t/error-simd-unsupported-on-docker-n8n-container/42155/7

To avoid duplicate issues and splitting the focus I am going to close this in favour of the forum issue and we can pick it up from there.
