### ISSUE TITLE
Salesforce Node - URI Format Issue

### ISSUE THREAD

**Issue by camcelroy** [n8n-io/n8n#886]
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Salesforce/GenericFunctions.ts

The salesforceApiRequest method builds a URI of the format <subdomain>.salesforce.com.  Salesforce environments which have been setup recently using "My Domain" should instead be built as <subdomain>.my.salesforce.com.  Documentation from Salesforce reflecting this is outlined at https://help.salesforce.com/articleView?id=domain_name_app_url_changes.htm&type=5

Our corporate Salesforce instance is configured in this way, and as such the <subdomain>.salesforce.com generated URI does not work.

I have worked around this by customizing my local Salesforce node, but an integrated solution would be best.

Similarly, a tip or doc for the Salesforce Salesforce OAuth2 API credentials noting the needed format for the Access Token URL would be helpful.

![Screen Shot 2020-08-25 at 6 36 56 PM](https://user-images.githubusercontent.com/5472147/91238370-7b220780-e702-11ea-930b-e3eefbaa584d.png)

**Comment by RicardoE105** [comment]
@camcelroy Thanks for letting us know about this issue. Will add it to the backlog and keep you posted. With regard to the documentation, we are continually improving it. Hopefully, we will have a 'how to get the credentials soon'

**Comment by RicardoE105** [comment]
Looks like this [PR](https://github.com/n8n-io/n8n/pull/834/commits/4c49030e85dcd67c820b8c9c09529ba9323da2f3) from a community member will fix the issue you are having. Can you confirm? @camcelroy

**Comment by camcelroy** [comment]
@RicardoE105 Confirmed.

**Comment by RicardoE105** [comment]
@camcelroy thanks.

**Comment by janober** [comment]
Thanks a lot @YEriin for the fix!

Just got released with n8n@0.79.0
