### ISSUE TITLE
Page title not always updated

### ISSUE THREAD

**Issue by kjee** [n8n-io/n8n#8861]
### Bug Description

Starting from a n8n page at a individual workflow, the page title is not updated if you click on left menubar at:

- /workflows
- /credentials
- /variables
- /settings

It works with /executions 

### To Reproduce

1. Open an individual workflow
2. Click on /workflows in the left menu bar
3. Check page title in browser

### Expected behavior

By clicking on

- /workflows
- /credentials
- /variables
- /settings

page title should be updated accordingly (e.g. n8n - workflows)

### Operating System

Debian 11

### n8n Version

1.29.1

### Node.js Version

18.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @kjee,

Thanks for taking the time to report this, I have created `N8N-7262` as the internal ticket to dig into it but I suspect this will be a low priorty as nothing is really broken in terms of functionality.
