### ISSUE TITLE
Slack Update User's Profile not passing `user` to API

### ISSUE THREAD

**Issue by troylar** [n8n-io/n8n#8907]
### Bug Description

When updating a profile in Slack, the `user` property is not getting set correctly in the API call.

### To Reproduce

According to the API spec, `user` should be passed as a parameter. It's currently NOT being passed at all and so all changes to the profile are being made to the API user.

### Expected behavior

When setting the `user` property, the profile should update the correct user.

### Operating System

Linux

### n8n Version

1.33.0

### Node.js Version

18

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by troylar** [comment]
The `user` property needs to be set here: https://github.com/n8n-io/n8n/blob/0c179e4e511e4e6075d390afc025c93630ef3241/packages/nodes-base/nodes/Slack/V2/SlackV2.node.ts#L1180

**Comment by Joffcom** [comment]
Hey @troylar,

Thanks for the report, I have taken a quick look and it looks like we do set the user but in the wrong place. It looks like we add it to the profile body instead of at the top level.

I have created `NODE-1246` as the internal dev ticket to fix this for a future release.

**Comment by janober** [comment]
Fix got released with [`n8n@1.63.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.63.0)
