### ISSUE TITLE
Mac enviroment:  pnpm install error

### ISSUE THREAD

**Issue by LinJianTingYu** [n8n-io/n8n#8935]
### Bug Description

The install on Mac fails:
`node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3: Running install script, failed in 1m 19.1s
.../sqlite3@5.1.7/node_modules/sqlite3 install$ prebuild-install -r napi || node-gyp rebuild

prebuild-install warn install connect ETIMEDOUT 185.199.108.133:443
│ No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
│ No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
│ xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/De…
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onExit (/Users/yujian/zkzd/projects/n8n/node_modules/.pnpm/node-gyp@8.4.1/nod…
│ gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Darwin 23.3.0
│ gyp ERR! command "/Users/yujian/.nvm/versions/node/v18.17.0/bin/node" "/Users/yujian/zkzd/projects/n8n/node_modu…
│ gyp ERR! cwd /Users/yujian/zkzd/projects/n8n/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3
│ gyp ERR! node -v v18.17.0
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok 
└─ Failed in 1m 19.1s at /Users/yujian/zkzd/projects/n8n/node_modules/.pnpm/sqlite3@5.1.7/node_modules/sqlite3
 ELIFECYCLE  Command failed with exit code 1.`

### To Reproduce

1、clone code
2、pnpm install

### Expected behavior

install success

### Operating System

mac

### n8n Version

1.33.0

### Node.js Version

18.17.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @LinJianTingYu,

I have just given this a go on my Mac and it is working, Looking at your log there is a network timeout so it could just be a temporary network issue.

> prebuild-install warn install connect ETIMEDOUT 185.199.108.133:443

It also looks like xcrun is upset possibly due to trying to build sqlite so you may need to also run `xcode-select --install` to install the Mac command line dev tools.

> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/De…

As this doesn't look like an n8n bug I am going to mark this as closed, Let me know if you have any other questions about this or if the above helps.
