### ISSUE TITLE
Send Discord DM Error

### ISSUE THREAD

**Issue by itsMattShull** [n8n-io/n8n#8936]
### Bug Description

Using the discord node to send a message to a channel in the discord server works great.  But when selecting User and trying to send a DM I get the following error:
![image](https://github.com/n8n-io/n8n/assets/5685667/2b8eacb8-d13d-4b49-bfbd-08951f204137)

The ID it mentions is not the channel ID, but my client ID.  That seems odd.  As you can see I am selecting from list to the specific user I want to send the message.  Changing to ID and putting my user ID doesn't change the output, I still get the error.
![image](https://github.com/n8n-io/n8n/assets/5685667/bc191b6b-8952-462d-bef8-9eb84f7a8f91)

### To Reproduce

Go to Discord
Select Resource: Message
Select Operation: Send
Server: select a server from list
Sent To: select User
User: select user from list
Test step and get the error.

### Expected behavior

It should send a DM to the user (like it does if I choose to send it to a channel on the discord server).

### Operating System

Raspbian

### n8n Version

1.32.2

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Thanks for the report I have managed to reproduce this and have created `NODE-1257` as the dev ticket to fix this. I have also made a note of the typos so we can get those fixed at the same time.

**Comment by janober** [comment]
Fix got released with [`n8n@1.39.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.39.1)
