### ISSUE TITLE
Cannot upgrade to version higher 1.26.0

### ISSUE THREAD

**Issue by karkill** [n8n-io/n8n#8993]
### Bug Description

When I try to upgrade n8n to newest version. It get error
```bash
User settings loaded from: /home/node/.n8n/config
Loading config overwrites [ '/n8n-config/config.json' ]
n8n ready on 0.0.0.0, port 5678
Migration "DropRoleMapping1705429061930" failed, error: column "role" of relation "user" contains null values
Error: There was an error running database migrations
QueryFailedError: column "role" of relation "user" contains null values
```
I only can upgrade to version before has `DropRoleMapping1705429061930`

### To Reproduce

1. Use n8n-helm-chart (8gears) install n8n version 1.1.1
2. Upgrade n8n to version  1.33.1

### Expected behavior

Can upgrade to newest version

### Operating System

K8s v1.23.17 - Linux 

### n8n Version

1.1.1

### Node.js Version

Not Set

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @karkill,

At any point have you manually made changes to the n8n database?

Looking at our fixes this should have been fixed in `1.27.2`, Would you be able to try updating to 1.7 first then going to the latest release and see if that helps.

**Comment by karkill** [comment]
> Hey @karkill,
> 
> At any point have you manually made changes to the n8n database?
> 
> Looking at our fixes this should have been fixed in `1.27.2`, Would you be able to try updating to 1.7 first then going to the latest release and see if that helps.

Thank for your help @Joffcom but I don't know what is `1.7`. Please help me.

**Comment by Joffcom** [comment]
Hey @karkil,

1.7 is a release of n8n, If you can set the version in your config to 1.7.1 then upgrade to that release and see if going from there works it would be handy.

**Comment by karkill** [comment]
Hi @Joffcom ,
Thank for your help. I have updated to the latest version. Thank you so much.
