### ISSUE TITLE
Youtube integration fails using date filters

### ISSUE THREAD

**Issue by h3ct0r12** [n8n-io/n8n#9007]
### Bug Description

Using the filter by "Publisher after" or "publisher before" fails when apply the "fixed" calendar. 
Error gives info about google expects time-zone notation

#######ERROR MESSAGE###########
**Bad request - please check your parameters
Invalid value at 'published_after' (type.googleapis.com/google.protobuf.Timestamp), Field 'published_after', Illegal timestamp format; timestamps must end with 'Z' or have a valid timezone offset.**

### To Reproduce

Use Youtube item configuring:

Resource
- Video

Operation
- Get Many

Channel ID
- **Any channel**

Filters (OR)
- Published After --> Use fixed data by integrated calendar
- Published Before --> Use fixed data by integrated calendar

### Expected behavior

By ussing the Fixed date in youtube, the query should use the date introduced and apply the workflow timezone to obtain list of videos between selected dates in the workflow timezone.

### Operating System

docker

### n8n Version

1.33.1

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @h3ct0r12,

Thanks for the report, I have created `NODE-1288` as the internal dev ticket to get this resolved. As a temporary solution you could use an expression instead or manually input the date.

**Comment by Joffcom** [comment]
Fix got released with [`n8n@1.59.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.59.0)
