### ISSUE TITLE
URL webhook is strange, I got 404 error

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#901]
I have webhook URL which does not have node name like this:
https://n8n.working24.net/webhook/2a3de057-89c3-46bc-bc30-5f7943d64f8f

I read some doc have URL like this:
http://localhost:5678/webhook-test/2/webhook/test

When I check above link with my browser, it is successful

But when I POST json from other service to this link, it took 404 error:
The app returned "The requested webhook "POST 2a3de057-89c3-46bc-bc30-5f7943d64f8f" is not registered.".

I executed or active node before test. What cause this?
![n8n-io-Workflow-Automation](https://user-images.githubusercontent.com/1112881/91519534-1b537880-e91d-11ea-89ca-fa8e32572175.png)

**Comment by janober** [comment]
All new webhook-URLs do not have the node-name nor the workflow-ID in them. That is a change we did a while ago to fix multiple issues the old URLs caused.

Webhook-Nodes which got created in the past should still work normally with the same webhook-URLs. All newly created Webhook-Nodes will by default allow setting a full path and that path will by default be a unique UUID4.

If you say you check with your browser it sounds for me like you are making a GET request and there it works. That would then explain why the POST request does not work as the Webhook-Node is probably configured to listen to GET requests and not POST ones.

**Comment by cmdntd** [comment]
Well, sorry, I understand now.
Thank you

**Comment by janober** [comment]
Great to hear that it works now. I am closing this issue now.

Have a great upcoming weekend!
