### ISSUE TITLE
N8N_EDITOR_BASE_URL sets url for test webhooks

### ISSUE THREAD

**Issue by lawfulsoftware** [n8n-io/n8n#9030]
### Bug Description

`WEBHOOK_URL` sets the base URL for production webhooks
`N8N_EDITOR_BASE_URL` sets the base URL for test webhooks as well as the base URL for the REST API
`N8N_HOST` sets the URL of the UI

This has existed for a long time.

### My Configuration

Set `N8N_HOST`=n8n.domain.com
Set `N8N_EDITOR_BASE_URL`=https://webhook.domain.com
Set `WEBHOOK_URL`=https://webhook.domain.com

Production webhooks use: https://webhook.domain.com/webhook
Test webhooks use: https://webhook.domain.com/webhook-test
REST API uses: https://webhook.domain.com/rest

UI can be accessed from both `https://webhook.domain.com` and `https://n8n.domain.com`

### Expected Proper Configuration

Set `N8N_HOST`=n8n.domain.com
Set `N8N_EDITOR_BASE_URL`=https://n8n.domain.com
Set `WEBHOOK_URL`=https://webhook.domain.com

Production webhooks use: https://webhook.domain.com/webhook
Test webhooks use: https://n8n.domain.com/webhook-test
REST API uses: https://n8n.domain.com/rest

UI can be accessed from both `https://webhook.domain.com` and `https://n8n.domain.com`

### Expected behavior

`WEBHOOK_URL` should set the base URL for all webhooks.
UI should only be accessible from `N8N_EDITOR_BASE_URL`

### Operating System

n8nio/n8n:1.35.0

### n8n Version

n8nio/n8n:1.35.0

### Node.js Version

n8nio/n8n:1.35.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @lawfulsoftware,

Looking at this I would say it is working as expected, `n8n_host` is used to set the hostname n8n runs on and is used as a fallback if `webhook_url` is not set. (https://docs.n8n.io/hosting/configuration/configuration-examples/webhook-url/)

`webhook_url` is used to define the path to webhooks when running n8n behind a reverse proxy and `n8n_editor_base_url` is used to set the url used in email notifications.

By setting these n8n doesn't block any routing it is expected that a reverse proxy or load balancer would be handling that so on your reverse proxy you would to only allow `/webhook/*` traffic on your `webhook_url` and on your `n8n_editor_base_url` you would allow everything else including `/webhook-test/*` as test webhooks always need to hit the editor so you can see the result.

For now as this appears to be working as expected I am going to mark this as closed but let me know if you have any other questions on this one.
