### ISSUE TITLE
N8n does not save data that we got

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#904]
After refresh old session of work, I must load sample data again
Could I keep "sample data" of nodes that got from old session test?

**Comment by janober** [comment]
Sorry, do not understand what you mean. Does however also not sound like a bug more like a question and should so probably be posted in the forum as the GitHub issues are only for bugs:
https://community.n8n.io/

**Comment by cmdntd** [comment]
I got data to node by "test-url" of webhook. 

But when I open it again in next session, that sample data lost.

This sample data can't get by production-url. This make me must change url so many time to get data.
