### ISSUE TITLE
Bug in API that have encapsulated variables without body or headers - ActiveCampaign Integration Problem

### ISSUE THREAD

**Issue by kaueca** [n8n-io/n8n#9066]
### Bug Description

When trying to use variables from the previous node coming from ActiveCampaign, it is not possible to select variables that contain []
![image](https://github.com/n8n-io/n8n/assets/166092998/79032345-bb0a-474f-8213-6b4ae07136c4)

### To Reproduce

1. ActiveCampaign Trigger >
2. Try to get any variable from Deal Note by webhooks api with contain [] for example **deal[contact_email]**

### Expected behavior

That I can select the variables and create my flows

### Operating System

Ubuntu 22.04 64bit with Docker

### n8n Version

1.34.2

### Node.js Version

16.x

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @kaueca,

This doesn't look to be a bug as such and is more a general data structure issue. Using `deal[contact_email]` would be the same as using dot notation with `deal.contact_email` so you would need to correctly escape the `[ ]` so your expression should be `{{ $('ActiveCampaign Trigger').item['deal[contact_email]'] }}

There are other characters that can also cause the same problem but this should fix the problem you are having. For now as there is nothing for us to really fix I am going to mark this as closed, Let me know if you have any other questions about this.

**Comment by kaueca** [comment]
{{ $('ActiveCampaign Trigger').item.json['deal[contact_email]'] }}
I got it, the correct way would be with json

Thanks for the help
