### ISSUE TITLE
Error in your SQL syntax - MariaDB

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#909]
When I take off route from MySQL node, it run and show this error:

Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SELECT id FROM contact WHERE id LIKE 'dan.nt@cmdgroups.com'' at line 1
    at PromiseConnection.query (/usr/local/lib/node_modules/n8n/node_modules/mysql2/promise.js:92:22)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/MySql/MySql.node.js:160:35
    at Array.map (<anonymous>)
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/MySql/MySql.node.js:158:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:369:47

**Comment by janober** [comment]
Do not think this is n8n related as it does not do anything except taking the query the user did enter, and then execute it via the npm module `mysql2`.
So please check first what the error suggests and then check the npm module `mysql2` which n8n is using. If something has to get changed to make it work it would be probably in that module and not in n8n itself.

Here the code that runs in n8n:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/MySql/MySql.node.ts#L191
You can see there is sadly not much happening so nothing we can fix.

As already written in the forum did I test something similar with MySQL and there it worked fine. So maybe worth research there some more.

**Comment by krynble** [comment]
Hey @cmdntd were you able to further test this? Have you found any other issue?
