### ISSUE TITLE
Send Email Node erroring

### ISSUE THREAD

**Issue by RhysGruffyddAI** [n8n-io/n8n#9113]
### Bug Description

The send email trigger node works fine (IMAP). However, I cannot get the 'Send Email' node to work, for any accounts. I have triple-checked that all details are correct, but I encounter the same error message every time 'The service refused the connection - perhaps it is offline'.

### To Reproduce

1. Create a 'Send Email' Node 
2. Enter the credentials for the node 
3. Attempt to test the node 
4. Encounter error message 'The service refused the connection - perhaps it is offline'

### Expected behavior

For the Send Email node to work as expected, and send an email without receiving an error message. 

### Operating System

Dell Laptop

### n8n Version

1.36.1

### Node.js Version

2.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @RhysGruffyddAI,

The error message you are seeing is saying that the service refused the connection, I was using the send email node yesterday with no issues so it should be ok.

Can you confirm where you have n8n running are you using n8n cloud or self hosting, I would also make sure you are using the correct ports and protocol, The send email node uses SMTP not IMAP so you will need to make sure this is correct.

**Comment by RhysGruffyddAI** [comment]
@Joffcom We are using n8n cloud for this workflow - I have ensured credentials are correct (email and password) - What Host/ port does SMTP use?

**Comment by Joffcom** [comment]
Hey @RhysGruffyddAI,

The host and port would depend on the mail server you are connecting to.

Which mail provider are you using?

**Comment by RhysGruffyddAI** [comment]
@Joffcom I am using Gmail - I have tried following the troubleshooting instructions but I am still experiencing the same issue

**Comment by Joffcom** [comment]
Hey @RhysGruffyddAI

For GMail using the GMail node may be better as SMTP with gmail can be tricky but you should be able to connect using a host of `smtp.gmail.com`, a port of `587` and disable the `ssl/tls` box.

**Comment by RhysGruffyddAI** [comment]
@Joffcom Unfortunately that didn't work -I keep getting the error message 'Invalid login: 534-5.7.9 Application-specific password' - However, the password is 100% correct.

**Comment by RhysGruffyddAI** [comment]
@Joffcom Finally sorted thanks to your help - thank you!

**Comment by Joffcom** [comment]
Hey @RhysGruffyddAI,

That is good news, Thanks for the update 👍🏻
