### ISSUE TITLE
Timezone is broken in v1.36.2

### ISSUE THREAD

**Issue by detoxhby** [n8n-io/n8n#9131]
### Bug Description

After upgrading the timezone has gotten set to **EDT-4** even though the `GENERIC_TIMEZONE` is different.

Downgrading back to 1.36.1 fixed the issue. Since there is no indication about anything related in release notes I assume it's an unintended change that broke the system.

It is really unfortunate as CRON triggers are going off totally at different time, causing many problems so I consider this issue high severity.

### To Reproduce

1. set up docker container with `GENERIC_TIMEZONE` set as ENV
2. application does not respect timezone

### Expected behavior

running with proper timezone as before

### Operating System

Debian Stable

### n8n Version

1.36.2/latest

### Node.js Version

built in

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by tadwohlrapp** [comment]
Yes, can confirm the same.

`GENERIC_TIMEZONE` and `TZ` are both set to `Europe/Berlin` here, and after updating to v1.36.2 this morning a workflow scheduled for 6AM daily suddenly ran again at noon.

The Schedule Trigger confirmed the timezone change to `EDT -04:00` in its output.

Reverting back to v1.36.1 fixed it for now.

**Comment by Joffcom** [comment]
Hey @tadwohlrapp & @detoxhby,

Can you try `1.37.1` and see if you have the same issue?

**Comment by krynble** [comment]
Thanks for reporting, we'll be releasing 1.36.3 to fix this in a little bit.

**Comment by itsmichaelk** [comment]
Is it possible to downgrade to a version prior to v1.36.2 until the fix is released?
We **cannot** upgrade to a pre-release version, but we need our workflows to work as expected.

**Comment by Joffcom** [comment]
@itsmichaelk 1.36.4 was released on Monday which fixes this issue, We forgot to send the notification here. 1.37.2 was also just released which will be moved to the `latest` tag later today / tomorrow as `1.38.0` is about to be released.

**Comment by netroy** [comment]
I believe this has been resolved. If someone is still seeing the issue, we can re-open this.
