### ISSUE TITLE
When there are no nodes, can still use shortcut keys to execute

### ISSUE THREAD

**Issue by ybom77** [n8n-io/n8n#9133]
### Bug Description

![image](https://github.com/n8n-io/n8n/assets/15134783/bd1f8a74-9554-4ade-8f81-6eb39811cf30)

### To Reproduce

1.open new workflow
2.press ctrl + enter

### Expected behavior

No need to execute

### Operating System

ubuntu 22.04

### n8n Version

1.37.0

### Node.js Version

20.12.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @ybom77

That is a fun one, thanks for the report. I have created `PAY-1511` as the internal ticket to get this resolved.
