### ISSUE TITLE
docker.n8n.io/n8nio/n8n:latest-debian docker image out of date 

### ISSUE THREAD

**Issue by gav-** [n8n-io/n8n#9134]
### Bug Description

docker.n8n.io/n8nio/n8n:latest is n8n version 1.36.1
docker.n8n.io/n8nio/n8n:latest-debian is n8n version 0.222.0

Is the debian image no longer maintained ?

I am looking for a glibc based image, and not a musl libc based one, any alternatives ?

### To Reproduce

1. $ docker run -it docker.n8n.io/n8nio/n8n:latest
. . .
Version: 1.36.1

2. $ docker run -it docker.n8n.io/n8nio/n8n:latest-debian
. . .
Version: 0.222.0

### Expected behavior

That docker.n8n.io/n8nio/n8n:latest-debian is an up to date version of n8n

### Operating System

Ubuntu 22.04.4 LTS

### n8n Version

n/a

### Node.js Version

n/a

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @gav-,

We stopped maintaining the Ubuntu and RHEL images when we released 1.0 (https://docs.n8n.io/1-0-migration-checklist/#image-removal)

If you need to use Ubuntu you could try building a custom docker image or installing n8n using npm.

**Comment by gav-** [comment]
Understood. Thanks for the quick reply @Joffcom and for the pointer to the details. Hopefully this issue can be useful to others who may have missed the announcement.
