### ISSUE TITLE
Response to Webhook node does not work with n8n form since version 1.1

### ISSUE THREAD

**Issue by n8n-ninja** [n8n-io/n8n#9156]
### Bug Description

The "Response to Webhook" node does not work with the submission from the "n8n Form" node. It returns an error stating "No Webhook node found in the workflow." I checked and found that:
- In version 1 of the "Response to Webhook" node, it was working.
- In version 1.1, it is not working.

### To Reproduce

1. Add a n8n form to your workflow
2. Chose Respond when "Using respond to webhook"
3. Add a Respond to webhook node
4. Run workflow. 

### Expected behavior

It should work as if there was a Webhook node in the workflow. 

### Operating System

Self hosted

### n8n Version

1.36.4

### Node.js Version

18.16.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @n8n-ninja,

Thanks for the report, I have managed to reproduce this and have created `NODE-1305` to get it fixed.

**Comment by n8n-ninja** [comment]
you are welcome 🥷
thank you for your reactivity.
