### ISSUE TITLE
Http Request Node: Proxy setting

### ISSUE THREAD

**Issue by Zetanova** [n8n-io/n8n#9169]
### Bug Description

using a http proxy (tinyproxy) with the http request node produces 400 Bad request
related issue https://github.com/axios/axios/issues/5256

### To Reproduce

using a tinyproxy for the http request node
making a request to GET https://mocktarget.apigee.net/echo
result: 400 Bad Request

### Expected behavior

Http status code with success 

### Operating System

docker

### n8n Version

1.37.3

### Node.js Version

docker

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Zetanova,

Are you using an https proxy or an http proxy? There is an existing issue where http proxies don't always work correctly due to an issue with Axios not supporting the connect method.

**Comment by Zetanova** [comment]
Yes, regular http proxy in the local network to switch the IP,
the https connect method does not work.

Don't understand why the proxy option is offered in the first place.
To use an https proxy has other issues like CA rollout 

Here more related issues about this problem
https://community.n8n.io/t/add-support-for-connect-method-on-http-request-node/23262/4
https://github.com/axios/axios/issues/4531

**Comment by Joffcom** [comment]
Hey @Zetanova,

That would be the one and we have a few others like it, Oddly making the request using an HTTPS proxy is fine the issue only seems to be when making https calls over an http proxy.

This is pretty much the same issue as https://github.com/n8n-io/n8n/issues/7037 so for now I am going to mark this as closed as it is known issue. This is one of those issues that I have been wanting to fix for a long time but have not had a chance to fit it in yet.

I do expect to have it resolved soon though.
