### ISSUE TITLE
Gmail Node Authentication in (next) branch

### ISSUE THREAD

**Issue by wkalamaras** [n8n-io/n8n#9170]
### Bug Description

When attempting to connect new Gmail oauth2 credentials signing in ends with “ {"status":"error","message":"Unauthorized"}” and immediately logs the user out of n8n.

This issue only appears to be affecting the more recent versions of n8n on the “next” tag in docker hub (through 04/17). I have noticed this issue over two consecutive weeks of release but it is not present in the “latest” tag, only “next” through 1.38.0 (not tested on 1.38.1). As of 04/17 it had been present on arm and x86 architecture.

### To Reproduce

1. Add gmail oauth2 credentials under credentials
2. Click sign in
3. Follow through the prompts, when the uri attempts to redirect the error is produced. 

### Expected behavior

Successful completion of oauth2 credentials

### Operating System

Ubuntu 23.10, Debian 12

### n8n Version

1.38.0

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
I believe this is the same issue as #9151 .
The fix for this was released in 1.37.3 and 1.38.1.
Can you please try either of those versions, and let us know if that fixes the issue?

**Comment by wkalamaras** [comment]
This does appear to be fixed now, and is in fact a duplicate. Apologies for missing that. Thank you guys for the incredible work here
