### ISSUE TITLE
Unable to refresh oauth 2 token using Qonto integration

### ISSUE THREAD

**Issue by RJiraya** [n8n-io/n8n#9178]
### Bug Description

We are note able to refresh token with Qonto integration because the option send credentials in body is not applied for the refresh token method.

### To Reproduce

1. Create an oauth application that used credentials in body (I'm using Qonto API)
2. Configure the OAuth 2 credentials
3. Connect to the service
4. Wait token expires
5. Retry the flow
6. You will get an error like ```Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).```

### Expected behavior

The token should be refreshed passing the credentials in the body

### Operating System

Docker 24.0.7

### n8n Version

1.30.0

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @RJiraya,

Is this a generic oauth2 credntial you are using and did you already try setting it to use body instead of headers for auth?

**Comment by janober** [comment]
Fix got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)
