### ISSUE TITLE
Retrieval QA node not taking vector store's output

### ISSUE THREAD

**Issue by arnaudfrn** [n8n-io/n8n#9225]
### Bug Description

Hey,

It seems like the retrievalQA node fails to take the output from the vector store as input in the prompt. This result in the LLM having no context from the retrieved data. I've tested this with both Pinecone and Qdrant.

<img width="1356" alt="Screenshot 2024-04-23 at 11 35 05" src="https://github.com/n8n-io/n8n/assets/44318409/64389e9d-675a-458e-9f59-65ff4a49c1bf">
<img width="1023" alt="Screenshot 2024-04-23 at 11 36 54" src="https://github.com/n8n-io/n8n/assets/44318409/a8ef6c90-317d-46a9-a1eb-047aeb9df26f">

This is on cloud and tested with 1.38 and 1.39 (Beta)

Also posted a message on the forum about this with workflow template.
https://community.n8n.io/t/retrieval-with-pinecone-not-getting-information-in-prompt/44860

### To Reproduce

workflow template:
https://community.n8n.io/t/retrieval-with-pinecone-not-getting-information-in-prompt/44860

### Expected behavior

The output of the vector store should be passed to the RetrievalQA node

### Operating System

Cloud

### n8n Version

1.38

### Node.js Version

Cloud

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @arnaudfrn,

As you have raised this on the forum already I am going to close this so that we don't split the internal attention between the 2 topics.
