### ISSUE TITLE
 credentials for node included in NODE_EXCLUDES should be disabled

### ISSUE THREAD

**Issue by jimmylegendary** [n8n-io/n8n#9237]
### Bug Description

When self hosting, I set NODE_EXCLUDES.
But credentials for node included in NODE_EXCLUDES is not disabled so that there is conflict.
As I see code, loadAll() in LazyPackageDirectoryLoader(DirectoryLoader.ts:389) only excludes nodes.

if (this.excludeNodes.length) {
  for (const nodeName of this.excludeNodes) {
	  delete this.known.nodes[nodeName];
  }
  
  **this.types.nodes = this.types.nodes.filter(
	  (nodeType) => !this.excludeNodes.includes(nodeType.name),
  );**
}

But I guess this should be changed like

if (this.excludeNodes.length) {
  for (const nodeName of this.excludeNodes) {
	  delete this.known.nodes[nodeName];
  }
  
  **this.types.nodes = this.types.nodes.filter(
	  (nodeType) => !this.excludeNodes.includes(nodeType.name),
  );**
  **this.types.credentials = this.types.credentials.filter(
	  (nodeType) => !this.excludeNodes.includes(nodeType.name),
  );**

Or add CREDENTIAL_EXCLUDES, then

if (this.excludeNodes.length) {
  for (const nodeName of this.excludeNodes) {
	  delete this.known.nodes[nodeName];
  }
  
  **this.types.nodes = this.types.nodes.filter(
	  (nodeType) => !this.excludeNodes.includes(nodeType.name),
  );**
  **this.types.credentials = this.types.credentials.filter(
	  (credentialType) => !this.excludeCredentials.includes(credentialType.name),
  );**

### To Reproduce

Self hosting and set NODE_EXCLUDES env variable

### Expected behavior

 credentials for node included in NODE_EXCLUDES should be disabled

### Operating System

n8n docker

### n8n Version

1.34.0

### Node.js Version

18.19.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jimmylegendary,

This is a good find, I suspect we keep the credential there as in some cases they could be used in the HTTP Request node. Is there a specific reason why you wanted to hide the credentials as well as other than keeping the list clean I couldn't think of anything as we do currently have credentials that we don't have nodes for to make life easier.

**Comment by jimmylegendary** [comment]
No, that is the reason I want to disable unused credentials.
It could make users confused as I serve n8n inside company.
I just hope that there is one option like nodes_exclude for credentials

**Comment by Joffcom** [comment]
Hey @jimmylegendary,

There isn't an option to exclude credentials at the moment, Is it the credentials that don't have nodes that you want to hide as we could possibly add an option to hide those. But this is maybe more of a feature request and better suited to the forum than a bug 🤔

**Comment by jimmylegendary** [comment]
Thank you and I created feature request https://community.n8n.io/t/creds-exclude-env/45206
And I guess I can implement this functionality if I am allowed to contribute to n8n opensource

**Comment by Joffcom** [comment]
Hey @jimmylegendary,

Perfect, I will get this closed and we can keep an eye on the feature request although I am still not sure what this would actually help with but we can pick that up on the forum.
