### ISSUE TITLE
Wrong link on documentation

### ISSUE THREAD

**Issue by DavidHernandez** [n8n-io/n8n#9243]
### Bug Description

On this section of the documentation: https://github.com/n8n-io/n8n/tree/master/docker/images/n8n#use-with-postgresdb

There is a sentence that says `A full working setup with docker-compose can be found [here](https://github.com/n8n-io/n8n/blob/master/docker/compose/withPostgres/README.md)`

The link does not work, as that file and folder does no longer exists.

### To Reproduce

Go to this page: https://hub.docker.com/r/n8nio/n8n#updating-a-running-docker-compose-instance

See broken link

### Expected behavior

Don't see the sentence or a working link.

### Operating System

All

### n8n Version

1.38.2

### Node.js Version

Does not apply

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @DavidHernandez,

Thanks for making us aware of this, We moved all of the docker examples to the repo here: https://github.com/n8n-io/n8n-hosting but forgot to update that file.

**Comment by Joffcom** [comment]
Hey @DavidHernandez,

Moving to closed as we have merged the PR, It may not appear on Dockerhub until we push there next.

**Comment by janober** [comment]
Fix got released with [`n8n@1.40.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.40.0)
