### ISSUE TITLE
K8s worker Stats

### ISSUE THREAD

**Issue by Dasio** [n8n-io/n8n#9288]
### Bug Description

When I look at individual worker stats, it displays stats about the whole node, instead of container one.
So e.g. I see  Free Memory: 55.54GB / 62.81GB. Which is for whole node

### To Reproduce

1. Go to Settings -> Workers
2. Look e.g. at Free Memory

### Expected behavior

I expect to see actual Pod usage/limits.

Check cgroup v2

### Operating System

Alpine Linux v3.19

### n8n Version

1.39.1

### Node.js Version

v18.19.1

### Database

PostgreSQL

### Execution mode

queue

**Comment by netroy** [comment]
This is working as currently implemented. n8n Worker stats simply report the data that is available to the node.js process using the [`os` module](https://nodejs.org/api/os.html).

While it'd be great to get this data from cgroups v2, and then also use that optimize the max heap-size, unfortunately this won't be doable until we drop support for node.js 18.

**Comment by Joffcom** [comment]
As this is not currently seen as a bug I am going to move this to closed for now.
