### ISSUE TITLE
Duplicate options for Gmail Create Draft operation

### ISSUE THREAD

**Issue by nchourrout** [n8n-io/n8n#9293]
### Bug Description

Hello,

Some options fields are listed twice for the Gmail node with resource set to `Draft` and operation set to `Create`.

The duplicate options are:
* To Email
* BCC
* CC
* Send Replies To
* To Email

![image](https://github.com/n8n-io/n8n/assets/342382/94cda7b0-c18d-419a-b1bb-f36064778e8d)

Note: if I select one of the duplicate fields, it will add the same field twice to the node.

![image](https://github.com/n8n-io/n8n/assets/342382/3ec87fa5-ac93-4951-812c-0b063cf67b36)

This seems new on 1.40.0

### To Reproduce

1. Admin Panel > Manage > Update n8n version to 1.40.0 > Save Changes
2. Add Workflow
3. Add Gmail node with "Create a draft" action
4. Open the node
5. Click "Add Option"
6. Some options are duplicated
7. Click on "CC"
8. The option CC has been added twice

### Expected behavior

* Each option should only appear once
* Clicking on an option should only add it once

### Operating System

n8n cloud

### n8n Version

1.40.0

### Node.js Version

unknown

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
@nchourrout good spot that is likely my fault, I will get it fixed in the morning.

**Comment by Joffcom** [comment]
Hey @nchourrout,

I have just put in a PR for this, Once reviewed and merged it will be available in the next release. Thanks for letting us know about this 🙌🏻
