### ISSUE TITLE
Token usage on Langchain nodes is no longer available in 1.40.0

### ISSUE THREAD

**Issue by mprytoluk** [n8n-io/n8n#9294]
### Bug Description

Token usage is no longer available at logs on Langchain nodes in 1.40.0. It was working up until at least 1.37.0.

1.37.0:
![image](https://github.com/n8n-io/n8n/assets/107938570/47bcb947-cbfc-407c-9e1b-3565ecbe496f)
1.40.0:
![image](https://github.com/n8n-io/n8n/assets/107938570/e2bfb1e8-ad6c-4c9a-94cf-211359600547)

Please note that the output on an added langchain callback on the llm is also empty:

1.37.0:
![image](https://github.com/n8n-io/n8n/assets/107938570/4819a1d2-b3d6-49e8-a13e-faed1c2f7bf9)
1.40.0:
![image](https://github.com/n8n-io/n8n/assets/107938570/c88382c4-ecae-4461-992a-9de194af8403)

### To Reproduce

Use any LLM/Langchain related node and check the logs.

### Expected behavior

There should be the token usage info on LLM/Langchain nodes logs.

### Operating System

Ubuntu

### n8n Version

1.40.0

### Node.js Version

18.x

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mprytoluk,

Thanks for the report, The team are looking into this now.

**Comment by mprytoluk** [comment]
Thank you for your reply @Joffcom. I can confirm the reported behavior for 1.37.0 is the same for 1.38.1, so it is still working on 1.38.1.

**Comment by janober** [comment]
Fix got released with [`n8n@1.42.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.42.0)
