### ISSUE TITLE
v0.28: Error Trigger workflow could not be activated 

### ISSUE THREAD

**Issue by sutidor** [n8n-io/n8n#93]
Hi Jan,

I tried to implement an error workflow today but I cant activate it. Gives me following error:

There was a problem and the workflow could not be activated:
The workflow can not be activated because it does not contain any nodes which could start the workflow. Only workflows which have trigger or webhook nodes can be activated.

What I dont quite get as well, is there a global error workflow or is there an error path per workflow? (I tried the latter too, but the error node did not get executed)

Viele Grüße
Sven

**Comment by janober** [comment]
Hello Sven,

please ask questions if possible always in the forum (https://community.n8n.io) first. Only create an issue here if it is a bug for sure. Just to have a single location where people can look things up if they need to.

Yes, the Error Workflow does not have to get activated. If it has an "Error Trigger"-Node it will get executed if it is set as Error Workflow on another workflow.

It is possible to set an Error Workflow for each workflow in the workflow-settings as described here:
https://docs.n8n.io/#/workflow?id=error-workflow

So multiple workflows can have the same one or totally different ones. It is quite normal that many workflows share the same one which simply sends some kind of message if something went wrong.

blue skies

Jan

**Comment by janober** [comment]
I guess the "hooray" reaction means that the problem got solved ;-) So close the issue.
