### ISSUE TITLE
LinkedIn API version deprecated

### ISSUE THREAD

**Issue by floryn90** [n8n-io/n8n#9306]
### Bug Description

From LinkedIn api documentation page:
Deprecation Notice
The Marketing version 202304 (Marketing April 2023) and below has been sunset and the unversioned APIs are going to be sunset soon. We recommend that you migrate to the [versioned APIs](https://learn.microsoft.com/en-us/linkedin/marketing/versioning?view=li-lms-2023-04) as well as migrate to the new [Content](https://learn.microsoft.com/en-us/linkedin/marketing/community-management/contentapi-migration-guide?view=li-lms-2023-04) and [Community Management APIs](https://learn.microsoft.com/en-us/linkedin/marketing/community-management/community-management-api-migration-guide?view=li-lms-2023-04) to avoid disruptions. See the [Migration](https://learn.microsoft.com/en-us/linkedin/marketing/integrations/migrations?view=li-lms-2023-04) page for more details. If you haven’t yet migrated and have questions, submit a request on the [LinkedIn Developer Support Portal](https://linkedin.zendesk.com/hc/en-us).

### To Reproduce

Na

### Expected behavior

LinkedIn api version upgraded to 202404 from 202304

### Operating System

Docker containers

### n8n Version

Latest

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @floryn90,

I am going to close this as we have the PR from you 👍🏻
