### ISSUE TITLE
Send Email Randomly Fails Due to Missing Nodemailer Configuration

### ISSUE THREAD

**Issue by MarleTangible** [n8n-io/n8n#9320]
### Bug Description

Send Email action is using Nodemailer behind the scenes and when using certain SMTP relay a missing `name` configuration item is causing the mail sending to fail. NocoDB had [a similar issue](https://github.com/nocodb/nocodb/issues/7103) which was resolved by adding the name parameter as an option.

Here's the underlying issue as far as I can surmise: [Nodemailer SMTP configuration](https://nodemailer.com/smtp/) has an option called `name` which defaults to the hostname of the machine the app is running. As long as the program is running on a reputable IP address everything works fine, but the moment you use an internal IP via docker etc. the SMTP server randomly starts rejecting emails with various errors.

Allowing users to add the `name` parameter either via SMTP configuration or Send Email action would resolve this issue.

### To Reproduce

1. Add an SMTP relay with an anonymous authentication.
2. Create a workflow that uses the Send Email action.
3. Send enough, more than 5, emails to see `NodeApiError: Server terminates connection.` errors.

### Expected behavior

Emails to be sent reliably.

### Operating System

Docker via Debian Bookworm

### n8n Version

1.39.1

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MarleTangible,

Thanks for the report, Oddly enough this is the first time I have seen this reported. Does this only happen in your environment with anonymous mail relays?

**Comment by netroy** [comment]
[I've created a branch to add a new option in SMTP credential, and if that field is set, it will used to set `name` on the SMTP options passed in to nodemailer.](https://github.com/n8n-io/n8n/compare/fix-9320?expand=1)

I've also triggered the [CI](https://github.com/n8n-io/n8n/actions/runs/8985601854) to build a custom image from this branch. Can you please try running the docker image `n8nio/n8n:fix-9320` and see if that fixes the issue for you 🙏🏽.

**Comment by Joffcom** [comment]
Hey @MarleTangible,

The change for this has been released in `1.41.0` and should be good to go.
