### ISSUE TITLE
I can't save my node

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#935]
It has this error:

> There was a problem and the workflow could not be deactivated:
> Could not find credentials for type "mySql" with name "MySQL cmd_contact".

But when I delete all MySQL nodes, it still has this error.

![n8n-▶️-Central-new-contact](https://user-images.githubusercontent.com/1112881/92351937-28cfe600-f107-11ea-83c6-4ec71460f051.png)

**Comment by janober** [comment]
Are you sure that there are no MySQL-Nodes somewhere else in the flow that are currently not visible (as for example also the Start-Node)?

If you anyway just want to have the visible nodes you can:
 1. Select the nodes you want to keep, copy and then paste in a text-editor
 2. Press "ctrl + a" to select all nodes in the workflow
 3. Press "del" key to delete all nodes (the only node that will be left behind will be the Start-Node)
 4. Copy the JSON from the text-editor and paste that into n8n
 5. Save now

**Comment by cmdntd** [comment]
I tested,
When I ctrl-a to select all nodes, and delete, I still cannot save it with the same error
(But Start-node does not be deleted only)

There is 1 node with mysql has old credential. When I delete this credential, and try to change to new credential, it cause error.
Something is stuck with old credential, although I delete all nodes to save...

**Comment by cmdntd** [comment]
Could I force to delete this workflow by command?

**Comment by janober** [comment]
There is no delete force command. But can you not just delete it totally normally via the Editor-UI?

**Comment by cmdntd** [comment]
Yes, totally. I can not delete this workflow, save, or turn it off.

**Comment by janober** [comment]
Then the only way is to delete it directly from the database.

**Comment by cmdntd** [comment]
Hi again, I have second node with same error
It take error when I create credential and create node with it, then I delete credential that connected with existed node
This make me can't save, delete, rename or deactivate it.

It seems  workflow check if it can not find existed credential of its, it will just show error and stop everything
I think you should fix it soon, it wil be continued to take error when someone detele credential first...

**Comment by cmdntd** [comment]
It will be ok if some actions like delete, rename or deactivate is more important than stop by error of workflow database's null...

**Comment by cmdntd** [comment]
This is more serious, because it make error for all of workflow have connected with this cerdential
And I will have so many workflows can not do anything in error of this.
![n8n-▶️-Central-new-contact](https://user-images.githubusercontent.com/1112881/93903671-284c6780-fd23-11ea-9b81-dce72d994ab5.png)

**Comment by janober** [comment]
Sorry, do not understand. How can credentials be more independent? They are already totally independent. You have credentials and you have workflows. Each of them have a name and all the workflow saves is the name of the credentials he should use. If you now delete these credentials the workflow can not use them anymore (as you just deleted them) and so the only thing he can do is error (after all without them authentication is not possible and it is impossible to execute the node) and tell the user that. So what has to happen then is that the user goes in and selects other credentials
Maybe what you are asking for is that the credentials get additionally also saved with the workflow that is using them? That is however nothing we would ever consider.

**Comment by cmdntd** [comment]
This error is over any action of user
This mean you can not deactive/delete node or workflow/select other credentials, and every action of user just stop at showing error.
Could you take user to able to delete node, workflow related to old credentials to stop this error?

**Comment by janober** [comment]
Will have a look if I can reproduce and fix.

**Comment by janober** [comment]
Ah found now the missing piece to the puzzle. The problem you are experiencing happens only with activated workflows. So at least I can now reproduce the problem and so fix it.

**Comment by janober** [comment]
Ok issue got fixed. So after credentials got renamed or deleted it will still not be possible to activate a workflows but now simply other onces can be selected and the workflow saves then just fine.

Will be released with the next version.

**Comment by cmdntd** [comment]
Hopefully! Because I do with so many credentials at the same time.

**Comment by janober** [comment]
But just to be clear. If you rename/delete credentials that are used in a workflow it is still very bad (as the workflows will still not work). So that is something you always have to be very careful with and avoid if absolutely possible. The only difference is now that you can fix this issues.

**Comment by cmdntd** [comment]
Yep, because of so many credentials
I just want to re-order list by name to follow easier...

**Comment by janober** [comment]
Got released with n8n@0.84.0
