### ISSUE TITLE
pipedrive cannot resolve properties anymore

### ISSUE THREAD

**Issue by flyos777** [n8n-io/n8n#9353]
### Bug Description

n8n cannot retreive Pipedrive persons properties anymore (the issue started on 8th of May)
Error message is `json[key].split is not a function`
![2024-05-10 09_21_14-n8n - ⚠️ Consolidation - Pipedrive - WIP and 2 more pages - Work - M](https://github.com/n8n-io/n8n/assets/5772436/0d73e3d9-f24b-44da-996e-f1d1295393b4)

### To Reproduce

1. Create a pipedrive node
2. Get details of a person
3. Tick the box "Resolve Properties"

### Expected behavior

Return person properties

### Operating System

Ubuntu with docker

### n8n Version

1.39.1

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @flyos777,

This was fixed in `1.41.0` in this PR: https://github.com/n8n-io/n8n/pull/9319

Can you try upgrading and if you still see the same issue let me know and we can open this again.

**Comment by flyos777** [comment]
It worked, thank you very much ! 🤗
