### ISSUE TITLE
ERROR: The DNS server returned an error, perhaps the server is offline

### ISSUE THREAD

**Issue by ItsJamesMurray** [n8n-io/n8n#9414]
### Bug Description

I am self hosting via Docker container.  I had a few automations setup that were running properly until this Sunday (3 days ago).   Now all the HTTP requests or any app connections are erroring out and the error says `The DNS server returned an error, perhaps the server is offline`.  I've not made any changes to my stack or tooling.

I have the this running on an ubuntu mini-pc on my network with tailscale running.  webook url is `https://mini-pc.MYTAILSCALENETWORK.net` and is set via env vars.

### To Reproduce

1. Go to an active workflow with a HTTP request or App connection
2. Add a "Click" trigger
3. Test Workflow
4. Workflow works until it reaches the HTTP request or app connection.  Error shows `Problem in node ‘Foobar‘ The DNS server returned an error, perhaps the server is offline`

### Expected behavior

I expect the requests to run properly as they had in the past.

### Operating System

Ubuntu

### n8n Version

1.27.3

### Node.js Version

18.19.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
That sounds like the MagicDNS isn't working for some reason. Have you tried reconnecting to Tailscale?

**Comment by Joffcom** [comment]
Hey @ItsJamesMurray,

I am going to move this to closed as this doesn't look to be directly related to n8n and as a possible configuration issue would be better suited to the support forum.

Let me know if you have any questions on this.
