### ISSUE TITLE
workflows.map is not a function

### ISSUE THREAD

**Issue by zhiru** [n8n-io/n8n#9429]
### Bug Description

when executing for example n8n import:workflow --input=/home/node/.n8n/workflows/backups/RvOzh6w5dDiHnLgY.json

show me the errors:

~/.n8n/workflows/backups $ n8n import:workflow --input=/home/node/.n8n/workflows/backups/RvOzh6w5dDiHnLgY.json 
User settings loaded from: /home/node/.n8n/config
An error occurred while importing workflows. See log messages for details.
workflows.map is not a function

### To Reproduce

Install docker queue mode with worker and webhook, try to import workflow

### Expected behavior

workflow imported with success

### Operating System

Windows 11

### n8n Version

1.41.1 (latest)

### Node.js Version

latest

### Database

SQLite (default)

### Execution mode

queue

**Comment by netroy** [comment]
`n8n import:workflow --input=file.json` assumes that `file.json` contains an array of objects. This sounds like this file contains a single object, which would imply that it was either downloaded from the web/frontend, or was was exported with a `--separate` flag.

Can you please try either running `n8n import:workflow --separate --input=/home/node/.n8n/workflows/backups` to import all backups from that folder, or import this single workflow via the UI instead.

**Comment by zhiru** [comment]
worked, thanks!!
