### ISSUE TITLE
Renaming the node by leaving the name field empty causes unexpected behavior

### ISSUE THREAD

**Issue by khashashin** [n8n-io/n8n#9430]
### Bug Description

When renaming an OpenAI model node by leaving the name field empty, the editor for that particular node opens and cannot be closed. This issue persists even when navigating to the Workflows overview. Selecting the affected workflow reopens the editor mode immediately after the workflow canvas is displayed.

### To Reproduce

1. Open a workflow.
2. Rename an OpenAI Model node by leaving the name input field empty.
3. Press Enter.

### Expected behavior

Users should be able to create nodes without names. The system should handle nodes by their unique indexes, allowing normal access and functionality without causing the editor to become stuck open.

### Operating System

Ubuntu 22.04

### n8n Version

Version 1.39.1

### Node.js Version

18

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by janober** [comment]
Thanks for reporting this.
Users should, however, not be able to create nodes without names. After all, would it then for example be impossible to reference data from it via expressions. Additionally would a million other things break inside of n8n.
Anyway, it should for sure display an error message when a user tries to do that and ultimately not allowing it. So for sure something we have to fix.

**Comment by khashashin** [comment]
Yeah, I understand it is too late for such a change since it would result in a breaking change. However, I believe allowing the use of names in expressions was not the best idea. Names are subject to change, often based on user preference, which can lead to broken assignments in other expressions.

**Comment by janober** [comment]
This like any other choice, it has advantages and disadvantages. We discussed it a while ago especially regarding expressions and we came to the conclusion that there are still more advantages.

Generally should it not cause any problems when a node is renamed, as all expressions in the workflow get also updated automatically as well.

**Comment by Joffcom** [comment]
Hey @khashashin,

I have created `ADO-2226` as the internal ticket to get this one resolved, If no name is inputted it should really just keep the orginal name.

**Comment by janober** [comment]
Fix got released with [`n8n@1.44.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.44.0)
