### ISSUE TITLE
Can you add options for multi-branch parallel execution and for nodes to continue the workflow execution even if an error occurs? 

### ISSUE THREAD

**Issue by newBBnew** [n8n-io/n8n#9432]
### Bug Description

I have made several attempts to modify the code to allow nodes in branches to run simultaneously, but I haven't succeeded. Can you consider addressing this issue, as my work requires the ability to execute multiple branches simultaneously? Additionally, could each node have an option to continue the workflow execution instead of stopping entirely when an error occurs, besides just retrying?

### To Reproduce

no

### Expected behavior

no

### Operating System

ubuntu

### n8n Version

1.41

### Node.js Version

18.16

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @newBBnew,

We only use GitHub issues for bug reports, feature requests should be raised on the [Community Support Forum](https://community.n8n.io)

When it comes to parallel executions in workflows some users will use the execute workflow node with the instant reply option or will use http request nodes to call webhook triggered workflows.

This approach will work if you don't care about the response / output of those tasks.

For now though as there is no bug here I am going to mark this as closed, Let me know if you have any questions on this.
