### ISSUE TITLE
Node Max Tries / Wait Values Limits Too Low

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#9458]
### Bug Description

Within the Airtable node, it seems I can't set the `Max. Tries` value to anything above `5` and the `Wait Between Tries (ms)` value to anything above `5000`.  This is frustrating, because sometimes I need to set much longer retries due to Airtable API issues.  However, that's not possible in the n8n UI:

![image](https://github.com/n8n-io/n8n/assets/85660/aed7f453-a618-4635-82dc-2db2c75af73a)

I suspect these limits were set at some sort of global level (applied equally across all node types), but I'm not sure.

Rather than trying to come up with better upper limits, could we just have the upper limit check code disabled through some sort of global configuration setting (like an ENV variable)?  That would help a ton.

### To Reproduce

1. Create a new workflow
2. Specify an Airtable `Create or Update` node
3. Click gear icon
4. Enable `Retry On Fail`
5. Specify a `Max. Tries` value of `20`
6. Specify a `Wait Between Tries (ms)` value of `20000`
7. Save the workflow
8. Open back up the Airtable node
9. Click the gear icon
10. See that both values are set much lower than specified.

### Expected behavior

I expect n8n to allow me to set arbitrarily high values for `Max. Tries` and `Wait Between Tries (ms)`.  I really don't want any annoying guard rails here.

### Operating System

Google Cloud Linux

### n8n Version

1.41.0

### Node.js Version

18.16

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund 

This sounds more like a feature request than a bug and would be better suited to the support forum.

As there is not really anything for us to fix here I am going to mark this as closed, When you create the feature request on the forum don't forget to vote to make it count.

Let me know if you have any other questions about this one.

**Comment by dkindlund** [comment]
Hey @Joffcom , that's surprising, but sure -- I've submitted the feature request here:
https://community.n8n.io/t/node-max-tries-wait-values-limits-too-low/46284

**Comment by Joffcom** [comment]
Hey @dkindlund,

Thanks for that 👍

Which bit is surprising? We try to keep GitHub for bugs only and have the feature requests on the forum this helps us prioritise and it means the community can all vote for the feature requests.

**Comment by dkindlund** [comment]
Hey @Joffcom, let me explain further... the fact that you use the forum for feature requests is not surprising.

What I find surprising is that this issue isn't a bug to begin with.  Setting an arbitrary global upper bound of 5 times and 5000 ms wait per try seems like a bug.  Maybe those values were picked back when n8n had perhaps only 20 node types -- but now, with many, many more node types, it seems like a tech debt item.

**Comment by Joffcom** [comment]
Hey @dkindlund,

I take a very simplisitic view to what is a bug and what isn't a bug, If something is broken it is a bug. If it is brand new feature or an enhancement to something that already exists it is for the forum.

There are some issues that even cross this line like with the Airtable issues you found with the data being cached in the workflow json leading to larger files and slower responses, This was labelled as a bug as the behavior was not expected.

When we look at this one as we have set a limit in the past and the retries are happening so everything is working as expected and it is not broken.

Interestingly enough I did raise an internal feature request for this a while back as not only do I want to set a higher limit I also want to be able to specify other options like being allowed to increase the timeout on each failure so rather than always being 10 seconds it can grow with each attempt up to 5 minutes or something.

**Comment by dkindlund** [comment]
> Interestingly enough I did raise an internal feature request for this a while back as not only do I want to set a higher limit I also want to be able to specify other options like being allowed to increase the timeout on each failure so rather than always being 10 seconds it can grow with each attempt up to 5 minutes or something.

Totally makes sense, @Joffcom!  Heck, exponential backoff is a common practice these days, so it would make absolute sense to implement that on some node types where the API rate limits are much, much lower.

Bonus points if you could control the retries and wait limits using `Expression` values (where you're giving the workflow creator the ability to dynamically set these values based on workload specific information).

Otherwise, if a workflow creator wants more granular control over retries, they're forced to implement it themselves within the workflow directly (which is a pain).

Another side thought I had was: Being able to globally set default retry / wait times by node type -- that way, different retry / wait times could be defined for like Postgres versus Airtable.  If you want maximum flexibility, perhaps anchoring default retry / wait times to specific *credentials* for that node type would make a lot of sense, long term.

**Comment by Joffcom** [comment]
Expressions would be great as well, I will check the internal request I made to see if that is on there.  I like the idea of wait times in credentials as well sounds like a good option for the future.
