### ISSUE TITLE
Pagination Does Not Reset When Re-Testing Node

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#9463]
### Bug Description

Pagination state of test output does not reset back to Page 1 upon retest operations.  This causes the test output window to fail to show data on subsequent retests when the amount of data is less than the previous page.  Check the reproduce steps for more detail.

### To Reproduce

1. Create a new Workflow
2. Add a node to the workflow that will generate more than 1 page of test data (for example `Airtable`) and make sure to return enough data to exceed more than 1 page by adjusting the `Limit` param.
3. Click the `Test step` button.
4. Navigate to like the 5th page of the `Output`, as shown below:

<img width="1017" alt="image" src="https://github.com/n8n-io/n8n/assets/85660/6634e7e1-d31c-48eb-9d3f-539d3fbeeeea">

5. Then, while still on the 5th page of the output, *change* the `Limit` param back to 1.
6. Click the `Test step` button
7. See that the `Output` window is completely **EMPTY**:

![New Note](https://github.com/n8n-io/n8n/assets/85660/0364a39f-f643-4c5d-8451-b054d93a6974)

I suspect what is happening, is that n8n attempts to "remember" that it is on the 5th page after the `Test step` button is clicked.  And because the new test doesn't yield as many pages of output, the 5th page is **INVALID**, which is why the empty window is shown.

### Expected behavior

I would expect that upon clicking the `Test step` button, that the current page **RESETS** back to the 1st page, accordingly.

### Operating System

Google Cloud Run

### n8n Version

1.41.0

### Node.js Version

18.10

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund,

Thanks for the report, I managed to reproduce it with the DebugHelper node. The internal dev ticket to resolve this is `ADO-2230`.

**Comment by janober** [comment]
Fix got released with [`n8n@1.46.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.46.0)

**Comment by Joffcom** [comment]
Hey @dkindlund,

Good news, We have fixed this. I am going to close this but if you still see the issue after updating let me know and we can open it again.
