### ISSUE TITLE
http node executes "successfully" but error is returned

### ISSUE THREAD

**Issue by nepomuc** [n8n-io/n8n#9465]
### Bug Description

I call a url which is not reachable, but the http node still thinks it ran successfully, even though I don't have "Never Error" option activated.
![image](https://github.com/n8n-io/n8n/assets/864660/f8769764-c014-41ad-a740-258aa185dedf)

### To Reproduce

Simply call any unreachable url. It's weird :/

### Expected behavior

I would expect the node to fail.

### Operating System

Official Docker Image v1.41.1

### n8n Version

Official Docker Image v1.41.1

### Node.js Version

Official Docker Image v1.41.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nepomuc,

Under the Settings for the node do you have it set to Continue on Error?

**Comment by nepomuc** [comment]
Oh. My. God! I don't know why but yes. 🫣 At first it didn't help to set it to "Stop Workflow" though. So I recreated the http node, since I saw that I was using not the latest http node version. Now it fails as expected. Thanks for the lightning fast help!

**Comment by Joffcom** [comment]
Hey @nepomuc,

That is good to hear thanks for the update.
