### ISSUE TITLE
 1.41.0 - Adding Too Many Parameters Causes Node Window to Shake?!

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#9543]
### Bug Description

This is really hard to describe.  It's really just better if you see the video:

https://github.com/n8n-io/n8n/assets/85660/e9553982-ea97-4f57-88aa-565cf7f1492b

### To Reproduce

1. Create a new workflow
2. Add a Switch node
3. Add 7 or more parameters
4. Resize the browser window
5. Watch the panel "shake"

### Expected behavior

I do not expect panels to shake when resizing the browser -- if they must shake, then maybe play some music? ;)

### Operating System

Google Cloud Run

### n8n Version

1.41.0

### Node.js Version

18.10

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund 

The first question I have on this is why are you using for the amazing background disco?

I will try and reproduce this in the morning and get a ticket created for this.

**Comment by dkindlund** [comment]
> The first question I have on this is why are you using for the amazing background disco?
Here you go: https://steamcommunity.com/sharedfiles/filedetails/?id=1748506393  Enjoy! ;)

> I will try and reproduce this in the morning and get a ticket created for this.
Sounds good.  Thanks!

**Comment by Joffcom** [comment]
Hey @dkindlund,

I don't have a screen big enough to reproduce this issue, Can you let me know what the screen size is, resolutiona and what browser you are using and I will include in the report.

**Comment by Joffcom** [comment]
Cheers, Will add it to the ticket.

**Comment by nik8n** [comment]
Hey @dkindlund, sorry for taking so long on this one. We just tried to reproduce this in the new version and were not able to do so anymore. Can you confirm?

**Comment by dkindlund** [comment]
Hi @nik8n , I don't see this issue reappear again in the latest version -- I think it's resolved.
