### ISSUE TITLE
The Read/Write Files from Disk Node do not working

### ISSUE THREAD

**Issue by try2020-code** [n8n-io/n8n#9544]
### Bug Description

i am sure my file path is right , i put it to File(s) Selector ,when i click "test step"  ,it do not working and then it show a msg say "Node executed successfully"  ,but it do not return any result

![image](https://github.com/n8n-io/n8n/assets/84961646/42d430ba-9008-430f-9ce7-e0547248c46f)

1. i am sure the n8n install to my windows pc ,not docker or any vm
2. i am sure the file file have any permissions

### To Reproduce

1. go add  Read/Write Files from Disk  and set read type
2. write a file path ,it type is txt
3. click the "Test step"
4. see any result?

### Expected behavior

return any result

### Operating System

windows

### n8n Version

new

### Node.js Version

v20.14.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @try2020-code,

It looks like the issue here could be with the path separators, Can you try replacing the `\` with `/` and see if that works?

**Comment by try2020-code** [comment]
![image](https://github.com/n8n-io/n8n/assets/84961646/d482da98-11e9-450a-a5d8-6a8a7f14b787)

hi it looks useful ,but i  think it a problem , the path should be '\' in win system , i know the '/' in linux  but ... can we Identify and fix it?

**Comment by Joffcom** [comment]
Hey @try2020-code,

Technically Windows will support both `\` and `/` but yeah I agree we should do something in the node to automatically replace these to make life easier.

**Comment by janober** [comment]
Fix got released with [`n8n@1.53.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.0)

**Comment by IntrinsicNerd** [comment]
I am also having this issue now on the current version of n8n. Neither read nor write work. No matter the path I choose, the file will not write, and if I try to read a file, even if I am pointing to it with a completely static reference. I also do have n8n locally installed, and I can't think of any read or write permission issues I could be having.

**Comment by Quentin-Pinot** [comment]
Hello, 

This issue is still happening to me as well, and I'm using version 1.79.2

**Comment by VCDragoon** [comment]
Still happening on 1.103.2 npm version but a little more subversive for me, on windows.  When running on linux I get no issues.  I have tried changing `\ `for `/`, but after the nodes find the file, they seem to change it back to `/`. 

Going into the actual load file node and giving it the full Windows path with `/` and it runs and finds the file. The issue seems to be dynamically getting the path when a file changes.
