### ISSUE TITLE
BASE_PATH not been replaced correctly

### ISSUE THREAD

**Issue by brookqin** [n8n-io/n8n#9559]
### Bug Description

<img width="937" alt="2024-05-31 11 36 39" src="https://github.com/n8n-io/n8n/assets/405636/591a4699-a0ad-4750-baf9-55707371f47e">

### To Reproduce

1. pnpm install & build & dev
2. open a workflow
3. open browser debug console

### Expected behavior

Load resources correctly

### Operating System

macOS

### n8n Version

1.44.0

### Node.js Version

v18.20.3

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @brookqin 

Have you set any environment variables, your steps to reproduce this issue don't include any but it is worth checking.

**Comment by brookqin** [comment]
No, all are default settings

**Comment by janober** [comment]
Fix got released with [`n8n@1.44.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.44.1)
