### ISSUE TITLE
LICENSE file is incorrect

### ISSUE THREAD

**Issue by sneak** [n8n-io/n8n#960]
The LICENSE file in this repository says:

`License: Apache 2.0`

This is a false statement.  The Apache 2.0 license does not apply to this software.

The Apache 2.0 license is a ***free software, open source license***.

***The license that governs this project is not free software, and it is not open source***.

https://faircode.io/ linked from the project website is terribly misleading:

> How does fair-code relate to open-source or free software?

> We see fair-code as an alternative model which addresses key concerns which open-source and free software currently fail to address. We support the community at large, and it is strongly encouraged that fair-code projects donate and contribute to likely more financially strained free and open source siblings if possible. As fair-code is adopted by software projects, more people who appreciate open-source and free software will have the financial means to support the open-source projects that they rely on.

This is down at the bottom, and it is entirely unclear that this project is not open source software.

The LICENSE file says Apache, but it's not an Apache license: it's this weird not-open-source thing.

Please fix the LICENSE file and fix the messaging on the webpage (and ideally clarify the faircode.io website too).

It's still misrepresenting the project as open source, and #40 is still an issue, as I got bit by this today when I discovered the project.

**Comment by sneak** [comment]
From https://commonsclause.com/:

> Is this “Open Source”?

> *No.*

> “Open source”, has a specific definition that was written years ago and is stewarded by the Open Source Initiative, which approves Open Source licenses. Applying the Commons Clause to an open source project will mean the source code is available, and meets many of the elements of the Open Source Definition, such as free access to source code, freedom to modify, and freedom to re-distribute, but not all of them. So to avoid confusion, it is best not to call Commons Clause software “open source.”

**Comment by janober** [comment]
Got changed.
