### ISSUE TITLE
Spreadsheet File Node date time format issue

### ISSUE THREAD

**Issue by michaltalaga** [n8n-io/n8n#9624]
### Bug Description

At some point Spreadsheet File started producing strange date format like 45092.84722222222 instead of normal ISO like date

### To Reproduce

given input like this
"Symbol","Date/Time","Amount","TransactionID"
"GOLD","2023-06-15 20:20:00","30","24187476554"

output will look as follows:
Symbol Date/Time Amount TransactionID
GOLD	**45092.84722222222**	30	24187476554

### Expected behavior

Symbol Date/Time Amount TransactionID
GOLD	**2023-06-15 20:20:00**	30	24187476554

### Operating System

docker image

### n8n Version

1.44.1

### Node.js Version

docker image

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @michaltalaga,

I am not able to reproduce this, Using your sample data as a csv file and reading it I am getting a date as expected.

![image](https://github.com/n8n-io/n8n/assets/4688521/8bafa334-2955-4881-9ae2-d0400d5e7e69)

Are you also using the Extract from file node or the older Spreadsheet node?

**Comment by michaltalaga** [comment]
full workflow
![image](https://github.com/n8n-io/n8n/assets/10220151/9ed4fe86-877e-4c87-bd37-0415b4532cf2)
![image](https://github.com/n8n-io/n8n/assets/10220151/304c6c60-0c08-4e7a-ab1e-ee18bdd236f5)
![image](https://github.com/n8n-io/n8n/assets/10220151/e1c46986-7828-42ab-bd79-9a1c1450d426)

I'm 100% sure it worked before as I can still see the data correct data in my database.
But at some point I started getting those date issues. cannot track it to anything I did (I've not changed the workflow) nor any specific n8n version update either.

I think I managed to extract the safe parts to files here:
[workflow.json](https://github.com/user-attachments/files/15592862/workflow.json)
[n8n-sample.txt](https://github.com/user-attachments/files/15592864/n8n-sample.txt)

**Comment by michaltalaga** [comment]
anyways I can see it works with Extract from File node

**Comment by ngustavo** [comment]
I can confirm this. I'm trying to read a bunch of CSV and XLSX files with Spreadsheet node. It works only for XLSX on my setup.
