### ISSUE TITLE
Gotify- "ignore SSL issues" option doesn't work

### ISSUE THREAD

**Issue by MichalMarchewka** [n8n-io/n8n#9640]
### Bug Description

"Ignore SSL Issues" option doesn't work. I have self-hosted Gotify with self-signed certificate. n8n outputs **"SSL Issue: consider using the 'Ignore SSL issues' option"** but the option is enabled

### To Reproduce

1. Self-host Gotify with self-signed certificate. Gotify is running and is accessible.
2. Create an app in Gotify. Copy token.
3. In n8n create new Credentials to connect with Gotify:
* paste API token
* fill URL field- https://gotify.domain.tld
* enable "Ignore SSL Issues option
4. Test workflow step to send a message to Gotify. 
* **"SSL Issue: consider using the 'Ignore SSL issues' option"** error will be printed
* Stack trace message:

`NodeApiError: SSL Issue: consider using the 'Ignore SSL issues' option at Object.gotifyApiRequest (/root/.nvm/versions/node/v18.20.3/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Gotify/GenericFunctions.ts:43:9) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/root/.nvm/versions/node/v18.20.3/lib/node_modules/n8n/node_modules/n8n-nodes-base/nodes/Gotify/Gotify.node.ts:227:22) at Workflow.runNode (/root/.nvm/versions/node/v18.20.3/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1378:8) at /root/.nvm/versions/node/v18.20.3/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1057:29 at /root/.nvm/versions/node/v18.20.3/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1744:11`

### Expected behavior

As "Ignore SSL Issues" option is enabled messages can be successfully sent to Gotify

![image](https://github.com/n8n-io/n8n/assets/56821715/4664489b-0e46-4f8e-ad8d-32ae175c5295)

![image](https://github.com/n8n-io/n8n/assets/56821715/32bf616e-dd11-4b05-8eae-9d04e728ec01)

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.42.1

### Node.js Version

18.20.3

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by MichalMarchewka** [comment]
Update:
* Sending message to Gotify using HTTP request with "Ignore SSL Issues" enabled works

**Comment by Joffcom** [comment]
Hey @MichalMarchewka 

Thanks for the report, it looks like there is a small typo stopping this option from working which I will fix in the morning.

**Comment by janober** [comment]
Fix got released with [`n8n@1.44.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.44.2)
