### ISSUE TITLE
Elasticsearch- "SELF_SIGNED_CERT_IN_CHAIN"

### ISSUE THREAD

**Issue by MichalMarchewka** [n8n-io/n8n#9677]
### Bug Description

Unable to connect to Elasticsearch  when self-signed certificate is used in ES. Response when testing credentials: "SELF_SIGNED_CERT_IN_CHAIN". Also HTTP request does not work, even no error message in response. "Ignore SSL issues" option is selected.

### To Reproduce

1. Create Elasticsearch deployment with self-signed certificate (default certificate generated during Elasticsearch installation)
2. Note or re-generate password for 'elastic' built-in user
3. Use proper credentials when configuring Elasticsearch node
4. Test credentials
5. `Couldn’t connect with these settings SELF_SIGNED_CERT_IN_CHAIN` will be printed

![image](https://github.com/n8n-io/n8n/assets/56821715/5e8c6f1e-fde6-41e0-b33e-9089f7009034)

![image](https://github.com/n8n-io/n8n/assets/56821715/8cc4f86c-fc8d-47f5-a32c-328faccbf8b8)

### Expected behavior

Even if Elasticsearch has self-signed certificate the communication with ES should be permitted from n8n.

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.42.1

### Node.js Version

18.20.3

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @MichalMarchewka,

Thanks for the report, It looks like while the credential test fails the node should still work. I have popped in a PR that fixes the issue with the credential test. Once reviewed it will be merged and available in a future release.

**Comment by Joffcom** [comment]
Good news this got released with [n8n@1.47.0](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)
