### ISSUE TITLE
Nextcloud can't upload files anymore

### ISSUE THREAD

**Issue by mokkin** [n8n-io/n8n#9708]
### Bug Description

Since n8n v1.44.x I can't use the upload functionality of Nextclouds anymore. I'm trying to upload csv files, but I am getting `Cannot read properties of undefined (reading 'error')`
```
{
  "errorMessage": "Cannot read properties of undefined (reading 'error')",
  "errorDetails": {},
  "n8nDetails": {
    "n8nVersion": "1.44.1 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "TypeError: Cannot read properties of undefined (reading 'error')",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:666:253",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1079:20"
    ]
  }
}
```

On another instance with n8n v1.41.1 it is working as exepected on the same Nextcloud instance with the same credentials.

### To Reproduce

1. create  an array or list
2. convert it to binary (csv)
3. upload the binary file to a Nextcloud path

### Expected behavior

Uploading works.

### Operating System

Ubuntu 22.04

### n8n Version

1.44.1

### Node.js Version

inside Docker container

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
This is like the same as #9665

**Comment by mokkin** [comment]
Solved with https://github.com/n8n-io/n8n/releases/tag/n8n%401.44.2
