### ISSUE TITLE
[Webhook Node] Dynamic-value will make URL always include a random GUID

### ISSUE THREAD

**Issue by 1itt1eB0y** [n8n-io/n8n#9721]
### Bug Description

![图片](https://github.com/n8n-io/n8n/assets/29831189/3dec9328-47fc-4752-9375-0d606807a7aa)
![图片](https://github.com/n8n-io/n8n/assets/29831189/35287f9c-d24b-4942-8a15-d7ea08385ee8)

### To Reproduce

add a webhook node, and configure the path

### Expected behavior

I think there just "https://domain/webhook/ntfy/:id".

### Operating System

Docker

### n8n Version

1.44.2

### Node.js Version

Docker version

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
Path params make it very complicated for us to route webhook requests correctly without a static prefix like that. This is why we have to prefix the path with the webhook's id.
It might be possible to "fix" this, but that would most likely break workflows for everyone else.
In the future however we could consider letting users define a static value for the `workflowId` by validating that no other webhook on that instance is already using the same id.
