### ISSUE TITLE
[AwsSes.node.ts] SignatureDoesNotMatch : The request signature we calculated does not match the signature you provided.

### ISSUE THREAD

**Issue by NK74** [n8n-io/n8n#974]
Hello,

**Describe the bug**
Unable to send email with SES Integration.

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**To Reproduce**

- Use the code snippet from https://n8n.io/workflows/507
- Create your credentials on AWS SES Console, Fill your credentials in N8N UI
- General setup in the integration (Subnet, Body, Sender, From...)

```
ERROR: Error: AWS error response [403]: 403 - "<ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n <Error>\n <Type>Sender</Type>\n <Code>SignatureDoesNotMatch</Code>\n <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n </Error>\n <RequestId>c1774ff6-4120-42f2-a68e-5c3d91b1ee92</RequestId>\n</ErrorResponse>\n"
Error: Error: AWS error response [403]: 403 - "<ErrorResponse xmlns=\"http://ses.amazonaws.com/doc/2010-12-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>SignatureDoesNotMatch</Code>\n    <Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.</Message>\n  </Error>\n  <RequestId>c1774ff6-4120-42f2-a68e-5c3d91b1ee92</RequestId>\n</ErrorResponse>\n"
    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/AwsSes.node.js:265:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

N8N UI
![image](https://user-images.githubusercontent.com/17825769/93690567-11670480-fada-11ea-9ba0-0523951ac4ed.png)

**Expected behavior**
Simply send an email

**Environment (please complete the following information):**
 - OS: Amazon AMI Linux 2
 - n8n Version 0.83.0
 - Node.js Version v12.16.3

**Additional context**

```
{
  "nodes": [
    {
      "parameters": {
        "subject": "n8n Rocks",
        "body": "This is a sample message body in an email\n",
        "fromEmail": "myemail@domain.xyz",
        "toAddresses": [
          "myemail@domain.xyz"
        ],
        "additionalFields": {}
      },
      "name": "AWS SES",
      "type": "n8n-nodes-base.awsSes",
      "position": [
        510,
        330
      ],
      "typeVersion": 1,
      "credentials": {
        "aws": "AWS SES eu-west-1"
      }
    }
  ],
  "connections": {}
}

```

AWS IAM SES policy (created with AWS SES)
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ses:SendRawEmail"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by RicardoE105** [comment]
@NK74 thanks for putting this together. Just tested it and it working just fine for me. I use n8n version 0.89.2. Can you try with the latest version?

**Comment by christiaanwesterbeek** [comment]
@NK74 How did you fix this? I have the same.

![image](https://user-images.githubusercontent.com/465989/154791169-bc247149-8206-4996-b7d0-5e2cc26c4c2d.png)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/465989/154791112-b12459fb-48c2-43fd-825e-16a5bf1389ba.png">

**Comment by NK74** [comment]
@christiaanwesterbeek I don't use n8n anymore ... 😄  Good luck
