### ISSUE TITLE
Google Drive Trigger File Type filter creates confusion

### ISSUE THREAD

**Issue by mrcrdwd** [n8n-io/n8n#9773]
### Bug Description

When filtering the Google Drive Trigger based on the File Type option, the options are ambiguous and leave room for misinterpretation. For example, selecting `Audio` as the File Type, you'd expect that any uploaded wav, m4a or mp3 file would fall in this category, but it doesn't. The Audio filter only triggers when the associated mime type is `application/vnd.google-apps.audio` [source](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Google/Drive/GoogleDriveTrigger.node.ts#L360) and that's not the case for most audio files.

### To Reproduce

1. Create and configure Google Drive Trigger
2. Select Audio as the File Type filter
3. Upload an `.wav` to your Google Drive
4. Watch the trigger not get activated

### Expected behavior

Option 1: Display the actual mime type in the File Type filter on the front end instead of `Audio` so the user knows exactly what Audio means.
Option 2: Improve the n8n documentation on the Google Drive Trigger node to explain which mime types fall under the labels
Option 3: Actually mime type that start with `audio/*` to be returned by the filter.

### Operating System

Ubuntu 22.04 LTS

### n8n Version

1.45.1

### Node.js Version

20.5.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @mrcrdwd,

That is an interesting thought, I don't think this is a bug though as it looks like we have made a choice to only use the Google formats.

Would you be able to open a feature request for this on the forum as this is better suited there and we can collect feedback and implement any changes in the next node version.
