### ISSUE TITLE
Slack: "Automated with n8n" Footer - UPDATE

### ISSUE THREAD

**Issue by mywebmasteruk** [n8n-io/n8n#9803]
### Bug Description

When using Slack Update Node, I am getting the footer “Automated with this n8n workflow”

There is an option to remove it when you “Send” a new message, but it's missing for Update.

### To Reproduce

Add to any workflow Slack node set to Update.
When the message is updated, you get the footer "Automated with this n8n workflow (edited)"

### Expected behavior

under “Options” there should be an option "Include Link to Workflow" in order to switch it off

so that the footer is not shown in the message.

### Operating System

Ubuntu

### n8n Version

1.45.1

### Node.js Version

Not sure

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Thanks for the report @mywebmasteruk, We have created `NODE-1423` as the internal ticket to look into this.

**Comment by mickmcgrath13** [comment]
Bump.  Also looking forward to it.

could it be as simple as adding [this](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Slack/V2/MessageDescription.ts#L560-L567):
```suggestion
		{
			displayName: 'Include Link to Workflow',
			name: 'includeLinkToWorkflow',
			type: 'boolean',
			default: true,
			description:
				'Whether to append a link to this workflow at the end of the message. This is helpful if you have many workflows sending Slack messages.',
		},
```

to this options list: https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Slack/V2/MessageDescription.ts#L955

?

**Comment by saravicius** [comment]
What is the status of this issue? It was reported quite far ago... @mickmcgrath13 even gave you a line and a solution.. guys :) pls

**Comment by janober** [comment]
Fix got released with [`n8n@1.61.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.61.0)

**Comment by Joffcom** [comment]
Hey @saravicius,

The change for this was put in before your comment but to give some more insight we prioritise the issues based on how urgent it is so it can time for us to fix some that are not breaking anything.

We do however accept pull requests so if it looks like an easy fix we are more than happy to review a PR :) In this case the fix was waiting for one of our bug bashing sessions and has now been sorted.

**Comment by muhtalhakhan** [comment]
Hello,

I am using a self-hosted n8n version (1.102.3) and still facing a similar issue.

<img width="454" height="876" alt="Image" src="https://github.com/user-attachments/assets/9a158c44-fbbf-4f54-9a4d-48cd68cd9f24" />

There is no option to turn off the n8n attribution.

Please help!
