### ISSUE TITLE
MR 9412 removes icon files, which are still referenced in some nodes

### ISSUE THREAD

**Issue by marzn** [n8n-io/n8n#9843]
[MR 9412](https://github.com/n8n-io/n8n/pull/9412) removes icon files, which are still referenced in some nodes:
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/ActiveCampaign/ActiveCampaignTrigger.node.ts#L19
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/Affinity/AffinityTrigger.node.ts#L18
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/Amqp/AmqpTrigger.node.ts#L20
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/Flow/FlowTrigger.node.ts#L17
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/LoneScale/LoneScaleTrigger.node.ts#L18
- https://github.com/n8n-io/n8n/blob/16d3083af7465d0788f25d843e497b4c7d69de92/packages/nodes-base/nodes/RabbitMQ/RabbitMQTrigger.node.ts#L25

_Originally posted by @marzn in https://github.com/n8n-io/n8n/issues/9412#issuecomment-2186185718_

**Comment by Joffcom** [comment]
Hey @marzn,

Good spot, I have opened a PR to go through and resolve these.

**Comment by janober** [comment]
Fix got released with [`n8n@1.48.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.48.0)
