### ISSUE TITLE
Credentials error with Pipedrive Trigger node

### ISSUE THREAD

**Issue by frankie567** [n8n-io/n8n#987]
**Describe the bug**

Pipedrive Trigger nodes can't be executed. It shows the following error : `Error: Node type "n8n-nodes-base.pipedriveTrigger" does not have any credentials of type "pipedriveOAuth2Api" defined!`

**To Reproduce**

1. Create Pipedrive credentials
2. Create a new workflow
3. Add a Pipedrive Trigger node
4. Save the workflow
5. Try to execute the Pipedrive Trigger node
6. Get the error

**Expected behavior**

The Pipedrive Trigger node should start listening on webhook calls.

**Environment (please complete the following information):**
 - OS: Alpine Linux (Docker Image)
 - n8n Version : 0.84.4
 - Node.js Version : 12.16

**Additional context**

* I think we are missing here an "Authentication method" option (API Token or OAuth), which is available on regular Pipedrive nodes. Missing this option, the `pipedriveApiRequest` cannot determine how to authenticate with the API.
* There is a new request made when triggering the node to check if the webhook exists or not. I guess it wasn't doing it in previous versions, which could explain why it was working before.

**Comment by janober** [comment]
Thanks a lot! We will check it out.

**Comment by RicardoE105** [comment]
@frankie567 Just sent a PR fixing the issue. We will let you know when is released. Thanks for letting us know.

**Comment by frankie567** [comment]
Great! Thank you for the very quick fix 🙏

**Comment by janober** [comment]
Fix got released with n8n@0.85.0
