### ISSUE TITLE
I have this error when create new post to wordpress by node

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#989]
I have this error when create new post to wordpress by node
(My user permission: administrator)

ERROR: Wordpress Error: Sorry, you are not allowed to create posts as this user.

```
Error: Wordpress Error: Sorry, you are not allowed to create posts as this user.
    at Object.wordpressApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Wordpress/GenericFunctions.js:35:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by RicardoE105** [comment]
Hey @cmdntd. Did you install the basic authentication plugin in your WordPress instance? If not please do, you download it [here](https://github.com/WP-API/Basic-Auth) and then import it into WordPress. I believe it should fix the issue. If it does not or you have a question, please come back to me.

**Comment by cmdntd** [comment]
I installed it and config .htaccess like this instruction here:
https://community.n8n.io/t/i-have-error-when-try-to-post-to-wordpress/2455

**Comment by janober** [comment]
You can maybe have a look at those issues. Maybe they help:
https://github.com/WP-API/Basic-Auth/issues/51
https://github.com/WP-API/Basic-Auth/issues/35

**Comment by krynble** [comment]
Hi @cmdntd were you able to fix the issue you were facing?

It does not seem to be a problem with n8n itself but let us know if you still need help.

**Comment by nukeador** [comment]
I was facing similar issues, and it seems only wp users with editor role or up can auth (not sure if it's a wp thing or a n8n thing)
