### ISSUE TITLE
Base URL of OpenAI sub-node does not work

### ISSUE THREAD

**Issue by BKDragon** [n8n-io/n8n#9949]
### Bug Description

When I use an OpenAI API proxy service, it requires a change in Base URL.
OpenAI sub-node in n8n has an option where I fill in the requested Base URL, but it doesn't work.
Supported models cannot be refreshed in the Model option.
When I try to force a model name, the entire LangChain node doesn't work properly

### To Reproduce

1. Create a Basic LLM Chain
2. Adding an OpenAI Model
3. Modify Base URL

### Expected behavior

Get the list of supported models from OpenAI's proxy service and make OpenAI nodes work properly.

### Operating System

Ubuntu 23.04

### n8n Version

1.47.1

### Node.js Version

18.16.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @BKDragon

Which service are you trying? Some don't return the models in the same way which breaks the filters.

**Comment by BKDragon** [comment]
I tried two services.
The first was closeai-asia.com, an OpenAI proxy service popular in the Chinese community. The other is [OneAPI](https://github.com/songquanpeng/one-api/blob/main/README.en.md), which is a self-hosted open-source OpenAI proxy solution, and neither of them refreshes the model list properly.
Meanwhile, I tested both services in other frontend ([ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)) and both worked fine.

**Comment by BKDragon** [comment]
When I searched further, I found this issue from last week:
https://github.com/n8n-io/n8n/issues/9862

I think it's the same problem, but the difference is that it actually doesn't get non-OpenAI models correctly, even OpenAI models that start with gpt, and more importantly, filling in a definite model name with "Expression" doesn't help solve the problem.

**Comment by Joffcom** [comment]
Hey @BKDragon,

So I suspect if it is down to model loading this will be the same as the issue you found and this will be down to how we filter the models.

I am going to close this in favour of the issue so we don't have the duplication.
