### ISSUE TITLE
"Update" operation does not support schema

### ISSUE THREAD

**Issue by trygvis** [n8n-io/n8n#996]
**Describe the bug**
There is no "schema" field for the Update operation. If I try to use "myschema.mytable" in the table field, I this error message:

    error: relation "myschema.mytable" does not exist

I assume that this is because of the quoting/escaping done by the node.

**Environment:**
 - n8n v0.84.4

**Comment by janober** [comment]
Which node are you reporting the issue for?

**Comment by trygvis** [comment]
Sorry, this is for the PostgreSQL node.

**Comment by janober** [comment]
The Postgres-Node has a special "Schema" parameter directly on top of the "Table" one which is meant for that.
![Screenshot from 2020-09-28 23-13-12](https://user-images.githubusercontent.com/6249596/94486840-452fe180-01e0-11eb-9e19-14f00dc64e52.png)

**Comment by trygvis** [comment]
Not my version:

![image](https://user-images.githubusercontent.com/36284/94595290-ea9f8f80-028a-11eb-827c-15e803d64388.png)

**Comment by janober** [comment]
Then I sadly really doubt that you are using n8n@0.84.4

**Comment by janober** [comment]
One more idea. If you do not run n8n via Docker (which is the preferred way) rather having it npm installed then I guess the problem could be that your n8n version is on 0.84.4 but npm messed something up and did not upgrade the other modules. Then it would display you 0.84.4 but you would get old versions of nodes as the `n8n-nodes-base` package would be out-of-date.

**Comment by trygvis** [comment]
I am using it via docker, and the server say I am running v 0.84.4:

![image](https://user-images.githubusercontent.com/36284/94607644-7a016e80-029c-11eb-81a6-5946cd686e95.png)

**Comment by janober** [comment]
Very strange. Will investigate.

**Comment by janober** [comment]
Ok found the issue. Was to 100% my mistake.
I overlooked that you were talking about the "update" operation and so checked the "insert" one. You are right for "update" there is currently no schema-option. Added it now and will be released with the next version. Will update you here once it got released.

**Comment by janober** [comment]
Fix got released with n8n@0.85.0
