### ISSUE TITLE
Git branch containing certain characters not supported

### ISSUE THREAD

**Issue by nicmart-dev** [n8n-io/n8n#9963]
### Bug Description

Using character like forward slash in branch name as separator, that [some recommend](https://codingsight.medium.com/git-branching-naming-convention-best-practices-a71d5603373a), does not show up properly and cause error on save:

<img width="234" alt="image" src="https://github.com/n8n-io/n8n/assets/10499747/b862e16a-7a49-4206-8177-ffdee1d35584">

<img width="830" alt="image" src="https://github.com/n8n-io/n8n/assets/10499747/58aaa6a9-e3d2-4d71-aedb-4320b9908270">

### To Reproduce

1. Open n8n
2. Click Settings / Environments and set up Git workflow per https://docs.n8n.io/source-control-environments/create-environments/
3. Select branch containing `/` character
4. Notice name of branch after `/ ` is truncated
5. Click Save Settings
6. Notice error

### Expected behavior

Branch name should appear with / character and not cause an error on save.

### Operating System

Synology DSM 7

### n8n Version

1.47.3

### Node.js Version

20.14.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @nicmart-dev,

Good find, would you also be able to email in to help@n8n.io so I can link this issue to your enterprise / startup plan license and make sure it is treated with any SLA you may have with us?

**Comment by janober** [comment]
Fix got released with [`n8n@1.52.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.52.0)
