### ISSUE TITLE
Bug? Cannot dynamically set Form Path for Form Trigger

### ISSUE THREAD

**Issue by J-Fo-S** [n8n-io/n8n#9975]
### Bug Description

When dynamically setting the form path for the form trigger, the node shows the correct address. However, when executing the workflow, a webhook 'path is not registered' error appears. In the error, it shows the address incorrectly as the json-formatted expression, and not the result of the expression. See the attached images.

### To Reproduce

1. write a json expression to dynamically set the form path of a form trigger node.
2. return a webhook to the node.

### Expected behavior

the json expression should be evaluated for the webhook registration

### Operating System

Windows 11

### n8n Version

1.37.3

### Node.js Version

20.11.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by J-Fo-S** [comment]
![Screenshot 2024-07-09 124028](https://github.com/n8n-io/n8n/assets/26536159/45de439b-bd0e-4c93-bb0b-23803efe02d7)
![Screenshot 2024-07-09 124146](https://github.com/n8n-io/n8n/assets/26536159/9f1581f6-a04d-463b-8bee-6bfacc4eeed6)

**Comment by Joffcom** [comment]
Hey @J-Fo-S,

Thanks for opening this, I have done some testing and have created `NODE-1488` as the internal ticket for this. While testing I found this to only be an issue if you use the test buttons if the workflow is active the expression is correctly parsed. 

For testing you can copy the test link and paste it into a browser window while the workflow is running in test mode.
