### ISSUE TITLE
Wordpress node has error with "categories" option

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#998]
Categories options can not load every in long list, and when I try to select one, I can't

1. Can't load long list categories
2. Can't select
3. When edit categories, it does not update immediately (you know, user use so many cache system, includes cloudflare)

You should let me insert slug or ID of category, in-stead of loading dynamic data
Anyway, nodes need exactly parameters than dynamic

**Comment by RicardoE105** [comment]
Hey, @cmdntd 

you can set them manually using an expression. Something like the example below:

![image](https://user-images.githubusercontent.com/16496553/94559254-f3627800-022e-11eb-8037-435777b92d5b.png)

![image](https://user-images.githubusercontent.com/16496553/94559326-11c87380-022f-11eb-8d16-13e82561a463.png)

Let me know if that helps.

**Comment by cmdntd** [comment]
Yes, I will try this
Thank you so much

**Comment by RicardoE105** [comment]
@cmdntd were you able to figure this out?

**Comment by cmdntd** [comment]
Sorry, I try to shorten my category first... to process my work faster
Now, I do not have any case to test this

You could check it by testing yourself, please

**Comment by krynble** [comment]
Hey @cmdntd we were unable to test this issue so far, is it still happening? Maybe had something to do with the credentials issue you reported earlier?

Let me know if you are still having this issue so I can look into this.
